### PR TITLE
[Docs] Added documentation for onChangeText prop of TextInput

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Before -

react native a framework for building native apps using react 2015-06-12 10-18-03


After - 

react native a framework for building native apps using react 2015-06-12 10-18-14

**Comment by ide** [comment]
Can you also note that the new text is passed to the handler?

**Comment by prathamesh-sonpatki** [comment]
@ide Updated. Please check.

**Comment by sahrens** [comment]
@facebook-github-bot import

**Pull request closed without merging**
