### PR TITLE
android emulator has been changed last update

### PR DESCRIPTION
**Pull request by ThaJay**
https://github.com/facebook/react-native/issues/6919

### CODE REVIEW

**Comment by ThaJay** [comment]
https://github.com/facebook/react-native/issues/6919

**Comment by dsibiski** [comment]
Thanks! Could you please capitalize "OS X", "Windows" & "Android" respectively?

**Comment by ThaJay** [comment]
missed those. -done.

**Comment by dsibiski** [comment]
Can you specify which version of the Android emulator and below respond to the F2 and Page Up commands? Saying, "In the old version..." isn't so helpful because it's relative to when you are reading this doc.

**Comment by facebook-github-bot-8** [comment]
@sunnylqm would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by facebook-github-bot-6** [comment]
@ThaJay updated the pull request.

**Comment by ThaJay** [comment]
sorry for not updating sooner. Added Android emulator version number.

**Comment by facebook-github-bot-7** [comment]
@ThaJay updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@sunnylqm would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by facebook-github-bot-4** [comment]
@ThaJay updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@sunnylqm would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by sunnylqm** [comment]
@dsibiski

**Comment by dsibiski** [comment]
Thanks @ThaJay, lgtm.

**Comment by dsibiski** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1575533472761234/int_phab) to review.

**Comment by facebook-github-bot-5** [comment]
Something went wrong when importing this pull request. Please cc someone from the team at fb to help with importing this.

**Comment by ThaJay** [comment]
@dsibiski what went wrong here? the tutorial file seems to be gone from the repo but it is still on the docs site.

**Comment by javache** [comment]
This pull request hasn't seen activity in a while. If you still want to merge this, please open a new pull request.

**Pull request closed without merging**
