### PR TITLE
Fix how FlatList counts the number of items it has

### PR DESCRIPTION
**Pull request by meno1**
Without this fix FlatList will not render items < numColumns.

### CODE REVIEW

**Comment by meno1** [comment]
Just realized I have to sign some CLA.  Can someone else handle this?  Or should I open it up as an issue instead?

**Comment by brentvatne** [comment]
@meno1 - is there some reason that you cannot sign the CLA?

**Comment by brentvatne** [comment]
cc @sahrens re: the diff (not CLA stuff)

**Comment by sahrens** [comment]
Good change, thanks!

**Comment by sahrens** [comment]
I made the change for you in another diff, so no need for this.

**Comment by mkonicek** [comment]
Thanks Spencer!

**Pull request closed without merging**
