### PR TITLE
cleanup AndroidX

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

cleanup AndroidX BUCK files

## Changelog

[Android] [Changed] - cleanup AndroidX BUCK files

## Test Plan

CI is green

### CODE REVIEW

**Comment by dulmandakh** [comment]
@mdvacca tests are failing because it's trying to resolve optional resource reference.

**Comment by cpojer** [comment]
@dulmandakh what's the status of this PR?

**Comment by dulmandakh** [comment]
I'll rebase it today. I don't have enough experience with Android tests, especially instrumentation tests, so need help.

**Comment by dulmandakh** [comment]
closing this because https://github.com/facebook/react-native/commit/44fe9904ace426088e20727212cccce8796b8068 did the same

**Pull request closed without merging**
