### PR TITLE
Missing return in React Native Navigator documentation

### PR DESCRIPTION
**Pull request by jvorcak**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @scarlac to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by scarlac** [comment]
I believe this is a duplicate of #9161 has already been fixed in master but not backported to 0.31-stable.

@hramos what is the recommendation action for PRs not targeting master / backports?

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
I just changed the base branch to master. @jvorcak can you take a look and make sure this isn't already fixed in #9161?

**Comment by mkonicek** [comment]
@jvorcak I'll close this for now but if you see it's still needed can you please open a new PR against master? This one has many commits in it.

**Comment by jvorcak** [comment]
@mkonicek sorry for not responding, I was quite busy these days. It looks like the issue is solved anyway as far as I've checked.

**Pull request closed without merging**
