### PR TITLE
Bugfix: App crashes when some input method switching keyboard on Android.

### PR DESCRIPTION
**Pull request by bunnyc1986**
The users told us that our Android app crashes when they switch the keyboard. The crash report we received was following:
```
java.lang.IndexOutOfBoundsException: charAt: -1 < 0
at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:119)
at com.facebook.react.views.textinput.ReactEditTextInputConnectionWrapper.setComposingText(ReactEditTextInputConnectionWrapper.java:104)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:346)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:5958)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```
I was able to reproduce the problem recently. Some input method (eg. Sogou Pinyin) sends an empty batch change command and will result in chatAt(-1) operation.

## Test Plan

Unit test: I need help with unit test script. I got error when I tried to run unit test script:
```
UNKNOWN ERROR: Unknown cell: xplat
java.lang.AssertionError: Unknown cell: xplat
	at com.facebook.buck.rules.AbstractCellPathResolver.lambda$getCellPathOrThrow$0(AbstractCellPathResolver.java:42)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.buck.rules.AbstractCellPathResolver.getCellPathOrThrow(AbstractCellPathResolver.java:39)
	at com.facebook.buck.parser.BuildTargetParser.parse(BuildTargetParser.java:114)
	at com.facebook.buck.rules.coercer.BuildTargetTypeCoercer.coerce(BuildTargetTypeCoercer.java:53)
	at com.facebook.buck.rules.coercer.BuildTargetTypeCoercer.coerce(BuildTargetTypeCoercer.java:29)
	at com.facebook.buck.rules.coercer.CollectionTypeCoercer.fill(CollectionTypeCoercer.java:77)
...
```

I also need help with testing it with my app. How could I build it into my app?

## Related PRs

N/A

## Release Notes

[ANDROID] [BUGFIX] [TextInput] - App crashes when user switch keyboard on some input method (e.g. Sogou Pinyin)

### CODE REVIEW

**Comment by viotti** [comment]
@bunnyc1986 try to run the unit tests script in the *055-stable* branch. On the *master* branch I am also getting this `java.lang.AssertionError: Unknown cell: xplat` error.

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :lock: package.json - <i>Changes were made to package.json. This will require a manual import by a Facebook employee.</i>
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR - <i>This PR is extremely unlikely to get reviewed because it touches 34468 lines.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by bunnyc1986** [comment]
@viotti Thanks. I was able to pass the tests on 0.55-stable branch.
which (developing) branch shall I submit my new PR based on?

**Comment by viotti** [comment]
According to the How to Contribute section of the manual, pull requests should be opened against the master branch.

**Pull request closed without merging**
