### PR TITLE
Update NavigatorIOS component doc

### PR DESCRIPTION
**Pull request by caabernathy**
Reference: #8203

Changes made:

- Added more to the intro section and updated the intro examples to ES6
- Added more details to prop explanations
- Added parameter descriptions for methods

**Test plan (required)**

Ran the website locally and checked: http://localhost:8079/react-native/docs/navigatorios.html

component_navigatorios_2

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @katrinanova to be potential reviewers.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/856501787816919/int_phab) to review.

**Comment by JoelMarcey** [comment]
Ugh -- looks like this needs to be rebased after https://github.com/facebook/react-native/commit/9bd80cbc26437dc931fe6e883ee467755be798db

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/856501787816919/int_phab) to review.

**Pull request closed without merging**
