### PR TITLE
Enable Flipper for custom Xcode configurations

### LINKED ISSUE #34332: Flipper not enabled for custom Xcode configurations
### Description

**The problem:**
Flipper does not find app if the Xcode build configuration is renamed from "Debug" to "Banana" (anything other than "Debug").

**The recommended workaround (does not work):**
Add your custom xcode build configuration name in the Podfile, such that cocoapods generates the correct xcconfig files, and `use_flipper(...)` must be passed a list of configurations that it should work for.

**The problem:**
The workaround does not work _fully_. It correctly adds `-DFB_SONARKIT_ENABLED=1` to the main project but fails to add it to the `React-Core` pod.
This causes Flipper to recoginize the simulator but fail to find the app, causing this message to appear in Flipper:
Screen Shot 2022-08-02 at 12 20 30
("NO APPLICATION SELECTED")

**The actual workaround (works for me):**
- Use `patch-package` to add your debug configurations to React Native's `scripts/react_native_pods.rb` file such that it adds the preprocessor variable/value, or
- Manually add the flag in Xcode to the custom "Banana" config for "Other C Flags":
Screen Shot 2022-08-02 at 12 26 48

**The cause:**
Some important definitions as I understand them - because they can be quite confusion to discuss otherwise:
- Xcode **scheme**: The top bar drop down in Xcode where you select a scheme. A scheme points to a build configuration and defines if a build is debuggable, among other things.
- Xcode **build configuration**: A scheme points to a build configuration, which is defined in part by the `.xcconfig` files
`react_native_post_install(installer)`: A function that calls `flipper_post_install` which installs Flipper in the build configurations. The default configurations are "Release" and "Debug".

While this change introduced a fix for standard installations, it fixes with a hardcoded configuration name, which silently fails/gets ignore despite all flags being set correctly for the project itself (for v0.68.2):
https://github.com/facebook/react-native/pull/33499/files#diff-adcf572f001c2b710d14f409c14763f1a50b08369b3034548f1602685d21f67f
(and [this line in main at the time of writing, from 'main' branch](https://github.com/cipolleschi/react-native/blob/f3db6cc52792e3006a16408df4ae40f3aee19a86/scripts/cocoapods/flipper.rb#L86))

**A proposal for a fix?**
Instead of a hardcoded `"Debug"` configuration, we should base it off of the list of provided configurations and their cocoapod mapping, e.g. the `Podfile` for this demo project is as such, and this should be the source of truth:
```ruby
project 'AwesomeProject',
  "Debug" => :debug,
  "Banana" => :debug,
  "Release" => :release
# ....
target 'AwesomeProject' do
  use_flipper!(configurations: ['Debug', 'Banana'])
  # ...
end
```

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 346.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/sesoliman/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 32.0.0
      System Images: android-28 | ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a project using `npx react-native init AwesomeProject`, i.e. follow the general guide
2. `xed ios/` to open the workspace in Xcode
3. Rename or clone the build configuration from "Debug" to "Banana"
4. Add the recommended changes to `ios/Podfile`
```
project 'AwesomeProject',
  "Debug" => :debug, # in this case I cloned the config instead of renaming it
  "Banana" => :debug,
  "Release" => :release
```
and
```
use_flipper!(configurations: ['Debug', 'Banana'])
```
6. Run `cd ios && pod install`
7. Run the project
8. Open Flipper
9. No plugins will be available, the error "NO APPLICATION SELECTED" will appear

### Snack, code example, screenshot, or link to a repository

Banana config added to new project:
Screen Shot 2022-08-02 at 12 38 05

Confirmation that despite making the necessary `Podfile` changes,
the React-Config pod is still missing the correct build flag:
Screen Shot 2022-08-02 at 12 40 59

### PR DESCRIPTION
**Pull request by scarlac**
Fixed Flipper not recognizing app when using custom Xcode configuration names.

## Summary

This fixes the problem that renaming the "Debug" Xcode configuration causes Flipper to not work. Despite using the recommended `:configurations` parameters and instructing Cocoapods that it was a debug build (see #34332), it still wouldn't recognize the app due to missing C preprocessor flags, specifically it was missing `-DFB_SONARKIT_ENABLED=1`.

## Changelog

[General] [Fixed] - Flipper now supports custom Xcode build configuration names

## Test Plan

I applied the PR change to 0.68.2 (which work similarly but code was refactored since then). I then used `patch-package` to test the change and the fix worked on 2 separate projects.
Patch-package change equivalent:
```diff
diff --git a/node_modules/react-native/scripts/react_native_pods.rb b/node_modules/react-native/scripts/react_native_pods.rb
index f2ceeda..2ea57d6 100644
--- a/node_modules/react-native/scripts/react_native_pods.rb
+++ b/node_modules/react-native/scripts/react_native_pods.rb
@@ -180,7 +180,7 @@ def flipper_post_install(installer)
     # Enable flipper for React-Core Debug configuration
     if target.name == 'React-Core'
       target.build_configurations.each do |config|
-        if config.name == 'Debug'
+        if config.debug?
           config.build_settings['OTHER_CFLAGS'] = "$(inherited) -DFB_SONARKIT_ENABLED=1"
         end
       end
```

**Screen shot of Xcode after the patch has been applied, for RN v0.68.2:**
Screen Shot 2022-08-02 at 14 31 49

### CODE REVIEW

**Comment by cipolleschi** [comment]
Hi @scarlac, thanks for the PR. Could you also update the [ruby tests](https://github.com/facebook/react-native/blob/main/scripts/cocoapods/flipper.rb), please?

**Review by cipolleschi — CHANGES_REQUESTED** [review]
Hi @scarlac, thanks for the PR. Could you also update the [ruby tests](https://github.com/facebook/react-native/blob/main/scripts/cocoapods/flipper.rb), please?

**Comment by scarlac** [comment]
@cipolleschi I tried updating the tests but it started to go beyond what I can reasonably test. The limitation of the mocks is that they don't implement the `config.debug?` method and adding it in requires either simply hard-coding it based on a name, which won't improve tests, or reimplementing the [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) functionality quite extensively:
Xcodeproj's [build_configuration.rb](https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/project/object/build_configuration.rb#L63) implements `?debug`, which calls `resolve_build_setting`, which calls `resolve_variable_substitution`, which calls `expand_build_setting`, and it goes on.
On top of that, I don't know how to modify the cocoapods debug mappings in the current tests.

Do you have any specific test in mind that you want added?

**Comment by cipolleschi** [comment]
@scarlac Thanks for trying. My opinion on tests is that we should test what we own, not other parts. We don't own the implementation of the `debug?` property, therefore I don't think we should worry about how it is implemented.

What I would do is to:
1. Go to the [`InstallerMock.rb`](https://github.com/facebook/react-native/blob/main/scripts/cocoapods/__tests__/test_utils/InstallerMock.rb)
2. Update the [`BuildConfigurationMock`](https://github.com/facebook/react-native/blob/main/scripts/cocoapods/__tests__/test_utils/InstallerMock.rb#L174):
  ```diff
  class BuildConfigurationMock
    attr_reader :name
    attr_reader :build_settings
  +  @is_debug

  - def initialize(name, build_settings = {})
  + def initialize(name, build_settings = {}, is_debug = false)
      @name = name
      @build_settings = build_settings
  +  @is_debug = is_debug
    end

  + def debug?
  +    return @is_debug
  +  end
  end
  ```
3. Go to [`flipper-test.rb`](https://github.com/facebook/react-native/blob/main/scripts/cocoapods/__tests__/flipper-test.rb)
4. Update the [`prepare_mock_installer`](https://github.com/facebook/react-native/blob/main/scripts/cocoapods/__tests__/flipper-test.rb#L131) to accept the `is_debug` parameter and pass it to the build config.
6. Update the [`test_postInstall_updatesThePodCorrectly`](https://github.com/facebook/react-native/blob/main/scripts/cocoapods/__tests__/flipper-test.rb#L73) to pass the proper parameter to the `prepare_mock_installer` function
7. Potentially add another `test_postInstall_whenConfigIsNotDebug_doeNotUpdateThePod` to make sure that when `debug?` returns false, we don't change anything.

What do you think?

PS: Danger fails because the changelog must have the square brackets. So it should be:
`[General] [Fixed] - Flipper now supports custom Xcode build configuration names`

**Comment by scarlac** [comment]
@cipolleschi I added the test. It needs to check for the config name, because if it uses `debug?` in the test then it will always succeed due to the mock both being initialized with the value, and just simply checking that same value again. We need to match on the config name and then then build_settings (which was being done already).
The new dummy config is called `CustomConfig`.
The tests will already make sure that "Release" and "Debug"'s `build_settings` are correct (empty or has FB_SONARKIT_ENABLED, respectively) so I don't think we need another test.
I fixed the change log message as well.

**Review by cipolleschi — APPROVED** [review]
Thanks for the changes! That's exactly what I tried to convey with my suggestion!

**Pull request closed without merging**
