### PR TITLE
fix(android): fix mapbuffer jni headers not found consuming react-native from prefab

### PR DESCRIPTION
**Pull request by hannojg**
## Summary:

I was getting build errors when I tried to include `StateWrapperImpl.h` in my library's code on android. The error was:
CleanShot 2024-12-12 at 15 02 44@2x

```
node_modules/react-native/ReactAndroid/build/prefab-headers/reactnative/react/fabric/StateWrapperImpl.h:11:10: fatal error: 'react/common/mapbuffer/JReadableMapBuffer.h' file not found
#include <react/common/mapbuffer/JReadableMapBuffer.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.
```

The problem is that the map buffer files inside the mapbuffer folder are nested, so the prefab outcome looks like this:

CleanShot 2024-12-12 at 14 53 26@2x

Hence it can't resolve the header path.

This change removes the header prefix part as its not needed, since the nested folder structure in mapbuffer already matches what we need, see:

https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/main/jni/react/mapbuffer

## Changelog:

[ANDROID] [FIXED] - Fixed build issue when including mapbuffer jni headers in library code

## Test Plan:

make sure the header path looks correct in the prefab build dir:

CleanShot 2024-12-12 at 14 41 43@2x

### CODE REVIEW

**Review by cortinico — APPROVED** [review]
Thanks for fixing this

**Comment by hannojg** [comment]
Sure! Do I need to do something about the failing CI? (the failed CI runs are iOS and this is a iOS only change so I am confused to why they failed)

**Comment by cortinico** [comment]
> Sure! Do I need to do something about the failing CI? (the failed CI runs are iOS and this is a iOS only change so I am confused to why they failed)

cc @cipolleschi

**Comment by hannojg** [comment]
Okay, after a merge with master we are good 👍

**Pull request closed without merging**
