### PR TITLE
New way of centering content in ScrollView

### LINKED ISSUE #10376: [iOS] ScrollView centerContent interferes with alwaysBounceVertical and alwaysBounceHorizontal
### Issue Description

When you set alwaysBounceVertical or/and alwaysBounceHorizontal on the ScrollView. You expect just that, that it will always bounce. But it does not do that if the content of the scrollview is equal or less in size to the scrollview and centerContent is enabled.

Why does this happen? 
centerContent is implemented in - (void)setContentOffset:(CGPoint)contentOffset
on the ScrollView. When the user zoomes or pans the scrollview. this method will be called. This methods centers the content by updating the contentOffset property.
The logic in this method will lock the view when the content is smaller or equal to the size of the content hence disabling the bouncing effect.

Another issue with this approach of centering the content in the ScrollView is that it does not account for contentInset and therefor calculate the wrong center point of the content if one uses contentInset. (Notised this when I tried to hack my way around the non-bouncing by creating a negative inset).

There are several of other ways to center content in a UIScrollView:
http://stackoverflow.com/questions/1316451/center-content-of-uiscrollview-when-smaller
And among the ones in this thread we also see the current code that RN uses today.

I would very much like to help with this issue, If the core team think it's an issue, but I don't know the correct approach and what to consider. 
### Steps to Reproduce / Code Snippets

```
<ScrollView
          style={{
          backgroundColor: 'red'
        }}
          centerContent={true}
          bounces={true}
          alwaysBounceVertical={true}
          alwaysBounceHorizontal={true}
          style={{
          width: 200,
          height: 200
        }}>
          <View
            style={{
            backgroundColor: 'blue',
            width: 200,
            height: 200
          }}></View>
        </ScrollView>
```

#### Expected Results

I should bounce
### Additional Information
- React Native version: 0.35
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?):  macOS

### PR DESCRIPTION
**Pull request by olofd**
This aims to fix #10376 

Using the method described in WWDC 2010 ScrollView-session.
Tried to choose the best way to do this recommended from : http://stackoverflow.com/questions/638299/uiscrollview-with-centered-uiimageview-like-photos-app

Tests coming.

### CODE REVIEW

**Comment by satya164** [comment]
cc @javache

**Comment by hramos** [comment]
@olofd did you get around to writing the tests?

**Comment by olofd** [comment]
nope @hramos . Had no know time, and don't really know how/what to test.

**Comment by dlowder-salesforce** [comment]
@olofd maybe a simple unit test that adds views of different sizes to a scrollview, and then checks that view origin is correct?

**Comment by lacker** [comment]
It looks like this pull request has been abandoned so I am going to close it. If you are still interested in working on this then please feel free to reopen it!

**Pull request closed without merging**
