### PR TITLE
[Android] Check if mCurrentActivity is set according to LifecycleState

### PR DESCRIPTION
**Pull request by RoJoHub**
## Summary

Issues: Related to  #13439  
react-native-website:Related to PR [#792](https://github.com/facebook/react-native-website/pull/792) 
solution: https://github.com/facebook/react-native/issues/13439#issuecomment-400256114

When we integration with Existing  Android Apps.and set LifecycleState  is `LifecycleState.RESUMED`.
It's lead to `mCurrentActivity`  is null .

At this time , the behave of set `mCurrentActivity ` which  is unexpectedly.

## Changelog
[Android] [Fixed] - Check if mCurrentActivity is set according to LifecycleState

## Test Plan
Everything should run as usual.And Fix this Bug #13439 .

### CODE REVIEW

**Comment by RoJoHub** [comment]
Also i am confused that `setCurrentActivity` is not  be used.

If `setupReactContextRunnable` runs faster than maybeRecreateReactContextRunnable,the value of activity is null from now on.Because of `setupReactContextRunnable` and  `maybeRecreateReactContextRunnable` are asynchronous.

**Comment by RoJoHub** [comment]
@matthargett

I'm not change iOS.But ci is warming.--->`ci/circleci: test_ios`

**Comment by RoJoHub** [comment]
@matthargett 
Also we should change doc of android.
[integration-with-existing-apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps)

```diff
public class MyReactActivity extends Activity implements DefaultHardwareBackBtnHandler {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
+              .setCurrentActivity(activity)
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "MyReactNativeApp", null);

        setContentView(mReactRootView);
    }

    @Override
    public void invokeDefaultOnBackPressed() {
        super.onBackPressed();
    }
}
```

**Comment by hey99xx** [comment]
I didn't review what's the actual bug, but I just want to point out that there are use cases of creating a ReactInstanceManager outside of an activity context. Requiring activity be set initially would break that use case.

For example in a brownfield app where not all activities are in RN, before the user navigates to a ReactActivity to speed things up, we can create ReactInstanceManager on the background, save it in an instance variable, then once the activity is launched we use that ReactInstanceManager already prepared.

**Comment by hey99xx** [comment]
Similarly I don't understand how HeadlessJsTaskService where you pass null for activity would work after this change. Does it rely on that ReactNativeHost will always be creating a ReactInstanceManager first with an activity and then HeadlessJsTaskService will reuse the same ReactInstanceManager? If so that may not always be true either.

**Comment by RoJoHub** [comment]
@hey99xx 

----

## Please observe its running order

---

```java
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        // 注意这里的MyReactNativeApp必须对应“index.js”中的
        // “AppRegistry.registerComponent()”的第一个参数
        mReactRootView.startReactApplication(mReactInstanceManager, "MyReactNativeApp", null);

        setContentView(mReactRootView);
    }
```


**startReactApplication** ->
createReactContextInBackground ->
recreateReactContextInBackgroundInner ->
recreateReactContextInBackgroundFromBundleLoader ->
recreateReactContextInBackground ->
runCreateReactContextOnNewThread ->
mCreateReactContextThread ->
setupReactContext ->
moveReactContextToCurrentLifecycleState ->
**moveToResumedLifecycleState(true)** ->
**currentContext.onHostResume(mCurrentActivity)**

---

In `moveToResumedLifecycleState(true) ->
currentContext.onHostResume(mCurrentActivity)`, **we will pass `mCurrentActivity` to `currentContext`, but what if `mCurrentActivity` is null at this time**?

We can know that `setupReactContext` is **asynchronous**.
We set the value of `mCurrentActivity` through the `onHostResume` of `ReactInstanceManager`.

----

In the past, `reactInstanceManager.builder()` was not call `setCurrentActivity`.
So in `ReactInstanceManager`, the value of `mCurrentActivity` is always null, and only wait until `mReactInstanceManager.onHostResume(this, this)` is executed to set value of `mCurrentActivity`

---
Set the value of `mCurrentActivity` of `mReactInstanceManager` here.
Before this, the value of `mCurrentActivity` is null.


```java
@Override
protected void onResume() {
    super.onResume();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onHostResume(this, this);
    }
}
```

-----


#Summary

Sometimes the `moveToResumedLifecycleState` in `startReactApplication` is executed first than `mReactInstanceManager.onHostResume(this, this);`.
At this time, the value of `mCurrentActivity` is null.
So it will call **`currentContext.onHostResume(null)`**

```java
private synchronized void moveToResumedLifecycleState(boolean force) {
        ...
        // at this time,the value of mCurrentActivity is null
        currentContext.onHostResume(mCurrentActivity);
        ...
    }
```

---

So the value obtained by other modules executing `getCurrentActivity` is null

```java
public @Nullable Activity getCurrentActivity() {
    if (mCurrentActivity == null) {
      return null;
    }
    return mCurrentActivity.get();
  }
```

**Comment by RoJoHub** [comment]
We are asynchronous to set the value of `mCurrentActivity` in `ReactInstanceManager`!!!!!!

We are asynchronous to set the value of `mCurrentActivity` in `ReactInstanceManager`!!!!!!

We are asynchronous to set the value of `mCurrentActivity` in `ReactInstanceManager`!!!!!!

We are asynchronous to set the value of `mCurrentActivity` in `ReactInstanceManager`!!!!!!

We are asynchronous to set the value of `mCurrentActivity` in `ReactInstanceManager`!!!!!!

**Comment by RoJoHub** [comment]
My English is very poor, please carefully observe the execution order and changes in mCurrentActivity.

**Comment by RoJoHub** [comment]
```
**startReactApplication** ->
createReactContextInBackground ->
recreateReactContextInBackgroundInner ->
recreateReactContextInBackgroundFromBundleLoader ->
recreateReactContextInBackground ->
runCreateReactContextOnNewThread ->
mCreateReactContextThread ->
setupReactContext ->
moveReactContextToCurrentLifecycleState ->
moveToResumedLifecycleState(true) ->
currentContext.onHostResume(mCurrentActivity)
```

and

```java
@Override
protected void onResume() {
    super.onResume();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onHostResume(this, this);
    }
}
```

**Comment by hey99xx** [comment]
I understand `onHostResume` is called with null and looks like a bug, but regardless of that you should attempt to fix a bug in a way considering other use cases:

For your flow:

> moveReactContextToCurrentLifecycleState ->
moveToResumedLifecycleState(true) ->
currentContext.onHostResume(mCurrentActivity)

`moveReactContextToCurrentLifecycleState` will call `moveToResumedLifecycleState` only if it's at `LifecycleState.RESUME` state:
https://github.com/facebook/react-native/blob/be282b5287f7eecf8a3fd14b06ab36454dbba5fe/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L693-L697

But you can call `ReactInstanceManager.builder().setInitialLifecycleState(LifecycleState.BEFORE_CREATE)`; then your initial state isn't `LifecycleState.RESUME` and will not reach moveToResumedLifecycleState until `mReactInstanceManager.onHostResume(this, this);` is called.

So maybe you can improve code by:

```diff
+ if (mInitialLifecycleState == LifecycleState.RESUME) {
    Assertions.assertNotNull(
         mCurrentActivity,
-        "activity property has not been set with this builder");
+        "activity needs to be set if initial lifecycle state is resumed");
+ }
```

**Comment by hey99xx** [comment]
You can see that by default `.setInitialLifecycleState(LifecycleState.BEFORE_CREATE)` is already called. 

So your problem only happens if you called `.setInitialLifecycleState(LifecycleState.RESUMED)` manually.

https://github.com/facebook/react-native/blob/b002df945b267c6e36aa1041397ffd1c73167037/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java#L66-L76

**Comment by RoJoHub** [comment]
> I understand `onHostResume` is called with null and looks like a bug, but regardless of that you should attempt to fix a bug in a way considering other use cases:
> 
> For your flow:
> 
> > moveReactContextToCurrentLifecycleState ->
> > moveToResumedLifecycleState(true) ->
> > currentContext.onHostResume(mCurrentActivity)
> 
> `moveReactContextToCurrentLifecycleState` will call `moveToResumedLifecycleState` only if it's at `LifecycleState.RESUME` state:
> [react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java](https://github.com/facebook/react-native/blob/be282b5287f7eecf8a3fd14b06ab36454dbba5fe/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L693-L697)
> 
> Lines 693 to 697 in [be282b5](/facebook/react-native/commit/be282b5287f7eecf8a3fd14b06ab36454dbba5fe)
> 
>  private synchronized void moveReactContextToCurrentLifecycleState() { 
>    if (mLifecycleState == LifecycleState.RESUMED) { 
>      moveToResumedLifecycleState(true); 
>    } 
>  } 
> But you can call `ReactInstanceManager.builder().setInitialLifecycleState(LifecycleState.BEFORE_CREATE)`. Then your initial state isn't `LifecycleState.RESUMED` and will not reach `moveToResumedLifecycleState` until `mReactInstanceManager.onHostResume(this, this);` is called.
> 
> So maybe you can improve code by:
> 
> ```diff
> + if (mInitialLifecycleState == LifecycleState.RESUMED) {
>     Assertions.assertNotNull(
>          mCurrentActivity,
> -        "activity property has not been set with this builder");
> +        "activity needs to be set if initial lifecycle state is resumed");
> + }
> ```



> You can see that by default `.setInitialLifecycleState(LifecycleState.BEFORE_CREATE)` is already called.
> 
> So your problem only happens if you called `.setInitialLifecycleState(LifecycleState.RESUMED)` manually.
> 
> [react-native/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java](https://github.com/facebook/react-native/blob/b002df945b267c6e36aa1041397ffd1c73167037/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java#L66-L76)
> 
> Lines 66 to 76 in [b002df9](/facebook/react-native/commit/b002df945b267c6e36aa1041397ffd1c73167037)
> 
>  protected ReactInstanceManager createReactInstanceManager() { 
>    ReactMarker.logMarker(ReactMarkerConstants.BUILD_REACT_INSTANCE_MANAGER_START); 
>    ReactInstanceManagerBuilder builder = ReactInstanceManager.builder() 
>      .setApplication(mApplication) 
>      .setJSMainModulePath(getJSMainModuleName()) 
>      .setUseDeveloperSupport(getUseDeveloperSupport()) 
>      .setRedBoxHandler(getRedBoxHandler()) 
>      .setJavaScriptExecutorFactory(getJavaScriptExecutorFactory()) 
>      .setUIImplementationProvider(getUIImplementationProvider()) 
>      .setJSIModulesPackage(getJSIModulePackage()) 
>      .setInitialLifecycleState(LifecycleState.BEFORE_CREATE);

You're right.
But docs is said that [integration-with-existing-apps-Android](http://facebook.github.io/react-native/docs/integration-with-existing-apps) .

```
public class MyReactActivity extends Activity implements DefaultHardwareBackBtnHandler {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "MyReactNativeApp", null);

        setContentView(mReactRootView);
    }

    @Override
    public void invokeDefaultOnBackPressed() {
        super.onBackPressed();
    }
}
```

It's call `setInitialLifecycleState(LifecycleState.RESUMED)`.
So.this bug only happen [Integration with Existing Apps-Android](http://facebook.github.io/react-native/docs/integration-with-existing-apps)

**Comment by RoJoHub** [comment]
> @hey99xx
> 
> # We are asynchronous to set the value of `mCurrentActivity` in `ReactInstanceManager`!!!!!!
> # Execute first
> ```java
> @Override
> protected void onResume() {
>     super.onResume();
> 
>     if (mReactInstanceManager != null) {
>         mReactInstanceManager.onHostResume(this, this);
>     }
> }
> ```
> 
> # Post execution
> ```java
> @Override
> protected void onResume() {
>     super.onResume();
> 
>     if (mReactInstanceManager != null) {
>         mReactInstanceManager.onHostResume(this, this);
>     }
> }
> ```

I have a place before I said something wrong.

`moveToResumedLifecycleState(true)` is  run faster than `mReactInstanceManager.onHostResume(this, this);`

At this time,the state is `LifecycleState.RESUMED`,and also the value of `mCurrentActivity`is **null**.

So it caused this bug.#13439

**Comment by RoJoHub** [comment]
@hey99xx 
I have change my pr.
Please review my code again.

---

Also we should change doc of android.
[integration-with-existing-apps-android](https://facebook.github.io/react-native/docs/integration-with-existing-apps)

```diff
public class MyReactActivity extends Activity implements DefaultHardwareBackBtnHandler {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
+               .setCurrentActivity(this)
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "MyReactNativeApp", null);

        setContentView(mReactRootView);
    }

    @Override
    public void invokeDefaultOnBackPressed() {
        super.onBackPressed();
    }
}
```

**Comment by hey99xx** [comment]
I'll approve the PR but I'm neither working for FB nor a maintainer for react-native so you'll wait for someone else's approval.

> Also we should change doc of android.

Agreed. Do you want to send a pull request to https://github.com/facebook/react-native-website/blob/master/docs/integration-with-existing-apps.md too?

**Comment by RoJoHub** [comment]
> I'll approve the PR but I'm neither working for FB nor a maintainer for react-native so you'll wait for someone else's approval.
> 
> > Also we should change doc of android.
> 
> Agreed. Do you want to send a pull request to https://github.com/facebook/react-native-website/blob/master/docs/integration-with-existing-apps.md too?

哈哈,我刚刚提交了这个 [PR#792](https://github.com/facebook/react-native-website/pull/792#issue-253289969).
请帮我看一下.谢谢!!!

**Comment by RoJoHub** [comment]
@mdvacca @matthamil 
Please review again.

**Comment by RoJoHub** [comment]
@mdvacca
I update Summary and ChangeLog
Please review again.

**Comment by cpojer** [comment]
Yeah it seems like this is definitely a breaking change that causes a ton of failures at FB, so we cannot merge this one.

**Comment by RoJoHub** [comment]
> Yeah it seems like this is definitely a breaking change that causes a ton of failures at FB, so we cannot merge this one.

Sorry.i can't find any error on master.

**Comment by cpojer** [comment]
Here is the trace:
```
java.lang.AssertionError: activity needs to be set if initial lifecycle state is resumed
	at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:250)
	at com.facebook.react.testing.ReactAppTestActivity$3.run(ReactAppTestActivity.java:261)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
```

It seems like the ReactAppTestActivity might need some changes?

**Comment by RoJoHub** [comment]
> Here is the trace:
> 
> ```
> java.lang.AssertionError: activity needs to be set if initial lifecycle state is resumed
> 	at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
> 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:250)
> 	at com.facebook.react.testing.ReactAppTestActivity$3.run(ReactAppTestActivity.java:261)
> 	at android.os.Handler.handleCallback(Handler.java:751)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:154)
> 	at android.app.ActivityThread.main(ActivityThread.java:6077)
> 	at java.lang.reflect.Method.invoke(Native Method)
> ```
> It seems like the ReactAppTestActivity might need some changes?

I'm so sorry.
Please review again.
@hey99xx  @cpojer

**Comment by cpojer** [comment]
It seems like the only thing in our way is one more internal test that is now failing. I'm unfortunately not an Android expert so I'm unsure how to get the current activity so I can set it on the builder. All I seem to have available is an `InstrumentationRegistry` (from `android.support.test.InstrumentationRegistry`) or an `InstrumentationTestCase` (from `android.test.InstrumentationTestCase`). Do you have any idea about how I could patch up my test?

It does seem that part of the test is to wait for a ReactContext to be initialized asynchronously, so I'm unsure whether this can be fixed :O

**Comment by RoJoHub** [comment]
> InstrumentationTestCase

Maybe is that?

```Java
        Activity activity = (Activity)InstrumentationRegistry.getTargetContext();;
        build.setCurrentActivity(activity);
```
Related to [Get context of test project in Android junit test case](https://stackoverflow.com/questions/8605611/get-context-of-test-project-in-android-junit-test-case?answertab=votes#tab-top)

**Comment by RoJoHub** [comment]
I can't find other info for this pr because The current problem is that this test is internal .

Could you please tell what to do next?

**Comment by cpojer** [comment]
@RoJoHub sorry I was away last week so I couldn't get to this. I just tried your proposed change but now it causes an issue when destroying the instance manager: `java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactInstanceManager.destroy()' on a null object reference` :(

**Comment by RoJoHub** [comment]
> @RoJoHub sorry I was away last week so I couldn't get to this. I just tried your proposed change but now it causes an issue when destroying the instance manager: `java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactInstanceManager.destroy()' on a null object reference` :(


Now the error prompts that the `onDestory` method is called on a null object.

The current information can't make me locate the error.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactInstanceManager.destroy()' on a null object reference
```



By the way ,It's hard to locate where the error is.
Beacause I don't know what happened to the internal test.

**Comment by cpojer** [comment]
I'm sorry for making this hard but I'm not an expert on this part of the codebase so it's a bit hard. I did the cast as you suggested but maybe it didn't work properly and it is now setting the wrong thing as the activity, that then later crashes? Do you have any suggestions on how I could figure this out properly?

**Comment by RoJoHub** [comment]
### Case 1: ActivityInstrumentationTestCase2
If We extend `ActivityInstrumentationTestCase2`.The `generics ` is  class of activity.
For example :`extends ActivityInstrumentationTestCase2<ReactAppTestActivity>`

https://github.com/facebook/react-native/blob/b41ce43c07c038aed88f07b0aa5fb5a8f6374b47/ReactAndroid/src/androidTest/java/com/facebook/react/testing/ReactInstrumentationTest.java#L26-L49

If we want get activity,just call `Activity`
```
Activity activity = getActivity();
```

### Case 2: AndroidJUnit4.class

If an annotation  is `AndroidJUnit4.class`.

we should set a activity that we want test.

```
@Rule public ActivityTestRule<Activity> mActivityRule = new ActivityTestRule<>(Activity.class);
```

If we want get activity,just call `mActivityRule.getActivity()`
```
Activity activity = mActivityRule.getActivity();
```

https://github.com/facebook/react-native/blob/be282b5287f7eecf8a3fd14b06ab36454dbba5fe/ReactAndroid/src/androidTest/java/com/facebook/react/tests/core/ReactInstanceManagerTest.java#L25-L37

### Case 3: InstrumentationTestCase & InstrumentationRegistry
`public Activity startActivitySync (Intent intent)`
[startActivitySync(https://developer.android.com/reference/android/app/Instrumentation.html#startActivitySync(android.content.Intent))



```
        Instrumentation instrumentation = InstrumentationRegistry.getInstrumentation();
        Intent intent = new Intent();
        intent.setClass(instrumentation.getTargetContext(), Activity.class);
        Activity activity =InstrumentationRegistry.getInstrumentation().startActivitySync(intent);
```

**Comment by RoJoHub** [comment]
@cpojer

**Comment by cpojer** [comment]
Thanks to @makovkastar who fixed the internal issue we were having I was finally able to land this Pull Request. I want to apologize again for how long it took.

**Pull request closed without merging**
