### PR TITLE
Update UIExplorer <Text /> example to respect ultralight font

### LINKED ISSUE #6735: iOS - System Ultralight Font Weights Don't Work
Hi there,

I'm not really sure where to start with this, but I just checked out the UIExplorer sample trying to get a San Francisco Ultralight font to work

I've provided an image as a sample
pasted_image_at_2016_03_31_17_48

It's the same as the light font. What too heck should I do? I'm going to go tool through UIFont stuff right now to see if I can send a PR through.

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #6735

On font sizes smaller than 20, iOS will swap SystemFont to SF version optimised for smaller sizes which does not have ultralight and thin. That results in ultralight and light example to be rendered with the same weight.

Bumping to `20` makes it render differently as per below screenshot https://cloud.githubusercontent.com/assets/2464966/14622260/0789e500-05c9-11e6-920a-8c948a5b79b4.png

### CODE REVIEW

**Comment by janicduplessis** [comment]
Looks like there's a text screenshot test that fails, I think you'll have to update it.

**Comment by grabbou** [comment]
Let's see if we can get it green with just a link :D

**Comment by grabbou** [comment]
PS. Test failure seems unrelated.

**Comment by grabbou** [comment]
@janicduplessis do you think we can ship that? Looks like a small change, I believe Travis fails as in every other PR due to some FB internal issues.

**Comment by janicduplessis** [comment]
I'm pretty sure the screenshot test failure is related since you changed that page. Can you take a look at that test?

Heres the relevent log
```
Failures:
  0) -[UIExplorerSnapshotTests testTextExample] (UIExplorerIntegrationTests.xctest)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2016-04-19 08:05:50.501 UIExplorer[2708:9560] If you have Kaleidoscope installed you can run this command to see an image diff:
```

**Comment by jenmarie43** [comment]
Unsubscribe

**Comment by grabbou** [comment]
@janicduplessis shall I remove the URL link entirely?

**Comment by janicduplessis** [comment]
Not sure what URL you are talking about. I'm not familiar at all with how this test works, looks like it uses images from [these files](https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/UIExplorerIntegrationTests/ReferenceImages/Examples-UIExplorer-UIExplorerApp.ios). Not sure what's the best way to update the image, maybe ping the author of these tests.

**Comment by grabbou** [comment]
cc: @mkonicek would you mind helping us with these tests? Is that something related to this PR?

**Comment by grabbou** [comment]
@janicduplessis Ah sorry, for some reason from the very beginning I thought you were referring to an imagine being in PR description. All makes sense now.

**Comment by mkonicek** [comment]
iOS tests on Travis are currently broken, let's see if this passes internal tests.

@facebook-github-bot shipit

**Comment by grabbou** [comment]
@mkonicek the issue here might be there's a snapshot of this view and obviously, after these changes it's going to fail. Not sure how to re-generate it.

**Comment by grabbou** [comment]
@facebook-github-bot shipit

@mkonicek updated snapshot, fixed flow - will try once again

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
