### PR TITLE
[iOS][Critical Bug]Fix ScrollView don't response touch event bug

### PR DESCRIPTION
**Pull request by wenpkpk**
Fix RCTScrollView don't response user touch event

This pull request fix bug ScrollView don't response user touch event after user drag the scrollview and click the bottom tabbar button.
#### Reproduce

```
1、launch app and you can see the window that contains a tabbarController;
2、(select first tabbar button, and )press the blue view. -> you can see an alert view with text "1";
3、drop down（up） the scrollview and click the second tabbar button immediately when released. 

4、goto step 2. you can't see an alert view anymore, unless you drop down（up）the scrollview.
```

image link
#### iOS code bellow

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  UITabBarController *tabVC = [[UITabBarController alloc] init];
  UIViewController *a = [[UIViewController alloc] init];
  a.title = @"----------";
  a.view.backgroundColor = [UIColor whiteColor];
  UIViewController *b = [[UIViewController alloc] init];
  b.title = @"++++++++++";
  tabVC.viewControllers = @[a, b];

  NSURL *jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/Examples/2048/Game2048.bundle?platform=ios&dev=true"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Game2048"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.frame = a.view.bounds;
  [a.view addSubview:rootView];

  UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:tabVC];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.rootViewController = nav;
  [self.window makeKeyAndVisible];
  return YES;
}
```
#### JS code

```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  ScrollView
} = React;


class Game2048 extends React.Component {

  constructor(props: {}) {
    super(props);
  }

  render() {
    return (
      <View>
        <ScrollView
          style={{backgroundColor: 'red', height: 1000, }}
          onScroll={this.onScroll}
        >
        <TouchableHighlight onPress={() => {alert(1)}}>
          <View style={{backgroundColor: 'blue', height: 200, width: 200,}}>
          </View>
        </TouchableHighlight>
        </ScrollView>
      </View>
    );
  }
}

AppRegistry.registerComponent('Game2048', () => Game2048);

module.exports = Game2048;
```

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @grabbou and @Kureev to be potential reviewers.

**Comment by wenpkpk** [comment]
@facebook-github-bot

**Comment by facebook-github-bot-8** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @nicklockwood as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by hramos** [comment]
Is this still an issue on RN 0.37? Were you able to reproduce it using RNPlay.org?

**Comment by lacker** [comment]
It seems like this pull request has been abandoned so I am going to close it. If I am mistaken and you  are still working on this then please feel free to reopen it.

**Pull request closed without merging**
