### PR TITLE
Fix mutil currentBundleTask when add productFlavors in build.gradle

### PR DESCRIPTION
**Pull request by wv1124**
fixed issue: 
1. add productFlavors build.gradle
`productFlavors {
        Qianmi {
            manifestPlaceholders = [UMENG_CHANNEL:"WEB"]
            buildConfigField "String", "CHANNEL", "\"WEB\""
        }
    }`

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @AndrewJack and @jaggs6 to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by AndrewJack** [comment]
I'm not sure what this fixes? I have been using `productFlavors` for months without issue? Could you give us more detail on your setup, e.g. windows/mac, react native version.

Maybe a sample project which reproduces the issue?

**Comment by AndrewJack** [comment]
Relates to: #6967

**Comment by wv1124** [comment]
Yes, new version 0.25 has fixed. 
so close

**Pull request closed without merging**
