### PR TITLE
feat: Add iOS Paper implementation of inset logical properties

### PR DESCRIPTION
**Pull request by gabrieldonadel**
## Summary

This PR adds Paper support to `inset` logical properties on iOS as requested on https://github.com/facebook/react-native/issues/34425. This implementation includes the addition of the following style properties 

- `inset`, equivalent to `top`, `bottom`, `right` and `left`.
- `insetBlock`, equivalent to `top` and `bottom`.
- `insetBlockEnd`, equivalent to `bottom`.
- `insetBlockStart`, equivalent to `top`.
- `insetInline`, equivalent to `right` and `left`.
- `insetInlineEnd`, equivalent to `right` or `left`.
- `insetInlineStart`, equivalent to `right` or `left`.
 

Android changes are in a separate PR to facilitate code review https://github.com/facebook/react-native/pull/36242

## Changelog
 
[IOS] [ADDED] - Add Paper implementation of inset logical properties
 

## Test Plan

1. Open the RNTester app and navigate to the `View` page
2. Test the new style properties through the `Insets` section

image

### CODE REVIEW

**Comment by NickGerleman** [comment]
> One thing that still needs to be figured out is how to respect the same precedence as [here](https://github.com/facebook/react-native/blob/9669c10afceef65626c82149210afc07d47df98b/ReactCommon/react/renderer/components/view/YogaLayoutableShadowNode.cpp#L335-L375) when using Paper (cc @NickGerleman)

Yeah, I think that is the main extra thing we need to merge this. Just ensuring that `insetBlockStart` and `insetBlockEnd` do not overwrite `position: top` and `position: bottom`.

We are allowed to have a sequence that looks like:
1. Set `positionTop: 5`
2. Set `insetBlockStart: 10`
3. Clear `positionTop`

There, we should evaluate a top position of "5" at steps 2 and 3, then "10" at step 3. So if we clear out one prop, the state for the other one still needs to be around.

The way I solved this in the Fabric case was that we always had the full set of props available to read from (this is already Fabric's prop parsing model), then we generated the flattened YGStyle after parsing everything. The model for how prop parsing works on paper is different, but I imagine we might need the state for both potential props around, to do this sort of thing.

**Comment by gabrieldonadel** [comment]
Thanks for the review @NickGerleman, I managed to fix the precedence problem by adding a `_positionMetaProps` param to the ShadowView, using a similar approach to what we already have for padding, margin, and borders. Please let me know if this approach looks good to you, if so I'll try to do something similar for android.

**Review by NickGerleman — APPROVED** [review]
Ah, that looks correct. Were you able to validate it against the scenario?

**Comment by gabrieldonadel** [comment]
> Ah, that looks correct. Were you able to validate it against the scenario?

Yeah, from my testing everything is working as expected

**Comment by NickGerleman** [comment]
Hey @gabrieldonadel, we had to revert this change since it caused a few screenshot test failures that seem legitimate. I think this example is setting position via `start. FYI @necolas as well.

image

**Comment by gabrieldonadel** [comment]
Hey @NickGerleman, do you mind sharing some more details about this screenshot test? Which combination of props were you using? Setting positions using `start` and `end` seems to be working fine on my end
image

**Comment by NickGerleman** [comment]
> Hey @NickGerleman, do you mind sharing some more details about this screenshot test? Which combination of props were you using? Setting positions using `start` and `end` seems to be working fine on my end image

It looks like `start: 'n%'`, repeatedly updated, with `width`, `height`, `marginStart`, and `position: 'absolute'` all set, but static.

**Comment by gabrieldonadel** [comment]
> It looks like `start: 'n%'`, repeatedly updated, with `width`, `height`, `marginStart`, and `position: 'absolute'` all set, but static.

Hmm, not sure why that would happen, maybe we're not computing the position on the first pass somehow?

**Comment by lunaleaps** [comment]
Let me see if I can get a small repro of the issue out so we can debug and also see if the Android version suffers the same issue

**Comment by lunaleaps** [comment]
@gabrieldonadel I can reproduce on Paper with this:
```
<View
    style={{
       backgroundColor: 'blue',
       height: 20,
       position: 'absolute',
       width: 20,
       start: '10%'
    }}
/>
```
[Screenshot for Fabric](https://user-images.githubusercontent.com/1309636/222932745-1313399f-8c8b-40c9-a9d2-97b29489f312.png) | [Screenshot for Paper](https://user-images.githubusercontent.com/1309636/222932732-c97facec-9fb9-4954-9af9-d1c837fbd650.png)

**Comment by gabrieldonadel** [comment]
Sorry for the delay on this, I'll take a look tomorrow!

**Comment by lunaleaps** [comment]
Hey @gabrieldonadel do you have a status update on this?

**Comment by gabrieldonadel** [comment]
> Hey @gabrieldonadel do you have a status update on this?

Hi @lunaleaps unfortunately I was still not able to reproduce this issue, are you testing it through RNTester?

image

**Comment by lunaleaps** [comment]
Yes, essentially the same as RNTester, it's an empty surface. You're not able to reproduce on the legacy renderer?

**Comment by gabrieldonadel** [comment]
> Yes, essentially the same as RNTester, it's an empty surface. You're not able to reproduce on the legacy renderer?

Yes, I'm trying to reproduce this inside the View Example of RNTester running Paper

https://user-images.githubusercontent.com/11707729/226581676-4f759a9b-1290-4615-9c41-113bf28b80a7.mov

**Comment by gabrieldonadel** [comment]
Any thoughts on how can I reproduce this @lunaleaps using RNTester?

**Comment by lunaleaps** [comment]
Hey @gabrieldonadel sorry for the delay, I just tested it on the 0.72 release, picking this commit and I was able to reproduce in RNTester

Simulator Screen Shot - iPhone 14 Pro - 2023-04-24 at 16 23 28

**Pull request closed without merging**
