### PR TITLE
Update RCTDevMenu.mm

### LINKED ISSUE #35899: Typo when failing to open Flipper
### Description

There is a typo with the word `running` in 2 places when failing to open Flipper.

https://github.com/facebook/react-native/blob/c6daadcab4387de85fb0070502a6e898d7f473a9/React/CoreModules/RCTDevMenu.mm#L274
https://github.com/facebook/react-native/blob/c6daadcab4387de85fb0070502a6e898d7f473a9/React/CoreModules/RCTDevMenu.mm#L285

### Version

0.70.4

### Output of `npx react-native info`

System:
    OS: macOS 12.6.2
    CPU: (8) arm64 Apple M1
    Memory: 1.52 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.1/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a React Native app
Build in Xcode and open on physical device
Either don't have idb installed or point to the wrong path in Flipper settings:
image

Shake device and press `Open Debugger`
See warning with misspelled 'running' as 'runnning'

### Snack, code example, screenshot, or link to a repository

image

### PR DESCRIPTION
**Pull request by Sheikh-JamirAlam**
## Summary
Fixed typo with the word "running" in 2 places when failing to open Flipper.
Fixes #35899 .

## Changelog

[Internal] - fix typo with the word "running" when failing to open Flipper

## Test Plan

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
> In order to merge **any pull request** (code, docs, etc.), we **require** contributors to sign our **Contributor License Agreement**, and we don't seem to have one on file for you.

@Sheikh-JamirAlam could you sign our CLA?

**Comment by Sheikh-JamirAlam** [comment]
@cortinico I signed the CLA once I saw the CLA check failed.

**Comment by cortinico** [comment]
Can you also provide a changelog entry as suggested by Danger?

**Comment by Sheikh-JamirAlam** [comment]
@cortinico Is my pr gonna get merged?

**Comment by Sheikh-JamirAlam** [comment]
@cortinico Is my pr gonna get merged?

**Pull request closed without merging**
