### PR TITLE
Set viewState to LOADING

### PR DESCRIPTION
**Pull request by sorenbs**
viewState should be set to LOADING so the WebView renders the loading view

### CODE REVIEW

**Comment by stereodenis** [comment]
@sorenbs rebase?

**Comment by sorenbs** [comment]
@stereodenis This issue is very old, so I would have to check if it still applies. Can you confirm this is still an issue in a recent build?

**Comment by facebook-github-bot-4** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
Hey @sorenbs! Thanks for making the pull request! Since it's not clear whether this still applies, I'll close this for now to make sure every PRs is either being worked on or closed, so that we don't have PRs that stay open with no clear idea what to do with them. If you want to get your proposed changes merged, please rebase your branch with master and send a new pull request. :)

**Pull request closed without merging**
