### PR TITLE
Android: upgrading to OkHttp from v3 to v4

### PR DESCRIPTION
**Pull request by arazabishov**
Extends https://github.com/facebook/react-native/pull/30694 to fix tests.

## Summary

OkHttp v4 was released almost a year ago. Even though v3 is still receiving security and bug fixes, most of the new improvements and features are landing in v4. This PR bumps OkHttp from v3 to v4 and addresses backward-incompatible changes. 

Side effects of this upgrade:
 - OkHttp v4 depends on Kotlin's standard library, so react-native will have a transitive dependency on it. 
 - The dex method count of test apk has exceeded the maximum, so multidexing had to be enabled for android tests.

## Changelog

[Android] [Changed] - Bumping OkHttp from v3 to v4. 

## Test Plan

Automated (relying on the test suite) and manual testing.

### CODE REVIEW

**Review by dulmandakh — APPROVED** [review]
LGTM @fkgozali @mdvacca @hramos

**Comment by dulmandakh** [comment]
closing in favor of https://github.com/facebook/react-native/pull/31084

**Comment by dulmandakh** [comment]
I'm happy that this PR would open door to more Kotlin code in RN.

**Comment by nelsonprsousa** [comment]
@dulmandakh any idea if this will end up in the next RN release?

We are seeing a bunch of stability warning reports on Google Play console. Most of them okhttp3 related. Not sure if this affects ASO in any way, tho.

**Pull request closed without merging**
