### PR TITLE
refactor!: drop deprecated `StatusBarIOS`

### PR DESCRIPTION
**Pull request by ecreeth**
## Summary

This component has been merged with `StatusBar` and deprecated since [Jun 24, 2019](https://github.com/facebook/react-native/commit/a8337785539d572009d2cc4263aef7755ae03097)

## Changelog

[JavaScript] [Removed] - refactor!: drop deprecated `StatusBarIOS`

## Test Plan

Warning when user imports `StatusBarIOS`

### CODE REVIEW

**Review by lunaleaps — CHANGES_REQUESTED** [review]
Can we update merge conflicts?

**Comment by ecreeth** [comment]
@lunaleaps is done!

**Comment by lunaleaps** [comment]
@ecreeth Did you want to also remove the docs for StatusBarIOS on [react-native-website](https://github.com/facebook/react-native-website)

**Comment by ecreeth** [comment]
👍 Of course! I'll do it tomorrow early.

**Pull request closed without merging**
