### PR TITLE
Update Getting Started instructions for Android

### PR DESCRIPTION
**Pull request by hramos**
Addresses a ton of feedback from #10372. React Native does require Marshmallow to be installed.

## Android on Windows
screencapture-localhost-8079-react-native-docs-getting-started-html-1478125642639

## Android on Linux
screencapture-localhost-8079-react-native-docs-getting-started-html-1478125630469

## Android on macOS
screencapture-localhost-8079-react-native-docs-getting-started-html-1478125615552

## iOS on Windows
screencapture-localhost-8079-react-native-docs-getting-started-html-1478125604686

## iOS on Linux
screencapture-localhost-8079-react-native-docs-getting-started-html-1478125594366

## iOS on macOS
screencapture-localhost-8079-react-native-docs-getting-started-html-1478125584016

### CODE REVIEW

**Comment by hramos** [comment]
There's also a lot of discussion going on at [#10479](https://github.com/facebook/react-native/pull/10479). cc @satya164 - you mentioned there that API Level 22 is the minimum supported, but the tooling seems to require API Level 23 to be installed.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@hramos That's weird indeed.

**Comment by saevarb** [comment]
Hi. I'm not sure if I'm missing something, but as far as I can see, this pull request has been accepted and merged, but it is not reflected in [the guide](https://facebook.github.io/react-native/docs/getting-started.html) yet?

**Comment by hramos** [comment]
These changes landed after the current release was cut. If you click the number next to "React Native" at the top of the site, then choose Docs from master, you will be able to see the changes.

**Comment by saevarb** [comment]
Ah, okay. I think that's kind of a strange decision, given that currently, new users will land on blatantly broken documentation. But it's good to know that it's up. Thanks!

**Comment by lacker** [comment]
I totally agree that experience could be better - if you would like to help out and improve it to not do this weird dance with master-docs we do take pull requests ;-)

**Comment by JoelMarcey** [comment]
There is the option to cherry-pick commits to `master` into the most current release branch. We have done that before too for particularly showstopping documentation issues.

**Comment by saevarb** [comment]
I did make a pull requests a while ago(which unfortunately turned out be wrong -- `platform_tools` in `PATH` instead of `platform-tools` but oh well), in an attempt to help fix the documentation. I also opened an issue in order to find out how to find out what to do wrt. the 6.0 vs 7.x API issue in the documentation. That is, whether it was a bug that react-native chose 6.0, meaning that it should be fixed and the documentation should remain the same, or whether the documentation should be updated to tell people to install 6.0. (The point being: I would definitely like to contribute. react-native is awesome)

I think cherry-picking should be considered. FWIW, here is an experience I just had tonight:

I am currently a part of a project to develop an app for the computer science faculty at my university. We chose react-native, and I just spent the evening getting ~6 people up and running. I am lucky in that I am able to figure stuff like this out(which is what I did when I set it up on my own before this evening), but for mostly everyone except me of those participating in this project, the broken documentation would have been a complete show stopper, and would perhaps have lead them to pursue other ways of writing the app.

**Pull request closed without merging**
