### PR TITLE
fix(ActionSheetIOS): allows using showActionSheetWithOptions in some app extensions

### PR DESCRIPTION
**Pull request by Etienne-M**
This fixes https://github.com/facebook/react-native/issues/29840. It ended up being much easier than I initially thought. I'm a bit confused as to why the action sheet does not use the RCTAlertController though.

## Summary

Allows using the ActionSheetIOS showActionSheetWithOptions inside an app extension granted the developer set up the override of the view controller.

## Changelog

[iOS] [Fixed] - ActionSheetIOS.showActionSheetWithOptions method works with RCTUtilsUIOverride.setPresentedViewController

## Test Plan

Setup an app extension in react-native. Then,
1. Use the action sheet without setting the override, see the updated message;
2. Use the action sheet with the override, it works! 🎉

### CODE REVIEW

**Comment by Etienne-M** [comment]
I've signed the CLA and tried to re-trigger the pipeline with a commit, but it still says I haven't signed the CLA 😞

**Comment by Etienne-M** [comment]
It looks like the CI is failing for things completely unrelated to my changes 🤔 What's up with that?

**Review by janicduplessis — APPROVED** [review]
Thanks! LGTM

cc @shergin

**Comment by Etienne-M** [comment]
@janicduplessis @shergin @dulmandakh I hope you don't mind me tagging you people directly. The PR is quite small and it's been more than a month now. I'm simply worried it fell in between the cracks. Cheers!

**Comment by janicduplessis** [comment]
@hramos Could you help land this?

**Comment by Etienne-M** [comment]
😢

**Pull request closed without merging**
