### PR TITLE
Indicate width and height params are being passed to onContentSizeChange.

### PR DESCRIPTION
**Pull request by joshuapinter**
I had to do a little trial and error to find this out. Would be helpful to have it in the docs.

I'm not sure if there's a standard wording or format you prefer for indicating handler function params.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
@joshuapinter updated the pull request.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1016393655110376/int_phab) to review.

**Pull request closed without merging**
