### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Priyanshu2001**
Omitted 'own'.. from 2nd para 3rd line.
Added comma in 3rd line after 'developing tools' under the "Upgrading" topic.
bugfixes>> Bug fixes in 7th line under topic "How to contribute".

## Changelog

[CATEGORY] [TYPE] - Message

### CODE REVIEW

**Comment by cpojer** [comment]
@Priyanshu2001 could you sign the CLA so we can merge this change? See code.facebook.com/cla – it only takes a minute :)

**Comment by Priyanshu2001** [comment]
I have signed it

**Comment by Priyanshu2001** [comment]
I have signed it ... But if there is an issue please kindly send me cla url
again..

Thanks!

**Comment by cpojer** [comment]
Hello again @Priyanshu2001! Could you check again whether you filled it out correctly? Please go to https://code.facebook.com/cla and make sure you username is correct when you sign it :)

**Comment by Priyanshu2001** [comment]
I have done it!!

**Pull request closed without merging**
