### PR TITLE
Manually bind PickerAndroid instance methods

### PR DESCRIPTION
**Pull request by dzautner**
In the current version of react-native, the Picker component would some times fail on Android due undefined context (`this === undefined`) in the methods that are defined using the experimental class property syntax. 

As this is experimental syntax which seems to be unreliable in its current form and usage, I suggest to manually bind these methods in the component's constructor.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @spicyj and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-6** [comment]
@dzautner updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9789/files/45a79f4c9b990528674860b388da2a003154df30..797e6ae5b66941649ab4956c19b2811cf81e5dd7)

**Comment by facebook-github-bot-6** [comment]
@dzautner updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9789/files/797e6ae5b66941649ab4956c19b2811cf81e5dd7..218980e04eaa653125f067df1f2efd9d8dba8c96)

**Comment by mkonicek** [comment]
> As this is experimental syntax which seems to be unreliable in its current form and usage, I suggest to manually bind these methods in the component's constructor.

We're using this syntax a lot and it should be reliable thanks to Babel. It looks like the code is equivalent actually. Can you consistently reproduce the bug with `this` being `undefined`? When does it happen? Does the bug go away with your change?

**Comment by dzautner** [comment]
@mkonicek, sorry for not providing enough information.

Yes, we can consistently reproduce the issue with this specific component. We actually use this exact code to resolve the issue temporarily until it is resolved upstream.

**Comment by facebook-github-bot-1** [comment]
@dzautner updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9789/files/218980e04eaa653125f067df1f2efd9d8dba8c96..47a16944a639e629422a25d42de0cf91c0240ecf)

**Comment by spicyj** [comment]
Can you please determine why the current code is breaking?

**Comment by dzautner** [comment]
I'll try to run some tests and narrow it down to the exact cause of the issue.

**Comment by dzautner** [comment]
@spicyj:

I narrowed the issue down to an issue with babel the is already acknowledged. When using babel with passPerPreset the class property syntax will not be bound to the correct context. 

https://github.com/babel/babel/issues/4230
https://github.com/babel/babel/issues/4337

**Comment by spicyj** [comment]
Yeah, that's unfortunate. If you have transform-class-properties in the plugins section then it will work.

**Comment by dzautner** [comment]
👍  thanks!

**Pull request closed without merging**
