### PR TITLE
Expose NavigationExperimental PropTypes

### PR DESCRIPTION
**Pull request by arbesfeld**

### CODE REVIEW

**Comment by mkonicek** [comment]
What is the motivation? What is this needed for? Can you add description to the pull request showing some example where this would be useful?

**Comment by arbesfeld** [comment]
We'd like to use the PropTypes from NavigationExperimental for prop type validation in our components.

**Comment by hedgerwang** [comment]
This looks legit to me. Will merge it once the checks finishes.

**Comment by nevir** [comment]
Also see https://github.com/facebook/react-native/pull/6644

**Comment by mkonicek** [comment]
Ah, I missed #6644, let's merge that one then since it was submitted first.

**Pull request closed without merging**
