### PR TITLE
Launch the packager with `react-native run-android` on Windows

### PR DESCRIPTION
**Pull request by janicduplessis**
Adds support for launching the packager in a new window on Windows.

**Test plan (required)**

Tested that the packager is launched in a completely independent process. This means that exiting the `react-native run-android` command should not close the packager window and it should exit properly when completed even if the packager window is still opened. Pretty much made sure it behaves exactly like on mac.

Also tested that an error in the packager will not close the window immediately to show the error stack trace.

### CODE REVIEW

**Comment by janicduplessis** [comment]
@mkonicek Can anyone review Windows PRs? :o

**Comment by facebook-github-bot-6** [comment]
@janicduplessis updated the pull request.

**Comment by mkonicek** [comment]
Wow this is awesome!! The test plan looks good, can't run the code but trust you :)

@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1714551465482831/int_phab) to review.

**Pull request closed without merging**
