### PR TITLE
More Resources doc, updating Support doc and quickstart too

### PR DESCRIPTION
**Pull request by lacker**
TLDR even more docs changes

So I created a More Resources doc that aggregates the high-quality-but-off-site stuff. Let's try to put more outlinks there. Also I removed the stuff on Support that was not support, and some misc changes to clean stuff up.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @hramos to be potential reviewers.

**Comment by lacker** [comment]
Resolving https://github.com/facebook/react-native/issues/8166

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1621954701452809/int_phab) to review.

**Pull request closed without merging**
