### PR TITLE
[RNPM] Fix params patch

### PR DESCRIPTION
**Pull request by geof90**
`this` is a `ReactNativeHost` post RN 0.29, so the current patch doesn't compile. Simply `getResources()` will work for all versions - Post RN 0.29, it will be the method in the outer `MainApplication`, Pre RN 0.29, it will be the method on the `MainActivity`.

@grabbou @Kureev

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @grabbou and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
@geof90 updated the pull request.

**Comment by grabbou** [comment]
Sounds good, very good hint. LGTM, @Kureev ?

**Comment by geof90** [comment]
@Kureev could you take a look ASAP? Users are hitting this issue.

**Comment by facebook-github-bot-2** [comment]
@geof90 updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9381/files/d904965036da089713b04d3238d03908e0eab7fd..d5e8ddad57c3d15982b56d2bc601db47e5602246)

**Comment by grabbou** [comment]
Going to shipit since I need to send out the stable version today. Looks good to me so I'll go ahead.

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3744162) to review internal test results.

**Comment by Kureev** [comment]
Sorry for delay guys, was ⛵ last week. I know it doesn't make any difference anymore, but LGTM. Thanks for taking care of it, @grabbou ❤️

**Pull request closed without merging**
