### PR TITLE
Update Android dependencies

### PR DESCRIPTION
**Pull request by ronocod**
Fixes https://github.com/facebook/react-native/issues/12929 by using newer versions of Android dependencies:

* Updated Android SDK 23 to 25
* Updated Build Tools from 23.0.1 to 25.0.2
* Updated `compileSdkVersion` and `targetSdkVersion` to 25
* Updated AppCompat from 23.0.1 to 25.2.0

_This is a work in progress, and may require more changes to fix the issue_

This can be tested by:
* Building the Example apps and ensuring they run as expected
* Creating a new app with `react-native init` and ensuring it runs as expected

### CODE REVIEW

**Comment by hramos** [comment]
Circle, which is where our Android tests run, is failing with the following error message:

```
BUILD FAILED: Google APIs not found in /usr/local/android-sdk-linux/add-ons/addon-google_apis-google-25/libs.
```

**Comment by mkonicek** [comment]
This is going to be pretty difficult to do. We build RN internally at fb using exactly those versions we use on GitHub. Updating the versions is usually done by fb employees by updating both the internal and the OSS dependency. Additionally, this work should be done carefully and in steps - one dependency at a time, allow some time to test that everything works.

**Comment by mkonicek** [comment]
I completely agree we should do this if RN was a purely OSS project. Hope you'll understand and continue contributing!

**Comment by mkonicek** [comment]
We might be able to update the `compileSdkVersion` and `targetSdkVersion` though I think.

**Comment by ronocod** [comment]
Updating the `compileSdkVersion` and `targetSdkVersion` should be enough to fix the issue, the rest of the changes were just to keep things up to date. Thanks!

**Comment by mkonicek** [comment]
Thanks! Feel free to send a new PR.

**Comment by ronocod** [comment]
PR just for `compileSdkVersion` and Build Tools here: https://github.com/facebook/react-native/pull/12974

**Pull request closed without merging**
