### PR TITLE
React Native Android Duplicate file error when generating apk

### PR DESCRIPTION
**Pull request by mepritam**
## Summary

I was getting an error "~/React-Native/xxxx/android/app/build/intermediates/res/merged/release/drawable-mdpi-v4/icon_logo: error: Duplicate file...
Native/xxxx/android/app/build/intermediates/res/merged/release/drawable-mdpi-v4/icon_logo_main: error: Duplicate file.
"

## Changelog

1. Changes on React.gradle 
[CATEGORY] [TYPE] - Message

## Test Plan
1. Generate apk from android studio

### CODE REVIEW

**Comment by guhungry** [comment]
Duplicate with #24518

**Comment by hramos** [comment]
I'll review and land #24518 first if possible. If #24518 gets merged, I'll close out this PR.

**Comment by Santu1245** [comment]
When you bundle the file using the following code:

 `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res`

duplicate image files get generated in the drawable folder in the following path:

"android/app/src/main/res/drawable-xxx/"

Delete all those duplicate files and run:

`react-native run-android`

It will generate apk file.

**Comment by cpojer** [comment]
Closing because this is a duplicate.

**Pull request closed without merging**
