### PR TITLE
Fix an ArrayIndexOutOfBoundsException when setMaxLength for EditText

### PR DESCRIPTION
**Pull request by wjyadlx**
When set setMaxLength, in some case, there are some InputFilters, and we need to insert a new LengthFilter.
And you can see the code directly, which is a fault committed unintentionally.

### CODE REVIEW

**Comment by mkonicek** [comment]
I don't understand what's broken unfortunately. Can you please provide a repro on https://rnplay.org/ or screenshots showing what's broken?

How did you test this code change doesn't break anything?

**Comment by wjyadlx** [comment]
@mkonicek  thank you for reply~
Sorry that I should provide more information.

At beginning, I found a crash reported by our self crashreport system, which look like this:
image

Then ,I go to review the source code ReactTextInputManager, as ths link shows: 
[https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java](url)
image
As shown, in line 405, you means to create a new InputFilter array "newFilter" and its length is longer than the original "currentFilters", then you copy the array from "currentFilters" to "newFilter", and then ,**in line 408, I think that you just want to create a new LengthFilter and insert it to the "newFilter", because at last you set the "newFilter" to the "view", as in line 416.** But, the original code is 
` currentFilters[currentFilters.length] = new InputFilter.LengthFilter(maxLength);`
So, I think this line may lead to crash, as I said in the beginning :
java.lang.ArrayIndexOutOfBoundsException:length=1; index=1

That is the reason why I make this modify, sorry for not provide more information again.
Hope for your reply~

**Comment by wjyadlx** [comment]
In addition, please ignore the diffrence, that the crash line shown in my screenshot of the crash is not same as the original source code, because I changed some code in my local repo, but the "setMaxLength" method is just the same.

**Comment by wjyadlx** [comment]
@mkonicek Hi, martin, have you review my reply? 
Hope for your reply~

**Comment by littlesome** [comment]
Got same error, this change works for me.

**Comment by lacker** [comment]
Sorry, I still don't understand what's broken here. I think a unit test would be pretty helpful, otherwise there's no guarantee that someone doesn't just break this again.

**Comment by littlesome** [comment]
hi @lacker ,  this code will always throws an ArrayIndexOutOfBoundsException, it's just a bug here
```java
if (!replaced) {
  newFilters = new InputFilter[currentFilters.length + 1];
  System.arraycopy(currentFilters, 0, newFilters, 0, currentFilters.length);
  currentFilters[currentFilters.length] = new InputFilter.LengthFilter(maxLength);  // should use newFilters 
}
```

**Comment by lacker** [comment]
If the code always throws an error right now then it should be pretty easy to cover this with a unit test! (I'll keep my fingers crossed.)

**Comment by hramos** [comment]
It's been two months, any chance you might add a unit test here?

**Comment by hramos** [comment]
This PR appears to be abandoned. Closing for now.

**Pull request closed without merging**
