### PR TITLE
Showcase: add 'FastPaper' app

### PR DESCRIPTION
**Pull request by liubko**
Spritz reader for Pocket articles
github: https://github.com/liubko/FastPaper
app store: https://itunes.apple.com/us/app/fast-paper/id1001174614?mt=8

### CODE REVIEW

**Comment by brentvatne** [comment]
Nice! Congrats on launching @liubko :smile: :100: :8ball:

**Comment by brentvatne** [comment]
@liubko - warning, this crashes for me on iOS9, as soon as I open it!

**Comment by liubko** [comment]
@brentvatne app store just approved new version with react-native v0.10(there was v0.6). Maybe that will matter. I don't have ios9 yet.

**Comment by brentvatne** [comment]
Seems to work now @liubko! Except I can't try it too much because I don't use Pocket - I use Instapaper :) But it doesn't crash on opening it

**Comment by liubko** [comment]
@brentvante good to know :) thanks

**Comment by liubko** [comment]
@brentvatne good to know :) thanks

**Pull request merged**
