### PR TITLE
update android ndk 

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation (required)

The ndk react-native using is too old, and now Android Studio ships with sdk manager you can install ndk directly (only latest available).

## Test Plan (required)

Run UIExplorer on Android device and check it works.

I have test on genymotion(Android 4.1 & 7.0 & 7.1) and real device (Smartisan T2-android 5.1).
Both works fine.

### CODE REVIEW

**Comment by charpeni** [comment]
I'm afraid this will be useless, as Facebook uses GCC 4.8 internally.

I think @lexs could answer to this, did the migration to clang had happened?

**Comment by gengjiawen** [comment]
But this library works with gcc 4.9 too. This pr doesn't change the build tool to clang, just use the gcc version to the ndk-bundle include (which is gcc 4.9).My main purpose for this pr is to make this library works with latest android ndk, which is included in android studio sdk manager.

**Comment by lexs** [comment]
Clang hasn't happened yet, but we moved to GCC 4.9 some time ago.

**Comment by gengjiawen** [comment]
@lexs will you review this or you inclined update ndk should be done internally by fb ?

**Comment by hramos** [comment]
Let's stick to r10e for now as that is what we're using in our own tests.

Happy to approve any updates to the docs that use Android Studio over the deprecated tool. You can also take a look at `scripts/circle-ci-android-setup,sh` for up to date commands for installing the NDK using the CLI.

**Pull request closed without merging**
