### PR TITLE
WIP: bump okhttp to 4.x

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

Bump OkHTTP to 4.x, which uses Kotlin. This 

https://square.github.io/okhttp/upgrading_to_okhttp_4/

## Changelog

[Android] [Changed] - Bump OkHTTP to 4.x,

### CODE REVIEW

**Comment by arazabishov** [comment]
Thanks for doing his @dulmandakh. I've searched-up the repo for usages of internal OkHttp APIs and found one at RequestBodyUtil:L135. It is a call to Util.closeQuietly, which we can easily replicate. Do you think it is something that we can fix in this PR?

**Comment by dulmandakh** [comment]
Any help is welcome. They say that they made some APIs final thus having problems with mocking.

**Comment by arazabishov** [comment]
Alright, do you want me to push to this branch then? I will take a look at it later today

**Comment by arazabishov** [comment]
Also, how do you usually test changes like this? (dep upgrades for example)

**Comment by dulmandakh** [comment]
First of we need to make tests pass, but with this change test_android is failing. Please feel free work which ever way works for you

**Comment by ecreeth** [comment]
@dulmandakh I think that we can remove [TLSSocketFactory](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/TLSSocketFactory.java)
> This class was needed for TLS 1.2 support on Android 4.x

**Comment by arazabishov** [comment]
Hey folks. I've picked up this branch to fix broken tests and created a follow-up PR here: https://github.com/facebook/react-native/pull/31084. Feel free to review and leave comments if any.

**Comment by dulmandakh** [comment]
closing in favor of https://github.com/facebook/react-native/pull/31084

**Pull request closed without merging**
