### PR TITLE
Replace React.createClass with create-react-class

### LINKED ISSUE #14620: Warning: React.createClass is no longer supported.
When try ```react-native run-ios```, by using ```Debug JS Remotely```,  it showed those warning in Google Chrome developer tools.

```
ExceptionsManager.js:71 Warning: React.createClass is no longer supported.
 Use a plain JavaScript class instead. 
If you're not yet ready to migrate, 
create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
```

> https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass

By searching ```React.createClass``` in ```react-native``` folder, there are many parts used it.

For example, in ```Image.android.js```, line 79:

```
var Image = React.createClass({
  propTypes: {
    ...ViewPropTypes,
    style: StyleSheetPropType(ImageStylePropTypes),
```

* React Native version: 0.45.1
* Platform: iOS
* Development Operating System: macOS 10.12.5
* Build tools: Xcode 8.3.2

### PR DESCRIPTION
**Pull request by mojodna**
This replaces all uses of `React.createClass` with `createReactClass` from the `create-react-class` package, attempting to match use of `var` and `const` according to local style.

Fixes #14620
Refs #14712

### CODE REVIEW

**Comment by mojodna** [comment]
Done in fb5a63e

**Comment by hramos** [comment]
Having trouble landing this internally. Won't this require `create-react-class` to be added to `package.json`?

**Comment by mojodna** [comment]
`create-react-class` is already present: https://github.com/facebook/react-native/blob/master/package.json#L165

I just rebased against master, removing the changes in `ReactNativeFiber-dev.js` and `ReactNativeStack-dev.js` (there are warning messages that reference `React.createClass` but only in strings).

**Comment by hramos** [comment]
Alright, let me dig in a bit more into these failures.

**Comment by grabbou** [comment]
@hramos were you able to indicate why it never landed?

**Comment by grabbou** [comment]
Tip: bump `react-docgen` in `website` to `3.0.0-beta5` so it supports `create-react-class` package. I believe this is source of errors. I had to do the same for 0.46-stable.

**Comment by hramos** [comment]
Apologies for the delay, just came back from a long holiday weekend. Taking a look again. I've been kicking the internal land every couple of days and finally got past some flaky tests. The only thing holding it back right now is a failure during the generation of the website which I haven't been able to reproduce on a local check out of this PR. I'm importing the latest changes (post merge with master) to try again.

**Comment by grabbou** [comment]
Sounds good, thanks @hramos for taking care of that. In the meantime, I have sent 0.47.0-rc.0 build and planning to release rc.1 with that fix.

0.46.0-stable already has it cherry-picked.

**Comment by hramos** [comment]
This is close to landing. While create-react-class was already present in package.json, it wasn't yet in use in React Native proper, so I had to make some changes internally to make sure the new dep was loaded correctly by other projects at Facebook. There's only one more issue to resolve and I'll be able to land this.

**Comment by hramos** [comment]
This should be landing shortly. Props to @skevy for pointing me in the right direction to resolve the failed Jest snapshot tests that were holding this PR back.

When `createReactClass` is used, a `displayName` property must be defined in order for Jest to generate the snapshots correctly. I've opened https://github.com/facebook/react/pull/10122 to fix the React docs.

**Pull request closed without merging**
