### PR TITLE
Add tests for utility functions of library

### PR DESCRIPTION
**Pull request by gandreadis**
## Summary

I was looking at the coverage report of the JavaScript code in the `Libraries` folder, and found some of the modules and functions to be (partially) untested. I believe that adding tests to them would formally capture their behaviour and avoid future regressions. In this PR, I've added some unit tests for 3 utility components.

Perhaps a more general question: Are these kinds of PRs appreciated? I'd be interested in submitting more of them in the future.

## Changelog

Not applicable, since it only adds tests.

## Test Plan

This is a testing PR, so I do not believe that is necessary :)

### CODE REVIEW

**Comment by ericlewis** [comment]
@gandreadis these types of PRs are *loved*!

**Comment by ericlewis** [comment]
this LGTM!

**Comment by gandreadis** [comment]
Thanks! I have no idea why that one CircleCI build is failing, possibly a flaky test? If so, could someone with the right permissions rerun that check? It does not seem to be related to my changes, in any case.

**Comment by cpojer** [comment]
@gandreadis These types of PRs are extremely appreciated, thank you!! Please keep sending them :)

**Pull request closed without merging**
