### PR TITLE
--reset-cache no longer accept a boolean parameter.

### PR DESCRIPTION
**Pull request by danielbraun**
The gradle :app:bundleReleaseJsAndAssets task is currently broken on master.
Gradle attaches a boolean parameter to --reset-cache, while it no longer accepts it.

Related:
* https://github.com/facebook/react-native/blob/master/local-cli/bundle/bundleCommandLineArgs.js#L52
* #9134 
* https://github.com/facebook/react-native/blob/master/local-cli/bundle/bundleCommandLineArgs.js#L52

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @philikon and @AndrewJack to be potential reviewers.

**Comment by satya164** [comment]
cc @Kureev

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing.

**Pull request closed without merging**
