### PR TITLE
Fix `withCredentials` flag for fetch requests

### PR DESCRIPTION
**Pull request by JonnyBurger**
This PR changes `RCTNetworking.mm` so that the cookies are managed using `HTTPShouldHandleCookies ` if the `withCredentials` flag is set to true.

This was the behavior in react-native@0.45, but was broken in react-native@0.46 where the cookies would be overwritten no matter what the `withCredentials` flag is set to.

This PR restores the behavior of the `withCredentials` flag from react-native@0.45, but still uses the new cookie management from react-native@0.46 if that flag is not set. 

I have documented the issue and explained why this code change is necessary here: #14869

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Can this be considered for 0.47? @grabbou

This fixes a bug introduced in 0.46.

**Comment by chirag04** [comment]
cc @rigdern

**Comment by jamesreggio** [comment]
Given the relative lack of interest, I'm going to propose a PR to revert #10575. Maybe that will spark up the conversation we need to have about these breakages.

**Comment by JonnyBurger** [comment]
I agree with @jamesreggio actually, my PR is not the right way to do it.
I think either  #10575 should either be reverted or fixed so that cookies are only sent when `withCredentials` is true. Currently the cookies are always being included, but not using `request.HTTPShouldHandleCookies`.

**Comment by jamesreggio** [comment]
@JonnyBurger, I opened a PR to revert the original breaking change in https://github.com/facebook/react-native/pull/16127.

If you agree, do you mind chiming in?

**Pull request closed without merging**
