### PR TITLE
Fix packager issue that happens as a result of incorrect node-haste callsites.

### PR DESCRIPTION
**Pull request by skevy**
Resolves issue @mkonicek mentioned here: https://github.com/facebook/react-native/issues/6036#issuecomment-186388671

### CODE REVIEW

**Comment by skevy** [comment]
cc @cpojer

**Comment by janicduplessis** [comment]
We should also lock node-haste to revisions as there are breaking changes between minor versions at the moment (react-natives specifies v2.0.0 but there are breaking changes in 2.2.0) or respect semver in node-haste. This will be problematic especially when there will be release versions that use node-haste from npm.

**Comment by bestander** [comment]
@janicduplessis haste is fixed to ~2.0.0 in 89ea98554046356f934d7607270a22d0924b49c9.

**Comment by davidaurelio** [comment]
I guess this is covered in b41ad9f5dc556f119f5512ec2e0b048aa16db642

**Pull request closed without merging**
