### PR TITLE
Add Sin and Cos to Animated 

### PR DESCRIPTION
**Pull request by dested**
## Motivation

If you want to use the native driver to do things like move things in a circle, Animated.sin and Animated.cos are crucial. The implementation ended up being trivial, I mostly duplicated the work from things like Animated.multiply, but for sin and cos. I haven't yet updated the docs yet, but if the pull request is on track to get added, I will make the needed changes there.

A possible use could look something like:

```javascript
this.animated = new Animated.Value(0);
Animated.timing(this.animated, {
  toValue: 2 * Math.PI,
  duration: 5000,
  useNativeDriver: true
}).start()
...
<Animated.View style={{
  transform: [
    { translateX: Animated.multiply(Animated.cos(this.animated), radius) },
    { translateY: Animated.multiply(Animated.sin(this.animated), radius) },
    { rotate: this.animated }
  ], 
  width: 100, height: 100, backgroundColor: 'red'
  }} 
/>  
```

With the rendering being: 

animation

This resolves issue #18263 

## Test Plan

I basically mimicked the effort for things like Animated.multiply, which I couldn't find very many tests for. I'm not certain the best place to add tests for this with no prior art, but the code itself is 95% boilerplate from AnimatedMultiply.

## Release Notes
[GENERAL] [ENHANCEMENT] [Animated] - Added Sin and Cos to Animated

### CODE REVIEW

**Comment by dested** [comment]
There seems to be some issues on iOS, I will fix them in the morning.

**Comment by dested** [comment]
I have fixed the outstanding issues for iOS, but the test_ios CI build has still failed. It seems to be related to metro, but that may be a red herring and it is still my fault. Any insight would be really appreciated. 

This was a lot of fun to build and I think it would be a useful feature. If you agree then I will go ahead and plumb the tests and documentation and update the pull request accordingly.

Thanks!

**Comment by dested** [comment]
closing to reopen with a clean branch

**Comment by maxkomarychev** [comment]
hey @dested have you managed to get this merged?

**Comment by dested** [comment]
Sorry, no, life got in the way. If you think its worth adding to the library I can spend time this week fixing up the repo and submitting the pull.

**Comment by maxkomarychev** [comment]
@dested thanks for your effort, although these functions are definitely missing I found couple alternatives which suit me for now:
- https://github.com/rastapasta/react-native-animated-math (although not tried)
- https://stackoverflow.com/a/45209889 (this one works well enough for me)

**Pull request closed without merging**
