### PR TITLE
Expose pressRetentionOffset for Text

### PR DESCRIPTION
**Pull request by evollu**
expose this property to make Text having same property like TouchableHighlight

### CODE REVIEW

**Comment by lacker** [comment]
`pressRetentionOffset` is an odd name for this, what does "retention" have to do with it? How would you document what this does, exactly? Also, I think this is likely to break unless there is some sort of test, so I think it would help to add a test for this.

**Comment by evollu** [comment]
@lacker The prop type does add some explanation. Is there any test example in current repo? like for TouchableWithoutFeedback?

**Comment by lacker** [comment]
What is "retention" in the name for?

**Comment by evollu** [comment]
retention here is allow press detection area to be larger than Touchable view rect so that if long press will be triggered even if user moves figure slightly outside of the touchable area.
It is the same name and behavior as TouchableWithoutFeedback, I just copied over

**Comment by ide** [comment]
This is simply proxying an existing touchable property, looks fine to me.

**Comment by janicduplessis** [comment]
I agree with @ide I don't think we need to add any test / changes since it simply proxies the touchable prop.

**Comment by ide** [comment]
Let's ship this then. The maintenance cost and complexity are low I think.

@facebook-github-bot shipit

**Pull request closed without merging**
