### PR TITLE
Fix maxLength issue of TextInput on MarkedRange and AutoCompletion

### PR DESCRIPTION
**Pull request by hubertwang**
Current implementation of maxLength has two issues of AutoCompletion and MarkedRange.
**AutoCompletion**
The maxLength check is not working on AutoCompletion. The reason is that textField:shouldChangeCharactersInRange:replacementString: will not be called when we type by the word suggested by system. So we need to check in UIControlEventEditingChanged.
auto-completion-breaks-max-length

**MarkedRange**
In some language, such as Chinese and Japanese, a word may composed by multiple key strokes. If the maxLength check does not exclude strings that are marked, then we will not be able to complete the input.

marked-text-should-not-be-limited-by-max-length

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

fix-auto-completion

fix-marked-range

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

MaxLength doesn't work correctly with MarkedRange and AutoCompletion.
In some cases,
textField:shouldChangeCharactersInRange:replacementString: will not be
called when using AutoCompletion. And, we should allow user to type
when the confirmed string length is not exceed the limitation of
maxLength. So we need to check the length of text when we receive
UIControlEventEditingChanged event.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @cava23 and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
@hubertwang updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@hubertwang updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@hubertwang updated the pull request.

**Comment by lacker** [comment]
@janicduplessis - would you mind taking a look at this?

**Comment by lacker** [comment]
Could you add a test for this? Also, be sure to sign the CLA.

**Comment by hubertwang** [comment]
Hi @lacker,
Could you tell me where I can find an example for test? I have no idea what I should add to this PR. Thank you.

**Comment by lacker** [comment]
I would try putting it with the other iOS-centric tests in UIExplorer.

**Comment by hramos** [comment]
@hubertwang do you still want to ship this? The CLA needs to be signed, and tests are needed.

**Comment by hubertwang** [comment]
Hi @hramos, 
Yes, I have signed the CLA. If I didn't misunderstand what lacker said, he will add test for this? Umm..actually, I just don't know what should I do for test, could you please give me an example? Thank you.

**Comment by hramos** [comment]
Ah, the bot hasn't tagged this yet, so it looks like the CLA wasn't signed.

You can take a look at the examples in the UIExplorer to see what a test might look like.

**Comment by lacker** [comment]
Does that make sense @hubertwang - have you figured out how to add a test?

**Comment by hubertwang** [comment]
Hi @lacker,
Is it TextInputExample.ios.js, where I was supposed to add a test?
I've check the 'MaxLength' section and found it hard to add a test, because I need to use keyboard to reproduce the scenario.

**Comment by lacker** [comment]
Maybe the keyboard can get mocked out somehow?

**Comment by hramos** [comment]
Any interest in shipping this? There's some outstanding feedback.

Can you also let me know when or how did you sign the CLA? Unfortunately I can't import this until the bot tags this PR properly with the CLA Signed label.

**Comment by hramos** [comment]
Closing as we cannot look at this until the CLA is signed.

**Pull request closed without merging**
