### PR TITLE
Document BaseActivityEventListener & new onActivityResult API

### PR DESCRIPTION
**Pull request by foghina**

### CODE REVIEW

**Comment by foghina** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @alvinthen and @Nepherhotep to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
I will not rubber stamp and land your change for you @foghina!  I can import it for you and you can get your change reviewed by someone though :)

**Comment by foghina** [comment]
@facebook-github-bot you're the worst. @bestander can you rubber stamp and land my change pls?

**Comment by bestander** [comment]
@facebook-github-bot shipt

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3886231) to review internal test results.

**Pull request closed without merging**
