### PR TITLE
[Docs] Split iOS and Android docs into different categories

### PR DESCRIPTION
**Pull request by nkt**
This screenshot explains everything:
screen shot 2015-09-18 at 20 53 05
If this would be accepted, I'll do the same with components.

### CODE REVIEW

**Comment by ide** [comment]
This looks quite nice and is easier to read. Generally I'm in favor of grouping articles/code/whatever by feature instead of platform but here I think what you've done makes sense.

**Comment by nkt** [comment]
@ide so you don't think that this would be helpfull for component's docs?

**Comment by ide** [comment]
I think for components it'd be nice too. Send a PR and I'll take a look.

**Comment by ide** [comment]
Just my general sentiment is that we don't want the docs to be split at the topmost level between iOS and Android... the way to think of it is that you are firstly a mobile React developer and the platform is an implementation detail. But in cases where there are clear platform differences (ex: StatusBarIOS) creating small iOS and Android sections does look easier to read.

**Comment by jaygarcia** [comment]
Fantastic!!!

**Pull request merged**
