### PR TITLE
Add Myntra to showcase

### PR DESCRIPTION
**Pull request by paramaggarwal**
We are using React Native on our app's homepage for the Daily Fashion Feed - a curated list of content to discover inspiring content. We recently went live to 100% and happy to share this news with the community.

Also, we are shipping JS updates on the fly to our customers and loving it!

(Myntra is India's largest online fashion retailer, a subsidiary of Flipkart Pvt. Ltd. out of Bangalore, India. We recently went app-only by shutting down our website.)

### CODE REVIEW

**Comment by paramaggarwal** [comment]
Thanks @ide.

**Comment by chirag04** [comment]
too late @facebook-github-bot. @vjeux  maybe add a check to see if the PR/issue is still open.

**Comment by paramaggarwal** [comment]
Haha, @ide is faster than bots. :)

**Comment by chirag04** [comment]
haha. @ide is megabot!

**Comment by vjeux** [comment]
wtf, the bot is running every minute, it shouldn't comment 15 minutes later oO

**Pull request merged**
