### PR TITLE
[website] fix `for` being used instead of `htmlFor`

### PR DESCRIPTION
**Pull request by mdamien**
When building the website, I saw this warning: 

`Warning: Unknown DOM property for. Did you mean htmlFor?`

So, here's the fix.

## Test plan:
   
 1. do `npm start`
 2. load the homepage (with the newsletter input)
 3. see warning: `Warning: Unknown DOM property for. Did you mean htmlFor?`

### CODE REVIEW

**Comment by hramos** [comment]
Looks simple enough. I don't see a test plan in your PR however, can you update the description?

**Comment by mdamien** [comment]
@hramos updated the description, can you reproduce ?

**Comment by hramos** [comment]
Is the warning gone after the fix is applied?

**Comment by mdamien** [comment]
@hramos I can confirm it's gone, yes

image

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
There's a merge conflict. Can you rebase please?

**Comment by mdamien** [comment]
@mkonicek I have rebased, it should be fine now

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Thanks!

**Pull request closed without merging**
