### PR TITLE
Set WebChromeClient to the android's WebView during instantiation

### PR DESCRIPTION
**Pull request by lucasfeliciano**
Motivation: #6405

Follow up of: #6603

@satya164

### CODE REVIEW

**Comment by charpeni** [comment]
CircleCI build failed, cannot find symbol Class WebChromeClient.

You must add `import android.webkit.WebChromeClient;`

I just tested your branch with the fix mention up there and everything works fine ! 

Google maps can now be used without getting a blank page, youtube videos works as well, websites with some unhandled height css properties doesn't display blank page and IMO loading seems faster.

About the prop, at first I was fearing an unexpected behaviors that can appear with WebChromeClient that cause breaking change, but it seems I was wrong.

**Comment by lucasfeliciano** [comment]
Ops, true.

I added to the commit without saving in the text editor.
my bad.
Fixing it now

**Comment by lucasfeliciano** [comment]
It is done :)

**Comment by charpeni** [comment]
Hey @lucasfeliciano! Thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by lucasfeliciano** [comment]
Should I squash the merge as well?

**Comment by charpeni** [comment]
@lucasfeliciano Yes and don't worry about Travis CI, it's really slow these days.

**Comment by lucasfeliciano** [comment]
@charpeni Squashed

**Comment by stereodenis** [comment]
@charpeni how to test this?
I build from source with this changes and it's not working...

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by charpeni** [comment]
@stereodenis Follow these steps : [Building React Native from source](http://facebook.github.io/react-native/releases/next/docs/android-building-from-source.html#content)

**Comment by stereodenis** [comment]
@lucasfeliciano I try to use 0.25-0-rc version with your PR, but when I click on fullscreen button — video becomes black, but I still hear it sound. Looks like video goes to background

**Comment by lucasfeliciano** [comment]
@stereodenis I'm not sure what is happening.

I need some time to check it out what is going on with 0.25.

I'll try to do it this week.

**Pull request closed without merging**
