### PR TITLE
update yeoman-generator to 0.21 because of RegExp DoS issue

### PR DESCRIPTION
**Pull request by hollanderbart**
Installing react-native gives a warning because of outdated version of yeoman-generator. The warning is ```npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue```.
This MR will update the yeoman-generator version to 0.21.0 to resolve this warning.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hollanderbart** [comment]
Can someone please rerun the CI?

**Comment by hollanderbart** [comment]
Ammended the commit to rerun the CI (flaky test)

**Comment by satya164** [comment]
cc @bestander

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-4** [comment]
I cannot do that @bestander, because @hollanderbart does not have an active CLA on file.

**Comment by bestander** [comment]
Ok, some temporary infra fail, should be resolved in a couple of hours

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-4** [comment]
I cannot do that @bestander, because @hollanderbart does not have an active CLA on file.

**Comment by fredemmott** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/291951697862544/int_phab) to review internal test results.

**Comment by fredemmott** [comment]
@bestander: ping? I just imported this to make sure the bot would, not able to review.

**Comment by bestander** [comment]
Thanks, Fred, this is on my list

**Pull request closed without merging**
