### PR TITLE
webview can enable chromeClient through props.

### PR DESCRIPTION
**Pull request by lucasfeliciano**
Motivation: #6405

### CODE REVIEW

**Comment by bestander** [comment]
FYI buck build rpoblems

**Comment by satya164** [comment]
@lucasfeliciano Why not just set it by default?

**Comment by lucasfeliciano** [comment]
@satya164 I came with this idea as well.

I mentioned it in #6405 but @charpeni said it was better to make the PR that way and discuss alternatives here.

One of the things of enable it as a prop is that if you are developing a product which target devices with no hardware acceleration you can disable it.

In my case I could enable as a default behaviour but I dont know about other people

**Comment by satya164** [comment]
@lucasfeliciano IMO it doesn't make sense to have this as a prop. Being able to embed videos is something people expect by default.

Moreover, the prop is also quite confusing, as the name of the prop is tied to the implementation detail and not the feature it enables. But again, I don't think `enableVideos` is the correct prop name since setting a `WebChromeClient` allows to handle far more things rather than just videos.

About enabling it only for devices which have hardware acceleration, don't all devices have hardware acceleration these days? Even then, since being able to embed videos requires both hardware acceleration and setting a `WebChromeClient`, just setting a `WebChromeClient` shouldn't be an issue.

cc @mkonicek

**Comment by stereodenis** [comment]
branch 'feature/chromeClient-on-android-webview' not working on 0.22

**Comment by lucasfeliciano** [comment]
@satya164 I agree with you.

Default is the best approach for me.
IMHO, even better if there is a prop to disable it if the developer wants.

**Comment by lucasfeliciano** [comment]
I think I made some boo boo here with the rebase.
:disappointed:

**Comment by lucasfeliciano** [comment]
I'll fix this soon.

Tried to do this asap, didnt end how I expected.
hahaha

**Comment by bestander** [comment]
:)

**Comment by lucasfeliciano** [comment]
Sorry for the delay, I was out the whole weekend.

Working upon v0.22 now.

And the discussion about "props vs default"?

@satya164 I'm into have this a default behaviour

**Comment by satya164** [comment]
@lucasfeliciano Let's make it default. Also can you fix the PR?

**Comment by lucasfeliciano** [comment]
@satya164 sure.
I'm on it now

**Comment by lucasfeliciano** [comment]
I'll close this PR and make a new one!

**Pull request closed without merging**
