### PR TITLE
Remove defaultProps from DatePickeriOS | #31605

### PR DESCRIPTION
**Pull request by oguzturker8**
## Summary

Removed defaultProps from core components;

-  DatePickeriOS  -> removed `mode: 'datetime'` prop #31605

## Changelog

[iOS] [Removed] - Removed defaultProps from DatePickerIOS.ios.js

## Test Plan

CI is passing  **BUT** `test_android` & `test_docker` give buck error.
Used #31593 's a44c4bd5216d17bfebb95b363a0f1919061d4f9d & 395eb213a67049666dd17ed46bfa6e6bdd5c868d commits.

### CODE REVIEW

**Comment by lunaleaps** [comment]
Hi @oguzturker8, thank you for your effort here! 

Can you split these up per issue and comment on them so I can assign them to you? We already have someone who claimed StatusBar https://github.com/facebook/react-native/issues/31607 -- can you please drop your changes to StatusBar? 

Going forward, I'm hoping people claim the issue first before committing a PR -- apologies for not clarifying that! I will update future parent issues with that disclaimer.

**Comment by oguzturker8** [comment]
Hi @lunaleaps, sorry for that. 
I didn't know i need to claim the issue before committing a PR. I'll be taking DatePickeriOS #31605 and updating the PR first. Thanks

**Comment by lunaleaps** [comment]
@oguzturker8 No worries! It was my bad for not communicating it clear enough! Thanks again for your contributions!

**Comment by oguzturker8** [comment]
It's better to create a new PR. Most of current commits are redundant.

**Pull request closed without merging**
