### PR TITLE
Copy over code from RCTView to allow individual image border radii

### PR DESCRIPTION
**Pull request by jacobp100**
This *works*. It’s not the best solution for this, and I think we need to consider how we handle UIView superclasses. This is mostly a demonstration to show what I want to achieve, but I will need guidance on how this should best be implemented.

This implementation is just copying over the code from UIView.m.

screen shot 2016-11-28 at 20 30 17

### CODE REVIEW

**Comment by javache** [comment]
cc @shergin

**Comment by shergin** [comment]
Yes, we do want fix/improve/unify border related stuff on iOS but obviously just duplicating the code is not an answer.

**Comment by jacobp100** [comment]
I’m happy to look more into this. Could you give some pointers about where the abstraction should be? Should RCTImage inherit from RCTView, or should we make a new class that both RCTImage and RCTView inherit form, or something entirely different?

**Comment by lacker** [comment]
I think the TLDR is that nobody has a clear idea of what to do here, but it's reasonably clear that we should not be copying code over. I think you will just have to investigate and see if you discover a reasonable solution. Sorry I don't have a smarter answer here. Anyway, for this specific pull request I think we should close it because this code approach is not the ideal way to solve it. Thanks for submitting this and if you figure out a nice way to do this then it would be great to submit another pull request!

**Pull request closed without merging**
