### PR TITLE
Add Tencent Classroom app to the Showcase

### PR DESCRIPTION
**Pull request by WeweTom**
add a Tencent education app 腾讯课堂 , which is a hybrid app , It's index page use ReactNative

### CODE REVIEW

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
@WeweTom can you sign the CLA?

**Comment by mkonicek** [comment]
It looks like this PR changes a few unrelated apps too?

Thanks for sending this pull request. According to the guidelines in that file, "infoLink" must be one of:

 1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native

I am going to close this, but if you have one of those two things, feel free to reopen with a new link.

**Comment by lacker** [comment]
OK I think Hector and Martin disagree. I'm going to close but if you sign the CLA I will import it

**Comment by WeweTom** [comment]
Sorry to reply late. I have signed the CLA.

**Pull request closed without merging**
