### PR TITLE
Revert schedule() function for rendering cells per #14348

### PR DESCRIPTION
**Pull request by niftylettuce**
See #14348

### CODE REVIEW

**Comment by niftylettuce** [comment]
This isn't valid

**Comment by sahrens** [comment]
The only extra work it does is a little bit of math to determine if it should be a hi-pri update or not. Or are you seeing that the updates are hi-pri more often than they should be?

**Comment by niftylettuce** [comment]
@sahrens hey I sent you a message on Slack! (Expo)

**Comment by sahrens** [comment]
I'm not on the expo channel - can you invite me or use messenger or something?

**Comment by sahrens** [comment]
Or just discuss here?

**Comment by niftylettuce** [comment]
@sahrens So ignore the PR - the poor performance was due to my list having components that were not PureComponent's.  I was using the [NativeBase library](http://nativebase.io) and it was causing rendering issues/slow performance.  I switched to rendering with pure <View> and <Text> and it works great now.

**Comment by sahrens** [comment]
Awesome, glad to hear it.

**Comment by tjmadsen** [comment]
@niftylettuce I'm facing the same issue (very slow initial load).  Can you explain a bit more on what you had to do to fix this, or point me int he right direction?  It's slightly faster once I changed my renderItem component to be a PureComponent, but still slower to load than ListView was.  Do you know what is causing the slow load performance?

**Comment by niftylettuce** [comment]
@tjmadsen I think the only approach for fast scrolling lists on React Native right now is to use FlatList in combination with React.PureComponent, and to not really have many views or components going on at once.  In general though, React Native does not really support fast and long scrolling lists.  It's very slow and limited with what you can do.  I have considered writing a pure iOS and Android component instead.

**Comment by tjmadsen** [comment]
@niftylettuce FYI - just implemented this fix and it made it WAY faster for me (though still not perfect)
https://github.com/facebook/react-native/commit/ebcf5fd24173c2628a5dcc65871fa7a8b219f96e

**Pull request closed without merging**
