### PR TITLE
Updates from Tue July 7 - includes new Animated API

### PR DESCRIPTION
**Pull request by sahrens**

### CODE REVIEW

**Comment by ide** [comment]
0.8.0-rc is really shaping up to be an exciting release. Also really happy to see bezier support. I've been using cubic animations to approximate the keyboard animation and it's not quite there.

**Comment by brentvatne** [comment]
What a beauty!

**Comment by sahrens** [comment]
Let me know if you have any feedback - easiest to make changes now before
people build too much on top of it :)

**Comment by brentvatne** [comment]
It looks like this is failing because `require('warning')` isn't working - it can no longer be required directly from react-tools. I fixed it by copying warning and emptyFunction over to Utilities: https://github.com/brentvatne/react-native/commit/00e023359b41442f94f61447f5aae392f8557e07

**Comment by devknoll** [comment]
Any chance we'll see animated broken out into its own npm lib?

**Comment by sahrens** [comment]
Definitely - I already reserved the module name "react-animated". We're going to get it working on web first, then publish it.

**Comment by joewood** [comment]
Does "getting to work on the web" include LayoutAnimation? Are there plans for that, or are you excluding that as the browser is managing flex layout on the web side of things?

**Comment by brentvatne** [comment]
@joewood - LayoutAnimation is separate from the Animated api, you could do this for the web with CSS animations :)

**Comment by sahrens** [comment]
We would probably need to wire everything up with css-layout to get LayoutAnimation support on web. Should be doable, but definitely more work.

**Comment by joewood** [comment]
Right, I was going to say, unless I'm missing something CSS transitions won't help with browser based layout, at least not without using dummy elements and an overlay. It would be nice to see the css-layout JS code managing a container supporting layout animations. I'm assuming this is going to be a requirement to get real web parity with the new animation features in RN.

**Comment by devknoll** [comment]
@sahrens @brentvatne Please tell me if you think I'm being crazy, but... I think it would be beneficial to encourage folks to use something in this direction (untested, don't shoot me if it doesn't work):

* [Tinder Example](https://gist.github.com/devknoll/19aeab25bc50f0d70820)
* [Bounce Example](https://gist.github.com/devknoll/b4aefa3155f60da9c05e)

It seems maybe almost a little harmful to (inadvertently?) encourage folks to mix in a bunch of animation code into their regular components. It might be a good thing to take a page from the recent HoC trend.

**Comment by devknoll** [comment]
Another half baked idea:

It would be nice if `Animated.<Component>` could somehow become hidden from the user. Imagine instead using:

```js
<BounceOnMount start={1.5} end={0.8} friction={0.8}>
  {bounceValue => (
    <Image
      source={{uri: 'http://i.imgur.com/XMKOH81.jpg'}}
      style={{
        flex: 1,
        transform: [
          {scale: bounceValue},
        ]
      }}
    />
  )}
</Bounce>
```

And `BounceOnMount` could automatically create an `Animated.Image`.

In general, it seems strange to me that a component needs to know that it's going to be animated, but perhaps at some level that's unavoidable.

**Comment by ide** [comment]
@devknoll you could animate a container View in many cases if you prefer that route. I believe the reasoning behind Animated.View is so that the core components (namely how the style prop is handled) aren't married to this Animated library.

There are also a lot of cases where it's much easier to be able to use the animation library directly if the animation is non-trivial e.g. the interactive and linked animations in Spencer's talk.

**Comment by sahrens** [comment]
Yes, @ide touched on a key use-case that we aim to make easier with Animated which is complex coordinated animations between multiple components. Often times you basically end up layering two separate graphs on top of each other which is unwieldy when constrained to use the component hierarchy to propagate animation updates as in your example.

**Comment by sahrens** [comment]
Also, a specific and important goal of Animated is to be able to do optimizations including offloading the animations to another thread which is hard to do with an API that requires React-re-rendering on every frame.

**Comment by sahrens** [comment]
Finally got the tests to pass - merged!

**Comment by potiuk** [comment]
:+1: I was waiting for it :) .

**Comment by sahrens** [comment]
New docs are up too:

http://facebook.github.io/react-native/docs/animations.html

**Comment by brentvatne** [comment]
:heart_eyes:

**Comment by chirag04** [comment]
@sahrens Is rotateX, rotateY, rotateZ going to be added in transform any time soon? Right now we just have rotate which i think is kindof rotateX.

I need to make a flip card animation. Something like this: http://chrisharrington.github.io/demos/react-controls/flipper.html

Wondering if this is possible with the animation lib.

**Comment by ide** [comment]
@chirag04 send a PR?

**Comment by chirag04** [comment]
I don't think i have enough expertise to send a PR on this. I would love to explore more on this though. 

Also, @ide you sure it will not be possible to have that flip animation with this new animation lib?

**Comment by ide** [comment]
I don't know, I haven't tried it. There's a very good chance that it will work out of the box if style.transform already supports rotation.

**Comment by chirag04** [comment]
Will have to wait for @sahrens's input i guess.

I did try to animate using transform/rotate and the animation api. What i think i can do is rotate along x axis. I think flip is kindof 3d. Not sure.

**Comment by chirag04** [comment]
After digging deeper, I think we can use transformMatrix for 3d rotations. transformMatrix is not clearly documented but i think it takes a 4x4 matrix derived from ``quaternion`` matrix.

eg: If i were to rotate a view by 180 on y axis: quaternion matrix would be [0, 0, 1, 0] which converts to ``[-1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1]`` 4d matrix. 

If the new animation api can use transformMatrix, I think we would be able to handle 3d animations.  @sahrens What do you think? Not sure if any of this makes any sense.

**Comment by brentvatne** [comment]
It doesn't look like 3d transforms are currently supported, you could do your own matrix math and leverage the `transformMatrix`style though. It would be nice to see support for the `perspective` transform: https://desandro.github.io/3dtransforms/docs/perspective.html

**Comment by sahrens** [comment]
Shouldn't be an issue to support flip animations at all, just need to do
the math. Check out the _precomputeTransforms function that combines the
style transforms into one 3D matrix (in precomputeStyle.js)

**Comment by JonasJonny** [comment]
Thank you very much guys for this. You are such an inspiration to me.

(BTW: @ide If you will share a gist with "better" keyboard animation, as you will be satisfied it would be fantastic too)

**Comment by chirag04** [comment]
@sahrens  @vjeux  I changed precomputeStyle.js to expose rotate(X,Y,Z). Happy to PR if you would like.

This is how far i could go using rotateX with the new animated api. Not sure why the transition doesn't look like a flip. check: http://chrisharrington.github.io/demos/react-controls/flipper.html

Code for below animation is here: https://gist.github.com/chirag04/5ac0d44aa154fe91d000

ezgif com-video-to-gif

**Comment by sahrens** [comment]
You need the perspective via m34 - checkout for some info http://blog.radi.ws/post/11484924164/flipping-with-proper-perspective-distortion-in

-Spencer

**Comment by chirag04** [comment]
@sahrens  Awesome tip on perspective. Had to read a lot on perspective but i got it working. 

ezgif com-video-to-gif 1


I had to change the react-native source code to support rotate(X,Y,Z) transform and adding perspective transformations in ``MatrixMath`` for ``reuseRotateXCommand`` etc.
I could have done this by just using transformMatrix as well but seems like i cannot use animated lib with transformMatrix.

I see two approaches to solve this:
1) Animated lib should support animation with transformMatrix.
Or
2) expose rotateX, rotateY, rotateZ.(Already implemented in source. just need to expose).  Add ``perspective matrix`` as a property of transform.

It would make 3d animations really really smooth and easy. 

Let me know what you think? I can PR also i guess on this.

cc @vjeux  @ide @brentvatne

**Comment by sahrens** [comment]
Exposing everything (including perspective) as supported transforms in
style that animated can drive would be great.

**Comment by brentvatne** [comment]
Well done @chirag04! I agree with @sahrens, exposing all of those transforms would be ideal

**Comment by chirag04** [comment]
Cool. I can work a PR out for rotateX, Y, Z.  Is it ok?

Will add perspective to PR as well.

What happens to the current ``rotate`` which is just an alias to rotateZ? Keep or deprecate in favor of rotateZ?

**Comment by sahrens** [comment]
Awesome!  You can just keep "rotate" as an alias for "rotateZ". 

-Spencer

**Comment by vjeux** [comment]
A good way to know what the API should be is to mimic the web one: https://developer.mozilla.org/en-US/docs/Web/CSS/transform

**Pull request merged**
