### PR TITLE
New Toast Android Component Use Cases

### PR DESCRIPTION
**Pull request by chirag-singhal**
## Summary
 * New use cases for toast android component in rn-tester

## Changelog
[General] [Changed] - Changed use cases for toast android component in rn-tester

## Test Plan 
* Tested app in both Android and iOS
After - 
image
Before - 
image

### CODE REVIEW

**Review by rickhanlonii — COMMENTED** [review]
Code looks good, can you include a before/after demo in the test plan?

**Comment by chirag-singhal** [comment]
Updated the test plan!

**Comment by rickhanlonii** [comment]
@chirag-singhal the new pressable items say "click me" instead of "tap me", shouldn't they say "tap"?

**Comment by chirag-singhal** [comment]
@rickhanlonii The older version says click me, the new changes says tap to view toast

**Comment by chirag-singhal** [comment]
@rickhanlonii the new version says tap to view toast, the older version had text 'click me'

**Comment by rickhanlonii** [comment]
Oh I see, thanks!

**Pull request closed without merging**
