### PR TITLE
Upgrade Flipper to 0.44.0

### PR DESCRIPTION
**Pull request by sunnylqm**
## Summary

Current flipper version would:
1. block form data request on android. The patch was landed on 0.39 https://github.com/facebook/flipper/commit/f3edfb36db4638b3c3352ca8ff7476074e44f76a
2. crash when using base64 image on ios. The patch was landed on 0.37 
https://github.com/facebook/flipper/commit/e44c7f40622750e7b374312c9eb6f6983a84b3ae

Fixes https://github.com/facebook/react-native/issues/28551 , and https://github.com/facebook/react-native/issues/28469

## Changelog

[Android] [Changed] - Upgrade Flipper to 0.44.0
[iOS] [Changed] - Upgrade Flipper to 0.44.0

## Test Plan

RNTester build pass

### CODE REVIEW

**Comment by anthony1110** [comment]
Hi All, I know how to upgrade Flipper version at android but how can I upgrade IOS Flipper version to 0.44 at ios/podfile there?

**Comment by sunnylqm** [comment]
@anthony1110 For 0.62 you can modify `ios/Podfile`, for 0.63 currently you have to modify `node_modules/react-native/scripts/react_native_pods.rb`

**Comment by anthony1110** [comment]
> @anthony1110 For 0.62 you can modify `ios/Podfile`, for 0.63 currently you have to modify `node_modules/react-native/scripts/react_native_pods.rb`

I am using RN 0.63. Thanks for the info.

**Comment by sunnylqm** [comment]
@anthony1110 Just found that you can pass the version in `iod/Podfile`, e.g, 
```
use_flipper!('Flipper' => '0.51.0')
```

**Comment by safaiyeh** [comment]
Closing as flipper upgrade has been merged to a higher version than this PR

**Pull request closed without merging**
