### PR TITLE
[don't merge] Revert "Make the new bridge the default"

### PR DESCRIPTION
**Pull request by bestander**
Testing if tests change

### CODE REVIEW

**Comment by foghina** [comment]
@facebook-github-bot shípit

**Comment by bestander** [comment]
Got me scared, Felix :)

**Comment by bestander** [comment]
9ee1cfb8a4fc259d6ead995189273b85f059c4773614283a94553ef7363dffc7
I reverted everything that could be involved

**Comment by bestander** [comment]
fixed in #8539

**Pull request closed without merging**
