### PR TITLE
bump Android SDK to 28

### PR DESCRIPTION
**Pull request by dulmandakh**
This PR is bumping compileSdkVersion to 28, buildToolsVersion to 28.0.3, Gradle to 4.10.2, Android Gradle plugin to 3.2.1.

Gradle 4.7 added support for Java 10 and 11.

Test Plan:
----------
CI is green, and RNTester app is working as expected.

Release Notes:
--------------
[ANDROID] [ENHANCEMENT] [SDK] - bump to 28

### CODE REVIEW

**Comment by dulmandakh** [comment]
bumped Gradle to 4.10.2 because gradle-download-task landed tests for it. Also bumped android plugin to 3.2.1.

**Comment by hramos** [comment]
This was blocked for a while, as upgrading the Gradle binary internally takes some manual work. 

The problem I'm running into now is that while Android SDK 28 is available in our internal repository, we do not yet have access to Build Tools 28.0.3. The latest version we have is 28.0.2, but Gradle 4.10.2's minimum supported version is 28.0.3.

**Comment by hramos** [comment]
This is landing now. As build tools 28.0.3 are not available on our internal build servers yet, I had to downgrade the gradle plugin as 3.2.1 requires 28.0.3. The combination I landed on is compileSdkVersion to 28, buildToolsVersion to 28.0.2, Gradle to 4.7, and Android Gradle plugin to 3.2.0.

**Comment by dulmandakh** [comment]
https://github.com/facebook/react-native/commit/f3e5cce4745c0ad9a5c697be772757a03e15edc5 bumped cradle to 4.10.2 and remove build tools version. Now only need to bump gradle android plugin.

**Comment by hramos** [comment]
That commit bumped the Gradle version used in OSS to 4.10.2, but our internal Gradle tests were still on 4.7 and therefore failing internally.

**Pull request closed without merging**
