### PR TITLE
[SampleApp] Delete SampleApp

### PR DESCRIPTION
**Pull request by ide**
The sample app's code has been converted to Yeoman generator templates. Tell people to run the UIExplorer instead, or the `react-native init` project (which is the same as the SampleApp). This will slightly reduce the size of the npm package and cleans up unused files.

### CODE REVIEW

**Comment by foghina** [comment]
I'm all for this, just CCing some iOS people to make sure it's OK with them as well.

@vjeux @tadeuzagallo @nicklockwood @sahrens - can one of you guys confirm this is OK?

**Comment by vjeux** [comment]
I'm all for it

**Comment by foghina** [comment]
@facebook-github-bot shipit

**Comment by ajwhite** [comment]
With the removal of `Examples/SampleApp`, where do the new generator templates live?

**Comment by ajwhite** [comment]
Ah - https://github.com/facebook/react-native/tree/master/local-cli

**Pull request closed without merging**
