### PR TITLE
Fixed images required from node_modules

### PR DESCRIPTION
**Pull request by bestander**
This fixes https://github.com/facebook/react-native/issues/6638 by resolving AssetRegistry relatively.

### CODE REVIEW

**Comment by bestander** [comment]
cc @davidaurelio

**Comment by bestander** [comment]
David, when Haste update is propagated I'll be happy to add a test for this case.

**Comment by ide** [comment]
Travis tests are failing:

> <unknown>:0: failed: caught "NSInternalInconsistencyException", "*** Assertion failure in -[RCTTestRunner runTest:module:initialProps:configurationBlock:expectErrorBlock:], /Users/travis/build/facebook/react-native/Libraries/RCTTest/RCTTestRunner.m:154: RedBox error: Unhandled JS Exception: Requiring unknown module "../../../../Libraries/Image/AssetRegistry.js". If you are sure the module is there, try restarting the packager or running "npm install"."

**Comment by bestander** [comment]
Thanks, James.
Maybe it needs haste change to propagate first

**Comment by davidaurelio** [comment]
node-haste v2.9.5 is published. Please update package.json to `"node-haste": "~2.9.5"`, and bump the version in `packager/package.json`

**Comment by bestander** [comment]
will do, thanks

**Comment by davidaurelio** [comment]
oh, this needs even more changes. Lovely. Let me come to your desk

**Comment by davidaurelio** [comment]
That looks like a sound solution! I couldn’t have come up with anything better than this!

**Comment by davidaurelio** [comment]
@facebook-github-bot import

**Pull request closed without merging**
