### PR TITLE
Remove internal `utf8` utility

### PR DESCRIPTION
**Pull request by mathiasbynens**
## Motivation

As requested by @davidaurelio in https://github.com/mathiasbynens/utf8.js/issues/17#issuecomment-312500535, this makes it possible for developers to use the `utf8` package from npm in combination with React Native.

Ref. https://github.com/mathiasbynens/utf8.js/issues/17

### CODE REVIEW

**Comment by EdenGottlieb** [comment]
https://github.com/facebook/react-native/blob/master/Libraries/Utilities/utf8.js#L9
` * @providesModule utf8`

This is what causes react-native's utf8 to override node_modules one, not the filename.

**Comment by EdenGottlieb** [comment]
The real question would be: why is it even there? I couldn't find a single require/import of utf8 in the whole repo.

**Comment by mathiasbynens** [comment]
> I couldn't find a single require/import of utf8 in the whole repo.

Outside of the tests, indeed!

**Comment by janicduplessis** [comment]
Yea I think we can delete it unless some internal code @fb depends on it.

cc @davidaurelio

**Comment by mathiasbynens** [comment]
@davidaurelio Can you confirm whether this is used internally at Facebook? If not, I’d be happy to update the patch to remove these files.

**Comment by janicduplessis** [comment]
@mathiasbynens You can go ahead and remove it, it won't pass fb internal CI anyway if it's used.

**Comment by mathiasbynens** [comment]
@janicduplessis Done.

**Comment by hramos** [comment]
Landing, I could not find internal uses but like Janic said, CI should block this from landing if it's indeed used internally.

**Pull request closed without merging**
