### PR TITLE
Merge the two Gradle Plugins

### PR DESCRIPTION
**Pull request by cortinico**
Summary:
This diff merges the `react-native-gradle-plugin` and the `react-codegen/android` into a single plugin.
This will allow us to iterate faster on a single plugin, will create less confusion for our users (`react` vs `reactApp`)
and will help us avoid race conditions when the two plugins are applied together (as we will control the whole lifecycle of it).

Changelog:
[Internal] [Changed] - Merged the two Gradle Plugins

allow-large-files

Differential Revision: D30765147

### CODE REVIEW

**Comment by ecreeth** [comment]
👀 This change looks like comes with bundle size optimization. Compared with PR https://github.com/facebook/react-native/pull/32176#issuecomment-916131891

**Comment by cortinico** [comment]
> 👀 This change looks like comes with bundle size optimization. Compared with PR [#32176 (comment)](https://github.com/facebook/react-native/pull/32176#issuecomment-916131891)

Thanks for pointing it out. I believe the bundle size should actually be unaffected so that might be a false reporting. I'll look into it.

**Comment by dulmandakh** [comment]
@cortinico  I would suggest **com.facebook.react.gradle** as plugin name

**Comment by cortinico** [comment]
> @cortinico I would suggest **com.facebook.react.gradle** as plugin name

I believe we will end up with `com.facebook.react` as plugin name, but it's still up for debate. cc @ShikaSD

**Comment by dulmandakh** [comment]
> > @cortinico I would suggest **com.facebook.react.gradle** as plugin name
> 
> I believe we will end up with `com.facebook.react` as plugin name, but it's still up for debate. cc @ShikaSD

It's even better 👍

**Pull request closed without merging**
