### PR TITLE
Added the  PushFromLeft animation to Navigator

### PR DESCRIPTION
**Pull request by wanone**
Added the  PushFromLeft animation to Navigator

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @MengjueW and @neciu to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by danielbraun** [comment]
@yunfeng123 Can you try to merge master again?

**Comment by facebook-github-bot-2** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @MengjueW as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by danielbraun** [comment]
If it's any help, I've merged into my local branch and it works well.

**Comment by mkonicek** [comment]
Thanks!

@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3841403) to review internal test results.

**Pull request closed without merging**
