### PR TITLE
Invoke `node` directly in generate-specs.sh

### PR DESCRIPTION
**Pull request by ivanmoskalev**
## Summary

Currently, Codegen bash wrapper (`generate-specs.sh`) for Xcode invokes JS-based Codegen tooling via `yarn --silent node <...>`. This breaks both: 

- when Yarn is not installed (if NPM is used), for obvious reasons
- when Yarn v2 ("Berry") is active
 
This PR changes the way `generate-specs.sh` locates `node` executable to the following algorithm: 

- use the path provided in the `NODE_BINARY` env var
- if `NODE_BINARY` env var is not defined, find `node` with `command -v node`

## Changelog

[iOS] [Fixed] - Fix Codegen silently failing when Yarn is not installed, or when Yarn v2 is active.

### Case 1 (no Yarn installed)

1. Ensure `yarn` is not present in PATH
2. Run Xcode build
3. Check that Codegen artifacts are produced

### Case 2 (Yarn v2 is used)

1. Ensure `yarn` is running in the v2 ("Berry") mode
2. Run Xcode build
3. Check that Codegen artifacts are produced

### CODE REVIEW

**Review by janicduplessis — APPROVED** [review]
LGTM

cc @hramos

**Comment by ivanmoskalev** [comment]
@janicduplessis I actually would want to have some advice from the code owners on [this](https://github.com/facebook/react-native/pull/30781#discussion_r563157174). Currently, we still need to work around that line, since it breaks Codegen for Yarn-less machines. I can either work in some fallback for that case, OR, instead, get rid of yarn invocations altogether, if the callsite is now intended to be unreachable.

**Comment by janicduplessis** [comment]
@ivanmoskalev The link doesn't work, but I assume you are talking about the last YARN_BINARY callsite. This one should only happen when building RN from source. Still a good idea to fix it I think. One possibility is just call this script instead https://github.com/facebook/react-native/blob/bec5e147cb0a84225f88b3dbc2f87c39c0ef0bc7/packages/react-native-codegen/scripts/oss/build.sh. It already handles npm and yarn.

**Comment by janicduplessis** [comment]
We're also in the process of landing https://github.com/facebook/react-native/pull/30792 which will make changes to this code. I think after this you will want to check for whether the NODE_BINARY exists and make sure to add ` || true` after the new `command -v`.

**Comment by ivanmoskalev** [comment]
Adding fixes in a couple hours, was on a sick leave for ~ last week.

**Comment by ivanmoskalev** [comment]
@janicduplessis @hramos I have updated the script, would you have a look, please? 

I've also got 2 questions: 
- Do CI tests cover the usecase in which `$CODEGEN_PATH/scripts/oss/build.sh` will be called? I'm asking because I don't know how to properly test it on my machine.
- I expect merge conflicts with #30792 – do I need to wait for it to land and rebase my fork myself, or will conflict resolution be done by the FB team when they import this PR into their monorepo?

**Comment by hramos** [comment]
I'll take care of the conflict.

**Pull request closed without merging**
