### PR TITLE
Add missing resizeMode prop on Image Android

### PR DESCRIPTION
**Pull request by Bhullnatik**
It seems like the `resizeMode` propType was missing from `Image.android.js`, this PR adds it.
I caught by trying to use `Image.propTypes.resizeMode` on Android, and getting a warning because it was `undefined`.

It's not supposed to break anything, maybe pop a few warnings but not much more.

**Test Plan:**
- Launched UIExplorer

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @christopherdro and @ide to be potential reviewers.

**Comment by Bhullnatik** [comment]
Now that I think about it, it may be better to do a common propType file for both `Image`s, like [`ViewStylePropTypes`](https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewStylePropTypes.js) so that problems like that don't surface again, but it loses precision over platform-specific propTypes.

**Comment by facebook-github-bot-0** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @cornedor as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by christopherdro** [comment]
@Bhullnatik LGTM! 👍 
Would you mind rebasing to master?

**Comment by facebook-github-bot-5** [comment]
@Bhullnatik updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@Bhullnatik updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@Bhullnatik updated the pull request.

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @andreicoman11 as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1710043185944103/int_phab) to review internal test results.

**Pull request closed without merging**
