### PR TITLE
Add null checks for operations execution

### PR DESCRIPTION
**Pull request by MAKARD**
## Summary:

A fix for the related issue, that still occurs for some people.
https://github.com/facebook/react-native/pull/11428

Stacktrace
image

## Changelog:

[ANDROID] [FIXED] - Added null checks for queued ui operations execution

## Test Plan:

Unfortunately, I'm not able to reproduce the issue, therefore I don't have any particular steps for testing.

### CODE REVIEW

**Comment by MAKARD** [comment]
up

**Comment by MAKARD** [comment]
up

**Comment by MAKARD** [comment]
up

**Comment by javache** [comment]
I don't believe the right fix, as we never add null elements to those arrays.

Please apply the reverse proguard renaming to that stacktrace to see where this actually crashed.

**Comment by MAKARD** [comment]
@javache I did Desymbolication of the stacktrace, but I'm still not sure where else I can look apart from UIViewOperationQueue.java 
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.uimanager.UIViewOperationQueue$UIOperation.execute()' on a null object reference
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
  at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches(UIViewOperationQueue.java:1)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
  at android.view.Choreographer.doCallbacks(Choreographer.java:923)
  at android.view.Choreographer.doFrame(Choreographer.java:847)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
  at android.os.Handler.handleCallback(Handler.java:942)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:226)
  at android.os.Looper.loop(Looper.java:313)
  at android.app.ActivityThread.main(ActivityThread.java:8762)
  at java.lang.reflect.Method.invoke(Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

@javache could you point me out what I am doing wrong?

**Pull request closed without merging**
