### PR TITLE
Remove instructions about IP address on iOS

### LINKED ISSUE #8651: [Docs] Update docs for "Running on Device"
Hi there,

I'm new to React Native and I was having problems with Running on Device yesterday on iOS. I was following this section of the docs:

https://facebook.github.io/react-native/docs/running-on-device-ios.html

I realised after I was using 0.28 and in the latest stable release 0.29 you don't have to change `localhost` to your IP Address on the network as stated in these docs.. In fact I couldn't even find localhost in the `AppDelegate.m` so this part no longer seems relevant and may be confusing to people reading it.

### PR DESCRIPTION
**Pull request by charpeni**
The documentation was not updated after this change : Implemented automatic IP detection for iOS (8c29a52) 

Fixes #8651.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @joelcloralt to be potential reviewers.

**Comment by janicduplessis** [comment]
👍 

@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1785748351639744/int_phab) to review.

**Comment by apearce** [comment]
The documentation for Using the offline bundle still appears to be incorrect. It references uncommenting a line that does not exist. It would be great if it was updated with the correct way of doing this.

**Comment by charpeni** [comment]
@apearce Thank you for reporting, I'll look into this.

**Pull request closed without merging**
