### PR TITLE
Breaking: Ignore StatusBarManager rejected state

### PR DESCRIPTION
**Pull request by leeight**
See #10236

### CODE REVIEW

**Comment by janicduplessis** [comment]
Thinking about this more (sorry), we should just get rid of the promise. iOS doesn't have that and it's only used to report the error back to JS, but then we won't event use it.

We could just log it instead in native and do nothing with something like:
```
FLog.w(ReactConstants.TAG, "StatusBarModule: Ignored status bar change, current activity is null.");
```

**Comment by leeight** [comment]
@janicduplessis You mean change the method signature and remove `final Promise res`, so that make it consistent with iOS?

`public void setHidden(final boolean hidden, final Promise res) {` --> `public void setHidden(final boolean hidden) {`

**Comment by janicduplessis** [comment]
Yes, it's a breaking change but I doubt anyone was using the promise.

**Comment by janicduplessis** [comment]
LGTM, let's wait a bit see if someone has something to add. If not I'll shipit.

**Comment by leeight** [comment]
@janicduplessis Could you shipit?

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
Just a reminder, if anyone is merging any breaking change, please change the commit message to include `breaking` so we can find it when writing the release notes.

**Comment by leeight** [comment]
@janicduplessis Is there anything else i can do to fix the merge failed issue?

**Comment by janicduplessis** [comment]
@leeight Not sure why it failed lets just try it again

@facebook-github-bot shipit

**Comment by leeight** [comment]
@janicduplessis I guess some FB internal test cases failed, maybe we shouldn't change the method signature. Could you help me check the internal logs? Or we should ignore rejected state in `StatusBar.js` but keep `StatusBarModule.java` the same.

**Comment by janicduplessis** [comment]
@foghina Could you have a look at why internal tests are failing?

**Comment by gotounix** [comment]
When will merge it into a release version?

**Comment by gotounix** [comment]
When this commit will be merged into master, and when will be merged into a release version?

**Comment by leeight** [comment]
@janicduplessis How about try it in another way? Fix it in the JS side, and don't change the java method signature?

**Comment by satya164** [comment]
cc @bestander

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by bestander** [comment]
Hm. of course, look at the Circle CI log:
```
/home/ubuntu/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/statusbar/StatusBarModule.java:23: error: package com.facebook.common.logging does not exist
import com.facebook.common.logging.FLog;
```

**Comment by bestander** [comment]
You need to change Buck file

**Comment by janicduplessis** [comment]
Ugh, how did I miss that -_- thanks @bestander !

**Comment by leeight** [comment]
Thanks @bestander, DONE.

**Comment by leeight** [comment]
PING

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
