### PR TITLE
[Profiler] Fix makefile target

### PR DESCRIPTION
**Pull request by ide**
Simple rename.

Test Plan: `make`

### CODE REVIEW

**Comment by tadeuzagallo** [comment]
Thanks! :)

@facebook-github-bot import

**Comment by ide** [comment]
@tadeuzagallo btw do you have a trick to visualize the data like loading it into Web Inspector?

**Comment by tadeuzagallo** [comment]
We are working on the tool for that internally, and making the profiling workflow smoother. I'll make it available here as soon as everything is working nice together.

**Comment by ide** [comment]
Cool, that will be helpful for speeding up app code =)

**Pull request closed without merging**
