### PR TITLE
Document arguments to onSelectionChange

### PR DESCRIPTION
**Pull request by xixixao**
To update the documentation. Works on iOS, so I assume this is the same on Android.

### CODE REVIEW

**Comment by xixixao** [comment]
@mkonicek ping :)

**Comment by mkonicek** [comment]
I don't see pings on GitHub (too many notifications). Message me please :)

**Comment by mkonicek** [comment]
I don't see pings on GitHub (too many notifications). Message me please :)

**Comment by mkonicek** [comment]
Thanks for improving the docs!

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
