### PR TITLE
CLI: Add support for project templates

### PR DESCRIPTION
**Pull request by mkonicek**
Currently it is not trivial for people to get started with React Native. `react-native init MyApp` just creates a simple app with a single screen. People have to spend time figuring out how to add more screens, or how to accomplish very basic tasks such as rendering a list of data or handling text input.

Let's add an option: `react-native init --template navigation` - this creates a "starter" app which can be easily tweaked into the actual app the person wants to build.

**Test plan (required)**

- Checked that 'react-native init MyApp' still works as before:

screenshot 2017-02-02 16 56 28

screenshot 2017-02-02 16 58 04

- Ran 'react-native init MyNavApp --template'. This prints the available templates:

```
$ react-native init MyNavApp --template
...
The available templates are:
navigation
You can use these to create an app based on a template, for example: you could run: react-native init MyNavApp --template navigation
```

- Checked the template works:

```
$ react-native init MyApp --template navigation
...
$ cd MyApp
$ react-native run-ios
```

screenshot 2017-02-02 18 52 24

- Checked an error is printed when a bad template name is provided:

```
$ react-native init MyNavApp --template foo
Setting up new React Native app in /private/tmp/MyNavApp
readline.js:982
            throw err;
            ^

Error: Uknown template: foo
```

### CODE REVIEW

**Comment by ericvicenti** [comment]
The template generator code is looking great!

Only feedback is that I think a TODO app may be a preferable example. Also it may be nice to have a stack in the example, because stack navigators are super common.

**Comment by mkonicek** [comment]
Thanks for the review! While building the Chat example I realized it shows most of the concepts well, and a Todo app might be a bit boring? Not a strong opinion though..

The app is using a StackNavigator - it's the top level one, and the TabNavigator is nested inside it.

**Comment by mkonicek** [comment]
I'll merge it for now and iterate on the template.

@facebook-github-bot shipit-ninja

**Comment by mkonicek** [comment]
@facebook-github-bot shipit-ninja

**Pull request closed without merging**
