### PR TITLE
[Documentation] (Using Navigators) Remove getDefaultProps() from ES6 …

### PR DESCRIPTION
**Pull request by kurapikats**
Motivation: 
I'm studying react-native, when I got to Using Navigator part of the Tutorial I got stuck because of unclear instructions.

The changes are: 
1. I've remove the getDefaultProps() method inside the MyScene.js since it's a ES6 Component, then passed initial title props at <MyScene> instance.
2. Replaced YoDawgApp component and class name with SimpleNavigationApp for consistency.
3. Added AppRegistry on Complete Example code.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @scarlac to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
@kurapikats updated the pull request.

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
The edit in #1 shouldn't be necessary as you can use ES6 components in React Native.

**Comment by hramos** [comment]
I believe that using different names for YoDawgApp and SimpleNavigationApp is intentional, to differentiate between the complete example at the end and the code snippet.

**Comment by facebook-github-bot-0** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @hramos as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
Can you rebase?

**Comment by hramos** [comment]
Closing. If rebased, we can reopen and import.

**Pull request closed without merging**
