### PR TITLE
Return component in renderScene prop

### PR DESCRIPTION
**Pull request by romidane**
**motivation**
The previous example was not returning the component therefore would not render anything is someone followed the example

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @scarlac to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by scarlac** [comment]
I believe this is a duplicate of #9161

**Comment by romidane** [comment]
@scarlac You're right! I'll close the pull request

**Pull request closed without merging**
