### PR TITLE
[React Native] Use full path for react-native on HMR config

### PR DESCRIPTION
**Pull request by martinbigio**
Fixes https://github.com/facebook/react-native/issues/6731

### CODE REVIEW

**Comment by martinbigio** [comment]
I've already released 1.5.6 and a few users have confirmed it works for them. This change only applies the tweak to the code and bumps the version.

cc @skevy @satya164

**Comment by satya164** [comment]
What's the reason it doesn't work without the full path? I test as soon as I have a decent connection.

**Comment by martinbigio** [comment]
We don't know, both @skevy and I looked into it and couldn't figure it out. The same thing is happening for assets (#6638)

**Comment by martinbigio** [comment]
In theory it should work because we transform before resolving dependencies. However the packager is not redirecting the require to the actual main module of the package when the `require('react-native')`is added by the hmr plugin. Since it keeps the path as `react-native`, when all translated requires get turned into numeric IDs, this one is kept so we end up failing on runtime because there's no `__d` for `react-native`

**Comment by martinbigio** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
