### PR TITLE
Allow CameraRoll to export videos

### PR DESCRIPTION
**Pull request by corbt**
This PR adds the ability to export videos to the CameraRoll on both Android and iOS (previously only photos were possible, at least on iOS). The API has changed as follows:

```
// old
saveImageWithTag(tag: string): Promise<string>

// new
saveToCameraRoll(tag: string, type?: 'photo' | 'video'): Promise<string>
```

if no `type` parameter is passed, `video` is inferred if the tag ends with ".mov" or ".mp4", otherwise `photo` is assumed.

I've left in the `saveImageWithTag` method for now with a deprecation warning.

**Test plan (required)**

I created the following very simple app to test exporting photos and videos to the CameraRoll, and ran it on both iOS and Android. The functionality works as intended on both platforms.

```js
// index.js

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  CameraRoll,
} from 'react-native';
import FS from 'react-native-fs';

const vidPath = FS.DocumentDirectoryPath + '/vid.mp4';
const picPath = FS.DocumentDirectoryPath + '/pic.jpg';

class SaveToCameraRoll extends Component {
  componentDidMount() {
    FS.downloadFile({ fromUrl: 'https://s3.amazonaws.com/assets.emberall.com/TMP/pic.jpg', toFile: picPath })
    FS.downloadFile({ fromUrl: 'https://s3.amazonaws.com/assets.emberall.com/TMP/vid.mp4', toFile: vidPath })
  }
  _exportPhoto = () => {
    console.log('EXPORTING PHOTO');
    CameraRoll.saveToCameraRoll(picPath);
  };

  _exportVideo = () => {
    console.log('EXPORTING VIDEO');
    CameraRoll.saveToCameraRoll(vidPath);
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Test Camera Roll
        </Text>
        <Text style={styles.instructions} onPress={this._exportPhoto}>
          Export Photo
        </Text>
        <Text style={styles.instructions} onPress={this._exportVideo}>
          Export Video
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('SaveToCameraRoll', () => SaveToCameraRoll);
```

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @bestander and @dmmiller to be potential reviewers.

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1761932914088325/int_phab) to review.

**Comment by bestander** [comment]
Note that this commit broke website generation, I'll see if there is a quick fix

**Pull request closed without merging**
