### PR TITLE
Navigator - velocity override

### PR DESCRIPTION
**Pull request by seb0zz**
This code change allows changing the transition velocity of the navigator
when switching views.

Whats the use case? If you have different types of
animations your animations might also need different transition velocities.

### CODE REVIEW

**Comment by ide** [comment]
You need to add support for popping too.

**Comment by seb0zz** [comment]
@ide thanks for the hint, added support for popping.

**Comment by mkonicek** [comment]
cc @ide, @ericvicenti 

Do we still want to merge PRs for Navigator given it's getting deprecated in favor of NavigationExperimental?

**Comment by facebook-github-bot-9** [comment]
@AaaChiuuu would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by ericvicenti** [comment]
This looks reasonable. If you still want to land this, please rebase so we can test and ship it

**Comment by seb0zz** [comment]
Never did a rebase before but I think it should be fine now?

**Comment by ericvicenti** [comment]
Cool, hopefully the tests pass. Can you also add this to any relevant proptypes and documentation?

**Comment by seb0zz** [comment]
@ericvicenti would definitely do that but it seems that there is no real documentation about overriding parts of scene configs. Would be a completely new section in the [navigator docs](https://facebook.github.io/react-native/docs/navigator.html)

**Comment by ericvicenti** [comment]
Lets skip it for now, considering we are about to deprecate Navigator

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1561825797441364/int_phab) to review.

**Pull request closed without merging**
