### PR TITLE
add quotes to handle pathnames with spaces in it

### LINKED ISSUE #3135: [Packager] Development server not auto starting from Xcode
I am trying to run the react native application through Xcode, however, the development server does not seem to get started automatically. I must always type npm start at the project root before running in Xcode. Where am I going wrong?

### PR DESCRIPTION
**Pull request by mroswald**
fixes #3135

### CODE REVIEW

**Comment by mkonicek-pr-test** [comment]
@facebook-github-bot shipit

**Comment by mkonicek-tester** [comment]
@facebook-github-bot shipit

**Comment by mroswald** [comment]
do I have to rebase this branch to the current master in order to pass the ci checks? for this I'd force-push on this branch. Don't know if that's ok or really necessary?

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
