### PR TITLE
replaced ^ with ~ in versions in package.json

### PR DESCRIPTION
**Pull request by bestander**
"^" in versions is a bit loose.
A new recent example:immutable.js update 3.8.0 broke all react native flow checks that used ^3.7.0 as version.

**Test plan (required)**

Confirm that CI with clear cache passes all tests.

### CODE REVIEW

**Comment by bestander** [comment]
Need to import it manually and generate shrinkwrap

**Comment by mkonicek** [comment]
shipit 👍

**Comment by skevy** [comment]
I had mentioned this before, but this will cause potential breakages with Babel. May want to use ^ for the Babel deps still.

Cc @kittens

**Comment by kittens** [comment]
This wont effect transitive dependencies so once their ranges exceed these then there's going to be a lot of duplicated dependencies.

**Comment by bestander** [comment]
Could you please show an example how it would break?

**Comment by bestander** [comment]
To recap, we are going to keep babel with `^` and others with `~`.
Need to refresh the PR to latest.
Currently I am full, so this PR will hang for a while.

**Comment by facebook-github-bot-9** [comment]
@bestander do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by mkonicek** [comment]
@bestander Let's open a new PR once you work on it again? Just trying to keep the number of open PRs down.

**Pull request closed without merging**
