### PR TITLE
Implementing space-evenly

### PR DESCRIPTION
**Pull request by gedeagas**
## Motivation

So in v0.52.0 space-evenly is introduced but not yet implemented (1050e0b by @woehrl01). This pull request implements the space-evenly.

## Test Plan

Manual Testing.
notes marker

## Release Notes

[IOS] [FEATURE] [Yoga] Adding space-evenly on justify-content in iOS
[ANDROID] [FEATURE] [Yoga] - Adding space-evenly on justify-content in Android

### CODE REVIEW

**Comment by gedeagas** [comment]
Referencing an issue about this
#17728

**Comment by shergin** [comment]
@gedeagas Thank you!! ❤️

**Comment by mizinin** [comment]
It would be very cool to cherry-pick this patch into current stable branch (0.53) and make update

**Comment by GollyJer** [comment]
Can we please get this merged?
Just banged my head against a wall for a few hours.  I didn't realize "introduced" doesn't mean "implemented". 😄 
This feature will make photo grids significantly easier to create.

**Comment by gedeagas** [comment]
Hi, @GollyJer this feature is fully supported for react-native 0.54 above. 

The docs that live right now is for react-native version 0.54. Sadly if you use react-native version 0.53 you will not be able to use this feature hence the docs for 0.53 are not stating space-evenly (https://facebook.github.io/react-native/docs/0.53/flexbox.html). 

if you have a problem using this on react-native version 0.54 please feel free to ask me.

**Comment by turnrye** [comment]
@GollyJer sorry for the confusion -- working to update the 0.52 changelog now to clarify.

**Pull request closed without merging**
