### PR TITLE
Docs for manual linking in PushNotificationsIOS

### LINKED ISSUE #3831: [PushNotification] RCTPushNotificationManager.h not found
I followed everything here (https://facebook.github.io/react-native/docs/pushnotificationios.html
) to use PushNotification on iOS, but when I try to build the app, I get the following error. 

`RCTPushNotificationManager.h file not found`

I even added `RCTPushNotification.xcodeproj` to Libraries but it still get the same error.

### PR DESCRIPTION
**Pull request by magus**
close #3831

- always start website/setup.sh in website
- use setup.sh in website README

### CODE REVIEW

**Comment by satya164** [comment]
Hey @magus . Can you separate the PR into two? I cannot merge both together since the website docs are not synced to FB internal repo.

**Comment by magus** [comment]
Broke the pull up into two branches, hopefully it's the right split. I assume the website/ folder and the Libraries were the two things that needed to be separated.

https://github.com/facebook/react-native/pull/5008

**Comment by christopherdro** [comment]
@vjeux @mkonicek Not sure whats going on here.

**Comment by magus** [comment]
Originally branch was from my fork master, split it out into two branches. Not sure why there are repeated notifications though, I'm definitely not manually pushing anything to the branch or fork repo. Once my other PR is merged I will delete my fork entirely.

**Comment by vjeux** [comment]
So sorry about the spam. Our bot is broken and the person that works on it is in vacation right now. I'll disable it in the meantime

**Pull request closed without merging**
