### PR TITLE
Changed iOS to Android

### PR DESCRIPTION
**Pull request by madhur**
This article is for Android, not iOS

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @lacker to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@madhur Thanks for the pull request.

In addition to having to sign the CLA as mentioned above, we require that general pull requests target `master` and not a specific release like you do here. Can you change the pull request to target `master` -- or close this one and create a new one that does?

**Comment by JoelMarcey** [comment]
See the pull request template for information on this: https://github.com/facebook/react-native/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Pull request closed without merging**
