### PR TITLE
Provide a chance for making a callback reusable

### PR DESCRIPTION
**Pull request by rocman**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @lexs and @astreet to be potential reviewers.

**Comment by rocman** [comment]
Sometimes, when we are calling a native method from the JavaScript side passing in a callback, we want the callback can be called several times. This pull request make it possible.

**Comment by ide** [comment]
This seems risky because you need to remember to set `callback.reusable = false` when you're done with it. This might not be a bad idea -- we could have the native side say that it's done with the callback, which would tell the JS side to free the callback -- but we should think through this carefully and be sure that it's better than using an event emitter.

**Comment by rocman** [comment]
It's better than using an event emitter in the case that we just want to communicate between a specific js component and a specific RCTBridgeModule, because with reusable callback we don't need to write the dispatching logic.

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @lexs as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by javache** [comment]
I'd rather explore alternative solutions for making it possible for native to call JS multiple times, rather than opening up the possibility of leaks here.

**Pull request closed without merging**
