### PR TITLE
use Keep annotation instead of DoNotStrip

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

This PR replaces custom DoNotStrip annotation uses with Keep annotation from AndroidX, because in ReactAndroid we use nullability annotations from AndroidX and AndroidX annotations are already in dependencies.

## Changelog

[Android] [Changed] - use Keep annotation instead of DoNotStrip

## Test Plan

RNTester builds and runs as expected.

### CODE REVIEW

**Comment by dulmandakh** [comment]
Yep, Yoga ones and we need to discuss with FB guys about using AndroidX
annotations in it. Previously, they suggested not to use it when I migrated
nullable annotations.

**Comment by bartolkaruza** [comment]
Just posting this for reference: https://github.com/facebook/react-native/commit/ffdf3f22c68583fe77517f78dd97bd2e97ff1b9e

**Comment by yungsters** [comment]
By the way, I have been in discussions with the team at Facebook working on [Redex](https://github.com/facebook/redex) to understand if we can safely migrate to `@Keep` instead of `@DoNotStrip`.

If I can get a consensus that we can safely do this, @dulmandakh — would you be willing to rebase this pull request?

**Comment by yungsters** [comment]
Closing this because it was opened a long time ago and would require a rebase / rewrite.

If we want to pursue this in the future, I recommend only converting a single annotation (or a single class) so that we can verify it does not cause problems with people's Proguard configurations (e.g. if people are not composing the default configurations). If we can develop confidence with one call site, then we can go with a broader migration.

**Pull request closed without merging**
