### PR TITLE
Fixes NPE in setFontWeight method

### PR DESCRIPTION
**Pull request by bestander**
We have a crash in prod t11090540, urgent fix same way as in setFontStyle

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @brunobar79 and @dmmiller to be potential reviewers.

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1572532849710463/int_phab) to review.

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1572532849710463/int_phab) to review.

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1572532849710463/int_phab) to review.

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1572532849710463/int_phab) to review.

**Comment by dmmiller** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
