### PR TITLE
Add applicationIconBadgeNumber to LocalNotification.

### PR DESCRIPTION
**Pull request by joshuapinter**
- Add to PushNotificationIOS docs as well.

A remake of #2931 for current master. Thanks @alvaromb!

**Motivation**
Set the Application Badge Number with Local Notifications. Pretty key.

**Test plan (required)**
It's a very simple change - a single line to the RCTConvert. In my test app I did a simple `presentLocalNotification` in order to test if the application badge icon changed:

```js
PushNotificationIOS.presentLocalNotification({
  alertBody: "Testing Application Badge Icon becomes 3!",
  applicationIconBadgeNumber: 3
});
```

And it did change. Not sure if there are automated tests for this - let me know and I'll add to them for this.

### CODE REVIEW

**Comment by vjeux** [comment]
I have no context on this, do you know who would be a good reviewer?

**Comment by joshuapinter** [comment]
@vjeux Just based on the previous PR this came from, @chirag04 and @majak seemed to be good options.

**Comment by vjeux** [comment]
Cool, if either of them is signing off on this, i'll merge it in :)

**Comment by joshuapinter** [comment]
@vjeux Sounds good. I haven't heard from them about it specifically but it's a small change so hopefully they can have a quick look when they have a minute. Thanks. :)

**Comment by joshuapinter** [comment]
Whoops. Sorry about that. I have another PR for adding `scheduledLocalNotifications` and accidentally merged that into this branch. I'll revert that merge and keep the two separate.

**Comment by chirag04** [comment]
I don't have context on this and probably not the best person to review. seems trivial tho.

**Comment by joshuapinter** [comment]
@chirag04 Anybody else you can think of that would have context to approve this? Thanks!

**Comment by joshuapinter** [comment]
@chirag04 @vjeux 

Hey guys, any chance of getting this merged in? 

Thanks!

Josh

**Comment by joshuapinter** [comment]
Looks like things are moving forward with #2931 again so I'm going to close this. 

Thanks @alvaromb!

**Pull request closed without merging**
