### PR TITLE
Update TouchableHighlight.js

### PR DESCRIPTION
**Pull request by CorpusCallosum**
changing the default underlay color to transparent, as this is the expected default functionality

### CODE REVIEW

**Comment by ide** [comment]
Could you expand on your reasoning why this should be the default? (Partly because everyone esp Facebook is going to have to update their TouchableHighlight call sites, which is doable if the change is greatly justified but there has to be a strong reason for the thrash.)

**Comment by CorpusCallosum** [comment]
If you look at the default iOS functionality, when you touch down on an
interactive element, it dims slightly. However, the default functionality
in React Native, is that the element dims slightly, and a black background
appears. This is unexpected (for a while I thought it was a bug, until I
realized that the underlayColor defaults to black). By making the default
underlay color transparent, the touchable elements will behave the same as
most touchable iOS elements, without the need for redefining the underlay
color.

It would be even better if there was a way to define alternate styles for
the pressed and unpressed states, much like a:hover in css.

On Thu, Nov 5, 2015 at 2:14 PM, James Ide <notifications@github.com> wrote:

> Could you expand on your reasoning why this should be the default? (Partly
> because everyone esp Facebook is going to have to update their
> TouchableHighlight call sites, which is doable if the change is greatly
> justified but there has to be a strong reason for the thrash.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/pull/3921#issuecomment-154157919>
> .
>



-- 
Jack Kalish
www.jackkalish.com

**Comment by ide** [comment]
TouchableHighlight matches a different default iOS function -- links in attributed strings. You're probably looking for TouchableOpacity.

**Comment by CorpusCallosum** [comment]
Ah yes, I must have missed that one in the documentation. Not sure what
"links in attributed strings" is. Still, I don't think having the default
highlight color be black makes much sense. Perhaps a semi-transparent grey?

On Thu, Nov 5, 2015 at 3:15 PM, James Ide <notifications@github.com> wrote:

> TouchableHighlight matches a different default iOS function -- links in
> attributed strings. You're probably looking for TouchableOpacity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/pull/3921#issuecomment-154177694>
> .
>



-- 
Jack Kalish
www.jackkalish.com

**Comment by ide** [comment]
It's black @ 0.8 opacity by default which is close to translucent grey.

Native iOS links: https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSAttributedString_UIKit_Additions/index.html#//apple_ref/doc/c_ref/NSLinkAttributeName

**Pull request closed without merging**
