### PR TITLE
[Android] assets' filename can contain non-latin letter

### PR DESCRIPTION
**Pull request by wusuopu**
## Summary
Relation Issues: https://github.com/react-native-community/cli/issues/1165

## Changelog
[Android] [Changed] - Image assets' filename can contain non-latin letter

## Test Plan
Added a unit test case in file `Libraries/Image/__tests__/resolveAssetSource-test.js`.

### CODE REVIEW

**Comment by wusuopu** [comment]
Relation Pull Request: https://github.com/react-native-community/cli/pull/1166

**Comment by thymikee** [comment]
needs a rebase

**Comment by charlesbdudley** [comment]
Thanks for this PR @wusuopu. Are these two included .png files necessary for the modified tests?

**Comment by charlesbdudley** [comment]
Hi @wusuopu, in an effort to clean up our outstanding PRs, and because this one is quite old and we haven't heard back from you, we're going to close this to focus on active ones. If you would like to pick this back up please comment and I'll be happy to reopen it! Thanks

**Pull request closed without merging**
