### PR TITLE
Fixed typo in docs

### PR DESCRIPTION
**Pull request by kapv89**

### CODE REVIEW

**Comment by satya164** [comment]
Can you sign the CLA so that we can merge your PR?

**Comment by kapv89** [comment]
@satya164 Have signed it
screenshot from 2016-04-05 18 24 10

**Comment by kapv89** [comment]
Also, please look into this: http://stackoverflow.com/questions/36373982/react-native-android-how-to-increase-dbmaximumsize

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
