### PR TITLE
replace DoNotStrip with Keep annotation

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

This PR replaces DoNotStrip with Keep annotation, and resurrection of https://github.com/facebook/react-native/pull/26178 per @yungsters  recommendation.

## Changelog

[Internal] [Changed] - replace DoNotStrip with Keep annotation

## Test Plan

CI is green

### CODE REVIEW

**Comment by dulmandakh** [comment]
@yungsters implementation is almost identical except Keep support annotations, https://android.googlesource.com/platform/frameworks/support/+/a9ac247af2afd4115c3eb6d16c05bc92737d6305/annotations/src/main/java/androidx/annotation/Keep.java

**Comment by yungsters** [comment]
Thanks for creating this! This will let us try out `@Keep` to make sure it works in all apps using React Native.

> @yungsters implementation is almost identical except Keep support annotations, https://android.googlesource.com/platform/frameworks/support/+/a9ac247af2afd4115c3eb6d16c05bc92737d6305/annotations/src/main/java/androidx/annotation/Keep.java

I think the problem is not with the implementation of `Keep`, but rather the default Proguard configuration that apps respect.

**Comment by dulmandakh** [comment]
@yungsters could you please let me know about the results of the PR. thanks

**Comment by yungsters** [comment]
@dulmandakh Will do! I have several PRs that I need to have imported and need to fix up before merging.

**Comment by yungsters** [comment]
Quick update: In order to test this internally, I had to update some build files specific to Yoga (not in the React Native repository). Tests are running now…

**Pull request closed without merging**
