### PR TITLE
use latest infer-annotations from maven

### PR DESCRIPTION
**Pull request by dulmandakh**
This PR removes infer-annotation from the repo and uses latest version of it from maven.

Test Plan:
----------
Everything builds and runs as normal

### CODE REVIEW

**Comment by gengjiawen** [comment]
Why can't i see android build ?

**Comment by dulmandakh** [comment]
@gengjiawen no idea, here is the link https://circleci.com/gh/dulmandakh/react-native/1349

**Comment by hramos** [comment]
GitHub sometimes fails to show all tests, but you can usually follow the link to Circle CI in order to see the entire workflow.

**Comment by dulmandakh** [comment]
@hramos I found that fresco and some other FB projects use infer-annotations from maven. Please review and merge.

**Pull request closed without merging**
