### PR TITLE
Improved error reporting for react-native link's Cocoapods integration

### PR DESCRIPTION
**Pull request by erlendfh**
## Motivation
Ran into an issue (#16774) with the new cocoapods integration after upgrading to 0.50.3. The error message `Cannot read property 'match' of undefined` is not very helpful, so I've added some more tests and a bit better error reporting.

## Test Plan

I've updated and added to the existing set of specs for the local-cli/link/pods implementation, and added a new example Podspec. I've also manually tested this version against a react native project by running `link` and `unlink`, both with a valid and invalid Podspec. Running with an invalid podspec now yields this:

> rnpm-install info Linking react-native-video android dependency
> rnpm-install info Android module react-native-video has been successfully linked
> rnpm-install info Linking react-native-video ios dependency
> rnpm-install info Adding podspec for react-native-video to testproject
> rnpm-install info Couldn't find "# Add new pods below this line" in Podfile, will try to find target...
> rnpm-install ERR! Something went wrong while linking. Error: Couldn't find "# Add new pods below this line" or "target 'testproject' do" in Podfile, unable to continue
> Please file an issue here: https://github.com/facebook/react-native/issues
> 

## Release Notes

[IOS] [BUGFIX] [cli] - Improved error messages for working with Podspecs that don't match the expected format

### CODE REVIEW

**Comment by erlendfh** [comment]
Maybe @Kureev or @grabbou would be willing to take a look at this Cocoapods-related PR?

**Comment by Kureev** [comment]
This PR is definitely a step into right direction, although I'm wondering if `MARKER_TEXT` is required at all. I'd rather detect the last pod in the list and append new one afterwards. Is it something other people would like to consider?

**Comment by erlendfh** [comment]
@Kureev Thanks for taking a look at this! Just to make a couple of clarifications:
- The original PR already implements looking for `target '${projectName}' do` and then adds the pod below that line
- MARKER_TEXT is not something I've introduced, it was already in the original PR for Podspec support. MARKER_TEXT will only be used if the above method fails, i.e. for more complex Podfile configurations. All I've done is add a few tests and ensure that a more informative error message is displayed in the npm log.

**Comment by erlendfh** [comment]
@Kureev any chance of getting this PR merged?

**Comment by cpojer** [comment]
This PR has been open for a long time without resolution. We just moved this code to https://github.com/react-native-community/react-native-cli so please submit your PR there.

**Pull request closed without merging**
