### PR TITLE
DatePickerIOS add initialDate option

### PR DESCRIPTION
**Pull request by jgibbons**
This PR addresses a bug with DatePickerIOS (#8169, #4787) where month/day/year go out of sync when quickly changing values. By adding an initialDate option the component will not go out of sync. Granted this isn't a perfect solution, but does provide a workaround for a fairly serious bug provided the date does not need to be updated after initialization.

**Test plan (required)**
Using the changes in our app OpenSports.

### CODE REVIEW

**Comment by JakeRawr** [comment]
Hey @jgibbons Thank you for the fix!

Do we pass the same value date for the initialDate prop as the date prop?
like the example below?

```
class DatePickerBug extends Component {
  constructor(props) {
    super(props);
    this.state = {
      date: new Date()
    };
  }

  onDateChange(date) {
    this.setState({
      date: date
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>{this.state.date.toString()}</Text>
        <DatePickerIOS
          date={this.state.date}
          initialDate:{this.state.date}
          mode="date"
          onDateChange={(date) => this.onDateChange(date)}
        />
      </View>
    );
  }
}
```

**Comment by jgibbons** [comment]
Hey @JakeRawr, just pass initialDate. I also had to comment out one line  (https://github.com/OpenSports/react-native/commit/b992926404739d526e6b8c03fab6dc0e7cfdd644#diff-bb7f9a35dd5ae2a59fcff0292caf41f3R37) for the solution to work. I'm sure there is an elegant way to make it backwards compatible and hopefully others will chime in, but I can confirm that then it will work.

``
<DatePickerIOS
                initialDate={date}
                mode={'date'}
                onDateChange={ (date) => this.onDateChange(date)}
              />

**Comment by JakeRawr** [comment]
Ah, I see. So the idea is that every time data picker is opened, instead of resuming where the date is currently at, it always start from the initial date. 

Thanks, I'll give this a try and report feedbacks (if any)

**Comment by jgibbons** [comment]
@JakeRawr Exactly. Please confirm that this technique is working for you.

**Pull request closed without merging**
