### PR TITLE
chore: update RNTester Cocoapods to 1.13

### PR DESCRIPTION
**Pull request by okwasniewski**
## Summary:

This PR updates the internal version of cocoapods to 1.13, template already uses this version. I've also removed the root folder Gemfile as it's not necessary anymore.  

## Changelog:

[INTERNAL] [CHANGED] - Update RNTester Cocoapods to 1.13

## Test Plan:

Check if cocoapods installs correctly by running: 

1. `bundle install`
2. `bundle exec pod install`

### CODE REVIEW

**Comment by okwasniewski** [comment]
When I removed the root Gemfile CI failed so it looks like its still needed

**Comment by cipolleschi** [comment]
Yeah, it's not a simple removal. It should go, but there are other cleanup that are required to remove it properly!

**Comment by okwasniewski** [comment]
@cipolleschi Can we merge it without removing the root one?

**Comment by cipolleschi** [comment]
yes sure. I thought I had already imported this one. Sorry.

**Pull request closed without merging**
