### PR TITLE
Remove unused react-addons dependencies

### PR DESCRIPTION
**Pull request by janicduplessis**
We don't export addons anymore so we can remove those.

cc @bvaughn

### CODE REVIEW

**Comment by ide** [comment]
@hramos could you please help shepherd this commit through FB internally? (it removes some package.json deps)

**Comment by ide** [comment]
I added this to 0.43-stable and 0.44-stable as well (both have no more references to React add-ons in the code).

**Comment by hramos** [comment]
cc @ericvicenti current oncall

**Comment by ericvicenti** [comment]
Actually I think we can land normally if we are just removing dependencies

**Comment by chirag04** [comment]
i was about to send a PR for this. lol. @ericvicenti can we ship?

**Pull request closed without merging**
