### PR TITLE
[Cocoapods] min_ios_version_supported -> min_supported_versions

### PR DESCRIPTION
**Pull request by Saadnajmi**
## Summary:

One of the most common diffs we have in React Native macOS is simply extending the `platforms` key Inside every pod spec to include macOS. React Native tvOS does the same to add tvOS. In the future, React Native may support visionOS, at which point we do the same thing again. Let's define a `min_supported_versions` hash that can be overridden at one place that is extensible to more platforms, instead of just specifying `min_ios_version_supported`.

Note: In doing this change, I have set it that `React-Hermes.podspec` doesn't build for macOS anymore. I think this is safe, since anyone using Hermes on macOS was probably using React Native macOS where we already have a diff to add macOS back?

## Changelog:

[IOS] [CHANGED] - Add min_supported_versions helper to cocoa pods scripts

## Test Plan:

CI should pass.

### CODE REVIEW

**Comment by dmytrorykun** [comment]
@Saadnajmi could you please rebase on the latest main, as there were unrelated CircleCI failures recently.

**Comment by Saadnajmi** [comment]
> @Saadnajmi could you please rebase on the latest main, as there were unrelated CircleCI failures recently.

Uuuh, I seem to have messed up the branch a bit with the rebate, I'll fix shortly

**Comment by dmytrorykun** [comment]
@Saadnajmi there are some Ruby Test failures. Reproducible locally with
```
cd packages/react-native/scripts
sh run_ruby_tests.sh
```
Could you please fix them?

**Comment by Saadnajmi** [comment]
@dmytrorykun looks like we're good now!

**Comment by bingDBdu** [comment]
image
image
I don't think it can find the `min_supported_versions` 

What should I do more fetch the value from cocoapods helper?

**Comment by Saadnajmi** [comment]
@bingDBdu Without knowing much of your setup, I see you're using cocoapods 1.15.0, which I think is actually not compatible with React Native at the moment

**Pull request closed without merging**
