### PR TITLE
[Packager] Fix DependencyResolver to support ES6 multiline imports

### LINKED ISSUE #1939: [Packager] DependencyResolver fails to handle ES6 modules import statements with new lines
We found out that while the packager does its module wrapping thing for lines like this:
```js
import theDefault, { named1, named2 } from 'src/mylib';
```
It fails to do the same for multi line imports:
```js
import theDefault, { 
  named1, 
  named2 
} from 'src/mylib';
```
We've tracked done the issue to a [faulty regular expression in replacePatterns.js](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/replacePatterns.js#L12)

You can see various import statements with the problematic regular expression [here](http://regexr.com/3bc8m)

We've figure out a better regular expression (you can play around with it [here](http://regexr.com/3bd3s)), and I'll open a pull request soon with the fix + tests.

### PR DESCRIPTION
**Pull request by shlomiatar**
*This is a PR to fix #1939 (DependencyResolver fails to handle ES6 modules import statements with new lines)*

**This PR includes:**
- A fix to the problematic regular expression
- Updated tests that support the new line style.

**Summary:**
We found out that while the packager does its module wrapping thing for lines like this:
```js
import theDefault, { named1, named2 } from 'src/mylib';
```
It fails to do the same for multi line imports:
```js
import theDefault, { 
  named1, 
  named2 
} from 'src/mylib';
```
We've tracked done the issue to a [faulty regular expression in replacePatterns.js](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/replacePatterns.js#L12)

You can see various import statements with the problematic regular expression [here](http://regexr.com/3bc8m)

We've figure out a better regular expression (you can play around with it [here](http://regexr.com/3bd3s))

### CODE REVIEW

**Comment by ide** [comment]
The pattern should be something like [\s\S] instead of [^;].

Also could you squash your commits?

**Comment by shlomiatar** [comment]
@ide,
Squashed my commits, and updated the regular expression to:
```js
exports.IMPORT_RE = /(\bimport\s+(?:\s*?|[\s\S]+?from\s+?))(['"])([^'"]+)(\2)/g;
```
to support both `import "module"` and `import {coolness} from "module"` cases. 
You can check it out here: 
http://regexr.com/3bckg

**Comment by ide** [comment]
this is a little simpler:
`/(\bimport\s+(?:[\s\S]+?from\s+)??)(['"])([^'"]+)(\2)/g`

**Comment by ide** [comment]
This looks good to me. Thanks for the comprehensive tests too.

**Comment by ide** [comment]
I realized it'd be easy to filter out some more invalid statements... take a look at http://regexr.com/3bd3s

**Comment by sahrens** [comment]
How does this relate to #1993?

**Comment by ide** [comment]
#1993 adds babel support for converting import statements to require calls but the packager builds its dependency graph before babel runs, so it needs to grep for both require and import. The regex it was using to look for import statements didn't match a couple of valid cases and with this PR now it does.

**Comment by shlomiatar** [comment]
@ide, oh cool! :)
Updated the PR with the latest regex + updated the PR comment.

**Comment by ms88privat** [comment]
This is so crucial in combination with "try restarting the packager" error message. I have multiple other imports, which are working fine with multiline statements already... 

Looking forward :+1:

**Comment by despairblue** [comment]
This would be super helpful. Took me days to figure out that the new lines where the culprit, I just thought react-native was using a broken babel version or something like that. I kept (and keep) fixing it like this:

```javascript
import theDefault from 'src/mylib'
const { 
  named1, 
  named2 
} = theDefault
```

**Comment by skevy** [comment]
I noticed when converting my project back to just the normal packager (and no longer use react-native-webpack-server) I ran into this issue. I also ran into the issue with things like `export * from './videos'` wouldn't work either. So the updated regex here I think should also include the keyword "export"...as `export [blank] from [blank]` is just like importing. I fixed it locally by changing the regex in this PR to:

`/(\b(?:import|export)\s+(?:[^'"]+\s+from\s+)??)(['"])([^'"]+)(\2)/g`.

Thoughts?

**Comment by ide** [comment]
@skevy seems good. It's always a bit frustrating when other tooling lags behind babel.

**Comment by skevy** [comment]
@shlomiatar what do you think about the updated regex?

**Comment by jeanregisser** [comment]
I had added `export from` syntax in #1975.
It also has tests for it.
We can probably combine those 2 or merge separately.

**Comment by sahrens** [comment]
@amasad: want to import this?

**Comment by amasad** [comment]
Sorry this took so long, I was out for a while.

We're actually in the process of moving the packager to it's own github repo and we'll be able to accept contributions like this much faster (we can just use the Github merge button). I'm hoping we can release it some time this week.

**Comment by skevy** [comment]
@amasad @sahrens any updates on moving the packager out to it's own repo? Would love to see this merged.

**Comment by joevp** [comment]
Can this happen soon?

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by ide** [comment]
What's the status of this import?

**Comment by martinbigio** [comment]
it should have been merged 7 days ago

**Comment by ide** [comment]
@martinbigio Yep, I see it in the commit history now! Closing this PR since it has been merged into master :D

**Comment by brentvatne** [comment]
:tada:

**Pull request closed without merging**
