### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by king6cong**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @michalgr to be a potential reviewer.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hramos** [comment]
@facebook-github-bot import

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
I cannot do that @hramos, because @king6cong does not have an active CLA on file.

**Comment by facebook-github-bot-0** [comment]
I cannot do that @hramos, because @king6cong does not have an active CLA on file.

**Comment by king6cong** [comment]
CLA signed up

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3771663) to review internal test results.

**Pull request closed without merging**
