### PR TITLE
Add more autogenerated documentation to the whitelist

### PR DESCRIPTION
**Pull request by lacker**
I went through and checked what React Native exports that we don't have any autogen docs for, and added the missing stuff into the whitelist. The extra docs seem useful.

Still not reference-documented because docgen chokes:
AppStateIOS
ART
Keyboard
LinkingIOS
Platform
RecyclerViewBackedScrollView
Touchable
UIManager

I also fixed up a bit of alphabetical order

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @sahrens to be potential reviewers.

**Comment by caabernathy** [comment]
This probably solves #8202 in a non automatic way for now. Looks good.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/825463540887367/int_phab) to review.

**Pull request closed without merging**
