### PR TITLE
add flow check to windows ci

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
add flow check to windows ci
## Test Plan
none
## Related PRs
none
## Release Notes
 [GENERAL] [INTERNAL] [CI] - add flow check to windows ci.

### CODE REVIEW

**Comment by hramos** [comment]
Should we run Flow for iOS files as well? Since this is only JavaScript, I expect it to work on Windows.

**Comment by TheSavior** [comment]
Is it even worth running this? Since it runs on Circle, running it on Appveyor is essentially just testing Flow itself to make sure it doesn't have weird windows specific bugs. It doesn't seem like it really tells us anything extra about our codebase.

**Comment by gengjiawen** [comment]
@TheSavior Yes, because now flow is broken on windows, if we have this, we can find this earlier see https://github.com/facebook/react-native/issues/21311.

@hramos Yes, I think we can add it. My first thought is that iOS check maybe redundant on windows platform.

**Comment by TheSavior** [comment]
Flow is broken on Windows!? :O

**Comment by gengjiawen** [comment]
If there is no future question, I think this can be merged.

**Comment by gengjiawen** [comment]
@hramos Is anyone working on the flow issue in windows ?

**Comment by hramos** [comment]
This is not something I am tracking closely at the time. We should definitely merge this once #21311 is fixed, though, to prevent regressions as you suggested.

**Comment by hramos** [comment]
Appveyor build failed with:

```
$ flow check --flowconfig-name .flowconfig.android
C:\projects\react-native\node_modules\flow-bin\cli.js:17
  throw new Error('Platform not supported.');
  ^
```

**Comment by gengjiawen** [comment]
After swith to x64 platform, here is the new error:
```console
$ flow check --flowconfig-name .flowconfig.android
Error -------------------------------------------------------------------- node_modules/invariant/invariant.js.flow:4:14
Unclear type. Using `any`, `Object`, or `Function` types is not safe! (`unclear-type`)
   4|   condition: any,
                   ^^^
Error -------------------------------------------------------------------- node_modules/invariant/invariant.js.flow:6:18
Unclear type. Using `any`, `Object`, or `Function` types is not safe! (`unclear-type`)
   6|   ...args: Array<any>
                       ^^^
```

**Comment by jamesisaac** [comment]
It's complaining about this file: https://github.com/zertosh/invariant/blob/master/invariant.js.flow

Imo that file should be erroring... it's annotated Flow strict mode, but it's using `any` types, which correctly triggers the `unclear-type` rule.  So the bug seems to me more like why does that file not error on Linux?

I can't see anything in RN's flowconfig which indicates that file is meant to be ignored.  So don't think this is to do with normalizing file paths like the previous errors were.

**Comment by jamesisaac** [comment]
@gengjiawen Maybe this explains it: https://github.com/facebook/flow/commit/ba425e403cf40e9232aab68aff96b8e3fca192b0

**Comment by gengjiawen** [comment]
> @gengjiawen Maybe this explains it: [facebook/flow@ba425e4](https://github.com/facebook/flow/commit/ba425e403cf40e9232aab68aff96b8e3fca192b0)

Let's wait for next release :)

**Comment by cpojer** [comment]
@gengjiawen the latest Flow version should now be deployed on master. Can you rebase and make this PR pass on Windows? Then we can finally land and enable it!

**Comment by gengjiawen** [comment]
> @gengjiawen the latest Flow version should now be deployed on master. Can you rebase and make this PR pass on Windows? Then we can finally land and enable it!

Done :)

**Comment by hramos** [comment]
🎉 It worked! Landing.

**Pull request closed without merging**
