### PR TITLE
Sync with Resolver/polyfills/require.js

### PR DESCRIPTION
**Pull request by jetzhliu**
I don't know which version is better, but it should sync with `Resolver/polyfills/require.js: 168`
```js
    // keep args in sync with with defineModuleCode in
    // packager/react-packager/src/Resolver/index.js
    // and packager/react-packager/src/ModuleGraph/worker.js
    factory(global, require, moduleObject, exports, dependencyMap);
```

### CODE REVIEW

**Comment by ericvicenti** [comment]
Hi, can you please provide more details about the change, why it is needed, and what you have done to test it and avoid breaking things?

**Comment by jetzhliu** [comment]
@ericvicenti 
I have update the test spec.
`ModuleGraph` is Not in used yet, but the code it yield is mismatch with current version of `__d`, the detail is current use `__d(function(global, require, module, exports) {/**/}, moduleName)`, while `ModuleGraph` use `__d(function(require, module, global, exports) {/**/}, moduleName)`, the order of params of module definion mismatch.
Relative code:

> Resolver/polyfills/require.js: 168
> Resolver/index.js: 245
> ModuleGraph/worker/transform-module.js: 38

**Comment by jetzhliu** [comment]
this PR jest change the order of definition's params.

**Comment by davidaurelio** [comment]
Good catch, thank you. I’m happy to merge this, but we need you to sign the CLA.

**Pull request closed without merging**
