### PR TITLE
Fix race-condition when loading local images

### LINKED ISSUE #29364: Missing request token for request: <NSURLRequest: 0x60000253e5a0> { URL: file://
## Description
I just upgraded to RN 0.63.0 and all fine, but only for upload using axios, i get 

```
Missing request token for request: <NSURLRequest: 0x60000253e5a0> { URL: file:
```

image

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 163.19 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Here is my code snippet and that gives me error

```
  const cleanURL = body.imageData.uri.replace("file://", "");
  const data = new FormData();
  let fileName = body.imageData.fileName ? body.imageData.fileName : moment().unix()+'.jpg'
  data.append('file', {
    uri: cleanURL,
    name: fileName,
    type: body.imageData.type
  });
  data.append('fileName', fileName)
  return axiosclient.post(
    '/upload,
    data,
    {
      headers: {
        "content-type": "multipart/form-data"
      }
    }
  ).then(res => {
   
  }).catch(err => {
    
  })
```

## Expected Results
Should upload file, it was fine in 0.62.2

### PR DESCRIPTION
**Pull request by paddlefish**
In local images, the callback is called inline, and so requestToken is always nil at the time the block is executed. In this case, the requestToken is irrelevant because the task is completed before it could be canceled. So initializing it with a do-nothing block satisfies the delegate.

It could also be a race condition even if the block is called on another thread, and so I also add @synchronized to protect against that race as well.

Fixes #29364 "Missing request token for request: <NSURLRequest: 0x60000253e5a0> { URL: file://"

## Summary

Loading a local image will fail with an error "Missing request token for request:"

## Changelog

[iOS] [Fixed] - Fix error thrown in RCTImageLoader.mm when accessing a file:// url

## Test Plan

I have a react-native app which loads images from the camera roll using `react-native-image-picker`. When I added `maxWidth: 480,  maxHeight: 480,` parameters this error started appearing.  This code commit fixes that issue.

### CODE REVIEW

**Comment by paddlefish** [comment]
I agreed to the CLA

**Comment by marsbergen** [comment]
Any plans when this PR will be part of the next patch release?

**Review by alshamiri5 — APPROVED** [review]

**Review by ivanzhang2 — APPROVED** [review]

**Comment by danilobuerger** [comment]
@shergin could you please review this? its impossible to upload local images anymore in the current rn version...

**Comment by barunprasad** [comment]
Any updates on this PR? Have been waiting for this to be merged for quite some time now.

**Comment by devkrkanhaiya** [comment]
in 
node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm   file

 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                               size:(CGSize)size
                                              scale:(CGFloat)scale
                                         resizeMode:(RCTResizeMode)resizeMode
                                    progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                                 partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                                  completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
{
  UIImage *image = RCTImageFromLocalAssetURL(imageURL);
  if (image) {
    if (progressHandler) {
      progressHandler(1, 1);
    }
    completionHandler(nil, image);
  } else {
    NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
    RCTLogWarn(@"%@", message);
    completionHandler(RCTErrorWithMessage(message), nil);
  }
  
  return nil;
}

**With**



 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                           size:(CGSize)size
                                          scale:(CGFloat)scale
                                     resizeMode:(RCTResizeMode)resizeMode
                                progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                             partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                              completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
 {
   __block auto cancelled = std::make_shared<std::atomic<bool>>(false);
   RCTExecuteOnMainQueue(^{
     if (cancelled->load()) {
       return;
     }

     UIImage *image = RCTImageFromLocalAssetURL(imageURL);
     if (image) {
       if (progressHandler) {
         progressHandler(1, 1);
       }
       completionHandler(nil, image);
     } else {
       NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
       RCTLogWarn(@"%@", message);
       completionHandler(RCTErrorWithMessage(message), nil);
     }
   });

   return ^{
     cancelled->store(true);
   };
 }

This..

Like and Love , if it work 👍

**Comment by devkrkanhaiya** [comment]
in 
node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm   file

 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                               size:(CGSize)size
                                              scale:(CGFloat)scale
                                         resizeMode:(RCTResizeMode)resizeMode
                                    progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                                 partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                                  completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
{
  UIImage *image = RCTImageFromLocalAssetURL(imageURL);
  if (image) {
    if (progressHandler) {
      progressHandler(1, 1);
    }
    completionHandler(nil, image);
  } else {
    NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
    RCTLogWarn(@"%@", message);
    completionHandler(RCTErrorWithMessage(message), nil);
  }
  
  return nil;
}

**With**



 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                           size:(CGSize)size
                                          scale:(CGFloat)scale
                                     resizeMode:(RCTResizeMode)resizeMode
                                progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                             partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                              completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
 {
   __block auto cancelled = std::make_shared<std::atomic<bool>>(false);
   RCTExecuteOnMainQueue(^{
     if (cancelled->load()) {
       return;
     }

     UIImage *image = RCTImageFromLocalAssetURL(imageURL);
     if (image) {
       if (progressHandler) {
         progressHandler(1, 1);
       }
       completionHandler(nil, image);
     } else {
       NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
       RCTLogWarn(@"%@", message);
       completionHandler(RCTErrorWithMessage(message), nil);
     }
   });

   return ^{
     cancelled->store(true);
   };
 }

This..

Like and Love , if it work 👍

**Comment by vincentjames501** [comment]
@shergin we hate to keep bothering you! This is affecting many folks (I see at least 5 different open tickets relating to this with comments from hundreds of folks). Seems like this is a simple fix/PR? Uploading images is completely broken on iOS via fetch and many applications depend on this functionality (we can't release our app until this one gets merged). Appreciate all your hard work!

**Comment by fairlycasual** [comment]
Any updates on timing for this being merged and released? We are midway through upgrading to 0.63.2 and this has become a blocker for us. We are not super comfortable with any of the work arounds presented, unless you can convince us of the stability for pegging package.json to use the nightly builds. 

We appreciate all of your help and hard work on this, and many more issues!

**Comment by wakogitcl** [comment]
v.0.63.3 is out and this PR hasn't been merged yet.

**Comment by ThukuWakogi** [comment]
v0.63.3 is out and this hasn't been merged yet.

**Comment by honzajerabek** [comment]
@ThukuWakogi some ppl already reported that 0.63.3 fixes this issue. Haven’t tried it but there’s a chance 🤞

**Comment by AbleCable1** [comment]
Version 0.63.3 does not fix this issue, but this PR does. Would be good to get this merged soon. Currently we have to always manually modify the correct files in node_modules before building. It would be great to not have to do that every time

**Comment by fyujn** [comment]
Any Updates on this?

**Comment by paddlefish** [comment]
This should be closed. The issue was fixed another way

**Pull request closed without merging**
