### PR TITLE
fix Android CI

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

This PR fixes Android CI.

## Changelog

[Android] [Fixed] - fix Android CI

## Test Plan

Android CI is green again

### CODE REVIEW

**Comment by dulmandakh** [comment]
@mdvacca you're welcome. I thought that US developers are asleep, thanks.

**Comment by dulmandakh** [comment]
@mdvacca could you please help land the PR

**Comment by mdvacca** [comment]
Trying again

**Comment by mdvacca** [comment]
This is failing with the following error:

```
The rule .../react-native-github/ReactAndroid/src/main/third-party/java/testing-support-lib:monitor-binary could not be found.
Please check the spelling and whether it exists in .../react-native-github/ReactAndroid/src/main/third-party/java/testing-support-lib/BUCK.
This error happened while trying to get dependency '.../react-native-github/ReactAndroid/src/main/third-party/java/testing-support-lib:monitor-binary' of target '.../react-native-github/ReactAndroid/src/main/third-party/java/testing-support-lib:runner'
```

**Comment by dulmandakh** [comment]
@mdvacca please try again 👍

**Comment by mdvacca** [comment]
I received the same error when landing

```
The rule .../react-native-github/ReactAndroid/src/main/third-party/java/testing-support-lib:monitor-binary could not be found.
Please check the spelling and whether it exists in .../react-native-github/ReactAndroid/src/main/third-party/java/testing-support-lib/BUCK.
```

**Comment by dulmandakh** [comment]
Could you please share contents of react-native-github/ReactAndroid/src/main/third-party/java/testing-support-lib/BUCK file

**Comment by dulmandakh** [comment]
@mdvacca thank you

**Pull request closed without merging**
