### PR TITLE
how to find and stop process using port on windows

### PR DESCRIPTION
**Pull request by bbodenmiller**
Improve troubleshooting section to include details on how to find and stop process using port on Windows.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @lloydnye to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
Thanks for adding this! LGTM

**Comment by facebook-github-bot-1** [comment]
@bbodenmiller updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9997/files/8cf8634118895052cf27bc857aa3ea2f8c3bb16f..aa7428ff9b446cb8d0178cdf4444d0a018b0ed98)

**Pull request closed without merging**
