### PR TITLE
Fix inverted FlatList for Android: add perspective transform

### PR DESCRIPTION
**Pull request by bartolkaruza**
On one of our test phones, a Huawei P10 VTR-L09, running Android 7.0 any rotate or scale animations through transforms are not working, unless `{"perspective": 1}` is added in the transforms array. I found the perspective solution here https://github.com/facebook/react-native/issues/13522 .

The new `inverted` property for `FlatList` relies on a scaleX/scaleY transform. Because this transform does not work on some Android devices, the FlatList is not displayed at all on those devices. This fix just adds the extra perspective array element. The result is a correctly displayed FlatList when `inverted` is set to `true`.

## Test Plan

Tested this on inverted `FlatList` on Android and iOS, on real devices. iOS is unaffected by the addition. Android now displays the `FlatList` correctly.

Minimal gist for testing: https://gist.github.com/bartolkaruza/87ef49d1b2d0227782739584b110722b

Minimal gist showing the View transform with scaleY issue:
https://gist.github.com/bartolkaruza/42bb9f9d63baaaebb48fc493c8127e1a

### CODE REVIEW

**Comment by janicduplessis** [comment]
@bartolkaruza Thanks for figuring out a fix for this issue. I think a better fix would be to always set perspective: 1 for all transforms in the native code, this way it would completely fix the bug instead of just for FlatList.

I think we could always call view.setCameraDistance with whatever camera distance value `perspective: 1` gives if no perspective transform is specified. I was thinking just adding an else branch in that code https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java#L195

**Comment by bartolkaruza** [comment]
I agree that would be a much better fix. I can look into this today if you are not implementing it @janicduplessis ?

**Comment by Feng999** [comment]
Seems to be same problem with #14462

**Comment by janicduplessis** [comment]
@bartolkaruza I don't have a Huawei device so if you could look into it it would be great.

**Comment by bartolkaruza** [comment]
I opened a new PR for the fix in native code https://github.com/facebook/react-native/pull/14646

**Comment by yury** [comment]
We have Huawei device and `{"perspective": 1}` doesn't help :(
Works only with deprecated scaleX/Y.

**Comment by bartolkaruza** [comment]
@yury Have you tried `"perspective": 1280`, which I used in the proposed fix at https://github.com/facebook/react-native/pull/14646? Both are working on a P9 Huawei device for me.

**Comment by yury** [comment]
@bartolkaruza I didn't try 1280, but I think it is not good solution either - it is dependant on screen density.
> The distance is expressed in "depth pixels." The default distance depends on the screen density. For instance, on a medium density display, the default distance is 1280. On a high density display, the default distance is 1920.
[from docs](https://developer.android.com/reference/android/view/View.html#setCameraDistance(float))

**Comment by bartolkaruza** [comment]
The perspective value is multiplied in native code. So 1280 * density is the actual applied value. By setting 1280 you set it to the default value for all densities respectively.

**Comment by yury** [comment]
@bartolkaruza will try 1280 later today and let you know about results.

**Comment by yury** [comment]
@bartolkaruza `1280` works

**Pull request closed without merging**
