### PR TITLE
correct flow types

### PR DESCRIPTION
**Pull request by nmn**
The function should have optional arguments, but not nullable types.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @davidaurelio to be a potential reviewer.

**Comment by davidaurelio** [comment]
yup, thanks!

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1116560478385236/int_phab) to review.

**Pull request closed without merging**
