### PR TITLE
Made npm deployment to be independent of git tags cache

### PR DESCRIPTION
**Pull request by bestander**
Fixes npm deployment script as in https://circleci.com/gh/facebook/react-native/6745.

Example situation:
- admin is ready to release 0.26.0
- admin adds tag v0.26.0 and pushes to origin
- Circle CI build fails because of code error
- admin cherry-picks a fix and tags v0.26.0 again and pushes to origin
- Circle does not update local tag v0.26.0 because it already has it cached, compiles the code but fails to deploy to npm because v0.26.0 is not on branch HEAD from Circle point of view

The previous version of the script was checking the tags on current commit as well but it used the local branch tags.
This change fetches tags from `origin` fresh and allows us to redeploy the same version multiple times.

Test Plan:
- tested in prod
https://circleci.com/gh/facebook/react-native/6754
https://circleci.com/gh/facebook/react-native/6877

The script got big enough to justify for some unit tests, I will add tests honestly the next time I need to change the script.
Right testing environment for such scripts is not configured.

### CODE REVIEW

**Comment by bestander** [comment]
Travis master is broken now, can be ignored

**Comment by facebook-github-bot-7** [comment]
@bestander updated the pull request.

**Comment by mkonicek** [comment]
Super clear summary and love the comments in the code!

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1029266157150093/int_phab) to review.

**Comment by grabbou** [comment]
Amazing work @bestander!

**Pull request closed without merging**
