### PR TITLE
[NavigationExperimental] Kill NavigationAnimatedView

### PR DESCRIPTION
**Pull request by jmurzy**
NavigationAnimatedView is deprecated. Use NavigationTransitioner.

As discussed in #8262, #8189.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @ericvicenti to be potential reviewers.

**Comment by ide** [comment]
@ericvicenti can you take care of this? I'm thinking there might be callers of NavigationAnimatedView still within FB-internal code and deleting the file will break internal apps/tests.

**Comment by ericvicenti** [comment]
@ide, you read my mind!

**Comment by ericvicenti** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1605549233074971/int_phab) to review.

**Comment by jmurzy** [comment]
@ericvicenti Also, there is a [bug](https://github.com/facebook/react-native/commit/7db7f78dc7d2b85843707f75565bcfcb538e8e51#commitcomment-17945401) in `NavigationTransitioner` that needs to be fixed before we completely get rid of `NavigationAnimatedView`.

/cc @hedgerwang 

🍺

**Comment by tpisto** [comment]
NavigationTransitioner is very very slow compared to previous NavigationAnimatedView. With NavigationAnimatedView the transition was instant, but now with NavigationTransitioner the same change takes like 3 seconds.

**Comment by ericvicenti** [comment]
@tpisto, I don't think NavigationTransitioner is inherently much slower, but it depends on how it is used. Could you post a code snippet that demonstrates how slow it is now?

**Comment by tpisto** [comment]
Hi! Thank you for quick reply. I am using this solution:

https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/blob/0.27/app/containers/AppContainer.js

But before I used AnimatedView. And with AnimatedView animations go like this:

screen recording 2016-07-23 at 01 31 pm

After updating to 0.30.0 and switching to Transitioner the animations go like this (not that I click the arrow down when the cursor moves slightly - so making many seconds the transition to happen):

screen recording 2016-07-23 at 12 51 pm

There are no any additional changes to code - just 0.29.2 -> 0.30.0 and AnimatedView -> Transitioner. (And Transitioner seems to need render instead of renderScene)

**Comment by arronmabrey** [comment]
@tpisto Is this still an issue you're facing or were you able to figure it out? Debating on upgrading to 0.30.0 but might hold off if you're still seeing this issue.

**Pull request closed without merging**
