### PR TITLE
Default providesModuleNodeModules set in packager and exports it

### PR DESCRIPTION
**Pull request by yuanyan**
We use @providesModule in our project, it useful for the user.

### CODE REVIEW

**Comment by ide** [comment]
@amasad and @martinbigio are you planning to expose this option?

**Comment by martinbigio** [comment]
Hmm we kind of wanted the packager to have as lest config as possible. @amasad is this something that has already came up before?

**Comment by facebook-github-bot-8** [comment]
@amasad would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
Based on the comment above:

> Hmm we kind of wanted the packager to have as lest config as possible. @amasad is this something that has already came up before?

And the fact that @amasad doesn't work on React Native anymore, I'll close this PR. I'm going through all open PRs making sure each of them is either being actively worked on or closed, to keep the number of open PRs under control. Thanks for the contribution and hope you'll keep contributing to React Native in the future.

**Comment by mkonicek** [comment]
As a side note, I think we want to move away from Haste (`@providesModule`) actually. Managing two different module systems in one project has proven extremely difficult recently.

**Pull request closed without merging**
