### PR TITLE
remove cxx TM autolinking

### PR DESCRIPTION
**Pull request by philIip**
Summary:
Changelog: [iOS][Android][Breaking]

this was a meaningful exploration, but since we have support in TM for jsi runtime access and that's been widely advertised and accepted, let's get rid of this. it's a bit hacky and hard to use (shown by no one using it), so i want to stop any possibility of its usage.

if interested in accessing jsi::Runtime via a native module, please consider the following options:
- [Android] BindingsInstaller: https://github.com/facebook/react-native/pull/44526
- [iOS] RCTTurboModuleWithJSIBindings: https://github.com/facebook/react-native/pull/44486
- C++ TurboModules (no autolinking): https://github.com/reactwg/react-native-new-architecture/blob/main/docs/turbo-modules-xplat.md

### CODE REVIEW

**Comment by kraenhansen** [comment]
For what it's worth, I actually liked the simplicity of this API as it didn't rely on any React Native auto-linking / code generation to "pick up" and call into it. All you needed was some C++ code calling into this function "on load". Looking at https://github.com/search?q=registerCxxModuleToGlobalModuleMap&type=code it also seems other notable packages were toying around with it) and I had [a branch of `realm`](https://github.com/realm/realm-js/pull/6718/files#diff-4c2e32ef8516d65b7620f553d6358b058c5424d8bc65900acd9d9f48dc6d1c71R35) where I was also contemplating using it.

Although I understand the desire to avoid fragmentation, I'm a bit sad to see it go 😞

**Comment by hsjoberg** [comment]
> but since we have support in TM for jsi runtime access and that's been widely advertised and accepted, let's get rid of this. 

What does this mean?

There seems to be a couple of projects out in the wild that actually relies on this, like https://github.com/mrousavy/react-native-mmkv/blob/12c051704e0db363f9f63d2b30dbf291151f90d4/package/ios/MmkvOnLoad.mm#L18, cc @mrousavy), and I was going to make my own C++ TM using this method. Instead of using this, what would be the recommended approach?

**Comment by mrousavy** [comment]
woah - I use this in a lot of libraries! I use this in react-native-mmkv, nitro (the upcoming "Nitro Modules" library), and a few others that fully rely on this.

Any chance we can keep this?

**Comment by mrousavy** [comment]
I need access to `jsi::Runtime` **and** `std::shared_ptr<CallInvoker>` in my modules. I don't think the other APIs you suggested have this feature.

Also, Nitro is a CxxTurboModule (both on iOS and Android) that does not use CodeGen - this means that on Android, it is **not built by CodeGen's CMake project**, but instead built by it's own `build.gradle`'s `externalNativeBuild` spec. 
This would completely break that flow..

**Comment by philIip** [comment]
sorry all i apologize, i did not realize that there was actually interest in using this, i thought it was so unwieldy that no one would understand how to use it! but this is a good opportunity now to see if we can come up with a more formalized replacement.

the main reason i wanted to get rid of it is because it was extremely hacky, didn't work in it's original form without updating the compiler, and @mrousavy had to add that +load in order to get things to actually work. i don't think he even used the macro. (also apologies, i didn't know you actually committed to using this, thought it was just prototyping!). and i was skeptical it would lead us to a place where we would find a safer autolinking solution.

since TM now has the installJSIBindings flow, i thought that we can use TM as a forwarding layer to a shared C++ layer which kinda can fulfill the role of reusing shared code. but i understand that we can't leverage the lifecycle management of TM within a pure C++ environment.

let me follow up to these comments to see if we can reintroduce this in a form that is more stable.

**Comment by philIip** [comment]
> I need access to `jsi::Runtime` **and** `std::shared_ptr<CallInvoker>` in my modules. I don't think the other APIs you suggested have this feature.
> 
> Also, Nitro is a CxxTurboModule (both on iOS and Android) that does not use CodeGen - this means that on Android, it is **not built by CodeGen's CMake project**, but instead built by it's own `build.gradle`'s `externalNativeBuild` spec.
> 
> This would completely break that flow, and I don't think there's any alternatives?..

thanks for surfacing this marc. i see the callsite in +load on iOS. how does the registration work on android? do you actually use the macro, or just the C++ methods like registerCxxModuleToGlobalModuleMap?

**Comment by philIip** [comment]
> Feels like this could've been a discussion. Some developers were already building on top of this. For instance we had a C++ only TurboModule in the works for create-react-native-library.

yes, in hindsight that appears to be the case! i'm sorry for the churn. do you have examples of how you were using the API to register your modules?

**Comment by mrousavy** [comment]
No worries thanks @philIip !! :)

> do you actually use the macro, or just the C++ methods like registerCxxModuleToGlobalModuleMap? how did you register in Android?

Yea on iOS I use +load, but on Android I have to create a dummy Java package which does nothing except loading the C++ library. This calls JNI_OnLoad, which then calls the register... func, same way as on iOS.

I'm not so sure about the installJSIBindings - does this also contain the CallInvoker? I'd need that too

**Comment by mrousavy** [comment]
(it has to be a dummy Java package for autolinking to initialize it)

**Comment by philIip** [comment]
> No worries thanks @philIip !! :)
> 
> > do you actually use the macro, or just the C++ methods like registerCxxModuleToGlobalModuleMap? how did you register in Android?
> 
> Yea on iOS I use +load, but on Android I have to create a dummy Java package which does nothing except loading the C++ library. This calls JNI_OnLoad, which then calls the register... func, same way as on iOS.
> 
> I'm not so sure about the installJSIBindings - does this also contain the CallInvoker? I'd need that too

i see, so there's no usage of the RCT_EXPORT_CXX_MODULE_EXPERIMENTAL macro? that's the part i mainly found problematic, because it would often get stripped by the compiler. i'd like to get rid of that, would that be okay? it shifts the burden of the actual link onto the library, but it seems like that's already the case for you.

**Comment by mrousavy** [comment]
Yep the macro is not used! I can also create the revert PR with just the macro removed if that lifts some work off your shoulders! Thanks

**Comment by mrousavy** [comment]
Created a PR here: https://github.com/facebook/react-native/pull/46360

**Pull request closed without merging**
