### PR TITLE
Support font-variant-ligatures values

### PR DESCRIPTION
**Pull request by finnp**
## Summary
The text style prop `fontVariant` in React Native is supposed to map to the CSS `font-variant` property. The CSS property is a short-hand for the following CSS properties:

- [font-variant-alternates](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates)
- [font-variant-caps](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps)
- [font-variant-east-asian](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-east-asian)
- [font-variant-emoji](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-emoji)
- [font-variant-ligatures](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures) 👈 
- [font-variant-numeric](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric)
- [font-variant-position](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position)

Currently React Native only supports a subset of the values from `font-variant-numeric` and `font-variant-caps`.

This change increases the `font-variant` support by adding all values from `font-variant-ligatures`.

## Changelog:

[iOS] [Added] - Add all fontVariant values for font-variant-ligatures
[Android] [Added] - Add all fontVariant values for font-variant-ligatures

## Test Plan:

See https://github.com/facebook/react-native/pull/36740#issuecomment-1492546631
## Resources
- [Apple True Type Reference](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html)
- [Webkit Source Code](https://opensource.apple.com/source/WebCore/WebCore-7602.1.50.1.1/platform/graphics/cocoa/FontCacheCoreText.cpp)
- [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures)
- [Android TextView Documentation](https://developer.android.com/reference/android/widget/TextView#setFontFeatureSettings(java.lang.String))

### CODE REVIEW

**Comment by finnp** [comment]
This change is related to increasing compability with web, linking https://github.com/facebook/react-native/issues/34425

**Comment by finnp** [comment]
Here's a table of all the values:

Name | Android TextView setting | iOS Feature Type | iOS Feature Selector
-- | -- | -- | --
common-ligatures | `'liga', 'clig'` | kLigaturesType | kCommonLigaturesOnSelector
no-common-ligatures | `'liga' off, 'clig' off` | kLigaturesType | kCommonLigaturesOffSelector
discretionary-ligatures | `'dlig'` | kLigaturesType | kRareLigaturesOnSelector
no-discretionary-ligatures | `'dlig' off` | kLigaturesType | kRareLigaturesOffSelector
historical-ligatures | `'hlig'` | kLigaturesType | kHistoricalLigaturesOnSelector
no-historical-ligatures | `'hlig' off` | kLigaturesType | kHistoricalLigaturesOffSelector
contextual | `'calt'` | kContextualAlternatesType | kContextualAlternatesOnSelector
no-contextual | `'calt off'` | kContextualAlternatesType | kContextualAlternatesOffSelector

**Review by necolas — APPROVED** [review]
Stamping

**Comment by finnp** [comment]
# Test Plan
I started testing **iOS** with a test project with the following code: https://github.com/finnp/react-native-font-test/blob/main/A

The results looks like this:

To find proper fonts to test I searched Github and also used https://otf.show/onum.

**Comment by finnp** [comment]
@cortinico @necolas Is anything else needed here to get this merged?

**Comment by cortinico** [comment]
> @cortinico @necolas Is anything else needed here to get this merged?

Yes we need CircleCI tests to be green before we can import this. Can I ask you to logoff/login  to your CircleCI as your token got revoked. You can do so from this UI: https://app.circleci.com/pipelines/github/facebook/react-native/21404

**Comment by professorkolik** [comment]
When this can be released?

**Comment by cortinico** [comment]
> When this can be released?

This will land in 0.73

**Pull request closed without merging**
