### PR TITLE
Catch Throwable instead of Exception from loadLibrary

### PR DESCRIPTION
**Pull request by felipecsl**
**Summary**

We're seeing cases where RN initialization fails due to:
`UnsatisfiedLinkError: could find DSO to load: libreactnativejni.so`
We're using `NativeModuleCallExceptionHandler` to catch initialization
exceptions and prevent the app from crashing. However, since
`UnsatisfiedLinkerError` is an `Error` instead of `Exception`, it is not
caught and thus the app crashes anyways.
This change fixes that by catching `Throwable` instead of `Exception`
from `XReactInstanceManagerImpl.doInBackground()`. I also had to change
`Result.of()` to take a `Throwable` as well, thus a few other places had
to be updated as well.

**Test plan**

All tests pass, throwing an `Error` from `SoLoader.loadLibrary()` is correctly caught
and reported to `NativeModuleCallExceptionHandler`

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
@felipecsl updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9797/files/479d82cf89ad1f827c7a62e9a3966d8b6373c894..a5e549055b559f16bc9a9668fb83a99e44ff93ee)

**Comment by facebook-github-bot-4** [comment]
@felipecsl updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9797/files/a5e549055b559f16bc9a9668fb83a99e44ff93ee..1c219278e5ff25728c5b8122474e943c436a6601)

**Comment by spikebrehm** [comment]
Looks like you need to rebase from master.

**Comment by facebook-github-bot-5** [comment]
@felipecsl updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9797/files/1c219278e5ff25728c5b8122474e943c436a6601..cf390fc73ea21c68cc5fd15ab77c9e62a4adf7c7)

**Comment by lelandrichardson** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
@felipecsl updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9797/files/cf390fc73ea21c68cc5fd15ab77c9e62a4adf7c7..8686f4c9ab4d17b02edd4735132c299b0f08359f)

**Comment by facebook-github-bot-9** [comment]
@felipecsl updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9797/files/cf390fc73ea21c68cc5fd15ab77c9e62a4adf7c7..8686f4c9ab4d17b02edd4735132c299b0f08359f)

**Comment by felipecsl** [comment]
@lelandrichardson can you try to ship it again?

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3864976) to review internal test results.

**Comment by facebook-github-bot-6** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by felipecsl** [comment]
@facebook-github-bot shipit

**Comment by ide** [comment]
cc @mkonicek could you help us take a look at the stack trace or reason why the import failed?

**Comment by facebook-github-bot-2** [comment]
@felipecsl updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9797/files/4ac35ec9f38dd3b5d539a12d6119e92e849f756f..f20427d99674062f732ed3990a28942ad596544b) - [changes since last import](https://github.com/facebook/react-native/pull/9797/files/8686f4c9ab4d17b02edd4735132c299b0f08359f..f20427d99674062f732ed3990a28942ad596544b)

**Comment by lelandrichardson** [comment]
@facebook-github-bot shipit

**Comment by ericvicenti** [comment]
Failed due to this exception:

```
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/react/IgReactExceptionManager.java:25: error: com.instagram.android.react.IgReactExceptionManager is not abstract and does not override abstract method handleException(java.lang.Throwable) in com.facebook.react.bridge.NativeModuleCallExceptionHandler
public class IgReactExceptionManager extends BaseJavaModule implements
       ^
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/react/IgReactExceptionManager.java:153: error: method does not override or implement a method from a supertype
  @Override
  ^
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/react/SimpleReactFragment.java:35: error: com.instagram.android.react.SimpleReactFragment is not abstract and does not override abstract method handleException(java.lang.Throwable) in com.facebook.react.bridge.NativeModuleCallExceptionHandler
public class SimpleReactFragment extends IgFragment implements
       ^
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/react/SimpleReactFragment.java:244: error: method does not override or implement a method from a supertype
  @Override
  ^
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/activity/MainTabActivity.java:-1: note: Some input files use or override a deprecated API.
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/activity/MainTabActivity.java:-1: note: Recompile with -Xlint:deprecation for details.
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/activity/FlickrAuthActivity.java:-1: note: Some input files use unchecked or unsafe operations.
/data/sandcastle/boxes/instance-fb4a-fbsource-android-instrumentation-tests/fbandroid/java/com/instagram/android/activity/FlickrAuthActivity.java:-1: note: Recompile with -Xlint:unchecked for details.
Errors: 4. Warnings: 20.
```

**Comment by felipecsl** [comment]
I guess this requires Facebook to make internal changes to accomodate this. The only thing is replacing `Exception` with `Throwable` in places where you implement `NativeModuleCallExceptionHandler`

**Comment by felipecsl** [comment]
Ping on this again

**Comment by AaaChiuuu** [comment]
Why catch all Throwables? Most errors aren't recoverable from so they should rightly so crash the system; we shouldn't be catching everything. Have you looked into catching the UnsatisfiedLinkError, which sometimes can be recovered from, at the root of crash site?

**Comment by felipecsl** [comment]
We can't catch this because it happens inside an `AsyncTask` started from RN:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.UnsatisfiedLinkError: could find DSO to load: libreactnativejni.so
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:213)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:39)
        at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:31)
        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
        at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
        at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:193)
        at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:179)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by felipecsl** [comment]
Also we don't want to crash the app at startup because RN failed to initialize. Most of the app is still usable. While you won't be able to use the RN flows, the rest works fine and we want to gracefully recover from that

**Comment by AaaChiuuu** [comment]
I think you're confounding the boundaries between error vs exception. In general, it's bad practice to catch errors and it's ok to catch checked Exceptions, which doesn't include RuntimeExceptions/uncheck Exceptions, but lucky for us UnsatisfiedLinkError is an ... exception (har har).

I'm sure you've tried fixing the SoLoader issue and haven't been able to find a real solution and that's resulted in this pull request. cc @michalgr 

Try doing something like
```
try {
    ReactBridge.staticInit(); // b/c this is what's causing your crash.
} catch (UnsatisfiedLinkError e) {
    // Set some flag to not start RN.
}
```
before attempting to initialize RN.

**Comment by felipecsl** [comment]
I don't know what you mean by `UnsatisfiedLinkError` being an `Exception`. It extends `Error` instead: https://developer.android.com/reference/java/lang/UnsatisfiedLinkError.html

**Pull request closed without merging**
