### PR TITLE
chore: Add menu to test-manual-e2e script

### PR DESCRIPTION
**Pull request by gabrieldonadel**
## Summary

Add a menu to the test-manual-e2e script in order to allow a user to select which scenario they want to test rather than having to run them all in order.

Closes https://github.com/facebook/react-native/issues/32679

## Changelog

[Internal] [Added] - Add menu to test-manual-e2e.sh in order to accept configurations

## Test Plan

Manually run `./scripts/test-manual-e2e.sh` and test all menu options 

https://user-images.githubusercontent.com/11707729/149861072-211c78d3-0b0a-4854-b252-d81a019957f1.mov

### CODE REVIEW

**Comment by lunaleaps** [comment]
Amazing! Let me take a closer look later today! Thanks so much for working on this!

**Comment by yungsters** [comment]
Neat! Minor suggestion… when expecting input from the user, maybe prepend the line with `> `.

```
Which app do you want to test?
  1 - RNTester
  2 - A new app using the template
> …
```

**Comment by gabrieldonadel** [comment]
> Neat! Minor suggestion… when expecting input from the user, maybe prepend the line with `> `.
> 
> ```
> Which app do you want to test?
>   1 - RNTester
>   2 - A new app using the template
> > …
> ```

Sure @yungsters, I've just updated it to a prepend the line with `> `
image

**Comment by cortinico** [comment]
> Add a menu to the test-manual-e2e script in order to allow a user to select which scenario they want to test rather than having to run them all in order.

That's great stuff. Just a minor question: wouldn't supporting cli arguments a better approach here? Having something like `--android-only`, `--hermes-only` or so?

Asking as if this is happening inside a development loop, having to go through a menu selection will introduce a lot of friction.

**Comment by lunaleaps** [comment]
Yea that's a good suggestion, maybe we can do both? Currently this isn't part of a dev loop but it would be great to use this for our CI tests

**Comment by gabrieldonadel** [comment]
> Yea that's a good suggestion, maybe we can do both? Currently this isn't part of a dev loop but it would be great to use this for our CI tests

How would this work? Would we bypass the menu if any arguments were provided? If that's the case what do you think about supporting the following arguments?

- `--android-only` (would run all Android related tests)
-  `--ios-only` (would run all iOS related tests)
- `--hermes-only` (would run both Android and iOS tests using hermes)
- `--jsc-only`  (would run both Android and iOS tests using JSC)

Combining arguments examples:

- `--android-only --hermes-only` (would run Android tests using hermes)
-  `--ios-only --jsc-only` (would run iOS tests using JSC) 

Also, should I tackle this in a follow-up PR or should I add these changes to this one?

cc: @lunaleaps @cortinico

**Comment by cortinico** [comment]
> How would this work? Would we bypass the menu if any arguments were provided?

My 2 cents: I think the menu could be ditched as it probably adds a bit of complexity to the script. It's a nice to have though so as it's already coded, I think we can eventually keep it.

Anyway I believe you should just skip the menu if any positional argument is passed 👍 

I would suggest to:

> * `--android` (would run all Android related tests)
> * `--ios` (would run all iOS related tests)
> * `--hermes` (would run both Android and iOS tests using hermes)
> * `--jsc`  (would run both Android and iOS tests using JSC)

Also remove the `--all` as that's the default.

Combining arguments should intersect them:

> * `--android --hermes` (would run Android tests using hermes)
> * `--ios --jsc` (would run iOS tests using JSC)

**Comment by lunaleaps** [comment]
Yup all sound good, re: separate PR or this one, maybe let's merge this one and do a follow-up?

**Comment by gabrieldonadel** [comment]
> Yup all sound good, re: separate PR or this one, maybe let's merge this one and do a follow-up?

Cool, sounds good to me

**Pull request closed without merging**
