### PR TITLE
[Android] textinput: Maintain cursor position when secureTextEntry toggles.

### PR DESCRIPTION
**Pull request by jainkuniya**
## Motivation

On current [master](https://github.com/facebook/react-native/tree/8235a49a33cc8e84cd4ba1cc15bc09eed6712b4c), text input cursor resets to start when `secureTextEntry` prop toggles on Android. This motivate me to maintain position when `secureTextEntry ` prop toggles for better user experience.

On current [master](https://github.com/facebook/react-native/tree/8235a49a33cc8e84cd4ba1cc15bc09eed6712b4c)
ezgif com-video-to-gif-3

## Test Plan
On this PR
ezgif com-video-to-gif-4

## Release Notes

[ANDROID] [BUGFIX] [TextInput] - Fix: cursor positions resets to start on toggling `secureTextEntry` prop.

### CODE REVIEW

**Comment by janicduplessis** [comment]
Thanks for improving this!

I would like to avoid changing the way we make the text input a password field, I think it would be possible to keep using updateStagedInputTypeFlag and instead do the selection position logic when we commit the input flags here https://github.com/jainkuniya/react-native/blob/c7a678947587488183e855fe56d53325d8ca08c8/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L310.

**Comment by janicduplessis** [comment]
We could also preserve the selection end while at it :)

**Comment by jainkuniya** [comment]
hi @janicduplessis Thanks for the review 
I have updated PR :)
Now we are preserving both start and end selection positions when flags toggles :)
Let me know other changes.

**Comment by janicduplessis** [comment]
Looks good, thanks!

@facebook-github-bot shipit

**Comment by ravirajn22** [comment]
@janicduplessis and @jainkuniya this commit does not fix the issue completely in Android, I am still getting it in v0.55.3. Check out this thread #18377 for more info.

**Comment by jainkuniya** [comment]
Hi @ravirajn22 there is a follow up PR for this https://github.com/facebook/react-native/pull/17990. It will be fixed once https://github.com/facebook/react-native/pull/17990 gets merged.

**Pull request closed without merging**
