### PR TITLE
Use ReactActivity for UIExplorer and Movies examples

### PR DESCRIPTION
**Pull request by janicduplessis**
This also fixes the examples since the app lifecycle methods were renamed recently.

### CODE REVIEW

**Comment by janicduplessis** [comment]
cc @satya164

**Comment by mkonicek** [comment]
Cool, thank you @janicduplessis! I assume you've ran both apps? (Asking about a Test plan as on every PR.) If both work let's shipit.

**Comment by janicduplessis** [comment]
Yes, I ran both apps to test it.

**Comment by mkonicek** [comment]
Good! :)

@facebook-github-bot shipit

**Pull request closed without merging**
