### PR TITLE
Add "Easybooking" app to showcase.

### PR DESCRIPTION
**Pull request by Minh0001**
Submitting PR for adding Easybookibng App to React Native showcase

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by bestander** [comment]
@Minh0001 could you please follow the style of using comma for all elements in array?
```
 {
     name: 'YazBoz',
     icon: 'http://a4.mzstatic.com/us/r30/Purple6/v4/80/4f/43/804f431d-2828-05aa-2593-99cfb0475351/icon175x175.png',
     link: 'https://itunes.apple.com/us/app/yazboz-batak-esli-batak-okey/id1048620855?ls=1&mt=8',
     author: 'Melih Mucuk',
   },
```

We imported a few previous ones without it but let's get back on track.

**Comment by facebook-github-bot-5** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @brentvatne as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by lacker** [comment]
Hey, I'm really sorry for the churn, but we are changing up how the showcase works, and just focusing on apps that have some media presence or technical blog posts / other content. So I appreciate the spirit behind this pull request but I think we should close it.

**Pull request closed without merging**
