### PR TITLE
Fix for dimensions not updating correctly on iPad due to screen rotation

### PR DESCRIPTION
**Pull request by manicakes**
On certain devices (in my case, any iPad Pro model), listening to `DeviceEventEmitter.didUpdateDimensions` would call back *before* the interface change takes places (i.e. calling `Dimensions.get()` in this callback would return wrong values). Turns out that we were listening for the wrong native event.

Edit to add: now using `[RCTSharedApplication() statusBarOrientation]` to get the current orientation. Not yet sure why, but the `userInfo` provided by the notification was returning the wrong orientation *only* on the first time you rotate the device.

This fixes the open issue: https://github.com/facebook/react-native/issues/7340

### CODE REVIEW

**Comment by manicakes** [comment]
@javache if you could review this, would be much appreciated - thanks!

**Comment by adrienbataille** [comment]
@manicakes Your changes fix my issue!

**Comment by manicakes** [comment]
@adrienbataille thanks very much for the feedback! Fingers crossed this gets merged in soon.

**Comment by javache** [comment]
Looks good, but wouldn't this delay the event being sent until after the rotation animation? It's weird that the userInfo for the original event would be wrong...

**Comment by rigdern** [comment]
> It's weird that the userInfo for the original event would be wrong...

@javache Yes, Apple seems to have some iOS bugs related to their orientation APIs:
  1. For the **did change** event, `userInfo` is sometimes incorrect as reported by @manicakes.
  1. For the **will change** event, `[[UIScreen mainScreen] bounds]` is sometimes incorrect (specifically, `width` and `height` are swapped on some iPads).

#11181 is an alternative fix which keeps the **will change** event. A downside of that fix is that it requires a bit more code change.

@manicakes, as @javache pointed out, **did change** fires later than **will change**. Have you tested to see if the additional delay caused by the event switch has any noticeable impact?

Other than this one concern, this fix looks okay to me.

**Comment by manicakes** [comment]
@rigdern @javache thanks for the feedback and info. I actually wasn't sure if this calls back after the animation, so I tested to confirm. Here's an iPad Pro 9.7" simulator running my branch, with "Slow Animations" enabled. Good news, it calls back with updated dimensions *before* the rotation animation, so I think we're good. I took a video and posted here: https://www.youtube.com/watch?v=CnRIJFz6jeA

I think if we want to callback before the rotation takes place, we could do that, but maybe add that in with a different name like `willUpdateDimensions`.

ps. I added `DimensionsChangeExample` to the UI Showcase in my working copy, shall I update my PR with it?

**Comment by rigdern** [comment]
@manicakes Cool, thanks for the video.

Can you elaborate on what you meant by this?:

> I think if we want to callback before the rotation takes place, we could do that, but maybe add that in with a different name like willUpdateDimensions.

I don't quite follow what you mean.

**Comment by manicakes** [comment]
@rigdern I'm just thinking that `didUpdateDimensions` implies the past tense - the dimensions "did" already change, and we are being notified. If we wish to know that dimensions "will" change (i.e. in the immediate future), then we should have a different event with a name like `willUpdateDimensions`. 

Hope that makes sense! :)

**Comment by rigdern** [comment]
@manicakes I see, that's an interesting point. Apple's iOS APIs distinguish between `will` and `did` events. I think one of the primary differences between these kinds of events is, in a `will` event global state (e.g. `[[UIScreen mainScreen] bounds]`) should reflect the old state whereas in a `did` event, global state should reflect the new state. iOS also has `should` events which you can use to stop an action from happening.

I'm not sure if RN's `did` prefix for events is intended to be as meaningful (perhaps somebody from the RN team can let us know). If there's no meaningful `will` vs `did` naming convention in RN, I would hesitate to rename this event because it would be a breaking change.

**Comment by manicakes** [comment]
@rigdern ahh, thanks for the explanation. Makes sense.

**Comment by javache** [comment]
Thanks for checking @manicakes. We definitely try to match Apple's conventions of will/did, and in this case we we just assumed that the rotation that **will** happen, also **did** happen.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by sospedra** [comment]
Is this merged? Issues still raising

**Comment by rigdern** [comment]
@sospedra This fix is available starting in React Native 0.41.0.

**Pull request closed without merging**
