### PR TITLE
Update opacity when `disabled` prop is changed

### LINKED ISSUE #17105: `TouchableOpacity` does not let you control opacity when `disabled` prop changes
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.7.0
  Yarn:  1.2.1
  npm:  5.4.2
  Watchman:  4.7.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.50.3 => 0.50.3

### Steps to Reproduce

1. have a `TochableOpacity` with prop `disabled = true` and style `opacity: 0.5`
2. toggle disabled flag to `false` and style to `opacity: 1`

### Expected Behavior

Opacity of component should change from 0.5 to 1

### Actual Behavior

Opacity remains the same unless you press the component (which still looks like disabled)
img_5209

### Reproducible Demo

https://snack.expo.io/rJhh9F8Zz

```
import React, { Component } from 'react';
import { Text, View, StyleSheet, TouchableOpacity, Button } from 'react-native';
import { Constants } from 'expo';

export default class App extends Component {
  state = {
    isDisabled: true,
  }
  onPressBox=()=>{
    this.setState({
      isDisabled: !this.state.isDisabled,
    })
  }
  render() {
    const { isDisabled } = this.state
    return (
      <View style={styles.container}>
        <Text>
          Example of bug in TouchableOpacity.
          The green box is disabled initially.
          If you press "toggle `disabled`" is it supposed become fully opaque.
          It will not change opacity until you tap it.
        </Text>
        <View style={styles.column}>
          <View style={styles.row}>
            <TouchableOpacity
              style={isDisabled?styles.disabled:styles.enabled} 
              disabled={isDisabled}>
              <View style={styles.box}>
                <Text>{isDisabled ? "Disabled" : "Enabled"}</Text>
              </View>
            </TouchableOpacity>
            <Button title="toggle `disabled`" onPress={this.onPressBox} />
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: 'white',
  },
  enabled: {
    opacity: 1,
  },
  disabled: {
    opacity: 0.3,
  },
  row: {
    flexDirection: 'row',
  },
  column: {
    flexDirection: 'column',
  },
  box: {
    width: 100,
    height: 100,
    backgroundColor: 'green',
  },
});
```

### PR DESCRIPTION
**Pull request by maxkomarychev**
fixes #17105

If you render

```
    <TouchableOpacity
        disabled={true}
        style={{opacity: 0.5}}
    >
        ...
    </TouchableOpacity>
```

and then

```
    <TouchableOpacity
        disabled={false}
        style={{opacity: 1}}
    >
        ...
    </TouchableOpacity>
```

The content of `TouchableOpacity` will still have opacity = 0.5 because real
opacity is controlled by animated property which should be properly updated
when `disabled` prop changes.

## Motivation

Usually when a button or other UI component is built with `TouchableOpacity` you may want to change it's opacity if state of component is changed (enabled/disabled). Opacity provided in props is overridden with internally-managed animated value. Add extra check when component is updated to trigger opacity animation upon change of `disabled` flag.

## Test Plan

You can use code from https://github.com/facebook/react-native/issues/17105.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/react-native-website, and link to your PR here.)

## Release Notes
[GENERAL][BUGFIX][TouchableOpacity] - trigger animation on `opacity` upon change in `disabled` prop.

### CODE REVIEW

**Comment by maxkomarychev** [comment]
Hi @hramos, when do you think this PR can be reviewed? Thanks.

**Comment by maxkomarychev** [comment]
@dlowder-salesforce  @lwinkyawmyat @levsero, could you please review or suggest who can do that? thanks.

**Comment by maxkomarychev** [comment]
@javache

**Comment by jctf** [comment]
Anyone reviewing this??

**Comment by tobiastornros** [comment]
Anyone reviewing this?

**Comment by danilobuerger** [comment]
This again, valid patch, nobody reviewing... :(

**Comment by dlowder-salesforce** [comment]
I can review it, but I can't merge it.... maybe you can add release notes?  @shergin might be the right person for this....

**Comment by maxkomarychev** [comment]
@dlowder-salesforce updated release notes, appreciate your feedback! thanks!

**Comment by hramos** [comment]
@danilobuerger there's over a hundred PRs that have been filed ahead of this one. Please be patient!

**Comment by danilobuerger** [comment]
@hramos Instead of being patient, maybe RN just needs more maintainers. Waiting for months to get something reviewed has a chilling effect on contributors. (Disclaimer: I know, this is open source, everybody is doing this on their free time. My point is: RN needs more maintainers).

**Comment by hramos** [comment]
Please consider the chilling effect you could have on existing maintainers as well. Fortunately, we do provide a path to contributing back to the repo: [How to Contribute](http://facebook.github.io/react-native/docs/contributing.html).

**Comment by danilobuerger** [comment]
@hramos 
> Please consider the chilling effect you could have on existing maintainers as well. 

So I shouldn't speak up if I think something isn't right? How would things ever change if we all had to be quiet and tiptoe around each other?

> Fortunately, we do provide a path to contributing back to the repo: How to Contribute.

I know how to contribute, but that's not the issue when having > 100 PRs. It's missing maintainers.

**Comment by oferRounds** [comment]
+1

**Comment by dlowder-salesforce** [comment]
@maxkomarychev I'm going to review and test this PR.... I'm curious, does `TouchableHighlight` not have the same issue?

**Comment by dlowder-salesforce** [comment]
@facebook-github-bot shipit

**Comment by maxkomarychev** [comment]
Thanks a lot @dlowder-salesforce .
As for touchable highlight - I did not meet this kind of issue with that component, but I didn't work with it too much though.

**Pull request closed without merging**
