### PR TITLE
Use strong reference in RCTImageLoader

### PR DESCRIPTION
**Pull request by pfeiffer**
This PR is related to the multitude of crashes (#10016, #9751, #9882).

From my understanding, we should be using a strong reference when calling `decodeImageData` or we could be calling the method on a deallocated instance.

PR #9751 have mitigated this by adding a fail-safe, but I think the culprint is the weak reference, which this PR fixes.

Tested on iOS only, since it doesn't touch Android.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @skatpgusskat and @javache to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-9** [comment]
@pfeiffer updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10147/files/96e228460a20c8f396833855d81e7fdb2f4e2b58..75cd894ce4e6533b6c31b4843190389720d27ffc)

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by dmr** [comment]
Very cool!

**Pull request closed without merging**
