### PR TITLE
chore: refactor react-native-codegen into packages/codegen

### PR DESCRIPTION
**Pull request by shivenmian**
## Summary

Renaming packages/react-native-codegen folder to packages/codegen and updating references; part of RFC480

## Changelog

[General] [Changed] - Renamed packages/react-native-codegen to packages/codegen and updated references.

### CODE REVIEW

**Review by tido64 — CHANGES_REQUESTED** [review]
Some files lost their executable bit. They are marked as `100755 → 100644`. Can we restore them?

**Comment by shivenmian** [comment]
@tido64 done

**Review by tido64 — APPROVED** [review]
Approved to remove the "requested changes" tag:

image

**Review by cortinico — COMMENTED** [review]
Thanks for sending this over @shivenmian 

Let's undo the folder renaming. It will make easier for us to import and merge this change 👍 

I've also posted an update on the monorepo effort there:
- https://github.com/facebook/react-native/issues/34692

**Comment by cortinico** [comment]
> @cortinico This PR mostly just does the folder renaming and corrects the references accordingly - I was going to send a separate PR for the actual package renaming as we had discussed. Should I close this PR then?

Yeah it's better to close this off and send a new one with just the package renaming 👍

**Comment by shivenmian** [comment]
@cortinico closed this one and opened https://github.com/facebook/react-native/pull/34804

**Pull request closed without merging**
