### PR TITLE
Add HorizontalSwipeJumpFromLeft animation to Navigator

### PR DESCRIPTION
**Pull request by yuya-fujimoto**
This brings RN Navigator to add HorizontalSwipeJumpFromLeft animation.
HorizontalSwipeJumpFromRight has been implemented but FromLeft version of SwipeJumpAnimation hasn't been there.

### CODE REVIEW

**Comment by christopherdro** [comment]
@yuya-fujimoto Thanks for the PR!

Any chance this new animation can be added to the UIExplorer demo?

**Comment by yuya-fujimoto** [comment]
@christopherdro Thanks for the comment.
As of the UIExplorer demo, I don't think HorizontalSwipeJumpFromLeft should be in it since it's just a mirroring animation of HorizontalSwipeJumpFromRight and it might be kind of confusing to implement mix of those. (Just like FloatFromRight is in UIExplorer demo but FloatFromLeft isn't there.)

**Comment by leeight** [comment]
LGTM

**Comment by ide** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
