### PR TITLE
Changing timeStamp to timestamp to match ios property name. Fixes #4046

### LINKED ISSUE #4046: [Android] Touch timestamp key different from iOS
As demonstrated here https://rnplay.org/apps/batXmQ

The key for timestamps on touch events is "timeStamp" on android and "timestamp" on iOS. If the documentation is to be taken as the source of truth, then the iOS name is correct.

### PR DESCRIPTION
**Pull request by msathis**
Fixes #4046

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks for the fix! How did you test this?

**Comment by dmmiller** [comment]
Why did you choose iOS instead of Android as the canonical one?  Looking through the code, it looks like it will work either way except in ImageCropper.android which seems to require it be timeStamp.

**Comment by msathis** [comment]
As @dmmiller suggested it's a breaking change. Someone with good knowledge about the product should look into this. Sorry for half baked PR :(

**Comment by christopherdro** [comment]
@msathis :+1: You had good intentions I think you have here is fine. 
I don't see any other code that would conflict with this change. Going to open this back up.

@dmmiller Could you point me to the file containing ImageCropper.android? I can't seem to find anything like that.

I feel like using `timestamp` over `timeStamp` keeps things consistent not only across iOS but other languages in the react-native codebase. Plus, timestamp is considered to be one word so it shouldn't need to be written in camel case. :)

**Comment by mkonicek** [comment]
The ImageCropper is part of the Ads Manager unfortunately. Have to fix it manually..

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by satya164** [comment]
Seems the import failed. Let's try again.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
ping @mkonicek

**Comment by mkonicek** [comment]
@christopherdro, @msathis, @dmmiller  Looks like the web spec uses `timeStamp`:
https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp
http://www.w3.org/TR/DOM-Level-3-Events/

Should we change the iOS key to `timeStamp` instead?

**Comment by dmmiller** [comment]
(y)

I vote we go with the web.  Let's change iOS.

**Comment by satya164** [comment]
@msathis Can you update the PR?

**Comment by msathis** [comment]
@satya164  Yes. I will do it today.

**Comment by mkonicek** [comment]
Hey @msathis! Thanks for making the pull request, but we are closing it due to inactivity (80 days with no activity) to make sure all pull requests are either being worked on or closed. If you want to get your proposed changes merged, please rebase your branch with master and send a new pull request :)

Based on the comments above, we should change iOS to `timeStamp`.

**Comment by mkonicek** [comment]
Update: this has now been fixed by @andreicoman11, it's `timeStamp` on both platforms.

**Comment by andreicoman11** [comment]
Minor correction: we went for `timestamp` instead.

**Pull request closed without merging**
