### PR TITLE
feat: add languages

### PR DESCRIPTION
**Pull request by 1055843615**
## Summary

add missed languages

## Changelog

[iOS] [Added] - accessibility translations

### CODE REVIEW

**Comment by sota000** [comment]
@DingSoung, thanks for making the PR. I am curious, how did you make those translations?

**Comment by DingSoung** [comment]
> @DingSoung, thanks for making the PR. I am curious, how did you make those translations?

I'm staff of xiaomi, we supported accessibility in MiHome, The Plugins of MiHome is based on React Native.
We translated the missing languages

**Comment by sota000** [comment]
Thanks, @DingSoung. Would you mind looking into the merge conflict? Then, I will take it to the internal review. It might take some time to verify the translations for all the languages though.

**Comment by sota000** [comment]
Reviewed this internally. Historically we haven't added any other languages to React Native since it would increase the app size even they don't intend to support multi languages in their apps (e.g. market only in English speaking country). In the long run, hopefully the needs would be solved by some standard accessibility APIs or something the app can depend on to add translations they need. Please reopen and tag me if you think otherwise. Thank you for your time to contribute!

**Pull request closed without merging**
