### PR TITLE
merge the root .flowconfig and local-cli/generator/templates/_flowconfig

### PR DESCRIPTION
**Pull request by AaaChiuuu**
Test Plan: flow check && scripts/e2e-tests.sh

Note:
Flow check currently outputs this warning (but not an error!) because there are two [libs] specified in .flowconfig but only one of which is needed at anytime:

find: /Users/aaronechiu/code/react-native/node_modules/react-native/Libraries/react-native/react-native-interface.js: No such file or directory

Found 0 errors

I'll fix this in the next diff by ensuring we select the correct one with its given call site.

### CODE REVIEW

**Comment by AaaChiuuu** [comment]
cc @vjeux

**Comment by vjeux** [comment]
The e2e tests on travis fail because of a bunch of flow errors :( Doesn't seem to be working :x

**Comment by AaaChiuuu** [comment]
abandoning in favor of https://github.com/facebook/react-native/pull/2976

**Comment by AaaChiuuu** [comment]
This diff was based on a bad base.

**Pull request closed without merging**
