### PR TITLE
Fix AlertIOS Examples

### PR DESCRIPTION
**Pull request by jamesfzhang**
This fixes the examples that are out of date.

### CODE REVIEW

**Comment by christopherdro** [comment]
:+1: LGTM

**Comment by vjeux** [comment]
@christopherdro feel free to write `@facebook-github-bot shipit` ;)

**Comment by jamesfzhang** [comment]
Thank you for the quick review.

**Comment by christopherdro** [comment]
@facebook-github-bot shipit

**Comment by christopherdro** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
