### PR TITLE
Improve ReactModalHostView sizing logic

### PR DESCRIPTION
**Pull request by rgngl**
## Motivation

Setting the size of modal host's children according to the top level FrameLayout we have, instead of querying screen size and manually subtracting sizes of screen decorations. This way we don't need the custom shadow node for the modal.

This also fixes a rare corner case that happens on certain Android devices where the application windows are smaller than the actual resolution of the screen and scaled up by the hardware scaler while being composited.

## Test Plan

Show a `<Modal/>` component on an Android device.

### CODE REVIEW

**Comment by rgngl** [comment]
@christopherdro Hi! Any comments about this?

**Comment by RobertSheaO** [comment]
Just implemented this locally, it fixes the modal perfectly! We ought to get this merged into master!

**Comment by chirag04** [comment]
cc @shergin @AaaChiuuu.

**Comment by RobertSheaO** [comment]
I've tested this on the following physical devices:

iPhone 6 (11.1)
iPhone 7 Plus (11.1.2),
Galaxy S5 (6.0.1 API 23),
Galaxy S6 (7.1.1, API 24),
Galaxy Note 8 (7.1.1 API 25),
LG Nexus 5X (7.1.2, API 25)

**Comment by janicduplessis** [comment]
Can you fix conflicts in ModalHostShadowNode.java please?

**Comment by rgngl** [comment]
Will do.

**Comment by rgngl** [comment]
@janicduplessis @shergin Hi, could we get this merged please?

**Comment by Axbon** [comment]
This is rendering out app unsuable on Galaxy S8, S9 so a merge of this would indeed be sweet.

**Comment by Winglonelion** [comment]
it worked perfectly

**Comment by abhishekdewan101** [comment]
@rgngl thank you for the fix I can confirm this to be an issue on the following devices
1) Samsung Galaxy S8 and S8+
2) Samsung Galaxy Note 8
3) Samsung Galaxy S9 and S9+ 
If we can merge this it would really help the community as on said devices the modal makes the UI look weird!!

**Comment by 8luerain** [comment]
it worked perfectly for Mi 8.   Good job guys

**Comment by wasedaigo** [comment]
What happened to this change? I do not think this is merged ?

**Comment by matyj** [comment]
@rgngl is there something we can do about this? What happened?

**Comment by rgngl** [comment]
I opened this PR almost two years ago and for some reason it didn't get merged. It's a simple fix for a simple problem. If anybody is still interested in fixing it, feel free to take it and apply to latest RN source tree and try again to get it merged.

**Comment by adrianha** [comment]
hi @shergin @janicduplessis , can we get this PR merged?

**Comment by ronakjain90** [comment]
I've tested this code fixes in the expo fork of `react-native` SDK. But it doesn't seem to be working.

https://github.com/ronakjain90/react-native/releases/tag/33.0.1

2 years and it still doesn't work, this is so frustrating.

**Pull request closed without merging**
