### PR TITLE
Add `asdf` as a node version manager

### PR DESCRIPTION
**Pull request by pvinis**
## Summary

Adding `asdf` as a node version manager.

https://github.com/asdf-vm/asdf

asdf is a great version manager, and it was missing from here, so my projects couldn't find the node binary. Now they can!

## Changelog

[Internal] [Added] - Find node binary when using asdf as the node version manager

### CODE REVIEW

**Comment by pvinis** [comment]
lol @akshetpandey, what's up with the thumbs down?

**Comment by akshetpandey** [comment]
Oh god, I used the wrong emoji

**Comment by pvinis** [comment]
All good, I was just very confused how that might trigger someone 😅.

**Comment by pvinis** [comment]
Closing this, since https://github.com/facebook/react-native/pull/30111 got merged.

**Pull request closed without merging**
