### PR TITLE
Allow setting elevation on any type of View

### PR DESCRIPTION
**Pull request by janicduplessis**
Moved setElevation from ReactViewManager to BaseViewManager. This allows
setting elevation on any type of view such as Toolbar for exemple.

### CODE REVIEW

**Comment by corbt** [comment]
Awesome! What different view types have you tested this on?

**Comment by janicduplessis** [comment]
@corbt The main goal was to make it work for Toolbar so I tested that, not sure if there are other type of views that are supposed to produce a shadow when elevation is set.

**Comment by satya164** [comment]
cc @mkonicek

**Comment by corbt** [comment]
I've been looking over this PR just now, and it works great. I'm curious though -- would your use case be served by wrapping a `ToolbarAndroid` inside a `View` and setting the elevation on the outer `View`?

There are already a number of properties that are only available on `View`s and `ImageView`s like all the `border*` styles. That said, I'm not sure if there's a particular reason why that's the case. I don't see a reason why we shouldn't make `elevation` generally available.

**Comment by janicduplessis** [comment]
@corbt Yes it is possible to wrap it but it would be better not to have to. Like you said I don't think there is a reason to limit it to View, especially since it is a method on the native View class so it is always possible to set it.

**Comment by corbt** [comment]
Ok @janicduplessis if no one else chimes in I am sufficiently convinced that this is a good idea. I think maybe the `border*` stuff was only on `View`s because it couldn't easily be implemented across the board, but since `elevation` is baked into Android on any view in the hierarchy (at least those that define an outline), it makes sense to make that available everywhere.

Since the Travis build failed and it's been kinda iffy for the last few days, but seems better now, could you rebase this on `master`, and then I'll merge it!

**Comment by janicduplessis** [comment]
@corbt Done, all green now.

**Comment by corbt** [comment]
@facebook-github-bot shipit

**Comment by corbt** [comment]
:tada:

**Pull request closed without merging**
