### PR TITLE
Fix require polyfill

### LINKED ISSUE #2862: Allow exporting by assigning to 'this'
Apologies in advance  'cause I cannot even test this thing right now and double check, but it is since about kinda ever that in CommonJS node modules the `this` context is the exports itself.

``` js
// this is method.js
// this === module.exports
this.method = function () {
  console.log('here I am');
};

// this is from node console
require('./method').method();
```

The reason this is historically handy is that you can have a single file that exports through `this.functionality = function () {}` and have it working both as global/window script (so that `functionality` will be globally available on the DOM, as example) and as module.

There are people filing bugs about the fact apparently React-native didn't implement the module context in such way so here I am warning few modules out there might just break for such simple, and historically assumed, reason.

By any chance this can  be fixed?

Thanks and Best Regards

### LINKED ISSUE #3298: Cyclic dependency returns empty object
http://stackoverflow.com/questions/29807664/cyclic-dependency-returns-empty-object-in-react-native

I ran into above issue myself when I accidentally tried to require module A from module B which accidentally had the A also required (not to be confued with navigation issue on #3076). It took some head scratching to determine why the object came back as empty so ideally a warning would be raised when accidentally (or purposefully) doing this.

### PR DESCRIPTION
**Pull request by mhofman**
Using some 3rd party libraries with React Native is not possible due to their reliance on some CommonJS/node module behavior not implemented by the React Native require polyfill from the packager.

This PR adds some of these behaviors:
- Circular dependencies when exporting by assignment to the `module.exports` object. Should fix #3298 for good.
- Exporting by assignment to the `this` object. Fixes #2862
- The `module.id` represents a unique identifier that can be used in `require()` calls.

There were no tests for the require polyfill so I added one.

### CODE REVIEW

**Comment by ide** [comment]
Can you please sign the CLA? Otherwise this LGTM, getters and setters are supported on all RN-supported platforms.

**Comment by mhofman** [comment]
The CLA is getting reviewed by my company's legal department right now.

**Comment by mhofman** [comment]
Since my company is in the process of a spin-off / merger, they won't sign any CLA for the time being, at least until Feb 2017.

This PR is a generic fix on react-native, and unrelated to my company's business. Is there any way the PR can be merged without the CLA being signed?

**Comment by ide** [comment]
This isn't legal advice but to my knowledge if you wrote the code on your own time on your own hardware with no company resources, IP, know-how, or other assistance you could sign the individual CLA.

**Comment by mhofman** [comment]
I know that, but it wasn't on my own time.
We're using react-native as a tool, but the code in this fix is unrelated to our business.
Since my company's legal department isn't being flexible right now, I was hoping Facebook's legal department might be a little more accommodating.

**Comment by lacker** [comment]
Ah, I'm sorry for how annoying this is but we really do need people to sign the CLA. If you don't know if you'll ever be able to sign one, then unfortunately we will have to decline this pull request. Would it help your legal team if they could ask questions of the FB legal team? If so, feel free to send me an email at lacker at fb dot com and we can discuss offline.

**Comment by lacker** [comment]
I'm closing this pull request as we cannot accept for licensing reasons. It would be great if someone else implemented this functionality though.

**Pull request closed without merging**
