### PR TITLE
Add product pains to support

### PR DESCRIPTION
**Pull request by vjeux**
Follow up for https://github.com/facebook/react-native/pull/6334

screen shot 2016-03-09 at 2 52 12 pm

### CODE REVIEW

**Comment by arasmussen** [comment]
Hmm, it sucks to have it truncate to 360px though. In my PR I included a <script> that auto resizes the iframe to the content size.

**Comment by vjeux** [comment]
People can scroll down to see the entire thing or click on Product Pains to view the full page.

**Comment by vjeux** [comment]
I also think that you should make the display denser, there's a ton of whitespace in there.

**Comment by arasmussen** [comment]
We could look into that. The widget was designed to be on it's own page (eg. /feedback) rather than embedded in a small section of a larger page, which is probably why it looks too spaced out.

Perhaps consider bumping the height from 360px to 600px (same size as the Twitter feed).

**Comment by vjeux** [comment]
600px it is

**Comment by arasmussen** [comment]
Did you mean to change the Discord URL?

**Comment by vjeux** [comment]
Yeah, while I was doing that I figured I would fix it at the same time... :p

**Comment by arasmussen** [comment]
Cool. LGTM. :)

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Thanks for the initial pull request, it fits very nicely there!

**Comment by arasmussen** [comment]
Do we need to regenerate the docs?

**Comment by vjeux** [comment]
Docs are now showing the prod version by default. It shows up in master ( http://facebook.github.io/react-native/releases/next/ ) and will show up on the main website in about ~4 weeks if we don't do anything.

I could cherry-pick it to the release branches if you want

**Comment by arasmussen** [comment]
Not a big deal. Four weeks seems long though. :P

**Comment by vjeux** [comment]
Yeah... People complained before when we used the docs for master as they would see things in the future.

Need to figure out how to push faster things like this which are not tied to a release

**Pull request closed without merging**
