### PR TITLE
Update template devDependencies

### PR DESCRIPTION
**Pull request by Bardiamist**
## Summary

Update template devDependencies before 0.64.0 release

## Changelog

[JavaScript] [Changed] - Update devDependencies (`@babel/core` to `7.12.9`, `@babel/runtime` to `7.12.5`, `@react-native-community/eslint-config` to `2.0.0`, `babel-jest` to `26.6.3`, `eslint` to `7.14.0` and `jest` to `26.6.3`)

## Test Plan

- [ ] Check babel
- [ ] Check eslint
- [ ] Check jest

### CODE REVIEW

**Comment by kelset** [comment]
Thanks for the PR @Bardiamist, let me try to get it in front of the right people to tell us if this is mergeable :)

**Review by thymikee — APPROVED** [review]
Yes please. These are technically breaking changes for the template, so worth mentioning them in the changelog appropriately.

**Comment by TheSavior** [comment]
@cpojer, can you help with this? I'm not sure if these deps can be bumped if they don't match the versions of the rest of the monorepo

**Comment by cpojer** [comment]
Yes they can be updated, you should be able to import and land the diff.

**Pull request closed without merging**
