### PR TITLE
Move yargs to a dependency to avoid script failures

### PR DESCRIPTION
**Pull request by cjhines**
## Summary

`yargs` depdendency is unavailable on `npm ci` breaking certain CI builds.

Fixes https://github.com/facebook/react-native/issues/35893#issuecomment-1397494372

Changelog: [Internal]

Prevent script failures on certain npm CI setups

### CODE REVIEW

**Comment by cortinico** [comment]
Apologize this took a bit longer to land @cjhines

**Comment by cjhines** [comment]
How come this was reverted? I'm maybe missing something from your workflow

**Comment by cortinico** [comment]
This was causing a failure on one of our internal builds and another engineer had to revert it. I'm attempting to land it again, will comment here if this happens

**Comment by cortinico** [comment]
re-merged here https://github.com/facebook/react-native/commit/5093e557efac35632d99cd2094527f9e01cbc519

**Pull request closed without merging**
