### PR TITLE
Add note about Android support

### PR DESCRIPTION
**Pull request by Daniel15**
I think it's important to mention the most popular smartphone OS :)

Sourced from https://code.facebook.com/posts/1014532261909640/react-native-bringing-modern-web-techniques-to-mobile/:

> Today, we're excited to open-source React Native for iOS and make it available on GitHub. Android support is coming soon, and we're also continuing full steam ahead on React for the web, but we wanted to get this initial iOS support out as early as possible so we can get input from others who are also excited about this approach

### CODE REVIEW

**Comment by SOSANA** [comment]
Epic!

**Comment by ragnraok** [comment]
Excited!

**Comment by yasoob** [comment]
I can not wait. BTW what would this mean for ionic framework :/

**Comment by PawelOwczarekFalcon** [comment]
Cordova will die :) imho

**Comment by ragnraok** [comment]
And I found a similar project: https://github.com/NativeScript/NativeScript , but for android, it seem that when app launch, it will load the v8 engine, and ti cost so many time, in my Nexus 5, it use 4s to launch a simple HelloWorld project, and the size of apk is so large, a HelloWorld project consume 8.4M. I'm pretty curious about how react-native solve this problem

**Comment by lenage** [comment]
if you can't wait to try React on Android, give a [reapp.io](http://reapp.io) try. :)

**Comment by xu6148152** [comment]
nice

**Comment by ElijahLynn** [comment]
"later this year" -> https://github.com/facebook/react-native/issues/309#issuecomment-86879861

**Comment by vjeux** [comment]
Give us 6 months. http://facebook.github.io/react/blog/#when-is-react-native-android-coming

**Comment by Daniel15** [comment]
@vjeux Thanks. That's still not mentioned in the readme or on the site though. Could we please add it?

**Comment by vohof** [comment]
*heavy breathing*

**Comment by zhangxiaang** [comment]
excited

**Comment by marconi** [comment]
3 months to go! :D

**Comment by sliuqin** [comment]
3 months to go! :D

**Comment by Daniel15** [comment]
The very first React Native Android app came out a few days ago (
https://play.google.com/store/apps/details?id=com.facebook.adsmanager) so
it shouldn't be long until it makes it into the open source version :)

**Comment by jagandecapri** [comment]
:+1:

**Comment by checkraiser** [comment]
(y)

**Comment by isairz** [comment]
+1

**Comment by rockerhieu** [comment]
+1

**Comment by brunoksato** [comment]
1 month, 2 weeks, 3 days, 8 hours, 55 minutes and 55 seconds !!!  +1

**Comment by JuanMaCuevas** [comment]
http://www.reactnativeandroid.com/

**Comment by Daniel15** [comment]
For what it's worth, the first Android React Native app was recently released ([Facebook Ads Manager](https://play.google.com/store/apps/details?id=com.facebook.adsmanager)) so it shouldn't be *too* far away :)

**Comment by andrerpena** [comment]
:+1:

**Comment by sanketsahusoft** [comment]
1 month, 1 week, 5 days, 5 hours, 6 minutes and 53 seconds

**Comment by MathieuDoyon** [comment]
Ok! @sanketsahusoft I don't think follower of this needed to be update with that kind of countdown. Please stop spamming our mailbox.

**Comment by bikasv** [comment]
can Facebook write a blog about what feature we can expect in React Native for Android? This will be deciding factor whether to wait for React Native or go with Cordova/ Ionic which do decent job.

**Comment by bikasv** [comment]
@lenage I tried reapp kitchen sink on Android browser. Not only slow like hell, it can't even scroll. Definitely not usable at all.

**Comment by AlokBansal8** [comment]
@Daniel15 Its been quite long. What do you say?

**Comment by Daniel15** [comment]
It's out! https://code.facebook.com/posts/1189117404435352/react-native-for-android-how-we-built-the-first-cross-platform-react-native-app/

**Comment by zhangxiaang** [comment]
soooooo  cool

**Pull request closed without merging**
