### PR TITLE
when keyboardDismissMode ==='on-drag', we also make sure we are reall…

### PR DESCRIPTION
**Pull request by RonnieRen**
…y on-drag state and then dismiss the keyboard.

## Motivation

fix issue #16635
the issue is a little serious if you use a scrollview which contains textinput, you will never get a chance to input something since keyboard will always be dismissed because of on-drag event if your scroll-view use the property: keyboardDismissMode ='on-drag'

## Test Plan

verify the issue https://github.com/facebook/react-native/issues/16635 and tested this fix worked

### CODE REVIEW

**Comment by RonnieRen** [comment]
https://github.com/facebook/react-native/issues/16635

**Comment by shergin** [comment]
@RonnieRen Could you please sign the CLA?

**Comment by angly-cat** [comment]
I'd like to see this PR merged.

> Is this pull request still relevant? If yes could you please rebase?

@RonnieRen could you rebase it, please?

**Comment by mistenkt** [comment]
Any change of a merge? Having a problem on android that would be fixed with this PR

**Comment by canastro** [comment]
Having this fix merged would be really important for the app I'm currently developing. Any update?

**Comment by cpojer** [comment]
Sorry for the long wait. It seems like @mistenkt already made the same change and as of today it is present in `ScrollView.js`: https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L835 changed in https://github.com/facebook/react-native/commit/2f1421dec7cd3a35779caceac108e872033c7d72.

**Pull request closed without merging**
