### PR TITLE
Fix KeyboardAvoidingView padding on Android

### PR DESCRIPTION
**Pull request by ivpusic**
Related issue https://github.com/facebook/react-native/issues/10517

### CODE REVIEW

**Comment by lacker** [comment]
Can you explain how you tested that this fix is correct?

**Comment by ivpusic** [comment]
for calculating y2 I think it is used the fact that (frame.y + frame.height) will give you distance from top of the screen until start of container, but this is true on iOS. On Android (frame.y + frame.height) is giving you distance from status bar and we need it from top of the screen. Any thoughts on this?

I tried it on my project (see issue https://github.com/facebook/react-native/issues/10517), tried adding dummy views bellow, above to verify that it works if container is in the middle, start, end of the screen, and so far it worked on Android 4, 5, 6.

I know this is sensitive change, so would be good if you can also spend some time testing it.
Thanks

**Comment by lacker** [comment]
Sorry if I'm being obtuse here, I just don't understand why the previous behavior was wrong and why the behavior you propose is correct. This seems like it would alter the behavior of KeyboardAvoidingView all the time, for example, and the other commenter on https://github.com/facebook/react-native/issues/10517 reported an intermittent issue.

**Comment by ide** [comment]
Looking at this, I'm not sure if this is always the right fix. I believe Android reports different values for the status bar offset depending on whether the status bar is opaque or translucent. Also the windowSoftInputMode might affect this behavior as well. I don't have a fix in mind but my concern is that this PR might fix one combination of config params but break another.

**Comment by ivpusic** [comment]
@ide I agree. Will close this PR and fork KeyboardAvoidingView to adjust it to my needs. Hope so in the future we get the proper fix for all cases on Android.

**Pull request closed without merging**
