### PR TITLE
Add 儿戏亲子游 App to React Native showcase

### PR DESCRIPTION
**Pull request by nowaits**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by lacker** [comment]
Hey, I'm really sorry for the churn, but we are changing up how the showcase works, and just focusing on apps that have some media presence or technical blog posts / other content. So I appreciate the spirit behind this pull request but I think we should close it.

**Comment by nowaits** [comment]
@lacker how can i add my app to showcase? My app have use react native for one year both on ios and  android platform , it works very well, so i want to commit to showcase :)

**Comment by lacker** [comment]
So the new format has an infoLink / infoTitle which we are using to link to media coverage or technical information about the app. That way we ensure that each item on the showcase is useful to someone who's reading the page. If this isn't the sort of app that has any media coverage or an official blog that discusses technical stuff, then it might not be useful to put it on the showcase.

**Pull request closed without merging**
