### PR TITLE
[Docs] Fixed word auto-correction in TextInput.js

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Before:
react native a framework for building native apps using react 2015-06-11 18-31-22


After:
react native a framework for building native apps using react 2015-06-11 18-31-37

**Comment by ide** [comment]
This looks good to merge.

**Comment by prathamesh-sonpatki** [comment]
@ide Thanks for the review. Will the website be updated automatically?

**Comment by ide** [comment]
@prathamesh-sonpatki yes, once your commit is merged the website HTML will be regenerated from the JS source code.

**Pull request closed without merging**
