### PR TITLE
Enable ATS w/ localhost exception for generated iOS proj

### PR DESCRIPTION
**Pull request by andrewsardone**
Building off of the work in https://github.com/facebook/react-native/pull/5290, this…

- Remove the total disabling of ATS from the react-native generated iOS project in favor of a localhost exception

### CODE REVIEW

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by ide** [comment]
Does this break developing on devices since they connect via LAN IPs?

**Comment by andrewsardone** [comment]
@ide, current setup, yes, but we could add a step in the [_Running On Device_ docs](http://facebook.github.io/react-native/docs/running-on-device-ios.html#accessing-development-server-from-device) that notes changing the `localhost` exception to the user's computer's IP address. I have pushed a change here: https://github.com/andrewsardone/react-native/commit/ac8da491d154d514d059b3dc0057496dd3695841

Let me know if that works – thanks!

**Comment by ide** [comment]
I'm not sold that we want this in the template project. Another approach would be to mention ATS in the docs for people who want to turn it on.

**Comment by andrewsardone** [comment]
> I'm not sold that we want this in the template project.

@ide, I understand the skepticism, but I disagree. The purpose of a template project is to easily generate a best practices setup for an app, and I think it'd be irresponsible for React Native to push the community to opt-out of a potentially important security measure. 

This places a knowledge burden on the app developer in two scenarios:

1. Running on a device (as noted in the docs) requires some extra work: tweaking a configuration file that is buried in Xcode, so it might be unfamiliar to some. But running on a device _already_ requires extra work (changing the address of your dev server requests), so I see this only as a minor trade-off.
2. Developers who are totally unfamiliar with iOS and App Transport Security could come across unsecure requests in the development of their app (e.g., they’re working with a bad server, or needing to interact with HTTP-served assets) and be totally lost on how to fix “the bug” that they’re up against. I view this as an opportunity to improve docs and tooling so we end up with a community that prioritizes security and ships better apps.

I don’t think these two points should push React Native to disable ATS by default.

For more information on the “why” of enabling App Transport Security, @cdzombak put together some [nice slides on the subject][blogpost].

I'm curious to know, @ide, if there are other difficulties that this change would introduce. Thanks!

[blogpost]: https://www.dzombak.com/talks/2016-01-14-App-Transport-Security--What--Why--How-.html

**Comment by mkonicek** [comment]
What problem does this PR solve? Why is the new (quite complicated) step in the docs needed?

If people need this step only in case of some error, they should only have to worry about it if they hit that error, not every time when reading the tutorial on how to run their app on a device.

**Comment by ide** [comment]
@mkonicek In iOS 9, Apple added an optional feature to prevent your app from making any non-SSL connections, with the ability to whitelist specific hosts, like `localhost` for connecting to the packager. This PR turns on the SSL requirement in template apps with an exception for `localhost` which means:

- iOS will enforce that all connections except to localhost are over SSL. The good thing is it prevents you from making insecure connections, the bad thing is you have to set up SSL.
- Local development on the iOS simulator will continue to work
- Development on a device, connecting to the MacBook's IP address will not work because Apple doesn't offer pattern matching like `10.0.0.0/8` or `192.168.0.0/16`.

This option is entirely configurable in your app's config file. This issue is just about the default settings in the RN template.

**Comment by andrewsardone** [comment]
> What problem does this PR solve?

@mkonicek, as noted by @ide, this change alters the default React Native template to enable iOS 9’s App Transport Security (ATS). Enabling ATS is the standard for new (native) Xcode projects, and in general it's considered a “best practice” to leave enabled. Not only does it prevent your app from making any non-SSL connections, but it [also sets some other minimum standards](https://speakerdeck.com/dzombak/app-transport-security-what-why-how?slide=14).

I think React Native’s template project should adhere to best practices, particularly in the area of security.

Note, I have also rebased this branch against `origin/master` as it was quite stale.

**Comment by facebook-github-bot-2** [comment]
@foghina would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
I have to admit I don't have bandwidth to review this, will let @ide merge this one.

**Comment by ide** [comment]
OK let's try this out and learn if people run into issues or if it is fine.

@andrewsardone can you add an entry to the Known Issues page that includes the text of potential ATS errors so people can find out more easily how to turn it off? These are the error messages:
 
> App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

and

> NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

**Comment by facebook-github-bot-1** [comment]
@andrewsardone do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by facebook-github-bot-2** [comment]
@andrewsardone updated the pull request.

**Comment by andrewsardone** [comment]
I apologize for the delay – the notifications went past my radar.

@satya164 & @ide, I have rebased against `origin/master` and [updated the known-issues with an ATS entry](https://github.com/facebook/react-native/pull/5355/commits/31bb10a21d33cc661516da4563a627d6d1c05cae) (per [this recommendation](https://github.com/facebook/react-native/pull/5355#issuecomment-204801794)).

Thanks!

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1684485818503873/int_phab) to review.

**Comment by jondot** [comment]
@andrewsardone @mkonicek @ide I've just synced `react-native-network-boot` against this change. Regardless you might want to get familiar with it since it automates the pain of configuring IPs (or now ATS exceptions):
 https://github.com/jondot/react-native-network-boot

**Pull request closed without merging**
