### PR TITLE
Fix View documentation typo

### PR DESCRIPTION
**Pull request by alcedoatthis**
Fix typo in View component documentation.

### CODE REVIEW

**Comment by alcedoatthis** [comment]
CLA signed

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3923619).

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3923619).

**Pull request closed without merging**
