### PR TITLE
Update GettingStarted.md

### PR DESCRIPTION
**Pull request by abdelouahabb**
requirement should be inside iOS now that android is supported too.

### CODE REVIEW

**Comment by kmagiera** [comment]
flow & watchman is required for android as well

**Comment by abdelouahabb** [comment]
so that means no windows/linux support yet?

**Comment by abdelouahabb** [comment]
BTW, why Algeria doesent figure in the list of countries:
https://code.facebook.com/cla

**Comment by kmagiera** [comment]
@abdelouahabb Please see https://github.com/facebook/react-native/issues/2684 for some more info about host platform requirements
According to CLA question maybe @caabernathy can help?

**Comment by abdelouahabb** [comment]
@kmagiera it seems that linux/windows will be supported but not  in the nearest future :(

**Comment by vjeux** [comment]
@abdelouahabb: congratulation, you are the first Algerian that is committing anything to a Facebook open source project!

**Comment by abdelouahabb** [comment]
@vjeux thank you :3

**Comment by mkonicek** [comment]
No official Linux or Windows support yet but will update Getting Started once there are more operating systems supported. Getting RN to work on Linux shouldn't be hard and we should document it. People in the community are looking into Windows support too.

For now the guide is pretty accurate: https://facebook.github.io/react-native/docs/getting-started.html

Closing this PR as the guide will likely have larger changes as there are more operating systems supported.

**Comment by abdelouahabb** [comment]
ok, thank you, waiting for android-windows support :dart:

**Pull request closed without merging**
