### PR TITLE
Removing --reset-cache from bundle generation scripts

### PR DESCRIPTION
**Pull request by geof90**
This PR proposes reverting the change made in https://github.com/facebook/react-native/commit/bb0653661637e907c13c4352d657974c5daf1513.

The problem I have observed with `--reset-cache` is that it generates a slightly different JS bundle each time you run `react-native bundle` with that flag, even though the JS code and other app assets have not been changed at all. Specifically, it appears that the module IDs are randomized each time.

image

If the `--reset-cache` is omitted, the generated JS bundle is always the same as long as the JS code files and assets are not updated. If they are updated, the JS bundle would be different, which is expected behaviour. I have seen on some occasions that a stale JS bundle might still get generated, however the workaround I have observed to always work in practice is running `rm -rf $TMPDIR/react-*` as recommended in https://github.com/facebook/react-native/issues/4289.

The reason why this behaviour is a problem is because in the CodePush plugin, we hash the contents of the JS bundle and assets and send the hash to the backend server to prevent the app from having to download an identical update from CodePush. Hashing also helps us to provide only the changed files to the app, so that the app doesn't have to always download a full version when only a subset of the files are changed, hence saving network resources. See https://github.com/Microsoft/react-native-code-push/issues/345 for more information. We rely on the behaviour that if the code files and assets are not changed, the exact same JS bundle should be deterministically generated every time. 

I don't have enough knowledge about the inner workings of `node-haste` to know why `--reset-cache` has this behaviour of randomizing module IDs (i'm guessing its something to do with parallel processing), so more information would be appreciated. However, since it seems to be causing problems such as this, I propose reverting https://github.com/facebook/react-native/commit/bb0653661637e907c13c4352d657974c5daf1513 and using a different workaround to the original problem it was trying to solve (such as using `rm -rf $TMPDIR/react-*` in the bundle generation scripts).

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @frantic and @mroswald to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
@geof90 updated the pull request.

**Comment by satya164** [comment]
cc @davidaurelio @martinbigio

**Comment by mroswald** [comment]
@geof90 Wouldn't it be better to fix the cause, not removing a feature? :-) Building a new app should definitely build a fresh bundle. What's your method to build a new bundle for CodePush updates? As far as I understood it correctly, `code-push release-react` should be run, but it takes an existing bundle. So calling `react-native bundle` on yourself before would allow you to omit the `--reset-cache`, right?

**Comment by geof90** [comment]
@mroswald, thats not the problem. `release-react` doesn't call `reset-cache`. The app is prebuilt with a bundle that already was built with `reset

**Comment by geof90** [comment]
Sorry, accidentally closed.

**Comment by mroswald** [comment]
@geof90 So, if two persons are working on the app, both pushing the exact same version of the js code to codePush, this will lead to a new bundle download, right? That's the same effect as having the cache cleared. I mean, wouldn't it be better if a bundle is the same when the source code is the same, regardless of any caches?

**Comment by geof90** [comment]
> wouldn't it be better if a bundle is the same when the source code is the same, regardless of any caches
Exactly right. That's part of what this discussion is intended to highlight. I would never have detected this problem before `reset-cache` was put into the default bundle generation scripts, this drew my attention that somehow, bundle generation is not deterministic, and it is a problem. I agree that we need to fix the root cause, but right now, I think removing `reset-cache` addresses the problem for many existing users who always build and release apps from a single machine, whether they are a single developer or using a CI build.

**Comment by mroswald** [comment]
I will check that later this day or tomorrow. I assume it must be somewhere between `packager/react-packager/src/Resolver/index.js` and `node-haste`.

**Comment by frantic** [comment]
We should just fix the cause, I believe it won't be hard to make the module IDs deterministic, might be just the matter of sorting dependencies by file names before composing the bundle. This could break down in case we have multiple bundles that share a subset of modules, but for `react-native bundle` it shouldn't be a problem.

@davidaurelio any toughts?

**Comment by lostintangent** [comment]
@frantic That would be awesome!

**Comment by lostintangent** [comment]
@frantic Any update on this? Thanks!

**Comment by lostintangent** [comment]
@davidaurelio Any updates here? I'm assuming this PR can be closed, but I'd love to discuss/track the ideal fix that @frantic referred to.

**Comment by davidaurelio** [comment]
I tried a simple approach, but that’s not enough. I’ll have to double check multiple parts of the system in order to understand why the order of ID assignments to module can be different

**Comment by mroswald** [comment]
@davidaurelio As far as I understood and remember correctly, the DependencyGraph is built and resolved asynchronously. The greater your DG is and the more modules you have, the more difference you'll have in your bundle IDs

**Comment by davidaurelio** [comment]
@mroswald I made it work, but the commit needs internal review. node-haste is jumping through some hoops to guarantee depth-first traversal order.

**Comment by davidaurelio** [comment]
@lostintangent @geof90 can you confirm that this commit fixed the issue?

**Comment by lostintangent** [comment]
@davidaurelio I can confirm that identical bundle files are being created in RN 0.29.0, even when setting the `--reset-cache` flag. Thanks so much for the amazingly quick turnaround!

Now we just need to account for the new `.meta` file that is being generated :) I'll go ahead and close this PR since it isn't necessary anymore.

**Comment by davidaurelio** [comment]
We are using that file internally. It contains a sha1 and an encoding flag (0 = unknown, 1 = ascii, 2 = utf-8, 3 = utf-16 le. We should probably hide it behind a flag.

**Pull request closed without merging**
