### PR TITLE
Appearance.setColorScheme support (revisited)

### PR DESCRIPTION
**Pull request by birkir**
## Summary

Both Android and iOS allow you to set application specific user interface style, which is useful for applications that support both light and dark mode.

With the newly added `Appearance.setColorScheme`, you can natively manage the application's user interface style rather than keeping that preference in JavaScript. The benefit is that native dialogs like alert, keyboard, action sheets and more will also be affected by this change.

Implemented using Android X [AppCompatDelegate.setDefaultNightMode](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#setDefaultNightMode(int)) and iOS 13+ [overrideUserInterfaceStyle](https://developer.apple.com/documentation/uikit/uiview/3238086-overrideuserinterfacestyle?language=objc)

```tsx
// Lets assume a given device is set to **dark** mode.

Appearance.getColorScheme(); // `dark`

// Set the app's user interface to `light`
Appearance.setColorScheme('light');

Appearance.getColorScheme(); // `light`

// Set the app's user interface to `unspecified`
Appearance.setColorScheme(null);

Appearance.getColorScheme() // `dark`
 ```

## Changelog

[GENERAL] [ADDED] - Added `setColorScheme` to `Appearance` module

## Test Plan

Added a RNTester for the feature in the Appearance section.

Three buttons for toggling all set of modes.

### CODE REVIEW

**Comment by birkir** [comment]
Please provide guidance on further improvements for this PR, if any.

@NickGerleman @jacdebug @cortinico

**Comment by cortinico** [comment]
@NickGerleman should be taking care of this one. Don't you mind rebasing on top of main as the CI should be green now 👍

**Comment by NickGerleman** [comment]
@birkir would you be willing to add the new API to this page as well? https://github.com/facebook/react-native-website/blob/main/docs/appearance.md

**Comment by birkir** [comment]
CI still broken I guess

**Pull request closed without merging**
