### PR TITLE
bump RNTester targetSdkVersion to 26

### PR DESCRIPTION
**Pull request by gengjiawen**
Motivation
bump RNTester targetSdkVersion to 26

Test Plan
pass all current ci.

Related PRs
none

Release Notes
[GENERAL] [INTERNAL] [RNTester] - bump RNTester targetSdkVersion to 26

### CODE REVIEW

**Comment by janicduplessis** [comment]
@gengjiawen Could you rebase on master to make sure Android CI passes

**Comment by gengjiawen** [comment]
@janicduplessis done.

**Comment by gengjiawen** [comment]
It seems the ci is broken again in master branch ...

**Comment by rghorbani** [comment]
@gengjiawen Thanks but this already has been implemented. #19662

**Pull request closed without merging**
