### PR TITLE
support SafeAreaView bottom margin

### PR DESCRIPTION
**Pull request by elelad**
Fix for issue: https://github.com/facebook/react-native/issues/18177

Modal component does not support SafeAreaView bottom margin

### CODE REVIEW

**Comment by fsfhiyg** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by fsfhiyg** [comment]
https://github.com/facebook/react-native/pull/23501#issuecomment-464498339

**Comment by cpojer** [comment]
It doesn't seem like that is the right fix and it is a breaking change as well. Your PR also doesn't conform to the template, and there is no explanation about why this fixes the issue so I'm gonna close this PR for now. Feel free to make a similar modification in your project.

**Comment by elelad** [comment]
You're right, this is not the correct approach to solving the issue, I will try another way.

**Pull request closed without merging**
