### PR TITLE
Add docs for View BorderWidth

### PR DESCRIPTION
**Pull request by morenoh149**

### CODE REVIEW

**Comment by Crash--** [comment]
I closed #2755 because this one is complete ;).

**Comment by browniefed** [comment]
I'm not sure these are necessary. These are properties of Flexbox because they account for width in layouts. The layout props are here https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/LayoutPropTypes.js and the documentation can be found here for them https://facebook.github.io/react-native/docs/flexbox.html#proptypes

**Comment by morenoh149** [comment]
@browniefed ah didn't see those. I thought they were properties of Views. A note instead on View's docs pointing to flex docs for borders?

**Comment by browniefed** [comment]
Yes those get linked anytime something inherits from view, it would may be more beneficial if we inlined flex box and transform with a title instead of linking to them. @ide @brentvatne thoughts?

**Comment by Crash--** [comment]
I like @browniefed's idea. Having the full list of all style properties directly on the View Page (and not just a link to the flexbox & transorms) can be a great solution! 

ATM  we don't know why some properties are listed on the style section and why some not. Pretty confusing for an user.

**Comment by mkonicek** [comment]
@Crash-- The convention is everything that has the same behavior on web is in style. Everything else is in props.

See http://www.w3schools.com/cssref/pr_border-top_width.asp

**Comment by vjeux** [comment]
The idea is that we want to be a subset of the web as much as possible, this way people can reuse their existing knowledge or if they don't have it, can learn something and reuse it on the web for their next non react-native project.

**Comment by morenoh149** [comment]
So list `Border{Top,Left,Bottom,Right}Width` in the View styles docs right? as it's the same as on web and works if you pass them into a StyleSheet on `View`s

**Comment by Crash--** [comment]
I agree with you @mkonicek and @vjeux. I'm just asking why, for exemple, `borderRightColor`is currently listed in ViewStylePropTypes.js and not `borderRightWidth`. Both of them are `flexbox` properties but only one is listed in the first place. 

I created #2755 after spending a few minutes wondering why I couldn't get the border I wanted. And now, I see with this PR, that I'm not the only one to find that the documentation is not very clear on that subject.

**Comment by mkonicek** [comment]
Looks like this is supported on Android: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseCSSPropertyApplicator.java
And on iOS: https://github.com/facebook/react-native/blob/master/React/Views/RCTView.m

Thanks for adding the docs, it's good to make this more explicit.

We could document these are in points (not pixels) but that's probably quite obvious.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
