### PR TITLE
Specify width and height for Image(remote source)

### PR DESCRIPTION
**Pull request by sunnylqm**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @lacker to be a potential reviewer.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/484613391663217/int_phab) to review.

**Comment by lacker** [comment]
Hey, is this change needed? At this point if you are reading the tutorial linearly the reader has not learned about "style" yet, and the text only mentions the "source" prop, so it's a bit odd. We were trying to avoid extraneous styling in the examples.

**Comment by facebook-github-bot-5** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by sunnylqm** [comment]
@lacker  I know what you mean. But the fact is that "style" is required for Image, otherwise the readers would get nothing to show on their screens. (Somehow the react-native-web-player shows the image because the different implementations between web and RN I guess). So either change to a simpler example which would work with only one prop, or have some words about style here. I am not a native speaker: (, and not so confident with long sentences. So I choose the simplest way to PR, that is, to remind you since issues would probably be ignored.

**Comment by lacker** [comment]
Arrrr ok. Let's get this in and then I can mess around with the wording later. The bot seems to have rejected it though... lets just try again, if it doesnt work again maybe it needs a rebase.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/484613391663217/int_phab) to review.

**Comment by sunnylqm** [comment]
Seems already done https://github.com/facebook/react-native/commit/6b2a49e73e52bf40ab82f792e7748aa36847c17f

**Comment by lacker** [comment]
Oh - I'm confused why the Import Failed tag is on here then. Dunno....

**Comment by sunnylqm** [comment]
And I forget the space between style and the ending tag...sorry to left it to you.

**Comment by JoelMarcey** [comment]
Optimally, the import failed bot should be removed after import started and pull request closed. Just a tooling thing.

**Pull request closed without merging**
