### PR TITLE
Add troubleshooting note for #8890

### PR DESCRIPTION
**Pull request by khaled**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @lloydnye to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by javache** [comment]
I believe this has been fixed in a newer React Native release? Otherwise can we fix the podfile to take care of this? Adding troubleshooting instead of fixing the source of the issue seems sub-optimal.

**Comment by khaled** [comment]
@javache  This happens on a fresh React Native 0.32.0 project generated with `react-native-cli` 1.0.0.  The XCode project's test target initially has no value in `Other linker flags`.  If, after creating a project, I run `pod init` and `pod install` in the `ios/` directory, then try to run via `react-native run-ios`, the build fails do to the lack of the '-lc++' flag.

I agree that fixing at the source would be optimal (in which case perhaps #8890 should be re-opened), but in the mean time it'd be nice to have a troubleshooting note, as this seems like it'd be a pretty common case.

**Comment by hramos** [comment]
A couple of months ago we cleaned up the troubleshooting page to remove anything that may already be documented as an issue in this repo. The issue tracker is a better place for this, as the docs can easily become stale once the issue is resolved.

If it's a question of discoverability, maybe we should encourage people to look up GitHub issues if their issue is not covered in the troubleshooting page.

**Comment by mkonicek** [comment]
Thanks for the pull request! I kind of like the Troubleshooting page but agree with @hramos it's difficult to make sure it's up to date. As long as GitHub issues and StackOverflow questions have good titles, people can Google the error message to find a solution - the issue or questions will be up to date with comments.

With that I'll close this PR. Hope you won't mind and please keep sending improvements to docs any time you find anything could be made clearer.

**Pull request closed without merging**
