### PR TITLE
Making console write to the Safari debugger console as well as NSLog

### PR DESCRIPTION
**Pull request by ccheever**
We still write to NSLog or similar as well

There may be some performance penalty but I don't think so unless the REPL
window is open. It would not be hard to add a flag to this if necessary.
This will definitely make debugging and development easier.

### CODE REVIEW

**Comment by ccheever** [comment]
Any thoughts on this? @vjeux

**Comment by tjwudi** [comment]
I don't think it is necessary to send it to Safari debugger. It will make it complicated, when Windows support is released. I think it can send to the development server, which will somehow keep consistency among different platforms.

**Comment by ide** [comment]
@tjwudi the diff is just calling the native console and would be simple to skip calling the native console's if it's not defined. The idea is that Web Inspector (Safari or Chrome's) are useful as REPLs and it's helpful to see all the console output in one place.

**Comment by ccheever** [comment]
I'm going to resubmit this pull request because:
(a) The Travis CI build failing looks bad even though I believe that the diff is fine and the repo was just in a bad state when I submitted the PR
(b) The switchover from react-native being private to public has broken connection to my fork.

**Pull request merged**
