### PR TITLE
Add the license field on package.json

### PR DESCRIPTION
**Pull request by dalinaum**
Add the license field on package.json

### CODE REVIEW

**Comment by ide** [comment]
jest is unrelated to testing:https://www.npmjs.com/package/jest

**Comment by dalinaum** [comment]
```
scripts": {
    "test": "jest",
    "lint": "node linter.js Examples/ Libraries/",
    "start": "./packager/packager.sh"
  },
```

Because test requires jest, it should be added on package.json

**Comment by dalinaum** [comment]
Oh. I have a mistake. I think jest is needed. I have to remove jest on package.json.

**Comment by vjeux** [comment]
Sounds good, react has the same https://github.com/facebook/react/blob/master/package.json#L13

**Comment by vjeux** [comment]
@facebook-github-bot import

**Comment by brentvatne** [comment]
This made it into today's sync, closing!

**Pull request closed without merging**
