### PR TITLE
Update wc to latest version to remove insecure warning

### PR DESCRIPTION
**Pull request by gtanner**
- [x] Updated wc dependency to latest version.  
 - Noticed on bitHound wc was marked as insecure: [bitHound Dependencies]
(https://www.bithound.io/github/facebook/react-native/master/dependencies/npm)
 - details on bitHound [here](https://www.bithound.io/github/facebook/react-native/master/dependencies/npm/ws)
 - Updated the dep to remove that warning: [bitHound Dependencies](https://www.bithound.io/github/gtanner/react-native/master/dependencies/npm)
  - bitHound generated pr can be seen [here](https://github.com/gtanner/react-native/pull/1)
- [x] Added a bitHound badge to the readme to track the state of your dependencies.

**Test plan**

* Ran `npm test` before and after updating the dependency
* Build the 2048 sample app and ensured that livereload / remote debugging / packaging was all still working since that is where I could see `ws` being used.

### CODE REVIEW

**Comment by bestander** [comment]
Hey, @gtanner that looks nice and useful, let's give it a try/

Can we hold on ws update though?
It requires a bit more effort to update a dependency because we need to be in sync with internal FB repo  and we have a big update to packages coming, just don't want to deal with merge conflicts at the moment :)

**Comment by gtanner** [comment]
Works for me :+1:

**Comment by bestander** [comment]
Ok, once you remove package.json changes I'll import the PR

**Comment by gtanner** [comment]
Rebased it out.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
:+1:

**Comment by mkonicek** [comment]
screen shot 2016-03-01 at 5 23 55 pm

Bithound still reports dependencies are unsecure, and also reports many of them are unused, which is probably not correct? https://www.bithound.io/github/facebook/react-native/master/dependencies/npm

Does Bithound work well and do we want the icon in the readme?

cc @bestander, @gtanner

**Pull request closed without merging**
