### PR TITLE
Add infix feature for dynamic file selection

### PR DESCRIPTION
**Pull request by bartolkaruza**
iOS and Android native developers have access to features that allow them to generate multiple apps from a single code base. At build time these features can help swapping out functionality, strings, assets, etc… 

The use cases can vary; One app for each city for a bike app, different imagery and text for a festival app framework, different app for each country for a B2B app, etc…

For iOS this can be done with targets and in Android you can use gradle flavors. Up until now there is no similar facility in React Native for assets and js files. Inspired by the —platform switch, we propose —infix as the way to generate multiple apps from a single react native javascript code base.

Allowing the packager server to receive a query parameter (```&infix=chicago```), causing the selection of files to check for this infix in the file names for assets and js files;

Choosing:
``` test.chicago.js ```
over
``` test.js ```

The functionality is tested and working in combination with platform, (```platform=ios&infix=chicago```)

Choosing:
``` test.chicago.ios.js ```
over
``` test.ios.js ```

See unit tests from line 6191 at ``` packager/react-packager/src/node-haste/__tests__/DependencyGraph-test.js ``` for cases.

Main changes in node-haste:
- ResolutionRequest
- getPlatformExtension 
- getAssetDataFromName

**Test Plan:**

Unit tests added for main cases on levels of packager, DependencyGraph, Bundler, AssetServer.

Manually tested on clean project and easily repeatable at this [example project](https://github.com/immidi/infixPrClientExample)

P.S. 
There is two unit tests failing, that were already failing before this PR but skipped because of another test suite in the file having an ``` fdescribe( ``` instead of a ``` describe( ```. I raised an issue #9192 about his but I'm not sure what to do with this is in the context of this PR. Simply disabling them seemed un-prudent.

P.P.S
Where to document this feature was not immediately obvious to me. If the core functionality is something you like, some guidance on documenting would be appreciated.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @davidaurelio and @frantic to be potential reviewers.

**Comment by bartolkaruza** [comment]
Implementation of : https://github.com/facebook/node-haste/issues/81
cc @brentvatne @davidaurelio @ide @nikki93 @cpojer

**Comment by bartolkaruza** [comment]
cc @deepaksisodiya @AbhishekCode

**Comment by cpojer** [comment]
I really believe we should **not** expand our module resolution algorithm to be even more custom. I would recommend to use a system similar to the `Platform` module and inline these things in code instead and use dead-code-elimination to get rid of unwanted code.

For small differences:

```js
if (App.is(MyApp)) {
  return <GreenButton />;
} else {
  return <RedButton />;
}
```

for big differences:

```js
if (App.is(MyApp)) {
  const GreenButton = require('GreenButton');
  return <GreenButton />;
} else {
  const RedButton = require('RedButton');
  return <RedButton />;
}
```

every change we make to our resolution algorithm requires all tooling to move along, like linters, flow, Jest, everything.

**Comment by cpojer** [comment]
Oh, also, can't you use platform extensions for this already or is the concern that you'd have to provide one file for all combinations of platform extensions?

Like, you could have a platform extension `myapp-ios` and `fooapp-android`. But as said, I guess the number of forks would explode then.

**Comment by bartolkaruza** [comment]
@cpojer Some of our immediate needs that are not covered by the examples you suggest are dynamic/conditional loading of Static Image Resources. From the docs:
```
// GOOD
<Image source={require('./my-icon.png')} />

// BAD
var icon = this.props.active ? 'my-icon-active' : 'my-icon-inactive';
<Image source={require('./' + icon + '.png')} />
```
**Bad** because the packager will not correctly load the image unless the path is known at package/bundle time.

Our apps have a lot of different image assets per app that need to be switched between depending on the specific app that is being bundled. Is there some other way we could prevent image resources from increasing app size other than using the native utilities (Xcode asset catalogs or Android drawable folder)?

Also, the [node-haste package is now back in the react-native repo](https://github.com/facebook/react-native/commit/667aaa4621a9f59b620cb17b39af8dd309ebd0da) because Jest does not use it anymore. Does this mean that jest, linter and flow all have specific code in them to accommodate the platform file switch in react-native? Or are they simply unaware of this react-native specific resolution and they would be unaware of the infix resolution similarly?

**Comment by javache** [comment]
I don't think this is something we'd want to adopt in React Native. Past experience has also shown us that automatically overriding certain modules in different apps leads to unmaintainable code. In fact, the whole .ios and .android suffix is a bit of an anti-pattern.

Instead prefer passing this all in from above. How about for each city you have a separate top-level container where you have an ApplicationConfig that is configured with the city-specific modules?

**Comment by bartolkaruza** [comment]
Ok, thank you for considering this. We are going to solve our problem using the [native](https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources) tooling provided for now.

**Comment by cpojer** [comment]
To answer your question about node-haste and Jest: we are working on consolidating our infrastructure and are planning to kill node-haste in favor of jest-haste-map and jest-resolve which yield better performance. See [Jest's packages](https://github.com/facebook/jest/tree/master/packages).

**Comment by bartolkaruza** [comment]
@cpojer @javache Having built up some knowledge on the packager while working on this functionality, I feel reluctant to just let that knowledge fade without adding anything useful to the project. Is there any part of the jest restructuring in combination with RN that I could add to that would be in line with your plans?

**Pull request closed without merging**
