### PR TITLE
[Animated] Export AnimatedInterpolation 

### PR DESCRIPTION
**Pull request by dvine-multimedia**
Export AnimatedInterpolation as "Interpolation" for the purpose of type checking in propTypes

### CODE REVIEW

**Comment by mkonicek** [comment]
@vjeux What do you think?

**Comment by Kureev** [comment]
Can you please rebase a PR, @dvine-multimedia?

**Comment by facebook-github-bot-6** [comment]
@dvine-multimedia do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by javache** [comment]
This pull request hasn't seen activity in a while. If you still want to merge this, please open a new pull request.

**Pull request closed without merging**
