### PR TITLE
bump Android NDK to r14b

### PR DESCRIPTION
**Pull request by dulmandakh**
Bump Android NDK to r14b.

NDK tool chain is set to GCC 4.9 (in *Application.mk* file), because clang fails to build RN.

Below are notable changes to r14b
> GCC is no longer supported. It will not be removed from the NDK just yet, but is no longer receiving backports.

and

> NDK_TOOLCHAIN_VERSION now defaults to Clang.

CI: https://circleci.com/gh/dulmandakh/react-native/573

Test Plan:
----------
Builds and runs as before

Release Notes:
--------------
[ANDROID] [ENHANCEMENT] [NDK] - bump version to r14b

### CODE REVIEW

**Comment by dulmandakh** [comment]
RN community, let's make it compile with clang 😄

**Comment by gengjiawen** [comment]
This pr https://github.com/facebook/react-native/pull/19536 bump ndk to 16, r13b maybe to old.

**Comment by dulmandakh** [comment]
IMHO, NDK 13 requires almost no change in source code and still builds the source code. I see it as a small, but non-disruptive step in supporting newer NDK versions and 64bit CPUs.

**Comment by dulmandakh** [comment]
Bumped NDK to r14b, which became possible with https://github.com/facebook/react-native/commit/8ce758f48adc263924db0349d3b7059e52fc0be7.

I couldn't build with versions above 14, and I'm not proficient enough in C++ to fix build errors.

CC: @hramos

**Comment by gengjiawen** [comment]
I still prefer to the latest ndk, since it's for all cpu arch, not just arm64.

**Comment by dulmandakh** [comment]
@gengjiawen me too, if you read through revision history NDK is not adding support for CPU architectures but removing them.

NDK is switched from GCC to Clang, GNU C++ standard library to Clang's libc++ and unified headers therefore it might require some code changes. For example, folly github page states that it requires GCC to build. If merged, we'll land clang, libc++ and unified headers to play with.

I think it's better to have small incremental changes rather than nothing or disruptive big change.

**Comment by dulmandakh** [comment]
Please review @hramos @mdvacca

**Comment by gengjiawen** [comment]
@ulmandakh I think the removed abi won't has effect for this project, since they removed the abi is no one used or deprecated as you can see https://github.com/android-ndk/ndk/wiki/Changelog-r17. I agree with we should small incremental changes, but I think the latest ndk is okay.

**Comment by dulmandakh** [comment]
Please review @fkgozali @hramos @mdvacca . Once merged I would like help with landing Unified Headers introduced in NDK r14 and default in r15.

* https://android.googlesource.com/platform/ndk.git/+/ndk-r14-release/docs/UnifiedHeaders.md
* https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeadersMigration.md

**Pull request closed without merging**
