### PR TITLE
[website] Streamline Getting Started Instructions

### PR DESCRIPTION
**Pull request by hramos**
The Getting Started guide is one of the first documents a new user will encounter. This pull request aims to minimize the amount of time it takes to get a React Native app up and running.

### Installing React Native
* The original section title, "Required prerequisites", is redundant. "Installing React Native" is a better description of what this section is about.
* Detailed installation instructions for each of the required tools are delegated to the first party instructions where available.
* If the installation instructions already take care of installing the latest version, there's no need to warn the user about the minimum required version.

### Recommending the use of package managers
* Assume the user is familiar with Homebrew or Chocolatey, and defer installation instructions to the package manager's website. The installation and explanation of what a package manager is is out of scope within this document.
* Link to Node.js package manager instructions and let savvy Linux users use the package manager native to their distro, instead of installing from NodeSource.

### Remove optional installs, and double down on highly recommended installs
* Optional installs distract the user from the goal, and have been removed.
* Flow and Nuclide are not required to use React Native, and have been removed from the Getting Started guide. Learning about static type checkers and a new IDE at the same time the user is picking up React Native can distract the user.
* Watchman is not necessarily required, but is extensively used within Facebook. If we think it is highly recommended to install it, then we should straight up tell the user to install it.

### Android Emulators
* Instructions about using Genymotion and other emulators have been removed when the text is not referring to an issue that is unique to React Native development.

### Debugging and Troubleshooting
* Troubleshooting tips have been moved out of the Getting Started and into the existing Troubleshooting doc that is already linked at the end of the guide. Focus on a great experience, and allow the user to dig deeper if and only if they run into trouble.
* Update Debugging and Troubleshooting tips to be consistent with its references to the Developer Menu and the various keyboard shortcuts.
* RedBoxes and YellowBoxes are one of the first things a user will encounter when their app has an error. Document these at the top.
* Reloading JavaScript and Live Reload can be documented together.
* When instructions for iOS and Android are provided, do not use an ordered list. Assume the user is interested in one platform or the other, in no specific order.

# Test plan

Website was generated locally and verified on Chrome v51.0.2704.84 OS X, Safari Version 9.1.1 (11601.6.17) OS X. The scope of the pull request is limited to copy changes and therefore testing on additional browsers is deemed unnecessary.

***Steps to generate website***
```
cd website
npm install
npm start
open http://localhost:8079/react-native/docs/getting-started.html
open http://localhost:8079/react-native/docs/debugging.html
open http://localhost:8079/react-native/docs/troubleshooting.html
```

### Getting Started: iOS on Mac
gettingstarted-ios-mac

### Getting Started: Android on Mac
gettingstarted-android-mac

### Getting Started: Android on Linux

gettingstarted-android-linux

### Getting Started: Android on OS X

gettingstarted-android-osx

### Getting Started: Android on Windows

gettingstarted-android-windows

### Debugging

debugging

### Troubleshooting

troubleshooting

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @grabbou to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
@hramos updated the pull request.

**Comment by caabernathy** [comment]
For consistency's sake (and future proofing), I recommend removing the detailed Android Studio instructions and linking off to the official Android docs. We could document best practices separately. This would make it consistent with the iOS instructions and mean we don't have to make updates for future Android SDK versions.

**Comment by caabernathy** [comment]
Looks great!

**Comment by JoelMarcey** [comment]
I would like to review this a bit as well --- for example, I noticed all the highly recommended installs (e.g., Nuclide) were taken out. I will go through the current diff and make comments inline as I have them.

**Comment by hramos** [comment]
@JoelMarcey Nuclide was removed as it is not required to use React Native. It makes sense to mention Nuclide elsewhere where using it provides a clear advantage (e.g. Debugging), but the Getting Started page is not the place to do that.

**Comment by JoelMarcey** [comment]
> It makes sense to mention Nuclide elsewhere where using it provides a clear advantage (e.g. Debugging), but the Getting Started page is not the place to do that.

@hramos I suppose that is fair enough. 

I am a little nervous about removing all the Android Studio setup instructions given that there are specific things you need to now hope are defaulted in the Studio setup process that are required for React Native (e.g., specific versions of the SDK tools, making sure you choose to have the Intel HAXM and Android Virtual Device checked and installed, etc.), but....

Let's just ship this and see what happens. I am down with simpler. We can always add stuff back if people get confused or the Android Studio default install causes chaos.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1616202052042080/int_phab) to review.

**Comment by JoelMarcey** [comment]
Let me know if you want this cherry-picked immediately into the current docs branch or you think waiting until the next RN push for it to go live is fine.

**Comment by hramos** [comment]
@JoelMarcey next RN push is fine.

The current Android Studio instructions guide the user through the installation of the latest API level Android SDK, as well as Intel HAXM. So far, that seems like a standard set of steps to get a basic Android development environment up and running. 

One of my worries is that including references to specific Android releases (such as Marshmallow) may lead to stale docs further down the line, when all that is necessary is to install a recent Android SDK (the [README](https://github.com/facebook/react-native/blob/master/README.md) already documents the minimum API level for savvier users with an existing Android dev environment).

Correct me if I'm wrong, but Intel HAXM does not appear to be a hard requirement. It does improve the experience of using the Android emulator, but I contend that documenting such tips falls outside the scope of a React Native Getting Started guide.

**Comment by JoelMarcey** [comment]
> Correct me if I'm wrong, but Intel HAXM does not appear to be a hard requirement. It does improve the experience of using the Android emulator, but I contend that documenting such tips falls outside the scope of a React Native Getting Started guide

Not a hard requirement, no. But could be a huge point of frustration without it. I think a Getting Started guide can provide both the absolute system requirements and some things that won't make people throw their hands in the air. You could argue, then, of course, that why aren't the things that reduce frustration just absolute requirements in the first place. That's another discussion.

But, let's see what people say when they use this new streamlined guide. Maybe we won't get any feedback about not mentioning some of the "nice to have" things.

**Pull request closed without merging**
