### PR TITLE
Extract fragment conversions to separate functions

### PR DESCRIPTION
**Pull request by cubuspl42**
## Summary:

Extract fragment conversions to separate functions to make refactoring easier and simplify reasoning about the code.

This code is being modified later.

This is a minor improvement in the context of my multi-PR work on https://github.com/react-native-community/discussions-and-proposals/issues/695.

## Changelog:

[INTERNAL] [CHANGE] - Extract fragment conversions to separate functions

### CODE REVIEW

**Comment by cubuspl42** [comment]
@robhogan Any chance you could review this?

**Review by robhogan — APPROVED** [review]
I understand these are being extracted for reuse in a PR coming soon? LGTM.

**Comment by cubuspl42** [comment]
@robhogan Kind of! I'm modifying the whole structure, adding another layer on top of fragments (the codename for that layer is "shards"). I'm doing all I can to make the diff of the upcoming "substantial" changes as easy to review as possible, so I'm submitting a wave of smaller PRs cleaning up the relevant codebase fragments.

**Comment by cubuspl42** [comment]
@robhogan Do you have the permissions to "import" this PR?

**Comment by cubuspl42** [comment]
@robhogan Thank you so much for the quick review! If you are in a reviewing mood, you can also take a look at one or two similar tiny PRs: [(my PRs)](https://github.com/facebook/react-native/pulls/cubuspl42) 😄

**Pull request closed without merging**
