### PR TITLE
Revert "Reverted commit D3417194"

### PR DESCRIPTION
**Pull request by bestander**
This reverts commit 7df2af58c78d57d95dc1577e489dc795bafe7ce8.

cc @janicduplessis

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1026608077376622/int_phab) to review.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1026608077376622/int_phab) to review.

**Pull request closed without merging**
