### PR TITLE
fix NullPointerException Caused by manageChildren

### PR DESCRIPTION
**Pull request by ASCE1885**

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @dmmiller and @janicduplessis to be potential reviewers.

**Comment by dmmiller** [comment]
There is a lot of random clean up in here in other files.  Can you remove that or do those as separate PRs?  Either way, this one should be focused on just fixing the NPE.

**Comment by dmmiller** [comment]
I'm also more concerned why we are getting a tag that doesn't match a view at this point rather than protecting against it.  Seems like something went wrong further up the stack we should fix.

**Comment by ASCE1885** [comment]
@dmmiller I have revert the other commits, you may try again,thx!

**Comment by dmmiller** [comment]
Thanks!

@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1723409581252427/int_phab) to review internal test results.

**Pull request closed without merging**
