### PR TITLE
[Website] Rename Support to Help, and re-style to better guide users to help themselves

### PR DESCRIPTION
**Pull request by hramos**
Duplicate of #9552 which failed to land internally.

### CODE REVIEW

**Comment by hramos** [comment]
@facebook-github-bot shipit-ninja

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @vjeux to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Normally, hramos, someone else should review and ship your pull request. However, we will trust that you know what you are doing. Shipping!

**Comment by facebook-github-bot-2** [comment]
Sorry, I can't do that @hramos - this feature is only supported for non-employees; you can land via the internal pull request dashboard.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
@hramos updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9796/files/5301c1bb93fd02cb5f0f59f2adc0986a9de36ccd..dbe2269f0ca3f66dfd58829a425e38743c2bffc9)

**Comment by facebook-github-bot-6** [comment]
@hramos updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9796/files/dbe2269f0ca3f66dfd58829a425e38743c2bffc9..42752587a2e3da0e95d6fc3d49ec813023b694e2) - [changes since last import](https://github.com/facebook/react-native/pull/9796/files/dbe2269f0ca3f66dfd58829a425e38743c2bffc9..42752587a2e3da0e95d6fc3d49ec813023b694e2)

**Pull request closed without merging**
