### PR TITLE
fix [Navigator] Wrong scene transformation after pop #9485

### PR DESCRIPTION
**Pull request by liusy182**
fix for #9485 

This bug can be reproduced by doing navigator transition `FloatFromRight` then `FadeAndroid` then do a `navigator.popToTop()`. 

The reason for the bug is because `FloatFromRight` specifies a translation for the scene but `FadeAndroid` does not (it only specifies opacity). As a result, `navigator.popToTop()` does not recover translation done by `FloatFromRight` properly, as the translation property will stay at last specified value (value of `FloatFromRight.transformTranslate.to`).

To fix this bug, we will provide a default `transformTranslate` property to `FadeIn` and `FadeOut` so that translation is able to recover.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @MengjueW and @neciu to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
@liusy182 updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9493/files/39aac88a4092adfa1fd46d9055536b1c0fda7696..0a23da08d593644c583235fe137b8599d502b42c)

**Comment by mkonicek** [comment]
@skevy Any opinions on this one?

**Comment by mkonicek** [comment]
Is the issue only with the fade animations? With this fix, would the default `transformTranslate` transform have to be added to other animation configs added in the future?

The solution in https://github.com/facebook/react-native/pull/9516 seems more generic?

**Comment by facebook-github-bot-3** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @MengjueW as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by hramos** [comment]
Ping @liusy182

**Comment by liusy182** [comment]
yes i think #9516 is a more proper fix.

**Pull request closed without merging**
