### PR TITLE
Remove CxxModuleWrapper.makeDSO

### PR DESCRIPTION
**Pull request by javache**
Summary: Changelog: [Internal][Removed] CxxModuleWrapper.makeDSO is not actively used and has been replaced by TurboModule infra.

Reviewed By: NickGerleman

Differential Revision: D50878589

### CODE REVIEW

**Comment by Sunbreak** [comment]
Why remove `makeDso` and leave `CxxModuleWrapper` behind?

Any further plan to remove `CxxModuleWrapper`?

**Comment by Sunbreak** [comment]
Here is an example to use `CxxModuleWrapper`'s `makeDso`

https://github.com/Sunbreak/reactnative-jsi.trial/tree/4ab32c06da932079e2d6e7acb4f13b168a71bce8/cxx-legacy

**Comment by javache** [comment]
@Sunbreak Usages of CxxModuleWrapper should be replaced with C++ TurboModules.

**Comment by Sunbreak** [comment]
> @Sunbreak Usages of CxxModuleWrapper should be replaced with C++ TurboModules.

Do you mean `legacy TurboCxxModule` or `pure TurboCxxModule`?

# legecy TurboCxxModule

> - `legecy TurboCxxModule` could be used in project with newArchEnabled=`false`
> - `legecy TurboCxxModule` needs a derived hybrid class from `CxxModuleWrapper.java/cpp` with `makeDsoNative`

[[ReactNative笔记]my-mod适配legecy TurboCxxModule](https://juejin.cn/post/7298170736480698368)

```cpp
class MyModModule
: public HybridClass<MyModModule, CxxModuleWrapper> {
  // ...
  static local_ref<MyModModule::javaobject> makeDsoNative(
      alias_ref<jclass>,
      const std::string& soPath,
      const std::string& fname) {
    // ...
    return MyModModule::newObjectCxxArgs(
        std::unique_ptr<CxxModule>((*factory)()));
  }
}
```

# pure TurboCxxModule

> - `pure TurboCxxModule` could only be used in project with newArchEnabled=`true`
> - `pure TurboCxxModule` needs to be registered inside APP's `TurboModuleManagerDelegate.cpp`

[[ReactNative笔记]my-mod适配pure TurboCxxModule](https://juejin.cn/post/7298167437526335488)

```cpp
std::shared_ptr<TurboModule> cxxModuleProvider(
    const std::string &name,
    const std::shared_ptr<CallInvoker> &jsInvoker) {
  if (name == "MyMod") {
    return std::make_shared<mymod::MyModCxxModule>(jsInvoker);
  }

  // Not implemented yet: provide pure-C++ NativeModules here.
  return nullptr;
}

// ...

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *) {
  return facebook::jni::initialize(vm, [] {
    facebook::react::DefaultTurboModuleManagerDelegate::cxxModuleProvider =
        &facebook::react::cxxModuleProvider;
    // ...
  });
}
```

**Comment by javache** [comment]
There's (legacy) C++ modules and C++ TurboModules. You're right that the latter currently require `newArchEnabled`.

`makeDSONative` was a helper method, which you may be able to copy over to your own repo. We've seen no usage of it internally and very limited externally. If you can't use TurboModules yet, you'll need to create a little C++ wrapper like below to expose it to Java.

```
@ReactModule(name = "MyCxxModule", isCxxModule = true)
public class MyCxxModule extends CxxModuleWrapper {
  static {
    SoLoader.loadLibrary("mycxxmodule");
  }

  public MyCxxModule() {
    super(initHybrid());
  }

  private static native HybridData initHybrid();
}
```

```
class JMyCxxModule
    : public jni::
          HybridClass<JMyCxxModule, react::CxxModuleWrapper> {
 public:
  static constexpr auto kJavaDescriptor =
      "Lcom/facebook/react/MyCxxModule;";

  static jni::local_ref<jhybriddata> initHybrid(jni::alias_ref<jclass>) {
    return makeCxxInstance(std::make_unique<MyCxxModule>());
  }

  static void registerNatives() {
    registerHybrid({
        makeNativeMethod(
            "initHybrid", JMyCxxModule::initHybrid),
    });
  }

 private:
  friend HybridBase;
  using HybridBase::HybridBase;
};

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(
        vm, [] {
    JMyCxxModule::registerNatives();
  });
}
```

**Pull request closed without merging**
