### PR TITLE
Show default `activeOpacity` value in docs.

### PR DESCRIPTION
**Pull request by joshuapinter**
Useful to know what the default value without having to dig into the library code.

### CODE REVIEW

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1075960132464579/int_phab) to review.

**Comment by joshuapinter** [comment]
@janicduplessis Thanks, Janic! 

Quick question: I have a couple of other PRs and I'm always a little confused with the process. Now that you've said "shipit" is there anything else that I need to do for it to get merged in or is it out of my hands? 

Thanks!

**Comment by janicduplessis** [comment]
@joshuapinter The shipit bot will import the diff and run it through facebook internal CI then if all these tests pass it will commit, sync it to github and close the PR.

If fb internal tests fail the bot will label the PR with 'import failed' after retrying a few times over ~1 day. So unless that happens, everything is good on your end :)

I don't know if this process is documented anywhere but it would be really nice if it was.

**Comment by joshuapinter** [comment]
@janicduplessis I agree! Thanks for giving me the run down. :)

**Comment by janicduplessis** [comment]
@joshuapinter Could you rebase on master looks like it failed some internal tests.

**Comment by mkonicek** [comment]
Merging again, the internal test failure seems unrelated.

**Pull request closed without merging**
