### PR TITLE
Further RNPM integration

### PR DESCRIPTION
**Pull request by grabbou**
This commit removes `rnpm` folder that we left during initial merge to keep the diff cleaner. The `core`, `link` and `install` have now the same directory structure as any other command to make development more natural for all of us. 

From most notable differences:
1) the `src` folder is now gone. The new structure should make it easier for people to work with the stuff and also move us closer to 100% rnpm integration,
2) There's also no `package.json` present in any of the `rnpm` packages, since they are no longer standalone modules,
3) There's no `bugs.url` in link.js since main package.json of React doesn't specify it. Decided to hardcode it to facebook/react-native since it's really unlikely to change. If one would prefer to use pkg.bugs.url as before, a separate PR modifying package.json should be sent.

### CODE REVIEW

**Comment by grabbou** [comment]
CC: @Kureev

**Comment by Kureev** [comment]
134 files, man 😵 

Is it possible to deliver it by chunks? Probably 10 PR by 13 files or so? ^^

**Comment by Kureev** [comment]
I'll try to take a look tomorrow tho

**Comment by grabbou** [comment]
> Is it possible to deliver it by chunks? Probably 10 PR by 13 files or so? ^^

I wouldn't consider path changes a big deal. What's the point of delivering it in 10 PRs?

**Comment by grabbou** [comment]
@Kureev, you should look at the diff first. There are no changes to code except moved files (counts as a file in a diff, but it's empty) and path changes (`src/` chunk removed from every path since it's now gone). 

There's nothing to review code-wise here in my opinion, just to check the new structure.

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Comment by Kureev** [comment]
I think CircleCI issue is not related to this change, so we can safely ship it

**Comment by facebook-github-bot-9** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3751115) to review internal test results.

**Pull request closed without merging**
