### PR TITLE
[ScrollView] [UIExplorer] Fixes #3060

### LINKED ISSUE #3060: Kitchen sink ScrollView bug
The second scrollView in the UIExplorer example project doesn't behave as expected.
Video https://youtu.be/MZUzuUR58mI

I would expect the cells within the scrollview to remain within the container. However it looks like some unintentional vertical scrolling is happening as well.

### PR DESCRIPTION
**Pull request by grabbou**
This pull request fixes a glitch that occurred when scrolling horizontally, as described in the #3060.

### CODE REVIEW

**Comment by grabbou** [comment]
Signed, I thought I did it already.

**Comment by ide** [comment]
Could you also set `automaticallyAdjustContentInsets={false}` while you're at it since we never want to set a top inset on this view anyway?

**Comment by grabbou** [comment]
Sure. No probs.

**Comment by ide** [comment]
(And squash commits :)

**Comment by grabbou** [comment]
Yeah, I am on it :dash:

**Comment by grabbou** [comment]
Done :) CC: @ide

**Comment by mkonicek** [comment]
Thanks for the fix!

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
