### PR TITLE
migrate ci to official docker

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
Simplify current build and offer it to community as official docker.
I have also created an [rfc](https://github.com/react-native-community/discussions-and-proposals/pull/36).
## Test Plan
pass all current ci.
## Related PRs
none
## Release Notes
 [GENERAL] [INTERNAL] [CI] - migrate ci to official docker

### CODE REVIEW

**Comment by gengjiawen** [comment]
@hramos `Collect Test Results` failed, but looks like not related to this pr.

**Comment by hramos** [comment]
Thanks for taking a stab at this. Happy to set up Docker accounts as needed. I'll try to review this sooner rather than later.

**Comment by gengjiawen** [comment]
@hramos ping.

**Comment by dulmandakh** [comment]
@gengjiawen where I can find Dockerfile for your image?

**Comment by gengjiawen** [comment]
Current build failure due to circle ci limit docker memory to 4GB.

**Comment by cpojer** [comment]
What's the status of this PR?

**Comment by gengjiawen** [comment]
wait for android ci fixed on master.

**Comment by gengjiawen** [comment]
cc @hramos @cpojer Please review.

**Comment by dulmandakh** [comment]
@gengjiawen this is huge milestone in Android CI. Congratulations 👏👍

**Comment by gengjiawen** [comment]
@dulmandakh Thanks for working with me for the docker build.

**Pull request closed without merging**
