### PR TITLE
feat: Added PixelRatio API example

### PR DESCRIPTION
**Pull request by Biki-das**
## Summary:
Added the [PixelRatio](https://reactnative.dev/docs/pixelratio) API to the RN tester app on the API list examples.

## Changelog:

[General] [Added] - Add examples for the Pixel Ratio API, with all the available methods.

## Test Plan:

**iOS** 

https://github.com/facebook/react-native/assets/72331432/dd481916-a8df-4a62-8f63-61936d886d33

**android**

https://github.com/facebook/react-native/assets/72331432/4d8d67dc-ddeb-4ca7-b61c-07522951f9ee

### CODE REVIEW

**Comment by Biki-das** [comment]
cc @hoxyq

**Comment by Biki-das** [comment]
friendly ping @hoxyq , must be good to go!

**Comment by hoxyq** [comment]
@Biki-das Could you please update Flow requirements from `@flow` to `@flow strict-local` for the new file?

This may require adding more types.

**Comment by Biki-das** [comment]
@hoxyq i have changed the file to ```@flow strict local```, no flow issues, seems like flow is happy with some changes!

**Pull request closed without merging**
