### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by nihgwu**
The link to `'ShadowPropTypesIOS'` in `View` and `Image` docs is broken since RN0.29

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @lacker to be potential reviewers.

**Comment by lacker** [comment]
Hmm, I stuck the if (filepath == 'ShadowPropTypesIOS') { return 'Shadow Props'; } in there so that the name on the left hand side would look like something logical. Is there a way to make the left hand bar still say "Shadow Props" but have the other links work?

**Comment by nihgwu** [comment]
@lacker I don't know much about the doc generation, actually there is no need to hiding `ShadowPropTypesIOS` from the left hand bar and the will be `ShadowPropTypesIOS` in there, but I've noticed that `Transform` is in `HIDDEN_COMPONENTS` list and I think they are quite the same in some way, so I did it.

**Comment by nihgwu** [comment]
@lacker done with the side menu, and I also redirect `LayoutPropTypes` to `Layout Props` instead of `FlexBox` as it's already in the `THE BASICS`, but I'm still wondering why `Layout Props` and `Shadow Props` are in `APIS` group ( or why `Transform` is hidden from there)

**Comment by nihgwu** [comment]
ping @lacker

**Comment by lacker** [comment]
They are just in the API group because they used to be and I didn't see any more-logical place to put them. They are kind of APIs? They are certainly not components.

Anyway this LGTM but it looks like you need to merge into the latest base branch before shipping.

**Comment by facebook-github-bot-4** [comment]
@nihgwu updated the pull request.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/513705468839718/int_phab) to review internal test results.

**Pull request closed without merging**
