### PR TITLE
Update Showcase with Geektime mobile app, based on RN.

### PR DESCRIPTION
**Pull request by avishayil**
- Update Showcase with Geektime mobile App.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @alexleventer to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
@avishayil updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9621/files/3628a56d70415ed2b60fdb4a809d14fabddfa796..457d0e27f5daff6acb313fcaa9723d0f7315197a)

**Comment by facebook-github-bot-7** [comment]
@avishayil updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9621/files/3628a56d70415ed2b60fdb4a809d14fabddfa796..457d0e27f5daff6acb313fcaa9723d0f7315197a)

**Comment by hramos** [comment]
Thanks for sending this pull request. According to the guidelines in that file, "infoLink" must be one of:

 1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native

I am going to close this, but if you have one of those two things, feel free to reopen with a new link.

**Pull request closed without merging**
