### PR TITLE
Docs - explain how to access the geolocation API

### PR DESCRIPTION
**Pull request by rh389**
Explain that, unlike other APIs, geolocation follows the browser spec and is exposed through `navigator.geolocation` rather than as an `react-native` export.

This can be inferred from the example code but isn't otherwise stated in the docs. See also https://github.com/facebook/react-native/pull/9793

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @davidaurelio to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@rh389 updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9810/files/9fcb586aa73476339dc9ffccea4d3ab198d88821..11bd4688a1bf3bdd663f89a0fee39308adc3ed79)

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Something went wrong when importing this pull request. Please cc someone from the team at fb to help with importing this.

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3841341) to review internal test results.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3841341) to review internal test results.

**Pull request closed without merging**
