### PR TITLE
Add boost.podspec speed up download time & reduce size of the package

### PR DESCRIPTION
**Pull request by itchingpixels**
## Motivation

Speed up download time & reduce size of the `boost` dependency. This closes https://github.com/facebook/react-native/issues/16381

## Test Plan

1. Install react-native via Cocoapods (or move a helloWorld react-native application over to use Cocoapods for dependency management)
2. Add CxxBridge instead of BatchedBridge to your Podfile
3. run `pod install`
4. run `react-native run-ios`

## Release Notes
 [IOS] [FEATURE] [third-party-podspecs] - added boost.podspec

### CODE REVIEW

**Comment by itchingpixels** [comment]
this should be ready to go, I'm not sure whom to ping regarding the review.

**Comment by bestander** [comment]
Ok, got a comment from @mhorowitz, he is super busy with an important project.
I'll just paste here:
"... looks like they're trying to make the cocoapods integration use the same subset of boost that the standard android and ios OSS builds use.  If it's the same version, and it actually works, I don't see why not."

So let's land and if anything gets broken we'll revert

**Comment by bestander** [comment]
The failed CI seems unrelated, `ci/circleci: test-objc-ios` passes

**Comment by itchingpixels** [comment]
hi! are there any news on this? are you referring to the public react - native 's project master?

**Comment by CFKevinRef** [comment]
I'm not sure I understand why the podspec is being added to *this* repo when it represents a self-contained external dependency, available in full at https://github.com/react-native-community/boost-for-react-native/

Would it be better to add the podspec to that repo, and simply reference it from here?

There is an open issue: https://github.com/react-native-community/boost-for-react-native/issues/3

**Comment by bestander** [comment]
@CFKevinRef if you can add the podspec to that repo without making changes here then yeah send a PR, I'll merge it.

Otherwise looks like master branch is fixed now and I can try landing this diff afain

**Comment by bestander** [comment]
https://github.com/react-native-community/boost-for-react-native/pull/4 seems like an easier fix.
Let's merge it there.
Closing this PR, sorry on behalf of our CI :)

**Pull request closed without merging**
