### PR TITLE
Report size of app bundles on PRs

### PR DESCRIPTION
**Pull request by tido64**
## Summary

Report size of app bundles on PRs. See [React Native Benchmark Suite](https://github.com/react-native-community/discussions-and-proposals/issues/186) for further discussion.

## Changelog

[Internal] [Added] - Report size of app bundles on PRs

## Test Plan

PRs should start seeing comments from a bot with app bundle sizes, given that they got built successfully.

### CODE REVIEW

**Comment by tido64** [comment]
This is still a work in progress. You can review it now but do note that it may change often while I work things out.

**Comment by hramos** [comment]
Making a slight adjustment - moving octokit/rest from a devDependency in the root package.json, to the bots/package.json file should work as well. It also keeps us from having to add octokit to our internal yarn offline mirror (which is based off the root package.json).

I couldn't update bots/package.json in your PR so the latest CI run will likely fail, but you may safely ignore that. I already made these changes internally.

**Comment by tido64** [comment]
@hramos Thanks for reviewing this! Don't we also have to add an extra step to install the dependencies under `bots/`? That's where I had it originally but it failed and I wasn't sure what the right approach is. Since you've bumped the version number, should we also fix the deprecation warnings?

**Comment by hramos** [comment]
Merged! Yes, we should fix the deprecated warnings. I also filed https://github.com/facebook/react-native/issues/28043 as a related item that came up while testing this.

**Pull request closed without merging**
