### PR TITLE
Added ruby as requirement

### PR DESCRIPTION
**Pull request by davidhellsing**
Ruby is needed to run the init, or you will get a syntax error

### CODE REVIEW

**Comment by amasad** [comment]
I really don't want us to add more items to the requirement list. It would
be awesome if you can port the ruby script to node!

**Comment by vjeux** [comment]
Ruby is installed by default on mac os and this is the only platform to run the project on (thanks xcode!). I'm curious, why didn't you have ruby?

**Comment by jordwalke** [comment]
If this only updates the guide to accurately reflect what is required, that seems fine but:
1. Why do we need ruby? Can we not?
2. Can whatever ruby does be ported to JS?

**Comment by vjeux** [comment]
@jordwalke: we only have one script and it doesn't need ruby, need someone to clean it up.

**Comment by frantic** [comment]
#440

**Pull request closed without merging**
