### PR TITLE
[Docs] Add note about JS names for exported methods and RCT_REMAP_METHOD

### PR DESCRIPTION
**Pull request by ide**
Described how JS method names are derived from Obj-C selectors and mention RCT_REMAP_METHOD.

### CODE REVIEW

**Comment by brentvatne** [comment]
:+1: - nice one @ide

**Comment by frantic** [comment]
:cool:

**Comment by ide** [comment]
This PR documents a macro added in #802 so this newly documented feature won't be available until that PR is merged.

**Comment by brentvatne** [comment]
@ide - oh hm I thought this meant that PR was merged already, my bad on :+1:'ing

**Comment by nicklockwood** [comment]
It's now merged.

**Pull request merged**
