### PR TITLE
CI: use react-native-android:2020-6-4 docker image

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

In https://github.com/react-native-community/docker-android/commit/b9ea45f3c56dc7ecca80883923bd5cc94c8579e7, we bumped Buck to 2020.05.14.01, NDK to 20.1.5948944.

## Changelog

[Internal] [Changed] - CI: use react-native-android:2020-6-4 docker image, with Buck 2020.05.14.01 and Android NDK 20.1.5948944

## Test Plan

CI must be green

### CODE REVIEW

**Comment by gengjiawen** [comment]
`test_android` is failing since the avd not start, I am restarting it to see retry result.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/issues/28870

**Comment by fabriziobertoglio1987** [comment]
I checkout out your branch head [`57993a5110`](https://github.com/dulmandakh/react-native/commit/57993a5110658ca28f3e6529ffdc2536f3b327cf) and I run locally 

```
➜  react-native git:(57993a5110) source scripts/android-setup.sh && launchAVD
emulator: WARNING: encryption is off
emulator: INFO: VideoFrameSharer.cpp:76: Initialized handle: videmulator5554
emulator: INFO: WebRtcBridge.cpp:263: Launching: /home/fabrizio/Android/Sdk/emulator/goldfish-webrtc-bridge --daemon --logdir /tmp/android-fabrizio --port 34377 --handle videmulator5554 --turn
emulator: INFO: WebRtcBridge.cpp:273: Launched /home/fabrizio/Android/Sdk/emulator/goldfish-webrtc-bridge --daemon --logdir /tmp/android-fabrizio --port 34377 --handle videmulator5554 --turn  , pid:21958
emulator: WARNING: EmulatorService.cpp:448: Cannot find certfile: /home/fabrizio/.android/emulator-grpc.cer security will be disabled.
E0608 11:23:49.186321122   21941 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1591608229.186287598","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
Started GRPC server at 127.0.0.1:8554
```
At the same time I run in another session `waitForAVD` and it works fine

```
➜  react-native git:(57993a5110) source scripts/android-setup.sh && waitForAVD
Waiting for Android Virtual Device to finish booting...
boot animation status=stopped
Android Virtual Device is ready.
```

Output without running `launchAvd` command

```
➜  react-native git:(57993a5110) ✗ source scripts/android-setup.sh && waitForAVD
Waiting for Android Virtual Device to finish booting...
boot animation status=adb: no emulators found
boot animation status=adb: no emulators found
boot animation status=adb: no emulators found
```

**Comment by hramos** [comment]
I've rebased on top of master. `test_android` failing at the AVD creation step, it looks like we might need to adjust that:

```
source scripts/android-setup.sh && launchAVD
emulator: WARNING: encryption is off
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
E0925 00:22:26.296880951     586 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1600993346.296870234","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```

https://app.circleci.com/pipelines/github/facebook/react-native/6481/workflows/495a3e4d-ce2b-4604-8a24-d6afa2338339/jobs/169310

**Comment by fkgozali** [comment]
@dulmandakh let's update this per @hramos' comment, then we can merge other pending PRs that are waiting for this.

Also, should we update the image to include NDK v21 based on discussion in #29013?

**Comment by dulmandakh** [comment]
I'll add NDK 21 on top of 20 to facilitate migration, and update this PR very soon. Thanks

**Pull request closed without merging**
