### PR TITLE
docs(android): install release for android

### PR DESCRIPTION
**Pull request by yutin1987**
maybe, it is a better command.

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks! Good idea to use the `--variant=release` :) Does it do the release build under the hood? Can you please paste full gradle logs somewhere showing it's building the release build?

Make sure you kill the packager (local dev server) before running `react-native run-android --variant=release`. Is the JS packaged inside the app? If the app is running correctly then it is.

There's a line below you'll need to update too:

> Note that `installRelease`

**Comment by facebook-github-bot-3** [comment]
@yutin1987 updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@yutin1987 updated the pull request.

**Comment by yutin1987** [comment]
Thank @mkonicek for your reminder

https://github.com/facebook/react-native/blob/master/local-cli/runAndroid/runAndroid.js#L85
`install + release = installRelease`

gradle logs
image

**Comment by satya164** [comment]
LGTM

@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3674229) to review internal test results.

**Pull request closed without merging**
