### PR TITLE
Add 惠首尔(huiseoul) to showcase

### PR DESCRIPTION
**Pull request by johnwook**
> It also must be useful considering that the majority
of readers only speak English. So, each app in the showcase should link to either:
1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native
For each app in the showcase, use infoLink and infoTitle to reference this content.

- We wrote a technical post on [medium](https://engineering.huiseoul.com/building-a-conversational-e-commerce-app-in-6-weeks-with-react-native-c35d46637e07#.776ll9ram)
- My company was funded, also. Reference [#1](http://besuccess.com/2015/08/huiseoul/), [#2](https://www.crunchbase.com/organization/trillionaire#/entity)

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @alexleventer to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by lacker** [comment]
Is there an English-language name we could use for the app? Or maybe both English + Chinese in conjunction? Just trying to make sure this page works for an English-language audience.

**Comment by johnwook** [comment]
@lacker Hi, thanks for prompt reply. Yes we have one. You can call our service `Huiseoul(惠首尔)`. Do you want me to update this PR to use that name? :)

**Comment by facebook-github-bot-9** [comment]
@johnwook updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9807/files/8954a5b1a1e9855095a927d57c5474e6482c0bea..2417fda9da02c64de5c9b2d174b3a0e54c0789a8)

**Comment by facebook-github-bot-6** [comment]
@johnwook updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9807/files/2417fda9da02c64de5c9b2d174b3a0e54c0789a8..40bd9f368856a8bbcebf3e0a29b8da3698fb6aa7)

**Comment by facebook-github-bot-4** [comment]
@johnwook updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9807/files/2417fda9da02c64de5c9b2d174b3a0e54c0789a8..40bd9f368856a8bbcebf3e0a29b8da3698fb6aa7)

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3843024) to review internal test results.

**Pull request closed without merging**
