### PR TITLE
Fixed trunk: Libraries/Image/Image.android.js

### PR DESCRIPTION
**Pull request by bestander**
Set up proper path to emptyfunction

Test Plan:
- Circle CI

### CODE REVIEW

**Comment by bestander** [comment]
will ninja land to fix trunk

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @andreicoman11 and @ide to be potential reviewers.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
Oh damn, new feature

**Pull request closed without merging**
