### PR TITLE
Make the CLI recognize CRNA projects

### LINKED ISSUE #14828: run app on a device is throwing an error index.android.js not found
### Is this a bug report?

yes

### Have you read the Bugs section of the Contributing to React Native Guide?

yes

### Environment
MacOS

1. `react-native -v`: react-native-cli: 2.0.1 react-native: 0.45.1
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): MacOS
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):

### Steps to Reproduce

(Write your steps here:)

1. run `create-react-native-app AwesomeProject`
2. run `react-native run-android`
3. then you can see this error

### Expected Behavior

I hope it will work

### Actual Behavior

error cannot found index.android.js or index.ios.js
photo_2017-07-04_16-55-21

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

I have tried solution from: #3442, #5174, #14246  did not work

### PR DESCRIPTION
**Pull request by fson**
1. Make running `react-native run-ios` or `react-native run-android`
inside a project created with Create React Native App run the
corresponding react-native-scripts command instead of failing.

    **Before**:
    screen shot 2017-07-21 at 16 55 32screen shot 2017-07-21 at 16 55 52
    **After**:
    screen shot 2017-07-21 at 16 52 15

2. Make running `react-native link` inside a CRNA project display a
helpful error message.

    **Before**:
    screen shot 2017-07-21 at 16 55 10
    **After**:
    screen shot 2017-07-21 at 16 53 10

Fixes #14828.

## Test plan:

* Run `react-native run-ios`, `react-native run-android` and `react-native link` in:
  * A CRNA project (screenshot above)
  * A traditional RN project (existing behaviour)
  * A folder that contains neither (existing behaviour)

### CODE REVIEW

**Comment by dikaiosune** [comment]
:100:

One thing I wanted to point out is that some people who eject from CRNA don't follow the instructions to delete node_modules and reinstall (*most* things continue to work), which means that they might be a bit confused by this error. Including a "if you ejected and are seeing this reinstall n_m" bit for the error could be good?

@brentvatne maybe CRNA should just delete things on behalf of users instead of https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/scripts/eject.js#L223-L224 ? Could be a bit invasive or problematic though.

**Comment by fson** [comment]
@dikaiosune You shouldn't be able see this error after ejecting, because we only look for `react-native-scripts` if we can't find a React Native Android/iOS project in the folder. After ejecting those will exist.

**Comment by Kureev** [comment]
CI is failing, although I think it isn't your fault:

> Wrong version of Flow. The config specifies version ^0.49.1 but this is version 0.50.0
Flow check does not pass
Killing packager 2413

Therefore I feel safe to push it through

**Comment by Kureev** [comment]
@facebook-github-bot ship it

**Comment by fson** [comment]
I wonder why the bot isn't importing this. Is it because the CI is still failing?

**Comment by Kureev** [comment]
Hm, looks like it. I think we can ping @hramos directly in this case :)

**Comment by hramos** [comment]
It's `shipit`, one word. But there's a problem importing these PRs we haven't solved yet.

**Comment by Kureev** [comment]
Ok, seems something went wrong. Can we have some insights so we can fix it? @hramos

**Comment by hramos** [comment]
We've had some unrelated internal tests block all of our imports for the last day or two. Working through them right now...

**Comment by grabbou** [comment]
Shall we cherry-pick this?

**Pull request closed without merging**
