### PR TITLE
Fix Unexpected token ) in babel-preset-react-native

### LINKED ISSUE #15513: [android / ios] bundling failed: "TransformError
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
1. `react-native -v`:
react-native-cli: 2.0.0
react-native: n/a - not inside a React Native project directory
(I was inside the folder, version is: 0.47.1)
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version`: 0.17.10

Then, specify:
- Target Platform: Android, iOS
- Development Operating System: macOS Sierra 10.12.6
- Build tools: Using Xcode 8.3.3 and Android Studio 2.3

### Steps to Reproduce
1. `react-native init rn_reproduce_transform_error`
2. `cd rn_reproduce_transform_error`
3. `react-native run-ios` or `react-native run-android`

### Expected Behavior
Should show the default "Welcome to React Native!" screen.

### Actual Behavior
bundling failed: "TransformError: /Users/eduardo/Desktop/rn_reproduce_transform_error/index.ios.js: Unexpected token ) (While processing preset: \"/Users/eduardo/Desktop/rn_reproduce_transform_error/node_modules/babel-preset-react-native/index.js\")"

Same error occurs when I tried to update RN version to 0.48.0-rc.1
SyntaxError: Unexpected token )

### Reproducible Demo
https://github.com/esganzerla/rn_reproduce_transform_error

### Notes
- This happens both on android and iOS.
- I saw some people having the same problem on issue #15496.

### PR DESCRIPTION
**Pull request by charpeni**
Fixes #15513 

cc @jeanlauliac

### CODE REVIEW

**Comment by charpeni** [comment]
cc @cpojer

**Comment by TheSavior** [comment]
Good find! We really should have a linter that disallows @format in this repo until we configure prettier to not require trailing commas in this repo. cc @zertosh @vjeux

**Comment by TheSavior** [comment]
Thanks for contributing!

**Comment by jeanlauliac** [comment]
Thank you very much. We still need to release `v3.0.1` of the package afaik.

This problem is caused by the fact I tested on Node 8 and it didn't come to my mind there could be incompatibilities showing up with older versions.

**Comment by TheSavior** [comment]
There are a bunch more cases that I'm fixing internally and then we will probably need to release a few packages.

**Comment by javache** [comment]
fyi, the end-to-end test is also failing with this error: https://travis-ci.org/facebook/react-native/jobs/268332171

**Comment by jeanlauliac** [comment]
Ugh, I suspect this is because the `babel-preset-react-native@2.0.1` is including some breaking changes, along with incorrect syntax? I don't know why this version was released, I'll look into it and release a `2.2.0`, since `2.1.0` was already released on 2017-07-05.

**Pull request closed without merging**
