### PR TITLE
Fix NPE in Android Switch during measure

### LINKED ISSUE #16000: Switch of android will cause a NullPointerException
### Is this a bug report?

(Yes)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(No)

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: 6.11.1
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: Android

- Development Operating System: macOS

- Build tools: Android Studio

### Steps to Reproduce

(Write your steps here:)

1. using library `com.android.support:appcompat-v7:24.2.1`
2. using component `<Switch />`

### Expected Behavior

display a `Switch` component

### Actual Behavior

switch-crash

### Reason
switch-reason

from this picture, `line 59` and `line 102` create instance of ReactSwitch; 

the difference: 
1. the first one hasn't called `setShowText(false)`, it will get the error of the red box, while calling `measure`.
2. the second one has called `setShowText(false)`, that's right.

how to fix:

follow `line 59`, insert a new line `reactSwitch.setShowText(false);`

if using `com.android.support:appcompat-v7:23.0.1`, it will not get this error; but i think this error can be avoided without downgrading `appcompat-v7` library. Sorry for my poor english, thank you!

### PR DESCRIPTION
**Pull request by 4ndroidev**
Fixes #16000

see [Issue #16000](https://github.com/facebook/react-native/issues/16000) 
fix a null pointer exception while using higher version 'com.android.support:appcompat-v7'

## Test Plan
N/A

## Release Notes

[ANDROID][BUGFIX][Switch] - Fix NPE in Android Switch during measure

### CODE REVIEW

**Comment by shergin** [comment]
@4ndroidev Could you please sing CLA?

**Comment by 4ndroidev** [comment]
@shengmin Sorry, I have already signed in CLA.

**Comment by Fortidude** [comment]
okey, what about ping? This is annoying :/

**Comment by hey99xx** [comment]
I believe this is also fixing https://github.com/facebook/react-native/issues/12359

**Comment by janicduplessis** [comment]
Looks good, sorry about the delay reviewing this!

Just updated the PR title since that will be the commit message and added release notes.

@facebook-github-bot shipit

**Pull request closed without merging**
