### PR TITLE
Bump Robolectric to 3.6.1

### PR DESCRIPTION
**Pull request by dulmandakh**
This PR bums Robolectric version to 3.6.1, which is the latest version we can have due to that later versions require SDK 27 or above.

**Notable changes**:
* Robolectric 3.3 improved Android support, please see http://robolectric.org/blog/2017/03/02/robolectric-3-3-and-roadmap/.
* Starting with 3.6 version they are adding support for resources http://robolectric.org/blog/2017/11/13/resources-for-real/.

Notes, I'll try to bump testing tools in near future. Then try to cleanup or refactor some RN tests.

Test Plan:
----------
Tests run and succeed as normal.

Release Notes:
--------------
[ANDROID] [ENHANCEMENT] [Robolectric] - Bump version to 3.6.1

### CODE REVIEW

**Comment by hramos** [comment]
Tests are all passing, thanks for the PR! I'll import this.

**Comment by dulmandakh** [comment]
I watched Android testing videos from Google IO and test code looks so clean. So thought that need to bump testing tools then cleanup tests, maybe write some tests. Also I found that most guides and examples for Android Testing use newer version of tools we have, which makes writing test a little bit harder.

**Comment by dulmandakh** [comment]
This might help http://robolectric.org/migrating/

**Comment by hramos** [comment]
Looks like this will require some additional work to land internally. 

```
Summary: 
stderr: ReactAndroid/src/test/java/com/facebook/react/modules/dialog/DialogModuleTest.java:26: error: package org.robolectric.android.controller does not exist
ReactAndroid/src/test/java/com/facebook/react/modules/dialog/DialogModuleTest.java:35: error: cannot find symbol
  private ActivityController<Activity> mActivityController;
          ^
  symbol:   class ActivityController
  location: class com.facebook.react.modules.dialog.DialogModuleTest
stderr: ReactAndroid/src/test/java/com/facebook/react/modules/share/ShareModuleTest.java:34: error: package org.robolectric.shadow.api does not exist
ReactAndroid/src/test/java/com/facebook/react/modules/share/ShareModuleTest.java:85: error: cannot find symbol
      ((ShadowApplication) Shadow.extract(RuntimeEnvironment.application)).getNextStartedActivity();
                           ^
```

**Comment by dulmandakh** [comment]
@hramos here is the migration guide http://robolectric.org/migrating/

**Comment by hramos** [comment]
Re-importing, but just want to note that this will not land for a while, as there is some manual effort required on our end. I'll add it to my never-ending queue...

**Pull request closed without merging**
