### PR TITLE
Add CircleCI tests for use frameworks

### PR DESCRIPTION
**Pull request by cipolleschi**
Summary:
In 0.71.0-RC.2, we had a regression in `use_frameworks!`.

This adds some CircleCI jobs to make sure we do not regress on those. It also updates the template to support these tests.

## Changelog
[iOS][Added] - CircleCI jobs to keep the use_framework! setup in check for the Old Arch

Differential Revision: D41551288

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This is fantastic - adding the use_frameworks CI job at least up to the point of what we know *should* work (static linkage, -Flipper, -NewArch) should be a big help, and you've got the infra in at the same time to toggle those on as possible in the future. Huge +1

**Comment by mikehardy** [comment]
Huh - seems like JSC has some other problem, maybe related? I don't know I have been testing with hermes on for quite some time now (a couple react-native releases) so I'm not sure if this is a prior regression in 0.70 or 0.71-rc or from this PR

```
CompileC /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/Objects-normal/x86_64/JSIDynamic.o /tmp/iOSTemplateProject/node_modules/react-native/ReactCommon/jsi/jsi/JSIDynamic.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-jsidynamic' from project 'Pods')
    cd /tmp/iOSTemplateProject/ios/Pods
    /Applications/Xcode-14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-ios12.4-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu++14 -stdlib\=libc++ -fmodules -gmodules -fmodules-cache-path\=/Users/distiller/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/distiller/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=jsi -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -isysroot /Applications/Xcode-14.0.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Index.noindex/DataStore -iquote /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/jsi-generated-files.hmap -I/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/jsi-own-target-headers.hmap -I/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/jsi-all-non-framework-target-headers.hmap -ivfsoverlay /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/all-product-headers.yaml -iquote /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/jsi-project-headers.hmap -I/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/React-jsidynamic/include -I/tmp/iOSTemplateProject/ios/Pods/boost -I/tmp/iOSTemplateProject/ios/Pods/RCT-Folly -I/tmp/iOSTemplateProject/ios/Pods/DoubleConversion -I/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/DerivedSources-normal/x86_64 -I/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/DerivedSources/x86_64 -I/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/DerivedSources -F/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/React-jsidynamic -F/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/DoubleConversion -F/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/RCT-Folly -F/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/React-jsi -F/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/fmt -F/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/glog -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -include /tmp/iOSTemplateProject/ios/Pods/Target\ Support\ Files/React-jsidynamic/React-jsidynamic-prefix.pch -MMD -MT dependencies -MF /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/Objects-normal/x86_64/JSIDynamic.d --serialize-diagnostics /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/Objects-normal/x86_64/JSIDynamic.dia -c /tmp/iOSTemplateProject/node_modules/react-native/ReactCommon/jsi/jsi/JSIDynamic.cpp -o /Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsidynamic.build/Objects-normal/x86_64/JSIDynamic.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/React-jsidynamic.build/Objects-normal/x86_64/JSIDynamic.o
In file included from /tmp/iOSTemplateProject/node_modules/react-native/ReactCommon/jsi/jsi/JSIDynamic.cpp:8:
/tmp/iOSTemplateProject/node_modules/react-native/ReactCommon/jsi/jsi/JSIDynamic.h:11:10: fatal error: 'jsi/jsi.h' file not found
#include <jsi/jsi.h>
         ^~~~~~~~~~~
/tmp/iOSTemplateProject/node_modules/react-native/ReactCommon/jsi/jsi/JSIDynamic.h:11:10: note: did not find header 'jsi.h' in framework 'jsi' (loaded from '/Users/distiller/Library/Developer/Xcode/DerivedData/iOSTemplateProject-aohwrowpvresgmgsahuobbtcwdbo/Build/Products/Debug-iphonesimulator/React-jsidynamic')
1 error generated.
```

https://app.circleci.com/pipelines/github/facebook/react-native/18053/workflows/8c1fc885-9488-4f2e-b006-1e219e043c2c/jobs/374631?invite=true#step-111-933

My own local test (with this PR included via this patch ) just finished though - results

1- :heavy_check_mark:  ios debug + old arch + hermes + static frameworks
2- :heavy_check_mark: ios release + old arch + hermes + static frameworks
3- :x: macCatalyst debug + old arch + JSC + static fraemworks

It had this issue you noted in the road to 0.71 discussion:

> build/generated/ios/FBReactNativeSpecJSI.h can't find <react/bridging/Bridging.h>

:thinking: You mentioned that "was a dirty setup", I'm not sure what you mean by that? In the past I have not had to do any deep cleaning between my iOS build runs and my macCatalyst build run. Is there something that needs cleaning now?

**Comment by cipolleschi** [comment]
So, the two problems are different:

1. JSC => The problem is that we tried to split JSI and JSIDynamic in two different pods/modules. It didn't work, so tomorrow I'll put the two back together. I tried this locally in an app and it seems to work. So, after this change, we should have the whole situation under control (and tests! 🎉 )

2. Dirty setup => I still have to investigate why, but multiple execution of `pod install` generated a `FBReactNativeSpecJSI.h` and `FBReactNativeSpecJSI-generated.mm` that should not be there in the old architecture - at least I think so. 😅  
I don't know why this is happening, but the solution so far was to `rm -rf build && bundle exec pod install`. 

The fun fact is that in 0.71-stable, cocoapods should do a cleanup as [first step](https://github.com/facebook/react-native/blob/0.71-stable/scripts/react_native_pods.rb#L64) but it's not working properly... I need to fix that as well.

**Comment by mikehardy** [comment]
I did this:

```bash
\rm -fr ios/build ios/Pods
npx pod-install
```

...and I'm rebuilding successfully for macCatalyst now (still using the patch from this PR) and that seems to work. So there is some sort of "you need to clean things out" requirement that's somewhat new versus react-native 0.70

**Comment by mikehardy** [comment]
I just re-checked and my macCatalyst build is actually also Hermes, so I have not been touching JSC for quite some time, my 3rd report result up there is thus a mix of a real problem and a phantom (though the JSC problem *does* exist as seen by CI here, I wasn't seeing it)

With the extra "clean" steps, and this PR diff I think I'll have my build demo at least going through cleanly, but (and this is a good thing!) the CI here will now be a *superset* of my build demo, which is a nice end result + good progress, even apart from the actual fixes here

**Comment by mikehardy** [comment]
:heavy_check_mark: All checks have passed -> :trophy: @cipolleschi thank you!

**Comment by gosham2016** [comment]
Класс

**Pull request closed without merging**
