### PR TITLE
allow for dark background in the debugger view

### PR DESCRIPTION
**Pull request by pvinis**
I prefer a darker environment when coding, and having the Chrome window be dark except the part that I cannot hide, is making my eyes hurt. This is for the people that prefer the darker color scheme when developing.

### CODE REVIEW

**Comment by pvinis** [comment]
i dont see why the tests are failing.. its not from my changes i think?

**Comment by hramos** [comment]
Can you add some screenshots that show the new dark mode as well as the settings window with the checkmark? Also, can you provide a test plan, e.g. How did you test this?

**Comment by pvinis** [comment]
first one is as it is now (plus the checkbox), image and the next one is the new dark one.
image

**Comment by pvinis** [comment]
well, i dont know how to test this.. its just changing the css. does this screen have any other tests? maybe i could get some idea from that, if there is anything.

**Comment by hramos** [comment]
Test plan doesn't necessarily require adding tests. When you open a new PR, there's a template with all the info we need, including a test plan describing how this change was tested.

**Comment by pvinis** [comment]
ok, yes. well, as i wrote, i wanted a darker environment, and i made a simple one. then i tested by actually clicking in the checkbox to make sure its working. i used it for a whole day and it felt much easier on the eyes.

**Comment by mkonicek** [comment]
Thanks for adding the test plan (screenshots). Merging.

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by pvinis** [comment]
i will rebase it and see if that helps..

**Pull request closed without merging**
