### PR TITLE
Making babel to use the babelrc file if we find it

### PR DESCRIPTION
**Pull request by benhughes**
This PR tells babel where the babelrc file is if it has been found in the project root. I know you guys are relying on babel to find it when you tell babel the filename and sourceFilename, this works fine in normal js/node projects, here is an example where this will not work.

We have a big repo that can contain a few react-native / js projects. Our build system is similar to BUCK and we keep our third party dependencies in a separate folder (having a global package.json at the project route is not feasible as everyone will have to install every apps dependencies even when they don't need them), the structure looks a bit like this:

`third_party/js/.` packages from node_modules
`common/js/` common code used by numerous apps, common components, services etc.
`my_app/native` the app

What's happening is something from `my_app/native` (where the .babelrc file is) is requiring something from `common/js` which is then requiring something from `third_party/js` and so babel has no idea what .babelrc file to use and we get compilation errors.

This PR fixes that by telling babel to extend the .babelrc file found in the first project root.

### CODE REVIEW

**Comment by ide** [comment]
@skevy does this seem good to you? LGTM if you think so.

**Comment by benhughes** [comment]
Any update on this. I assume I have to fix that ci check failure?

**Comment by facebook-github-bot-3** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @skevy as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by satya164** [comment]
Does this merge the `.babelrc` or uses only the new `.babelrc`?

**Comment by benhughes** [comment]
It extends the supplied babelrc (as described here: https://babeljs.io/docs/usage/options/). Which then get's extended by the following line with react-natives extraConfig:
```
let config = Object.assign({}, babelRC, extraConfig);
```

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
