### PR TITLE
Update RCTWebview to enable caching again for iOS. https://github.com…

### PR DESCRIPTION
**Pull request by jaygarcia**
**motivation** 
This pull request is for issue #1344.
Original PR: https://github.com/facebook/react-native/pull/2672

**Test plan (required)**
I tested this by modifying `WebViewExample.js` locally:
```
        <WebView
          ref={WEBVIEW_REF}
          automaticallyAdjustContentInsets={false}
          style={styles.webView}
          source={{uri: this.state.url}}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          decelerationRate="normal"
          onNavigationStateChange={this.onNavigationStateChange}
          onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
          startInLoadingState={true}
          scalesPageToFit={this.state.scalesPageToFit}
          cacheEnabled={true}  <----
        />
```

/cc @geirman @nicklockwood @stereodenis @alexisvincent

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @nicklockwood to be potential reviewers.

**Comment by javache** [comment]
The numbers here all seem quite arbitrary, and it will only enable caching for the initial load. Doesn't UIWebView caching work by default for you? Is your server sending down the correct headers?

**Comment by charpeni** [comment]
You can use the diff syntax to display added lines.

```diff
<WebView
  ref={WEBVIEW_REF}
  automaticallyAdjustContentInsets={false}
  style={styles.webView}
  source={{uri: this.state.url}}
  javaScriptEnabled={true}
  domStorageEnabled={true}
  decelerationRate="normal"
  onNavigationStateChange={this.onNavigationStateChange}
  onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
  startInLoadingState={true}
  scalesPageToFit={this.state.scalesPageToFit}
+ cacheEnabled={true}
/>
```

**Comment by charpeni** [comment]
@jaygarcia Any news?

**Comment by facebook-github-bot-1** [comment]
@jaygarcia do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by mkonicek** [comment]
@jaygarcia I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment asks a question. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to continue working on this.

**Comment by aqnaruto** [comment]
@mkonicek   we need cathe ! please

**Comment by aqnaruto** [comment]
@jaygarcia greact job, does it surport catheEnable now,on react native 0.44?

**Pull request closed without merging**
