### PR TITLE
[iOS] Add extensibility point on react-native-xcode.sh script

### PR DESCRIPTION
**Pull request by brunolemos**
Original pull request: #12863

## Motivation

Useful for generating source maps, for example.

Feature parity with Android, that already have this extensibility point on `build.gradle`:
```
project.ext.react = [
    extraPackagerArgs: [...]
]
```

## Test Plan

Xcode > Build Phases > Bundle React Native code and Images
```
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output ${SRCROOT}/build/main.jsbundle.map"
../node_modules/react-native/scripts/react-native-xcode.sh
```

## Release Notes

[IOS] [FEATURE] [./react-native-xcode.sh] - Added $EXTRA_PACKAGER_ARGS extensibility point

### CODE REVIEW

**Comment by brunolemos** [comment]
cc @grabbou this is a quick one

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by brunolemos** [comment]
@grabbou is there something we should do? It seems it got stuck

**Comment by brunolemos** [comment]
@grabbou I think you have already reviewed this because you marked as ship-it, could we include this on 0.53?

**Comment by brunolemos** [comment]
@rafeca @mjesun Could any of you help us get this merged? Found you through the commits. Thank you.

**Comment by mjesun** [comment]
cc @yungsters, who works on the project :)

**Comment by brunolemos** [comment]
No worries, thanks for taking the time to land this pr 🙌🙌

**Pull request closed without merging**
