### PR TITLE
Fix release Github link on website for latest RC version

### PR DESCRIPTION
**Pull request by Kerumen**
Each RC created ends with `rc.0` so the link on the website is broken. This PR fix this.

https://facebook.github.io/react-native/versions.html

But maybe it's the RC tag that is wrong and should be fixed instead of the website link.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @vjeux and @bestander to be potential reviewers.

**Comment by janicduplessis** [comment]
I think this is correct and the RC version now have .0 at the end.

cc @Kureev

**Comment by janicduplessis** [comment]
Oups, I mean cc @grabbou :)

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by grabbou** [comment]
Thanks, good catch. Indeed, we changed the naming patterns of `-RC` and forgot to update the website.

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3852046) to review internal test results.

**Comment by Kerumen** [comment]
Does this `.0` means that you can create several RCs (`.1`, `.2` ...) ?
As I hardcoded this it will forever point to the first RC of the serie.

**Comment by janicduplessis** [comment]
Yea we can but I don't think it will ever be an issue since this is only for docs and we won't change an API in an RC patch.

**Comment by Kerumen** [comment]
Okay :)

PS: Your bots love the `CLA Signed` label!

**Comment by janicduplessis** [comment]
@mkonicek Looks like the bot is crazy about the CLA Signed label, not really a big deal but maybe mention it to whoever is taking care of the bot :)

**Comment by bestander** [comment]
We have many bots, all of them like to participate in setting CLA Signed label.
We kind of leave this to them if it pleases them.

**Pull request closed without merging**
