### PR TITLE
Remove eslint-plugin-prettier from eslint-config-react-native

### PR DESCRIPTION
**Pull request by LukaRusadze**
## Summary:

Citing [Prettier docs](https://prettier.io/docs/en/integrating-with-linters.html):

Linters usually contain not only code quality rules, but also stylistic rules. Most stylistic rules are unnecessary when using Prettier, but worse – they might conflict with Prettier! Use Prettier for code formatting concerns, and linters for code-quality concerns, as outlined in [Prettier vs. Linters](https://prettier.io/docs/en/comparison).

This plugin was especially useful when Prettier was new. By running Prettier inside your linters, you didn’t have to set up any new infrastructure and you could re-use your editor integrations for the linters. But these days you can run prettier --check . and most editors have Prettier support.

The downsides of those plugins are:

- You end up with a lot of red squiggly lines in your editor, which gets annoying. Prettier is supposed to make you forget about formatting – and not be in your face about it!
- They are slower than running Prettier directly.
- They’re yet one layer of indirection where things may break.

------------

This PR aims to remove eslint-plugin-prettier from eslint-config-react-native. This will offload code stylistic rules to prettier from eslint. This will also remove all of the eslint(prettier/prettier) warnings and errors while typing which gets fixed by formatting with prettier but gets quickly annoying until you save to format.

I'd also go as far as to remove some/all of the styling ESLint rules and move everything to Prettier config instead (if they aren't already in it) so linter doesn't do formatter's job.

image

## Changelog:

- [General] [Removed] Remove eslint-plugin-prettier in eslint-config-react-native
- [General] [Changed] Replace 'plugin:prettier/recommended' with 'prettier' in eslint-config-react-native

## Test Plan:

Before:
image

After:
image

This was tested by making the proposed changes in node_modules of a newly initialised project

### CODE REVIEW

**Comment by ryancat** [comment]
Adding on top of the [Prettier docs](https://prettier.io/docs/en/integrating-with-linters.html), this [stackoverflow post](https://stackoverflow.com/a/44690309) also provides more context of this as well as points to the recently published post from ESLint on deprecating formatting rules.

This seems a reasonable change to me, but it might miss reporting formatting issues if someone using RN doesn't have prettier setup in their IDE/dev environment, which could be a regression (although less severe to production regressions).

I think we should send a deprecating message first before removing this.

**Comment by ryancat** [comment]
Besides, could you help with identifying the gaps after we removing `eslint-plugin-prettier` from a user's perspective? For example, what might stop working with the change, and how to recover/fix them?

This would help us find a better way roll out the change without causing surprises.

**Comment by LukaRusadze** [comment]
This could be a migration issue for those who check code style validity with `eslint .` in CI, manually, or some other place. The can be replaced with `prettier --check .`

Also your point of people not having prettier installed is valid but I don't think it's an issue. I'd say, in general, Prettier's already mostly adopted and every project, where it's necessary, has it enforced. The adoption issue can quickly be caught be a CI process as well.

I've seen a few developers disable ESLint altogether because of the styling errors/warnings you get while writing code, something that gets fixed the moment you save/format.

This is just the `eslint-plugin-prettier` removal PR atm but I'd go as far as to remove all styling related ESLint rules and rely solely on Prettier when it comes to styling.

**Comment by yungsters** [comment]
Closed by https://github.com/facebook/react-native/commit/727f30bd0b27ff168e6a6556a9ffbc7e42dbb8f0.

**Comment by OrkhanAlikhanov** [comment]
>it might miss reporting formatting issues if someone using RN doesn't have prettier setup in their IDE/dev environment

@ryancat you had predicted this 👏🏼

**Pull request closed without merging**
