### PR TITLE
Update DevelopmentSetupAndroid.md

### PR DESCRIPTION
**Pull request by LuckyLuky**
Emulator in Android Studio 2.0 introduced new shortcut for hardware menu button.

### CODE REVIEW

**Comment by christopherdro** [comment]
@LuckyLuky Thanks for the PR! Does it make sense to have `Frappé` as it's own option?

**Comment by LuckyLuky** [comment]
@christopherdro I've thought about it too, since it's just a bonus and it's for OS X only. But I wasn't sure if I should delete someone else's work. Do you think I should delete it then? If it was up to me, I would probably get rid of it.

**Comment by christopherdro** [comment]
@LuckyLuky Frappe looks pretty nice and @niftylettuce is pretty active in the community so I think we should keep. 

5. To bring up the developer menu press F2 (or ⌘+M for Android Studio 2.0 or newer) 
6. Install [Frappé](http://getfrappe.com). OSX only

**Comment by LuckyLuky** [comment]
@christopherdro Done.

**Comment by christopherdro** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
