### PR TITLE
Expose `rrc_text` via prefab

### PR DESCRIPTION
**Pull request by tomekzaw**
## Summary:

The `rrc_text` was not exposed via prefab. I'm adding it to make possible for react-native-live-markdown to integrate on top of React Native via prefab. Based on #36166.

## Changelog:

[ANDROID] [CHANGED] - Expose `rrc_text` via prefab.

### CODE REVIEW

**Comment by cortinico** [comment]
@tomekzaw can you rebase and fix the merge conflicts

**Review by cortinico — APPROVED** [review]

**Comment by tomekzaw** [comment]
@cortinico Done, conflicts resolved

**Comment by tomekzaw** [comment]
@cortinico Could you please check why **Facebook Internal - Builds & Tests** workflow is failing?

**Comment by cortinico** [comment]
> @cortinico Could you please check why **Facebook Internal - Builds & Tests** workflow is failing?

Yup is some internal flakyness. I've triggered a land, should be merged in a couple of hours at most

**Pull request closed without merging**
