### PR TITLE
[Dev] Update to Danger 2.0

### PR DESCRIPTION
**Pull request by orta**
## Motivation

Danger 2.0 is pretty stable now (Apollo-client just updated to 2.0, so I was reminded of RN) and more importantly for RN, it doesn't depends on jest's internals now. This means Danger doesn't need special casing like before. 

/cc @hramos @grabbou 

## Test Plan

I ran Danger PR to validate that any PR runs:

screen shot 2017-12-15 at 6 04 55 pm

I expect the CI will tell me whether it works or not

## Related PRs

https://github.com/facebook/react-native/pull/16350

### CODE REVIEW

**Comment by hramos** [comment]
Looks great. I'll import it without landing first, as I believe this will require updating our internal repo's offline yarn cache. While danger is not used internally, we have some tests that ensure all dependencies in package.json are available offline.

**Comment by orta** [comment]
Thanks @hramos

**Comment by orta** [comment]
That makes sense to me 👍

**Comment by orta** [comment]
Ah, this PR is still open, closing as https://github.com/facebook/react-native/pull/17310 did it

**Pull request closed without merging**
