### PR TITLE
bump Gradle to 5.4.1

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

Bump Gradle to 5.4.1, includes many improvements and fixes.

## Changelog

[Android] [Changed] - Bump Gradle to 5.4.1

## Test Plan

RNTester is running as expected.

### CODE REVIEW

**Comment by dulmandakh** [comment]
@gengjiawen  @hey99xx what is you opinion about JVM options changes?

**Comment by gengjiawen** [comment]
why change the jvm options ?

**Comment by dulmandakh** [comment]
wrapper task did change it

**Comment by gengjiawen** [comment]
> ./gradlew wrapper task did change it

I tried the change locally, works as expected.
But I didn't find related changelog. Anyway, I think this is good to ship.

**Pull request closed without merging**
