### PR TITLE
Update AlertIOS.js

### PR DESCRIPTION
**Pull request by PaulMest**
This fixes a broken link in the docs.

### CODE REVIEW

**Comment by lacker** [comment]
Thanks! - let me make sure the tests pass so that I can use the auto tooling and then i'll land this.

**Comment by lacker** [comment]
Ah, you have to sign the CLA for me to accept this, otherwise this annoying bot rejects my request to land this PR. @PaulMest would you mind signing it?

**Comment by PaulMest** [comment]
@lacker Just signed the CLA. Let me know if there's anything else I should do.

**Comment by PaulMest** [comment]
@lacker It looks like @facebook-github-bot needs some help. Any idea what's wrong?

**Comment by lacker** [comment]
Let me re-try - I think there were some CI problems.

**Pull request closed without merging**
