### PR TITLE
Make readonly object editable for change style object attributes

### PR DESCRIPTION
**Pull request by meetdhanani17**
## Summary:
Fixes  https://github.com/facebook/react-native/issues/45285
object created by StyleSheet.create provide readonly object and it cannot be changeable for farther value or type change according to native requirements, so I have added condition in flattenStyle function, if it's readonly than convert into editable object 

## Changelog:
[GENERAL] [FIXED] - fixed fontWeight number value error for android (java.lang.Double cannot be cast to java.lang. String)

### CODE REVIEW

**Comment by javache** [comment]
This doesn't seem right to me. If the value we receive is frozen, we do not want to make an extra copy here for what will be a very common scenario.

This is a perf-sensitive code-path, let's be careful with changes here (eg with is the cost of calling isFrozen?)

**Comment by meetdhanani17** [comment]
As you know about the styles it's doing frozen when enviroment is dev in ptoduction all the cost of reassign an object removed becuase we will not get frozon object that time, and when an object came in list then we are also regenerating an object, as it is development environment different it doesn't change in production/release

**Comment by javache** [comment]
It's not clear what this PR enables?

It is desirable for the output of flattenStyle to not be mutable and it shouldn't be assumed to be. `flattenStyle` is also an internal API that should not be called directly ideally.

**Comment by meetdhanani17** [comment]
but this also make an array mutable that's what I want to tell you

**Comment by meetdhanani17** [comment]
> It's not clear what this PR enables?
> 
> It is desirable for the output of flattenStyle to not be mutable and it shouldn't be assumed to be. `flattenStyle` is also an internal API that should not be called directly ideally.

`flattenStyle` after calling this function In text component we are change the font weight of this style, I can also apply solution for that component only but i was thinking like this is what kind of object if i pass array of immutable then its return mutable object and mutable object pass then also its return mutable object so there is no meaning to differentiate

**Comment by javache** [comment]
> my question again is why we are try to change immutable object

> flattenStyle after calling this function In text component we are change the font weight of this style

We should address the root cause here, which does seem to be the text component, we shouldn't be mutating the return value of flattenStyle.

I'd recommend changing Text.js like this instead (the $FlowFixMe's there a clear sign the API boundary is not respected)

```
let processedStyle = flattenStyle(_style);
if (processedStyle != null) {
  let overrides = null;
  if (typeof processedStyle.fontWeight === 'number') {
    overrides = overrides || {};
    overrides.fontWeight = processedStyle.fontWeight.toString();
  }
  [...]
  if (overrides != null) {
    processedStyle = [processedStyle, overrides];
  }
```

**Comment by javache** [comment]
I will send a PR for this.

**Comment by javache** [comment]
https://github.com/facebook/react-native/pull/45340 addresses this issue.

**Comment by meetdhanani17** [comment]
Ok great, but i'm am also working on native side for fix it

**Comment by meetdhanani17** [comment]
> I'd recommend changing Text.js like this instead (the $FlowFixMe's there a clear sign the API boundary is not respected)

That what i have talked with you, like i have multiple ways to solve this issue if you said to change only text file then i'll fix using only Text.js file

**Pull request closed without merging**
