### PR TITLE
[Navigator] check if this._navBar has immediatelyRefresh method

### PR DESCRIPTION
**Pull request by andrewgrewell**
`Navigator` throws an error if using a custom `NavigationBar` component that does not have a `immediatelyRefresh` method present.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
@andrewgrewell updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@andrewgrewell updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@andrewgrewell updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9438/files/5e20b1695ed3803ca331d5380e6e4598ad562f71..2b2744fe9fbee2e88cf618cc3bae0085cfa4f5fb)

**Comment by mkonicek** [comment]
Thanks for the fix!

@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3838928) to review internal test results.

**Pull request closed without merging**
