### PR TITLE
Update NavigatorIOS.ios.js

### PR DESCRIPTION
**Pull request by katrinanova**
Allow props passed to the route object to overwrite props passed to the navigator.

### CODE REVIEW

**Comment by brentvatne** [comment]
Thanks @katrinanova! If you can clean up those trailing space issues this looks good to me.

In a follow-up PR it would also be good to have this behaviour explicitly documented - I think a good place for this would be [in the comment docblock in NavigatorIOS.ios.js](https://github.com/katrinanova/react-native/blob/patch-1/Libraries/Components/Navigation/NavigatorIOS.ios.js#L94-L175). The docs extract the docblock and make this: https://facebook.github.io/react-native/docs/navigatorios.html#content

**Comment by katrinanova** [comment]
@brentvatne not sure why the travis ci failed :( everything ran fine when I've tested it

**Comment by skevy** [comment]
@katrinanova it's failing in an objc test. It's not you. We really need to fix that one of these days.

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
Whoops. Could you also sign the CLA? https://code.facebook.com/cla

**Comment by katrinanova** [comment]
@skevy signed

**Comment by skevy** [comment]
@katrinanova thanks! And thanks for the PR!

**Pull request closed without merging**
