### PR TITLE
Fixed #632 using relative path instead of absolute path for Image tag

### LINKED ISSUE #632: Can not see the images on the web page
in the http://facebook.github.io/react-native/docs/embeded-app.html#content

2 images link is broken. 

I think It should use relative path instead of absolute path. 

screen shot 2015-04-03 at 10 10 51 am
screen shot 2015-04-03 at 10 10 44 am

### PR DESCRIPTION
**Pull request by krazyeom**
It cannot see the some images that are using absolute path on the [web page](http://facebook.github.io/react-native/docs/embeded-app.html#content),

so I think it should use absolute path.

### CODE REVIEW

**Comment by spicyj** [comment]
Tricky. This way works on the website (probably), but not when viewing on GitHub…

**Comment by tjwudi** [comment]
@spicyj Maybe `react-native/img/EmbeddedAppExample.png` works.

**Comment by krazyeom** [comment]
@spicyj it's not tricky. MD files in docs folder is using for http://facebook.github.io/react-native/docs/ 
another md files are using Relative path. ex) LinkingLibraries.md 
```
![](/react-native/img/AddToLibraries.png)
![](/react-native/img/AddToBuildPhases.png)
![](/react-native/img/AddToSearchPaths.png)
```

**Comment by spicyj** [comment]
Sure, okay. Maybe we can find something that works on both later.

**Pull request merged**
