### PR TITLE
Fix documentations to build application in production

### PR DESCRIPTION
**Pull request by btrd**
The Xcode menu where you can `Edit Scheme` is called `Product` and not `Project`.

capture d ecran 2016-09-26 a 12 20 30

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @jacobp100 and @hramos to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jacobp100** [comment]
This was my typo. LGTM.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3924147).

**Pull request closed without merging**
