### PR TITLE
Add gradle support for multi-dimensional product flavors

### PR DESCRIPTION
**Pull request by wsxyeah**
#14791 

Replace `productFlavors.each ` with `applicationVariants.each` to support multi-dimensional product flavors.

### CODE REVIEW

**Comment by Almouro** [comment]
Hi,
Thanks @wsxyeah !
This PR works for me and just solved my problem.

@mkonicek, you seem to be the only Facebook employee present in the blame information of this file :) 
Do you know how we can help with this PR?

**Comment by mkonicek** [comment]
> you seem to be the only Facebook employee present in the blame information of this file :)

I quit Facebook to take some time off and starting a new job on Monday actually. Looks like there are a few contributors to the file who might know more, albeit the code for product flavors is very old:

https://github.com/facebook/react-native/blame/master/react.gradle

**Comment by wsxyeah** [comment]
@AndrewJack @foghina
Cloud you help review this PR?

**Comment by AndrewJack** [comment]
@wsxyeah I'll try to have a look over the next few days

**Comment by petersimons** [comment]
@wsxyeah This solved my issue where JS failed to bundle across multiple flavor dimensions, definitely deserves re-opening

**Comment by wesleymooiman** [comment]
this pr should be reopened

**Comment by sytler** [comment]
+1

**Comment by pietro3092** [comment]
+1

**Pull request closed without merging**
