### PR TITLE
[Packager] Add gif, bmp, webp to the list of valid assetExts

### LINKED ISSUE #3731: [Asset System] Does not support gifs
The new asset system described here: https://github.com/facebook/react-native/pull/3545 does not currently support gifs - it throws an unable to resolve module error when I try.

cc @frantic

### PR DESCRIPTION
**Pull request by brentvatne**
Fixes #3731 - thanks @frantic & @martinbigio!

### CODE REVIEW

**Comment by martinbigio** [comment]
@facebook-github-bot shipit

**Comment by martinbigio** [comment]
I want to move the defaults outside of the cli, and maybe allow the user to provide values for this through `rn-cli.config.js`

**Comment by brentvatne** [comment]
@martinbigio - makes sense!

**Comment by brentvatne** [comment]
@martinbigio - feel free to close this if you're going to do the work on another branch instead

**Comment by martinbigio** [comment]
@brentvatne the bot didn't close the issue because the pr didn't get merge successfully on our internal copy.  I'll take a look during the weekend

**Comment by mattmo** [comment]
@martinbigio - did this land in another branch?

**Comment by nicklockwood** [comment]
Seems like this already landed.

**Pull request closed without merging**
