### PR TITLE
if the NSURLResponse return nil,set URLCache will crash!

### PR DESCRIPTION
**Pull request by yesman317**
the crash stack is:
0 CoreFoundation 0x0000000185d62580 CFRetain + 164
1 CFNetwork 0x00000001857c2174 __CFCachedURLResponse::__CFCachedURLResponse(_CFURLResponse*, __CFData const*, void const*, CFURLCacheStoragePolicy) + 80
2 CFNetwork 0x00000001857c20cc CFCachedURLResponseCreateWithUserInfo + 120
3 CFNetwork 0x00000001858c7a34 -[NSCachedURLResponse initWithResponse:data:userInfo:storagePolicy:] + 328
4 Qzone 0x000000010026b3b8 __87-[RCTImageLoader loadImageWithTag:size:scale:resizeMode:progressBlock:completionBlock:]_block_invoke_2.195 (RCTImageLoader.m:292)
5 Qzone 0x00000001002630fc -[RCTNetworkTask URLRequest:didCompleteWithError:] (RCTNetworkTask.m:132)
6 Qzone 0x0000000100268074 -[RCTHTTPRequestHandler URLSession:task:didCompleteWithError:] (RCTHTTPRequestHandler.m:114)
7 CFNetwork 0x00000001858c46a8 ___51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke227 + 64
8 Foundation 0x0000000186d6f1c4 ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
9 Foundation 0x0000000186cc0604 -[NSBlockOperation main] + 96
10 Foundation 0x0000000186cb01cc -[__NSOperationInternal _start:] + 636
11 Foundation 0x0000000186d71f28 ___NSOQSchedule_f + 228
17 libdispatch.dylib 0x00000001981d1954 __dispatch_client_callout + 16
23 libdispatch.dylib 0x00000001981dc0a4 __dispatch_queue_drain + 1448
24 libdispatch.dylib 0x00000001981d4a5c __dispatch_queue_invoke + 132
25 libdispatch.dylib 0x00000001981de318 __dispatch_root_queue_drain + 720
26 libdispatch.dylib 0x00000001981dfc4c __dispatch_worker_thread3 + 108
27 libsystem_pthread.dylib 0x00000001983b121c _pthread_wqthread + 804
1 libsystem_pthread.dylib 0x00000001983b0ee0 start_wqthread + 4

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @rigdern to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @skatpgusskat as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by skatpgusskat** [comment]
@yesman317 could you let me know which case the NSURLResponse become nil on that handler?

**Comment by skatpgusskat** [comment]
Please put the label ```Need more information``` on this pull request.

**Comment by lacker** [comment]
This PR has needed more information for a while, so I'm going to hypothesize it's no longer relevant and close it. Feel free to reopen if someone has the additional info requested here.

**Pull request closed without merging**
