### PR TITLE
<Image /> source not reloading on source & size change

### LINKED ISSUE #7130: Downsampling an <Image /> through the style prop doesn't properly reload the source if source.uri has changed
I'm using RN 0.24.0 and 0.21
when i change the image source,width,height( with a diffrent aspect ratio ) ,it doesn't work
the image and size doesn't change
please confirm it
example: https://rnplay.org/apps/hSHgIA

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #7130 

This is probably not meant to be merged as is as I consider this a bit brittle (more importantly, I am unaware of edge cases, so feedback and review welcome). However, decided to submit a PR just to demo where's the problem.

Basically, what's happening here (apart from great reproductions by community in #7130) is - when you change an image source and dimensions at the same time so that new dimensions return false from `RCTShouldReloadImageForSizeChange` (e.g. new dimensions smaller then loaded size, scale & ration the same) - we will hit the `Our existing image is good enough` case on [this line](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/Libraries/Image/RCTImageView.m#L269) and that will cancel request issued from `setSource` [here](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/Libraries/Image/RCTImageView.m#L139) (which was called first).

Added a simple boolean to guard against such case and seems to be working, however I am not really sure what are edge cases here.

Maybe a better idea would've been to ensure `setSource` is called after `reactSetFrame` if we can control that.

| Before | After |
| -------- | ------- |
|  |  |

### CODE REVIEW

**Comment by DannyiCracked** [comment]
@grabbou Your gifs aren't loading :)

**Comment by grabbou** [comment]
How come?
screen shot 2016-04-23 at 21 00 06

**Comment by nicklockwood** [comment]
We can't control the order in which props are set, but we have a didSetProps method that is called after all props have been set, so potentially we should move the logic to there so that it can properly take into account which props have changed, and avoid the race condition.

**Comment by grabbou** [comment]
Okay, thanks for the tips, will rebase & explore that later :)

**Comment by facebook-github-bot-9** [comment]
@bnham would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by dubert** [comment]
I'm encountering this issue too. I have a an object full of images:
```js
const images = {
  1: require('../images/1.jpg'),
  2: require('../images/2.jpg'),
  3: require('../images/3.jpg'),
  4: require('../images/4.jpg'),
  5: require('../images/5.jpg'),
  6: require('../images/6.jpg'),
  7: require('../images/7.jpg'),
  8: require('../images/8.jpg'),
}
```

and when I swap out the source, it works on the simulator, but not on the device.

**Comment by javache** [comment]
There's some more discussion on this happening in https://github.com/facebook/react-native/pull/9137. Let's close this one.

**Pull request closed without merging**
