### PR TITLE
Make Animated.SpringAnimation JS compatible with Expo SDK 22 (CRNA) native code

### PR DESCRIPTION
**Pull request by skevy**
In Expo SDK 22 we shipped this commit:

https://github.com/facebook/react-native/commit/26133beda9034d374afb95b3a653353e25c40c84

Which had changes to the native code for native spring animations.

In order to keep CRNA compat, we need to make sure the .49 stable JS is compatible with the
Expo SDK 22 native code.

This should be pulled into the .49 stable branch and released as 0.49.5.

Note -- it does not need to be cherry-picked to master.

Sorry for the trouble!

cc @grabbou @ide @brentvatne

### CODE REVIEW

**Comment by skevy** [comment]
cc @satya164 when you get a chance tomorrow, could you test this in your project that you had a problem with today?

**Comment by satya164** [comment]
@skevy will do

**Comment by grabbou** [comment]
@satya164 let me know when you're done, so I can follow up with next release

**Comment by grabbou** [comment]
I tested and it's okay.

**Pull request merged**
