### PR TITLE
Fixed ART Surface initialization: do not cancel updates to the surfce, make them pen…

### PR DESCRIPTION
**Pull request by tepamid**
My PR was pulled into RN 0.37 (https://github.com/facebook/react-native/commit/d294e15c43a6222f25953dae8189d0e220dbdf7e). Since then an issue was discovered: ARTSurface skipped drawing the first render cycle if native TextureView takes too long. In case a static graphic is rendered in a single render cycle, it may be skipped resulting in an empty canvas being displayed.

A solution proposed in this PR: instead of skipping updates, make them pending and flush once the TextureView is ready.

This solution is released within our production app. It fixed ArtSurface initialisation issues cased by original PR to RN 0.37.

### CODE REVIEW

**Comment by hramos** [comment]
As the reviewer of the [original PR](https://github.com/facebook/react-native/pull/9486), @foghina do you mind taking a look?

**Comment by foghina** [comment]
@facebook-github-bot shipit

**Comment by foghina** [comment]
Thanks for the fix, @tepamid! And thanks for the ping, @hramos :)

**Comment by tepamid** [comment]
Give me a few more days to update this PR. There is one more improvement to be added for the case when device orientation is changed.

**Comment by foghina** [comment]
@tepamid ok, good thing the import failed then. Ping me when you're done and I'll have another look (and support any internal breakages).

**Comment by tepamid** [comment]
@hramos This PR hasn't been merged. Why did you close it?

**Comment by hramos** [comment]
Hmm I don't recall a particular reason why. I probably did not notice the recent commits prior to me closing this. Sorry about that.

**Comment by tepamid** [comment]
@foghina would you please help me to route cause the reason of Travis CI test failing?

I check the log files and as I see some tvOS tests are failing (_The command ./scripts/objc-test-tvos.sh exited with 65._). However since I changed only Android related .java files, it's seem strange to me that my commits caused these errors. Can you you help me sort this out?

**Comment by hramos** [comment]
@tepamid tests on Travis broke a couple of weeks ago, so it is possible they are not failing because of your changes, necessarily.

**Pull request closed without merging**
