### PR TITLE
Fix regression in Android unlink command

### PR DESCRIPTION
**Pull request by matt-block**
Motivation:
--------------
Commit 4dfdec9b28074b311ffd75084d9d2a3cbd41a800 introduced a regression in the `unlink` command for Android projects: native modules previously linked with the now-deprecated `compile` configuration will not be detected anymore and by extension will not be unlinked.

`unlink` should be aware of both new and deprecated options to ensure functionality also in existing projects that previously linked modules with the old convention.

This PR fixes the regression by:
1. `makeDeprecatedNativeModule` is added so to have the deprecated patch line that could be present in the Gradle build file.
2. updating the Android `isInstalled` to check, for a given package name, for both `compile` (using the function introduced in step 1) and `implementation` dependency records in `build.gradle`.
3. Android `unregisterNativeModule` will proceed to revoke both possible patch lines from `build.gradle`.

This PR together with commit 4dfdec9b28074b311ffd75084d9d2a3cbd41a800 provide the following behaviour:

- `link` will continue to work as intended using `implementation`. This works without issues even with older packages that still use `compile` internally for their own dependencies.
- `link` will detect previously linked packages with `compile` and will not proceed with a new linkage. Instead, it will log that `Platform 'android' module X is already linked`.
- `unlink` will detect dependencies with both `compile` and `implementation` and proceed to unlink as expected.

Test Plan:
----------
- Ran tests locally on my branch, all related tests passed.
- Manually tried the changes on my existing projects that still use `compile` and the described behaviour listed above was matched.

Related PRs:
--------------
- #20853

Release Notes:
--------------
[CLI] [BUGFIX] [local-cli/link] - Fixed regression in Android `unlink`.

### CODE REVIEW

**Comment by matt-block** [comment]
@Kureev @grabbou Let me know your thoughts.

**Comment by matt-block** [comment]
@grabbou since [your proposal](https://github.com/react-native-community/discussions-and-proposals/pull/13) passed (congrats 🎉), shall we postpone this until we separate the CLI or proceed as always?

**Comment by cpojer** [comment]
Thank you for your PR. We just moved this code to https://github.com/react-native-community/react-native-cli so please submit your PR there.

**Comment by grabbou** [comment]
Hey @matt-block! Thanks for submitting this PR! Apologies for not getting back, but the whole CLI extraction process got me super busy with other notifications.

We ended up fixing this bug in the CLI with this PR: https://github.com/react-native-community/react-native-cli/pull/81 which takes a slightly different approach compared to your take. Would love to hear your opinion about that take - please feel free to comment on the PR or message me!

**Pull request closed without merging**
