### PR TITLE
Make the method signatures stand out more

### PR DESCRIPTION
**Pull request by JoelMarcey**
And more delineated from other parts of the method
information.

Hopefully this makes it easier to parse through.

Test Plan:

http://localhost:8079/react-native/docs/asyncstorage.html

screencapture-localhost-8079-react-native-docs-asyncstorage-html-1466792316485

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @janicduplessis to be potential reviewers.

**Comment by JoelMarcey** [comment]
@bestander Made link this color instead.

screenshot 2016-06-26 08 07 04

**Comment by bestander** [comment]
Hey Joel, that looks contrast enough to me :)
Thanks for considering feedback and shipit at will

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/258175081223784/int_phab) to review.

**Pull request closed without merging**
