### PR TITLE
Rename yoga.podspec to Yoga.podspec

### PR DESCRIPTION
**Pull request by hassanbazzi**
## Summary

When doing RN init from scratch for 0.61, I noticed pod install was failing. This was because "Yoga.podspec" was mis-spelled to "yoga.podspec" in the yoga ReactCommon folder. Thus, `pod install` was failing

```
[!] No podspec found for `Yoga` in `../node_modules/react-native/ReactCommon/yoga
```
## Changelog

[iOS] [Fixed] - Fix Yoga.podspec case sensitivity

## Test Plan

`pod install` now runs successfully with a clean build of master.

### CODE REVIEW

**Comment by jerson** [comment]
@hassanbazzi When yoga is renamed Yoga, many imports need to be replaced, wouldn't it be better to change the pod to yoga?

**Comment by grabbou** [comment]
Introduced via https://github.com/facebook/react-native/commit/8d02e1723fd972d55eceb7de7c25dacf691d83df CC: @axe-fb @axemclion (not sure which one is "the right" now)

**Comment by grabbou** [comment]
I think what happened here is that Git is not tracking case changes in the filename and you need to run `git mv` yourself instead of `mv` to rename the files. 

At least that's what I had to do when applying this change in the 0.61-stable branch. I need this fix right now, but let's ship this to `master` instead, so that @hassanbazzi can get its first contribution right there!

(btw, thanks for sending this!)

**Comment by cpojer** [comment]
Let's see if this works with out syncing at FB, otherwise we may have to do something funky here ;)

**Comment by axe-fb** [comment]
The reason I had to make `Yoga` upper case is that the Yoga Cocoapods externally are used as such. Also, i believe that the convention in cocoapods is to use upper case names.

**Pull request closed without merging**
