### PR TITLE
Let LayoutAnimation respect style opacity on Android. Fix issue #11769

### PR DESCRIPTION
**Pull request by vinceyuan**
Fix issue #11769

When a view or text is created with style opacity (e.g. 0.2) and LayoutAnimation is enabled on Android, what we expected to happen is the view or text has opacity (e.g. 0.2).
What actually happens is the view or text's opacity is always 1.

In the following screenshot of the sample app, the odd numbered view/text's opacity should be 0.2. If we create them without LayoutAnimation, everything is good. But when we do with LayoutAnimation, the style opacity is not respected.
Screenshot

Reproduced on rnplay.org https://rnplay.org/apps/JbdOpQ
The sample project I created: https://github.com/vinceyuan/ReactNativeOpacityBugDemo
You can try my fix on branch fix-react-native-issue-11769 https://github.com/vinceyuan/ReactNativeOpacityBugDemo/tree/fix-react-native-issue-11769

### CODE REVIEW

**Comment by janicduplessis** [comment]
Hey thanks for fixing this! There is an issue with your current solution, if the animation is reversed then it will animate to the current opacity instead of 0. I suggest we handle all possible cases inside both cases of the switch. So for opacity it should be something like:
```
float fromValue = isReverse() ? view.getAlpha() : 0.0f;
float toValue = isReverse() ? 0.0f : view.getAlpha();
```
Also would that bug also happen with a scale? Let's say the view has a 0.5 scale transform and is created with layout animation. Then we'd have to do something similar in the scale case, if not we can keep the 1 -> 0, 0 -> 1.

**Comment by vinceyuan** [comment]
@janicduplessis Thanks for pointing it out. I will modify it and check if this bug also happens with a scale soon.

**Comment by vinceyuan** [comment]
@janicduplessis I updated the code according to your suggestion.

I also updated the demo app to check scaling.  `ScaleAnimation` works well when width/height changes. `ScaleAnimation` has nothing to do with style `transform`. See https://rnplay.org/apps/JbdOpQ and https://github.com/vinceyuan/ReactNativeOpacityBugDemo

Screenshot

**Comment by vinceyuan** [comment]
I noticed CI build failed. I am trying to run tests locally.

**Comment by janicduplessis** [comment]
Opacity change looks good. To test scale you have to actually use the scale layout animation when creating views. To test it you should do something like your opacity test but use LayoutAnimation.configureNext and pass an object similar to https://github.com/facebook/react-native/blob/master/Libraries/LayoutAnimation/LayoutAnimation.js#L107 and change 'property' to scaleXY.

**Comment by vinceyuan** [comment]
@janicduplessis Got it. I will try. Thanks.

**Comment by vinceyuan** [comment]
@janicduplessis I have checked `scaleXY` animation. It works well with transition scale style (e.g. `{transform: [{scale: 0.5}]}`). See https://rnplay.org/apps/JbdOpQ and https://github.com/vinceyuan/ReactNativeOpacityBugDemo

(You can see there is another issue when removing items with LayoutAnimation. Some views/texts disappeared.)

Screenshot

**Comment by janicduplessis** [comment]
Cool, looks good!

@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
Yea there's quite a few issues with delete animations, I never had time to work on fixing them :(

**Comment by vinceyuan** [comment]
@janicduplessis The bot said you have imported this PR. When will it be merged into `master` branch?

**Comment by janicduplessis** [comment]
Let's try shipping again, not sure why it didn't go through.

@facebook-github-bot shipit

**Pull request closed without merging**
