### PR TITLE
bump android target version to 27

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
bump target version to 27
## Test Plan
pass all current ci.
## Related PRs
none
## Release Notes
[GENERAL] [ANDROID] [FEATURE] - bump android target version to 27

### CODE REVIEW

**Comment by dulmandakh** [comment]
Please edit buckconfig and ReactAndroid build.gradle to target 27 👍

**Comment by gengjiawen** [comment]
`buckconfig` is updated, is there am I missing ? ReactAndroid build.gradle don't need it, you can see https://github.com/facebook/react-native/pull/20846.

**Comment by dulmandakh** [comment]
@gengjiawen oops

**Comment by gengjiawen** [comment]
@dulmandakh Fixed the wrong rebase, and bump target sdk version to 27.

**Comment by dulmandakh** [comment]
@facebook-github-bot  shipit

**Comment by dulmandakh** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
