### PR TITLE
Fix UIExplorer CameraRoll example onEndReached doesn't take effect bug

### PR DESCRIPTION
**Pull request by narychen**
The detail of the bug is declared on https://github.com/facebook/react-native/issues/7237.
The ListView of the Photos doesn't have a height so that it cannot load new photos when onEndReached and always load all photos at once.

### CODE REVIEW

**Comment by bestander** [comment]
ping @dsibiski 
The CI tests crashes are infra problem, can be ignored for this PR

**Comment by facebook-github-bot-5** [comment]
@narychen updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@narychen updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@narychen updated the pull request.

**Comment by narychen** [comment]
What's wrong with it ?

**Comment by facebook-github-bot-1** [comment]
@narychen updated the pull request.

**Comment by mkonicek** [comment]
@narychen Please read this guide to contributing and update your pull request: https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by narychen** [comment]
simulator screen shot 2016 5 10 11 00 11
The screenshot after modified
simulator screen shot 2016 5 10 11 30 36
The screenshot before modified

**Comment by facebook-github-bot-8** [comment]
@narychen updated the pull request.

**Comment by mkonicek** [comment]
@narychen Why is the second screenshot better?

**Comment by narychen** [comment]
@mkonicek because it doesn't limit the height of the ListView.  This will cause the issue https://github.com/facebook/react-native/issues/7237

**Comment by mkonicek** [comment]
@narychen I see, can you please change the title and description of your pull request to explain what it does? The title and description will eventually become the commit message if we merge this.

**Comment by narychen** [comment]
@mkonicek I changed.

**Comment by facebook-github-bot-2** [comment]
@narychen I tried to find reviewers for this pull request and wanted to ping them to take another look. However, based on the blame information for the files in this pull request I couldn't find any reviewers. This sometimes happens when the files in the pull request are new or don't exist on master anymore. Is this pull request still relevant? If yes could you please rebase? In case you know who has context on this code feel free to mention them in a comment (one person is fine). Thanks for reading and hope you will continue contributing to the project.

**Comment by bestander** [comment]
Ok, let's get it in

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1605875946397770/int_phab) to review internal test results.

**Comment by bestander** [comment]
@narychen, thanks for the contribution but have a look at https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md next time.

We need contributors to take responsibility for testing and be explicit what steps they have made to test that the change.

**Comment by bestander** [comment]
@narychen, import is failing.
Could you please rebase on master?

**Comment by narychen** [comment]
@bestander  It's been a long time, maybe I should create another PR.

**Pull request closed without merging**
