### PR TITLE
Fix blocks mixed up between mac, linux and windows in Getting Started doc

### LINKED ISSUE #11220: Tutorial to install the cli on windows 10
I couldn't find any tutorial on the getting started page on how to install react native cli on windows 10.

### PR DESCRIPTION
**Pull request by eloekset**
Fixes #11220

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Thanks! This seems better.

**Comment by hramos** [comment]
I don't see a test plan. Can you elaborate on how this fix was tested?

This is a tricky doc to update, and a fix in the Windows+Android section can easily introduce bugs in other sections (which is what likely happened when I last updated this doc).

Can you, for example, post screenshots for each of the 6 permutations of this guide with the fix in place?

**Comment by eloekset** [comment]
@hramos Here are the 6 screenshots generated without image files:

**Comment by hramos** [comment]
Looks like there's an issue when iOS + Linux is selected - it should simply display an "Unsupported" message, with no further instructions. You can see that this is handled correctly when iOS + Windows is selected.

Wrong (iOS + Linux):




Correct (iOS + Windows):

**Comment by eloekset** [comment]
@hramos You're right. I didn't test it, but just assumed that everything under a block would be displayed for the platforms and OSes listed in the block element until the next block, but it's probably more complicated than that.

**Comment by hramos** [comment]
@eloekset I fixed the issue, landing this as part of your PR if you don't mind.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
