### PR TITLE
add a mapping ability to the interpolate method

### PR DESCRIPTION
**Pull request by rocman**
This makes it possible to do the interpolation on properties of any type. For example, the contentOffset of a ScrollView.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @lelandrichardson and @vjeux to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@rocman updated the pull request.

**Comment by rocman** [comment]
@fatihict big thanks to your reviewing. The change you mentioned above is a mistake. And I've fixed it just now. Thanks.

**Comment by facebook-github-bot-9** [comment]
@rocman updated the pull request.

**Comment by lelandrichardson** [comment]
An API like this won't be compatible with native animations, unfortunately. I wonder if there is any way we could make it so that it would be?

Have to run right now, but will look at this PR a bit more and think about it. You may want to look at this PR for comparison, which could achieve something similar: https://github.com/animatedjs/animated/pull/12

**Comment by facebook-github-bot-7** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @lelandrichardson as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by mkonicek** [comment]
@rocman I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment mentions:

> An API like this won't be compatible with native animations, unfortunately. I wonder if there is any way we could make it so that it would be?

I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to continue working on this.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (62/60 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:53930)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1biJSG-003Jts-AX
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:54:46 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES256-SHA:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1biJSF-0005d8-36
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:54:44 -0700
Date: Fri, 09 Sep 2016 03:54:42 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1473418482;
	bh=ScCjE5x8kVn1WvnDY3pzTZByRo/wh5Ta8yIQzide9z8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Tbo5QoE41JvJEEeza5YRnJUoZLxCyDbuRxpRpT0wFs+YsGKIzBS/ugH9ERWwbd99s
	 qP9vFVkyj2Yurz4p7VCNCB8aj7Onn5GaE1gLbFuoJkRv8iWr9Bvwd5LOON+e8R51lV
	 NawFPK/NioSOmPcD7J2FXw6sSUpLiF5C/HjnKwSM=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (63/60 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:53982)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1biJSN-003Jw9-Fo
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:54:53 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES256-SHA:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1biJSM-0005hL-CZ
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:54:51 -0700
Date: Fri, 09 Sep 2016 03:54:49 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1473418489;
	bh=7sp7lCOOmbAZRpP+pBQOPx33ufehjE58sSZ2swX2yLg=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gIqWuxJZqkPeRNInlzCv7MeYJSEwg7+UnsW4KBEpNS+vp2W2f0qNfokNOvRanwZWR
	 9lMYbcMWrBcGBnilAh/UuvQwC1D3G7raHBAFeXCfIQLU8rdMqxXX8tcREUBsoRYHFt
	 kf9fVbr0WuB+KCSLZviR3WiARzJUaDgzlt45tOoA=

**Pull request closed without merging**
