### PR TITLE
Change website readme to list port 8079

### PR DESCRIPTION
**Pull request by morenoh149**

### CODE REVIEW

**Comment by rjoonas** [comment]
Good point, the default port is defined as `8079` in [server.js:60](https://github.com/facebook/react-native/blob/master/website/server/server.js#L60).

**Comment by chirag04** [comment]
Already on master: https://github.com/facebook/react-native/pull/4545

**Comment by christopherdro** [comment]
@morenoh149  Sorry, I didn't know there you had a PR already open.

**Comment by morenoh149** [comment]
🌊

**Pull request closed without merging**
