### PR TITLE
Update Switch.js docs - tintColor changes border

### PR DESCRIPTION
**Pull request by Piwaii**
Update documentation for Switch as it's not a background color that is displayed when the switch off, but juste the border (the background remains transparent)

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @yungsters and @davidaurelio to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@Piwaii updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9707/files/68b94bf04632416c0c65725b4ab4d928cdb8c5c7..bbd1bf26ffb99bbdce24270958400933b454c137)

**Comment by facebook-github-bot-0** [comment]
@Piwaii updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9707/files/bbd1bf26ffb99bbdce24270958400933b454c137..b459a75d889e59992bd03c66202c3fc0a3640896)

**Comment by mkonicek** [comment]
Ah, good catch! Wonder why it said background - could it be that it's the background on older iOS versions? Could you add a screenshot please showing how the tinted switch looks?

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3819887) to review internal test results.

**Pull request closed without merging**
