### PR TITLE
Add gif and webp support to Fresco

### PR DESCRIPTION
**Pull request by charpeni**
Motivation #7760 

**Test plan**
Build from source with a gif image, everything works fine.

However, i'm not sure about the BUCK part. While building I saw the dependencies I added being downloaded, but the app built with BUCK doesn't support gif. Maybe someone with more experience with BUCK than me can check this?

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @cjhopman and @mkonicek to be potential reviewers.

**Comment by ide** [comment]
@andreicoman11 do you guys want this on facebook's side?

**Comment by andreicoman11** [comment]
I think we want this.
@bestander these libraries don't automatically get built as part of the app, unless you explicitly include each library, right?

**Comment by bestander** [comment]
@andreicoman11, regarding app sizes.
- Gradle will include these libraries by default because they are on "compile" target now. Prod apps would want to exclude them with proguard or some custom gradle scripts.
- Buck will include everything that is required via dependency tree, i.e. if there are modules that use `imagepipeline` target those will be downloaded and included

The short answer to all is `yes, they will automatically get built as part of the app`

**Comment by andreicoman11** [comment]
That is bad news. Afaik, these libraries are quite big, it sounds like we shouldn't include them automatically for everybody.

**Comment by charpeni** [comment]
@andreicoman11, before version 0.10 of Fresco these libraries were included by default into the Fresco library. Since 0.10, these libraries has been split up, so in theory we don't add much weight to React Native since it was there previously. But I understand what you mean, I just want to be sure you know all facts.

If you still don't want it into React Native, I will add some documentation about gif and webp support into the Image component, just let me know.

**Comment by andreicoman11** [comment]
Thanks for the info @charpeni . The fresco split up was requested by multiple parties, since the whole library was so big. I think we should keep the core size as small as we can, and in this case, the majority of the people won't be needing those libraries.
If you could add docs about gif and webp support, that would be much appreciated.

**Comment by charpeni** [comment]
Good, I will do that.

**Pull request closed without merging**
