### PR TITLE
Make LinkingIOS App extension safe 

### PR DESCRIPTION
**Pull request by shrutic123**
… extension)

Thanks for submitting a PR! Please read these instructions carefully:

- [ X ] Explain the **motivation** for making this change.
Due to the deprecation of NAvigator, moving to react-navigation requires me to include RCTLinkingIOS pod subspex. Including this reveals usage of code that is not allowed inside an App extension ( an iMessage extension in my case). 
- [ X ] Provide a **test plan** demonstrating that the code is solid.
I have made sure that the new code does not cause any errors, but I dont have scenarios that runs the code. Open to suggestions on how to test
- [ X ] Match the **code formatting** of the rest of the codebase.
- [X ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

What existing problem does the pull request solve?
Due to the deprecation of NAvigator, moving to react-navigation requires me to include RCTLinkingIOS pod subspex. Including this reveals usage of code that is not allowed inside an App extension ( an iMessage extension in my case). 

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

## Next Steps

Sign the [CLA][2], if you haven't already.

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by javache** [comment]
Can you configure your Podfile instead to only include LinkingIOS in the  main target and not in the app extension?

**Comment by shrutic123** [comment]
Got an unrelated error in React Android code ( that I didnt touch) 

/home/ubuntu/react-native/ReactAndroid/../ReactCommon/jschelpers/JSCHelpers.h:23: error: undefined reference to 'folly::stringPrintf(char const*, ...)'
/home/ubuntu/react-native/ReactAndroid/../ReactCommon/jschelpers/JSCHelpers.h:35: error: undefined reference to 'folly::stringPrintf(char const*, ...)'
/home/ubuntu/react-native/ReactAndroid/../ReactCommon/jschelpers/JSCHelpers.h:35: error: undefined reference to 'folly::stringPrintf(char const*, ...)'

Any help on how to resolve?

**Comment by shrutic123** [comment]
No I cannot as I am using react-native in my App extension ( iMessage Extension)

**Comment by javache** [comment]
I don't think we should wrap all of our API's like this. Instead, we should try to make react-nativigation not depend on LinkingIOS when it's being used in an extension.

**Comment by shergin** [comment]
@javache I think we have to consider providing workaround for `openURL` in RN. As a former app extension developer I feel this pain. I know that Apple explicitly disallow using `openURL` in extensions, but the reality is that almost all of (for instance) keyboard extensions use that API and... Apple kinda okay with it.

**Pull request closed without merging**
