### PR TITLE
Make loop iterate over all elements in the array

### PR DESCRIPTION
**Pull request by seekshiva**
Was: invariant

### CODE REVIEW

**Comment by ide** [comment]
Can you fix the test that now fails (looks easy to fix, at a glance): https://travis-ci.org/facebook/react-native/jobs/109107195#L1863

**Comment by nicklockwood** [comment]
cc: @ericvicenti

**Comment by seekshiva** [comment]
It doesn't seem like an issue from my code. Should we re-run the tests?

**Comment by facebook-github-bot-5** [comment]
@ericvicenti would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by satya164** [comment]
@seekshiva You can rebase against master to run the tests.

**Comment by facebook-github-bot-1** [comment]
@seekshiva do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by seekshiva** [comment]
@satya164 I've rebased against master.

**Comment by facebook-github-bot-7** [comment]
@seekshiva updated the pull request.

**Comment by satya164** [comment]
cc @ericvicenti @hedgerwang

**Comment by facebook-github-bot-7** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @hedgerwang as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by hedgerwang** [comment]
@seekshiva : this test has been changed a lot. Please rebase and see if this issue is apply. Thanks

**Comment by seekshiva** [comment]
yeah. This PR is not relevant anymore.

**Pull request closed without merging**
