### PR TITLE
Fixes facebook/react-native#9777 Add support for resource-id

### PR DESCRIPTION
**Pull request by lightboys22**
Track react tag using android.view.View.tag.  Allow developers to set resource id by setting component.testID

Thank you for sending the PR! We appreciate you spending the time to work on these changes. 
Help us understand your motivation by explaining why you decided to make this change.

This pull request fixes the following issue.
https://github.com/facebook/react-native/issues/9777

## Test Plan

First, you need to declare the resource id by creating /_your_android_studio_folder_/res/values/ids.xml

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item type="id" name="my_test_id"/>
</resources>
```

Second, set the testID of your component to a resource name.

```
<Button
    onPress={onButtonPress}
    title="Press Me"
    testID='test_id'
    />
```

Third, run the app and observe the resource id using UIAutomator viewer (/Android/sdk/tools/bin/uiautomatorviewer)

## Related PRs

This PR doesn't require a documentation change.

## Release Notes

[ANDROID] [BUGFIX] [com/facebook/react/uimanager/BaseViewManager] - Allow developers to set resource id by setting component.testID

### CODE REVIEW

**Comment by grabvinod** [comment]
@lightboys22 can yo confirm which version of react native this has the support?

**Comment by lightboys22** [comment]
@grabvinod Hi Vinod, I verified my changes on react native v54.
I just rebased my commit and resolved merge conflict.  See the [new pull request here](https://github.com/facebook/react-native/pull/18527).  But I need help fixing the failing tests.

**Comment by nes123** [comment]
Can you clarify where the xml file should added to? I tried to create it in /myproject/android/app/src/main/res/values

but I cant see good results.

**Comment by lightboys22** [comment]
> Can you clarify where the xml file should added to? I tried to create it in /myproject/android/app/src/main/res/values
>
> but I cant see good results.

Hi nes123, that is the correct folder.  But you need to change the React Native source code in order to be able to change the Android.view.View.id

**Comment by nes123** [comment]
any plans to try to merge your changes?

**Pull request closed without merging**
