### PR TITLE
bump gradle to 4.8

### PR DESCRIPTION
**Pull request by dulmandakh**
Bump gradle version to 4.8, and greatly improves performance for sequential/incremental builds. Very useful for native Android development.

## Test Plan

Everything builds as usual, CI is still GREEN https://circleci.com/gh/dulmandakh/react-native/421

## Release Notes

[ANDROID] [ENHANCEMENT] [Gradle] - bump to 4.8

### CODE REVIEW

**Comment by gengjiawen** [comment]
I am getting this error when build RNTester release version on windows (using gradle 4.8). Still not figure out the problem is.
```
> Task :RNTester:android:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':RNTester:android:app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Failed to create MD5 hash for file content.

```

**Comment by dulmandakh** [comment]
Do not install or yarn install, it'll go away.

**Comment by gengjiawen** [comment]
The problem still exists even if I do not install, weird.

**Comment by dulmandakh** [comment]
I had same problem, and did fresh npm install. Sorry for typo

**Comment by gengjiawen** [comment]
On Windows or on macOS ? In both suitable, we may need a fix to `react.gradle` is needed.

**Comment by dulmandakh** [comment]
Works on Mac and Linux (CI). Not sure about Windows, but should be fine.

Your above issue should be caused by JS

**Comment by gengjiawen** [comment]
But I am using nodejs 10.4.1, just as macOS. I have `rm -rf node_modules && npm install` multi times. The problem still exists.

**Comment by dulmandakh** [comment]
Oh yea, I removed .buckd folder and it worked.

**Comment by gengjiawen** [comment]
I am not using buck.

**Comment by dulmandakh** [comment]
me too, but remove if it's there

**Comment by gengjiawen** [comment]
I remove some build cache. The problem still exists.

**Comment by gengjiawen** [comment]
@grabbou @hramos  Next release we may need to do need some test on windows.

**Comment by ACCTFORGH** [comment]
This will be a much needed update. I've encountered a number of libraries that weren't able to compile because of gradle version, one of them being https://github.com/react-native-community/react-native-camera 

However, whenever I try to increment gradle version myself, it always introduces a chain of errors. I'm not familiar with the source code of React Native but I suspect the gradle version upgrade will involve some deeper dependency and configuration change as well.

**Comment by dulmandakh** [comment]
@hramos @mdvacca newer gradle version greatly improves build speed, thus enhance developer experience, but also I think that this PR will make it easier to bump android gradle plugin version in the future

**Comment by dulmandakh** [comment]
@patrickkempff it was causing some issues when used with gradle plugin 3.x. And created another PR with gradle 4.4 or version recommended by Android Studio. https://github.com/facebook/react-native/pull/19899

**Pull request closed without merging**
