### PR TITLE
[npm] Update to stacktrace-parser@0.1.3 and ws@0.8.0 to satisfy io.js 3 / Node 4

### LINKED ISSUE #2258: Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
@ide @vjeux 
https://github.com/Homebrew/homebrew/issues/42553

Thought you guys might run into this issue with using brew inside travis.yml

Simple fix would be 

```
brew update; brew update # Workaround for https://github.com/Homebrew/homebrew/issues/42553
```

instead of

```
brew update
```

### PR DESCRIPTION
**Pull request by ide**
The previous version of stacktrace-parser 0.1.2 had an line in its package.json file that required Node <= 2.x. That line was removed, so it no longer warns on io.js 3.x or Node 4.x.

Similarly, ws 0.8.0 was published with support for the new V8, so it compiles with io.js 3.x and therefore should work with Node 4.x.

Updated the Travis file as well to run on io.js 3.x.

Fixes #2258, #2455

Test Plan:
```
$ nvm use iojs-v3
Now using io.js v3.1.0 (npm v2.13.3)

$ npm i
<no compiler errors>
```

### CODE REVIEW

**Comment by brentvatne** [comment]
:+1: :+1:

**Comment by ide** [comment]
Node 4.0 is expected to ship next week Sep. 3 or Sep. 7, so it would be timely to get this in soon.

**Comment by ide** [comment]
Updated this to use pinned versions instead of the npm caret^

cc @tadeuzagallo

**Comment by tadeuzagallo** [comment]
@facebook-github-bot import

**Pull request merged**
