### PR TITLE
Text docs - Update to improve readability for ellipsizeMode

### PR DESCRIPTION
**Pull request by Frazer**
added context for easier understanding as 'ellipsizeMode' appears before 'numberOfLines' in https://facebook.github.io/react-native/docs/text.html

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Upon first reading the Text docs, the ellipsizeMode function is confusing.  This update aims to remove the confusion.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@Frazer Thanks. I think after you fix the trailing spaces issue, this should be good.

**Comment by Frazer** [comment]
I just removed one trailing space.  Is it possible it passed the second set of tests because github went down?

**Comment by JoelMarcey** [comment]
@hramos This looks reasonable to me; but wanted to get your take and you can land.

**Comment by lacker** [comment]
I think this is some spurious error in FB's internal system. I'll investigate

**Comment by Frazer** [comment]
Github went down for a few minutes when I made this pull request, and tests
were failing for 10-30 minutes after that.  Is there any chance that
introduced some error in the testing system?

**Comment by lacker** [comment]
OK it's merged! Yeah it's extremely possible a GitHub outage introduced some error, I'm fairly astonished that all this syncing between GitHub and the FB internal codebase works in the first place so it's not too surprising when a butterfly flapping its wings in Australia leads to some transient failures. Thanks for bearing through it ;-)

**Pull request closed without merging**
