### PR TITLE
[docs]fix the syntax error in doc tutorial

### PR DESCRIPTION
**Pull request by yeatszhang**
maybe it is a bug when migrating from es5 to es6

### CODE REVIEW

**Comment by bhamodi** [comment]
@yeatszhang - actually the current syntax is correct. It is used to close the `styles` variable.
```js
var styles = StyleSheet.create({
   container: {
     flex: 1,
     flexDirection: 'row',
     justifyContent: 'center',
     alignItems: 'center',
     backgroundColor: '#F5FCFF',
   },
   rightContainer: {
     flex: 1,
   },
   title: {
     fontSize: 20,
     marginBottom: 8,
     textAlign: 'center',
   },
   year: {
     textAlign: 'center',
   },
   thumbnail: {
     width: 53,
     height: 81,
   },
   listView: {
      paddingTop: 20,
      backgroundColor: '#F5FCFF',
    },
 });
```

**Comment by bhamodi** [comment]
Looks good now. :+1:

**Comment by yeatszhang** [comment]
Thanks.  I made a mistake. 😝

**Comment by ide** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
