### PR TITLE
bringSubviewToFront ADD style properties for view …

### PR DESCRIPTION
**Pull request by Iragne**
ADD style properties for view …

bringSubviewToFront: ReactPropTypes.bool,
sendSubviewToBack: ReactPropTypes.bool,

### CODE REVIEW

**Comment by ide** [comment]
Can you design an API closer to z-index? I'm not sure if we want z-index exactly because the stacking context rules get complex but I'm almost certain that exposing bringSubviewToFront as a prop is too inflexible and confusing e.g. consider multiple views that set the prop.

**Comment by Iragne** [comment]
Create something like zIndex is a very bad idea because you have to reorder all and you will lost performance.
However it's possible to rename it like sentToTop.

If i had to do a zIndex i need a liitle bit help to retrive styleproperty from an UIView 

OR

parse the DOM from react 

@ide  Can you help me for that ?

**Comment by ide** [comment]
I'm not too concerned about performance at this point -- we need to design a good API first. Perhaps someone with extensive experience with stacking layers can chime in.

**Comment by brentvatne** [comment]
There are a lot of issues to consider when thinking about z-indexing, I believe this would work best right now as an external library until a comprehensive solution is ready.

**Comment by nicklockwood** [comment]
If performance is a concern, a possible alternative approach would be to set the `layer.zPosition`, although that doesn't affect the order of touch processing, so potentially we could branch the implementation depending on the value of pointerEvents.

In any case, I agree with @ide, exposing bringToFront/sendToBack seems like the wrong abstraction.

**Comment by Iragne** [comment]
Alright let me change my method.
@ide, @nicklockwood  or @brentvatne do you knwn what in react is the method call when the dom is completly finish rendering ?

**Comment by sahrens** [comment]
Agreed this isn't the right API and z-index is fraught with potential issues.

There is no DOM in ReactNative of course, but on the web componentDidMount should be called after renering to the DOM.  We'd like to make it work the same way in ReactNative such that once the native view is rendered comonentDidMount is called, but we haven't gotten around to doing that.  Usually what we do now is use requestAnimationFrame to perform operations after the component has rendered in native.

**Comment by sahrens** [comment]
I'm going to close this PR for now.  Feel free to put up a new one if you can come up with something awesome that is more like a z-index API.

**Pull request closed without merging**
