### PR TITLE
Click basic button & scroll down until item 600 is visible

### PR DESCRIPTION
**Pull request by l2hyunwoo**
## Summary:

This pr is part of issue https://github.com/facebook/react-native/issues/46757 solving a task - [ME2E0008] [ME2E0009]

- Set up a test
  - Starts the app
  - Scrolls until flatlist is visilbe and clicks on flatlist
  - Click basic button
  - Scroll down until item 600 is visible

## Changelog:

[Internal] [Added] - Add e2e-test logic that click button & scroll down until specific item is visible

### Test Locally

- iOS

```bash
yarn install
cd packages/rn-tester
yarn e2e-build-ios
```

- Android

```bash
yarn install
cd packages/rn-tester
yarn e2e-build-android
```

### Start Maestro

- iOS

```bash
 cd packages/rn-tester
 yarn e2e-test-ios
```

- Android

```
cd packages/rn-tester
yarn e2e-test-android
```

### Test in CI

To test in CI, just add a comment on your PR with the text:

```
/test-e2e
```

### Screenshot

스크린샷 2024-10-11 오후 2 59 11

### CODE REVIEW

**Comment by shubhamguptadream11** [comment]
@cipolleschi @l2hyunwoo Any update on this PR?
**ME2E0010** this task seems to be dependent on this.

**Comment by l2hyunwoo** [comment]
@cipolleschi Can you review this pr?

**Comment by alanleedev** [comment]
@l2hyunwoo @cipolleschi @cortinico 
Seems like this test is continually failing on main and may need to be looked into.
It has been mostly red after this was merged.
https://github.com/facebook/react-native/actions/workflows/test-all.yml?page=5&query=branch%3Amain

**Comment by cipolleschi** [comment]
the problem is not the test, but Maestro being unreliable on emulator in CI. Infinite Red is helping out, and we will reach out to the people working on Maetstro to try and reduce flakyness!

**Pull request closed without merging**
