### PR TITLE
Android subpixel text

### PR DESCRIPTION
**Pull request by kevinresol**
Fixes inconsistency in custom font rendering in android. See explanation below.

## Test Plan

I tested the following on my physical device (Sony Z5C) and on Android emulator on Mac.
The test app contains various fonts in the AvenirNext family, which are added to the app as `.ttf` format.

### Before:

Note that the character "thickness" is inconsistent. Some characters looks thicker than other. See the screenshots below as an example:
- Looks thicker: right half of the `g` and `&` as in "Region & Language" (list-view screen)
- Looks thicker: `w` as in `Change Password` (list-view screen)
- Looks vertically compressed: `a` and `e` as in "Message" in the bottom bar (list-view screen)
- Looks thicker: `A`, `N`, `V`, `v` (paragraph screen)
- Looks thinner: `i` (paragraph screen), it leaves extra space on its right hand side

screenshot_20180427-151129
screenshot_20180427-151419

### After: 

Every characters has consistent "weight" and looks nice:

screenshot_20180427-150835
screenshot_20180427-151639

## Related PRs

None

## Release Notes

[ANDROID] [ENHANCEMENT] [CustomStyleSpan] - Enable subpixel text rendering

### CODE REVIEW

**Comment by kevinresol** [comment]
no idea. but maybe @mdvacca? I see him reviewed some PR in the folder

**Comment by kevinresol** [comment]
@mkonicek I see you were the original implementer. Could you give us some comment on this?

**Comment by kevinresol** [comment]
What can I do to get this reviewed?

**Comment by kevinresol** [comment]
@mkonicek @mdvacca sorry to bother but at least I would like to have some feedback/comments

**Comment by kevinresol** [comment]
or @andreicoman11 ?

**Comment by kevinresol** [comment]
@mkonicek @mdvacca @andreicoman11 can even anyone point me to a direction?

**Comment by kevinresol** [comment]
@mkonicek @mdvacca @andreicoman11 could you please at least point me to some possibly responsible persons?

**Comment by kevinresol** [comment]
@mkonicek @mdvacca @andreicoman11

**Comment by kevinresol** [comment]
@mkonicek @mdvacca @andreicoman11

**Comment by kevinresol** [comment]
@pasqualeanatriello any idea I could get this reviewed?

**Comment by kevinresol** [comment]
@hramos sorry to bother but I would like to have someone from facebook to review this, or can you at least give me some directions?

**Comment by kelset** [comment]
Hey Kevin sorry no one of the people you tagged have replied here - I'll try to find someone who can review this, since it's a one-line change I feel it would be a good-to-have in next releases 🤗

(sadly I can't re-run tests, can you rebase your commit to trigger a new one?)

**Comment by kevinresol** [comment]
Updated.

**Comment by kelset** [comment]
Looks like the errors in CI are not related to your commit, let's try to merge it :)

**Comment by kelset** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
