### PR TITLE
Add app to showcase with source link

### PR DESCRIPTION
**Pull request by manonthemat**
3 small changes

Added a published android app to the showcase.

Modified the rendering of the apps.
When there's a _source_ property on the app object, the link will show up as shown in this screenshot.
screen shot 2016-02-04 at 9 13 31 am

Also, external links have the _blank target and not just blank (without the underscore), so a new tab/window will always be opened.

### CODE REVIEW

**Comment by chirag04** [comment]
idk if we need source in the showcase. @brentvatne your call.

**Comment by manonthemat** [comment]
Travis CI seems to be failing because of wordwrap not being installable via npm (even though it's on npmjs.com). Is there anything I can do to solve this issue?

**Comment by satya164** [comment]
ping @brentvatne

**Comment by brentvatne** [comment]
I think adding a source link is fine!

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@manonthemat Seems there are conflicts. Can you fix them before I merge?

**Comment by manonthemat** [comment]
I did, but travis is still failing :(

**Comment by brentvatne** [comment]
@manonthemat - please rebase against master, and squash to one commit :) thanks!

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
