### PR TITLE
Add support for calling .start() multiple times on animated sequence

### PR DESCRIPTION
**Pull request by lbrdar**
## Summary

This PR solves #26790 

## Changelog

[General] [Fixed] - Fix error thrown when sequence animation was started for the second time

## Test Plan

I've added a test to cover this case

### CODE REVIEW

**Comment by TheSavior** [comment]
What happens if start is called again before the first animation sequence finishes?

**Comment by lbrdar** [comment]
@TheSavior good question. It won't break but the animation won't play properly either. 

I don't think other types of animation (e.g. parallel) handle that case. I guess the user should take care of that? What do you expect to happen in that case?

**Comment by TheSavior** [comment]
I'm not sure what the "correct" behavior is here, I just wanted to flag it as it seems like a common edge case of being able to call start multiple times. 

Can parallel be called multiple times? What happens for parallel? Naively, I'd hope that they'd be consistent with respect to each other.

**Comment by cpojer** [comment]
I was going to bring up the same concern that @eliwhite did. I think it makes more sense to me to throw an error if `start` is called more than once. What do you think?

**Comment by lbrdar** [comment]
@cpojer are you suggesting that RN always throw an error when start() is called again or just if it's called before the previous iteration is complete? 

I'd say it makes sense to throw if called while the previous iteration is still running. Otherwise no.  Because I don't see a reason to block a user from starting the same animation multiple times.

**Comment by cpojer** [comment]
Yeah I think that makes sense.

**Comment by lbrdar** [comment]
@cpojer @TheSavior updated per your request. 

Could you help me with failing checks here?

**Comment by cpojer** [comment]
I took an extended break, sorry I didn't get back to your PR earlier. I thought about this some more and do not feel comfortable changing the behavior right now. While I do not know what the original authors intended, I recommend creating new instances for new animations instead of re-using the same ones.

**Pull request closed without merging**
