### PR TITLE
Cherry-pick #9149 into 0.30-stable branch

### PR DESCRIPTION
**Pull request by hramos**
#9149 resolved an issue where Edit on GitHub links lead to a release branch, which results in pull requests being opened against a release branch instead of master. Many issues "resolved" in this manner have already been addressed in master.

This PR is intentionally against `0.30-stable` as it is cherry-picking changes already landed to master.

### CODE REVIEW

**Comment by hramos** [comment]
@JoelMarcey you're the cherry-picking expert here, did I do it right? :)

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @JoelMarcey to be potential reviewers.

**Comment by JoelMarcey** [comment]
@hramos I think so. I see 8 commits here. We all of these commits part of one final squashed commit when landed into `master`? Or are all of these separate commits in `master` itself?

**Comment by hramos** [comment]
My process here was:

1. Check out `0.30-stable` locally.
2. Go to https://github.com/facebook/react-native/pull/9149/commits to find all the commits in that PR
3. For each of them, run `git cherry-pick <commit>` in order.
4. Commit

Seems like for step 2 I should have cherry-picked just the one squashed commit to master instead? That being 01cb1e4ef679dae822e0780331b8c5ef8aab43ad

**Comment by JoelMarcey** [comment]
@hramos Yeah. I think the one, squashed commit would be better to cherry-pick moving forward. However, GitHub loves us and gives us a  `Squash and Merge` :)

So we are ok for this one, as long as we choose that.

screenshot 2016-08-04 15 56 09

**Comment by satya164** [comment]
cc @grabbou

**Comment by hramos** [comment]
Since 0.31 stable is now out, I'll go ahead and open a new PR against it with a proper single squashed commit.

**Pull request closed without merging**
