### PR TITLE
[WebSocket] Add support for binary type data (ArrayBuffer)

### PR DESCRIPTION
**Pull request by lindskogen**
Entirely based on https://github.com/facebook/react-native/pull/1829
I just updated the diff to be compatible with the current master branch.

### CODE REVIEW

**Comment by whokilledtheelectricmonk** [comment]
This just encodes the binary buffer as a string using base64. Unless the server is expecting base64-encoded data, this won't help.

**Comment by lindskogen** [comment]
Actually, it returns an `ArrayBuffer`

**Comment by whokilledtheelectricmonk** [comment]
Woops, :+1:. Is it possible to extend this for 
- Android
- sending messages?

**Comment by lindskogen** [comment]
@whokilledtheelectricmonk Does binary data make android crash too?

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
This one has successfully landed internally. Will be closed once the export is fixed.

**Comment by saulshanabrook** [comment]
Did this add support for array buffers on android as well?

**Pull request closed without merging**
