### PR TITLE
[Android] Add support for full-screen WebView

### PR DESCRIPTION
**Pull request by osdnk**
Motivation: Handle issue https://github.com/facebook/react-native/issues/16444
It was impossible to show full screen in Android's WebView 

## Test Plan

Simply go to page like youtube.com and try to enter full-screen. Before this changes it wasn't possible to do it

## Related PRs
Inspired by: https://github.com/facebook/react-native/pull/10327

## Release Notes

 [ANDROID] [Feature] [WebView] - Add full-screen view

### CODE REVIEW

**Comment by osdnk** [comment]
Did i make sth wrong with release notes?

**Comment by osdnk** [comment]
@hramos, would you like to take a look?

**Comment by arpu** [comment]
would be cool to get this merged

**Comment by arpu** [comment]
how can i use this without waiting for the merge and new release? any hints?

**Comment by patrickkempff** [comment]
@arpu you can [build react-native from source](https://facebook.github.io/react-native/docs/building-from-source)

**Comment by osdnk** [comment]
I'm not convinced if it to a good idea to be dependent on RN's private fork and build from sources from that reason

**Comment by hramos** [comment]
WebView PRs are on hold until https://github.com/react-native-community/discussions-and-proposals/pull/3 is approved.

**Comment by jamonholmgren** [comment]
@osdnk Feel free to submit to the new repo! https://github.com/react-native-community/react-native-webview

**Comment by hramos** [comment]
Let's get this on the new repo instead.

**Pull request closed without merging**
