### PR TITLE
Migrate RCTWebView to WKWebView.

### PR DESCRIPTION
**Pull request by bowerman0**
## Motivation

https://github.com/facebook/react-native/issues/321 - Use WKWebView instead of UIWebView, because WKWebView is faster, consumes less memory, and is more stable.

This is meant to be a drop-in replacement for the existing UIWebView-based RCTWebView.

## Test Plan

Used a web view loosely based on [RNTester's WebViewExample.js](https://github.com/facebook/react-native/blob/master/RNTester/js/WebViewExample.js), and tested in an ejected AwesomeProject. Browsed around the internet.

## Release Notes

[IOS][ENHANCEMENT][RCTWebView] - Migrate RCTWebView to use WKWebView instead of UIWebView.

### CODE REVIEW

**Comment by bowerman0** [comment]
Is there some way to test/fix the flow check locally? I did not change any JavaScript code in this PR, so I am not sure how this broke it.

node 6:
> npm info lifecycle react-native@1000.0.0~flow: react-native@1000.0.0
>
> react-native@1000.0.0 flow /home/circleci/react-native
> flow "check"
>
> Error: node_modules/metro-bundler/src/Bundler/util.js.flow:46
> 46: ): Ast {
>        ^^^ identifier `Ast`. Could not resolve name
>
>
> Found 1 error
>
> npm info lifecycle react-native@1000.0.0~flow: Failed to exec flow script
> npm ERR! Linux 4.4.0-97-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "flow" "--" "check"
> npm ERR! node v6.11.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! react-native@1000.0.0 flow: `flow "check"`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the react-native@1000.0.0 flow script 'flow "check"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the react-native package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     flow "check"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs react-native
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls react-native
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/circleci/react-native/npm-debug.log

and node 8:
> react-native@1000.0.0 flow /home/circleci/react-native
> flow "check"
> 
> Error: node_modules/metro-bundler/src/Bundler/util.js.flow:46
>  46: ): Ast {
>         ^^^ identifier `Ast`. Could not resolve name
>
>
> Found 1 error
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! react-native@1000.0.0 flow: `flow "check"`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the react-native@1000.0.0 flow script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/circleci/.npm/_logs/2017-11-11T19_25_11_051Z-debug.log
> Exited with code 2

**Comment by randyzhao** [comment]
This looks really awesome. Thanks for working on it. 

BTW, not only is `WKWebview` faster, consumes less memory and stable, but it's required by Apple now. 
```
Starting in iOS 8.0 and OS X 10.10, use WKWebView to add web content to your app. Do not use UIWebView or WebView.
```

https://developer.apple.com/documentation/webkit/wkwebview

**Comment by bowerman0** [comment]
Thanks @randyzhao! I'd love to hear any issues that you (or anyone else) run into with the WKWebView version of RCTWebView.

**Comment by grabbou** [comment]
Thanks for the PR. It's quite big, so let me get attention from few more people.

CC: @ide - I think there was an idea of moving WebView outside of React Native as its not extensively used at Facebook? If not, apologies, I probably confused that with another component.

**Comment by bowerman0** [comment]
@ide @grabbou Should the web view move into a standalone module?

**Comment by grabbou** [comment]
That's my understanding. Also, there's already quite interesting community implementation, called `react-native-wkwebview` that I've been using myself.

**Comment by zachrip** [comment]
@bowerman0 @grabbou @ide one reason I'd like to see this hit rn is so that expo will have it without having to eject. So either it'd need to be supported by the expo team (they pull in some modules like this I guess) or it'd have to go in here (in order to use it in expo without ejecting). https://expo.canny.io/feature-requests/p/wkwebview-support - as you can see the request is pretty low in priority :/

**Comment by JamesHealdUK** [comment]
Any updates from the React team on this? This is a crucial part of my app and it would be awesome to *not* have to eject my expo app.

**Comment by grabbou** [comment]
I am pretty sure WebView will remain part of Expo regardless, but you can
ask this on their support forum just in case :)

**Comment by hpmax00** [comment]
Any updates for this pr?

**Comment by RSNara** [comment]
A new `WKWebView` implementation was recently merged into this repository, and then extracted to [react-native-webview](https://github.com/react-native-community/react-native-webview). Since this PR seems to be addressing a problem that was already solved, I'm going to close it.

**Pull request closed without merging**
