### PR TITLE
codegen 107: add interfaceDeclaration prop in parsers

### PR DESCRIPTION
**Pull request by Shubham1429**
## Summary:

part of codegen issue https://github.com/facebook/react-native/issues/34872

> Add a interfaceDeclaration: string property to the Parser class. Implement it in the Flow parser so that it returns InterfaceDeclaration and in the TypeScriptParser so that it returns TSInterfaceDeclaration. Replace the case in the switch  in the [parsers/typescript/utils.js](https://github.com/facebook/react-native/blob/e133100721939108b0f28dfa9f60ac627c804018/packages/react-native-codegen/src/parsers/typescript/utils.js#L69) with this prop.

## Changelog:

[Internal][Added]: Add interfaceDeclaration property in parsers

## Test Plan:

yarn test

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
Wonderful, thanks for these changes! I hope we could move this all block to a common place soon! :D

**Review by migueldaipre — COMMENTED** [review]
There is a typo. (interfaceDelcaration -> interfaceDeclaration)

**Comment by Shubham1429** [comment]
> There is a typo. (interfaceDelcaration -> interfaceDeclaration)

Ohh yeah, thanks for noticing ✌🏼

**Comment by migueldaipre** [comment]
@cipolleschi @Shubham1429 It was merged with typo

**Comment by Shubham1429** [comment]
@cipolleschi It seems PR needed to be re imported before merging.

**Comment by cipolleschi** [comment]
That's... weird... I'll forward fix that.

**Pull request closed without merging**
