### PR TITLE
Build single variant when `deviceId` is given.

### LINKED ISSUE #18409: [android] all flavors are built when trying to run on specific device
When having an app with multiple flavors and trying to run app on specific device or emulator by adding `--deviceId` arg to cli the gradle is building *all* variants of the app which takes enormous amount of time.

### Environment

Scanning folders for symlinks in /Users/***/rn/runandroid/node_modules (10ms)

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.3
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

### Expected Behavior

Single variant should be built when asking to run on specific device.

### Actual Behavior

Gradle is building all variants because of `./gradlew build`.

### Steps to Reproduce

sample project https://github.com/maxkomarychev/rn-runandroid

1. create new project with `react-native init`
2. add flavors to the app in build.gradle (see sample project mentioned above)
3. run `react-native run-android --variant productionDebug --deviceId <some device id>`

### PR DESCRIPTION
**Pull request by maxkomarychev**
Fixes #18409

There's a bug when `deviceId` option is given `./gradlew build` is
executed resulting in *all* variants being built. This is a problem in
projects which have >1 flavor. Only single variant should be built in
this case.

Small hack with `glob` was made to make resolution of `.apk` file
compatible with different versions of gradle plugin:

1. gradle 2 outputs apk to
`[...]/outputs/apk/app-<variant-with-dashes>-debug.apk`
2. gradle 3 outputs apk to
`[...]/outputs/apk/<flavor>/<config>/app-<variant-with-dashes>-debug.apk`

using `glob` it is possible to make it work regardless of version of
gradle plugin.

## Test Plan

The following project can be used as reference for multi-flavor setup https://github.com/maxkomarychev/rn-runandroid
relevant branches: 
* master (default setup, no flavors)
* flavors - extra flavors added
* gradle3 - upgraded version of gradle plugin

#### run default
`react-native run-android` should build & run variant `debug` on all available devices
#### specific variant
`react-native run-android --variant productionDebug` should build, install app on all devices & emulators and run variant `debug`
#### specific variant on specific device
`react-native run-android --variant productionDebug --deviceId emulator-5554` should build, install and run variant `productionDebug` on specific device.
#### default variant on specific device
`react-native run-android --deviceId emulator-5554` should build, install and run variant `debug` on specific device.

## Release Notes

[ CLI ] [ BUGFIX ] [ local-cli/runAndroid/runAndroid.js ] - better support of multi-flavor apps on android. Fix bug when all variants were built when `deviceId` option was given.

### CODE REVIEW

**Comment by maxkomarychev** [comment]
updated release notes, how do I ask bot to re-evaluate this?

**Comment by maxkomarychev** [comment]
I doubt very much I broke tests which are currently failing

**Comment by maxkomarychev** [comment]
is this fine?
image

@hramos bot is going crazy?

**Comment by hramos** [comment]
@maxkomarychev the bot had a crazy weekend but it's under control now.

**Comment by cpojer** [comment]
Thank you for your PR. We just moved this code to https://github.com/react-native-community/react-native-cli so please submit your PR there.

**Pull request closed without merging**
