### PR TITLE
Fix: layout animations on Android

### PR DESCRIPTION
**Pull request by coado**
## Summary:

Layout animations are not working on the new architecture, because the animation driver is not added to the mounting coordinator. When the app starts running, `ReactInstance.java` calls [startSurface](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java#L323-L338) on `FabricUIManager.java`, which starts the surface handler. The animation driver has to be added to the mounting coordinator after the surface handler starts because the mounting coordinator is created there, so I've added a check that will prevent adding an animation driver if the surface handler is not running.

On the other hand, we could just call [startSurface](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/jni/react/fabric/Binding.cpp#L130-L169) from the `Binding.cpp` which adds an animation driver internally, but I guess there is a reason to not do that 🤔

## Changelog:

[ANDROID] [FIXED] - add animation driver to the mounting coordinator on Fabric

## Test Plan:

Tested on examples from [docs](https://reactnative.dev/docs/layoutanimation) in rn-tester.

### CODE REVIEW

**Comment by coado** [comment]
Also, I don't think that setting `UIManager.setLayoutAnimationEnabledExperimental(true)` is necessary anymore 🤔

**Comment by javache** [comment]
If I understand correctly, we already call `setMountingOverrideDelegate` when we call `startSurface`. Do you know why that isn't working and we need a second call?

**Comment by coado** [comment]
> If I understand correctly, we already call `setMountingOverrideDelegate` when we call `startSurface`. Do you know why that isn't working and we need a second call?

Which function do you refer to exactly?

**Comment by coado** [comment]
If you mean the one defined in `Binding.cpp`, this function is not called. ReactInstance calls [startSurface](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java#L323-L338) on FabricUIManager.java, which does not call any of `Binding.cpp` functions that call `setMountingOverrideDelegate`. I am not sure if that's on purpose, so I just added new function that adds animation driver from the FabricUIManager.

**Comment by javache** [comment]
Hmm, startSurfaceWithConstraints and startSurface in FabricUIManager don't seem aligned.  Maybe the issue here is that when `startSurface` is used, and we later call `updateRootLayoutSpecs` we miss some of these steps?

**Comment by javache** [comment]
Working on a fix for this - I believe I found the discrepancy.

**Comment by cortinico** [comment]
Closing in favor of:
- https://github.com/facebook/react-native/pull/46691

**Pull request closed without merging**
