### PR TITLE
iOS websocket: include cookies with request

### PR DESCRIPTION
**Pull request by jellevandenhooff**
This PR modifies the Websocket implementation on iOS to pass cookies to the server. Sending cookies is useful for clients that wish to access protected Websocket endpoints without creating a new authentication protocol.

### CODE REVIEW

**Comment by martinbigio** [comment]
@facebook-github-bot import

**Comment by jellevandenhooff** [comment]
Hi @martinbigio, please let me know if you need anything else on this PR. Thanks!

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by rodrigopivi** [comment]
This is not working for me on #master.

I expect the first handshake request to send the httpOnly cookies that were previously created using fetch, but they are not send. Is this still working for you on master @jellevandenhooff ?

**Comment by jellevandenhooff** [comment]
Hi @rodrigopivi, I think you're right that this no longer works on master. While looking at #7167, I found that 205b5d4732747bac09ebc0f67ed1b1e430ec70fc broke this commit by switching from `initWithURL` to `initWithURLRequest`.

**Pull request closed without merging**
