### PR TITLE
[Android] Webview: Fix broken fullscreen modals due to zero body height.

### LINKED ISSUE #5211: [Android WebView] can't load url
I'm trying to load this URL `https://gitter.im/login` in my web view component, but it doesn't loads.

It just displays this:

I've tried to load it in a default android browser and it had loaded successfully.

Some code: 
```jsx
        <View style={{flex: 1}}>
          <WebView
            ref='webview'
            style={{height: 400}}
            url={'https://gitter.im/login/'}
            javaScriptEnabled={true}
            domStorageEnabled={true}
            onNavigationStateChange={this.onNavigationStateChange}
          />
        </View>
```

I'm on 0.18.0-rc.

Also tried other URLs, and it ~~works perfectly~~ works well only if there is no js. It seems like a bug with enabling javascript. 

Also tried to use `javaScriptEnabledAndroid`, but nothing was change.

### PR DESCRIPTION
**Pull request by danielbraun**
Supersedes PR #8536 
Fixes #5211

JavaScript plugins such as Fotorama are broken when attempting use its fullscreen feature.

If there's an absolute HTML element with 100% height under <body>, its height is 0 when rendered in the Android WebView.

This commit fixes it.

### CODE REVIEW

**Comment by satya164** [comment]
Seems Android tests are failing due to some error with `NativeRunnable`.

cc @bestander

**Comment by bestander** [comment]
Yeah, it is based on a broken trunk.
@danielbraun, could you please rebase on master?

**Comment by danielbraun** [comment]
There's an exception in the test runner, unrelated to the PR. I've seen the same error exception occur in other PR's as well.

**Comment by bestander** [comment]
Can you rebase then?
It should be fine now

**Comment by danielbraun** [comment]
Seems the tests passed.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1096260800458765/int_phab) to review internal test results.

**Comment by bestander** [comment]
@danielbraun could you rebase please?
The patch does not apply

**Comment by facebook-github-bot-1** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by danielbraun** [comment]
try again? I solved the conflicts

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1096260800458765/int_phab) to review internal test results.

**Comment by facebook-github-bot-0** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by bestander** [comment]
We have some infrastructure errors, I'll deal with that

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1096260800458765/int_phab) to review internal test results.

**Pull request closed without merging**
