### PR TITLE
Bump fresco to 2.3.0

### PR DESCRIPTION
**Pull request by mikehardy**
## Summary

Fresco animated-gif and drawee pipeline has an incompatible change from 2.2 to 2.3 and it needs a bump here to use newer fresco:
https://github.com/facebook/fresco/commit/036605d9c3dcd21a8efbfa9e5b5d4f72db36b512

OkHTTP 3.12.x all work with Android 4 (minSdkVersion 16), no need to sit on 3.12.1

Robolectric is test only but better to stay current if possible

## Changelog

[Android] [Changed] - Bump fresco (2.3.0), okhttp (3.12.12), robolectric (4.4)

## Test Plan

I use OkHTTP 3.12.12 in other projects, it works, down to API16 (https://github.com/ankidroid/Anki-Android/blob/44650ca45ab5aac03211cd483dc8d740dd4e4773/AnkiDroid/build.gradle#L249)

Fresco animated-gif 2.2 works fine but attempting to use current stable (2.3) pointed out this incompatibility. CI should show that it works fine?

### CODE REVIEW

**Comment by dulmandakh** [comment]
@mikehardy you need to update buck dependencies too

**Comment by mikehardy** [comment]
@dulmandakh sorry - I know nothing of buck, I'm a non-facebook type person and have never used buck in real life - any pointers?

**Comment by dulmandakh** [comment]
Please look into https://github.com/facebook/react-native/pull/29741 which bumps OkHTTP

**Comment by mikehardy** [comment]
Ah perfect thanks @dulmandakh - need to remove okhttp from my PR then, verify there are no others active for robolectric and/or fresco, then re-push with buck changes. Thanks for the pointer

**Comment by mikehardy** [comment]
@dulmandakh I believe I have BUCK updated correctly, and this applies cleanly to master. Should be ready to go?

**Comment by mikehardy** [comment]
CircleCI refuses to let me in and see the details, so I can't investigate to see if that's from this change or not :shrug:

**Comment by safaiyeh** [comment]
Here ya go @mikehardy 

test_android
```
stderr: /root/react-native/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java:551: error: cannot access com.facebook.fresco.ui.common.OnDrawControllerListener
      combinedListener.addListener(mDownloadListener);
                      ^
  class file for com.facebook.fresco.ui.common.OnDrawControllerListener not found
/root/react-native/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageDownloadListener.java:-1: note: Some input files use or override a deprecated API.

/root/react-native/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageDownloadListener.java:-1: note: Recompile with -Xlint:deprecation for details.

/root/react-native/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.java:-1: note: Some input files use unchecked or unsafe operations.

/root/react-native/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.java:-1: note: Recompile with -Xlint:unchecked for details.

Errors: 1. Warnings: 0.

    When running <javac>.
    When building rule //ReactAndroid/src/main/java/com/facebook/react/views/image:image.

Exited with code exit status 1
```

test_docker
```
stderr: /app/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java:551: error: cannot access com.facebook.fresco.ui.common.OnDrawControllerListener
      combinedListener.addListener(mDownloadListener);
                      ^
  class file for com.facebook.fresco.ui.common.OnDrawControllerListener not found
/app/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageDownloadListener.java:-1: note: Some input files use or override a deprecated API.

/app/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageDownloadListener.java:-1: note: Recompile with -Xlint:deprecation for details.

/app/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.java:-1: note: Some input files use unchecked or unsafe operations.

/app/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.java:-1: note: Recompile with -Xlint:unchecked for details.
```

**Comment by mikehardy** [comment]
Ah okay, looks like it will need a little forward porting. Interesting that a semver minor caused a break but hey, versioning. I'll look into it thanks @safaiyeh

**Comment by dulmandakh** [comment]
hey @mikehardy, I created a PR to bump Fresco to 2.3.0 https://github.com/facebook/react-native/pull/30061

**Comment by mikehardy** [comment]
Thanks @dulmandakh i was just out of time so far, I appreciate it!

**Pull request closed without merging**
