### PR TITLE
Remove survey link

### PR DESCRIPTION
**Pull request by JoelMarcey**
We have enough responses now and we are in the lockdown for improving the documentation.

We can add another "did we improve?" survey after lockdown sometime.

Test Plan:

Went to http://localhost:8079/react-native/docs/getting-started.html (and other pages) and saw that the survey was not in the footer any longer.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @vjeux and @easyCZ to be potential reviewers.

**Comment by vjeux** [comment]
Can you also remove the css and the image from the repo?

**Comment by vjeux** [comment]
(Feel free to ship it when done)

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/828288353972557/int_phab) to review.

**Pull request closed without merging**
