### PR TITLE
Bump Android NDK to r17b

### PR DESCRIPTION
**Pull request by dulmandakh**
This PR bumps Android NDK version to r17b (latest). Cleaned up redundant **LOCAL_EXPORT_CPPFLAGS** rules in .mk files

Test Plan:
----------
Everything compiles and runs as usual

Release Notes:
--------------
[ANDROID] [ENHANCEMENT] [NDK] - Bump to r17b version

### CODE REVIEW

**Comment by gengjiawen** [comment]
Thanks for the job, nicely done. Let's wait the ci fixed on master and then merge this.

**Comment by dulmandakh** [comment]
I did some cleanup and will push once master CI fixed.

**Comment by dulmandakh** [comment]
Done and CI is green 😄. Had to bump buck because it was trying to use removed ABI from NDK, and buck v2018.07.09.01 fixed it with https://github.com/facebook/buck/commit/4ef8e96bae72988f4bd77994a0228a595aa42ac6.

**Comment by dulmandakh** [comment]
@hramos please review and merge

**Comment by dulmandakh** [comment]
I would like to note that RNTester app works as usual. And I found that **LOCAL_EXPORT_CPPFLAGS** exports CFLAGS to including module, which resulted in polluted and mixed CFLAGS.

**Pull request closed without merging**
