### PR TITLE
Add Mixcloud app to the Showcase page

### PR DESCRIPTION
**Pull request by davarisg**
Mixcloud is an online music streaming service for long form audio (radio shows, podcasts, interviews etc.)

We recently did an almost full rewrite of our Android and iOS apps in React Native and we are really loving it!

### CODE REVIEW

**Comment by hramos** [comment]
Thanks for sending this pull request. According to the guidelines in that file, "infoLink" must be one of:

 1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native

I am going to close this, but if you have one of those two things, feel free to reopen with a new link.

**Comment by matclayton** [comment]
It's kinda disappointing that there is a restriction of a funded start up or public company, given we're bootstrapped it kinda makes both impossible (for the time being ;) ). We're shipping react native apps to 8+ Million mobile users now, so it kinda seems against the spirit of it. 

Would the following link work, given it mentions the app/react native? https://developers.facebook.com/case-studies/mixcloud/

**Comment by hramos** [comment]
I can see how this is not great for some people. We decided to come up with a criteria to make sure we did not end up with a bunch of random apps. We want to make sure entries in the showcase provide value to people, and asking for at least a technical blog post that talks about the dev's experience using React Native to develop the app is a fair ask.

You can also submit an entry to the Deco showcase if you prefer: https://www.decosoftware.com/showcase

**Comment by matclayton** [comment]
No worries, the objective of the policy makes a lot of sense.

We've been meaning to write up a technical articles on some of the tricks we've done to get the performance up, would that suffice even though we're not funded startup which is stated as required in the guidelines?

**Pull request closed without merging**
