### PR TITLE
increase MAX_WAIT_TIME

### PR DESCRIPTION
**Pull request by 1mike12**
increase the `MAX_WAIT_TIME` in FileWatcher since live reloading doesn't work for a lot of users on windows when developing android. There may be a better timeout than arbitrarily tripling it, I'm sure the original developer would be able to pick out a good one, but many of us have used this change to finally be able to use RN here on windows. 

fixes https://github.com/facebook/react-native/issues/8784 https://github.com/facebook/react-native/issues/7257

### CODE REVIEW

**Comment by ericnakagawa** [comment]
Hi @1mike12, this looks good on my end. I'm going to accept because this PR only affects the timeout.

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@1mike12 Just curious, why did you for 3x? Would 2x be sufficient?

**Comment by 1mike12** [comment]
@mkonicek like I said, it was completely arbitrary. I picked it because it was the value that a lot of others in the thread were using and seemed to work well for them. For all I know, 2x probably could've worked, but for sure 3x works for everybody.

**Pull request closed without merging**
