### PR TITLE
Remove min/max Width/Height in the docs

### PR DESCRIPTION
**Pull request by vjeux**
An initial implementation was done on css-layout but isn't working correctly on many cases. The binding from React Native has been removed a long time ago. Let's not confuse people and remove it from the docs :)

### CODE REVIEW

**Comment by vjeux** [comment]
I ibgs for those and there aren't any results. It's also not working but I wanted to be sure

**Comment by spicyj** [comment]
:+1:

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
I needed to remove a couple more call sites. https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=maxWidth

**Pull request closed without merging**
