### PR TITLE
Fix incorrect merged asset path with flavor for Android Gradle Plugin 3.2.

### PR DESCRIPTION
**Pull request by yatatsu**
When we use product flavor (e.g. develop/production) with Android Gradle Plugin 3.2,
javascript bundle is not copied due to that merged asset path point to incorrect location.

related #21408

Test Plan:
----------
1. Create new plain react native project.
2. Edit `android/app/build.gradle`, add simple product flavor `one`, `two`.
3. Assemble release apk, and we can find `index.android.bundle` in apk.

Release Notes:
--------------
[ANDROID][BUGFIX][react.gradle] - Fix incorrect merged asset path for Android Gralde Plugin 3.2.

### CODE REVIEW

**Comment by kelset** [comment]
@dulmandakh what do you think?

**Comment by dulmandakh** [comment]
@kelset I'll test it tomorrow 👍

**Comment by ikesyo** [comment]
@dulmandakh Any progress on this?

**Comment by mikemorris** [comment]
I'm building for multiple flavors and https://github.com/facebook/react-native/pull/21408 was an insufficient fix for me (runtime crash with`index.bundle.android` missing from APK assets when building with Gradle 3.2+) but everything is working again with this patch applied. Thanks!

**Comment by ikesyo** [comment]
As @nokite and @mikemorris say this is a working solution, it should be okay to merge this. Could you please land this @kelset?

**Comment by kelset** [comment]
Thanks for the feedback - I'll double check this soon and we'll try to import it.

cc @hramos

**Comment by ikesyo** [comment]
Hi @kelset @dulmandakh @hramos 

Could you take a look and let's import this and cherry-pick into 0.57-branch.

**Comment by dulmandakh** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
