### PR TITLE
Update Flipper

### PR DESCRIPTION
**Pull request by mweststrate**
## Summary

The current Flipper version included in new React Native is quite old, causing some bugs to be present which have long been solved, such as freezing the UI after inspecting it.
Fixes

This fixes https://github.com/facebook/react-native/issues/29492 /
https://github.com/facebook/flipper/issues/1399

## Changelog

[general][changed] - Update Flipper to 0.54

## Test Plan

Updated the RN 0.63.2 based test project https://github.com/mweststrate/flipper-issue-1399-repo with `use_flipper!('Flipper' => '0.54.0')` (in `ios/Podspec`) / `FLIPPER_VERSION=0.52.1` in `gradle.properties` in the test project https://github.com/mweststrate/flipper-issue-1399-repo and verified that everything builds and connects correctly, and that the bug is no longer present.

Tried to run RN-tester project in this repo. For iOS this succeeded, on Android I got a build error:

```
make: Leaving directory '/Users/mweststrate/Desktop/react-native/ReactAndroid/src/main/jni/react/jni'
make: Entering directory '/Users/mweststrate/Desktop/react-native/ReactAndroid/src/main/jni/react/jni'
fcntl(): Bad file descriptor
[armeabi-v7a] Compile++ thumb: folly_json <= FileUtil.cpp
/Users/mweststrate/Desktop/react-native/ReactAndroid/build/third-party-ndk/folly/folly/FileUtil.cpp:37:14: error: no matching function for call to 'wrapNoInt'
make: Leaving directory '/Users/mweststrate/Desktop/react-native/ReactAndroid/src/main/jni/react/jni'
  return int(wrapNoInt(open, name, flags, mode));
             ^~~~~~~~~
/Users/mweststrate/Desktop/react-native/ReactAndroid/build/third-party-ndk/folly/folly/detail/FileUtilDetail.h:34:9: note: candidate template ignored: couldn't infer template argument 'F'
ssize_t wrapNoInt(F f, Args... args) {
        ^
1 error generated.
make: *** [/opt/android_sdk/ndk/21.3.6528147/build/core/build-binary.mk:478: /Users/mweststrate/Desktop/react-native/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/folly_json/folly/FileUtil.o] Error 1
make: *** Waiting for unfinished jobs....
fcntl(): Bad file descriptor
make: Entering directory '/Users/mweststrate/Desktop/react-native/ReactAndroid/src/main/jni/react/jni'
[armeabi-v7a] Compile++ thumb: folly_json <= Demangle.cpp
```

No idea if it is related. I guess not since without making the change I got the same error.

### CODE REVIEW

**Comment by safaiyeh** [comment]
@fkgozali Could we also get this merged in? It resolves an outstanding issue  https://github.com/facebook/react-native/issues/28551

**Comment by fkgozali** [comment]
cc @passy (Flipper team), any concern?

**Comment by fkgozali** [comment]
(I'll import this one and let @passy review internally - for context, I'm focusing on TurboModule related changes for Android/Gradle for now, so I won't be able to merge general PRs at the moment).

**Comment by mweststrate** [comment]
@fkgozali just FYI since I think I pushed this accidentally with my personal account, I'm on the Flipper team ;-)

**Comment by SaeedZhiany** [comment]
Hi,

I have a question (I guess it's not worth it to open a new issue and better to ask it here).

Is it safe to always using the latest version of the flipper and bump its version in RN projects without waiting for the community? or I should always stick with the version that committed in the released RN template and also install the same version of the flipper desktop application?

**Pull request closed without merging**
