### PR TITLE
Fix nits in update View API documentation

### PR DESCRIPTION
**Pull request by JoelMarcey**
Ref comments in #8341

Ref #8203 

Test plan:

Ran site locally.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @janicduplessis to be potential reviewers.

**Comment by caabernathy** [comment]
Excellent!

**Comment by caabernathy** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1127052684006997/int_phab) to review.

**Pull request closed without merging**
