### PR TITLE
add textProps to NavigationHeaderTitle

### PR DESCRIPTION
**Pull request by pkwak-sf**
I want to add option to set props (eg: numberOfLines to truncate long titles) for the internal `<Text/>` in header titles.

### CODE REVIEW

**Comment by hramos** [comment]
Can you explain why this change is needed?

**Comment by pkwak-sf** [comment]
My purpose is to set `numberOfLines`, so long nav-bar titles to are truncated/ellipsized to 1 line, instead of wrapping to multiple lines (and looking visually wrong when it goes beyond 3 lines).
Passing in as textProps (instead of adding numberOfLines only) will give option to set any props that can be set to the <Text> element of the NavigationHeaderTitle.

**Comment by satya164** [comment]
I don't think `textProps` is a good idea. What if you pass both `textStyle` and `style` in `textProps`?

Though why not just use a simple `Text` component? I'm not even sure why we have a `textStyle` prop. It's basically the same as using a own `Text` component with a `style` prop. `NavigationHeaderTitle` is nothing, but a styled text for the header. I don't think we should be adding customisation options to it while you could easily use a `Text` component.

**Comment by pkwak-sf** [comment]
If your recommendation is 'don't use NavigationHeaderTitle', that's fine. This PR is pointing out exactly that, NavigationHeaderTitle can't be used with long titles because the Text doesn't take in props and requires modifications/customizations.
Anyway, if that's the way to go, this PR can be closed. Let me know, thanks.

**Comment by lacker** [comment]
It seems like that's the way to go, so I'm going to close this PR. Thanks for bringing this up!

**Pull request closed without merging**
