### PR TITLE
[Packager] Update Run script to escape spaces in directory name

### PR DESCRIPTION
**Pull request by phamhieu**
Previous discussion in [#668](https://github.com/facebook/react-native/issues/668)

It turns out that my project is moved to a folder with "space" character in the name. So the run script fail to run.
This commit will wrap run script file path in quotes to escape the spaces.

### CODE REVIEW

**Comment by frantic** [comment]
That would definitely be useful, thanks for fixing! Could you please rebase your work on top of current master? TravisCI will ensure that e2e tests are still working.
Sorry about getting to this so late, I somehow missed it.

**Comment by skevy** [comment]
@phamhieu pinging you on this...can you rebase? I know some of these scripts have changed, so please make sure your change still applies when you rebase.

**Comment by satya164** [comment]
Any updates? @phamhieu

**Comment by satya164** [comment]
Closing this. Let's reopen if you are interested to work on this again.

**Pull request closed without merging**
