### PR TITLE
[WebView] WebView's getWebWiewHandle property

### PR DESCRIPTION
**Pull request by tonyhb**
This is meant to be named `getWebViewHandle` instead of `Wiew`, right?

### CODE REVIEW

**Comment by tonyhb** [comment]
@ide done :) made me laugh as autocomplete suggested wiew.

**Comment by vjeux** [comment]
@facebook-github-bot import

**Comment by brentvatne** [comment]
@tonyhb - looks good, seems like this can't be cleanly merged anymore could I bother you to do a rebase?

**Comment by satya164** [comment]
@tonyhb Hey, could you rebase?

**Comment by satya164** [comment]
Closing this. Let's reopen if you are interested to work on this again.

**Pull request closed without merging**
