### PR TITLE
Update Tutorial-IntegrationWithExistingApps.md

### PR DESCRIPTION
**Pull request by sunnylqm**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey to be a potential reviewer.

**Comment by mkonicek** [comment]
cc @ide, @skevy, @davidaurelio

**Comment by mkonicek** [comment]
I don't think this will install compatible versions of React and React Native?

@sunnylqm What's the Test plan?

I'm looking at the CLI code but not sure how we install React, I think we changed this recently:
https://github.com/facebook/react-native/blob/master/react-native-cli/index.js

**Comment by mkonicek** [comment]
@sunnylqm Added the 'needs-revision' label, please check:
https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by skevy** [comment]
Yes, it could break. Latest react@latest is not always compat with react-native@latest.

**Comment by sunnylqm** [comment]
I don't know how to better describe the compatibility problem without modifying this doc time to time. I think they should analyse the npm error hints by themselves.

**Comment by JoelMarcey** [comment]
Where did we end up on this?

**Comment by facebook-github-bot-1** [comment]
@sunnylqm do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Pull request closed without merging**
