### PR TITLE
Add support for web-style data-uris

### PR DESCRIPTION
**Pull request by colinramsay**
This implements base64-encoded data-uris for the Image component.

### CODE REVIEW

**Comment by iamdustan** [comment]
:clap: I’m all for this!

**Comment by vkurchatkin** [comment]
I wonder, what is the use case for this?

**Comment by colinramsay** [comment]
It came up from this question on SO:

http://stackoverflow.com/questions/29380265/does-react-native-support-base64-encoded-images

I think it's one of those things that's expected to *just work*.

**Comment by skpodcast** [comment]
i am going to build SK genesis

**Comment by vkurchatkin** [comment]
What I mean is storing/transferring images in base64 is pretty wasteful

**Comment by iamdustan** [comment]
@vkurchatkin I agree with @colinramsay that Base64 images should just work.

We’re using google drive spreadsheets to power a few internal tools. Images are often inserted as base64 images to guarantee their presence.

**Comment by vjeux** [comment]
:+1: we have this in our internal image component and its pretty handy

**Comment by wootwoot1234** [comment]
I think this could be really useful because it will allow the use of js libraries that generate base64 images.  For example, I'm currently wanting to generate a simple graph.

**Comment by foghina** [comment]
Merged internally and synced.

**Comment by rt2zz** [comment]
heads up for people using data uris, you will need isStatic: true e.g.
`<Image source={{uri: 'data:image/jpeg;base64,'+ base64ImageString, isStatic: true}} />`

**Comment by PaulBGD** [comment]
Thanks @rt2zz! That should be somewhere in the doc.

**Comment by geirman** [comment]
I'm unclear whether this has made it into a release. Doesn't appear so, and I'm not sure whether "Commit has since been removed from the repository and is no longer available." means it never will or not. Can someone explain?

**Comment by vjeux** [comment]
we didn't have a good sync tooling at the time. Should be there

**Comment by geirman** [comment]
Thanks @vjeux, it occurred to me I could just check, so I did. I wasn't able to find the code changes in [master](https://github.com/facebook/react-native/blob/master/React/Base/RCTConvert.m), nor could I find any reference to it in the [RCTConvert.m history[(https://github.com/facebook/react-native/commits/master/React/Base/RCTConvert.m). To make doubly sure I'm not a complete idiot (which is totally still possible), [I setup a test at rnplay](https://rnplay.org/apps/PAj27w) using the isStatic: true referenced in [@rt2zz's April 21st comment](https://github.com/facebook/react-native/pull/576#issuecomment-94962156).

**Comment by vjeux** [comment]
I can see it here: https://github.com/facebook/react-native/blob/4472bb54c97c3284cf959e1671729d6b6cb60ff1/React/Base/RCTConvert.m#L871-L872

But, the comment at the top says "/* This method is only used when loading images synchronously, e.g. for tabbar icons */" so maybe it's not working.

Would happily take in a pull request that actually makes it work :)

**Comment by vjeux** [comment]
Also, isStatic should no longer be needed.

**Comment by vjeux** [comment]
Looks like most of the image code blames to @nicklockwood, maybe he knows what's going on here

**Comment by nicklockwood** [comment]
@geirman your code looks OK to me (as @vjeux says, `isStatic` isn't needed, but it shouldn't stop it from working either).

There's a base64 example in the UIExplorer Image example (the puzzle piece). It was working last time I checked.

**Comment by geirman** [comment]
Thanks @nicklockwood. I found the [UIExplorer Image Example you referenced](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ImageExample.js#L391,L394) and updated [my rnplay example](https://rnplay.org/apps/PAj27w) to match. I wasn't able to get it to work, but noticed something strange as I was setting it up. When I add borderWidth to the styles element, I get the `No suitable image URL loader` error. If I remove it, the image isn't showing, but that's probably something I'm doing wrong. I think this might be a bug. 

See for yourself by taking the following steps.

1. Go to [my rnplay example](https://rnplay.org/apps/PAj27w)
2. with the image styles set to `style={[styles.base64, styles.outline]}`, notice the `No suitable image url loader` error
3. now set Image styles to `style={[styles.base64]}`, notice there is no error (also no image, but that might be my fault)

**Comment by kevando** [comment]
I get the same "No suitable image URL loader error. " 

IT happens the Image component, but I can render the base64 icons with the TabIOS component. Anything beyond javascript is sort of a black box to me, so I'm happy to provide any of my configuration settings if that helps.

**Comment by geirman** [comment]
Looks like we need to reopen this issue

**Comment by kevando** [comment]
Alternatively - I really just want a way to upload images from the camera roll (ios) in my app and just store the base64 encoding and not have to worry about the file path (because it breaks between app versions).

**Comment by mkonicek** [comment]
Based on Nick's comment:

> @geirman your code looks OK to me (as @vjeux says, isStatic isn't needed, but it shouldn't stop it from working either). There's a base64 example in the UIExplorer Image example (the puzzle piece). It was working last time I checked.

And other people reporting "No suitable image URL loader error." after I'd say we should open a GitHub issue for this, or better a StackOverflow question, to figure out what's going on and if Base64 Images are supported now.

This pull request is almost a year old now and would have to be rebased. I suggest we close it and discuss what needs to be done first and then make a new PR if needed.

**Pull request closed without merging**
