### PR TITLE
Update EmbeddedAppIOS.md

### PR DESCRIPTION
**Pull request by sunnylqm**
Now react should be installed separately.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @davidyaha and @hfossli to be potential reviewers.

**Comment by hfossli** [comment]
LGTM

**Comment by davidyaha** [comment]
Hi, 
Already included here: https://github.com/facebook/react-native/pull/7810.
Great day,
David

**Comment by sunnylqm** [comment]
OK

**Pull request closed without merging**
