### PR TITLE
[Text] Support "textAlign: justify" in Text components

### LINKED ISSUE #529: [Text] textalign should implement 'justify' css property
"justify" property seems to be crucial in order to implement nice text alignment we know so well from newspapers and magazines (and latex). Right now, it doesn't seem to be implemented. If it is a simple implementation, I could try to take a stab at it, if someone shows me how it is implemented for other values.

### PR DESCRIPTION
**Pull request by ide**
Finished adding support for justified text on iOS... just had to expose a prop value.
Fixes #529

Test Plan: View the Text example in the UIExplorer and see that all but the last lines of text in the justified text example are justified and extend to the far right of the available space. Tested on iOS 8, iPhone 6 simulator.

text

### CODE REVIEW

**Comment by sahrens** [comment]
So I think the history is that we intentionally removed this when we found out that android doesn't support justified spacing (see http://stackoverflow.com/a/4314724 for lolz).

I'm not sure that's the right call, though, and honestly I'd rather just land this than hamstring iOS capabilities.

One thing we also considered was naming it "justifyIOS" or something to make it clear it's IOS-only (although windows phone and other platforms probably support it?), or just put a comment in the code.  A redbox on Android might also be sufficient.  Thoughts?

**Comment by sahrens** [comment]
Also, can you fix tests?  You need to re-record the snapshot:

2015-06-02 00:42:56.318 UIExplorer[2473:7064] If you have Kaleidoscope installed you can run this command to see an image diff:
ksdiff "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/Examples-UIExplorer-UIExplorerApp/reference_testTextExampleSnapshot_1@2x.png" "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/Examples-UIExplorer-UIExplorerApp/failed_testTextExampleSnapshot_1@2x.png"
2015-06-02 00:42:56.355 UIExplorer[2473:7064] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** Assertion failure in __32-[RCTTestModule verifySnapshot:]_block_invoke, /Users/travis/build/facebook/react-native/Libraries/RCTTest/RCTTestModule.m:55: Snapshot comparison failed: Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo=0x7abbe320 {NSLocalizedDescription=Images different}'

**Comment by ide** [comment]
> One thing we also considered was naming it "justifyIOS" or something to make it clear it's IOS-only (although windows phone and other platforms probably support it?), or just put a comment in the code. A redbox on Android might also be sufficient. Thoughts?

My preference is to add a comment and document it because that's easiest and I can't test Android, and the failure mode on Android will have a sane default -- I expect it will either redbox because it doesn't know what to do with the prop value, or it will fall back to left-aligned text which is still totally usable and at worst a lo-pri bug in most cases.

**Comment by sahrens** [comment]
Yeah, let's go with the comment.

**Comment by sahrens** [comment]
I fixed by re-recording locally, but did you do something funky to the snapshot images after recording them?  Our internal png crush script couldn't process them:

Crushing Libraries/FBReactKit/js/react-native-github/Examples/UIExplorer/UIExplorerIntegrationTests/ReferenceImages/Examples-UIExplorer-UIExplorerApp.ios/testTextExampleSnapshot_1@2x.png
Traceback (most recent call last):
  File "/Users/sahrens/src/fbobjc-hg/Tools/pngcrush/../IconStamp/png_meta.py", line 80, in <module>
    parse_header(f)
  File "/Users/sahrens/src/fbobjc-hg/Tools/pngcrush/../IconStamp/png_meta.py", line 17, in parse_header
    if not all([ord(f.read(1)) == PNG_SIGNATURE[i] for i in xrange(0, len(PNG_SIGNATURE))]):
TypeError: ord() expected a character, but string of length 0 found

While measuring IDATs in /Users/sahrens/src/fbobjc-hg/Libraries/FBReactKit/js/react-native-github/Examples/UIExplorer/UIExplorerIntegrationTests/ReferenceImages/Examples-UIExplorer-UIExplorerApp.ios/testTextExampleSnapshot_1@2x.png pngcrush caught libpng error:
   Read Error

Could not find file: /Users/sahrens/src/fbobjc-hg/Libraries/FBReactKit/js/react-native-github/Examples/UIExplorer/UIExplorerIntegrationTests/ReferenceImages/Examples-UIExplorer-UIExplorerApp.ios/testTextExampleSnapshot_1@2x.png_tmp

We should probably just disable the crush lint for ReferenceImages...

**Comment by ide** [comment]
I don't think I did anything weird to the screenshots. I captured them by opening the UIExplorer project, set `_runner.recordMode = NO` to `YES`, and hit Cmd+U. I do have imagemagick and a couple of other image processing programs on my laptop (OS X 10.10.3) so perhaps they got automatically invoked somewhere along the way.

**Pull request closed without merging**
