### PR TITLE
Native Animated - Fix timing animation delay on iOS

### LINKED ISSUE #12388: Bugs in Animated + useNativeDriver time values
### Description

When `useNativeDriver` is used with a supported value like `opacity`, several bugs manifest around time values:

- `delay` appears to operate in seconds, not milliseconds. This makes it look like the animation doesn't run at all, when in fact it's just delaying for several minutes.
- When `delay` is set, `duration` doesn't appear to work – animations just jump to their end frame without tweening.

### Reproduction

https://rnplay.org/apps/MQ5xNg

### Solution

unknown

### Additional Information

* React Native version: 0.40.0
* Platform: iOS only (don't think useNativeDriver is implemented on Android yet)
* Operating System: MacOS

CC @kmagiera @janicduplessis

### PR DESCRIPTION
**Pull request by janicduplessis**
Delay was broken with native animations on iOS. After checking what android does to handle delay, I noticed it does nothing at all since the delay is already handled when generating the animation frames. This removes all code that tried to handle delay on iOS since it is not needed and breaks it. Also updated an example to have delay in UI explorer.

Fixes #12388

**Test plan**
Tested that delay works in UIExplorer on iOS and Android.

### CODE REVIEW

**Comment by janicduplessis** [comment]
cc @ide

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@ide Could you try this again?

**Comment by ide** [comment]
@facebook-github-boy shipit

**Comment by ide** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
