### PR TITLE
isModalInPresentation prop for iOS >= 13

### PR DESCRIPTION
**Pull request by luco**
## Summary

Adds a `isModalInPresentation` for  iOS >= 13, which prevents the modal with `presentationStyle` set as `pageSheet` or `formSheet` being dismissed with swipe down.

## Changelog

[iOS] [Added] - `isModalInPresentation` Modal prop for  iOS >= 13 for preventing modal with `presentationStyle` set as `pageSheet` or `formSheet` being dismissed with swipe down.

## Test Plan

ezgif-4-4e84d1284557

### CODE REVIEW

**Comment by mrousavy** [comment]
On `react-native` 0.63 this doesn't work anymore, the `modalInPresentation` propertiy must somehow get overridden?

**Comment by luco** [comment]
@shergin Can you review this?

**Comment by rafaelmotta** [comment]
Is there any way of reviewing this pull request? It's super annoying this issue, and there's no way to use a modal with pageSheet or formSheet with this bug.

**Comment by burakgormek** [comment]
Any update?
We can get new PR based on this one for attention. Looks like new PRs being quickly reviewed.

**Pull request closed without merging**
