### PR TITLE
Improved window.postMessage implementation

### PR DESCRIPTION
**Pull request by tqc**
Adds a queue to postMessage so that messages sent close together are not lost. 

Setting location="a";location="b" results in only "b" reaching shouldStartLoadWithRequest. Making the second update asynchronous with setTimeout does not fix the issue unless a delay is added.

With this update, postMessage queues "b" until it gets a "message:received" event that confirms "a" has already been processed.

The included test sends two messages from a webview and checks that both are received. It fails against the preexisting code with the first message being dropped.

### CODE REVIEW

**Comment by jacobp100** [comment]
LGTM

**Comment by SRandazzo** [comment]
So happy to find this and know i'm not crazy that messages were being dropped, looking forward to this being integrated thanks!

**Comment by headlessme** [comment]
Any idea when this might get merged?

**Comment by jacobp100** [comment]
I can’t merge it, it has to be someone on the FB team. @spicyj?

**Comment by lacker** [comment]
This branch has conflicts, could you resolve them? After that it looks good to me and I can help merge it in.

**Comment by tqc** [comment]
I've merged in the current master. The ci failure appears to be an unrelated timeout. 

Do I need to squash/rebase, or does the merge script handle that?

**Comment by mayfield** [comment]
Anything I can do to help get this cleaned up and merged?  I have a use-case that's completely dependant on a reliable `postMessage` on ios.

**Comment by jacobp100** [comment]
It looks like the ci is still failing. Merge in the latest master and see it that fixes things!

**Comment by tqc** [comment]
Looks like a bug / invalid assumption in the ci script - current master has some lint errors in files not touched by this pull request, and code-analysis-bot.js fails because the lines with errors are not in the patch file.

**Comment by tqc** [comment]
Trying a rebased version. code-analysis-bot works with a list of files changed in the latest (merge) commit, which included 3 months of master updates rather than the actual changes in this pull request.

**Comment by farazs** [comment]
Curious why this approach isn't used? http://www.joshuakehn.com/2014/10/29/using-javascript-with-wkwebview-in-ios-8.html

According to the react-native readme `Supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0.`

**Comment by tqc** [comment]
@farazs Totally off topic on this PR, but the initial versions of wkwebview have bugs that prevent their use in this context.

**Comment by blankg** [comment]
Hi @tqc, is this PR still active? (also wanted to propose a similar solution)

**Comment by jacobp100** [comment]
If this is ready, try pinging someone on the Facebook team!

**Comment by tqc** [comment]
It's ready and waiting to be merged, assuming that there aren't any more random test failures after a merge to fix conflicts

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/improved-windowpostmessage-implementation

**Comment by jacobp100** [comment]
@hramos I'm not sure this should be closed: it's working and just waiting to be merged.

**Comment by hramos** [comment]
Agreed, closed prematurely in error.

**Comment by hramos** [comment]
@tqc can you take a look at the conflicts? Then I'll try importing again.

**Comment by tqc** [comment]
@hramos I've fixed the conflict. However, the conflicting change was made 3 hours after the import failed - likely the import error was just the result of all builds being broken at that point.

**Comment by sachinrekhi** [comment]
I'm running into this issue where 2 postMessage calls made close together result in only one of the messages reaching the react native app. Seems like this PR would fix it!

But is there any workaround in the meantime?

**Comment by sachinrekhi** [comment]
@tqc I see that the PR adds a queue when you are sending messages from the web view out to React Native. I'm curious, is the other way error free? As in calling postMessage from the react native side to send a message to the web view doesn't have any issues in terms of potentially losing messages that are sent too close together?

**Comment by tqc** [comment]
@sachinrekhi You could lose anything sent before the web code adds a message listener, but there shouldn't be any issues after initialization - stringByEvaluatingJavaScriptFromString blocks until the message is properly sent, and it is calling document.dispatchEvent rather than setting a variable which could be overwritten.

**Comment by hramos** [comment]
The PR was merged on July 28, 2017. The fix has been in place for a while.

**Pull request closed without merging**
