### PR TITLE
fix ListView renderSeparator

### PR DESCRIPTION
**Pull request by jetzhliu**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Example: When "Adding a function to do X", explain why it is necessary to have a way to do X.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

ListView separator should not render after last row at any sections.

### CODE REVIEW

**Comment by dsibiski** [comment]
I believe this is a matter of choice for the developer and some may want the separator to render. It should be up to them whether they display it or not.

The current implementation is how it works on UIKit.

**Comment by dsibiski** [comment]
@facebook-github-bot expected

**Comment by facebook-github-bot-1** [comment]
@pglotov would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by damusnet** [comment]
@facebook-github-bot expected

**Comment by lacker** [comment]
This is expected behavior so I'm going to close this PR.

**Review by Chandramuhilan — COMMENTED** [review]
## 🤖 Automated PR Review

**PR:** fix ListView renderSeparator
**Files Changed:** 1
**Lines:** +1 -2

### Pattern-Based Analysis

**Total Issues Found:** 10


### ⚠️ High Priority (3)
- **Line 2**: Potential division by zero - add zero check
- **Line 2**: Potential division by zero - add zero check
- **Line 2**: Potential division by zero - add zero check


### ℹ️ Medium Priority (1)
- **Line 4**: Potential null pointer access - add null check


---
*Generated by PR Review Agent*

**Review by Chandramuhilan — COMMENTED** [review]
## 🤖 Automated PR Review

**PR:** fix ListView renderSeparator
**Files Changed:** 1
**Lines:** +1 -2

### Pattern-Based Analysis

**Total Issues Found:** 10


### ⚠️ High Priority (3)
- **Line 2**: Potential division by zero - add zero check
- **Line 2**: Potential division by zero - add zero check
- **Line 2**: Potential division by zero - add zero check


### ℹ️ Medium Priority (1)
- **Line 4**: Potential null pointer access - add null check


---
*Generated by PR Review Agent*

**Pull request closed without merging**
