### PR TITLE
fix windows ci

### PR DESCRIPTION
**Pull request by gengjiawen**

### CODE REVIEW

**Comment by cpojer** [comment]
@facebook-github-bot shipit

**Comment by cpojer** [comment]
Dammit. I’m on mobile and thought this would still work.

**Comment by gengjiawen** [comment]
@cpojer No hurry at all :). Also we should wait for windows build run all tests.

**Comment by gengjiawen** [comment]
windows build passed: https://ci.appveyor.com/project/Facebook/react-native/builds/20843535.

**Pull request closed without merging**
