### PR TITLE
Update to new ReactPerf

### PR DESCRIPTION
**Pull request by gaearon**
This is a work in progress on removing the dependency on the old ReactPerf and replacing it with the new one. Related PRs in React: https://github.com/facebook/react/pull/6647, https://github.com/facebook/react/pull/6046.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @sebmarkbage and @tadeuzagallo to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
@gaearon updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@gaearon updated the pull request.

**Comment by gaearon** [comment]
This is ready for review.
It depends on https://github.com/facebook/react/pull/6647.

@sebmarkbage

**Comment by satya164** [comment]
@gaearon Tests seem to be broken!

**Comment by gaearon** [comment]
Sorry, I should have been clear.
It depends on a version of React that hasn’t been released yet.
I won’t be available the next two weeks so I’m leaving this for the team to merge during the next RN sync.

**Comment by satya164** [comment]
@gaearon Okay then. I'm assigning this to @sebmarkbage as he usually does the sync.

**Comment by gaearon** [comment]
Test plan:

1. Launch any app
2. Cmd D, Start Systrace
3. Mount, update, unmount some views
4. Cmd D, Stop Systrace
5. Drop generated JSON on about:tracing and check it contains reconciler and composite events

For the other change,

1. Add RCTRenderingPerf toggle() and start() calls on init
2. Add stop() call in a timeout
3. Do stuff
4. Check that it logs tables similar to the tables on the web

**Comment by spicyj** [comment]
Landed as part of a95405f4194480d22005df0ac1c32e44753d17be, thanks.

**Pull request closed without merging**
