### PR TITLE
Use mergeFast in a hotspot

### PR DESCRIPTION
**Pull request by rigdern**
In profiling our app, we found that the usage
of `merge` in `Text.js` was showing up as a
hotspot. We've replaced this usage of `merge`
with `mergeFast`.

**Test plan (required)**

This change is used in my team's app.

Adam Comella
Microsoft Corp.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @MattFoley to be potential reviewers.

**Comment by MattFoley** [comment]
This is the first time I've been poked by Github bot, but this change looks good to me. 

The only suggestion I would have is to use `let` or even better `const`, rather than `var`, but I don't know RN's policy on using ES6 syntax in the main repo.

**Comment by ide** [comment]
`merge(a, b)` and `mergeFast(a, b)` aren't guaranteed to be the same for all (a, b), which is concerning since `merge(a, b)` is run in` __DEV__` but not production. Keeping dev and production the same as much as possible is one of the best ways to head off bugs.

It would be better either to use `mergeFast` in all environments or write a new helper function like `mergeOwnPropertiesFast` with the same semantics as `merge` by doing `hasOwnProperty` checks or iterating over `Object.keys`, whichever's faster.

**Comment by rigdern** [comment]
@ide you make a good point about dev vs production. I updated my PR to use `mergeFast` in all environments.

**Comment by facebook-github-bot-9** [comment]
@rigdern updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9654/files/2fa121bb3e276231792269fb62b91d904c5dd9d1..af55fa8da24cfdd215100c6b620e2626fa394069)

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3801791) to review internal test results.

**Pull request closed without merging**
