### PR TITLE
Add assign module constants pre check for performance improve.

### PR DESCRIPTION
**Pull request by yuanyan**

### CODE REVIEW

**Comment by ide** [comment]
(a) how big of a performance improvement is this? and
(b) we should make Object.assign fast instead of making every callsite have to do this

**Comment by nicklockwood** [comment]
Is there any reason to use Object.assign() instead of just `module.constants =`?

**Comment by ide** [comment]
@nicklockwood Object.assign loops over each key in `constants` and assigns it to `module`.

**Comment by nicklockwood** [comment]
Oh, of course. Never mind then.

**Comment by yuanyan** [comment]
@ide In most time, `constants ` is null, only small detail improve.

**Comment by ide** [comment]
Did you measure the performance improvement? I ask because it seems like it would be very small since this code is run only once per native module and if calling the Object.assign is slow, we should speed up the Object.assign polyfill.

**Pull request closed without merging**
