### PR TITLE
Remove defaultProps from DrawerLayoutAndroid

### PR DESCRIPTION
**Pull request by Setito**
## Summary

Issue #31647. Removing the property defaultProps from the component DrawerLayoutAndroid.android.js

## Changelog

[Android] [Removed] - Remove defaultProps from the DrawerLayoutAndroid component.

### CODE REVIEW

**Review by lunaleaps — CHANGES_REQUESTED** [review]
Thank you for working on this!

We'll still want to use 'white' as the default `drawerBackgroundColor` but not leverage React's `defaultProps`. For example on line 192, we're still reading the value of `drawerBackgroundColor`, if that value is null/undefined, we'd like to use the default of 'white'.

If you run the jest tests (I believe through `yarn test`) then I think the DrawerLayoutAndroid-test will fail currently.

**Review by pedrocardoz0 — COMMENTED** [review]
At line `177` try to use something like this:

```
const {
      onDrawerStateChanged,
      drawerBackgroundColor="white"
      ...props
 } = this.props;
```

**Review by pedrocardoz0 — APPROVED** [review]
👍

**Comment by Setito** [comment]
Thank you @pedrocardoz0 for reaching out and giving advice.
It looks obvious that immutability was the correct answer here, I will remember it for future developments.
Besides, sorry for the delay on this.

**Comment by lunaleaps** [comment]
Closing this as I think https://github.com/facebook/react-native/pull/32162 addresses this issue now

**Pull request closed without merging**
