### PR TITLE
Publish DocDown Commits Into Next Release (0.29)

### PR DESCRIPTION
**Pull request by JoelMarcey**
We want to get the results of our documentation lockdown into the hands of users asap without them having to go to `next`. `0.29` is planned to be released within the next several days, so this will get it in the hands of users sooner rather than another 2+ weeks.

This interactive rebased all of our docdown commits onto the `0.29-stable` branch. e.g., 

```
git rebase -i --onto docdown-to-0.29-stable f2affcf24dd7ff12455c0bc12f693dda5a196244^
```

Test Plan:

The site looks the same as it currently does at http://facebook.github.io/react-native/releases/next/

screencapture-localhost-8079-react-native-docs-image-html-1467156577327
screenshot 2016-06-28 16 28 40
screenshot 2016-06-28 16 28 25
screenshot 2016-06-28 16 28 14
screenshot 2016-06-28 16 28 02

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @RetroPoktan to be potential reviewers.

**Comment by lacker** [comment]
As far as I can tell from my mere-human reviewing, this has the stuff I'm aware of in it. So LGTM. I'll leave it to you to figure out when to ship

**Comment by caabernathy** [comment]
It all looks good to me.

**Comment by bestander** [comment]
Ok, let's do this.
cc @grabbou this is a large one and improves all docs, I'll squash the commits

**Pull request merged**
