### PR TITLE
[docs] Deprecate MapView in favor of airbnb/react-native-maps

### PR DESCRIPTION
**Pull request by mkonicek**
Compared to the `<MapView>` that comes with React Native, [react-native-maps](https://github.com/airbnb/react-native-maps) work on Android and is more feature complete. It is actively maintained and used extensively (9.2k installs / month, see [JS.Coach](https://js.coach/react-native/react-native-maps?search=react-native-maps)).

We think now is a good time to switch to react-native-maps in your applications and make `react-native-maps` the official `<MapView>` implementation for React Native.

We are going to release the deprecated `<MapView>` as a separate npm module so you can migrate to `react-native-maps` at your own pace.

**Test Plan**

Checked the docs render correctly on the website:

```
cd website
npm install
npm start
```

screenshot 2016-11-01 20 17 31

Warning is shown:

screenshot 2016-11-01 20 39 21

Published the module separately (https://github.com/facebookarchive/react-native-deprecated-modules, will also publish to npm in January) so people can continue using it and migrate to Airbnb maps at their own pace. Linked the module to a sample app using `react-native link`, it works 🎉 

    import MapView from 'deprecated-react-native-ios-mapview';

    export default class MapsTest extends Component {
      render() {
        return (
          <View style={styles.container}>
            <Text style={styles.welcome}>
              Welcome to React Native!
            </Text>
            <MapView
              style={{width: 200, height: 200, margin: 40}}
              showsUserLocation={true}
              onRegionChangeComplete={(region) => {alert(region.longitude)}}
            />
    ...

screenshot 2016-11-01 18 43 14

### CODE REVIEW

**Comment by spikebrehm** [comment]
Exciting!

**Comment by lacker** [comment]
How about making it so that if you use this class, a warning gets logged?

**Comment by lacker** [comment]
What do people have to do to make this warning go away - just `npm install deprecated-react-native-ios-mapview` and add the appropriate import? Also, let's not refer to it as "Airbnb maps" any more than we refer to the existing one as "Facebook maps" - let's just call it "the react-native-maps module".

**Comment by mkonicek** [comment]
> What do people have to do to make this warning go away - just npm install deprecated-react-native-ios-mapview and add the appropriate import?

Yes that will work, but probably only at version >= 0.42 where we remove the native code. If people install `deprecated-react-native-ios-mapview` (and `react-native link` it) they'd have the Obj-C code twice, until we remove it in v0.42. Let me check how that works but seems strange.

Ideally people would migrate to react-native-maps to make the warning go away. But I see your point the warning can be annoying and you'd just like to make it go away. We have other deprecation warnings like this in the codebase though - maybe their point is to always be visible until you fix the code?

**Comment by mkonicek** [comment]
Updated the warning message 👍

**Comment by lacker** [comment]
Looks good. Not sure if the travis error is spurious - I'll try rebuilding. Once CI is clear let's shipit.

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@lacker Sandcastle confirms this breaks some screenshot tests (probably by showing the warning :)). I'll fix that.

**Comment by mkonicek** [comment]
@lacker Should be good to go now, tests passed.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
