### PR TITLE
Link fix on Splash, add TRED.

### PR DESCRIPTION
**Pull request by alexleventer**
Fix the link for Splash, add TRED to React Native app showcase.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
@alexleventer updated the pull request.

**Comment by lacker** [comment]
Hey, I changed up the format on the showcase. It would be great to have a listing for Tred though. Maybe this article - http://www.geekwire.com/2015/mobile-dealership-tred-raises-another-1m-to-help-used-car-owners-make-more-money/ with an infoTitle like "Mobile Dealership Tred Raises $1M"? See https://github.com/facebook/react-native/pull/8263 for the new format.

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @lacker as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by hramos** [comment]
@alexleventer do you still want to merge this?

**Comment by alexleventer** [comment]
Yea @hramos - updating now

**Comment by hramos** [comment]
Ping

**Comment by mkonicek** [comment]
@alexleventer I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment asks a question. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to continue working on this.

**Pull request closed without merging**
