### PR TITLE
update the way of starting packager on windows

### PR DESCRIPTION
**Pull request by sunnylqm**
update the way of starting packager on windows

### CODE REVIEW

**Comment by mkonicek** [comment]
:+1: Thanks a lot!

**Comment by mkonicek** [comment]
Looks like you need to rebase, I've changed that file recently. Then I'll merge this.

**Comment by sunnylqm** [comment]
@mkonicek I've rebased.

**Comment by sunnylqm** [comment]
Sorry for uncarefully closed this PR. Please check it again! @mkonicek

**Comment by satya164** [comment]
Shouldn't `react-native start` work for all versions? Do we need to document 2 different ways?

**Comment by sunnylqm** [comment]
@satya164 `react-native start` can not be guaranteed for legacy versions.

**Comment by mkonicek** [comment]
We don't support old versions in any way, we ask people to always be on the latest version. Please simply document `react-native start`. Thanks for adding the note about the watcher timeout!

**Comment by mkonicek** [comment]
:+1: Thank you!

**Pull request merged**
