### PR TITLE
[flow-strict] Flow strict in DatePickerAndroid.android.js, DatePickerAndroid.ios.js

### PR DESCRIPTION
**Pull request by nd-02110114**
Related to #22100

Turn Flow strict mode on for DatePickerAndroid

## Test Plan:
- [x] npm run prettier
- [ ] npm run flow-check-ios
- [ ] npm run flow-check-android
 
This error was happend #22101 #22048 

## Release Notes:
[GENERAL] [ENHANCEMENT] [Components/DatePickerAndroid/DatePickerAndroid.android.js] - Flow strict mode
[GENERAL] [ENHANCEMENT] [Components/DatePickerAndroid/DatePickerAndroid.ios.js] - Flow strict mode

### CODE REVIEW

**Comment by nd-02110114** [comment]
I got this error...
```
// Getters and setters can have side effects and are unsafe. (unsafe-getters-setters)
static get dismissedAction() {
    return 'dismissedAction';
}
```

I should add `unsafe.enable_getters_and_setters` in .flowconfig?

**Comment by empyrical** [comment]
I am not quite sure why those are getters. (Perhaps in an earlier revision, they were getting things from `NativeModules`?)

But you should be able to change them to normal static properties like:

```js
static dismissedAction = 'dismissedAction';
```

**Comment by nd-02110114** [comment]
@empyrical 
Thank you for advice! I fixed.

**Comment by TheSavior** [comment]
We have two internal flow errors from this change:

```
Cannot call await with `DatePickerAndroid.open(...)` bound to `p` because property `action` is missing in `Promise` [1].
                                                   v-----------------------
  87|     const {action, year, month, day} = await DatePickerAndroid.open({
  88|       date: this._getDefaultStartDate(),
  89|       minDate: minDate,
  90|       maxDate: maximumDate,
  91|     });
      -----^
References:
  react-native/Libraries/Components/DatePickerAndroid/DatePickerAndroid.ios.js:35:33
  35|   async open(options: Options): Promise<DatePickerModuleOpen> {
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
```

It looks like it expects action as part of the resolved promise. Is that something native actually provides and the type should be including or does it seem like a bug in our callsites?

**Comment by nd-02110114** [comment]
I refer to these lines 
https://github.com/facebook/react-native/blob/0a39cda39a83313fa1628759b2735d58ffcc02ec/ReactAndroid/src/main/java/com/facebook/react/modules/datepicker/DatePickerDialogModule.java#L116-L120

**Comment by TheSavior** [comment]
@nd-02110114, was there a reason that you closed this PR? We hadn't gotten a chance to finish landing it but it was on our radar. I'd still like to land it. :-/

**Comment by nd-02110114** [comment]
@TheSavior 
I'm so sorry 🙇 Reopened!!

**Pull request closed without merging**
