### PR TITLE
[Windows build vol. 2] Work around max path length during source build of RN Android

### PR DESCRIPTION
**Pull request by rectified95**
## Summary

Building ReactAndroid from source on Windows has recently hit the limitation of maximum path lengths.
At build time, during the `:ReactAndroid:buildReactNdkLib` task, the linker tries to access several of the intermediate binaries located deep in the tmp folder hierarchy, eg.
```
D:\r\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/react_render_components_progressbar/D_/r/ReactAndroid/__/ReactCommon/react/renderer/components/progressbar/android/react/renderer/components/progressbar/AndroidProgressBarMeasurementsManager.o
```
**Suggested fix:** for modules such as `react_render_components_progressbar` and `react_render_components_picker`, rename them to `rrc_progressbar` etc.

**NOTE**: this assumes that the fix from #30535 is in place. This regression happened while #30535 has been pending checkin.

**Other mitigations I've tried:** 
- setting [`LOCAL_SHORT_COMMANDS`](https://developer.android.com/ndk/guides/android_mk#local_short_commands) for the problematic modules or `APP_SHORT_COMMANDS` for the root project. Turns out those commands don't work on the NDK version RN requires, but even after manually applying a [patch ](https://android-review.googlesource.com/c/platform/ndk/+/1126440) to my local copy of the NDK, these flags had no effect.
- moving the repo directory higher in the file system tree, and using short directory names `D:\r\...` was not enough
- creating virtual drive letters for specific long paths with the [`sust`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst#examples) command is not workable, since they depend on the source folder structure, and get partly generated by the build system, which I can't plug into
- just enabling long path support on Windows is not enough, since the compiler toolchain doesn't support them.
## Changelog

[Android] [Fixed] - Fix source build on Windows machines vol. 2

## Test Plan

Run `.\gradlew installArchives`

Before:
image
Now:
image

### CODE REVIEW

**Review by mdvacca — COMMENTED** [review]
Thanks for working on this @rectified95 

Can you also help unifying naming to use "rrc_" instead of "react_render_components" everywhere? It can be done as part of another PR if that works better for you.

also, can you make sure to build and run RN Tester with Fabric enabled:

```
USE_FABRIC=1 ./gradlew :packages:rn-tester:android:app:installHermesDebug
```

Thanks

**Comment by rectified95** [comment]
@mdvacca Apart from the ones I'm touching, these names are similar, although they don't contain the full `react_render_components_`  prefix:
```
libreact_render_core
libreact_render_graphics/debug/imagemanager
libreact_render_mounting
react_render_componentregistry
libreact_render_scheduler/uimanager/attributestring/mapbuffer
```
What do you  think I should change them to? Would something like `librr_core, librr_mounting, libbuimanager` make sense?

As for running `./gradlew :packages:rn-tester:android:app:installHermesDebug` with the env. variable USE_FABRIC set, I'm getting an error, quite far in the build, after `:packages:rn-tester:android:app:mergeHermesDebugNativeLibs` - `com.android.builder.testing.api.DeviceException: No connected devices!`
I don't think anyone has ever built this code on Windows, and I'd need more time to investigate this error (may be as simple as running a simulator, but I don't have the capacity to do it right now.) 

Would you be ok with this PR going in as is so as to unblock the basic scenario of building without Fabric for now? 

(To reiterate, this PR strictly depends on #30535 being checked in first - I've resolved a merge conflict that appeared there since it was imported 2 weeks ago - can you also take a look?)

Thanks for helping out here!

**Comment by rectified95** [comment]
@mdvacca PR #30535 has been merged. Can you take another look at this one?

**Comment by mdvacca** [comment]
I'm importing to review and land

**Review by mdvacca — APPROVED** [review]

**Comment by rectified95** [comment]
@mdvacca Can I help move the check-in forward?

**Pull request closed without merging**
