### PR TITLE
chore(babel,flow): realign version bumps

### PR DESCRIPTION
**Pull request by kelset**
## Summary

While working on https://github.com/facebook/react-native/pull/35786 I noticed some inconsistencies in the versioning for Babel and Flow across the monorepo. So in this PR I wanted to address that so that for 0.72 we'll have the codebase in a more consistent shape.

Happy to split in multiple PRs if needed.

## Changelog

[GENERAL] [CHANGED] - Bump Babel packages to ^7.20.0 (or closest latest release), bump flow parser to 0.201 in a few places that were left out from latest bump

## Test Plan

CI is green.

### CODE REVIEW

**Comment by robhogan** [comment]
Thanks! This is one of those changes that'll need aligning across Meta projects to pass internal CI - the `@babel/runtime` is a big one - but I'll see if we can make it stick.

**Comment by kelset** [comment]
> Thanks! This is one of those changes that'll need aligning across Meta projects to pass internal CI - the `@babel/runtime` bump is a big one - but I'll see if we can make it stick.

yeah no worries, I'm happy to split in multiple PRs if needed (in particular the flow aligments and the babel bump in template)

**Review by cipolleschi — APPROVED** [review]

**Comment by kelset** [comment]
@robhogan just wanted to check in how's it going for this PR - as mentioned, I'm happy to split in multiples to get as much of this in as possible right away

**Comment by kelset** [comment]
@robhogan @cipolleschi I just gave another pass and a cleanup to this PR, is it worth keeping open or I should just close it?

**Comment by cipolleschi** [comment]
I don't know... maybe @robhogan has more info/ideas?

**Comment by robhogan** [comment]
Sorry for not getting back @kelset - this is a tricky one to land because it needs syncing with a bunch of other projects outside RN. I suggest we hold it until after @hoxyq's monorepo work (which I know is bumping/syncing a few of these deps anyway) and then tidy up what's left.

**Comment by hoxyq** [comment]
> Sorry for not getting back @kelset - this is a tricky one to land because it needs syncing with a bunch of other projects outside RN. I suggest we hold it until after @hoxyq's monorepo work (which I know is bumping/syncing a few of these deps anyway) and then tidy up what's left.

Monorepo changes also include bumping `yargs` outside of react-native, but not in `react-native-github/hermes-inspector-msggen`. I think we should return to this PR next week, if monorepo won't be landed by this time, we should at least merge this PR to have in 0.72 (as stated in summary)

**Comment by kelset** [comment]
works for me, let's keep this frozen until the monorepo PR is successfully landed 👍 thanks for the update folks

**Comment by kelset** [comment]
allright, branch rebased and updated! lmk what you want to do with it folks 🤗

**Comment by cipolleschi** [comment]
What's the actionable here, @robhogan @hoxyq? do we need to import and land this?

**Comment by kelset** [comment]
> @kelset Lorenzo Sciandra FTE Looks like we completely missed it, can you please resolve the conflicts and I will help with importing it this week?

I'm at chainreact - will take a look next week 🤗

**Pull request closed without merging**
