### PR TITLE
remove PushNotificationIOS following the issue Lean Core #23313

### PR DESCRIPTION
**Pull request by cromatikap**
## Summary

Remove the deprecated PushNotificationIOS and its references, following the issue Lean Core #23313

## Changelog

[iOS] [removed] - PushNotificationIOS removed

## Test Plan

PushNotificationIOS is deprecated. Use @react-native-community/push-notification-ios instead.

### CODE REVIEW

**Comment by gedeagas** [comment]
Nice.
As far as I know, PushNotificationIOS is used internally at FB, and finally, someone refactors it :D

**Comment by Simek** [comment]
> Nice.
> As far as I know, PushNotificationIOS is used internally at FB, and finally, someone refactors it :D

https://github.com/react-native-community/releases/issues/207#issuecomment-696365400

**Comment by gedeagas** [comment]
> > Nice.
> 
> > As far as I know, PushNotificationIOS is used internally at FB, and finally, someone refactors it :D
> 
> 
> 
> https://github.com/react-native-community/releases/issues/207#issuecomment-696365400

So it's still used internally then 😞

**Comment by Simek** [comment]
@bidetaggle You have missed import and handlers in `RNTester` app:
* https://github.com/facebook/react-native/blob/master/packages/rn-tester/RNTester/AppDelegate.mm#L228

**Pull request closed without merging**
