### PR TITLE
Accessing console logs

### PR DESCRIPTION
**Pull request by hramos**
Instructions for accessing the output of a `console.log`.

debugging

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @digeff to be a potential reviewer.

**Comment by javache** [comment]
@mkonicek has a task for this too to integrate this into run-ios, but it is also possible to view logs without running Xcode. See http://stackoverflow.com/questions/10165641/how-can-i-get-the-console-logs-from-the-ios-simulator.

Even simpler is to do "Debug > Open System Log..." from the Simulator menu when your app is running.

**Comment by hramos** [comment]
Good catch @javache, that makes it simpler to document. Updated, PTAL!

debugging

**Comment by JoelMarcey** [comment]
@hramos Looks like you need to rebase....

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1788207904745393/int_phab) to review.

**Comment by JoelMarcey** [comment]
@hramos Can you try rebasing again? I fear we may have to do an interactive rebase since we are getting patch apply failures internally. Check out the Phabricator link above.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1788207904745393/int_phab) to review.

**Pull request closed without merging**
