### PR TITLE
add previous tag for all docs and autodocs

### PR DESCRIPTION
**Pull request by hxx**
I found that the documents website had link code for previous document in layout file, but there is no previous tag in every document, so I add previous tag for all docs. :smiley:

### CODE REVIEW

**Comment by mkonicek** [comment]
Hey @hxx, what is "link code for previous document in layout file"?

What is the motivation for this PR? Have you seen the pull request template when submitting this PR?
https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md

Please add all the relevant info so we know what this PR does and demonstrate that it works. In case of changing the website you'll want screenshots too.

**Comment by hxx** [comment]
hi, @mkonicek 
I found these code blew:
https://github.com/facebook/react-native/blob/master/website%2Flayout%2FDocsLayout.js#L42-L45
https://github.com/facebook/react-native/blob/master/website%2Flayout%2FAutodocsLayout.js#L517-L518

before add previous metadata, these is no "Prev" link on document page:
qq20160311-1 2x

after add previous metadata, there will show the "Prev" link like this:
qq20160311-2 2x

The GH revision is 0.22 and master.

**Comment by mkonicek** [comment]
Thanks for the explanation @hxx!

Is there any way to do this without having to ask people to maintain the `previous` entry in each document? This adds quite a bit of work for people maintaining the docs and introduces potential for errors. Can the link to the previous page be inferred automatically since we already know what the order of pages is based on the `next` entries?

**Comment by hxx** [comment]
@mkonicek sorry, I didn't find a good way to know the previous entry when render a document.

I think that we render a document from the layout only can get the information from metadata of this document and people should maintain the `previous` metadata just like the `next` metadata.

**Comment by mkonicek** [comment]
> people should maintain the previous metadata just like the next metadata.

This is too much to ask from people, it's not going to work long term and it's going to lead to bugs when people make a mistake.

I suggest we try to find a way to do this without the need to the previous link or close this PR.

**Comment by satya164** [comment]
I don't know how we generate the docs, but since every page has an id and a next prop, we could easily generate the previous page link, for example, we could parse the metadata into an array, and easily extract the previous and next pages,

**Comment by hxx** [comment]
@mkonicek All right, it is too much work to maintain these metadata, I will give you another PR if I find a good way to get previous link from the `next` metadata. Thanks for your advise. :smile:

**Pull request closed without merging**
