### PR TITLE
Added docs for UITableView vs. <ListView>

### PR DESCRIPTION
**Pull request by paramaggarwal**
When I started out with React Native, I instinctively looked around for a `UITableView` component so I could display stuff in a list. But now I understand that React will never get `UITableView` or `UICollectionView` for reasons mentioned by @vjeux here as a comment on a particular issue: https://github.com/facebook/react-native/issues/499#issuecomment-87821298

I feel that it accurately explains the reason, and should be surfaced up to the docs. Hence adding it here.

### CODE REVIEW

**Comment by brentvatne** [comment]
@paramaggarwal - can you wrap lines at 80 characters?

**Comment by spicyj** [comment]
I don't know that it's true that React Native will _never_ have a UITableView wrapper. I think it's certainly possible to build one but it's nontrivial due to the reasons listed.

**Comment by vjeux** [comment]
What @spicyj said. Also, we are not satisfied with the current ListView implementation as it grows memory linearly and never reclaims it. What we have right now is a first shot but expect it to change down the road

**Comment by brentvatne** [comment]
@paramaggarwal - given the above comments perhaps you could turn your docs into a blog post about why there is *currently* not a `UITableView` wrapper in react-native :smile:

**Comment by paramaggarwal** [comment]
The contents of my entire PR are basically what @vjeux has said over at https://github.com/facebook/react-native/issues/499#issuecomment-87821298. It explains why we _currently_ don't have a `UITableView` wrapper. This is a common question from people I believe.

**Comment by pie6k** [comment]
@sophiebits do you think the situation has changed in any way now?

I've seen your post: https://reactnative.dev/blog/2018/06/14/state-of-react-native-2018

> Today, it's not possible to incorporate native navigation and gesture handling or native components like UICollectionView and RecyclerView without complex hacks. After our changes to the threading model, building features like this will be straightforward.

The feature I miss the most comparing `UICollectionView` to current RN list views is native drag-and-drop sorting.

`State of React Native 2018` seems a bit outdated, so I wonder if there is anything on the horizon.

Thanks!

**Pull request closed without merging**
