### PR TITLE
Add Reach24 App to React Native showcase

### PR DESCRIPTION
**Pull request by prabakarviji**
Submitting PR for adding Reach24 App to React Native showcase

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by dsibiski** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1023419794414455/int_phab) to review.

**Comment by prabakarviji** [comment]
@dsibiski Why it is failed? Is there any issue with our-side and how to handle this?

**Comment by facebook-github-bot-7** [comment]
@prabakarviji updated the pull request.

**Comment by mkonicek** [comment]
Got stuck due to unrelated failures, retrying.

**Pull request closed without merging**
