### PR TITLE
Make a note of ?dev=false flag in app template

### PR DESCRIPTION
**Pull request by glenjamin**
Not the greatest docs I've ever written, but this should help tie the pieces together a bit more easily for now.

### CODE REVIEW

**Comment by frantic** [comment]
There is also `minify=true`, I'm going to add them to the docs in #240

**Comment by glenjamin** [comment]
@frantic - oh cool, does that do the __DEV__ branch elimination too?

**Comment by frantic** [comment]
@glenjamin no, but there is a task open to look into it.

**Comment by frantic** [comment]
http://facebook.github.io/react-native/docs/runningondevice.html

**Pull request closed without merging**
