### PR TITLE
adding importantForAccessibility for Text, Button, ImageBackground

### PR DESCRIPTION
**Pull request by fabriziobertoglio1987**
## Summary

Previously published by [grgr-dkrk][2] as [#31296][3], fixes the following issues:

1) ImportantForAccessibility="no" does not work on Text, Button
2) ImportantForAccessibility="no-hide-descendants" does not work on Text, Button, or ImageBackground.

Note: On ImageBackground, focus is prevented on the imageBackground node itself, but focus is not prevented on its descendants.

Note: [Button component expected behavior for prop importantForAccessibility][4]
>Some components like Button seem like atomic units, but they end up rendering a hierarchy of components for example a wrapper View with a Text inside them. Allowing those descendants to become focusable, breaks the model of these being a single component to consider and forcing no-hide-descendants makes sense here.

>The other option is always to render any descendants of these elements with importantForAccessibility="no", so they can never be focusable on their own. This would have the same result, **BUT may potentially cause issues when the descendant content is supposed to automatically get moved up to the focusable ancestor to act as a label** (which is what Talkback does with unfocusable text elements by default).

Note: [importantForAccessibility="no" does not allow screenreader focus on nested Text Components with accessibilityRole="link" or inline Images][5]

fixes https://github.com/facebook/react-native/issues/30850 related https://github.com/facebook/react-native/pull/33690

## Changelog

[Android] [Fixed] - adding importantForAccessibility for Text, Button, ImageBackground

## Test Plan

1) testing ImageBackground importantForAccessiblity ([link to test][1])
2) importantForAccessibility="no" does not allow screenreader focus on nested Text Components with accessibilityRole="link" or inline Images ([link to test][5])
3) testing ImageBackground importantForAccessiblity ([link to test][6])
4) Button with importantForAccessibility=no ([link to test][7])

[1]: https://github.com/facebook/react-native/pull/31296#issuecomment-1192341626 ""
[2]: https://github.com/grgr-dkrk "grgr-dkrk"
[3]: https://github.com/facebook/react-native/pull/31296 "#31296"
[4]: https://github.com/facebook/react-native/pull/31296#discussion_r616184584 "expected behaviour with prop importantForAccessibility in Button component"
[5]: https://github.com/facebook/react-native/issues/30850#issuecomment-1192286477 "importantForAccessibility=no does not allow screenreader focus on nested Text Components with accessibilityRole=link or inline Images"
[6]: https://github.com/facebook/react-native/pull/34245#issuecomment-1192446124 "testing ImageBackground importantForAccessiblity"
[7]: https://github.com/facebook/react-native/pull/34245#issuecomment-1192443589 "Button with importantForAccessibility=no"

### CODE REVIEW

**Comment by fabriziobertoglio1987** [comment]
- [ ] further test Text component and nested Text scenarios
- [ ] add more AccessibilityExamples in rn-tester app
- [ ] add more jest test cases

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Button with importantForAccessibility=no</summary>
<p>

<video src="https://user-images.githubusercontent.com/24992535/180423864-1685d4ca-f63e-4c83-9aa0-606dd61d6706.mp4" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>testing ImageBackground importantForAccessiblity</summary>
<p>

https://github.com/facebook/react-native/pull/34245/commits/365b3d3df28ebc8f3e798851224e7819c088f10c

<video src="https://user-images.githubusercontent.com/24992535/180402100-d73cacc0-a042-484f-a617-d894a464430f.mp4" width="1000" />

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
- [ ] documentation update https://reactnative.dev/docs/next/accessibility#importantforaccessibility-android

**Comment by fabriziobertoglio1987** [comment]
@dmitryrykun Thanks for importing the pull request. Could you share the warning message that makes the PR fail internally? 🙏

**Comment by lunaleaps** [comment]
Ah I think it's the incorrect license for ImageBackground-test.js -- we can fix that internally

**Pull request closed without merging**
