### PR TITLE
Support show a progress indicator for Image while loading from URL (both Android and iOS)

### PR DESCRIPTION
**Pull request by quangcm**
Added some more props for Image component (includes `Image.ios.js` and `Image.android.js`) to show a progress indicator while loading image from URL

- `showLoadingIndicator` - by default, nothing changes if this flag is not used.
- `loadingIndicatorSize` - supports `small` and `large` (similar to `UIActivityIndicatorViewStyleWhite` and `UIActivityIndicatorViewStyleWhiteLarge` of iOS).
- `loadingIndicatorColor` - allows change to any color
- `failureImageSource` - if image loading is failed, then a static local image will be displayed

```javascript
<Image style = {styles.image}
                  source = {{ uri: image_url }}
                  showLoadingIndicator = {true}
                  loadingIndicatorSize = 'large' 
                  loadingIndicatorColor = 'blue'
                  failureImageSource = {require('./noimage.png')}
                  resizeMethod = 'resize'
                  resizeMode = 'cover' />
```

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
Looks like you didn't add your new files to the tvOS target in RCTImage Xcode project.... tvOS tests seem to be failing compilation.

**Comment by ide** [comment]
I think this should live in JS and be a separate component that contains and image. What if you want to customize the loading indicator? We expose primitives like onLoad and onError so that you can add features like this without making changes to core.

**Comment by quangcm** [comment]
@dlowder-salesforce 
Thank you for your reviewing, I already fixed RCTImage project for tvOS target.

@ide 
I think this feature could help developers very much, the effort to handle the task of downloading an URL image will decrease significantly.
I provided a standard loading indicator (similar to native iOS and native Android), of course you can customise the color and size. If someone wants to customise more, he/she can find another way, but I think the standard way is enough for most of application developers.

**Comment by DarkHollow** [comment]
@quangcm I'm with you, this would help me a lot. I have spent a few days trying something like this with onLoad and onError and the app turns out to be poor in performance, I don't know the way to do it well at the moment.

**Comment by salanki** [comment]
https://github.com/oblador/react-native-image-progress Is a popular library to do this today.

**Comment by DarkHollow** [comment]
@salanki but that library does not have the `failureImageSource` or `defaultSource` for Android, does it?
This feature on other hand has that and the progress indicator.

If this does not end up being merged into master I would like it to be at least an external library like oblador's React Native Image Progess.

**Comment by salanki** [comment]
@DarkHollow: My post was primarily for reference, not saying it replaces the need for this PR. `defaultSource` on Android as you say would be a nice addition but isn't covered by this PR right?

As @ide mentions the advantage of doing the progress indicator in JS like obladors lib is that you can customize it any way you want. The disadvantage might be performance. I only develop against modern target devices and have not had any issues with his approach, but there might be cases I don't see. Having a progress indicator out of the box in RN would be nice, but it would be good if the style could be customized.

**Comment by DarkHollow** [comment]
@salanki I have see `failureImageSource` and I have guessed it is for Android too. If it isn't, sorry. And now I understand the advantage of doing it in JS. Thank you.

**Comment by hramos** [comment]
@quangcm have you signed the CLA yet?

**Comment by quangcm** [comment]
@hramos yes, I already signed CLA, but I don't know why it isn't shown beside the title of my PR

**Comment by mkonicek** [comment]
I agree with @ide. This adds a lot of code to be maintained indefinitely while not many people might use the feature.

I think building this as a component that renders an `Image` and the loading indicator on top of it and releasing it to npm is the right way to go. That way anyone who needs the loading indicator can still use your code.

Hope you'll understand and thanks for building this - hope you'll continue contributing.

**Comment by quangcm** [comment]
@mkonicek 
I see the major reason to deny this PR is "making changes to core" or "adds a lot of code", it's not persuasive.
The reason which made me decide to change core is: I found the `loadingIndicatorSource` property in `Image.android.js` but it's not useful (load a static image then automatically rotate it, what a weirdo behaviour of loading indicator). I think the author wanted to support a standard `loadingIndicator` of `Image` from core, but maybe he didn't have enough effort to improve.
If we found something to improve the core, I think we should do. Is that the way every system to become better, isn't it?
Another reason, personally, I always prefer a standard way instead of using external library.

**Comment by nihgwu** [comment]
IMO, it's not a **lot of code** change

**Comment by DarkHollow** [comment]
Very sad that this pull request is closed...

@quangcm if you make a library of this, could you let us know here?
Thank you for your work.

**Comment by salanki** [comment]
Out of curiosity, what have your issues been when doing this in JS (like in the libraries linked earlier) that motivates a native implementation?

**Comment by quangcm** [comment]
@salanki 

I have no issue when doing this in JS. But my mention is not about having issue :)

@DarkHollow seems to have issue of performance. I think the reason is: when doing in JS, people often uses nested layout (with many wrap `View` components), that is not good for performance.

**Pull request closed without merging**
