### PR TITLE
Remove exported constants from RCTTimers to allow lazy initialization

### PR DESCRIPTION
**Pull request by janicduplessis**
As per @javache comments in #8734.

Also removes now useless feature detection check.

**Test plan**
Tested that rIC still works in UIExplorer example.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @javache and @yungsters to be potential reviewers.

**Comment by janicduplessis** [comment]
cc @ide @javache

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/549882385218325/int_phab) to review internal test results.

**Pull request closed without merging**
