### PR TITLE
fix: webview.postMessage throws not a constructor in WebView in Android 4.1 ~ 4.3

### PR DESCRIPTION
**Pull request by pinqy520**
`new MessageEvent` not support for Android 4.1 ~ 4.3 WebView.

change

``` javascript
document.dispatchEvent(new MessageEvent('message', data)))
```

to

``` javascript 
(function () {
  var event;
  var data = {};
  try {
    event = new MessageEvent('message', data);
  } catch (e) {
    event = document.createEvent('MessageEvent');
    event.initMessageEvent('message', true, true, data.data, data.origin, data.lastEventId, data.source);
  }
  document.dispatchEvent(event);
})()
```

### CODE REVIEW

**Comment by peichao01** [comment]
i meet this problem too
I never thought the react-native team never test Android4.1-4.3 😭😭
After very long time debug of many uncorrelated BUG representation and error shown,
i found this is the root problem.

**Comment by jacobp100** [comment]
@satya164 Could this be merged in? Thanks!

**Comment by pinqy520** [comment]
@satya164 Could this be merged in? Thanks!

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by pinqy520** [comment]
@satya164 Nothing happens, what should i do next?

**Comment by jacobp100** [comment]
It'll be in a release, so keep an eye on it. If there are problems, this will get reopened

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by pinqy520** [comment]
@jacobp100 ok, thanks ^_^

**Comment by pinqy520** [comment]
@satya164 This PR is still open..., is there any problem?

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
