### PR TITLE
ActionSheetIOS - support share sheet on modals

### LINKED ISSUE #6913: ActionSheetIOS.showShareActionSheetWithOptions not show on Modal
Pic1 is normal View and ActionSheetIOS work fine.

Pic2 is Modal, ActionSheetIOS cannot show.

## pic1
img_0023

## pic2
img_0022

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #6913 - follow up to this commit https://github.com/facebook/react-native/commit/43dcdaffe2caa8a6a8a38932a3e97ccb172bbc13 to support this in the 2nd method as well.

Test plan:
Open share sheet from modal

CC: @christopherdro as originally involved in the issue

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @dajomu to be potential reviewers.

**Comment by janicduplessis** [comment]
Maybe we should move that logic to `RCTKeyWindow` and add a property like `presentedViewController` or `topViewController` and replace the places where we do this.

**Comment by grabbou** [comment]
@janicduplessis that's true. I like the idea of another helper, but changing `RCTKeyWindow` might be a bit risky. I think we could name it `RCTPresentingController`?

**Comment by janicduplessis** [comment]
Yes that's what I was thinking, what about `RCTPresentedViewController`?

**Comment by grabbou** [comment]
Both are actually good candidates I think, just wanted to align with the way `iOS` names the `presentingController`, but 2nd one also works well :)

**Comment by janicduplessis** [comment]
I thought it was named presentedViewController in iOS, whatever the iOS name is is good :)

**Comment by grabbou** [comment]
You are actually right! So that part is solved 🎯

**Comment by facebook-github-bot-1** [comment]
@grabbou updated the pull request.

**Comment by grabbou** [comment]
@janicduplessis is there anything more you want me to add here? I don't think rebase is needed for the Circle to go green as the Travis build works just fine.

**Comment by janicduplessis** [comment]
LGTM

@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1222635404425052/int_phab) to review.

**Pull request closed without merging**
