### PR TITLE
fix bug in controlled selection #41966

### PR DESCRIPTION
**Pull request by jcubic**
## Summary:

This fixes bug #41966 in changing selection via controlled selection of the TextInput when using children (when prop.value is not used). 

## Changelog:

[ANDROID] [FIXED] - fix changing controlled selection of TextInput when using children

## Test Plan:

Peek 2023-12-18 21-18

This is the [repo of the bug](https://github.com/jcubic/react-native-text-input.git), it's fixed after the change. If unit tests are required I would need a hit on how to write them.

### CODE REVIEW

**Comment by jcubic** [comment]
IT seems that flow typechecker doesn't understand that `props.value` is a string:

```javascript
    const nativeUpdate: {text?: string, selection?: Selection} = {};
    const haveValue = typeof props.value === 'string';

    if (lastNativeText !== props.value && haveValue) {
        nativeUpdate.text = props.value;
    
```

got error:

> Cannot assign `props.value` to `nativeUpdate.text` because null or undefined [1] is incompatible with string [2].

But this is a string, there is a check.

**Comment by NickGerleman** [comment]
Should we just assign text on L1153 to null if value isn't present? I think the only place previously relying on empty string was here.

**Comment by jcubic** [comment]
Yes, that will work, let me change that.

**Comment by jcubic** [comment]
I'm not sure.

**Comment by jcubic** [comment]
I can change that code to null but I'm not sure if it will not break anything.

Is there any unit test that will make it safe? I can also add a new one. But I'm not sure where are the tests.

**Comment by jcubic** [comment]
Aweseome.

**Comment by smfunder** [comment]
It does work for me on iOS with RN 0.76.1. I will patch RN.

**Comment by jcubic** [comment]
@smfunder great news, I need to check my demo project after upgrade.

But note that my fix was not merged and the issue was closed.

**Comment by smfunder** [comment]
@jcubic thank you for the fix. Yes, I applied to the RN 0.76.1 code and created a patch file using patch-package. Now I'm able to make the selection correctly by code.

**Comment by jcubic** [comment]
@smfunder I misunderstood, I thought it was working without my PR.

**Pull request closed without merging**
