### PR TITLE
fix es6 class method

### PR DESCRIPTION
**Pull request by sunnylqm**

### CODE REVIEW

**Comment by knowbody** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by knowbody** [comment]
Thanks. I think I don't have the access
-- 
Best,
Matt

**Comment by satya164** [comment]
@knowbody Nah, the bot is acting weird for past few days.

**Comment by bestander** [comment]
merged

**Pull request closed without merging**
