### PR TITLE
[WebSocket] Add support for sending binary data (ArrayBuffer)

### PR DESCRIPTION
**Pull request by dewe**
Adding WebSocket support for sending ArrayBuffer. This was previously not implemented, just printing a warning to console.

Support for receiving ArrayBuffers was implemented in #4483.

**Test plan**
 Code was tested with [Paho MQTT Client](https://www.eclipse.org/paho/clients/js/) that requires support for sending ArrayBuffers. 

This test code roundtrips an MQTT message over websockets and writes to console:
```javascript
// Download from http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.javascript.git/plain/src/mqttws31.js
import './mqttws31'; 

window.localStorage = {
    _data       : {},
    setItem     : function(id, val) { return this._data[id] = String(val); },
    getItem     : function(id) { return this._data.hasOwnProperty(id) ? this._data[id] : undefined; },
    removeItem  : function(id) { return delete this._data[id]; },
    clear       : function() { return this._data = {}; }
  };

var client = new Paho.MQTT.Client('broker.mqttdashboard.com', 8000, 'rn-client');

client.onConnectionLost = onConnectionLost;
client.onMessageArrived = onMessageArrived;

client.connect({
  onSuccess: onConnect,
  onFailure: onFail
});

function onConnect() {
  console.log("Sending message...");
  var message = new Paho.MQTT.Message('MQTT over websockets, ' + new Date().toISOString());
  message.destinationName = 'test/websockets';
  client.subscribe('test/websockets');
  client.send(message);
}

function onMessageArrived(msg) {
  console.log(`Received from '${msg.destinationName}': ${msg.payloadString}`);
}

function onConnectionLost(r) {
  console.log('Connection lost: ' + r.errorMessage);
}

function onFail(e) {
  console.log('Failed connect', e);
}
```

CLA has been signed.

### CODE REVIEW

**Comment by mckn** [comment]
Awesome! I really need this feature as well :+1:

**Comment by sreesharp** [comment]
This is great! @dewe Are you planning to submit the Android fix as well?  If not, I can submit that as another PR.

**Comment by dewe** [comment]
Go ahead @sreesharp. I wasn't aware this was a problem on Android as well.

**Comment by jeremyong** [comment]
Just FYI, I took the liberty to resubmit this as #6327 and fixed the conflicts and all that so it is available as a single clean commit (I also squashed your existing commits). Authorship was not changed.

**Comment by dewe** [comment]
Closing this in favour of #6327

**Pull request closed without merging**
