### PR TITLE
[ResolutionRequest] Fix 'isRelativeImport' to allow require('.') and require('..')

### PR DESCRIPTION
**Pull request by aleclarson**
@davidaurelio 👍

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @davidaurelio to be a potential reviewer.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3898703) to review internal test results.

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3898703).

**Pull request closed without merging**
