### PR TITLE
fix gradle wrapper issue

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
Just change gradle.properties version number to change gradle version is not the right way. Because sometimes the gradlew and gradlew.bat or even the jar need to be updated too.
I also add the wrapper task to `build.gradle`, so next time, we just need to change the version number and execute `gradlew wrapper`.
## Test Plan
pass all current ci.
## Related PRs
none
## Release Notes
 [GENERAL] [BUGFIX] [Android] - fix gradle wrapper issue

### CODE REVIEW

**Comment by gengjiawen** [comment]
@hramos @janicduplessis

**Comment by gengjiawen** [comment]
@hramos Can you review this pr, thanks.

**Comment by hramos** [comment]
@gengjiawen I saw your earlier ping, and I probably will not be able to merge this just yet. We have some internal tests that may need to be updated but I have some other higher priority tasks at this time, it looks like this can wait.

**Comment by gengjiawen** [comment]
I have sync the change to gradle 4.4.

**Comment by dulmandakh** [comment]
gradle 4.4 landed in master 😄 https://github.com/facebook/react-native/commit/33d20da41b814a2fb9ba02cbab8b61a819cad95b

**Comment by gengjiawen** [comment]
Yes, this pr is just based on your commit. This is more of a bugfix than a feature. I still want to this get merged soon.

**Pull request closed without merging**
