### PR TITLE
BugFix: Title should be from scene.route.title

### PR DESCRIPTION
**Pull request by SunnyGurnani**
Its a minor Bug fix for rendering Title in NavigationHeader

### CODE REVIEW

**Comment by SunnyGurnani** [comment]
I have signed the agreement. Feel free to let me know if any more is needed.

**Comment by javache** [comment]
None of the types in https://github.com/facebook/react-native/blob/229d6d2fd0eb1efdd5257303e2c25493730e0450/Libraries/NavigationExperimental/NavigationTypeDefinition.js really promise that any of these have a title property, not even as an optional property, so I don't think you can really claim this is wrong.

**Comment by SunnyGurnani** [comment]
I have added title in type definition. The existing implementation is looking for title in navigation state which never going to work. Since every route will have its own title.

**Comment by ericvicenti** [comment]
Yeah I agree this makes more sense- I'm not sure how it was supposed to work before.

I don't think title should be mandatory inside of `NavigationRoute` because people may decide to define their title differently, so I think this approach is the way to go.

@facebook-github-bot shipit

**Comment by ericvicenti** [comment]
Oh it looks like you need to rebase

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1066958613341465/int_phab) to review.

**Pull request closed without merging**
