### PR TITLE
[Bugfix] Within NavigatorIOS, navigator.replace doesn't update the navigation bar.

### PR DESCRIPTION
**Pull request by rocman**

### CODE REVIEW

**Comment by cancan101** [comment]
Duplicate of #3516?

**Comment by rocman** [comment]
@cancan101 oh yes, it is. I've just closed the other one.

**Comment by rocman** [comment]
about "this.state.updatingAllIndicesAtOrBeyond >= i" changing to "this.state.updatingAllIndicesAtOrBeyond <= i":
I've checked the context, updatingAllIndicesAtOrBeyond is meant to be the min index of those to be updated. So the comparing should be "<= i" either than ">= i"

**Comment by rocman** [comment]
CI_Test faild with "TEST_TYPE=e2e". What's this?

**Comment by ghamaide** [comment]
Any updates on this issue ?

**Comment by satya164** [comment]
cc @mkonicek

**Comment by rocman** [comment]
It seems that every pull request does not pass the ci test.

**Comment by rocman** [comment]
Can we just ignore the ci test, and review the code to decide whether it can be accepted?

**Comment by nicklockwood** [comment]
I'll need a bit more context on this. The PR is described as a bug fix, but seems to introduce new API in the form of the `skipUpdate` property? What is that for?

**Comment by nicklockwood** [comment]
(and yes, don't worry about the tests, they're broken on master right now)

**Comment by rocman** [comment]
@nicklockwood the update method is a convenient method to adjust the current route, and it implements this through the replace method. And the skipUpdate property is a helper property to tell the render method not to change the component.
I know these are not the essential for the bugfix. However, without a proper update method, the developer can only directly use the replace method to do the update things, and probably writes a buggly code, for example, forgetting passing in the current component property or the current passProps property when he/she writes replace({title: 'new title'}) to update the title. For this reason, I provide the convenient method together with the bugfix.

**Comment by facebook-github-bot-6** [comment]
@mrspeaker would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
@rocman Note that the Navigator is getting deprecated in favor of `NavigationExperimental`. Do you plan to rebase this PR or should we close it? Sorry for the churn.

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @janicduplessis as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by javache** [comment]
This pull request hasn't seen activity in a while. If you still want to merge this, please open a new pull request.

**Comment by xogeny** [comment]
If I understand it correctly, this issue is still not resolved (since I found myself here because I was having this issue).  So I don't quite understand...why was this closed?  Are we supposed to move to `NavigationExperimental` (as someone previous mentioned) and therefore this isn't worth fixing in `NavigatorIOS`?

**Comment by satya164** [comment]
@xogeny the PR was closed because it was inactive for almost a year.

**Comment by xogeny** [comment]
@satya164 Understood.  But as far as I can tell from the discussion, the PR was submitted but never reviewed.  So it isn't really an issue with the submitter but the maintainers. (?)  Given that the bug is still present, should I assume from this that there just isn't an interest in fixing it?  Or is there some change on the horizon that makes this all irrelevant.  I'm just trying to understand if this will ever be fixed.

**Comment by satya164** [comment]
@xogeny sometimes it takes long to start the review since the team is busy with other work. the PR needed to be rebased against master to be able to be merged, and @mkonicek asked the author to rebase the PR. it was closed because there was no response from the author for 4 months.

AFAIK Facebook doesn't use `NavigatiorIOS` internally, and it's usage is not encouraged in the docs either, so it's a low priority for them. It's upto the contributors to fix bugs and maybe help in reviewing PRs.

Besides it's going to be deprecated soon when React Navigation is released - https://github.com/facebook/react-native/wiki/Roadmap

**Comment by xogeny** [comment]
@satya164 Thanks.  That is exactly the kind of summary I was looking for.

Note: you say that the use of `NavigatorIOS` is "not encouraged in the docs" but the docs actually say: " If you are only targeting iOS and would like to stick to the native look and feel, check out NavigatorIOS." which is part of what through me off.  But since it is clear from your answer that `NavigatorIOS` is on its way out, I'll try `NavigationalExperimental` which, according to the docs, I "can't go wrong with".

Thanks again.

**Comment by satya164** [comment]
@xogeny I'd suggest to hold off using Navigation Experimental. We're working on React Navigation which will be released soon. It's much easier to use and has more features.

**Pull request closed without merging**
