### PR TITLE
Add section for troubleshooting. Closes #3622

### LINKED ISSUE #3622: [docs] add Troubleshooting entry for when devices can't connect to the packager server
This pops up occasionally. Two possible causes:

Android: You need to run `adb reverse tcp:8081 tcp:8081` to forward requests from the device to your computer. Works only on Android 5.0 and newer.
iOS: Ensure you are on the same WiFi network as your computer. If you're using a cell data plan, your phone can't access your computer's local IP address.

### PR DESCRIPTION
**Pull request by christopherdro**

### CODE REVIEW

**Comment by paramaggarwal** [comment]
You can put `adb reverse tcp:8081 tcp:8081` inside back ticks - ` to have it format as code.

**Comment by christopherdro** [comment]
@paramaggarwal Thanks for the suggestion!
Will clean up the commits shortly as well. Not sure what happened.

**Comment by ide** [comment]
Thanks @christopherdro! Once you squash the commits we'll merge this.

**Comment by christopherdro** [comment]
@ide: NP! Should be good to go now.

**Pull request merged**
