### PR TITLE
Add key action info to Android EventHandler events.

### PR DESCRIPTION
**Pull request by aamalric**
## Summary

Add event key action for Android EventHandler events, helps to know if the key event is a up (key release, value is 1) or down (key pressed, value is 0) action.

## Changelog

[ANDROID] [ADDED] - Add event key action to EventHandler events.

## Test Plan

No test added

### CODE REVIEW

**Comment by cpojer** [comment]
@aamalric Before I can merge this commit, would you mind signing the CLA at code.facebook.com/cla? It only takes one minute. Thank you!

**Comment by aamalric** [comment]
@cpojer Yes for sure we will soon sign the CLA

**Comment by dblachut-adb** [comment]
This results in double `onPress` on TV devices when pressing button on a remote. Was this intended? I am guessing to since the doc was not updated: https://facebook.github.io/react-native/docs/building-for-apple-tv ?

**Comment by aamalric** [comment]
@dblachut-adb Hi, yes now when you press one button on TV, you'll have 2 events **onPress** but with 2 differents events:
- one will be for the press (eventKeyAction = ACTION_DOWN = 0) 
- one will be for the release (eventKeyAction = ACTION_UP = 1).

You'll have to make the check on this event if you need to handle the press only.

**Comment by dblachut-adb** [comment]
IMHO this is not good as I would not normally expect to receive two events for single press in one handler. Correct me if I am wrong but in web environment there are two separated events for it. In non-tv RN `onPress` is fired one on single user touch and release, but you have an **option** to listen for touch down and up and others separately.

As this is a breaking change and a bit counterintuitive it would be great to provide separate callbacks or if this is really desired it should be documented.

Also - do you know how is this handled on AppleTV? Didn't this commit broke the compatibility between those two platforms? I have just started to wonder...

**Comment by aamalric** [comment]
On TV you have to use the **TVEventHandler** wich allows you to listen to events for **events** not specifically 'onPress' like you said. 
Take a look at https://facebook.github.io/react-native/docs/building-for-apple-tv
The TVEventHandler is enabled with a callback that will receive an event, then depending on this event parameters, it's up to you to call your own 'onPress' or 'onRelease' functions...
There's no existing mechanism of onPress/onRelease for TV inputs in RN for now as far as I know

**Comment by dblachut-adb** [comment]
Yes there is and it is specifically described in the link that you have provided. I am talking about `Touchable*` elements (Buttons) `onPress` property. Touchables can be focused using directional navigation and then after you press **OK** (select) on remove you will receive `onPress` callback.

> The `Touchable` mixin has code added to detect focus changes and use existing methods to style the components properly and initiate the proper actions when the view is selected using the TV remote, so `TouchableWithoutFeedback`, `TouchableHighlight`, `TouchableOpacity` and `TouchableNativeFeedback` will "just work". In particular:
> - onFocus will be executed when the touchable view goes into focus
> - onBlur will be executed when the touchable view goes out of focus
> - onPress will be executed when the touchable view is actually selected by pressing the "select" button on the TV remote.

You are talking about 'global' event handler, maybe that is where we don;t understand each other. Does your change affect only global event handler?

**Comment by aamalric** [comment]
My changes were originally made to detect a **press** from a **release** on TVEventHandler events.
We don't use Touchable on our TV version as we didn't like the way the spatial navigation was handled with a TV remote...
So I must admit that I didn't test the Touchable handlers behavior with my modifications.

**Comment by dblachut-adb** [comment]
I can see that somebody have already filed an issue for it: https://github.com/facebook/react-native/issues/25979

**Comment by hitaloramon** [comment]
I also have the same problem. Using the mouse works fine, but using a keyboard or box control onPress runs twice

**Comment by mtkopone** [comment]
This was a pretty major breaking change for us that we did not anticipate...

**Comment by dblachut-adb** [comment]
> This was a pretty major breaking change for us that we did not anticipate...

@mtkopone Are you sure that this change is the cause? As I have mentioned - it is not yet released under any version.

**Comment by hitaloramon** [comment]
Looking at the code, I think the problem is in this "OR" of print. It checks two button click actions when you press the button and when you release it.

I may be wrong, but I think the problem is because of this. I think I needed to check only 1 of the actions.

[https://i.imgur.com/kawDqJ1.png](url)

**Comment by dblachut-adb** [comment]
That was my first assumption as well, but this commit is not yet released to any RN version which means that you would have to:
- build react-native from sources
- have sources checked out to master branch or have this commit cherry picked

**Comment by freddieerg** [comment]
This thread is a year old and I still don't understand why onLongPress, onPress, onPressIn, onPressOut are handled as you would expect by touch but then onLongPress, onPressIn, onPressOut have no effect on a keypress, instead just firing onPress 3 times and expecting you to deal with it?

**Pull request closed without merging**
