### PR TITLE
Fix failing flow tests

### PR DESCRIPTION
**Pull request by grabbou**
Metro Bundler ships with `react_native_fb` flow annotations whereas our repo is set to ignore `react_native_oss` flow issues.

For now, a hot fix is to make our repo ignore both. 

Detailed discussion happens here: https://github.com/facebook/metro-bundler/commit/87cfc05ea67e19c367e24e644915b49024ce3f2a#commitcomment-24884835

Those changes have been applied to `0.50.0-rc.0` in order to make it green.

### CODE REVIEW

**Comment by grabbou** [comment]
@hramos this is the correct PR, previous one was from a wrong branch.

**Comment by grabbou** [comment]
I have updated this with other master fixes to demonstrate its green again! Will ship again once test finish. Looks like previous attempt was stuck.

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Comment by grabbou** [comment]
@hramos all the tests have passed (green) excluding Travis, but I haven't been playing around with it. Looks like something failed during the import process.

**Comment by grabbou** [comment]
Import most likely failed because of a conflict with internal Facebook commit. Rebased.

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Comment by hramos** [comment]
I'm working on unsticking this

**Comment by hramos** [comment]
Done!

**Pull request closed without merging**
