### PR TITLE
Fixing Issue #7526

### PR DESCRIPTION
**Pull request by RobRoseKnows**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

Fixing a bug detailed in Issue #7526 where Android app was crashing when using a binary number.

**Test plan:**
- Build & Run UIExplorer
- Build & Run UIExplorer with `const binaryNumber = 0b101010` inserted into UIExplorerApp.android.js
- Use `react-native init` to create a new blank project, then replace files in node_modules and insert `const binaryNumber = 0b101010` into index.android.js.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @skevy and @frantic to be potential reviewers.

**Comment by janicduplessis** [comment]
Thanks @RobRoseKnows, Can you just also bump the minor version number (1.x.0) in babel-preset/package.json and in react-native's package.json.

@bestander Do you need to update fb internal node_modules and publish to npm for this?

**Comment by facebook-github-bot-8** [comment]
@RobRoseKnows updated the pull request.

**Comment by bestander** [comment]
Yeah, I'll publish to npm and restart the tests then

**Comment by janicduplessis** [comment]
@bestander I'll let you merge this PR :)

**Comment by RobRoseKnows** [comment]
It looks like the TravisCI and CIrcleCI errors are a result of the new version not being published to NPM. Is there anything I have to do regarding that?

**Comment by bestander** [comment]
Yep, I'll do a publish, restart the test and then import this PR

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1738671376420292/int_phab) to review.

**Pull request closed without merging**
