### PR TITLE
[animation]  Add support for animating nested styles

### PR DESCRIPTION
**Pull request by mlanter**
This adds the ability to nest animated styles and is a follow up to #11030 .
 
**Test plan (required)**
Verify a component with a shadowOffset animation animates.

Example:
```
<Animated.View
  style={{
    shadowOffset: {
      width: 0,
      height: this._pressAnim.interpolate({
        inputRange: [0, 1],
        outputRange: [20, 5],
      }),
    },
  }}, 
/>

```

example

### CODE REVIEW

**Comment by mlanter** [comment]
@janicduplessis This is a follow up to #11030.  I didn't know how to add a validation that makes sure we don't use useNativeDriver with nested styles.  Do you have a place I could look?  

I tried with `useNativeDriver: true` and it does throw an error-

screen shot 2017-03-13 at 4 07 40 pm

**Comment by janicduplessis** [comment]
Thanks a lot, looks good to me. An animated unit test is currently failing because of this, could you check out why and fix it?

**Comment by janicduplessis** [comment]
👍 

@facebook-github-bot shipit

**Comment by mlanter** [comment]
Thanks @janicduplessis !

**Pull request closed without merging**
