### PR TITLE
Fix new-library to copy to current project

### PR DESCRIPTION
**Pull request by dozoisch**
- new-library was copying file inside the <project_root>/node_modules/react-native/Libraries instead of <project_root>/Libraries. This was due to the path.resolve that was being passed 2 full paths instead of a base path + relative path segment.

---

Before:

```js
console.log(libraryDest, dest, path.resolve(libraryDest, dest);

// <base-path>/Libraries/TestLib 
// <base-path>/node_modules/react-native/Libraries/TestLib/package.json 
// <base-path>/node_modules/react-native/Libraries/TestLib/package.json
```

After:

```js
console.log(libraryDest, dest, path.resolve(libraryDest, dest);

// <base-path>/Libraries/TestLib 
// ../TestLib/package.json 
// <base-path>/Libraries/TestLib/package.json
```

### CODE REVIEW

**Comment by dozoisch** [comment]
@grabbou Let me know if there is anything I can do to help get this merge :) Thanks!

**Comment by grabbou** [comment]
Thanks, just got back after holidays. I've scheduled branch update to see if tests are passing this time. 

I'll get back to reviewing it soon.

**Comment by dozoisch** [comment]
@grabbou awesome thanks!

**Comment by dozoisch** [comment]
@grabbou seems like tests that failed are not related, and I can't rerun the two envs that failed.

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by grabbou** [comment]
Yeah, I am experiencing same issues in my other PRs, but let's try landing that one! Thanks for the fix

**Pull request closed without merging**
