### PR TITLE
Fix tutorial hello world so it can run on recently generated project

### PR DESCRIPTION
**Pull request by fmatosqg**
The very first hello world example, right after creating a new project, is broken. It runs in react web simulator but not in the recently created project as the text below it suggests: 

> If you are feeling curious, you can play around with sample code directly in the web simulators. You can also paste it into your index.ios.js or index.android.js file to create a real app on your local machine.

### CODE REVIEW

**Comment by janicduplessis** [comment]
Thanks for the PR, could you explain why changing the name fixes the problem?

**Comment by mkonicek** [comment]
Where does the string "AwesomeProject" come from? What it the issue and how does this fix it?

In the tutorial we use "HelloWorldApp": http://facebook.github.io/react-native/docs/tutorial.html

**Comment by mkonicek** [comment]
I'll close this for now but please feel free to open a PR also with a Test Plan demonstrating how the code fixes the issue.

**Comment by fmatosqg** [comment]
It comes from the Android .java file, and probably from some equivalent iOS file as well.

The native tutorial project is called AwesomeProject, that's the moment it's decided what goes inside the Android file.

Note that the Fixed Dimensions is the only tutorial that would compile if copy pasted into .js files. But the Hello World is the only one that says you can copy/paste it into android.index.js, which will certainly generate an error.

If this PR proposal doesn't go forward I'd suggest adding instructions for changing .java/iOS equivalent.

@mkonicek please reopen PR, or suggest next steps for fix.

**Pull request closed without merging**
