### PR TITLE
Cherry-pick in 0.29: Specify width and height for Image(remote source)

### PR DESCRIPTION
**Pull request by JoelMarcey**
Summary: 

Better for doc examples

Original commit: https://github.com/facebook/react-native/commit/6b2a49e73e52bf40ab82f792e7748aa36847c17f

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @sunnylqm to be potential reviewers.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1010983489015237/int_phab) to review.

**Comment by JoelMarcey** [comment]
Ah -- we don't use the shipit bot for cherry-picks into non-`master` branches. You just do direct merges.

**Comment by JoelMarcey** [comment]
cc @grabbou

**Pull request merged**
