### PR TITLE
Use latest simulator by not specifying the OS version

### PR DESCRIPTION
**Pull request by jsierles**
Appetize asked for this so they can better support us, since they will usually have more simulators available for the latest versions.

### CODE REVIEW

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by jsierles** [comment]
What needs to happen for this to show up on the website? Appetize is asking.

**Comment by janicduplessis** [comment]
Since the website is versioned now it won't show up by default until 0.26 is released, it should show up if you choose the 'master' version of the docs though.

**Comment by jsierles** [comment]
I see - is there a way to make an exception?

**Comment by janicduplessis** [comment]
I think it is if we cherry pick the commit in the release branches.

cc @bestander

**Comment by bestander** [comment]
We can do this, sure.

**Comment by bestander** [comment]
cherry-picked, this is the build that will deploy the website https://circleci.com/gh/facebook/react-native/5682

**Comment by janicduplessis** [comment]
@bestander you should probably do it for 0.25-rc too since this won't be in until 0.26

**Comment by bestander** [comment]
Added link to the tracking issue

**Comment by jsierles** [comment]
Thanks!

**Comment by vjeux** [comment]
Would be nice to automate this process. Maybe a command

@facebook-github-bot ship-website-live

Or something

**Comment by bestander** [comment]
Maybe, although I think it is an exception when we want to release
something to current stable website.
Cherry-picking took me 2 minutes.

**Pull request closed without merging**
