### PR TITLE
Added: informational error message on getting Android drawable folder…

### PR DESCRIPTION
**Pull request by BrunoVillanova**
… suffix for asset

Better informational error message on getting Android drawable folder suffix error using the asset name scale.

## Motivation

I've got an not well described error when trying to bundle my React Native project package.

## Test Plan

You can test the React Native bundle command like this:

node node_modules/react-native/local-cli/cli.js bundle --platform android --dev false --reset-cache --entry-file index.android.js --bundle-output /project/android/app/build/intermediates/assets/release/index.android.bundle --assets-dest /project/android/app/build

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/react-native-website, and link to your PR here.)

### CODE REVIEW

**Comment by BrunoVillanova** [comment]
We use it on react native to generate bundle.

**Comment by cpojer** [comment]
Thank you for this PR. Sorry I haven't been involved earlier so couldn't see this. Do you mind rebasing this so I can land it? Thank you!

**Comment by BrunoVillanova** [comment]
> Thank you for this PR. Sorry I haven't been involved earlier so couldn't see this. Do you mind rebasing this so I can land it? Thank you!

Sure, I will.

**Comment by cpojer** [comment]
Could you run prettier on this file and update the PR?

**Pull request closed without merging**
