### PR TITLE
Fix bug when clearing text when securityTextEntry is true

### LINKED ISSUE #35668: TextInput clears text when secureTextEntry is true﻿
### Description

Hi, I am having an issue with my UITextField, When a secureTextEntry is true﻿ and I try to edit it, it keeps getting cleared. 
I understand that it works as intended by IOS, but I would like to keep password value when I try to edit.

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 30.74 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.2.0 - ~/reactnative/node_modules/.bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.0 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Snack, code example, screenshot, or link to a repository

After looking for a workaround, I was able to modify native code in node module using  [patch-package](https://www.npmjs.com/package/patch-package)

Here is the path i tried to edit code 
// node_modules/react-native/   
// Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m

Before

```swift
// node_modules/react-native/   
// Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m


- (BOOL)textField:(__unused UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string
{
  NSString *newText =
    [_backedTextInputView.textInputDelegate textInputShouldChangeText:string inRange:range];

  if (newText == nil) {
    return NO;
  }

  if ([newText isEqualToString:string]) {
    _textDidChangeIsComing = YES;
    return YES;
  }

  NSMutableAttributedString *attributedString = [_backedTextInputView.attributedText mutableCopy];
  [attributedString replaceCharactersInRange:range withString:newText];
  [_backedTextInputView setAttributedText:[attributedString copy]];

  // Setting selection to the end of the replaced text.
  UITextPosition *position =
    [_backedTextInputView positionFromPosition:_backedTextInputView.beginningOfDocument
                                        offset:(range.location + newText.length)];
  [_backedTextInputView setSelectedTextRange:[_backedTextInputView textRangeFromPosition:position toPosition:position]
                              notifyDelegate:YES];

  [self textFieldDidChange];

  return NO;
}
```

After
```swfit
// node_modules/react-native/   
// Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m


- (BOOL)textField:(__unused UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string
{
    //Setting the new text.
    NSString *updatedString = [textField.text stringByReplacingCharactersInRange:range withString:string];
    textField.text = updatedString;

    //Setting the cursor at the right place
    NSRange selectedRange = NSMakeRange(range.location + string.length, 0);
    UITextPosition* from = [textField positionFromPosition:textField.beginningOfDocument offset:selectedRange.location];
    UITextPosition* to = [textField positionFromPosition:from offset:selectedRange.length];
    textField.selectedTextRange = [textField textRangeFromPosition:from toPosition:to];

    //Sending an action
    [textField sendActionsForControlEvents:UIControlEventEditingChanged];

    return NO;
}
```

it solved the password reset problem. However As you can see, there is a major flaw in this code.

The variable called _backedTextInputView has disappeared, and modified code has applied to all textField, so consonants and vowels are separated when writing in Korean.

So, I wonder if there is a way to apply the after code written above only when secureTextEntry is true while maintaining the existing code.

p.s. I wonder if React-native team can generate the corresponding props. (e.g. textFiled.clearsOnBeginEditing.)

### PR DESCRIPTION
**Pull request by adnan-khan1122**
When a secureTextEntry is true and I try to edit it, it keeps getting cleared.

This PR solves this by patching function `shouldChangeCharactersInRange` adding a condition that checks `isSecureTextEntry` in `textfield` is true so overrides the behaviour of clearing the text, the change was done in the file `RCTBackedTextInputDelegateAdapter.mm`

This fixes #35668

## Summary:

**Motivation**:
When the `secureTextEntry` property is set to true on a `TextInput` component, users experience an issue where the text gets cleared each time they attempt to edit it. This behaviour is particularly problematic in cases where users need to modify their input, such as entering or correcting a password, leading to a frustrating user experience.

**Resolution**:
To address this, a condition was added in the `shouldChangeCharactersInRange` function within the `RCTBackedTextInputDelegateAdapter.mm` file. This condition checks whether `isSecureTextEntry` is enabled on the `UITextField`. If it is, the function now overrides the default behaviour, preventing the text from being cleared when users attempt to edit it. This ensures a smoother and more intuitive experience for users when dealing with secure text inputs.

## Changelog:

[iOS] [Fixed] - Resolved an issue where text would be cleared when editing a `TextInput` with `secureTextEntry` enabled. The shouldChangeCharactersInRange function was patched to prevent this behaviour.

## Test Plan:
- The first attached video demonstrates the issue where enabling secure entry causes the entered password to be cleared when attempting to retype it.
- The second video shows that the issue has been resolved, allowing continued typing after enabling secure entry.

https://github.com/user-attachments/assets/a34f1606-c68b-4449-a0c3-8aeaf1b61f4f

https://github.com/user-attachments/assets/23e4d54f-0fe4-4e1c-83cf-b688a84faa5b

### CODE REVIEW

**Comment by adnan-khan1122** [comment]
- The first attached video demonstrates the issue where enabling secure entry causes the entered password to be cleared when attempting to retype it.
- The second video shows that the issue has been resolved, allowing continued typing after enabling secure entry.

https://github.com/user-attachments/assets/f43df872-52b5-499a-8d6d-28dfa7147f47


https://github.com/user-attachments/assets/044c5b0d-19d1-4cbb-935a-0d58d886f96f

**Comment by adnan-khan1122** [comment]
Our patchwork solution remains compatible with the new React Native version 0.75.1, as the underlying issue still persists.

**Comment by AntoineDoubovetzky** [comment]
We shouldn't deviate from the iOS behaviour by default. If we want to add this behaviour, I think we should enable it through a prop.

But even then, I don't think we want to add and maintain a new prop to deviate from the default iOS behaviour.

**Comment by angvp** [comment]
> We shouldn't deviate from the iOS behaviour by default. If we want to add this behaviour, I think we should enable it through a prop.
> 
> But even then, I don't think we want to add and maintain a new prop to deviate from the default iOS behaviour.

With all due respect, the default iOS behaviour is bad, (and that's why you might see several issues / threads on internet talking about this) and probably maintaining a version that is safer is the way to go, users of apps also shouldn't feel the difference between one mobile or the other in these type of details, sorry but your reasoning doesn't make much sense to me.

**Comment by angvp** [comment]
@cortinico Hi there! Sorry to tag you unexpectedly, but since you added the "author needs feedback" tag on #46154, I was hoping you could help us get a review? We've been waiting for some time now, and your input would be greatly appreciated. Thanks so much!

**Review by cipolleschi — APPROVED** [review]
Changes looks good to me, thanks for fixing this issue.

**Comment by cipolleschi** [comment]
@angvp could you please rebase on top of main? I'd like to verify that everything builds in CI before importing this PR.

**Comment by angvp** [comment]
> @angvp could you please rebase on top of main? I'd like to verify that everything builds in CI before importing this PR.

For sure, I'm not the author but I'll ping him @adnan-khan1122 thanks for reviewing it again!

**Comment by adnan-khan1122** [comment]
@cipolleschi  Updated to top of main, thanks!

**Comment by angvp** [comment]
@cipolleschi First of all thank you for your effort!, sorry to bug you again but we would like to know when and if this will be merged? Thanks

**Comment by cipolleschi** [comment]
There have been some internal discussions about when to respect web behavior and when to respect native behavior.
An iOS users might be puzzled by this behavior that align more to web, and moving on with this change will hint that the app has been developed with React Native instead of being a native application.

We have not reach consensus on what to do yet, so we have to pause this for a bit, while we come to a resolution.

**Comment by melyux** [comment]
I don't think any user on iOS would be happy with the current behavior. Anything's better than the status quo, which is broken.

**Comment by angvp** [comment]
> There have been some internal discussions about when to respect web behavior and when to respect native behavior. An iOS users might be puzzled by this behavior that align more to web, and moving on with this change will hint that the app has been developed with React Native instead of being a native application.
> 
> We have not reach consensus on what to do yet, so we have to pause this for a bit, while we come to a resolution.

Makes sense, thanks for your response

**Comment by cipolleschi** [comment]
> I don't think any user on iOS would be happy with the current behavior. Anything's better than the status quo, which is broken.

It's not broken, it is how the platform works. If you try and setup a project with Apple technologies (Objective-C or Swift, UIKit or SwiftUI) you'll see that this is how the platform behaves.

**Comment by cipolleschi** [comment]
We would not go forward with this. In the past we worked hardly to remove all those React Native behaviors that were tells that the app was built with React Native. 

One of the goals of the framework is to appear as a much as Native as possible. Implementing this behavior would make every TextInput with a show/hide of a secret text behaving different than the platform and people would be able to tell that the app could have been built with React Native.

If this is an issue for your users, I suggest to create a custom component that implement this new behavior.

Thanks for the patience and the understanding.

**Pull request closed without merging**
