### PR TITLE
Remove deprecated PullToRefreshViewAndroid and onRefreshStart / endRefreshing

### PR DESCRIPTION
**Pull request by janicduplessis**
Removes the deprecated APIs that were replaced by `RefreshControl`. Those API have been deprecated for a while already so I think it's fine to remove them at this point. Also ported the `SwipeRefreshLayoutTestModule` test to use `RefreshControl` instead of `PullToRefreshViewAndroid`.

**Test plan (required)**

Made sure no references are left in the codebase to `PullToRefreshViewAndroid`, `onRefreshStart` and `endRefreshing`.
Tested that `ScrollView` examples in UIExplorer still work properly.
Check that the `SwipeRefreshLayoutTestModule` passes on CI.

### CODE REVIEW

**Comment by bestander** [comment]
@andreicoman11 @foghina  what do you think?

**Comment by foghina** [comment]
@bestander android part lgtm, we only have a couple of usages of `PullToRefreshViewAndroid` internally AFAICT, should be fairly easy to fix.

**Comment by facebook-github-bot-9** [comment]
@janicduplessis updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@janicduplessis updated the pull request.

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1728701027408958/int_phab) to review.

**Comment by foghina** [comment]
Ping @bestander

**Comment by bestander** [comment]
Being landed now, thanks @foghina

**Pull request closed without merging**
