### PR TITLE
feat(iOS): added support of line break mode prop for textInput component

### PR DESCRIPTION
**Pull request by shubhamguptadream11**
## Summary:

Solves this issue: https://github.com/facebook/react-native/issues/44107

## Changelog:

[IOS] [ADDED] - Line break mode for TextInput components

## Test Plan:

- Test it does not affect existing text components when set default(none) strategy.
- Tested all the modes: `'wordWrapping' | 'char' | 'clip' | 'head' | 'middle' | 'tail'`.
- Tested it wouldn't affect TextInput if not provided lineBreakMode.
- Written test case with these props.

### CODE REVIEW

**Comment by shubhamguptadream11** [comment]
@javache Can you please help here in fixing test cases.
I am getting this error: `Error: Unable to download artifact(s): Artifact not found for name: hermes-darwin-bin-Release`.
Not able to narrow down the exact cause. I did fixed all the test cases related test cases.

**Comment by okwasniewski** [comment]
Shouldn't this first go through the discussions and proposals repo (https://github.com/react-native-community/discussions-and-proposals)? 

Adding an iOS-only feature probably should be discussed first as we also need to keep Android in mind.

**Comment by shubhamguptadream11** [comment]
@okwasniewski This issue is coming only in iOS because of default value of one props(lineBreakMode) in paragraphStyles object. By changing lineBreakMode property this issue is getting resolved.
This issue is not coming on android as of now. So I didn't thought of implementing this in android.

**Comment by shubhamguptadream11** [comment]
Closing this PR. Raising it from another handler.

**Pull request closed without merging**
