### PR TITLE
[Text] allow wordWrapping on iOS and tvOS

### PR DESCRIPTION
**Pull request by JulienKode**
The goal of this pull request is to add wordWrapping on iOS and tvOS 

I have test it on iOS and tvOS like that: 

```
<Text ellipsizeMode="wordWrapping">
    {this.props.text}
</Text>
```

Word wrapping is available in [RCTConvert.m](https://github.com/facebook/react-native/blob/master/React/Base/RCTConvert.m#L276)

### CODE REVIEW

**Comment by hramos** [comment]
Can you add screenshots? Just want to make sure this works on iOS.

**Comment by JulienKode** [comment]
Hello,

This is some screenshot with and without wordWrapping:

WordWrapping

Default mode

**Comment by JulienKode** [comment]
Yes, let met show you a little example:

If we have this text: 
`let test = "Hello I am a test\nHello I am a test REACTNATIVEPOWER";`

With wordWrapping, you can see the last word was cut (this is the behavior of [NSLineBreakByWordWrapping](https://developer.apple.com/documentation/uikit/nslinebreakmode/nslinebreakbywordwrapping?language=objc)):
WordWrapping

With tail this is the bahavior: 
Tail


You can see the code of the component: 

```
<View style={styles.container}>
	<Text
		ellipsizeMode={"wordWrapping"}
		numberOfLines={2}
		style={styles.instructions}
	>
		{test}
	</Text>
</View>
```

**Comment by shergin** [comment]
Yes, `ellipsizeMode={'wordWrapping'}` is supported, but the problem here is that `wordWrapping` is not `ellipsizeMode` conceptually; it is something like `wrapMode`.
Initially conversion from `ellipsizeMode={'wordWrapping'}` to NSLineBreakByWordWrapping was not implemented intensionally, but lately someone add this.

So, we have to implement a new prop for this functionality.

**Comment by JulienKode** [comment]
Hello,

Thanks for your answer, how many wrapMode there are ?

**Comment by shergin** [comment]
I can imagine another values, but we can start from this.

**Pull request closed without merging**
