### PR TITLE
Change android assets names

### PR DESCRIPTION
**Pull request by vovanmozg**
## Motivation

https://github.com/facebook/react-native/issues/16263

## Test Plan

First run the android emulator

> git clone https://github.com/vovanmozg/react-native-test-android-assets-paths.git
> cd ./react-native-test-android-assets-paths
> yarn
> patch node_modules/react-native/local-cli/bundle/assetPathUtils.js android_filenames.patch
> cd android && ./gradlew assembleRelease

You should see image in the center of test app screen.

## Release Notes
[CLI] [BUGFIX] [./local-cli/bundle/assetPathUtils.js] - Change android assets names representation

### CODE REVIEW

**Comment by charpeni** [comment]
Something seems wrong with your PR.

Did you recently rebase your changes? You probably just need 67ba7d5937d643ca654cfed2712192ee8a41596c.

**Comment by vovanmozg** [comment]
@charpeni I rebased changes, please check it.

**Comment by janicduplessis** [comment]
Can we use a sha1 hash using node's crypto module instead to avoid the extra dep? That's what we use for hashes in metro-bundler https://github.com/facebook/metro-bundler/blob/b08ce130fdd8bd455ec2f0528a597ac986866de4/packages/metro-bundler/src/lib/TransformCaching.js#L139.

**Comment by vovanmozg** [comment]
@janicduplessis I think it might be used node's crypto module. Filenames must be unique and this looks suitable.

**Comment by vovanmozg** [comment]
@janicduplessis looks like I can't use crypto in this context.
```
Unable to resolve module `crypto` from `/Users/vovanmozg/pro/remove/react-native-test-android-assets-paths/node_modules/react-native/local-cli/bundle/assetPathUtils.js`: Module does not exist in the module map
```

**Comment by ponomarevv** [comment]
@janicduplessis 
> Can we use a sha1 hash using node's crypto module instead to avoid the extra dep?

Unfortunately, no. 
`getAndroidResourceIdentifier` is used in `react-native/Libraries/Image/AssetSourceResolver`, so that it runs inside mobile JSCore, not in node environment

Also, we can't use node.js core modules inside JSCore 'as is' without any mubo-jumbo-workarounds.
https://medium.com/@aakashns/using-core-node-js-modules-in-react-native-apps-64acd4d07140

There are many related issues here, but none of them are yet resolved in general.
https://github.com/facebook/react-native/issues/1871
https://github.com/facebook/react-native/issues/6253

So I see only three ways here (to resolve this issue, of course):

- fix related issues to use node.js core modules (a long way, but best of all)
For ex., https://github.com/facebook/react-native/issues/1871#issuecomment-235667345 is one workaround which looks not so bad as many others are

- use new external dependency in react-native

- copy-paste any sha1 / md5 / etc as inplace function / nearby import and maintain it (not so good as new external deps, but almost same way)

Last (and worse of all) way - leave it "as is". Deeply nested component structure sometimes adds PITA to bundle/deploy process.

Thoughts?

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :lock: package.json - <i>Changes were made to package.json. This will require a manual import by a Facebook employee.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cpojer** [comment]
This PR has been open for a long time without resolution. We just moved this code to https://github.com/react-native-community/react-native-cli so please submit your PR there.

**Pull request closed without merging**
