### PR TITLE
Fix crash when calling substring() on a string containing emoji.

### LINKED ISSUE #23459: [Android] [RN 58.3] Calling substring() on a String that contains an emoji causes "Error: Exception in HostFunction: basic_string::resize"
## 🐛 Bug Report
On Android (I couldn't test on iOS), with react-native 0.58.3, try to call substring(0,1) on a string that begins with an emoji.
You should get this error: [Error: Exception in HostFunction: basic_string::resize]
I guess this is linked to some bad conversion from UTF 16 to UTF 8.

This is not happening on 0.57.3 for instance (which I was using earlier for the same project) 

## Code Example
```
const text = '🙃blablabla'
try {
    const newText = text.substring(0, 1)
    Alert.alert(newText)
  } catch(e) {
    console.error(e)
}
```
## Environment
    React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 41.97 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 10.3, macOS 10.12, tvOS 10.2, watchOS 3.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.0, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 8.3.3/8E3004b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

### PR DESCRIPTION
**Pull request by ericlewis**
## Summary

Fixes #23459. It is not legal to write the character array of a std::string, and can result in undefined behavior.

## Changelog

[General] [Fixed] - Crash when substring intersects with emoji

## Test Plan

Updated RNTester `TextExample.ios.js & TextExample.android.js` with a section containing the below: 
```
<Text>{'test🙃'.substring(0, 5)}</Text>`
```
Also updated the test snapshot for iOS. So long as it doesn't crash tho, the test technically is passed.

### CODE REVIEW

**Comment by ericlewis** [comment]
seems as tho circle ci is pitching a fit..

**Comment by ericlewis** [comment]
@cpojer @hramos anything I need to do to get unstuck?

**Comment by hramos** [comment]
@ericlewis I followed up on the imported diff and it looks like David is seeking additional review from some fellow team members. No action needed on your part for now. Thanks for the PR!

**Comment by mdvacca** [comment]
@ericlewis the PR is approved, I tried to land this but got conflicts on the png.  can you rebase it? I will land it after. Thanks

**Comment by ericlewis** [comment]
@mdvacca done! (tho I seem to have messed up the history a bit 🤔)

**Comment by cpojer** [comment]
@ericlewis yeah it seems like the PR was messed up. Could you rebase on top of master and force push to your branch with only the changes you made?

**Comment by ericlewis** [comment]
@cpojer fixed!

**Comment by uncledent** [comment]
Hello everyone and thank you for your work. I can't figure it out, which version on RC has this fix inside?

**Pull request closed without merging**
