### PR TITLE
Support for scoped templates

### LINKED ISSUE #18973: Improve install of templates from places other than `npm` registry
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When trying to install a project template from other place than published as a `npm` package (github forks, local filesystem, local tarfile, http server...) I can't be able to do it due to several problems. Debuging them, I get to the conclussion the problem is at https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/local-cli/generator/templates.js#L112-L120, not processing the template name correctly. Problems I've found in this code snippet are:

- lack of support to download a git project subpath (seems a problem in `npm` not supporting mono-repos)
- `templateName` gets not cleaned, file extension should be removed
- `templateName` can't be different of the package name at the template `package.json` file, correct name should be extracted once the template is installed
- when installed from `npm`, `installPackage` is just a concatenation of the string `react-native-template-` and the provided template name, not allowing to use scoped packages as templates. Provided template should be checked and splitted, and the scoped prefixed to the generated `templateName`

## Environment
```
Environment:
  OS: Linux 4.13
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2
```
## Steps to Reproduce
Try to init a React Native project using a template from a git mono-repo, or from a local filesystem folder, or from a tarfile on the local filesystem or a web server, or from a scoped `npm` package.

## Expected Behavior
All the provided methods should be able to correctly install the provided template.

## Actual Behavior
All of them fails.

### PR DESCRIPTION
**Pull request by scally**
This is a rebase of #18974 in the hopes that it would get merged.

Add support for templates published as scoped packages. Partially fixes #18973.

Test Plan

Published a template as a scoped package and installed it.

Related PRs

Documentation says nothing regarding lack of support for scoped packages, so intuitively they should work. This pull-request just makes that intuitive assumption true, so I think no changes on documentation are needed.

Release Notes

[CLI] [BUGFIX] [local-cli/generator/templates.js] - Support for scoped npm packages as templates

### CODE REVIEW

**Comment by scally** [comment]
@RSNara I don't have a link at hand, as I tested with a private repo. You could publish the existing RN default template as a scoped package, or I could try to do the same soon.

**Comment by scally** [comment]
@RSNara I uploaded a public sample scoped template you can use to test with.

```
react-native init mycoolapp --template=@sampleorg123/sample
```

**Comment by scally** [comment]
@RSNara Could you please take a look at this & the provided example when you have a second? I don't want to see this PR get closed like the last one fixing this issue. :)

**Comment by scally** [comment]
@RSNara bump 😸

**Comment by scally** [comment]
@lucianomlima @TheSavior @hramos Mentioning some other folks that worked on this file in the hopes it can see some traction. @RSNara said above he wanted to land this ASAP, but I haven't heard from him in a month. Is there anyone else that could verify or sign off on this fix? I have provided a sample publicly scoped template to test with above:

```
react-native init mycoolapp --template=@sampleorg123/sample
```

**Comment by TheSavior** [comment]
cc @grabbou since this is CLI stuff

**Comment by cpojer** [comment]
Thank you for your PR. We just moved this code to https://github.com/react-native-community/react-native-cli so please submit your PR there.

**Comment by piranna** [comment]
Can someone tell me if there's some pull-request for this feature at `react-native-cli` repo?

**Comment by grabbou** [comment]
We haven't merged it and I feel really bad that we have waited with it for so long. Let's actually make sure this is working.

CC: @Esemesek since you are working on `init` right now.

**Pull request closed without merging**
