### PR TITLE
Do not publish src/**/__tests__ folder for react-native

### LINKED ISSUE #43242: Tests moved from Libraries to src/private are now being published in the NPM package
### Description

It looks like some part of the NPM publish process filters out the `__tests__` folders within `react-native/Libraries` from being published. It's not filtered in the `package.json` AFAIK, so maybe in some script?

Anyway, when moving files to `src/private` (particularly in `src/private/webapis/dom/oldstylecollections/` ) that filtering is no longer being applied, so those test files are now being published.

This probably isn't a problem for most, but downstream in `react-native-windows` this breaks our validation as flow checks fail for those files. We're trying to catch up so we can publish 0.74. We're hitting the issue here, integrating to `0.74.0-nightly-20240122-4e92f87df` in this PR: https://github.com/microsoft/react-native-windows/pull/12761

Example:
```
Error ------------------------------------ src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:139:39

Cannot get `collection[i]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:139:39
   139|         expect(value).toBe(collection[i]);
                                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]
```

### Steps to reproduce

1. Look at react-native NPM package >= 0.74.0-nightly-20240122-4e92f87df.
2. See that there are __tests__ folders that shouldn't be there

### React Native Version

0.74.0.rc.1

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.26063
  CPU: "(24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores     "
  Memory: 48.67 GB / 63.86 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.6.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 16.11.34601.136 (Visual Studio Enterprise 2019)
    - 17.9.34616.47 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:23:23

Cannot get `collection[0]` because property `0` is missing in `DOMRectList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:23:23
   23|     expect(collection[0]).toBe(domRectA);
                             ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:24:23

Cannot get `collection[1]` because property `1` is missing in `DOMRectList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:24:23
   24|     expect(collection[1]).toBe(domRectB);
                             ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:25:23

Cannot get `collection[2]` because property `2` is missing in `DOMRectList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:25:23
   25|     expect(collection[2]).toBe(domRectC);
                             ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:26:23

Cannot get `collection[3]` because property `3` is missing in `DOMRectList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:26:23
   26|     expect(collection[3]).toBe(undefined);
                             ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:33:16

Cannot assign `new DOMRectReadOnly()` to `collection[0]` because property `0` is missing in `DOMRectList` [1].
[prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:33:16
   33|     collection[0] = new DOMRectReadOnly();
                      ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:47:18

Cannot assign `new DOMRectReadOnly()` to `collection[0]` because property `0` is missing in `DOMRectList` [1].
[prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:47:18
   47|       collection[0] = new DOMRectReadOnly();
                        ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:49:23

Cannot get `collection[0]` because property `0` is missing in `DOMRectList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:49:23
   49|     expect(collection[0]).toBe(domRectA);
                             ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ---------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:70:37

Cannot get `collection[i]` because property `0` is missing in `DOMRectList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/DOMRectList-test.js:70:37
   70|       expect(value).toBe(collection[i]);
                                           ^

References:
   src/private/webapis/dom/oldstylecollections/DOMRectList.js:74:4
   74| ): DOMRectList {
          ^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:18:23

Cannot get `collection[0]` because property `0` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:18:23
   18|     expect(collection[0]).toBe('a');
                             ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:19:23

Cannot get `collection[1]` because property `1` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:19:23
   19|     expect(collection[1]).toBe('b');
                             ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:20:23

Cannot get `collection[2]` because property `2` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:20:23
   20|     expect(collection[2]).toBe('c');
                             ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:21:23

Cannot get `collection[3]` because property `3` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:21:23
   21|     expect(collection[3]).toBe(undefined);
                             ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:28:16

Cannot assign `'replacement'` to `collection[0]` because property `0` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:28:16
   28|     collection[0] = 'replacement';
                      ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:42:18

Cannot assign `'replacement'` to `collection[0]` because property `0` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:42:18
   42|       collection[0] = 'replacement';
                        ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:44:23

Cannot get `collection[0]` because property `0` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:44:23
   44|     expect(collection[0]).toBe('a');
                             ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:65:37

Cannot get `collection[i]` because property `0` is missing in `HTMLCollection` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/HTMLCollection-test.js:65:37
   65|       expect(value).toBe(collection[i]);
                                           ^

References:
   src/private/webapis/dom/oldstylecollections/HTMLCollection.js:80:4
   80| ): HTMLCollection<T> {
          ^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:18:23

Cannot get `collection[0]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:18:23
    18|     expect(collection[0]).toBe('a');
                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:19:23

Cannot get `collection[1]` because property `1` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:19:23
    19|     expect(collection[1]).toBe('b');
                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:20:23

Cannot get `collection[2]` because property `2` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:20:23
    20|     expect(collection[2]).toBe('c');
                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:21:23

Cannot get `collection[3]` because property `3` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:21:23
    21|     expect(collection[3]).toBe(undefined);
                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:37:16

Cannot assign `'replacement'` to `collection[0]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:37:16
    37|     collection[0] = 'replacement';
                       ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:51:18

Cannot assign `'replacement'` to `collection[0]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:51:18
    51|       collection[0] = 'replacement';
                         ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:53:23

Cannot get `collection[0]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:53:23
    53|     expect(collection[0]).toBe('a');
                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------- src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:74:37

Cannot get `collection[i]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:74:37
    74|       expect(value).toBe(collection[i]);
                                            ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------ src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:109:39

Cannot get `collection[i]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:109:39
   109|         expect(value).toBe(collection[i]);
                                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------ src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:127:46

Cannot get `collection[i]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:127:46
   127|         expect(entry).toEqual([i, collection[i]]);
                                                     ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------ src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:139:39

Cannot get `collection[i]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:139:39
   139|         expect(value).toBe(collection[i]);
                                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]


Error ------------------------------------ src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:153:39

Cannot get `collection[i]` because property `0` is missing in `NodeList` [1]. [prop-missing]

   src/private/webapis/dom/oldstylecollections/__tests__/NodeList-test.js:153:39
   153|         expect(value).toBe(collection[i]);
                                              ^

References:
   src/private/webapis/dom/oldstylecollections/NodeList.js:102:65
   102| export function createNodeList<T>(elements: $ReadOnlyArray<T>): NodeList<T> {
                                                                        ^^^^^^^^^^^ [1]
```

### Reproducer

https://github.com/microsoft/react-native-windows/pull/12761

### Screenshots and Videos

_No response_

### PR DESCRIPTION
**Pull request by cortinico**
## Summary:

We should not be publishing the `__tests__` folder to the npm package.
Fixes #43242

## Changelog:

[INTERNAL] [CHANGED] - Do not publish src/**/__tests__ for react-native

## Test Plan:

Nothing to test

### CODE REVIEW

**Comment by NickGerleman** [comment]
Probably should be grouped with the existing globs of files to pack (and ignore). https://github.com/facebook/react-native/blob/4d2262b8d2b38eddbdfb2264a33f87c28aa7712f/packages/react-native/package.json#L62

**Comment by jonthysell** [comment]
Yeah I'm curious, as the old folder `/packages/react-native/Libraries/DOM/OldStyleCollections/__tests__` wasn't published before (none of the `__tests__` folders under `Libraries\` are) yet I can't find an `.npmignore` nor a file ignore in `package.json` that explains it.

**Comment by cortinico** [comment]
> yet I can't find an `.npmignore` nor a file ignore in `package.json` that explains it.

@jonthysell it's this one:
https://github.com/facebook/react-native/blob/1df38129337168d2968f4172a10b23bb88ab4c95/packages/react-native/Libraries/.npmignore#L1

@NickGerleman I really dislike we do have a mixture of `.npmignore` and glob exclusions in the package.json. Let's merge this one and clean things up afterwards?

**Pull request closed without merging**
