### PR TITLE
Update OkHttp to 3.3.1

### PR DESCRIPTION
**Pull request by AndrewJack**
### Motivation
Fixes: #7743

- Android apps can recover from a `REFUSED_STREAM` in HTTP/2.
- A few other fixes mentioned in the [CHANGELOG.md](https://github.com/square/okhttp/blob/master/CHANGELOG.md)

### Test plan

- CircleCi
- Integrate into sample project ([Project](https://github.com/AndrewJack/react-native-test/tree/okhttp_3.3_7746))

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @bestander to be potential reviewers.

**Comment by bestander** [comment]
ping when it is ready

**Comment by AndrewJack** [comment]
@bestander I have tested with a sample app and all seems to be fine.

The tests are failing with BUCK, but pass in the IDE and with Gradle. 
I've tired changing a few BUCK config files but it doesn't seem to work. Do you have any idea?

**Comment by bestander** [comment]
The first exception is
```
FAILURE com.facebook.react.modules.network.NetworkingModuleTest testGetWithoutHeaders: 
java.lang.AssertionError
	at okhttp3.internal.AndroidPlatform.isCleartextTrafficPermitted(AndroidPlatform.java:143)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:73)
```

I wonder if it is something system specific

**Comment by facebook-github-bot-9** [comment]
@AndrewJack updated the pull request.

**Comment by AndrewJack** [comment]
I've updated this PR to [OkHttp 3.3.1](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-331). 

Still stumped on the BUCK unit test errors

Most of the failures have this error:
```
java.lang.NoClassDefFoundError: okhttp3.OkHttpClient
```

**Comment by bestander** [comment]
This is the error:
`okhttp3.internal.AndroidPlatform.isCleartextTrafficPermitted(AndroidPlatform.java:143)`
Could it be emulator based?
We could bump to another version other than 19.

**Comment by AndrewJack** [comment]
Relates to this issue: https://github.com/square/okhttp/issues/2533

**Comment by mkonicek** [comment]
Good find @AndrewJack. Should we wait for a fix in OkHttp?

**Comment by AndrewJack** [comment]
Upgraded Robolectric to fix the issue, but 3.1 doesn't currently work with power mock.

Waiting for 3.1.1...
https://github.com/robolectric/robolectric/issues/2429

**Comment by AndrewJack** [comment]
Closing this issue. #8672 fixes the issues experienced upgrading to 3.3.1

**Pull request closed without merging**
