### PR TITLE
fix: building dependencies for Android missing with pnpm

### PR DESCRIPTION
**Pull request by Hector-Chong**
## Summary:

This PR resolves building dependencies for Android missing if using `pnpm` as dependency manager.

When I saw the release of stable symlink, I couldn't help myself initializing the latest project template and install dependencies with `pnpm`. However, it's not working on Android, as the Gradle script could not find files in `node_modules`.

image

The reason for this is very simple. `pnpm` does not share the same `node_modules` structure with other dependency managers like `yarn` and `npm`. As you can see below, the structure is neater but significant dependencies `@react-native-community/cli-platform-android`  and `"@react-native/gradle-plugin"` are not present in the root of `node_modules`. This absence leads to a building issue. However, it's important to note that these dependencies are not missing; they are placed inside the .pnpm directory.

image

To resolve this issue, these dependencies should be specified in `package.json`, so that pnpm will put them in the root of `node_modules`.

## Changelog:

[Android] [Fixed] - changing `package.json` in template

## Test Plan:

Reinstall dependencies after modifying `packgae.json` with `pnpm`

### CODE REVIEW

**Comment by ryancat** [comment]
Thanks for the fix to the template! It seems the two plugins are listed in the [package.json file at root](https://github.com/facebook/react-native/blob/main/packages/react-native/package.json#L99-L104) with a higher version (13.0.0 and ^0.74.0). Is there a reason why your diff chose to use a lower version?

**Comment by Hector-Chong** [comment]
> Thanks for the fix to the template! It seems the two plugins are listed in the [package.json file at root](https://github.com/facebook/react-native/blob/main/packages/react-native/package.json#L99-L104) with a higher version (13.0.0 and ^0.74.0). Is there a reason why your diff chose to use a lower version?

Both versions in root package.json has not been published on NPM.

Should I change them to matche those in root package.json?

**Comment by NickGerleman** [comment]
If they are part of the root package.json, they might have previously been part of the react-native package before it was split out to `packages/react-native/package.json`.

@cortinico do you know what is resolving the gradle one?

**Comment by Hector-Chong** [comment]
> If they are part of the root package.json, they might have previously been part of the react-native package before it was split out to `packages/react-native/package.json`.
> 
> 
> 
> @cortinico do you know what is resolving the gradle one?

I don't quite understand what do u mean and what it would result in.

Would that cause certain dependencies in project not sync with those in react-native package?

**Comment by cortinico** [comment]
cc @robhogan as he's working on pnpm support for Android.
I think we should not merge this PR as you should not depend directly on `@react-native/gradle-plugin`. That dependency is provided by React Native instead.

**Comment by robhogan** [comment]
> I think we should not merge this PR as you should not depend directly on @react-native/gradle-plugin. 

Yeah, I agree with this.

@Hector-Chong correctly points a real problem here that user code shouldn't depend on transitive `node_modules` dependencies, and this breaks with valid `node_modules` layouts like pnpm's defaults. 

**But**, adding these dependencies to the user project brings its own problems - primarily that we would likely end up with multiple versions of `cli-platform-android` and `@react-native/gradle-plugin` installed (and multiple versions of dependencies doesn't play well with native, unlike JS - Gradle can't have more than one version of a plugin used in the same build, for example). Secondarily, it adds churn to upgrades and more complexity in userland. `peerDependencies` *could* work, but they're inconsistently implemented and it'd mean pushing even more complexity into user projects.

Instead, I think the best solution (at least as long as the template is part of `react-native`) is for the `react-native` package itself to wrap or re-export the necessary APIs, so that the template project only contains direct references to `react-native`. That's on me at the moment.

(CC @kraenhansen also, who's been working close to this problem)

**Comment by Hector-Chong** [comment]
Now I understand. Thanks for the elaboration.

**Pull request closed without merging**
