### PR TITLE
update docs for Linking.openURL

### PR DESCRIPTION
**Pull request by gwmccull**
## Motivation (required)

What existing problem does the pull request solve?

I was seeing errors in the crash monitoring software for my app in production.  Many took the form of, `Unable to open URL: telprompt:5551231234`

After some research, I found that when the user attempts to call a phone number, a dialog pops up in iOS asking the user to confirm or cancel the call.  If the call is canceled, the promise returned by `openURL` is rejected. 

This PR improves the documentation around what happens to the promise returned by `openURL`.

## Test Plan (required)

No test plan, text changes only.

## Next Steps

Sign the [CLA][2], if you haven't already.

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by gwmccull** [comment]
@hramos, I'm trying to figure out why this Import Failed.  Are you able to give me some advice?  It looks to me like all of the public tests passed and there were no conflicts with master (before the bot closed it).

I'd like to figure out if I did something wrong because there are some other pieces of documentation that I'd like to work on.

**Comment by javache** [comment]
You can ignore the warning, your PR landed as https://github.com/facebook/react-native/commit/8da9b04bb64e214819c7fad5b167804eefa082e0

**Comment by gwmccull** [comment]
@javache thanks!

**Comment by Priccc** [comment]
@gwmccull I think this `README.md` file is unreasonable。
I read this source code, found some code as below：
`RCT_EXPORT_METHOD(openURL:(NSURL *)URL
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
{
  BOOL opened = [RCTSharedApplication() openURL:URL];
  if (opened) {
    resolve(nil);
  } else {
    reject(RCTErrorUnspecified, [NSString stringWithFormat:@"Unable to open URL: %@", URL], nil);
  }
}`
I not familiar with iOS, but i think that I can not gain dialog's status.
Or am I not using the right way？

**Comment by gwmccull** [comment]
@Priccc I'm sorry, I don't understand what you're asking.  What are you trying to do?

**Comment by Priccc** [comment]
@gwmccull I am wondering the docs about the behavior of Linking.openURL promise rejection/resolve are not accurate.

Because I have tested with react-native v0.48.4, when I call Linking.openURL with `tel:xxx`, the promise resolves immediately, however, when the phonecall was cancelled, there is no promise rejection, the rejection only occurs when the test was performed in iPhone Simulator(there is no phone call app).

**Comment by jaycanty** [comment]
I am seeing the same as @Priccc on a device when testing Linking.openURL with `tel:2125551212`.  

I get the `confirm/cancel` popup....  

When I hit `confirm`, `Linking.openURL` is resolved.
When I hit `cancel`, `Linking.openURL` is resolved.

**Pull request closed without merging**
