### PR TITLE
Updated ScrollView's keyboardShouldPersistTaps doc

### PR DESCRIPTION
**Pull request by simonayzman**
I noticed that even when a ScrollView's `keyboardShouldPersistTaps` prop is set to true, the ScrollView's children can still respond to tap events (even if the scroll view itself will not respond to tap events and the keyboard does not dismiss automatically). This is a point of ambiguity in the React Native docs; it implies that no touch events can be handled if `keyboardShouldPersistTaps` is set to true.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @sahrens and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hramos** [comment]
Good to go once the minor eslint nit is addressed (I'm aware this is a doc change and the linting rules shouldn't apply, but it will help keep others from getting pinged about this in the future when editing this file).

**Comment by facebook-github-bot-1** [comment]
@simonayzman updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@simonayzman updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@simonayzman updated the pull request.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/306312403043022/int_phab) to review internal test results.

**Pull request closed without merging**
