### PR TITLE
Feature/gradle font sync

### PR DESCRIPTION
**Pull request by punksta**
## Summary

https://github.com/react-native-community/discussions-and-proposals/issues/89

## Changelog

[Android] [Changed] - added fonts linking in build time. 

## Test Plan

1) add some fonts in `./assets/fonts`
2) build android apk `gradlew assembleDebug`
3) find fonts in apk(you can unzip it or use android studio apk previewer)
image

### CODE REVIEW

**Comment by dulmandakh** [comment]
here is my PR to land downloadable fonts support https://github.com/facebook/react-native/pull/23865. I think that RN will deprecate assets fonts support in the future.

**Comment by punksta** [comment]
@dulmandakh I think it's good alternative, but not replacement.

**Comment by dulmandakh** [comment]
@punksta why not replace asset fonts?

**Comment by punksta** [comment]
@dulmandakh 
About [downloadable fonts](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts): I think we will always need ability to bundle fonts in app. First of all it's easy and doesn't require internet connection and handling "certs". So this can't replace fonts bundling.

About [fonts-in-xml ](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml) I just don't see enough reasons of using that in react-native now. RN is not using native xml layouts so it's so important from where to load font file (asset or resource). 
The only reasons I can find are: 
- android resource system (for example different fonts in different system languages or screen sizes)
- supporting recent android standards.

maybe if you write motivation of pull request it would be more clear.

**Comment by dulmandakh** [comment]
You can use fonts from res/font folder or custom font family defined in xml resource. Even you can ask to download files from the Internet to reduce APK size. But also you can use other font weights than normal and bold, like medium.

I should've added more summary to the PR, and will update it soon.

**Comment by cpojer** [comment]
Closing because of @dulmandakh's PR.

**Pull request closed without merging**
