### PR TITLE
Silently (warning) fail when <Image> source has empty uri

### LINKED ISSUE #3127: [Image] No suitable image URL loader found for
Hi guys,

I'm stuck by an issue when updating to react-native@0.12.0-rc : "No suitable image URL loader found for".

This issue seems to be occurring when image uri is not correct (non existing images).

Thanks !

Please let me know if you need anything else.

### PR DESCRIPTION
**Pull request by dralletje**
fixes #3127

### CODE REVIEW

**Comment by ide** [comment]
This warning is good to have in JS but I think we should have a check on the native side as well. It's better for the native side to be robust against mistakes.

**Comment by dralletje** [comment]
Done! Also added it to android.
Is it a problem that I am just returning an empty block in loadImageWithTag?

**Comment by ide** [comment]
I think it's ok to return nil since that's what happens if `loadHandler` is nil.

**Comment by dralletje** [comment]
Like this? :grin:

**Comment by nicklockwood** [comment]
@facebook-github-bot import/shipit

**Pull request closed without merging**
