### PR TITLE
Update `releases` to refer to month instead of two weeks

### PR DESCRIPTION
**Pull request by grabbou**
We also have to update internal guides.

CC: @mkonicek

### CODE REVIEW

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@grabbou @satya164 1st of January might be ambitious given it's the New Year's Day? :)

In general hitting the exact date every month might be difficult. How about saying "first week of each month"?

**Comment by mkonicek** [comment]
@satya164 Not sure why the bot didn't work :/

**Comment by mkonicek** [comment]
This landed internally but exporting back to GitHub failed.

**Comment by fredemmott** [comment]
It got exported to github: https://github.com/facebook/react-native/commit/830d7f6426a433c108726d91808fad4b40b590b9

 - the bot message didn't appear here for some unknown reason
 - the 'Closes #11269' part was removed because 'CC:' is magic to our internal tools

Closing because this PR has been merged, github just doesn't know.

**Pull request closed without merging**
