### PR TITLE
fix CSSNodeList memory leak

### PR DESCRIPTION
**Pull request by ymmuse**
CSSNodeListFree does not free the list->items memory

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @emilsjolander to be a potential reviewer.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ide** [comment]
Thanks for the PR. The original repo with this code is actually https://github.com/facebook/css-layout -- could you open a new PR with this same code there?

**Comment by ymmuse** [comment]
Sure

**Pull request closed without merging**
