### PR TITLE
Remove duplicate call delegate->moduleNames()

### PR DESCRIPTION
**Pull request by leeight**

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @cjhopman and @mhorowitz to be potential reviewers.

**Comment by leeight** [comment]
Ping @mkonicek

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3923050).

**Pull request closed without merging**
