### PR TITLE
Fixing Race condition that happens with _wasBatchActive

### PR DESCRIPTION
**Pull request by atkit**
Issue Fix: #13485 

## Motivation (required)

Yet another race condition that was found by XCode's Thread Sanitizer. 
Happens because wasBatchActive is read/write from multiple threads at the same time

## Test Plan (required)
- opened UIExplorer and see it works
- npm run test pass 
- tested on own project as well

## Next Steps

Signed CLA

### CODE REVIEW

**Comment by javache** [comment]
Instead of making this a property (with all its other overhead, can you make that bool a C++ atomic_bool?

**Comment by atkit** [comment]
I think that could work better, I can use that.
But to use that I will have to rename to .mm to use std::atomic_bool and Objective C++.

Is it fine for overall plan about Batched Bridge?

**Comment by javache** [comment]
Yeah, that's fine. We use Objective-C++ in quite a few places. You'll just need to make sure to update all the targets in React.xcodeproj (and maybe make the same change for RCTCxxBridge and ReactCxx.xcodeproj)?

**Comment by atkit** [comment]
ok

**Comment by javache** [comment]
Thanks! Can you update RCTCxxBridge too? https://github.com/facebook/react-native/blob/master/React/CxxBridge/RCTCxxBridge.mm#L106

**Comment by atkit** [comment]
It can be done as well, but I it seems _wasBatchActive is never set.

**Comment by javache** [comment]
Huh, that's a separate bug then. I'll follow up. Thanks again for fixing this!

**Comment by atkit** [comment]
done rebase with master

**Comment by atkit** [comment]
@javache did I do something wrong that caused bot to close review?

**Comment by atkit** [comment]
I see now, just different workflow that done by bot

**Pull request closed without merging**
