### PR TITLE
Example code and video for gesture responder system

### PR DESCRIPTION
**Pull request by liesislukas**
I've created this code to test out touch responder system. It would be so much easier if that would be already in place done by someone else. I think it will help others like me to learn React faster.

### CODE REVIEW

**Comment by brentvatne** [comment]
Thanks @liesislukas! Can you rebase this against master so tests pass? It looks like a showcase commit snuck in there as well :)

**Comment by Kureev** [comment]
Can you also split it up for two PRs? One for the showcase and one for the docs?

**Comment by facebook-github-bot-3** [comment]
@brentvatne would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by geirman** [comment]
@liesislukas if you could, please rebase and split into 2 prs as requested above

**Comment by javache** [comment]
This pull request hasn't seen activity in a while. If you still want to merge this, please open a new pull request.

**Pull request closed without merging**
