### PR TITLE
fixed website generation code (refer some API that is now in React codebase)

### PR DESCRIPTION
**Pull request by bestander**
@vjeux @spicyj this fixes website generation because these API are now in React.

I would refer React file but it seems fragile because it is a thirdparty dependency now.
How do we document thirdparty API?

### CODE REVIEW

**Comment by vjeux** [comment]
Sgtm

**Comment by spicyj** [comment]
I think it's okay to reference the file from React directly. It's still used only for RN (and won't be documented on the React side), just lives in the React repo to make changes easier.

**Comment by janicduplessis** [comment]
Removing this from the docs would kind of suck :( I remember the pan responder one was pretty useful when I started using it.

As @spicyj mentioned it should be possible to reference it directly from node_modules/react

**Comment by bestander** [comment]
Fixed the paths to refer node_modules/react path.
However all the docs of PanResponder.js are react-native specific and are styled for react native autodocs generation, this setup may be inconvenient.
I'll ship to fix website generation for now but would like to add this to the issues to be resolved.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
