### PR TITLE
Fix image source prop change updating image

### LINKED ISSUE #7795: BUG: TouchableOpacity can't change image and text same time.
```
          <TouchableOpacity onPress={() => this.onPraise()}>
            <View style={styles.barItem}>
                <Image source={praiseImage}/>
                <Text style={styles.barItemText}>{this.props.praise_number|'赞'}</Text>
            </View>
          </TouchableOpacity>
```

### LINKED ISSUE #8500: IOS: Image Source change issues
I'd been building an app and recently upgraded from 0.23 to 0.28 and latest React aswell. The Android just had views issues but the iOS app broke. It gives the error JSON null for RCTImage, without mentioning any line number. Figuring it down to the bits, i found that the Image's source does not take new data anymore, whether it's from props or state. Even tried using the defaultSource prop but nothing. Upon ignoring the red screen error message (esc) the red disappears and the view seems to have loaded the image just fine. The Image's source does get changed, but it shows that error first. So the thing works but gives an error for no reason ?
I think it probably makes the image source "null" for a bit before placing the new correct source there? And that bugs out xCode? I'm also using the prop resizeMode='contain' with all the images.
Really hoping to having this fixed because my app relies heavily on props for images and state changes on images source and null values for images source.

### PR DESCRIPTION
**Pull request by alexanderjarvis**
fixes #7795
fixes #8500

Motivation: When having a simple button that changes the Image source when tapped, the image doesn't change (or at least sometimes, intermittently it works).

This was found to be an issue where the request was being sent to the native layer correctly but then being subsequently cancelled by the `reactSetFrame: method`  ...

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @DavidGoldman and @bnham to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by javache** [comment]
It seems like the original logic had some purpose. Can you instead make sure `desiredImageSourceDidChange` return the correct answer here?

**Comment by skatpgusskat** [comment]
@javache ```desiredImageSourceDidChange``` doesn't work.
1. source & size changed.
2. ```setSource``` called.
3. 2. call ```reloadImage```.
4. on ```reloadImage```, ```_imageSource``` become recent source.
5. some later, ```reactSetFrame:frame``` called, it call ```desiredImageSourceDidChange```.
6. on ```desiredImageSourceDidChange```, compare ```_imageSource``` with recent source. by the 4., always true.

To solve, (1) need ```_previousImageSource``` variable or (2) make function re-order that ```reactSetFrame``` call first before ```setSource```.

**Comment by alexanderjarvis** [comment]
Thanks @skatpgusskat 
Please review again @javache

**Comment by DavidGoldman** [comment]
`desiredImageSourceDidChange` is supposed to return YES when the image source changed as a result of the view resizing when multiple sources are provided. This change completely negates this, making it so that `desiredImageSourceDidChange` always returns YES.

@javache The question is why we were cancelling the image load ("Our existing image is good enough"). I don't see why it's there...

**Comment by skatpgusskat** [comment]
My commit could be wrong. I didn't think about multiple source image case.

**Comment by javache** [comment]
Yes, this doesn't handle frame changes and the need to switch image source.

**Comment by javache** [comment]
@DavidGoldman good point, I'm not super familiar with that logic either. Could it be that even the image source loaded is correct it still needs to be resized to fit the new frame? It could be that @alexanderjarvis initial version here was correct, but I'd like to understand what the impact of the original version was.

**Comment by DavidGoldman** [comment]
@alexanderjarvis @javache Yeah, it looks like the initial version of this PR was correct.

The bug (race condition) here appears to be:

- `-|reloadImage|` is called and starts an image load
- `-|reactSetFrame:|` is called while the image is still loading and cancels the request
- The image now never loads!

I'm not quite sure why it cancelled the image request previously - doesn't seem to make sense. It also seems odd that the same bit of code would also set `_targetSize` when not actually loading the image.

**Comment by DavidGoldman** [comment]
@alexanderjarvis @javache Yeah, it looks like the initial version of this PR was correct.

The bug (race condition) here appears to be:

- `-|reloadImage|` is called and starts an image load
- `-|reactSetFrame:|` is called while the image is still loading and cancels the load
- The image now never loads!

I'm not quite sure why it currently cancels the image load - doesn't seem to make sense. It also seems odd that it sets `_targetSize` without loading the image when that variable is used to decide whether to reload or not.

**Comment by facebook-github-bot-3** [comment]
@alexanderjarvis updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@alexanderjarvis updated the pull request.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3702867) to review internal test results.

**Pull request closed without merging**
