### PR TITLE
Add "modules" option to babel-preset to allow disabling transpilation…

### PR DESCRIPTION
**Pull request by hedgepigdaniel**
… of ES6 modules to CommonJS

## Motivation

Since the majority of react-native code is written using ES6 modules, it is possible to do static analysis to achieve some new things:
 * Eliminate dead code, since if an ES6 export is never imported from the application, it cannot run
 * Identify programmer errors faster, since it is possible to detect and warn when the programmer imports a value that was not exported from a module.

Using [haul](https://github.com/callstack/haul) (which uses babel-preset-react-native by default) is it possible to compile a react-native project with [webpack](https://webpack.js.org/). Webpack natively supports ES6 modules, and will [generate a warning or error](https://github.com/webpack/webpack/pull/4348) if user code imports a value that was not exported. This only works for ES6 imports/exports however, so it does not work if babel transpiles all the imports/exports to CommonJS before webpack bundles them.

## Test Plan

I copied the contents of babel-preset from this repository into a [seperate repository](https://github.com/hedgepigdaniel/babel-preset-react-native/commit/8c41f19590264eada2cc755b13d2aeeed75b4fd2) (because I could not work out how to build this repository such that native compilation worked). I started from the latest master which was #cec2e80fc251e4ea45ce1e446323716a3792390d.

I created a [test repository](https://github.com/hedgepigdaniel/BabelPresetReactNativeTest/commits/master) to test/demonstrate the change. You can check out different commits to observe the changes made. [This commit](https://github.com/hedgepigdaniel/BabelPresetReactNativeTest/commit/eff82f6d035d922498796181179efd618fec1004) replaces babel-preset-react-native with my forked version. You can run the app as follows:
```
$ yarn
$ yarn run run-android
$ yarn run haul
```
You must disable "Delta bundles" in "Dev settings" in the device menu since haul does not support them. With the forked babel-preset-react-native (but without any new options in `.babelrc`), the app works the same as before (i.e. this is not a breaking change). It displays `FAIL! This undefined import should have been caught during compilation!`.

[This commit](https://github.com/hedgepigdaniel/BabelPresetReactNativeTest/commit/6c804ef1ee2cb6f36d23c1384d7fbe95f8d91aef) demonstrates how to use the new option. The app now fails to compile with an error that looks like this:
```
 ERROR  Failed to compile.

./App.js
1:2187-2201 "export 'IMPORTED_THING' was not found in './helper.js'
   at HarmonyImportSpecifierDependency._getErrors (/home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
   at HarmonyImportSpecifierDependency.getErrors (/home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:44:16)
   at Compilation.reportDependencyErrorsAndWarnings (/home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/webpack/lib/Compilation.js:712:22)
   at Compilation.finish (/home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/webpack/lib/Compilation.js:561:9)
   at applyPluginsParallel.err (/home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/webpack/lib/Compiler.js:506:17)
   at /home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/tapable/lib/Tapable.js:289:11
   at _addModuleChain (/home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/webpack/lib/Compilation.js:507:11)
   at processModuleDependencies.err (/home/daniel/flattenedmonad/BabelPresetReactNativeTest/node_modules/webpack/lib/Compilation.js:477:14)
   at process._tickCallback (internal/process/next_tick.js:150:11)
@ ./App.js
@ ./index.js
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./index.js
```

[This commit](https://github.com/hedgepigdaniel/BabelPresetReactNativeTest/commit/3cc35e2c085b8e0066434586298bf660734fc210) fixes the bug in the application that was causing the error. The app now builds successfully and prints `SUCCESS! IMPORTED_THING = "tomatoes :}"`.

The diff in this PR is the same as the diff [here](https://github.com/hedgepigdaniel/babel-preset-react-native/compare/8c41f19590264eada2cc755b13d2aeeed75b4fd2...478a7a2020589a3291623eea23d2e8ad126ccf24) which are the before/after versions used in the example.

## Release Notes

[INTERNAL] [ENHANCEMENT] [babel-preset] - Add option to disable transformation of ES6 modules to CommonJS

### CODE REVIEW

**Comment by hedgepigdaniel** [comment]
Not at all clear to me why these tests are failing... I didn't change any JS dependencies at all...

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
cc @hramos

**Comment by janicduplessis** [comment]
Looks like there is a conflict now, could you fix that please?

**Comment by hedgepigdaniel** [comment]
Should be fixed. Here is a new branch of the testing repository based on the latest diff, and it still works with and without the modules option: https://github.com/hedgepigdaniel/BabelPresetReactNativeTest/commits/rebase

**Comment by hramos** [comment]
Looks like this needed to be rebased past some problematic commits. I've already done so internally and will land this PR once all internal tests pass.

**Comment by hramos** [comment]
Unfortunately, it looks like this would introduce several failures to our internal suite of tests. I'll need to get back to this one later.

**Comment by hedgepigdaniel** [comment]
@hramos I've recreated this PR based on the latest version of the preset here: https://github.com/facebook/metro/pull/203

Is it possible to revisit this?

**Comment by cpojer** [comment]
As you can see on the Metro repo, @rafeca replied with an option that was added to Metro for doing this. Closing this PR here. I'm so sorry for the long wait.

**Pull request closed without merging**
