### PR TITLE
remove appcompat-v7, support-v4 from Android Support Library BUCK

### PR DESCRIPTION
**Pull request by dulmandakh**
For FB import testing purpose only

Test Plan:
----------
Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!

Changelog:
----------
Help reviewers and the release process by writing your own changelog entry. When the change doesn't impact React Native developers, it may be ommitted from the changelog for brevity. See below for an example.

[CATEGORY] [TYPE] - Message

### CODE REVIEW

**Comment by dulmandakh** [comment]
@hramos please import this, and let's see if it breaks something 😉

**Comment by hramos** [comment]
Tried to import it, but we're having trouble with our OSS tooling this morning. Will try again later.

**Comment by hramos** [comment]
This one didn't run into any issues, either. @dulmandakh is this for testing only?

**Comment by dulmandakh** [comment]
@hramos yes, so closing it.

**Pull request closed without merging**
