### PR TITLE
[CI] Start tracking coverage (JavaScript) [2/2]

### PR DESCRIPTION
**Pull request by hramos**
Adds a new step to the test suite. Test coverage is now collected and sent to Coveralls.

Initial configuration is limited to the Libraries/ and local-cli/ directories. Please let me know if additional directories should be considered.

I have enabled this repo on the coveralls service. The coveralls token has been added to React Native's Circle CI environment variables.

# Test Plan

1. Fork the repo: [hramos/react-native](https://github.com/hramos/react-native)
1. Add the fork's coveralls token to the fork's Circle CI environment variables
1. Push these changes to the fork's master branch (we're only collecting data on master).
1. Verify coverage is collected: 
 - https://circleci.com/gh/hramos/react-native/1075
 - https://coveralls.io/github/hramos/react-native
1. Push these changes to a branch on the fork, verify coverage is *not* collected: https://circleci.com/workflow-run/b7b5bb96-c30c-40f0-bf3d-252dc1910333 (test_coverage is not invoked)

# Future work

- Track coverage on PRs, and fail PRs that lower the coverage %
- Increase coverage :)

# Release Notes

[INTERNAL] [ENHANCEMENT] [.circleci/config.yml] - Start tracking code coverage (JS)

### CODE REVIEW

**Comment by janicduplessis** [comment]
Do Coveralls supports native tests as well?

**Comment by hramos** [comment]
Coveralls supports tracking coverage on Java and Objective C tests. Tracking JavaScript coverage was trivial thanks to Jest's coverage support. I will look into what it'd take to gather coverage from xcodebuild and buck.

**Comment by hramos** [comment]
xcodebuild has built-in coverage support, and [Slather](https://github.com/SlatherOrg/slather) can collect and send the results to Coveralls

buck has built-in coverage support, [JaCoCo](http://www.eclemma.org/jacoco/trunk/doc/maven.html) can be used to collect the results, and the [coveralls maven plugin](https://github.com/trautonen/coveralls-maven-plugin) can send the data to Coveralls

I have not enabled iOS coverage collection yet as those tests are currently failing on master.
I have not enabled Android coverage collection yet as it requires a few more dependencies to be set up.

This is a WIP -- I encourage anyone interested in collecting coverage in this project to take a stab at this, i.e. by opening additional PRs that cover Android and iOS separately.

**Comment by janicduplessis** [comment]
@hramos Awesome, I think landing JS is a great first step, was just curious about iOS and Android since those tests tend to be more neglected.

**Pull request closed without merging**
