### PR TITLE
Fixed - Text with adjustsFontSizeToFit changes the text layout infinitely

### PR DESCRIPTION
**Pull request by alfonsocj**
## Summary

Fixes the infinite loop explained in the issue https://github.com/facebook/react-native/issues/33129 by reverting commit  59021521e7aba0f70b91b5c7778ccdd1b30eaae4. PR https://github.com/facebook/react-native/pull/31538.

`onCollectExtraUpdates` is part of the node update cycle. By marking the node as updated `markUpdated()` in `onCollectExtraUpdates` we are restarting the update infinitely.

Unfortunately, reverting this PR also reintroduces the original issue https://github.com/facebook/react-native/issues/30717 which IMO is minor compared to the infinite loop.

## Changelog

[Android] [Fixed] - Text with adjustsFontSizeToFit changes the text layout infinitely

## Test Plan

I added a console.log to the Text `onTextLayout` in [packages/rn-tester/js/examples/Text/TextAdjustsDynamicLayoutExample.js ](https://github.com/facebook/react-native/blob/main/packages/rn-tester/js/examples/Text/TextAdjustsDynamicLayoutExample.js) to see if the infinite loop is gone.

image

Screen Shot 2022-02-17 at 11 20 31 AM

```

### CODE REVIEW

**Comment by shergin** [comment]
Yeah, as the author of the original fix (being reverted here), I believe we should back it out because it introduces way more problems than solves.

**Comment by alfonsocj** [comment]
Thanks @lunaleaps! Can we also try to include this fix in the [discussion for 0.66.5](https://github.com/reactwg/react-native-releases/discussions/8)?

**Comment by lunaleaps** [comment]
> Thanks @lunaleaps! Can we also try to include this fix in the [discussion for 0.66.5](https://github.com/reactwg/react-native-releases/discussions/8)? I'm not sure if you fix previous versions as well.

Generally no, we usually only target the current stable or release candidate.

**Comment by Orange9000** [comment]
Is there a way to apply this fix without upgrading react-native? I tried patching react-native package, but that doesn't seem to do anything, as if module remains unchanged.

**Pull request closed without merging**
