### PR TITLE
fix: ripple should be applied even when borderless == false

### PR DESCRIPTION
**Pull request by vonovak**
## Summary

With current master, when you render `<Pressable android_ripple={{borderless: false}}>`, there is no ripple effect at all.

I think the expected behavior is to have ripple with default color and radius, just not borderless.

This was how it was done (by me) in https://github.com/facebook/react-native/pull/28156/files but in the import process, the implementation was changed: https://github.com/facebook/react-native/commit/bd3868643d29e93610e19312571a9736df2cbdf8 so either this PR is a fix or you can just close it (but I'd be curious why).

## Changelog

[Android] [fixed] - ripple should be applied even when borderless == false

## Test Plan

`<Pressable android_ripple={{borderless: false}}>` on master

SVID_20200404_123614_1

`<Pressable android_ripple={{borderless: false}}>` in this PR

SVID_20200404_122754_1

### CODE REVIEW

**Comment by TheSavior** [comment]
Thanks for following up. It's possible I broke the implementation when making changes locally.

The change was made because of a comment in internal review:

> You should do this normalization at line 49 instead of here. It means this useMemo would not need to be recomputed if borderless were to change from undefined or null to false.

**Comment by vonovak** [comment]
@TheSavior thanks for the explanation, I see. 

if we change 

```
// this is master
const normalizedBorderless = borderless === true;
return useMemo(() => {
  ...
}, [color, normalizedBorderless, radius, viewRef]);
```

to 

```
const normalizedBorderless = !!borderless;
return useMemo(() => {
  ...
}, [color, normalizedBorderless, radius, viewRef]);
```

wouldn't that work? `undefined`, `null` and `false` would all be normalized to `false`

**Comment by TheSavior** [comment]
What's the difference between `!!borderless` and `borderless === true`? Wouldn't `borderless === true` give `false` for `undefined`, `null`, and `false`? Are there other changes in the code that I'm not understanding? When borderless is set, is it some other truthy value than `true`?

**Comment by vonovak** [comment]
@TheSavior I'm sorry, there's no different obviously 😅 it's late here, I think I should leave this for morning. I did push another commit though, just changing a condition. The idea is - on android, when you pass `android_ripple` prop to Pressable, you'll get a default ripple. That includes even passing just `{}` though. Maybe the condition could be 

```
    if (
      Platform.OS === 'android' &&
      Platform.Version >= 21 &&
      (color != null || borderless != null || radius != null)
    )
```

what would you expect when you pass `android_ripple={ color: null, borderless: null, radius: null }`? I'd expect a ripple effect that has default radius, color, and is not borderless. Someone else might expect no ripple effect at all I guess. Maybe 

```
export type RippleConfig = {|
  color?: ?ColorValue,
  borderless?: ?boolean,
  radius?: ?number,
|};
``` 

should be changed to 

```
export type RippleConfig = {|
  color?: ColorValue,
  borderless?: boolean,
  radius?: number,
|};
```

**Comment by TheSavior** [comment]
I think it is reasonable to change the type to:
```
export type RippleConfig = {|
  color?: ColorValue,
  borderless?: boolean,
  radius?: number,
|};
```

I think I find `android_ripple={{}}` to signal that you want the default values, a bit strange. It looks like a bug to me. I think I'd prefer something more explicit like: `android_ripple={true}`. So you can pass true or an object. What do you think?

**Comment by TheSavior** [comment]
@vonovak, is this ready to merge?

**Comment by vonovak** [comment]
@TheSavior I changed the type to 

```
export type RippleConfig = {|
  color?: ColorValue,
  borderless?: boolean,
  radius?: number,
|};
```

I previously used `prop?: ?type` pattern because most props are typed that way, but since this is not a "direct prop" (like a `string` or some callback fn) but an object, I feel like this also makes sense and it makes the implementation more straightforward by not having to handle the useMemo case you posted above.

- `android_ripple={{}}` will do nothing, at least one key has to be present for the ripple to show up. I think this is reasonable
- I did not add support for `android_ripple={true}`, I think it's (1) easy enough to simply pass an object and (2) it's explicit, but if you feel like having it, we can make it so that we normalize `rippleConfig ={true}` => `rippleConfig={borderless: false}` and `rippleConfig={false}` => `rippleConfig={undefined}`. 
- Also, now that I'm looking at it, Pressable uses this branch 

https://github.com/facebook/react-native/blob/b9944e54ae35c2beed0e78ea454d871e0fe92ec6/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactDrawableHelper.java#L56

but TouchableNativeFeedback can also use this one

https://github.com/facebook/react-native/blob/b9944e54ae35c2beed0e78ea454d871e0fe92ec6/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactDrawableHelper.java#L36

I'm not actually sure what the reason for two branches is, maybe it's because of old android versions (?) - not sure. There are some [docs](https://reactnative.dev/docs/touchablenativefeedback#methods), but for example the docs for the `"RippleAndroid"` are inaccurate because they claim `color` is required, but it's not, as seen in this [`else` branch](https://github.com/facebook/react-native/blob/b9944e54ae35c2beed0e78ea454d871e0fe92ec6/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactDrawableHelper.java#L65). So... what do you think? I feel like it's ready for merge. (I hope, somehow this ripple thing has been more complicated than it seemed at first 😅 )

**Comment by vonovak** [comment]
> I feel like the intent from the feedback the internal review got lost and this is just reverting it.
> ...
> recommendation was to pull `borderless: borderless === true` out of useMemo so that we are specifically checking a boolean, and a change from undefined to null won't cause a recalculation.

yes, it is correct that this is reverting that part. I did that knowingly. The idea is - previously `borderless` entry was `borderless?: ?boolean` and so, as pointed out in review, to support such api, we needed to take into account various changes to `borderless` in order for `memo` to work well.

By changing the api to `borderless?: boolean` I'm saying "I expect borderless to be true or false (not null or undefined) and by doing this, memoization will work if consumer uses the the api as it is designed." - I see this may come off as me being lazy but it's simple and it works well when used "as advertised".

> Perhaps I'm misunderstanding how pulling out const normalizedBorderless = borderless === true; caused a behavior issue.

the problem in behavior was caused by changing this condition

https://github.com/facebook/react-native/blob/bd3868643d29e93610e19312571a9736df2cbdf8/Libraries/Components/Pressable/useAndroidRippleForView.js#L56

when `<Pressable android_ripple={{borderless: false}}>` is rendered, the condition evaluates to `false` and `null` is returned, meaning no ripple, when I instead expect a bordered ripple (see gif at the top).

We could somehow handle the memoization issue pointed out in the internal review. Eg, have an extra flag that would be used in the aforementioned condition so that even in the case of `<Pressable android_ripple={{borderless: false}}>`the condition would evaluate to true. But that'd make the code more complicated and it would mean one more thing to memoize. I just didn't think it was worth it.

**Comment by TheSavior** [comment]
> By changing the api to borderless?: boolean I'm saying "I expect borderless to be true or false (not null or undefined)

I don't think this is true. I think `null` isn't possible anymore since the key has to be boolean if it is there, but the key isn't required, which means it could be `undefined`. So `borderless` could change from `undefined` to `false` and cause memo to recalculate unnecessarily. 

Maybe I'm not clear on what the different states should render with regards to border. Let me debug this out loud for myself.

Your behavior:
| value | my expectation of the default | my understanding of the behavior in your change |
| ----- | ------------ | --------- |
|undefined| border | no ripple if `{}`, with border otherwise |
|false| border | border|
|true|no border| no border | 

my behavior:
| value | `const normalizedBorderless = borderless === true;` | my understanding of my result | 
| ----- | ------------ | -------- |
|undefined|false|no ripple if `{}`, with border otherwise |
|false|false| no ripple if `{}`, with border otherwise|
|true|true|no border|

Ah, alright. I see how this broke `<Pressable android_ripple={{borderless: false}}>` as you said. Okay, I'm on board with this change. I agree that it seems complicated to keep useMemo from recalculating and maintain the behavior you have between `undefined` and `false`. Thanks for being patient with me 😇

------------

How do you want to handle `<Pressable android_ripple={{}}>`? Do you want to throw if none of the keys are specified?

**Comment by vonovak** [comment]
> I think null isn't possible anymore since the key has to be boolean if it is there, but the key isn't required, which means it could be undefined.

eh, right, jezus, my thinking on this has been so embarrassing I feel like I shouldn't have even started this 💦 😅

I'd even suggest we create these static creators like [touchablenativefeedback](https://reactnative.dev/docs/touchablenativefeedback#selectablebackground) has. They are just functions that return the ripple config objects, and that way we have more control over how the ripple is used, and we can avoid the `useMemo` issues. WDYT? Then `<Pressable android_ripple={{}}>` would be "undefined behavior" and currently, if I'm not wrong, it would not show any ripple which is okay.

**Comment by TheSavior** [comment]
Heh, no worries, I have felt the exact same way. That is why i had to create the tables to force myself to walk through it carefully. :-D

I’ll import this tomorrow

**Comment by vonovak** [comment]
One more thing that might be useful would be having these static config creators like [touchablenativefeedback](https://reactnative.dev/docs/touchablenativefeedback#selectablebackground) has - they are just functions that return an object with the ripple config. If we had these and instructed people to use those we would have more control over the passed object and maybe avoid potential weirdness I got trapped into myself here.

**Comment by TheSavior** [comment]
I don’t think we’ve painted ourselves into a corner. I think we can ship Pressable as is and decide to add those later if we find they’d help simplify things.

**Pull request closed without merging**
