### PR TITLE
Revert "Add subviewStyle prop to NavigationHeader"

### PR DESCRIPTION
**Pull request by bestander**
This reverts commit 1dc82a9e5f27339c352e171a5d1c760d90b04440.

Breaks OSS tests

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
Reverts https://github.com/facebook/react-native/pull/7214

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @satya164 to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1695259990729341/int_phab) to review.

**Pull request closed without merging**
