### PR TITLE
upgrade image-size version fix caculate webp image size bugs

### PR DESCRIPTION
**Pull request by Lxxyx**
When I try to use webp for app. But some webp images get an error message `unsupported file type` by image-size@0.3.5.

And I in image-size repo I found a issue https://github.com/image-size/image-size/issues/65.
This is the same problem.

And try image-size^0.5.1 the error fixed.

image

### CODE REVIEW

**Comment by Lxxyx** [comment]
@shergin The new pull request is here.
Thank you.

**Comment by Lxxyx** [comment]
@shergin import failed but I don't know what makes test failed. Would you help me?

**Comment by shergin** [comment]
@Lxxyx I believe we also have to update `DependencyGraph-test.js`. Could you please do this?

**Comment by shergin** [comment]
It can not be landed because this diff breaks a packages consistency test.

**Pull request closed without merging**
