### PR TITLE
Native propTypes RCTDatePickerIOS !== propTypes DatePickerIOS

### PR DESCRIPTION
**Pull request by dejakob**
The propTypes of RCTDatePickerIOS do not fit with the propTypes of DatePickerIOS.
All dates (date, minimumDate, maximumDate) are a timestamp (check line 126), so they should have propType number.
OnDateChange function should not be required since it is called onChange in the iOS implementation.

The problem currently causes warnings that the given types are wrong, while they were added correctly.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @gabelevi to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by nicklockwood** [comment]
Ah nice, this looks like a better solution than the previous proposals.

**Comment by facebook-github-bot-9** [comment]
@dejakob updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@dejakob updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@dejakob updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@dejakob updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@dejakob updated the pull request.

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/231636790556680/int_phab) to review.

**Comment by dejakob** [comment]
👍

**Pull request closed without merging**
