### PR TITLE
Fixed a few language errors in the Introducing Hot Reloading blog post.

### PR DESCRIPTION
**Pull request by nlindroos**
Have completed the CLA.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @vjeux to be a potential reviewer.

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Thanks a lot! That's what you get from putting two non native english speakers in charge of writing a blog post :)

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1728200044122745/int_phab) to review.

**Pull request closed without merging**
