### PR TITLE
Bugfix - Only add valid IOSPicker items.

### PR DESCRIPTION
**Pull request by ajwhite**
Fixes https://github.com/facebook/react-native/issues/9216.

As @nickzuber describes in #9216, conditional `Picker.Item` elements will lead to exceptions downstream when the `Picker` attempts to construct the collection of items.

[In the picker source](https://github.com/facebook/react-native/blob/a2fb703bbb988038323c55b29b40e8f5ff52966d/Libraries/Components/Picker/PickerIOS.ios.js#L48-L53) we can see that `child.props` is accessed when `child` has the potential to be an invalid `React` element.

```js
ReactChildren.forEach(props.children, function (child, index) {
  if (child.props.value === props.selectedValue) {
    selectedIndex = index;
  }
  items.push({value: child.props.value, label: child.props.label});
});
```

This change ensures the incoming element is valid

```diff
ReactChildren.forEach(props.children, function (child, index) {
+ if (!React.isValidElement(child)) {
+   return;
+ }
  if (child.props.value === props.selectedValue) {
    selectedIndex = index;
  }
  items.push({value: child.props.value, label: child.props.label});
});
```

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @spicyj and @davidaurelio to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @spicyj as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by spicyj** [comment]
What else would it be? Erroring seems better than silently failing.

**Comment by ajwhite** [comment]
> conditional `Picker.Item` elements will lead to exceptions downstream when the Picker attempts to construct the collection of items.

```js
<Picker>
  {predicate && <Picker.Item ... />}
</Picker>
```

If that evaluates to `false`, then `Picker` receives `false` as one of the `children`. It will attempt to unsafely access a property on this value, `child.props.value`, where `child` has the potential to not be a React element

There's a good example in https://github.com/facebook/react-native/issues/9216

**Comment by ajwhite** [comment]
> Erroring seems better than silently failing.

This is a good point -- if we get a value that is truthy, but is not a React element (doesn't have `props`), then it shouldn't be accepted.

However conditional picker items should be allowed gracefully - perhaps instead of `React.isValidElement`, we can do a simple truthiness check

```js
if (!child) {
  return;
}
```

This would satisfy the situation where we have a conditional `Picker.Item`, and continue to throw an error if you insert something that is an invalid element

#### Ignored
```jsx
<Picker>
  {false && <Picker.Item ... />}
<Picker>
```

#### Exception raised
```jsx
<Picker>
  {{foo: 'bar'}}
</Picker>
```

**Comment by nickzuber** [comment]
@spicyj Allowing for falsy values to silently be ignored by the picker seems to be almost expected behavior (maybe that's just me).

Like @ajwhite suggested, it would make sense to throw an error when an illegal item attempts to pass through the picker as a child, but with the exception of `null` or `false` etc, I can't see any reasons not to allow for these to silently be skipped over.

**Comment by spicyj** [comment]
I'm fine changing this to skip over true/false/null/undefined which are the children that React ignores. If you use React.Children.toArray (unlike map and forEach) that should happen automatically.

**Comment by ajwhite** [comment]
> If you use `React.Children.toArray` (unlike map and forEach) that should happen automatically.

Fantastic - was not aware it behaves this way, will update.

**Comment by facebook-github-bot-7** [comment]
@ajwhite updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9243/files/de0c164a9735e54aba51124c0e2bff06e9f3e653..bb0a814b8b4fd00a8c594f20612fcf30dbc93e77)

**Comment by facebook-github-bot-3** [comment]
@ajwhite updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9243/files/bb0a814b8b4fd00a8c594f20612fcf30dbc93e77..3b7adfbfe66fa6ac97b77d76939f5746f22e6b83)

**Pull request closed without merging**
