### PR TITLE
Fix to make bundling available for iPhone simulators again

### PR DESCRIPTION
**Pull request by poonamst**
Motivation:-

Being a framework, other teams are not debugging RN part of code but use it as a blackbox component. It creates a lot of inconveniences for developers which use the framework in a way as many other standard frameworks, real device or simulator does not make any difference for developers who are not directly develop RN code.

For iOS projects that create the JSBundle within the DyLib framework, this condition results in the bundle being unavailable for iOS emulators and results in an infinite loop resulting in a crash saying _fbBatched bridge undefined. Removing this piece of code would make the bundle available for iOS simulators for all such projects when the JSLocation is pointing to the RN Bundle.

### CODE REVIEW

**Comment by frantic** [comment]
So this is the same cycle we went through inside Facebook. At first it was "always bundle", then it was too slow and we switched to "skip bundling for simulator", then a bunch of edge cases appeared (e.g. "Release builds in simulator still need the bundle"). Then RN got into a larger app that many non-RN engineers work on and we faced the same problem you are describing. We haven't yet came out with solution that makes everyone happy.

Merging this in means everyone in open source community will get slower builds.

What you could do for now is copy and customize the `packager/react-native-xcode.sh` script into your project and replace the reference in Xcode.

image


The alternative would be to add some kind of setting to that script like `FORCE_BUNDLE`, but then it's another piece of configuration to maintain.

**Comment by marcshilling** [comment]
@frantic "Release builds in simulator still need the bundle"...yes, this is a need of mine. What I don't understand though (and this could be my lack of shell script knowledge) is isn't the `if [[ "$PLATFORM_NAME" = "iphonesimulator" ]]; then skip bundle` only executed if running a debug build. Why is the bundle still skipped for me when running a Release configuration on the simulator?

**Comment by poonamst** [comment]
@frantic Yes we are currently not using the react-native-xcode.sh and overriding it with our own script but would be difficult to maintain with the changes in every upgrade. Weighing this with the concern you mentioned, would it be worth making this available for all the teams depending on this again?

**Comment by facebook-github-bot-6** [comment]
@clickthisnick would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by javache** [comment]
For now we'll keep react-native-xcode as-is. Internally, we're using Buck which makes usage of react-native transparent to engineers not using it.

**Pull request closed without merging**
