### PR TITLE
Pass applyAnimation through CardStack

### PR DESCRIPTION
**Pull request by ptomasroos**
Currently its not possible when rendering a CardStack to control the animation of the AnimatedView.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @gabelevi to be potential reviewers.

**Comment by geirman** [comment]
@ptomasroos bump

**Comment by facebook-github-bot-6** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @hedgerwang as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ptomasroos** [comment]
I think this is outdated by now.

**Pull request closed without merging**
