### PR TITLE
Fix react-native link fails

### PR DESCRIPTION
**Pull request by HazAT**
I've noticed that `react-native link` doesn't link correctly anymore.
Took some time until I found out that `params` passed in the android link step is an empty array.
I am pretty sure the reason for this lies somewhere else, this fixes the issue though.
So I made the check in the if more explicit which shouldn't harm either way.

Before the fix: 
`$ react-native link react-native-sentry`
```
Scanning 563 folders for symlinks in /Users/haza/Projects/sentry-examples/react-native/AwesomeProject/node_modules (5ms)
```

After the fix:
`$ react-native link react-native-sentry`
```
react-native link react-native-sentry
Scanning 563 folders for symlinks in /Users/haza/Projects/sentry-examples/react-native/AwesomeProject/node_modules (6ms)
rnpm-install info Linking react-native-sentry android dependency
rnpm-install info Android module react-native-sentry has been successfully linked
rnpm-install info Linking react-native-sentry ios dependency
rnpm-install info iOS module react-native-sentry has been successfully linked
android/sentry.properties already exists
ios/sentry.properties already exists
```

### CODE REVIEW

**Comment by taquayle** [comment]
Thanks for this!, was driving me insane trying to get link to go anything

**Comment by grabbou** [comment]
cc: @Kureev

**Comment by HazAT** [comment]
Sorry, I don't like to bump things but this still seems broken for some version.
@grabbou @Kureev

**Comment by Kureev** [comment]
Sorry for not reacting earlier. I'm on it right now. Will test it on a blank project. If I can reproduce the issue and fix it by running `react-native link` from your branch - I'll give my approve.

**Comment by halilb** [comment]
I can confirm this PR fixes the linking problem for my project. I've been applying this patch before linking anything for some time.

**Comment by Kureev** [comment]
I just checked the current state of the link using blank project and `react-native-sentry`. So far it all works good. 

Here is my `package.json`:
```json
{
        "name": "Test",
        "version": "0.0.1",
        "private": true,
        "scripts": {
                "start": "node node_modules/react-native/local-cli/cli.js start",
                "test": "jest"
        },
        "dependencies": {
                "react": "16.0.0-alpha.12",
                "react-native": "0.47.2",
                "react-native-sentry": "^0.22.0"
        },
        "devDependencies": {
                "babel-jest": "20.0.3",
                "babel-preset-react-native": "3.0.2",
                "jest": "20.0.4",
                "react-test-renderer": "16.0.0-alpha.12"
        },
        "jest": {
                "preset": "react-native"
        }
}
```
In the project I use
```
react-native-cli: 2.0.1
react-native: 0.47.2
```

For some reason I can't reproduce your issue. Can you be a bit more specific about it?

**Comment by HazAT** [comment]
@Kureev I can confirm that this error is gone for the latest react-native version `0.47.2`.
As I wrote in the initial PR comment the reason for this possibly lies somewhere else than the fix I submitted.
But this was broken for a version in the past. 
So I let you decide what to do from here, probably you can just close it and people should upgrade their react-native if they are still having troubles.

**Comment by Kureev** [comment]
@HazAT I'm wondering if you know the way we can fix it for previous versions. IIRC there were no incidents when the previous version has been patched after the new one is released with the fix.

Theoretically speaking: if I merge this PR, it'll land in something like 0.47.3 or 0.48, but in these versions the issue you want to fix is already gone, so I don't see any arguments for merging.

Don't get me wrong, you did a great job investigating and solving the issue, but because of the delay from our side it is not relevant anymore 😞 . I'm very sorry for this experience, especially taking into account it is your first contribution to the project. I hope it won't undermine your trust in the community or RN team and we'll see your contributions in the future.

I'm about to close this PR as the issue is already fixed in the newest version. If you feel there is still something we need to do, feel free to ping me to re-open this.

Thanks for understanding!

**Comment by HazAT** [comment]
@Kureev No problem at all 😄 
I totally understand the decision, would have done the same.
move fast, break things, fix stuff >>> never release anything
that's the best and worst thing about react native 😂

**Comment by HazAT** [comment]
@Kureev Another user of ours reported that it's not working.
Turns out the broken version was `0.47.0`

Steps to reproduce:
`react-native init AwesomeProject --version react-native@0.47.0`
`cd AwesomeProject`
`yarn add react-native-sentry`
`react-native link react-native-sentry`

Output: 
```
Scanning 583 folders for symlinks in /private/tmp/AwesomeProject/node_modules (9ms)
```

So no actual linking, since this is working in `0.47.2` there is nothing to do, I just wanted to document this for completeness.

**Comment by MovingGifts** [comment]
I have the same issue with `0.46.0`, I am using ReactXP which just upgraded react native to `0.46.0`. Is there any way I can get `react-native link` working on that version?

Really stuck on this one, any help is highly appreciated :)

**Comment by Anees-Raja** [comment]
Still having the same issue as @HazAT posted on Aug 31

**Pull request closed without merging**
