### PR TITLE
showcase link on React-native website.

### LINKED ISSUE #2184: [Docs] I think it's time to add a showcase for react-native
I think if there should have a showcase for react-native-app in the website.

Now I only know that, groups is power by react-native. The showcase will make more people know the power of react-native, and then they will try.

How do you think?

### PR DESCRIPTION
**Pull request by chirag04**
Initial implementation of showcase. Everyone should PR to add a new showcase div. Happy to add my app if you guys approve.

Sample screenshot attached below.

fixes #2184.

cc @brentvatne @vjeux 

showcase react native a framework for building native apps using react

### CODE REVIEW

**Comment by soliury** [comment]
good. +1

**Comment by brentvatne** [comment]
@chirag04 - this looks like a good start, can you add some apps to it?

**Comment by soliury** [comment]
@chirag04 Maybe [noder](https://github.com/soliury/noder-react-native) a choice?

**Comment by chirag04** [comment]
@soliury sure. I'm updating the PR to add some apps.

Here is the list so far:

f8, groups, ads manager
react native playground
ncredible(https://itunes.apple.com/ca/app/ncredible/id1019662810?mt=8)
mintrain(https://itunes.apple.com/us/app/mintrain/id1015739031?mt=8)
youmeyou(https://itunes.apple.com/us/app/youmeyou/id949540333?mt=8)
HSK Level 1 Chinese Flashcards(https://itunes.apple.com/us/app/hsk-level-1-chinese-flashcards/id936639994)
Mr. Dapper - Men Fashion App(https://itunes.apple.com/us/app/mr.-dapper-men-fashion-app/id989735184?ls=1&mt=8)
Lumpen Radio(http://appsto.re/us/NdeV7.i)
Night Light - Soft Light, Nursery Light and Baby Lamp(https://itunes.apple.com/gb/app/night-light-feeding-light/id1016843582?mt=8)
Facebook Ads Manager - Android Apps on Google Play(https://play.google.com/store/apps/details?id=com.facebook.adsmanager)
Beetroot(https://itunes.apple.com/us/app/beetroot/id1016159001?ls=1&mt=8)

**Comment by chirag04** [comment]
@brentvatne  updated the PR. added all the apps you mentioned in no particular sort order.

@soliury  couldn't find the itunes link to noder app.

**Comment by soliury** [comment]
@chirag04 yes, the noder have not hang on the app store.

**Comment by RWOverdijk** [comment]
:+1:. Perhaps also link to code if anything is open source? It'd be very interesting to see some code bases and learn from others.

**Comment by ssssssssssss** [comment]
https://itunes.apple.com/cn/app/tong-xing-wang/id914254459?mt=8

**Comment by dsibiski** [comment]
Here is another one: https://itunes.apple.com/us/app/discovery-vr/id1030815031?mt=8

**Comment by chirag04** [comment]
Let's add all these links once we have this PR merged. Not sure if there is anything i can do to get this merged.

cc @ide @vjeux @brentvatne

**Comment by vjeux** [comment]
That's awesome!

One nit, can you make the items smaller, right now they are wayy to big :p

**Comment by chirag04** [comment]
Awesome! I will submit a PR for reducing the size.

**Comment by soliury** [comment]
@chirag04 good job, look nice.

**Pull request merged**
