### PR TITLE
Create a simple swift project from React Native CLI

### PR DESCRIPTION
**Pull request by bokri**
Create a swift iOS code base instead of the old Objective C project with the same command React Native CLI.
react-native init NameOfMyAwesomeProject

### CODE REVIEW

**Comment by jeanregisser** [comment]
This should probably NOT be the default as switching the app to Swift makes it grow by about 5MB because it then needs to embed Swift's runtime frameworks. See http://stackoverflow.com/questions/28275711/adding-swift-to-project-increase-size-substantiously-how-and-when-can-it-be-avo

Maybe this could be an opt-in option with the cli? I'll let the RN maintainers share their thoughts.

**Comment by hramos** [comment]
Can you please make sure to fill out the PR template? Please explain your motivation behind this and why you feel this should be the default behavior.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/create-a-simple-swift-project-from-react-native-cli

**Comment by hramos** [comment]
This was closed in error yesterday, but upon further review it looks like it is indeed inactive with no follow up from the author in over two months.

**Pull request closed without merging**
