### PR TITLE
Make Getting Started labels a bit more clear

### PR DESCRIPTION
**Pull request by JoelMarcey**
Target > Platform to represent target for your RN app
Development > OS to represent your RN Development environment

screen shot 2016-05-19 at 10 33 47 am

### CODE REVIEW

**Comment by atifmansoor** [comment]
shipit

**Comment by janicduplessis** [comment]
Agree with 'Target', maybe 'Development OS' or keeping just 'OS' would be better?

**Comment by JoelMarcey** [comment]
Ugh.... my commits got all crazy here although what is being committed is right. Let me see if i can fix.

**Comment by JoelMarcey** [comment]
I don't like all these commits. And I don't want to deal with squashing, etc. I am just going to create a new pull request, since this was such a simple one.

**Comment by facebook-github-bot-9** [comment]
@JoelMarcey updated the pull request.

**Pull request closed without merging**
