### PR TITLE
[Android] Add onUserLeaveHint support to ReactActivityDelegate

### PR DESCRIPTION
**Pull request by behenate**
## Summary:

This PR adds `onUserLeaveHint` support into the `ReactActivityDelegate`. It allows modules to receive an event every time user moves the app into the background. This is slightly different than `onPause` - it's called only when the user intentionally moves the app into the background, e.g. when receiving a call `onPause` should be called but `onUserLeaveHint` shouldn't.

This feature is especially useful for libraries implementing features like Picture in Picture (PiP), where using `onUserLeaveHint` is the [recommended way of auto-entering PiP](https://developer.android.com/develop/ui/views/picture-in-picture#:~:text=You%20might%20want%20to%20include%20logic%20that%20switches%20an%20activity%20into%20PiP%20mode%20instead%20of%20going%20into%20the%20background.%20For%20example%2C%20Google%20Maps%20switches%20to%20PiP%20mode%20if%20the%20user%20presses%20the%20home%20or%20recents%20button%20while%20the%20app%20is%20navigating.%20You%20can%20catch%20this%20case%20by%20overriding%20onUserLeaveHint()%3A) for android < 12.

This is a re-submission of https://github.com/facebook/react-native/pull/42741. The problematic `assert` has been changed to an `if` - it's not a problem if onUserLeaveHint is received from an activity different to the current one, but in that case we shouldn't emit the event.

## Changelog:

[ANDROID] [ADDED] - Added `onUserLeaveHint` support into `ReactActivityDelegate`

## Test Plan:

Tested in the `rn-tester` app - callbacks are correctly called on both old and new architecture.

### CODE REVIEW

**Comment by cortinico** [comment]
@behenate sadly this had to be reverted once more due to a crash on one of our internal products. I'll get back to you on Monday with more details and we'll see what are the next steps

**Comment by behenate** [comment]
@cortinico Interesting, I'm not sure what could be causing a crash in this code since it's pretty straightforward. Waiting for more info!

**Comment by cortinico** [comment]
@behenate so the app gets stuck on the loading screen with this stacktrace:

```
E  Handling exception for crash
java.lang.AssertionError
	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:82)
	at com.facebook.react.ReactInstanceManager.onUserLeaveHint(ReactInstanceManager.java:596)
	at com.facebook.react.ReactDelegate.onUserLeaveHint(ReactDelegate.java:105)
	at com.facebook.react.ReactActivityDelegate.onUserLeaveHint(ReactActivityDelegate.java:129)
	at com.facebook.react.ReactActivity.onUserLeaveHint(ReactActivity.java:111)
	at android.app.Activity.performUserLeaving(Activity.java:9167)
	at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1667)
	at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:5693)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5673)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by behenate** [comment]
@cortinico I'm also not sure why onUserLeaveHint is called this early in the app, but it should be safe to ignore it. I will make another PR tomorrow. Hopefully third time's the charm 🙃

**Comment by cortinico** [comment]
Sadly we have to revert this once more as it's causing a couple of internal apps to fail. Here the stacktrace:

https://github.com/facebook/react-native/pull/43642

**Pull request closed without merging**
