### PR TITLE
[react-native-gradle] Add flavor support for gradle plugin

### PR DESCRIPTION
**Pull request by achellies**
react-native-gradle plugin will occur errors when apply in build.gradle which contains flavor settings.

if we add flavor in our project build.gradle, and at the same time we apply 'com.facebook.react' plugin , the following error message will occur when we sync build.gradle:

"processReleaseResources Task does not existed"

### CODE REVIEW

**Comment by foghina** [comment]
Thank you for the pull request, @achellies! Unfortunately, we are deprecating the gradle plugin in favor of more configurable gradle tasks that actually run `react-native bundle` instead of directly hitting the dev server. Check out 9dc036d.

**Comment by mkonicek** [comment]
Closing as the Gradle plugin is not needed anymore. @foghina is going to remove it. Sorry for the confusion.

**Comment by foghina** [comment]
Already removed in ce7de93.

**Comment by achellies** [comment]
ok, i see

**Pull request closed without merging**
