### PR TITLE
Add `RCTBundleURLProcessor` files to Xcode project

### PR DESCRIPTION
**Pull request by martinbigio**

### CODE REVIEW

**Comment by martinbigio** [comment]
cc @vjeux @nicklockwood

**Comment by vjeux** [comment]
:+1:

**Comment by martinbigio** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
