### PR TITLE
Initial implementation of adjustsFontSizeToFit.

### PR DESCRIPTION
**Pull request by MattFoley**

### CODE REVIEW

**Comment by MattFoley** [comment]
It had been way too long to fix it up myself, so I've reopened the PR. Here's the original. https://github.com/facebook/react-native/pull/2327

**Comment by MattFoley** [comment]
This should be stable enough to merge now.

**Comment by MattFoley** [comment]
Keeping this squashed on master led to a missed file. Corrected.

**Comment by MattFoley** [comment]
@nicklockwood, @sahrens, @a2 Correct me if I'm wrong, but the tests failing after my last commit/squash are not due to my code changes, correct?

**Comment by nicklockwood** [comment]
Did something go wrong with the merge/rebase?

The `adjustsFontSizeToFit` and `minimumFontScale` are defined on both `RCTText` and `RCTShadowText`, but the ones on `RCTShadowText` aren't used anywhere in the code, and the ones on `RCTText` aren't exported in `RCTTextManager`.

Also, you don't seem to have added the new props to `Text.js` or `TextStylePropTypes.js`

**Comment by MattFoley** [comment]
I think that's just misunderstanding on my part, and the age of this PR. Let me remove them from `RCTShadowText`.

I was assuming that RCTTextManager just needed the two `RCT_EXPORT_SHADOW_PROPERTY` lines it has, is that not correct? Give me a bit and I will add them to `Text.js` and `TextStylePropTypes.js`.

**Comment by nicklockwood** [comment]
RCT_EXPORT_SHADOW_PROPERTY exports properties on the shadow view. To export properties on the view you need RCT_EXPORT_VIEW_PROPERTY. I'm not sure how this could ever have worked in its current form.

**Comment by MattFoley** [comment]
Miracle of science I suppose.

**Comment by MattFoley** [comment]
Are you sure that RCT_EXPORT_VIEW_PROPERTY is correct in this instance? It's not used once inside the entire RCTText project?

**Comment by MattFoley** [comment]
You know, I think I see part of what's missing. `RCTText` must be an odd case. From what I can tell, all properties of `RCTText` are exported as shadow properties, and then passed into `RCTText` from `RCTShadowText` via `NSTextContainer`, `NSTextStorage`, and `NSLayoutManager`. That being said, there were a few lines in RCTShadowText that have been squashed out. Updating now.

**Comment by SAPIBELPRODUCTIONS** [comment]
What can you make you more confortable when you are at your page

**Comment by nicklockwood** [comment]
Github spam. That's a new one.

**Comment by nicklockwood** [comment]
@MattFoley thanks, that makes more sense. Is there any reason that this resizing logic can't be implemented on the shadow view though? It seems like it only relies on the view frame, which is calculated on the shadow side.

The reason we have this thread architecture is because calculating text layout is fairly expensive, so we do it off the main thread. But it seems like we lose the benefit of that if we then re-calculate it on the main thread in order to do the size adjustment.

**Comment by MattFoley** [comment]
That makes sense. I think I'm mainly doing it on the main thread now so that I knew the font was only modified after the frame was completely set for the view. I'm trying to move it out to the RCTextShadowView now without much luck yet.

**Comment by MattFoley** [comment]
Ah, immediately after typing that I figured out what I was doing wrong. Give me a bit and I'll have this cleaned up and moved out to RCTShadowText.

**Comment by nicklockwood** [comment]
This looks great, thanks!

@facebook-github-bot import

**Comment by MattFoley** [comment]
I'm going to run some more in depth tests on this @nicklockwood with some of my own projects that are using this, just to make sure everything is solid on master. But yay! :tada:

**Comment by nicklockwood** [comment]
It would be great if you could add an example to the TextExample.hs in UIExplorer that demos the feature.

**Comment by MattFoley** [comment]
Yeah, I will, may be a few days. After these changes, I'm having trouble running against this with some of my older projects using this stuff, so I'd like to take a little while to make sure this is working the way it should. (Probably has something to do with my build environment.) Wait on this PR until there's a working example?

**Comment by GantMan** [comment]
:+1:  hope to see this feature soon.  Great work!

**Comment by marcshilling** [comment]
I cherry-picked this and have been using it in my app. Pretty great! The only thing is I wish it would append '...' if your `minimumFontScale` was not small enough to fit the whole string. Think that could be accomplished?

**Comment by marcshilling** [comment]
@MattFoley hmmm, I'm running into some issues with this today. It appears that text isn't always re-rendering. 

I'm logging a variable `name` in my render method, and using it inside a `<Text>` component. On the initial render, `name` is an empty string, but eventually new props come in and it becomes a valid string. Re-render is triggered (I see `name` logged correctly), but the `<Text>` remains blank.

Any idea what could be going on?

**Comment by skevy** [comment]
@MattFoley just wanted to ping on this...any news on this PR?

**Comment by MattFoley** [comment]
Still haven't had time to build an example for this. @marcshilling Were you able to fix the issues you found with this? or for the `...`? I haven't had a chance to look into either yet.

**Comment by marcshilling** [comment]
@MattFoley I have not. The ellipses thing is more of a nice to have feature, but the text not re-rendering is definitely a bug that needs to be fixed. I wouldn't really know where to start...but if it would help I could try to put together an example project that displays it breaking?

**Comment by MattFoley** [comment]
That would definitely be appreciated! :)

**Comment by marcshilling** [comment]
@MattFoley here ya go: https://github.com/marcshilling/react-native-auto-sizing-font-bug

Pull that down, `npm install`. Give it a shot. Note that on a 1 sec delay in `componentDidMount` I set state to change the text and its color. The text never re-renders.

I hope this helps you figure it out and get this fixed!

**Comment by mkonicek** [comment]
This has been imported to the internal Phabricator but not merged yet.

Sorry about the churn @MattFoley, can you try to rebase it please? @nicklockwood do we want to merge this as-is?

**Comment by nicklockwood** [comment]
@mkonicek still working on it. Pieter had some review feedback.

**Comment by mkonicek** [comment]
:+1:

**Comment by MattFoley** [comment]
Going to try really really hard to wrap this up this week

**Comment by mkonicek** [comment]
I think @nicklockwood is still working on it? You might want to wait for an update.

**Comment by MattFoley** [comment]
I've had some requests to make changes to this, I'm going to work on getting those into this PR this week, is what I meant. Is @nicklockwood doing work on top of this as well?

**Comment by MattFoley** [comment]
@marcshilling I saw something tonight that suggests the re-render issue may not be with my code. I'm sorry I haven't had a chance to look into this more yet, but I noticed it tonight while I was building two separate countdowns labels for different screens in an upcoming release.

I was working on iOS 9.2 simulator, with RN 0.18 (with my PR applied on top), Node 5.4. The text nodes were not being re-rendered as I updated the countdown text in my state. I confirmed that the render functions were being called, and the string was changing. Once I set the key of my node to the string I wanted to render it begin redrawing each time. Is it possible that something is being too aggressive on caching DOM elements in the newer versions of RN?

Again, I'll try to come back to this PR soon, but all my focus is going into current work project at Skillz.

**Comment by MattFoley** [comment]
I have a small problem with this, and actually need to fix it elsewhere as well. If I do my resizing on the native/ObjC side, how do I notify RN that the view's size has changed, and that it then needs to relayout the rest of the view? This is a small problem for this PR, but I'm also working on a wrapper for THLabel, and currently it requires a fixed width or RN just lays it out as 0 width.

**Comment by mkonicek** [comment]
cc @nicklockwood

**Comment by MattFoley** [comment]
I was hoping there was some way to communicate directly to the ui manager, rather than firing an event, and setting style value manually.

**Comment by nicklockwood** [comment]
You can call [bridge.uiManager setFrame:forView:] to trigger a layout update. That will automatically call onLayout on the JS side, etc.

**Comment by MattFoley** [comment]
Thanks Nick!

**Comment by marcshilling** [comment]
@MattFoley let me know if that works and hopefully we can get this merged soon!

**Comment by marcshilling** [comment]
@MattFoley any updates here? Been waiting on this to land for soooooo long

**Comment by mkonicek** [comment]
@MattFoley I'm going through all PRs to make sure they are either being worked on or closed. Closing all PRs after a month of inactivity, leaving this one open since it's been 20 days.

**Comment by marcshilling** [comment]
Let's please not let this one get closed! Lot of work done here and this is still a huge missing piece of React Native `Text

**Comment by facebook-github-bot-2** [comment]
@MattFoley do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by mkonicek** [comment]
OK sounds good :+1:

**Comment by facebook-github-bot-6** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by duhduhdan** [comment]
@MattFoley Do you have a laundry list of what needs to happen to finish this up? I cherry picked it and started playing around with it. Would love to help tackle some outstanding tasks to get some momentum back to this feature. Definitely a must have!

**Comment by marcshilling** [comment]
@duhduhdan check out my [comment above](https://github.com/facebook/react-native/pull/4026#issuecomment-169800630). That repo probably isn't a good example anymore since it's 5 months old, but the JS-side of the code illustrates what the issue was at the time (text not re-rendering). Maybe things have changed? But that was the only issue I was seeing back in the day.

**Comment by duhduhdan** [comment]
@marcshilling Awesome, thanks. I'll start applying some brain power to this

**Comment by MattFoley** [comment]
@duhduhdan I've been waiting for someone to ask me that exact question! Part of the reason this has lasted so long is that I didn't feel comfortable finishing this without another outside developer giving it concrete use. The PR here is slightly out of date, but the feature itself is not, we are using it in production here at Skillz and will continue to do so.

You can see an example of our usage in production [here](https://itunes.apple.com/us/app/diamond-strike/id567160401?mt=8). 

Here's my todo list here:
• Find another developer to actually use it, get feedback on the API/functionality.
• Default adjustsFontSizeToFit to true, rather than false as it is right now?
• Fix the text re-rendering issue (for now we just use the key prop to workaround that issue)
• Add "..." truncation when the minimum text scale can't be reached
• Possibly improve binary search, still feels a bit weird for multi-line auto-shrinking.
• Android support? (We're iOS developers here.)

**Comment by duhduhdan** [comment]
@MattFoley Perfect! Thanks for the list. Excited to see this moving forward again!

**Comment by MattFoley** [comment]
Also good to know is that right now when the text shrinks, the frame of the Text node does not, so you can see some strangeness related to text sizing. Haven't figured out a great solution for this yet.

**Comment by MattFoley** [comment]
Another thing, and this is probably not a big issue for most developers on React Native, but due what seems to be an [ancient issue with NSLayoutManager](http://www.cocoabuilder.com/archive/cocoa/197008-how-does-nsbuttoncell-do-its-drawing.html) dating all the way back to OSX, Japanese text is drawn a a bit above the baseline. 

You can see how I use `usedRectForTextContainer` in `calculateSize` in `RCTShadowText`.

**Comment by facebook-github-bot-3** [comment]
@MattFoley updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by facebook-github-bot-8** [comment]
@MattFoley updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by facebook-github-bot-3** [comment]
@MattFoley updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by Hagbarth** [comment]
Hi! Just pinging this to see how this is moving forward?

**Comment by MattFoley** [comment]
@Hagbarth Working on adding a UIExplorer example today, and fix the dynamic text element issue. If I manage to implement both of those today, I'm going to recommend this be merged without the `...` truncation feature.

**Comment by MattFoley** [comment]
I've added a UIExplorer demo to this, and updated it so that the frame of the Text element ends up being drawn at the exact size required (no leftover space after being shrunk).

There is still one minor issue, if an element is shrunk by adding text to it, and then that text is removed, the height of the element will not grow back to it's original height, which leads to the font being stuck at a certain size, or number of lines being lessened.

However, that seems like an edge case, and it turns out that the re-render issue mentioned by @marcshilling is no longer a problem on the latest React Native, so I'm going to suggest this finally be merged in. We're still using it in production just fine.

@ide @nicklockwood @mkonicek I have no idea who's in charge of this now! Sorry it has taken so long!

**Comment by MattFoley** [comment]
I think I caught everything mentioned by eslint-bot, please let me know if I missed something else.

**Comment by MattFoley** [comment]
Rebased on top of master again this morning, so this is once again ready to be merged! :)

**Comment by mkonicek** [comment]
@majak would you mind taking a look please? Just trying to triage impactful PRs, splitting iOS ones between you and Pieter.

**Comment by facebook-github-bot-9** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @rigdern as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by MattFoley** [comment]
I'm on Discord as `teejayF#8027`, please feel free to reach out to me there. I'd like to get this merged in as soon as possible! Thanks! :)

**Comment by MattFoley** [comment]
Still waiting on a review here @majak @mkonicek @rigdern.

**Comment by Mtnt** [comment]
Hi guys! Could I somehow to use it before it`s merged? I really need this feature to use right now =)

**Comment by MattFoley** [comment]
Hi, just another friendly reminder that this still needs a review. @majak Thanks!

**Comment by facebook-github-bot-8** [comment]
@MattFoley updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@MattFoley updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@MattFoley updated the pull request.

**Comment by MattFoley** [comment]
I've rebased this on top of the latest master. The failure in `continuous-integration/travis-ci/pr` doesn't seem to be related to this PR.

**Comment by MattFoley** [comment]
@marcshilling Looks like you've been reviewing and merging in ObjC PRs. Feel good about merging this one in? I've just been bumping this PR and rebasing since June, it feels good to merge to me.

**Comment by marcshilling** [comment]
@MattFoley not me - I don't have merge permissions! I would if I could!

**Comment by MattFoley** [comment]
@marcshilling Thanks Marc, is there anyone else I can poke about this?

**Comment by facebook-github-bot-5** [comment]
@MattFoley updated the pull request.

**Comment by MattFoley** [comment]
Just cleaning up what I think the last thing ESLint bot was complaining about.

**Comment by MattFoley** [comment]
Rebased on top of master again.

**Comment by MattFoley** [comment]
@mkonicek @majak I hate to keep pinging you guys on this, but I'd really like to get this merged in before I do another RN update. Is there anything I can do to help move this along? Thanks!

**Comment by facebook-github-bot-5** [comment]
@MattFoley updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@MattFoley updated the pull request.

**Comment by MattFoley** [comment]
Note, I had to update this PR to fix a failing test due to a previous rebase.

**Comment by paramaggarwal** [comment]
cc: @majak @javache

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@MattFoley thank you SO much for sticking with this for so long. Sorry it took so long to get it merged!

**Comment by facebook-github-bot-4** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D2678492) to review internal test results.

**Comment by marcshilling** [comment]
@skevy @MattFoley 👏👏👏👏

**Comment by MattFoley** [comment]
@skevy Thanks!!!!!!!!!!!!!!!!!!!!!!!!

ps. @brentvatne it happened. 🎉

**Comment by collinglass** [comment]
👏👏👏

**Comment by chandlervdw** [comment]
@MattFoley so, is this available in react-native@0.32 or no? Thanks so much for this!

**Comment by MattFoley** [comment]
It's in .33rc I think, you're welcome!

**Comment by pyankoff** [comment]
Text gets truncated a little bit (maybe because of large font?). Easily solved by adding `style={{marginVertical: 6}}` tho.

**Comment by jasan-s** [comment]
can adjustsFontSizeToFit work with TextInput? On the user input

**Comment by garrettmac** [comment]
You can add `adjustsFontSizeToFit={true}` (currently undocumented) to you `Text` Component to auto adjust the size inside a parent node. 

      <Text adjustsFontSizeToFit={true} numberOfLines={1}>Hiiiz</Text>

You can also add the following in your Text Component:

    <Text style={{textAlignVertical: "center",textAlign: "center",}}>Hiiiz</Text>

Or you can add the following into the parent of the Text component:

    <View style={{flex:1,justifyContent: "center",alignItems: "center"}}>
         <Text>Hiiiz</Text>
    </View>

or both

     <View style={{flex:1,justifyContent: "center",alignItems: "center"}}>
         <Text style={{textAlignVertical: "center",textAlign: "center",}}>Hiiiz</Text>
    </View>

or all three

     <View style={{flex:1,justifyContent: "center",alignItems: "center"}}>
         <Text adjustsFontSizeToFit={true} 
               numberOfLines={1} 
               style={{textAlignVertical: "center",textAlign: "center",}}>Hiiiz</Text>
    </View>

before 
screen shot 2017-07-19 at 9 48 05 am

after

screen shot 2017-07-19 at 9 47 34 am

It all depends on what you're doing. You can also checkout my full blog post on the topic

 https://medium.com/@vygaio/how-to-auto-adjust-text-font-size-to-fit-into-a-nodes-width-in-react-native-9f7d1d68305b

**Comment by mkozhukharenko** [comment]
it does not work for Android in react 47.1 and does not work perfectly for IOS

**Comment by AfiyaA** [comment]
Does this work for Android? It works for me for IOS but need Android support as well.

**Comment by skv-headless** [comment]
I should be doable for android https://react-native.canny.io/feature-requests/p/textandroid-autosizing-support. But I failed to implement it maybe someone more experienced with react-native can do it.

**Comment by cmacdonnacha** [comment]
Would be great to get this on Android too!

**Comment by yurykorzun** [comment]
We desperately need this on Android

**Comment by cmacdonnacha** [comment]
I see this is closed, was it merged in?

**Pull request closed without merging**
