### PR TITLE
Update getting-started.html

### PR DESCRIPTION
**Pull request by kieranju**
Spelling correction.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@kieranju Can you sign the CLA so we can import this? Thanks.

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by JoelMarcey** [comment]
Oh -- you signed it. Good.

**Comment by JoelMarcey** [comment]
You changed the `.html` file. You need to change the `.md` file `QuickStart-GettingStarted.md`.

**Comment by kieranju** [comment]
My bad, I simply spotted the spelling error and attempted to hotfix. Looks like the getting-started documentation has been refactored in the latest stable branch.

**Pull request closed without merging**
