### PR TITLE
added Agendakar and NEF to the showcase apps

### PR DESCRIPTION
**Pull request by hkairi**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

### CODE REVIEW

**Comment by mkonicek** [comment]
@hkairi Can you sign the CLA please? See the comment from the bot above.

**Comment by mkonicek** [comment]
Please add these to `apps`, not `featuredApp` and sort alphabetically.

**Comment by facebook-github-bot-4** [comment]
@hkairi do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by lacker** [comment]
Hey, I'm really sorry for the churn, but we are changing up how the showcase works, and just focusing on apps that have some media presence or technical blog posts / other content. So I appreciate the spirit behind this pull request but I think we should close it.

**Pull request closed without merging**
