### PR TITLE
[iOS] Initial UIKitForMac support

### PR DESCRIPTION
**Pull request by radex**
## Summary

This PR adds initial support for Project Catalyst a.k.a. UIKitForMac. This is not yet meant for production, but this is enough for RNTester to successfully compile and mostly work :)

Some APIs are not supported on the Mac -- e.g. telephony, and deprecated APIs are removed on Mac -- those had to be ifdef'd out via platform checks.

The biggest limitation right now is that I couldn't get Web Socket code to successfully compile, and so there are a lot of temporary platform checks  for that , and the RCTWebSocket.xcodeproj is marked as not supporting UIKitForMac. Again -- temporary, until someone with more knowledge knows how to fix this.

https://github.com/react-native-community/discussions-and-proposals/issues/131

## Changelog

[iOS] [Added] - Fixed compilation for macOS (Project Catalyst) -- not meant for production use yet

## Test Plan

- Open RNTester/RNTester.xcodeproj with Xcode 10.2, run it like a normal iOS app -- make sure it compiles and runs correctly (no regression)
- Open the same project with Xcode 11 beta 2 (or higher) on macOS Catalina beta, select "My Mac" as device target, and run -- see that it actually compiles and runs. **Note** there are unfortunately some required steps:
   - change build configuration to Release (because packager doesn't work correctly yet)
   - change development team to yours if Xcode tells you to
   - go to RNTester project → Build phases → Link binary with libraries, and change `platforms` for `libRCTWebSocket.a` to `iOS` (without Mac compatibility). I can't commit that change because it breaks compatibility with earlier Xcode versions

The two extra steps for successful compile will disappear once web socket compilation for Catalyst is fixed

### CODE REVIEW

**Comment by radex** [comment]
Screenshot 2019-06-28 at 14 21 04

It compiles!

**Comment by LukasBombach** [comment]
Does this mean we can write macOS apps **today**? How would you go about and do this (couldn't find any docs on this)?

**Comment by radex** [comment]
@LukasBombach There are no docs. Feel free to contribute!

**Comment by LukasBombach** [comment]
@radex thank you. but is it at all possible? if so, I can figure out how and try and add some docs

**Comment by radex** [comment]
@LukasBombach kinda, but also not really -- it requires more work to work well. you can compile it, and it runs, but it looks all wrong and auto-reload doesn't work

**Comment by LukasBombach** [comment]
Ah ok, not sure I have the time to fix that. I'd leave that to someone else then or maybe me even future-me. Thanks!

**Comment by joevo2** [comment]
Any updates on this? Can I actually build mac catalyst app using RN now?

**Comment by tonycoco** [comment]
Yes.

**Comment by LukasBombach** [comment]
Awesome! Do you know _how_ thought? Because I could not find anything no this.

**Comment by tonycoco** [comment]
Select the macOS target in Xcode when building...



See: https://github.com/react-native-community/discussions-and-proposals/issues/131

**Comment by LukasBombach** [comment]
Oh awesome! Thank you!

**Pull request closed without merging**
