### PR TITLE
fix minor grammar and typo errors in comments

### PR DESCRIPTION
**Pull request by ultralame**
comments only. no code modified.

### CODE REVIEW

**Comment by ide** [comment]
@ultralame you'll have to sign the CLA before this PR can be merged.

**Comment by ultralame** [comment]
is this all set to merge? if there's a problem feel free to close. loving RN so far, thanks for all you do! ^_^

**Comment by brentvatne** [comment]
@ultralame - yup just need to wait for it to be pulled into a sync

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
