### PR TITLE
Fix issue #21065 getInspectorDataForViewTag is not a function

### LINKED ISSUE #21065: [React-native 0.56] [Toggle Inspector] renderer.getInspectorDataForViewTag is not a function
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
      Memory: 613.02 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.1.0 - ~/.nvm/versions/node/v9.1.0/bin/node
      npm: 5.5.1 - ~/.nvm/versions/node/v9.1.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.2
      react-native: ^0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-git-upgrade: 0.2.7
```

## Description
After upgrate RN to 0.56, I'm try Toggle Inspector but that below error occur when I click anywhere in screen
simulator screen shot - iphone 7 - 2018-09-12 at 17 35 21

### PR DESCRIPTION
**Pull request by TranLuongTuanAnh**
Fix renderer.getInspectorDataForViewTag is not a function when try Toggle Inspector

Fixes #21065

Release Notes:
--------------
[BUGFIX] [MINOR] [/react-native/Libraries/Inspector/Inspector.js]

### CODE REVIEW

**Comment by hramos** [comment]
Would you mind adding a test plan to your PR?

**Comment by cpojer** [comment]
@TranLuongTuanAnh thank you for your PR. Unfortunately, there is no explanation for this pull request in terms of how to reproduce this issue and what it actually fixes. Since there hasn't been a reply in more than a month. I'm going to close this PR, but I am happy to reopen and land it if you can add the information back.

**Comment by th317erd** [comment]
This should be reopened. See here: https://github.com/facebook/react-native/issues/21065

**Comment by th317erd** [comment]
No @hramos, this PR is fine, and just needs to be reopened. If you need another PR request from the author just ask. Besides, it peeves me greatly to try and follow Facebook's stringent and ridiculous "Community Guidelines". They essentially bitch-slap their community members all the time by closing PRs, closing and locking legitimate bug requests, being rude, and generally having the all around "don't give a shit about our community" attitude. I am not eager to help out the Facebook community because of this, and because nearly every interaction I have had with one of their developers has been a negative experience. If they don't want the help from the community (that IMHO is blatantly obvious through their actions and attitude), that is Facebook's problem, not mine. Sorry, normally with any other community I would be happy to help, not this time.

**Comment by cpojer** [comment]
Thanks for the quick turnaround. Landing this issue now.

**Comment by th317erd** [comment]
Thank you @cpojer!

**Comment by tkow** [comment]
Is any progress?

**Pull request closed without merging**
