### PR TITLE
[Packager] Fix transforming when ast is not available

### PR DESCRIPTION
**Pull request by gitim**
Fixes https://github.com/facebook/react-native/issues/12071. I found that [babel.transform](https://github.com/facebook/react-native/blob/master/packager/transformer.js#L109) does not generate ast for files from babelrc' ignore list, so [babel-generator](https://github.com/facebook/react-native/blob/master/packager/transformer.js#L110) fails. I don't know the best way to handle such files, so I restored logic that was used before https://github.com/facebook/react-native/commit/0849f84df26e4c56f5763375363bae90d94015fe for files without ast.

### CODE REVIEW

**Comment by gitim** [comment]
cc @davidaurelio

**Comment by gitim** [comment]
Looks that this issue solved in 0.41.2

**Comment by ruiaraujo** [comment]
@gitim @davidaurelio This is still happening on 0.42 and I have verified that this PR fixes the issue.

**Comment by dkpalmer** [comment]
Verified same as @ruiaraujo, 0.42.0rc3

**Pull request closed without merging**
