### PR TITLE
[CLI] Options parsing, add support for --version

### PR DESCRIPTION
**Pull request by pedro**
- Using commander to parse command line options so it's a bit more declarative/extensible
- Support for `react-native --version`

### CODE REVIEW

**Comment by vjeux** [comment]
Looks good to me, @frantic what do you think?

**Comment by gaearon** [comment]
Commander wasn't a nice option for Babel:

https://github.com/babel/babel/issues/836#issuecomment-75135408
https://github.com/babel/babel/issues/756#issuecomment-74286864

**Comment by frantic** [comment]
@pedro why commander? Did you consider any alternatives?

**Comment by pedro** [comment]
Interesting – I just went with Commander because of the nice interface and how it wraps stuff like the help view. Looked at [minimist](https://github.com/substack/minimist) too, but it's pretty raw so we'd still have to do validation/help screen/etc.

And just found [argparse](https://github.com/nodeca/argparse), thoughts on it?

**Comment by brentvatne** [comment]
ping @frantic

**Comment by frantic** [comment]
We already use `optimist` in RN, can we use it for this as well for consistency?

**Comment by pedro** [comment]
For sure, sounds good! I'll bring it in in another pull.
Thanks folks!

**Comment by frantic** [comment]
:cool: Also note there is #1125 that is likely to be merged in

**Pull request closed without merging**
