### PR TITLE
Don't create long paths during build to avoid failures on Windows

### PR DESCRIPTION
**Pull request by alespergl**
## Summary

When building Android C++ targets on Windows the generated output paths can be over the MAX_PATH limit of 260 characters causing build errors. This is due to the fact that when `$(wildcard)` is used to generate a list of input files it produces absolute paths. Those are then processed to replace special characters, and appended to the build target's output root which creates an unnecessarily long path for each output file.

This change converts the absolute input paths to relative paths by stripping the `LOCAL_PATH` portion used to generate them.

## Changelog

[Android] [Fixed] - Improved build on Windows by avoiding failures due to long output paths

## Test Plan

n/a

### CODE REVIEW

**Comment by kelset** [comment]
@cortinico @mganandraj wouldn't this address the Windows+Android issue?

**Comment by mganandraj** [comment]
> 

This might help .. I actually tried explicitly listing file names in one project and it made a difference .. but this approach of replacing the prefix after enumerating the files through wild card  is neater..

**Comment by mganandraj** [comment]
@alespergl This change will won't have any effect on main branch which has switched to cmake .. but it would be very useful change in 0.68-stable branch.. We have issues especially with newarchitecuture enabled, as the fabric code hierarchy is even deeper.. I would appreciate if you could test building on Windows with newarchitecuture enabled in 0.68-stable branch, which might require fixing a lot more makefiles !!

**Comment by kelset** [comment]
so just to be clear, it'd be probably better if Ales rebased this PR on top of the 0.68-stable branch and re-targetted this PR to it right?

**Comment by mganandraj** [comment]
> 



> 

Yes, even better build with newArchitecuture turned on.

**Comment by mganandraj** [comment]
I extended this change to add all the new modules and created a PR against 0.68-stable branch : https://github.com/facebook/react-native/pull/33707

The change is verified on a ~10 character long host applications path .. And it allows us to revert the ndk bump. Actually ndk23 is frequently crashing ! which i'll continue investigating ..

**Comment by alespergl** [comment]
@mganandraj Thanks for taking this and porting it to the 0.68 branch. Normally I would suggest to just update this PR but since you already created a new one I'll wait for that to be completed and then this one can be withdrawn. Not sure if it makes sense to merge it to the original 0.66 since then it would be missing in 0.67.

**Comment by cortinico** [comment]
Thanks for sending this over @alespergl.
Sorry it took so long to review/merge but we wanted to verify this was effectively fixing the issue. I've left a comment on https://github.com/facebook/react-native/pull/33707 to explain what are the next steps.

We anyway need to backport that PR to main as well, as we'll have to include this fix inside `react-native-codegen` regardless.

**Comment by cortinico** [comment]
Closing as the fixes for long paths on Windows already landed and are available on 0.69+ which are the supported versions of React Native at the time of writing.

**Pull request closed without merging**
