### PR TITLE
refactor: use ESM exports in ReactNativeViewConfigRegistry

### PR DESCRIPTION
**Pull request by jbroma**
## Summary:

When transpiling `react-native` with `swc` this file caused some trouble as it mixes ESM and CJS import/export syntax. This PR addresses this by converting CJS exports to ESM exports. All other affected files were aligned to support this change.
## Changelog:

[INTERNAL] [CHANGED] - use ESM exports in ReactNativeViewConfigRegistry

### CODE REVIEW

**Comment by javache** [comment]
The source of truth for ReactNativeViewConfigRegistry is actually in React, and gets synced as part of React releases to React Native - https://github.com/facebook/react/blob/main/scripts/rollup/shims/react-native/ReactNativeViewConfigRegistry.js

**Comment by jbroma** [comment]
@javache ok, I will make open the PR in React then.

**Comment by jbroma** [comment]
@javache considering how these files are linked through the sync script, is there going to be an option to sync just this change? I've noticed there is a ton of changes related to server components that would get synced and that's definitely not desirable. How do you see this PR going forward? Thanks!

**Comment by javache** [comment]
> @javache considering how these files are linked through the sync script, is there going to be an option to sync just this change? I've noticed there is a ton of changes related to server components that would get synced and that's definitely not desirable. How do you see this PR going forward? Thanks!

Just this change will be synced. We only update the renderer as part of a React npm release.

**Comment by jbroma** [comment]
I've added a PR in 'react': https://github.com/facebook/react/pull/27508

I've also removed changes to ReactNativeViewConfigRegistry as it will be synced.

**Comment by javache** [comment]
Merged the React PR, it should land here in the next few days, please rebase on top of that.

**Pull request closed without merging**
