### PR TITLE
Convert Image resizeMode `contain` to FIT_CENTER

### PR DESCRIPTION
**Pull request by cosmith**
Convert from `CENTER_INSIDE` to `FIT_CENTER`.
The difference between those is that `CENTER_INSIDE` will not upscale if the image is too small.
See the Fresco docs: http://frescolib.org/javadoc/reference/com/facebook/drawee/drawable/ScalingUtils.ScaleType.html

Original issue: https://github.com/facebook/react-native/issues/4031

### CODE REVIEW

**Comment by cosmith** [comment]
I'm not sure about this: https://github.com/facebook/react-native/blob/cc449b394e9cd3300343016a5d6a3c924823cd2b/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModuleConstants.java#L91

Does anyone know what those constants are used for?

**Comment by mkonicek** [comment]
Those constants can be read from JS, not sure what `ContentMode` itself is used for.

**Comment by cosmith** [comment]
It doesn't look like they are used anywhere in the codebase: https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=ScaleAspectFit but I should still probably update it.

**Comment by christopherdro** [comment]
Just gave this PR a try an am still getting a white screen when setting resizeMode to "contain".

For some strange reason if I set some arbitrary value for the images height and width, it works as "contain" should. However, if I use `Dimensions` to set it to the window's height and width, the image render stretched out unproportional to the viewport.

**Comment by cosmith** [comment]
Hi @christopherdro, it works as expected for me even when using `Dimensions` to set the width/height.

Before (current master):

screenshot-2016-02-09t12 05 06

After:
screenshot-2016-02-09t12 06 32

With `Dimensions`:
screenshot-2016-02-09t12 14 45



Notice that `stretch` is broken on `master`...

**Comment by christopherdro** [comment]
@cosmith I'll give it another shot later today.

**Comment by AlexErofeev** [comment]
Thank you for this fix! Eagerly waiting for it to appear in mainstream :)

**Comment by nicklockwood** [comment]
cc: @dmmiller

**Comment by mkonicek** [comment]
Thanks for the screenshots and sorry for the delay. From the [docs](https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageResizeMode.js) it's not actually clear what happens if the image is smaller than the view:

    /**
     * contain - The image will be resized such that it will be completely
     * visible, contained within the frame of the View.
     */

But since this is the iOS behavior, let's ship it. Can you please rebase so we can merge this? If you can update the docs too to explain what happens with images smaller than the view, that would be amazing. I think the other two cases are clear.

**Comment by mkonicek** [comment]
And weird that 'stretch' is so broken! Are we passing a wrong constant there too?

**Comment by mkonicek** [comment]
It looks like "This branch is out-of-date with the base branch" is reported on all PRs now, maybe because we made the master branch protected. Let's try to ship it:

@facebook-github-bot shipit

**Comment by farwayer** [comment]
Nice! I remember there were many problems with image scaling in Titanium Mobile several years ago. So be care with it. It's very often used functionality. And don't forget to add note to changelog cos it's backward incompatible change.

**Comment by mkonicek** [comment]
Retrying the merge to the internal Mercurial codebase.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by holyxiaoxin** [comment]
There seem to be an issue when I'm trying to use `resizeMode="contain"`.

When I didn't specify `resizeMode="contain"`, the image was 
image


However, after specifying `resizeMode="contain"`, the image took on a smaller size.
image

Even after specifying a width and height, the image still remains small(same size as picture) and does not fill the width/height of the given style.

**Comment by holyxiaoxin** [comment]
And to add on, this is only an issue with Android. I tested on IOS and it works fine.

**Comment by cosmith** [comment]
Hi @holyxiaoxin this will only land in 0.23 I think, what you're seeing is the bug that this PR fixes. @mkonicek and @knowbody I think this should be in the release notes for 0.23? I don't see it there https://github.com/facebook/react-native/releases/tag/v0.23.0-rc1 .

**Comment by knowbody** [comment]
thank you, will add it

**Pull request closed without merging**
