### PR TITLE
resolve this issue by default

### PR DESCRIPTION
**Pull request by xyx2011**
https://github.com/facebook/react-native/issues/15049

(Write your motivation here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

### CODE REVIEW

**Comment by javache** [comment]
Please update the instructions to use the CxxBridge subspec, as BatchedBridge is deprecated.

**Comment by GingerBear** [comment]
@javache I am trying to integrate react-native@0.48.3 into Objective-C project by following the guide. And when I do `pod install` with `CxxBridge` in subspec, I get error:

screen shot 2017-09-20 at 4 05 24 pm

However, if I use `BatchedBridge` instead, everything runs fine.

**Comment by javache** [comment]
@GingerBear Is node_modules/react-native/third-party-podspecs/Folly.podspec in your node_modules folder?

**Comment by javache** [comment]
@xyx2011: you'll need to sign the CLA to have this be merged.

**Comment by GingerBear** [comment]
@javache yes, Folly.podspec is there

**Comment by javache** [comment]
Fixed in react-native-website: https://github.com/facebook/react-native-website/blob/master/docs/integration-with-existing-apps.md

**Comment by AWDGroup** [comment]
@javache Still missing for Objective-C
I just created a PR
https://github.com/facebook/react-native-website/pull/103

**Pull request closed without merging**
