### PR TITLE
Fix documentation inconsistancy with flexbox alignItems default value

### PR DESCRIPTION
**Pull request by gmuraleekrishna**
As per mozilla docs alignItems already has made `stretch` as default
value

https://developer.mozilla.org/en-US/docs/Web/CSS/align-items. 

This resolves issue https://github.com/facebook/react-native/issues/8920

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by gmuraleekrishna** [comment]
This PL resolves #9397

**Comment by ide** [comment]
Can you mention that stretch is the default? That seems more important to me than "like CSS" although both pieces of information are helpful.

**Comment by facebook-github-bot-9** [comment]
@gmuraleekrishna updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@gmuraleekrishna updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@gmuraleekrishna updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@gmuraleekrishna updated the pull request.

**Comment by ide** [comment]
This looks great!

@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3718410) to review internal test results.

**Pull request closed without merging**
