### PR TITLE
[Android] Added size information for webviews

### PR DESCRIPTION
**Pull request by KingHUBIYIN**
look for [#1358](https://github.com/facebook/react-native/pull/1358)

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @mkonicek as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by lacker** [comment]
I think according to the discussion in https://github.com/facebook/react-native/pull/1358 people concluded this wasn't the right way to do it, because it hurts performance with a reflow. I'm going to close this but feel free to reopen if I am misinterpreting the consensus here.

**Pull request closed without merging**
