### PR TITLE
More information about boilerplate `ios`ing

### PR DESCRIPTION
**Pull request by michaelghinrichs**
Hello wonderful React Native people!

I am proposing this change because it took me a frustratingly long time to see why my `component` wasn't rendering any children.
I feel like something like this would have helped me.

However, I may be an edge case as my first attempt at any React Native was doing a Navigator...

Your call! This is my feedback!

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @katrinanova to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by janicduplessis** [comment]
What about we just set `NavigatorIOS` to have `{flex: 1}` by default. It doesn't really make sense to have a non-fullscreen navigator and we already do that for some components like `ScrollView` for example https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L476.

cc @mkonicek

**Comment by michaelghinrichs** [comment]
That would be even better and wouldn't pollute the readme with tangential info :) 

My vote is for this to be a default setting on NavigatorIOS!

Thanks for such a speedy response :)

**Comment by mkonicek** [comment]
Setting `flex: 1` by default seems reasonable. Can you update this PR or close this and send a new one please?

**Comment by michaelghinrichs** [comment]
Sounds good @mkonicek :)

So, adding a `flex: 1` to [here](https://github.com/facebook/react-native/blob/master/Libraries/Components/Navigation/NavigatorIOS.ios.js#L706)? 

Is what needs to be done? Will get right on it!

**Comment by janicduplessis** [comment]
It's probably on this view: https://github.com/facebook/react-native/blob/master/Libraries/Components/Navigation/NavigatorIOS.ios.js#L698

**Pull request closed without merging**
