### PR TITLE
Modification of the method "replaceAtIndex" in Navigator.js to allow adding new routes to the end and creation of new method "removeAtIndex"

### PR DESCRIPTION
**Pull request by PhilippKrone**
# replaceAtIndex
### Old behavior:
* if specified index is smaller than currentRouteStack.length, it will replace existing route
* if specified index is equal to currentRouteStack.length, it will return
* if index is larger than currentRouteStack.length, it will return

### New behaior:
* if specified index is smaller than currentRouteStack.length, it will replace existing route
* **if specified index is equal to currentRouteStack.length, it will add a new route to the end of the routeStack**
* if index is larger than currentRouteStack.length, it will return

### Test:
* Used the following app for testing: https://rnplay.org/apps/cm53mA/

# removeAtIndex
* added new method "removeAtIndex" which deletes a route from the routeStack specified by its current index

### CODE REVIEW

**Comment by ericvicenti** [comment]
I think the change to `replaceAtIndex` looks totally reasonable.

I'm a bit concerned about `removeAtIndex`, mostly because I want to keep complexity down right now, and this will expose us to more edge cases. Do you have a strong use case for the new method?

It will be easier to commit the `replaceAtIndex` change in a separate PR from `removeAtIndex`

**Comment by PhilippKrone** [comment]
Hi,

I currently have a scenario in which I need to remove routes from the routeStack without being able to use pop - especially after adding them via the new replaceAtIndex method.

Basically IMO its the counterpart to the (new) replaceAtIndex method and would thus make sense to exist as well.

Anyway, I can make two PRs out of it, but Id prefer to handle any edge cases you can think of in the remiveAtIndex method. :)

**Comment by PhilippKrone** [comment]
Especially because i cant use popToRoute() as this will remove ALL routes between the route i come from and the target route and not only the route I come from.

**Comment by ericvicenti** [comment]
@hedgerwang, any thoughts on this?

**Comment by hedgerwang** [comment]
@PhilippKrone: there are some edge cases such as the nagative index used and it matches no route.

In the new API that we're working on, the index has to be a valid index that must match a route in the stack otherwise it will throw an "IndexOutOfBound" Error.

By default, we don't want to make the navigation too tolerant with navigation error (e.g. invalid index, invalid route, ...etc). However developer can escape  the navigation errors easily by using the default API to do that.

For instance, your case can do done via something like this:

```
class Example extends React.Component {
  doAction(route, index) {

    var navigationContext = this.context.navigationContext;
    var maxIndex = navigationContext.routeStack.size - 1;
    if (index === maxIndex) {
      // if the specified index is equal to currentRouteStack.length, 
      // it will add a new route to the end of the routeStack
      navigationContext.push(route);
      return;
    }

    if (index <= maxIndex) {
      // if specified index is smaller than currentRouteStack.length, 
      // it will replace existing route
      navigationContext.replaceAtIndex(route, index);
      return;
    }    
  }
}

```

Alternatively, we're building an event system that shall allow you to implement the same behavior with something like this:

```
class Example extends React.Component {
  componentDidMount() {
    this.context.navigationContext.addListener(
      'action', 
      this._onNavigationAction
    );
  }

  _onNavigationAction(event: NavigationEvent) {
    if (event.data.action !== 'replace') {
      return;
    } 

    if (event.target !== this.context.navigationContext) {
      return;
    }
    
    var navigationContext = event.target;
    var index = event.data.index;
    
    if (index >= navigationContext.stack.size) {
      // stop the `replace` action.
      event.preventDefault();
    }

    if (index === navigationContext.stack.size) {
      // if specified index is equal to currentRouteStack.length, it will add a 
      // new route to the end of the routeStack
      // this shall emit another event loop for the action `push`.
      navigationContext.push(event.data.route);
      return;
    }  
  }

  doAction(route, index) {
    // this shall emit an event loop for the action `replace`.
    this.context.navigationContext.replaceAtIndex(route, index);    
  }
}
```

Note that different people may want to build different navigation system that 
behaves differently, and we should enable people to do that instead of forcing
people to adapt to only one type of behavior.

**Comment by PhilippKrone** [comment]
@hedgerwang thanks for your reply. The new API looks really good, looking forward to that. However, I'm currently unable to see the connection to the new methods I have written. Basically those two new (one new and one modified) methods give you the possibility to add and remove new routes to a route stack, which will - as far as I understand your code examples - not be possible with the new API as well. 

What I basically need is to be able to modify the route stack without doing any kind of transitions, including adding and removing routes. The way I tried to code the new methods is exactly to allow:

> Note that different people may want to build different navigation system that 
behaves differently, and we should enable people to do that instead of forcing
people to adapt to only one type of behavior.

so that everyone can use them the way they need it for their navigation behaviour. Up to now, there are some things that are not possible with the current implementation (as e.g. easily adding / removing routes without transition, and some other things).

Concerning the negative indizes: I can gladly remove that from the coding, I was just adding it out of consistency reasons with the other methods. I've never used it to be honest. :)

**Comment by PhilippKrone** [comment]
@ericvicenti @hedgerwang How shall we continue here? :)

**Comment by hedgerwang** [comment]
@PhilippKrone :


*If specified index is equal to currentRouteStack.length, it will add a new route to the end of the routeStack*

My concern is that we'll break your code by throwing IndexOutOfBound Error in the upcoming version.

IMHO, it's safer to write a helper function that handles this type of customization separately:

For instance:

```
// make your own navigation logic here.
function replaceAtIndex(navigator, route, index) {
  var length = navigator.getCurrentRoutes().length;
  if (index === length) {
    navigator.push(route);
  } else if (index < length) {
    navigator.replaceAtIndex(route, index);    
  }
}
```

**Comment by PhilippKrone** [comment]
@hedgerwang I get that, but the point is that your and my code have a different functionality: My code adds something to the routeStack without transitioning to it. Same with removing from routeStack without having a transition (nor a scene change). Contrary to that, your code (using push()) automatically transitions towards the new scene - what I dont want. Currently, there is no way to manipulate the routeStack (except replacing existing routes) without triggering an active route change. I'm adding this functionality with my PR. 

Concerning breaking my code by throwing IndexOurOfBound errors: perhaps then we should add a function "addSceneToRouteStack" which adds to the end of the routeStack and which does not trigger the "IndexOutOfBound" error?

**Comment by nikhilaravi** [comment]
@hedgerwang with `navigator.push` the route is being added to the route stack after the active route, not at the end of the route stack: 

https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L908-L912 

```   js
var activeLength = this.state.presentedIndex + 1;
    var activeStack = this.state.routeStack.slice(0, activeLength);
    var activeAnimationConfigStack = this.state.sceneConfigStack.slice(0, activeLength);
    var nextStack = activeStack.concat([route]);
```

Routes in the route stack after the current active route are deleted. 

Is there a way of adding a route to the end of the route stack without @PhilippKrone 's solution?

**Comment by hedgerwang** [comment]
@PhilippKrone : Would  `navigagtor.immediatelyResetRouteStack` help?

```
// adds something to the routeStack without transitioning to it. 
var routes = navigagtor.getCurrentRoutes();
var index = routes.indexOf(navigator.getNavigationContext().currentRoute);
routes.push(route); 
navigagtor.immediatelyResetRouteStack(routes);
navigatro.jumpTo(index);
```

**Comment by nikhilaravi** [comment]
@hedgerwang I get an error that `navigator.getNavigationContext()` is not a function.

**Comment by hedgerwang** [comment]
@nikhilaravi 

Sorry I forgot that `navigator.getNavigationContext` isn't a valid public API yet.
Please use `navigator.navigationContext` instead.

**Comment by facebook-github-bot-9** [comment]
@hedgerwang would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by hedgerwang** [comment]
@ericvicenti : this PR looks reasonable to me. We can accept it.

**Comment by hedgerwang** [comment]
@PhilippKrone : this PR has some conflicts. could you please update your PR? thanks.

**Comment by mkonicek** [comment]
In this case, I believe the navigator is getting deprecated in favor of NavigationExperimental, would it make sense to make the changes there?

**Comment by facebook-github-bot-8** [comment]
@PhilippKrone do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by javache** [comment]
This pull request hasn't seen activity in a while. If you still want to merge this, please open a new pull request.

**Pull request closed without merging**
