### PR TITLE
Website improvements

### PR DESCRIPTION
**Pull request by zpao**
- Quick fix for responsiveness
- Optimized images (shave off ~40% of bytes)
- Don't link to `#content` (feels really bad on mobile)

### CODE REVIEW

**Comment by zpao** [comment]
Well, I set the size wrong for that breakpoint image AND I forgot about retina displays, so it's blurry...

**Comment by amasad** [comment]
Does this fix the horizontal scroll on mobile?

**Comment by zpao** [comment]
Almost, need to also set overflow: auto on .prism (code).

I'm going to drop the image resizing and just optim them and add the prism fix.

**Comment by amasad** [comment]
(y)

**Comment by zpao** [comment]
Alright, all better.

screen shot 2015-03-26 at 11 51 23 am

**Pull request merged**
