### PR TITLE
feat: add initialProps property to RCTAppDelegate

### PR DESCRIPTION
**Pull request by jblarriviere**
## Summary

Hi there, 

While upgrading to 0.71 we realised the RCTAppDelegate doesn't offer a way to set custom `initProps` that would depend on `launchOptions`. 

This PR adds an `initialProps` property to the RCTAppDelegate. This would let us set this property based on `launchOptions` in our implementation of `didFinishLaunchingWithOptions` before calling `[super didFinishLaunchingWithOptions]`

Thanks !

## Changelog

[IOS] [ADDED] - Add `initialProps` property to `RCTAppDelegate`

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
It looks good to me. I'm wondering how we can let users know about this. With this change only, it will be hidden in the AppDelegate library. 🤔 
How do you feel about modifying the template adding something, like:

```diff
 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"HelloWorld";
+  // You can add your custom initial props in the dictionary below.
+  // They will be passed down to the ViewController used by React Native.
+  self.initialProps = @{}; 
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

In this way we will also teach our users how to use this new property.

**Comment by jblarriviere** [comment]
> It looks good to me. I'm wondering how we can let users know about this. With this change only, it will be hidden in the AppDelegate library. 🤔 How do you feel about modifying the template adding something, like:
> 
> ```diff
>  - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   self.moduleName = @"HelloWorld";
> +  // You can add your custom initial props in the dictionary below.
> +  // They will be passed down to the ViewController used by React Native.
> +  self.initialProps = @{}; 
>   return [super application:application didFinishLaunchingWithOptions:launchOptions];
> }
> ```
> 
> In this way we will also teach our users how to use this new property.

Thanks for your feedback. That sounds like a good way to let users know, I've added the comment you suggested .

**Review by cipolleschi — APPROVED** [review]

**Comment by codemickey78** [comment]
Screenshot 2023-01-29 at 5 37 52 PM

I get this error in my AppDelegate file 
`Property 'initialProps' not found on object of type 'AppDelegate *'` 
When I comment it out it works buh some assets like fonts don't apply to the app.
Any solution for this issue

**Comment by jblarriviere** [comment]
> I get this error in my AppDelegate file `Property 'initialProps' not found on object of type 'AppDelegate *'` When I comment it out it works buh some assets like fonts don't apply to the app. Any solution for this issue

Are you using the 0.71.1 ? This PR is not available in previous versions

**Comment by cipolleschi** [comment]
@codemickey78 if you are updating from a previous version of React Native, make sure that your AppDelegate extends `RCTAppDelegat`. If you followed the upgrade helper, you may have modified the `AppDelegate.mm` file but forgot to update the `AppDelegate.h` file.

**Pull request closed without merging**
