### PR TITLE
Fixed broken links by adding missing ')'

### PR DESCRIPTION
**Pull request by artemyarulin**
Just a docs fix

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @mtunique to be potential reviewers.

**Comment by JoelMarcey** [comment]
@artemyarulin Hi. Please have this pull request target `master` instead of a release branch as stated in the `CONTRIBUTING.md` guidelines. Thank you.

**Comment by artemyarulin** [comment]
Oh, I'm sorry - just noticed the error in the docs and pressed "Edit on Github button". I'll create a new PR

**Comment by JoelMarcey** [comment]
@artemyarulin Yeah. Sorry. The `Edit on GitHub` link should be fixed to point to `master` by default. The PR for that has landed in `master` and `0.31-stable`, but hasn't gone live in the latter yet.

cc: @grabbou @hramos

**Pull request closed without merging**
