### PR TITLE
[General] [Removed] - remove accessibilityComponentType and accessibilityTraits props (a11y)

### PR DESCRIPTION
**Pull request by elucaswork**
## Summary

Closes: https://github.com/facebook/react-native/issues/24016

React Native 0.57 introduced cross-platform `accessibilityRole` and `accessibilityStates` props in order to replace `accessibilityComponentType` (for android) and `accessibilityTraits` (for iOS). With #24095 `accessibilityRole` and `accessibilityStates` will increase, receiving more options, which seems to be a good moment to remove deprecated props.

## Changelog

Remove deprecated `accessibilityComponentType` and `accessibilityTraits` props. 

[General] [Removed] - Remove accessibilityComponentType and accessibilityTraits props

## Test Plan

Create a view with old props: 

```
<View
  accessible={true} 
  accessibilityComponentType="button"
  accessibilityTraits="button">...
</View>
```
Neither VoiceOver nor TalkBack should announce this element as "button".

Documentation update PR: https://github.com/facebook/react-native-website/pull/873

**Further work**: Remove props from Fabric in a separate PR

cc @marcmulcahy @jessebeach

### CODE REVIEW

**Comment by cpojer** [comment]
Let me see what happens when I import this to FB. It may take some work to migrate internally before we can land this.

**Comment by cpojer** [comment]
Did all the necessary work at FB, so just waiting until the diff lands (currently some internal build failure unrelated to this). Thanks for sending a PR removing code, those count triple in my book! :)

**Comment by elucaswork** [comment]
@cpojer nice. I'm going to remove those props also in Fabric code. In case the internal failure gets fixed before I remove it, do you mind to hold off the merge? My plan is to do it between today and tomorrow.

**Comment by cpojer** [comment]
Do you mind doing that in a separate PR? :)

**Comment by elucaswork** [comment]
@cpojer sure. I can do it in a separate PR 👍

**Pull request closed without merging**
