### PR TITLE
Add BallisticsARC to the showcase

### PR DESCRIPTION
**Pull request by rdixonbhw**
This adds [BallisticsARC](https://thebhwgroup.com/projects/geoballistics) to the showcase.

### CODE REVIEW

**Comment by hramos** [comment]
I'm going to hold off on merging this as we are about to land #10243 which will conflict with this.

In the meantime, I want to make sure this addition meets the Showcase requirements. Is there any news article or other source you can share that shows this is a funded startup?

**Comment by hramos** [comment]
Thanks for sending this pull request. According to the guidelines in that file, "infoLink" must be one of:

 1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native

I am going to close this, but if you have one of those two things, feel free to reopen with a new link.

**Comment by rdixonbhw** [comment]
Sorry, does public company mean it needs to be publicly traded?

**Comment by hramos** [comment]
Yes.

**Pull request closed without merging**
