### PR TITLE
Update NativeComponentsIOS.md

### PR DESCRIPTION
**Pull request by CoderGLM**
RCTMap is not available yet when I code this line `RCT_CUSTOM_VIEW_PROPERTY(region, MKCoordinateRegion, RCTMap)`, so changing `RCTMap` to `MKMapView` does work well.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @jeanregisser and @sebmarkbage to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by javache** [comment]
For that code example to work, you'd need to import the [RCTMap header file](https://github.com/facebook/react-native/blob/master/React/Views/RCTMap.h). The code is not meant to be copy-pasted but to understand how this works in context.

**Pull request closed without merging**
