### PR TITLE
fix(ios): line break mode property added for iOS

### PR DESCRIPTION
**Pull request by shubhamguptadream11**
## Summary:

Solves this issue: https://github.com/facebook/react-native/issues/44107

## Changelog:

[IOS] [ADDED] - Line break mode for TextInput components

## Test Plan:

- Test it does not affect existing text components when set default(none) strategy.
- Tested all the modes: `'wordWrapping' | 'char' | 'clip' | 'head' | 'middle' | 'tail'`.
- Tested it wouldn't affect TextInput if not provided lineBreakMode.
- Written test case with these props.

### CODE REVIEW

**Comment by shubhamguptadream11** [comment]
@cortinico @cipolleschi 
I understand the current focus is on New Architecture specific bugs. This fixes the issue coming in old and new arch both. Whenever you have some time, I would really appreciate it if you could review this PR. No rush at all—please review it whenever it's convenient for you. Thanks again!

**Comment by ecreeth** [comment]
Why not `lineBreakMode`?

**Comment by shubhamguptadream11** [comment]
@ecreeth This is iOS specific props. I followed convention from existing props: `lineBreakStrategyIOS`

**Comment by ecreeth** [comment]
> @ecreeth This is iOS specific props. I followed convention from existing props: `lineBreakStrategyIOS`

I know, the think is that there's other props without this IOS suffix that are platform specific like: `dynamicTypeRamp` , `minimumFontScale` etc.

**Comment by shubhamguptadream11** [comment]
I thought this makes much more sense by specifying platform in props. But I am okay to rename it.

**Comment by shubhamguptadream11** [comment]
@cipolleschi @NickGerleman Can you guys please check this PR once?

**Review by cipolleschi — CHANGES_REQUESTED** [review]
Hi @shubhamguptadream11, thanks for working on this.
This PR is too big, it will be quite hard to review and land it.

Can I suggest to split it in multiple parts? 
Ideally, we can have:
1. a part that introduce the C++ changes and new functions we need
2. a part that updates the iOS part to consume those new functions, even though they are not usable from JS
3. the last part which implement the Js APIs to use the new mode.

**Comment by shubhamguptadream11** [comment]
Hi @tmikov,

Thanks for the feedback! I completely understand the concern. I'll split the PR into the suggested parts:

- C++ changes and new functions
- iOS updates to consume those new functions (without JS integration)
- Implementation of the JS APIs for the new mode
I'll work on breaking it down and submit the smaller, more manageable PR's shortly.

Thanks again for the guidance!

**Comment by shubhamguptadream11** [comment]
Hi @cipolleschi 

I've gone ahead and split the original PR into three separate ones as suggested:

[[PR 1]](https://github.com/facebook/react-native/pull/46130) - Introduces the C++ changes and new functions.
[[PR 2]](https://github.com/facebook/react-native/pull/46129) - Updates the iOS part to consume the new functions (not yet exposed to JS).
[[PR 3]](https://github.com/facebook/react-native/pull/46128) - Implements the JS APIs for the new mode.
Each PR is focused on a specific part of the overall change, making them easier to review and land. Please feel free to review them at your convenience.

**Pull request closed without merging**
