### PR TITLE
fix: add mixed to aria-checked typings

### PR DESCRIPTION
**Pull request by ankit-tailor**
## Summary

`aria-checked` prop should accept `mixed` as value as given [here](https://www.w3.org/WAI/GL/wiki/Using_WAI-ARIA_aria-checked%3Dmixed) and also [accessibilityState.checked](https://reactnative.dev/docs/accessibility#accessibilitystate) accepts mixed to represent checkboxes. This change refers to issue #34424 and PR https://github.com/facebook/react-native/pull/34524

## Changelog

[General] [Added] - Added `mixed` value for `aria-checked`.

## Test Plan

```js
<TouchableOpacity
  accessibilityRole="checkbox"
  aria-checked="mixed"
  accessibilityHint="click me to change state">
  <Text>Checkbox example</Text>
</TouchableOpacity>
```

### CODE REVIEW

**Review by necolas — APPROVED** [review]

**Comment by necolas** [comment]
There was an internal request to update the typescript types too. cc @lunaleaps

**Review by lunaleaps — CHANGES_REQUESTED** [review]
Hi @ankit-tailor! As Nicolas mentioned can we update the TS types here: https://github.com/facebook/react-native/blob/43636267011a97490ed7495b08e500c5d0d54872/Libraries/Components/View/ViewPropTypes.js#L534
and other related places if any

**Comment by ankit-tailor** [comment]
Yes @lunaleaps, I'll do the necessary changes.

**Comment by ankit-tailor** [comment]
@lunaleaps, Only ViewAccessibility props required the above changes, other than that everywhere else ViewAccessibility props are extended.

**Review by lunaleaps — APPROVED** [review]

**Comment by gabrieldonadel** [comment]
@lunaleaps any updates on this?

**Pull request closed without merging**
