### PR TITLE
[showcase] Add DN Prio

### PR DESCRIPTION
**Pull request by olofd**
One of Swedens largest newspapers built their latest app in React Native.
http://www.dn.se

(Author of the app here.)

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1119109554829299/int_phab) to review.

**Comment by mkonicek** [comment]
Thanks for choosing React Native! 👍

**Comment by facebook-github-bot-5** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by mkonicek** [comment]
@olofd It looks like this needs rebasing, sorry about that.

**Comment by lacker** [comment]
Hey, this app looks cool and showcaseworthy but I slightly changed up the format. Sorry for the conflict. Is there something to link to like a newspaper article that covers this app? Or any technical post about building it? See https://github.com/facebook/react-native/pull/8263 for the new showcase data format.

**Comment by hramos** [comment]
@olofd do you still want to merge this?

**Pull request closed without merging**
