### PR TITLE
Missing function tags

### PR DESCRIPTION
**Pull request by bsthomsen**
It seems like it's not written in es6, hence no arrow functions, therefor we must have the function tag for it to work?

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @grgmo to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by janicduplessis** [comment]
Thanks!

@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3736797) to review internal test results.

**Pull request closed without merging**
