### PR TITLE
[Blog] Improve social share previews, expand author bylines

### PR DESCRIPTION
**Pull request by hramos**
Several blog and sharing improvements are included in this update.

* A larger default preview image is used when a blog post or doc is shared on social media as recommended by [best practices](https://developers.facebook.com/docs/sharing/best-practices#images).
* Follow other Facebook Sharing best practices such as associating the site with a Facebook Page (React) and a Page Admin (121800083 is my fbid, and I am an admin for the React page).
* If the shared blog post contains a hero image, use it as a share preview image.
* Use actual doc content instead of generic site description when sharing docs.
* Update existing hero images to use the larger recommended size.
* Add titles to each author's byline.
* Add author's avatar to their byline.
* Add Twitter Card support.
* Link to individual blog posts from the title and hero image in the blog index.

Old metadata tags (blog post):
```
<meta property="og:title" content="Toward Better Documentation – React Native | A framework for building native apps using React">
<meta property="og:type" content="website">
<meta property="og:url" content="https://facebook.github.io/react-native/blog/2016/07/06/toward-better-documentation.html">
<meta property="og:image" content="http://facebook.github.io/react-native/img/opengraph.png?2">
<meta property="og:description" content="Part of having a great developer experience is having great documentation. A lot goes into creating good docs - the ideal documentation is concise, helpful, accurate, complete, and delightful. Recently we&#x27;ve been working hard to make the docs better based on your feedback, and we wanted to share some of the improvements we&#x27;ve made.">
```

New metadata tags (blog post):
```
<meta property="fb:app_id" content="1677033832619985">
<meta property="fb:admins" content="121800083">
<meta property="og:site_name" content="React Native">
<meta property="og:title" content="Toward Better Documentation">
<meta property="og:url" content="https://facebook.github.io/react-native/blog/2016/07/06/toward-better-documentation.html">
<meta property="og:image" content="http://facebook.github.io/react-native/img/opengraph.png">
<meta property="og:description" content="Part of having a great developer experience is having great documentation. A lot goes into creating good docs - the ideal documentation is concise, helpful, accurate, complete, and delightful. Recently we&#x27;ve been working hard to make the docs better based on your feedback, and we wanted to share some of the improvements we&#x27;ve made.">
<meta name="twitter:site" content="@reactnative">
<meta name="twitter:card" content="summary">
<meta property="og:type" content="article">
<meta property="article:author" content="Kevin Lacker">
<meta name="twitter:creator" content="@lacker">
```

OId metadata tags ([tutorial](https://facebook.github.io/react-native/releases/next/docs/tutorial.html)):
```
<meta property="og:description" content="A framework for building native apps using React">
```

New metadata tags ([tutorial](https://facebook.github.io/react-native/releases/next/docs/tutorial.html)):
```
<meta property="og:description" content="React Native is like React, but it uses native components instead of web components as building blocks. So to understand the basic structure of a React Native app, you need to understand some of the basic React concepts, like JSX, components, `state`, and `props`. If you already know React, you still need to learn some React-Native-specific stuff, like the native components. This">
```

New author bylines:
screen shot 2016-08-29 at 2 00 17 pm

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @Andreyco and @JoelMarcey to be potential reviewers.

**Comment by JoelMarcey** [comment]
👍 

It looks like a rebase is in order first, though.

**Comment by hramos** [comment]
@facebook-github-bot shipit-ninja

**Comment by facebook-github-bot-2** [comment]
@hramos updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9648/files/d788a17315369e9843a6d5ece04ed939e2b2d551..c6e514c11c398230783f25caa21b37254cc9893d)

**Comment by facebook-github-bot-9** [comment]
Normally, hramos, someone else should review and ship your pull request. However, we will trust that you know what you are doing. Shipping!

**Comment by facebook-github-bot-3** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3790332) to review internal test results.

**Pull request closed without merging**
