### PR TITLE
Fix typo in "YGZeroOutLayoutRecursively"

### PR DESCRIPTION
**Pull request by ultramiraculous**
## Motivation

Noticed the typo in the change log.

## Test Plan

Code should compile regularly after the change.

## Release Notes

 [GENERAL][ MINOR       ] [Yoga] - Typo in the zero-ing method

### CODE REVIEW

**Comment by shergin** [comment]
Thank you!
I think we have to fix it in Yoga repo though.

**Comment by ultramiraculous** [comment]
Sorry just remembered to check. Is the fix internal or am I missing it? It looks like it's still the same over here: https://github.com/facebook/yoga/blob/master/yoga/Yoga.cpp

**Comment by chirag04** [comment]
@ultramiraculous He mean't open this PR on yoga repo too and let's get this merged on yoga repo first. yoga source here in RN is just a copy of the original yoga repo.

**Comment by shergin** [comment]
Or... I can fix it by myself internally if you are okay with it.
Great catch, BTW! 😄

**Comment by ultramiraculous** [comment]
Yeah I'm fine if you want to just do it. I'm not looking for glory with this PR 😂

**Pull request closed without merging**
