### PR TITLE
[Android] Add docs on building from source

### PR DESCRIPTION
**Pull request by satya164**
Mostly taken from @chirag04 's comment here - https://github.com/facebook/react-native/issues/3337#issuecomment-147243916

cc @ide @mkonicek

### CODE REVIEW

**Comment by ide** [comment]
👍🏻

**Comment by satya164** [comment]
ping @mkonicek

**Comment by chirag04** [comment]
:+1:

**Comment by mkonicek** [comment]
Sorry for the delay!

**Pull request merged**
