### PR TITLE
Add new application "Chemin de Fer de Provence"

### PR DESCRIPTION
**Pull request by ThierryDH**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by janicduplessis** [comment]
@ThierryDH Can you move it to keep the alphabetic order

**Comment by ThierryDH** [comment]
@janicduplessis Done ! Thanks ;)

**Comment by facebook-github-bot-6** [comment]
@ThierryDH updated the pull request.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/356826881108272/int_phab) to review.

**Pull request closed without merging**
