### PR TITLE
Update Upgrading.md

### PR DESCRIPTION
**Pull request by odino**
Just updating the docs as .18 is quite old :)

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @frantic and @sunnylqm to be potential reviewers.

**Comment by javache** [comment]
LGTM, but we really shouldn't try to keep this up-to-date continuously. It's just an example after all.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1707843002818702/int_phab) to review.

**Pull request closed without merging**
