### PR TITLE
Use PropTypes instead of React.PropTypes.

### PR DESCRIPTION
**Pull request by livioso**
Already used PropTypes in most cases but a few in this file => use PropTypes everywhere.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @nathanajah and @pglotov to be potential reviewers.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/492516550946748/int_phab) to review.

**Comment by javache** [comment]
Could you rebase this? It no longer applies cleanly to master.

**Comment by facebook-github-bot-3** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by javache** [comment]
Your merge has gone wrong. Please verify your pull-request only contains the actual changes you're making.

**Comment by javache** [comment]
This pull request hasn't seen activity in a while. If you still want to merge this, please open a new pull request.

**Pull request closed without merging**
