### PR TITLE
[Switch] Remove fixed size for Android. Fixes #3785

### LINKED ISSUE #3785: Layout inconsistency between Switch & SwitchAndroid
### Switch

Switch
### SwitchAndroid
SwtichAndroid

The width value here seems to be incorrect.
https://github.com/facebook/react-native/blob/master/Libraries/Components/Switch/Switch.js#L113

No exactly sure if this applies to all devices so I wanted to check before making any kind of PR.

### PR DESCRIPTION
**Pull request by christopherdro**
Fixed #3785

### CODE REVIEW

**Comment by christopherdro** [comment]
cc @mkonicek

**Comment by mkonicek** [comment]
I think this is good! cc @sahrens

How have you tested it? Can you add a screenshot from the UIExplorer for example?

**Comment by christopherdro** [comment]
@mkonicek Yea I've tested it. 
Here is a screenshot from UIExplorer using `Switch` instead of `Switch Android`.

wo-changes

## With change matches: `SwitchAndroid`
w-changes

**Comment by sahrens** [comment]
Can we please not have different layout behavior between iOS and android? This makes android switch stretch and right align which is super weird and does not match iOS.

**Comment by sahrens** [comment]
Can we just change the width? Or pass down the width from the native module if it varies by device?

**Comment by christopherdro** [comment]
@sahrens I had originally thought about just adjusting the width but after speaking with @mkonicek he mentioned something about auto-layout with Android and that it's not necessary to define and fixed values. 

Adjust the width to 45 makes it not get cut off but all the switches are still aligned left.

Does the switch component even vary in size between different Android devices?

**Comment by kmagiera** [comment]
Size of switch on android varies between OS versions, it can be different when some of the accessibility features are on AFAIK, not to mention custom skins/themes some vendor like to preinstall. It's always been measuring itself because of the aforementioned reasons and I personally support this change. Not sure what the benefit would be from having it send over but it will definitely introduce some limitations (e.g currently we can start initialising the bridge before activity is started and we don't yet have access to the theme at that time, to pass it down as a constant we'd need to have theme before we initialise the bridge)

**Comment by sahrens** [comment]
If it's not reasonable to pass the size through as a constant, there are two options to make it consistent with iOS:

1) make it not stretch to fill the parent (it should end up left aligned in the example).

2) change iOS to stretch and fill the parent and right-align in the example like android (and fix all the existing usage of switch in our iOS apps so we don't break anything). 

The only thing I really care about is consistency.

**Comment by christopherdro** [comment]
The current changes should keep the same layout behavior if you were to use SwitchIOS or SwitchAndroid separately since SwitchIOS is the only one that has styling pre defined and passed into the native component.

**Comment by sahrens** [comment]
If it's not reasonable to pass the size through as a constant, there are
two options to make it consistent with iOS:

1) make it not stretch to fill the parent (it should end up left aligned in
the example).

2) change iOS to stretch and fill the parent and right-align in the example
like android (and fix all the existing usage of switch in our iOS apps so
we don't break anything).

The only thing I really care about is consistency. App code shouldn't have
to change styles and layout to use switches on different platforms.

**Comment by sahrens** [comment]
But are they interchangeable? We should strive for interchangeable whenever it's reasonable, and this seems like a perfect case for that.

**Comment by mkonicek** [comment]
I like what Spencer suggested:

> 1) make it not stretch to fill the parent (it should end up left aligned in the example).

Is that doable? I think you need to change the measure logic in Java. I agree it's a bit strange the Android Switch fills parent and is right-aligned.

**Comment by satya164** [comment]
@christopherdro Would love to get this merged. Without this the Cross platform switch component is not usable.

**Comment by mkonicek** [comment]
Let's figure out the alignment on Android separately. I agree without this PR the cross-platform switch is unusable.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
