### PR TITLE
Update UsingAScrollView.md

### PR DESCRIPTION
**Pull request by dfischer**
Simple spacing update for consistency.

Super simple PR. I'm just fixing the spacing in the documentation to be consistent with the other docs.

### CODE REVIEW

**Comment by dfischer** [comment]
Added

**Comment by hramos** [comment]
This is a transient import failure. I'll re-import shortly.

**Comment by mkonicek** [comment]
(Ignore the changing of the labels, testing an improvement to a script to retry merging pull requests that got stuck.)

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
