### PR TITLE
[WIP] measure-binary-size.sh script to measure binary size impact of React Native

### PR DESCRIPTION
**Pull request by lyahdav**
## Motivation (required)

Many developers that are considering using React Native have concerns about the binary size impact of adding the framework, especially on Android. This script makes it quick to measure the size of new React Native project with different parameters.

This is a WIP, but a good beginning.

## Test Plan (required)

This is just a script, no tests. I have run it manually and verified it works for me.

### CODE REVIEW

**Comment by lyahdav** [comment]
Also the script currently fails if you enable Proguard because of https://github.com/facebook/react-native/issues/13089

**Comment by ide** [comment]
I've found that the APK size on disk is very different from what shows up in the Play Store, and the same is true for the iOS App Store. I think it's really important to call out that any numbers before seeing what the App Store / Play Store displays are not accurate.

**Comment by lyahdav** [comment]
Do you know what reasons are that APK and size in the Play Store could be different? I still think others may find this script useful, it was actually @ericvicenti who suggested I make this a pull request. Maybe I'll just add a disclaimer in the script to your point?

**Comment by ide** [comment]
I'm not sure why, I just saw that APK downloader sites reported one size for our app (the smallest), physical devices reported another (the middle), and the actual APK was another size (the largest).

I think the disclaimer is helpful in telling people that this tool can show directional changes (ex: did the APK get way bigger?) but that to see the actual numbers you should publish to the Play Store.

**Pull request closed without merging**
