### PR TITLE
feat: Remove platform check in requireNativeComponent to support additional platforms

### PR DESCRIPTION
**Pull request by jhampton**
## Motivation

Using platform checks can make it difficult to incorporate changes for other platforms (e.g. Windows). 
 Using a check for the underlying function accomplishes the same goal without relying on an Android-specific check.  This change allows this JS file to be re-used instead of copied and modified. 

## Test Plan

[X] Run Jest tests
[X] Test in RNTester on simulators
[X] Test in Playground

## Related PRs

No related PR's found :)

## Release Notes

[GENERAL] [ENHANCEMENT] [Libraries/ReactNative/requireFabricComponent.js] - Simplified check against UIManager to support additional platforms, removing Android-specific check

### CODE REVIEW

**Comment by rozele** [comment]
@jhampton #18378 😆

**Comment by jhampton** [comment]
Quick question @rozele – I wasn't sure if the `else if` you've included was necessary.  Is there another implementation we might need to support (either bubbling or lazy and ...?)

**Comment by rozele** [comment]
@jhampton the else if is to prevent iOS from calling `merge` - but I now see that merge works as expected when either source or destination is null.

**Comment by rozele** [comment]
I'm good with this PR if you add the same change to `requireNativeComponent`

**Comment by jhampton** [comment]
Great, thank you!  Quick question @rozele : is there a reason this couldn't/shouldn't be refactored into a separate module and `require`d in both files?

**Comment by rozele** [comment]
@jhampton - I'm supportive of a separate module.

**Comment by jhampton** [comment]
I ended up making the same change to `requireNativeComponent` per @rozele 's original PR.  I'm not sure about the future of these two files vis-a-vis the transition to Fabric and historical context, so this is sufficient for now.

Also, it looks like CI is failing on `yarn` ATM. I'll check back in a bit later.

**Comment by hramos** [comment]
The `yarn` failure appears to be related to a Circle CI outage. The outage is over, and my colleagues at github.com/facebook/docusaurus found that jobs spawned from newer commits are no longer seeing the `yarn` failure, but I haven't had luck on this repo yet.

You may want to try pushing a dummy commit to trick Circle into running again, just in case.

**Comment by jhampton** [comment]
Thank you @hramos!  I tried again, and it looks like `yarn` is still not found.

image

**Comment by hramos** [comment]
If you rebase past https://github.com/facebook/react-native/commit/6f6084db69de372cbc6dcec259389e4b7dfd7fa5, it should be fixed. Sorry for the trouble!

**Comment by jhampton** [comment]
Interesting...it looks like there are quite a few eslint failures in the new tests.  I should be up to date as of this morning's `master`.

**Comment by grabbou** [comment]
I think I've seen CI to fail for other lint related reasons as well earlier today. I'll look into that too as I am planning on cutting few more releases today.

Meanwhile, let's try merging that.

**Comment by grabbou** [comment]
Interesting... 🤔

**Pull request closed without merging**
