### PR TITLE
Add vertical ScrollView content offset on Android

### PR DESCRIPTION
**Pull request by jonaslu**
This is the (evil) twin commit to:
https://github.com/facebook/react-native/pull/12502

Fixes that contentOffset is not available on
vertical scroll-views on Android.

## Test Plan
* Create an Android component with a ScrollView. Add enough
  items to fill beyond the visible screen. Set the content
  offset to some value that makes the content scroll. Verify
  that it snaps to the y-axis as expected.
* Remove items so screen is no longer filled, keep content
  offset parameter. Scroll view still works but does not scroll.
* Set only one parameter to content-offset (x || y) -
  parameters are now ignored since they must be a pair.
* Remove contentOffset, scrollView still works as before.

### CODE REVIEW

**Comment by shergin** [comment]
I am sorry, but we are thinking about deprecating `contentOffset`.
https://github.com/facebook/react-native/issues/6849#issuecomment-323551327

**Comment by henrikra** [comment]
@jonaslu Looks good! Mind fixing conflicting files? :D

**Comment by jonaslu** [comment]
Well, sure, but before I go ahead -do you know if it's going to be merged? The comments in #6849 seems omnious and not so conclusive..

**Comment by henrikra** [comment]
I noticed them too @jonaslu But I think this is the best solution so far. Someone can refactor better solution if they now better. Your solution is better than no solution on Android :)

**Comment by Jacse** [comment]
@shergin have you guys arrived at a decision? If no decision for a better implementation could be made can we get this merged so we'll at least have something working?

I don't think "the old way" should be deprecated before a new and better way is implemented.

**Comment by fbartho** [comment]
This would be a really valuable feature. We need this for consistency between our behavior on both platforms.

**Comment by cpojer** [comment]
I'll close this based on @shergin's comment that we may want to deprecate `contentOffset` altogether.

**Pull request closed without merging**
