### PR TITLE
Make getCurrentActivity public on ReactContext

### PR DESCRIPTION
**Pull request by marcshilling**
Addresses #8661

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @foghina and @ginandi to be potential reviewers.

**Comment by foghina** [comment]
Please use these powers for good :)

@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/157465998010710/int_phab) to review internal test results.

**Comment by nickhudkins** [comment]
YAS!!!!!!!

**Pull request closed without merging**
