### PR TITLE
Using an updated version of Sinopia that works with node 4&5

### PR DESCRIPTION
**Pull request by bestander**
While waiting for https://github.com/rlidwka/sinopia/issues/311 to be resolved I cloned repo and make e2e tests install from my fork.

### CODE REVIEW

**Comment by bestander** [comment]
@davidaurelio need a stamp please

**Comment by davidaurelio** [comment]
@facebook-github-bot yeeeha!

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
merged

**Pull request closed without merging**
