### PR TITLE
Stabilized TestIdTestApp integration test

### PR DESCRIPTION
**Pull request by bestander**
- TestIdTestModule instrumentation tests is responsible for too many occasional crashes, e.g. https://circleci.com/gh/facebook/react-native/7054. 
This should fix the problem (will monitor over next week)

- Made file naming more consistent

- 5 retries don't make e2e tests more stable, reduced back to 3 but I need to investigate how to make it more reliable

Test Plan:
- Circle CI tests

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @ide to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@bestander updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@bestander updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@bestander updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@bestander updated the pull request.

**Comment by bestander** [comment]
Instrumentation test passes, landing to get some live data by next week

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1025614530842159/int_phab) to review.

**Pull request closed without merging**
