### PR TITLE
add crowdsource case

### PR DESCRIPTION
**Pull request by xujinyang**
if you need  test account,please sent email to 1119117546@qq.com

### CODE REVIEW

**Comment by mkonicek** [comment]
Very cool!

I've just merged another PR that added an app to the end of the list. You might want to wait until it's merge and then rebase.

**Comment by brentvatne** [comment]
Please rebase @xujinyang

**Comment by bestander** [comment]
@xujinyang, another branch that breaks the build became part of the PR.
You may find this useful: http://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master

**Comment by chirag04** [comment]
@facebook-github-bot close

**Comment by chirag04** [comment]
duplicate of #https://github.com/facebook/react-native/pull/6718

**Pull request closed without merging**
