### PR TITLE
Fix Xcode 11 build

### PR DESCRIPTION
**Pull request by hileix**
## Summary
Fixes build in Xcode 11 beta, the signature for __unused was changed. This adds a new check for the new style.

In my project, react-native version 0.49.5 was used.
I met this [issue](https://github.com/facebook/react-native/issues/29069) and found a solution, but I need to modify the code in `node_moduels/reac-native` by myself. It is not convenient for me to migrate the project.

I was hoping you guys would release react-native 0.49.6.

## Changelog

[iOS] [Fixed] - Xcode 11 beta build

## Test Plan
Build & run RNTester

### CODE REVIEW

**Comment by shergin** [comment]
@hileix Could you please sign CLA?

**Comment by hileix** [comment]
> @hileix Could you please sign CLA?

I've logged in to CLA.

**Comment by shergin** [comment]
@hileix Could you please change the base of the PR to `master` (instead of `0.49-stable`).

**Comment by hileix** [comment]
> @hileix Could you please change the base of the PR to `master` (instead of `0.49-stable`).

Ok.The new PR is [here](https://github.com/facebook/react-native/pull/29100)

**Pull request closed without merging**
