### PR TITLE
[babel] exclusively use babel-core

### PR DESCRIPTION
**Pull request by ide**
We don't need babel the CLI tool... just babel-core suffices. Remove babel, which speeds up npm install, and just use babel-core.

Test Plan: Delete the packager cache and launch the UIExplorer.

### CODE REVIEW

**Comment by amasad** [comment]
Thanks! Will merge this week once we open source the packager repo.

**Comment by ide** [comment]
@amasad the packager now uses just babel-core so this PR simply removes babel from package.json + shrinkwrap now.

**Comment by ide** [comment]
cc @martinbigio this should be pretty straightforward and reduce some npm deps =)

**Comment by martinbigio** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
