### PR TITLE
Add DatePickerIOS countdown support

### PR DESCRIPTION
**Pull request by EnricoGallus**
Thanks for submitting a PR! Please read these instructions carefully:

- [ ] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)
Want to use the countdown mode of the DatePickerIOS

What existing problem does the pull request solve?

Not supported mode on the DatePickerIOS

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

I haven't found any unit tests for the components, did i overlook something?

## Next Steps

Sign the [CLA][2], if you haven't already.

done

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by javache** [comment]
Can you update the comment in https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/React/Views/RCTDatePickerManager.m#L23 and add an example to `DatePickerIOSExample`

**Comment by chirag04** [comment]
this is not going to be as straight forward.

Refer: 
https://github.com/facebook/react-native/issues/5470
https://github.com/facebook/react-native/pull/5223

**Comment by hramos** [comment]
What's the latest status here? Tests are in the UIExplorer app, you can add any there.

**Comment by hramos** [comment]
This PR appears to be abandoned. Closing for now.

**Pull request closed without merging**
