### PR TITLE
Native Animated - Add module test on Android

### PR DESCRIPTION
**Pull request by janicduplessis**
Add tests for the NativeAnimated module on Android. Separated this from #15919 since it caused issues internally.

**Test plan**
Run android unit tests

### CODE REVIEW

**Comment by janicduplessis** [comment]
Here's the error that happens internally. Looks related to the version of mockito. 

```
ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedModuleTest.java:67: error: cannot find symbol
        mUIBlocks.add(invocation.getArgumentAt(0, UIBlock.class));
```

**Comment by janicduplessis** [comment]
@hramos Could you have someone from fb try to fix this?

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :clipboard: Release Notes - <i>This PR appears to be missing Release Notes.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by janicduplessis** [comment]
@hramos Rebased on master, this PR was really old, might be why it didn't land.

**Comment by hramos** [comment]
It's failing once the diff goes through Sandcastle:

```
ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedModuleTest.java:65: error: cannot find symbol
        mUIBlocks.add(invocation.getArgumentAt(0, UIBlock.class));
                                ^
ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedModuleTest.java:72: error: cannot find symbol
        mUIBlocks.add(0, invocation.getArgumentAt(0, UIBlock.class));
                                   ^
```

**Comment by janicduplessis** [comment]
@hramos  Looks like fb is using mockito@2+ and OSS was using 1+. It was updated recently in https://github.com/facebook/react-native/commit/3ea803a814f43edb3ec256dd85d778c652ca99d1#diff-5df8978d901ea853da66f065feee64ab. I simply rebased on master and updated to the test to the new api (getArgument instead of getArgumentAt). Lets see if CI passes now.

**Comment by cpojer** [comment]
@janicduplessis seems like there are more errors at FB:
```
Summary: 
 ** Summary of failures encountered during the build **
Rule xplat//js/react-native-github/ReactAndroid/src/test/java/com/facebook/react/animated:animated_NativeAnimatedModuleTestAndroid FAILED because Command failed with exit code 1.
stderr: /mnt/btrfs/trunk-hg-fb4a-fbsource-39225875-1547660989/xplat/js/react-native-github/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedModuleTest.java:65: error: cannot find symbol
        mUIBlocks.add((UIBlock)invocation.getArgument(0));
                                         ^
  symbol:   method getArgument(int)
  location: variable invocation of type org.mockito.invocation.InvocationOnMock
/mnt/btrfs/trunk-hg-fb4a-fbsource-39225875-1547660989/xplat/js/react-native-github/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedModuleTest.java:72: error: cannot find symbol
        mUIBlocks.add(0, (UIBlock)invocation.getArgument(0));
                                            ^
  symbol:   method getArgument(int)
  location: variable invocation of type org.mockito.invocation.InvocationOnMock
Errors: 2. Warnings: 0.

    When running <javac_jar>.
    When building rule xplat//js/react-native-github/ReactAndroid/src/test/java/com/facebook/react/animated:animated_NativeAnimatedModuleTestAndroid#testsjar.
Not all rules succeeded.
```

Mind checking those before we can land this for real?

**Comment by janicduplessis** [comment]
@cpojer I'll see if I can get time to update this, it's pretty low prio for me atm though.

**Comment by janicduplessis** [comment]
Going to close this for now, if anyone has time feel free to pick this up.

**Pull request closed without merging**
