### PR TITLE
Adding support for multi platform key in `Platform.select`

### PR DESCRIPTION
**Pull request by dudeinthemirror**
### Motivation
When using `Platform.select` in e.g. a `Stylesheet.create` construct, often times we have the situation where a bunch of props are the same across platforms, but maybe only one or two are different for one of the platforms. This PR is addressing that by adding the option of specifying a multi-key e.g. 

`['ios, android']:` 

Instead of:

```javascript
import { Platform, StyleSheet } from 'react-native';
const styles = StyleSheet.create({  
  container: {
    flex: 1,
    ...Platform.select({
      ios: {
        flexWrap: 'wrap',
        width: 125,
        marginLeft: 40,
        marginRight: 40
      },
      android: {
        flexWrap: 'wrap',
        width: 125,
        marginLeft: 40,
        marginRight: 40
      },
    }),
  },
});
```

you can do:
```javascript
import { Platform, StyleSheet } from 'react-native';
const styles = StyleSheet.create({  
  container: {
    flex: 1,
    ...Platform.select({
      ['ios, android']: {
        flexWrap: 'wrap',
        width: 125,
        marginLeft: 40,
        marginRight: 40
      },
    }),
  },
});
```
thus, avoiding duplicate chunks of code.

This also allows you to define a set of common props, and then override one or more values for a specific platform e.g.

```javascript
import { Platform, StyleSheet } from 'react-native';
const styles = StyleSheet.create({  
  container: {
    flex: 1,
    ...Platform.select({
      ['ios, android']: {
        flexWrap: 'wrap',
        width: 125,
        marginLeft: 40,
        marginRight: 40
      },
      ios: {
        marginRight: 50,  // this will override the value in the multi-key
        marginTop: 10     
      },
      android: {
        marginRight: 60,  
      },
    }),
  },
});
```

In this case this will resolve to 

```javascript
{ flexWrap: 'wrap', width: 125, marginLeft: 40, marginRight: 50, marginTop: 10 }  // for ios
{ flexWrap: 'wrap', width: 125, marginLeft: 40, marginRight: 60 }                 // for android
```

### NOTES: 
- this feature is very handy for react-native-web projects where most styles will have a set of props for `ios` and `android` and a different set for `web`.
- this feature is going to be very useful when more platforms are added 

### Test plan

I've added 8 test cases to `Platform-test.js`. Here is a screenshot of all tests passing 
( `yarn run test` )

image 2017-03-01 at 6 15 01 pm

### Documentation
screen shot 2017-03-02 at 10 18 05 am
screen shot 2017-03-02 at 10 19 00 am

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks for the detailed description and test plan. For API changes like this, you could post in React Native Community to discuss first.

This can be solved like this without this PR:

```
const containerStyle =  {
  flex: 1,
  flexWrap: 'wrap',
  width: 125,
  marginLeft: 40,
  marginRight: 40
};

const styles = StyleSheet.create({  
  container: {
    ...containerStyle,
    Platform.select({
      ios: {
        marginRight: 50,  // this will override the value in the multi-key
        marginTop: 10     
      },
      android: {
        marginRight: 60,  
      },
    }),
  },
});
```

I'm not convinced we need this API.

Also note the Babel transform - the `Platform.select` gets inlined for performance. If we want to make another API change we'd have to fix the Babel transform too. See https://github.com/facebook/react-native/pull/11608

**Comment by dudeinthemirror** [comment]
Hi @mkonicek, thanks for your review.
- re: post to the React Native Community to discuss first: I'll keep it in mind for future PR's
- re: this can be solved without this PR: I totally agree, however for large projects, especially when more platforms are involved, this might help with readability / traceability
- re: Babel transform inline: yes, I am aware of that change needed. I was planning to do it when/if this PR advanced

**Comment by dudeinthemirror** [comment]
Looking into the CI Flow errors.

**Comment by mkonicek** [comment]
I realized this could be done even without the extra variable:

```
const containerStyle = };

const styles = StyleSheet.create({  
  container: {
    ...{
      flex: 1,
      flexWrap: 'wrap',
      width: 125,
      marginLeft: 40,
      marginRight: 40
    },
    ...Platform.select({
      ios: {
        marginRight: 50,  // this will override the value in the multi-key
        marginTop: 10     
      },
      android: {
        marginRight: 60,  
      },
    }),
  },
});
```

Will that work and override the value correctly? If yes I think the code snippet above is not too different from the snippet in your PR description?

Because of the above I'm not yet convinced it's worth adding this extra API and code to be maintained into RN. However, you could always create a helper to use in your projects and share it on npm for anyone to use.

**Comment by mkonicek** [comment]
With multiple platforms involved could this API create an opportunity for people to write code that's confusing their colleagues on the project?

```
const styles = StyleSheet.create({  
  container: {
    flex: 1,
    ...Platform.select({
      ['ios, android']: {
       ...
      },
      ['ios, 'web']: {
       ...
      },
      web: { ... },
    }),
  },
});
```

It would be quite hard for me tracing all the paths in the rules above and understanding what the component would look like on each platform.

**Comment by mkonicek** [comment]
@dudeinthemirror I don't think we should proceed with the PR until the questions above are answered. Adding more commits is not very useful at this point.

**Comment by skv-headless** [comment]
Or there is another great package https://github.com/vitalets/react-native-extended-stylesheet#media-queries

**Comment by dudeinthemirror** [comment]
@mkonicek please find the answers below:
- re: 'will this work?': yes, this definitely works, see:
https://cl.ly/1Z0a1O3I0O0y
**However**, when you reverse the order of the 2 object spread's in `container` the resulting style is not correct, see:
https://cl.ly/1h2O3z0u1f2T
With the proposed change, the results would be the same regardless of the order, see:
https://cl.ly/2k1k0s0A270h
https://cl.ly/0F0s3E2r3H1R
As I mentioned before, things get even uglier when introducing a third platform (e.g. `web`) into the picture.
- re: 'create an opportunity for people to write code that's confusing': that is a fair point, with more flexibility you always get more chances of people abusing the newly added levers and knobs
- re: 'adding more commits is not very useful': sorry about that, `travis-ci` caught a Flow error which I'd missed during development; regardless of the fate of the PR, I don't like to leave un-finished code behind :)

**Comment by sravich** [comment]
Thank you so much . This is really useful 👍

**Comment by dudeinthemirror** [comment]
@mkonicek: I am pushing one last commit: adding more test cases, improving tests readability, fixing a bug.
Please let me know if you want to close this PR or leave it open. 
Either way, thanks again for your time and advice!

**Comment by mkonicek** [comment]
> However, when you reverse the order of the 2 object spread's in container the resulting style 

I think this is OK, people should know that the order matters.

I'll close it as it's quite possible to achieve the same result with the current simple API and prefer for keeping it simple.

Hope it won't discourage you from contributing in the future!

**Comment by dudeinthemirror** [comment]
Fair enough, I trust you guys' judgement. 
No, no discouragement :) I learnt quite a bit by going through the PR process.
Hope to meet you tonight at the FB react-native meetup.

**Comment by fkgozali** [comment]
@dudeinthemirror - thanks for pointing this PR out to me during the meetup. I looked through the discussion here, and I think overall I agree with @mkonicek here that the spread operator is probably the most friendly approach to solve this use case.

The way I think about it is:
* The existing support (ios: ..., android: ...) is pretty basic JavaScript format that is easy to understand -- It actually exists as a helper because the traditional `Platform.OS === 'ios'` check everywhere could lead to messy code. So this PR feels like a helper on top of another helper.
* When you put the key `'ios, android'` in there, it may introduce confusion, as discussed above, and also because you're now no longer using a simple key without any space. While in theory this will work fine, in practice, any *additional concept* that we need to teach developers is discouraged, both for ease of use and for future maintainability.

Anyway, like @mkonicek said, hope you'll keep contributing in the future :).

**Comment by dudeinthemirror** [comment]
hey @fkgozali, appreciate your time reviewing this. I understand the concern, keeping things simple is a big part of a good API, I agree.

**Pull request closed without merging**
