### PR TITLE
[Android] Update dev menu to keep track of element inspector.

### PR DESCRIPTION
**Pull request by christopherdro**
This PR makes the android dev menu consistent with iOS where toggling the inspector will update the button label accordingly.

### CODE REVIEW

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@mkonicek just pinging because it looks like it didn't, in fact, "shipit"

**Comment by christopherdro** [comment]
cc @mkonicek

**Comment by mkonicek** [comment]
Thanks for the ping. There's some closed source code that depends  on this and fails to compile. Will merge it manually, hope to get to it soon.

**Comment by christopherdro** [comment]
@facebook-github-bot shipit

**Comment by christopherdro** [comment]
cc @mkonicek eh, I think I may of just shipped this by accident

**Comment by mkonicek** [comment]
@christopherdro Sorry for the delay, I'm on vacation. If you don't hear back from the bot it's because some internal code at fb failed to compile or some internal tests failed. In this case it was a compilation error. Luckily we've open sourced the test which failed to compile now: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/androidTest/java/com/facebook/react/testing/ReactSettingsForTests.java

I'm merging this manually, there's been long enough delay for you on this already :)

**Comment by mkonicek** [comment]
We'll work on reporting the status back to github next year.

**Pull request closed without merging**
