### PR TITLE
fix(deps): update `jscodeshift`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Summary

This will include https://github.com/facebook/jscodeshift/pull/473, which will fix the problems with the `colors` package (see https://github.com/facebook/jscodeshift/issues/474)

## Changelog

[Internal] [Security] - update `jscodeshift`

## Test Plan
N/A

### CODE REVIEW

**Review by cortinico — CHANGES_REQUESTED** [review]
Thank you for doing this @MichaelDeBoey 
Don't you mind running a `yarn install` to rebuild the lockfile?

**Comment by MichaelDeBoey** [comment]
@cortinico Should be fine

**Review by cortinico — APPROVED** [review]
Change looks fine but it's failing internally. I need to look into it. So it might take a bit longer for this to merge.

**Comment by SimenB** [comment]
https://github.com/facebook/react-native/blob/efc56b27904e7fdfd0a4f156b599017b0bdaa11f/repo-config/package.json#L41 as well?

**Pull request closed without merging**
