### PR TITLE
[iOS] Fabric: Refactor ParagraphComponentView to support border 

### LINKED ISSUE #45938: Text Not Show Content When style both set borderWidth and backgroundColor.
### Description

Text Not Show Content When style both set borderWidth and backgroundColor.
if Text style is styles.tag, the '预售' Not Show，only show backgroundColor
else style is styles.tag, the '停止营业' Can show normally
like this
5851723083312_ pic

The Code below
`
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import type {PropsWithChildren} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';

import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

type SectionProps = PropsWithChildren<{
  title: string;
}>;

function Section({children, title}: SectionProps): React.JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
}

function App(): React.JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
         <Text style={styles.tag}>预售</Text>
        <Text style={styles.tag1}>停止营业</Text>
         
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
  tag: {
    fontSize: 20,
    fontWeight: '400',
    marginLeft: 16,
    width: 124,
    height: 32,
    borderRadius: 4,
    backgroundColor: '#F5F6F7',
    borderWidth: 1,
    borderColor: '#C8C9CC',
    paddingHorizontal: 12,
    paddingVertical: 4
  },
  tag1: {
    fontSize: 20,
    fontWeight: '400',
    marginLeft: 16,
    width: 124,
    height: 32,
    borderRadius: 4,
    backgroundColor: '#F5F6F7',
    borderColor: '#C8C9CC',
    paddingHorizontal: 12,
    paddingVertical: 4
  },
});

export default App;

`

### Steps to reproduce

1.cd ReproducerApp
2. npm  run start
3. run Xcode

### React Native Version

0.73.9

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
Node Version : v20.11.1
```

### Stacktrace or Logs

```text
none log
```

### Reproducer

https://github.com/zdpdsy/reproducer

### Screenshots and Videos

5851723083312_ pic

### PR DESCRIPTION
**Pull request by zhongwuzw**
## Summary:

Fixes #45938. 

## Changelog:

[IOS] [FIXED] - Fabric: Refactor ParagraphComponentView to support border

## Test Plan:

Demo in #45938 .

### CODE REVIEW

**Review by cipolleschi — COMMENTED** [review]
Thanks for working on this.
Just to understand, why do we have to create a UIGraphicsImageRenderer context and paint into it, rather that just draw borders around the ParagraphComponentView? 
I'm a bit afraid that this implementation might have some performance implications.

**Comment by zhongwuzw** [comment]
> Thanks for working on this. Just to understand, why do we have to create a UIGraphicsImageRenderer context and paint into it, rather that just draw borders around the ParagraphComponentView? 

@cipolleschi  We should add a new subview to ensure text render above border layer . We used `zIndex` but it may not work.

> I'm a bit afraid that this implementation might have some performance implications.

I think it may not have much difference because we used `drawRect` which also creates a context. By changing to UIGraphicsImageRenderer context, we can more control over when to re-render text compared to the `drawRect` method.

**Comment by cipolleschi** [comment]
Hey @zhongwuzw! Huge thanks for working on this. We really appreciate the time you are investing to make the New Architecture great and your contribution is really valued as you helped solving so many issues already!

I was talking with some other expert of Fabric internally and looking at the code, and I spent something playing with the reproducer, and we don't think that this is the proper solution for the problem.

This solution is basically a brute-force approach: we already have the code that draws the background and the broders in the [`RCTViewComponentView.mm` file](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm#L674-L928) and the current solution basically reimplement that work in the `RCTParagraphComponentView`. The responsibility of the `RCTParagraphComponentView` should be to only draw the Text and leave the rest to the parent class

We have to understand why the rendering is broken first. It could be that we are executing some instructions in the wrong order or that we are not overriding the right method.

**Comment by cipolleschi** [comment]
I think I found the root cause and I have a possible solution.
The problem is in this [piece of code](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm#L772-L779)

Here we create an image with a specific border and a background and we assign the image to a `_borderLayer` object (a `CALayer`).
The `_borderLayer` is added as sublayer to the `RCTParagraphComponentView`. 

The RCTParagraphComponentView uses NSTextKit to draw text, but it is not clear to me where these text are drawn: are they drawn to a layer? are they drawn as raw pixel on the screen?

Despite that, the added layer is rendered **on top** of the text that is drawn by the `RCTParagraphComponentView`.

Removing the background color makes the text appear, because the image that is created in this case has a transparent background, therefore iOS does not draw those pixels and leaves the text visible.

Removing the `borderWidth` invalidate the borderLayer somehow and the text is rendered. However, with non-uniform `borderRadiuses`, even removing the BorderWidth kept the background rendering on top of the text.

**Comment by cipolleschi** [comment]
I might have a solution that can work, but I need to validate it internally first.

**Comment by zhongwuzw** [comment]
> I think I found the root cause and I have a possible solution. The problem is in this [piece of code](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm?rgh-link-date=2024-08-16T10%3A50%3A02Z#L772-L779)
> 
> Here we create an image with a specific border and a background and we assign the image to a `_borderLayer` object (a `CALayer`). The `_borderLayer` is added as sublayer to the `RCTParagraphComponentView`.
> 
> The RCTParagraphComponentView uses NSTextKit to draw text, but it is not clear to me where these text are drawn: are they drawn to a layer? are they drawn as raw pixel on the screen?
> 

Hi, the text is rendered on the `RCTParagraphComponentView`'s layer, in the `contents`.

> Despite that, the added layer is rendered **on top** of the text that is drawn by the `RCTParagraphComponentView`.
> 
> Removing the background color makes the text appear, because the image that is created in this case has a transparent background, therefore iOS does not draw those pixels and leaves the text visible.
> 
> Removing the `borderWidth` invalidate the borderLayer somehow and the text is rendered. However, with non-uniform `borderRadiuses`, even removing the BorderWidth kept the background rendering on top of the text.

The root cause I think is we rendered the text on the view's layer directly, so we can't let border draw under the view's layer even though we changed border layer's zPosition to -1023.

**Comment by cipolleschi** [comment]
> The root cause I think is we rendered the text on the view's layer directly, so we can't let border draw under the view's layer even though we changed border layer's zPosition to -1024.

Yeah, that's the thing! we should try to either draw on a separate layer, that we attach on top of the other layers added in the `invalidateLayer` method or we find a different path.

**Comment by zhongwuzw** [comment]
@cipolleschi I changed the renderer from view to layer, Is this meeting your expectations?

**Review by cipolleschi — COMMENTED** [review]
Hi @zhongwuzw, thanks for working on this.
In the end, after discussing with several people internally, we decided for a different approach, which is to create an auxiliary subview that is set as `contentView` and let it do the drawing.

You can find the solution in [this PR](https://github.com/facebook/react-native/pull/46081) which already landed internally and will be synched shortly.

I apologize that I have not seen the updated version on Friday and that you spent time on this.

**Comment by zhongwuzw** [comment]
@cipolleschi  Ah, I just looked at that PR. Seems the solution is not much different from mine which is based on UIView and I used the CALayer? Actually I’m worried about performance because CALayer is lighter than UIView  :). But it's ok if the team decides to use UIView. I'll close my PR. :)

**Pull request closed without merging**
