### PR TITLE
Fix BackAndroid subscriptions calls

### PR DESCRIPTION
**Pull request by webzepter**
`BackAndroid` JS event subscriptions should be called in reverse order
(the subscription from the latest `addEventLister` should run first).

Also if listener returns true, don't call other listeners.

**Motivation**: We use `BackAndroid` listeners to prevent closing screens with user's input.
When we have two screens in stack (each screen with listener, which show alerts),
we want to show alert only from the last screen listener, not from all.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by satya164** [comment]
Looks reasonable.

cc @dmmiller will this break internal apps?

**Comment by dmmiller** [comment]
@satya164 perhaps, but it seems like the proper behavior, so let's give it a go.

**Comment by dmmiller** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/546011068943460/int_phab) to review internal test results.

**Pull request closed without merging**
