### PR TITLE
docs/handling-touches Issue - Fixed broken links throughout doc

### PR DESCRIPTION
**Pull request by dazziola**
This pull request is super simple. 

All links in this guide were unresolved and linked to code.facebook.com. I've prepended them all with "/react-native" which will resolve this issue.

### CODE REVIEW

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1780889495531283/int_phab) to review.

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mquandalle** [comment]
These were fixed in 70e97f96448a6af5ee314cf764b1cb609a9dedbf.

**Comment by facebook-github-bot-5** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by hramos** [comment]
@mquandalle good catch. @dazziola please open PRs against the master branch. The core contributors will then cherry-pick commits into the stable branches if needed.

**Pull request closed without merging**
