### PR TITLE
fix getPhotos params on RNTester XHR example.

### PR DESCRIPTION
**Pull request by ericlewis**
## Summary

Fixes redscreen on RNTester's XHR page. CameraRoll getPhotos was missing params.

ss: https://i.imgur.com/JLThyrF.png

## Changelog

[iOS] [Fixed] - RNTester XHR Example crash

## Test Plan

Run RN tester

### CODE REVIEW

**Comment by ericlewis** [comment]
this also fixes the iOS snapshots (yet again)

**Comment by ericlewis** [comment]
@hramos, I noticed you are trying to update the screenshots- I have also done so on this PR & is passing.

**Comment by hramos** [comment]
Great, I’ll merge this once I’m back at my computer. Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hramos** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
