### PR TITLE
[cli] convert project generation to use yeoman

### PR DESCRIPTION
**Pull request by foghina**
* have one parent generator for `index.ios.js`, `.flowconfig` and `.gitignore`
* have one child generator for `ios/**`
* add tests for both

Note: I had to remove the chalk mock as it was interfering with yeoman in the test environment. I added manual `setMock()` calls in the tests that made use of it.

### CODE REVIEW

**Comment by mkonicek** [comment]
This looks good to me! Can you get @frantic to review this?

Tests look good! I assume you've also tried `react-native init` and ran the iOS app and reloaded JS?

**Comment by frantic** [comment]
Overall looks good and e2e tests pass! I'll do another pass tomorrow. My main concern is that now maintaining the template files is going to be a pain.

FYI there is also .watchmanconfig that needs to be copied, see #2263

**Comment by foghina** [comment]
@mkonicek yep, everything works.

@frantic I had to update `scripts/e2e-test.sh` a bit but yes, they pass :). I also added `.watchmanconfig` now.

**Comment by foghina** [comment]
Ping. @frantic @vjeux

**Comment by vjeux** [comment]
Sorry don't have the time to review it but i'm happy with the change

**Pull request merged**
