### PR TITLE
Android: Add support to pass Touch events through native views

### PR DESCRIPTION
**Pull request by stephenkopylov**
## Summary
The main reason explained here:
https://github.com/facebook/react-native/issues/28953

## Changelog
[Android] [Added] - **onTouchEvent**-alternative for JSTouchDispatcher ReactViewGroup

## Test Plan
Now we can easily do things like this:
out

### CODE REVIEW

**Comment by stephenkopylov** [comment]
Don't know why, but circleCI can't find ReactViewGroup.java
Screenshot 2020-05-23 at 17 45 45

If it's necessary, we can rewrite this code using interface (like ReactHitSlopView etc)

**Comment by stephenkopylov** [comment]
I did not touch the iOS code, but the CI is failing on iOS... 
Can anybody re-run this test?

**Comment by sudomann** [comment]
@stephenkopylov I see this PR has been sitting for about a year now 😄

**Comment by stephenkopylov** [comment]
@CezarCobuz sorry for disappearing - I'll try to get back into issue in closest few weeks!

**Comment by ShivamJoker** [comment]
Seems like more than a month 😉

**Comment by adgang** [comment]
Any progress on this? I don't see any alternative to this use case in https://github.com/ibitcy/react-native-hole-view
At least none that is so straightforward.

**Comment by YDaskaloff** [comment]
What's going on here? Is this going to be merged? It's such a good addition to react-native!

**Comment by nvictor-acv** [comment]
WE NEED THIS IN RN, COME ON YOU GUYS! WTF?

**Comment by ranjandsingh** [comment]
Any update on this ?

**Pull request closed without merging**
