### PR TITLE
Fixes #9294

### LINKED ISSUE #9294: react-native link add empty lines in strings.xml
For each package that are linked by `react-native link` an empty string is added into `res/values/strings.xml`.

`react-native unlink` removed them as well.

Is this normal ? Maybe [makeStringsPath](https://github.com/facebook/react-native/blob/7028929d8f44872e790376875c7971155bb99f81/local-cli/rnpm/link/src/android/patches/makeStringsPatch.js#L4-L8) should not add a new line if the package does not contain any parameters.

react-native@0.31.0
react-native-cli@1.0.0

cc @grabbou @Kureev

### PR DESCRIPTION
**Pull request by grabbou**
CC: @Kureev

Fixes #9294

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek to be a potential reviewer.

**Comment by facebook-github-bot-3** [comment]
@grabbou updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9528/files/fda4f95b422a5a08bd4b333433ae7b0be59874f9..872145a71f2d0db3a43d8d994506bc748f5662db)

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3752878) to review internal test results.

**Comment by facebook-github-bot-2** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by grabbou** [comment]
@bestander JS checks on my end are fine, there are no parts that could break the tests here. Any ideas?

**Comment by bestander** [comment]
Travis failed because of network.
Circle because of Buck issues, a rebase would fix it but it is not a problem.
Merge failed because we have internal .flowconfig that I need to fix.
Will be landing in 30 minutes

**Comment by bestander** [comment]
This has landed actually https://github.com/facebook/react-native/commit/107fc72dab6b0189878b7023c08bd9bfad10c160

**Pull request closed without merging**
