### PR TITLE
[feat] Add optional callback on Navigator.pop()

### PR DESCRIPTION
**Pull request by alvarowolfx**
Basically I want to pop from the current scene and go to the next scene, but with the current API doing a ```navigator.pop()``` then ```navigator.push(route)``` will cause a error because the pop transition it's on course when I do a push. I could do a ```navigator.replace(route)``` but this executes without transition.

So this PR add a optional callback function to the pop method, so I can execute something after the transition end.  Something like:

```
let { navigator } = this.props;
navigator.pop( () => {
  navigator.push({ component: NextScene });
});
```

And I also add a helper method called popAndPushRoute, to the same thing above but more simply:

```
let { navigator } = this.props;
navigator.popAndPushToRoute({ component: NextScene });
```

Already tested on my app here, the code is pretty simple, if needed I can make a test repo using this method.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @hedgerwang to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
@alvarowolfx updated the pull request.

**Comment by chirag04** [comment]
`popAndPush` is really unusual and probably not a nice user experience. Seems like you need animated replace. There are PR/issues for animated replace, feel free to search for them. 

If it's a blocker, you can monkey patch navigator with your method. Something like this:
```
Navigator.prototype.popNAndPush = function(route, n) {
  if (n === 0) {
    return;
  }
  this.state.routeStack.splice(this.state.presentedIndex - n + 1, n);
  this.state.sceneConfigStack.splice(this.state.sceneConfigStack - n + 1, n);
  this.state.presentedIndex = this.state.presentedIndex - n;
  this.state.transitionCb = null;
  this.push(route);
};
```

**Comment by chirag04** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-9** [comment]
@chirag04 tells me to close this issue. If you think it should still be opened let us know why.

**Pull request closed without merging**
