### PR TITLE
Expose the testID to black-box testing frameworks on Android

### LINKED ISSUE #7135: testID information not visible on UIAutomator in Appium.
Hi there,

We are doing an automation test for Android (API version 21) on Appium.

And we are using UI Automator Viewer to see the node details information and we need `resource-id` information visible in order to test for unique nodes so we know which elements are being interacted.

But currently, `resource-id` column is empty even though we have applied `testId` property on each `<View>`.

Please close this issue if there is a duplicate, otherwise please advise on what we can do to have each nodes to have unique id's specified from `testId` value provided.

Thanks,

Sam

### PR DESCRIPTION
**Pull request by jdeff**
## Summary

There has been a long-standing issue where black-box testing frameworks like Appium and Xamarin UITest have not been able to access the `testID` view prop for Android (see #7135). A natural place for this to be exposed is via a view's `resource-id`. The `resource-id` is what I have used when working on UIAutomator-based tests for native Android apps and is a non-localized, development-only identifier. As mentioned in the linked ticket, you can dynamically set the resource-id using the view's AccessibilityNodeInfo. This change simply checks to see if a testID is provided for a view and then exposes it through the view's accessibility node delegate.

## Changelog

[Android] [Fixed] - Fixes #7135,  #9942, and #16137. Display the `testID` as the `resource-id` for black-box testing frameworks

## Test Plan

I used the `uiautomatorviewer` tool to verify that the resource-id is populated with the `testID` of a few different views of the RNTester app.
Screen Shot 2020-08-10 at 3 38 27 PM
Screen Shot 2020-08-10 at 3 40 41 PM

### CODE REVIEW

**Comment by jdeff** [comment]
Also fixes #9777 and #16137

**Comment by jdeff** [comment]
Should be a simple, low-risk change. Let me know if there is anything else I can do/provide to move this through.

**Comment by jdeff** [comment]
Quick ping on this PR. Thoughts?

**Comment by jlipps** [comment]
Thanks for this @jdeff, can't speak for RN but from the Appium side it looks like it would remove a lot of headaches for our users!

**Comment by jdeff** [comment]
Just another friendly ping.

**Review by alshamiri5 — APPROVED** [review]

**Comment by jdeff** [comment]
Thanks @alshamiri5!

**Comment by frankitox** [comment]
Hi @jdeff! I was planning on using this PR with patch-package but the resource-id is just not showing up in the UI Automator Viewer. I simply copied the code to the corresponding file in `node_modules`. Am I missing something? I started the Metro server resetting the cache (`react-native start --reset-cache`).

**Comment by jdeff** [comment]
Hi @frankitox! I think `react-native start --reset-cache` only affects javascript files. One thing to try would be cleaning and rebuilding the native code as well (e.g. `cd android && ./gradlew clean`) as this code change is in native-land.

**Comment by frankitox** [comment]
Huh, no luck with it. Still thanks for the hint :+1: ! I hope they merge this one or something similar to fix this problem. For the moment I'll just create a separate appium environment and conditionally change `:accessibilityLabel`'s value.

**Comment by jdeff** [comment]
@frankitox what version of Android are you using? Also, are you able to share the patch file you have and the component where you are setting the `testID`?

**Comment by jdeff** [comment]
@frankitox for reference, here are the two examples that I used in the screenshots above:

https://github.com/facebook/react-native/blob/master/packages/rn-tester/js/examples/JSResponderHandlerExample/JSResponderHandlerExample.js#L55
https://github.com/facebook/react-native/blob/master/packages/rn-tester/js/examples/Pressable/PressableExample.js#L99

**Comment by bitcrumb** [comment]
Would also be interested in seeing this being adopted :) 👍

**Comment by tri-fraga** [comment]
I also would really like to see this happen. Any reason why this is not accepted yet?

**Comment by jdeff** [comment]
@alloy @alshamiri5 any idea who I should reach out to get these changes merged? It's been a couple months and I don't want this to get stale.

**Comment by alloy** [comment]
I’ll ask around, but can’t promise anything.

**Comment by jdeff** [comment]
Thank you!

**Comment by simoreira** [comment]
Any news about this?

**Comment by tmadej** [comment]
To support @jdeff, this solves a huge industry problem for cross-platform test automation, especially users of appium & webdriverio. I know at least 40+ devs that would benefit from this. When can we get this merged in?

**Comment by bitcrumb** [comment]
Would really love to see this land as well. We now have to resolve to workarounds to be able to properly use Appium for testing.

**Comment by TwFlem** [comment]
@frankitox or for anyone else who'd like to try this in their own project.

patch-package will not work, you'll have to build Android from source.

With such a small change like this, the easiest thing to do is use the [community docker container](https://hub.docker.com/r/reactnativecommunity/react-native-android) mentioned in this [building from source documentation](https://github.com/facebook/react-native/wiki/Building-from-source#publishing-to-a-git-fork-dependency). Trying to build from source locally so you can test locally has some complexity. I wouldn't recommend it in this case.

Make sure you pull the right image. For example, in the particular project, we are on 0.62.2. I had to find the date that 0.62.2 was released and match that up as closely as I could to tags in dockerhub. In this case, it the image was reactnativecommunity/react-native-android:2020-4-1.


@jdeff 

Thank you! Who knew the solution to this problem all these years was this small change? 

This contribution is a huge step that allows developers to add E2E test automation to their apps without comprising the quality to their users with disabilities. I hope it gets merged in soon so we can see higher quality and more accessible react native apps across the board.

**Comment by MrLoh** [comment]
@yungsters @JoshuaGross @shergin sorry to ping, I am sure there is an insane amount of stuff going on in this project. But this tiny PR solves a problem that people have had to work around for 4 years unsuccessfully by introducing a degraded experience to vision impaired users to make the largest testing framework in the mobile world work with react native. It would be really great if you could give it some serious consideration, making Appium easier to use with React Native would have a big impact on building well tested applications for medical device related apps or other apps that have to adhere to very strict regulatory standard where detox doesn't quite cut it for E2E testing.

**Comment by frankitox** [comment]
Thank you for shedding some light on this @TwFlem :smiley:, I suppose you need to build Android because the PR modifies a `.java` file. At the time I just gave up and created a special testing environment then sprinkled some ifs thoughout the code base to either test or show proper descriptions. As you said, hope they merge this one, will save a lot of headaches.

**Comment by johnsonj561** [comment]
Thanks @jdeff. Being able to use Appium without sacrificing accessibility is absolutely essential. I'm really hoping to see this get merged soon 🙏

**Comment by yungsters** [comment]
I haven’t looked at this PR, yet. But I wanted to set expectations that the team is currently on a holiday and will likely not get to this until at least Monday. (For anyone else who celebrates it here, Happy Thanksgiving!)

**Comment by jdeff** [comment]
Thanks for the response @yungsters. Happy Thanksgiving!

**Comment by MrLoh** [comment]
@yungsters thanks for taking a look and happy thanksgiving. We are all incredible thankful for the great work being done on react native by the core team and the community.

**Comment by tmadej** [comment]
@yungsters Thanks for looking into this! Happy belated thanksgiving! 🦃

**Comment by thinlizee** [comment]
@yungsters thanks for taking a look! Much obliged 👍

**Comment by tmadej** [comment]
This would be an awesome holiday present for the test automation community. 🎁

**Comment by jocimarcan** [comment]
@jdeff Thank you for that contribution!
 This works perfectly on most components, except for the TextInput component. Did you get to test for TextInput? Was it expected to work for that component as well?

**Comment by hubastard** [comment]
@jocimarcan I've also noticed that the testID is not working for the EditText and the Slider components.

### The issue
The issue is that both the EditText and Slider components are using `AccessibilityDelegateCompat` instead of `ReactAccessibilityDelegate`.

### The fixes
In `ReactEditText.java`, you must replace [this line](https://github.com/facebook/react-native/blob/3dda7ee43843991ad06036c6a15f0ae41585afe5/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L158) with `new ReactAccessibilityDelegate()` instead of `new AccessibilityDelegateCompat()`

In `ReactSliderManager.java`, you must replace [this line](https://github.com/facebook/react-native/blob/3dda7ee43843991ad06036c6a15f0ae41585afe5/ReactAndroid/src/main/java/com/facebook/react/views/slider/ReactSliderManager.java#L281) with `extends ReactAccessibilityDelegate` instead of `extends AccessibilityDelegateCompat`

**Comment by MrLoh** [comment]
Is there a PR out for this already to get it into the next RN release?

**Comment by hubastard** [comment]
I'll open one right now and link it to this one.

**Comment by jocimarcan** [comment]
@hubastard thanks for the detailed suggestion!
I replaced these lines in react-native 0.64.0, but TextInput testID is not getting mapped into EditText resource-id yet.
I also tried to add some imports like `import com.facebook.react.uimanager.ReactAccessibilityDelegate;`, but without success.
Do you have some public branch repo with these changes?

**Comment by sasmit** [comment]
@TwFlem as per your comment above https://github.com/facebook/react-native/pull/29610#issuecomment-732302973
1) First I tried through by following the steps from https://github.com/facebook/react-native/wiki/Building-from-source but there was some ndk related issue. so I gave up this approach
2) Second I tried is "use the community docker container mentioned in this building from source documentation". Below are the things I did so far
a) Download the "docker desktop" software for windows
b) Ran below command
docker run --rm --name rn-build -v $PWD:/pwd -w /pwd reactnativecommunity/react-native-android:2020-4-1 /bin/sh -c "./gradlew installArchives"

Next step is https://github.com/facebook/react-native/wiki/Building-from-source#publishing-to-a-git-fork-dependency
but i am not able to find the binary image which it generated at step 2(b). 
I just see this in docker desktop tool

image

**Comment by hubastard** [comment]
@sasmit I've also used docker to generate a new version and it generated an `Android` folder inside my react-native repo at the root. You should find the .aar and .jar files in there.

**Comment by sasmit** [comment]
> @sasmit I've also used docker to generate a new version and it generated an `Android` folder inside my react-native repo at the root. You should find the .aar and .jar files in there.

@hubastard If I understood correctly then I must run the docker command (docker run --rm --name rn-build -v $PWD:/pwd -w /pwd reactnativecommunity/react-native-android:2020-4-1 /bin/sh -c "./gradlew installArchives") from react-native repo folder ?
If thats the case then its my bad I did not run the command from there

**Comment by hubastard** [comment]
Yes in my case I ran the docker command from  the root of my react-native fork. Also, you can look at the logs of the docker command to see if the android build was successful.

**Comment by sasmit** [comment]
@hubastard Thanks for your quick response .
I will do that now. 

It would be really helpfull for me if you just point out the next steps you did afte running the docker command.
I am new to react-native and struggling at same point from last 3 days.

**Comment by sasmit** [comment]
I also ran the docker command from the root of my react-native fork. but I did not see the Android folder generated there. Below is the logs

C:\Sasmit\Work\Project\fork\Twfl\react-native>docker run --rm --name rn-build -v $PWD:/pwd -w /pwd reactnativecommunity/react-native-android:2020-4-1 /bin/sh -c "./gradlew installArchives"
Unable to find image 'reactnativecommunity/react-native-android:2020-4-1' locally
2020-4-1: Pulling from reactnativecommunity/react-native-android
5bed26d33875: Pull complete
f11b29a9c730: Pull complete
930bda195c84: Pull complete
78bf9a5ad49e: Pull complete
7c10d6954d08: Pull complete
64ab726f9d7a: Pull complete
15977c5df74e: Pull complete
4dc52d9ee7ae: Pull complete
c153bb21d243: Pull complete
Digest: sha256:6aebebd3cdaf580c996a5a5965d05e8702750bc26039226c18b7b22d8764d197
Status: Downloaded newer image for reactnativecommunity/react-native-android:2020-4-1
docker: Error response from daemon: create $PWD: "$PWD" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by sasmit** [comment]
Created a sample app with testID to resource-id implementation on react-native 0.64.0 version. verified many components and its working fine. Thanks  a lot to @jdeff 

link : https://github.com/sasmit/sampleAppTestidToResourceId

**Comment by codedaemon12** [comment]
Is it working with TextInput ? I created one and added testID but don't seem to find resource-id. I am seeing resource id for labels.

**Comment by cpdyj** [comment]
Now I have the same problem as  appium/appium#15354 . The behaviour is real strange. What's the best practice when I facing the problem?

**Comment by liweijian** [comment]
> @jocimarcan I've also noticed that the testID is not working for the EditText and the Slider components.
> 
> ### The issue
> The issue is that both the EditText and Slider components are using `AccessibilityDelegateCompat` instead of `ReactAccessibilityDelegate`.
> 
> ### The fixes
> In `ReactEditText.java`, you must replace [this line](https://github.com/facebook/react-native/blob/3dda7ee43843991ad06036c6a15f0ae41585afe5/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L158) with `new ReactAccessibilityDelegate()` instead of `new AccessibilityDelegateCompat()`
> 
> In `ReactSliderManager.java`, you must replace [this line](https://github.com/facebook/react-native/blob/3dda7ee43843991ad06036c6a15f0ae41585afe5/ReactAndroid/src/main/java/com/facebook/react/views/slider/ReactSliderManager.java#L281) with `extends ReactAccessibilityDelegate` instead of `extends AccessibilityDelegateCompat`

Just out of curiosity , is there any PR on fixing these components' `testID` ?

**Comment by hubastard** [comment]
@liweijian Yeah, I forgot to create one back then, here is the PR now #31865

**Pull request closed without merging**
