### PR TITLE
Fixing another iOS app extension unsafe API usage in react native

### PR DESCRIPTION
**Pull request by shrutic**
Thanks for submitting a PR! Please read these instructions carefully:

- [yes] Explain the **motivation** for making this change.
    Using react-native library inside iOS app extension causes a compile error inside react native stating that usage of UIAlertView is not allowed inside iOS app extension and should use UIAlertController instead. I have updated the code to use UIAlertController based on the other instances of the UIAlertController usage in the react-native library

- [ partial ] Provide a **test plan** demonstrating that the code is solid.
This code should be launched when developers start the profiler from the React native debug menu. I am currently in process of upgrading my app from 0.34 to the latest react native ( aka app not in working state). Would appreciate if there is an alternative way for me to test this functionality out.

Just tried to create a new react-native project using "react-native init testproject" and upon running "react-native run-ios", I  hit the following error and hence I could not test the debug menu Performance profiler alert.
image

- [ yes ] Match the **code formatting** of the rest of the codebase.
- [ yes ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

What existing problem does the pull request solve?

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

## Next Steps

Sign the [CLA][2], if you haven't already.

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by dannyharding10** [comment]
@shrutic Do you have any update on the status of this and your other related merge requests? (#14263 and #13227) I would really like to use react-native in an iMessage application but these issues make it impossible :(

**Comment by shrutic** [comment]
Nope. I need a sign off that the fb engineers are not giving

Shruti

**Comment by shrutic** [comment]
I forgot to mention. I created my own repo of react native and pointed my app to that repo with required changes. We need to periodically update it either the master branch. Hope this option works for you

Shruti

**Comment by dannyharding10** [comment]
What changes did you need to make to your fork in order to get it to work?

**Comment by shrutic** [comment]
The 2 Pull requests that you pointed in your previous message. 

Shruti

**Comment by dannyharding10** [comment]
Great, thank you for your help @shrutic!

**Pull request closed without merging**
