### PR TITLE
[Docs] Add debugging with Stetho instructions #934

### PR DESCRIPTION
**Pull request by RakanNimer**
**Motivation** : Debugging RN with Stetho is very helpful but not very well documented.

**Result Screenshot**

debugging-with-stethos-screenshot

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @JoelMarcey to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/484406568422463/int_phab) to review internal test results.

**Pull request closed without merging**
