### PR TITLE
Adding Zribbble

### PR DESCRIPTION
**Pull request by catalinmiron**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @brentvatne to be potential reviewers.

**Comment by satya164** [comment]
Can you move this to the end? The list is alphabetical.

**Comment by catalinmiron** [comment]
@satya164 done.

**Comment by lacker** [comment]
It gets sorted so you don't have to move it to the end. But - the link should be to news coverage to meet the guidelines. It seems like there is not currently news coverage or technical content about Zribbble, so although the app seems pretty cool, I think that it does not currently meet the guidelines for inclusion in the showcase.

**Comment by catalinmiron** [comment]
@lacker thanks! I'll reopen the PR once I have a post about it.

**Pull request closed without merging**
