### PR TITLE
Remove Unnecessary @Override for Examples/UIExplorerActivity.java

### PR DESCRIPTION
**Pull request by leeight**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @janicduplessis to be potential reviewers.

**Comment by lexs** [comment]
Overrides are never unnecessary as they communicate intent. `@Override` on a non-overridden method is an error in Java.

**Comment by leeight** [comment]
@lexs Due to this commit https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d, `getBundleAssetName`, `getJSBundleFile`, `getJSMainModuleName`, `getUseDeveloperSupport`, `getPackages` were removed from `ReactActivity.java`. So in the subclass `UIExplorerActivity.java`,  `@Override` is not necessary for `getBundleAssetName`, `getJSBundleFile` and `getPackages`, which will cause compile errors.

**Comment by lexs** [comment]
@leeight I see, but in that case wouldn't removing `@Override` only perhaps make this compile but it would still be broken as nobody will call those methods? This seem to require more work to fix it.

**Comment by leeight** [comment]
@lexs Thanks for your comment. I post a new PR which fixed uiexplorer and movies examples. https://github.com/facebook/react-native/pull/8223

**Pull request closed without merging**
