### PR TITLE
Android: Add setLaunchOptions to ReactRootView

### PR DESCRIPTION
**Pull request by funorpain**
**Motivation**

When ReactRootView is used in a Android layout file, its properties is expected to be changeable at run time like other native views. iOS RCTRootView has a method named setAppProperties, but no such method found on Android.

**Test plan (required)**

Create a Android project for TicTacToe example.

Modify TicTacToeApp.js in Examples/TicTacToe:

Change from
`<Text style={styles.title}>EXTREME T3</Text>`
to
`<Text style={styles.title}>EXTREME T3 {this.props.title}</Text>`

Implement a TicTacToeActivity:
```java
public class TicTacToeActivity extends ReactActivity {
  private String mTitle;

  @Override
  protected String getMainComponentName() {
    return "TicTacToeApp";
  }

  @Nullable
  @Override
  protected Bundle getLaunchOptions() {
    Bundle args = new Bundle();
    args.putString("title", mTitle);
    return args;
  }

  @Override
  public boolean onKeyUp(int keyCode, KeyEvent event) {
    if (keyCode == KeyEvent.KEYCODE_1 || keyCode == KeyEvent.KEYCODE_2) {
      mTitle = keyCode == KeyEvent.KEYCODE_1 ? "1" : "2";
      notifyLaunchOptionsChanged();
    }
    return super.onKeyUp(keyCode, event);
  }
}
```

Launch TicTacToe app in an emulator, press 1 or 2, you can see the title is changed.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @cjhopman and @foghina to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @cjhopman as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by satya164** [comment]
cc @foghina

**Comment by foghina** [comment]
AFAICT this requires restarting the app when calling `setLaunchOptions`? This is highly inefficient and I'd rather have a placeholder in XML that gets replaced with a `ReactRootView` in `onCreate` with the correct launch options.

**Comment by foghina** [comment]
I'd rather not add this API for the reasons stated above. Feel free to reopen if I misunderstood something.

**Pull request closed without merging**
