### PR TITLE
Cleanup packager dead debug endpoint

### PR DESCRIPTION
**Pull request by belemaire**
When trying to access the debug dependency graph through the `/debug/graph` endpoint of the packager server (documented in the packager README and listed as well when hitting the root `/debug` endpoint), all I am getting back is a nasty HTTP 500 error :'(

What triggers this HTTP 500 is a `TypeError` being thrown while trying to access a function that doesn't exists (anymore). Here is the error log of the packager when trying to access this endpoint :

```
TypeError: this._depGraph.getDebugInfo is not a function
    at Resolver.getDebugInfo (index.js:270:27)
    at Bundler.getGraphDebugInfo (index.js:575:27)
    at Server._processDebugRequest (index.js:369:28)
    at Server.processRequest (index.js:423:12)
    at next (/Users/blemair/Code/DependencyGraphTest/node_modules/connect/lib/proto.js:174:15)
    at Object.module.exports [as handle] (cpuProfilerMiddleware.js:17:5)
    at next (/Users/blemair/Code/DependencyGraphTest/node_modules/connect/lib/proto.js:174:15)
    at Object.module.exports [as handle] (systraceProfileMiddleware.js:17:5)
    at next (/Users/blemair/Code/DependencyGraphTest/node_modules/connect/lib/proto.js:174:15)
    at Object.module.exports [as handle] (statusPageMiddleware.js:19:5)
```

Ultimately this is due to the call to `this._depGraph.getDebugInfo()`.   
`_depGraph` here is an instance of the `DependencyGraph` class exported by `node_haste` module. After taking a look at the class from this module, there is indeed no `getDebugInfo()` method defined in this class (and it is not added to the `DependencyGraph` prototype anywhere in the packager code from what I can see).

I don't really know if this is an issue or just a dead endpoint for which documentation and code was not cleaned up. Anyway, I ultimately thought that opening a PR would be more appropriate than opening an issue as it'll help reviewer pinpoint in the code what I am talking about more precisely (by looking to the small commits). And in case this is indeed dead stuff (for now), then at least this PR is up and ready to clean things up quick and easy ;) If not, just close it and open an issue ;P

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @davidaurelio and @martinbigio to be potential reviewers.

**Comment by bestander** [comment]
Yeah, it looks like this endpoint was added more than a year ago when the project was open sourced.
I don't see any debug info on dependency graph in node-haste.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/246827542354218/int_phab) to review.

**Pull request closed without merging**
