### PR TITLE
[cli] Remove 'react-native link'

### PR DESCRIPTION
**Pull request by mkonicek**
`react-native link` was an early experiment, [rnpm](https://github.com/rnpm/rnpm) does this much better. After merging this PR we should merge rnpm so that `react-native link` works again :)

@grabbou @Kureev Just making some space here :)

This reverts 4e5a2bc0791a77ac67c2b564a220278bea889fcf.

**Test Plan**

e2e tests on Travis and CircleCI

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @martinbigio and @sam-swarr to be potential reviewers.

**Comment by josemariadelgado** [comment]
:shipit:

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
screen shot 2016-04-29 at 12 45 07 pm

**Comment by grabbou** [comment]
Thanks! We have some exciting plans ahead #topsecret

**Pull request closed without merging**
