### PR TITLE
Fix TextInput shadow props not update when setText on iOS

### LINKED ISSUE #20224: [0.56][iOS] TextInput setNativeProps({ text }) not working second time
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 250.06 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.0
        API Levels: 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-scripts: 1.14.0
```

## Description
On iOS, `TextInput.setNativeProps({ text })` works only the first time for the same `text`.
Example, I set the text `"ReactNative"` on `TextInput`, then use keyboard to change text to `"React"`, then set `"ReactNative"` again, it's not working and keeping `"React"`.

See the below gif:

bug

If I don't use the same `text`, it works every time.

This looks similar to #18272 but it's not the same. It's happen to all texts, not just empty string or calling `clear()`.

## Reproducible Demo

```js
import React from "react";
import { View, Text, TextInput, TouchableOpacity } from "react-native";

export default class App extends React.Component {
  state = {
    isReactNative: true
  };

  insertText = () => {
    this.textInput.setNativeProps({ text: "ReactNative" });
  };

  render() {
    return (
      <View style={{ paddingTop: 128, alignItems: "center" }}>
        <TextInput
          style={{
            width: "100%",
            backgroundColor: "#ccc",
            fontSize: 48,
            textAlign: "center"
          }}
          ref={ref => {
            this.textInput = ref;
          }}
        />

        <TouchableOpacity style={{ padding: 16 }} onPress={this.insertText}>
          <Text style={{ fontSize: 24 }}>Insert ReactNative</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

```

The code below will work because it switches the text everytime:

```js
  insertText = () => {
    this.textInput.setNativeProps({
      text: this.state.isReactNative ? "ReactNative" : "Native"
    });

    this.setState(prev => ({ isReactNative: !prev.isReactNative }));
  };
```

### PR DESCRIPTION
**Pull request by zhongwuzw**
Fixes #20224

Test Plan:
----------
The code as below, click `TouchableOpacity`, click textInput , edit text, then click `TouchableOpacity` again.

```
import React from "react";
import { View, Text, TextInput, TouchableOpacity } from "react-native";

export default class App extends React.Component {
  state = {
    isReactNative: true
  };

  insertText = () => {
    this.textInput.setNativeProps({ text: "ReactNative" });
  };

  render() {
    return (
      <View style={{ paddingTop: 128, alignItems: "center" }}>
        <TextInput
          style={{
            width: "100%",
            backgroundColor: "#ccc",
            fontSize: 48,
            textAlign: "center"
          }}
          ref={ref => {
            this.textInput = ref;
          }}
        />

        <TouchableOpacity style={{ padding: 16 }} onPress={this.insertText}>
          <Text style={{ fontSize: 24 }}>Insert ReactNative</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```

Release Notes:
----------
 [IOS] [BUGFIX] [TextInput] - Fix TextInput shadow props not update when update local data.

### CODE REVIEW

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :clipboard: Release Notes - <i>This PR appears to be missing Release Notes.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by zhongwuzw** [comment]
@hramos Emm, I think it's not the cause from [RCTBaseTextInputView.m](https://github.com/facebook/react-native/blob/master/Libraries/Text/TextInput/RCTBaseTextInputView.m#L121). because we only call it when we compare it wether changed in [shadow view](https://github.com/facebook/react-native/blob/bbc1af65366ebef5e055857a1d4eff56b86e6024/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m#L161). And because we don't update the `text` of `RCTBaseTextInputShadowView`, leads to [wrong comparison](https://github.com/facebook/react-native/blob/bbc1af65366ebef5e055857a1d4eff56b86e6024/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m#L133).

**Comment by cpojer** [comment]
What's the status of this PR?

**Comment by zhongwuzw** [comment]
I'll closing this because the issue already fixes.

**Pull request closed without merging**
