### PR TITLE
Update documentation to use newer version of fresco - fixes #13345

### LINKED ISSUE #13345: [Android] Regression with animated gifs in react native 0.43 - hard crash
### Description

After the upgrade to react native 0.43 from 0.42 our app crashes hard on the display of animated gifs.

### Reproduction Steps and Sample Code

In http://facebook.github.io/react-native/releases/0.43/docs/image.html#gif-and-webp-support-on-android you describe how to use animated gifs with react native. Basically it's adding one line to `android/app/build.gradle`:

    compile 'com.facebook.fresco:animated-gif:0.11.0'

and then just using the Image tag.

As a repro we did that on top of hello world sample:

* https://github.com/forki/GifRepro <- broken with RN 0.43
* https://github.com/forki/GifRepro/tree/r42 <- working with RN 0.42

For repro:

1) Clone the project
2) Check out a branch
3) run `npm install`
4) open android emulator
5) run `react-native run-android`

### Additional Information

* React Native version: 0.43.1 and 0.43
* Platform: Android
* Development Operating System: Windows 10
* Dev tools: Command line

### PR DESCRIPTION
**Pull request by forki**
Thanks for submitting a PR! Please read these instructions carefully:

## Motivation (required)

React Native crashes hard on fresco 0.11.0 - see #13345

## Test Plan (required)

Repro case in #13345

### CODE REVIEW

**Comment by AndrewJack** [comment]
As of 0.43.0 react native uses Fresco 1.0.1, could you change to that version?

https://github.com/facebook/react-native/blob/0.43-stable/ReactAndroid/build.gradle#L280

**Comment by forki** [comment]
@AndrewJack confirmed. it works. I updated the PR

BUT: I think this will probably break again with future RN update ;-(

**Comment by AndrewJack** [comment]
@forki It probably will. Ideally the release notes would detail it as a breaking change.

Always worth checking the versions that react native uses when upgrading.

**Comment by forki** [comment]
there is no way to bundle it automatically with the correct version? or make the upgrade tool fix it at least?

**Comment by AndrewJack** [comment]
Upgrade tool won't work in this case because the fresco addons are optional.

The extra fresco dependencies weren't included in the react native library to reduce the app size for people who don't need the extra fresco features.

**Comment by forki** [comment]
Upgrade tool could be smart and to string replacement. But I assume release
notes will be good enough.

Am 10.04.2017 16:30 schrieb "Andrew Jack" <notifications@github.com>:

**Pull request closed without merging**
