### PR TITLE
Compatible with react native windows

### PR DESCRIPTION
**Pull request by sm2017**
In react native windows `MainPage.cs` is renamed to `MainReactNativeHost.cs`

## Motivation

Compatibility with react-native-windows

## Test Plan

N/A

## Related PRs
N/A

## Release Notes

[ CLI ] [BUGFIX] [local-cli/core/windows] - To be compatible with react native windows new changes

### CODE REVIEW

**Comment by sm2017** [comment]
Please accept the PR

**Comment by sm2017** [comment]
@facebook , I just change 1 line and After a month the bot request rebase?

**Comment by hramos** [comment]
The `windows` folder was removed in https://github.com/facebook/react-native/commit/a40bfa730e05c68da49e6f217ae0f161dcc7ba98#diff-2e0c111cfda40b14855cb446fc70c150, it's why the PR doesn't apply and can't be merged today.

**Comment by hramos** [comment]
Closing because it doesn't seem like this can be fixed in this repo, but happy to re-open if I am wrong.

**Pull request closed without merging**
