### PR TITLE
Updated trouble shooting doc for "watchman taking too long to load" error

### PR DESCRIPTION
**Pull request by linshu123**
Added another workaround - initiate a source control repository

### CODE REVIEW

**Comment by linshu123** [comment]
Someone has documented this workaround: #2042. I believe it should be on the trouble shooting page.

**Comment by andismith** [comment]
Please can this be merged in to the troubleshooting doc as it's caused my team some headaches, which would have taken less time to figure out had this been included.

**Comment by javache** [comment]
@wez: can you confirm that this is a legitimate workaround? Is @frantic's https://github.com/facebook/react-native/commit/1e1efce69b4b7e188a9de8d3e905ff93ad160b0c a sufficient fix?

**Comment by wez** [comment]
@frantic's fix should be sufficient.  It is true that having source control initiated will also resolve this, but the presence of a `.watchmanconfig` file is the definitive signal to watchman on locating the root of the repo.

**Pull request closed without merging**
