### PR TITLE
removed image! and replaced with .img/

### PR DESCRIPTION
**Pull request by anback**
Tried the UI Explorer on 0.14 stable branch, this is what i had to do to get it working

### CODE REVIEW

**Comment by ide** [comment]
Could you actually apply this commit to a branch based on master, and send a PR to merge it into master?

**Comment by mkonicek** [comment]
Thanks for doing this! Can you please provide a "Test plan"? This would be ideally screenshots from the Movies app and each example in the UIExplorer you're changing.

**Comment by facebook-github-bot-2** [comment]
@vjeux would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by anback** [comment]
I vieux!

Forget it, it was my first PR, ill send you better ones in the near future! 

Cheers
A

**Comment by vjeux** [comment]
No worries :) Let's close it for now since it's been a while

**Pull request closed without merging**
