### PR TITLE
Fixed nvm for travis CI

### PR DESCRIPTION
**Pull request by bestander**
NVM started failing on Travis

Test Plan:
- see Travis results

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @ide and @spicyj to be potential reviewers.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/289969441334301/int_phab) to review.

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/289969441334301/int_phab) to review.

**Pull request closed without merging**
