### PR TITLE
Bugfix - Typos

### PR DESCRIPTION
**Pull request by jutaz**
Fixed few typos in `./Examples` and `./Libraries` folders.

### CODE REVIEW

**Comment by satya164** [comment]
OMG, that's a lot. Thanks :)

One request, can you separate the changes inside `docs/` folder to another PR? The docs are not stored in the FB internal repo, so the patch will not go through.

**Comment by jutaz** [comment]
Sure thing, will do that in a few minutes

**Comment by jutaz** [comment]
Updated. Will open up separate PR for `./docs`

**Comment by satya164** [comment]
Thanks @jutaz

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
