### PR TITLE
Explain custom configuration debugging gotcha

### PR DESCRIPTION
**Pull request by jeffbowen**
Debugging tools won't work if you're using a custom configuration and Cocoapods and didn't specify the configuration to be a `debug` configuration using the `xcodeproj` setting in your Podfile. When integrating React Native into an existing Xcode project, this is a common situation to encounter.

See https://github.com/facebook/react-native/issues/2246#issuecomment-217187621

### CODE REVIEW

**Comment by hfossli** [comment]
Lgtm

**Comment by facebook-github-bot-8** [comment]
@jeffbowen updated the pull request.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/498028643723744/int_phab) to review.

**Pull request closed without merging**
