### PR TITLE
Make UIExplorerExampleContainer static to avoid re-render

### PR DESCRIPTION
**Pull request by littlesome**
This PR solves issue #9948 

NavigationCard no longer implements shouldComponentUpdate (RN 0.33), so
it’s scene’s responsibility to do this.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @mmmulani to be a potential reviewer.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mmmulani** [comment]
@facebook-github-bot import

**Comment by javache** [comment]
Could you implement this method by actually checking the props? E.g. just verify that this.props.module is not different?

**Comment by hramos** [comment]
@littlesome can you resolve the conflicts?

**Comment by lacker** [comment]
It looks like this pull request has been abandoned. I'm going to close it but if you are still interested in working on this please feel free to reopen it!

**Pull request closed without merging**
