### PR TITLE
Adding Sleeperbot to Showcase

### PR DESCRIPTION
**Pull request by weixiyen**
Adding Sleeperbot to Showcase.

Apple is featuring us in their Fantasy Football section, currently a 5 star app, one of the more complicated apps to show off RN capabilities.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @alexleventer to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-4** [comment]
@weixiyen updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9716/files/5c59daaeae3014a4d544a3d5c97daa15ade6df6f..e5822a2a38bacf62128615a102cb923aef328c78)

**Comment by facebook-github-bot-7** [comment]
@weixiyen updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9716/files/5c59daaeae3014a4d544a3d5c97daa15ade6df6f..e5822a2a38bacf62128615a102cb923aef328c78)

**Comment by mkonicek** [comment]
Ping @lacker.

**Comment by lacker** [comment]
Hi, thanks for your pull request! The guidelines in the showcase state:

Thousands of applications use React Native, so we can't list all of them
in our showcase. To be useful to someone looking through the showcase,
either the app must be something that most readers would recognize, or the makers of the application must have
posted useful technical content about the making of the app. It also must be useful considering that the majority
of readers only speak English. So, each app in the showcase should link to either:
1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native
For each app in the showcase, use infoLink and infoTitle to reference this content.

It looks like this submission doesn't meet the guidelines above. I'm going to close this pull request, but feel free to reopen if the situation changes in the future. Thanks again for your submission.

**Comment by weixiyen** [comment]
Hi @lacker 

Could you be more specific on what part of the guideline we didn't meet?

I linked my medium post in the submission.

Sleeperbot is pretty well known for anyone who plays fantasy football.  Our app is also near the top in terms of downloads and star ratings when compared to the other apps in the showcase.  Only Facebook, Facebook Groups, QQ and Discord have more DAU than us in their apps.

Our startup is also funded.

Could it be that the article needed to be more technical?

Please let me know!

Thanks,

Weixi

**Comment by lacker** [comment]
I was looking at:

https://www.crunchbase.com/organization/sleeperbot#/entity

Usually I go by crunchbase or just a google search for news for a company announcement.

I think the blog post is good, we just want to make sure that the brands we reference have other supporting information about them. Like is there any public information about your funding?

**Comment by weixiyen** [comment]
Fair enough, we will get all this information updated.  It's a medium sized seed round.  Will ping again once we get all that in order.

**Pull request closed without merging**
