### PR TITLE
NavigatorIOS: stopPropagation on navigationComplete event. Fixes #1241

### LINKED ISSUE #1241: NavigatorIOS crashes when "pushing" to a new route
Error message:

```
Invariant Violation: No navigator item should be pushed without JS knowing about it 1 0"
```

The red screen is displayed as soon as a new route is pushed.

Sample app available at https://github.com/sharathprabhal/TestNavigatorIOS

screen shot 2015-05-11 at 8 46 58 pm

### PR DESCRIPTION
**Pull request by ephemer**
With nested NavigatorIOS components:

```
<NavigatorIOS initialRoute={{
  component: ComponentWithAnotherNavigatorIOSInSubtree
  title: 'xyz'
}}>
```

Navigating (via push etc.) in ComponentWithAnotherNavigatorIOSInSubtree's `navigator` caused an invariant error, making apps with this structure unusable. The reason was that the `navigationComplete` nativeEvent was being propagated to the outer Navigator due to React's automatic event bubbling, making the outer NavigatorIOS incorrectly think it was holding navigation stack state inconsistent with its native UINavigationController.

Concretely, if the outer navigation stack is empty except for its initial state and something is pushed onto the inner stack, the outer NavigatorIOS suddenly complains that it has 2 items on its stack rather than 1. In reality, the outer Navigator still only has 1 item on its stack but the inner Navigator's event (containing information about the inner Navigator) incorrectly bubbles up and reaches the outer Navigator too. 

The event bubbling in question was automatic and almost certainly unintentional, so preventing it should not cause unintended side-effects.

See demo repo in the OP at #1241 for more a more detailed example.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @jacobp100 to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-8** [comment]
@ephemer updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9828/files/27251821f75c2d60967954dd420ba59a0e9a95da..d4df28151c5c67c80d6ee7b19ca6ce8fd61b62c9)

**Comment by nerdmed** [comment]
@caabernathy @jacobp100 any updates here? Seems pretty straight forward as its a one line change.

**Comment by jacobp100** [comment]
Sorry, looks like I was included to review this, although I’ve never worked on this bit of code!

**Comment by nerdmed** [comment]
@jacobp100 any idea who could be responsible to merge this?

**Comment by jacobp100** [comment]
@nerdmed I’m not sure. Sorry!

**Comment by nerdmed** [comment]
@vjeux @sahrens @hramos @spicyj someone here ready to review/merge this one-line fix for this really annoying bug 🔨  👍

**Comment by vjeux** [comment]
@ericvicenti can you please look into it? Thanks!

**Comment by ericvicenti** [comment]
Sure, this seems like the right way to fix the problem.

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
