### PR TITLE
[TextInput] returnKeyType, enablesReturnKeyAutomatically, secureTextEntry, more keyboardTypes

### PR DESCRIPTION
**Pull request by ide**
This diff completes adding support for the following UITextField properties:

- returnKeyType: what the return key on the keyboard says
- enablesReturnKeyAutomatically: the return key is disabled iff there is no text entered. This too could be implemented in React but it feels better in UIKit right now because it is handled synchronously.
- secureTextEntry: obscure passwords
- keyboardType: added all the keyboard types, they are useful in different scenarios

There were varying degrees of support for these properties so it looks like this diff continues some unfinished work. I also updated the keyboardType enum to use native constants instead of strings like the other properties here.

Added examples to the UIExplorer.

### CODE REVIEW

**Comment by ide** [comment]
Fixes the secure text field request in #245

**Comment by a2** [comment]
I CANT USE PHABRICATOR MACROS HERE MY POWERS ARE USELESS
But actually this looks good to me star ship it.

**Comment by ide** [comment]
@a2 awesometown

I would be 80% serious if I said to move the code review off of GitHub and onto Phabricator. Phacility has done a really great job making the flow intuitive compared to other products.

**Comment by spicyj** [comment]
@ide Yeah, hhvm uses Phabricator (reviews.facebook.net) now and it's something we could look at doing here and on React too.

**Comment by vjeux** [comment]
This has been requested many times, need to merge it asap

**Comment by tadeuzagallo** [comment]
Landed internally, will be out on the next sync

**Comment by ide** [comment]
Thanks for the code review guys

**Comment by mrtom** [comment]
@ide, @a2 any idea when this will be in a released version of reactive-native?

**Comment by a2** [comment]
It should have been synced by now?

**Comment by tadeuzagallo** [comment]
Yes, it was synced on 9a4ee17adba756e676ea2585e13ca4e5884801a5

**Comment by mrtom** [comment]
But that's not been pushed out via NPM, right?

**Comment by mrtom** [comment]
Ignore me, I'm being a muppet... Sorry!

**Comment by billinghamj** [comment]
Any chance you guys could work publicly on github rather than syncing from an internal repo?

**Comment by spicyj** [comment]
Internal commits are now synced out within minutes so there's not a huge difference.

**Pull request closed without merging**
