### PR TITLE
XMLHttpRequest withCredentials defaults to "true"

### PR DESCRIPTION
**Pull request by DanielZlotin**
see https://github.com/facebook/react-native/issues/14063

### CODE REVIEW

**Comment by talkol** [comment]
This PR is necessary to fix the breaking change until the discussion in https://github.com/facebook/react-native/issues/14063 is completed

**Comment by satya164** [comment]
Thank you for the PR.

@facebook-github-bot shipit

**Comment by grabbou** [comment]
Going to cherry pick this as soon as it lands

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
@ericvicenti is working on getting this landed today

**Pull request closed without merging**
