### PR TITLE
Add nightly build

### PR DESCRIPTION
**Pull request by sweggersen**
Note: I'm currently testing this, so do not review just yet.

## Summary

Adding a nightly CI build in preparation for further work on [React Native: Benchmark Suite](https://github.com/react-native-community/discussions-and-proposals/issues/186.)

Currently it will only run the job `nightly_job` which will simply run `$ echo "Nightly build run"`. The plan is to do nightly checks and performance status on the React Native repo, and create a dashboard where we can see performance changes over time. More on this in the proposal: [React Native: Benchmark Suite](https://github.com/react-native-community/discussions-and-proposals/issues/186.)

## Changelog

[General] [Added] - Add nightly CI build

## Test Plan

Individual jobs will have their own test plan.

### CODE REVIEW

**Comment by grabbou** [comment]
I don't see anything on the CI and I don't think there's anything wrong with the config. Have you tried changing interval to something such as every hour? Right now, I guess it's everyday at 8:37, according to this page https://crontab.guru/#37_8_*_*_*

**Comment by sweggersen** [comment]
Hi @grabbou. Thanks for taking a look! I've updated the PR to make the cronjob schedule execute every hour, and do it based on master. My circleci dashboard is very limited (lack of permissions) so it's hard for me to verify if things are working or not. Could you have a look again when you've got time and let me know if you see something related to the schedule? Thanks!

**Comment by hramos** [comment]
This seems fine to me. I think it's alright to merge this, to validate that it will print the message nightly once on master. The actual job can be added on another PR.

**Comment by grabbou** [comment]
LGTM.

**Pull request closed without merging**
