### PR TITLE
bump fresco to 2.3.0

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

Bump Fresco to 2.3.0. 

## Changelog

[Android] [Changed] - Bump Fresco to 2.3.0

### CODE REVIEW

**Review by fkgozali — APPROVED** [review]

**Comment by fkgozali** [comment]
Hmm actually, test_android failure seems related:

```
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.imagepipeline.platform.KitKatPurgeableDecoder
```

Can you double check?

**Comment by dulmandakh** [comment]
It looks like failing to load native libraries, and I'm not good at Buck to resolve the issue. Could you please ask someone in FB for help.

**Comment by fkgozali** [comment]
I'll find time to investigate next week, but expect some delay.

**Comment by mikehardy** [comment]
I maintain a lot of repos and I dislike it when people just "bump" things, at the same time, I am sort of powerless to help on this one and I actually tried with a related PR :-), because I don't have access to the internal systems/logs. Any chance of investigation and merge on this one? Other than buck-related things this should work...

**Comment by mikehardy** [comment]
@dulmandakh entropy is starting to take hold on this one, with a conflict

**Comment by fkgozali** [comment]
Sorry I was quite swamped with the new architecture work for RNTester, I’ll try to pick this up again early next week. Any help figuring out the Buck issue would be very useful as well.

**Comment by mikehardy** [comment]
I wonder if the failure above will self-resolve after resolving conflicts and re-pushing here. I say that because I noticed "KitKat" in the error and I believe minSdkVersion is 21 now, KitKat is 19. One can hope

**Comment by fkgozali** [comment]
Yeah that’s possible, I was just thinking about that. @dulmandakh wanna try rebasing?

**Comment by dulmandakh** [comment]
Got it, will do soon

**Comment by fkgozali** [comment]
So I looked into this a bit. This PR was days before the commit to bump test to run SDK 21: https://github.com/facebook/react-native/commit/7dcecb2907a2f4046ed4729ae183f30516247074

So to save time, I'm going to merge this PR and we'll fix forward any breakage after.

**Comment by fkgozali** [comment]
Side note: testing this locally would require installing https://github.com/react-native-community/docker-android image locally, which is quite a big set up.

**Comment by fkgozali** [comment]
This seems to pass: https://app.circleci.com/pipelines/github/facebook/react-native/7775/workflows/1b8515a7-bb5b-44ce-a404-674d04b828da/jobs/184957

So we're all good to go.

**Comment by mikehardy** [comment]
Just in time for fresco 2.4.0 :-)

**Pull request closed without merging**
