### PR TITLE
Add interactive dismiss enabled to add full support for iOS 13 style page sheet modals

### PR DESCRIPTION
**Pull request by jacobp100**
## Summary

Add interactive dismiss enabled to add full support for iOS 13 style page sheet modals

See #31500

> In this PR, only support for partial drag is added. i.e. user can't drag the modal up and down completely. I added full user dragging but reverted in this commit to support controllable onRequestClose. If someone has any suggestion to have full draggable support + controllable onRequestClose, please let me know.

In the current behaviour, there's friction when dismissing. This enables removing that friction via a new `interactiveDismissEnabled` prop.

When using this prop, you must implement `onDismiss` - and that callback must lead to setting `visible: false`.

I felt this was consistent, because `onDismiss` was called when a modal was fully dismissed. When using the interactive dismissal, we only get notified when it's actually dismissed.

This feature is opt-in to maintain backwards compatibility.

## Changelog

[iOS] [Added] - Added interactiveDismissEnabled prop to Modal component

## Test Plan

Added example in RN tester. Video below.

https://user-images.githubusercontent.com/7275322/135142938-b9a5a044-aeed-4ab0-8015-db711ab17ded.mov

### CODE REVIEW

**Comment by 10000multiplier** [comment]
Any hope of this being merged?

**Comment by jacobp100** [comment]
I've fixed the merge conflicts

**Comment by burakgormek** [comment]
I think this still needed, or am I missing something? Mentioned PR doesn't seem to have this functionality.

**Comment by erquhart** [comment]
@jacobp100 this was never merged, any chance of revisiting? There is currently no way to present a native modal in iOS that can be dismissed smoothly via swipe down, including community libraries. We really need this.

**Comment by erquhart** [comment]
Actually it looks like this is superseded by: https://github.com/facebook/react-native/pull/38641

**Pull request closed without merging**
