### PR TITLE
Update the PR template

### PR DESCRIPTION
**Pull request by odino**
Added a link to the contributing.md -- there's a bunch of stuff there that's not mentioned in this template.

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks! Please remove the commit hash in the URL (link to master).

**Comment by odino** [comment]
I did it on purpose to be have to have an unbreakable link -- anyhow makes sense to link to master in this case. Updated, squashed, delivered, all yours :)

**Comment by odino** [comment]
BTW just rebased again ;)

**Comment by dsibiski** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/921613564625980/int_phab) to review.

**Pull request closed without merging**
