### PR TITLE
Expose category property of iOS notifications

### PR DESCRIPTION
**Pull request by webmariner**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `master` branch, NOT a "stable" branch.

## Motivation

This change allows app code to access the 'category' property of incoming iOS remote push notifications. Currently the property is not made available.

## Test Plan

Create a test application which:
- registers for remote notifications with APNs
- passes the returned token to your push notification service provider
- displays the contents of the notification, including the 'category'
Send a remote push notification including a value for the category property in the payload. Check that the category is displayed in the application.

I considered updating RNTester but I couldn't for the life of me figure out how to get it to compile on my machine, sorry ;-) I can confirm my change works when applied directly in the node_modules of an existing RN project.

## Next Steps

I've signed the CLA. Hope this is enough info to go on, please let me know if not!

### CODE REVIEW

**Comment by javache** [comment]
Does it need to be added for local notifications too?

**Comment by webmariner** [comment]
I didn't check that for my use case, but I notice it seems likely yes. Shall I create a new request to add what looks to be the missing line?

**Comment by javache** [comment]
You can add to this PR

**Comment by webmariner** [comment]
Thanks - have just added that to the PR.

**Comment by webmariner** [comment]
Oops :-) Should be there now, thanks!

**Pull request closed without merging**
