### PR TITLE
[PushNotificationIOS] fixes requestPermissions base on @DannyvanderJagt…

### PR DESCRIPTION
**Pull request by potsypantsy**
fixes PushNotificationIOS requestPermissions base on @DannyvanderJagt's fix in https://github.com/facebook/react-native/pull/1979

### CODE REVIEW

**Comment by DannyvanderJagt** [comment]
@potsypantsy Did you already sign the cla?

**Comment by potsypantsy** [comment]
@DannyvanderJagt I will sign the cla. But the the bigger problem is actually the tests failing. I am unable to get the tests to pass :(

**Comment by DannyvanderJagt** [comment]
Does the master pass all of its tests? I will take a look at it in a few hours, maybe I can help you.

**Comment by DannyvanderJagt** [comment]
I have created a [branch with the same changes as this PR](https://github.com/DannyvanderJagt/react-native/tree/pushnotifications-register) and all the [tests are passing](https://travis-ci.org/DannyvanderJagt/react-native/builds/75509267). Maybe a rebase will help.

Besides the rebase the only thing that is different is that I removed this from `.travis.yml`:
```
branches:
  only:
    - master
```
But that shouldn't be a problem.

**Comment by potsypantsy** [comment]
@DannyvanderJagt I rebased hopefully tests will pass

**Comment by potsypantsy** [comment]
@DannyvanderJagt tests still fail :( maybe you should make the pr instead. I will just close this one.

**Pull request closed without merging**
