### PR TITLE
Add alternative lsof command for killing a process running on port 8081.

### PR DESCRIPTION
**Pull request by JoelSanchez**
I was running RN 0.31 on ArchLinux (kernel 4.7), and "react-native start"
was refusing to run on the default (and sometimes required, as I have
noticed) port. I tried executing the suggested lsof command, but that did not
work. Somewhere I found the lsof command I include in this commit, and that
worked (it was a node.js process). So I'm including it, since I found it
helpful.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-9** [comment]
@JoelSanchez updated the pull request.

**Comment by mkonicek** [comment]
Thanks for the fix! Why didn't `sudo lsof -n -i4TCP:8081` work? Rather than recommending two `lsof` commands, how about fixing the existing command so that it works everywhere?

**Comment by JoelSanchez** [comment]
Just did a quick little test, this works in my system:

` lsof -n -i6TCP:8081 | grep LISTEN `

But this does not:

` lsof -n -i4TCP:8081 | grep LISTEN `

Which, to me, suggests that on some machines the local port may be running on IPV6, and thus "i4TCP" fails to match. This is the output from the last command:

`node    16289 joel   16u  IPv6 3975829      0t0  TCP *:sunproxyadmin (LISTEN)`

The alternative command matches *all* 8081 connections, no matter if they are IPV4, IPV6, TCP, or UDP. Which should always work. It's also easier to write, but that's not important.

So my advice is to just use the alternative command.

**Comment by JoelSanchez** [comment]
Also the node process is "react-native start", both this time and the time I was having problems. Maybe suggesting killing node ("pkill node") to kill other RN packagers running would be a good addition.

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @grabbou as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by lacker** [comment]
OK, so if the right thing to do is to always run the alternative command, how about just making this PR make you suggestion the only one? Rather than suggesting two. Seems reasonable to me.

**Comment by hramos** [comment]
@JoelSanchez do you still want to ship this? It seems like an useful PR, and addressing the last bit of feedback will likely get it approved.

**Comment by JoelSanchez** [comment]
@hramos Removed the other command, sorry for not replying for so long. I'm still interested in merging this.

**Pull request closed without merging**
