### PR TITLE
add 一休 app In the showcase

### PR DESCRIPTION
**Pull request by Menq**
add  一休 app which is using React Native to build and release in the app store. Glad to share to everyone

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by dsibiski** [comment]
Hi @Menq, please edit the `showcase.js` source file: https://github.com/facebook/react-native/blob/master/website/src/react-native/showcase.js ...and not the generated html file. 👍

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by janicduplessis** [comment]
Closing this PR, merged in #7611

**Pull request closed without merging**
