### PR TITLE
[Codegen] Fix generated EventEmitter code for nested objects in arrays.

### PR DESCRIPTION
**Pull request by tvanlaerhoven**
## Summary:

This PR fixes the code for generating EventEmitter C++ code in case nested objects in arrays are used.

```typescript
export interface NativeProps extends ViewProps {
  onEvent: DirectEventHandler<
    Readonly<{
      payloadArray: Readonly<
        {
          obj: Readonly<{ str: string }>
        }[]
      >
    }>
  >;
}

export default codegenNativeComponent<NativeProps>('SomeComponent');
```

In this case the generated `EventEmitters.cpp` code would contain:

```c
obj.setProperty(runtime, "str", payloadArrayValue,obj.str);
```

while

```c
obj.setProperty(runtime, "str", payloadArrayValue.obj.str);
```

is expected.

## Changelog:

[GENERAL] [FIXED] - Support nested objects in arrays

## Test Plan:

Tested with the reproduction case above to verify correct output.

### CODE REVIEW

**Review by javache — APPROVED** [review]

**Comment by elicwhite** [comment]
It seems like we don't have a test fixture that exercises this case. Can you add one/modify one that generates this issue?

**Comment by tvanlaerhoven** [comment]
> It seems like we don't have a test fixture that exercises this case. Can you add one/modify one that generates this issue?

@elicwhite OK sure!

**Comment by tvanlaerhoven** [comment]
@elicwhite Any action needed from my side? I see some pipelines are failing, but I have no access to the details. Locally the unit tests were running successfully.

**Comment by elicwhite** [comment]
No, it's on me. I'm splitting this into two pieces (done) but our infra is mad cause it only sees it connected to a single PR. It's on my plate but I haven't gotten to work on it in a couple days

**Pull request closed without merging**
