### PR TITLE
ImagePickerIOS take photo with wrong orientation

### PR DESCRIPTION
**Pull request by yujiayinshi**
When using ImagePickerIOS camera take photo, photos only have landscape orientation, which is not matched with fact. 
So I add a function to save orientation info.

### CODE REVIEW

**Comment by yujiayinshi** [comment]
anyone can help review ?

**Comment by hramos** [comment]
Hey! I've been going through PRs and would like to get this one moving. Two things stand out to me: there is no test plan, and there is no example of what happens prior to the fix.

Ideally your PR would include all of the sections listed in the PR template. This will help us gauge the extent of the problem as well as understand how the fix was tested.

**Comment by doochik** [comment]
@shergin Hi! Any chance to see this PR merged. I also have this bug with photo orientation and this patch works for me.

**Comment by hramos** [comment]
@doochik see my comment above, this PR lacks a test plan. Since there has been no response from the author, I'll close it. Feel free to open a new PR if you feel strongly about getting this merged.

**Comment by doochik** [comment]
@hramos Ok, I've opened new PR https://github.com/facebook/react-native/pull/15060

**Pull request closed without merging**
