### PR TITLE
Instantiate local notifications different than remote notifications

### PR DESCRIPTION
**Pull request by JAStanton**
# Motivation
To use `PushNotificationIOS` for local notifications in the same way as we use them for remote notifications. Today remote notifications are being constructed correctly but local notifications are not. Related issue: https://github.com/facebook/react-native/issues/8014

## Details
When ObjC receives local notifications it does not serialize the `UILocalNotification` the same way as we do for remote notifications. And when we go to construct a `PushNotificationIOS` javascript instance it works for remote notifications but not for local notifications.

### How are they being serialized differently?
- Some of remote notification's data is wrapped in an `aps` dict (https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW1).
- All of local notifications are being received and passed to javascript as a flat dictionary: (https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L151-L163)

### How are we instantiating `PushNotificationIOS`'s?
For both local and remote the constructor iterates over the `aps` key (https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/PushNotificationIOS.js#L323-L326). This will work for remote notifications but not for local notifications...

# Test plan

Input:
```js
PushNotification.presentLocalNotification({
  alertBody: "Present local notification alert body",
  soundName: 'default',
  applicationIconBadgeNumber: 13,
  userInfo: {
    hello: "world",
  },
});
```

**Local notifications before this PR**
Everything gets shoved in `_data`... Thereby calling `getMessage()`, `getSound()`, `getBadgeCount()` will return `undefined` and calling `getData()` will return all my info...
```json
{
  "_data": {
    "applicationIconBadgeNumber": 13,
    "alertBody": "Present local notification alert body",
    "soundName": "default",
    "userInfo": {
      "hello": "world"
    },
  }
}
```

**After this PR**
Everything is as it should be, calling `getData()`, `getMessage()`, `getSound()`, `getBadgeCount()` will all return the values expected.
```json
{
  "_data": {
    "hello": "world"
  },
  "_badgeCount": 13,
  "_sound": "default",
  "_alert": "Present local notification alert body"
}
```

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @slycoder to be potential reviewers.

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/118504435239056/int_phab) to review.

**Comment by JAStanton** [comment]
Thanks @nicklockwood :) I appreciate all your review support the last week!

**Comment by facebook-github-bot-8** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by JAStanton** [comment]
Tests passing, rebased on master, most likely internal test failure? I know you guys have static analyzers that isn't exposed via Github tests could be those. Let me know what I can fix up! Thanks

**Pull request closed without merging**
