### PR TITLE
[Text] Add textDecoration style attributes

### PR DESCRIPTION
**Pull request by KJlmfe**
I add `textDecorationLine`, `textDecorationStyle`, `textDecorationColor` style property for Text module.

And it follows the CSS naming convention and using method is same with CSS.

1. `textDecorationLine` refers to: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line
2. `textDecorationStyle` refers to: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style
3. `textDecorationColor`refers to: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color

Here is a simple demo:

```javascript
<Text style={{textDecorationLine: 'underline', textDecorationStyle: 'solid'}}>
  Solid underline
</Text>
<Text style={{textDecorationLine: 'underline', textDecorationStyle: 'double', textDecorationColor: '#ff0000'}}>
  Double underline with custom color
</Text>
<Text style={{textDecorationLine: 'underline', textDecorationStyle: 'dashed', textDecorationColor: '#9CDC40'}}>
  Dashed underline with custom color
</Text>
<Text style={{textDecorationLine: 'underline', textDecorationStyle: 'dotted', textDecorationColor: 'blue'}}>
  Dotted underline with custom color
</Text>
<Text style={{textDecorationLine: 'none'}}>
  None textDecoration
</Text>
<Text style={{textDecorationLine: 'line-through', textDecorationStyle: 'solid'}}>
  Solid line-through
</Text>
<Text style={{textDecorationLine: 'line-through', textDecorationStyle: 'double', textDecorationColor: '#ff0000'}}>
  Double line-through with custom color
</Text>
<Text style={{textDecorationLine: 'line-through', textDecorationStyle: 'dashed', textDecorationColor: '#9CDC40'}}>
  Dashed line-through with custom color
</Text>
<Text style={{textDecorationLine: 'line-through', textDecorationStyle: 'dotted', textDecorationColor: 'blue'}}>
  Dotted line-through with custom color
</Text>
<Text style={{textDecorationLine: 'underline line-through'}}>
  Both underline and line-through
</Text>
```

￼

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks for the pull request! Would be nice to follow the CSS naming convention for this
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style

And, if you can provide a jsfiddle that shows that the code works on a span on the web that would be awesome!

**Comment by KJlmfe** [comment]
@vjeux text-decoration-style is only support on firefox. So the jsfiddle web demo is not really needed.

**Comment by vjeux** [comment]
We're trying to use web naming whenever possible, even if it's not implemented everywhere. This way we can redirect users to mdn documentation, and don't have to bikeshed on naming.

**Comment by iostalk** [comment]
That's awesome!
I desire this feature for a long time!

**Comment by KJlmfe** [comment]
@vjeux  I rewrite the code and change the pull request title and content. Now it follows the CSS naming convention and using method is same with CSS.

And here is working on web demo: https://jsfiddle.net/kjlmfe/a1zvL6s8/1/ (Only for firefox)

**Comment by luics** [comment]
cool

**Comment by mariodu** [comment]
cool

**Comment by LyndonChin** [comment]
awesome ! DiaoZhaTian

**Comment by SoXeon** [comment]
66666!

**Comment by imochen** [comment]
看到，吊炸天。。。

**Comment by brentvatne** [comment]
@sahrens - looked at the `git blame` and wasn't quite sure who to assign here, your name stood out so I just added you, re-assign if I'm off.

@KJlmfe - thanks! can we get a rebase?

**Comment by sahrens** [comment]
Looks great!  Can you rebase, squash your commits, and re-record the TextExample snapshot test?  Set reRecord yes here and run with cmd+U:

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorerTests/UIExplorerTests.m#L97

Also, assigning over to @a2 who is our Text master.

**Comment by cssoul** [comment]
well done~

**Comment by KJlmfe** [comment]
@sahrens I had merge branch 'facebook/react-native/master' into my master and resolve the conflicts.

**Comment by brentvatne** [comment]
@KJlmfe - instead of merging could you do a `git rebase -i` to squash the commits into one? [See this guide](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by constantx** [comment]
:+1:

**Comment by brentvatne** [comment]
@KJlmfe - I'm confused about what's going on here, I will close this but will happily re-open if you rebase and squash into one commit! Thanks

**Comment by KJlmfe** [comment]
@brentvatne I had rebased and squashed into one commit! 

See it https://github.com/KJlmfe/react-native/commit/fdaca5d19b76bafc771822361d37719509403441

**Comment by pcottle** [comment]
Can we reopen this? Would be sweet to get underlining in :D

**Comment by MossP** [comment]
did this ever get merged?

**Comment by pcottle** [comment]
I threw up a fresher version of this over at https://github.com/facebook/react-native/pull/1869 that was rebased, hopefully once the Travis CI build is green we can merge!

**Comment by pcottle** [comment]
Woohoo! this made it into the `v0.8.0-rc` release:
https://github.com/facebook/react-native/releases/tag/v0.8.0-rc

underline all the things

**Comment by MossP** [comment]
:+1:

**Comment by MossP** [comment]
Does it work for you, @pcottle? I don't seem to be seeing any text decoration.

**Comment by ide** [comment]
It's working in the UIExplorer.

**Comment by MossP** [comment]
Ah, it seems that my project has reverted to 0.7.1 somewhere along the line. Apologies. I'll go try again.

**Comment by MossP** [comment]
That fixed it, thanks @ide. Sorry for the newbie error.

**Comment by herbertdai** [comment]
I does not work on Android in 0.19.0.

**Comment by pewh** [comment]
Hello, what's the current status of this? I need `textDecorationColor` props

**Pull request closed without merging**
