### PR TITLE
Implement WebSocket module for Android with EventTarget interface

### PR DESCRIPTION
**Pull request by satya164**
This is basically a merge of https://github.com/facebook/react-native/pull/2839 and https://github.com/facebook/react-native/pull/2599

### CODE REVIEW

**Comment by satya164** [comment]
cc @mkonicek @ide @foghina

**Comment by satya164** [comment]
I was waiting for #2599 to be merged before I do this. But that PR now has merge conflicts, and I'm impatient!

**Comment by ide** [comment]
Please keep the commits separate. They're easier to merge and bisect.

**Comment by satya164** [comment]
@ide Yeah, I understand. I was just too impatient.

The commits are still separate though, after you merge the other pull requests, I won't have to create this again, so I'll leave this until the previous ones are merged, then I'll just rebase it against master and I'll be good to go :)

**Comment by ide** [comment]
Closing this because your other PR (https://github.com/facebook/react-native/pull/2839) supersedes this.

**Pull request closed without merging**
