### PR TITLE
Added 'react-native start' command, which was missing

### PR DESCRIPTION
**Pull request by vinigfer**
Thanks for submitting a PR! Please read these instructions carefully:

- [ ] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

Getting started page located here https://facebook.github.io/react-native/docs/getting-started.html
was not enough to actually perform a 'hello world' app.

## Test Plan (required)

Perform exactly what is written in the page with a noob developer and an android emulator, and you'll see he'll get an "Error calling Appregistry.runApplication".

## Next Steps

Sign the [CLA][2], if you haven't already.

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by hramos** [comment]
This change has been attempted before and has been rejected. It shouldn't be necessary to run this command. If you're indeed facing this issue, I'd rather this be fixed in the `react-native run-android` CLI itself in order to match the iOS dev experience.

**Comment by vinigfer** [comment]
It shouldn't be necessary, but it was.
Is there a `react-native run-android CLI` repository to post this as a bug?

**Comment by hramos** [comment]
The `react-native` CLI code is in this repository

**Comment by hramos** [comment]
If you file this as a bug against the CLI, see if you can find specific repro steps. In my experience, it is not necessary to start the packager separately as `react-native run-android` will take care of it. That said, other people have run into this before so it would be great to figure out what sort of configuration triggers it.

**Comment by hramos** [comment]
There might be a fix in #13825. @vinigfer which OS did you see this issue on?

**Comment by vinigfer** [comment]
We are using Ubuntu 16.04.2 LTS, 64 bits

**Pull request closed without merging**
