### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by bluetec**
Fix typo in documentations.
change `node_nodules` to `node_modules`

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @lacker to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@bluetec Hi. Thanks for the pull request. Please sign the CLA so we can merge your fix.

Also, this should actually be put into `master` and not `0.29-stable` so that we don't lose the fix moving forward. I can then possibly cherry-pick this into `0.29-stable`, etc.

**Comment by hramos** [comment]
Closing, please reopen against master, thanks!

**Pull request closed without merging**
