### PR TITLE
Update ModalExample.js

### PR DESCRIPTION
**Pull request by polandtyler**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

Could be mistaken (kind of a n00b), but doesn't seem like this line is necessary? Showed up in the modal example (https://facebook.github.io/react-native/docs/modal.html) and confuzzled me.

### CODE REVIEW

**Comment by vjeux** [comment]
I have no idea sorry :(

**Comment by facebook-github-bot-8** [comment]
@dmmiller would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by dmmiller** [comment]
What does this do for us?

**Comment by facebook-github-bot-3** [comment]
@polandtyler updated the pull request.

**Pull request closed without merging**
