### PR TITLE
Revert "Reverted commit D3516741"

### PR DESCRIPTION
**Pull request by bestander**
Unrevert a revert

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @frantic and @martinbigio to be potential reviewers.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/523357194514939/int_phab) to review.

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/523357194514939/int_phab) to review.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/523357194514939/int_phab) to review.

**Pull request closed without merging**
