### PR TITLE
Set host of development server for setupDevtools

### PR DESCRIPTION
**Pull request by jhen0409**
Related to #15126, and this would be useful for use React DevTools on real device without modify `setupDevtools.js`.

In Android emulator, the host of `SourceCode.scriptURL` is same with `PlatformConstants.ServerHost` so we can just replace it.

## Test Plan

* Tested on iOS device with [react-devtools](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) package.
* Tested on Android emulator, the `getDevServer` module got the correctly hostname so that don't need `adb reverse`.

## Release Notes

[ENHANCEMENT] [setupDevtools] Set host of development server for setupDevtools

### CODE REVIEW

**Comment by macrozone** [comment]
This would be awesome to have. In particular with https://github.com/jhen0409/react-native-debugger. Any update on this?

**Comment by gaearon** [comment]
@javache is not working on RN anymore so we'll need to find somebody else to review this.

**Comment by vlkosinov** [comment]
Can someone merge it? 
Seems like there is no way to use react-devtools for real devices without changing host manually in `Libraries/Core/Devtools/setupDevtools.js` :(

@gaearon

**Comment by macrozone** [comment]
It‘s extremly sad that this pr has been closed :(

This is a very useful change, developing on a feal device is not unusual and sometimes the only way

**Comment by jhen0409** [comment]
Actually this change have been landed in master, it should be released as [RN 0.53](https://github.com/facebook/react-native/commit/fa574c60920588e29d7b642e547e240ac8655e66).

Thanks @javache come back to deal with this. 😃

**Comment by gaearon** [comment]
The PR appears as closed because RN is set up to sync to our internal repository. So all PRs are “closed” on GitHub when they’re imported, but the commits appear on master.

**Pull request closed without merging**
