### PR TITLE
Add React Native Web Player to most component basics

### PR DESCRIPTION
**Pull request by JoelMarcey**
> ListView is not supported by React Native Web as of yet, so it will not have it.

Test Plan:

It runs so nice!

screen shot 2016-06-22 at 2 27 02 pm

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @ericnakagawa to be a potential reviewer.

**Comment by JoelMarcey** [comment]
This is so awesome @dabbott. Thanks so much for adding this functionality to the docs!

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1033594146689080/int_phab) to review.

**Pull request closed without merging**
