### PR TITLE
[Android] Fix: setSelection methods is always returned.

### PR DESCRIPTION
**Pull request by jainkuniya**
## Motivation

Because mMostRecentEventCount < mNativeEventCount is always true as mMostRecentEventCount is not updated.

So determine whether text is set or not from getting current text. Also handle out of bound selection.

## Test Plan
Use this component to test with & without this PR

Before this PR, on clicking Button, nothing will happen.
On this PR: text will be selected starting from 0 and ending at 3. (Just for testing I have barcoded `start` & `end` value)
Just created a component to test (below). 

```
/* @flow */
import React, { PureComponent } from 'react';
import { View, TextInput, StyleSheet, TouchableHighlight, Text } from 'react-native';

const componentStyles = StyleSheet.create({
  input: {
    flex: 1,
  },
  button: {
    //position: 'absolute',
    right: 0,
    alignItems: 'center',
    padding: 10,
  },
  buttonText: {
    color: '#000',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});

export default class PasswordInput extends PureComponent<Props, State> {
  props: Props;

  state: State;

  state = {
    selection: { start: 0, end: 0 },
  };

  handleSelectionChange = event => {
    const { selection } = event.nativeEvent;

    this.setState({
      selection,
    });
  };

  render() {
    const { selection } = this.state;

    return (
      <View>
        <View style={componentStyles.row}>
          <TextInput
            style={[componentStyles.input]}
            placeholder={'Start typing here'}
            placeholderTextColor={'green'}
            autoCorrect={false}
            autoCapitalize="none"
            selection={selection}
            onSelectionChange={event => this.handleSelectionChange(event)}
          />
        </View>
        <TouchableHighlight
          style={componentStyles.button}
          onPress={() => this.setState({ selection: { start: 0, end: 3 } })}
        >
          <Text style={componentStyles.buttonText}>
            {'Selection (Click me to select text starting from 0 to 3 in above textInput)'}
          </Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

Current behaviour
ezgif com-video-to-gif-5

This PR
ezgif com-video-to-gif-6

## Release Notes

[ANDROID] [BUGFIX] [TextInput] Fix: setSelection methods is always returned.

### CODE REVIEW

**Comment by jainkuniya** [comment]
Thanks! @facebook-open-source-bot I have updated and included Test Plan. 👍 :)

**Comment by jainkuniya** [comment]
hi @janicduplessis please review this PR too. :)
#17851 is not affective until this issue is solved. :)

**Comment by cpojer** [comment]
Yeah this doesn't seem like the solution we are looking for here. I'm gonna close this PR.

**Comment by jainkuniya** [comment]
Hey @cpojer can you please also review #17990

**Pull request closed without merging**
