### PR TITLE
Add animation support to resetTo method

### PR DESCRIPTION
**Pull request by ademars94**
This change allows a react-native developer to navigate to a new route using the standard transition animation, while also resetting the route stack.  This was previously not possible.  I created this pull request because I wanted to use this feature in a project I am working on.

The usage for `resetTo` and `push` remains the same, but `resetTo` now uses the same animation as `push`.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by antoinerousseau** [comment]
but the animation implies that the user can navigate back, which is relevant with `push` but not sure about `resetTo`

**Comment by ademars94** [comment]
@antoinerousseau I could put the normal `resetTo()` method back in, and then create a `resetToWithAnimation()` method with my changes.

**Comment by facebook-github-bot-6** [comment]
@ademars94 I tried to find reviewers for this pull request and wanted to ping them to take another look. However, based on the blame information for the files in this pull request I couldn't find any reviewers. This sometimes happens when the files in the pull request are new or don't exist on master anymore. Is this pull request still relevant? If yes could you please rebase? In case you know who has context on this code feel free to mention them in a comment (one person is fine). Thanks for reading and hope you will continue contributing to the project.

**Comment by rclai** [comment]
I find it hard to believe that this was never available. When you log in, why would you keep the login scene still in the stack? I had to create a `pushReset` function to handle this for me.

**Comment by ademars94** [comment]
@facebook-github-bot-0 @rclai I was able to find a work around with the help of some other people who were having similar issues.  I am no longer using the changes from this pull request.

It turns out that when you are doing a `push()`, you  can actually include a `reset: true` property as part of the route object.  Then you use the built in navigator `onDidFocus` prop, and call `immediatelyResetRouteStack()`.

So  when you want to  navigate you do this, getting the nice animation:
```
this.props.navigator.push({ name: routeName, reset: true });
```
And then wherever your navigator is in  your project.  Notice I have the navigator component setting itself as a ref, and then I am using that ref to access `immediatelyResetRouteStack()`.  Also worth noting, make sure you are passing the actual route and not just the route name, otherwise you will re-render whatever scene you pushed into the route stack.
```
  resetRouteOnFocus = (route) => { // Prevent user from navigating back to login
    if (route.reset) {
      route.reset = false;
      this.refs.navigator.immediatelyResetRouteStack([ route ]);
    }
  };
```
Here's my navigator component:
```
<Navigator style          = { s.container }
           initialRoute   = {{ name: "Login" }}
           renderScene    = { this.renderScene }
           onDidFocus     = { (route) => this.resetRouteOnFocus(route) }
           configureScene = { () => Navigator.SceneConfigs.FloatFromRight }
           navigationBar  = { navbar }
           ref            = { "navigator" }/>
```
Feel free to contact me if you have any questions.

**Comment by rclai** [comment]
Oh wow that makes a lot of sense. Thanks.

**Pull request closed without merging**
