### PR TITLE
Give more details about js require.

### PR DESCRIPTION
**Pull request by sunnylqm**
Native developers may get confused by require statement.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks for the PR, but really not sure about this. Modules are a fundamental thing to know while working with frontend apps.

**Comment by ide** [comment]
Modules are part of the JavaScript language and the module lookup algorithm is CommonJS... I don't think we want to focus on teaching JS basics (or likewise mobile basics to people who have more web experience). That said adding `./` to the example I think would allow the reader to infer where the required file is supposed to be. @sunnylqm could you update your PR so that the only change is ToastAndroid -> ./ToastAndroid?

**Comment by sunnylqm** [comment]
Thanks for the reminding! I've found this "@provideModule" which I had never noticed before! Maybe we should explain more of refer some link about @provideModule here? (Is it platform specific? Feature of ecmascript/react.js/react native? How does it avoid name/path collision?)Any documents?  I get nothing useful from google.

**Comment by ide** [comment]
providesModule is specific to Facebook, which is why I believe it is intentionally not documented.

**Comment by mkonicek** [comment]
Leaving up to you @ide, feel free to merge or close.

**Comment by ide** [comment]
LGTM thanks

**Pull request merged**
