### PR TITLE
[flow-strict] Flow strict-local in InternalScrollViewTypes

### PR DESCRIPTION
**Pull request by flowkraD**
Issue in focus: #22100 

All instances of `any` were replaced with their respective Flow types.
`getScrollResponder()` returned `this` and after going through the official flow documentation for [functions](https://flow.org/en/docs/types/functions/) , I removed the return type altogether. If this was a wrong approach, please correct me.
Any changes needed will be implemented at the earliest of my convenience (^_^)

Test Plan:
----------
* [x]  yarn prettier
* [x]  npm run lint
* [x]  npm run flow
* [x]  npm run flow-check-android

Release Notes:
----------
[GENERAL][ENHANCEMENT][InternalScrollViewType.js] - Flow Type
[GENERAL][FIXED][deepFreezeAndThrowOnMutationInDev-test.js] - Lint Error

### CODE REVIEW

**Comment by flowkraD** [comment]
@TheSavior 
Just wondering which of the internal test failed. Would be able to rectify the mistake I made.

**Comment by TheSavior** [comment]
Sorry for not getting back to this, thanks for pinging me.

These are the flow errors:

```
Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

               v-----------------------------------------------------------
  242|         scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
  243|           ReactNative.findNodeHandle(this._submitButton),
  244|           INPUT_FIELD_OFFSET,
  245|           true,
  246|         );
       --------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `this._scrollViewRef.getScrollResponder().scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

             v------------------
  365|       this._scrollViewRef
  366|         .getScrollResponder()
  367|         .scrollResponderScrollNativeHandleToKeyboard(
     :
  370|           preventNegativeScrollOffset,
  371|         );
       --------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `this._scrollViewRef.getScrollResponder().scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

             v------------------
  334|       this._scrollViewRef
  335|         .getScrollResponder()
  336|         .scrollResponderScrollNativeHandleToKeyboard(
     :
  339|           preventNegativeScrollOffset,
  340|         );
       --------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

             v-----------------------------------------------------------
  280|       scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
  281|         ReactNative.findNodeHandle(this._inputRef),
  282|         /* $FlowFixMe This issue was
     :
  285|         true,
  286|       );
       ------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

           v-----------------------------------------------------------
  475|     scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
  476|       inputNodeHandle,
  477|       Platform.select({
     :
  481|       true,
  482|     );
       ----^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollView.getScrollResponder().scrollResponderScrollTo` because property `scrollResponderScrollTo` is missing in undefined [1].

                   v--------------------------------------------------------
  511|             scrollView.getScrollResponder().scrollResponderScrollTo({
  512|               x: 0,
  513|               y: Math.min(questionY, maxScrollOffset),
  514|               animated: true,
  515|             });
       -------------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

           v-----------------------------------------------------------
  200|     scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
  201|       inputNodeHandle,
  202|       Platform.select({
     :
  206|       true,
  207|     );
       ----^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

                 v-----------------------------------------------------------
  234|           scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
  235|             inputNodeHandle,
  236|             BASE_SCROLL_OFFSET,
  237|             true,
  238|           ),
       ----------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot create `MyComponent` element because undefined [1] is incompatible with `InternalScrollViewType` [2] in property `scrollResponder`.

                     v-------------------
  363|               <MyComponent
  364|                 errorCodes={this._errorCodes}
  365|                 questions={questions}
     :
  367|                 onNext={this._onNextPage}
  368|               />
       ---------------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]
  ProductCode.js:
  19|   scrollResponder: ScrollView,
                         ^^^^^^^^^^ [2]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot create `MyComponent` element because undefined [1] is incompatible with `InternalScrollViewType` [2] in property `scrollResponder`.

                     v--------------------------
  401|               <MyComponent
  402|                 contextContent={redacted}
  403|                 contextContentStyle={this.getContextContentStyle()}
     :
  409|                 onNext={this._onNextPage}
  410|               />
       ---------------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]
  ProductCode.js:
  34|   scrollResponder: ScrollView,
                         ^^^^^^^^^^ [2]

ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` with `ReactNative.findNodeHandle(...)` bound to `nodeHandle` because null or undefined [1] is incompatible with number [2].

  ProductCode.js:
  77|             ReactNative.findNodeHandle(this._component),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
  react-native/Libraries/Renderer/shims/ReactNativeTypes.js:133:43
  133|   findNodeHandle(componentOrHandle: any): ?number,
                                                 ^^^^^^^ [1]
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:34:17
  34|     nodeHandle: number,
                      ^^^^^^ [2]

ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` with `ReactNative.findNodeHandle(...)` bound to `nodeHandle` because null or undefined [1] is incompatible with number [2].

  ProductCode.js:
  91|               ReactNative.findNodeHandle(this._component),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
  react-native/Libraries/Renderer/shims/ReactNativeTypes.js:133:43
  133|   findNodeHandle(componentOrHandle: any): ?number,
                                                 ^^^^^^^ [1]
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:34:17
  34|     nodeHandle: number,
                      ^^^^^^ [2]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

                    v-----------------------------------------------------------
  91|               scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
  92|                 ReactNative.findNodeHandle(inputRef),
  93|                 /* $FlowFixMe This issue
    :
  96|                 true,
  97|               );
      --------------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollResponder.scrollResponderScrollNativeHandleToKeyboard` because property `scrollResponderScrollNativeHandleToKeyboard` is missing in undefined [1].

            v-----------------------------------------------------------
  74|       scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
  75|         inputNodeHandle,
  76|         44 + 20 + 10,
  77|         true,
  78|       );
      ------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `scrollView.getScrollResponder().scrollResponderScrollTo` because property `scrollResponderScrollTo` is missing in undefined [1].

                     v--------------------------------------------------------
  318|               scrollView.getScrollResponder().scrollResponderScrollTo({
  319|                 x: 0,
  320|                 y: Math.min(inputY, maxScrollOffset),
  321|                 animated: true,
  322|               });
       ---------------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]

Error ---------------------------------------------------------------------------
ProductCode.js:
Cannot call `this._scrollViewRef.getScrollResponder().scrollTo` because property `scrollTo` is missing in undefined [1].

               v--------------------------------------------------
  202|         this._scrollViewRef.getScrollResponder().scrollTo({
  203|           y: Math.max(
  204|             this.state.commentsBottom -
     :
  210|           ),
  211|         });
       ---------^

References:
  react-native/Libraries/Components/ScrollView/InternalScrollViewType.js:29:23
  29|   getScrollResponder() {}
                            ^ [1]
```

**Comment by flowkraD** [comment]
@TheSavior,
After a bit of digging, I found getScrollResapender returns a ScrollView object from this [line](https://github.com/facebook/react-native/blob/6ebee18d1348441f2f201e6a6faf5d14bc7fe361/Libraries/Components/ScrollView/ScrollView.js#L604) but the ScrollView is based on `createReactClass` whose alternate I think is still being worked out by the guys there.
I'm not sure `strict-local` can be taken care of, as of now.

**Comment by TheSavior** [comment]
Thanks for digging. It isn't critical that we jump to strict-local. I mostly just care that we make this better than it was. :) 

What do you think about changing your PR to only include the changes you are confident in without using strict-local. Then we can merge the PR and improve it even further later when other files it depends on are improved.

**Comment by flowkraD** [comment]
@TheSavior, 
Sorry for not getting back earlier.
I have dialed back the return type of `getScrollResponder` to `any` so now it can return the `ScrollView` object which takes care of all the internal errors as all of them were related to this single change.
The changes were added in a02fcb8t but I haven't squashed the two commits as one. Please let me know if this is necessary and I'll do it in a jiffy. 
Thank you (^_^)

**Comment by flowkraD** [comment]
#22301 Removes `InternalScrollViewTypes.js` completely so this PR becomes redundant after that. Should I go ahead and close this @TheSavior ?

**Pull request closed without merging**
