### PR TITLE
[ListView] Reset ListViewDataSource "dirty bit" so that a row will only ever re-render once when changed

### PR DESCRIPTION
**Pull request by chrisbianca**
Currently, a ListView will continue to re-render dirty rows until the ListViewDataSource is updated with new data.  See more details here: https://github.com/facebook/react-native/issues/5255

**Test plan (required)**

1) Log to console each time a row renders
2) Update datasource for a single row
3) Check that the row only ever re-renders once

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @pglotov and @davidaurelio to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@chrisbianca updated the pull request.

**Comment by davidaurelio** [comment]
@chrisbianca sorry for not taking a look earlier
@spicyj @vjeux, could you check this out? I have hardly any knowledge about this file. Thank you!

**Comment by facebook-github-bot-0** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @pglotov as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @pglotov as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by lacker** [comment]
My guess is that @davidaurelio is probably a better reviewer here - David would you mind taking a look, or do you have a suggestion of who would be better? Feel free to ping me off github....

**Comment by chrisbianca** [comment]
@lacker thanks for prompting.  It would be good to get this reviewed - it's a single line change and has been unreviewed for the best part of 6 months.  I realise that it's not a major issue, but is an optimisation nonetheless.

From @davidaurelio's previous reply, he had already suggested @spicyj and @vjeux as potentially knowing more about this component, but it still hadn't been picked up.

**Comment by hramos** [comment]
I'll see if I can get this reviewed, sorry for the delay.

**Comment by lacker** [comment]
OK I call dibs on this one. It seems legit but I'm afraid we're going to be accidentally breaking this. Can you add a test to ensure it works? I feel like the test process of manually checking it out is not good enough.

**Comment by ide** [comment]
Can you address the original problem by clearing the dirty bits from ListView's componentDidUpdate? We shouldn't perform mutations in rowShouldUpdate since that's confusing and also it's called from render() which should be idempotent.

**Comment by chrisbianca** [comment]
@ide That makes sense.  I'm pretty snowed under at the moment but will try and update next week.

**Comment by javiercr** [comment]
I stumbled upon this same problem today. Kudos to this PR!

**Comment by hramos** [comment]
Ping @chrisbianca

**Comment by ericvicenti** [comment]
I'm closing this in favor of #12650

**Pull request closed without merging**
