### PR TITLE
Resolved : [TextInput] Auto correction doesn't call onChangeText after submit #2552 

### PR DESCRIPTION
**Pull request by RD1991**
Hi There ,

This is my first ever attempt for pull request in react-native. Im very happy to be part of it.
We were having an issue regarding TextInput onChangeText call when user selects value from auto correction. 
onChangeText doesn't get called was the issue.
So solution for that could be just add a function call to textFieldDidChange in method textFieldEndEditing. 
[self textFieldDidChange];
  
So it will look like, 
- (void)textFieldEndEditing
{
  [self textFieldDidChange];
  [_eventDispatcher sendTextEventWithType:RCTTextEventTypeEnd
                                 reactTag:self.reactTag
                                     text:self.text
                                      key:nil
                               eventCount:_nativeEventCount];
}

Thanks,
RD.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @RetroPoktan to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by javache** [comment]
You didn't set up the pull-request correctly, can you send a new one?

**Pull request closed without merging**
