### PR TITLE
iOS: trigger didUpdateDimensions event when resizing without changing traits

### PR DESCRIPTION
**Pull request by jpdriver**
## Summary:

- when using the `useWindowDimensions()` hook in a component, it's possible for the hook to report incorrect sizes and not update as frequently as it should
- this is most applicable to apps built for iPad and macOS
- closes https://github.com/facebook/react-native/issues/36118

### Existing Behavior - https://youtu.be/NcV6kEDg20E

- either when resizing a React Native app to a different [Size Class](https://developer.apple.com/design/human-interface-guidelines/layout#Device-size-classes) or changing the Appearance, we dispatch an `RCTUserInterfaceStyleDidChangeNotification` notification
- these are then handled in the `interfaceFrameDidChange` method of `RCTDeviceInfo`
  - this results in a `didUpdateDimensions` Device Event, which in turn updates the results of `useWindowDimensions()`
  - see [RCTDeviceInfo.mm#L217-L232](https://github.com/facebook/react-native/blob/v0.72.0-rc.4/packages/react-native/React/CoreModules/RCTDeviceInfo.mm#L217-L232)
  - and [Dimensions.js#L119-L124](https://github.com/facebook/react-native/blob/v0.72.0-rc.4/packages/react-native/Libraries/Utilities/Dimensions.js#L119-L124)
  
🐛 **However** 🐛
- if you are resizing without triggering a `UITraitCollection` change, the Dimensions reported by `useWindowDimensions()` can become stale, until you either:-
  - hit a certain width that is considered a different Size Class
  - change the Appearance
  - background then resume the app
  - make the app full-screen
  
### Changed Behavior - https://youtu.be/w9BevpZ2y08

- added a new `RCTRootViewFrameDidChangeNotification` notification
  - the thinking here is to avoid additional overhead by re-using the same `RCTUserInterfaceStyleDidChangeNotification`
  - maybe it's overkill?
- the new notifications are sent from an override of `setFrame` on `RCTRootView`
- the new notifications call the same `interfaceFrameDidChange` method of `RCTDeviceInfo`
- Dimensions are now reported correctly when resizing; even within the same Size Class

## Changelog:

[IOS] [FIXED] - Dimensions could be reported incorrectly when resizing iPad or macOS apps

## Test Plan:

**Reproduction: https://github.com/jpdriver/Dimensions**

or to recreate it yourself:-

- Generate a new project
- Change App.tsx
```
import * as React from 'react';
import {View, Text, useWindowDimensions} from 'react-native';

export default function App() {
  const {width, height} = useWindowDimensions();

  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Width: {width}</Text>
      <Text>Height: {height}</Text>
    </View>
  );
}
```
- Open the iOS project in Xcode and enable iPad support
- Enable the iPad app to be used in any orientation
- Run the app
- Enable Stage Manager
- Drag one of the corners to resize the app

### CODE REVIEW

**Comment by javache** [comment]
This only works for React Native applications with a single root view, or where the rootview takes up the entire window frame.

`useWindowsDimensions` represents the size of the window/display your application is hosted in, not the size of your React root.

**Comment by jpdriver** [comment]
right -- but this PR doesn't _change_ anything about RCTDimensions, they way we report them, or the `useWindowDimensions` hook..

- (if anyone reading through needs context, see [RCTUIUtils.m#L12-L31](https://github.com/facebook/react-native/blob/b50874cad41f06519a263fa53d15f76c836fd167/packages/react-native/React/UIUtils/RCTUIUtils.m#L12-L31))

all this PR does is dispatch the existing `didUpdateDimensions` events more often.. is there a problem doing that?

@javache would you prefer if we moved that `postNotification` somewhere other than `setFrame`? 🤔

**Comment by javache** [comment]
Ah, I misunderstood. You're using a root view frame change as a signal that the window dimensions might have changed (but you're not actually using the rootview's frame to update those dimensions!).

**Comment by jpdriver** [comment]
> You're using a root view frame change as a signal that the window dimensions might have changed

Yes, correct -- that's the intent here.

> Are there any better callbacks we could leverage for this?

Some other things I learnt while looking into this:-

- UIKit views are not guaranteed to be KVO-compliant, so we can't observe the `frame` directly
- Overriding `layoutSubviews` seems to be generally accepted by the iOS community as the place for logic like this; though in the context of a React Native component tree I figured that probably gets called a lot? 😅

---

maybe `layoutSubviews` could be a better place, provided we track the old dimensions and do nothing unless they've actually changed?

this could be similar to how `reactSetFrame` works on `RCTView`
- see [RCTView.m#L779-L789](https://github.com/facebook/react-native/blob/v0.72.0-rc.4/packages/react-native/React/Views/RCTView.m#L779-L789)

@javache what do you think?

**Comment by javache** [comment]
`reactSetFrame` is just our wrapper to `setFrame` which is called as part of the mount.

What I meant with my question is: is there any other callback given to your application, other than the `setFrame` on the root, to signal its window dimenions have changed? E.g. if you break in the native debugger on that setFrame call, is there any higher-level hook (eg on AppDelegate) that we should hook into. If not, this approach seems fine.

**Comment by jpdriver** [comment]
> is there any higher-level hook (eg on AppDelegate) that we should hook into

@javache I doubled checked but nope this is as high as we can get 🙇🏻‍♂️

Screenshot 2023-06-26 at 1 58 13 PM

is there anything else I need to do for this PR?

**Comment by javache** [comment]
> > is there any higher-level hook (eg on AppDelegate) that we should hook into
> 
> @javache I doubled checked but nope this is as high as we can get 🙇🏻‍♂️
> 
> Screenshot 2023-06-26 at 1 58 13 PM
> is there anything else I need to do for this PR?

Could you expand the full stack there? Just curious if there's any other UIKit symbols there that could be relevant.

If nothing useful shows up there, I'm ok to pull this in.

**Comment by jpdriver** [comment]
I think this is all just UIKit innards right? 😅 

Screenshot 2023-06-27 at 4 27 36 PM

**Comment by javache** [comment]
I think the right approach would be to hook into [`windowScene:didUpdateCoordinateSpace:interfaceOrientation:traitCollection:`](https://developer.apple.com/documentation/uikit/uiwindowscenedelegate/3198094-windowscene?language=objc) to get this information.

I'm sorry to push back on this, but we want to avoid having spurious events from across the codebase to set this piece of shared state. In an app with multiple rootviews, we'd be sending this event quite frequently for no valid reason.

Feel free to pull this `setFrame` handler in your RCTRootView subclass (eg. manually emitting `RCTUserInterfaceStyleDidChangeNotification` there)

**Comment by jpdriver** [comment]
> it doesn't look like we're setting up a WindowScene explicitly in the app template right now

could introducing a `SceneDelegate` to the Hello World template be something the team would be open to? 🙏🏻 

that would ultimately solve the issue with `useWindowDimensions()` for _most_ RN apps (or at least the ones that use the OSS template!)

if that's of interest, I'd be happy to open a new PR to try it 🙇🏻‍♂️

**Comment by javache** [comment]
I think that's the right approach longer-term, but I don't know what the other implications of that are. @cipolleschi?

**Comment by cipolleschi** [comment]
Hi there, happy to chime in! :D 

So, most of the logic for the template/AppDelegate is actually wrapped in the [`RCTAppDelegate`](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm) on which we have full control.

So, whether we use the Scene based approach or the old approach, is now an implementation detail.

If we need to expose some method to the final users, for example if we want to allow them to customize some Scene specific logic, we would have to expose that in the `RCTAppDelegate.h`.

My only concern here is that, AFAIK, React Native is not set up to work with multiple Scenes, right now, so changing this could have implications on other OSS projects we are not aware of and we cannot control or check internally.

But Scene based apps are the new standard apple was pushing, so I'd say that yes, we should have a PR which promotes the Scene APIs in the RCTAppDelegate.

Possibly, we should split the PR in two:
1. Add the Scene support in the RCTAppDelegate
2. Fix the `didUpdateDimensions` issue.

How does this sound? Does it makes sense to you, guys?

**Comment by jpdriver** [comment]
ok so just to confirm: we'll introduce something like an `RCTSceneDelegate` first and then for 

> 2. Fix the didUpdateDimensions issue.

we're saying we want to hook into `windowScene:didUpdateCoordinateSpace:interfaceOrientation:traitCollection:` **instead** of `setFrame` right?

**Comment by cipolleschi** [comment]
Why do you think that we need a `RCTSceneDelegate`? Can we use the same `RCTAppDelegate` as `SceneDelegate`? So the users won't have to deal with another class and they can override an `RCTAppDelegate` method if they have to customize the behavior.
How does this sound?

**Comment by jpdriver** [comment]
@cipolleschi ah I thought we'd need a separate `RCTSceneDelegate` from other modern-ish iOS apps where I've seen **both** an `AppDelegate` and a `SceneDelegate`.

I've updated this PR so the existing `RCTAppDelegate` itself is the `UISceneDelegate` too.

one minor nit about this approach -- it won't work for iOS < 13.0, whereas `setFrame` goes even further back in terms of compatibility..

should we pause work on this until 0.73 and the iOS minor version is set to 13? 🤔

**Comment by cipolleschi** [comment]
> one minor nit about this approach -- it won't work for iOS < 13.0, whereas setFrame goes even further back in terms of compatibility..
>
>should we pause work on this until 0.73 and the iOS minor version is set to 13? 🤔

Well spotted! If the issue is not pressing and can wait for 0.73, that would be the best option, probably.
Main is already on a 13.4 min requirement, so we can actually land this on main and it will be automatically included in 0.73.

If we need this in 0.72 also, we can send a local commit there to fix this behavior.

What do you think?

**Comment by jpdriver** [comment]
(accidentally closed because I didn't realize these commits were on `main` in my fork 🤦🏻‍♂️)

@cipolleschi can we land this? It would be great to have it in 0.73+

I don't think we need to worry too much about back-porting to other releases.

**Review by cipolleschi — APPROVED** [review]

**Comment by cipolleschi** [comment]
@NickGerleman could you reimport this PR whenever you can? 🙏

**Comment by Saadnajmi** [comment]
Chiming in after the fact, I appreciate the existence of this PR for React Native macOS as `RCTDeviceInfo` is where we have a lot of diffs trying to support RootView / it's window being as resizable as you want. Hopefully will make things better in 0.73 there too :D

**Comment by Saadnajmi** [comment]
Following up again, I have a few questions about this PR, as I'd like to expand on it for React Native macOS and/or make some changes to the iOS side:

1) Since `RCTRootViewFrameDidChangeNotification` is now actually signaling _window_ changes, does it makes sense to rename the notification?
2) I see we moved away from overriding RCTRootView/RCTSurfaceHostingViews' `setFrame` method. However, it is possible  for the root view's window size to change while the root view frame remains constant (namely on macOS, but also possibly visionOS). In cases as such, we _probably_ want to still fire a `RCTRootViewFrameDidChangeNotification` style notification (maybe just... that one if we decide to rename it) so that RCTDeviceInfo can listen to it and `useWindowDimensions()` can update. Would we be open to re-introducing that override? @javache / @jpdriver FYI

For context, I currently emit the same notification from `RCTRootContentView` on React Native macOS, but would like to change/align that. https://github.com/microsoft/react-native-macos/blob/dbbfafc3b1931aa070f8dd131db14539bb3e539c/packages/react-native/React/Base/RCTRootContentView.m#L79C1-L82C1

**Pull request closed without merging**
