### PR TITLE
Changed round to roundf to fix PR #3406

### PR DESCRIPTION
**Pull request by Ajackster**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

This PR fixes a #3406 where the original person that opened the issue never made a PR.

The `Invalid layout for (1)<RCTRootContentView: 0x7bb9e0c0; reactTag: 1; frame = (0 0; 414 736); gestureRecognizers = <NSArray: 0x7bb72450>; layer = <CALayer: 0x7bb783d0>>. position: {nan, nan}. bounds: {{0, 0}, {nan, nan}}` error was being caused by a function in the [https://github.com/facebook/react-native/blob/master/React/Base/RCTUtils.m](https://github.com/facebook/react-native/blob/master/React/Base/RCTUtils.m) at line 303 where we are using `round()` which is for the type double. Changing `round()` to `roundf()` fixed the error.

Explain the **motivation** for making this change. What existing problem does the pull request solve?

This pull request solves the `Invalid layout for (1)<RCTRootContentView: 0x7bb9e0c0; reactTag: 1; frame = (0 0; 414 736); gestureRecognizers = <NSArray: 0x7bb72450>; layer = <CALayer: 0x7bb783d0>>. position: {nan, nan}. bounds: {{0, 0}, {nan, nan}}` error.

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

**Before**
screen shot 2016-12-12 at 10 23 41 am

**After**
screen shot 2016-12-12 at 10 29 44 am

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by javache** [comment]
What version of RN are you hitting this on? roundf takes in a float, so there would be precision loss when passing in a double. Perhaps you could import `tgmath.h` and use the version of round it exports?

**Comment by Ajackster** [comment]
This was being used on 0.37.0. I upgraded 0.39.1 today and it seems like the error disappeared without the `roundf`. It seems like this is a sporadic error and I don't necessarily understand the error message either. Do you think this still needs to be fixed? I can't seem to replicate the issue again.

**Comment by javache** [comment]
We made some other changes to always consistently use floats when bridging to yoga/css-layout which may help. Feel free to open a new PR if you encounter this again.

**Comment by joypatel04** [comment]
@javache Same issue encounter for me 
react-native 0.39.2

Invalid layout for (2858)<RCTView: 0x7fefec1c1240; reactTag: 2858; frame = (0 0; 329 22); layer = <CALayer: 0x610000627080>>. position: {nan, 11}. bounds: {{0, 0}, {nan, 22}}

**Comment by joypatel04** [comment]
screen shot 2017-01-05 at 11 01 10 am


@javache Can you please help me to figure out this issue's solution?

**Comment by Ajackster** [comment]
@joypatel04 Does this happen to a specific view/component? If you click 'Dismiss' it should show the view. I can try to figure it out if you send me the code for that view.

**Comment by joypatel04** [comment]
@Ajackster Here is my code so i figured that something is wrong in AccountsSummaryView's ListView like when i remove that LIstView and just render  {this.renderRecentActivities()} error goes away but with that ListView it show up.

  # AccountsSummaryView

    renderRow(rowData) {
        return (<AccountSummary account={rowData} />);
    }

    renderRecentActivities() {
        return (<RecentActivityList list={this.state.recentTransactions} />);
    }

    render() {
        return (
            <View style={styles.container}>
                <ListView contentContainerStyle={[styles.contentContainer]} dataSource={this.state.dataSource}
                    renderRow={this.renderRow.bind(this)} removeClippedSubviews={false} enableEmptySections={true} />
                {this.renderRecentActivities()}
            </View>
        );
    }


#  RecentActivities

    renderHeader(data) {
        /*global require:true*/
        /*eslint no-undef: "error"*/
        return (
            <View>
                <View style={styles.blankSpace}/>
                <View style={[styles.recentActivityWrapper]}>
                        <Text style={styles.sectionNameText}>
                            Recent Activity
                        </Text>
                </View>
            </View>
        );
    }

    renderRow(rowData) {
        return (<Transaction transaction={rowData} showCardInfo={true} showDate={true} onPress={() => this._gotoTransactionDetailView(rowData)} />);
    }

    render() {
        if (this.state.list.length > 0) {
            return (
                <View>
                    <ListView
                        dataSource={this.state.dataSource}
                        renderRow={this.renderRow.bind(this)}
                        renderHeader={this.renderHeader.bind(this)}
                        removeClippedSubviews={false}
                        enableEmptySections={true} />
                    <View style={{ padding: 15 }} />
                </View>
            );
        }
        else {
            return null;
        }
    }


# TabBar View


                   <TabBar.Item
                        icon={require('../Images/tabBar/Accounts_Inactive.png') }
                        selectedIcon={require('../Images/tabBar/Accounts_Active.png') }
                        selectedTab={false}
                        navTextColor={'#455A64'}
                        navTextColorSelected={'#00BFA5'}
                        onPress={() => {
                        } }
                        title="Accounts">
                        <ScrollView>
                            <AccountsSummaryView />
                        </ScrollView>    
                    </TabBar.Item>

**Comment by Ajackster** [comment]
@joypatel04 I think the error is in your styles. This error seems to always happen at random times but it seems that using `flexGrow` instead of `flex` in a certain spot (Most likely where height or width have been declared) made the error go away. I recommend trying to switch out each `flex` with `flexGrow` one at a time so you can see which item is actually causing the error. Hopefully this fixes your problem.

**Comment by joypatel04** [comment]
@Ajackster That should be possible. 
Let me try the way you said i'll let if i fixe the issue.

Thanks

**Pull request closed without merging**
