### PR TITLE
Update Android Performance for opening trace.html

### PR DESCRIPTION
**Pull request by xvalentino**
Right now systrace generates an html file that is using the Object.observe function which is now deprecated in most up to date browsers.

Since we don't want to depend on the systrace being up to date, we should advise opening the trace through the Tracing tool, since that is the only way to get it working until systrace removes its dependency on Object.observe.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @astreet and @bestander to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@xvalentino updated the pull request.

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by astreet** [comment]
Thanks! If Object.observe isn't available, doesn't it crash the tab instead of bring blank? It might be worthwhile to show a screenshot of what it looks like when they need to manually load...

**Comment by xvalentino** [comment]
@astreet In my experience, the page is blank (at least in Chrome) and if you open the console you get something along the lines of "Object.observe is not a function".

I think images would definitely help though.

**Comment by mkonicek** [comment]
> It might be worthwhile to show a screenshot of what it looks like when they need to manually load...

@xvalentino Could you add a screenshot please?

**Comment by hufeng** [comment]
image

ReactNative 0.26
Chrome: 
image

**Comment by xvalentino** [comment]
screen shot 2016-06-16 at 2 24 35 pm
screen shot 2016-06-16 at 2 24 55 pm

**Comment by xvalentino** [comment]
React-Native 0.27 only shows a blank page. Looks like the page varies from React-Native versions. All consistently show `Uncaught TypeError: Object.observe is not a function` in the console. I will post a picture of that.

**Comment by xvalentino** [comment]
Viewing the markdown on my repo doesn't display any of the images, should work but let's make sure I'm actually showing the image.

**Comment by mkonicek** [comment]
@xvalentino You can run the website locally using `cd website; npm install; npm start`.

**Comment by xvalentino** [comment]
Thank you @mkonicek 

Should be all set.

**Comment by astreet** [comment]
@facebook-github-bot shipit

Thanks!

**Comment by xvalentino** [comment]
@astreet sorry it looks like there was some kind of failing test before, merge please! Thank you!

**Comment by christopherdro** [comment]
screen shot 2016-07-01 at 6 00 50 pm

I still get the following error.

**Comment by astreet** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/853611391432486/int_phab) to review.

**Pull request closed without merging**
