### PR TITLE
Fix KeyboardAvoidingView to keep frame height

### PR DESCRIPTION
**Pull request by shunwitter**
### KeyboardAvoidingView

There is an issue like below when `behavior="height"` is selected.

KeyboardAvoidingView stops working when you change input type (e.g. from English to Emoji).
This is how to reproduce the issue.

- Use `KeyboardAvoidingView behavior="height"`
- Focus input field
- Keyboard appears
- Change keyboard type
- `KeyboardAvoidingView` goes back to the original height, therefore nested elements return to the original position.

Related issue: https://github.com/facebook/react-native/issues/26293

### KeyboardAvoidingViewExample

Added `height` option example in RNTester.

## Changelog

[General] [Fixed] - Fix KeyboardAvoidingView's behavior "height"

### Before

KeyAvoidingView-demo

### After

Fixed

### CODE REVIEW

**Comment by vomchik** [comment]
@shunwitter Thanks! Works for me.
Could you fix conflicts?

**Comment by shunwitter** [comment]
@vomchik I guess it's already fixed thanks to [this commit](https://github.com/facebook/react-native/commit/b08fff6f869e00c20c0dcdf7aca71284c2f276f0).

**Comment by krskrs** [comment]
Hi @shunwitter I'm resuming this PR  from 1 year ago, because we're facing this exact issue and it looks like that so far the only reasonable fix is yours. You said that the issue had been fixed in another commit, but after checking it thoroughly it doesn't seem the case. Latest code, on master, still doesn't include the key change you proposed in this PR, and none of the changes from the commit you referenced to as the fix seem to address this particular issue.
Currently we have 'forked' this component and we're using our version, with a fix identical to yours, but we believe this issue should be resumed and taken into consideration b/c it's a quite relevant one.
Can I ask you if you have kept using your patched code? Or if you just have stopped using react native and lost the interest in this PR, as we're almost 100% sure the issue is still there.

**Comment by shunwitter** [comment]
hi @krskrs, I recently noticed this issue still exists when I create a new react-native project. I have been using my version of KeyboardAvoidingView component but maybe I can create a new PR for this.

**Comment by krskrs** [comment]
Hi @shunwitter ! I have been working on a small variation of this fix. The core principle is the same, but I also tried to use a more accurate height than the one simply captured on first onLayout event, because, in some cases, I have seen multiple consecutive onLayout events with slightly different height values occurring just after component instantiation. Moreover, just in case there were external causes which might cause the base frame height to change, I try to keep it updated, as, again, using the initial value won't be enough in such cases.

https://gist.github.com/krskrs/4a3d347a8a42435e74dc32b8c3abe93b

**Comment by shunwitter** [comment]
Thank for sharing it, @krskrs . I'll try that out :)

**Comment by krskrs** [comment]
@shunwitter thank you. When you do it, feel free to comment or ask anything, if you want. Any comment or suggestion would be appreciated. ;)  Meanwhile I will keep it updated in case we make any further changes.

**Pull request closed without merging**
