### PR TITLE
Added FanVision Bolt to showcase

### PR DESCRIPTION
**Pull request by jeanregisser**
Hi there,

I showed this app to a couple of FB people at the React Europe conf in June (@ndfred @tadeuzagallo @ericvicenti @astreet and others), they suggested I should submit it to be part of the showcased apps.

It's used in production since the beginning of the year and fully usable at all NASCAR events.
The external accessory receives the digital TV signal broadcasted around the track by an antenna on a FanVision truck.
People rent the accessory there at our kiosks. It also recharges your smartphone battery.

I linked to a demo video so people can actually see what it does without having the required accessory.

The app is of course powered by React Native. I've built custom modules to integrate the native code that does all the heavy work (talking to the accessory, demuxing the raw data, decoding the audio and video, processing the additional data for all stats, etc).

Let me know what you think.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @RetroPoktan to be potential reviewers.

**Comment by lacker** [comment]
Seems like a cool app. This seems cool for the showcase, although that link and title don't seem to quite explain what it is. How about a different infoTitle, like... well what *is* this thing exactly? It's an app plus accessory that gives you live TV at NASCAR events?

**Comment by jeanregisser** [comment]
Yes, I've updated the infoTitle with more details.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/519951851531577/int_phab) to review.

**Pull request closed without merging**
