### PR TITLE
Fixing a recurring crash when replacing a switch with a spinner

### PR DESCRIPTION
**Pull request by dannolan**
Hi there Ladies and Gents!

I've made a simple change which is the order of operations with which updates are propagated for the switch component :D. Currently we propagate to the native props in the onChange callback **after** we send through the onChange command. In a fairly common iOS idiom, where you use a spinner in place of a switch while you're doing a network load, if you re-render a cell that has the spinner, the callback fires after it's rendered, which means the function continues and crashes when trying to update its own native props, as itself has become... the dreaded null.

I've tested this extensively locally and decided I may as well send a pull request. It's a very minor change but it makes the component more flexible and predictable without side effects :dancer: 

I love you guys!

### CODE REVIEW

**Comment by kmagiera** [comment]
Thanks for sending this @dannolan

Do you mind squashing this simple change into a single commit that is rebased on current master as opposed to being 2 commits + 2 merge commits

Please also fix ident in line 76 and I'll be happy to merge this

**Comment by satya164** [comment]
Any updates on this? @dannolan

**Comment by dannolan** [comment]
I didn't get the alert - I'll do this today.

**Comment by facebook-github-bot-5** [comment]
@dannolan do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by dannolan** [comment]
I'll just reissue this on the current master

**Pull request closed without merging**
