### PR TITLE
Add observers for local notifications

### PR DESCRIPTION
**Pull request by slycoder**
This commit adds the delegate hooks so that local notifications get
passed onto the JS and adds a new event listener type for local
notifications.

Also add functions to clear local notifications

### CODE REVIEW

**Comment by slycoder** [comment]
@jacobrosenthal

**Comment by antihate** [comment]
Why this PR haven't merged yet? Doesn't it supposed to fix this #4053?

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by antihate** [comment]
Thanks @nicklockwood =)

**Pull request closed without merging**
