### PR TITLE
Show an example of composition in the Text docs.

### PR DESCRIPTION
**Pull request by StevenXL**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

- There is no example in the documentation of the Text component on how
  to use composition in order to "reuse" styles. This is left to the
user to infer. By providing an example, we clear things up a bit.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
@StevenXL updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@StevenXL updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@StevenXL updated the pull request.

**Comment by JoelMarcey** [comment]
This seems reasonable to me. Thanks. I am going to shipit.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3740902) to review internal test results.

**Pull request closed without merging**
