### PR TITLE
Fix RNTester on Windows

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
Currrent, RNTester can not work on windows. 
* Fixes https://github.com/facebook/react-native/issues/19654.

Test Plan:
--
pass all current ci.

Release Notes:
--
 [GENERAL] [INTERNAL] [RNTester] - fix RNTester on windows.

### CODE REVIEW

**Comment by gengjiawen** [comment]
I can split the pr, they are in same pr because I want to fix build problem on windows, which still exists (see https://github.com/facebook/react-native/issues/19654).

As for `packager.sh`, it has to be removed if you want to make it on windows. As for `max-workers`, I think it can add back.

**Comment by gengjiawen** [comment]
@pvdz The metro issue has been around for a month. Can you help on this issue ?

**Comment by gengjiawen** [comment]
@hramos This can be merged.

**Comment by hramos** [comment]
@gengjiawen I'll defer to @pvdz for approval + merging.

**Comment by gengjiawen** [comment]
@pvdz Can you merge this pr ?

**Comment by pvdz** [comment]
@gengjiawen Can you confirm this is still an issue on Metro 42.2 (depending on a new version of Babel) and RN 0.57 (which should resolve most pending Windows issues)? The error reported in #19654 was almost certainly caused by the Babel regression that has been fixed by now.

As for this PR, it _still_ drops typing that we want to keep and it _still_ drops a shell script we want to keep so those points have not been addressed.

Please confirm this issue is still blocking you with the latest metro/rn or close this ticket if that's now resolved. Thank you!

**Comment by gengjiawen** [comment]
The type thing is fixed by metro, I have confirmed here @kelset. As I stated in clarification, My main fix is refactor current unix-like bash to nodejs script so we can test RNTester on windows.

**Comment by gengjiawen** [comment]
@dulmandakh @janicduplessis Can you guys review my pr ? Thanks.

**Comment by gengjiawen** [comment]
@rafeca I have updated the code.

**Comment by rafeca** [comment]
This looks good to me, I'm going to import this to Phabricator.

@hramos : any thoughts?

**Pull request closed without merging**
