### PR TITLE
add settings to android webview to allow enabling file scheme and thi…

### PR DESCRIPTION
**Pull request by thurber**
Add two props to android WebView:
- acceptFileSchemeCookies: controls whether or not android WebViews that load file scheme urls are allowed to used cookies
- acceptThirdPartyCookies: controls whether or not android WebViews allow third party cookies

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @spicyj and @caabernathy to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hramos** [comment]
What issue is this solving? Can you add tests?

**Comment by thurber** [comment]
I had needed this to be able to view pdfs via an implementation of Mozilla's pdfjs embedded as a file url, when the pdfs required a previously obtained session cookie to access. I've since implemented a workaround, so happy to close out this PR if no one else needs it.

**Comment by jacobp100** [comment]
There's another PR (10946) that lets you add behaviour to the existing web view. I think this is quite specific, so I think we should wait and see what happens with said PR.

**Comment by lacker** [comment]
I think we have too many possible configurable behavior things to add every prop to WebView, so if the approach in 10946 works that is ideal. Let's close this pull request but we can reopen if more general approaches fail.

**Pull request closed without merging**
