### PR TITLE
Change the 'propTypes.elementStyle' value

### PR DESCRIPTION
**Pull request by crdesai**
In "Pass Styles around" section, it seems that the intent was to use "Text.propTypes.style" as the value for "elementStyle" to demonstrate passing element styles across components. I have made the change accordingly, so please review it.

### CODE REVIEW

**Comment by ide** [comment]
elementStyle is passed to a View.. this isn't right.

**Comment by crdesai** [comment]
@ide Are you suggesting that the <View> on which elementStyle is being applied should be changed to <Text>?

**Comment by ide** [comment]
Sure, or leave the example as-is. The code you introduced isn't right though..

**Comment by mkonicek** [comment]
`elementStyle` is still applied to the `View` below. I don't think this is right so will close this. Let me know if I'm mistaken so we can reopen :)

**Pull request closed without merging**
