### PR TITLE
[RN][Android] remove JSIModule from UIManagerModule

### PR DESCRIPTION
**Pull request by Sunbreak**
## Summary:

`UIManagerModule` inherates `JSIModule` because `UIManager` inherates `JSIModule`

```mermaid
classDiagram
    class NativeModule {
        +initialize()
        +onCatalystInstanceDestroy()
        +invalidate()
    }
    NativeModule <|-- BaseJavaNativeModuele
    class BaseJavaNativeModuele {
        +invalidate()
    }
    BaseJavaNativeModuele <|-- ReactContextBaseJavaModule
    class ReactContextBaseJavaModule {
    }
    ReactContextBaseJavaModule <|-- UIManagerModule
    class UIManagerModule {
        +initialize()
        +onCatalystInstanceDestroy()
    }
    class JSIModule {
        +initialize()
        +onCatalystInstanceDestroy()
    }
    JSIModule <|-- UIManager
    class UIManager {
    }
    UIManager <|-- UIManagerModule
    UIManager <|-- FabricUIManager
    class FabricUIManager {
        +initialize()
        +onCatalystInstanceDestroy()
    }
```

With the patch, the inheritance is more reasonable

```mermaid
classDiagram
    class NativeModule {
        +initialize()
        +onCatalystInstanceDestroy()
        +invalidate()
    }
    NativeModule <|-- BaseJavaNativeModuele
    class BaseJavaNativeModuele {
        +invalidate()
    }
    BaseJavaNativeModuele <|-- ReactContextBaseJavaModule
    class ReactContextBaseJavaModule {
    }
    ReactContextBaseJavaModule <|-- UIManagerModule
    class UIManagerModule {
        +initialize()
        +onCatalystInstanceDestroy()
    }
    class UIManager {
    }
    UIManager <|-- UIManagerModule
    class JSIModule {
        +initialize()
        +onCatalystInstanceDestroy()
    }
    JSIModule <|-- UIManagerJSI
    UIManager <|-- UIManagerJSI
    class UIManagerJSI {
    }
    UIManagerJSI <|-- FabricUIManager
    class FabricUIManager {
        +initialize()
        +onCatalystInstanceDestroy()
    }
```

## Changelog:

[ANDROID][Refactor] - Remove JSIModule from UIManagerModule

## Test Plan:

TODO

### CODE REVIEW

**Comment by javache** [comment]
What makes you say this "class hierarchy is more reasonable"? Does it enable behaviours / changes that you couldn't before? JSIModule is a simple marker interface (which we're planning to remove), so it shouldn't cause any issues.

**Comment by Sunbreak** [comment]
It is confusing to find `UIManagerModule` inherting `JSIModule` when walking through new architecture logic.

Jump code inside `JSIModuleHolder.getJSIModule` and find too many implementations of `JSIModule`, especially `ReanimatedUIManager`
Screenshot 2023-09-14 at 19 44 12

**Comment by Sunbreak** [comment]
Another PR #39445 helps to clearify the hierarchy as well

**Comment by javache** [comment]
@arushikesarwani94 is looking at removing the JSIModule abstraction which should simplify this. Thanks for the PR!

**Pull request closed without merging**
