### PR TITLE
[Website] Upgrade all dependencies. Use React 14.

### PR DESCRIPTION
**Pull request by christopherdro**
Required changes to get website running locally.

### CODE REVIEW

**Comment by vjeux** [comment]
Feel free to merge if the site is still running, lgtm

**Comment by ide** [comment]
The test failed, here's the relevant bits of the error...

```
Bundling 161 JS files for /react-native/404.html   -   HTML blocks UI, JS Gen does not
HTML Gen:        
Error: SyntaxError: Unexpected token :
    at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/guard.js:27:12
    at onOutputGenerated (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/index.js:96:9)
    at Object.renderReactPage.done (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:345:7)
    at renderReactPage (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/renderReactPage.js:130:17)
    at renderComponentPackage (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:331:3)
    at routePackageHandler (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:274:5)
    at onComputePackage (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/index.js:100:9)
    at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/guard.js:29:10
    at onWarmed (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/Packager.js:270:9)
    at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/node_modules/async/lib/async.js:116:25
    at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/node_modules/async/lib/async.js:24:16
    at transformModuleImpl (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/Packager.js:206:5)
    at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/Packager.js:234:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

That's about as specific as it gets unfortunately.

**Comment by christopherdro** [comment]
@ide No real luck yet trying to figure out whats going on. Running  `node /server/generate.js` doesn't reproduce any errors. The only real difference i've been able to notice is where locally its shows 
`Bundling 160 JS files for /react-native/404.html` whereas on Travis is shows `Bundling 161 JS files for /react-native/404.html`. Would be interested to see what that 1 file is that's not being included locally.

**Comment by christopherdro** [comment]
So the build for the website passes when using Node 5 instead of 4 on travis. 
However, this causes the obj-c test to fail. 

I also attempted to switch to the latest version of xcode 7.1 and came across https://github.com/facebook/xctool/issues/619. This is probably worth opening up a separate issue but I just wanted to reference it here first.

Will continue looking into it.

**Comment by christopherdro** [comment]
@vjeux @ide 
Looks like the website test is passing now. I ran the test a few times to double check.

**Comment by vjeux** [comment]
@skevy was looking into it today. Can you review? Lgtm

**Comment by skevy** [comment]
I'll merge in the morning.

Tomorrow (or over he holiday) I'm going to actually go through and modernize this website codebase a bit...but this PR is a good first step. Gracias @christopherdro

**Comment by christopherdro** [comment]
:+1: Sounds good! Thanks @skevy

**Comment by christopherdro** [comment]
@skevy Any updates? Would like to get this merged in.

**Comment by satya164** [comment]
There are conflicts now!

**Comment by christopherdro** [comment]
@satya164 What are the conflicts?

**Comment by christopherdro** [comment]
Ya thats from #5080 being merged in

**Comment by christopherdro** [comment]
Not sure what happened here. I guess just forget about this PR.

**Comment by skevy** [comment]
@christopherdro sorry about that. I honestly just got busy with the holidays and forgot. :(

Did #5080 fix the same things as this PR...or do we still need to do what's in here?

**Comment by christopherdro** [comment]
It appears #5080 had a few of the same changes but mine were based on upgrading React to 0.14.5 and all other dependencies to the their latest versions.

I don't know what happened earlier when I tried rebasing to master and resolve the merge conflicts but screwed up on something.

**Comment by vjeux** [comment]
You guys all have commit access, feel free to merge it in whenever this is working

**Pull request closed without merging**
