### PR TITLE
chore: remove the unused packages from package.json

### PR DESCRIPTION
**Pull request by nimish-gupta**
## Summary

There are couple of packages which are installed as dependency but are not directly used in the project. In this PR I have remove those packages from dependency from the package.json.

## Changelog

[General] [Removed] - Remove the unused packages from package.json

### CODE REVIEW

**Comment by cpojer** [comment]
This is awesome! @nimish-gupta can you walk me through the process you used to find unused dependencies? I wanna just make sure we aren't removing anything that we still need.

**Comment by gengjiawen** [comment]
Do they originally belong to `react-native-cli` ?

**Comment by cpojer** [comment]
@gengjiawen yes, or Metro. See https://github.com/facebook/react-native/issues/23313 for more information.

**Comment by nimish-gupta** [comment]
@cpojer for removing the packages
-  I just search the dependencies through out the repo, and if that is not used from anywhere I just removed it.
- I also did `yarn remove` but it doesn't cause any change because these dependencies are indirectly used by different packages.

**Comment by nimish-gupta** [comment]
@cpojer yeah sure I will work on this one.
 > As a next step, do you think you could identify the largest dependencies and make an issue so we can analyze which ones we may want to consider stripping? Thank you!

**Comment by dalcib** [comment]
It seems that `lodash` is no longer used either.
https://github.com/facebook/react-native/search?q=lodash&type=Code

**Comment by cpojer** [comment]
Importing again because there was an issue yesterday…

**Pull request closed without merging**
