### PR TITLE
update GettingStarted.md for new iOS run

### PR DESCRIPTION
**Pull request by GantMan**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

the iOS run is now aligned with Android and can be run preferably from the command line.

### CODE REVIEW

**Comment by Kureev** [comment]
Hi @GantMan and thanks for your contribution!

I believe both options (manual run and CLI-run) are valid. So, instead of replacing a manual run instructions, can you just add a `$ react-native run-ios` as an alternative to it?

It may looks like this:
```
- `$ react-native run-ios` or open `ios/AwesomeProject.xcodeproj` and hit "Run" button in Xcode
```

**Comment by GantMan** [comment]
Hi @Kureev - I've updated the doc as you suggested :+1:

**Comment by Kureev** [comment]
ping @vjeux @mkonicek @DavidYKay

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
