### PR TITLE
Add Fuzzy to Showcase

### PR DESCRIPTION
**Pull request by sdimmick**
Hi there! 

We at [Fuzzy](https://www.yourfuzzy.com/) just released the first version of our React Native app. We had an overwhelmingly positive experience, and would love to be added to the showcase.

I'm happy to provide more information. Thanks!

### CODE REVIEW

**Comment by lacker** [comment]
Hi, thanks for submitting a pull request! According to the instructions in this file:

Thousands of applications use React Native, so we can't list all of them
in our showcase. To be useful to someone looking through the showcase,
either the app must be something that most readers would recognize, or the
makers of the application must have posted useful technical content about the
making of the app. It also must be useful considering that the majority of
readers only speak English. So, each app in the showcase should link to either:
1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native
For each app in the showcase, use infoLink and infoTitle to reference this
content.

I'm closing this pull request since it does not adhere to these guidelines.

**Comment by sdimmick** [comment]
@lacker thanks for the follow-up! I did include a link to a technical post about building our app in React Native:

```js
{
...
infoLink: 'https://medium.com/@stephen.dimmick/why-we-chose-react-native-40f80ff5662e#.uw6smhg6n',
infoTitle: 'Why We Chose React Native',
...
}
```

**Comment by lacker** [comment]
Yeah, sorry for being annoying about this, but we ended up filtering on "on a funded startup or public company blog" just kind of for branding type stuff, we are trying to filter for recognizable brands here.

**Comment by sdimmick** [comment]
Haha, gotcha. No worries. I'll re-open this PR in a year once we're more recognizable :)

**Comment by lacker** [comment]
awesome 😃

**Pull request closed without merging**
