### PR TITLE
Apple TV support 4: support for input (tvOS focus engine)

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
* Motivation

Support Apple TV input using the remote or keyboard.  TouchableHighlight and TouchableOpacity have been modified so that TV remote navigation will work with existing projects that use these components.

* Test plan

Existing CI for tvOS still passes.  New snapshot tests for programmatically changing focus will be added in a later PR.

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
In looking at the Travis CI logs, it seems that the automated tests will not run correctly if StatusBar and PushNotification don't exist.  So I added those back to the Apple TV build, and stubbed out the parts that don't compile on tvOS.  After this, I was also able to enable most of the UIExplorerSnapshot tests.

**Comment by dlowder-salesforce** [comment]
@javache here is round 3 of Apple TV changes -- these make Apple TV fully working with Siri Remote and keyboard input.  Travis CI seems broken now... objc-test.sh, objc-test-tvos.sh, npm test, and npm flow check are all passing in my environment.

**Comment by chirag04** [comment]
@dlowder-salesforce after updating to master it seems like project.pbxproj is full of

```
464A35741DB137BD0070CA98 /* PBXContainerItemProxy */ = {
+                 isa = PBXContainerItemProxy;
+                 containerPortal = 464A34C01DAEB7F20070CA98 /* RCTLinking.xcodeproj */;
+                 proxyType = 2;
+                 remoteGlobalIDString = 2D2A28471D9B043800D4039D;
+                 remoteInfo = "RCTLinking-tvOS";
+         };
```

Wondering if it matter and if yes can it be optional?

**Comment by dlowder-salesforce** [comment]
@chirag04 yes those should be there... the project now has tvOS targets and RCLinking-tvOS is needed.  They shouldn't matter unless you're doing a tvOS build.

**Comment by dlowder-salesforce** [comment]
I closed this PR, will submit it again later once Travis stability issues are under control.

**Pull request closed without merging**
