### PR TITLE
Don't hardcode 'localhost:8081' as the _hmrURL in the Bundler

### PR DESCRIPTION
**Pull request by skevy**
@martinbigio this fixes your TODO. :rocket: :rocket: :rocket:

### CODE REVIEW

**Comment by skevy** [comment]
Along with some of the changes in https://github.com/facebook/react-native/pull/5741 we should no longer be bound by the crazy confines of localhost 8081 :)

**Comment by martinbigio** [comment]
Awesome, thanks!

**Comment by martinbigio** [comment]
@facebook-github-bot shipit

**Comment by martinbigio** [comment]
@skevy `Server/index.js` and `Bundler/index.js` could be used without an actual packager server running. We shouldn't be passing the host and port as options for these 2 components but directly on the `hmrBundle` function on the bundler. Would you mind making that change?

**Comment by skevy** [comment]
@martinbigio good call on this. Made the changes and tested... :)

**Comment by martinbigio** [comment]
Awesome, thanks!. Will merge now :)

**Pull request closed without merging**
