### PR TITLE
Small typo s/they/the/

### PR DESCRIPTION
**Pull request by denmark**
Just a typo

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @JoelMarcey to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
I cannot do that @lacker, because @denmark does not have an active CLA on file.

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
I cannot do that @lacker, because @denmark does not have an active CLA on file.

**Comment by lacker** [comment]
Dangit @facebook-github-bot-2 can you get your story straight with @facebook-github-bot-8 ?

**Comment by facebook-github-bot-1** [comment]
Something went wrong when importing this pull request. Please cc someone from the team at fb to help with importing this.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
I cannot do that @JoelMarcey, because @denmark does not have an active CLA on file.

**Comment by facebook-github-bot-8** [comment]
Something went wrong when importing this pull request. Please cc someone from the team at fb to help with importing this.

**Comment by hramos** [comment]
@denmark can you open this PR against master? Generally we only cherry-pick commits from master into the versioned releases.

**Comment by denmark** [comment]
@hramos Sure, closing this one.  Opened a new one here: https://github.com/facebook/react-native/pull/8813

**Comment by JoelMarcey** [comment]
> can you open this PR against master? Generally we only cherry-pick commits from master into the versioned releases.

@hramos good catch!!

**Pull request closed without merging**
