### PR TITLE
[ANDROID] color support for TextInput secureTextEntry={true}

### PR DESCRIPTION
**Pull request by brunobar79**
Color property is ignored for TextInput with secureTextEntry={true} on Android.

This is coming  from #6540 and being split into 2 PRs by suggestion of @dmmiller.
As he mentioned does almost the same  except it #6064 doesn't handle null case.

Working example:

scn949wlce

### CODE REVIEW

**Comment by dmmiller** [comment]
Will you also add a change to the Text sample which shows it working please?  And then I'll accept.

**Comment by brunobar79** [comment]
@dmiller Sure. What kind of change?

**Comment by dmmiller** [comment]
Look at TextExample.android.js in UIExplorer.  It has a bunch of Text boxes with examples of how to use various properties.  Add a new one as appropriate to show the usage.

**Comment by brunobar79** [comment]
@dmiller NVM. I know what are you talking about. I'll update shortly

**Comment by brunobar79** [comment]
@dmiller added example

**Comment by dmmiller** [comment]
@facebook-github-bot shipit

Awesome, thanks for doing this.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by cupofjoakim** [comment]
Are there any information on when/if this is being added to an actual release?

**Pull request closed without merging**
