### PR TITLE
[Android] Checkbox to inherit from AppCompatCheckBox

### PR DESCRIPTION
**Pull request by vonovak**
## Motivation

The checkbox components inherits from `android.widget.CheckBox`. `AppCompatCheckBox` offers better appearance and support for advanced features (eg. tinting) on older APIs. 

~~However, the build fails for some reason; If somebody could shed some light on this, I'd appreciate it.~~ Thanks for the comment, I was being blind and somehow ignored the BUCK file.

## Test Plan

I have created a simple app with a checkbox.

Screenshot from android 4.1 (current master):

Screenshot after applying the change, also android 4.1:

## Related PRs

https://github.com/facebook/react-native/pull/18300 (this PR is needed to support tinting on older android api levels)

## Release Notes

[ANDROID]  [ENHANCEMENT]  [Checkbox] - Checkbox inherits from AppCompatCheckBox

### CODE REVIEW

**Comment by janicduplessis** [comment]
@vonovak Thanks for the PR! React Native supports [BUCK](https://buckbuild.com/setup/getting_started.html) on Android, this is the part of the build that fails. You will need to add the dependency to the BUCK file in the checkbox folder. You can probably have a look at another component that uses the support library to figure out what you need to add.

**Comment by vonovak** [comment]
@janicduplessis thanks for the quick response, since I'm not experienced in using buck myself, I somehow ignored the buck files. the PR should be good for merge.

**Comment by janicduplessis** [comment]
Looks good! I’ll check out your other PR too soon. 

@facebook-github-bot shipit

**Comment by hramos** [comment]
Thanks for the contribution! It looks like I'll need to update some buck related files on our side before I can merge this. I'll add it to my task list. No further action is required on your part -- please do not add commits to this PR now that it has been approved as doing so may prevent it from getting merged.

**Comment by hramos** [comment]
Looked into this again, the actual error we're seeing is:

```
Warning: com.facebook.react.views.checkbox.ReactCheckBox: can't find referenced method 'boolean isChecked()' in program class com.facebook.react.views.checkbox.ReactCheckBox
Warning: com.facebook.react.views.checkbox.ReactCheckBoxManager: can't find referenced method 'void setOnCheckedChangeListener(android.widget.CompoundButton$OnCheckedChangeListener)' in program class com.facebook.react.views.checkbox.ReactCheckBox
Warning: com.facebook.react.views.checkbox.ReactCheckBoxManager: can't find referenced method 'void setEnabled(boolean)' in program class com.facebook.react.views.checkbox.ReactCheckBox
Warning: there were 3 unresolved references to program class members.
```

I need to get back to this again later.

**Comment by janicduplessis** [comment]
@hramos Any update on this, could be related with the crazyness in https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/third-party/android/support/v7/appcompat-orig/BUCK.

**Comment by hramos** [comment]
The error logs were cleared, so let's try importing again.

**Pull request closed without merging**
