### PR TITLE
Rename WebView postMessage method to postMessageNative.

### PR DESCRIPTION
**Pull request by soldovskij**
Rename WebView postMessage to postMessageNative. The old name "postMessage" breaks the functional of some scripts in WebView using cross-domain communication via postMessage. Example: https://api-maps.yandex.ru/2.1/?lang=ru_RU

## Motivation (required)

The old name "postMessage" breaks the functional of some scripts in WebView using cross-domain communication via postMessage. This bug avalible if WebView has onMessage callback.

## Test Plan (required)

Not working

Working

Send message to react-native WebView - window.postMessageNative("data", "*");

Replace original window.postMessage - bad idea;

### CODE REVIEW

**Comment by soldovskij** [comment]
This bag avalible only if WebVev has onMessage callback

**Comment by farazs** [comment]
I think something like `window.rnBridge.postMessage` would be preferable. It would also let you use the  built-in`JavascriptInterface` directly on Android. The current implementation is slightly bugged.

**Comment by axten** [comment]
This PR is strongly needed, because many users get Error `Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined`

see  #10865 for detailed info.

**Comment by Thomas101** [comment]
Just ran into this today. Real pain :(

**Comment by mcmar** [comment]
The current implementation is completely 100% broken and unusable. Using it results in a red page that says `Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined`. It always results in that red page, no matter what you do.

Given that context, I think we should merge this. Something is clearly better than nothing. And even nothing is better than something that's 100% broken.

**Comment by davidgross** [comment]
100% agree with @mcmar we are needing to be able to use onMessage for an app we are building.

**Comment by twairball** [comment]
Current implementation breaks for webviews that load Meteor js content.

**Comment by shergin** [comment]
I believe we can fix this without breaking backward compatibility. What if we can call `window.originalPostMessage` inside our overridden `postMessage`? Seems we can do it on Android right now, but we have to change the way we communicate with native side on iOS.

**Comment by twairball** [comment]
`window.postMessage` is a browser API. The subject issues are due to RCTWebview hijacking this window function. 

In the case for RN Webviews I think its safe to assume we are using `postMessage` to achieve some kind of bridging between webview <--> RN ? 

If so, if the concern is breaking backwards compatibility, does it make sense to instead have a parallel `window.postMessageNative` that doesn't impact current `window.postMessage`?

**Comment by neerfri** [comment]
@mkonicek is this an acceptable PR to solve #10941 ?

**Comment by nazrdogan** [comment]
@twairball Did you solve your problem. I m facing same issue.

**Comment by twairball** [comment]
@nazrdogan the proposed changes in this PR work. I made my own fork for current version react-native (warning; lots of work) and added similar changes for renaming `postMessage` to `postMessageNative`

**Comment by henrylearn2rock** [comment]
This should definitely **not** be closed.

**Comment by patientplatypus** [comment]
Yeah, so this issue (see here: https://github.com/facebook/react-native/issues/10865) was brought up in *2016* and I'm still getting it in production. And a bot automatically closes a PR to fix this? Get it together you guys.

**Comment by ohtangza** [comment]
This PR is something we MUST have. Currently, it conflicts several web SDKs including Google's, which relies on `window.postMessage`.

**Pull request closed without merging**
