### PR TITLE
Native ARIA Roles: Remove JS Shim

### PR DESCRIPTION
**Pull request by NickGerleman**
Summary:
### Stack

ARIA roles in React Native are implemented on top of accessibilityRole. This is lossy because there are many more ARIA roles than accessibilityRole. This is especially true for RN on desktop where accessibilityRole was designed around accessibility APIs only available on mobile.

This series of changes aims to change this implementation to instead pass the ARIA role to native, alongside any existing accessibilityRole. This gives the platform more control in exactly how to map an ARIA role to native behavior.

As an example, this would allow mapping any ARIA role to AutomationControlType on Windows without needing to fork to add new options to accessibilityRole.

It also allows greater implementation flexibility for other platforms down the line, but for now, iOS and Android behave the same as before (though with their implementation living in native).

### Diff

This removes the JS shimming of `role` to `accessibilityRole`. It can be landed when the native `role` implementation for both iOS and Android are live for versions we service OTA.

This will require any out of tree platforms to add their own native implementation for `role` to continue to work.

Changelog: [Internal]

Differential Revision: D45432518

### CODE REVIEW

**Comment by NickGerleman** [comment]
FYI @acoates-ms @Saadnajmi

To keep `role` working, and to map it to map the various ARIA roles, you will want to add a native implementation in desktop once this diff (represented as the last commit in this PR) lands.

**Comment by Saadnajmi** [comment]
> FYI @acoates-ms @Saadnajmi
> 
> To keep `role` working, and to map it to map the various ARIA roles, you will want to add a native implementation in desktop once this diff (represented as the last commit in this PR) lands.
> 
> 

Is the plan to land this with 0.72 or 0.73? If so, then we can pre-emptively plan for it. I'm pretty sure on macOS already have a native implementation for 'role' because we had to.. 
https://github.com/microsoft/react-native-macos/blob/main/React/Base/RCTConvert.m#L1437-L1503

**Comment by NickGerleman** [comment]
> > FYI @acoates-ms @Saadnajmi
> > To keep `role` working, and to map it to map the various ARIA roles, you will want to add a native implementation in desktop once this diff (represented as the last commit in this PR) lands.
> 
> Is the plan to land this with 0.72 or 0.73? If so, then we can pre-emptively plan for it. I'm pretty sure on macOS, we already have a native implementation for 'role' because we had to.. https://github.com/microsoft/react-native-macos/blob/main/React/Base/RCTConvert.m#L1437-L1503

It will land in 0.73. The existing implementation there maps `AccessibilityRole` values, but not ARIA role values. You can take a look at the iOS change here to see what roughly changes.

**Comment by Saadnajmi** [comment]
> > > FYI @acoates-ms @Saadnajmi
> > > To keep `role` working, and to map it to map the various ARIA roles, you will want to add a native implementation in desktop once this diff (represented as the last commit in this PR) lands.
> > 
> > 
> > Is the plan to land this with 0.72 or 0.73? If so, then we can pre-emptively plan for it. I'm pretty sure on macOS, we already have a native implementation for 'role' because we had to.. https://github.com/microsoft/react-native-macos/blob/main/React/Base/RCTConvert.m#L1437-L1503
> 
> It will land in 0.73. The existing implementation there maps `AccessibilityRole` values, but not ARIA role values. You can take a look at the iOS commit here to see what roughly changes. ([4bfd06d](https://github.com/facebook/react-native/commit/4bfd06d9ed70937fa1027211d05db32237ef65f2) at time of writing)

@mischreiber @harrieshin @chiuam FYI. I added stuff to our backlog for 0.73, but looks like we'll need to revisit accessibility in a future merge.

**Comment by jonthysell** [comment]
Is this Fabric-only or will this affect Paper? The decision/assertion made by the RN release crew was that all new APIs/props (esp. for web / xplat) would be explicitly treated as experimental and Fabric-only, so as not to block releases waiting on Paper implementations. This has trickled down to customers, aka RNW took this to not worry about having to update Paper and instead focus on the Fabric implementation.

RNW's tracking of web props/aria for Fabric:

* https://github.com/microsoft/react-native-windows/issues/11185
* https://github.com/microsoft/react-native-windows/issues/11432

**Comment by NickGerleman** [comment]
This affects Paper as well. Most of the existing web props like ARIA role do work on paper in 0.71, with the exception of a couple layout ones which were implemented in native first instead of JS.

**Pull request closed without merging**
