### PR TITLE
Ignore another autogenerated folder.

### PR DESCRIPTION
**Pull request by ianlevesque**
This folder contains only autogenerated files but was missing from the gitignore.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @ide to be potential reviewers.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
@ianlevesque updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10022/files/4a8a94bc811e29ba6db4a1fa7fbd4fbe437d345c..7c79b534c1b13c78f5e6259c781e7816c4a2f449)

**Comment by ide** [comment]
Sorry, trying again.

@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3917014).

**Pull request closed without merging**
