### PR TITLE
UIExplorer duplicate example fix

### PR DESCRIPTION
**Pull request by brentvatne**
It's a great example but we probably only need to show it once

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
good point :+1:

**Comment by nicklockwood** [comment]
Can you remove the other one instead? The list seems to be alphabetical apart from that one.

**Comment by nicklockwood** [comment]
This has now been fixed in an internal PR anyway.

**Pull request closed without merging**
