### PR TITLE
Fix layout width calculation in onTextLayout

### PR DESCRIPTION
**Pull request by reepush**
## Summary
There is a rounding issue in layout calculation when using onTextLayout method in Text component on Android.
As you can see in the example below onTextLayout returns 3 lines, but in fact text is rendered in 2 lines:

Screenshot 2023-02-19 at 23 48 53

This happens because `(int) width` casting works like `Math.floor`, but after changing it to `Math.round` we get correct result:

Screenshot 2023-02-19 at 23 51 11

## Changelog

[ANDROID] [FIXED] - Fix layout width calculation in onTextLayout

## Test Plan

This issue can be tricky to reproduce as width calculation depends on device width. I'm attaching code that I used to reproduce it. You need to tap on the screen to run through different sentences and sooner or later you will get the one with this rounding issue.

<details>
  <summary>Code to reproduce</summary>

```js
import React, { useState, useEffect } from 'react'
import { SafeAreaView, Text, View } from 'react-native'

function App() {
  const [state, setState] = useState({
    index: 0,
    lines: [],
    sentences: [],
  })

  const onTextLayout = (event) => {
    const lines = event.nativeEvent.lines
    console.log(JSON.stringify(lines, null, 2))

    setState(state => ({ ...state, lines }))
  }

  useEffect(() => {
    fetch('https://content.duoreading.io/20-the-adventures-of-tom-sawyer/translations/english.json')
      .then(response => response.text())
      .then(response => {
        setState(state => ({ ...state, sentences: JSON.parse(response) }))
      })
  }, [])

  return (
    <SafeAreaView style={{ flex: 1, padding: 30 }}>
      <View style={{ flex: 1 }} onTouchStart={() => setState(state => ({ ...state, index: state.index + 1 }))}>
        <Text style={{ fontSize: 22 }} onTextLayout={onTextLayout}>
          {state.sentences[state.index]}
        </Text>

        {state.lines.map((line, index) => (
          <View
            key={index}
            style={{
              position: 'absolute',
              top: line.y,
              left: line.x,
              width: line.width,
              height: line.height,
              opacity: 0.3,
              backgroundColor: ['red', 'yellow', 'blue'][index % 3],
            }}>
          </View>
        ))}
      </View>
    </SafeAreaView>
  )
}

export default App
```
</details>

### CODE REVIEW

**Comment by javache** [comment]
This seems similar to https://github.com/facebook/react-native/commit/8b00b4f2860de50e5cefa43735d32bf4bdb8518d (cc @lunaleaps). Should we constrain the fix similarly?

**Comment by reepush** [comment]
@javache I checked commit that you mentioned and it seems `Math.ceil` is used everywhere and is preferable way to do it. I updated my changes replacing `Math.round` with `Math.ceil` and everything continue to work.

**Comment by javache** [comment]
The changes in https://github.com/facebook/react-native/commit/8b00b4f2860de50e5cefa43735d32bf4bdb8518d are only applied in Android 11+. Your change affects all versions of Android, including pre-6.0 (which I'm not even sure we support anymore), can you check if we need to move this to a separate branch, just for 11+?

**Comment by reepush** [comment]
@javache @lunaleaps Yes, I'm testing on Android 11+ and 0.71.3. Also now I understand what checks for `VERSION_CODES.M` (Android 6) and `VERSION_CODES.Q` (Android 10) means and we need to implement this fix only for Android 11+. I just copied the code that @lunaleaps implemented.

**Pull request closed without merging**
