### PR TITLE
Detox setup

### PR DESCRIPTION
**Pull request by AnshG714**
## Summary
This PR isn't really meant to be merged in right now. This is more of a call for help, as suggested by @rickhanlonii. I primarily need help with the iOS setup. This is a branch that's being worked on from the MLH react-native repository.

## Background
We have migrated the RNTester app to the packages folder (and deleted the old RNTester app). This was meant to separate RNTester from the react-native repository. 

## How to set up the project to replicate error
After cloning the repo, run `yarn link` in the root `react-native` repository. Then, run `yarn link react-native` in `react-native/packages/RNTester`. Run `yarn install && cd ios && pod install.` Open `RNTester.xcworkspace` in the `ios` directory. You should see build errors (the error I get when I open it up is related to the `XCTest` framework not being recognisable.

### CODE REVIEW

**Comment by rickhanlonii** [comment]
@AnshG714 can you post a screenshot of the error you're seeing?

**Comment by AnshG714** [comment]
@rickhanlonii The error is an Xcode build error: `'XCTest/XCTest.h' file not found`. Don't see any more information. This error comes up in every file in `RNTesterUnitTests` that references `XCTest.h`.

**Comment by rickhanlonii** [comment]
@AnshG714 Can you share the version of Xcode/Node/etc that you're using?

You can run `react-native info` for everything except the Xcode version.

**Comment by rickhanlonii** [comment]
It looks like `RCTMultipartStreamReaderTests.m` has the wrong target, it should be a test target but I'm not sure how to fix that.

**Comment by AnshG714** [comment]
Hey @rickhanlonii!
My Xcode version is 10.3.
Here are my other version info:

`
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 26.95 MB / 8.00 GB
    Shell: 5.0.16 - /usr/local/bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 29
      Build Tools: 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /usr/bin/javac
    Python: 3.6.8 - /Applications/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 1000.0.0 
  npmGlobalPackages:
    *react-native*: Not Found
`

**Comment by rickhanlonii** [comment]
@alloy sorry for the ping, are you familiar with `XCTest/XCTest.h file not found`? Some searching I've done suggests that this may a related to the pod config, is this a quick fix or is there a place we can look deeper?

**Comment by alloy** [comment]
@rickhanlonii Don’t know offhand, but I’ll take a look-see 👍

**Comment by alloy** [comment]
The `XCTest/XCTest.h file not found` is caused because all the test files are added to the normal app target, which is not a test target and so the XCTest framework will not be available. Removing all those test files from the normal app target should solve that issue.

Screenshot 2020-07-20 at 15 45 04

**Comment by rickhanlonii** [comment]
Wow thanks @alloy, that fixed it 💛

**Comment by nitint007** [comment]
Hi All,

I understand this would not be the right stage for my question but I think the techies involved here can answer and possible solutions.

Does DETOX work for a web app developed using react.js for UI testing automation?
We are planning to use DETOX for web (as mentioned above) app and react native apps for test automation.

Looking forward for your valuable inputs.

**Comment by rickhanlonii** [comment]
Hey @nitint007, not sure, I would ask in https://github.com/wix/Detox

**Comment by rickhanlonii** [comment]
Going to close this in favor of https://github.com/facebook/react-native/pull/29567#pullrequestreview-465347805

**Pull request closed without merging**
