### PR TITLE
[rfc] Update `fbjs-scripts` to ^0.7.0

### PR DESCRIPTION
**Pull request by steveluscher**
`fbjs-scripts` 0.4.0 has Babel 5 as a dependency, which causes some amount of havoc when you're trying to use `react-native` in a project that's otherwise dependent on Babel 6 and using the flat-installing npm >=3.

Test plan: Travis/Circle CI

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @davidaurelio to be potential reviewers.

**Comment by steveluscher** [comment]
This PR requires changes. Please hold.

**Comment by facebook-github-bot-6** [comment]
@steveluscher updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@steveluscher updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@steveluscher updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@steveluscher updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@steveluscher updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@steveluscher updated the pull request.

**Comment by steveluscher** [comment]
OK. This is ready to look at. The [rfc]-ness of this PR comes in the form of this meta-question: do we want to keep supporting the `inlineRequires` option, now that `babel-preset-fbjs` lets you configure this per-project. cc/ @zpao.

**Comment by facebook-github-bot-7** [comment]
@steveluscher updated the pull request.

**Comment by javache** [comment]
LGTM. Can you import to Phabricator and make the required changes to update node modules. For the inline requires question, what does the `babel-preset-fbjs` API look like? Could you update `TransformOptions.js` internally to make use of it?

**Comment by steveluscher** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/507820962740405/int_phab) to review.

**Comment by facebook-github-bot-9** [comment]
@steveluscher updated the pull request.

**Comment by steveluscher** [comment]
The API for the new preset looks like this:

```
require('babel-core').transform('code', {
  presets: [
    require('babel-preset-fbjs/configure')({
      inlineRequires: true,
    }
  ]
});
```

I took a look through `TransformOptions`. It's probably best that I leave that up to @davidaurelio, should you want to go all the way!

**Pull request closed without merging**
