### PR TITLE
[NativeAnimation] Move RCTNativeAnimatedModule onto the main queue

### PR DESCRIPTION
**Pull request by ryangomba**
We're mutating dictionaries on one thread for bookkeeping (anytime we receive a call over the bridge) and iterating over them on the main thread each frame (in `updateAnimations`). Seems like this can all happen on the main thread without issue. Am I missing something?

**Test plan (required)**

Run UIExplorer NativeAnimated examples before and after - compare the results. Nothing should have changed.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @buba447 to be a potential reviewer.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-1** [comment]
@ryangomba updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@ryangomba updated the pull request.

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by javache** [comment]
cc @ritzau

**Comment by ryangomba** [comment]
@janicduplessis can I loop you into this?

**Comment by janicduplessis** [comment]
LGTM, this should make this properly thread safe.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
