### PR TITLE
Update IntegrationWithExistingApps.md for Swift 3

### PR DESCRIPTION
**Pull request by ganjianwei**
Update integrating with existing Swift App code for Swift 3.

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by lacker** [comment]
@ganjianwei We need a signed CLA to ship this - would you mind signing it?

**Comment by ganjianwei** [comment]
Just signed the CLA.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
