### PR TITLE
Add "camigo" to showcase

### PR DESCRIPTION
**Pull request by mcliquid**

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-1** [comment]
@mcliquid updated the pull request.

**Comment by nicklockwood** [comment]
@mcliquid has the app been released yet? When I tried the app store link it said it wasn't available in the German store.

**Comment by mcliquid** [comment]
Yes, it should be availible for all countries. 

[Screenshot to prove](http://s33.postimg.org/qj6shmw9b/Bildschirmfoto_2016_06_09_um_07_41_26.png)

**Comment by mcliquid** [comment]
You may should check the links again. New update is available world wide:

https://itunes.apple.com/de/app/camigo/id1088876278?l=de&ls=1&mt=8
https://play.google.com/store/apps/details?id=com.mobileemotion.camigo

**Comment by mkonicek** [comment]
I can open the links. They take me to the German App Store, not sure that's intentional?

@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1741403186073195/int_phab) to review.

**Comment by mcliquid** [comment]
@nicklockwood How long until it's online? Thanks!

**Pull request closed without merging**
