### PR TITLE
Docs: Revise language around mobile web

### PR DESCRIPTION
**Pull request by ericvicenti**
Addresses some criticism: https://twitter.com/ryanflorence/status/806236197731172352

As the author of this original text, I promise no offense was meant towards mobile web technologies.

I just want to help people build apps that feel great.

### CODE REVIEW

**Comment by ryanflorence** [comment]
Nice, since it's really about inputs and not platforms, I'd probably just say "Touch events are much more complex than mouse events" since some devices have both the mouse and a touch screen.

**Comment by ericvicenti** [comment]
Revised to "Touch handling" because the responder system is inherently more complicated than events. This doc is meant to make that apparent but maybe isn't very clear.

**Comment by ryanflorence** [comment]
> Poor visual feedback and cancel-ability are leading factors that make some web apps feel less comfortable than native apps.

You can provide poor visual feedback on native too, I'm not sure why you feel inclined to talk about web? I'm unclear why delivering code via html or the app store matters?

**Comment by ryanflorence** [comment]
anyway, sorry, not trying to be a pain in the neck, the doc just sounds a bit elitist, it definitely takes more work on the web, so if you feel like its important to bring that up, then go for it.

Thanks for making the updates :)

**Comment by lacker** [comment]
We don't really need to insult the mobile web in the docs, plenty of thought leaders are out there doing it for us. I suggest removing all anti-mobile-web statements :P

**Comment by ericvicenti** [comment]
@lacker I feel misunderstood because there is really no insult here. Touch handling is genuinely more complicated than cursor events.

But to keep everybody happy I've removed all references to web. Lets land this

**Comment by ryanflorence** [comment]
> Touch handling is genuinely more complicated than cursor events.

And the web has touch.

**Comment by ericvicenti** [comment]
I was originally criticizing mobile browser vendors for not implementing a nice touch responder system like they have in their proprietary walled gardens. Its unfair for them to push the implementation burden to the application developers on mobile web.

**Comment by lacker** [comment]
LGTM - need to wait for travis/circle to merge though 🙄

**Comment by lacker** [comment]
NM i was just in firefox

**Comment by ryanflorence** [comment]
@ericvicenti totally agree there 😭

**Pull request closed without merging**
