### PR TITLE
Fixed e2e tests for HMR

### PR DESCRIPTION
**Pull request by bestander**
HMR e2e test red-screened because of the wrong path to react.

**Test plan (required)**

Make sure e2e tests pass

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by bestander** [comment]
tested locally, test is fixed

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
lgtm

**Comment by mkonicek** [comment]
>  wrong path to react

What was wrong about the path?

**Comment by bestander** [comment]
| What was wrong about the path?

It changed with a big revamp of paths between React and React-Native.
React is sort of a standalone independent dep now

**Pull request closed without merging**
