### PR TITLE
Make KeyboardAvoidingView with behavior="height" resize on keyboard close

### LINKED ISSUE #13754: KeyboardAvoidingView with behavior="height" doesn't resize back on keyboard close
### Description
When using the KeyboardAvoidingView with behavior set to height it works correctly the first time you open the keyboard, but after keyboard is dismissed it doesn't return to it's original position.

tnyozqi5fe

Recreation:
https://snack.expo.io/rJYAymwy-

The code below can be used to recreate this problem:
```
<View style={{flex: 1, backgroundColor: "blue"}}>
	<KeyboardAvoidingView behavior="height"  style={{ backgroundColor: "green", paddingTop: 22, flex: 1, justifyContent: 'center'}}>
	    <View>
	          <TextInput style={{height: 30, backgroundColor: "red"}} />
	    </View>
	</KeyboardAvoidingView>
</View>
```

### Additional Information

* React Native version: 0.43.4
* Development Operating System: MacOS
* Dev tools: This was shown on the IOS simulator but the problem also occurs on android

### PR DESCRIPTION
**Pull request by WaldoJeffers**
Fixes #13754 

## Test Plan

The bug was present because `flex: 0` was applied even if the keyboard was closed (ie `this.state.bottom === 0`), and also because the initial frame height was never saved. On every render, the code used the current frame height, which was incorrect because the keyboard height is subtracted each time.
Also removed a weird `componentWillUpdate` which mutated the next state.

**Before**

**After**

## Related PRs

This PR does not require a documentation as it fixes a bug. It's related to #16965, but goes further. Credits to @shauns for the initial commit, and thanks to @matthieulemoine for his help!

## Release Notes

[ANDROID] [BUGFIX] [KeyboardAvoidingView] - Make KeyboardAvoidingView resize back on keyboard close
[IOS] [BUGFIX] [KeyboardAvoidingView] - Make KeyboardAvoidingView resize back on keyboard close

### CODE REVIEW

**Comment by dNitro** [comment]
@hramos , this PR needs reviewer. Issue still presents on latest versions ( 0.55.4 ).

**Comment by WaldoJeffers** [comment]
Yep, would appreciate some reviewers, but didn't know whom to ping :/

**Comment by hramos** [comment]
Looking at the blame/history information for the files touched by the PR is a good way to find people that could review your PR.

**Comment by raphaelrk** [comment]
Would be great to have this fix in, our app has UI's that don't scale back to their full size after the keyboard closes and I assume this would fix it

**Comment by WaldoJeffers** [comment]
Will try to resolve the conflicts today :)

**Comment by WaldoJeffers** [comment]
@raphaelrk @hramos I merged & fixed all tests but one, I'm having trouble figuring out what's wrong :/

**Comment by hramos** [comment]
CocoaPods failure is unrelated. Tests look good.

**Comment by WaldoJeffers** [comment]
Maybe @nicklockwood could help reviewing?

**Comment by bcalik** [comment]
So why this is not merged yet?

**Comment by hramos** [comment]
@bcalik it has not been merged because it has not been reviewed. I myself am not comfortable reviewing this area of the code, otherwise I'd jump in.

**Comment by WaldoJeffers** [comment]
@hramos Isn't there a better system to find people who might be able to review this one?

I tried to look into these files' history and pinged someone, but from the outside of the React Native team, it's frankly very hard to say who's in the team, who's still active, who will answer you. It's quite frustrating to dedicate some time contributing, knowing that you have absolutely no idea if there's a probability to find a reviewer and to see your PR merged.

If you're not familiar with this code, do you know who would be more familiar with it, even if it's not the person who will do the review in the end?

**Comment by hramos** [comment]
If the people who've worked on the file before haven't responded, I'd look through the recent PRs that have been merged and see if any of the people who reviewed them can take a look.

The issue you raised is one we see within the team as well - we're a small team and there's components like this one where there is no clear owner. Typically, if there's a bug affecting one of our products, the person affected will take ownership of shipping the fix as they're in the best position to validate the fix.

We'd like to get to a point where we can process more of these contributions and get feedback back as fast as possible, but we're not there yet.

**Comment by PeteTheHeat** [comment]
This change seems very reasonable to me, merging.

**Pull request closed without merging**
