### PR TITLE
Fixed RCTWebSocketDebugger contains SockeRocket Source code，causing dupl...

### PR DESCRIPTION
**Pull request by dolphinux**
Fixed RCTWebSocketDebugger contains SockeRocket Source code，causing duplicate symbol conflict. Because the project has integrated sockeRocket by Cocoapods

### CODE REVIEW

**Comment by dolphinux** [comment]
When the script download is complete, a notification is sent to the observer. After receiving notification observer, it can be used to detect script load times, trigger other asynchronous tasks.

**Comment by vjeux** [comment]
@facebook-github-bot import

**Comment by nicklockwood** [comment]
This should no longer be an issue in 0.4.4.

**Pull request closed without merging**
