### PR TITLE
Improve display of error in debugger console

### PR DESCRIPTION
**Pull request by satya164**
The error message in chrome debugger are useless right now. As you cannot get any useful info from them except the error message. Ideally it should contain the proper stack trace with source maps to actually be useful.

Currently, the only alternative is, find the file name and line number on phone, and then open the corresponding file in the sources panel, then scroll to the lines number, as opposed to clicking a link on the console and directly going to the file.

I've been looking into how to do it. And would really like your thoughts on how to achieve it.

1. We can forget sourcemaps, and just log the error object with `console.error(e)` instead of how we're doing it right now, i.e. - `console.error(e.message)`. Doing this will help in jumping to the line in the bundle much easier. Even if sourcemaps are not there, you quickly get the idea of where the error came from, and adding breakpoints in the transformed source. Even if it's worse than sourcemaps, it's pretty convenient.

2. We can compromise a bit, and show a `console.log` instead of actual error (the stack trace is not useful anyways), and then log the actual error as soon as source maps arrive. This PR implements that currently.

react native debugger google chrome today at 2 42 13 am

This is how it looks in the console, which I think is eons better than what we currently have.

**Caveats:** Currently there seems to be bug in master where the sourcemap is not loaded until you  interact with app. Also the parser we're using for getting the stacktraces from sourcemaps right now doesn't seem to give column numbers.

Would love your thoughts and ideas on how to improve this. I believe debugging should be as easy as possible.

### CODE REVIEW

**Comment by martinbigio** [comment]
cc @vjeux

**Comment by satya164** [comment]
@vjeux What do you think?

**Comment by vjeux** [comment]
> Ideally it should contain the proper stack trace with source maps to actually be useful.

Why isn't it the case? It used to work, no?

**Comment by satya164** [comment]
@vjeux Yes, it's not the case for several releases for now. Not exactly sure which version. But there is comment added here - https://github.com/facebook/react-native/commit/34d57afc32b25984741d3772a7cf832cfa189d79

**Comment by satya164** [comment]
@vjeux I think this is the commit where it was removed - https://github.com/facebook/react-native/commit/0c83407dd2a748d31bc2dd17477c6dff59f1ef54

cc @javache

**Comment by facebook-github-bot-8** [comment]
@martinbigio would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Pull request closed without merging**
