### PR TITLE
made all package versions strict

### PR DESCRIPTION
**Pull request by bestander**
Yet another breakage of npm installation motivated me to fix all direct dependencies of react native.
This will make RN dependencies not patchable without a new release of RN but to me it seems a lesser problem then fixing master branch and chasing package maintainers.

### CODE REVIEW

**Comment by bestander** [comment]
From https://circleci.com/gh/facebook/react-native/4936:

EndToEndTest@0.0.1 /tmp/react-native-w7Xd8VPp/EndToEndTest
└─┬ UNMET PEER DEPENDENCY react@15.0.0
  └── fbjs@0.8.0

**Comment by bestander** [comment]
Open to discussion.

**Comment by cpojer** [comment]
If you do this, it will mean that for every tiny bug that gets fixed in a small package you'll have to tag a new release of react-native.

**Comment by bestander** [comment]
I realize that.
Imagine if we shipped shrinkwrap, it would be the same.
Community members actually requested shrinkwrap earlier but it ended up being flaky.

**Comment by bestander** [comment]
And BTW releasing a patch of RN is quite easy, a matter of a few minutes now.

**Comment by skevy** [comment]
I think the biggest problem with this is the strict Babel deps.

We've done this before, but had to revert. The problem is transitive dependencies. Babel-plugins may be locked in the RN repo, and we may depend on a specific version of Babel-Core. But those plugins and and their transitive dependencies won't be locked, and thus you may have several versions of babel-core/babylon/etc that get installed. It leads to an impossible situation of fixing a broken Babel dependency.

Perhaps @kittens can say more about this.

**Comment by janicduplessis** [comment]
We should probably also update all the dependency version number to the one used when using ^ before doing that, this might downgrade some packages otherwise. Also as @skevy pointed I think we should keep using ^ for babel.

**Comment by janicduplessis** [comment]
Also have you considered using ~ instead? Would that have also prevented the recent breakages?

**Comment by bestander** [comment]
Talked to @sebmarkbage in an internal group.
He has a good point that we loose ability for patches if we make all strict.

**Comment by bestander** [comment]
Considering that it does not happen too often maybe it is too early to make this change now.
@janicduplessis good point about ~.
@sebmarkbage what do you think if we use ~ instead of ^?
It probably will allow patches but not minor version updates.

**Comment by ide** [comment]
Which package was the problem here? If it was something specific like node-haste, we could use ~ just for that package.

**Comment by bestander** [comment]
If we are not consistent in our versioning then it will not stick.
JSON does not have comments and 1-2 outstanding with ~ don't make sense.

**Comment by janicduplessis** [comment]
Maybe ~ for every current / new package and ^ for babel since it has so many inter dependencies.

**Comment by Daniel15** [comment]
> Also have you considered using ~ instead? 

I think this makes sense. Patch versions should always be safe to immediately upgrade, whereas a minor or major update should generally have some amount of testing.

**Comment by bestander** [comment]
Implemented in a new PR of https://github.com/facebook/react-native/pull/7064

**Pull request closed without merging**
