### PR TITLE
Update LayoutWithFlexbox.md

### PR DESCRIPTION
**Pull request by foobar8675**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @dabbott and @JoelMarcey to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@foobar8675 Hi. Thanks for the pull request. Please sign the CLA as linked to above. Also, please make this merge into `master` instead of `0.29-stable`; otherwise, the fix will not propagate to other releases. We can cherry-pick into `0.29-stable` as needed.

**Comment by foobar8675** [comment]
done. the fix was a tiny typo anyways.

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by JoelMarcey** [comment]
@foobar8675 

This has already been fixed in `master` 8 days ago. It just wasn't cherry-picked into `0.29-stable`. Probably doesn't need to be since `0.30-stable` is coming out soon.

**Pull request closed without merging**
