### PR TITLE
[Codegen] extract emitPromise from parsers modules to shared parsers-primitives

### PR DESCRIPTION
**Pull request by AntoineDoubovetzky**
## Summary

This PR is a task from https://github.com/facebook/react-native/issues/34872:
> Extract the content of the case 'Promise' ([Flow](https://github.com/facebook/react-native/blob/b444f0e44e0d8670139acea5f14c2de32c5e2ddc/packages/react-native-codegen/src/parsers/flow/modules/index.js#L90-L97), [TypeScript](https://github.com/facebook/react-native/blob/00b795642a6562fb52d6df12e367b84674994623/packages/react-native-codegen/src/parsers/typescript/modules/index.js#L197-L205)) into a single emitPromise function in the parsers-primitives.js file. Use the new function in the parsers.

Note that this PR should be merged after https://github.com/facebook/react-native/pull/34933

## Changelog

[Internal] [Changed] - Extract contents of the case 'Promise' into a single emitPromise function inside parsers-primitives

## Test Plan

I tested using jest and flow commands.

### CODE REVIEW

**Comment by rshest** [comment]
This PR is a bit confusing, tbh... the title says one thing, but the code does at least two other things?.. :)

**Comment by AntoineDoubovetzky** [comment]
This PR depends on https://github.com/facebook/react-native/pull/34933 that extracts `assertGenericTypeAnnotationHasExactlyOneTypeParameter` and that's why https://github.com/facebook/react-native/pull/34933 should be merged first and then we should rebase this PR

**Comment by rshest** [comment]
@AntoineDoubovetzky Ah, this makes sense, thanks for correcting the title!

**Comment by AntoineDoubovetzky** [comment]
I rebased after adding a commit to https://github.com/facebook/react-native/pull/34933

**Pull request closed without merging**
