### PR TITLE
Support static values in NativeAnimated transforms on iOS

### PR DESCRIPTION
**Pull request by janicduplessis**
Support static values (non-animated) in transform config like Android already does.

**Test plan**
Tested in UIExplorer native animated example by adding a transform with a static value and comparing with JS.

### CODE REVIEW

**Comment by ryangomba** [comment]
Looks good

**Comment by ide** [comment]
Please ping me when the tests pass (Travis hasn't even started yet 😩) and I'll ship this.

**Comment by janicduplessis** [comment]
@ide ping

**Comment by ide** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
