### PR TITLE
CI now builds docs website and deploys it to /%version% path

### PR DESCRIPTION
**Pull request by bestander**
Copy of #5760 reverted merge.

We need to preserve history of docs changes on the webserver.
The goal is to allow users to browse outdated versions of docs.
To make things simple all websites will be released to https://facebook.github.io/react-native/releases/version/XX folder when there is a branch cut.

I switched from Travis CI to Cirle CI because it works faster and I am more familiar with it.

How it works:

1. If code is pushed to `master` branch then CI will build a fresh version of docs and put it in https://github.com/facebook/react-native/tree/gh-pages/releases/next folder.
Github will serve this website from https://facebook.github.io/react-native/releases/version/next URL.
All relative URLs will work within that website

2. If code is pushed to `0.20-stable` branch then CI will build a fresh version of docs and put it in https://github.com/facebook/react-native/tree/gh-pages/releases/0.20 folder.
Github will serve this website from https://facebook.github.io/react-native/releases/version/0.20 URL.
All relative URLs will work within that website

3. If code is pushed to any `XX-stable` or `master` branch and this commit has a tag `latest` then CI will build a fresh version of docs and put it in https://github.com/facebook/react-native/tree/gh-pages/ folder.
Github will serve this website from https://facebook.github.io/react-native/ URL.
All relative URLs will work within that website

I have tested this in a fork, this is the example:
http://bestander.github.io/react-native/
http://bestander.github.io/react-native/releases/next
http://bestander.github.io/react-native/releases/0.40
http://bestander.github.io/react-native/releases/0.41

Caveats: Searchdocs algolia works only with stable version of website, so it will redirect from a versioned to the stable one.

Next steps:
- widget/page to switch between versions of websites (still to decide)
- (?) simple UI indication mechanism that you are observing not latest/stable docs

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by foghina** [comment]
*dances around a fire*

*mumbles unspeakable words*

*stirs a large pot of magical potions*

@facebook-github-bot shipit

**Comment by bestander** [comment]
I think the bot not only ignores my shipit commands but also she ignores PRs coming from me

**Comment by bestander** [comment]
@facebook-github-bot shipit :( :( :(

**Comment by foghina** [comment]
@facebook-github-bot shipit

**Comment by foghina** [comment]
sheeeeeep eeeeeeet

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by sunnylqm** [comment]
What a lovely bot. lol

**Pull request closed without merging**
