### PR TITLE
Added `inverted` prop to ScrollView

### PR DESCRIPTION
**Pull request by jakex7**
## Summary

This PR refers an already existing `inverted` prop for FlatList and implements the same mechanism for ScrollView.
The `inverted` prop makes content appear from the bottom of the View.

> if the first item should appear at the bottom, items inside ScrollView should be placed in reversed order.

## Changelog

[General] [Added] - Add inverted prop to ScrollView component

## Test Plan

https://user-images.githubusercontent.com/39670088/180623991-81f173b6-a5e8-45af-9b40-b6d64966bfbb.mov

### CODE REVIEW

**Comment by cipolleschi** [comment]
Hi @jakex7, many thanks for this PR. Some tests are failing. Could you update them, please?

**Comment by jakex7** [comment]
> Some tests are failing. Could you update them, please?

Hi @cipolleschi, sure. They're failing because the style object is different from the previous snapshot. I used an array to combine three styles, instead of the previously used `StyleSheet.compose` to combine two. Is it ok, or should I do it differently? Maybe compose those three using `Object.assign`?

**Comment by javache** [comment]
Does this need to be a ScrollView prop? Couldn't anyone just create their own ScrollView wrapper that uses `contentContainerStyle` to achieve this behaviour? We should prefer to keep the props-list for components small.

**Comment by jakex7** [comment]
@javache This way I wanted to get a similarity to the behavior in FlatList where is similar `inverted` prop. Using transform (scale) to achieve something like this is rare, so hardly anyone will figure it out. If it will be available as a prop, many people will be able to use it

**Comment by javache** [comment]
I'd recommend you publish this as a separate library, or publish a code snippet somewhere. For FlatList, it is necessary to build in support for inversion as it affects calculation of visible cells.

**Review by viniciuspetrachin — COMMENTED** [review]
It makes sense, and would be very good in the specific case I'm having with a client in the house.

**Comment by sergeyzhukov** [comment]
I think anyone who needs this can add transform style by itself, no need to add this to core RN.

**Pull request closed without merging**
