### PR TITLE
Improve the documentation for ListView and ListViewDataSource

### PR DESCRIPTION
**Pull request by gwmccull**
## Motivation (required)

What existing problem does the pull request solve?
My motivation was to improve the documentation for ListView and ListViewDataSource because I always have trouble remembering how they work and the documentation was lacking an example for `cloneWithRowsAndSections`

My PR does the following:
* add a note about how headers and footers are rendered on a horizontal ListView
* fix a typo in an example
* clarify that the sectionIdentities should match the keys or array indexes of the data source
* add an example of cloneWithRowsAndSections
* add notes on the return values of `getRowCount` and `getRowAndSectionCount`

## Test Plan (required)

n/a; documentation only

screenshot of ListViewDataSource changes

### CODE REVIEW

**Comment by gwmccull** [comment]
@javache any advice on how I can move this one along?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/improve-the-documentation-for-listview-and-listviewdatasource

**Comment by gwmccull** [comment]
@hramos Do you need me to make any updates so this can be merged?

**Comment by hramos** [comment]
LGTM.

**Pull request closed without merging**
