### PR TITLE
ReactActivity extends AppCompatActivity

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

Google recommends to extend AppCompatActivity. and This PR changes ReactActivity to extend AppCompatActivity

## Changelog

[Android] [Changed] - ReactActivity extends AppCompatActivity

## Test Plan

CI is green and everything should work as usual.

### CODE REVIEW

**Comment by dulmandakh** [comment]
@mdvacca I just realized that I had learned something while working on landing Android Support Library 28.0.0. Please import it and see if it works. Thank you very much.

**Comment by mdvacca** [comment]
There is an internal build error because of lack of dependency but buck works fine, I will update that dependency and then land this

**Comment by mdvacca** [comment]
This PR produced runtime crashes with errors:
`
You need to use a Theme.AppCompat theme (or descendant) with this activity.
`

We should flag this PR as a backward in-compatible change for next release
CC @cpojer, @hramos

**Comment by dulmandakh** [comment]
@mdvacca I couldn't find non AppCompat theme reference in RN repo. But I agree that we should add notes about it.

**Pull request closed without merging**
