### PR TITLE
fix: multiple modal on iOS

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
This PR aims to resolve.
https://react-native.canny.io/feature-requests/p/multiple-modal-components
https://github.com/facebook/react-native/issues/3445

## Summary

In order to open multiple modals at once, they need to be nested within a modal on iOS. To fix this issue, we mount each modal into a new UIWindow. `pageSheet` and `formSheet` modal presentation styles are exceptions, they animate the behind view so it cannot be presented in a new window so we use the last presented controller for them to match native behavior. 

## Changelog:

[iOS] [Fixed] - Multiple modals

## Test Plan

Verified the existing and added functionality in the RN Tester app.

### CODE REVIEW

**Comment by lfoliveir4** [comment]
@intergalacticspacehighway why this merge is blocked?

**Comment by intergalacticspacehighway** [comment]
@lfoliveir4 only collaborators can merge PR.

**Review by lucianomlima — APPROVED** [review]

**Comment by lfoliveir4** [comment]
@lucianomlima When you can review and dive into this PR, can you please let us know?

**Comment by carloslibardo** [comment]
Why this PR doesn't be merged?

**Comment by carloslibardo** [comment]
Hello @intergalacticspacehighway , i upgrated my app to your branch because i'm with the same issue, and your solution works, in some cases...

When i already has a modal open and another modal will be opened, for example:

```
const [modalOpen, setModalOpen] = useState(false)
setTimeout(() => {
    setModalOpen(true)
}, 1000)

return(
    <>
        <Modal visible={true}/>
        <OtherModal visible={modalOpen}/>
    </>
)
```

works fine, but if a have a flow of modals, for example:

```
const [currentModal, setCurrentModal] = useState('modal1')

return(
    <>
        <Modal1 visible={currentModal === 'modal1'}><Button onClick={() => {setCurrentModal('modal2')}}/></Modal1>
        <Modal2 visible={currentModal === 'modal2'}><Button onClick={() => {setCurrentModal('modal3')}}/></Modal2>
        <Modal3 visible={currentModal === 'modal3'}/></Modal3>
    </>
)
```

**Comment by intergalacticspacehighway** [comment]
@carloslibardo Thanks for testing this out. I tried to analyse the issue and I get this log on running your second example
```
 [Presentation] Attempt to present <RCTModalHostViewController: 0x7fd1a00abb20> on <RCTModalHostViewController: 0x7fd1a04137e0> (from <RCTModalHostViewController: 0x7fd1a04137e0>) whose view is not in the window hierarchy.
```

I think it tries to open the second modal before the first one is completely dismissed and there's where it breaks. Changing the above code to something like below works.

```
 <Modal
        visible={currentModal === 'modal1'}
        transparent
        onDismiss={() => {
          setCurrentModal('modal2');
        }}>
          <Button
            title="111"
            onPress={() => {
              setCurrentModal('dummyState');
            }}
          />
      <Modal visible={currentModal === 'modal2'} transparent>
          <Button
            title="button 2"
            onPress={() => {
              setCurrentModal('modal3');
            }}
          />
      </Modal>
```

I'll try to find a solution!

**Comment by carloslibardo** [comment]
@intergalacticspacehighway thanks for reply and keep trying to solve this problem =)

I tried use your second sample to solve my problem, using modal as children of modal, but doesn't works correctly.

**Comment by carloslibardo** [comment]
@intergalacticspacehighway some updates?

**Comment by AlkanV** [comment]
any update on this?

**Comment by KingAmo** [comment]
hi all , any update ?

**Comment by lfoliveir4** [comment]
@intergalacticspacehighway What problem are we facing for this PR to be merged? Many UI's use flows with multiple modals... This PR would make life easier for many engineers... Any updates on it?

**Comment by thenriquedb** [comment]
+`1

**Comment by YangJonghun** [comment]
Unfortunately this PR can't be fix below case
(below code use [react-native-modal](https://github.com/react-native-modal/react-native-modal) for transition)

```
const positionStyle = [
  { top: 200, left: 200 },
  { top: 200, right: 200 },
  { bottom: 200, left: 200 },
  { bottom: 200, right: 200 },
]

const colors = ['red', 'purple', 'gray', 'orange']
const modals = [0, 1, 2, 3]

const App = () => {
  const [visible, setVisible] = useState(0)
  return (
    <>
      <View
        style={{ height: '100%', width: '100%', justifyContent: 'center', alignItems: 'center' }}
      >
        <TouchableOpacity onPress={() => setVisible(v => (v + 1) % 5)}>
          <Text>Press me</Text>
        </TouchableOpacity>
      </View>
      {modals.map((_v, i) => (
        <Modal isVisible={i + 1 === visible} key={i}>
          <View
            style={{
              position: 'absolute',
              justifyContent: 'center',
              alignItems: 'center',
              ...positionStyle[i],
              backgroundColor: colors[i],
            }}
          >
            <TouchableOpacity onPress={() => setVisible(v => (v + 1) % 5)}>
              <Text>Press me</Text>
            </TouchableOpacity>
          </View>
        </Modal>
      ))}
    </>
  )
}
```
The code above expects the old modal to disappear when the new one appears,
but the native implementation of this PR stacks the new modal on top of the old one,
so the new one will disappear. (Android works well)

**Comment by intergalacticspacehighway** [comment]
@carloslibardo i pushed a few changes to the PR. Can you try your usecase again?

**Comment by erquhart** [comment]
This is the [most upvoted open PR](https://github.com/facebook/react-native/pulls?q=is:pr+is:open+sort:reactions-+1-desc) on the repo, would be amazing to get multiple modals working. A bit crippling for app developoers trying to go all in on RN.

**Comment by fabOnReact** [comment]
This PR is included in the [react-native-improved](https://github.com/fabriziobertoglio1987/react-native-improved) library:

# react-native-improved

- **Supports ONLY react-native 0.73**.
- Supports only old architechture (new architechture is WIP)

## Set-up

In package.json

```diff
 "scripts": {
+  "postinstall": "yarn run react-native-patch"
 }
```

Then

## npm

```sh
npm install react-native-improved --save-dev
```

## yarn v1

```sh
yarn add react-native-improved --dev
```

**Comment by erquhart** [comment]
Still the most upvoted PR on the repo.

**Comment by erquhart** [comment]
pour one out

**Pull request closed without merging**
