### PR TITLE
Set text color to white instead of dark grey

### PR DESCRIPTION
**Pull request by olgarithm**
## Summary

Hello! I'm working on the Messenger Desktop team at Facebook, and I noticed that the message text in the LogBox is not very visible on the dark background.
https://ibb.co/Hg0WYj9

Proposing this change so that the text is more visible- not sure this is the right change (or color), but getting my foot in the door! :)

## Changelog

[General] [Changed] - Updated plaintext message text to be white so it show up against dark background

## Test Plan

I'm not exactly sure how to test this out on my personal machine. This is my first time touching React Native code

### CODE REVIEW

**Comment by lunaleaps** [comment]
Hi @olgatron9000, I haven't been able to reproduce this issue locally. Can you provide steps for how to get this logbox with black text?

**Review by lunaleaps — CHANGES_REQUESTED** [review]
Requesting changes for follow-up to repro steps

**Comment by vaibhav4516** [comment]
Think it needs some modification, some checks are failing.
Thanks , Happy Coding !

**Review by vaibhav4516 — COMMENTED** [review]
Think it needs some modification, some checks are failing.
Thanks , Happy Coding !

**Pull request closed without merging**
