### PR TITLE
[fix] Update 0.72-stable with rncore podspec fix

### PR DESCRIPTION
**Pull request by hoxyq**
cherry-picking #36571 into 0.72-stable

### CODE REVIEW

**Comment by cipolleschi** [comment]
I think we need to look at all the CI failures before we can merge this. :(

**Comment by hoxyq** [comment]
> I think we need to look at all the CI failures before we can merge this. :(

To fix JS ones we need to run prettier, or maybe cherry-pick https://github.com/facebook/react-native/pull/36568, where this line is changed

**Comment by kelset** [comment]
yeah don't worry too much about fixing CI with this PR, I was planning to try and tackle it with some local commits

**Comment by cipolleschi** [comment]
@hoxyq @kelset:
1. Do we still need this?
2. If yes, can we rebase this on top of 0.72-stable to see if the CI stay green? (It should)

**Comment by hoxyq** [comment]
> @hoxyq @kelset:
> 
> 1. Do we still need this?
> 2. If yes, can we rebase this on top of 0.72-stable to see if the CI stay green? (It should)

1. Yes
2. Will do it today

**Comment by kelset** [comment]
headsup: no need for this PR anymore, took care of cherry-picking directly while preparing the branch for RC1: https://github.com/facebook/react-native/commits/0.72-stable

CP here: https://github.com/facebook/react-native/commit/7700d7fd78bc6fb62ded7acd267fc4a793f6d858

**Pull request closed without merging**
