### PR TITLE
Fix header elevation of NavigationExperimental

### PR DESCRIPTION
**Pull request by marcobonaldo**
Updated according to the documentation:  http://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @satya164 to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by mkonicek** [comment]
cc @hedgerwang @ericvicenti

**Comment by satya164** [comment]
I had added 4 initially, but changed it to 2 since it looked really ugly as we've a white appbar as default.

**Comment by ericvicenti** [comment]
Can you post screenshots? Is this meant to change for iOS as well, or should we make this platform-specific?

**Comment by corbt** [comment]
@ericvicenti `elevation` only applies to Android, so this is platform-specific by default. I don't think any analogous change needs to be made for iOS, because nav bars with shadows aren't as common of a design pattern there.

**Comment by facebook-github-bot-3** [comment]
@marcobonaldo updated the pull request.

**Comment by facebook-github-bot-0** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @hedgerwang as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1137899506242631/int_phab) to review.

**Pull request closed without merging**
