### PR TITLE
Change NavigationCardStack's direction props to accept a function to …

### PR DESCRIPTION
**Pull request by alvinthen**
This allow NavigationCardStack to have different navigation animation for every card in the stack instead of a universal animation.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @jmurzy to be potential reviewers.

**Comment by cmcewen** [comment]
👍  - had a similar motivation with this PR https://github.com/facebook/react-native/pull/8719 but either way would work for me

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @hedgerwang as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by joypatel04** [comment]
@brentvatne Can you please look at into it!! It might be useful !! If you have any other ideas that helpful instead of this??

**Comment by ide** [comment]
Two suggestions - rename to getDirection for clarity + preserve "direction" and add a deprecation warning for it.

**Comment by alvinthen** [comment]
I'm working on it now. One question, how do I add deprecation warning?

**Comment by ide** [comment]
Use `fbjs/lib/warning` ex: https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/Libraries/Vibration/VibrationIOS.android.js#L19

**Comment by alvinthen** [comment]
I have updated the PR with `getDirection` props and deprecation warning on `direction`.
Please review and feedback thanks

**Comment by lacker** [comment]
Why deprecate `direction` here? It seems like if both `direction` and `getDirection` were available, it would usually be better to use `direction`. How about overloading the `direction` prop be either a constant, or a function.

**Comment by ericvicenti** [comment]
@lacker is right: the normal `direction` prop would always work in this case because a render would be happening again. But that still exposes issues like this: https://github.com/facebook/react-native/issues/9433

What does everybody think about my proposed API for this here?: https://github.com/facebook/react-native/pull/8719#issuecomment-257345794

PS. It feels like a bad idea to deliberately introduce randomness into the API as it is here. It will always be nicer to have a predictable API and reasonable defaults!

**Pull request closed without merging**
