### PR TITLE
<Text> Expose Android's includeFontPadding property to JavaScript.

### PR DESCRIPTION
**Pull request by benvium**
By default Android will put extra space above text to allow for upper-case accents or other ascenders. With some fonts, this can make text look slightly misaligned when centered vertically.

We have found that the effect is very noticeable with certain custom fonts on Android. On iOS the font aligns vertically as expected.

Android exposes a property `includeFontPadding` that will remove this extra padding if set to false. This PR exposes that to JS, and adds it to the documentation and UIExplorer.

Test Plan:
- Run UIExplorer
- Scroll down to find the <Text> option
- Click and scroll to bottom to see a sample with the default text vertical alignment (includeTextPadding: true) and the result when using includeTextPadding: false.

screen shot 2016-08-09 at 17 38 05

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @skv-headless and @spicyj to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
@benvium updated the pull request.

**Comment by rigdern** [comment]
@spicyj, have you had a chance to review this yet? This feature would be useful in my team's app.

Adam Comella
Microsoft Corp.

**Comment by spicyj** [comment]
@mkonicek Can you triage?

**Comment by facebook-github-bot-5** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @rigdern as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by rigdern** [comment]
cc @mkonicek

**Comment by rigdern** [comment]
ping @mkonicek, this feature would be useful in my team's app. Can somebody review it?

**Comment by hramos** [comment]
Triaging...

**Comment by lacker** [comment]
This looks good to me. I wish there were a better way to test this sort of thing but since it's just passing through a parameter this might be overkill.

**Comment by lacker** [comment]
@benvium Can you resolve the merge conflict and then I'll ship this?

**Comment by benvium** [comment]
@lacker Yes, I can. Will do tomorrow morning UK time. Thank you.

**Comment by benvium** [comment]
@lacker I have updated the PR as requested. I re-tested using UIExplorer on API 22 and confirmed that it still works.

**Comment by lacker** [comment]
The Travis failure seems spurious, let me try rerunning it.

**Comment by benvium** [comment]
@lacker Looks like it succeeded.

**Pull request closed without merging**
