### PR TITLE
added info CLI command

### PR DESCRIPTION
**Pull request by tabrindle**
## Motivation (required)

Many issues filed on Github are missing platform/toolchain version information. Others have different ways of writing it, and require the issue writer to look in multiple places for these versions. 
Other CLI tools like Ionic have this function, and it's incredibly useful. Related to https://github.com/facebook/react-native/issues/14420 

## Test Plan (required)
Run in terminal/command prompt `react-native info`

```
trevors-imac:AwesomeProject tabrindle$ react-native info
Versions:
  React Native:  1000.0.0
  OS:  macOS Sierra
  Node:  v6.10.3
  Yarn:  0.24.5
  npm:  5.0.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
```

## Next Steps

- CLA signed ✅
- Verify functionality + implementation

### CODE REVIEW

**Comment by stoffern** [comment]
Great idea. 
Would you add a Android Studio version check + packages if possible too? 😉

**Comment by tabrindle** [comment]
Gets a bit hairy there because Android studio can be installed anywhere. Also sdkmanager and the older android manager very different. 

I'll do my best, any recommendations are welcome.

**Comment by tabrindle** [comment]
@stoffern By packages do you mean dev/Dependencies from package.json?

**Comment by stoffern** [comment]
@tabrindle yes more like `react-native` and `react` versions

**Comment by tabrindle** [comment]
Output now looks like this:

```
Versions:
  React Native:  1000.0.0
  React:  16.0.0-alpha.12
  OS:  macOS Sierra
  Node:  v6.10.3
  Yarn:  0.24.5
  npm:  5.0.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
  Android Studio:  2.3 AI-162.3934792 ```

**Comment by stoffern** [comment]
Thats all i have.  Is it tested fully and ready to be merged?

**Comment by tabrindle** [comment]
I have tested on Windows Linux and MacOS for typical install locations, mostly because of Android Studio being difficult. If nobody has any objections, I believe it is ready.

**Comment by stoffern** [comment]
Looks good to me 😉

**Comment by tabrindle** [comment]
My other PR has been updated to reflect the changes here as well - can you review that one too? It is for the issue template.
https://github.com/facebook/react-native/pull/14422

**Comment by stoffern** [comment]
@tabrindle i do not have the rights to confirm the review.
Perhaps @hramos can help out with thisone and #14422? 😉

**Comment by tabrindle** [comment]
I got tired of waiting for this PR to be looked at - I have been working on a separate module based on this work called envinfo on npm. That way, this can be used and extended in other projects. 

`npm i -g envinfo`, then `envinfo` will result in essentially the same output as above. 

If you use npx (`npm i -g npx`) you can directly invoke envinfo (or any other package) without a global install, then invoke it like this: `npx envinfo`

Bonus, this package now has the ability to specify through command line args which packages to pull from the cwd package.json, or all of them, like this: `envinfo --packages react,react-native` and it will look like this:

```
Environment:
  OS:  macOS Sierra
  Node:  v7.10.0
  Yarn:  0.24.5
  npm:  4.2.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
  Android Studio:  2.3 AI-162.3934792 
  react:  16.0.0-alpha.6
  react-native:  0.44.0
```

In an effort to start helping user+maintainers in the issues, I will start posting this.

**Comment by hramos** [comment]
Sorry for the delay in getting this looked at. As you may have noticed, I've been spending more time trying to get the number of issues down rather than working on getting PRs moving as we usually do. Providing this as a separate package seems like a better approach as this can benefit many other projects. I suppose we can pull in this as a dependency on the CLI and therefore still provide a `info` command?

**Comment by tabrindle** [comment]
No problem at all! I just wanted to be able to help get the issue count down. Once this is in, we can just close issues without the relevant debug info. 

As long as you are comfortable pulling in my separate package, and just using it for the `react-native info` command, I will modify this PR for that.

I wasn't sure if that was the direction I should go, considering how few external modules are used in the CLI. I am planning to continue developing my envinfo module, and wasn't sure the react/react-native team would allow code that wasn't reviewed first hand.

**Comment by shergin** [comment]
Omg, I think it is suuuuper useful.
I have not strong point about where it should live, but I believe it should be available as `react-native info` **without** additional hassle.

We have to merge https://github.com/facebook/react-native/pull/14422 as well!

**Comment by tabrindle** [comment]
I have updated the PR to simply wrap my envinfo module.  I have also added options through the react native cli to add additional package versions if necessary, along with examples to go with it. By default the `react-native info` command will pass react and react-native to the `envinfo --packages` command, but you can add whatever else you want. 

Output now looks like this by default:

```
Environment:
  OS:  macOS Sierra 10.12.4
  Node:  v7.10.0
  Yarn:  0.24.5
  npm:  4.2.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
  Android Studio:  2.3 AI-162.3934792 
Packages:
  react:  16.0.0-alpha.6
  react-native:  0.44
```

--help looks like this:

```
  react-native info [options]
  Get relevant version info about OS, toolchain and libraries

  Options:

    -h, --help           output usage information
    --packages [string]  Which packages from your package.json to include, in addition to the default React Native and React versions.
    --config [string]    Path to the CLI configuration file

  Example usage:

    Get standard version info: 
    react-native info

    Get standard version info & specified package versions: 
    react-native info --packages jest,eslint,babel-polyfill
```

adding additional packages looks like this:

```
Environment:
  OS:  macOS Sierra 10.12.4
  Node:  v7.10.0
  Yarn:  0.24.5
  npm:  4.2.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
  Android Studio:  2.3 AI-162.3934792 
Packages:
  react:  16.0.0-alpha.6
  react-native:  0.44
  jest:  ^20.0.4
  eslint:  ^3.19.0
  babel-polyfill:  ^6.23.0
```

@hramos Let me know if there is anything else you can think of.

**Comment by hramos** [comment]
Working on the merge failure, shouldn't be too long.

**Comment by tabrindle** [comment]
Would it help if I rebased @hramos?

**Comment by hramos** [comment]
It should by landing shortly. Don't add any more commits, please.

**Comment by tabrindle** [comment]
👍

**Pull request closed without merging**
