### PR TITLE
add NullPoint protection

### PR DESCRIPTION
**Pull request by jameshen17**
Summary: minor change

sometimes we got cssNodeToManage obj as null, it will lead to app
crash. we’d better add nullpoint protection here, if got null, just
return.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @korDen and @kmagiera to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-3** [comment]
@jameshen17 updated the pull request.

**Comment by satya164** [comment]
Can you post a sample reproducing when we get it as null?

**Comment by jameshen17** [comment]
@satya164 it seems this issue cannot be easy reproduced, I only saw once in crash log.

And I noticed that there are similar nullpoint checkers for ShadowNodeRegistry.getNode method in codes, maybe we also need it here.

**Comment by mkonicek** [comment]
We might actually want to crash? Does it make sense to simply ignore this?

**Comment by mkonicek** [comment]
We need to understand why this happens before simply ignoring it.

**Comment by jameshen17** [comment]
@mkonicek agree, I want to find out root cause as well, but it seems it's just a random issue. I met this crash only one or two times.

**Comment by facebook-github-bot-7** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @korDen as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ide** [comment]
Agreed with @mkonicek. We should fix the root cause but you're obviously free to patch your own copy of React Native if this issue is meaningfully impacting your users.

**Comment by jameshen17** [comment]
thanks @mkonicek  @ide , we can close this PR.

**Pull request closed without merging**
