### PR TITLE
Include jestSupport for npm package

### PR DESCRIPTION
**Pull request by kujohn**
https://github.com/facebook/react-native/pull/1639 was closed for unknown reason. This will help unit test with Jest without manually copying them into node_modules/react-native.

### CODE REVIEW

**Comment by ide** [comment]
What are you testing?

**Comment by kujohn** [comment]
I am unit testing the js components.

**Comment by ide** [comment]
Your own JS components or React Native's? If you are testing React Native itself, the recommended way to test it (and other npm packages, generally speaking) is to clone the repository and run the test suite. Many (most?) npm packages don't publish their test-related code to npm.

**Comment by kujohn** [comment]
We are testing against our JS components. Without `jestSupport` in the npm package, we would have to manually copy that over to run jest test in our project. The other choice would be vendoring react-native npm package internally with jestSupport included. But overall, including `jestSupport` in the npm package will speed up setting up jest for internal tests.

**Comment by ide** [comment]
Got it - thanks for the context. 

@sahrens @vjeux any objections to publishing the jest helpers to npm?

**Comment by DaleJefferson** [comment]
I've been using the jestSupport folder from react-native to enable unit testing for the last three weeks along with my development team, it works. Adding jestSupport to the npm package would be great.

**Comment by sahrens** [comment]
I don't see any reason not to :)

**Pull request closed without merging**
