### PR TITLE
add zrcaifu app to showcase

### PR DESCRIPTION
**Pull request by jxintang**
add zrcaifu app to showcase

### CODE REVIEW

**Comment by chirag04** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@jxintang could you please rebase? The file changed recently and merge breaks

**Comment by bestander** [comment]
@jxintang just a friendly reminder that we may close this PR unless you respond.
We try to keep number of open PRs within manageable limits

**Comment by chirag04** [comment]
duplicate of https://github.com/facebook/react-native/pull/6148.

**Pull request closed without merging**
