### PR TITLE
Support user-defined PlatformColors on iOS

### PR DESCRIPTION
**Pull request by oblador**
## Summary

This is a continuation of https://github.com/facebook/react-native/pull/29683. I've talked to @danilobuerger who does not intend on continue work on it and is OK with me picking up where he left. This PR is identical besides adding a test case in the RN Tester app as requested in the original PR. 

In summary it gives iOS feature parity with Android in the sense that one can use user-defined native colors, something even the docs claim is possible. It's useful as it enables accessibility features such as high contrast colors and makes implementing dark mode simple. For an example on how it can be used, see https://github.com/klarna-incubator/platform-colors

## Changelog

[iOS] [Added] - Allow PlatformColor to return user-defined named asset color

## Test Plan

Test case added to RN Tester.

### CODE REVIEW

**Comment by p-sun** [comment]
Is there an example for how custom colors can be defined similarly in Android in RN Tester?

**Comment by oblador** [comment]
@p-sun: In the linked repo there's this for example: https://github.com/klarna-incubator/platform-colors/blob/master/examples/ColorViewerApp/ios/ColorViewerApp/Images.xcassets/accent.colorset/Contents.json Is that what you're asking for?

**Comment by p-sun** [comment]
> In summary it gives iOS feature parity with Android in the sense that one can use user-defined native colors

I wondering how this similar feature works in Android and whether there's an usage example.

**Comment by oblador** [comment]
The main use case for me is supporting dark mode without having to re-implement that logic in JavaScript. Additionally it adds accessibility features such as high contrast color support.

**Comment by oblador** [comment]
The documentation for `PlatformColor` can be found here if that helps: https://reactnative.dev/docs/platformcolor

**Comment by p-sun** [comment]
Would this break if the color defined in [RCTSemanticColorsMap in RCTConvert.m](https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/React/Base/RCTConvert.m#L596) doesn't match the one defined in Apple's [UI Element Colors](https://developer.apple.com/documentation/uikit/uicolor/ui_element_colors)?

This feature this PR adds is similar to custom colors in Android, but hasn't been documented for iOS, since this custom color is neither a "UIColor Standard Colors" or "UIColor UI Element Colors", from [the React Native docs](https://reactnative.dev/docs/platformcolor).

**Comment by oblador** [comment]
If you have a custom color defined with a name conflicting with one defined in `RCTSemanticColorsMap` it would prefer the custom color. 

Re docs: yep that's fair, I'll make a PR updating the docs explicitly stating that custom colors are supported on iOS if this one lands.

**Comment by p-sun** [comment]
I edited my previous comment with a different question.  ^

**Comment by oblador** [comment]
Do you mean this one?
> Is there an example of how custom colors can be defined similarly for Android in RN Tester?

If so it doesn't seem that way aside from `textColor`, here's an [example](https://github.com/klarna-incubator/platform-colors/blob/master/examples/ColorViewerApp/android/app/src/main/res/values/colors.xml) on how that can look like. Do you want me to add an example for Android too as a part of this PR?

**Comment by p-sun** [comment]
I meant this question. 
> Would this PR cause a different color to appear if the defined in RCTSemanticColorsMap in RCTConvert.m doesn't match the one defined in Apple's UI Element Colors. i.e. Could this PR cause Apple's UI Element Colors to override the one in RCTSemanticColorsMap? 

You don't need to add an example to Android as part of this PR, unless you want too.

**Comment by oblador** [comment]
To my understanding it would only use `RCTSemanticColorsMap` if the color doesn't exist on that particular version of iOS. I can change is so that `RCTSemanticColorsMap` is preferred, but don't think that should matter as the purpose of it is providing fallbacks.

**Comment by oblador** [comment]
@p-sun: To keep this PR moving, are there any changes you want?

**Pull request closed without merging**
