### PR TITLE
Update curl reference to force IPv4

### PR DESCRIPTION
**Pull request by nicinabox**
Includes references in examples, tests, and docs.

### CODE REVIEW

**Comment by frantic** [comment]
@nicinabox can you check something for me? (I can't repro the original issue)

can you try patching [this line](https://github.com/facebook/react-native/blob/master/packager/packager.js#L216) to have something like

```javascript
return http.createServer(app).listen(options.port, '::', readyCallback)
```

and see if `curl` without `-4` works?

Thanks!

**Comment by nicinabox** [comment]
That works!

**Comment by frantic** [comment]
@spicyj has fixed this internally, should be out with the next sync. @nicinabox thanks for bringing our attention to it! :)

**Comment by nicinabox** [comment]
:+1: Thanks guys

**Pull request closed without merging**
