### PR TITLE
bump Android Gradle Plugin to 4.0.0

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

Bump Android Gradle Plugin to 4.0.1, part of Android Studio 4.0 release.

## Changelog

[Android] [Changed] - Bump Android Gradle Plugin to 4.0.1

## Test Plan

RNTester builds and runs as expected. And my app with RN 0.63 builds and runs as expected.

### CODE REVIEW

**Comment by dulmandakh** [comment]
@cpojer @hramos @mdvacca  please merge 👍

**Comment by friederbluemle** [comment]
The PR draft with an update to 4.0.0 is already open here: https://github.com/facebook/react-native/pull/29013

Can we merge #28170 with the update to `3.6.3` first please? It's been open since Feb 28, and has been rebase/updated multiple times. We should update in smaller incremental steps if possible.

**Comment by mdvacca** [comment]
CC @fkgozali

**Comment by fkgozali** [comment]
Sorry for the delay. I need to merge the Gradle upgrade to 6.6 today, then I'll merge the android tools upgrade (this one, #28170, #29013)

**Comment by friederbluemle** [comment]
Hi @fkgozali, thanks for the reply!

Just double checking, can you please confirm the order:

1. Gradle Wrapper 6.6 #29613 (Let me know if you want me to update this to `6.6.1`, released yesterday)
2. Android Gradle plugin 3.6.4 #28170
3. I'll rebase #29013 for early testing with AGP 4+, and change it from draft to open PR
4. Additional testing period before upgrading to AGP 4+ (I'd suggest at least a few weeks)

We can also close this PR (#29044), since AGP 4+ will be done in #29013

**Comment by fkgozali** [comment]
> (Let me know if you want me to update this to 6.6.1, released yesterday)

No, as previously discussed, let's not always take the latest without discussion.

Re: 3/4, why not just go straight to 4.0.1 instead of 4.0.0, then 4.0.1?

**Comment by friederbluemle** [comment]
@mdvacca @fkgozali - Do you happen to have any information on the recent history destroying force pushes on the master branch? It happened (at least) twice already today. https://github.com/facebook/react-native/issues/29779

**Comment by rickhanlonii** [comment]
The force pushes were necessary to fix the history, so the history was changed, not destroyed.

**Comment by friederbluemle** [comment]
@rickhanlonii - Thanks for the reply! Maybe "destroyed" was not the right word, sorry about that. What I meant is that history was _changed_, i.e. the commits were overridden. Just curious: What kind of fix was necessary?

**Comment by dulmandakh** [comment]
@fkgozali let's merge this PR, and go ahead

**Comment by fkgozali** [comment]
@dulmandakh - but there's already https://github.com/facebook/react-native/pull/29013 right? Shouldn't we just merge that one instead?

**Comment by dulmandakh** [comment]
I think we can settle on NDK version later on, and it might be better to move on with AGP.

**Comment by fkgozali** [comment]
> I think we can settle on NDK version later on, and it might be better to move on with AGP.

Yeah but the other PR also upgrades to 4.0.1, which one should I merge for now? cc @friederbluemle

**Pull request closed without merging**
