### PR TITLE
Fix focus engine issue with list views on Apple TV

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
**Motivation**: Fix issue where Apple TV focus engine overscrolls when a list or scroll view is set to remove clipped subviews.  See https://github.com/facebook/react-native/issues/12793 .

**Test plan**: Manual testing using modified source for UIExplorer's ListViewGridLayoutExample.

### CODE REVIEW

**Comment by shergin** [comment]
Thank you so much for pointing this out!
Therefore, I believe it should be fixed on native side because it is actually related to implementation details of very internal clipping feature.
I hope I will fix this soon.

**Comment by dlowder-salesforce** [comment]
@shergin if you would prefer a native fix, I can have a look, since this seems to only affect Apple TV.  I also realized that we probably need to make some doc changes so users know that `removeClippedSubviews` behaves differently on TV... http://facebook.github.io/react-native/docs/view.html#removeclippedsubviews

**Comment by shergin** [comment]
@dlowder-salesforce I will appreciate any help in researching this area, therefore:
 * I don't think that turning clipping off completely in some conditions is a good idea at all. It would be great if we can have more targeted and appropriate solution;
 * Even if right now it affects only tvOS (I have not tested yet), we have to support iOS as well. If not right now, but eventually iOS with attached keyboard will utilize this feature;
 * I would love to fix it with having accessibility issue (https://github.com/facebook/react-native/issues/12374) in mind, because it is essentially same (and, I have to admit, more important) problem.

**Comment by dlowder-salesforce** [comment]
@shergin yes it would be great if we could still do the clipping and not have this issue.  Maybe there's some heuristic we can put in where we don't clip subviews that are near the edge of the viewable area, so that the bottom visible subview is not the bottommost view in the hierarchy, and this focus engine scrolling problem won't be triggered.

**Comment by dlowder-salesforce** [comment]
@shergin I tested out an idea where we create a buffer zone around the visible area of the view, and don't remove subviews that touch that zone.  Setting it to 500 px seems to work well for the modified ListViewGridLayoutExample I've been testing with.  See the most recent commit in https://github.com/dlowder-salesforce/react-native/tree/tvos-listview-native-fix .

**Comment by shergin** [comment]
Yeah, I also thought about that. Probably increasing `leeway` [here](https://github.com/facebook/react-native/blob/5353d39172034d04114f8e498fc983b92a786a78/React/Views/RCTScrollView.m#L468) can help.
Therefore, personally, I am not satisfy with this solution because it is not universal and hacky. :(

**Comment by dlowder-salesforce** [comment]
@shergin It's not clear to me what else we could do, other than increasing `leeway` or something similar -- I don't see any other general way of deciding which subviews to keep.  Maybe the way to keep it non-hacky is to expose `leeway` as a view property, so that the application developer can decide how many hidden views to keep....

**Comment by dlowder-salesforce** [comment]
@shergin I did some more testing of my native fix.  It seems to work well as long as one doesn't navigate down the scrollview too fast.  However, if you use the TV remote or arrow keys to go too fast, it seems like the code to add and remove and render subviews is having trouble keeping up, and occasionally the focus engine will get confused and pop the focus back up to the top.  With removeClippedSubviews disabled, I don't seem to see any of those problems.  Based on what I'm seeing right now, I believe that disabling removeClippedSubviews is the right solution for Apple TV.

**Comment by shergin** [comment]
@dlowder-salesforce Oh, that's interesting and super important observation! Thank you!!1
As a next step I would like to investigate/reevaluate the clipping mechanism completely. I have a filling that having this in RN is not worth it at all. If it is the case, we probably have to remove it completely. If my tests show promising results, I will share them with the community, and it can end up with removing this feature completely.

But, again, right now, it is just a feeling, no real proof. Give me some time.

**Comment by dlowder-salesforce** [comment]
Ok sounds good... since there is a workaround for the issue on Apple TV, I'll close this and wait for you to complete your work.

**Pull request closed without merging**
