### PR TITLE
Add the android gitignore to sample app

### PR DESCRIPTION
**Pull request by jhen0409**

### CODE REVIEW

**Comment by satya164** [comment]
Won't it be ideal to ignore the whole editor specific `.idea` folder rather than ignoring certain files/subdirectories?

**Comment by jhen0409** [comment]
@satya164
If `.git` appears in the main path, I would use Android Studio to import main path, so `.idea` will appear in the main path.

**Comment by jhen0409** [comment]
@satya164
If .git appears in the main path, I would use Android Studio to import main path, so .idea will appear in the main path.

**Comment by jhen0409** [comment]
@mkonicek 
Are there any problems? Or do I just need to change the `_gitignore`?

**Comment by chirag04** [comment]
@mkonicek @jhen0409 can you ignore this in cli template also?

agreed with @satya164  we can ignore the entire ``.idea`` folder.

**Comment by jhen0409** [comment]
I agreed ignore the entire `.idea` folder also.
If no problem, then I will send the new PR to modify `local-cli/generator/templates/_gitignore`.

**Pull request closed without merging**
