### PR TITLE
Fixes Fetch error when debugging in Chrome

### PR DESCRIPTION
**Pull request by bestander**
Fixes https://github.com/facebook/react-native/issues/6679

Test Plan:
- reproduce #6679 locally

BTW, why don't we use fetch via node_modules instead of copy/pasting code?

### CODE REVIEW

**Comment by bestander** [comment]
cc @davidaurelio

**Comment by davidaurelio** [comment]
An excellent change! Cheers to you, my friend!

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1589694211328835/int_phab) to review.

**Pull request closed without merging**
