### PR TITLE
Update _scrollAnimatedValue offset of ScrollViews.

### PR DESCRIPTION
**Pull request by miyabi**
# Motivation

`_scrollAnimatedValue` offset of ScrollView is set once in `UNSAFE_componentWillMount` but it is never updated.
It causes unexpected render result.

rn-scrollview-fix1

So I suggest to update `_scrollAnimatedValue` offset when ScrollView contentInset is updated.

# Test Plan

Here is a demo and an example code:

rn-scrollview-fix2

```jsx
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  SectionList,
  Dimensions,
} from 'react-native';

export default class RNScrollExample extends Component {
  state = { navigationBarHeight: 88 };
  onChangeDimensions = this.onChangeDimensions.bind(this);

  componentDidMount() {
    Dimensions.addEventListener('change', this.onChangeDimensions);
  }

  componentWillUnmount() {
    Dimensions.removeEventListener('change', this.onChangeDimensions);
  }

  onChangeDimensions({ window, screen }) {
    if (window.width > window.height) {
      this.setState({ navigationBarHeight: 44 });
    } else {
      this.setState({ navigationBarHeight: 88 });
    }
  }

  renderSectionHeader(title) {
    return (
      <View style={styles.sectionHeader}>
        <Text>{title}</Text>
      </View>
    );
  }

  renderItem(content) {
    return (
      <View style={styles.cell}>
        <Text>{`Item ${content}`}</Text>
      </View>
    );
  }

  renderSeparator() {
    return <View style={styles.separator} />;
  }

  renderSectionList() {
    const sections = Array.from(Array(10), (e, i) => ({ title: `Section ${i+1}`, data: Array.from(Array(10)).map((e, i) => i+1) }));
    const { navigationBarHeight } = this.state;
    return (
      <SectionList
        automaticallyAdjustContentInsets={false}
        contentInset={{ top: navigationBarHeight }}
        contentOffset={{ y: -navigationBarHeight }}
        sections={sections}
        keyExtractor={(item, index) => index}
        renderSectionHeader={({ section }) => this.renderSectionHeader(section.title)}
        renderItem={({ item }) => this.renderItem(item)}
        ItemSeparatorComponent={this.renderSeparator}
      />
    );
  }

  renderHeader() {
    return (
      <View style={[styles.header, { height: this.state.navigationBarHeight }]}>
        <Text style={styles.headerText}>Contents</Text>
      </View>
    );
  }

  render() {
    return (
      <View>
        {this.renderSectionList()}
        {this.renderHeader()}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: '#ffffffcc',
  },
  headerText: {
    fontSize: 16,
    lineHeight: 44,
    fontWeight: 'bold',
  },
  sectionHeader: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#05bbd3',
  },
  cell: {
    paddingHorizontal: 8,
    paddingVertical: 16,
    backgroundColor: '#82dde9',
  },
  separator: {
    height: 1,
    backgroundColor: '#7d888d',
  },
});

AppRegistry.registerComponent('RNScrollExample', () => RNScrollExample);
```

# Release Notes

[IOS][BUGFIX][ScrollView] Fix that _scrollAnimatedValue offset is not updated even contentInset is updated.

### CODE REVIEW

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :clipboard: Release Notes - <i>This PR appears to be missing Release Notes.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by miyabi** [comment]
I added Release Notes.

**Comment by miyabi** [comment]
@shergin Could you review this PR?

**Comment by cpojer** [comment]
Thanks for this PR! Sorry that it took so long to get back to you.

In order to merge it, please fix the flow error. Also, can you make it so the method is only invoked if the inset changed between props? Thank you!

**Comment by miyabi** [comment]
@cpojer Thank you for reviewing. I fixed error and updated my code.

**Comment by cpojer** [comment]
Thank you! I don't think it's a good idea to create up to two empty objects every time the props change. Could you change your code to be a bit more verbose but doesn't create empty objects?

**Comment by miyabi** [comment]
@cpojer I improved my code. Thanks!

**Pull request closed without merging**
