### PR TITLE
[Typo] Update "integration-with-existing-apps.html"

### PR DESCRIPTION
**Pull request by faceach**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

Typo issue fix.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@faceach Please sign the CLA and please target `master` instead of a release branch as stated in the pull request template

> Unless you are a React Native release maintainer and cherry-picking an existing commit into a current release, ensure your pull request is targeting the master React Native branch.

Thank you!!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by JoelMarcey** [comment]
@faceach Thanks for signing the CLA. Now you just have to target the `master` branch.

**Comment by lacker** [comment]
Somehow this branch seems totally wacked and github got confused. One of the typos already got fixed in master, the other one is 1 char so I just pulled it out into https://github.com/facebook/react-native/pull/10529 . I'm going to close this PR, let's just typo-fix in the other branch. Thanks for pointing this out and showing how to fix it!

**Pull request closed without merging**
