### PR TITLE
add show case

### PR DESCRIPTION
**Pull request by xujinyang**
add showcase for crowdsource

"Fengniao Crowdsource app" is a mobile app, developed by Eleme, Inc, for Fengniao Crowdsource, the largest crowdsourced logistics platform in China.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @RetroPoktan to be potential reviewers.

**Comment by lacker** [comment]
Is there any English-language news coverage or technical content for this app?

**Comment by xujinyang** [comment]
ok please wait！

**Comment by xujinyang** [comment]
now l udpate the infoLink in showcase.js. thanks for all

**Comment by hramos** [comment]
@xujinyang hi there, we've recently changed the way the showcase works. In order to add an app to the showcase, it must meet the following requirements:

1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical blog post by the app creators specifically discussing React Native

As it happens, this app does not currently meet these requirements.

**Pull request closed without merging**
