### PR TITLE
set state to LOADING on reload()

### PR DESCRIPTION
**Pull request by stereodenis**
https://github.com/facebook/react-native/issues/8239

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @janicduplessis to be potential reviewers.

**Comment by charpeni** [comment]
Did it work?

**Comment by stereodenis** [comment]
@charpeni yes!

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1719115258361566/int_phab) to review.

**Comment by facebook-github-bot-0** [comment]
Something went wrong when importing this pull request. Please cc someone from the team at fb to help with importing this.

**Comment by charpeni** [comment]
cc @javache @bestander Import failed.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1719115258361566/int_phab) to review.

**Pull request closed without merging**
