### PR TITLE
Updated TextInput autoCompleteType prop to autoComplete

### PR DESCRIPTION
**Pull request by jeswinsimon**
## Summary

Fix for bug #26003 Rename TextInput prop "autoCompleteType" to "autoComplete". Abandoning previous PR due to branch issues

## Changelog

[Android] [Changed] - Updated `autoCompleteType` prop of `TextInput` to `autoComplete`

## Test Plan

Test Pass

PR for [Doc Update](https://github.com/facebook/react-native-website/pull/1184)

### CODE REVIEW

**Comment by necolas** [comment]
As per #26003, I think this prop should have been called `autoComplete`

**Review by lunaleaps — CHANGES_REQUESTED** [review]
@jeswinsimon Do you want to rebase these changes?

**Comment by jeswinsimon** [comment]
@lunaleaps I have completed the rebase. There is a PR https://github.com/facebook/react-native-website/pull/1184 to update the docs here.

**Comment by lunaleaps** [comment]
As an FYI, I'll be splitting these changes around to work with our release cycle!

**Pull request closed without merging**
