### PR TITLE
Update NavigatorIOS.ios.js

### PR DESCRIPTION
**Pull request by stereodenis**

### CODE REVIEW

**Comment by mkonicek** [comment]
Does `onBack` need to be bound as well?

**Comment by stereodenis** [comment]
@mkonicek there is no `_onBack` in the example

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @hramos to be potential reviewers.

**Comment by hramos** [comment]
@stereodenis can you elaborate on the purpose for this PR? Why is the constructor being removed?

**Comment by stereodenis** [comment]
@hramos cause there is no need for it

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by stereodenis** [comment]
:tada:

**Comment by stereodenis** [comment]
🎉

**Pull request closed without merging**
