### PR TITLE
add ScrollResponder#scrollResponderZoomTo animated second argument

### PR DESCRIPTION
**Pull request by gre**
ScrollResponder was missing a non animated version for zoomToRect.

- scrollResponderScrollTo <> scrollResponderScrollWithoutAnimationTo
- ~~scrollResponderZoomTo <> :new: **scrollResponderZoomWithoutAnimationTo**~~
- `scrollResponderZoomTo(rect, animated = true)`

### CODE REVIEW

**Comment by nicklockwood** [comment]
Why not just add an `animated` argument to the existing zoomTo function, and have it default to `true` if undefined?

**Comment by nicklockwood** [comment]
Oh, I see - you're following the existing convention. That's reasonable. I think the existing convention is bad though :-/

Can you switch to using an `animated` param as I suggested, and I'll change the other method to work the same way, and deprecate the `scrollToWithoutAnimation` method.

**Comment by gre** [comment]
ok I will do, and I guess i need to default it to `true` to make it backwards compatible

**Comment by nicklockwood** [comment]
@gre, yeah, so something like this:

    scrollResponderZoomTo: function(
      rect: { x: number; y: number; width: number; height: number; },
      animated?: boolean
    ) {
      if (Platform.OS === 'android') {
        invariant('zoomToRect is not implemented');
      } else {
        ScrollViewManager.zoomToRect(
          React.findNodeHandle(this),
          rect, animated === undefined ? true : animated
        );
      }
     },

**Comment by gre** [comment]
@nicklockwood why not using the ES6 default ? I've committed my change.

Aso weird thing on this feature, on my advanced use-case the disabling of animation only works if user have already zoom the scrollview. I have no idea why, any idea? I've logged things and zoomToRect do get called with animated:NO so i'm not sure we can do anything about it. (maybe it's another bug with something I use)

**Comment by nicklockwood** [comment]
@gre

>why not using the ES6 default

Because I'm a JS n00b :-) Is the ? after `animated` still needed in that case though?

>Aso weird thing on this feature, on my advanced use-case the disabling of animation only works if user have already zoom the scrollview

I've no idea. Could you add an example to UIExplorer that demos the problem? Then I can investigate.

**Comment by gre** [comment]
about the `?` I have not sure, AFAIK it's only for flow to know the parameter is optional (but can flow infer this from the default, that's the question, i'm not sure if flow is aware of the ES6 stuff actually, maybe it only happens after the babel transpilation?).

for the weird animated, it's tricky actually, it works in most cases. I'm not sure if it will repro on UIExplorer but I'll test it. (but probably not before tonight)

Thanks

**Comment by nicklockwood** [comment]
@gre - cool, I'll ship the feature now then. If you get a chance to produce a test case for the bug later then please create another PR. Thanks!

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by gre** [comment]
@nicklockwood awesome! thanks!

**Comment by gre** [comment]
@nicklockwood actually, I think I just had a cache issue, I was still using the old version that always animates. I'll let you know if this actually happens and if I can repro it

**Comment by nicklockwood** [comment]
Sorry this took so long to land - we had some weird issues with our internal CI.

**Pull request closed without merging**
