### PR TITLE
Android ci stability

### PR DESCRIPTION
**Pull request by bestander**
Something broke Circle CI tests in many places.
Can't repro locally.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @mhorowitz and @cjhopman to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
@bestander updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10135/files/14a4fff94daae51bd1b718a0bf38c9113ba0d0d0..aee977d84837eebaa9bbaaa8fe41475cd93705a5)

**Comment by facebook-github-bot-1** [comment]
@bestander updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10135/files/aee977d84837eebaa9bbaaa8fe41475cd93705a5..467e5c21dba2abaaed7bbbd38d14e1d23761972c)

**Comment by facebook-github-bot-5** [comment]
@bestander updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10135/files/467e5c21dba2abaaed7bbbd38d14e1d23761972c..f485f3285603c515603527a5aef47a6763435f75)

**Comment by bestander** [comment]
closing, fix is coming from fb code

**Pull request closed without merging**
