### PR TITLE
Call init with --verbose in the first example.

### PR DESCRIPTION
**Pull request by edthedev**
init can take a very long time on the first use and gives no output until it finishes.

Simply calling it with --verbose lets the user know that it is working, and that they should be patient.

After being confused myself by this command apparently hanging; I found three separate opened and closed GitHub issues, each with dozens of comments by new users similarly confused. 

Getting to go Google for a solution is not a great introduction to the framework, and I think we can avoid it easily here by including the verbose flag the first time we suggest the command.

I have prepared, and will submit separately, a pull request that outputs a 'This may take a long time' warning, when 'init' is called without the --verbose flag. I realize there may be other reasons to reject that change, which is fine. I think this is the more important change, of the two. (Although we should keep in mind that not everyone finds this Getting Started guide.)

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @lacker to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by JoelMarcey** [comment]
@edthedev Hi. Please have this pull request target `master` instead of a release branch per the `CONTRIBUTING.md` guidelines. Thank you.

**Comment by hramos** [comment]
FYI @edthedev, you can now change the base branch without opening a new PR: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by lacker** [comment]
I'd like to hear @mkonicek chime in on whether this is the right thing to do - Joel and I are more for the docs side of things. E.g. if this is the right advice maybe we should alter how the CLI works.

**Comment by edthedev** [comment]
I changed this to target master and it looks like it got messy.
(FYI it seems that web GitHub doc edits target stable, surprisingly.)

 It won't hurt my feeling if someone wants to just close this and steal my brilliant change.

**Comment by JoelMarcey** [comment]
I think we still want to hear from @mkonicek or @bestander whether having `--verbose` is actually what we want. If so, we can add it for you :)

**Comment by bestander** [comment]
Yeah, something did go bad with the PR rebase :)
Looking at the first commit, I would not recommend using `--verbose` by default.
Afaik it gets a bit slower because of the amount of output even though it fixes the illusion that CLI hangs.

On the bright side we are working on a faster and leaner solution to install node_modules for React Native and a revamp of the CLI tool.
So let's just wait till September-October when this gets fixed for good rather than patch it with verbose logs.

**Pull request closed without merging**
