### PR TITLE
Remove left over code from deprecating Android < 21

### PR DESCRIPTION
**Pull request by safaiyeh**
## Summary
Came to learn RN is deprecating Android 19, 20: https://github.com/facebook/react-native/commit/a17ff44adcf003dd4e4ef2301e1f80b77913f712

Did a quick check of left over code from the deprecation.

## Changelog

[Android] [Deprecated] - Cleanup usages of deprecated Android API

### CODE REVIEW

**Comment by safaiyeh** [comment]
cc @JoshuaGross if you could check this out

**Comment by safaiyeh** [comment]
@fkgozali

**Comment by JoshuaGross** [comment]
Cool! Thanks for doing this!

**Review by dulmandakh — APPROVED** [review]
LGTM

**Pull request closed without merging**
