### PR TITLE
iOS: Fix refreshControl layouting

### PR DESCRIPTION
**Pull request by yogevbd**
## Summary

In `react-native-navigation` we allow the usage of native iOS navigationBar **largeTitle** which cause the title to "jump" when pulling to refresh.
We found that the layout calculations of the refreshControl element mess up the system behaviour.

## Changelog

[iOS] [Fixed] - Fix refreshControl messes up navigationBar largeTitles

### Before the fix:
before

### And after:
after

### How it looks like with react-native init app after the fix:
ezgif com-video-to-gif (4)

### CODE REVIEW

**Comment by maxencehenneron** [comment]
Thanks you for the PR. However, it seems that the refreshControl property is only available on iOS 10+.

see: https://developer.apple.com/documentation/uikit/uiscrollview/2127691-refreshcontrol

can you wrap the assignation in an @available condition? Also, maybe keep the current code in older versions for retro compatibility?

**Comment by shergin** [comment]
I think we dropped support for iOS 9 in January, so that should be possible to land. I will be oncall next week, so I will try to land it today.

**Comment by yogevbd** [comment]
@shergin The build should pass now. Can you please review? Thanks!

**Comment by guyca** [comment]
Only the windows tests suite fails. I'm assuming it's flaky since this PR was rebased yesterday and other builds are passing. Could someone please trigger the failing tests suite? 🙏 @shergin

**Comment by guyca** [comment]
@shergin Tests are green! 💚

**Comment by shergin** [comment]
This PR broke a bunch of internal stuff, so until I fix that I have to revert the PR. :(
I will investigate that later this week.

**Comment by guyca** [comment]
@shergin Anything we (react-native-navigation maintainers) can do to help here? 🙇

**Comment by simonmitchell** [comment]
This also crashes in `beginRefreshingProgramatically` because the `RCTRefreshControl`'s `superView` is force-casted to `UIScrollView`... I'm looking into this for a patch we're going to apply in one of our projects!

**Comment by PeteTheHeat** [comment]
Some more context about shergin's comment. 

The reason this PR broke things internally is because FB has a custom refresh control that is a `UIView`, not a `UIRefreshControl`. `RCTScrollView` crashes when trying to set a refreshControl with a UIView. 

Question:
- Is that change vital to fixing the layout bug? Are we only able to delete the custom layout code in this PR because of the switch to use a `UIRefreshControl`?

**Comment by yogevbd** [comment]
Hi @PeteTheHeat. Yes it is vital for fixing the layout in order to support the native navigationBar large titles. I have a better fix which will not break in cases where the refreshControl is a `UIView`, I am checking whether the `refreshControl` property is a subclass of `UIRefreshControl` and only then I am setting it to the scrollView refreshControl property. It's already updated in my fork.
Can you please reopen this PR? 🙏

**Comment by simonmitchell** [comment]
@yogevbd @PeteTheHeat these changes won't be enough unfortunately, let me upload our patch file here! If you manually change the refreshing state of the `UIRefreshControl` with this it will crash because the Obj-C code force-casts the `UIRefreshControl`'s `superView` to `UIScrollView` which is no longer the case!


[react-native+0.61.5.patch.txt](https://github.com/facebook/react-native/files/4818238/react-native%2B0.61.5.patch.txt)

**Comment by yogevbd** [comment]
@simonmitchell what do you mean by manually changing the `UIRefreshControl` state?
I applied your patch and added my changes on top of it and couldn't find anything unusual, can you explain how to reproduce this crash?
I also invited you to edit this fork in case you want to suggest changes. It will be great 🙏

**Comment by simonmitchell** [comment]
@yogevbd I basically made the same changes as you but where we were using the refresh control in a "controlled" manner:

```
<ScrollView
  contentInsetAdjustmentBehavior={'always'}
  onScroll={disablePristine}
  refreshControl={<RefreshControl refreshing={refreshing} onRefresh={this.onRefresh} />}
>
```

It was crashing on this line: https://github.com/yogevbd/react-native/blob/fa6375a9547b834e015225783a462c9ffb7e3954/React/Views/RefreshControl/RCTRefreshControl.m#L60 because of the way the refresh control's superview is cast to `UIScrollView` ☺️

**Comment by yogevbd** [comment]
@simonmitchell still couldn't reproduce on react-native@0.62.2  :(
Can you please send the crash log?

**Comment by simonmitchell** [comment]
@yogevbd sorry for the delay! I haven't been able to repro the issue in RNTester app this morning as suggested by @guyca... I can however still repro it in our own app which is using RNN (I wonder if that's where the issue stems from?) It seems to occur when the refresh happens whilst another screen is pushed on the navigation stack. It doesn't crash natively so I can't pass through a system crash log, but here's the stack trace:

```
Thread 1 Queue : com.apple.main-thread (serial)
Thread 1: Exception: "-[UIView contentOffset]: unrecognized selector sent to instance 0x7fe661b00f00"

#0	0x000000010b166705 in objc_exception_throw ()
#1	0x000000010c090fa4 in -[NSObject(NSObject) doesNotRecognizeSelector:] ()
#2	0x0000000115fb9163 in -[UIResponder doesNotRecognizeSelector:] ()
#3	0x000000010c076fb6 in ___forwarding___ ()
#4	0x000000010c078e88 in __forwarding_prep_0___ ()
#5	0x000000010294b019 in -[RCTRefreshControl beginRefreshingProgrammatically] at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTRefreshControl.m:54
#6	0x000000010294ba3e in -[RCTRefreshControl setRefreshing:] at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTRefreshControl.m:133
#7	0x0000000102882e26 in __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_14 at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTComponentData.m:294
#8	0x0000000102883890 in __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.98 at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTComponentData.m:314
#9	0x0000000102883ec8 in __49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2 at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTComponentData.m:334
#10	0x00000001028fe119 in RCTPerformBlockWithLogFunction at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Base/RCTLog.mm:110
#11	0x00000001028fe2cf in RCTPerformBlockWithLogPrefix at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Base/RCTLog.mm:118
#12	0x0000000102883e21 in __49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTComponentData.m:333
#13	0x00000001028840ad in __37-[RCTComponentData setProps:forView:]_block_invoke at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTComponentData.m:350
#14	0x000000010c0e53a2 in -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] ()
#15	0x0000000102883fb8 in -[RCTComponentData setProps:forView:] at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Views/RCTComponentData.m:349
#16	0x00000001029907a0 in __42-[RCTUIManager updateView:viewName:props:]_block_invoke at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Modules/RCTUIManager.m:1011
#17	0x0000000102992809 in __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Modules/RCTUIManager.m:1162
#18	0x0000000102992b63 in __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.485 at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Modules/RCTUIManager.m:1183
#19	0x000000010299bcb0 in __RCTExecuteOnMainQueue_block_invoke at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Base/RCTUtils.m:257
#20	0x000000010e9805d1 in _dispatch_call_block_and_release ()
#21	0x000000010e98163e in _dispatch_client_callout ()
#22	0x000000010e98e9d6 in _dispatch_main_queue_callback_4CF ()
#23	0x000000010bfd57f9 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#24	0x000000010bfcfe86 in __CFRunLoopRun ()
#25	0x000000010bfcf221 in CFRunLoopRunSpecific ()
#26	0x000000011268a1dd in GSEventRunModal ()
#27	0x0000000115bd2115 in UIApplicationMain ()
#28	0x00000001024ec560 in main at /Users/simonmitchell/Coding/forest-watcher-mobile-client/ios/ForestWatcher/main.m:16
#29	0x000000010e9f7551 in start ()
#30	0x000000010e9f7551 in start ()
Enqueued from com.facebook.react.ShadowQueue (Thread 49) Queue : com.facebook.react.ShadowQueue (serial)
#0	0x000000010e985c17 in dispatch_async ()
#1	0x000000010299bc52 in RCTExecuteOnMainQueue at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Base/RCTUtils.m:256
#2	0x0000000102992580 in -[RCTUIManager flushUIBlocksWithCompletion:] at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Modules/RCTUIManager.m:1177
#3	0x00000001029920e9 in -[RCTUIManager _layoutAndMount] at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Modules/RCTUIManager.m:1135
#4	0x0000000102991d54 in -[RCTUIManager batchDidComplete] at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/Modules/RCTUIManager.m:1111
#5	0x00000001028a6657 in __32-[RCTCxxBridge batchDidComplete]_block_invoke at /Users/simonmitchell/Coding/forest-watcher-mobile-client/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:1372
#6	0x000000010e9805d1 in _dispatch_call_block_and_release ()
#7	0x000000010e98163e in _dispatch_client_callout ()
#8	0x000000010e988b47 in _dispatch_lane_serial_drain ()
#9	0x000000010e9897c0 in _dispatch_lane_invoke ()
#10	0x000000010e9938b8 in _dispatch_workloop_worker_thread ()
#11	0x000000010ed79a3d in _pthread_wqthread ()
#12	0x000000010ed78b77 in start_wqthread ()
```

It seems to happen maybe when we've pull-to-refreshed once and then the refresh happens again with the user on another screen but I haven't worked out how to repro it 100% of the time yet. It's the only `RefreshControl` instance we have in the app and is super-simple:

```
<ScrollView
  contentInsetAdjustmentBehavior={'always'}
  onScroll={disablePristine}
  refreshControl={<RefreshControl refreshing={refreshing} onRefresh={this.onRefresh} />}
>
```

`refreshing` is calculated from redux-state.

**Comment by simonmitchell** [comment]
Note line numbers are slightly different, I couldn't get the app running pointing at RN 0.62.0 and more specifically pointing at your branch, but the changes I have made locally are identical to the ones you've made above ☺️

If you're happy for me to, I can create a PR to your fork with the fixes I had to make via a patch file in our project which resolve this? That way we don't have to find a way for you to reproduce this?

**Comment by yogevbd** [comment]
@simonmitchell sure thing! submitting a PR to my fork would be great! thanks

**Comment by simonmitchell** [comment]
Will set myself a reminder to do that first thing tomorrow @yogevbd :D

**Comment by simonmitchell** [comment]
@yogevbd sorry for the additional delay, yesterday ended up being incredibly busy! PR now submitted: https://github.com/yogevbd/react-native/pull/1

**Comment by guyca** [comment]
LGTM! 🔥

**Comment by yogevbd** [comment]
@shergin @PeteTheHeat Can you guys please try to merge it again?

**Comment by simonmitchell** [comment]
Whoop whoop! Great work guys, excited to see this merged as it's now patched in two of our projects 😝

**Comment by Evan-Younan** [comment]
Thanks a lot for this fix! Looking forward to seeing this merged soon.

**Comment by chrise86** [comment]
Has this made it into a release yet?

**Comment by chrise86** [comment]
@simonmitchell @yogevbd tried this out using a patch, and the refresh indicator works great now. I have noticed a couple odd jumps on load sometimes, where the title appears small to start and the content appears under the navbar, but generally much better. However it looks like this has broken `stickyHeaderIndices`, or at least the content inset calculation for it. Content now hides under the navbar when scrolled.

**Comment by guyca** [comment]
@chrise86 
Since it's a bit difficult to reproduce edge cases reported in issues - would you be able to push a minimal reproducible example?

**Comment by julian-baumann** [comment]
What is the current status on this?

Btw @yogevbd how did you manage to apply a transparent background to a large title only with react native navigation? And also remove the border.

**Comment by yogevbd** [comment]
@julian-baumann  These options should do with react-native-navigation:
```js
{
  topBar: {
    background: {
      color: 'transparent',
      noBorder: true
    }
  }
}
```

**Comment by julian-baumann** [comment]
Thanks, but that did not work. Already tried that. It only results in a completely transparent header. But I only want the background of the large title transparent. The default collapsed header should be translucent/white.


Didn't you make this view with React-Native-Navigation?

**Comment by brmk** [comment]
What is the plan for releasing this? It looks abandoned, doesn't it?

**Comment by habovh** [comment]
Well according to this commit details 1b0fb9bead4d158d14df5a994423d06716b5e377 it looks like this fix will be part of React Native 0.64 (currently in RC1).

**Comment by pouyarezvani** [comment]
Was this fix released? because I'm still having this issue with the large header and FlatList RefreshControl. 
If not I will need to Patch-Package it?

**Comment by dandre-hound** [comment]
@yogevbd we are discussing in #31461 how this PR introduces an undesirable visual jump when pulling to refresh on RN list components (scrollview, flatlist, and sectionlist). We are able to reproduce the visual jump on fresh react-native projects with and without navigation headers. After reverting this PR, pulling to refresh is smooth as expected. Do you have any pointers as to why this may be happening, especially since we're able to reproduce without navigation headers? We're really surprised more people haven't mentioned #31461 since it's easily reproducible and it's a very obvious UI issue.

Do you think we're safe to rollback this commit locally if we don't use large navigation headers? Or does this PR fix multiple issues with pulling to refresh? If this PR is only intended to fixe this one issue with pull to refresh on large header titles, we may roll this back locally. Thanks.

**Comment by yogevbd** [comment]
@dandre-hound it is safe to rollback this commit if you don't use navigation large headers. Will work on a fix asap.

**Comment by dandre-hound** [comment]
Sounds great @yogevbd -- we are happy to help test. Thank you for offering to look into this!

**Comment by tj-mc** [comment]
Is anybody working on a fix for the bug introduced by this PR? 
We still face this issue, and are anxious to revert a many-years-old patch 🤔

**Pull request closed without merging**
