### PR TITLE
Added the append method in custom Navigator

### PR DESCRIPTION
**Pull request by regeda**
Hi, All!

I use ```Navigator``` with ```Navigator.SceneConfigs.HorizontalSwipeJump``` scene config. My user should jump to the next route with auto forward (```push```) or sometimes I need to append the next route without transition. In that case, a user must swipe manually to the next scene. So, I've added a new method called ```append```.

### CODE REVIEW

**Comment by satya164** [comment]
@ericvicenti is working on a new implementation of the Navigator. Please checkout https://github.com/ericvicenti/navigation-rfc and post your comments there.

**Comment by regeda** [comment]
@satya164, OK!
But what will happen with the current navigator? Is it real to merge my pull request? I think ```append``` feature is very useful.

**Comment by satya164** [comment]
@regeda I think it'll be easier to support these kinds of use cases in new navigator rather than chaging the current navigator, which have a very not-flexible API. I dunno what will happen to the current navigator. I guess it'll just stop being maintained and eventually deprecated.

In any case, it'll be awesome if you could open an issue in the repo I linked and discuss your use case.

**Comment by mkonicek** [comment]
> I think it'll be easier to support these kinds of use cases in new navigator rather than chaging the current navigator, which have a very not-flexible API. I dunno what will happen to the current navigator. I guess it'll just stop being maintained and eventually deprecated.

That is indeed the case, all the development should happen in NavigationExperimental.

I'll close this one, sorry about the churn and hope you'll continue contributing to React Native!

**Pull request closed without merging**
