### PR TITLE
In order to fit the Android platform, join onRequestClose attributes in the Model module

### PR DESCRIPTION
**Pull request by jiangqqlmj**
In order to fit the Android platform, join onRequestClose attributes in the Model module

### CODE REVIEW

**Comment by litingjun2015** [comment]
Hi,

I have similar issue:

```
W/ReactNativeJS(23893): Warning: Failed prop type: Required prop `onRequestClose` was not specified in `Modal`.
W/ReactNativeJS(23893):     in Modal (created by BizQRCode)
W/ReactNativeJS(23893):     in BizQRCode (created by HomeIndex)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by AnimatedComponent)
W/ReactNativeJS(23893):     in AnimatedComponent (created by Styled(AnimatedComponent))
W/ReactNativeJS(23893):     in Styled(AnimatedComponent) (created by HomeIndex)
W/ReactNativeJS(23893):     in HomeIndex (created by Connect(HomeIndex))
W/ReactNativeJS(23893):     in Connect(HomeIndex) (created by DefaultRenderer)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by DefaultRenderer)
W/ReactNativeJS(23893):     in DefaultRenderer (created by SceneView)
W/ReactNativeJS(23893):     in SceneView (created by NavigationCard)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by AnimatedComponent)
W/ReactNativeJS(23893):     in AnimatedComponent (created by NavigationCard)
W/ReactNativeJS(23893):     in NavigationCard (created by Container)
W/ReactNativeJS(23893):     in Container (created by NavigationComponent)
W/ReactNativeJS(23893):     in NavigationComponent (created by NavigationAnimatedView)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by NavigationAnimatedView)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by NavigationAnimatedView)
W/ReactNativeJS(23893):     in NavigationAnimatedView (created by NavigationComponent)
W/ReactNativeJS(23893):     in NavigationComponent (created by DefaultRenderer)
W/ReactNativeJS(23893):     in DefaultRenderer (created by TabbedView)
W/ReactNativeJS(23893):     in StaticContainer (created by TabbedView)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by TabbedView)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by TabbedView)
W/ReactNativeJS(23893):     in TabbedView (created by TabBar)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by TabBar)
W/ReactNativeJS(23893):     in TabBar (created by DefaultRenderer)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by DefaultRenderer)
W/ReactNativeJS(23893):     in DefaultRenderer (created by SceneView)
W/ReactNativeJS(23893):     in SceneView (created by NavigationCard)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by AnimatedComponent)
W/ReactNativeJS(23893):     in AnimatedComponent (created by NavigationCard)
W/ReactNativeJS(23893):     in NavigationCard (created by Container)
W/ReactNativeJS(23893):     in Container (created by NavigationComponent)
W/ReactNativeJS(23893):     in NavigationComponent (created by NavigationAnimatedView)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by NavigationAnimatedView)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by NavigationAnimatedView)
W/ReactNativeJS(23893):     in NavigationAnimatedView (created by NavigationComponent)
W/ReactNativeJS(23893):     in NavigationComponent (created by DefaultRenderer)
W/ReactNativeJS(23893):     in DefaultRenderer (created by NavigationRootContainer)
W/ReactNativeJS(23893):     in NavigationRootContainer (created by Router)
W/ReactNativeJS(23893):     in Router (created by AppRouter)
W/ReactNativeJS(23893):     in AppRouter (created by App)
W/ReactNativeJS(23893):     in Provider (created by App)
W/ReactNativeJS(23893):     in App
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by AppContainer)
W/ReactNativeJS(23893):     in RCTView (created by View)
W/ReactNativeJS(23893):     in View (created by AppContainer)
W/ReactNativeJS(23893):     in AppContainer
```

I think it's the same reason?

**Comment by hramos** [comment]
@jiangqqlmj can you address the lint warnings issued above?

**Comment by jiangqqlmj** [comment]
@hramos   I try

**Comment by lacker** [comment]
It looks like this pull request has been abandoned so I'm going to close it. Please feel free to reopen it if you want to keep working on it!

**Pull request closed without merging**
