### PR TITLE
Fix Android 4.1-4.3 WebView source baseUrl bug

### PR DESCRIPTION
**Pull request by Etheryte**
## Motivation
Resolves https://github.com/facebook/react-native/issues/11753 and https://github.com/facebook/react-native/issues/9835.  

## Description
Android versions 4.1-4.3 don't understand the MIME type `text/html; charset=utf-8` and default to `text/plain` instead, rendering the content as an unparsed HTML string. Since the encoding is already set and passed separately, removing it from the MIME type has no negative effects.

The same fix has already been discussed, successfully tested and incorporated in https://github.com/NativeScript/NativeScript/issues/1038.

### CODE REVIEW

**Comment by Exilz** [comment]
Can someone review this PR so we can see it merged in the near future ? We had to make the exact same change on react-native, this is a quite critical bug for us.

**Comment by stereodenis** [comment]
@mkonicek how to help you get it merged?

**Comment by chung2014** [comment]
will this fix merge to master?

**Comment by vikkalen** [comment]
the scope of the property HTML_MIME_TYPE has recently changed from "private" to "protected". See commit e2c87b5. You should probably fix your pull request.

**Comment by Etheryte** [comment]
@facebook-github-bot This pull request is still relevant, I've merged master into the branch. I don't know who to highlight with this request.

**Comment by chirag04** [comment]
cc @shergin

**Comment by shergin** [comment]
I can merge this on Monday.

**Comment by Crash--** [comment]
+1 to merge this PR. ATM, we've to override the setSource() methods in order to be able to display HTML on Android 4.2.2 :(

**Pull request closed without merging**
