### PR TITLE
Fixed instrumentation test runner OK sniffing

### PR DESCRIPTION
**Pull request by bestander**
Fixed regex that looks for OK sign

**Test plan (required)**

- circle CI results

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
@bestander updated the pull request.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1099030790149636/int_phab) to review.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1099030790149636/int_phab) to review.

**Pull request closed without merging**
