### PR TITLE
Update RCTLinking.m 

### PR DESCRIPTION
**Pull request by shrutic123**
Thanks for submitting a PR! Please read these instructions carefully:

- [X ] Explain the **motivation** for making this change.be app extension safe 
- [X ] Provide a **test plan** demonstrating that the code is solid.
- [ X] Match the **code formatting** of the rest of the codebase.
- [X ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

What existing problem does the pull request solve?

React-navigation requires LinkingIOS to be referenced. When I include the RCTLinkingIOS subspec, it exposes more app extension unsafe code. This fix updates the RCTLinkingIOS code to 

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

Made changes locally and tested on my local device that the react-native code compiles with RCTLinkingIOS subspec specified

If you have added code that should be tested, add tests.

## Next Steps

Sign the [CLA][2], if you haven't already.

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by shrutic123** [comment]
image
Seems like the PR failed at a file that is unrelated to my code changes. Appreciate thoughts on how to resolve it

**Comment by shrutic** [comment]
Would appreciate if someone could review and check this code in. This PR blocks us from using react-navigation in our iMessage app extension. 

And given that Navigator is removed in the latest react-native release, the priority of this fix going in is much higher for us

**Comment by shrutic** [comment]
@javache .. Appreciate if you could take a look at this PR and import. Including you as you have imported my other similar PRs here https://github.com/facebook/react-native/pull/13328 and https://github.com/facebook/react-native/pull/13227

**Comment by javache** [comment]
Could you merge this again? It seems you've picked up a bunch of unrelated changes.

**Comment by shrutic123** [comment]
I have since created a new PR to address this issue. https://github.com/facebook/react-native/pull/14263. I thought I closed this one. Let me try and close it

**Pull request closed without merging**
