### PR TITLE
Fix launching text editor from a redbox stacktrace on windows

### PR DESCRIPTION
**Pull request by janicduplessis**
Launch the editor with cmd on windows.

### CODE REVIEW

**Comment by pcottle** [comment]
I'm worried the `args.unshift` will be brittle if someone else changes the implementation above.

maybe we should just fork on `win32` earlier? we already have `getArgumentsForLineNumber(editor, fileName, lineNumber)` abstracted out. id just like to see something like:

```
args = [
  editor,
  '\c', // explanation why this is
  fileName,
  lineNumber ? getArgumentsForLineNumber(editor, fileName, lineNumber) : '',
];
```

**Comment by janicduplessis** [comment]
@pcottle The goal here is just to launch the editor in a shell because Windows can only run .exe files with ```child_process.spawn```. I think forking at ```child_process.spawn``` is fine but you are right, using ```unshift``` isn't a good idea because it will modify the args object if we ever change something after it could break.

**Comment by pcottle** [comment]
Great! A ton cleaner. will import

**Comment by pcottle** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
