### PR TITLE
Fix IP detection on Mac with loopback

### PR DESCRIPTION
**Pull request by hilkeheremans**
## Motivation
There is a bug with IP detection on Macs that have (1) multiple ethernet interfaces, (2) are using the second or third interface as their primary connection and (3) have extra loopback IPs configured (for example when running OpenVPN, running some Docker configurations or other more exotic applications). In those cases, automatic IP detection will falsely detect the IP as something like `127.94.0.1`, which will make it impossible to run debug builds from a physical device.

## Cause
The underlying network configurations looks something similar to this (irrelevant parts omitted):
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet 127.94.0.1 netmask 0xff000000
	nd6 options=201<PERFORMNUD,DAD>
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=10b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV>
	ether xx:xx:xx:xx:xx:xx
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	inet 192.168.0.226 netmask 0xffffff00 broadcast 192.168.0.255
en2: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether xx:xx:xx:xx:xx:xx
	media: autoselect <full-duplex>
	status: inactive
```

In this configuration the packager will currently figure out `127.94.0.1` instead of `192.168.0.226`.

## Proposed Fix
In addition to the existing filter on `127.0.0.1`, also filter out all loopback addresses by adding a grep filter on `127.94.0`. This PR does exactly that.

Tested and found working on the culprit systems as well as various MacBooks.

### CODE REVIEW

**Comment by javache** [comment]
Could we instead filter out everything starting with 127.? That whole range is reserved for loopback addresses.

**Comment by hilkeheremans** [comment]
Yep, that would be an option.

`grep '^127.'` sound ok? I'll adjust the PR.

**Comment by javache** [comment]
Can you please rebase this change? It's failing to apply internally.

**Comment by hilkeheremans** [comment]
Done, merge conflict resolved. Let's see how this goes.

**Comment by javache** [comment]
Looks like something went wrong with the rebase (see the Files changed tab). Can you try again?

**Comment by hilkeheremans** [comment]
That's very odd. I must have made a mistake somewhere - monday morning after a heavy weekend ;-) Anyway, rather than risk messing this particular PR up even more, see PR #13415.

**Pull request closed without merging**
