### PR TITLE
[TextInput] Implements `blurOnSubmit`

### PR DESCRIPTION
**Pull request by dsibiski**
The default value (to retain current behavior) is set to `true`. Setting the value to `false` will prevent the textField from blurring but still fire the `onSubmitEditing` callback. However, the `onEndEditing` callback will not be fired.

Addresses issue: https://github.com/facebook/react-native/issues/2129

### CODE REVIEW

**Comment by dsibiski** [comment]
Doesn't look like this current implementation is going to work as it also blocks switching to other TextInputs and is causing some strange things with CMD-R...looking into those...

**Comment by brentvatne** [comment]
@dsibiski - this is awesome, I think it's a very important feature to get in. Have you fixed the implementation since your previous comment?

**Comment by brentvatne** [comment]
Pulling in your comment from #641 

> Basically, it allows for backward compatibility by defaulting to true, however, the main idea goes with the normal iOS convention that the keyboard should technically stay there even on submit. One day the default value of true could be deprecated.

> In the case of switching to different fields...the user would set blurOnSubmit to false (currently) and the keyboard would not dismiss. However, the onSubmitEditing callback would still fire and they would be able to programmatically do what @ide described earlier, by simply calling focus() on the ref of their choice. No keyboard "jumping" to deal with. :)

**Comment by dsibiski** [comment]
@brentvatne Yeah, my latest commit fixes the issue I commented on.

**Comment by brentvatne** [comment]
cc @ide @sahrens

**Comment by dsibiski** [comment]
@nicklockwood Any thoughts on this one?

**Comment by jim-lake** [comment]
This or something similar would be great to prevent keyboard flashing in apps.

**Comment by dsibiski** [comment]
Here is a quick demo of what this looks like when its working to switch between fields in a form...

bluronsubmit_demo

Here is the sample code that makes this work:

```javascript
var InputScreen = React.createClass({
    _focusNextField(nextField) {
        this.refs[nextField].focus()
    },

    render: function() {
        return (
            <View style={styles.container}>
                <TextInput
                    ref='1'
                    style={styles.input}
                    placeholder='Normal'
                    returnKeyType='next'
                    blurOnSubmit={false}
                    onSubmitEditing={() => this._focusNextField('2')}
                />
                <TextInput
                    ref='2'
                    style={styles.input}
                    keyboardType='email-address'
                    placeholder='Email Address'
                    returnKeyType='next'
                    blurOnSubmit={false}
                    onSubmitEditing={() => this._focusNextField('3')}
                />
                <TextInput
                    ref='3'
                    style={styles.input}
                    keyboardType='url'
                    placeholder='URL'
                    returnKeyType='next'
                    blurOnSubmit={false}
                    onSubmitEditing={() => this._focusNextField('4')}
                />
                <TextInput
                    ref='4'
                    style={styles.input}
                    keyboardType='numeric'
                    placeholder='Numeric'
                    blurOnSubmit={false}
                    onSubmitEditing={() => this._focusNextField('5')}
                />
                <TextInput
                    ref='5'
                    style={styles.input}
                    keyboardType='numbers-and-punctuation'
                    placeholder='Numbers & Punctuation'
                    returnKeyType='done'
                />
            </View>
        );
    }
});
```

**Comment by PhilippKrone** [comment]
cc @nicklockwood @sahrens  Any idea when this is going to get merged?

**Comment by PhilippKrone** [comment]
@dsibiski I've just applied your pull request into my fork (which is basically facebook/react-native master) and its not working. During debugging, I've noticed that its not jumping into 

````javascript
- (BOOL)textFieldShouldEndEditing:(UITextField *)textField
{
  if (_submitted) {
    _submitted = NO;
    return _blurOnSubmit;
  }
  return YES;
}
````

Do you have any idea here?

**Comment by dsibiski** [comment]
@PhilipKrone Ah yes, the delegate was moved to the RCTTextFieldManager. Should be able to move this implementation there with some slight modification. I'll try to do this later today.

**Comment by dsibiski** [comment]
@PhilippKrone That should work now. Please let me know.

**Comment by PhilippKrone** [comment]
Perfect, thanks a lot - it’s working. Would love to see it in core.

**Comment by JakeRawr** [comment]
Thanks, @dsibiski 

Before your work, my message system is not as user friendly because when they send a message, they had to refocus the textinput to show the keyboard. 

I hope this will be merged soon.

**Comment by brentvatne** [comment]
Awesome @dsibiski 

@nicklockwood @sahrens - I'd love to see this get imported when you get a chance

**Comment by cgarvis** [comment]
:+1:

**Comment by morenoh149** [comment]
would be useful to me too

**Comment by dsibiski** [comment]
@nicklockwood I think the last bit left to be able to push this one out would be adding a UIExplorer example and squashing commits...anything else?

**Comment by nicklockwood** [comment]
A UIExplorer example would be great. Don't worry about squashing commits.

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by ajwhite** [comment]
:clap: great enhancement

**Comment by ruandao** [comment]
Execute me!  
Where to find the `focus` function, it work correct, but I can't found it at [TextInput Props](http://facebook.github.io/react-native/docs/textinput.html#content), I mean where to find some other property like `focus`   
Thank you!

**Comment by dsibiski** [comment]
@ruandao: The `focus()` method is actually defined in `NativeMethodsMixin` here: https://github.com/facebook/react-native/blob/2c7de35dee347b5d9a40b4e87862622e60ddf7d9/Libraries/ReactIOS/NativeMethodsMixin.js#L131-L137

**Comment by ehd** [comment]
Hey, this is a feature I was really looking forward to, thanks for adding it!

When I played with this I noticed that it's implemented for `UITextField`, but not for a multiline `UITextView`. Is that something we want to support? [`UITextViewDelegate` does have an accompanying method](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UITextViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/UITextViewDelegate/textViewShouldEndEditing:).

**Comment by chirag04** [comment]
@ehd can you PR?

**Comment by nicklockwood** [comment]
The reason we don't have this for `UITextView` is that it treats `<return>` differently from `UITextField`. For `UITextField`, return characters are ignored, and pressing return either does nothing or ends editing and submits the field, but for `UITextView`, return is a valid character that will be inserted into the text.

If we were going to add `blurOnSubmit` for multiline fields it would have to default to `false` to avoid changing the default behaviour. I guess we can make that work though.

The alternative would be to have a separate property like `submitOnReturn`, but I'm not so keen on that (and it would still need to have a different default for single vs multiline so it doesn't really solve anything).

**Comment by ehd** [comment]
Yes, I now see what you mean after experimenting with the view's current behavior in v0.16.0-rc. In my case, in the multiline text input I was actually calling `blur` and have forgotten about it. So I'm just clearing the text now without bluring. However, I've been unable to handle the enter key the way I want to (to not create a newline, but to call a callback) without causing a value change event to be triggered, too.

**Comment by nicklockwood** [comment]
I'm going to try adding blurOnSubmit support for multiline textInput. I'll let you know how it goes.

**Comment by ehd** [comment]
@nicklockwood That is great, thank you!

**Comment by nicklockwood** [comment]
I've realised that there's a slight problem with this plan. blurOnSubmit = true will work fine for multiline fields, but blurOnSubmit = false (the default) won't actually do what the blurOnSubmit was originally intended for, namely allowing you to implement a multi-field form without keyboard flicker.

I don't think this is a reason not to ship the feature, but if anybody wants a multiline text field where pressing return triggers the submit action *without* blurring the field, we'll have to think of something else.

**Pull request closed without merging**
