### PR TITLE
Add instructions to reload simulator for non-QWERTY keyboards

### PR DESCRIPTION
**Pull request by anant90**

### CODE REVIEW

**Comment by christopherdro** [comment]
@anant90 Thanks for the PR!

I'm assuming this applies to all non-qwerty keyboards?
How about simplifying it a bit?

...to bring up the dev menu and click "Refresh" or `CMD + P` on Dvorak & Colemak layouts.

**Comment by anant90** [comment]
@christopherdro Thanks! Updated it to simpler text as you suggested.

**Comment by satya164** [comment]
I updated the PR title and removed the PR description to better reflect the changes. Hope you don't mind.

**Comment by christopherdro** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
