### PR TITLE
[Android] onKeyPress event not fired with numeric keys

### PR DESCRIPTION
**Pull request by fabriziobertoglio1987**
## Summary

This issue fixes https://github.com/facebook/react-native/issues/19507 fixes https://github.com/facebook/react-native/issues/30475 onKeyPress event not fired for numeric keyboard
The TextInput onKeyPress event is not fired when pressing numeric keys on Android.

The method sendKeyEvent will dispatchKeyEvent only for:
- ENTER_KEY_VALUE 
- KEYCODE_DEL (delete key)

The solution proposed is trigger dispatchKeyEvent for KeyEvents with event.getUnicodeChar() value included between 47 and 58 (numeric keys 0-9)

## Changelog

[Android] [Fixed] - onKeyPress event not fired with numeric keys

## Test Plan

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
|  |  |

</p>
</details>

### CODE REVIEW

**Comment by nukemonk** [comment]
Thank you very much for this fix! There's only one adjustment that needs to be made on line 135:    

boolean isNumberKey = event.getUnicodeChar() < 56 &&

the number needs to be < 58 since event.key for the number 9 is 57. Now number 8 and 9 are excluded and don't trigger the event.

**Comment by fabriziobertoglio1987** [comment]
@nukemonk thanks a lot for the correction, I will make the adjustment this weekend. I wish you a good day. Fabrizio

**Review by nukemonk — APPROVED** [review]

**Comment by mariomurrent-softwaresolutions** [comment]
Any Updates on this one?

**Comment by fabriziobertoglio1987** [comment]
@mariomurrent-softwaresolutions I need more time and have more detailed look at the detox failures. Thanks

test-android
```
+ buck fetch ReactAndroid/src/test/java/com/facebook/react/modules
Not using buckd because watchman isn't installed.
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
PARSING BUCK FILES: FINISHED IN 1.9s
Buck wasn't able to parse /root/react-native/ReactAndroid/src/main/java/com/facebook/BUCK:
Incorrect arguments to android_library with name yoga: Extra unknown kwargs: autoglob

This error happened while trying to get dependency '//ReactAndroid/src/main/java/com/facebook:yoga' of target '//ReactAndroid/src/test/java/com/facebook/react/modules:modules'

Exited with code exit status 1
```
test-docker
```
Not using buckd because watchman isn't installed.
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
PARSING BUCK FILES: FINISHED IN 3.3s
Buck wasn't able to parse /app/ReactAndroid/src/main/java/com/facebook/BUCK:
Incorrect arguments to android_library with name yoga: Extra unknown kwargs: autoglob

This error happened while trying to get dependency '//ReactAndroid/src/main/java/com/facebook:yoga' of target '//ReactAndroid/src/test/java/com/facebook/react/modules:modules'
The command '/bin/sh -c buck fetch ReactAndroid/src/test/java/com/facebook/react/modules' returned a non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by mariomurrent-softwaresolutions** [comment]
Okay, cool & thx

**Comment by mariomurrent-softwaresolutions** [comment]
@fabriziobertoglio1987 Is it done?

**Comment by vadimb** [comment]
@fabriziobertoglio1987 this CI's issue you are experiencing seems to have been fixed in master. Would you mind updating your branch to master please? I'm more then happy to collaborate on this if you are busy.

**Comment by fabriziobertoglio1987** [comment]
@vadimb thanks a lot for your feedback. Feel free to do a code review on this pr and collaborate with me. I'll be happy to accept your improvements.. Currently I'm working (in my free time) on other prs and I don't know of any problems with this pr, but I'll be happy to follow your advice/improvements. Thanks a lot :pray:

**Comment by vadimb** [comment]
@fabriziobertoglio1987 I just observed that you handle ONLY digits, right? So if I were to use a `phone-pad` typing on non-digit key like `+` e.g `+1 123 123 1234` wont work.

I'm wondering what keeps us from matching the iOS implementation https://github.com/facebook/react-native/blob/master/React/CoreModules/RCTEventDispatcher.mm#L85  where all keys get pass trough ?

**Comment by fabriziobertoglio1987** [comment]
thanks a lot @vadimb 

yes, but still reading your review and interacting with you is very valuable for me, as from our interaction we may get ideas on how to improve or break this functionality.

I consider you comment a very valuable code review. I did not think about this scenario and use case, but luckily it was covered.
I wish you a good evening. Thanks. Fabrizio

**Comment by vadimb** [comment]
@nukemonk can you please let us know if there is any eta when we this PR will be merged?

**Review by vadimb — APPROVED** [review]

**Comment by fabriziobertoglio1987** [comment]
@vadimb there is no eta. :pray:

**Comment by nukemonk** [comment]
> @nukemonk can you please let us know if there is any eta when we this PR will be merged?

@vadimb I am sorry but I am unsure about what you request of me. I am not a maintainer of this branch nor I am authorized to do anything with it.

**Comment by vadimb** [comment]
My bad - seeing that you approved thought you have super powers :) - but seems anyone can review/approve.

**Comment by mariomurrent-softwaresolutions** [comment]
I already updated the code from @fabriziobertoglio1987. But no PR approve on his side

**Review by msegers — APPROVED** [review]

**Review by pepf — APPROVED** [review]
🥇

**Comment by vastamaki** [comment]
Any estimate when this could be released? 🙂

**Comment by fabriziobertoglio1987** [comment]
@vastamaki you can check out https://github.com/sponsors/fabriziobertoglio1987 if you are interested, otherwise I can estimate 6-12 months.

**Comment by fabriziobertoglio1987** [comment]
>Any estimate when this could be released?

@vastamaki To answer the question of when this fix will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- once the Pull Request is merged, the issue is closed. The review and merge is performed by the Facebook Team that works on the Facebook Ads App running React Native from source. Currently we have 351 open pull requests so the review and merge may take some time.
- The fix is tested in Facebook Ads App running React Native from master for several months
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues to discuss
In this discussion everyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by lfabl** [comment]
Same problem. But not only android. My problem on both. ( IOS + Android ). I don't know why pull request was technically rejected, but I have a specific need. I am faced with a case that works according to an algorithm and I have to process individual letters. Just; numbers, commas, periods and backspace. For this reason, is it possible to come up with a solution?

**Comment by McSam94** [comment]
Guys, why is this PR close?

**Comment by Matiassimone** [comment]
Still persists,
on `"react-native": "0.68.2"`.

Using this `TextInput` with the follow props and `keyboardType="number-pad"`,
the numbers only trigger in the `onKeyPress`, 
`onChangeText` or `onChange` callbacks are NOT called when press numbers (1, 2, 3...).

```
      <TextInput
        autoFocus
        caretHidden
        contextMenuHidden
        onKeyPress={onKeyPress}
        ref={phoneRef}
        maxLength={6}
        autoCorrect={false}
        onChange={onChange}
        onChangeText={onChangeText}
        keyboardType="number-pad"
        textContentType="oneTimeCode"
        autoComplete="sms-otp"
        keyboardAppearance={isDarkMode ? 'dark' : 'light'}
        style={styles.nativeKeyboardHidden}
      />
```

**Pull request closed without merging**
