### PR TITLE
Fix cleanReactNdkLib task failure again

### PR DESCRIPTION
**Pull request by leeight**
1. See #7935
2. https://github.com/facebook/react-native/commit/37df151562f905f1ff54bc753406a8ba10656ff3

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @cjhopman and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
@leeight updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@leeight updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@leeight updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@leeight updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@leeight updated the pull request.

**Comment by leeight** [comment]
Ping  @cjhopman and @mkonicek

**Comment by facebook-github-bot-3** [comment]
@leeight updated the pull request.

**Comment by leeight** [comment]
https://github.com/facebook/react-native/pull/9607

**Pull request closed without merging**
