### PR TITLE
[iOS] [CLI] Make run-ios find if a device is booted better

### PR DESCRIPTION
**Pull request by rmevans9**
**Motivation**
This morning I was trying to test on iPhone 7 with iOS 10 so I booted that device and ran "react-native run-ios" expecting it to notice I had a simulator running and install my app to it. Instead it switched my device to the iPhone 6s iOS 9.2. After digging it was found that run-ios did not handle multiple versions of iOS being installed very well when it came to checking for the booted device. This PR resolves that.

**Test plan (required)**
Tests were added for the situation of multiple iOS versions being installed and a slight change to the code was completed to make the new tests pass and continue to keep the old tests passing.

### CODE REVIEW

**Comment by rmevans9** [comment]
After looking at this PR again I think there is another use case for multiple os versions that is not covered prior to this PR and also after. If I have 2 (or more) iOS versions installed all sharing a specific device (for ex iPhone 6s) and I run "react-native run-ios --simulator "iPhone 6s"" this will run it on the oldest iOS version available. I don't know if this matters since this PR would allow the developer to switch to the iPhone 6s on the newer OS version and then simply run "react-native run-ios" to have it run on the booted simulator. Let me know if anyone wants me to try and solve this additional use case with this PR.

**Comment by rmevans9** [comment]
Looks like travis failed on tvOS not anything I touched.

**Comment by dlowder-salesforce** [comment]
@rmevans9 The logging test failures in tvOS have been fixed, see https://github.com/facebook/react-native/pull/10568 .  If you do an upstream merge, hopefully all tests pass now :)

**Comment by rmevans9** [comment]
@dlowder-salesforce will do likely tomorrow. Thanks!

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
