### PR TITLE
Add Flipper to default template on Android and iOS

### PR DESCRIPTION
**Pull request by safaiyeh**
## Summary
Issue: https://github.com/facebook/react-native/issues/27565

initalizeFlipper should be set in template app by default.

## Changelog

[iOS] [Changed] - Added Flipper to template app
[Android] [Changed] - Added Flipper to template app

## Test Plan

Connect Flipper to the iOS application
Connect Flipper to the Android application

### CODE REVIEW

**Comment by rickhanlonii** [comment]
Wow this is great! What's the CI failure?

**Comment by rickhanlonii** [comment]
- So you know which commits are needed to cherry pick to 0.62 to support this?
- Should we add this to RNTester as well?

**Comment by safaiyeh** [comment]
@rickhanlonii the failed CI has been a known issue. The master build for that is failing as well.

You can cherry pick:
f0fbca47f398b4b468eb5cb54c5d75dcfbe2aa98
f1c70f207d427d6f05eed5b00c75d349699c38ae
22760d5860497724a59b065e9dd2ed8648a764fb

RNTester implementation is not consistent with 0.62 implementation. I can update that to match.

**Comment by rickhanlonii** [comment]
@safaiyeh how does the use_frameworks issue impact this?

**Comment by passy** [comment]
I think after #27837, this should be good to go.

**Comment by rickhanlonii** [comment]
Is this good to go now?

**Comment by passy** [comment]
I think so!

**Pull request closed without merging**
