### PR TITLE
add 昨日热推 app to showcase

### PR DESCRIPTION
**Pull request by chenxsan**

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @alexleventer to be potential reviewers.

**Comment by lacker** [comment]
Can you change the title to

"Developing the react-native-image-viewer library"

I think that would be more helpful as a description of the content at the link.

**Comment by facebook-github-bot-9** [comment]
@chenxsan updated the pull request.

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3727064) to review internal test results.

**Comment by alexleventer** [comment]
Looks like the press is a personal blog.

**Comment by lacker** [comment]
Guidelines now say press or technical blog post. I tried to be fair to account for a number of things that are not press level, but do have a technical blog post. Setting precise rules for this is tricky though. Maybe... do you think it would be better to require a corporate-branded technical blog post?

**Comment by chenxsan** [comment]
I developed this app all by myself, I think it's a good showcase that you can make an app with React Native even without a whole corporate backed :).

**Comment by alexleventer** [comment]
@lacker it's probably best to do corporate-branded technical blog post or press.

**Comment by lacker** [comment]
@alexleventer Seems reasonable going forward, although for fairness I'm ok keeping this one in. I'll send a PR

**Comment by lacker** [comment]
https://github.com/facebook/react-native/pull/9455

**Pull request closed without merging**
