### PR TITLE
Add an integration test for WebSocket

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
**Motivation**

See if we can safely run a WebSocket test in Travis CI

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
@satya164 Here's a network test that will hopefully run in Travis CI, per our discussion in Slack.  Please take a look and see what you think.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Thanks for adding it @dlowder-salesforce!

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
Let's give this another go.

**Pull request closed without merging**
