### PR TITLE
[ScrollView] Added props for disabling bouncing on certain edges.

### PR DESCRIPTION
**Pull request by brandonreavis**
This adds `bouncesTop`, `bouncesBottom`, `bouncesLeft`, `bouncesRight` properties to ScrollViews which can be used to turn off bouncing on particular edges of the control. 

http://stackoverflow.com/questions/14084657/uiscrollview-disable-vertical-bounce-only-at-bottom

Doing this purely with JS in the onScroll event is very glitchy so it has to be done natively.

### CODE REVIEW

**Comment by ide** [comment]
cc @nicklockwood 

this looks good to me even if it's bit of a quirky feature

**Comment by skevy** [comment]
At the very least, I think if we do this we need to add it to the ScrollView documentation.

In some future work, it would be worthwhile expanding on the ScrollView documentation to express the reasoning behind some of it's idiosyncrasies. To people coming to RN from native mobile...they already know how crazy these things are. But for people coming from a web background...it's definitely FAR from obvious why there's all these crazy options on this thing.

**Comment by mkonicek** [comment]
I believe this is a very edge-case feature that is not worth adding 4 extra props and code to be maintained by the React Native community.

I'll close this one. Please correct me if I'm wrong.

**Comment by brandonreavis** [comment]
I am generally in agreement. Subclassing RCTScrollView is probably the better way to go for people that need finer control of how a scrollview works. This has been working well except there are few quirks that could be resolved to make it easier. (`RCTBatchedBridge::initModules()` tries to call the `initWithFrame` constructor which RCTScrollView throws an "unimplemented" exception for)

**Pull request closed without merging**
