### PR TITLE
Add validate method to StyleSheet component

### PR DESCRIPTION
**Pull request by peteychuk**
This PR makes it so that adding a new `validate` method to StyleSheet component.
The main motivation is so a lot of popular react-native libraries* doesn't support StyleSheet style. Sometimes I have used `flatten` method for an extracting style object.
In my opinion, it's good to have validation method for such situations.

I believe this to be the good feature for developers. Would be much appreciated if we could get this merged in.

Thanks! Let me know if you have any questions.

*For example, few libraries doesn't support StyleSheet style:
https://github.com/react-native-community/react-native-elements
https://github.com/GeekyAnts/NativeBase

### CODE REVIEW

**Comment by peteychuk** [comment]
2) Absolutely agree with you. It's the right way to use StyleSheet.flatten accordingly to React Native documentation. But in fact, we have much more than 2 libraries (I have given 2 libraries only for example). It's a question for me why they don't support StyleSheet styles by default. But anyway, in my opinion, it's good to have validation method.

1) Yes, it's really weird. I would suggest two variants. First - rename method to `createPure`. Second - left name `validate` but don't return any data. In my opinion first variant is better because you can use this method as single API call:
```
export default StyleSheet.createPure({
   listItem: {
     flex: 1,
     color: '#eeeeee',
   },
   selectedListItem: {
     color: '#ffffff',
   },
 });
```

**Comment by vjeux** [comment]
I've been thinking about it some more and I don't think that this is a good idea to put this into core. We want people to use StyleSheet.create and the infrastructure behind it. If some libraries decide against it, then we shouldn't make it easier in the core library for them to do so.

If for your app you want to get the safety benefits of StyleSheet.create, then it's easy to make a wrapper for it:

```js
function validate(styles) {
  if (__DEV__) {
    StyleSheet.create(styles);
  }
  return styles;
}
```

and I encourage you to do so on your app.

Thanks very much for the pull request though, it is very appreciated!

**Comment by peteychuk** [comment]
I also have been thinking about it and decided to close this pull request because I think that using `flatten` is the right way and React Native core shouldn't support another additional method.

Thank you @vjeux for your time.

**Comment by peteychuk** [comment]
BTW: Let me explain more details, let's image the situation:
You have a page with different components (native components with StyleSheet style support and another component without StyleSheet style support) and you want to use just one style file:
```
export default StyleSheet.create({
  forNativeComponent: {
    backgroundColor: '#ffffff',
  },
  forExternalComponent: {
    backgroundColor: '#000000',
  },
});
```
In this case we can't use `StyleSheet.create` because external component doesn't support StyleSheet style.
Let's refactor this code:
```
const style = StyleSheet.create({
  forNativeComponent: {
    backgroundColor: '#ffffff',
  },
});
const pureStyle = {
  forExternalComponent: {
    backgroundColor: '#000000',
  },
}

export default Object.assign({}, pureStyle, style);
```
Now it's working for all components.
To validate component let's add wrapper `validate`:
```
function validate(styles) {
  if (__DEV__) {
    // 2 calls instead of suggested before method "validate".
    StyleSheet.flatten(StyleSheet.create(styles));
  }
  return styles;
};

const style = StyleSheet.create({
  forNativeComponent: {
    backgroundColor: '#ffffff',
  },
});
const pureStyle = validate({
  forExternalComponent: {
    backgroundColor: '#000000',
  },
});

export default Object.assign({}, pureStyle, style);
```

Thanks again!

**Pull request closed without merging**
