### PR TITLE
[CLI]let 'react-native bundle' support 'platform' option.

### PR DESCRIPTION
**Pull request by tdzl2003**
usage: 

react-native bundle --platform android --minify

platform defaults to "ios"

also fix error "Error validating module options:" on current master.

### CODE REVIEW

**Comment by Cococ** [comment]
that good

**Comment by Cococ** [comment]
good

**Comment by mkonicek** [comment]
Thanks for doing this!

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request merged**
