### PR TITLE
[Bugfix] Memory Leaks caused by RCTNavigator

### PR DESCRIPTION
**Pull request by rocman**
releasing the viewControllers referred by _navigationController.viewControllers, which is also releasing the related views

### CODE REVIEW

**Comment by javache** [comment]
This shouldn't be necessary. Deallocating the RCTNavigator should remove the last reference to the navigation controller, and it should release the view controllers in its dealloc. If you're still seeing memory leaks here, there must be something else keeping track of the navigation controller and/or view controllers.

**Comment by rocman** [comment]
@javache You are right. When I looked into the deep, I found that the root of the memory leaks is because the NavigationController is not removed from its parentViewController when the owner view of it deallocates.

**Comment by javache** [comment]
That still doesn't make sense. The container view controller would have a strong reference to the navigation controller, so its dealloc would never be invoked.

**Comment by rocman** [comment]
@javache It's been tested that when the NavigationController is removed from its parentViewController, the dealloc method on it is called. So I think this can prove that the parentViewController is the only object that refers to it.

**Comment by javache** [comment]
Ah yes, I see now, makes sense. Can you keep the `delegate = nil`? That avoids crashes when the navigation controller is still retained elsewhere.

**Comment by rocman** [comment]
Doesn't it automatically turns to be nil when the NavigationController deallocates?

**Comment by javache** [comment]
You can't guarantee that UINavigationController will also deallocate at that point (although it should). Also, a lot of UIKit is still using assign instead of weak (especially on older versions), so this is a good measure for memory safety.

**Comment by rocman** [comment]
OK, I understand your concern. I'll do as you suggested.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by rocman** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
