### PR TITLE
Fresh RN projects fails ESLint / Prettier by default

### LINKED ISSUE #25477: Fresh RN projects fails ESLint / Prettier by default
React Native version:
0.60.0

## Steps To Reproduce

1. Create new project `react-native init rn60stable && cd rn60stable`
2. Run `npm run lint`

Describe what you expected to happen:

- No errors

Snack, code example, or link to a repository:

- Output:

```
/Users/jonnyburger/rn60stable/App.js
   9:16  error  Replace `Fragment}·from·'react'` with `·Fragment·}·from·"react"`                              prettier/prettier
  16:12  error  Delete `,`                                                                                    prettier/prettier
  17:8   error  Replace `'react-native'` with `"react-native"`                                                prettier/prettier
  24:21  error  Delete `,`                                                                                    prettier/prettier
  25:8   error  Replace `'react-native/Libraries/NewAppScreen'` with `"react-native/Libraries/NewAppScreen"`  prettier/prettier
  34:36  error  Insert `⏎········`                                                                            prettier/prettier
  72:36  error  Delete `,`                                                                                    prettier/prettier
  75:34  error  Delete `,`                                                                                    prettier/prettier
  79:26  error  Delete `,`                                                                                    prettier/prettier
  83:17  error  Replace `'600'` with `"600"`                                                                  prettier/prettier
  84:24  error  Delete `,`                                                                                    prettier/prettier
  89:17  error  Replace `'400'` with `"400"`                                                                  prettier/prettier
  90:23  error  Delete `,`                                                                                    prettier/prettier
  93:17  error  Replace `'700',` with `"700"`                                                                 prettier/prettier
  94:4   error  Delete `,`                                                                                    prettier/prettier

/Users/jonnyburger/rn60stable/__tests__/App-test.js
   5:8   error  Replace `'react-native'` with `"react-native"`                prettier/prettier
   6:19  error  Replace `'react'` with `"react"`                              prettier/prettier
   7:17  error  Replace `'../App'` with `"../App"`                            prettier/prettier
  10:22  error  Replace `'react-test-renderer'` with `"react-test-renderer"`  prettier/prettier
  12:4   error  Replace `'renders·correctly'` with `"renders·correctly"`      prettier/prettier

/Users/jonnyburger/rn60stable/babel.config.js
  2:13  error  Replace `'module:metro-react-native-babel-preset'],` with `"module:metro-react-native-babel-preset"]`  prettier/prettier

/Users/jonnyburger/rn60stable/index.js
  5:9   error  Replace `AppRegistry}·from·'react-native'` with `·AppRegistry·}·from·"react-native"`      prettier/prettier
  6:17  error  Replace `'./App'` with `"./App"`                                                          prettier/prettier
  7:9   error  Replace `name·as·appName}·from·'./app.json'` with `·name·as·appName·}·from·"./app.json"`  prettier/prettier

/Users/jonnyburger/rn60stable/metro.config.js
  13:30  error  Delete `,`  prettier/prettier
  14:8   error  Delete `,`  prettier/prettier
  15:7   error  Delete `,`  prettier/prettier
  16:4   error  Delete `,`  prettier/prettier
```

Maybe there should be a prettier config? Or no prettier integration at all?
However, that there can be lint errors in a fresh projects does not seem right.

### PR DESCRIPTION
**Pull request by jpdriver**
## Summary
Fixes #25477

This PR adds a `.prettierrc.js` config file to the HelloWorld template.

`eslint-config-react-native-community` includes custom settings for some rules which conflict with Prettier's default settings.

Consequently, if you run `eslint` immediately after scaffolding a new app you get errors (see linked issue).

This PR configures Prettier to be compatible with both the existing ESLint config and the existing project template (with no code changes to the latter).

## Changelog

[General] [Changed] - Added a default Prettier config for new projects

## Test Plan

- The following screenshots show the output of `yarn lint` before and after these changes
- These were run immediate after running `npx react-native-cli init RN060`

### Without these changes

- Linting errors on new projects
- Unfixable automatically due to conflicting rules
Screenshot 2019-07-03 at 17 44 55
Screenshot 2019-07-03 at 17 45 07

### With these changes

- Brand new projects will not produce lint errors out of the box
Screenshot 2019-07-03 at 17 48 25

### CODE REVIEW

**Comment by cpojer** [comment]
Ideally we won't change the default and instead fix up the eslint config so that this problem doesn't happen. Could you make that change?

**Comment by karlmarxlopez** [comment]
Adding `.prettierrc` solves my problem

```js
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "singleQuote": true
}
```

**Comment by satya164** [comment]
I think we should add a `.prettierc.json` by default to the template

**Comment by cpojer** [comment]
Yes let's do that!

**Comment by jpdriver** [comment]
added a `.prettierrc` as per @satya164 's suggestion.

I did this as a `.js` using `module.exports` so it matches the corresponding default `.eslintrc.js`.

with a few minimal rules we're able to lint the HelloWorld template *with no template changes* ✨

**Comment by cpojer** [comment]
Can you run prettier? :)

**Comment by jpdriver** [comment]
@cpojer I think everything's ready and this can be landed now. Sorry I made the PR a little messy -- happy to open a fresh one if needed..

**Comment by keshav00001** [comment]
hi......
i am following your  suggestion but i am getting same issue.

**Comment by RobinCsl** [comment]
@cpojer Would it be necessary to add `prettierrc.js` to this [list](https://github.com/react-native-community/cli/blob/c386351b2b2219bd4e59b4e47962694ea68f8d95/packages/cli/src/commands/init/editTemplate.js#L45-L52) in `@react-native-community/cli` too so that `_prettierrc.js` gets renamed to `.prettierrc.js`?

#### Results of `./cli.js init --template=file:///path/to/react-native TestProject`

BEFORE patching `node_modules/@react-native-community/cli/build/commands/init/editTemplate.js`
Screenshot 2019-07-15 at 17 30 45


AFTER patching  `node_modules/@react-native-community/cli/build/commands/init/editTemplate.js` by adding `'prettierrc.js'` to the list `UNDERSCORED_DOTFILES`

Screenshot 2019-07-15 at 17 33 57

**Comment by satya164** [comment]
@RobinCsl will be great if you can send a PR

**Pull request closed without merging**
