### PR TITLE
Introduced class method to RCTLinkingManager to match new openURL handler

### PR DESCRIPTION
**Pull request by aaronsky**
iOS 10 deprecated an AppDelegate openURL handler in favor of another one. I copied the old one in RCTLinkingManager to better reflect this change in API.

### CODE REVIEW

**Comment by javache** [comment]
If we're not using the options dictionary, I don't think it's very useful to implement this method, as it just adds confusion and doesn't provide new value over the existing API.

**Comment by aaronsky** [comment]
For what it's worth, the sourceApplication and annotation objects aren't being used in the original method either. For the sake of consistency with that method, I matched the signature of the new openURL method.

**Comment by mkonicek** [comment]
I agree with @javache. Once there is a need for the `options` it would make more sense to add it then. Adding it now just because the other one is deprecated (with no plan to remove it?) doesn't add that much value given we're adding code that's potentially confusing (no explanatory comment in the code).

**Comment by joonhocho** [comment]
@aaronsky @javache @javache 
I need this as I am using FacebookSDK for react native and it uses the new api, and I realized that my RCTLinkingManager is not getting called. 
It turns out iOS favors the new API and does not call the old one if new one exists.

**Comment by iures** [comment]
I'm also on the same boat as @joonhocho. We can't make Deep Link work properly without this method.

**Comment by gvillenave** [comment]
+1, can we reopen this PR?

**Comment by perrosnk** [comment]
any updates on this?

**Comment by aaronsky** [comment]
It may be worth reconsidering this patch. The old method isn’t being removed and is already flagged deprecated by the compiler. The new implementation matches the body of the old method exactly, meaning any regressions would impact both implementations equally and the new implementation should not introduce a regression. Finally, the argument that the `options` dictionary isn’t being used in the new implementation feels like a cop-out since the additional information in the old method (`sourceApplication` and `annotation`) isn’t being used either. Let’s get this under review again, now that it’s been a year and iOS 11 is out.

**Comment by joonhocho** [comment]
@mkonicek

**Pull request closed without merging**
