### PR TITLE
Updates from Mon Aug 31st

### PR DESCRIPTION
**Pull request by sahrens**

### CODE REVIEW

**Comment by ide** [comment]
I restarted the Obj-C tests.. it failed the timeout ordering test which seems to have been flaky for awhile but looks unrelated to this sync.

**Comment by sahrens** [comment]
Yeah, I'm disabling the timer test

**Comment by sahrens** [comment]
Yeah, I think it's just a flow thing.  Same reason we don't support ES6 imports and other features I believe.  Fortunately none of them are that big a deal - we have most of the good stuff already ;)

**Comment by sahrens** [comment]
Actually looks like I was mistaken, default args are supported and enabled :)

**Comment by ide** [comment]
cool to hear that. thanks for confirming!

**Pull request merged**
