### PR TITLE
export SwipeableListView component.

### PR DESCRIPTION
**Pull request by chenxsan**
Explain the **motivation** for making this change. What existing problem does the pull request solve?

1. [`SwipeableListView`](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableListView.js) is already usable, I think it would be great to export it so users can test it.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @sebmarkbage and @nicklockwood to be potential reviewers.

**Comment by chirag04** [comment]
cc @fred2028

**Comment by fred2028** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1721931774723406/int_phab) to review.

**Pull request closed without merging**
