### PR TITLE
Consume touchable-bounce from npm

### PR DESCRIPTION
**Pull request by grabbou**
CC: @brentvatne @ide

This is not going to work for now since react-native-touchable-bounce requires react-native (had to change it to be `require('../../../')` instead to avoid cyclic dependency.

Any suggestions how to solve that? I was thinking about making a package.json for each `example` similar to this -> https://github.com/grabbou/react-native-touchable-bounce/blob/master/example/package.json

### CODE REVIEW

**Comment by ide** [comment]
There shouldn't be cycles if you make react-native be a peer dependency (but I don't know if it's actually a good idea to list react-native under peerDependencies). Just remove `react-native` from your dependencies and everything should still work.

**Comment by ide** [comment]
cc @vjeux about moving this component to npm

**Comment by grabbou** [comment]
In fact I do not depend on react-native at all @ide, it's just I am having `require('react-native')` in my index.js which is causing packager to wait forever for the bundle. Requiring via `'../../../` works, which is because react-native itself also depends on that package.

**Comment by mkonicek** [comment]
Would it make sense to not depend on it at all? TouchableBounce sounds like sort of a special case of a button that could be a standalone npm module.

**Pull request closed without merging**
