### PR TITLE
⬆️ Upgrade eslint-config deps

### PR DESCRIPTION
**Pull request by wcandillon**
## Summary

This dependency upgrade ensures that this eslint config now supports the latest TypeScript syntaxes.

## Changelog

[General] [Fixed] - Upgrade dependencies.

## Test Plan

Try this new version of the plugin on your project.

### CODE REVIEW

**Comment by matt-oakes** [comment]
@wcandillon Thanks for updating these. So this can be released as soon as it's merged, can you change the `version` in that `package.json` to `2.0.0`. I believe this should be a breaking change due [dropping support for Typescript 3.2](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0) and [adding new lint checks for hooks](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/CHANGELOG.md#400).

**Comment by wcandillon** [comment]
Thank You for looking into it so quickly. I'm using this upgrade already in some project via `yarn pack` and it's working well. I'm quite excited about this new version :)

**Comment by matt-oakes** [comment]
@wcandillon I've just pushed this to NPM as `2.0.0`

**Comment by wcandillon** [comment]
You've literally made my day @matt-oakes 🙌🏻
Thank you for your support.

**Pull request closed without merging**
