### PR TITLE
Make `yarn` and `yarn jest react-native-codegen` works on Windows with git

### PR DESCRIPTION
**Pull request by ZihanChen-MSFT**
## Summary

A few fixings to make `yarn jest react-native-doegen` works on Windows:

- ~~Add a `.gitignore` file to tell git not to track generated/temporary files.~~
- There is no `rm` on Windows, change it to `rimraf`.

I have been using it in the last 3 months and it works perfectly on Windows, otherwise I could not even build the code in my laptop.

## Changelog

[General] [Changed] - Make `yarn` and `yarn jest react-native-codegen` works on Windows with git

## Test Plan

`yarn jest react-native-codegen` passed

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
I am a bit concerned if this works also on unix-based system. But probably yes, given that it is a `node` module.

**Comment by robhogan** [comment]
> I am a bit concerned if this works also on unix-based system. But probably yes, given that it is a `node` module.

Yeah, rimraf is cross-platform

**Comment by cipolleschi** [comment]
From @robhogan 
> What's this about? Does react-native-codegen write into its own directory?
If this doesn't need to be in the published package then it should probably be in the root .gitignore for consistency. If it does need to be in the published package, that's a bit worrying - it should probably be using something under os.tmpdir() if it needs to write to the filesystem.

Also, we have a linting error:
> Files must end in a newline.
for the `.gitignore`

**Comment by ZihanChen-MSFT** [comment]
@cipolleschi 

> it should probably be using something under os.tmpdir() if it needs to write to the filesystem.

I remember they look like generated C++ files from the unit test, I don't know why these files are not checked in or something.

The `rimraf` is a different thing, it removes `lib` which are build result.

**Comment by cipolleschi** [comment]
> I remember they look like generated C++ files from the unit test, I don't know why these files are not checked in or something.

This looks like something that only happens in Windows... Could you try again, by removing that `tmp` folder and see whether there are those `tmp` files? Perhaps it was some failed execution that left some dirt behind and we don't need to commit the `.gitignore`.

Also, if we need that, a better approach would be to update the `.gitignore` in the [root folder](https://github.com/facebook/react-native/blob/main/.gitignore)

**Comment by ZihanChen-MSFT** [comment]
@cipolleschi Hi, looks like [this commit](https://github.com/facebook/react-native/commit/00458c94109776251678efbec10052702a41c335#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) added the `tmp` folder to the root `.gitignore` so I think I don't need to submit this file now.

**Pull request closed without merging**
