### PR TITLE
Call onclose after error in websocket connection

### LINKED ISSUE #3068: [WebSocket] WebSocket does not call the onClose handler when a connection fails
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#Connection_errors

States that when a connect fails, it calls onerror() handler and onclose(). It seems to call only the onerror().

The reason it matters is re-connect code uses the onclose() for connections that break as well as connections that fail to connect the first time.

### PR DESCRIPTION
**Pull request by dralletje**
fixes #3068

### CODE REVIEW

**Comment by ide** [comment]
Please include a test plan with your commit message. Especially with error handling it is important that it is tested and people can reproduce the steps to test.

**Comment by dralletje** [comment]
@ide Should I add a tests that attempts to connect to a bad domain, or should I explain how this is testable?

**Comment by ide** [comment]
I think manual tests are best for now, but if you wanted to follow up later with an E2E test that'd be really super too.

**Comment by dralletje** [comment]
Replaced by #3229

**Pull request closed without merging**
