### PR TITLE
[Lean Core] Removes SwipeableListView

### PR DESCRIPTION
**Pull request by ericlewis**
## Summary

As part of the effort in #23313.

## Changelog

[General] [Removed] - Remove SwipeableFlatList & SwipeableListView

## Test Plan

The relevant tests were removed.

### CODE REVIEW

**Comment by ericlewis** [comment]
I don’t believe the failing iOS test is related to this.

**Comment by TheSavior** [comment]
SwipeableFlatList is good and should live on in some repo separate from SwipeableListView. ListView and SwipeableListView should probably be moved to some other archived repo (or just deleted entirely).

**Comment by ericlewis** [comment]
Should it be part of react-native-community? Where does it belong? Prefer I reopen a PR removing only ListView?

**Comment by cpojer** [comment]
@ericlewis Could you send a PR to https://github.com/facebookarchive/react-native-deprecated-modules to add ListView and SwipeableListView, and keep SwipeableFlatList in the repo here? Then I can go ahead and migrate at FB and then land your PR :)

**Comment by ericlewis** [comment]
@cpojer sure!

**Comment by ericlewis** [comment]
@cpojer I think this is good: https://github.com/facebookarchive/react-native-deprecated-modules/pull/2

**Comment by cpojer** [comment]
Done in https://github.com/facebook/react-native/commit/14d9b2d68de77821bd6366bb2b3767f201c6cb4a.

**Pull request closed without merging**
