### PR TITLE
fix(types): cross platform autoComplete for TextInput

### PR DESCRIPTION
**Pull request by iRoachie**
## Summary:

Since v0.71 the autoComplete prop on TextInput is available on iOS ([release notes](https://reactnative.dev/blog/2023/01/12/version-071#component-specific-behavior)). However, this change is not reflected in the types.

Original types PR here - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65144 by @chwallen

## Changelog:

[GENERAL] [FIXED] - Fix autoComplete type for TextInput

## Test Plan

Setting the autoComplete prop on TextInput to `nickname`, `organization`, `organization-title`, or `url` should not result in typescript errors.

### CODE REVIEW

**Comment by javache** [comment]
Can you update the flow types too, so they're consistent? We may need to merge the iOSProps and AndroidProps version of it.

**Comment by iRoachie** [comment]
Sure thing

**Comment by iRoachie** [comment]
@javache can you verify the flow changes? Not too familiar with flow, but I ran `yarn flow` locally and it succeeded.

**Comment by javache** [comment]
Ah, you'll also need to update TextInput.js with the same changes as TextInput.flow.js (the duplication's a bit annoying, I know...)

**Pull request closed without merging**
