### PR TITLE
clean buck binary_jar warnings

### PR DESCRIPTION
**Pull request by dulmandakh**
This PR clears buck binary_jar warnings on CI.

CI is green https://circleci.com/gh/dulmandakh/react-native/458

## Test Plan

Will see no binary_jar warnings on CI

### CODE REVIEW

**Comment by hramos** [comment]
Importing without merging to verify our internal tests pass as well. I'll merge tomorrow if successful.

**Comment by dulmandakh** [comment]
@hramos did it work?

**Comment by hramos** [comment]
@dulmandakh this is currently awaiting review internally - I only had to make a few lint adjustments. Why did you close the PR? Should I abort the import process?

**Comment by dulmandakh** [comment]
@hramos accidentally deleted the branch :(. I can create a new PR tomorrow.

**Pull request closed without merging**
