### PR TITLE
onScrollAnimationEnd > onmomentumScrollEnd

### PR DESCRIPTION
**Pull request by irfaan**
As per https://github.com/facebook/react-native/issues/1410#issuecomment-105668129

### CODE REVIEW

**Comment by ide** [comment]
This is a different event. Can you add onMomentumScrollBegin/End as separate propTypes?

**Comment by mkonicek** [comment]
@brentvatne Looks like you have context - can you review this please?

**Comment by mkonicek** [comment]
Hey @irfaan! Thanks for making the pull request, but we are closing it due to inactivity (74 days with no activity) to make sure all pull requests are either being worked on or closed. If you want to get your proposed changes merged, please rebase your branch with master and send a new pull request :)

Based one the comment above:

> > This is a different event. Can you add onMomentumScrollBegin/End as separate propTypes?

**Comment by sunnylqm** [comment]
Why close this? The doc is still incorrect. @mkonicek @ide

**Pull request closed without merging**
