### PR TITLE
Bump NDK version to 23.0.7599858 (LTS)

### PR DESCRIPTION
**Pull request by svbutko**
## Summary

Bump NKD version to 23.0.7599858 (LTS) which:
- Includes Android 12 APIs
- Updates LLVM

And has very short list of known bugs

## Changelog

[Android] [Changed] - Bump NKD version to 23.0.7599858 (LTS)

### CODE REVIEW

**Comment by svbutko** [comment]
It's also slightly reduces size of apps which is always great

**Comment by cortinico** [comment]
I believe we're fine with bumping it. Yet we were looking into removing an explicit version entirely and let AGP pick the correct NDK version. Is it something you'd like to look into?

**Comment by svbutko** [comment]
> I believe we're fine with bumping it. Yet we were looking into removing an explicit version entirely and let AGP pick the correct NDK version. Is it something you'd like to look into?

Would be great

**Comment by svbutko** [comment]
```yml
      - ANDROID_NDK: "C:\\Android\\android-sdk\\ndk\\20.1.5948944"
      - NDK_VERSION: 23.0.7599858
```
I also changed the version in circle CI config, but didn't set the version path, should be changed probably

**Comment by cortinico** [comment]
Turns out we can't merge this as it is. We would first need to update the NDK version in the dockerfile here https://github.com/react-native-community/docker-android/blob/master/Dockerfile#L12 and update this PR to use the updated Docker image.

**Comment by cortinico** [comment]
Bumping back this one. Should we stay on the default NDK version instead? https://developer.android.com/studio/releases/gradle-plugin?buildsystem=ndk-build

**Comment by kelset** [comment]
cc'ing @dulmandakh

**Comment by dulmandakh** [comment]
IIRC, Buck doesn't support NDK 23 yet. @cortinico

**Comment by cortinico** [comment]
I'm trying to understand if there is a need for this specific version of the NDK or we're fine living the with the default one provided by the corresponding AGP version

**Comment by cortinico** [comment]
I'm leaning towards closing this PR in favor of this other: 
- https://github.com/facebook/react-native/pull/32848

I would like to hear your opinion about it.
Ideally we should leverage the NDK version that is installed side-by-side with AGP instead of specifying a version explicitly.

**Comment by cortinico** [comment]
Closing this as #32848 got merged. Happy to revisit if the approach doesn't work 👍

**Pull request closed without merging**
