### PR TITLE
ignore npm-debug.log

### PR DESCRIPTION
**Pull request by eddiemonge**
remove the mistakenly added file and ignore it in the future

### CODE REVIEW

**Comment by cpojer** [comment]
I'm waiting for some internal diffs to get stamped that should get rid of the file first, otherwise it is just getting synced out again.

**Comment by eddiemonge** [comment]
this line should keep it from happening: https://github.com/facebook/react-native/pull/2733/files#diff-a084b794bc0759e7a6b77810e01874f2R38

**Comment by eddiemonge** [comment]
and you might want to consider adding that to your personal `.gitignore_global` file

**Comment by cpojer** [comment]
Can you change this PR to only include the change to the .gitignore file? I'll land the internal diff with the removal of the file and then merge your PR.

**Comment by eddiemonge** [comment]
udpated

**Pull request merged**
