### PR TITLE
[Android]Flexible size and update properties implementation

### PR DESCRIPTION
**Pull request by littlesome**
Add android's missing RootView flexibleSize and update appProperties implementation, and UIExplorer example.

wechatimg9

Not sure about function and class's naming, feel free to leave me a comment if you have better suggestions :)

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @javache and @emilsjolander to be potential reviewers.

**Comment by hramos** [comment]
The description for this PR is too short given how much code is being added. Can you elaborate a bit more on the justification for why this is needed?

**Comment by ericvicenti** [comment]
@mkonicek, maybe you can do the review on this one? It looks pretty useful and would be nice to get feature parity with iOS

**Comment by sunnylqm** [comment]
Why was this pr closed?

**Pull request closed without merging**
