### PR TITLE
Include guide for BreakingChanges page

### PR DESCRIPTION
**Pull request by grabbou**
We now keep track of breaking changes - include required steps to sync them up with the release so they are relevant.

CC: @mkonicek

### CODE REVIEW

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Comment by grabbou** [comment]
Haha, @bestander I saw you using it and it actually works! Note: I didn't want to do it, but found `md` change a good place to test that out.

**Comment by mkonicek** [comment]
Thanks!

Wow "shipit-ninja" is good!

**Comment by grabbou** [comment]
@mkonicek got any ideas what's wrong with that? :)

**Comment by mkonicek** [comment]
Not sure, looks like when using shipit-ninja the bot doesn't comment with a link so I don't see the internal Phabricator diff and test failures. Very likely it's just flakiness or a merge conflict. Let's try:

@facebook-github-bot shipit

**Comment by lacker** [comment]
I think something was just borked on CI - I rebased so that it will rerun CI, once that works I'll land this.

**Comment by lacker** [comment]
It looks like this has actually gotten merged, but in something separate that isn't tied to this PR, because it got created separately by our internal system. Notice the diff now says 0 files changed. Probably the ninja part of the shipit got things confused. I'm going to close this because it looks like it's in, thanks!

**Pull request closed without merging**
