### PR TITLE
Fix Xcode Analyser warnings and deprecations

### PR DESCRIPTION
**Pull request by hansemannn**
Hey guys,

this PR basically resolves all common deprecation- and Xcode Analyser-warnings. Some notes: 
- Some of them have been surrounded by the `-Wdeprecated-declarations` flag, since there is no replacement for the methods available. So I followed the the existing way like done in the `RCTModuleData` for those cases
- I added the `__unused` flag to mute the unused-warnings in certain parameter lists. This was also done in some other classes as well, so this one unifies the way for all current API's
- I migrated some methods that have been deprecated (e.g. `UIActivityViewController`'s `completionHandler` method)

One note: I left the `NSStringArray` deprecation for now, since the migration should be done in an own PR, since it effects common type conversions across the project.

Thanks! 🚀

### CODE REVIEW

**Comment by hansemannn** [comment]
2/4 travis builds fail due to unrelated errors. May need to re-trigger those.

**Comment by lacker** [comment]
I just fixed a comment typo which will also trigger the CI to re-run. This looks good to me so if/when CI gives the thumbs-up I will land it.

**Comment by hansemannn** [comment]
It keeps failing. Unfortunately, I don't have travis access to this project so you might need to retrigger it yourself.

**Comment by lacker** [comment]
Ah, dang it. So I went on vacation a couple days after your last comment, lost track of this PR, and now there are conflicts. Would you mind resolving those @hansemannn ?

**Comment by shergin** [comment]
@hansemannn Could you resolve conflicts?

**Comment by shergin** [comment]
@hansemannn Sorry for late reply. 😭 Could you please rebase the diff on lastest master and resolve conflicts?

**Pull request closed without merging**
