### PR TITLE
BREAKING: Android - ReactNativeHost getUseDeveloperSupport to public

### PR DESCRIPTION
**Pull request by jpshelley**
## Overview

Currently React Native is opinionated in that the easiest approach is to extend ReactActivity. However to more easily allow integrating with existing application, we should allow some of the methods in ReactNativeHost to be public, and this is a very good first step.
* There is no harm in making this public from what I can tell.
* This allows `ReactNativeHost` to be more easily used outside of the `ReactActivity` and `ReactActivityDelegate` ecosystem. (A `ReactFragment` would be a good example)

## Addresses / Changes
_No issues found_

**Test plan (required)**

* Run any sample app and verify it still works.

Make sure tests pass on both Travis and Circle CI.

### CODE REVIEW

**Comment by jpshelley** [comment]
Looks like Circle failed, I can't tell how to fix the failure though.

**Comment by mkonicek** [comment]
As expected, we have some closed-source code that extends the application that we'll need to update.

Error from internal CI:

> getUseDeveloperSupport() in com.facebook.someapp.SomeClass cannot override getUseDeveloperSupport()

**Comment by mkonicek** [comment]
@jpshelley Is this change going to break the build for anyone overriding this method as `protected boolean getUseDeveloperSupport()` in their apps?

**Comment by jpshelley** [comment]
> How common is to override this method?

According to the react native documentation, it will be very common for others to override this.
* https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Examples/Movies/android/app/src/main/java/com/facebook/react/movies/MoviesApplication.java#L42
* https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Examples/TicTacToe/android/app/src/main/java/com/facebook/react/tictactoe/TicTacToeApplication.java#L42
* https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Examples/UIExplorer/android/app/src/main/java/com/facebook/react/uiapp/UIExplorerApplication.java#L42

Whats strange is UIExplorer (3rd link) already has it as public.

> Will this break the build for a lot of people?

I would _assume_ so. I didn't try building the example apps without changing the modifier yet. I'm trying right now but having issues with my ndk build again. I'll edit this comment once I get it to work or not work.

**Comment by jpshelley** [comment]
@mkonicek Is this something we can move forward on still? Like I said, some applications use a single activity multiple fragment approach and this would allow for creating a React Fragment.

**Comment by AaaChiuuu** [comment]
I'm attempting to fix the breakage internally right now; we'll see how it goes.

**Comment by jpshelley** [comment]
@AaaChiuuu it looks like the PR was accepted, however it didn't pick up all the changes. Was this intentional? I fear the example applications and any new ones started via the CLI won't build correctly.

**Comment by AaaChiuuu** [comment]
Crap, wanna send a new PR?

**Comment by jpshelley** [comment]
@AaaChiuuu I can, can you not take the commits from this PR somehow?

**Comment by AaaChiuuu** [comment]
can't re-import the same PR

**Pull request closed without merging**
