### PR TITLE
Documentation fix: dx vs. x0

### PR DESCRIPTION
**Pull request by scarlac**
> What existing problem does the pull request solve?

Purely a documentation/example error. Was misled/wasted time debugging because of this issue.

Description:
`dx`/`dy` are zero in onPanResponderGrant, not `x0`/`y0`. `x0`/`y0` will be the coordinates relative to the granted element, which are rarely zero.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @sebmarkbage and @sahrens to be potential reviewers.

**Comment by hramos** [comment]
LGTM. Can you rebase first?

**Comment by scarlac** [comment]
@hramos I auto-merged via GitHub. Is this good enough?

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
