### PR TITLE
Add support for reverse flex directions on Android and iOS

### PR DESCRIPTION
**Pull request by feichngr**
This PR adds support for both 'row-reverse' and 'column-reverse' for Android and iOS and is based on the changes in #6683 that looked like it's all but abandoned. 
It also adds examples for the new directions to the "Layout - Flexbox" section of UIExplorer as well as some rad new colors to the section to make the difference between "row-reverse" and "flex-end" more apparent.

**Test plan (required)**
Tested inside of UIExplorer

Android
screen shot 2016-06-05 at 7 42 14 pm

iOS
screen shot 2016-06-05 at 7 41 35 pm

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @rigdern to be potential reviewers.

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Something went wrong when importing this pull request. Please cc someone from the team at fb to help with importing this.

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/792847947518719/int_phab) to review.

**Pull request closed without merging**
