### PR TITLE
refactor: convert ReactPropForShadowNodeSetterTest to kotlin

### PR DESCRIPTION
**Pull request by moskalakamil**
## Summary:
This PR convert `ReactPropForShadowNodeSetterTest` to kotlin as part of #38825 

## Changelog:

[INTERNAL] [CHANGED] - Convert ReactPropForShadowNodeSetterTest to kotlin

## Test Plan:
```
./gradlew :packages:react-native:ReactAndroid:test
```

### CODE REVIEW

**Comment by cortinico** [comment]
Please see this PR where I fixed the tests. You should ideally rebase your Koltin convertion on top of it https://github.com/facebook/react-native/pull/41788

**Comment by moskalakamil** [comment]
> Please see this PR where I fixed the tests. You should ideally rebase your Koltin convertion on top of it #41788

hey @cortinico, I cherry-picked your commit locally and it seems to work!
image
I will wait once it land and I'll rebase on top of the main

**Comment by cortinico** [comment]
@moskalakamil please rebase and ping me when you're done. The CI should also be green before we can merge this

**Comment by moskalakamil** [comment]
@cortinico `NetworkingModuleTest` fails on main, I would be grateful for quick fix

**Comment by cortinico** [comment]
> @cortinico `NetworkingModuleTest` fails on main, I would be grateful for quick fix

Yes we're aware of it. @rshest is working on a fix that will be out soon.

**Comment by moskalakamil** [comment]
Hey, @cortinico I'm done

**Review by cortinico — APPROVED** [review]

**Comment by moskalakamil** [comment]
@cortinico I forgot to remove java test after rebase, now everything is fine

**Pull request closed without merging**
