### PR TITLE
Ui web view caching

### PR DESCRIPTION
**Pull request by jaygarcia**
This pull request is for issue https://github.com/facebook/react-native/issues/1344.

Question: Where are the tests for the native library and Related JavaScript? Is there documentation for unit test in general for contributions?

/cc @ide @brentvatne

### CODE REVIEW

**Comment by jaygarcia** [comment]
i'm confused.  The test failed because of the following?

```
Flow server launched for /private/tmp/react-native-Ya5nW9AK/EndToEndTest
.flowconfig:46 Wrong version of Flow. The config specifies version 0.14.0 but this is version 0.15.0
Could not start Flow server!
```

**Comment by alexisvincent** [comment]
What is the status on this?

**Comment by facebook-github-bot-6** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by geirman** [comment]
bump @nicklockwood @brentvatne @ide 

this pr is probably feeling a bit neglected

**Comment by nicklockwood** [comment]
Now that WebView supports a source object, it would probably make sense to make the cache policy part of that object rather than a separate property.

**Comment by geirman** [comment]
@nicklockwood does that mean we cant ship this unless and until @jaygarcia makes that change?

**Comment by nicklockwood** [comment]
@geirman it's going to need some significant work to rebase this anyway before it can ship, because the setURL method that @jaygarcia modified to implement the caching no longer exists.

**Comment by geirman** [comment]
@facebook-github-bot label  Needs Response from Author

@jaygarcia can you please weigh in?

**Comment by stereodenis** [comment]
@jaygarcia any progress on it?

**Comment by jaygarcia** [comment]
Holy moly guys.  I apologize but the messages got lost in the flood of emails from this repo.  

I will review things when I get to the office tomorrow and report back accordingly.

**Comment by jaygarcia** [comment]
There were issues with this PR & the repo i originally forked, so i'm going to recreate the PR: https://github.com/facebook/react-native/pull/8578

**Comment by aqnaruto** [comment]
加油 @jaygarcia ,this  is a very hepeful pr

**Pull request closed without merging**
