### PR TITLE
Remove Deprecated NavigationExperimental

### PR DESCRIPTION
**Pull request by ericvicenti**
Now that there are a number of good navigation solutions provided by the community, we are ready to remove NavigationExperimental from the RN core. The latest navigation doc explains the available options pretty well: http://facebook.github.io/react-native/docs/navigation.html . We should also add a mention to Airbnb's new native-navigation.

For anybody who continues to rely on it, it is recommended to migrate to React Navigation, which will be maintained over the long-term. For those who cannot migrate yet, it is possible to copy this code into your app.

### CODE REVIEW

**Comment by ptomasroos** [comment]
Good bye dear old friend, you served well.

**Comment by nihgwu** [comment]
Will this be shipped to 0.44? I'm using custom **Navigator** built on it, and it works really well, I've tried to use **react-navigation** but it's really frustrating, to be honest, it's still in a quite early stage, leaving so many issues unresolved( besides some really severe bugs ) and PRs pending there for weeks. IMO we should keep that in core until **react-navigation** reaches to 1.0.0-stable.

**Comment by ptomasroos** [comment]
You can use the transitioner from react navigation or copy the files
locally.

**Comment by nihgwu** [comment]
Then why not just keep them there until the others are ready?
**react-navigation** is still on the way to 1.0.0-stable
**react-navigation** is in active development to release 2.0.0
**native-navigation** just unveils itself a week ago
**react-native-router-flux** is using a very early version of NE so don't support native driver, so it's not on my list

**Comment by ptomasroos** [comment]
Facebook doesn't use it and don't wanna maintain it. Simple as that I
believe

**Comment by janicduplessis** [comment]
Someone could publish it as an npm package also.

**Comment by ptomasroos** [comment]
@janicduplessis thats what react-native-router-flux did

**Comment by farwayer** [comment]
What about adding note to *Breaking changes* section of 0.44 release?

**Pull request closed without merging**
