### PR TITLE
Added AnimatedValueXY.removeAllListeners

### PR DESCRIPTION
**Pull request by scarlac**
> Explain the **motivation** for making this change. What existing problem does the pull request solve?

`AnimatedValueX` has `removeAllListeners()` which is a convenient way to do cleanup when components unmount, but `AnimatedValueXY` was missing a similar method which doesn't really make sense. This change makes the two classes more similar, less confusing and more convenient.

### CODE REVIEW

**Comment by janicduplessis** [comment]
Thanks, seems useful and adds consistency.

@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by scarlac** [comment]
@janicduplessis is there an issue with the PR? I can't tell if it's been merged correctly. Let me know if there's something I need to do :)

**Comment by janicduplessis** [comment]
I think there were issues with fb internal CI when I shipped it, we'll see if it works now . PR will get closed with your commit if it goes through.

**Pull request closed without merging**
