### PR TITLE
Make "react-native start" work on Windows

### PR DESCRIPTION
**Pull request by BerndWessels**
This is necessary to run `react-native start` on Windows.

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks for doing this!

This way we lose the [`REACT_PACKAGER_LOG`](https://github.com/facebook/react-native/blob/master/packager/packager.sh) on Mac OS and Linux, @martinbigio is it used for anything?

I think a safer way would be to check for OS and only do this on Windows.

nit: Please keep the indentation.

**Comment by mkonicek** [comment]
@BerndWessels I committed your change in https://github.com/facebook/react-native/commit/a5463c4c1021009be6958c3821605e8b803edc45, thanks for the fix!

If you want you could make the `newWindow` branch work on Windows too: `react-native run-android` calls the function with `newWindow` set to true. On Mac and Linux this will open a new terminal Window and start the packager in it. On Windows it's currently a no-op so you have to run `react-native start` manually.

**Comment by yeso126** [comment]
When I run react-native start I get a watcher took too long to load error, any workaround?

**Comment by mkonicek** [comment]
@yeso126 What version of watchman are you using? Can you tweak the watcher timeout at the line where it throws the error? The file can be found in `node_modules`. What sometimes fixes this on Mac is simply running `watchman --version`.

**Comment by yeso126** [comment]
I'm trying to run react-native start on windows, watchman is not supported

**Comment by mkonicek** [comment]
OK, looks like we're using [sane](https://www.npmjs.com/package/sane) to do file watching. Not sure what causes the watcher to time out on Windows. Can you try increasing the timeout in this file (under your `node_modules/react-native`?

https://github.com/facebook/react-native/blob/master/packager/react-packager/src/FileWatcher/index.js#L17

**Pull request closed without merging**
