### PR TITLE
enable proguard in release mode

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
This is default behavior  in android project. With progurad the code runs fast, the apk is smaller.
## Test Plan
pass all current ci.
## Release Notes
[Android] [Feature] - enable proguard in release mode

### CODE REVIEW

**Comment by radeno** [comment]
@gengjiawen i like the idea about enabling it but is it safe for most of community modules ?

**Comment by radeno** [comment]
I see. So every module needs to set it by own in `build.gradle`.

Maybe there could be wider propagation that is new default option and most as possible community modules should support it.

**Comment by gengjiawen** [comment]
Yes, I agree we need add it to release note. But not every module need to config proguard rules.

**Comment by dulmandakh** [comment]
I think that it might not be necessary and leave it to developer. Also I assume that proguard will be deprecated in favor of R8.

**Comment by gengjiawen** [comment]
R8 still need time come close to production. And even with R8 the dsl may not be change.

**Comment by hramos** [comment]
Can we instead recommend people enable this themselves as part of the docs?

**Comment by gengjiawen** [comment]
I still think this should be default since minify in production is serious issue.

**Comment by gengjiawen** [comment]
I think we should keep up with android default behavior. Let's keep it open for a while.

**Comment by cpojer** [comment]
I agree with @hramos and @dulmandakh that we should add this to the documentation for now and ask users to do this manually. We should ensure reliability and correctness over size and speed, at least for now.

**Pull request closed without merging**
