### PR TITLE
fix: flatList onEndReached call prevent when array empty

### PR DESCRIPTION
**Pull request by zaferatli**
## Summary:

Fix FlatList prevent call onEndReact when array is empty. https://github.com/facebook/react-native/issues/38090

## Changelog:

[GENERAL] [FIXED] - I add empty array check

## Test Plan:

this code shouldn't call onEndReact:

`
return (
<SafeAreaView style={{flex:1}}>
      <FlatList
        data={[]}
        renderItem={() => {
          return (
            <View
              style={{
                height: 100,
                backgroundColor: 'red',
                borderRadius: 20,
                marginBottom: 20,
              }}>
              <CustomText>welcome</CustomText>
            </View>
          );
        }}
        ListEmptyComponent={() => {
          return (
            <View>
            <Text>Empty List</Text>
            </View>
          );
        }}
        onEndReached={() => {
          console.log('onEndReached');
        }}
      />
  </SafeAreaView>
)
`

### CODE REVIEW

**Comment by ryancat** [comment]
When the data list is empty, shouldn't `onEndReached` be called as we are actually reached the end of the list? Are you trying to fix any issues? If so, please share the use cases and how we can repro it. 

This change also lacks test cases associated with it. It would be nice to add a RNTester.

**Comment by zaferatli** [comment]
i saw this issue: https://github.com/facebook/react-native/issues/38090 and i think when array is empty its shouldn't call onEndReached and i create pr.

I am not sure is it necessary or not. Its seems to me easy to fix and i create pr.

We may close pr, i am not sure. If you say pr make sense we can merge when i add test then i will add.

**Comment by zaferatli** [comment]
when think again, its not correct flow. Just think you make lazy loading api call in onEndReached but when array is empty its should not be work because you didn't show anything. 

Also when look issue and https://github.com/bitpay/bitpay-app/pull/932 this pr i think its necessary.

**Comment by Aryk** [comment]
@ryancat that would make sense if you designed the paradigm around: 

1. Load in FlatList with empty results set because you haven't made the first query yet.
2. FlatList triggers onEndReached to trigger initial results

I've __never__ seen anyone structure page loading this way as you now rely on components to mount and fire off the initial request before actually interacts with the list. This coupling doesn't make sense to me. You should be controlling when you want to grab the initial data.  

This is one of many reasons it should not be the default behavior.

What if you preloaded the data and it just happened to be an empty array? You already made a server call. Under this paradigm, we will now make _another_ call just to tell us what we already know...that the list is already empty...

**Pull request closed without merging**
