### PR TITLE
Fix maxLength of multibyte characters for TextInput

### PR DESCRIPTION
**Pull request by liuyaodong**
Fix issue [#2343](https://github.com/facebook/react-native/issues/2343).  
- Combining character sequences like ў and emoji are count as one symbol.
- Marked text are not truncate because they represent text that are not confirmed yet, and the confirmed result could be shorter than the marked text. For example, the picture shows a Chinese strokes keyboard, where 3 marked text(strokes) could be confirmed as one character "要", as shown on the candidate bar.

### CODE REVIEW

**Comment by liuyaodong** [comment]
@milend `rangeOfComposedCharacterSequenceAtIndex:` returns only the range of one composed character sequence symbol.  We cannot deduce how many symbols have been input from that. Though inefficient, we have to count the whole text.  [This post](https://www.objc.io/issues/9-strings/unicode/) gives  a very good explanation.

**Comment by liuyaodong** [comment]
@milend I have considered extract the duplicate code and make them helper methods. However, I don't know where to place them after scanning the code organization of the project. These methods are very specific and maybe only used by `RCTTextView` and `RCTTextField`. Maybe a category is more appropriate.

**Comment by nicklockwood** [comment]
@liuyaodong don't worry too much about duplicate code between RCTTextView and RCTTextField - we'll probbably merge these two classes eventually as they share a lot of functionality, but that's not your problem.

By "static function", @milend just meant that for methods that don't access any ivars, we prefer you write them as static C functions instead of Objective-C methods, i.e.

    - (NSUInteger)_apparentLengthOfText:(NSString *)text

Should be

    static NSUInteger RCTApparentLengthOfText(NSString *text)

These are *truly* private, and more efficient both in terms of performance and generated code size.

**Comment by milend** [comment]
You can use the following implementation which loops like I suggested, rather than using the block-based NSString method.

```objc
static NSUInteger RCTApparentLengthOfText(NSString *text) {
  NSUInteger length = 0;
  for (NSUInteger i = 0, textLength = text.length; i < textLength; length++) {
    NSRange range = [text rangeOfComposedCharacterSequenceAtIndex:i];
    i = NSMaxRange(range);
  }

  return length;
}
```

**Comment by liuyaodong** [comment]
@nicklockwood @milend great thanks for your suggestion, I'll refactor them.

**Comment by mkonicek** [comment]
@liuyaodong This pull request is quite large and I think it will be quite hard for anyone to review it any time soon given how overloaded the team is. Is there any way to split this into several independent PRs to make it easier to review and merge?

**Comment by facebook-github-bot-8** [comment]
@tadeuzagallo would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by liuyaodong** [comment]
@mkonicek I think it's about two issues: 1) how to count multibyte characters. 2) work around to count text length when marked text is not confirmed. I'll try splitting them and fire new pull requests.

**Pull request closed without merging**
