### PR TITLE
Added Emergency Kittens to showcase

### PR DESCRIPTION
**Pull request by matt-casey**
Added Emergency Kittens iOS app to the showcase list. A simple, fun app that lets you swipe through cat gifs, save your favorites to your phone, and share the best ones with your friends.

### CODE REVIEW

**Comment by chirag04** [comment]
@matt-casey can you keep the list alphabetically sorted.

**Comment by matt-casey** [comment]
@chirag04 no problem, I've alphabetized the list

**Comment by chirag04** [comment]
@facebook-github-bot shipit

**Comment by chirag04** [comment]
@matt-casey thanks :+1:

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@matt-casey The PR has a merge conflict now, sorry about that. Can you rebase?

**Comment by mkonicek** [comment]
Adding the 'Needs revision' label because this needs a rebase.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Fails with a merge conflict. Can you rebase please?

**Comment by facebook-github-bot-8** [comment]
@matt-casey do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by lacker** [comment]
Hey, I'm really sorry for the churn, but we are changing up how the showcase works, and just focusing on apps that have some media presence or technical blog posts / other content. So I appreciate the spirit behind this pull request but I think we should close it.

**Pull request closed without merging**
