### PR TITLE
Documents StyleSheet.flatten()

### PR DESCRIPTION
**Pull request by prometheansacrifice**
Indicates the purpose and an alternative use for the method too.

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks! This is super useful.

Do you mind adding a big warning at the top that this is not a recommended method and is an escape hatch. Style objects being opaque is required if we want to do optimizations down the line or work on the web by outputting classes, if you use this method, you are going to break this assumption.

**Comment by prometheansacrifice** [comment]
@vjeux Do you think the following is valid use case?

```
// Child
render() {
  const overridingViewStyles = StyleSheet.flatten(this.props.style).viewStyles; //Ignore the fact that I could have cached it somewhere else instead of the render method. Bear with it for brevity.
  return <View style={[styles.defaultStyles, overridingViewStyles]} />
}
```

```
//Parent
render() {
  return <Child style={styles.childStyles} />
}
```

Basically, individual components nested within the child component, obtain their styles from `style` property. This would be possible only if the child component had access to the style objects passed by the parent.

**Comment by vjeux** [comment]
You can do more simply:

```javascript
// Child
render() {
  return <View style={[styles.defaultStyles, this.props.style]} />
}

**Comment by vjeux** [comment]
You don't need to flatten it at every step of the way, and really, you don't want to flatten it at every step of the way which is actually pretty expensive. You just want to forward it all the way down.

If we can even get it unflattened all the way to React, then we can build good dev tools where we can display how the styles were combined and overridden like we have on web.

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by prometheansacrifice** [comment]
@vjeux The issue with `style={[styles.defaultStyles, this.props.style]}` was that sometimes you have styles that apply to different children components (and specifically to those alone)
Say for example a child is a simple `Text` nested inside a `View`. When I pass styles to Child like this,

```
<Child style={styles.childStyles} />
```
both `View` and `Text` obtain all the styles, which can cause warnings. There needs to be a way to separate out the style passed on to `Child` to its children `Text` and `View`

**Comment by spicyj** [comment]
It is traditional to pass them as separate props.

```
<Component
  style={....}
  childStyle={...} />
```

Then you can just use `props.childStyle`.

**Comment by vjeux** [comment]
I tried to document this use case here: http://facebook.github.io/react-native/docs/style.html#content

**Comment by prometheansacrifice** [comment]
Thank you for your inputs @spicyj @vjeux

**Comment by prometheansacrifice** [comment]
@vjeux @spicyj  I noticed that `style.length` is not cached in the for loop ([here](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/flattenStyle.js#L37)). Replace it with `for (var i = 0, ii = style.length; i < ii; ++i) {`?

**Comment by satya164** [comment]
@prometheansacrifice Why not `l` instead of `ii`?

**Comment by prometheansacrifice** [comment]
@satya164 Sure. Open a new PR?

**Comment by satya164** [comment]
@prometheansacrifice Why not :)

**Comment by prometheansacrifice** [comment]
@satya164 Did so [here](https://github.com/facebook/react-native/pull/6671) :)

**Pull request closed without merging**
