### PR TITLE
[Animated API Example] : - added combining animted values example to the animated api example list

### PR DESCRIPTION
**Pull request by Biki-das**
## Summary:

Added an example to add ```combining``` values with the animated API

## Changelog:

[General] [Added] - Add examples for Combining Animated Values with the Animated API

## Test Plan:

https://github.com/facebook/react-native/assets/72331432/c4a0c1e2-df9d-4e73-8602-e4550a22b8dc

https://github.com/facebook/react-native/assets/72331432/d2f1196e-68b0-49d4-8d3d-2c53ee30652b

### CODE REVIEW

**Comment by Biki-das** [comment]
@huntie , would love to know your thoughts!

**Comment by Biki-das** [comment]
cc @rubennorte

**Comment by Biki-das** [comment]
@hoxyq can we get this merged?

**Review by hoxyq — COMMENTED** [review]
Hey @Biki-das, thanks for this contribution!

I think it would be nice also to add 2 inputs for these animated values `a`, `b`.
Also cc @cortinico @cipolleschi on L&A aspect of this.

**Comment by Biki-das** [comment]
> Hey @Biki-das, thanks for this contribution!
> 
> I think it would be nice also to add 2 inputs for these animated values `a`, `b`. Also cc @cortinico @cipolleschi on L&A aspect of this.

@hoxyq could you clarify a bit on this more, seems unclear what you mean by adding two inputs!

**Comment by hoxyq** [comment]
> > Hey @Biki-das, thanks for this contribution!
> > I think it would be nice also to add 2 inputs for these animated values `a`, `b`. Also cc @cortinico @cipolleschi on L&A aspect of this.
> 
> @hoxyq could you clarify a bit on this more, seems unclear what you mean by adding two inputs! do you want me to put two inputs which take the value for a and b, as required and then does the respective animation api method calculation!

Instead of pre-defined values of `a` and `b`:
https://github.com/facebook/react-native/blob/ee58dd69b5ce968281ffce8fe0e74b32dc014141/packages/rn-tester/js/examples/Animated/CombineExample.js#L26-L27

Can user actually use inputs on the screen to set them? And then use operators.

**Comment by Biki-das** [comment]
https://github.com/facebook/react-native/assets/72331432/fb85ab23-0ae4-4ba9-8909-5c6b6a2b59a8

@hoxyq let me know if this looks fine to you, now it renders two input boxes for the animted values to be experimented with

**Pull request closed without merging**
