### PR TITLE
Update node-haste dependency to 2.12.0

### PR DESCRIPTION
**Pull request by rozele**
Update to node-haste 2.12.0 to support pass through configuration of supported platforms.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @davidaurelio to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
@rozele updated the pull request.

**Comment by mkonicek** [comment]
@rozele Merging manually as this needs an update to our internal node modules cache.

@facebook-github-bot import

**Comment by mkonicek** [comment]
Will have to import this one manually - need to update our internal node modules cache.

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
(clicked wrong button :))

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/844262359039156/int_phab) to review.

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/844262359039156/int_phab) to review.

**Pull request closed without merging**
