### PR TITLE
fix(eslint-config): switch to new babel parser

### PR DESCRIPTION
**Pull request by Kerumen**
## Summary

[`babel-eslint`](https://github.com/babel/babel-eslint) is deprecated now. We should use the new Babel parser.

## Changelog

[General] [Fixed] - Use new Babel parser instead of deprecated one

## Test Plan

Ensure lint is working as expected.

### CODE REVIEW

**Comment by cortinico** [comment]
Thanks for sending this over @Kerumen 

This is sadly not sufficient. Please check another other similar attempt here:
- #33949 

We need to update all the references of `babel-eslint` in the codebase

**Comment by Kerumen** [comment]
@cortinico I don't see a lot of reference. Maybe I should also update the test [here](https://github.com/facebook/react-native/blob/91320e7ce9375981c60c58acf4d333975661b6e8/packages/eslint-plugin-react-native-community/__tests__/eslint-tester.js#L15)?

**Comment by cortinico** [comment]
> @cortinico I don't see a lot of reference. Maybe I should also update the test [here](https://github.com/facebook/react-native/blob/91320e7ce9375981c60c58acf4d333975661b6e8/packages/eslint-plugin-react-native-community/__tests__/eslint-tester.js#L15)?

A quick grep returns this:

```
rg "babel-eslint"
CHANGELOG.md
2835:- Upgrade babel-eslint to 9.0.0 ([44dc283bcd](https://github.com/facebook/react-native/commit/44dc283bcd0a75826d9be86cdc727e32d5697ef2) by [@rafeca](https://github.com/rafeca))
2966:- Upgrade babel-eslint to v9.0.0-beta.2 with better support for Flow ([abf1188de2](https://github.com/facebook/react-native/commit/abf1188de225e4b7d36ecbad316af92ca29c85c2) by [@rubennorte](https://github.com/rubennorte))

yarn.lock
1780:babel-eslint@^10.1.0:
1782:  resolved "https://registry.yarnpkg.com/babel-eslint/-/babel-eslint-10.1.0.tgz#6968e568a910b78fb3779cdd8b6ac2f479943232"

repo-config/package.json
19:    "babel-eslint": "^10.1.0",

packages/eslint-config-react-native-community/yarn.lock
403:babel-eslint@^10.1.0:
405:  resolved "https://registry.yarnpkg.com/babel-eslint/-/babel-eslint-10.1.0.tgz#6968e568a910b78fb3779cdd8b6ac2f479943232"

packages/eslint-config-react-native-community/package.json
17:    "babel-eslint": "^10.1.0",

packages/eslint-config-react-native-community/index.js
39:      parser: 'babel-eslint',

packages/eslint-plugin-react-native-community/__tests__/eslint-tester.js
15:  parser: require.resolve('babel-eslint'),

packages/eslint-plugin-specs/__tests__/eslint-tester.js
15:  parser: require.resolve('babel-eslint'),
```

**Comment by cortinico** [comment]
> Should I update them? I don't know what `repo-config` is doing.

Yeah the should all be updated.

`repo-config` is the yarn workspace for the whole repository

**Comment by Kerumen** [comment]
@cortinico Done! ✅

**Comment by Kerumen** [comment]
The CI is green now! 🟢 

Here is what I did:
- I added `requireConfigFile: false` as it's needed since Babel v11
- I added `@babel/preset-flow` for `eslint-plugin-specs` as it tests Flow code with some Flow syntax
- I added missing `@babel/core` in `eslint-config`

**Comment by cortinico** [comment]
> The CI is green now! 🟢
> 
> Here is what I did:
> 
> * I added `requireConfigFile: false` as it's needed since Babel v11
> * I added `@babel/preset-flow` for `eslint-plugin-specs` as it tests Flow code with some Flow syntax
> * I added missing `@babel/core` in `eslint-config`

Awesome stuff! We'll re-import this and we should be fine merging it 👍

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
> Any progress here? 🚀

Sadly not. I've been trying to merge this PR internally, but our setup related to babel is quite intricate and it's more challenging than expected.

**Comment by cortinico** [comment]
Kudos to @jacdebug for unblocking this 👍

**Pull request closed without merging**
