### PR TITLE
small hack to have circle.yml in gh-pages generated branch

### PR DESCRIPTION
**Pull request by bestander**
Ideally we would generate/prepare circle.yml specifically for gh-pages branch but for now this one is good enough.
Having this file in circle.yml will order circleCI to ignore the branch

### CODE REVIEW

**Comment by spicyj** [comment]
Okay.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
ups, this code is only in OSS

**Pull request merged**
