### PR TITLE
[Android] Added docs about generating a signed APK

### PR DESCRIPTION
**Pull request by satya164**

### CODE REVIEW

**Comment by satya164** [comment]
cc @mkonicek

**Comment by satya164** [comment]
cc @mkonicek

**Comment by mkonicek** [comment]
Nice! :+1: 

Thanks a lot Satyajit and sorry about the delay. We have a team meeting at fb soon to figure out how to stay on top of the pull requests and github issues better.

**Comment by satya164** [comment]
@mkonicek Great :)

The number of issues and pull requests is really overwhelming.

**Pull request merged**
