### PR TITLE
Use contentOffset to set the starting scroll offset in ReactHorizontalScrollView

### PR DESCRIPTION
**Pull request by xqwzts**
Implements `contentOffset` for horizontal scrollviews in Android [already implemented for ios]. This will allow specifying the position the `ScrollView` should start at.

A common use case is having a horizontal `ListView` with pagingEnabled, and having it open to a specified page, without having to wait for it to load and then call `scrollTo`.

Also see #6849 

### Usage:
Add `contentOffset={{ x: someInitialXValue, y: someInitialYValue }}` to your `ScrollView` props.

### Example:

```javascript

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ListView,
  Dimensions,
} from 'react-native';


export default class offsettest extends Component {
  constructor() {
    super();
    const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
    const { width } = Dimensions.get('window');
    this.state = {
      dataSource: ds.cloneWithRows(['row 1', 'row 2', 'row 3', 'row 4', 'row 5']),
      initialPage: width * 3,
    };
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Android Horizontal ListView ContentOffset Example
        </Text>
        <ListView
          dataSource={this.state.dataSource}
          renderRow={(rowData) => (
            <View style={{flex: 1, backgroundColor: 'red', width: Dimensions.get('window').width, justifyContent: 'center', alignItems: 'center'}}>
              <Text style={{color: 'white'}}>{rowData}</Text>
            </View>
          )}
          contentOffset={{ x: this.state.initialPage, y: 0 }}
          horizontal={true}
          pageSize={1}
          pagingEnabled={true}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 16,
    textAlign: 'center',
    margin: 10,
  },
});

AppRegistry.registerComponent('offsettest', () => offsettest);
```

### CODE REVIEW

**Comment by xqwzts** [comment]
Tests seem to be up and running again, I've rebased to see if they'll pass this time.

**Comment by BinLi-OW** [comment]
To make it work on Android, do you mean I should use this method using ListView instead of ScrollView ? And is this also working for iOS ?

**Comment by xqwzts** [comment]
`contentOffset` should already be working on iOS, this PR brings it to Android too, for both ScrollView and ListView. [And _maybe_ the new FlatList/VirtualizedList if they use the `ReactHorizontalScrollView` native component]

**Comment by kkjamie** [comment]
What about `ReactScrollView` as well as the horizontal one ?

**Comment by xqwzts** [comment]
Shouldn't take much to reproduce the same code there, my initial use case didn't include vertical so I didn't want to make a PR I wouldn't be testing, might do it over the weekend.

**Comment by BinLi-OW** [comment]
I see the commit is submitted at Feb 27, 2017, is it available on any release version now?

**Comment by xqwzts** [comment]
@BinLi-OW : This PR hasn't been merged in, so no, it isn't in any of the releases. You could apply the changes locally to have access to it and help test [if you do, please let me know of any bugs that pop up].

**Comment by kkjamie** [comment]
I have tested this a bit, and it appears to work. I have merged it into our product, it will be tested more throughout the week by myself and our QA team.

**Comment by xqwzts** [comment]
@kkjamie : That's awesome, please let me know if you spot any issues!

**Comment by BinLi-OW** [comment]
@kkjamie, would you please give tips how could I rebuild the react-native-XXX.jar in local storage?
As I thought, I make changes to the java files under node_modules, but it seems I should build out the jar first.

**Comment by kkjamie** [comment]
I actually just copied the file from this repo into my repo and renamed it, exposed it by a new Package. I don't want to be forking react-native and worrying about rebuilding, I know somebody at our company has done this. Checkout https://facebook.github.io/react-native/releases/next/docs/android-building-from-source.html

**Comment by chrisbianca** [comment]
I've just given this a try as I encountered the same problem, and can confirm that the change works as expected.

**Comment by xqwzts** [comment]
@BinLi-OW I did it by forking, applying the changes of this commit, then building from source following the link @kkjamie posted above.
@chrisbianca : Thanks for the feedback.

**Comment by hramos** [comment]
This PR doesn't have a test plan, can you fix that?

**Comment by xqwzts** [comment]
@hramos : I'll rebase it on master in the next few days and take a look at handling vertical ScrollViews as well. Any specific test suggestions? Would committing examples be enough?

**Comment by jonaslu** [comment]
Hi!

I've tried getting the vertical scroll to behave the same with great success! 

I did exactly the same as this patch does but in ReactHorizontalScrollView.java and ReactScrollView.java, dunno if you want to include it in your patch (would make more sense from a commit-perspective I guess) or if I should do this in a separate commit?

Also, a word of warning - we had an included react-native component (seems to be react-native-scrollable-tab-view) that submits a contentOffset with only an x parameter. I think it's this line: https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/index.js#L155)

This seems to be an illegal state if I understand the data-type PointPropType correctly, but I'm thinking it's a good thing to actually check that both properties are defined before trying to access them (our app crashed before I added validation that both properties are present).

**Comment by ssssssssssss** [comment]
@shergin Any chance to get this merged? Thanks.

**Comment by todorone** [comment]
@hramos @shergin It's very annoying not having contentOffset on Android. Is there any chance this PR could be reviewed? Thanks.

**Comment by hramos** [comment]
@todorone it's been closed for over a year. It'd have a better chance if someone opened a new PR and applied the feedback from this thread.

**Pull request closed without merging**
