### PR TITLE
[UIExplorer] Removing the clear interval button if timer is not shown

### PR DESCRIPTION
**Pull request by toxicFork**
In UIexplorer, for the Timers, TimerMixin page:

At the bottom, press Unmount timer, then press Clear Interval, it will show an error. This PR fixes that.

### CODE REVIEW

**Comment by toxicFork** [comment]
I guess I should have done a PR from a branch, now I can't push anything to my master until it's merged :smile:

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by toxicFork** [comment]
Any updates?

**Comment by vjeux** [comment]
@toxicFork so sorry for the long wait (at this point it's frankly bad). It doesn't apply cleanly anymore :x Would you mind rebasing?

**Comment by toxicFork** [comment]
Ah looks like it was fixed by moving the clear interval button was moved into the timer variable so it's fixed now :)

**Comment by toxicFork** [comment]
Dunno what I wrote just above, rewrote it. 

However, I am slightly irked by the var declarations inside the conditional branches and having arrays without keys, are they accepted?

```js
if (this.state.showTimer) {
            var timer = [ // array without keys?
              <TimerTester ref="interval" dt={25} type="setInterval" />,
              <UIExplorerButton onPress={() => this.refs.interval.clear() }>
                Clear interval
              </UIExplorerButton>
            ];
            var toggleText = 'Unmount timer';
          } else {
            var timer = null; // duplicate var declaration?
            var toggleText = 'Mount new timer';
          }
```

**Comment by vjeux** [comment]
The double var declaration isn't the end of the world but would be nice to not have it. Also, would be nice to have keys, this is going to throw a warning

**Comment by toxicFork** [comment]
Alright tomorrow afternoon I can create a new pr for those little things in this file :D

**Pull request closed without merging**
