### PR TITLE
Fix Switch causing RetryableMountingLayerException

### LINKED ISSUE #32594: RN 0.66 Switch causes a stuck operation in mViewCommandOperations
### New Version

0.66.1

### Old Version

0.65.2

### Build Target(s)

Android Release

### Output of `react-native info`

System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 497.72 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.5.0 - /usr/local/opt/nvm/versions/node/v12.5.0/bin/node
    Yarn: 1.22.17 - /usr/local/opt/nvm/versions/node/v12.5.0/bin/yarn
    npm: 6.9.0 - /usr/local/opt/nvm/versions/node/v12.5.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.0, 30.0.2, 31.0.0
      System Images: android-21 | Intel x86 Atom_64, android-22 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64
      Android NDK: 23.0.7344513-beta4
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.1 => 0.65.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

In UIViewOperationQueue there is a list of ViewOperations called mViewCommandOperations. Detox checks that this list is empty, among other things, in order to determine that a device has reached an idle state. 

In RN 0.66 a regression occured. In Android Release, the Switch component attempts to perform setNativeValue true/false during initial layout on the screen, and it very often fails with a RetryableMountingLayerException of "Trying to send command to a non-existing view with tag..", it then increments the operation retry counter, but the operation remains stuck in mViewCommandOperations and is not cleared until some further action occurs on the screen (for example, clicking on the switch). This leads to a situation where, as far as Detox is concerned, the device is not idle and our tests begin to timeout.

Here is the relevant section in the code: https://github.com/facebook/react-native/blob/cbec66ef9250319258bf4c917518c08c34b0d3cd/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java#L881

I've managed to locate the commit where this regression started to occur, apparently connected to refactoring the switch to a functional component: https://github.com/facebook/react-native/commit/ab66741c8c1a3be0f4813b903bf792fc14156f5a

There are two things that are not clear here: 

- Why is a RetryableMountingLayerException occurring so often on initial layout of the Switch? 
- Why is mViewCommandOperations not performing the retry and clearing the queue immediately, without awaiting further user interaction? 

To reproduce this issue:
Go into a screen containing a Switch component in Android Release. Poll the isEmpty method of UIViewOperationQueue and you will see that it returns false.

### PR DESCRIPTION
**Pull request by jonathanmos**
## Summary
Added a null check to native.value in Switch to fix regression from RN 66 -> stuck operation in mViewCommandOperations list in Android Release on initial layout of a screen with Switch component. If approved, please incorporate this fix into an RN 66 release.

## Changelog
[Android][Fixed] - Added a null check to native.value in Switch to fix #32594

## Test Plan
To reproduce, put a log in UIViewOperationQueue in dispatchViewUpdates you can see that the RetryableMountingException is no longer thrown for a screen with the Switch component on Android Release. As a result, mViewCommandOperations no longer has a stuck operation on initial layout.

### CODE REVIEW

**Review by lunaleaps — CHANGES_REQUESTED** [review]
In the issue, you mention that we attempt to `setNativeValue` on initial render but wouldn't `nativeSwitchRef.current` be null in this case?

I believe that's why we have the check there to avoid the case of the native view not being rendered yet. If this isn't the appropriate check, then maybe we need to update it.

**Comment by lunaleaps** [comment]
For more context, this was part of a Switch refactor and this logic used to live in a `componentDidUpdate` (https://github.com/facebook/react-native/blob/683b825b327e7fa71e87e3d613cb9acd37c24288/Libraries/Components/Switch/Switch.js#L220). I believe these changes should still occur in a `useLayoutEffect` as this behavior we're trying to do is keep the JS and native value in sync but maybe we need to also check if `nativeValue` is set.

Although, forgive me if I'm mis-remembering, shouldn't the native ref only be set when the native view has been rendered?

**Comment by d4vidi** [comment]
@jonathanmos ping?

**Comment by jonathanmos** [comment]
@lunaleaps I'd like to revive this pr and hopefully we can bring it to a conclusion. 

You suggested in your comments adding a check for whether native.value was set. I've tried adding such a check to shouldUpdateNativeSwitch and it does solve the issue, but I've hesitated to push it as a fix as i noticed that after this change shouldUpdateNativeSwitch seems to always return false (value is always equal to native.value) and so setNativeValue is not being called. I think I'm not understanding completely in what situation these values are both set but different. Do you know what steps I can use to simulate such a situation in a test to ensure that everything works as expected?

**Comment by jonathanmos** [comment]
Regarding the nativeref being set only on render, I'm unsure exactly what is going on here. The nativeref is undoubtedly set when the call to setnativevalue is made, but it still causes a retryableMountingException on the initial render

**Comment by asafkorem** [comment]
Hi @lunaleaps 👋🏼 
We will be very grateful to reach a solution soon, as this stuck operation affects Detox tests directly with synchronization issues and fails tests of screens that involves switch components unless a workaround is used. 🙏🏼

**Comment by jonathanmos** [comment]
@lunaleaps In the tests that I've run, out of the variables in `useLayoutEffect`, only `native.value` is null on initial render of the component (although this is unconnected to whether the `RetryableMountingLayerException` is thrown as sometimes it is and sometimes not). Adding a null check for `native.value` in [this](https://github.com/facebook/react-native/blob/d92ecda022e9038862e1864d5c9d0aa0d0bf4699/Libraries/Components/Switch/Switch.js#L173) line prevents `useLayoutEffect` from executing logic on the initial render. This 'solves' the issue by avoiding inserting the problematic operation into the queue. 

I've tried rapid toggling of disabled state for the switch, as well as sending many js operations, but was unable to produce a situation where sync was lost.

**Comment by lunaleaps** [comment]
@jonathanmos Can we update the changelog summary of this change as well? Thanks!

**Comment by jonathanmos** [comment]
@lunaleaps I've updated the changelog for the issue

**Comment by lunaleaps** [comment]
Oh actually thinking about this again, I think the case to test this is if we hardcode the JS value to be some constant value -- then we want to ignore any attempts of native to toggle the switch. Let me try this case out

**Pull request closed without merging**
