### PR TITLE
Allow listen to foreground or background notification separately

### PR DESCRIPTION
**Pull request by lazywei**
In many cases, the app need to respond to the notification in different ways.
Take chat app as an instance. The app need to jump to the certain chatroom when users opens the notification from background, while it shouldn't jump to anywhere when the chat app is in foreground.

So I split the notification type to foreground and background. In this way, the developers can listen to different type of notification accordingly.

Usage:

```javascript
PushNotificationIOS.addEventListener("notificationForeground",
    this._handleNotificationForeground);
PushNotificationIOS.addEventListener("notificationBackground",
    this._handleNotificationBackground);
```

### CODE REVIEW

**Comment by lazywei** [comment]
@brentvatne I rebased this and made the test pass. Would you mind help me review this or assign a reviewer for this?
Thanks :smile:

**Comment by brentvatne** [comment]
Hi @lazywei!

Some thoughts:

- Is it more common to listen to both foreground and background or to listen to them separately? With this approach, we will need to add two listeners if we want to listen to both.
- Could we use one event and pass in the event object whether it is foreground or background?

I don't have a lot of experience with this area so I'm curious what other smarter people like @ide think.

**Comment by ide** [comment]
Probably makes more sense to put this logic in your app's JS -- when your JS gets the "notification" event, check whether the application is foregrounded or not. 

I would also be surprised if this diff works... React Native does not work with backgrounded apps right now, and I think you need a different app delegate method to handle notifications while backgrounded.

**Comment by lazywei** [comment]
> Probably makes more sense to put this logic in your app's JS -- when your JS gets the "notification" event, check whether the application is foregrounded or not. 

I agree with you. However, the thing is currently we don't have a proper way to check the app's foreground/background state (at least I'm not aware of).

> I would also be surprised if this diff works... React Native does not work with backgrounded apps right now, and I think you need a different app delegate method to handle notifications while backgrounded.

Actually it works pretty well in my project (I'm using this PR in my app). It doesn't require RN work with backgrounded app I think. It's totally native solution -- only it emits different event for background / foreground app.
In a nutshell, the background notification will be triggered if we click the notification and jump to the app. On the other hand, the foreground notification will be triggered if the app is currently foregrounded.

**Comment by ide** [comment]
Check out https://facebook.github.io/react-native/docs/appstateios.html#content

**Comment by lazywei** [comment]
oh, that's cool.
OK, it makes sense to do that in JS side then.
I'm going to close this PR.

Thanks.

**Comment by brentvatne** [comment]
Thanks for it anyways @lazywei, even if it didn't work out :smile:

**Pull request closed without merging**
