### PR TITLE
[Packager] Configure Babel with .babelrc

### PR DESCRIPTION
**Pull request by jtremback**

### CODE REVIEW

**Comment by johanneslumpe** [comment]
I don't think it's a good idea to have babel config in either `.babel.rc` or `package.json`. I'd just go for one to make it more explicit how to configure babel.

**Comment by jtremback** [comment]
I'm just going on how Babel itself can be configured. I think there are advantages to either one. I prefer putting any configuration I can in package.json, because then I can just copy n paste to start a new project.

**Comment by johanneslumpe** [comment]
@jtremback fair enough :)

**Comment by jtremback** [comment]
Ooops. @johanneslumpe I was totally wrong. Am changing the PR to only look for `.babelrc`.

**Comment by sebmck** [comment]
The `.babelrc` merging behaviour in this PR is not consistent with how Babel does it and doesn't include a cache so you'll get some overhead. Babel can resolve `.babelrc` files itself by just specifying an absolute filename to `babel.transform`. Ref #1451.

**Pull request closed without merging**
