### PR TITLE
[cli] merge yeoman tests into one file to avoid concurrenct issues with jest

### PR DESCRIPTION
**Pull request by foghina**

### CODE REVIEW

**Comment by mkonicek** [comment]
Cool! There are still multiple `describe` calls. I'm not sure whether Jest parallelizes the tests based on files or `describe` calls. Let's ask @cpojer.

**Comment by mkonicek** [comment]
Just messaged Christoph.

**Comment by cpojer** [comment]
Currently we parallelize *per file* but I would like to get to a point where we can parallelize *per call to `it`*. Every `it` call should be seen as completely isolated. You can use `beforeEach` for common set-up, it will be run before every call to `it`.

**Comment by mkonicek** [comment]
Thanks for the explanation @cpojer! We need to run a yeoman generator per `it` which means we'll need to fix the fundamental issue in yeoman before Jest moves to parallelizing per call to `it`.

Keeping the CLI tests in a single file to run them sequentially for now.

**Pull request merged**
