### PR TITLE
Local cli/android/normalize project name

### PR DESCRIPTION
**Pull request by Titozzz**
## Motivation

Scoped packages are starting to be the new thing, and gradle does not work properly with '/' in the project name, so this PR links them and replaces '/' by '_' . This only affects android.

## Test Plan

I added tests in the 2 impacted functions + a test file for the normalizer function

## Related PRs

#17000 This was the initial PR but this is done without mutations

## Release Notes

[CLI] [BUGFIX] [local-cli/link/link.js] - On android, Scoped packages will now get the '/' replaced with '_' to ensure gradle works nicely.  ⚠️ However if you previously linked scoped packages, they will get linked again. ⚠️

### CODE REVIEW

**Comment by Titozzz** [comment]
@Kureev

**Comment by Kureev** [comment]
Hey!

Awesome PR, and definitely important for Android developers. I have only one thing to request: can you please verify that unlink also works as expected? 🙌

**Comment by Titozzz** [comment]
Hello, I did add some test to the helpers used by both link and unlink:
```
makeBuildPatch.js
makeSettingsPatch.js
```

so everything should be fine

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Comment by petermekhaeil** [comment]
Is this PR planned for a release?

**Comment by hramos** [comment]
@petermekhaeil it's in `0.56.0-rc`. You can corroborate this by looking at the tags in https://github.com/facebook/react-native/commit/dbd47592a18ed09ee6e94c79bed16d63be625af6

**Pull request closed without merging**
