### PR TITLE
Add video link and include new featured apps in showcase

### PR DESCRIPTION
**Pull request by brentvatne**

### CODE REVIEW

**Comment by brentvatne** [comment]
uh no thanks travis

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
Yeah, it will (should) work, Travis is a clowntown right now.
On my list to get it stable.
Once it is stable we will setup our CI to check for Travis/CI status before merging

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
Could you please rebase, showcase.js can't merge

**Comment by brentvatne** [comment]
@bestander - done!

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
