### PR TITLE
Add a local packager config, so that react can find react-native when…

### PR DESCRIPTION
**Pull request by davidaurelio**
The **motivation** for this PR is my sad colleague @bestander: I managed to break travis with bd60d828c5fc9cb066e5f647c87ecd6f70cb63a5, without considering the consequences. This PR solves this failure, and will fix it for good.

**Test plan (required)**

Travis will demonstrate that the code is solid.
Let’s make sure tests pass on both Travis and Circle CI.

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
okay-meme-gif-05

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/569985413182782/int_phab) to review.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
