### PR TITLE
fix ReactNativeART arc drawing on Android

### PR DESCRIPTION
**Pull request by dgladkov**
This patch fixes multiple problems with arc drawing on Android and makes it consistent with how `CGPathAddArc` works on iOS

### CODE REVIEW

**Comment by satya164** [comment]
cc @mkonicek

**Comment by dgladkov** [comment]
This problem can be reproduced when using react-art's Wedge shape (https://github.com/reactjs/react-art/blob/master/src/Wedge.art.js). I can create a sample RN project that illustrates the error if needed.

**Comment by satya164** [comment]
@dgladkov A sample would be great. Thanks.

**Comment by dgladkov** [comment]
Created a project to illustrate the bug https://github.com/dgladkov/RNArtArcDrawingBug
Check the README for screenshots of iOS and Android rendeirng

**Comment by dgladkov** [comment]
Fixes #5311

**Comment by mkonicek** [comment]
What's the test plan? Do you have some screenshots before / after?

**Comment by facebook-github-bot-1** [comment]
@spicyj would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
@dgladkov Can you add some screenshots please so we can see what it looks like?

**Comment by MikeOrtiz** [comment]
@mkonicek The author added 'before' screenshots illustrating the bug here: https://github.com/dgladkov/RNArtArcDrawingBug

Do you need @dgladkov to add 'after' screenshots as well?

**Comment by MikeOrtiz** [comment]
This PR had a bug in it. I submitted my own, including screenshots: https://github.com/facebook/react-native/pull/7049.

**Comment by mkonicek** [comment]
@MikeOrtiz We could merge #7049, it's being reviewed now.

**Comment by mkonicek** [comment]
> Created a project to illustrate the bug https://github.com/dgladkov/RNArtArcDrawingBug

Oh sorry @dgladkov I didn't see that, I look for a Test plan in the pull request summary, see https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by MikeOrtiz** [comment]
@mkonicek This PR can be closed now that #7049 was accepted.

**Comment by mkonicek** [comment]
Thanks for the update @MikeOrtiz!

**Pull request closed without merging**
