### PR TITLE
Fixed typo in ReactCommon/buffer/map.h

### PR DESCRIPTION
**Pull request by Kwasow**
## Summary

Fixed a typo inside ReactCommon.

## Changelog

[General] [Fixed] - Fixed typo in comment

## Test Plan

_This change does not require testing._

### CODE REVIEW

**Comment by cortinico** [comment]
> /rebase

@cipolleschi this failed as the users is too far behind

**Comment by cipolleschi** [comment]
@Kwasow could you manually rebase, please? 🙏

**Comment by Kwasow** [comment]
@cipolleschi I merged the changes from main into my branch

**Comment by cipolleschi** [comment]
@Kwasow, could you also log into `app.circleci.com` to renew the GitHub token that CircleCI has? Otherwise the CI pipelines won't run... :(

**Comment by Kwasow** [comment]
@cipolleschi I signed back in to CircleCI but am unable to re-run the workflow. Is it something you have to trigger on your end?

**Pull request closed without merging**
