### PR TITLE
Add WeatherEh to showcase

### PR DESCRIPTION
**Pull request by umhan35**
Skipping eveything in the contribution guide because adding an app to the Showcase

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by umhan35** [comment]
By developing this app, I open-sourced `react-native-search-bar`: https://github.com/umhan35/react-native-search-bar

**Comment by facebook-github-bot-2** [comment]
@umhan35 updated the pull request.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1555770444724088/int_phab) to review.

**Pull request closed without merging**
