### PR TITLE
Resolve 11457 - Packager very slow on first run

### PR DESCRIPTION
**Pull request by license2e**
Signed-off-by: Ilya Shindyapin <ilya@shindyapin.com>

## Motivation

https://github.com/facebook/react-native/issues/11457

## Test Plan

Without the change `react-native run-xxx` takes a LONG time to start the simulator, with the change, it is almost instantly...

Also, running `nc -w 5 -z localhost 8081` inside the terminal take a LONG time to run, while `nc -w 5 -z 127.0.0.1 8081` is almost instant.

### CODE REVIEW

**Comment by hramos** [comment]
```
$ time nc -w 5 -z 127.0.0.1 8081
real	0m0.007s
user	0m0.002s
sys	0m0.004s

$ time nc -w 5 -z localhost 8081
real	0m0.010s
user	0m0.002s
sys	0m0.004s
```

The difference is negligible on my system. Are you certain this is the right fix here?

**Comment by license2e** [comment]
@hramos It could be just my system or settings (see results below), but if this is happening to others, then it would affect how they develop using `react-native`. Also, if it makes no difference, then why not?

Here is the output on my system, **_without anything running on port 8081_** (it seems to get slower every time I run it):
```
$ time nc -w 5 -z 127.0.0.1 8081

real	0m0.008s
user	0m0.002s
sys	0m0.002s

$ time nc -w 5 -z localhost 8081

real	10m4.935s
user	0m0.002s
sys	0m0.004s
```

**Comment by license2e** [comment]
If I add the `-n` flag:

```
-n' Do not do any DNS or service lookups on any specified addresses, hostnames or ports.
``` 
- source: https://linux.die.net/man/1/nc

```
$ time nc -n -w 5 -z localhost 8081
nc: getaddrinfo: nodename nor servname provided, or not known

real	0m0.006s
user	0m0.002s
sys	0m0.003s
```

**Comment by license2e** [comment]
If I do have something running on `localhost:8081` (ie, an existing React Native project)

```
$ time nc -w 5 -z localhost 8081
Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!

real	0m0.026s
user	0m0.009s
sys	0m0.009s
```

**Comment by javache** [comment]
This could be a misconfiguration of your system. Could you check if your `/etc/hosts` file contains an entry for localhost?

**Pull request closed without merging**
