### PR TITLE
[react-native-cli] fixed issue with runIOS not being able to launch tvOS app

### PR DESCRIPTION
**Pull request by joeyjiron06**
## Is this a bug report?
Yes.

## Have you read the Contributing Guidelines?
Yes

## Environment
Environment:
OS: MacOS X 10.12.6 (16G29)
Node: 8.9.4
Yarn: N/A
npm: 5.4.2
Watchman: Not Found
Xcode: 9.2 (9C40b)
Android Studio: N/A

## Bug Summary
[CLI iOS runIOS] When using `react-native-cli` to try to launch the tvOS scheme the user get's an error because the current implementation for launching simulators ignores any simulator/device who's name does not start with `iOS`

## Steps to Reproduce

StackOverflow issue also found here :  https://stackoverflow.com/questions/48069690/how-to-select-project-to-run-tvos-version-with-npm-start

Actual command line steps
```
$npm i -g react-native-cli
...
$react-native init CoolProject
...
$cd CoolProject/
$react-native run-ios --simulator "Apple TV"  --scheme "CoolProject-tvOS"

Scanning folders for symlinks in /Users/jjiron/CoolProject/node_modules (7ms)
Found Xcode project CoolProject.xcodeproj
CoreData: annotation:  Failed to load optimized model at path '/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'

Could not find Apple TV simulator
```

## Expected Behavior
The cli tool should launch the tvOS application on the simulator.

## Actual Behavior
The user get's an error message saying "Could not find Apple TV simulator"

## The Fix
Don't ignore appletv simulators when looking for simulators to launch. Also use the correct application build when selecting which app to launch on the simulator/device.

## Test Plan
Added automated test for `findMatchingSimulator.js` to allow tvOS simulators

## Release Notes
[react-native-cli] Fixed issue where you cannot launch tvOS app on Apple TV simulator

### CODE REVIEW

**Comment by joeyjiron06** [comment]
yes this merges cleanly onto the master branch. im guessing that the merge doesnt work because `ci/circleci: build/hold` is on hold, and `ci/circleci: analyze-pull-request` failed. looking at the logs it seems like the npm install failed...not sure why, but i know it can happen from time to time on a CI server.

can someone re-run those jobs and try merging again?

**Comment by hramos** [comment]
A rebase is needed due to some changes that happened earlier this week in our internal monorepo outside of the synced react-native directory (but nonetheless prevent this PR from landing). Simply hitting Update branch should resolve it, let's see.

**Comment by joeyjiron06** [comment]
any update on this @hramos ?

**Comment by joeyjiron06** [comment]
why did the bot close this issue?

**Comment by hramos** [comment]
The bot closes pull requests automatically after merging them.

**Pull request closed without merging**
