### PR TITLE
add damusnet to React Native GitHub Issue Task Force

### PR DESCRIPTION
**Pull request by damusnet**

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @christopherdro to be potential reviewers.

**Comment by christopherdro** [comment]
@damusnet Can you put your handle in alphabetical order? 
Thanks!

**Comment by damusnet** [comment]
@christopherdro sure thing! Sorry I didn't notice it straight away 😳

**Comment by facebook-github-bot-2** [comment]
@damusnet updated the pull request.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1627607327564869/int_phab) to review.

**Pull request closed without merging**
