### PR TITLE
Update boost to 1.83.0

### PR DESCRIPTION
**Pull request by Kudo**
## Summary:

Since folly is updated from https://github.com/facebook/react-native/commit/17154a661fe06ed25bf599f47bd4193eba011971, it is good to bump boost too.

After updating boost, we can remove the Xcode 15 `_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION` workaround which originally to fix Xcode 15 for boost.

## Changelog:

[GENERAL][CHANGED] - Update boost to 1.83.0

## Test Plan:

- CI passed
- Build and launch RNTester on Android and iOS

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
Thanks @Kudo for taking care of this! 🙌

**Comment by cipolleschi** [comment]
> This PR is based on https://github.com/facebook/react-native/pull/39552. Not sure how Meta internally deal with stacked PRs. This PR just adds a new commit based on https://github.com/facebook/react-native/pull/39552 anyway.

I think that this PR contains all the changes that are in https://github.com/facebook/react-native/pull/39552, so we can land this one only. Could you double-check that as well?

**Comment by Kudo** [comment]
> I think that this PR contains all the changes that are in https://github.com/facebook/react-native/pull/39552, so we can land this one only. Could you double-check that as well?

that's correct! good to know we can just land this one. let me update this pr's description/changelog and close #39552.

**Comment by liamjones** [comment]
Something I've just noticed in relation to this PR when upgrading from 0.72.x to 0.73.x - if the `_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION` directive had been added to a project previously, it doesn't get removed again here.

Is that an issue or not? I noticed it's a `CXX17` directive and 0.73 moves to c++20 so maybe it isn't obeyed anyway?

**Comment by cipolleschi** [comment]
@liamjones it should not be an issue. The directive is needed to backport the name of an API that has changed. I don't think that it's an issue if we keep it. Unless you are seeing some specific errors: if that's the case, could you share them?

**Comment by liamjones** [comment]
@cipolleschi Nope, not seeing any errors. I jst noticed it wasn't being removed when I did the RN upgrade and wanted to check if it was deliberate. Thanks for confirming it was! 😄

**Pull request closed without merging**
