### PR TITLE
NavigationBarItem Update

### PR DESCRIPTION
**Pull request by Iragne**
Provide a function to update NavigationbarItem (button, title...)
Provide TitleIcon property
Fix Recursive render of hidden viewController
Provide Exemple

### CODE REVIEW

**Comment by cancan101** [comment]
What's up with the PR?

**Comment by Iragne** [comment]
@cancan101 i will restart to create it in the next days

**Comment by facebook-github-bot-4** [comment]
@mrspeaker would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
@Iragne Note that the Navigator is getting deprecated in favor of `NavigationExperimental`. Do you still plan to work on this or should we close it? I'm going through all PRs now making sure each PRs is either being actively worked on or closed, to keep the number of open PRs under control.

**Comment by jsierles** [comment]
@facebook-github-bot no-reply

**Comment by Iragne** [comment]
Well i woudl like to have time to work on it and don't let the comunity like that but i'm running out of time.
May be in the next month i will be able to update it

**Comment by javache** [comment]
This pull request hasn't seen activity in a while. If you still want to merge this, please open a new pull request.

**Comment by csujedihy** [comment]
This functionality is pretty useful.

**Comment by skycocker** [comment]
@Iragne thanks for this one, did help me a lot :)

**Pull request closed without merging**
