### PR TITLE
[StatusBarIOS] Add getStyle method

### PR DESCRIPTION
**Pull request by Kemcake**

### CODE REVIEW

**Comment by satya164** [comment]
@Kemcake what does it do? what's the use case?

**Comment by Kemcake** [comment]
I'm facing a situation where I need to present a view (let's say a modal) that needs the status bar white. This modal can be presented from various places in my app, and from views that may need status black. With this method I can store the status bar style before presenting the modal, change it to white on mount, and when I dismiss the modal I can change it back to the previous style.

(It was useful when presenting a SafariViewController in my case)

**Comment by satya164** [comment]
@Kemcake Aren't you setting the statusbar style somewhere? Then you could just pass down the prop to whichever component requires to know the current style.

**Comment by Kemcake** [comment]
Of course, I can pass the desired style through the action that present the view, I just though it was more convenient to let the presented view deals with it instead of the presenter view. 

Anyway, it could be useful in a case where we want to ensure that the status bar is correctly set.

**Comment by brentvatne** [comment]
@Kemcake - is there a reason this is preferred over just setting the status bar color regardless of the current color? It shouldn't have any impact if it's already the correct color

**Comment by Kemcake** [comment]
@brentvatne - No, actually set the status bar style directly is fine. This is just useful for components that you may not have full control of, I'm using it while presenting  SafariViewController, UIImagePickerController and UIDocumentPickerController. It may have others use cases 🤗

**Comment by satya164** [comment]
Can you give a small example? I feel like it isn't very React-like. For example the component state and props are the source of truth. You don'r read the values from the DOM.

**Comment by nicklockwood** [comment]
I think the actual problem here is the imperative API for StatusBarIOS, which is very un-React-like.

We should have made it a component, and allowed for nesting, so that the deepest/frontmost StatusBarIOS in the hierarchy dictates the status bar color.

That way, presenting a standard UIKit controller that overrides the status bar color wouldn't require you to store the current state and restore it, because the framework would do it automatically.

I might work on changing StatusBarIOS to a component at some point, unless someone else feels like opening a PR…

**Comment by satya164** [comment]
@nicklockwood +1 for it being a component. Shall I open an issue and add the "Help wanted" label on it?

**Comment by nicklockwood** [comment]
@satya164 sure!

**Comment by nicklockwood** [comment]
Closing in favor of the new `<StatusBar>` component API.

**Pull request closed without merging**
