### PR TITLE
Remove deprecated slider

### PR DESCRIPTION
**Pull request by AntoineDoubovetzky**
## Summary

Slider component is deprecated for a while, and the community package (https://github.com/react-native-community/react-native-slider) is now compatible with the new architecture (see https://github.com/react-native-community/discussions-and-proposals/issues/451).

I removed all occurrences of `Slider`, except:
<details>
  <summary>RNTNativeComponentWithStateCustomShadowNode in RNTester</summary>

[RNTNativeComponentWithStateCustomShadowNode.h#L25](https://github.com/facebook/react-native/blob/main/packages/rn-tester/NativeComponentWithState/cxx/RNTNativeComponentWithStateCustomShadowNode.h#L25):

```
/*
 * `ShadowNode` for <Slider> component.
 */
class RNTNativeComponentWithStateCustomShadowNode final
```

and [RNTNativeComponentWithStateCustomShadowNode.cpp#L40](https://github.com/facebook/react-native/blob/main/packages/rn-tester/NativeComponentWithState/cxx/RNTNativeComponentWithStateCustomShadowNode.cpp#L40):
```
// It is not possible to copy or move image requests from SliderLocalData,
// so instead we recreate any image requests (that may already be in-flight?)
// TODO: check if multiple requests are cached or if it's a net loss
```
because I'm not sure this code is specific to the Slider component.
</details>

<details>
  <summary>AccessibilityExample in RNTester</summary>

[AccessibilityExample.js#L732](https://github.com/facebook/react-native/blob/7afd8a0ddbd244dbf0116007ca523c5a9575be6b/packages/rn-tester/js/examples/Accessibility/AccessibilityExample.js#L732):

```
<RNTesterBlock title="Adjustable with increment/decrement actions">
  <View
    accessible={true}
    accessibilityRole="adjustable"
    accessibilityActions={[{name: 'increment'}, {name: 'decrement'}]}
    onAccessibilityAction={event => {
      switch (event.nativeEvent.actionName) {
        case 'increment':
          Alert.alert('Alert', 'increment action success');
          break;
        case 'decrement':
          Alert.alert('Alert', 'decrement action success');
          break;
      }
    }}>
    <Text>Slider</Text>
  </View>
</RNTesterBlock>
```
because I think the text here does not refer to the Slider component.
</details>

<details>
  <summary>Codegen fixtures</summary>

[fixtures.js#L441](https://github.com/facebook/react-native/blob/7afd8a0ddbd244dbf0116007ca523c5a9575be6b/packages/react-native-codegen/src/generators/components/__test_fixtures__/fixtures.js#L441) (3 more occurences in this file) and the [snap file](https://github.com/facebook/react-native/blob/7afd8a0ddbd244dbf0116007ca523c5a9575be6b/packages/react-native-codegen/src/generators/components/__tests__/__snapshots__/GeneratePropsJavaPojo-test.js.snap):

```
const IMAGE_PROP: SchemaType = {
  modules: {
    Slider: {
      type: 'Component',
```
because I feel like the name here is just a string but does not refer specifically to the Slider component, it could be any component name.
</details>

<details>
  <summary>Accessiblity roles and values</summary>

[View.js#L133](https://github.com/facebook/react-native/blob/7afd8a0ddbd244dbf0116007ca523c5a9575be6b/Libraries/Components/View/View.js#L133):

```
separator: undefined,
slider: 'adjustable',
spinbutton: 'spinbutton',
```

[ViewAccessibility.js#L99](https://github.com/facebook/react-native/blob/7afd8a0ddbd244dbf0116007ca523c5a9575be6b/Libraries/Components/View/ViewAccessibility.js#L99):

```
| 'separator'
| 'slider'
| 'spinbutton'
```

[ViewAccessibility.d.ts#L73](https://github.com/facebook/react-native/blob/7afd8a0ddbd244dbf0116007ca523c5a9575be6b/Libraries/Components/View/ViewAccessibility.d.ts#L73):

```
/**
 * Represents the current value of a component. It can be a textual description of a component's value, or for range-based components, such as sliders and progress bars,
 * it contains range information (minimum, current, and maximum).
 */
```

[ViewPropTypes.js#L508](https://github.com/facebook/react-native/blob/7afd8a0ddbd244dbf0116007ca523c5a9575be6b/Libraries/Components/View/ViewPropTypes.js#L508):

```
/**
 * alias for accessibilityState
 * It represents textual description of a component's value, or for range-based components, such as sliders and progress bars.
 */
```
because I feel that the `slider` role and the comments about slider are still relevant.
</details>

## Changelog

[General] [Removed] - Remove deprecated Slider component

## Test Plan

All the tests are green, and the RNTester app is running fine.

### CODE REVIEW

**Comment by AntoineDoubovetzky** [comment]
@huntie I see that Facebook Internal Builds and Linter failed. Is there anything I can do ?

**Comment by huntie** [comment]
@AntoineDoubovetzky Hey, yes we gave this a go and CI flagged that we are still depending on this component in several places internally at Meta — enough that this cannot be immediately merged.

We are going to create tasks/reach out to maintainers so that these internal usages can be replaced, but this will take some time (we cannot make any near-term commitment).

Let's keep this PR open in the meantime. I've assigned it to @NickGerleman as a task hook and he/someone should re-import this PR in future when ready.

**Comment by AntoineDoubovetzky** [comment]
Reading the issue I thought that the Slider was not used internally anymore. Good luck replacing it!

**Comment by AntoineDoubovetzky** [comment]
@huntie I believe the Slider has been removed in another PR: https://github.com/facebook/react-native/pull/35365

I can close this one, right?

**Comment by huntie** [comment]
@AntoineDoubovetzky Yes, thanks!

**Pull request closed without merging**
