### PR TITLE
`RCTAttributedTextUtils.mm`: Split `NSAttributedString` creation

### PR DESCRIPTION
**Pull request by cubuspl42**
## Summary:

`RCTAttributedTextUtils.mm`: Split `NSAttributedString` creation to functions in preparation for adding new logic here.

This is a minor improvement in the context of my multi-PR work on https://github.com/react-native-community/discussions-and-proposals/issues/695.

## Changelog:

[INTERNAL] [CHANGE] - Refactor `NSAttributedString` creation in `RCTAttributedTextUtils.mm`

### CODE REVIEW

**Comment by cubuspl42** [comment]
@sammy-SC Any chance you could review this?

**Comment by cubuspl42** [comment]
@sammy-SC ...but if you could recommend some Objective-C expert from the React Native team, I would also be grateful! 😃

**Review by cipolleschi — APPROVED** [review]
Hi @cubuspl42, thanks for your contribution!

**Comment by cubuspl42** [comment]
@cipolleschi 

Thank _you_!

You'll thank me later; non-trivial PRs will come after this wave.

Currently, the wave progress is 2/6. I would be extremely grateful for taking a look for maybe one more:

https://github.com/facebook/react-native/issues/42602#issuecomment-1905754408

**Pull request closed without merging**
