### PR TITLE
Fix broken link for Gesture Responding System page in Docs

### PR DESCRIPTION
**Pull request by vinaynb**
Fix broken link in [Handling Touches](http://facebook.github.io/react-native/docs/handling-touches.html)

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by vinaynb** [comment]
I just wanted to submit a PR to fix a broken link in docs. When i went to create a PL there was a placeholder text saying that unless i am a maintener i need to push commits to master branch. I think i did something wrong here. There are tons of commits being shown in my PR and whole lot of code.

Not too well versed with this stuff. Can someone help me out here ?

**Comment by hramos** [comment]
Can you rebase off master?

**Comment by hramos** [comment]
Actually, the change you are proposing in fe91dbd0f33de73eae65e6bfc7543a0579f71e6d is for something that was already fixed in master 3 weeks ago.

**Pull request closed without merging**
