### PR TITLE
[NativeAnimated] Allow animating the elevation style

### PR DESCRIPTION
**Pull request by janicduplessis**
Elevation should be supported by the native driver as it's a non-layout prop.

Test Plan:
----------
Tested that animating elevation with the native driver actually works in an app.

Release Notes:
--------------
Help reviewers and the release process by writing your own release notes. See below for an example.

[ANDROID] [ENHANCEMENT] [NativeAnimated] - Allow animating the elevation style

### CODE REVIEW

**Comment by kmagiera** [comment]
@facebook-github-bot shipit

**Comment by kmagiera** [comment]
LGTM 👍

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit-ninja

**Pull request closed without merging**
