### PR TITLE
Sort StyleProps alphabetically

### PR DESCRIPTION
**Pull request by janmonschke**
Sorting the StyleProps alphabetically makes it easier to scan through the list of available props e.g. in case of typos.

Filled out the FB CLA form just now.

Related to #1605

### CODE REVIEW

**Comment by janmonschke** [comment]
Not sure why the build is failing, though ;)

**Comment by sahrens** [comment]
nice find :)

**Comment by sahrens** [comment]
@facebook-github-bot import

**Comment by janmonschke** [comment]
@sahrens Do you need me to make the build green to merge this? I can hardly believe that an added `sort()` in that file would break the build :D

**Comment by sahrens** [comment]
The tests were failing on master earlier but should be stable now, probably just needs a rebase.

**Comment by janmonschke** [comment]
@sahrens That fixed it!

**Pull request closed without merging**
