### PR TITLE
[CLI] Fix --udid option with react-native run-ios

### LINKED ISSUE #10288: Choose Simulator iOS version
React-native v0.34

Anyway to choose a simulator's ios version to run?
I have list of simulators with iOS 9.3 and iOS 10.

When using --simulator it picks the simulator device with latest iOS which is 10.

Setting deployment target to 9.3 in the project settings doesnt help :/

Maybe a flag --iosversion would be beneficial in the next release.

Thank you very much in advance,

### PR DESCRIPTION
**Pull request by christopherdro**
Although I'm a strong advocate of using Xcode, I noticed a combination of issues requesting support for running a specific iOS version with `react-native run-ios`.

This is a follow up for changes that were made in the recent past.

https://github.com/facebook/react-native/commit/48ab5eb436d1e919d3997be30d8bc1219b66d6c3
https://github.com/facebook/react-native/commit/8b55e50d1da91dbeadddd7a5a40cc6e4532f9551

Tested using both `--device` and `--udid` with various simulator options and devices.

Closes #10288

### CODE REVIEW

**Comment by christopherdro** [comment]
@dlowder-salesforce 💚

**Comment by hramos** [comment]
Sorry for the churn here, we've landed other PRs that touch this file as well. Can you take a look at the conflicts in `local-cli/runIOS/runIOS.js`?

**Comment by StevePotter** [comment]
I'm happy to review once the conflicts are resolved.  @christopherdro please notify when it's done and i'll help review.  Thanks!

**Comment by christopherdro** [comment]
@hramos @StevePotter Waiting for tests.

**Comment by christopherdro** [comment]
@StevePotter @hramos Good to go

**Comment by christopherdro** [comment]
@hramos @StevePotter I'm going to have to rebase this again to resolve conflicts. 
I don't see the point of continuously doing this if its not going to be looked at afterwards. 

Please ping me when someone is available to look at this after the conflicts have been resolved.

**Comment by lacker** [comment]
There still appear to be some conflicts here. (Maybe they're different ones, in which case sorry!)

**Comment by hramos** [comment]
This PR appears to be abandoned. Closing for now.

**Pull request closed without merging**
