### PR TITLE
Add "Nabava.net" app to the showcase.

### PR DESCRIPTION
**Pull request by maranbomater**

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
@maranbomater updated the pull request.

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/822550344556078/int_phab) to review.

**Pull request closed without merging**
