### PR TITLE
Minor grammatical fixes:

### PR DESCRIPTION
**Pull request by kphed**
1. 'Install' should be 'installed' (past tense)
2. Change 'checkout' to 'check out' (check out is to inspect and checkout refers to "checking out at a hotel/grocery store")

### CODE REVIEW

**Comment by brentvatne** [comment]
@kphed - we'll need you to sign CLA before we can merge, see above ^

**Comment by kphed** [comment]
@brentvatne thanks for the heads up, Brent! I just signed the CLA :)

**Comment by brentvatne** [comment]
Great, thanks for the PR! :clap: hopefully the first of many

**Comment by kphed** [comment]
Most definitely! Thanks for the merge :dancers:

**Comment by brentvatne** [comment]
Hmm it seems like @facebook-github-bot is lagging a bit behind, hopefully it tags as CLI signed soon :P

**Comment by kphed** [comment]
I swear I signed it haha :suspect:

**Pull request merged**
