### PR TITLE
Viewpager fix

### PR DESCRIPTION
**Pull request by Anthonyzou**
Hello,

I have been making an image pinch and zoom module using the [photoview module](https://github.com/chrisbanes/PhotoView). There are crashes because of an NPE when the photo view is included in a view pager. I have been copying the current code with the fix into my repo [here](https://github.com/Anthonyzou/react-native-image-zoom/blob/master/android/src/main/java/com/image/zoom/viewpager/ReactViewPager.java#L132).

The issue is documented [here](https://github.com/chrisbanes/PhotoView#issues-with-viewgroups)

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mizinin** [comment]
it is very actual for me

**Comment by ide** [comment]
try-catch is almost never an acceptable way to fix NPEs. Please come up with a more correct fix.

**Comment by mkonicek** [comment]
@Anthonyzou I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment requests changes. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to continue working on this.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (72/60 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:55444)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1biJW3-003LP9-3j
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:58:40 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES256-SHA:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1biJW1-0007yS-RC
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:58:38 -0700
Date: Fri, 09 Sep 2016 03:58:36 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1473418716;
	bh=TNCc++NUWduLp25sYs0Pf0YPFjGgu8dOfUqyOkJGd1M=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZxJvC8kzjSmHbnA2ZWpvBqvtE7gboGLkli4N1XXADGDyWdF+IspCdALctY/1KJG1d
	 bzWna1vImCGGG3PNq0Yu5+TIGD9f7ahOG5eQ9wxVFfXDpuMua0DG1bCmhbbKJB8MoR
	 R1G5HaJ7/BcpiFOruMLJykIBYyQ1zYNKsw9xbdXI=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (74/60 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:55734)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJX0-003Lqc-Lg
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:59:40 +0000
Received: from o3.sgmail.github.com ([192.254.112.98])
	by filter01.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES128-SHA:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJWx-0008Ua-4C
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:59:38 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ogzg0veP1PtIZ0JcJYxxBNccXoc=; b=KWqHrDn5ZQeRzkLM
	PxTRcU3kanJ8n53dllxSFCq3JAo/lh8gbNf+o8kQgFWNSPmXIe6Ca/gFTUvRwPK6
	4wCmvdwzcFc8Lu9G7ZJS8peC77VVrvVgkjOG678mgyc52Ys1fPaO3fhHp21rkK36
	VvbU9tomu+YiUuxiiO1VxmdDULc=
Received: by filter0509p1mdw1.sendgrid.net with SMTP id filter0509p1mdw1.24831.57D295EC29
        2016-09-09 10:58:52.427509522 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id xj9amhgTRk2NANUjuymTtw
	for <bunny@thumbmunkeys.com>; Fri, 09 Sep 2016 10:58:52.355 +0000 (UTC)
Date: Fri, 09 Sep 2016 03:58:52 -0700

**Pull request closed without merging**
