### PR TITLE
A few NavigationExperimental improvements

### PR DESCRIPTION
**Pull request by brentvatne**
Very small details I came across while reading it, cc @ericvicenti

### CODE REVIEW

**Comment by satya164** [comment]
It's been 2 days, and Travis status is still pending O.o

**Comment by bestander** [comment]
That may happen, I think another push would fix it

**Comment by facebook-github-bot-5** [comment]
@ericvicenti would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by satya164** [comment]
@brentvatne can you rebase against master? :)

**Comment by brentvatne** [comment]
err I have no idea what happened there, rebased and it's showing no changes? lol oh well

**Comment by satya164** [comment]
O.o

**Pull request closed without merging**
