### PR TITLE
Update 0.29 "Image" document

### PR DESCRIPTION
**Pull request by EcutDavid**
We have to specify image size from style in 0.29, otherwise, there gonna be no image displayed.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@EcutDavid Thanks. Can you please sign the CLA so we can consider merging this?

@grabbou @bestander Are you ok with this going into 0.29?

**Comment by JoelMarcey** [comment]
Actually, we need this to into `master` first -- otherwise it won't propagate to later versions.

**Comment by bestander** [comment]
@JoelMarcey, you are right, no objections

**Comment by JoelMarcey** [comment]
ping @EcutDavid re: CLA and changing to `master` branch?

**Comment by hramos** [comment]
@EcutDavid please open a new PR against master, thanks!

**Pull request closed without merging**
