### PR TITLE
[Cosmetic] Minor typos

### PR DESCRIPTION
**Pull request by SellaRafaeli**

### CODE REVIEW

**Comment by brentvatne** [comment]
Won't merge cleanly anymore :( Can you rebase and push please @SellaRafaeli?

**Comment by sahrens** [comment]
@SellaRafaeli - can you rebase this and update?

**Comment by skevy** [comment]
@SellaRafaeli pinging on this...can you rebase and update?

**Comment by ide** [comment]
@sahrens could you import the TextInput change?

**Comment by SellaRafaeli** [comment]
I don't understand exactly what you mean - but it's just two typos. Perhaps I should open a new PR and just fix them there?

**Comment by chirag04** [comment]
@SellaRafaeli You can rebase and update your PR or create a new one.

Here is a link if you need help with rebasing: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by brentvatne** [comment]
New PR would work @SellaRafaeli!

**Pull request closed without merging**
