### PR TITLE
Change method name color for API/Component methods

### PR DESCRIPTION
**Pull request by JoelMarcey**
Test Plan:

Old:

screenshot 2016-06-28 18 16 03

New:

screenshot 2016-06-28 18 17 05

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @Andreyco and @caabernathy to be potential reviewers.

**Comment by JoelMarcey** [comment]
I am just going to land this so I can cherry-pick this and the NavigationExperimental tutorial into 0.29 -- and then we can officially close this lockdown out, I think :)

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/293108821078626/int_phab) to review.

**Pull request closed without merging**
