### PR TITLE
Fabric: DatePicker

### PR DESCRIPTION
**Pull request by ericlewis**
## Summary

Add DatePicker to Fabric. This is a wip. Outstanding question around how we deal with native date primitives in fabric, this means the date prop / onDateChanged props / events are not functioning.

## Changelog

[iOS] [Added] - Fabric: DatePicker

## Test Plan

Run RNTester with Fabric, observe that DatePickerIOS example works correctly.

### CODE REVIEW

**Comment by cpojer** [comment]
Thanks for doing this. Since we are actually extracting this component to a separate repo as part of Lean Core, I don't think we'll merge this.

**Comment by grabbou** [comment]
@ericlewis please let me know where I can follow this work further! Its interesting to see how the actual component migration looks like after all the Fabric internal discussions.

I am particularly interested in other files that need to be added. Maybe we can have a chat on Discord? :D

**Comment by ericlewis** [comment]
@grabbou more than happy to chat on Discord. It’s been quite a lot of fun playing with the system, especially with how easy it is to get something bound and working fairly quickly. I’ll continue to post on Twitter / discord my discoveries.

**Comment by ericlewis** [comment]
Also, for anyone who runs across this in the future: the answer to date primitive in fabric (as of this comment) is you can pass in dates as floats (FloatTypeAnnotation) because they are represented by JSI as floats. I haven’t figured out how to get it to work in the opposite direction however. Heheh.

**Comment by cpojer** [comment]
Also yeah, just wanna make clear: I love that you are doing this :)

**Comment by ericlewis** [comment]
@cpojer no worries! I have figured out a way to be able to “sideload” components that are missing, so dev is still easy :) trying to come up with a plan for how to apply this to components for 3rd parties & thing I have a fairly workable system going.

**Pull request closed without merging**
