### PR TITLE
Add RCT_EXTERN_REMAP_METHOD

### PR DESCRIPTION
**Pull request by rockwotj**
## Summary

The macro _RCT_EXTERN_REMAP_METHOD stated that RCT_EXTERN_REMAP_METHOD exists, but it does not.
This adds in the macro that allows for externing a method but choosing a custom JavaScript name.
We write all of our modules in Swift, so this is useful so we don't have to set all
of the argument labels properly to match up the Swift signature with the ObjC one.

## Changelog

[iOS] [Added] - Added RCT_EXTERN_REMAP_METHOD macro for externing a method with a custom JavaScript  name.

## Test Plan

My iOS app has already switched to calling `_RCT_EXTERN_REMAP_METHOD` with this signature, and it's a trivial change. However, I am happy to add a unit test somewhere if it's useful, but a point in the right place of where to add such a test would be appreciated.

### CODE REVIEW

**Comment by rockwotj** [comment]
@bigfootjon Why was this closed?

**Comment by yungsters** [comment]
Sorry, we are working through some remaining issues with renaming the `master` branch to `main` and this PR was accidentally closed. We're working on fixing the affected PRs.

**Comment by yungsters** [comment]
@rockwotj — I am suspecting that during the GitHub branch migration, this PR fell through the tooling cracks and got closed because the source repository no longer exists (and therefore this PR was not able to be redirected to the `main` branch).

Can you confirm whether the `subspace-team:rockwood/macro` repository is indeed deleted? And would you mind resubmitting this from an active repository?

I am terribly sorry for the inconvenience. (I am also still trying to better understand what went wrong here and whether this behavior was expected.)

**Comment by rockwotj** [comment]
@yungsters I've created an new fork and PR for these changes in #31875

The repo did get deleted (oops I thought this PR was using a different repo...)

**Comment by rockwotj** [comment]
No worries about the accident, and thank you for a quick response and explanation. Accidents happen and nobody got hurt :)

**Pull request closed without merging**
