### PR TITLE
update showcase.js

### PR DESCRIPTION
**Pull request by Menq**
add 一休 app to show case

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by bestander** [comment]
@Menq, could you please  rebase on master http://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master.
The tests are failing because the commit is based on a very old commit.

**Comment by Menq** [comment]
@bestander thanks , I will do this later

**Comment by janicduplessis** [comment]
Closing this PR, merged in #7611

**Pull request closed without merging**
