### PR TITLE
move prettier to peerDeps in eslint-config-react-native-community

### PR DESCRIPTION
**Pull request by sasurau4**
## Summary

In monorepo environment, prettier-plugin in some editor load from nearest `node_modules`. Older version of eslint-config-react-native-community includes prettier v1 in their dependencies. It cause conflict of code style inside the monorepo.

## Changelog

[Internal] [Fixed] - move prettier to peerDependencies in eslint-config-react-native-community

## Test Plan

I think it would be good with no plan to test.

### CODE REVIEW

**Comment by sasurau4** [comment]
I want to review it. Anyone knows I should mention whom?

**Comment by matt-oakes** [comment]
@cpojer Do you know who would be the best person to look into this?

**Comment by sasurau4** [comment]
@charlesbdudley rebased, thanks for your comment :+1:

**Comment by matt-oakes** [comment]
@charlesbdudley Thanks for merging this. Can you also take a look at and merge #32117 so I can release these changes to NPM?

**Comment by matt-oakes** [comment]
Published to NPM as `3.0.1`

**Pull request closed without merging**
