### PR TITLE
Do not expose define references in require polyfill

### PR DESCRIPTION
**Pull request by jgable**
See #406

Made sure the jest tests pass but didn't know a good unit test to add for this.

### CODE REVIEW

**Comment by vjeux** [comment]
I would just comment the line global.define = define; I'm really not sure why it is there if it is not working

cc @amasad

**Comment by NovaDev94** [comment]
I think if we don't want to support AMD-style module exporting then just commenting `global.define = define` would be better.

**Comment by jgable** [comment]
Updated to remove references of `global.define` and `_register('define', define)`.  

Still works in my app, and the jests pass.  Totally legit test plan right?

**Comment by NovaDev94** [comment]
We don't have the tests for *require* polyfill at the moment, afaik. And I
also think that it's necessary to make a test for that case.

On Monday, March 30, 2015, Jacob Gable <notifications@github.com> wrote:

> Updated to remove references of global.define and _register('define',
> define).
>
> Still works in my app, and the jests pass. Totally legit test plan right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/pull/427#issuecomment-87474424>.
>


-- 
Regards,
Truong Ngoc Dai

**Comment by amasad** [comment]
Happy to pull this but this tracks our internal require system. If `define` doesn't work I would want to have an understanding of why first.

**Comment by jgable** [comment]
I had a feeling something with static_upstream was gonna eff this up.  It looks like you are doing some custom stuff in your define method that the rest of the AMD world doesn't do.  Also, the npm modules would call that define function from different path roots that you would have to keep track of.

It seems like a huge pain to support proper define usage for npm modules.  In the meantime, this fix would allow a great swatch of npm modules to be used as expected.

**Comment by jgable** [comment]
On a whim, I messed around with seeing if the `NodeDependencyResolver` would work, but it looks like it's a non-starter.  It doesn't export a class that the `createDependencyResolver` function is expecting.  Even after hacking it into a class there is another error, not sure that it's a fruitful path.

**Comment by amasad** [comment]
It's dead code at this point. Since we had to stick to a mixed mode of providesModule and node dependencies haste is the only one that lived. I might as well just delete that code.

**Comment by amasad** [comment]
This landed, will publish a new version soon.

**Pull request closed without merging**
