### PR TITLE
remove a typo

### PR DESCRIPTION
**Pull request by sunnylqm**
I can't guess the point. Just simply removed this typo.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks @sunnylqm

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@mkonicek the shipit bot _really_ doesn't like me. :-p

**Comment by satya164** [comment]
@skevy Not only you, it seems to be happening for everyone.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
