### PR TITLE
Turn to ES6

### PR DESCRIPTION
**Pull request by sunnylqm**

### CODE REVIEW

**Comment by xlilien** [comment]
+1

**Comment by corbt** [comment]
@mkonicek would Facebook be ok with contributors migrating the example apps to ES6? I ask because it would be good to keep these docs in line with the code in `Examples/` directory so people learning RN don't have to juggle two syntaxes.

**Comment by mkonicek** [comment]
@davidaurelio @martinbigio Do you remember why we don't use ES6 classes internally at fb to declare React components?

**Comment by mkonicek** [comment]
I assume ES6 works fine in open source?

**Comment by corbt** [comment]
@mkonicek relevant: https://github.com/facebook/react-native/pull/1993#issuecomment-142427167

**Comment by mkonicek** [comment]
Sounds good, ship it :)

**Comment by davidaurelio** [comment]
yes, ship it. We don’t use them extensively internally b/c nobody wants to change existing code that works.

**Comment by corbt** [comment]
@facebook-github-bot shipit

**Comment by corbt** [comment]
@sunnylqm thanks. If you really want to go the extra mile you can open a new PR and update the code in the `Examples/Movies` app to match this format as well. :wink:

**Comment by mkonicek** [comment]
:+1:

**Comment by sunnylqm** [comment]
@corbt https://github.com/facebook/react-native/pull/5758

**Pull request closed without merging**
