### PR TITLE
fix banner for old node version

### PR DESCRIPTION
**Pull request by johannes-scharlach**
The file is used to notify users when they are using a node version < 4. Therefore we should not allow arrow functions. This was pointed out at the time when the arrow function was introduced but merged anyways: https://github.com/facebook/react-native/commit/db3a00d58c87f7ecfe7fb12a988a058ea46d0be8#commitcomment-16590379

Trying to run the code with Node version 0.10.32

Before:
```
…/node_modules/react-native/local-cli/server/formatBanner.js:48
    chalkFunction: (fn) => fn,
                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (…/node_modules/react-native/local-cli/server/checkNodeVersion.js:12:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

After:
```
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  You are currently running Node v0.10.32.                                  │
 │                                                                            │
 │  React Native runs on Node 4.0 or newer. There are several ways to         │
 │  upgrade Node.js depending on your preference.                             │
 │                                                                            │
 │  nvm:       nvm install node && nvm alias default node                     │
 │  Homebrew:  brew unlink iojs; brew install node                            │
 │  Installer: download the Mac .pkg from https://nodejs.org/                 │
 │                                                                            │
 │  About Node.js:   https://nodejs.org                                       │
 │  Follow along at: https://github.com/facebook/react-native/issues/2545     │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
```

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @Kureev to be a potential reviewer.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/861783630594036/int_phab) to review.

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Pull request closed without merging**
