### PR TITLE
Small typo s/they/the/

### PR DESCRIPTION
**Pull request by denmark**

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @JoelMarcey to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hramos** [comment]
Thank you! Let's see if the bot cooperates now.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
I cannot do that @hramos, because @denmark does not have an active CLA on file.

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
I cannot do that @hramos, because @denmark does not have an active CLA on file.

**Comment by hramos** [comment]
@facebook-github-bot-2 if that's so, why did @facebook-github-bot-3 and @facebook-github-bot-7 add the CLA Signed label?

**Comment by sdwilsh** [comment]
Uh, I think the bot is drunk, and to test that theory, I need to comment.  Please ignore this comment while I investigate the issue.

**Comment by sdwilsh** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/611146609060781/int_phab) to review internal test results.

**Pull request closed without merging**
