### PR TITLE
Remove Gemfile.lock from template

### PR DESCRIPTION
**Pull request by danilobuerger**
## Summary

For the same reason we don't keep a yarn.lock or Podfile.lock, we shouldn't be keeping a Gemfile.lock in the template. The user will generate this on his own pulling in the current dependencies with the constraints in Gemfile. No need to lock to a specific version.

cc @barbieri (author of https://github.com/facebook/react-native/pull/32303)
cc @ravirajn22 (for raising the issue)

## Changelog

[iOS] [Fixed] - Remove Gemfile.lock from template

## Test Plan

no test plan

### CODE REVIEW

**Comment by cortinico** [comment]
I suppose the CI failure is unrelated?

**Comment by danilobuerger** [comment]
@cortinico I think its coming from a recent commit to main: https://github.com/facebook/react-native/commit/45e2941367fbf13584193bbda598173802289167 If nobody is on it already, I could try fixing it in a separate pr?

**Comment by barbieri** [comment]
sorry taking long, but looks good to me :-)

**Comment by cortinico** [comment]
> @cortinico I think its coming from a recent commit to main: [45e2941](https://github.com/facebook/react-native/commit/45e2941367fbf13584193bbda598173802289167) If nobody is on it already, I could try fixing it in a separate pr?

I've realized it's a failure related to a missing version of `react-native-codegen`. I'm on it as this needs to be done internally, but thanks for offering to look into this @danilobuerger 🙏

**Pull request closed without merging**
