### PR TITLE
[GENERAL] Add .nvmrc + fix node version for eslint 5 compat

### PR DESCRIPTION
**Pull request by slorber**
A .nvmrc file is practical when working on many node projects with different version requirements.

Also, the current required node engine is incompatible with eslint5 requirements:

```js
  "engines": {
    "node": ">=8"
  },
```

It produces the following warning on install:

> error eslint@5.0.1: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
> error Found incompatible module

I made the requirement compatible with eslint5 requirements

Test Plan:
----------

`yarn test` is still passing

Release Notes:
--------------

[GENERAL] [ENHANCEMENT] Add .nvmrc and ensure node version required is compatible with ESLint 5

### CODE REVIEW

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :lock: package.json - <i>Changes were made to package.json. This will require a manual import by a Facebook employee.</i>
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  :clipboard: Release Notes - <i>This PR appears to be missing Release Notes.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by slorber** [comment]
not sure exactly why ios e2e tests are failing on CI, any idea?

**Comment by slorber** [comment]
Ok thanks, I'll update my PR with doc + checkNodeVersion to 8.10 soon

**Comment by slorber** [comment]
@janicduplessis actually not sure if I should make the changes you wanted

ReactNative can actually work for node >= 8.3, it's just ESLint which requires 8.10. So it may be a good idea to have a .nvmrc 8.10 for contributors, but not necessary to force end users to use 8.10 as they won't run ESLint anyway. I don't think the engines attribute allow that granularity between distinct version requirement for devtools and consumer code.

Maybe it's better to let engine >= 8.3 and only add nvmrc for a recommended contributor version to use?

cc @hramos who changed the version recently: https://github.com/facebook/react-native/pull/20236/files

**Comment by hramos** [comment]
@slorber that approach sounds good - let's use engine for end-user minimum required Node version, .nvmrc for contributors.

**Comment by slorber** [comment]
ok,

I've reverted the PR's code to only add a .nvmrc and let the engine >= 8.3

**Pull request closed without merging**
