### PR TITLE
docs(AppState.js): update example to ES6

### PR DESCRIPTION
**Pull request by goldylucks**
If this is the way to go, I'll update the rest of the document :)

> Explain the **motivation** for making this change. What existing problem does the pull request solve?

- Update basic usage to latest ES6-7 syntax
- Provide a working simple example of using AppState

### CODE REVIEW

**Comment by hramos** [comment]
Thank you, just one small nit, no space between the method name and parens: `render()`

**Comment by goldylucks** [comment]
@hramos 
the cirecleci is failing:
`Unable to download: mvn:org.easytesting:fest-util:jar:1.2.5`

Is that related to my changes?
(I assume not since I only touched documentations)

**Comment by hramos** [comment]
@goldylucks unlikely to be related. I'm working on solving these failed imports.

**Comment by goldylucks** [comment]
@hramos, why is the commit on your name?

it might be a dumb question, it's my first contribution to react-native :)

**Pull request closed without merging**
