### PR TITLE
Add borderWidth prop to the View Style documentation

### PR DESCRIPTION
**Pull request by Crash--**

### CODE REVIEW

**Comment by mkonicek** [comment]
Look OK but how do you test this doesn't break anything?

**Comment by mkonicek** [comment]
Note it's not just documentation, it's used for validation in a few places.

**Comment by Crash--** [comment]
Oh. I thought it was just about documentation. 

I just ran 2018 and Sample App with this modification and they are still working, at least on iOS.

**Comment by ide** [comment]
A good example to check is the UIExplorer which has a demo for borders.

**Comment by Crash--** [comment]
Seems to work like a charm. 

Note that in the exemple, available in the current documentation, use this property but it's not listed in the style section (https://facebook.github.io/react-native/docs/view.html#content).

**Comment by ide** [comment]
@Crash-- thanks for verifying!
@mkonicek shipit?

**Comment by Crash--** [comment]
See #3133

**Pull request closed without merging**
