### PR TITLE
bump android gradle plugin to 3.4.1

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

bump android gradle plugin to 3.4.1, includes many fixes and improvements.

## Changelog

[Android] [Changed] - bump android gradle plugin to 3.4.1

## Test Plan

RNTester builds and runs as expected

### CODE REVIEW

**Comment by gengjiawen** [comment]
Can you rebase to trigger the CI again, make sure android related build pass.

**Comment by hramos** [comment]
`test_android` is broken in this PR, can you rebase and see if that clears it up?

**Comment by dulmandakh** [comment]
@hramos rebased, and Android CI is green.

**Comment by dulmandakh** [comment]
@hramos please merge this before 0.60. Thank you

**Pull request closed without merging**
