### PR TITLE
[Android] Remove Stetho dependency from ReactAndroid

### PR DESCRIPTION
**Pull request by AndrewJack**
**Fixes**: #6131 
Stetho is a debug dependency which should not be included in releases. It unnecessarily bloats the apk size.

This change removes the dependency from the ReactAndroid library and adds an example Stetho implementation to the Android template. 

### Test plan
1. `react-native init StethoExample`
2. Update `package.json` to use `git@github.com:facebook/react-native.git#master`
3. `npm install` & `react-native upgrade`
4. Clone `https://github.com/AndrewJack/react-native/tree/remove_stetho_from_react_android`
5. Update the `android/build.gradle` file as specified in the building from source [guide](https://facebook.github.io/react-native/docs/android-building-from-source.html). Specify the ReactAndroid folder in the repo you just cloned.
6. Update `android/app/build.gradle` dependencies to use the module ReactAndroid. `compile project(':ReactAndroid')`
7. Configure Stetho to only compile with debug by using `debugCompile`
2. `cd StethoExample/android && ./gradlew app:assembleRelease`
3. Find APK in `StethoExample/android/app/build/outputs/apk`
4. Open apk in [ClassyShark](https://github.com/google/android-classyshark)
5. See Stetho not included in APK

### CODE REVIEW

**Comment by kmagiera** [comment]
Maybe @foghina can help with this one?

**Comment by AndrewJack** [comment]
Built apps using this branch's version of ReactAndroid.
Sample code here: https://github.com/AndrewJack/react-native-test/tree/6342_stetho

## Debug APK with Stetho
Debug APK

## Release APK without Stetho
Release APK

**Comment by mkonicek** [comment]
I think we use Stetho internally though? I'll post about it in our internal group to find out if it's used.

**Comment by mkonicek** [comment]
Just asked:

screen shot 2016-03-10 at 8 02 43 pm

**Comment by AndrewJack** [comment]
Stetho isn't enabled by default, at least in the OS version of RN, until you call `StethoUtil.initialize(this);` anyway.

Thanks for looking at this.

**Comment by mkonicek** [comment]
Np! The fb apps probably enable Stetho using `initializeWithDefaults` and then rely on Stetho being registered in the `NetworkingModule.`

**Comment by mkonicek** [comment]
In retrospect it wasn't an ideal choice to add Stetho directly into the open source module.

**Comment by mkonicek** [comment]
Removing Stetho from the OSS networking module is still work in progress internally. Will comment here once we can proceed with this PR.

**Comment by mkonicek** [comment]
Update: the internal diff is making some progress, it's been reviewed and is accepted now :)

**Comment by AndrewJack** [comment]
@mkonicek Great news! Is there anything that needs completing on my side?

See you at London React tonight! I'm looking forward to your talk.

**Comment by mkonicek** [comment]
Sorry for the delay @AndrewJack and sorry I missed you at the meetup. I only saw the notification now as I was on vacation.

Thanks to this PR and the discussion it started the Stetho dependency is now removed from React Native:
https://github.com/facebook/react-native/commit/3c488afb0fa09c7fc1189f3e4c0932c28045f065

**Comment by mkonicek** [comment]
Stetho is quite advanced for most users, I don't think we should add the Stetho example (`MainApplication.java`) to every RN app. Might be better to publish it as a blog post for example. What do you think?

Are you happy with https://github.com/facebook/react-native/commit/3c488afb0fa09c7fc1189f3e4c0932c28045f065? Do you want to make some additional changes on top of it?

Thanks again for making us remove the bloat! :+1:

**Comment by AndrewJack** [comment]
@mkonicek I enjoyed your talk, I had a great chat with @foghina, as you seemed rather busy.

I'll remove the Stetho code from the Android template then it'll be good to go.

**Comment by mkonicek** [comment]
OK I'll close this PR, thank you Andrew.

**Comment by mkonicek** [comment]
Oh yeah I should kill the BUCK file: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/third-party/java/stetho/BUCK

**Pull request closed without merging**
