### PR TITLE
Resolve single flow error in node-haste

### PR DESCRIPTION
**Pull request by skevy**
Makes flow pass.

### CODE REVIEW

**Comment by skevy** [comment]
cc @ericvicenti

**Comment by cpojer** [comment]
What's the flow error? It seems like we can fix that without a FlowFixMe?

**Comment by skevy** [comment]
Ok. I'll actually fix it. :(

**Comment by skevy** [comment]
I just wasn't concerned with actually fixing it, since it was my impression we were moving off of node-haste in the future. :-p

**Comment by skevy** [comment]
And was trying to fix a bug in another tangentially related project and get Flow to pass.

**Comment by cpojer** [comment]
That's a little while off. I'd prefer to fix type errors properly.

**Pull request closed without merging**
