### PR TITLE
Added HackerWeb App to website showcase

### PR DESCRIPTION
**Pull request by cheeaun**
Adding my HackerWeb iOS app to the app showcase.

### CODE REVIEW

**Comment by chirag04** [comment]
@facebook-github-bot shipit

**Comment by grabbou** [comment]
@chirag04 do we have to shipit again?

**Comment by chirag04** [comment]
yeah. I think the import failed. you want to give it a go one more time?

**Comment by grabbou** [comment]
Yeah, let's try :8ball: 

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Something's up, don't see anything in the cron job logs. Will use this PR as a test case for debugging.

**Comment by mkonicek** [comment]
Please don't add more comments so I can use this PR for testing :)

@cheeaun We'll eventually merge this, either using the bot or manually. Thanks for the patience.
If you're interested in what the `@facebook-github-bot shipit` does under the hood, check out this presentation I made: https://speakerdeck.com/mkonicek/under-the-hood-of-react-native?slide=45

**Comment by cheeaun** [comment]
@mkonicek cool, thanks! 👍😁

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
just checking :)

**Comment by mkonicek** [comment]
:)

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
OK the issue is that the PR summary contained an emoji which the import doesn't support.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
