### PR TITLE
[android] Inline and fix proguard rules

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
The original proguard rules are put in the template, which is not very convenient and easy to get wrong. Because new rules get put, people also has two copy paste the rule. And there are also existing project import react native as a dependency. So the best way to  keep a android library project proguard rule is to manage the rule itself, using `consumerProguardFiles` like [dagger](https://github.com/JakeWharton/butterknife/blob/46baef6d96e93a1872efa17fdfc1d2af59b36f0c/butterknife/build.gradle#L9) and other android library project.

## Test Plan

Use RNTester to build the release flavor (now it has bugs https://github.com/facebook/react-native/issues/18460, I keep my change in local for now), after build success, run to check if crash.

In the process, I also fix https://github.com/facebook/react-native/issues/12994 and https://github.com/facebook/react-native/issues/6624 by adding the following to proguard rules
```proguard
-keep,includedescriptorclasses class com.facebook.react.bridge.** { *; }
```

## Release Notes

[ANDROID] [ENHANCEMENT and BUGFIX] [Proguard rules] - inline and fix proguard rules .

### CODE REVIEW

**Comment by hramos** [comment]
The current test_android failure already exists on master. We'll need to fix that so you can rebase and ensure Android tests are green.

**Comment by gengjiawen** [comment]
Can the ci thing fixed in today ?

**Comment by hramos** [comment]
Of course.

**Comment by gengjiawen** [comment]
@hramos Any chance we can fix ci asap, this pr has stuck for a while.

**Comment by hramos** [comment]
@gengjiawen the major issues in the Android job were fixed a week or two ago. That fix surfaced some failures in the unit tests. Fixing those is not something that is a priority for me at the moment, and PRs to fix them would be appreciated.

**Comment by gengjiawen** [comment]
I will try to fix it, though I have few knowledge about buck.

**Comment by hramos** [comment]
If you're seeing buck errors, you may want to rebase. `test_android` is failing on master due to failing unit tests, not buck: https://circleci.com/gh/facebook/react-native/39551

In any case, the failing Android job shouldn't block your PR from being reviewed. These unit tests are failing on master and are unrelated to your changes.

**Pull request closed without merging**
