### PR TITLE
Update TouchableOpacity.js

### PR DESCRIPTION
**Pull request by Obooman**
Touchable element with user interface feedback need to update status immediately.Improve pressing dull feeling.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-9** [comment]
@Obooman updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@Obooman updated the pull request.

**Comment by ide** [comment]
This isn't right -- the opacity shouldn't instantaneously change if you drag your finger out of the button's hit box and back in. Making this change requires change to the TouchableMixin library and is a lot more than 1 line.

**Comment by Obooman** [comment]
@ide You are right.The button opacity change immediately ONLY on the first hit to the hit box.when drag finger out and in it changes with transition.I'll update this.

**Comment by Obooman** [comment]
@ide I find that when touchable mixin dispatch hit event there's a payload with `registrationName`.I think this is a user Interactive problem so distinguishing event types is a better solution,we only need to modify TouchableOpacity.js.I'll update the pr later.

**Comment by facebook-github-bot-6** [comment]
@Obooman updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@Obooman updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@Obooman updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@Obooman updated the pull request.

**Pull request closed without merging**
