### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by hramos**
Provide a sample new issue template to encourage people to provide additional detail as needed. This should help us reduce the number of new issues that are opened without sufficient information or actionable requests.

The minimal use of markdown is intentional, as these guidelines are more likely to be found in raw text inside the [new issue composer](https://github.com/facebook/react-native/issues/new) rather than rendered to HTML.

### CODE REVIEW

**Comment by mkonicek** [comment]
@hramos Is this good to go? Should we ship it as-is? I was going to merge it now but asking in case you're working on it.

**Comment by hramos** [comment]
@mkonicek it's good to go

**Comment by facebook-github-bot-8** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @mkonicek as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by hramos** [comment]
@facebook-github-bot shipit-ninja

**Comment by facebook-github-bot-6** [comment]
Normally, hramos, someone else should review and ship your pull request. However, we will trust that you know what you are doing. Shipping!

**Comment by facebook-github-bot-0** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3785606) to review internal test results.

**Pull request closed without merging**
