### PR TITLE
keyboardShouldPersistTaps:default value is false

### PR DESCRIPTION
**Pull request by hufeng**

### CODE REVIEW

**Comment by ide** [comment]
The current default is much less surprising -- it's not obvious that tapping the scroll view should hide the keyboard. Doing nothing seems like a better default to me.

**Comment by satya164** [comment]
It was `false` previously, and changed to `true` in 0.15 I think.

In the app I'm working on, there are 3 scenarios where I don't want the keyboard to be dismissed, and only 1 scenario where I want it to be dismissed. So I agree with @ide

**Comment by hufeng** [comment]
ok, I agree with @ide

**Comment by ide** [comment]
OK. I will close this PR.

**Pull request closed without merging**
