### PR TITLE
Typo.

### PR DESCRIPTION
**Pull request by chrisharrington**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@chrisharrington Thanks! Can you please the CLA so I can merge this in?

**Comment by chrisharrington** [comment]
Done!

**Comment by JoelMarcey** [comment]
So this would be a direct merge into `0.29-stable`. But we need this to into `master` first; otherwise, it would never propagate to later versions. Can you make it `master` instead.

**Comment by hramos** [comment]
Thanks for your pull request! 

Can you [change the base branch](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) to `master` as required in the [Pull Request template](https://github.com/facebook/react-native/blob/master/.github/PULL_REQUEST_TEMPLATE.md)?

**Comment by m3vaz** [comment]
This typo was fixed in 55bc825

**Comment by facebook-github-bot-2** [comment]
@chrisharrington do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by mkonicek** [comment]
@chrisharrington I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment requests changes. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to send a new pull request for the master branch.

**Pull request closed without merging**
