### PR TITLE
Move step by step guide closer to top

### PR DESCRIPTION
**Pull request by dmkato**
## Summary

The step by step guide is pretty buried in the rest of the more technical documentation. It could make the page more accessible to move the step by step guide closer to the top. 

## Changelog

[Internal] [Changed] - Moved step-by-step section of contributing.md closer to the top of the page.

## Test Plan

See git diff to ensure no other changes were made.

### CODE REVIEW

**Comment by cpojer** [comment]
@dmkato before I can merge this you'll need to sign the CLA: code.facebook.com/cla – It only takes a minute!

**Comment by hramos** [comment]
@dmkato while you're editing this document, do you mind adding a link to https://github.com/facebook/react-native/wiki/Issues under the Triaging Issues header? It's fine to do so in another PR if you prefer.

**Comment by cpojer** [comment]
Hey @dmkato! Did you have any chance to take a look at the CLA so we can merge this?

**Comment by cpojer** [comment]
Unfortunately I cannot merge this PR without the CLA signed.

**Pull request closed without merging**
