### PR TITLE
Add support for new iOS text content type cellular EID and cellular IMEI

### PR DESCRIPTION
**Pull request by pasc0al**
## Summary:
Support for new iOS text content type to autofill cellular EID or cellular IMEI:
- https://developer.apple.com/documentation/uikit/uitextcontenttypecellulareid?language=objc
- https://developer.apple.com/documentation/uikit/uitextcontenttypecellularimei?language=objc

## Changelog:

[IOS] [ADDED] - new text content type cellular EID and cellular IMEI
## Test Plan:

JavaScript Tests - yarn test [PASSED]
- No errors related with the changes

Flow - yarn flow && yarn lint [PASSED]
- No errors related with the changes

iOS Tests - ./scripts/objc-test.sh test [PASSED]
- No errors related with the changes

Build RNTester [PASSED]
- No errors related with the changes
- Proof: 
Screenshot 2024-09-07 at 12 06 48
Screenshot 2024-09-07 at 12 07 29
Screenshot 2024-09-07 at 12 13 02

Simulator Screenshot - iPhone 15 Pro - 2024-09-07 at 12 06 36
Note: Since the test was done using an iOS simulator the autofill suggestion won't appear for the cellularEID or cellularIMEI

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]

**Comment by cipolleschi** [comment]
@pasc0al thanks for working on this!

**Comment by cipolleschi** [comment]
All the tests are failing with this error:
Screenshot 2024-09-10 at 12 24 30

@pasc0al  Can you look at it and fix it?

**Comment by pasc0al** [comment]
> All the tests are failing with this error: Screenshot 2024-09-10 at 12 24 30
> 
> @pasc0al Can you look at it and fix it?

Yes, I notice that the pipeline is targeting the iOS 17.0 - 17.2 and using Xcode 15.2
Screenshot 2024-09-10 at 20 12 55
Screenshot 2024-09-10 at 20 14 55
This feature was introduced in iOS 17.4, I believe by updating the pipeline configuration to use the latest Xcode version 15.3 and install the new iOS 17.4 SDK should work. I'm not aware the pipeline configuration file exists in the source code

**Comment by cipolleschi** [comment]
Thanks for looking into that.
Updating the pipeline is not the right fix, anyway. On top of surrounding the code with:
```objc
if (@available(iOS 17.4, *)) {
 // ...
}
```

you should also add the `#ifdef` that actually excludes the code from being compiled.
[This](https://github.com/facebook/react-native/blob/a05f9c6771167f0b30113aa7beae18beb0dcdd98/packages/react-native/React/Views/RCTView.m#L903) is an example of something like that

The first check is a runtime check: when the code runs, if the current os is 17.4, the code in the `if` branch is executed.
The second check is a compile time check. If the OS is 17.4, the code in the `#ifdef` is compiled. Otherwise it is stripped from the binary.

**Comment by pasc0al** [comment]
> Thanks for looking into that. Updating the pipeline is not the right fix, anyway. On top of surrounding the code with:
> 
> ```objc
> if (@available(iOS 17.4, *)) {
>  // ...
> }
> ```
> 
> you should also add the `#ifdef` that actually excludes the code from being compiled. [This](https://github.com/facebook/react-native/blob/a05f9c6771167f0b30113aa7beae18beb0dcdd98/packages/react-native/React/Views/RCTView.m#L903) is an example of something like that
> 
> The first check is a runtime check: when the code runs, if the current os is 17.4, the code in the `if` branch is executed. The second check is a compile time check. If the OS is 17.4, the code in the `#ifdef` is compiled. Otherwise it is stripped from the binary. We need both checks!

Condition added. Thanks for the tip

**Comment by pasc0al** [comment]
> > Thanks for looking into that. Updating the pipeline is not the right fix, anyway. On top of surrounding the code with:
> > ```objc
> > if (@available(iOS 17.4, *)) {
> >  // ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you should also add the `#ifdef` that actually excludes the code from being compiled. [This](https://github.com/facebook/react-native/blob/a05f9c6771167f0b30113aa7beae18beb0dcdd98/packages/react-native/React/Views/RCTView.m#L903) is an example of something like that
> > The first check is a runtime check: when the code runs, if the current os is 17.4, the code in the `if` branch is executed. The second check is a compile time check. If the OS is 17.4, the code in the `#ifdef` is compiled. Otherwise it is stripped from the binary. We need both checks!
> 
> Condition added. Thanks for the tip

**Comment by pasc0al** [comment]
Sorry pressed the wrong button

**Pull request closed without merging**
