### PR TITLE
Implement embedding of jsbundle as base64 data string to enable AppStore encryption discussed in #1093

### PR DESCRIPTION
**Pull request by anton-matosov**
Update project template to have bundle step before compiling sources
Implement loading of base64 URLs

for motivation and details see #1093 

Changes in project template:
 - Move `Bundle React Native code and images` step to the top to make it run before source code compilation
 - Modify `Bundle React Native code and images` by adding `export EMBED_JS_BUNDLE=1` before running `react-native-xcode.sh` in order to enable base64 jsbundle header instead of embedding it as plain text file
 - Modify `AppDelegate.m` by adding new include:
```
#define JSBUNDLE_GENERATED_HEADER "JSBundle.generated.h"
#if __has_include(JSBUNDLE_GENERATED_HEADER)
#  import JSBUNDLE_GENERATED_HEADER
#endif
```
 and replace 
`jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];` 
with:
```
#if __has_include(JSBUNDLE_GENERATED_HEADER)
  jsCodeLocation = [NSURL URLWithString:@"data:text/javascript;base64," JSBUNDLE_BASE64];
#else
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#endif
```

### CODE REVIEW

**Comment by kesha-antonov** [comment]
Nice +1

**Comment by jaygarcia** [comment]
How does base64 encoding the JS source protect the code from reverse engineering?

**Comment by jaygarcia** [comment]
Ugh. Nm. I had to read the linked post. Apologies :)

**Comment by anton-matosov** [comment]
Can anyone please review this PR?

**Comment by fungilation** [comment]
+1 for *some* code protection with minimal downside (in performance)!

**Comment by ide** [comment]
I'm pretty against this since it doesn't encrypt the code whatsoever -- encryption != encoding -- and moreover "client secret" is generally an oxymoron. False senses of security typically aren't good.

If you're OK with how websites work (send JS/WASM to the client, keep secrets on the server), RN is the same in the important ways.

**Comment by fungilation** [comment]
Read the original referenced #1093 first. 

> The advantage of embedding the source code in this way is that by including it as a string constant in your app (as opposed to a text file in the app resources) it will automatically be encrypted using Apple's FairPlay DRM when you upload it to the App Store.

**Comment by ide** [comment]
That's fine - please do this without the overhead of base64-encoding and also be clear about the security benefits this provides. Using this does not make your JS source code less insecure than it was before, but still not actually secure.

**Comment by anton-matosov** [comment]
Hi @ide. Implementation without base64 will be much trickier as Objective-C doesn't have raw strings, so I'll have to implement transformation code of JS into string literal. Loading code will also need to be changed to support this.
If this is the only blocker I'll do it. But I need to be confident that this change will go in, otherwise I'll just keep it in a fork as is.

**Comment by LeoNatan** [comment]
The overhead here for a large bundle is very large. A static resource in a Mach-O binary remains always loaded in memory. So if you have a 10-20MB JS bundle, you’d end up with a (4/3)*(10-20MB) static blob in memory and it will remain there until the process is terminated. 

Also, this is very easy to circumvent. Using a tool such as https://github.com/KJCracks/Clutch on a jailbroken device, and then using `strings`, in less then 5 minutes I’d have access to the full source code.

I suggest using a different approach, such as obfuscating your JS files and / or implementing a symmetric encryption of the JS bundle on disk, and hiding the key well enough in ObjC/Swift so that it is much harder to discover (not as a single static string). This is also relatively easy to break with a disassembler, but complicates enough for most people.

**Comment by ide** [comment]
Yeah. I tend to agree with what @LeoNatan is saying, plus at the end of the day this is how every single website works. Can someone explain what the goal here is?

**Comment by fungilation** [comment]
Better, though basic if that but simple and implicit code protection. If it poses performance/memory penalty, make it optional with addition arg to react-native bundle?

**Comment by jaygarcia** [comment]
Just wanted to ensure that this is linked: Complaints of performance.

https://github.com/facebook/react-native/issues/1093#issuecomment-291906048

**Comment by anton-matosov** [comment]
Seems to be not a good solution that is still super easy to crack (which is even documented how now ;) )

**Pull request closed without merging**
