### PR TITLE
[RNTester][IOS] Enable Address and Undefined Behavior Sanitizers

### PR DESCRIPTION
**Pull request by Saadnajmi**
## Summary

This change does two things:

1) Moves RNTester on iOS to use an `.xctestplan` to configure its tests. This moves the test configuration out of the `.xcscheme` file, and into a new json file that Xcode likes. It also allows you to run the same tests multiple times with different configurations. This was done by clicking the focused button below.

image

Note: this is partially me upstreaming a change from React Native macOS (https://github.com/microsoft/react-native-macos/pull/190/), though at some point our Xcode project got messed up and we were no longer referencing them 🤷🏾.

2) Enables Address Sanitizer and Udefined Behavior Sanitizer through the xctestplan

This should help catch some extra vulnerabilities should they ever show up while our tests run. 

Notably, I did not _also_ add a configuration to run Thread Sanitizer, because tests start failing with that enabled 😅.

## Changelog

[IOS] [SECURITY] - Enable Address and Undefined Behavior Sanitizers on RNTester

## Test Plan

CI should pass

### CODE REVIEW

**Comment by cipolleschi** [comment]
Hi @Saadnajmi, thank you for the PR. I'll have a more thorough look at it on Monday, but currently the `[RCTAnimationUtilsTests testColorInterpolation]` test is failing consistently in CI. Could you have a look at it, please?

**Comment by Saadnajmi** [comment]
> Hi @Saadnajmi, thank you for the PR. I'll have a more thorough look at it on Monday, but currently the `[RCTAnimationUtilsTests testColorInterpolation]` test is failing consistently in CI. Could you have a look at it, please?

Sure. I'll take a look in the next day or two. I think I reproed the same crash locally but wasn't sure if it was local or acutally because I enabled the new sanitizers. It'll be interesting to see if we can make that test better now :)

**Comment by Saadnajmi** [comment]
For reference, the error I'm seeing locally is as follows:
```
=================================================================
==56710==ERROR: AddressSanitizer: odr-violation (0x000123ef2a80):
  [1] size=56 'folly::exception_wrapper::uninit_' react-native/packages/rn-tester/Pods/RCT-Folly/folly/ExceptionWrapper.cpp:25:52
  [2] size=56 'folly::exception_wrapper::uninit_' react-native/packages/rn-tester/Pods/Flipper-Folly/folly/ExceptionWrapper.cpp:25:52
These globals were registered at these points:
...
```

It looks like ASAN doesn't like we pull in Folly from both Flipper-Folly and RCT-Folly. Perhaps we only enable the sanitizer if flipper is not compiled? Working on it..

**Review by cipolleschi — APPROVED** [review]
Great job, thank you for spending time in fixing the tests! :D

Let's see if the internal infra is happy about these changes! 😅

**Review by cortinico — APPROVED** [review]
Great stuff @Saadnajmi 👍

**Pull request closed without merging**
