### PR TITLE
Revert "Revert "fix border style without borderRadius""

### PR DESCRIPTION
**Pull request by skv-headless**

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @bestander and @trave7er to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
@skv-headless updated the pull request.

**Comment by skv-headless** [comment]
@bestander take a look please. revert of revert of #6789 😄

**Comment by mkonicek** [comment]
> revert of revert of #6789

we-need-to-go-deeper_inception

**Comment by mkonicek** [comment]
Yay!

screen shot 2016-05-04 at 8 36 34 pm

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
The bot might have been down.

@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/291476731190117/int_phab) to review.

**Pull request closed without merging**
