### PR TITLE
Fixed Typo in QuickStart-GettingStarted.md

### PR DESCRIPTION
**Pull request by denniske**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

Fixed typo.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @hramos to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@denniske Once you sign the CLA, I will accept and land this. Thanks.

**Comment by denniske** [comment]
@JoelMarcey Signed it. Do I have to upload the PDF here?

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by JoelMarcey** [comment]
@denniske Nope. All good.

**Comment by JoelMarcey** [comment]
@denniske Actually, we want this to go into `master`, not `0.27-stable`. Can you make this PR be merged into `master`?

**Comment by denniske** [comment]
Corresponding text has already been changed in master branch. No pull request needed anymore.

**Pull request closed without merging**
