### PR TITLE
Add Switch docs

### PR DESCRIPTION
**Pull request by mrcasals**
This PR adds docs for the cross-platform Switch component. It also reorders the components links alphabetically.

Discussion comes from #4186. Does it need anything alse to be merged?

### CODE REVIEW

**Comment by vjeux** [comment]
cc @sahrens: are we going to stop documenting/exposing SwitchIOS and SwitchAndroid?

**Comment by mrcasals** [comment]
You might want o to wait until we have some versioned docs before merging this. Also, it would be nice if we had a list of components that are missing in the docs.

**Comment by satya164** [comment]
@vjeux Shall we merge this? It's already in the release versions.

**Comment by vjeux** [comment]
Do it

**Pull request merged**
