### PR TITLE
Add Emoji Poetry to showcase.js

### PR DESCRIPTION
**Pull request by MikePodgorniy**
Emoji Poetry app for showcase page

### CODE REVIEW

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by grabbou** [comment]
Ah, did `shipit` by a mistake @mkonicek - do you think @facebook-github-bot will automatically reject w/o CLA signed? If not - would be cool to stop it!

Also @MikePodgorniy please sign the CLA :)

**Comment by MikePodgorniy** [comment]
@grabbou how to sign the CLA? :)
It's my first commit.

**Comment by MikePodgorniy** [comment]
@grabbou done

**Comment by grabbou** [comment]
Thanks!

@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
