### PR TITLE
implement NativeMethods on ART components

### PR DESCRIPTION
**Pull request by magicismight**
implement NativeMethods on ART components
Group,Text,Surface,Shape
now can use setNativeProps method on the ref

### CODE REVIEW

**Comment by brentvatne** [comment]
cc @spicyj @sebmarkbage

**Comment by facebook-github-bot-9** [comment]
@brentvatne would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by spicyj** [comment]
Sorry I missed this. We don't want to add native-specific APIs here; the goal is to have exact parity between the DOM and native implementations of React ART. In most cases you should just do a rerender anyway. If that doesn't work, I can try to suggest an alternative if you explain your use case in more detail.

**Comment by brentvatne** [comment]
@magicismight ^

**Comment by sebmarkbage** [comment]
Little known fact is that the web ART API does expose the underlying imperative API API, which is already inconsistent on refs. However, it is pretty much never used so I think the use case could need some elaborating.

Maybe I also suggest wrapping your ART code in a view that you manipulate with transforms if you're doing animations etc.

**Comment by magicismight** [comment]
Fair enough.
Thanks anyway.

**Pull request closed without merging**
