### PR TITLE
When the app is rotated, reload the root view.

### LINKED ISSUE #813: Rotating list view causes text to disappear and sometimes causes app to STB
Rotating the list view causes the text to disappear.  In some cases, the UIExplorer sample STBs. 

Perhaps the Flex layout has something to do with it?
```
 row : {
        flexDirection   : 'row',
        justifyContent  : 'center',
        padding         : 10,
        backgroundColor : '#F6F6F6',
    },
```

My App:
stb2

UIExplorer:
stb

### PR DESCRIPTION
**Pull request by siuying**
A simple fix to rotation issue: on rotate simply reload the root view. 

Ideally it should animate the changes, but until I figure out how to do that this should do.

~~Fixes~~ Workaround #813.

### CODE REVIEW

**Comment by drkibitz** [comment]
I appreciate this, but IMO I wouldn't call it a "fix" for #813.  This behavior would not be acceptable in any app of mine. Especially wouldn't want this to be the default behavior. Another stopgap for that issue would be to set alignItems on any single line text, or explicit width if you can manage. There isn't a solution for multiline that I can find now though.

**Comment by siuying** [comment]
@drkibitz Agreed! The actual fix should include figure out why the label is disappearing, properly relayout the views on rotate (#809), animate them ...etc.

**Comment by ide** [comment]
You probably want to layout the React views when the root view / native view controller roots are resized and I expect the end effect will look quite nice.

Agree with @drkibitz that I wouldn't want to blow away the entire app when the user rotates their device and in some ways is similar to crashing if the user loses their state. If this behavior is ok for your app I think it'd be better to keep this behavior in your own app's code.

**Comment by drkibitz** [comment]
@siuying Please take a look at https://github.com/facebook/react-native/pull/857

Don't think it fixes #809, but it should fix #813

**Comment by sahrens** [comment]
Yeah, this is not the right way to go. Also note that the UIExplorer app does do somewhat animated re-layout on rotation...

**Pull request closed without merging**
