### PR TITLE
improve RTL

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

Google recommends to use Gravity.START and Gravity.END instead of Gravity.LEFT and Gravity.RIGHT to support RTL better.

## Changelog

[Android] [Changed] - Improve RTL support

## Test Plan

CI is green, and RNTester works as expected

### CODE REVIEW

**Comment by sm2017** [comment]
@dulmandakh You are not improved RTL , your PR is a full bug and destroyed RTL feature

**Comment by sm2017** [comment]
> Nice!

@cpojer What the nice?! Why you approve it?

**Comment by dulmandakh** [comment]
We all make mistakes, and this is one of them while I was trying to improve
React Native on Android. I followed Google's recommendation, but it didn't
worked well on React Natice. Lessons learned, I should've tested it more
and should've asked someone with RTL experience to review. So sorry about
it.

Also, I would like ask you and others to participate in development, review
PRs that might affect your apps or areas you have experience with.

**Comment by sm2017** [comment]
@dulmandakh OK , no problem!
Thank you

**Pull request closed without merging**
