### PR TITLE
[fetch] Better feature detection for FormData/FileReader/Blob

### PR DESCRIPTION
**Pull request by oblador**
This PR bumps fetch to 0.9.0, the latest release and fixes broken feature detection originating in that self is not referring to `window.self` but an empty object. Assigning that object to window.self or GLOBAL won't work in the chrome dev tools because of CORS restrictions. This is a pragmatic solution but maybe not ideal. 

Background to the problem can be read here: https://github.com/facebook/react-native/issues/2376

### CODE REVIEW

**Comment by ide** [comment]
Seems good to me. Someone on the fb side will need to merge and test against their apps.

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by ppiekarczyk** [comment]
:wave: anything I can help with to move this along?

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Sorry about this, I was testing the import script and it failed. Now should land correctly

**Comment by paramaggarwal** [comment]
This is a fork of https://github.com/github/fetch, so these changes need to be made there too I believe. Otherwise when this fork is updated, these changes might be lost.

**Comment by vjeux** [comment]
@paramaggarwal wow, you are right...

**Pull request closed without merging**
