### PR TITLE
Add AVIPEO Social Network to showcase

### PR DESCRIPTION
**Pull request by neogermi**
We have just released a complete overhaul of our social network for professionals from the aviation community. The complete app is written in React Native 0.34 and is available in the iOS store as well as in the Google Play store.

### CODE REVIEW

**Comment by ericnakagawa** [comment]
@neogermi Sebastian, please sign our CLA so we can include your app in the showcase.

**Comment by neogermi** [comment]
Hi @ericnakagawa I just signed the CLA. Thank you.

**Comment by ericnakagawa** [comment]
@neogermi Your submission is missing a few things:

1/ An English-language news article discussing the app, built either by your funded startup or for a public company

2/ An English-language technical post on a your funded startup or public company blog discussing React Native

Use infoLink and infoTitle to reference this content.

**Comment by hramos** [comment]
Thanks for sending this pull request. According to the guidelines in that file, "infoLink" must be one of:

 1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native

I am going to close this, but if you have one of those two things, feel free to reopen with a new link.

**Pull request closed without merging**
