### PR TITLE
Cherry-pick 68af89d for node-haste upgrade

### PR DESCRIPTION
**Pull request by rozele**

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @bestander to be potential reviewers.

**Comment by bestander** [comment]
Hey, @rozele , you don't need to bump package.json version, we have a script that bumps all version when doing a release

**Comment by rozele** [comment]
@bestander Should I submit a new PR?

**Comment by rozele** [comment]
Closing because I don't know how to follow instructions.

**Comment by bestander** [comment]
A PR for branch 0.27-stable is fine, I can merge it directly.
Just no need to bump versions manually.
Go ahead reopen, better squash commits into one

**Comment by grabbou** [comment]
Yeah, or just reference the original commit that I can cherry-pick. Otherwise a PR w/o version bump is fine.

**Pull request closed without merging**
