### PR TITLE
Added example implementation for Android `<Portal>` per #2501

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by mkonicek** [comment]
We've been discussing whether to keep the portal implementation or ship a native module for showing modals instead.

In the Ads Manager we currently use the Portal to implement modals (https://gist.github.com/mkonicek/1a45b8f8c36bb710478c) but might deprecate that actually.

Would you mind holding with this until it's clear whether we'll go with the native module?

**Comment by niftylettuce** [comment]
@mkonicek are you asking me?  I think this should be accepted as a PR or a decision should be made ASAP, there needs to be native modal support on Android.

**Comment by mkonicek** [comment]
The decision is we'd like to go with the native module to implement [`Modal`](https://github.com/facebook/react-native/blob/master/Libraries/Modal/Modal.js) on Android, there's the PR #5320 but still need to figure out touch handling.

I agree we should clear out the list of missing Android modules as quickly as we can: https://facebook.github.io/react-native/docs/known-issues.html, a few releases from now it should be gone except for push notifications for which we only have an implementation very tied to the fb infra and using it in the Ads Manager on Android.

**Comment by satya164** [comment]
@mkonicek We should probably document <Portal /> since Modal is not going to be ready anytime soon.

**Pull request closed without merging**
