### PR TITLE
README: correct missing reference for contributing section

### PR DESCRIPTION
**Pull request by vcapretz**
Thank you for sending the PR! We appreciate you spending the time to work on these changes. 
Help us understand your motivation by explaining why you decided to make this change.

If this PR fixes an issue, type "Fixes #issueNumber" to automatically close the issue when the PR is merged.

Test Plan:
----------
Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!

Release Notes:
--------------
Help reviewers and the release process by writing your own release notes. See below for an example.

[CATEGORY] [TYPE] [LOCATION] - Message

### CODE REVIEW

**Comment by hramos** [comment]
There's already a reference to the CONTRIBUTING file right before the line you added.

**Comment by vcapretz** [comment]
right, my bad!

but then on line 11 we would be missing a Contributing section for the anchor tag right? we can also point line 11 directly to the contributing file instead, what are your thoughts?

**Comment by hramos** [comment]
We can link from line 11. About the anchor tag, is there something specific you had in mind? Is there a convention to have a Contributing anchor on every readme?

**Comment by vcapretz** [comment]
@hramos not actually! it's just that currently if you click the Contributing link on line 11 it doesn't lead you anywhere, but I was not sure on what would be the best fix for that!

**Pull request closed without merging**
