### PR TITLE
Reverting Flow related changes from CI 15749 to get builds back in order

### PR DESCRIPTION
**Pull request by hramos**
Reverting 4 commits that introduced new Flow errors during build process. This has resulted in CI not being able to successfully build. The engineer working on this has been tasked.

63d3ea1
5042bae
6283878
f2687bf4b6201931454c8c43785d78054c856d80

Similar to #12450, but does not revert 118e883.

Unlike #12450, this PR should import successfully as I will be using a newer import tool.

### CODE REVIEW

**Comment by hramos** [comment]
Let's see if these three reverts are sufficient to unbreak CI.

**Comment by hramos** [comment]
This PR did not initially pass tests:

```
$ npm run flow -- check

> react-native@1000.0.0 flow /Users/hramos/git/react-native
> flow "check"

Libraries/Experimental/FlatList.js:132
132:   viewabilityConfig?: ViewabilityConfig,
                           ^^^^^^^^^^^^^^^^^ identifier `ViewabilityConfig`. Could not resolve name
```

I have now reverted f2687bf4b6201931454c8c43785d78054c856d80 which resolved the error above.

**Comment by skevy** [comment]
@hramos is this needed anymore given the fix that we're attempting to land for Flow in 12533.

**Comment by hramos** [comment]
Not any more, closing.

**Pull request closed without merging**
