### PR TITLE
[WebView][Api Change] Support for local files, inline html and relative requires.

### PR DESCRIPTION
**Pull request by JohnyDays**
(This PR is not ready to be merged, creating it for feedback on the api as per recommendation from @brentvatne in #1481)

# Features
* Support for local files using the file protocol, e.g file://htdocs/index.html
* Support for relative requires, e.g in the above file index.js would refer to htdocs/index.js
* Support for inline html (Also supports relative requires through baseUrl, solves #1442) 
* Added 2 buttons and a local test folder to UIExplorer, for testing this (this can be replaced by automated tests perhaps? Apologies, my obj-c/react testing knowledge is still limited)

# New api
```javascript
<WebView source={{uri: string, html: string, baseUrl: string}} />

<WebView source={{uri: 'file://htdocs/index.html'}} />
//is equivalent to 
<WebView source={{uri: 'index.html', baseUrl: '/htdocs'}} />

//Can also directly input the contents of the above index.html
<WebView source={{
  baseUrl: '/htdocs', 
  html: '<script src="index.js"></script>' /* this would load htdocs/index.js */}} />
```

# Future breaking changes

Both the ````url```` and ````html```` props are deprecated, in favor of the source object. ````url```` was also changed to the ````uri```` key, for parity with the ````<Image/>```` element's source object.
They still work as before if no source object is passed, although both methods do not seamlessly operate.

# Issues with the current state

- [ ] Setting inline html replaces the current navigation item. I'm not sure there is any relevant use case for having both uri's and inline html seamlessly navigate between one another, or even navigate between 2 different inline html(s). However, this could be accomplished by temporarily saving a file with the inline html, and pointing to it instead. I'm leaning more towards not supporting this though.
- [ ] I'm not sure how to deprecate remapped properties (url and html), can I get some say-so on this?
- [ ] Perhaps throw an exception if an invalid prop combination is passed? I'm not sure what the react recommended way is to indicate to the developer they have done this

### CODE REVIEW

**Comment by sahrens** [comment]
What do you think about this, @vjeux?  @brentvatne, @ide - any thoughts?

**Comment by brentvatne** [comment]
Sorry for lack of response here @JohnyDays, this totally slipped my mind. 

>  Setting inline html replaces the current navigation item. I'm not sure there is any relevant use case for having both uri's and inline html seamlessly navigate between one another, or even navigate between 2 different inline html(s). However, this could be accomplished by temporarily saving a file with the inline html, and pointing to it instead. I'm leaning more towards not supporting this though.

> Perhaps throw an exception if an invalid prop combination is passed? I'm not sure what the react recommended way is to indicate to the developer they have done this

I think these two are related. I can't imagine it would be particularly useful to mix both uri and inline html and I think this is a reasonable restriction to have. Rather than throw an exception, we could perhaps throw a warning? Just via `warning('uri and html properties cannot both be specified, you must pick one')` (something along those lines) should be fine.

> I'm not sure how to deprecate remapped properties (url and html), can I get some say-so on this?

You can use the `@deprecated` annotation for docs, like this: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L206-L221

This doesn't actually add any warnings though, so we should probably throw a `warning` in there as well, in the render function.

**Comment by brentvatne** [comment]
It looks like this has lingered for too long :( Closing, feel free to create a new PR to revive if this is important to you

**Comment by JohnyDays** [comment]
Hey, I'm not currently on the iOS track so I haven't had the opportunity to dedicate time to this. Anyway, this was just for a request in #1481, if no-one else has seen the need for it, I didn't have a particular need either. Cheers :beer:

**Comment by gs-akhan** [comment]
Amazing PR. This makes lot of sense. I am hoping this lands soon.

**Comment by dozoisch** [comment]
@JohnyDays Ah! That would have been so useful if it landed!

**Pull request closed without merging**
