### PR TITLE
improve text input docs

### PR DESCRIPTION
**Pull request by lacker**
Not a big deal, I was just going through the tutorial trying to figure out which doc was the most boring, and improve it a bit. IMO now the example is slightly funnier, and it mentions onSubmitEditing which in practice is probably a more useful callback.

### CODE REVIEW

**Comment by lacker** [comment]
The ListView doc also could use pizzazz but we really need react-native-web to support ListView before we can really make it compelling.

**Comment by hramos** [comment]
@facebook-github-bot ship-it

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by JoelMarcey** [comment]
@hramos no dash in `shipit` :)

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/922483234564751/int_phab) to review.

**Pull request closed without merging**
