### PR TITLE
Snapshot Delay in SnapshotViewIOS

### PR DESCRIPTION
**Pull request by kgowru**
**Explain the motivation for making this change. What existing problem does the pull request solve?**

This PR incorporates the ability to add a snapshotDelay to SnapshotViewIOS. I found the Snapshot Image comparison tests to be insanely useful. It adds capabilities that component tests just can't compare to. But, I have noticed the snapshot tests do not work well in views where there are animations after mounting. The snapshot compares the image instantly. The fix is simple, just pass in a `snapshotDelay` prop into SnapshotViewIOS. The delay specifies the number of seconds to wait before comparing the image to your goldfile image.

**Test plan (required)**

The tests all have passed as expected (iOS test, npm test, and linter).

**Code formatting**

All code is formatted but I think the way I’m implementing the wait might be able to be improved:

```
dispatch_async(dispatch_get_main_queue(), ^{
      dispatch_after(dispatch_time(DISPATCH_TIME_NOW, self.snapshotDelay * NSEC_PER_SEC),dispatch_get_main_queue(), ^{
        if (self.onSnapshotReady) {
          self.onSnapshotReady(@{@"testIdentifier" : self.testIdentifier});
        }
      });
    });
```

### CODE REVIEW

**Comment by ide** [comment]
Could this be more simply implemented using setTimeout in JS?

**Comment by kgowru** [comment]
@ide Great idea, updated! Let me know if you like this better .

**Comment by ide** [comment]
I mean doing this in your application code. This feature can be cleanly implemented (I think) without modifying the SnapshotViewIOS component. You could neatly write a wrapper component that implements this behavior.

**Comment by kgowru** [comment]
Well you could in fact do this: 

import {NativeModules} from react-native;

<SnapshotViewIOS >

</SnapshotViewIOS>

**Comment by kgowru** [comment]
Well you could in fact do this:
```
import {NativeModules} from react-native;
var TestModule = NativeModules.TestModule;
. . .
<SnapshotViewIOS onSnapshotReady={()=>{setTimeout(TestModule.verifySnapshot(TestModule.markTestPassed), 100);}}>
<UIExplorerExampleContainer module={ExampleModule} />
</SnapshotViewIOS>
. . .
```

But I think it's cleaner if it was passed into the prop as a delay so you don't have to import NativeModules in your wrapper component and all of the testing is encapsulated in <SnapshotViewIOS/>.

**Comment by ide** [comment]
What I mean is this:
```js
class C extends Component {
  state = { isReadyForSnapshot: false };
  componentDidMount() {
    setTimeout(() => { this.setState({ isReadyForSnapshot: true }); });
  }
  render() {
    return (
      <View>
        {this.state.isReadyForSnapshot && <SnapshotViewIOS ... />}
      </View>
    );
  }
}
```

**Comment by kgowru** [comment]
Not entirely sure. But I don't think that will work because the component you are testing needs to be wrapped in SnapshotViewIOS and you'll still run into the same issue after the wait.

**Comment by kgowru** [comment]
@spicyj What do you think here? Looks like you were tagged on this PR. I stand by my initial request of encapsulating that logic in SnapshotViewIOS. User's will also know it can be done.

**Comment by spicyj** [comment]
I dunno. I definitely agree with @ide that it seems weird to encode "delay" as a specific prop here because then you can't control more complex logic in JS. If the issue is that the component takes a while to mount then maybe there could be some prop `immediate={false}` and SnapshotViewIOS could support an imperative (ref-based) API where you can ask it to take a snapshot.

Something like

```
setTimeout(function() {
  this.refs.snapshotView.captureSnapshot();
}, 5000);
```

Not sure if it would make more sense to call onSnapshotReady back or for it to take its own callback.

I don't do much React Native these days so I'll leave any decisions up to @ide.

**Comment by ide** [comment]
I don't think a delay prop is right, it's too niche and doesn't allow for more control -- what if you want to cancel the snapshot, or run one last check before taking the snapshot? We'd need to add more niche props to support that case. It'd be better to provide an API like @spicyj suggested, which pushes more of the logic into application code and is likely to serve a lot of people's needs without needing more PRs.

**Comment by kgowru** [comment]
This is supported by passing onSnapshotReady prop into SnapshotViewIOS which overrides the `defaultAction()` in the component. So you could: 

``` javascript
<SnapshotViewIOS ref='snapview' onSnapshotReady={()=>{setTimeout(()=>{this.refs.snapview.defaultAction();}, 100);}}>
<UIExplorerExampleContainer module={ExampleModule} />
</SnapshotViewIOS>
```

Honestly, this solves my inital request fairly elegantly. We should document this so people are aware though.

**Comment by lacker** [comment]
Since this seems solved I am going to close this issue. I can add some extra documentation for `onSnapshotReady` since it has none - although I'm not quite sure what I would say. I'm guessing it just runs when the snapshot is ready. What else would you like to be documented here?

**Comment by kgowru** [comment]
@lacker This thread was created to highlight the ability to add a delay even after the 'snapshot is ready'. Useful for views that load after certain animations are completed. I would include an example of adding a delay similar to the one in my previous comment above :). If you want I can do this and propose a PR!

**Comment by lacker** [comment]
Yeah, I think that would be quite useful in the snapshot docs, a docs PR would be great!

**Pull request closed without merging**
