### PR TITLE
Link both iOS and tvOS libraries with react-native link (fix #13783)

### LINKED ISSUE #13783: React Native link adds tvOS library targets to the ios target
### Description

In adding a tvOS target to the react-native-vector-icons library, `react-native link` inadvertently adds the tvOS target to the normal ios target causing the app to fail to run

### Reproduction Steps and Sample Code

Described here: https://github.com/oblador/react-native-vector-icons/issues/461

### Solution

React Native link needs to properly link the ios and tvOS library targets with the right target

### Additional Information

* React Native version: 0.44
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: XCode 8.3.2

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
## Motivation

Fix issues with the react-native CLI when linking iOS and tvOS libraries to a project created with `react-native init`. (#13783)

## Test Plan

Verified the changes against test project at https://github.com/dlowder-salesforce/react-native-link-test.  Both `react-native link react-native-svg` and `react-native unlink react-native-svg` work correctly on this project.  Added new unit test for the new file added to `local-cli/link/ios`.

## Release Notes

[CLI] [BUGFIX] `react-native link` has been fixed to correctly link iOS and tvOS targets.
[IOS] [BUGFIX] `react-native link` has been fixed to correctly link iOS and tvOS targets.

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
@grabbou please review this when you get a chance.

**Comment by dlowder-salesforce** [comment]
@hramos or @shergin , could you please land this immediately, as it also fixes a complete tvOS breakage caused by https://github.com/facebook/react-native/commit/ee521f9c05c2be5b28a2c1bc86e0a89bbea6a0bf ? I'll be happy to make adjustments to the local-cli changes later if @grabbou requests them.

**Comment by dlowder-salesforce** [comment]
@grabbou could you please review this ASAP?

**Comment by grabbou** [comment]
Have this on my TODO list after Christmas. I am back today to work, will be
taking care of this this week.

**Comment by dlowder-salesforce** [comment]
@grabbou : @matthargett says this looks good, but is asking for automated testing of `react-native link` and `react-native unlink` with these changes.  I'll go ahead and start working on that.... it's up to you whether you want to go ahead and merge this, given the severity of the bug.

**Comment by hramos** [comment]
If this does not land shortly, please try re-basing. Due to a recent change to the internal repo, some PRs older than a week (as of today) may need to be rebased in order to land cleanly.

**Comment by dlowder-salesforce** [comment]
@hramos I just merged from facebook/master, hopefully it can be landed now... Thanks!!

**Comment by dlowder-salesforce** [comment]
@hramos after the last merge from master, I'm hitting https://github.com/facebook/react-native/issues/17742 when I test this locally... FYI

**Pull request closed without merging**
