### PR TITLE
[Codegen]: Refactor `buildPropertySchema` fn of (Flow, TS) into common fn

### PR DESCRIPTION
**Pull request by Pranav-yadav**
## Summary
This PR is a task of #34872 
- combined `Flow` and `TS` `buildPropertySchema` fn 's into common fn
- added callback param `resolveTypeAnnotation` to the same
- moved it to `parsers-commons.js`
- re-organized imports and exports

## Changelog

[INTERNAL] [CHANGED] - [Codegen]: Refactored `buildPropertySchema` fn of (Flow, TS) into common fn in `parsers-commons.js`

## Test Plan

- ensure 👇  is `#00ff00`
```bash
yarn lint && yarn flow && yarn test-ci
```

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
[.temp.log](https://github.com/facebook/react-native/files/9979987/default.temp.log)

**Comment by Pranav-yadav** [comment]
> NOTE: Skipped ci to avoid wastage of compute resources; will rm the tag once the following warning/issue is resolved

@cipolleschi 
Linter is complaining about "Circular Dependencies", shall I move dependents in parsers-commons (some tasks are already assigned to others) or anything else?
PFA logs.

<details><summary>Logs</summary>
yarn lint

<hr>
yarn flow
<pre>
yarn run v1.22.19
$ flow
No errors!
Done in 0.20s.
</pre>
</details>

**Review by cipolleschi — APPROVED** [review]
Great job moving this, thank you so much!

**Comment by Pranav-yadav** [comment]
@cipolleschi shall I remove the `[skip ci]` tag from commit msg as it might skip internal workflow?

**Comment by Pranav-yadav** [comment]
@cipolleschi 
Actually, I had tried that one earlier when I had a quick chat re: same, w/ @AntoineDoubovetzky (thank you) and I think I had similar warnings since that also depends on it(other)..

Will try it again on another branch and open a PR if it works, as that might solve similar warns for other PRs
Thanks

**Comment by cipolleschi** [comment]
I understand. I can try myself tomorrow morning.

**Comment by Pranav-yadav** [comment]
I think It's solved on my local, just finishing tests and chores..

**Comment by AntoineDoubovetzky** [comment]
@Pranav-yadav Looks like you found a solution to your error. If you ever encounter an error again, I am available to look at it together.

**Comment by Pranav-yadav** [comment]
> We should probably define some clear rules about what should go in parsers-primitives and what should go in parsers-commons... 🤔 Probably, it's better to put in primitives all the basic building blocks and commons all the utility functions, so that primitives can import commons but vice-versa should not happen.
>
> What do you think?

Definitely. Block comments should be added at top of both `parsers-commons.js` and `parsers-primitives.js` stating their purpose, functionalities, and what NOT to include in those files.. :) Also, It would be very useful for newbie contributors like me 👶 as well as existing..
Thanks

**Comment by Pranav-yadav** [comment]
@cipolleschi did u notice something strange about @react-native-bot ?
It stopped labelling merged PRs `Merged`, from last week. I hope the bot is okay :) <3
*\#offtopic* :)

**Comment by cipolleschi** [comment]
@Pranav-yadav thank you for reporting this. We have to look into that bot, I think.

**Comment by Pranav-yadav** [comment]
> > We should probably define some clear rules about what should go in parsers-primitives and what should go in parsers-commons... 🤔 Probably, it's better to put in primitives all the basic building blocks and commons all the utility functions, so that primitives can import commons but vice-versa should not happen.
> > What do you think?  --- _Riccardo_
> 
> Definitely. Block comments should be added at top of both `parsers-commons.js` and `parsers-primitives.js` stating their purpose, functionalities, and what NOT to include in those files.. :) Also, It would be very useful for newbie contributors like me 👶 as well as existing.. Thanks ---  _Pranav_

@cipolleschi After giving it another thought, I think we should merge those two files. Reason: **_Cohesion_**
1. Though, (logically) it's correct to keep them separate, the fns/types/interfaces exported by them are _not_ used sparsely (at different places).
2. We know that, they are highly related to each other (_highly cohesive => Good_ 🙂) and keeping logic together will be better as well as easy to maintain.

Thoughts?

PS: sorry for commenting under closed PR

**Pull request closed without merging**
