### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by laurilehmijoki**
Replaces https://github.com/facebook/react-native/pull/4469

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by mkonicek-tester** [comment]
@facebook-github-bot shipit

**Comment by mkonicek-tester** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Got stuck due to an infra failure. Adding merging this to my TODO-list.

**Pull request closed without merging**
