### PR TITLE
Update EmbeddedAppIOS.md

### PR DESCRIPTION
**Pull request by dgilliam**
Hi this pr is a few additions to the docs I thought would be helpful based on going through adding RN to a swift project myself. Thanks!

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @davidyaha and @hfossli to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by davidyaha** [comment]
Thanks for the PR. 
This is basically the same as: https://github.com/facebook/react-native/pull/7810

Have a great day,
David

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
> This is basically the same as: #7810

I see @davidyaha is already reviewing #7810, will close this one as a duplicate.

**Pull request closed without merging**
