### PR TITLE
Update MapView doc

### PR DESCRIPTION
**Pull request by caabernathy**
Reference: #8203

Changes made:

- Added a MapView example to the intro section
- Added more details to prop explanations
- Added more info to an exported type, even if it's not used anywhere I can see
- Removed mention of ios platform in props. Left an android one in there as I didn't want to touch code.

**Test plan (required)**

Ran the website locally and checked: http://localhost:8079/react-native/docs/mapview.html

component_mapview_2

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @benhoyt to be potential reviewers.

**Comment by JoelMarcey** [comment]
In general, I am good with this. I am wondering, though, if there is something we can do to make it more clear that this is iOS only.

Almost feels like, if we are removing all `@platform ios`, then we should put an `<h1>` markdown (`#`) at the top of the class that says `THIS COMPONENT IS CURRENTLY ONLY SUPPORTED ON iOS` -- just so people see it right away.

Having that one Android prop in there is really strange -- but I am using the "nothing to see here" philosophy on that :)

**Comment by caabernathy** [comment]
@JoelMarcey I made the iOS support clear as the first line.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1120146981378460/int_phab) to review.

**Pull request closed without merging**
