### PR TITLE
Allow for passing custom textProps to NavigationHeaderTitle

### PR DESCRIPTION
**Pull request by jeffberry**
It would be nice to be able to pass properties to the wrapped Text Component within the NavigationHeaderTitle View.

This is useful for truncating especially: 

```
<NavigationHeader.Title textStyle={styles.title} textProps={{ numberOfLines: 1 }}>
    {sceneProps.scene.route.title}
</NavigationHeader.Title>
```

### CODE REVIEW

**Comment by satya164** [comment]
Seems a bit overkill adding so many props to this component while you could just use your own `<View><Text>title</Text></View>`

**Comment by jeffberry** [comment]
@satya164  I have just used my own Title component for the time being. I would have preferred not to have to replicate code in my own codebase for such a simple feature though. How do you justify this as overkill? This PR adds one pass-thru property to the component, mimicking the `viewProps` support it already has.

It makes sense to me that the NavigationHeaderTitle component **included** in the package would support such a basic feature. I certainly don't see where there's any harm being done.

**Comment by satya164** [comment]
> How do you justify this as overkill?

It's just a simple view and text. The number of props it now has are more than the lines needed to write the component.

Your PR alone is not what makes it overkill, it's the number of props we've acquired.

> I certainly don't see where there's any harm being done.

Allowing passing arbitrary props means that when we change something internally, there's more chance of breaking things. This component is already exposing lots of internal details.

> This PR adds one pass-thru property to the component, mimicking the viewProps support it already has.

About `viewProps`, it could have just passed rest of the props to `View` after consuming, like all other components do. There was really no need for another prop. But it's there now, so can't do anything.

> It makes sense to me that the NavigationHeaderTitle component included in the package would support such a basic feature.

I think it's reasonable to have `numberOfLines` as 1 by default inside the component itself. No need to add a prop. I don't think anyone needs to pass any other props.

I think we should have reasonable defaults instead of allowing every bit of customisation especially since FB team is not maintaining the component.

**Comment by lacker** [comment]
I think Satya is correct here and this feature is overkill when there is the simple workaround of composing components yourself. I'm going to close this pull request, but if there is a different rationale here that we are missing please feel free to bring that up.

**Comment by jeffberry** [comment]
I understand - it's unfortunate to see cynical opinions hold back such small improvements to an open source project, but it's the way of the community!

My argument here would be that it's consistency -- the default component already allows for `viewProps` to be passed through, some of your other pre-built components allow for both `viewProps` and `textProps`, and I won't be the only person that finds it absurd that this component lacks that one line that makes it possible. I also don't think I'll be the only one that finds the default component completely useless -- in fact, I'm sure this component will be completely useless to the majority of users; anybody that wants their text to actually fit on the screen of their user's device will be forced to copy+paste this into their codebase simply to add one line.

**Pull request closed without merging**
