### PR TITLE
Picker (android): Convert children to an array before accessing with a position

### PR DESCRIPTION
**Pull request by justim**
When using the following component, `this.props.children` is not a flat array.

``` js
class Example extends Component {
    // ...

    render() {
        const values = ['1', '2'];

        return (
            <Picker
                value={this.state.value}
                onValueChange={this.onValueChange.bind(this)}
            >
                <Picker.Item
                    label="n/a"
                    value={null}
                />

                {values.map(value => {
                    return (
                        <Picker.Item
                            label={value}
                            value={value}
                        />
                    );
                })}
            </Picker>
        );
    }
}
```

The resulting `this.props.children` is:

``` js
[
    (child),
    [
        (child),
        (child),
    ],
];
```

Therefor you can't use `this.props.children[2]` to get the last item.

The Android version of the [Picker](https://facebook.github.io/react-native/docs/picker.html) does exactly this to get the value of the selected item to pass to the `onValueChange` prop.

This PR fixes that by normalising the children with `React.Children.toArray`.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @spicyj to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
The example seems reasonable but doing this the conversion in every change event seems unnecessary - the children don't change.

Is it possible to do the conversion just once? Alternatively, could you create a flat list in your application code?

    [
      <Picker.Item label="n/a" />
    ].concat(values.map(value => {
      ...
    }))

**Comment by justim** [comment]
The workaround I had so far was indeed to create one list of values and map them to a list of picker items.

Doing the conversion only on mount would not be enough in some cases (my case would be solved, but still), the first item might not always be available in the picker, same goes for any of the values — the children _might_ change.

I'm happy to go either way.

**Comment by mkonicek** [comment]
> Doing the conversion only on mount would not be enough in some cases (my case would be solved, but still), the first item might not always be available in the picker, same goes for any of the values — the children might change.

Could you convert the children to an array only when they change?
https://facebook.github.io/react/docs/component-specs.html

I'd argue, however, that converting children to an array automatically could confusing to the reader - I'd prefer the user to explicitly convert whatever data structure they have to an array for readability and clarity.

@spicyj What do you think?

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @mkonicek as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by spicyj** [comment]
Isn't the fact that it needs to be an array an implementation detail of Picker? This seems okay to me and better than what's currently here.

**Comment by AzizAK** [comment]
i think you can fix it by passing the initial item to the array:

`class Example extends Component {
    // ...

    render() {
        const values = ['1', '2'];
        let pickerItem = []
        pickerItem.push(<Picker.Item label="n/a" value={null} />)
        values.map(value => {
          pickerItem.push(
            <Picker.Item
                label={value}
                value={value}
            />
          )
        })
        return (
            <Picker
                value={this.state.value}
                onValueChange={this.onValueChange.bind(this)}
            >
              {pickerItem}
            </Picker>
        );
    }
}
`

Please correct me if wrong.

**Comment by satya164** [comment]
> @mkonicek :  Could you convert the children to an array only when they change?

This can be easily fixed by using a memoized function to get the current children. But is it really necessary? How slow is the conversion?

**Comment by hramos** [comment]
It's been a while since this PR has seen any activity. Is there any interest in landing this, any additional feedback?

**Comment by satya164** [comment]
@hramos I think we should land this.

**Comment by everyusernameistaken123** [comment]
I am experiencing a related issue.
Can't believe it takes 7months to merge 1 changed line?

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Trying again.

@facebook-github-bot shipit

**Comment by satya164** [comment]
cc @lacker

**Comment by danielfeelfine** [comment]
@justim it's fix this https://github.com/facebook/react-native/issues/12829?

**Comment by justim** [comment]
@danielfeelfine, yes, it should. The`React.Children.toArray` call in this PR handles the nested arrays.

**Comment by romjear12** [comment]
I used this "hack":
```
  render() {
    const values = ['1', '2'];

    return (
      <Picker
        value={this.state.value}
        onValueChange={this.onValueChange.bind(this)}
      >
      {
				<Picker
					value={this.state.value}
					onValueChange={this.onValueChange.bind(this)}
				>
				{
					[<Picker.Item
						label="n/a"
						value={null}
					/>].concat(values.map(value => {
							return (
								<Picker.Item
									label={value}
									value={value}
								/>
							)
							})
					) 
				}
				</Picker>
    );
  }
```

**Comment by justim** [comment]
There is no need for hacks anymore, this PR is merged and the example I gave at the top works now.

**Pull request closed without merging**
