### PR TITLE
async/await is not part of ES7

### PR DESCRIPTION
**Pull request by timjacobi**
I might be a little pedantic here but it is what it is ;-)

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @grgmo to be potential reviewers.

**Comment by satya164** [comment]
There's no ES8. It's ES2016.

**Comment by timjacobi** [comment]
ES7 is ES2016, ES8 would be ES2017 then.

**Comment by satya164** [comment]
Sure.

**Comment by hramos** [comment]
Good catch, async/await did not make the cut for ES7. If I'm being pedantic, I'd say the right wording here would be:

> You can also use the _proposed ES2017_ `async`/`await` syntax in _a_ React Native app:

(emphasis on edits)

**Comment by timjacobi** [comment]
That makes sense. Just updated.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/269420490091204/int_phab) to review.

**Pull request closed without merging**
