### PR TITLE
[AdSupportIOS] better module exports for AdSupportIOS

### PR DESCRIPTION
**Pull request by lvyile**
# Before:
```javascript
var AdSupportIOS = require('AdSupportIOS');
```
# After:
```javascript
var React = require('react-native');
var {
  //...
  AdSupportIOS,
  //...
} = React;
```

### CODE REVIEW

**Comment by lvyile** [comment]
Why I test succeed on my device, but  build failed on Travis CI ?

screen shot 2015-04-04 at 10 40 40 pm

**Comment by ccheever** [comment]
I think the code for this looks good but @lvyile you should probably squash your commits.

Someone from Facebook or more of a decision maker on the project probably needs to say whether 

```js
var AdSupportIOS = require('AdSupportIOS');
```

or 

```js
var React = require('react-native');
var {
  //...
  AdSupportIOS,
  //...
} = React;
```

is preferred. @brentvatne ?

**Comment by brentvatne** [comment]
I think the latter example is preferred in this case @ccheever.

One thing that we will want to do in addition to this is add some documentation in `AdSupportIOS.js` so that we can have it under the APIs section in the docs. If you're up for it @ccheever ;)

Agreed, can you squash your commits into one @lvyile?

**Comment by nicklockwood** [comment]
Seems like this now works as intended.

**Pull request closed without merging**
