### PR TITLE
Fix jest tests

### PR DESCRIPTION
**Pull request by grabbou**
https://www.facebook.com/groups/reactnativeoss/permalink/1627334037563224/

CC: @cpojer

### CODE REVIEW

**Comment by grabbou** [comment]
Travis is back green, thanks for help. I am going to ninja ship it for the sake for other pull requests awaiting.

@facebook-github-bot shipit-ninja

**Comment by manosim** [comment]
@grabbou My PR had one more commit that was renaming `object` to `dataBlob` - this one should fix it 👍

**Comment by grabbou** [comment]
@mkonicek for some reason the shipit bot no longer auto-closes as the commit already landed. I think worth investigating?

**Comment by cpojer** [comment]
Thanks Mike! This was silly; our internal diff didn't update after I canceled the land and re-shipped it.

**Pull request closed without merging**
