### PR TITLE
Fix retain cycles in RCTNetworkTask when used with RCTFileRequestHandler and RCTDataRequestHandler

### PR DESCRIPTION
**Pull request by jeanregisser**
Hi,

While implementing my own `RCTURLRequestHandler` I came across retain cycles in `RCTNetworkTask` when used with `RCTFileRequestHandler` and `RCTDataRequestHandler`.

The `NSBlockOperation` used in `RCTFileRequestHandler` and `RCTDataRequestHandler` could never be dealloc'ed because of a retain cycle.
And then the second issue was that those blocks were also strongly capturing the passed delegate which in this case is the `RCTNetworkTask` itself and then since the task was storing the block as a `requestToken`, the task could never be dealloc'ed as well.

Here are my proposed fixes. Let me know what you think.

### CODE REVIEW

**Comment by nicklockwood** [comment]
Good catch!

I wonder if it would be better to make the requestToken property of RCTNetworkTask weak instead though.

That way, you avoid having to make the delegate argument weak in RCTFileRequestHandler and RCTDataRequestHandler, which seems more fragile, and requires the implementations to know about the internals of RCTNetworkTask, which may change.

**Comment by jeanregisser** [comment]
Yes you're right!

I also tested adding `_requestToken = nil` in  `[RCTNetworkTask invalidate]` but it wasn't 100% correct since any next call to `validateRequestToken:` would change it back to the passed value.

So I'm gonna change it to what you're proposing.

**Comment by jeanregisser** [comment]
Also do you want me to squash everything into a single commit?

**Comment by nicklockwood** [comment]
That isn't necessary, t will be squashed by our import process. Thanks!

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
