### PR TITLE
moved normalizeColor and changed dependencies

### PR DESCRIPTION
**Pull request by isa3bel**
## Summary

Originally, normalizeColor.js was in Library/Color/ however, I noticed that its tests were in a completely different directly (Library/StyleSheet/__tests__) which was confusing. The other files such as processColor.js, setNormalizedAlphaColor.js had their tests in Library/StyleSheet/__tests__ as well. 

## Changelog

[Internal] [Changed] - Moved normalizeColor.js to a more appropriate directory where its tests live.

## Test Plan

I simply moved a file and changed dependencies. The code should still function as is.

### CODE REVIEW

**Comment by isa3bel** [comment]
I need to fix the builds before you can merge! thanks though for approving

**Comment by isa3bel** [comment]
some tests are failing but I feel like they aren't due to my change....?

**Comment by isa3bel** [comment]
was this merged or just closed?

**Comment by yungsters** [comment]
It was merged. 😄

**Pull request closed without merging**
