### PR TITLE
[React] Update React version to ~15.4.1 instead of the RC

### PR DESCRIPTION
**Pull request by ide**
React 15.4.x has been out for awhile. Test Plan: open UI Explorer, go through the various screens and look for warnings or errors.

### CODE REVIEW

**Comment by ide** [comment]
@ericvicenti could you take care of this? We've cherry picked it into 0.40-stable so that release isn't blocked, but we should eventually land this in master.

**Comment by ide** [comment]
@spicyj would someone on the React team be able to look at this?

**Comment by spicyj** [comment]
Should be fine – can someone on the RN team land this internally properly?

**Comment by ericvicenti** [comment]
I'll do the upgrade this afternoon. I'll ping you Ben if I run into any confusion

**Comment by ericvicenti** [comment]
I assume we should actually use `~15.4.2` now that it is out

**Comment by spicyj** [comment]
Sure, yes.

**Comment by ericvicenti** [comment]
Apologies for the delay on this! Turns out its a non-trivial upgrade, so @sebmarkbage is doing this upgrade as an internal commit.

**Comment by sebmarkbage** [comment]
We're going to go straight to 16.0.0-alpha.

**Comment by sebmarkbage** [comment]
The update to `16.0.0-alpha` has now landed in https://github.com/facebook/react-native/commit/b1da7a5f5d4152387feab26bdadd69188efd55f2

**Pull request closed without merging**
