### PR TITLE
Fix configure glog script when building from xcodebuild

### PR DESCRIPTION
**Pull request by janicduplessis**
I encountered an issue when building with fastlane gym / xcodebuild where glog would not build because of missing config.h header file. I tracked it down to the ios-configure-glog.sh script that ended up error-ing because of missing valid c compiler. I guess it didn't enter the if to set c compiler env in xcodebuild and that env doesn't have proper values set like it does in xcode so just removing this check fixed it. Also tested that it still works properly in xcode.

### CODE REVIEW

**Comment by janicduplessis** [comment]
cc @javache

**Comment by javache** [comment]
I added this because it was causing issues with the tvos build (see the Travis failure on your diff). Maybe a better approach would be to get the right `-sdk iphoneos` flag from the environment?

**Comment by janicduplessis** [comment]
@javache I see, I think getting -sdk flag from the env is the right solution I'll figure out how to get that.

**Comment by janicduplessis** [comment]
@javache Ok I've figured the problem we need to get both the sdk and the arch from the build env variables (tvos is arm64 probably why it didn't work).

Tested that it build for simulator and archive on iOS and tvOS.

**Comment by javache** [comment]
Awesome! Maybe we should provide defaults for these variables as well? In case people end up running the script outside of Xcode.

**Comment by janicduplessis** [comment]
@javache Added default values that match what the old code did

**Comment by rborn** [comment]
@janicduplessis I still have this issue. I have some pods installed and `fastlane gym` will complain with the below error while an xcode build (from the workspace of course) will go smooth

Any ideas? 😊

~~~
Undefined symbols for architecture arm64:
  "facebook::react::parseTypeFromHeader(facebook::react::BundleHeader const&)", referenced from:
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
  "_JSNoBytecodeFileFormatVersion", referenced from:
      +[RCTJavaScriptLoader loadBundleAtURL:onProgress:onComplete:] in libReact.a(RCTJavaScriptLoader.o)
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
ld: symbol(s) not found for architecture arm64

~~~

**Pull request closed without merging**
