### PR TITLE
Add app to showcase - FingerFrame

### PR DESCRIPTION
**Pull request by fingerframe**

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by lacker** [comment]
Hey, I'm really sorry for the churn, but we are changing up how the showcase works, and just focusing on apps that have some media presence or technical blog posts / other content. So I appreciate the spirit behind this pull request but I think we should close it.

**Comment by fingerframe** [comment]
Hi Kevin,

Well, I've worked alone on this app for almost 6 months as a side project
so i was counting on this showcase to get a little media presence
precisely....so I'm just disappointed to not have a chance to get a bit of
exposure. I understand the spirit behind this move but I think you should
do not forget that react native is living because of its passionate
community...

Thanks to send me an explanation on this close anyway.

Best,
Guillaume

**Comment by lacker** [comment]
Yeah, the thing is the showcase is getting so big that checking our analytics it seems like the traffic it sends is totally worthless nowadays. IMO the most effective way to get some media presence based on your tech stack is to write a blog post along the lines of "7 cool things I learned about React Native - the 5th one will surprise you" and then post to Hacker News. And then we could link to that from the showcase too ;-)

**Pull request closed without merging**
