### PR TITLE
Bump babel-preset-react-native version

### PR DESCRIPTION
**Pull request by janicduplessis**
To include a missing part of the fix to HMR on Windows that was done in 0.25rc. See https://github.com/facebook/react-native/commit/c61100d0ceb4b71c86f01f35d7464d2d8a02b342. Will need to also publish to npm.

cc @ide @grabbou

### CODE REVIEW

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@bestander Does this need an update to our internal node_modules?

@janicduplessis Are the test failures related? I just restarted both Travis and Circle CI tests.

**Comment by skevy** [comment]
Yah these failures are not related. @janicduplessis can you rebase?

**Comment by skevy** [comment]
And @mkonicek yah - probably need to update your internal node_modules. OSS would be unaffected though, as it has ^1.5.2 in package.json.

**Comment by mkonicek** [comment]
Thanks for the quick reply @skevy 👍

**Comment by janicduplessis** [comment]
Rebased but the build on travis seems to have issues, it just hangs and timeouts, looks like a process doesn't exit properly.

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself
```

Updating internal node modules may not be needed since this patch is for fixing hmr on windows.

**Comment by bestander** [comment]
Yep, Travis iOS builds got completely broken.
Infra failure

**Comment by janicduplessis** [comment]
Tests are good on circle now, let's try shipit again.

@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
Can someone publish the preset to npm? :)

**Comment by skevy** [comment]
@janicduplessis published. :)

**Comment by janicduplessis** [comment]
Thanks @skevy :)

**Pull request closed without merging**
