### PR TITLE
[docs] running on device does not require apple dev program

### PR DESCRIPTION
**Pull request by vonovak**
source https://developer.apple.com/support/compare-memberships/ (Benefits and Resources section) plus my own experience

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Thank you!

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing.

**Comment by JoelMarcey** [comment]
Ah - actually, you need to target `master` and not `0.30-stable` as stated in the pull request template.

**Comment by vonovak** [comment]
closing in favor of #9198

**Pull request closed without merging**
