### PR TITLE
[Android] Improve consistency for overflowed TextInput

### PR DESCRIPTION
**Pull request by redstar504**
## Summary

The purpose of this PR is to improve consistency in the behavior of overflowed TextInput components across supported platforms. 

Currently on Android, when a TextInput is rendered with a value that overflows the width of the TextInput, Android Native displays the end of the text line. Other platforms display the start and clip the end.  This also applies to setting text programatically (ie. by setting the value through state for an unfocused TextInput).

This PR aims to normalize the behavior by updating the Android Native implementation to display the start of the line and clip the end, bringing it in line with the behavior of other platforms.

To achieve this, we can invoke `scrollTo` in the `afterChangedText` event using the existing `TextWatcher` for detecting text changes for the Android widget.  To ensure this only applies to initial rendering and auto-filling, we condition on the field being unfocused.  When the field is focused, the behaviour will not apply and therefore not effect regular keyboarding events.

This problem was discussed more thoroughly in the longstanding issue here: https://github.com/facebook/react-native/issues/14845

## Changelog

[ANDROID] [Fixed] - TextInput not displaying start of text on render like other platforms

## Test Plan

My submitted solution includes an example within the `rn-tester` package. Below I will provide videos displaying the behaviour both there, and within our production app where the issue was identified.

<details>
<summary>Before Change (RNTester)</summary>

https://user-images.githubusercontent.com/1311325/224181112-7b7fb4bd-ce43-421d-913f-4e3a62a2060b.mp4

</details>

<details>
<summary>After Change (RNTester)</summary>

https://user-images.githubusercontent.com/1311325/224181178-5c7bd56f-ff92-43ae-b6d8-8ac7f99d7423.mp4

</details>

<details>
<summary>Before Change (Production app)</summary>

https://user-images.githubusercontent.com/1311325/224181324-6c816afa-792c-441a-9b46-14fcd3d86898.mp4

</details>

<details>
<summary>After Change (Production app)</summary>

https://user-images.githubusercontent.com/1311325/224181342-335611b1-163d-46c8-96d7-24b8d7aa2a04.mp4

</details>

### CODE REVIEW

**Review by NickGerleman — CHANGES_REQUESTED** [review]
Do we know what React Native is doing to move selection in the first place, if this doesn't happen on stock Android? https://github.com/facebook/react-native/issues/14845#issuecomment-414071473

Re-scrolling the text every time it is edited seems pretty broad. It would be better to understand where the behavior comes from instead.

**Comment by redstar504** [comment]
@NickGerleman Thank you for your comment. After further investigation, I have found that the issue is definitely caused on the RN side, due to the selection being manipulated during text updates:

https://github.com/facebook/react-native/blob/cbe934bcff0bdbd26f669fd9ace4fc818ca39e98/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L386

This method is always called with the text length for both arguments, effectively clamping the cursor at the end of the field. This does not occur on Android native, but it seems logical to place the cursor at the end when subsequently pressing on the field. It does however carry the side effect of scrolling to the end of the field.

While both scrolling and selection can act independently (i.e., we can set the selection to the end, and scroll to the beginning), if we do this too early in the update process, the TextInput appears to bounce between the end and the start of the input multiple times.  This seems to be a result of `setSelection` occurring multiple times during rendering.

To minimize this, my solution uses `View.post()` to scroll to the beginning only after all TextInput management has completed. I should point out that by adding the `!hasFocus` condition, we are only introducing this behavior for initial rendering and subsequent state changes that modify the text while the input is unfocused. The behavior does not apply when conducting text edits, since in that case the input would be focused while text management is occuring.

Overall, the goal of the solution is to increase text readability on initial render, and when adding text programatically.  I'm inferring that the user will not be as interested in seeing the beginning of the text immediately after editing it, so the behavior does not change in that regard.

**Comment by NickGerleman** [comment]
I still hold the concern that the solution proposed in this PR may have side effects beyond the problem we are targeting. It changes behavior, away from where the bug is happening.

You've identified this case, where RN is moving the selection without the user is telling it to. In this case, the framework is telling the EditText to change selection, though the user didn't.

Ideally, RN should not move selection in the EditText except when told to. It doing that is the root incorrect behavior which seems to cause this issue. I would accept a PR targeted at preventing these errant selection changes.


A recent PR that fixed a case of errant native selections (in a different scenario) is https://github.com/facebook/react-native/pull/37424

**Comment by redstar504** [comment]
@NickGerleman This issue stems from a couple of places.  Yes, React Native forces the selection to the text length when the selection is empty, causing the view to scroll to the rightmost character.  That is easy enough to change.  However, disabling that behaviour unmasks an underlying quirk (or bug) of Android itself.

Android normally displays the beginning of the text input when you set a value.  However, strangely, if you set or replace the value of a text input to `null` or to an empty string, and subsequently set a value using `Editable.replace` as is used in RN, it will also shift the selection to the end of the text.  I am assuming this may be related to the behavior explained at the last sentence in the [Android docs](https://developer.android.com/reference/android/text/Editable#replace(int,%20int,%20java.lang.CharSequence,%20int,%20int)), however I am not sure whether this specific behavior was intended.

So even if we did not manipulate the selection on RN, we would still be stuck with the Android behavior.  Text gets set to `null` or an empty string frequently in RN, therefore subsequent value changes will reflect themselves through a rightmost selection, which not within our control.

It seems like in this issue we're more concerned with scroll.  Scroll and selection can be independent.  In fact, I feel more accustomed to my cursor falling at the end of the text input when pressing on it (selection), as is the case in iOS. I also expect to see the beginning of the line of text when viewing text inputs (scroll).

It seems like we're a bit stuck here.  Do we force selection to the beginning when it's not set by the user?  Are we set on coupling selection with scroll, or can we consider managing them independently?  Should we simply expose the scroll method to Javascript so the behavior can be managed by the developer?

**Pull request closed without merging**
