### PR TITLE
[Android] [Deprecated] - update to gradle 4.10.1 or high

### PR DESCRIPTION
**Pull request by misaku**
Add suport to gradle 4.10.1 or high!
The new version of android studio 3.3 recommendete to update gradle project to 4.10.1 

> To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you update the Android Gradle plugin to version 3.3.0 and Gradle to version 4.10.1. [Release notes ](https://developer.android.com/studio/releases/gradle-plugin) 

>Android plugin 3.2.0 and higher now support building the Android App Bundle—a new upload format that defers APK generation and signing to compatible app stores, such as Google Play. With app bundles, you no longer have to build, sign, and manage multiple APKs, and users get smaller, more optimized downloads. [Learn more](https://developer.android.com/guide/app-bundle/?utm_source=android-studio)

but if the upgrade to the new Android gradle many warnings come up, becouse meny things was obsoleted 

> WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'. 

> WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.

> WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'. 

> It will be removed at the end of 2019.
> For more information, [see ](https://d.android.com/r/tools/task-configuration-avoidance.)
> To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

Changelog:
----------
[Android] [Deprecated] - fix warinings obsolete to update to gradle 4.10.1 or high

Test Plan:
----------
change gradle-wrapper.proprerties:
`- distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`
`+ distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`

and in build.gradle

` - classpath 'com.android.tools.build:gradle:3.2.0'`
`+ classpath 'com.android.tools.build:gradle:3.3.0'`

for warnnings starts, use this change and fix the problem! =)

### CODE REVIEW

**Comment by misaku** [comment]
I'm new to git, I'd like to help more. I test on my pc and I run ok, but I do not know what I can do to create the correct fork to pass this test. So if anyone can help me use correct. I appreciate it

**Comment by hramos** [comment]
Can you edit your original post at the top and make sure the template is filled out? What's the motivation, what are you fixing?

**Comment by dulmandakh** [comment]
@hramos with recent gradle bump, there are some new deprecating warnings and this PR is using non-deprecated APIs, thus remove deprecation warnings.

**Comment by dulmandakh** [comment]
@misaku Hi, I see deprecation warnings for below methods, and could you please fix them too.

```gradle
variant.getAssemble
variantOutput.getProcessResources
variantOutput.getProcessManifest
variant.getMergeResources
variant.getMergeAssets
variant.getPackageApplication
variant.getExternalNativeBuildTasks
```

**Comment by misaku** [comment]
@dulmandakh I will check this, thank you

**Comment by misaku** [comment]
i send new fix, but i cant join with this, thats is the link https://github.com/facebook/react-native/pull/23103

**Comment by tgensol** [comment]
@misaku Every time I am using the **Android Gradle Plugin 3.3** and doing an **Android App Bundle**, my app cannot launch and crash : `couldn't find DSO to load: libreactnativejni.so` (Even with RN 0.58 or 0.58.1, it doest not matter)

Did you have any success in bundling your app for Android with the 3.3 Gradle plugin ? Thanks

**Comment by tgensol** [comment]
@misaku Yes I was talking about the com.android.tools.build:gradle:3.3

I will try the pull and see thanks

**Pull request closed without merging**
