### PR TITLE
Fix typo of function name in ListView documentation

### PR DESCRIPTION
**Pull request by kenzan100**
When I read documents, I usually 'search within page' to see where they talk about specific things.
So I found this fix to be pretty useful. Hope it'll be merged!

### CODE REVIEW

**Comment by kenzan100** [comment]
@nicklockwood Is there anything else I should do before this will be merged? thanks!

**Comment by brentvatne** [comment]
@kenzan100 - It takes some time to merge changes to actual source files because these have to go through an internal Facebook process, even if it's just to a comment for docgen purposes, otherwise they will be overwritten later. Changes to markdown docs or files in the `/website` directory can be merged immediately though. So this one should get in there eventually.

**Comment by kenzan100** [comment]
@brentvatne OK, that makes sense. thanks!!

**Comment by brentvatne** [comment]
Great :smile: thanks!

**Comment by vjeux** [comment]
@facebook-github-bot import

**Pull request closed without merging**
