### PR TITLE
Call super in `onActivityResult`

### PR DESCRIPTION
**Pull request by satya164**

### CODE REVIEW

**Comment by astreet** [comment]
Does this affect anything? The super implementation is empty + the issue I'd be worried about is that if it ever did, we might accidentally double-handle the activity result.

**Comment by satya164** [comment]
@astreet Didn't affect anything in my test. I just added it because it wasn't there. BTW if the super does something at some point, how would we double handle it?

**Comment by satya164** [comment]
@astreet Please close the PR if it doesn't make any sense :)

**Comment by astreet** [comment]
If they were to add some activity result that is handled by default by all activities (I don't know what that'd be exactly :P) AND we sent it to JS to be handled, it could be double handled. Analogy: onBackPressed being handled by the activity and by JS (we also don't call super there). I think we should continue not to call super here.

**Pull request closed without merging**
