### PR TITLE
[iOS] enable versionning in xcode project

### PR DESCRIPTION
**Pull request by callmephilip**
## Motivation

Current Xcode project does not include settings to enable auto-incrementing build numbers using ```agvtool``` as described [here](https://developer.apple.com/library/ios/qa/qa1827/_index.html). Tools like Fastlane, for example, rely on this for commands like ```increment_build_number```. Having these settings enabled by default ensures that people will have one less thing to worry about setting up CI for RN based projects.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @jhen0409 and @tonyxiao to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-7** [comment]
@callmephilip updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9511/files/6c15a01b81e22d7ae027d3d92166c80bb48b2b59..649d3077fabc858bcfd84afe223f1f8ec50c658b)

**Comment by facebook-github-bot-8** [comment]
@callmephilip updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9511/files/6c15a01b81e22d7ae027d3d92166c80bb48b2b59..649d3077fabc858bcfd84afe223f1f8ec50c658b)

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3841281) to review internal test results.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (60/60 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:53695)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1biJRa-003JeC-RM
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:54:04 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES256-SHA:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1biJRX-00058n-I0
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:54:02 -0700
Date: Fri, 09 Sep 2016 03:53:58 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1473418438;
	bh=PQnUMYiwEsGgR0TBB9DOwS7bN4wuirMsco4csrdS37s=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jGKe42vWwW2DB5R41hq9bl36cLgzinZq9oHMyBo0sS60h9GGYIhS/le716WhY9wCA
	 35eDMcvaNljIY4cBCIVugh7LhPO4imjWqltZMZUDK6mQ9yLmY/cNUB31ftihytJmaR
	 Vp6x9+4vnii229xLWOEn55JkxX6hbdQUg+WBwioQ=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (61/60 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:42546)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJRy-003JnI-Qr
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:54:28 +0000
Received: from o8.sgmail.github.com ([167.89.101.199])
	by filter03.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES128-SHA:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJRx-00008j-0I
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:54:26 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ONS5S9wQUGGi6ojg98pwVe2mYM4=; b=ho5LiqTiaX+AtnK3
	3t7iTH9feoGaagix4gfJ5qr7s/o+dftnA8GquNZtLO9hvacR4SGClvclqex48lAZ
	KaGiNHtvVpeqmfSQl74ivpsigeD9VJVGZk15LnYWzucmPpgRCUJTV3CBOp+jU1hU
	Qz9bVf/pbB9JA5mT67J/PMwICXs=
Received: by filter0460p1mdw1.sendgrid.net with SMTP id filter0460p1mdw1.17019.57D294A92D
        2016-09-09 10:53:29.261629817 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id VjpSui0jQ8m58nPcPJS-Rg
	for <bunny@thumbmunkeys.com>; Fri, 09 Sep 2016 10:53:29.180 +0000 (UTC)
Date: Fri, 09 Sep 2016 03:53:29 -0700

**Pull request closed without merging**
