### PR TITLE
Adding PlaceAVote showcase app

### PR DESCRIPTION
**Pull request by SudoPlz**
Just added the PlaceAVote app to the react-native showcase file.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @alexleventer to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hramos** [comment]
Is https://www.crunchbase.com/organization/placeavote-com#/entity up to date?

It looks like you need to rebase before we can land this.

**Comment by facebook-github-bot-8** [comment]
@SudoPlz updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9850/files/5f3b228f37e010a0789c2de149d717c0c142449b..9db87225b2662a70213f356c61e0301bb517f75d)

**Comment by SudoPlz** [comment]
Yes I believe so. I have rebased to the latest branch, let me know if you want me to do something else please. Thank you.

**Comment by hramos** [comment]
I'm still unable to land this, looks like your own master branch is a little bit behind.

**Comment by SudoPlz** [comment]
Yes it gets updated SO fast....! Let me update the branch again!

**Comment by facebook-github-bot-0** [comment]
@SudoPlz updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9850/files/9db87225b2662a70213f356c61e0301bb517f75d..41cf8e10231ed8cac0b3462bfd86d2f4271e9c4e)

**Comment by hramos** [comment]
Can you sign the CLA as well? I know this is not strictly a code level change, but it's required by our tooling.

**Comment by facebook-github-bot-5** [comment]
@SudoPlz updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9850/files/41cf8e10231ed8cac0b3462bfd86d2f4271e9c4e..ec201f200d9ba8a2739d014f93b74de62dfd3fe1)

**Comment by SudoPlz** [comment]
Sure I just singed the CLA.

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
OK, lets give this another try!

**Pull request closed without merging**
