### PR TITLE
[Animated] support plain numbers in add and multiply operators

### PR DESCRIPTION
**Pull request by rt2zz**
This adds support for passing plain numbers into the add and multiply operators. This can be useful if you want to have one AnimatedValue for a component that is say a scale 0 -> 1 and then animated many style properties accordingly using derivative Animated values.

Thoughts? 

As far as implementation, there may be more performant implementations that do not require creating a whole new AnimatedValue for every static number. I am open to suggestion.

### CODE REVIEW

**Comment by rt2zz** [comment]
Ok I just read about flow union types and added the appropriate flow annotations. This should be fully usable now :+1:

**Comment by ide** [comment]
cc @vjeux @sahrens you guys own this API

**Comment by lelandrichardson** [comment]
I like this change. The `add()` and `multiply()` functions should definitely support primitive numbers in addition to Animated values.

As far as performance, this isn't any worse than it is right now (where the user would just be creating an `Animated.Value` themselves), and could be optimized later if need be...

:+1:

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
