### PR TITLE
Fixed Android cliPath Gradle configuration option for build.gradle

### PR DESCRIPTION
**Pull request by vitalyiegorov**
When using monorepo with react-native you need to provide `android/app/build.gradle` following params(`cliPath`):
```
project.ext.react = [
    root: "../../../../",
    cliPath: "../../../../node_modules/react-native/cli.js",
    entryFile: "...",
    hermesCommand: "../../../../node_modules/hermes-engine/%OS-BIN%/hermesc"
]
```

With latest react-native `0.64.2` version you will get:
```
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
```

Debugging this issue showed that providing `cliPath` options ends up building wrong path to cli:
```
> Task :app:bundleReleaseJsAndAssets FAILED
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '/node_modules/react-native/cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## Summary

Changed `react.gradle` for proper File creation for `cliPath` to support this configuration option.

## Changelog

[Android] [Fixed] - Changed `react.gradle` `detectCliPath` function logic for `cliPath` case

## Test Plan

Run `./gradlew assembleRelease` or `./gradlew assembleDebug`

### CODE REVIEW

**Comment by ionutmiftode** [comment]
Hello, when this will be released? A monorepo structure depends on this as `./gradlew bundleRelease` fails with the following error.

```
Error: Cannot find module '/node_modules/react-native/cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by cortinico** [comment]
> Hello, when this will be released?

This should be included in 0.67.0

**Comment by leoagomes** [comment]
Even though this issue is already closed, I want to add my two cents here since the change that "fixed" this issue broke what we had done to solve the problem of correctly finding the CLI in our monorepo.

Pinning relative paths the way it's being done here really isn't the way to go... it'll lead you down a path where you're `nohoist`ing `react-native` (and many, many more dependencies) and will give you tremendous head aches. (Even more so if your monorepo is composed of multiple React Native projects, with various native dependencies of differing versions.)

Doing something like [what expo suggests](https://docs.expo.dev/guides/monorepos/#common-issues) -- that is resolving paths to node modules dynamically -- works much, much better. Expo's approach, however, returns an absolute path and -- prior to the change introduced in this PR -- worked flawlessly. Prepending the absolute path with another absolute path (`projectDir`) then obviously resolves to an invalid path, which, in turn, breaks Expo's solution.

In order to work around the issue this PR introduces, we now had to add code that relativizes _exclusively_ the CLI path so that it yields the correct path when concatenated with `projectDir`, which is a really cumbersome, winding solution -- that is also not needed with either `hermesCommand` and `composeSourceMapsPath` because, as the comment in line 69 of the edited file says: if the user provides a path, we shouldn't really second guess it.

What I propose that is even more cumbersome but I guess better than what is available now is to add a check for `.`s in the beginning of `config.cliPath` prior to prepending it with `${projectDir}/` so that absolute paths resolve just as fine as relative paths. I would be down to implement something like this, but would like to hear more from others first.

**Comment by cortinico** [comment]
> if the user provides a path, we shouldn't really second guess it.

I totally agree here. Frankly the problem is that we should not even use `String` here as input. Those paths should actually be `File` references. Gradle gives you full access to the Java File API. You can easily create a file from the current project, the root project, or anywhere on the filesystem.

Ultimately, once the user passes a File reference, we should not transform it in any form.

The fact that those properties were designed as `cliPath: String` and not as `cliFile: File` is a design flaw of the API that should be addressed/fixed. Ideally with a proper deprecation cycle or so.

**Comment by Krisztiaan** [comment]
@leoagomes #32983 is a jab at fixing this issue, also including trying to resolve the path via `node`, and syncing the resolution strategy on both kotlin and gradle side.

**Pull request closed without merging**
