### PR TITLE
Replaced old password prop with secureTextEntry

### PR DESCRIPTION
**Pull request by emilioicai**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @trave7er to be potential reviewers.

**Comment by javache** [comment]
Actually, looks like we have the same property on iOS and Android but it's named differently, it's called password on Android, and secureTextEntry on iOS. Looks like we're using this completely the other way around in the android example too (https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/TextInputExample.android.js#L442). Would you mind fixing that too?

cc @dmmiller

**Comment by facebook-github-bot-1** [comment]
@emilioicai updated the pull request.

**Comment by emilioicai** [comment]
Ok, I updated my PR to also fix the Android example

**Comment by facebook-github-bot-9** [comment]
@emilioicai updated the pull request.

**Comment by javache** [comment]
Oh, actually it looks like the `password` property has been hidden/deprecated for a while and we should use `secureTextEntry` everywhere. I've filed a task to make the native API on Android use `secureTextEntry` as well.

Sorry for the churn but could you revert the Android changes? :)

**Comment by nicklockwood** [comment]
@pieterdb it looks like we already map `secureTextEntry` to `password` inside `TextInput.js` for the Android component, so I'm not clear exactly what the problem is? Can't we just use `secureTextEntry` everywhere already without needing any native changes.

**Comment by facebook-github-bot-8** [comment]
@emilioicai updated the pull request.

**Comment by javache** [comment]
@nicklockwood in this case it's just the iOS example that was broken. The Android API internally still uses password, but as you say we also map secureTextEntry to it.

**Comment by emilioicai** [comment]
haha, no worries, I put back secureTextEntry instead of password, this looks more consistent :)

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/637234696427414/int_phab) to review.

**Pull request closed without merging**
