### PR TITLE
Update BackAndroid.android.js

### PR DESCRIPTION
**Pull request by comountainclimber**
Simple update to the BackAndroid docs for clarity...

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @DanielMSchmidt and @webzepter to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-6** [comment]
@comountainclimber updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10005/files/15118171c17bd748939e1e5cc6070ad457dcfba3..e8b8abf434e68deceab0bd395fdaeb06077f8f9f)

**Pull request closed without merging**
