### PR TITLE
Add string as possible propType for 'systemIcon'

### LINKED ISSUE #2361: Unexpected icon error message in TabBarItemIOS
I have a TabBar item that's defined like this:

```html
<TabBarIOS.Item
    title='Projects'
    icon={ require('image!projects-32' ) }
  <Main style={styles.tab} />
</TabBarIOS.Item>
```

When I run this, the icon appears in the TabBar as hoped, but I also see this error message in the Chrome debug console:

```
Warning: Failed propType: Invalid prop `icon` of type `string` supplied to `RCTTabBarItem`, expected `object`. Check the render method of `TabBarItemIOS`.
```

I took a look at `TabBarItemIOS.ios.js` and found that if I changed [line 111](https://github.com/facebook/react-native/blob/master/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js#L111) from this:
```
    var icon = this.props.systemIcon || (
       this.props.icon && this.props.icon.uri
     );
```
to this:
```
    var icon = this.props.systemIcon || this.props.icon;
```
then the error message disappears and the icon still appears. I noticed in the debugger that the expression:
```
this.props.icon && this.props.icon.uri
```
evaluates to `"projects-32"`, when it seems that `TabBarItemIOS` is really expecting to get the full object in `this.props.icon`

Is this expected? I haven't seen anyone else mentioning this error message, so I wonder if there's something up with my implementation.

Thanks.

### PR DESCRIPTION
**Pull request by christopherdro**
Fixes #2361

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
O . M . G. It worked!

**Comment by brentvatne** [comment]
:O :O :rocket:

**Comment by sba7elfol** [comment]
Help! So how to get rid of the warning message??

**Pull request closed without merging**
