### PR TITLE
Add missing space in the io.js upgrade message

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
prathamesh react packager 81x24 2015-08-26 09-51-53

Before -

`upgradeto`

After -

`upgrade to`

### CODE REVIEW

**Comment by ide** [comment]
Thanks :)

**Comment by prathamesh-sonpatki** [comment]
Test failure on travis seems unrelated.

**Comment by javache** [comment]
Fixed by https://github.com/facebook/react-native/commit/ac069aaf129cba1990cadcf7aceb90460527fae1

**Pull request closed without merging**
