### PR TITLE
use zPosition in RCTViewHitTest to properly route touches

### PR DESCRIPTION
**Pull request by badfortrains**
Fixes https://github.com/facebook/react-native/issues/696.  Previously the hit test would return the first suitable, fully nested, view it found.  Changed the test to store all hits and chose the one with the greatest zPosition.  

The change can be seen in the UIExplorer <ListView> - Paging example.  Previously presses would fall through the sticky section headers, now the headers correctly catch the presses and the row animation underneath is not triggered.

### CODE REVIEW

**Comment by drkibitz** [comment]
1st impression :+1:  :+1:  :+1:

2nd, any measurable impact with the 2nd loop?

**Comment by badfortrains** [comment]
Haven't done any performance tests, not sure how expensive hit tests are but this could potentially add a fair number of them.  

Reading up a little more on iOS hit testing it looks like by default view layer zposition is not taken into account (haven't seen too many references to this, but [this book](https://books.google.com/books?id=QfhdAAAAQBAJ&pg=PT54&lpg=PT54&dq=ios+zposition+hit+test&source=bl&ots=O7pWC6r059&sig=ouSNK-KuFofHpzvXTyhA-WyjxOI&hl=en&sa=X&ei=xiAwVcZHgtSgBLqRgIgE&ved=0CEUQ6AEwBg#v=onepage&q=ios%20zposition%20hit%20test&f=false) claims so).  Not sure if that is something we want to honor.  If it is, or performance is an issue an alternative solution could be implementing a custom hitTest for RCTScrollView and only check for zposition there.  Maybe that would be better since I haven't actually seen any other instances of zposition being used.

**Comment by badfortrains** [comment]
My previous code was not properly dealing with children of zPositioned views, changed it so zIndex is compared at the sibling level.  This allows nesting buttons / touchable elements in sticky section headers on listViews.

**Comment by brentvatne** [comment]
@nicklockwood - I have run into this issue on my own as well - it's common for sticky headers to include touchable components, eg: for navigation, and this isn't possible currently. I tested this fix and it worked well for me.

cc @tadeuzagallo @a2

**Comment by nicklockwood** [comment]
Sorry this has been in limbo for a while. The issue we have with the fix is that it's very expensive to do the search like this. Because the loop is no longer exiting early, it basically increases the algorithm from O(n) to O(n<sup>2</sup>), which is troubling.

A possible alternative would be to pre-sort subviews by z-index, but since the JS-side of React isn't aware of the z-index property, it's not entirely clear how best to do that.

**Comment by brentvatne** [comment]
@nicklockwood - Thanks for the response! that does indeed sound troubling - what about the option of implementing a custom hitTest for RCTScrollView? It might be a good stop-gap solution until we can come up with a more comprehensive one.

**Comment by nicklockwood** [comment]
@brentvatne that sounds like a solid approach, especially since that's currently the only place we use z-index.

**Comment by brentvatne** [comment]
@badfortrains - are you up for modifying this PR based on the above conversation or would you like me to take care of it?

**Comment by nicklockwood** [comment]
It should be pretty straightforward - just loop through the sticky header indexed views first and if none of them return true, call [super hitTest].

There are certainly some optimisations that could be made, such as extracting some of the dockClosestSectionHeader logic so that you only need to check the docked headers (the others all have the same z-index as the normal views, so don't need special treatment), but I reckon that's a reasonable starting point.

**Comment by brentvatne** [comment]
Closing in favour of new PR, thanks!

**Comment by badfortrains** [comment]
Thanks @brentvatne for following up on this, the new pr looks like a good solution.

**Pull request closed without merging**
