### PR TITLE
refactor: convert `NetworkingModuleTest` to kotlin

### PR DESCRIPTION
**Pull request by KrzysztofMoch**
## Summary:
Migrated `NetworkingModuleTest` to kotlin (part of #38825)

## Changelog:
[Android] [CHANGED] - NetworkingModuleTest.java -> NetworkingModuleTest.kt

## Test Plan:
`./gradlew :packages:react-native:ReactAndroid:test`

### CODE REVIEW

**Comment by KrzysztofMoch** [comment]
I was unable to fix last 3 tests - `testCancelSomeCallsInvalidate`, `testCancelAllCallsInvalidate`, `testMultipartPostRequestBody`

@cortinico, @mdvacca I would greatly appreciate the reviews from you

**Comment by rshest** [comment]
@KrzysztofMoch Thanks for working on this one!

I see there are three test clauses that god disabled in the conversion process - those must be fixed before this can be merged.

**Comment by rshest** [comment]
> @KrzysztofMoch Thanks for working on this one!
> 
> I see there are three test clauses that got disabled in the conversion process, however - those must be fixed before this can be merged.

Ah, I've just realized that the whole suite was ignored before conversion and none of the tests were executed.

Those test would fail before the conversion as well, so it's not your change's fault.

**Comment by rshest** [comment]
> Yeah, I tried to fix them but wasn't able to. Can we left it as it is, or should I do something with it ?

No, it's alright, let's leave them like that for now, it's better be done as a follow up.

You've effectively *enabled* a bunch of tests running, not disabled, so kudos :)

**Comment by KrzysztofMoch** [comment]
Cool 🙌, let me know if you will need something

**Pull request closed without merging**
