### PR TITLE
assign webView's delegate to nil

### PR DESCRIPTION
**Pull request by itouch2**
assign webView’s delegate to nil when the delegate release

### CODE REVIEW

**Comment by ide** [comment]
What's the purpose of this? The delegate property already has the `assign` attribute:
`@property(nonatomic, assign) id< UIWebViewDelegate > delegate`
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebView_Class/#//apple_ref/occ/instp/UIWebView/delegate

**Comment by itouch2** [comment]
Setting non-weak delegates to nil is generally a good idea. Because if the delegate got deallocated, however, the UIWebView may still send message to it's delegate. This will cause a crash. Similar reasons can refer to [Set delegates to nil under ARC?](http://stackoverflow.com/questions/15016348/set-delegates-to-nil-under-arc)

**Comment by ide** [comment]
OK that makes sense. @nicklockwood could you take a quick look at this?

**Comment by nicklockwood** [comment]
Good catch, thanks!

@facebook-github-bot shipit

**Pull request closed without merging**
