### PR TITLE
Fix: Avoid contentInsets overwrites scrollIndicatorInsets on iOS #13025

### PR DESCRIPTION
**Pull request by timotew**
Fix to avoid contentInsets always overwrites scrollIndicatorInsets of ScrollView/ListView.
According to issue #13025 https://github.com/facebook/react-native/blob/a8391bde7d757d01521a6d12170fb9090c17a6a0/React/Views/RCTView.m#L299
always overide `scrollIndicatorInsets` when called and only works when `contentInsets` is not set.
We only need to worry about when `contentInsets` is set, We only have to check and reset it after `autoAdjustInsetsForView` is called.

## Motivation

Fix: https://github.com/facebook/react-native/issues/13025

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/react-native-website, and link to your PR here.)

### CODE REVIEW

**Comment by timotew** [comment]
@janicduplessis Hi there! How do we move forward on this PR.

**Comment by timotew** [comment]
@hramos  Hi there! Are these changes allowed?

**Comment by hramos** [comment]
@timotew do you have a test plan?

**Comment by timotew** [comment]
@hramos  my team has been using this branch every since. 
I will try to add a screenshot.

**Comment by brentvatne** [comment]
this is definitely a bug (I repro'd it on https://snack.expo.io/S1eOAIRrM -- `scrollIndicatorInsets` is completely ignored if `contentInset` is specified). i don't think this is the best fix, though. we should probably change [RCTView. autoAdjustInsetsForView](https://github.com/facebook/react-native/blob/22efd95be1f0b236eeaaa8a8e6d01e89771c9543/React/Views/RCTView.m#L299) so that it doesn't reset `scrollIndicatorInsets` to `baseInset` if the scrollview has a `scrollIndicatorInsets` prop set on it

**Comment by timotew** [comment]
@brentvatne that was my initial approach but I was considering the effects on other components that make use of `autoAdjustInsectsForViews`.

**Comment by brentvatne** [comment]
@timotew - I see.

I'm also concerned because `scrollIndicatorInsets` doesn't even seem to be in scope here? did you run this code? looks like it was made from Github directly

**Comment by timotew** [comment]
@brentvatne yes.  I did this before the pull then try the other approach. I later revert back to this. What fix do you think will be best and won't affect other components?

**Pull request closed without merging**
