### PR TITLE
Fix TextInput vertical alignment issue when using lineHeight prop on iOS (Paper - old arch)

### PR DESCRIPTION
**Pull request by fabriziobertoglio1987**
## Summary:

Adding paragraphStyle.maximumLineHeight to a iOS UITextField displays the text under the UITextField ([ios-screenshot-1][1], [ios-screenshot-2][2], [ios-screenshot-3][3]). The issue reproduces on Storyboard App (iOS) using UITextField and  paragraphStyle.maximumLineHeight. It is not caused by react-native.

[1]: https://user-images.githubusercontent.com/24992535/238834159-566f7eef-ea2d-4fd4-a519-099b0a12046c.png "ios-screenshot-1"
[2]: https://user-images.githubusercontent.com/24992535/238834184-feb454a9-6504-4832-aec8-989f1d027861.png "ios-screenshot-2"
[3]: https://user-images.githubusercontent.com/24992535/238834283-cf572f94-a641-4790-92bf-bbe43afb1443.png "ios-screenshot-3"

The issue is caused by a private class _UITextLayoutFragmentView (a CALayer children of UITextField), which assumes the wrong position when setting the lineHeight. _UITextLayoutFragmentView frame's y coordinates are set to 30, instead of 0 ([react-native-screenshot-1][4], [react-native-screenshot-2][5])
- The _UITextLayoutFragmentView layer does not correctly position 
- The issue is caused by adding paragraphStyle.maximumLineHeight to UITextField.attributedText
- The parent UITextField bounds do not correctly position child _UITextLayoutFragmentView. 
The issue causes the below text Sdfsd to display under the TextInput.

[4]: https://github.com/Expensify/App/assets/24992535/06726b45-7e35-4003-9fcc-50c8d0dff0f6
[5]: https://github.com/Expensify/App/assets/24992535/d9745d29-8863-4170-bcc3-e78fa7e550d2

I was able to fix the issue and correctly align the private layout view _UITextLayoutFragmentView using the public API RCTUITextField textRectForBound, which allows modifying the UITextField frame and inset.
The solution consists in the following steps, applied only to UITextField with lineHeight prop:

1) set _UITextLayoutFragmentView to vertically align to the top. Required to correctly align _UITextLayoutFragmentView.
2) apply custom bounds with RCTUITextField textRectForBound to align _UITextLayoutFragmentView with the correct y coordinates and height
2) Adjust text baseline to be center aligned

fixes https://github.com/facebook/react-native/issues/28012 fixes https://github.com/facebook/react-native/issues/33986
Related https://github.com/facebook/react-native/issues/35741 https://github.com/facebook/react-native/issues/31112

## Changelog:

[IOS] [FIXED] - Fix TextInput vertical alignment issue when using lineHeight prop on iOS (Paper - old arch)

## Test Plan:

Extensive test included in the PR comments https://github.com/facebook/react-native/pull/37465#issuecomment-1551459879

### CODE REVIEW

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Test Cases after applying the fix</summary>
<p>



https://github.com/Expensify/App/assets/24992535/5b9c0945-6415-4ce8-a1f2-c9d13838a92c

Screenshot 2023-05-11 at 9 24 44 AM


Screenshot 2023-05-11 at 9 25 24 AM

</p>
</details>

<details><summary>Test Cases before applying the fix</summary>
<p>

https://github.com/Expensify/App/assets/24992535/86cdcd45-0289-498c-a36e-6bc8d7fadd73


Screenshot 2023-05-11 at 9 36 15 AM

Screenshot 2023-05-11 at 9 36 53 AM

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>before fix - increase/decrease padding top</summary>
<p>

to make the video more clear, we change the style paddingTop to both TextInput

<video src="https://github.com/Expensify/App/assets/24992535/b8cc2c35-a563-4f4c-a267-a45bc4bd8aa3" width="250" />

</p>
</details>


<details><summary>after fix - increase/decrease padding top</summary>
<p>

We change the style paddingTop only for the first TextInput

<video src="https://github.com/Expensify/App/assets/24992535/fd1c8c59-5d5f-49a1-8074-1ddb3b068bc0" width="250" />


</p>
</details>



<details><summary>before fix - increase/decrease border</summary>
<p>


https://github.com/Expensify/App/assets/24992535/fc905f79-728f-4875-b03c-aad10bf49486


</p>
</details>

<details><summary>after fix - increase/decrease border</summary>
<p>



https://github.com/Expensify/App/assets/24992535/3720a9a1-0a7e-4225-a405-2808dc59125c


</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>before the fix - text is not correctly aligned with different lineHeight, fontSize and height</summary>
<p>


https://github.com/Expensify/App/assets/24992535/4cb1fe3f-65cf-4685-b84a-c469d481141c



</p>
</details>

<details><summary>after fix - text is correctly aligned with different lineHeight, fontSize and height</summary>
<p>

https://github.com/Expensify/App/assets/24992535/3e7636fc-3387-4f45-852d-878183094104

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Before - behaviour single line TextInput without lineHeight prop</summary>
<p>

https://github.com/Expensify/App/assets/24992535/1cdc96c4-3e54-4d81-8ef2-e6ec1fe89c0b

</p>
</details>

<details><summary>Before - behaviour single line TextInput with lineHeight prop</summary>
<p>

https://github.com/Expensify/App/assets/24992535/57968f55-d9cb-4399-8280-24cb86055ffe

</p>
</details>

<details><summary>Before - behaviour multi line TextInput without lineHeight prop</summary>
<p>



https://github.com/Expensify/App/assets/24992535/a681e7ec-72de-4760-8c46-bf7ffa0ead02


</p>
</details>

<details><summary>Before - behaviour multi line TextInput with a lineHeight prop</summary>
<p>


https://github.com/Expensify/App/assets/24992535/9c5e025d-18a5-41e0-9f3b-c896c1cffe8f

</p>
</details>

<details><summary>After - multi line TextInput with a lineHeight prop (first video)</summary>
<p>

https://github.com/Expensify/App/assets/24992535/7ea05a6d-a169-4085-a58a-820e055d0152

</p>
</details>

<details><summary>After - multi line TextInput with a lineHeight prop (second video)</summary>
<p>



https://github.com/Expensify/App/assets/24992535/d1c5fd82-d896-4824-8e4b-efe89bf44758


</p>
</details>

<details><summary>After - multi line TextInput without a lineHeight prop</summary>
<p>

https://github.com/Expensify/App/assets/24992535/c0c3d74c-2464-4578-a62b-509e7667cad4

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>After - Testing paddingTop on a single line TextInput</summary>
<p>


Screenshot 2023-05-12 at 4 45 37 PM


Screenshot 2023-05-12 at 4 47 46 PM


</p>
</details>

<details><summary>After - Testing borderWidth with single-line textinput</summary>
<p>


Screenshot 2023-05-12 at 4 49 17 PM


</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
<details><summary>Before - using fontSize multiplayer and lineHeight with TextInput</summary>
<p>

| Test Case    | fontSizeMultiplier setting |
| ----------- | ----------- |
| <video src="https://github.com/Expensify/App/assets/24992535/55282106-33bc-4f2b-8be4-e1b9941b7e7a" width="250" />    | <image src="https://github.com/Expensify/App/assets/24992535/7dc8542d-8e21-48b6-8e7e-f39b50a820be" width="250" />      |






</p>
</details>



<details><summary>After - using fontSize multiplayer and lineHeight with TextInput</summary>
<p>



https://github.com/Expensify/App/assets/24992535/543a646d-6850-4631-a8ab-45fec612bbc8



https://github.com/Expensify/App/assets/24992535/2b126f32-45a8-428b-9385-81dc849d06f4


</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/assets/24992535/230bff56-9f84-4c1e-a8c9-d1c5747b7b00

**Comment by fabriziobertoglio1987** [comment]
@sammy-SC Disabling the [debug flag](https://github.com/facebook/react-native/pull/35319#issuecomment-1414259311) did not show any errors. Could you please share the errors? Thanks a lot. I wish you a good day.

**Comment by NandoMB** [comment]
OMG, you fixed it? I'm almost having a ulcer trying to fix it in my code... Merge it, please! 😃

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot 🙏  @NandoMB 
- Issues https://github.com/facebook/react-native/issues/28012 and https://github.com/facebook/react-native/issues/33986. They are fixed with the PR
- Issue https://github.com/facebook/react-native/issues/31112 I replied in https://github.com/facebook/react-native/issues/31112#issuecomment-1562331521

**Review by fabriziobertoglio1987 — COMMENTED** [review]
<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<image src="https://github.com/facebook/react-native/assets/24992535/b3a0807d-a0a7-4e96-bfc7-e2d120b89517" width="250" />


</p>
</details>

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<image src="https://github.com/facebook/react-native/assets/24992535/2f97903e-61af-49c8-9568-f7e2da039eb8" width="250" />

</p>
</details>

<details><summary>CLICK TO OPEN TESTS RESULTS</summary>
<p>

<image src="https://github.com/facebook/react-native/assets/24992535/ceb680ad-864f-497f-a140-b6c6d552f30f" width="250" />

</p>
</details>

**Comment by sammy-SC** [comment]
> @sammy-SC Disabling the [debug flag](https://github.com/facebook/react-native/pull/35319#issuecomment-1414259311) did not show any warning. Could you please share the log of the CI step `Facebook Internal - Linter`? Thanks a lot. I wish you a good day.

Sorry for the slow reply, I was away for +2 weeks on vacation. I will just just fix the linter. No worries.

**Comment by sammy-SC** [comment]
Hello @fabriziobertoglio1987 

we will have to revert this change and evaluate next steps.

The change causes a slight difference on how text is rendered. I realise the change is small but it can lead to text's baselines being off, which we don't want.



Screenshot 2023-07-07 at 10 11 23

**Comment by fabriziobertoglio1987** [comment]
Thanks, @sammy-SC, could you please share the source code for this example?

**Comment by fabriziobertoglio1987** [comment]
### Update 12/07

There is a difference in the baseline computation between RCTTextShadowView [postprocessAttributedText](https://github.com/facebook/react-native/blob/9ab27e8895d6934e72ebdc601d169578ab9628f1/packages/react-native/Libraries/Text/Text/RCTTextShadowView.m#L124-L168) and RCTTextAttributes [effectiveParagraphStyle](https://github.com/facebook/react-native/pull/37465/files#diff-38333c03094e568d775af03727306a9e737fec7434e31f2f6e849f9663e48052R135-R139).

Given the following example:

```xml
<Text style={{lineHeight: 500, fontSize: 15, backgroundColor: 'red'}}>
  font size 15
  <Text style={{fontSize: 50, lineHeight: 500}}>font size 50</Text>
</Text>
```

- The RCTTextShadowView implementation calculates the same baseline for the entire Text based on the highest lineHeight/fontSize
- The RCTTextAttributes implementation calculates different baseline for each Text span, based on the Text span lineHeight and fontSize

**Comment by fabriziobertoglio1987** [comment]
Thanks, @sammy-SC. I published PR https://github.com/facebook/react-native/pull/38359 to fix the regression from comment https://github.com/facebook/react-native/pull/37465#issuecomment-1625110372.

**Pull request closed without merging**
