### PR TITLE
Unexpected token

### PR DESCRIPTION
**Pull request by alzuma**
with return I get error

image

by removing it - no errors, and it works
image

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @scarlac to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ide** [comment]
There needs to be a return value... this is not the right fix.

**Comment by alzuma** [comment]
https://facebook.github.io/react-native/docs/navigator.html there is no return in renderScene :)

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by ide** [comment]
There's an implicit `return` in those examples. Looking at your code the problem is that you added an explicit `return` when there should be an implicit one.

**Comment by alzuma** [comment]
That is not my code it is code from example. And it does not work with return...

**Comment by ide** [comment]
Your code and the code from the example are different because of the curly brace, take a closer look, read up on JS if you don't see the difference.

**Comment by alzuma** [comment]
It is not like I don't believe in you :)  - but https://www.youtube.com/watch?v=MuG14Ke62YE

**Pull request closed without merging**
