### PR TITLE
Add Copy Stack button to Red Box (iOS)

### PR DESCRIPTION
**Pull request by poppybank**
Added a button to the iOS Red Box to enable copying of the error and stack trace to the clipboard to make it easier to paste the error and stack into bug reports or other text windows. Clicking the Copy button on the bottom of the RedBox screen or pressing Cmd-Option-C keyboard shortcut in the simulator will copy the full stack trace as text to the iOS pasteboard and when in the simulator you can then hit Command-C to get the text to the Mac's pasteboard for pasting in your favorite reporting/tracking app.

No tests for this change - I don't see any tests to extend for the RCTRedBoxWindow class. No impact on APIs or core React Native functionality. I validated it by running test React Native apps with red box errors and both hitting the copy button or using the command key shortcut in the emulator to get the text of the stack to the iOS pasteboard.
redboxcopybutton

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @jeanregisser and @javache to be potential reviewers.

**Comment by poppybank** [comment]
@jeanregisser or @javache would you mind taking a quick look at this PR? Thanks.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1016878125027364/int_phab) to review.

**Comment by frantic** [comment]
Just noticed this, awesome! But can we change the copy and reload buttons order? I bet many people still rely on their muscle memory

**Comment by frantic** [comment]
Some more feedback – for people not familiar with iOS simulator that much it might be confusing that after pressing Copy they still need to Cmd+C to get Simulator's pasteboard content to be transferred to Mac's.

**Comment by jeanregisser** [comment]
Shouldn't the copy method be part of the actionDelegate? cc @javache

**Comment by javache** [comment]
@jeanregisser Yup, missed that. Moving this to the actionDelegate would be preferable.

@frantic: Any suggestion on how we should make that more clear? Some kind of toast message that appears to say "Press cmd+c to copy to system clipboard?"

**Comment by jeanregisser** [comment]
More code needed but why not have the packager handle putting the message in the osx clipboard?
Similar to what is done for opening the editor?

**Comment by frantic** [comment]
The packager idea is great, it will also mean things will just work on Android and when running on the phone (unless you want to copy the content on your phone :) )

**Comment by poppybank** [comment]
Copying the content on the phone is definitely useful and works with the current version. You can just tap Copy and then email or slack someone the error and stack. Checking for running in the Simulator and getting the packager to put it on the Mac's pasteboard is a good addition.

**Comment by poppybank** [comment]
Thanks for the suggestions folks. New PR submitted including the call through the packager to make it automatic when you are using the simulator for iOS - https://github.com/facebook/react-native/pull/7630

**Pull request closed without merging**
