### PR TITLE
Add ignoreSslError prop to <WebView />

### PR DESCRIPTION
**Pull request by leeight**
In the dev mode, we should ignore self-sign ssl error, so i add a new prop to `<WebView />`.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @spicyj and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@leeight updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9680/files/0772d272879e7b3366fefe0a7dc280363862294e..b618614214decfbe0859e1c7110f2548333fa23d)

**Comment by facebook-github-bot-4** [comment]
@leeight updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9680/files/b618614214decfbe0859e1c7110f2548333fa23d..1908e83b1d2d93a2c2ab082f33a2fa6f7aa57d49)

**Comment by facebook-github-bot-4** [comment]
@leeight updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9680/files/1908e83b1d2d93a2c2ab082f33a2fa6f7aa57d49..1f847d35041bdec0cea36bc423b5b1f4e27221e4)

**Comment by facebook-github-bot-4** [comment]
@leeight updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9680/files/1f847d35041bdec0cea36bc423b5b1f4e27221e4..297c52c7916b98a1159aacbf09b3166334ada4be)

**Comment by leeight** [comment]
Ping @spicyj

**Comment by spicyj** [comment]
I don't think this is a healthy practice so I'm going to reject this PR. It would be easy to forget to turn this option off in prod. For development, you can make a self-signed certificate and load it onto your phone so that it is trusted.

**Comment by leeight** [comment]
@spicyj I can install self-signed cert on my own device, But i don't have the authority To install it on some test devices. This option is helpful under this case.
Maybe we can show some warnings when this option was on.

**Comment by mkchx** [comment]
@leeight  Can you provide a sample example of how to extend the WebView and override onReceivedSslError in RN?

**Comment by xemasiv** [comment]
Just use a Free SSL that isn't self-signed instead.

## Free SSL & React Native Apps

Problem:
* Your react-native app can't reach your http server, since https is required
* Your https server can't be reached, because sites / endpoints using self-signed certificates are disallowed
* Long story short, XHR / axios / Webview can't reach your server

Solution:

1. Generate a CSR

* You can use Namecheap's tool - https://decoder.link/csr_generator
* Make sure you keep the private key, you'll use it later

2. Go get a Free SSL catered by Comodo.

* https://ssl.comodo.com/free-ssl-certificate.php
* The certificate bundle you'll get won't be a self-signed one, a commodo support representative confirmed this with me.
* Use your CSR, then validate your ownership
* After couple of minutes you'll receive your cert bundle in your email, with 4 files
  * `api_realtycoast_io.crt` (named after the domain I used, which is api.realtycoast.io)
  * `AddTrustExternalCARoot.crt`
  * `COMODORSAAddTrustCA.crt`
  * `COMODORSADomainValidationSecureServerCA.crt`
  
3. Do a CA/End-Entity Certificate matching

* Go to CA/End-Entity Certificate Matcher
* Paste the content of your `api_realtycoast_io.crt` equivalent as the END ENTITY CERTIFICATE
* Paste the content of your `COMODORSADomainValidationSecureServerCA.crt` as the CA CERTIFICATE
* Validate that shit, should be successful - if so, we proceed

4. Configure your Express SSL configuration

* Create a `/ssl` folder
* Put all those certificate files there
* Create a `private.key` file, PASTE YOUR PRIVATE KEY from STEP 1 there
* Now we use your site's certificate, your private key, and your CA certificate

```
const fs = require('fs');
const http = require('http');
const https = require('https');
const express = require('express');
const bodyParser = require('body-parser');

const SSL = {
  credentials: {
    key: fs.readFileSync('ssl/private.key', 'utf8'),
    cert: fs.readFileSync('ssl/api_realtycoast_io.crt', 'utf8'),
    ca: [
      fs.readFileSync('ssl/COMODORSADomainValidationSecureServerCA.crt', 'utf8')
    ]
  }
};

const app = express();
app.use(bodyParser.json());
app.get('/', (req, res) => res.send('Hello World!'));
http.createServer(app).listen(80);
https.createServer(SSL.credentials, app).listen(443);
```

* Git add, commit and push that shit
* Run your nodejs server again

5. Verify that shit

* Visit your `https://yoursite.com/` that should be working well
* Visit `https://www.sslshopper.com/ssl-checker.html`
* Check your server endpoint's url there, you should be seeing ALL CHECKS, AND NO X's

6. Rebuild your react-native app, and re-run it - should be workign well now

* Test code for webview

```
import { WebView, View } from 'react-native';

// in your component render(), below

return (
<View style={{flex:1}}>
	<WebView
	source={{uri: 'https://api.realtycoast.io/auth'}}
	javaScriptEnabled={true}
	domStorageEnabled={true}
	startInLoadingState={true}
	style={{ flex:1, height: 500, width: 350 }}
	/>
	</View>
);
```

* Test code for axios

```
	// replace your baseURL and url, below
	
          <Button onPress={
            ()=>{
              const x = axios.create({
                baseURL: 'https://api.realtycoast.io/',
                timeout: 10000,
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json',
                }
              });
            x.request({
              url: '/user/123'
            })
              .then(function (response) {
                console.log(response);
              })
              .catch(function (error) {
                console.log(error);
              });
            }
          }>
            <Text>Axios Test</Text>
          </Button>
```

**Comment by SuhairZain** [comment]
Why is @xemasiv solution downvoted so much? Also, I'd like to load a locally running server using a WebView. I couldn't find a way to make a non-self-signed certificate for localhost. Is there a way to make it happen or any workarounds?

**Comment by dbkblk** [comment]
> 
> 
> Why is @xemasiv solution downvoted so much? Also, I'd like to load a locally running server using a WebView. I couldn't find a way to make a non-self-signed certificate for localhost. Is there a way to make it happen or any workarounds?

I think that's because it's easy to generate a certificate nowadays, but you cannot use that in local networks. That means you cannot use webview as a local webview for a selfhosted app. That's unlucky, because I'm in a configuration where the server don't have any access to internet, and the clients does.

**Pull request closed without merging**
