### PR TITLE
[SliderIOS] Add thumbTintColor property

### PR DESCRIPTION
**Pull request by vitch**
This PR is an attempt to continue on from #799 and add the `thumbTintColor` property to `SliderIOS`

Unfortunately this doesn't work due to what seems to be [a bug in UIKit](http://stackoverflow.com/questions/19061157/ios-7-uislider-thumbtintcolor-does-not-change). I have tried to add the workaround but it still doesn't seem to work. Unfortunately I'm not experienced with Objective C so I'm not sure where to go next but I thought it was worth providing the PR for someone to continue on from...

### CODE REVIEW

**Comment by vitch** [comment]
The workaround works if I set it to an actual image in my `Images.xcassets` e.g. 

```
[slider setThumbImage:[UIImage imageNamed:@"BackArrow"] forState:UIControlStateNormal];
```

So it seems the problem is related to `slider.currentThumbImage` not returning a valid image...

**Comment by vitch** [comment]
And after a bit more digging it is timing related. If I return to a view then the `thumbTintColor` is set correctly. So I guess we are initially accessing `slider.currentThumbImage` too early in its lifecycle before it has been set...

**Comment by brentvatne** [comment]
@vitch - take a look at how this is handled currently for `value`, `minimumValue` and `maximumValue` - if you set `value` before either of those then it will be clipped to whatever the min-max range is, so it is similarly related to timing. [RCTSlider.m](https://github.com/facebook/react-native/blob/master/React/Views/RCTSlider.m)

**Comment by vitch** [comment]
Thanks for the comment @brentvatne but I'm not sure I understand.

The problem isn't with when the user sets the value, it's seems to be within UIKit - as shown [in this SO post](http://stackoverflow.com/questions/19061157/ios-7-uislider-thumbtintcolor-does-not-change). 

The issue I had with timing is that the workaround suggested in that post doesn't seem to work for me (see aff48abd8c5f6b4b11c33c0db5bdedd74fb9d5da) - my guess is that this is because `slider.currentThumbImage` isn't initialised at the time `view` is called but I'm a complete beginner at Objective C so I may be off the mark...

**Comment by brentvatne** [comment]
@vitch - any interest in following up on this?

**Comment by nicklockwood** [comment]
Already implemented.

**Pull request closed without merging**
