### PR TITLE
Add TextInput's prop caretHidden implementation for Android and add the prop to docs

### PR DESCRIPTION
**Pull request by henrikra**
This PR will:
- add missing documentation for `caretHidden` prop to the docs
- add `caretHidden` prop implementation for Android

I noticed this by accident when looking at `RCTTextFieldManager.m` and there is `RCT_EXPORT_VIEW_PROPERTY(caretHidden, BOOL)` which hides caret on iOS. Then I realised that the docs were missing for this prop and implementation on Android side :)

## Test plan
Render `TextInput` with prop `caretHidden`. After this caret is not visible anymore.
`<TextInput style={styles.input} caretHidden />`

If you omit the prop then caret is visible again
`<TextInput style={styles.input} />`

### CODE REVIEW

**Comment by henrikra** [comment]
Any comments on this PR? I have no idea why some test breaks because my PR is so small :D

**Comment by janicduplessis** [comment]
Hey thanks for the PR, looks good!

@facebook-github-bot shipit

**Comment by henrikra** [comment]
How this thing usually goes? The PR is now imported. What to do next? :D

**Comment by janicduplessis** [comment]
Looks like the import failed for some reason, could you rebase on master and I'll try again.

**Comment by henrikra** [comment]
@janicduplessis What about now?

**Comment by henrikra** [comment]
@janicduplessis Hello? :D Any updates? I see that https://github.com/facebook/react-native/commit/ae57b25134c4db8be8539a0f0e6e52d46c850339 this is getting into next version so I think this should too?

**Comment by janicduplessis** [comment]
Hey sorry, I missed the notification.

@facebook-github-bot shipit

**Comment by henrikra** [comment]
Thanks! How this btw goes? How can I see when this is on https://github.com/facebook/react-native/compare/v0.42.0-rc.0...master

**Comment by janicduplessis** [comment]
Your commit will appear on master once it passes facebook internal CI and the PR will get closed.

**Comment by janicduplessis** [comment]
Sorry we had a lot of CI issues this week, trying again.

@facebook-github-bot shipit

**Pull request closed without merging**
