### PR TITLE
[Codegen 101] Enrich getCommandProperties with the parser object

### PR DESCRIPTION
**Pull request by kyawthura-gg**
## Summary

> [Codegen 101] The code of getCommandProperties is almost identical in [Flow](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/components/index.js#L128) and [TS](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/typescript/components/index.js#L129). There are small differences between flow/ts, so we need for it to accept a Parser object. Enrich the parser object with the required methods if necessary.

## Changelog:

[Internal] [Changed] - Enrich getCommandProperties with the parser object

## Test Plan

`yarn test react-native-codegen`

### CODE REVIEW

**Review by cipolleschi — CHANGES_REQUESTED** [review]
That's a very good starting points.
There are a few other improvements we can do:
1. Flow, line 126 (it doesn't let me add a comment at that line) and Typescript, line 126: that check can go in the `Parser` object. So the Flow parser can return `InterfaceDeclaration` and the TS parser can return `TSInterfaceDeclaration`
2. Line 134: same as above. `Parser` can have a `bodyProperties` function that, given a typeAlias returns `body.properties` for Flow and `body.body` for TS.
3. Line 141: we can add the `propertyNames` function to the parsers that extract the right array of property names.
4. After these changes, the two functions should be actually identical and we can move it in a single file in `parser-commons.js`, for example.

What do you think?

**Comment by kyawthura-gg** [comment]
Moved propertyName to parser common file.
In Flow, from line 114 to 121 are almost the same as TypeScript. If we like to move those lines, `propertyName` function need to accept `language` param. Is this good idea? Let me know what you think.

**Comment by cipolleschi** [comment]
Yes and no. If property name has to switch over the language, it should not accept a `language` parameter, but it should accept a `Parser`. The parser encapsulates the language specific logic, so the `TypeScriptParser` knows how to return something for TypeScript and the `FlowParser` knows how to work with Flow. 

Does this make sense?

**Comment by kyawthura-gg** [comment]
Yes, I actually meant `Parser`. Sorry for confusion.

**Comment by kyawthura-gg** [comment]
I meant these lines. Sorry for confusion.

In Flow,
```js
  let properties;
  try {
    properties = typeAlias.body.properties;
  } catch (e) {
    throw new Error(
      `Failed to find type definition for "${commandTypeName}", please check that you have a valid codegen flow file`,
    );
  }
```

In TypeScript,
```js
  let properties;
  try {
    properties = typeAlias.body.body;
  } catch (e) {
    throw new Error(
      `Failed to find type definition for "${commandTypeName}", please check that you have a valid codegen typescript file`,
    );
  }
```

**Comment by kyawthura-gg** [comment]
Added `bodyProperties`

**Review by cipolleschi — APPROVED** [review]
Great job! It looks good to me!

**Pull request closed without merging**
