### PR TITLE
[css-layout] Only exit from layoutNode when no children

### PR DESCRIPTION
**Pull request by paramaggarwal**
Following https://github.com/facebook/react-native/pull/1538#issuecomment-116354660, this imports the one line change from https://github.com/facebook/css-layout/pull/84.

### CODE REVIEW

**Comment by vjeux** [comment]
@facebook-github-bot import

**Comment by paramaggarwal** [comment]
@vjeux This hasn't landed in `master` yet. Can't publish an OSS library for `AspectRatio` without this in core! Please help!

**Comment by paramaggarwal** [comment]
Please review!

**Comment by paramaggarwal** [comment]
This is marked as imported, but hasn't shown up on master!

**Comment by paramaggarwal** [comment]
Still hasn't shown up on `master`, please pull this in!

**Comment by chirag04** [comment]
is it taken care of from the latest sync of css-layout which landed in master today?

**Comment by paramaggarwal** [comment]
Yes! Thanks @chirag04.

**Comment by chirag04** [comment]
:+1:

**Pull request closed without merging**
