### PR TITLE
[MovieApp] Add key to image components inside of MovieCell.

### LINKED ISSUE #89: [Image] Old images on Movies example app listings
To reproduce, search for a movie and browse into it, then back out of the movie view to the search, then delete your search terms by holding down the delete key (on your laptop while running in simulator). It seems to be timing dependent but with a few tries I was able to generate the screenshots below.

wayne

apollo

Maybe this is throttling from the data API? Maybe caching would help?

not found

### PR DESCRIPTION
**Pull request by christopherdro**
Resolves #89

test plan: open movies app, search for various movie titles, ensure that the images match the titles

### CODE REVIEW

**Comment by brentvatne** [comment]
looks good to me

**Comment by spicyj** [comment]
It would probably be better to add the key to the whole cell:

https://github.com/facebook/react-native/blob/ccd9f00a848b9522a9b2f2e29b1ae3a1951499a0/Examples/Movies/SearchScreen.js#L264

Mind changing it to that?

**Comment by christopherdro** [comment]
That's actually what my first attempt at resolving the issue was. 

However, I was still able to reproduce the issue.

Could this a bug with the Image component?

**Comment by spicyj** [comment]
That doesn't make sense to me.

**Comment by spicyj** [comment]
If the row's key changes, all of its descendants including the Image will be recreated.

**Comment by christopherdro** [comment]
Hmm, I must've of overlooked something then. 
I just tested a decent amount of times with setting the key on the whole cell.

Will cleanup and push. Thanks

**Comment by christopherdro** [comment]
Sorry for the issue.
https://github.com/facebook/react-native/pull/2065

**Pull request closed without merging**
