### PR TITLE
[WIP] Android 64-bit

### PR DESCRIPTION
**Pull request by govi**
## Motivation

Scratching my own itch #2814  to make sure react-native works on 64-bit Android devices. Using abifilters to restrict it to bundle only 32-bit .so files drops performance heavily on 64-bit devices.

I have attempted to tackle the issue. Much of it 'just' worked, but without being able to verify them with the full suite of tests, I will leave this as Work in Progress. I pored over https://facebook.github.io/react-native/docs/testing.html but it wasn't a lot of help. I'll leave the details of the errors from the PR description for now.

## Headline changes

1. Enabled the 64bit arm eabi and x86_64
2. Changed the CXX11 flags for folly & cxxreact
3. Upgraded to use the new soloader(0.3.0) that no longer restricts the so files to be copied.
4. Upgraded double-conversion to 1.1.6, for 64-bit support.
5. Updated generator templates

## Test Plan

1. Used gradle to make the .aar file and verified that it contains the .so files for all architectures ("armeabi-v7a", "x86", "x86_64", "arm64-v8a").
2. Used that aar as a gradle dependency to build my react native app and verified it on a Nexus 6p.
3. SoLoader copies the right files, and React Native screens work as they should. 

### Automated Tests

It's not ideal. Probably because this is the first time I have attempted to run these.

Android Unit Tests pass but having massive trouble getting the integration tests going. Its the same both on master and on my branch. Would like some help with it.

Gradle tests fail on master (at least on my setup) for all yoga tests as its unable to load yoga.so. We have the same failures on this branch as well.

There also an oddity with robolectric, where the jars are not getting copied to their correct locations. Had to do it manually.

Buck tests for iOS fail on snapshots for Scroll View. Looks like the scroll view test page now has a new component that is not there in the snapshots. But that component has loading animation, and it is not going to be possible to have a 100% match (it's probable, but the probability is low). Have the same issue on master.

## Other Considerations 

Finally, we also need the 64-bit enabled JSC. There are two options,

1. Is to resurrect this https://github.com/facebook/android-jsc/pull/19. The tar location is gone now, so the script has to be modified to checkout the repo at the correct revision. Its a known version and since there are no "tests", seems like a safer option for this PR. Which is what I had to do locally and pointed it to our internal mvn that has the 64-bit enabled JSC.

2. The other option is to https://github.com/SoftwareMansion/jsc-android-buildscripts. Seems to be what expo are using/planning to use. Of course, it needs more testing. Last I have seen is expo rolling it back 

## Related PRs

Nothing at the moment.

## Release Notes

[ANDROID] [BUGFIX] [ReactAndroid] - Enabled 64-bit support

### CODE REVIEW

**Comment by gengjiawen** [comment]
Why bundle so  instead of generate from source?

**Comment by govi** [comment]
@gengjiawen that was a mistake.. i have since cleaned it up. Would really like some help to complete this PR.

**Comment by gengjiawen** [comment]
I think first we need to get https://github.com/facebook/android-jsc/pull/19 merged.

**Comment by AaaChiuuu** [comment]
@ayc1 @mdvacca @axe-fb ex-FB Android Messenger people at Uber are asking for this.

**Comment by govi** [comment]
@gengjiawen yup.. but we prolly have to update the PR. The tar ball location is 404. I had to checkout their SVN repo and up to the revision.

**Comment by gengjiawen** [comment]
@hramos @janicduplessis Can you guys to push https://github.com/facebook/android-jsc/pull/19 get merged, we have been stuck with old jsc and lack of armeabi-64 support for a long time.

**Comment by hovox** [comment]
This issue is super important for us. We have started RN integration into our app, and this may hold us back. Please let us know what we need to do to increase the priority of this issue, or if we can help somehow to get issue resolved.

**Comment by hey99xx** [comment]
Can we close this now? New JSC has been merged into master branch and it's 64-bit architectures are enabled in Application.mk

**Pull request closed without merging**
