### PR TITLE
[WIP] Fabric podspecs

### PR DESCRIPTION
**Pull request by ericlewis**
## Summary

In service of #22989. This PR adds a podspec capable of building / linking fabric with RNTester. A lot of the folly work is based on @kmagiera commits a few months ago, found [here](https://github.com/kmagiera/react-native/commits/fabric3).

## Todo
- [ ] Proper fix for Float.h conflicting with system headers. (Is a rename okay?)
- [ ] SliderEventEmitter uses floats, which causes Xcode to complain
- [ ] RCTSwitchComponentView references rncore, which appears to be missing 
- [ ] Importing RCTSurfacePresenter.h to AppDelegate causes header errors (due to not being objc++)
- [ ] Check if all folly imports are required
- [ ] Check if libevent is required.

## Changelog

[iOS] [Added] - Fabric podspec

## Test Plan

Pod install RCTFabric & RCTFabricSample & libevent to RNTester, run.

### CODE REVIEW

**Comment by fkgozali** [comment]
cc @shergin @JoshuaGross

also cc @fson who's looking into refactoring existing podspec (non fabric): https://github.com/facebook/react-native/pull/23559

**Comment by fson** [comment]
#23559 splits the subspecs of React.podspec into separate podspecs, so it would be good to move Fabric to it's own podspecs too. Following the format introduced in [RFC0004](https://github.com/react-native-community/discussions-and-proposals/blob/353d44f64957113409eb16f836e23dba396a6b46/proposals/0004-cocoapods-support-improvements.md) and implemented in #23559, pending any changes, I think this could mean two podspec files for fabric:
* Podspec for `React-RCTFabric` in `./React/Fabric/React-RCTFabric.podspec`
* Podspec for `React-fabric` in `./ReactCommon/fabric/React-fabric.podspec`

**Comment by ericlewis** [comment]
@fson is it also worth putting the fabric subspecs in their respective folders? It gets a little nested, so I am not sure if that is the right approach.

**Comment by ericlewis** [comment]
I am unable to work on this further, anyone else is free to pick up where I left off.

**Pull request closed without merging**
