### PR TITLE
bump NDK toolchain to 4.9

### PR DESCRIPTION
**Pull request by dulmandakh**
This PR will bump NDK_TOOLCHAIN_VERSION to 4.9 or use GCC 4.9 to build C++ code. Once merged, we can bump folly to a newer version, which requires GCC 4.9.

Test Plan:
----------
Everything build and run as usual.

Release Notes:
--------------
[ANDROID] [ENHANCEMENT] [NDK] - bump NDK_TOOLCHAIN_VERSION to 4.9

### CODE REVIEW

**Comment by hramos** [comment]
Also cc @fkgozali

**Comment by dulmandakh** [comment]
@fkgozali please review and merge

**Comment by dulmandakh** [comment]
Or maybe https://github.com/facebook/react-native/pull/19893, which does the same but also bumps NDK version. I tried every NDK version, and r14b was the latest version to compile with minimal code changes.

**Comment by dulmandakh** [comment]
@hramos is there any issue regarding merging this PR? I was able to compile RN with latest NDK, and would like to create a PR once this merged.

**Comment by hramos** [comment]
@dulmandakh No, no issues. We try to avoid landing diffs late on Friday afternoons. I'll get this going today.

**Pull request closed without merging**
