### PR TITLE
Add flowconfig to SampleApp

### PR DESCRIPTION
**Pull request by frantic**
Added `.flowconfig` template (and a test for it!)

Test Plan:

```
$ ./scripts/e2e-test.sh
```

### CODE REVIEW

**Comment by frantic** [comment]
@bhosmer - does `.flowconfig` look good?

**Comment by bhosmer** [comment]
@frantic LGTM - passes w/0 errors, right?

**Comment by ide** [comment]
On Flow's side would it be possible to transitively include .flowconfigs of [include]'d directories and require()'d npm packages? It would let projects customize their .flowconfig files while keeping an up-to-date reference to React Native's .flowconfig and other projects' .flowconfig files if Flow gains more adoption. I opened an issue over at https://github.com/facebook/flow/issues/308 if that's a better place to make progress.

**Comment by bhosmer** [comment]
@ide James, note that such an include wouldn't come in handy here - the project has its own copy of everything, it's not reaching back to the original React Native dir. That said, we've talked about some sort of include feature, but it would be more a way to include raw content than a deep "subproject" sort of feature, at least for now. Will update 308 with any progress.

**Comment by ide** [comment]
> the project has its own copy of everything
Yeah. It would be nice if individual projects could each import one React Native .flowconfig into each of their own .flowconfig files.

**Pull request merged**
