### PR TITLE
Enable event loop by default when bridgeless is enabled

### PR DESCRIPTION
**Pull request by rubennorte**
Changelog: [General][Changed] Enabled new event loop behavior when bridgeless (new architecture) is enabled.

Fixes https://github.com/facebook/react-native/issues/42742 and probably https://github.com/facebook/react-native/issues/33006.

Differential Revision: D54682678

### CODE REVIEW

**Comment by kraenhansen** [comment]
I tried disabling our workaround for https://github.com/facebook/react-native/issues/33006 based on the value of the `ReactNativeFeatureFlags.enableMicrotasks()` and unfortunately it doesn't seem to solve it.

I wonder if it'd be possible to extend rn-tester's [NativeCxxModuleExample](https://github.com/facebook/react-native/tree/main/packages/rn-tester/NativeCxxModuleExample) to exhibit this behaviour 🤔

**Comment by rubennorte** [comment]
> I tried disabling our workaround for #33006 based on the value of the `ReactNativeFeatureFlags.enableMicrotasks()` and unfortunately it doesn't seem to solve it.
> 
> I wonder if it'd be possible to extend rn-tester's [NativeCxxModuleExample](https://github.com/facebook/react-native/tree/main/packages/rn-tester/NativeCxxModuleExample) to exhibit this behaviour 🤔

Could you please open a new issue with the details about how to reproduce this with the new architecture enabled? (that enables the new event loop by default).

I took a quick look at the example in https://github.com/mfbx9da4/react-native-jsi-promise/blob/main/ios/JsiPromise.mm and I still see problems about how those promises are resolved (you can't call into JSI from any threads/queues, you should use the JS thread or you'd get undefined behaviors). To call into JS, you should use things like the call invoker that's passed to C++ TurboModules, which allows you to schedule async jobs in the JS thread, where you can safely resolve the promise.

**Comment by kraenhansen** [comment]
> Could you please open a new issue with the details about how to reproduce this with the new architecture enabled?

I agree, that's probably the best next step, which was why I mentioned extending rn-tester. I mainly wanted to mention that I failed to verify the fix in our code and I'll have to circle back to crafting a minimal reproduction of this later. I'll create a new issue referencing this PR and the original issue and tagging you, once I get there 👍 

> you should use the JS thread or you'd get undefined behaviors

We're asserting the thread is the JS thread in our implementation (I'm not associated with the example you posted).

**Comment by kraenhansen** [comment]
Please disregard my comments above .. As I outline in [my latest comment on #33006](https://github.com/facebook/react-native/issues/33006#issuecomment-2233063602) our way of scheduling async work was not through the `CallInvoker` and therefore didn't trigger drainage of the microtask queue.

**Pull request closed without merging**
