### PR TITLE
feat: a feature to support detect text cutoff problems

### PR DESCRIPTION
**Pull request by jcdhlzq**
## Summary:

This pr provide an option to detect the problem of Text cut off. And this may be helpful for fixing such a problem thoroughly.

## Changelog:

[ANDROID][ADDED]-Add an option that may be helpful for fixing text cutoff problems.

## Test Plan:

When the text cutoff is detected, some key information will be logged.

```
2023-09-21 22:41:47.783 11621-11685 unknown:ReactNative     com.facebook.react.uiapp             W  ReactTextShadowNode.detectTextCutoff: A text cutoff do occur with text=999
2023-09-21 22:41:47.783 11621-11685 unknown:ReactNative     com.facebook.react.uiapp             W  ReactTextShadowNode.detectTextCutoff: mLineCount=1 mBoringWidth=198 lineCount=2 boringWidth=201 mNumberOfLines=-1 mTextBreakStrategy=1 mFontFeatureSettingsnull mContainsImage=false mHyphenationFrequency=0 mIncludeFontPadding=true mAdjustsFontSizeToFit=false mTextAlign=0 mTextAttributes=TextAttributes {
                                                                                                      getAllowFontScaling(): true
                                                                                                      getFontSize(): 26.0
                                                                                                      getEffectiveFontSize(): 101
                                                                                                      getHeightOfTallestInlineViewOrImage(): NaN
                                                                                                      getLetterSpacing(): 0.0
                                                                                                      getEffectiveLetterSpacing(): 0.0
                                                                                                      getLineHeight(): NaN
                                                                                                      getEffectiveLineHeight(): NaN
                                                                                                      getTextTransform(): UNSET
                                                                                                      getMaxFontSizeMultiplier(): NaN
                                                                                                      getEffectiveMaxFontSizeMultiplier(): 0.0
                                                                                                    }
```

### CODE REVIEW

**Comment by ryancat** [comment]
Thanks for working on this -- is there a test can be added for this?

**Comment by jcdhlzq** [comment]
> Thanks for working on this -- is there a test can be added for this?

There is a demo https://snack.expo.dev/fl5DSrLBJ that can be reproduced on Xiaomi devices with miui13 and miui14 by setting text size and font weight to the maxium in system settings.

Also, if you have Xiaomi devices with miui12 on hand, giving `fontFamily` to default value `null`, a text cutoff can be reproduced.

These two cases both cause text cutoff problem, and they have same direct reason for the problem.

The direct reason is that yoga provides a width for one line text is smaller than a new value from `TextView#mBoring#width`, resulting in the text content will be layout in two lines with height not chagned. Then we can only see text that rendered on the first line.

**Comment by jcdhlzq** [comment]
> Thanks for working on this -- is there a test can be added for this?

Some test cases are added in a seperate pr: #39594

**Comment by jcdhlzq** [comment]
How about this PR？As there are so many issues about text cutoff and some of them can not be reproduced for unknown relevant causes, this PR may help to find the direct cause and root cause.

**Pull request closed without merging**
