### PR TITLE
 add x86_64 arm64-v8a support. Fixes #2814

### LINKED ISSUE #2814: Support third-party 64-bit libraries on Android
Excerpt from the Android Developers Blog article, [Get your apps ready for the 64-bit requirement](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html):
*[added by @hramos]*

### The 64-bit requirement: what it means for developers

Starting **August 1, 2019**:

* All new apps and app updates that include native code are required to provide 64-bit versions in addition to 32-bit versions when publishing to Google Play.
* Extension: Google Play will continue to accept 32-bit only updates to existing games that use Unity 5.6 or older until August 2021.

Starting **August 1, 2021**:

* Google Play will stop serving apps without 64-bit versions on 64-bit capable devices, meaning they will no longer be available in the Play Store on those devices.
* This will include games built with Unity 5.6 or older.

The requirement does not apply to:

* APKs or app bundles explicitly targeting Wear OS or Android TV, which are form factors that do not currently support 64-bit code.
* APKs or app bundles that are not distributed to devices running Android 9 Pie or later.

## Original Issue

Hey, it appears that React Native on Android doesn't provide a 64-bit version of the `libreactnativejni.so` native library, which can cause compatibility issues on 64-bit devices. I ran into this while attempting to integrate React Native with a large existing application I'm developing.

Steps to reproduce:
1. Create a new application with `react-native init`.
2. In the "android/app/build.gradle" file, add `compile 'io.realm:realm-android:0.82.2'` to the end of the `dependencies {}` block. (Note that I don't think this is an issue specifically caused by Realm, it's just an example dependency with a 64-bit native library).
3. Attempt to run on a Nexus 9. 

Stack trace:

```
E/AndroidRuntime(32171): FATAL EXCEPTION: main
E/AndroidRuntime(32171): Process: com.androidemberall, PID: 32171
E/AndroidRuntime(32171): java.lang.UnsatisfiedLinkError: could find DSO to load: libreactnativejni.so
E/AndroidRuntime(32171):    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:213)
E/AndroidRuntime(32171):    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
E/AndroidRuntime(32171):    at com.facebook.react.bridge.JSCJavaScriptExecutor.<clinit>(JSCJavaScriptExecutor.java:19)
...
```

I believe this to be caused by the shared library loading logic explained in [this answer](http://stackoverflow.com/a/27202958) on StackOverflow. Since Realm includes a 64-bit native binary, the system no longer automatically falls back to the 32-bit version of `libreactnativejni.so` provided by React.

This bug is blocking me from integrating React Native into my existing application, which I'm really excited to try!

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivaion

add arm64 support, related issue : https://github.com/facebook/react-native/issues/2814.
If we are okay with binary aar android-jsc, then the pr can be directly merged. Otherwise merge facebook/android-jsc#30 first and do a new release.

## Test Plan

RNTester all variant works. You can also test the apk from here: https://github.com/gengjiawen/react-native/releases/tag/v0.56beta.

## Related PRs

https://github.com/facebook/android-jsc/pull/30.

## Release Notes

 [ANDROID] [ENHANCEMENT] [ABI] - add x86_64 arm64-v8a support.

### CODE REVIEW

**Comment by hwangjr** [comment]
any progress about this support?

**Comment by gengjiawen** [comment]
@hramos Can you help on this ?

**Comment by hramos** [comment]
I'm not the right person to review this, sorry.

**Comment by hwangjr** [comment]
@hramos maybe you know the right person?

**Comment by hramos** [comment]
@mdvacca

**Comment by gengjiawen** [comment]
@hramos Why push commit to push pr. If we the new jsc is using internal by facebook, this https://github.com/facebook/react-native/pull/19536 is pr I more prefered.

**Comment by gengjiawen** [comment]
@mdvacca Any thought to merge this or wait for user-specific jsc support ?

**Comment by gengjiawen** [comment]
We have been stuck with #2814 too long, maybe merge this first.

**Comment by hramos** [comment]
@gengjiawen do we strictly need to wait for the ability to use your own JSC, or can this be merged before then?

**Comment by gengjiawen** [comment]
This can directly merge. I have tested arm64 on my Smartisan R2 last week.

**Comment by gengjiawen** [comment]
Also tested RNTester on x86_64 android emulator, also works.

**Comment by hramos** [comment]
What's wrong with the previous title?

Also, it looks like `test_android` is failing early.

**Comment by gengjiawen** [comment]
Using Fixes #issuenumber can automatically close the issue when got merged, so I changed the title. Maybe add this to last part of title.

For the test-android failure, looks like something wrong with memory issue, I try to rerun it.

**Comment by gengjiawen** [comment]
It now has the same failure with master https://circleci.com/gh/gengjiawen/react-native/876.

The CI failure looks like something wrong with buck. I tested RNTester using gradle on my win10, everything works.

**Comment by hramos** [comment]
"Fixes #N" can be in the body of the issue, so we can be more descriptive in the title.

**Comment by gengjiawen** [comment]
@hramos Can you check why this merge failed ?

**Comment by gengjiawen** [comment]
@hramos ping.

**Comment by luisnaranjo733** [comment]
@hramos @gengjiawen Is 64 bit support going to land on 0.57?
Or is this delayed for a future release?

**Comment by kelset** [comment]
I don't think we want to merge support to 64 bits yet because it creates issues for other things.

Moreover, usually when the import fails it means that FB needs to do some work on the PR to make it work properly, and according to what I've heard 64bits atm is causing troubles for builds.

I guess this will stay in this state for a little bit longer.

**Comment by hramos** [comment]
I looked into this again, and the sole failure is due to the removal of Navigator. https://github.com/facebook/react-native/commit/ce8125e4343f1dc01b50eb92ebeb33c3bbbe60c4 fixes this and is already on master, so rebasing past that commit should get this PR in a good state.

Once that is done, I leave it up to you folks to decide when it would be best to merge this. I have to admit 64-bit support is not something I'm tracking closely, and I am not sure what effects it might have on Facebook's usage. It looks like all of our tests are passing (Navigator failure aside), however, so if landing this causes issues, then it's on us to toughen up our testing to catch these in the future.

**Comment by gengjiawen** [comment]
@kelset Do you know the detail what problem has does 64bit exactly have ? I know some problem exists for https://github.com/react-community/jsc-android-buildscripts with the new jsc.

**Comment by kelset** [comment]
Not sure sorry, I can't recall any precise detail. But Hector has the final say on it, so maybe they have been fixed since the last time I've heard

**Comment by hramos** [comment]
I'm hesitant to import this myself. We should make sure it's compatible with the JSC used in open source, or wait until support for Bring Your Own JSC lands in master.

**Comment by gengjiawen** [comment]
> We should make sure it's compatible with the JSC used in open source

The armeabi-v7 and x86 is the original one, you can check the so file hash. So if arm64 has any problem, they can just exclude it using abi filter. I share your concern, but my concern is that if we don't adopt any arm64 arch, we won't know what problem may occur.

> or wait until support for Bring Your Own JSC lands in master

Will this happen soon ? Can you share how it is implement ?

**Comment by hramos** [comment]
I'll make a note to update https://github.com/facebook/react-native/issues/19737 with more details about what we're working on. Briefly, we'd like to open source a "JavaScript Interface" (JSI) library that aims to wrap calls to the JavaScript VM. 

We're working on using this JSI ourselves when using our own internal fork of the JSC, and whenever this is open sourced, we'll document how others can do the same to use the JavaScript VM of their choosing. We want to unlock the ability for people to use ChakraCore, V8, or whatever they prefer.

**Comment by gengjiawen** [comment]
That's looks like nodejs `n-api`, and truly amazing if come true.

But I still want this merged, for even with that, we still need a **base support for arm64 cpu**
Also after this get merged, it only affect the arm64 version, since armeabi related file stay unchanged, since I literally copy the origin so to the `android-jsc.aar`, You can download the file from https://bintray.com/react-native/android/android-jsc#files/org%2Fwebkit%2Fandroid-jsc%2Fr174650 and compare the hash , they are the same file.
```
aecc6828c2ec70060f4a8d094da26d52290a4340 *libjsc.so
```

**Comment by gengjiawen** [comment]
@hramos If your fork of jsc include support for arm64 and x86_64 too, I think I can abondon this pr. If not, please merge.

**Comment by gengjiawen** [comment]
Looks like take too long to import. @hramos

**Comment by CoreFloDev** [comment]
One quick question about this. How can we guaranty that there is no keylogger or bitcoin mining program inside the binary and it is doing only what it is suppose to do?

**Comment by hramos** [comment]
The import failed due to a binary size limit. I've whitelisted the PR and I am trying to land this again. Please do not add any commits, to ensure the land is not cancelled.

**Comment by RSNara** [comment]
@gengjiawen. When I tried to generate a new project using `react-native init`, the android version of the generated project insta-crashes after metro sends the bundle over. Here's the error that's logged by `adb logcat`:

```
09-27 08:37:10.889 16947 17028 D SoLoader: About to load: libreactnativejni.so
09-27 08:37:10.890 16947 17028 D SoLoader: libreactnativejni.so found on /data/data/com.rnapp1538062456/lib-main
09-27 08:37:10.897 16947 17028 D SoLoader: Loading lib dependencies: [libglog_init.so, libyoga.so, libprivatedata.so, libfb.so, libfolly_json.so, libjsc.so, libglog.so, libgnustl_shared.so, libandroid.so, liblog.so, libstdc++.so, libm.so, libc.so, libdl.so]
09-27 08:37:10.897 16947 17028 D SoLoader: About to load: libglog_init.so
09-27 08:37:10.898 16947 17028 D SoLoader: libglog_init.so found on /data/data/com.rnapp1538062456/lib-main
09-27 08:37:10.898 16947 17028 D SoLoader: Loading lib dependencies: [libglog.so, libgnustl_shared.so, liblog.so, libstdc++.so, libm.so, libc.so, libdl.so]
09-27 08:37:10.899 16947 17028 D SoLoader: About to load: libglog.so
09-27 08:37:10.899 16947 17028 D SoLoader: libglog.so found on /data/data/com.rnapp1538062456/lib-main
09-27 08:37:10.901 16947 17028 D SoLoader: Loading lib dependencies: [libgnustl_shared.so, libstdc++.so, libm.so, libc.so, libdl.so]
09-27 08:37:10.901 16947 17028 D SoLoader: About to load: libgnustl_shared.so
09-27 08:37:10.901 16947 17028 D SoLoader: libgnustl_shared.so found on /data/data/com.rnapp1538062456/lib-main
09-27 08:37:10.902 16947 17028 D SoLoader: Loading lib dependencies: [libm.so, libc.so, libdl.so]
09-27 08:37:10.902 16947 17028 D SoLoader: About to load: libm.so
09-27 08:37:10.903 16947 17028 D SoLoader: libm.so not found on /data/data/com.rnapp1538062456/lib-main
09-27 08:37:10.903 16947 17028 D SoLoader: libm.so not found on /data/app/com.rnapp1538062456-1/lib/x86_64
09-27 08:37:10.903 16947 17028 D SoLoader: libm.so not found on /system/vendor/lib
09-27 08:37:10.903 16947 17028 D SoLoader: libm.so found on /system/lib
09-27 08:37:10.903 16947 17028 D SoLoader: libm.so loaded implicitly
09-27 08:37:10.903 16947 17028 D SoLoader: Loaded: libm.so
09-27 08:37:10.903 16947 17028 D SoLoader: About to load: libc.so
09-27 08:37:10.903 16947 17028 D SoLoader: libc.so not found on /data/data/com.rnapp1538062456/lib-main
09-27 08:37:10.903 16947 17028 D SoLoader: libc.so not found on /data/app/com.rnapp1538062456-1/lib/x86_64
09-27 08:37:10.903 16947 17028 D SoLoader: libc.so not found on /system/vendor/lib
09-27 08:37:10.904 16947 17028 D SoLoader: libc.so found on /system/lib
09-27 08:37:10.904 16947 17028 D SoLoader: libc.so loaded implicitly
09-27 08:37:10.904 16947 17028 D SoLoader: Loaded: libc.so
09-27 08:37:10.904 16947 17028 D SoLoader: About to load: libdl.so
09-27 08:37:10.904 16947 17028 D SoLoader: libdl.so not found on /data/data/com.rnapp1538062456/lib-main
09-27 08:37:10.904 16947 17028 D SoLoader: libdl.so not found on /data/app/com.rnapp1538062456-1/lib/x86_64
09-27 08:37:10.904 16947 17028 D SoLoader: libdl.so not found on /system/vendor/lib
09-27 08:37:10.904 16947 17028 D SoLoader: libdl.so found on /system/lib
09-27 08:37:10.904 16947 17028 D SoLoader: libdl.so loaded implicitly
09-27 08:37:10.904 16947 17028 D SoLoader: Loaded: libdl.so
09-27 08:37:10.910 16947 17028 E SoLoader: Error when loading lib: dlopen failed: "/data/data/com.rnapp1538062456/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit lib hash: 38099cfdfc816f823cb69c5387381ddd search path is /data/app/com.rnapp1538062456-1/lib/x86_64
09-27 08:37:10.910 16947 17028 E SoLoader: couldn't find DSO to load: libgnustl_shared.so caused by: dlopen failed: "/data/data/com.rnapp1538062456/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
09-27 08:37:10.910 16947 17028 E SoLoader: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libgnustl_shared.so caused by: dlopen failed: "/data/data/com.rnapp1538062456/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
09-27 08:37:10.910 16947 17028 E SoLoader: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libgnustl_shared.so caused by: dlopen failed: "/data/data/com.rnapp1538062456/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
09-27 08:37:10.910 16947 17028 E SoLoader: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libgnustl_shared.so caused by: dlopen failed: "/data/data/com.rnapp1538062456/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
09-27 08:37:10.910 16947 17028 E AndroidRuntime: FATAL EXCEPTION: Thread-2
09-27 08:37:10.910 16947 17028 E AndroidRuntime: Process: com.rnapp1538062456, PID: 16947
09-27 08:37:10.910 16947 17028 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libgnustl_shared.so caused by: dlopen failed: "/data/data/com.rnapp1538062456/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:703)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:564)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:500)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:914)
09-27 08:37:10.910 16947 17028 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
09-27 08:37:10.922  1617  2151 W ActivityManager:   Force finishing activity com.rnapp1538062456/.MainActivity
09-27 08:37:10.954  1313  2102 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2691072
```

Pretty sure this commit is the problem since its parent works fine, but this commit doesn't. Are you familiar with what could have caused this problem, @gengjiawen?

**Comment by gengjiawen** [comment]
what device are you running ? Is it a x86_64 emulator ?

**Comment by kelset** [comment]
@RSNara did you pass some custom parameters to `react-native init`? Because I don't think this commit is available in any release yet (current latest 0.57.1) 🤔

**Comment by RSNara** [comment]
@kelset I used `node react-native-cli/index.js init <app-name>` to generate the project.

@gengjiawen It's a x86_64 emulator.

**Comment by gengjiawen** [comment]
I doesn't put x86_64 abi in template, only in RNTester. Normally from my experience a x86 emulator is sufficient.

**Comment by RSNara** [comment]
@gengjiawen, I'm not sure I follow your comment. What concrete steps can we take to fix this?

**Comment by gengjiawen** [comment]
If you want to run this on x86_64 emulator, add x86_64 to this line https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/android/app/build.gradle#L112.

**Comment by RSNara** [comment]
@gengjiawen, I just added `x86_64` to that line and rebuilt a starter project, and still no luck. Should making that change be sufficient to get the android starter working?

**Comment by gengjiawen** [comment]
@RSNara Can you try RNTester on that emulator ?

**Comment by RSNara** [comment]
@gengjiawen RNTester works fine.

**Comment by gengjiawen** [comment]
Can you check the so in the generated apk using android studio ?

**Pull request closed without merging**
