### PR TITLE
add image size to onLoad nativeEvent for android

### PR DESCRIPTION
**Pull request by playmusic9**
like this use it
```js
        <Image
          onLoad={(event)=>{
            this.setState({
              width:event.nativeEvent.width,
              height:event.nativeEvent.height,
            })
          }}
          style={{width:this.state.width,height:this.state.height}}
          resizeMode="contain"
          source={{uri:'https://avatars3.githubusercontent.com/u/8945429?v=3&s=96'}}/>
```

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @foghina to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@playmusic9 updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@playmusic9 updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@playmusic9 updated the pull request.

**Comment by satya164** [comment]
There seem to be lots of unrelated changes

**Pull request closed without merging**
