### PR TITLE
Unify platform behavior of processTransform

### PR DESCRIPTION
**Pull request by acoates-ms**
Currently both iOS and Android send over the list of transforms as an array.   But there is an if statement that causes other platforms to get a matrix.  This prevents other platforms from being able to use the fabric ViewProps class and the conversion functions as they exist in core, as those expect the transforms to be an array.

## Summary

Stop special casing iOS and android. - Which will allow for example Windows to be able to share more fabric code.

## Changelog

[Internal] [Changed] - All platforms should get transform sent to native as an array of transform operations instead of a matrix

## Test Plan

Similar change made in react-native-windows.
https://github.com/microsoft/react-native-windows/issues/9797

### CODE REVIEW

**Comment by TheSavior** [comment]
Does React Native Web need this code?

**Comment by acoates-ms** [comment]
Ah, Is that the other platform?  Was trying to work out why this if existed at all.  -- Shouldn't that be something that react-native-web can change?  This will likely be a change for many out of tree platforms.  But I'd rather have the default match ios/android, and platforms can fork this code back if they want to maintain the old behavior or update their projection to native to handle the new format.  As it stands, we have to fork the code to align with core, which seems like the wrong way around.

**Comment by ecreeth** [comment]
> Does React Native Web need this code?

I couldn't find anything related in the react native web repository. They have their own implementation of the StyleSheet API. Much more now in the new version that is about to be deployed in https://github.com/necolas/react-native-web/pull/2248

**Comment by ecreeth** [comment]
cc @cortinico

**Comment by cortinico** [comment]
Can we get a rebase + have the CI green before we import/merge this @acoates-ms ?

**Comment by acoates-ms** [comment]
@cortinico - Done.

**Comment by ecreeth** [comment]
It would be great if you could also remove the [MatrixMath.js](https://github.com/facebook/react-native/blob/main/Libraries/Utilities/MatrixMath.js) helper, it was only used by the processTransform.js

**Comment by NickGerleman** [comment]
[React VR](https://developers.facebook.com/videos/f8-2017/react-vr-build-amazing-vr-experiences-using-react/), which reports `Platform.OS` of 'vr', still assumes the transform is sent as a float array representing a matrix.

**Pull request closed without merging**
