### PR TITLE
Parse more fields from local notification created in JS

### PR DESCRIPTION
**Pull request by bogdantmm92**
Parse more fields for a local notification presented from js.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
@tadeuzagallo would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by Kureev** [comment]
I believe this one can be merged in, right?

**Comment by mkonicek** [comment]
@bogdantmm92 It looks like this needs to be rebased. Can you rebase please?

@tadeuzagallo Does this look good to you?

**Comment by facebook-github-bot-8** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @slycoder as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by mkonicek** [comment]
@bogdantmm92 Do you plan to rebase this on top of master and add a test plan (see https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md) or should we close the PR? Thanks for the contribution and sorry we didn't review it in time :(

**Comment by javache** [comment]
Most of these are already supported now https://github.com/facebook/react-native/blob/57d45235ecb5fc54c0b80d1147a38e712dd9c431/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L38-L49. Feel free to submit a new PR if you need other attributes.

**Pull request closed without merging**
