### PR TITLE
fix permission requests on pre-M android

### PR DESCRIPTION
**Pull request by vonovak**
On pre-M devices, `PermissionsAndroid.request` currently returns a boolean, whereas on newer, it returns GRANTED, DENIED or other constants defined in `PermissionsModule.java`

given the example form the [docs](https://facebook.github.io/react-native/docs/permissionsandroid.html) which I guess many people use, this will lead to code that does not work before M (it will tell you that permissions are not given even if they are in the manifest). 

I believe the author of [this](https://github.com/facebook/react-native/commit/51efaab1209a41254c90dcba596d49e3cbc2d925) forgot to change the resolved value in this one place but changed it in other places, eg [here](https://github.com/facebook/react-native/commit/51efaab1209a41254c90dcba596d49e3cbc2d925#diff-2a74096453bc8faa5d4a1599ad0ab33fL99).

The docs are written correctly:

> On devices before SDK version 23, the permissions are automatically granted if they appear in the manifest, so check and request should always be true.

but the code is not right because we'd need to check for `if (granted === PermissionsAndroid.RESULTS.GRANTED || granted === true) {`

Also, the behavior is done correctly in [requestMultiplePermissions](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/ReactAndroid/src/main/java/com/facebook/react/modules/permissions/PermissionsModule.java#L148) so returning a boolean is an inconsistency.

## Test Plan

I tested this locally. The code is the same as on line [148](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/ReactAndroid/src/main/java/com/facebook/react/modules/permissions/PermissionsModule.java#L148) where it is done correctly.

## Release Notes

[ANDROID] [BUGFIX] [PermissionAndroid] - return GRANTED / DENIED instead of true / false on pre-M android

### CODE REVIEW

**Comment by hramos** [comment]
Thanks! Do you want to take a look at https://github.com/facebook/react-native-website/blob/master/docs/permissionsandroid.md and see if there's improvements to be made to that guide?

**Comment by vonovak** [comment]
@hramos sure, I'll take a look

**Comment by jgcmarins** [comment]
Hi @hramos and @vonovak 
I think we have a similar problem on Android > 6.0: https://github.com/facebook/react-native/issues/17985

**Comment by vonovak** [comment]
I don't think the two issues are related, this one is not about not resolving the promise, but about resolving it with an incorrect value.

**Pull request closed without merging**
