### PR TITLE
fix: remove deprecated event listener method from appearance.js

### PR DESCRIPTION
**Pull request by matinzd**
## Summary
Remove unused deprecated event listener method from appearance.js

## Changelog

[General] [Removed] - Remove deprecated removeListener from Appearance that causes deprecation message in log box.

### CODE REVIEW

**Comment by yungsters** [comment]
Thanks for the contribution, @matinzd. I have added this to my list and will take a look as soon as possible.

**Comment by matinzd** [comment]
> Thanks for the contribution, @matinzd. I have added this to my list and will take a look as soon as possible.

Thank you! Let me know.

**Comment by yungsters** [comment]
Thanks again for the contribution, @matinzd.

Can you run `prettier` on this change? It is failing the `test_js` CI jobs as-is.

Also, would you be interested in removing the other deprecated remove listener methods? 😁

**Comment by matinzd** [comment]
> Thanks again for the contribution, @matinzd.
> 
> Can you run `prettier` on this change? It is failing the `test_js` CI jobs as-is.
> 
> Also, would you be interested in removing the other deprecated remove listener methods? 😁

Fixed.
Of course! I will do them in another PR.

**Comment by matinzd** [comment]
> Thanks again for the contribution, @matinzd.
> 
> Can you run `prettier` on this change? It is failing the `test_js` CI jobs as-is.
> 
> Also, would you be interested in removing the other deprecated remove listener methods? 😁

Of course, I will do it in another PR. Branch rebased with main and CI should pass.

**Comment by yungsters** [comment]
One more small thing — the changelog entry should be [Removed] for removing the deprecated method.

**Comment by matinzd** [comment]
> One more small thing — the changelog entry should be [Removed] for removing the deprecated method.

Changed. Is it ok?

**Comment by yungsters** [comment]
This is what I meant:

```diff
- [Internal] [Removed] - Remove deprecated removeListener from Appearance that causes deprecation message in log box.
+ [Removed] - Remove deprecated removeListener from Appearance that causes deprecation message in log box.
```

If you don't mind, I can make that change in the process of importing this diff.

**Comment by yungsters** [comment]
Sorry, I just realized why you were confused.

I made a typo in my comment. I meant to suggest removing "[Internal]", not "[Removed]".

Sorry for the confusion!

**Comment by matinzd** [comment]
> Sorry, I just realized why you were confused.
> 
> I made a typo in my comment. I meant to suggest removing "[Internal]", not "[Removed]".
> 
> Sorry for the confusion!

Oops :) No problem! It should be ok now.

**Comment by matinzd** [comment]
> Sorry, I just realized why you were confused.
> 
> I made a typo in my comment. I meant to suggest removing "[Internal]", not "[Removed]".
> 
> Sorry for the confusion!

The category should be there. I changed it to General. @yungsters

**Comment by matinzd** [comment]
> This is what I meant:
> 
> ```diff
> - [Internal] [Removed] - Remove deprecated removeListener from Appearance that causes deprecation message in log box.
> + [Removed] - Remove deprecated removeListener from Appearance that causes deprecation message in log box.
> ```
> 
> If you don't mind, I can make that change in the process of importing this diff.

The category should be there. I changed it to General. @yungsters

**Pull request closed without merging**
