### PR TITLE
[iOS] Remove RCTGetMultiplierForContentSizeCategory

### PR DESCRIPTION
**Pull request by Saadnajmi**
## Summary:

It seems this method is not referenced by anything anymore. I think https://github.com/facebook/react-native/pull/35017 made it redundant. Let's remove it?
I can also do the whole "Deprecate for one version, remove in the next" since this was publicly exported.

## Changelog:
[iOS] [REMOVED] - Remove RCTGetMultiplierForContentSizeCategory

## Test Plan:

CI should pass

### CODE REVIEW

**Comment by ryancat** [comment]
Yeah the concern would be public API being visible to unknown apps. What's the proper deprecation steps look like and how we enforce it? @cipolleschi

**Comment by cipolleschi** [comment]
Yeah, it seems like we are not even using this internally.
So... lets do the right thing:
- Let's add a `deprecated` annotation first.
- Let's release a version with the deprecation
- Let's remove the code in the next release

**Comment by Saadnajmi** [comment]
> Yeah, it seems like we are not even using this internally.
> 
> So... lets do the right thing:
> 
> - Let's add a `deprecated` annotation first.
> 
> - Let's release a version with the deprecation
> 
> - Let's remove the code in the next release 

To be clear, deprecate in 0.73 and remove in 0.74?

**Comment by Saadnajmi** [comment]
Deprecation done here: https://github.com/facebook/react-native/pull/39643, I'll revisit this PR post 0.73.

**Comment by Saadnajmi** [comment]
> Yeah, it seems like we are not even using this internally.
> 
> So... lets do the right thing:
> 
> - Let's add a `deprecated` annotation first.
> 
> - Let's release a version with the deprecation
> 
> - Let's remove the code in the next release 

Now that https://github.com/facebook/react-native/pull/39785 merged, can we revisit this?

**Comment by cipolleschi** [comment]
yeah... branch has been cut and the other commit is in the cherry pick list.
Could you rebase and fix the conflict, please?

**Pull request closed without merging**
