### PR TITLE
use AppCompat widgets

### PR DESCRIPTION
**Pull request by dulmandakh**
Android documentation recommends to use widgets from AppCompat, also Android Studio warns about it. This PR changes Picker, Slider, Text, TextInput components to use AppCompat widgets.

CI is GREEN https://circleci.com/gh/dulmandakh/react-native/453

## Test Plan

Android builds and runs as usual, almost no visual changes

## Release Notes
[ANDROID] [ENHANCEMENT] [WIDGET] - extend widgets from AppCompat

### CODE REVIEW

**Comment by dulmandakh** [comment]
These are widgets used when widgets (without appcompat) defined in XML layouts. Also this will enhance material design support, example https://github.com/facebook/react-native/commit/1723b6cd9c1eb834de137c8800b12ef6eadeb82a.

For Slider, we'll be able to add support for image thumb. Feature parity with iOS.

@hramos

**Comment by dulmandakh** [comment]
@hramos Please merge, I'm preparing a pull request that will add thumb image to Slider component (feature parity with iOS)

**Comment by dulmandakh** [comment]
@mdvacca Please merge

**Comment by dulmandakh** [comment]
@hramos any news? Please cherry pick it to stable

**Comment by hramos** [comment]
@dulmandakh it's still waiting on a review from @mdvacca.

**Comment by mdvacca** [comment]
The code looks good to me, @dulmandakh can you describe what are the visual changes that you mentioned in the description?

**Comment by mdvacca** [comment]
+ @ayc1

**Comment by dulmandakh** [comment]
@mdvacca I see no visual difference, but AppCompatSeekBar, AppCompatSpinner, AppCompatEditText, AppCompatTextView are introduced in support library 25.1.0 and used by default in layouts for compatibility.

excerpt from AppCompatSeekBar doc
> This will automatically be used when you use SeekBar in your layouts and the top-level activity / dialog is provided by appcompat. You should only need to manually use this class when writing custom views.

excerpt from AppCompatSpinner doc
> * Allows dynamic tint of its background via the background tint methods in CompoundButtonCompat.
> * Allows setting of the background tint using buttonTint and buttonTintMode.
> * Setting the popup theme using popupTheme.

> This will automatically be used when you use Spinner in your layouts. You should only need to manually use this class when writing custom views.

excerpt from AppCompatEditText doc
> * Allows dynamic tint of its background via the background tint methods in ViewCompat.
> * Allows setting of the background tint using backgroundTint and backgroundTintMode.

>This will automatically be used when you use EditText in your layouts and the top-level activity / dialog is provided by appcompat. You should only need to manually use this class when writing custom views.

excerpt from AppCompatTextView doc
> * Allows dynamic tint of its background via the background tint methods in ViewCompat.
> * Allows setting of the background tint using backgroundTint and backgroundTintMode.
> * Supports auto-sizing via TextViewCompat by allowing to instruct a TextView to let the size of the text expand or contract automatically to fill its layout based on the TextView's characteristics and boundaries. The style attributes associated with auto-sizing are autoSizeTextType, autoSizeMinTextSize, autoSizeMaxTextSize, autoSizeStepGranularity and autoSizePresetSizes, all of which work back to Ice Cream Sandwich.

> This will automatically be used when you use TextView in your layouts and the top-level activity / dialog is provided by appcompat. You should only need to manually use this class when writing custom views.

**Comment by dulmandakh** [comment]
@mdvacca please approve 😄

**Comment by dulmandakh** [comment]
@mdvacca please merge, it'll render widgets according to Google recommendations and allow us to support backgroundTint.

**Comment by dulmandakh** [comment]
@hramos is there any issue while importing this PR?

**Comment by hramos** [comment]
Here's an example of a failure that just surfaced when this PR was imported:

```
Summary: 
 ** Summary of failures encountered during the build **
Rule //redacted// FAILED because Command failed with exit code 1.
stderr: react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextView.java:24: error: cannot access android.support.v4.view.TintableBackgroundView
public class ReactTextView extends AppCompatTextView implements ReactCompoundView {
       ^
  class file for android.support.v4.view.TintableBackgroundView not found
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:43: error: First argument must be a subclass of View
  public void setNumberOfLines(ReactTextView view, int numberOfLines) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:48: error: First argument must be a subclass of View
  public void setEllipsizeMode(ReactTextView view, @Nullable String ellipsizeMode) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:63: error: First argument must be a subclass of View
  public void setTextAlignVertical(ReactTextView view, @Nullable String textAlignVertical) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:79: error: First argument must be a subclass of View
  public void setSelectable(ReactTextView view, boolean isSelectable) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:84: error: First argument must be a subclass of View
  public void setSelectionColor(ReactTextView view, @Nullable Integer color) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:103: error: First argument must be a subclass of View
  public void setBorderRadius(ReactTextView view, int index, float borderRadius) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:116: error: First argument must be a subclass of View
  public void setBorderStyle(ReactTextView view, @Nullable String borderStyle) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:130: error: First argument must be a subclass of View
  public void setBorderWidth(ReactTextView view, int index, float width) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:147: error: First argument must be a subclass of View
  public void setBorderColor(ReactTextView view, int index, Integer color) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:155: error: First argument must be a subclass of View
  public void setIncludeFontPadding(ReactTextView view, boolean includepad) {
              ^
react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextAnchorViewManager.java:160: error: First argument must be a subclass of View
  public void setDisabled(ReactTextView view, boolean disabled) {
              ^
```

**Comment by dulmandakh** [comment]
you need to add support-v4 as dependency
```
react_native_dep("third-party/android/support/v4:lib-support-v4")
```
and maybe support-annotations
```
react_native_dep("third-party/android/support-annotations:android-support-annotations")
```

**Comment by hramos** [comment]
Can you make the change on your PR? I'll re-import afterwards.

**Comment by dulmandakh** [comment]
@hramos Android CI is green 👍

**Comment by dulmandakh** [comment]
@hramos please try again 👍

**Comment by hramos** [comment]
Should we continue working on this?

**Comment by dulmandakh** [comment]
David and I working on landing AndroidX, and I hope that we can land this
after that.

>

**Pull request closed without merging**
