### PR TITLE
Update releasing guide

### PR DESCRIPTION
**Pull request by grabbou**
This is WIP as I am going through release steps. Submitting few ideas.

List:
- NDK is actually needed in the first step for the e2e scripts to run.

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks @grabbou!

@facebook-github-bot shipit

**Comment by grabbou** [comment]
Not sure if fb bot will handle re-opened case, but just leaving it here as I added few other changes to be reviewed :)

**Comment by bestander** [comment]
Better create a new pr

**Comment by mkonicek** [comment]
@grabbou The PR has been merged, can you create a new PR with the remaining changes please?

**Comment by grabbou** [comment]
Yep :)

**Pull request closed without merging**
