### PR TITLE
[Codegen 104] Add `getResolvedTypeAnnotation` to Parsers

### PR DESCRIPTION
**Pull request by siddarthkay**
## Summary:

[Codegen 104] This PR introduces `getResolvedTypeAnnotation` to the Parser class and implements this function in Typescript and Flow Parsers. 

We also get rid of usages `resolveTypeAnnotation` from : 
- `packages/react-native-codegen/src/parsers/typescript/utils.js`
-  `packages/react-native-codegen/src/parsers/flow/utils.js`

and replace it with `parsers.getResolvedTypeAnnotation` as requested on https://github.com/facebook/react-native/issues/34872

## Changelog:

[Internal] [Changed] - Add `getResolvedTypeAnnotation ` to Parsers and update usages.

## Test Plan:

Run yarn jest react-native-codegen and ensure CI is green

### CODE REVIEW

**Comment by siddarthkay** [comment]
Tests fail with : 

```log
TypeError: translateTypeAnnotation is not a function
Occurred while linting /home/circleci/react-native/packages/react-native/Libraries/ActionSheetIOS/NativeActionSheetManager.js:11
Rule: "@react-native/specs/react-native-modules"
    at translateFunctionTypeAnnotation (/home/circleci/react-native/packages/
    react-native-codegen/src/parsers/parsers-commons.js:281:7)
    at buildPropertySchema (/home/circleci/react-native/packages/react-native-codegen/
    src/parsers/parsers-commons.js:356:7)
    at /home/circleci/react-native/packages/react-native-codegen/src/parsers/
    parsers-commons.js:629:24
    at guard (/home/circleci/react-native/packages/react-native-codegen/src/parsers/
    utils.js:48:14)
    at /home/circleci/react-native/packages/react-native-codegen/src/parsers/
    parsers-commons.js:626:14
    at Array.map (<anonymous>)
    at buildModuleSchema (/home/circleci/react-native/packages/react-native-codegen/src/
    parsers/parsers-commons.js:618:6)
    at /home/circleci/react-native/packages/eslint-plugin-specs/
    react-native-modules.js:162:9
    at guard (/home/circleci/react-native/packages/react-native-codegen/src/
    parsers/utils.js:48:14)
    at Program:exit (/home/circleci/react-native/packages/eslint-plugin-specs/
    react-native-modules.js:161:7)
    at ruleErrorHandler (/home/circleci/react-native/node_modules/eslint/lib/linter/
    linter.js:1049:28)
    at /home/circleci/react-native/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/circleci/react-native/node_modules/eslint/lib/linter/
    safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/circleci/react-native/node_modules/
    eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/circleci/react-native/node_modules/
    eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (/home/circleci/react-native/node_modules/eslint/
    lib/linter/node-event-generator.js:349:14)
    at CodePathAnalyzer.leaveNode (/home/circleci/react-native/node_modules/eslint/lib/
    linter/code-path-analysis/code-path-analyzer.js:816:23)
    at /home/circleci/react-native/node_modules/eslint/lib/linter/linter.js:1086:32
    at Array.forEach (<anonymous>)
    at runRules (/home/circleci/react-native/node_modules/eslint/lib/linter/linter.js:1079:15)
    at Linter._verifyWithoutProcessors (/home/circleci/react-native/node_modules/eslint/
    lib/linter/linter.js:1328:31)
    at Linter._verifyWithoutProcessors (/home/circleci/react-native/node_modules/
    eslint-plugin-eslint-comments/lib/utils/patch.js:181:42)
    at Linter._verifyWithConfigArray (/home/circleci/react-native/node_modules/eslint/lib/
    linter/linter.js:1703:21)
    at Linter.verify (/home/circleci/react-native/node_modules/eslint/lib/linter/linter.js:1410:65)
    at Linter.verifyAndFix (/home/circleci/react-native/node_modules/eslint/lib/linter/linter.js:1962:29)
    at verifyText (/home/circleci/react-native/node_modules/eslint/lib/cli-engine/cli-engine.js:245:48)
    at CLIEngine.executeOnFiles (/home/circleci/react-native/node_modules/eslint/lib/
    cli-engine/cli-engine.js:823:28)
    at ESLint.lintFiles (/home/circleci/react-native/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/home/circleci/react-native/node_modules/eslint/lib/cli.js:417:36)
    at main (/home/circleci/react-native/node_modules/eslint/bin/eslint.js:135:24)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Failed to run eslint.
Finished.
/home/circleci/react-native/scripts/run-ci-javascript-tests.js:40
    throw Error(exitCode);
    ^

Error: 1
    at Object.<anonymous> (/home/circleci/react-native/scripts/run-ci-javascript-tests.js:40:11)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

When i look at usage of `translateTypeAnnotation` it does seem to be heavily used in `packages/react-native-codegen/src/parsers/parsers-commons.js`. 
However, `translateTypeAnnotation` is never imported but passed through each all the functions inside `parsers-commons.js`

Seems similar to the cyclic dependency described over here : https://github.com/facebook/react-native/pull/37043#issuecomment-1518646089

**Comment by siddarthkay** [comment]
`translateTypeAnnotation` is used in the following functions :  

1. `parseObjectProperty`
     Here `translateTypeAnnotation` is passed onto `unwrapNullable`.
    
2. `translateFunctionTypeAnnotation`
      Here `translateTypeAnnotation` is called.
   
3. `buildPropertySchema`
      This function calls `translateFunctionTypeAnnotation` and passes `translateTypeAnnotation` as a 
      parameter.
     
4. `buildSchemaFromConfigType`
     This function calls `buildModuleSchema` and passes `translateTypeAnnotation` as a 
      parameter.

5.  `buildSchema`
      This function calls `buildModuleSchema` and passes `translateTypeAnnotation` as a 
      parameter.
     
6.  `buildModuleSchema`
     This function calls `buildPropertySchema` and passes `translateTypeAnnotation` as a 
      parameter.
      
So the chain of call seems like this :
`buildSchema` ->  `buildModuleSchema` -> `buildPropertySchema` -> `translateFunctionTypeAnnotation`

**Comment by siddarthkay** [comment]
`buildSchema ` is exported from `parser-commons.js` and imported in : 

1. `flow/parser.js`
     Here `flowTranslateTypeAnnotation` is imported from `parsers/flow/modules/index.js` which then contains 
     the actual definition of `translateTypeAnnotation` which is exported under the name of 
   `flowTranslateTypeAnnotation`

2. `typescript/parser.js`
     Here `typeScriptTranslateTypeAnnotation` is imported from `parsers/typescript/modules/index.js` which 
     then contains the actual definition of `translateTypeAnnotation` which is exported under the name of 
   `typeScriptTranslateTypeAnnotation`
   
@cipolleschi : just sharing my debugging notes here for now, do share your perspective as well when you get a chance, I'd appreciate your insights on this one as well 🙏🏻

**Comment by cipolleschi** [comment]
uhm... your notes make sense... 🤔 
I may have created a task that is too complex for now. Feel free to pause/drop it. I don't have an immediate solution right now, I have to invest some time and play with the codebase to understand what we can do. 🤔

**Comment by siddarthkay** [comment]
I figured out the issue I also had to make changes in `packages/eslint-plugin-specs/react-native-modules.js` and now tests should pass 🤞🏻

**Comment by cipolleschi** [comment]
That's cool! Thank you so much for doing this!

**Comment by tarunrajput** [comment]
Hi @cipolleschi,  I think that pull requests for 105, 106, and 107 were merged after 104. As a result, we now have some duplicate code, resolveTypeAnnotation function for example.

**Comment by cipolleschi** [comment]
uhm... I see. I created the stack using the ordinal numbers, so the 104 was at the bottom of the stack, and then I applied all the other changes. :(

Probably this was the results of a badly handled git commit resolution.

This should fix the problem: https://github.com/facebook/react-native/pull/37477

Is there any other duplicated code?

**Comment by tarunrajput** [comment]
> Is there any other duplicated code?

@cipolleschi , These two functions still looks almost same. I think we should remove one of the functions and update all instances where they are used.

https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/parser.js#LL376C6-L443C1
https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/utils.js#LL18C5-L87C1

**Comment by tarunrajput** [comment]
> Is there any other duplicated code?
No, https://github.com/facebook/react-native/pull/37477 should remove all duplicated code

**Pull request closed without merging**
