### PR TITLE
Remove rnpm references in favour of react-native

### PR DESCRIPTION
**Pull request by designorant**
No need for the references now that rnpm is baked into core.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by designorant** [comment]
Just for the records, I've accepted the CLA [online](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) shortly before submitting this PR.

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by grabbou** [comment]
Great, thanks for updating the docs!

@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3914945).

**Pull request closed without merging**
