### PR TITLE
Upgraded Gradle wrapper to 6.5.1

### PR DESCRIPTION
**Pull request by SaeedZhiany**
## Summary
Welcome to Gradle 6.5.1!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5.1/release-notes.html

## Changelog

[Android] [Changed] - Update Gradle Wrapper to 6.5.1

## Test Plan

Build project and it should be built successfully.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Superseded by #29043

Also please note that Gradle 6.4+ unfortunately introduced a whitespace error in the `gradlew` script (see https://github.com/gradle/gradle/pull/13293 for details) on line 133: https://github.com/facebook/react-native/pull/29043/files#diff-36ffbd2ea7085cf19547193a7faf30c8R133. It's already fixed on Gradle's master branch, and hopefully we can update the Gradle Wrapper again for react-native before the next release, to avoid whitespace errors in the generated files.

**Comment by SaeedZhiany** [comment]
Thanks @friederbluemle.

I'll rebase my PR and upgrade to version 6.5.1. it's even newer than the PR you already mentioned.

**Comment by SaeedZhiany** [comment]
The failed build seems not related to my change. some internal error causes the problem.

**Comment by SaeedZhiany** [comment]
I close this PR due to a newer version is already merged in the master branch.

**Pull request closed without merging**
