### PR TITLE
[PushNotifications] Register for Remote Notifications and Extend AppDelegate

### PR DESCRIPTION
**Pull request by lazaronixon**
Added optional callback to requestPermissions Method.
If registration is successful, APNs returns a device token.
If there is a problem in obtaining the token, a error message is returned.
````javascript
    PushNotificationIOS.requestPermissions(function(error, token) {
      if (error) {
        console.log(error);
      } else {
        console.log(token);
      }
    });
````

Extend AppDelegate so you don’t need to call methods on AppDelegate.h

### CODE REVIEW

**Comment by brentvatne** [comment]
@lazaronixon  - I definitely like the improvement in the API here, are there any drawbacks to this approach? ObjC isn't my strongest language - is this automatically imported into `AppDelegate` in every app or will it be opt-in via manual import of the `+notification` category header?

cc @nicklockwood @tadeuzagallo

**Comment by whatupdave** [comment]
BTW I'm using this fork in my app, works great.

**Comment by tadeuzagallo** [comment]
This is pretty fragile... What if the person renames the file? or the folder? or move the library? This would also break any example app...

When I wrote it I tried swizzling as well, but it doesn't work because we don't know the AppDelegate's class at load time, we thought about some other options, but none of them seemed to be good.

Something that I'm not sure (cc @nicklockwood in case you don't know as well) is whether `didRegisterForRemoteNotificationsWithDeviceToken:` gets called every time you call `registerForRemoteNotifications`, and if it behaves in the exact same way in iOS7 & 8. In case it does, you'll still have to cleanup the callbacks on the JavaScript side.

**Comment by lazaronixon** [comment]
You're right @tadeuzagallo it is a price to pay, but too high to me, a solution i found was ```#if __has_include```, if file is not found it will work as today and you will need to call methods on the library in ObjC your self. Other solution could be AppDelegate.h come with methods calls to NotificationIOS and it be added by default as other libraries. I am feel really bad about need to write ObjC using react-native =/

**Comment by nicklockwood** [comment]
With a bit of runtime logic we could just detect if the RCTPushNotificationManager exists, and include the necessary code to call it in the AppDelegate of the standard project template. Maybe that's the best option.

**Comment by lazaronixon** [comment]
If I move AppDelegate+notification to SampleApp Folder and with ```#if __has_include("RCTPushNotificationManager.h")``` implement call methods to RCTPushNotificationManager? I would add NotificationIOS to SampleAPP as other libraries too.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tadeuzagallo** [comment]
@nicklockwood should we add this code to the SampleApp's AppDelegate, or should I close it for now?

**Comment by DannyvanderJagt** [comment]
@tadeuzagallo @nicklockwood  This PR consists of 3 discussions which are continued here:

**Extend the appdelegate**
There is another PR about this: https://github.com/facebook/react-native/pull/1979
This PR does exactly what nick suggested but there is also some discussing whether is should be added.
>With a bit of runtime logic we could just detect if the RCTPushNotificationManager exists, and include the necessary code to call it in the AppDelegate of the standard project template. Maybe that's the best option.

**Device token**
This is already available. When you use the `register` event the `devicetoken` will be passed as an argument.
```js
PushNotificationIOS.addEventListener('register', function(token){
   console.log('You are registered and the device token is: ',token)
});
```

**Error handling**
At the moment `PushNotificationIOS` doesn't have any error handling. The way this PR is implementing the error handling is by callback. I personally would prefer an error event instead of a callback.The event is cleaner and in line with the current api.
I have created a PR for this: https://github.com/facebook/react-native/pull/2336, it is also discussed here: https://github.com/facebook/react-native/issues/1613 and here  https://github.com/facebook/react-native/pull/1979


I think that this PR can be closed.

**Comment by satya164** [comment]
@lazaronixon Any updates on this?

**Comment by satya164** [comment]
Closing since no activity on the PR. let's re-open if you wanna work on it again.

**Pull request closed without merging**
