### PR TITLE
[Docs] update JS environment documentation for Babel

### LINKED ISSUE #274: Document that we're using Babel
https://github.com/facebook/jstransform/tree/master/visitors

### PR DESCRIPTION
**Pull request by jsierles**
This PR needs review for accuracy of the links, and to add links for those which aren't linked. I couldn't find references to them in the babel documentation.

Fixes #274

### CODE REVIEW

**Comment by vjeux** [comment]
Awesome, thanks!

You can find the correct list here: https://github.com/facebook/react-native/blob/41859e594d0dbd0be43cf7cc1561051ac4b1b853/packager/transformer.js#L21-L35

**Comment by jsierles** [comment]
@vjeux Yes, that list is what's now referenced in the docs. Does that mean we should take out ES5 reserved words?

**Comment by vjeux** [comment]
all the environments that we run on are ES5 so you can actually use reserved words. I would keep it there since people may not know about it

**Comment by amasad** [comment]
Can you please mention `.babelrc` to customize the transformers? see #1451

**Pull request merged**
