### PR TITLE
[Showcase] Add li.st (Android) to the showcase

### PR DESCRIPTION
**Pull request by ide**

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/213392322379153/int_phab) to review.

**Comment by mkonicek** [comment]
Congrats on shipping guys! 🎉

**Pull request closed without merging**
