### PR TITLE
Add React.js 2016 Conf videos

### PR DESCRIPTION
**Pull request by ppiekarczyk**
Here are all the conference videos for 2016.

Thanks!

### CODE REVIEW

**Comment by vjeux** [comment]
Not all those videos are related to React Native? Can you pick a few that are React Native related and put it here?

For the rest, we should put them on the conf website directly: http://conf.reactjs.com/schedule.html

See how it was done for 2015: http://conf2015.reactjs.org/schedule.html

**Comment by ppiekarczyk** [comment]
Gah, good call. Sorry, was _in the zone_

**Comment by vjeux** [comment]
Let me know when it's ready to merge

**Comment by ppiekarczyk** [comment]
@vjeux ready to :shipit:

**Comment by mkonicek** [comment]
Thanks! Just checked and all are RN-related (Andy's talk about gestures is not strictly related to RN but really good and relevant).

@facebook-github-bot shipit

**Pull request closed without merging**
