### PR TITLE
[Bugfix] Add controller to closest parent on time so as to fix the automaticallyAdjustContentInsets feature.

### PR DESCRIPTION
**Pull request by rocman**
Here's the bug to fix:
https://github.com/facebook/react-native/issues/898

### CODE REVIEW

**Comment by rocman** [comment]
https://github.com/facebook/react-native/issues/898

**Comment by nicklockwood** [comment]
Seems OK.

@javache does this make sense to you?

**Comment by javache** [comment]
So right now we do this on `reactBridgeDidFinishTransaction`. Would it make sense to do on `didMoveToSuperview` instead of `layoutSubviews`. The check is not expensive anyway, just wondering whether it's more correct.

**Comment by rocman** [comment]
Since binding the controller to its closest parent needs that the parent view exists, doing this in didMoveToSuperview might be too early. It is because the didMoveToSuperview does not ensure the view has been attached to the ui tree, which means the superview of its superview or so might be nil. Compared to didMoveToSuperview, layoutSubviews is called on the right time when the view is finally attached to the ui tree, and so every superview of it wouldn't be nil, and so we can get the right super controller for its controller.

**Comment by nicklockwood** [comment]
Makes sense. @facebook-github-bot shipit

**Comment by rocman** [comment]
Somebody?

**Comment by javache** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
