### PR TITLE
Include info about console.log

### PR DESCRIPTION
**Pull request by Emilios1995**
I spent so much time trying to optimize my JS without noticing this.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by gaearon** [comment]
May be a good idea to link to [no-console](http://eslint.org/docs/rules/no-console) eslint rule as a way to enforce this in application code.

**Comment by javache** [comment]
I would actually like to make the packager transform away all console.log/info/debug from the production JS bundle, since we drop them on the native side anyway.

**Comment by bestander** [comment]
#filetask [react native build infra] add console/debug stripping transform to packager :)

**Comment by Emilios1995** [comment]
That's exactly what I was planning to do ;) 
Do you prefer to do it yourselves?

**Comment by bestander** [comment]
Go for it, please! :)
Cc me and Pieter when you send the PR

**Comment by gaearon** [comment]
Can we get this merged for now? I’m not sure what RN merging process is so I’m afraid to hit the button 😄 .

**Comment by ide** [comment]
> I would actually like to make the packager transform away all console.log/info/debug from the production JS bundle

One thing to watch out for is side effects within console.log calls. IIRC assertions/warnings still run in prod but are silenced so that the assertion predicates are always evaluated. There was at least one SEV review due to assertions getting stripped out in prod and making a bug worse. So stripping the console.log calls to suppress output seems ok but I would suggest replacing them with no-ops.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1751399691794034/int_phab) to review.

**Pull request closed without merging**
