### PR TITLE
Update Podfile

### PR DESCRIPTION
**Pull request by dubiao**
Fix typo of "Pods" from "Poods"

## Summary

Fix typo

## Changelog

Typo "Poods" -> "Pods"

[CATEGORY] [TYPE] - Tyop

## Test Plan

None

### CODE REVIEW

**Comment by mdvacca** [comment]
@dubiao, thanks for the PR!
can you review the comment on https://github.com/facebook/react-native/pull/27382#issuecomment-560231333, this is necessary to land the PR.

Thank you

**Comment by isa3bel** [comment]
some of my checks for my Pr aren't passing either for the same problem. It seems these tests aren't failing due our changes. How can we get the tests to pass so it can be merged? @mdvacca

**Comment by hramos** [comment]
@isa3bel there's two tests in master that are failing [as of this writing](https://circleci.com/workflow-run/38fe22fe-e5db-47d4-a310-0578893dd366) - if your PR is failing at the same spot, it's likely not due to your changes. I'll be taking a look at the remaining CI failures on master today.

**Comment by AshishKapoor** [comment]
Apple MacBook Pro keyboard fails.🤦🏻‍♂️

**Comment by TheSavior** [comment]
As the CLA hasn't been signed we are unable to merge this PR. Please feel free to sign the CLA and let us know if you want us to reopen this PR

**Pull request closed without merging**
