### PR TITLE
[TextInput] Implements 'onKeyPress' for Android - PR fixes

### PR DESCRIPTION
**Pull request by adasiewiczr**
Link to original PR : https://github.com/facebook/react-native/pull/10665

It seems that author of the pull request from the link above has finished work on his PR, so I did a fork of his repository and I applied requested changes.

An attempt at the Android implementation. Attempted to mirror the iOS implementation by supporting 'Enter' and 'Backspace'.

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks for reviving this!

I have a n00b question - what's the use case for using `onKeyPress` in apps? Is it to detect when Enter and Backspace are pressed?
http://stackoverflow.com/questions/35764782/identify-return-key-action-in-react-native

**Comment by mxaly** [comment]
@mkonicek backspace is the one that i'm currently lacking on android and using on ios. On ios i was able to successfully build messenger like functionality for choosing/searching users (see creating new message screen) and used backspace to select and then remove last element. 

onChange is not fired when pressing backspace in empty input so can't use that in my case :(

**Comment by woshi82** [comment]
+1
`onChange is not fired when pressing backspace in empty input so can't use that in my case :(`

have any update? the PR is not work for me ,maybe there is something wrong in my code.

my use case is:
there are 5 textInput in my view, when i enter one word in textInput,it should auto focus the next textInput. when i delete the word ,if the length of the textInput's value is 0, it should auto focus prev textInput's. it's all OK with the onChangeText method.

**but when the length of the textInput's value  is 0 ,and  i press the delete key in android, nothing get work.**
image

**Comment by tiefox** [comment]
In my understanding in iOS onKeyPress actually works in any View and sub components, just tested on a Image component and it works. So would be good to have Android functionality that behaves in the same way. Regarding use cases, I'm developing an app that uses an external bar code scanner that actually behaves as a bluetooth external keyboard to iOS, so I have one custom view that can receive any keypresses from the barcode scanner.

**Comment by mxaly** [comment]
@mkonicek any updates here?

**Comment by codingrhythm** [comment]
@woshi82 you should use a hidden input to handle input, and just display the digits using normal Text and styles. It's way easier than handle 4 different text inputs

**Comment by AvijitDutta95** [comment]
@codingrhythm I like your solution but how can I use a hidden input in react native? I can't find much info on this online. Thanks!

**Comment by codingrhythm** [comment]
@AvijitDutta95 just change the opacity to 0

**Comment by shukerullah** [comment]
any updates here?

**Comment by dmueller39** [comment]
@adasiewiczr Any interest completing this? I would be happy to pick it up from here.

**Comment by Ashoat** [comment]
Heads-up that #14720 is happening in parallel to this one

**Comment by dmueller39** [comment]
@Ashoat That's really bizarre, @joshyhargreaves is actually a teammate of mine, and I had no idea he had that PR in the pipeline. Small world!

**Comment by voidstarfire** [comment]
Any progress on this, could really use it right now :-/

**Comment by BalalRaza** [comment]
@codingrhythm, is there a way to make user input data in some pre-described format? Suppose, I want to enter the value of a alpha-numeric code which goes like ABC123Z. I am currently using 3 input fields - one for the first ABC part, second for the numeric part and third for the last alphabet. I need the same use-case as required by @woshi82. How do I use a hidden input field in this case? Any help would be appreciated.

**Pull request closed without merging**
