### PR TITLE
Fix typo in ListViewDataSource documentation.

### PR DESCRIPTION
**Pull request by sheparddw**

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @pglotov and @davidaurelio to be potential reviewers.

**Comment by pglotov** [comment]
Could it be a case of [double copula](https://en.wikipedia.org/wiki/Double_copula)? )

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/485192651674591/int_phab) to review.

**Pull request closed without merging**
