### PR TITLE
Fix FlatList ItemSeparatorComponent type

### PR DESCRIPTION
**Pull request by bigcupcoffee**
## Summary
FlatList's ItemSeparatorComponent type did not support passing in react element as per documented in docs.

## Changelog
[GENERAL] [FIXED] - Fix FlatList ItemSeparatorComponent type

## Test Plan
None needed

### CODE REVIEW

**Comment by bigcupcoffee** [comment]
Welp from what I see in the code `VirtualizedSectionList` actually does not support react element as ItemSeparatorComponent, yet it's documented as supported? Do I make it support it or...

**Comment by NickGerleman** [comment]
> Welp from what I see in the code `VirtualizedSectionList` actually does not support react element as ItemSeparatorComponent, yet it's documented as supported? Do I make it support it or...

Does it work for FlatList, but not VirtualizedSectionList? It is does work for FlatList, but only FlatList, we could put this in FlatList typings instead of VirtualizedList typings.

**Comment by bigcupcoffee** [comment]
@NickGerleman I believe problem is VirtualizedSectionList does not properly override VirtualizedList's ItemSeparatorComponent type, and thus `this.props.ItemSeparatorComponent` comes in as possible Element which it should not be according to both code and the type override attempt(?) [here](https://github.com/facebook/react-native/blob/main/packages/virtualized-lists/Lists/VirtualizedSectionList.js#L44). Worth noting that SectionList docs actually state [Element](https://reactnative.dev/docs/sectionlist#itemseparatorcomponent) is supported as well, so we either support element in section list, or fix the type override and edit docs?

**Comment by bigcupcoffee** [comment]
@NickGerleman hey, would this get any attention? I'm glad to modify the PR as long as I know what would be the best fit here

**Comment by yungsters** [comment]
Thanks for the contribution, @bigcupcoffee!

It looks like support for elements was added in https://github.com/facebook/react-native/pull/32748.

However, there are Flow type errors surfaced by Circle CI. Can you look into fixing those? I can merge this after the errors addressed.

**Comment by yungsters** [comment]
Also, I apologize for the delay in reviewing this. (For some reason, our internal tooling that helps surface PRs was not working correctly.)

**Review by yungsters — CHANGES_REQUESTED** [review]
Requesting changes due to Flow errors in Circle CI.

**Comment by bigcupcoffee** [comment]
@yungsters I'm not sure how to fix the SectionList flow error, there seems to be an override already [here](https://github.com/facebook/react-native/blob/main/packages/virtualized-lists/Lists/VirtualizedSectionList.js#L44), which should mark the prop as Component only (since `VirtualizedSectionList` due to its own separator implementation doesn't support `Element` as for now, [this code](https://github.com/facebook/react-native/blob/main/packages/virtualized-lists/Lists/VirtualizedSectionList.js#L432)). I guess it comes from the `info.section.ItemSeparatorComponent || this.props.ItemSeparatorComponent` and one of these end up having `Element` as a possible type. I'm not good with flow so not sure how to resolve that, would really use some help here. While for `VirtualizedList` error, if I'm correct, you just need to add support for `React.Element` [right here](https://github.com/facebook/react-native/blob/main/packages/virtualized-lists/Lists/VirtualizedListCellRenderer.js#L25) and that should fix it.

Awaiting your reply about `SectionList`, as once again, [docs](https://reactnative.dev/docs/sectionlist#itemseparatorcomponent) state that `Element` is supported, so that should be fixed too?

**Pull request closed without merging**
