### PR TITLE
Remove invalid comma from Animated example

### PR DESCRIPTION
**Pull request by af**
Helps for suckers like me, who copy and paste example code ;)

### CODE REVIEW

**Comment by ide** [comment]
This code should run fine -- does it not for you?

**Comment by lelandrichardson** [comment]
@ide trailing commas for function invocations are a syntax error...  are you sure that runs for you?

**Comment by af** [comment]
Yeah it's a syntax error for ES6 and below. Try `console.log('hi',)` in the console. There is [a proposal](http://www.2ality.com/2015/11/trailing-comma-parameters.html) for it to be made legal in a future version of EcmaScript though.

**Comment by satya164** [comment]
FYI this transform is enabled in React Native by default.

**Comment by af** [comment]
Strange, it still gave me an error (using RN 0.17). Was that added recently? Regardless, probably better if the docs use standard JS when possible.

**Comment by mkonicek** [comment]
> FYI this syntax is enabled in React Native by default.

Closing based on the comment above.

**Comment by mkonicek** [comment]
>  Regardless, probably better if the docs use standard JS when possible.

Actually yeah, that's a valid point. I'm fine either way really.

@facebook-github-bot shipit

**Pull request closed without merging**
