### PR TITLE
* the NDK was on version 4.8 i stepup to the actual one 4.9 and fixed

### PR DESCRIPTION
**Pull request by mabels**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

I did not found the NDK with a version 4.8 so i step up to  the actual 4.9.

This raises some c++11x failures which i barely fixed.

---- Make sure tests pass on both Travis and Circle CI.

where is it?

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @mhorowitz and @cjhopman to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by charpeni** [comment]
Link to the Android NDK r10e (GCC 4.8) can be found here in the [React Native documentation](http://facebook.github.io/react-native/docs/android-building-from-source.html#download-links-for-android-ndk).

I'm not sure we should update to the GCC 4.9 since internally it uses 4.8 and it would probably needs more tests and changes than that. 

@astreet Any thoughts or news about that?

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mabels** [comment]
I agree and understand but, my c++11x changes should not.have any impact
backward to GCC 4.8.

I will try the old.ndk if there are some new problems rising

meno

**Comment by mabels** [comment]
Hi,

just loaded the old NDK and recompiled, and it also compiles it with out any problem.

I tried  the examples apps uiexplorer and moviesapp, no difference.

Yes i know this are not representing tests but my it looks like that my c++11x chances are 
backward compatible.

What you think could be the right tests for prove my changes?

meno

**Comment by ide** [comment]
AFAIK Facebook uses the r10e NDK internally and until they upgrade RN needs to be compiled with it. But if your changes are backwards compatible we could try merging this and see if it passes FB's internal acceptance tests.

@andreicoman11 @lexs would one of you be interested in seeing if this merges and builds for FB?

**Comment by mhorowitz** [comment]
Removing lambda capture initializers as this PR does will have a negative effect on performance.  https://gcc.gnu.org/gcc-4.9/changes.html talks a bit more about this; you need to use `-std=c++1y` to enable the feature.  But, I don't know if this flag is supported by g++ 4.8.

**Comment by mabels** [comment]
Hi,

I tried c++1y flag first, it does not worked on 4.8. I agree that there is
a performance degree, I could review my changes against this to give a
estimate about the possible impact. my quick assumption is in this case
there is no measurable performance lost.

I will try today to review it, and giving back my results.

meno

**Comment by mabels** [comment]
So here my findings... there are 7 more copys of small datastructures less than 32bytes each, 
which should removed by the optimizier anyways. 
The rest of the cases are the same like the implicit assignment. 
My opinion about no measurable performance impact is still ok.
If you are not following my assumption about "should removed by the optimizier" 
i could recheck this-:)

1) ReactAndroid/src/main/jni/react/Bridge.cpp
   -  new instance by std:move, no difference to the implicit assignment
2) ReactAndroid/src/main/jni/react/JSCExecutor.cpp
    - copy of a ptr and int, hopefully removed by the optimizier, "but harmless"
3) ReactAndroid/src/main/jni/react/jni/OnLoad.cpp
   -  copy of RefPtr<WeakReference>, hopefully removed by the optimizier
4) ReactAndroid/src/main/jni/xreact/jni/MethodInvoker.cpp
   - copy of two iterators, hopefully removed by the optimizier
5) ReactAndroid/src/main/jni/xreact/jni/ModuleRegistryHolder.cpp
   - new instance by std:move, no difference to the implicit assignment
6) ReactCommon/cxxreact/Instance.cpp
   - new instance by folly::makeMoveWrapper, no difference to the implicit assignment
7) ReactCommon/cxxreact/JSCExecutor.cpp
   - new instance by std:move, no difference to the implicit assignment
   - copy of a ptr and int, hopefully removed by the optimizier, "but harmless"
8) ReactCommon/cxxreact/NativeToJsBridge.cpp
  - new instance by std:move, no difference to the implicit assignment
  - new instance by folly::makeMoveWrapper, no difference to the implicit assignment

**Comment by lexs** [comment]
I'm afraid I don't really see the purpose of this. There shouldn't be any user-visibile differences between 4.8 and 4.9, in fact it seems we are even having less C++14 features in 4.9?

Internally we'll still continue to use 4.8 anyway so this will drift OSS away from what Facebook does which will cause problems for everyone. We are trying to move to Clang anyway so hopefully we can resolve this by also moving OSS to Clang.

**Comment by mabels** [comment]
Hi Alex

This patch works also with 4.8 and makes 4.9 working and I expect clang
will also work.

So I don't understand why you would like to integrate this in Facebook and
OSs?

It only 9  lines changed

Meno

**Comment by lexs** [comment]
Because I can't see any benefits this brings as we still need to compile with 4.8 internally (as there is loads on loads of other native code) which means that everything in RN still has to be compatible with 4.8. We'll never use 4.9 internally (as we skipped it and are moving to clang). Clang supports C++14 so we won't have to make any changes really.

What features specifically do you need from 4.9?

**Comment by mabels** [comment]
For nothing I just had the actual version installed and it failed on
compiling.

sorry that I tried.to improve your tooling.

thx for reactiv-native it's a great tool

meno

**Comment by lexs** [comment]
Thanks for trying to improve it! We know GCC 4.8 is a painpoint generally (I feel it every week) and we'll be able to move it to clang soon enough I hope.

**Comment by danielduner** [comment]
@lexs could you at least update the documentation to make it clear that you need to downgrade the NDK?

The page with [prerequisites](https://facebook.github.io/react-native/docs/android-building-from-source.html) implies it by using ndk-r10e in the example and linking to it, but doesn't specifically say that you need the old version.

[Other](https://github.com/facebook/react-native) [pages](https://github.com/facebook/react-native/tree/master/Examples/UIExplorer) simply say that you have to have the NDK installed, rather than specifying that you need an old version. I haven't had to use the NDK for regular react-native development and only needed it when compiling the UIExamples. If the UIExample readme had mentioned the need for an old NDK version that could have me a lot of time.

**Pull request closed without merging**
