### PR TITLE
bugfix for multiple shadow threads rendered at the same time, small probability crash.

### PR DESCRIPTION
**Pull request by chenmo187**
## Summary
bugfix for multiple shadow threads rendered at the same time, small probability crash.

## Changelog
Android
Fixed
ViewManagersPropertyCache.class

## Background:
on the Tab Page, every tab has a React Page. If the React page is not using the same ReactInstanceManager, multiple shadow threads will be generated.
A crash can occur when multiple pages are rendered at the same time.

## Reasons of issue: PropSetter class VIEW_MGR_ARGS, VIEW_MGR_GROUP_ARGS, SHADOW_ARGS, SHADOW_GROUP_ARGS is static.
one shadow put data in static array, it was changed by another shadow thread before method invoke.

## The solution:
use ThreadLocal instead of static array.

## Test Plan
Test on my App 20 times. it is not crash again.

### CODE REVIEW

**Comment by chenmo187** [comment]
I am not change anything about iOS. why  "ci/circleci: test_ios_unit_jsc — Your tests failed on CircleCI"

**Review by lunaleaps — CHANGES_REQUESTED** [review]
@chenmo187 Can you give more insight into the problem this is solving and a reproduction? Additionally, can you format your PR?

**Comment by chenmo187** [comment]
> @chenmo187 Can you give more insight into the problem this is solving and a reproduction? Additionally, can you format your PR?

**Comment by chenmo187** [comment]
> @chenmo187 Can you give more insight into the problem this is solving and a reproduction? Additionally, can you format your PR?

OK, I will make a new PR

**Comment by lunaleaps** [comment]
Cool, you can request a review from me.

**Pull request closed without merging**
