### PR TITLE
Remove survey banner.

### PR DESCRIPTION
**Pull request by JoelMarcey**
We have gathered enough data to determine whether our docs direction
was the right approach.

Test Plan:

Ran locally, no survey banner is displayed.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
No survey banner shown now...

screenshot 2016-09-23 09 40 38

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @Andreyco to be potential reviewers.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3914445).

**Pull request closed without merging**
