### PR TITLE
Make a new "Style" doc that's in The Basics and uses the RNWP

### PR DESCRIPTION
**Pull request by lacker**
The example uses StyleSheet.create and also arrays-of-styles. I think this covers everything the old one did, but in simple-enough-for-the-basics form, so I removed the old one. I also reordered so that "Style -> Dimensions -> Layout" is the flow for learning "Styley" things.

### CODE REVIEW

**Comment by lacker** [comment]
screencapture-localhost-8079-react-native-docs-style-html-1466714998878

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @dabbott to be potential reviewers.

**Comment by caabernathy** [comment]
Sweet.

**Comment by caabernathy** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/279974979059801/int_phab) to review.

**Pull request closed without merging**
