### PR TITLE
Doc fix for getPackages method

### PR DESCRIPTION
**Pull request by shanmbic**
getPackages() Method has been shifted to 'MainApplication.java' and not 'MainActivity.java'.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @satya164 and @alvinthen to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
Can you open the PR against master instead?

**Comment by shanmbic** [comment]
Hi ! I guess someone already corrected it. The master branch contains the reference to 'MainApplication.java' now . 👍

**Pull request closed without merging**
