### PR TITLE
Add zIndex support

### PR DESCRIPTION
**Pull request by tuckerconnelly**
Android uses [View.setZ()](https://developer.android.com/reference/android/view/View.html#setZ(float)), so it only works in 5.0+

If someone wants to take a crack at 4.1, you could probably get all the sibling views, sort them by zIndex, and then call View.bringToFront() on them in order.

### CODE REVIEW

**Comment by tuckerconnelly** [comment]
Working on 4.1 support.

**Comment by facebook-github-bot-7** [comment]
@tuckerconnelly updated the pull request.

**Comment by tuckerconnelly** [comment]
Alright, supports 4.1 :)

Definitely needs a review though

**Comment by mkonicek** [comment]
Thanks for working on this @tuckerconnelly, this is a much requested feature. It's cool Android added `View.setZ`.

The pull request has a lot of commit, it looks like you only want the last one?

Could you please also add example use cases in the UIExplorer (https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ViewExample.js) and some screenshots / videos to your Test plan? See https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by facebook-github-bot-6** [comment]
@tuckerconnelly updated the pull request.

**Comment by tuckerconnelly** [comment]
Moved to https://github.com/facebook/react-native/pull/7825 so I could cherrypick onto master

**Pull request closed without merging**
