### PR TITLE
Add missing closing brace in docs

### LINKED ISSUE #11150: Missing closing brace for fetchCompletionHandler in PushNotificationIOS Docs at https://facebook.github.io/react-native/docs/pushnotificationios.html
### Description

The PushNotificationIOS Docs is missing closing brace for fetchCompletionHandler.

### Reproduction

Try to compile using the current Docs:
 - See: https://facebook.github.io/react-native/docs/pushnotificationios.html.
```
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
   {
      [RCTPushNotificationManager didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
   }
   // Optionally implement this method over the previous to receive remote notifications. However
```

### Solution

Change Docs to read:
```
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
   {
      [RCTPushNotificationManager didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
   }
}
   // Optionally implement this method over the previous to receive remote notifications. However
```

### PR DESCRIPTION
**Pull request by damusnet**
This is a minor documentation fix

fixes #11150

### CODE REVIEW

**Comment by janicduplessis** [comment]
We can get rid of the extra set of braces so it just looks like:
```
- (void) application...
{
  [RCT... ]
}
```

**Comment by damusnet** [comment]
@janicduplessis makes sense. It looked weird but I just blindly followed the issue it's related to. Thanks for reviewing.

**Comment by janicduplessis** [comment]
Thanks!

@facebook-github-bot shipit

**Comment by tristanbbq** [comment]
@janicduplessis can you cherry pick this and integrate in `0.39-stable`? it needs to be fixed for people using 0.39 and avoid them from going through the same issue I had!

**Comment by tristanbbq** [comment]
Here's a new PR with cherry pick in `0.39-stable`: https://github.com/facebook/react-native/pull/11493

@janicduplessis can you merge and release?

**Comment by janicduplessis** [comment]
@tristanbbq Done

**Pull request closed without merging**
