### PR TITLE
[React] Change React version to 15.3.1 (no more RC)

### PR DESCRIPTION
**Pull request by ide**
React 15.3.1 has been published; stop using the RC.

### CODE REVIEW

**Comment by ide** [comment]
Can someone on FB's side apply this change?

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @zpao to be potential reviewers.

**Comment by grabbou** [comment]
Is there any extra action required or can we just ship it as is?

**Comment by zpao** [comment]
@grabbou Pretty sure dependency changes need to be done internally or things will break.

**Comment by mkonicek** [comment]
@zpao, @spicyj I can help. Is switching to 15.3.1 safe? Has it been tested with React Native?

**Comment by zpao** [comment]
https://github.com/facebook/react/compare/9e8846748572b3a36513044f9b94b41e108866c6...15df676d2e142d63dcb0a59b830f16759fab601e is the set of changes from rc2 to final. There were 2 non-dom changes: the test renderer got a tiny fix for null handling and proptypes error subclassing (which is all internal stuff so doesn't matter). I don't foresee this being risky in the slightest.

**Comment by zpao** [comment]
What's the status on the internal update @mkonicek? cc @spikebrehm

**Comment by philikon** [comment]
Note: please uplift to 0.34-stable branch once this has landed on master. Or perhaps just go ahead and do it on 0.34-stable branch since that doesn't affect FB internal anyway.

**Comment by ide** [comment]
@philikon good call, that's what I did for 0.33. Pushed to 0.34 in bd84b81114ec2e721.

**Comment by zpao** [comment]
I didn't realize that was even an option. Thanks @philikon & @ide.

**Comment by philikon** [comment]
merci @ide!

**Comment by mkonicek** [comment]
Sorry about the delay, will try to land this internally tomorrow :)

**Comment by mkonicek** [comment]
Aaand it landed :)

**Comment by mkonicek** [comment]
Please feel free to message me next time, my GitHub notifications are a mess :( I haven't found a good way to stay on top of them without spending 30 min every day. Fb groups and messages work very well.

**Pull request closed without merging**
