### PR TITLE
Animated.delay may not always be an interaction

### PR DESCRIPTION
**Pull request by Srirangan**
I have a passive animation sequenceon a screen. The sequence uses a delay. But the delay is always treated as an interaction. This causes all sorts of bugs / race conditions.

Delay sometimes may not be an interaction.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @wusuopu to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by javache** [comment]
I think this puts us on the slippery slope of requiring this parameter on every animated API. Instead, could you use the full API in your call site, or provide a helper method that does this?

Feel free to reopen if you disagree.

**Comment by Srirangan** [comment]
No its fine. But I can imagine a lot of usages of `Animated` for passive on screen animations, and interactions being mostly navigation related.

**Pull request closed without merging**
