### PR TITLE
Remove unnecessary double test in Navigator

### PR DESCRIPTION
**Pull request by dzautner**
_renderScene would unnecessary test if `this.state.transitionFromIndex != null` twice.

The left side and right side of the 'or' statement would always be the same.

For cleaner code I suggest to remove it.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
@dzautner updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10042/files/47ff7c4322af608ad56f0c05e48e5adab3c722a6..5e0a9323d1f81b72a70fa386d8514730e13e32ac)

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
@dzautner updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10042/files/d865043cc34bb306e0ab153421ce35b7295369af..7461a3e1f51b17f8e7a5dc85a4183499dc31f916)

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
@dzautner updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10042/files/7461a3e1f51b17f8e7a5dc85a4183499dc31f916..f3e72ddf11fe23abc3f29a57f039235fc091762c)

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3923058).

**Pull request closed without merging**
