### PR TITLE
Update fri 29 may

### PR DESCRIPTION
**Pull request by tadeuzagallo**

### CODE REVIEW

**Comment by ccheever** [comment]
I think this can be closed because a superset of commits was merged in https://github.com/facebook/react-native/pull/1432

@brentvatne - I don't have sufficient permissions to close but I know you're triaging today?

**Comment by tadeuzagallo** [comment]
I merged #1432 with the commits up to yesterday, these commits are today's, they don't have any commit in common. Be careful before closing things.

**Comment by ccheever** [comment]
@tadeuzagallo sorry my mistake -- i posted my comment to the wrong tab in my browser, and it should have gone to this page.
https://github.com/facebook/react-native/pull/1392

(Will note this on my earlier comment.)

**Comment by tadeuzagallo** [comment]
Oh, I see. Closed it, Thanks!

**Pull request merged**
