### PR TITLE
[Android] adding missing string case in ReadableNativeMap to HashMap

### PR DESCRIPTION
**Pull request by VonD**
about #6639

### CODE REVIEW

**Comment by ajwhite** [comment]
Yep, thank you @VonD. this looks good :+1:

**Comment by ajwhite** [comment]
Yep, thank you @VonD. this looks good :+1: 

/cc @satya164

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
Thank you for the PR

**Pull request closed without merging**
