### PR TITLE
enable the minWidth/maxWidth/minHeight/maxHeight features

### PR DESCRIPTION
**Pull request by rocman**

### CODE REVIEW

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by brentvatne** [comment]
We should get this in for Android as well! cc @mkonicek

**Comment by vjeux** [comment]
Sorry to be the bad guy here but the implementation of min/max width/height on css-layout isn't ready to be used. It only supports a couple of cases and not even many of the common use cases nor any edge case.

Using this one would be really bad as people are going to rely on this bad implementation and it's going to be a major pain to upgrade to the proper one once we fix the issues

**Comment by rocman** [comment]
Concerning about this. Is there any plan or even actual moves on implementing them?

**Comment by nicklockwood** [comment]
@vjeux Is the API likely to change?

**Comment by vjeux** [comment]
@nicklockwood: the api is going to stay the same. But if people use it today and we upgrade it, it'll break their app in subtle ways that we can't make backward compatible.

The current implementation is not just a bit off, it's completely wrong for most common inputs.

Right now no one is working on it, but I'll gladly accept pull requests that improve the implementation.

**Comment by bergl** [comment]
FYI It is inside documentation:
https://facebook.github.io/react-native/docs/flexbox.html#proptypes

and:
https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/LayoutPropTypes.js
https://github.com/facebook/react-native/commit/2244a86eea9e6ad2d4094b126530f07291324f15

**Comment by mkonicek** [comment]
FYI {min,max}{Width,Height} have been removed from the docs: https://github.com/facebook/react-native/commit/2529179769ff7f24f9b91acc5417e19983958ff6

A per vjeux's comment above:

> The current implementation is not just a bit off, it's completely wrong for most common inputs. Right now no one is working on it, but I'll gladly accept pull requests that improve the implementation.

The implementation is here: https://github.com/facebook/css-layout

**Comment by SudoPlz** [comment]
Temporary fix [here](http://stackoverflow.com/a/37308282/1658268):

**Pull request closed without merging**
