### PR TITLE
Upgrade RN CLI to v9.0.0 and Metro to 0.72.1

### PR DESCRIPTION
**Pull request by thymikee**
## Summary

Stable v9 of the CLI, no major changes compared to previous alpha releases.

Metro release notes: https://github.com/facebook/metro/releases/tag/v0.72.1

cc @kelset @huntie 

## Changelog

[General] [Changed] - Upgrade RN CLI to v9.0.0

## Test Plan

CI

### CODE REVIEW

**Review by robhogan — APPROVED** [review]

**Review by kelset — CHANGES_REQUESTED** [review]
it's missing the bump of the Metro deps to 0.72.1 - need to add those before getting this merged

**Comment by thymikee** [comment]
Shall I wait for the Metro team to upgrade it separately and then rebase?

**Comment by kelset** [comment]
> Shall I wait for the Metro team to upgrade it separately and then rebase?

my understanding is that the whole point of them doing a PR to CLI was that then the CLI+Metro bump would always be done together

**Comment by robhogan** [comment]
> it's missing the bump of the Metro deps to 0.72.1 - need to add those before getting this merged

Yep - sorry for the confusion, I missed some of this discussion yesterday. This is correct.

@thymikee happy to make that update to this PR myself if you don't have chance today

**Comment by thymikee** [comment]
@robhogan I'd appreciate that, thanks!

**Review by kelset — APPROVED** [review]

**Pull request closed without merging**
