### PR TITLE
Added way to not launch packager during CI build, as it hangs CI builds

### PR DESCRIPTION
**Pull request by BretJohnson**
Change & motivation:
Added an environment variable, RCT_NO_LAUNCH_PACKAGER, that when set
Xcode not the launch the packager when building. This switch is needed
for CI builds, where launching the packager, which stays running, causes
the build to hang; port conflicts can be an issue as well. Really the
packager is only appropriate for interactive developer builds.  This
is a problem for Visual Studio Team Services where we just added
React Native CI build support with a React Native build extension and
surely a problem for all CI systems.  This fix is simple, and now if
the build machine sets RCT_NO_LAUNCH_PACKAGER globally or passes
it as an arg to xcodebuild, the packager won't launch and all is well.

Testing:
I tested by building both with & without the environment variable defined, ensuring
things work probably in both cases.  I also added support to our VSTS build ask to use
this and verified it works as expected too, when setting the variable..

### CODE REVIEW

**Comment by mroswald** [comment]
@facebook-github-bot shipit

**Comment by BretJohnson** [comment]
As for the CLA Signed label: I did sign the CLA earlier, late last year. But my GitHub user name (not email) changed after the acceptance, which apparently caused issues with the Facebook CLA acceptance registry, which needed to be fixed manually.  Christine Abernathy at Facebook fixed that up today. I'm not sure what's needed to get the CLA Signed label to show up on this PR--hopefully something will trigger it--but I did sign the CLA.

**Comment by BretJohnson** [comment]
Good--my comment triggered the CLA Signed label being added. Hopefully you guys can merge this soon. Thx.

**Comment by BretJohnson** [comment]
Closing / reopening PR, to retrigger Travis build.

**Comment by BretJohnson** [comment]
Reopening PR, to retrigger Travis build.

**Comment by jeanregisser** [comment]
Can this be merged?

**Comment by facebook-github-bot-8** [comment]
@sahrens would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by dlahyani** [comment]
Can someone please rebase this branch so it could be merged?

**Comment by jeanregisser** [comment]
@BretJohnson any chance you can rebase your changes?

**Comment by facebook-github-bot-3** [comment]
@BretJohnson updated the pull request.

**Comment by BretJohnson** [comment]
@jeanregisser I just hit the "Update branch" button.  Will that do it?

**Comment by jeanregisser** [comment]
@BretJohnson looks like it's good.
@mroswald could you retry the `shipit` command? (or @sahrens?)

**Comment by mroswald** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by jeanregisser** [comment]
@mroswald looks like you don't have permission to import it. cc @mkonicek

**Comment by omeid** [comment]
Is there anything needs to be done to get this merged in?

**Comment by dlahyani** [comment]
I am still waiting for this PR.
People at my company already hate me for adding react-native to our app, now they have to suffer this packager server window popping with every build even though we embed the .jsbundle file into the app.

**Comment by sahrens** [comment]
Sorry for the delay on this.

@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3764648) to review internal test results.

**Comment by dlahyani** [comment]
@sahrens  Thanks!!

**Pull request closed without merging**
