### PR TITLE
add eventName property to RCTEventEmitter

### PR DESCRIPTION
**Pull request by ShogoSaito0607**
## Summary
- Enable to get `eventName` from RCTEventEmitter.
  - We can get eventName on subclass of RCTEventEmitter.
    - `eventName` is provided by `addListener` function from ReactNative.

## Changelog

[General] [Added] -  From RCTEventEmitter, enable to get `eventName` provided by `addListener` function.

## Test Plan

-

### CODE REVIEW

**Review by Sifat1998 — APPROVED** [review]

**Review by Sifat1998 — APPROVED** [review]

**Comment by trung2891** [comment]
hello

**Comment by charlesbdudley** [comment]
Hi @ShogoSaito0607 Can you help me understand the use case for this? Thanks

**Comment by cortinico** [comment]
Hey @ShogoSaito0607 
Are you still interested in merging this?

**Comment by cortinico** [comment]
Closing as the original author is unresponsive

**Pull request closed without merging**
