### PR TITLE
Add followUserLocation prop to focus on user s location

### PR DESCRIPTION
**Pull request by Crash--**
I had the same use case as #3105. I needed to display the User Location without focusing on it. 

`followUserLocation` was already defined but not used.

### CODE REVIEW

**Comment by udfalkso** [comment]
Nice.  Thanks!

**Comment by udfalkso** [comment]
Any progress on this?  Would be nice to get it merged in.  Thanks

**Comment by satya164** [comment]
@Crash-- could you rebase?

**Comment by Crash--** [comment]
Yep very soon

**Comment by jmeyers44** [comment]
Will this be merged? Thanks!

**Comment by Crash--** [comment]
I don't know, but I'll fix the PR today.

**Pull request closed without merging**
