### PR TITLE
Remove default transformer argument

### PR DESCRIPTION
**Pull request by vaskevich**
Specifying a default for `--transformer` causes any setting for `getTransformModulePath()` in a custom `rn-cli.config` file to be overshadowed. Note that this value was already set in `/packager/rn-cli.config.js`, which is loaded by default.

Test plan:
Running `react-native run-android` (or `start` or `run-ios`) with a custom `rn-cli.config.js` file now works as expected.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @grabbou and @Kureev to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
@vaskevich Do I understand it correctly that currently `getTransformModulePath` in the config was always ignored and this PR fixes that?

**Comment by facebook-github-bot-2** [comment]
@vaskevich updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9585/files/a696d28e32dd3dd75434b45917cdda57a006b6d3..61e5a962499ace9a40eb3ae7c451dc021db3e1ae)

**Comment by vaskevich** [comment]
@mkonicek: yeah, basically.

**Comment by mkonicek** [comment]
@vaskevich Thanks for clarifying 👍 I'll wait for @davidaurelio to take a look.

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3887234) to review internal test results.

**Comment by davidaurelio** [comment]
this was also in 111ed8d180d6a7dd693aa50fe9ae9fab322991c3

**Pull request closed without merging**
