### PR TITLE
chore: ☂️ Migrate UIManagerModuleConstantsHelperTest.kt to AssertJ

### PR DESCRIPTION
**Pull request by yakupozbaydar**
## Summary:
Issue: https://github.com/facebook/react-native/issues/45596

## Changelog:

[INTERNAL] [CHANGED] - Migrate UIManagerModuleConstantsHelperTest.kt to AssertJ testing library

## Test Plan:
Run ./gradlew -p packages/gradle-plugin test

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
Sweet stuff @yakupozbaydar !

**Comment by yakupozbaydar** [comment]
Thank you  🙌 @cortinico

**Comment by cortinico** [comment]
The test failed to compile though due to:

```
e: file:///__w/react-native/react-native/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelperTest.kt:68:29 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Map<String, Any?>?
```

**Review by cortinico — CHANGES_REQUESTED** [review]
Please fix the error and we can merge it afterwards

**Comment by yakupozbaydar** [comment]
i've just committed, thank you for your pointing out the mistake @cortinico

**Pull request closed without merging**
