### PR TITLE
Advice on how to remove console.log statements.

### PR DESCRIPTION
**Pull request by Emilios1995**
## Motivation

Provide a straightforward solution to the potential performance bottlenecks caused by `console.log` calls

### CODE REVIEW

**Comment by mkonicek** [comment]
Should `console.log` be a no-op under the hood automatically? Is `console.log` ever useful in production and would anyone want to ever ship an app that logs to the console to the app stores?

**Comment by Emilios1995** [comment]
@mkonicek I made a PR that did exactly that but it was rejected. see #8337

**Comment by Emilios1995** [comment]
@mkonicek the babel plugin `transform-remove-console` seems to work fine for me when bundling for iOS. 
Though back in October it was [reported](https://github.com/facebook/react-native/pull/8337#issuecomment-253814388) that it didn't work when running `assembleRelease` with gradle.

I can't test that right now. will do it later to see if the issue is gone.

If it is, it'll definitely be better to suggest using that plugin, rather than overriding the `console.log` method

**Comment by Emilios1995** [comment]
@mkonicek [Look](https://github.com/facebook/react-native/issues/10412#issuecomment-281321709), it seems that it's already solved. I'll open a new PR to suggest the usage of the plugin

**Comment by Emilios1995** [comment]
closed in favor of #13651

**Pull request closed without merging**
