### PR TITLE
Log a soft exception from accessibility event exceptions

### PR DESCRIPTION
**Pull request by Abbondanzo**
## Summary:

This PR attempts to solve [this issue](https://github.com/facebook/react-native/issues/33021) I created last year, where accessibility events can fire after a view has been unmounted, causing the entire application to crash. This newly added try/catch block is modeled and copies verbiage exactly from the Fabric implementation of accessibility events [here](https://github.com/facebook/react-native/blob/2d9c81780c2bb3c2c2dc8875147261c9a1843eb4/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/mounting/mountitems/SendAccessibilityEventMountItem.java#L30-L43) and [here](https://github.com/facebook/react-native/blob/2d9c81780c2bb3c2c2dc8875147261c9a1843eb4/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/mounting/mountitems/SendAccessibilityEventMountItem.java#L30-L43).

## Changelog:

[ANDROID] [FIXED] - Fixed an issue where calling `Accessibility.setAccessibilityFocus` on an unmounted component would crash

## Test Plan:

1. I reimplemented the crash demo from the Snack showcased in [this issue](https://github.com/facebook/react-native/issues/33021). I created the branch [here](https://github.com/Abbondanzo/react-native/pull/1/files), although I may archive or delete this repo in the future so the link is not permanent
1. I disabled the new Fabric architecture. This crash only occurs in the old architecture
1. I pressed the button that would set accessibility focus on an unmounted component, and it logs a soft exception as seen in the screenshot below. I've also attached a screenshot from an identical soft exception that already gets logged by Fabric
1. In both cases, the app continues to function as expected

|Example SoftException from this change|Example SoftException from Fabric (no changes to this code)|
|-|-|
|image|image|

### CODE REVIEW

**Comment by Abbondanzo** [comment]
Wanted to bump this one for review since it's still causing issues for a number of our users

**Comment by consuelo-sanna** [comment]
Hi @cortinico, @Titozzz,
I tag you here because we were discussing this topic, I hope you don't mind

As explained in the summary by Abbondanzo this PR would solve/improve the issue on Android that crashes if does not find the tag. you also mentioned that findNodeHandle is deprecated/is going to be deprecated - based on that, do you think this PR can be merged in?

I have not found much documentation about deprecating findNodeHandle, would you also be so kind to point me in the right direction for that?
Thank you

**Comment by cortinico** [comment]
Hey @consuelo-sanna
You mentioned there was a previous discussion around this topic which came to your attention. Could you share it here for future reference?

**Comment by cortinico** [comment]
When we met in person, you mentioned that someone shared that this is the "intended behavior". Could you link that conversation?

**Comment by consuelo-sanna** [comment]
yes, I was referring to this [comment](https://github.com/facebook/react-native/issues/22807#issuecomment-474410038) by titozzz

I definitely see titozzz's point of view, but being a feature used for accessibilities reasons I think it would make more sense to handle it more gracefully than crashing, which would also align with what happens on iOS

**Comment by Abbondanzo** [comment]
Syncing my fork reopened this PR, was going to start work on something else from main (converting some of those tests to Kotlin). Want me to close this PR since it's been imported on your end?

**Comment by zfrankdesign** [comment]
Has this been released yet? I can't find the RN version needed for this fix. Any help appreciated.

**Comment by Abbondanzo** [comment]
> Has this been released yet? I can't find the RN version needed for this fix. Any help appreciated.

https://github.com/facebook/react-native/commit/5323221d1442d1573bc65daff618478cb6f056f0
According to the commit it was included in, it should be in 0.73.0 and up

**Pull request closed without merging**
