### PR TITLE
Merge rnpm into react-native

### PR DESCRIPTION
**Pull request by grabbou**
This is initial (first step) in the merging process. For now, we are just going to move our code as is into `local-cli` folder (first commit). There were other tweaks made in separate commits to make it easier to go through the code as the diff is expected to be rather large. The purpose of this is to make it easier to start working in small batches and improving the CLI incrementally on a daily basis.

Current codebase will still leave in `rnpm` organisation on Github where we keep working on new features, bugs and ship releases to `npm` until we finish our integration and provide a nice interface for users to migrate (in case it changes at all)

Flow, Jest and npm will ignore this folder for now until we integrate it properly. 

Tests are to be rewritten from mocha to jest in `rnpm/link`. We will hook them all up as soon as we start using them in local-cli. 

For now, there's no point in having them running and possibly breaking the builds.

We will announce next steps with @Kureev later this week.

CC: @mkonicek

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @jeffmo to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
@grabbou updated the pull request.

**Comment by Kureev** [comment]
Thanks for taking it over, @grabbou ❤️

**Comment by ide** [comment]
I assume you guys considered publishing rnpm to npm and installing it from there (react-native's package.json would depend on rnpm). That seems like an almost strictly better idea than merging it into this repo but maybe there are good reasons not to?

**Comment by Kureev** [comment]
I think @mkonicek wants to see rnpm as a part of react-native (merged into core).

**Comment by grabbou** [comment]
> but maybe there are good reasons not to?

The main reason was that hopefully in like 2 or 3 months there will be no rnpm and everything is going to be merged / added / implemented as a part of local-cli. That includes things like upgrade command or these detection mechanism. Being in the repo means we can optimise the releases better and gain more contributions / code reviews w/o working on it alone.

We can of course require it normally from the react-native or just move out entire `cli` out of react-native repo and make the `rnpm` peerDependency (that has the benefit of not having the `yeoman` installed here).

**Comment by mkonicek** [comment]
@ide I thought since features like `rnpm link` are such core to React Native it made sense to make it part of React Native itself. Adding a dependency in package.json would work too. Since rnpm is going to be part of the CLI (`react-native link` for example) it might be easier to have the CLI and rnpm in the same repo, to be able to refactor code etc. This will also make rnpm part of the release. I remember with other parts of React Native, such as node-haste we had some issues with them living in a separate repo, such as not everyone working on React Native had a permission to npm publish when we needed to publish a fix. Is there an advantage of using a separate repo?

**Comment by mkonicek** [comment]
> Being in the repo means we can optimise the releases better and gain more contributions / code reviews w/o working on it alone.

This is a good argument too.

**Comment by mkonicek** [comment]
Let's shipit :)

@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1565572200404149/int_phab) to review.

**Pull request closed without merging**
