### PR TITLE
Support centerOffset and calloutOffset on MapView annotations

### PR DESCRIPTION
**Pull request by erickreutz**
Pretty straight forward additions here. Added this because most of the time annotations are in "pin" form and you would like the center to be the bottom center of the pin. You could always set a transform but this feels better.

Happy to add these props to the docs if you guys want to get this upstream. Anything else I need to do?

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @jerolimov to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@erickreutz updated the pull request.

**Comment by erickreutz** [comment]
@nicklockwood, @jerolimov anything I need to do to get this in?

**Comment by facebook-github-bot-1** [comment]
@erickreutz updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@erickreutz updated the pull request.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/support-centeroffset-and-calloutoffset-on-mapview-annotations

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Pull request closed without merging**
