### PR TITLE
ScrollView should not use RefreshControl on tvOS

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
**Motivation**: On tvOS, Flatview and other components that use ScrollView with a RefreshControl will break without this change.

**Test plan**: Manual testing on tvOS simulator.

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
@ericvicenti here is the separate PR for the ScrollView/RefreshControl fix for tvOS.

**Comment by janicduplessis** [comment]
I'd rather put the TVOS check in the same check as `Platform.OS === 'ios'` a few lines after. I guess it would still work properly since isTVOS is probably undefined on Android but that would make it clearer.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
plz bot :o

@facebook-github-bot shipit

**Comment by dlowder-salesforce** [comment]
@facebook-github-bot status

**Comment by dlowder-salesforce** [comment]
ur bot is broken, I think

**Comment by janicduplessis** [comment]
Yea I'll bug @mkonicek

**Comment by mkonicek** [comment]
Hi guys, sorry I don't see GitHub notifications - there are too many to keep track of, and I think there's no way to filter them by mentions? Please message me on Slack like Janic did.

**Pull request closed without merging**
