### PR TITLE
Bump SocketRocket to 0.7.0

### PR DESCRIPTION
**Pull request by Saadnajmi**
## Summary:

We've been using SocketRocket 0.7.0 (to pick up a few bug fixes) without issue in React Native macOS. Might as well bump it upstream before 0.73 if we can.

## Changelog:

[IOS] [CHANGED] - Update SocketRocket to 0.7.0

## Test Plan:

CI should pass

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
@Saadnajmi there are some issues with 0.7.0 and Flipper on Android: https://github.com/facebook/react-native/issues/38012#issuecomment-1613461259

**Comment by Saadnajmi** [comment]
> @Saadnajmi there are some issues with 0.7.0 and Flipper on Android: [#38012 (comment)](https://github.com/facebook/react-native/issues/38012#issuecomment-1613461259), don't know if this is fixed or not, just pointing it out

Thanks! Maybe because Flipper is getting deprecated (see https://github.com/react-native-community/discussions-and-proposals/pull/641) this is fine, but I guess we shall see :D

**Comment by ryancat** [comment]
cc @cipolleschi 

I think Flipper is planned to get deprecated, but there are still people using it and we may need to have a deprecation plan for it?

**Comment by cipolleschi** [comment]
Hi! Unfortunately, the fact that Flipper is deprecated, but not removed, means that we can't bring this in right now. We will have to wait at least until 0.74, when the plan is to remove the default Flipper integration. :(

**Comment by cipolleschi** [comment]
I think we can keep this open... just... re-ping us when we removed flipper and we approach 0.74, if we forget about this! 😝

**Comment by Saadnajmi** [comment]
> I think we can keep this open... just... re-ping us when we removed flipper and we approach 0.74, if we forget about this! 😝

Should be good since https://github.com/facebook/react-native/commit/899e7cdb55197fc17a96a93af4f8bcc7519553c2 landed? I didn't update the `Podfile.lock` because that seems to have git hashes and always has a merge conflict in my experience :(

**Comment by cipolleschi** [comment]
I wonder if we have to mark this as breaking, with a message that instruct our users to run `bundle exec pod install --repo-update` in order to grab the most recent SocketRocket spec... what do you think?

**Comment by Saadnajmi** [comment]
> I wonder if we have to mark this as breaking, with a message that instruct our users to run `bundle exec pod install --repo-update` in order to grab the most recent SocketRocket spec... what do you think?

I'm pretty used to having to do this whenever any pod changes (folly, etc). Did we have to tell users that when we went to 0.6.1? It doesn't hurt I suppose, but I don't to m think there's a precedent for it. Cocoapods is pretty great at telling you to run exactly that if your pod install fails.

**Pull request closed without merging**
