### PR TITLE
[TabBarIOS] badgeColor property

### PR DESCRIPTION
**Pull request by skv-headless**
**motivation:**

make possible to use new tab bar item property

### CODE REVIEW

**Comment by mmmulani** [comment]
@facebook-github-bot import

**Comment by skv-headless** [comment]
@mmmulani #10241 almost the same pull request maybe you can take a look.

**Comment by skv-headless** [comment]
I assume that something went wrong. May I help somehow?

**Comment by mmmulani** [comment]
sorry about the delay, trying to land it now

**Comment by mmmulani** [comment]
agh this is running into a problem with our testing scripts trying to run on iOS 10 but our internal infra using iOS 10.1, trying to get it resolved now

**Comment by skv-headless** [comment]
@mmmulani what progress on this?

**Comment by mmmulani** [comment]
sorry, let me try landing again

@facebook-github-bot shipit

**Pull request closed without merging**
