### PR TITLE
navigator.getCurrentRoutes

### PR DESCRIPTION
**Pull request by Kureev**
According to our talk with @ericvicenti about `renderScene` arguments

### CODE REVIEW

**Comment by ericvicenti** [comment]
So, I've thought about this, and I am concerned because this navState will sometimes appear to be incorrect in the renderScene prop.

Here's the simplest example:
- Initialize navigator with one scene
- Push on a new scene
- The navState and the routeStack that was passed to the first renderScene is now out-of-date, but we don't want to re-render it because it is going offscreen

I think this would probably add more confusion. Instead, I want to add a method to Navigator that lets you get the current routeStack.

Is there a reason you need to access the routeStack from inside the navigator? Maybe I could show you where you might run into some issues and help you find an alternative.

cc @ide , we were talking about this earlier

**Comment by Kureev** [comment]
@ericvicenti Thanks for your feedback! Yeah, I have a use-case for that: for example, I created a navbar component I wanna use with Navigator. As far as I'm not sure how `navigationBar` property supposed to work (position at the bottom in the render stack is really confusing me. I don't wanna add `position: absolute, top: 0, left: 0` to every view). You can check the [stub I made in my component](https://github.com/Kureev/react-native-navbar/blob/master/index.js#L45-L47) to support this. Probably, it's a good idea to expose `getRouteStack()`-like endpoint as third parameter for `renderScene`?

**Comment by ericvicenti** [comment]
I don't want to pollute renderScene's arguments. Thanks for adding it to the navigator! This looks good, I'll start merging this in.

We can come back to the navBar ordering issue later. Absolute positioning of the navBar is OK because it needs to appear over the scenes in most cases. You shouldn't need to apply `position: absolute, top: 0, left: 0` to every scene; have you tried `flex: 1`?

**Comment by Kureev** [comment]
Is it going to be merged some day?

**Pull request closed without merging**
