### PR TITLE
[NavigationExperimental] Migrate NavigationCardStack

### PR DESCRIPTION
**Pull request by jmurzy**
As discussed in #8262.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @ericvicenti to be potential reviewers.

**Comment by jmurzy** [comment]
@ericvicenti For NavigationCardStack, do we want to stay opinionated on issues mentioned in #7210? @hedgerwang fixed that in facebook/react-native@3a6231432a48f49d67d24fa87dac75e8fb7ac345. Not sure if we should follow the same path for CardStack though. It would only add additional complexity to the examples and I don't think it's worth it.

**Comment by ericvicenti** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/794259024008671/int_phab) to review.

**Pull request closed without merging**
