### PR TITLE
[PermissionsAndroid] Prevent app from crashing when getCurrentActivity is null

### PR DESCRIPTION
**Pull request by cmcewen**
We're seeing a lot of crashes from `PermissionsModule` not being able to access the current activity, mentioned in #10009 and here: https://github.com/facebook/react-native/issues/9310#issuecomment-245657347

As far as I can tell, there is no way to ensure the Activity exists since the `ReactContext` holds a `WeakReference` to the current Activity and it appears that the lifecycle calls are happening in the right order (so not the same as #9310).

This will at least allow people to catch the error in JS and update the UI or try again as opposed to crashing the app.

I'm working on some bigger changes in #10221 but this is a smaller change and important to get fixed I think.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks a lot!

@facebook-github-bot shipit

**Comment by satya164** [comment]
cc @grabbou can we cherry-pick this to the stable release?

**Comment by aouaki** [comment]
Hey guys, we're seeing a lot of crashes on Android and this should fix them. Could we get this commit in the 0.36 ?

Thanks!

**Comment by grabbou** [comment]
Hey @aouaki, I've added this commit to the pending rc.2 release of 0.36 - should be up soon. You can follow the status here -> https://github.com/facebook/react-native/issues/10329

**Pull request closed without merging**
