### PR TITLE
Update new_architecture.rb for React-ImageManager

### PR DESCRIPTION
**Pull request by billnbell**
## Summary:

This added React-ImageManager to the use_frameworks! - a lot of rpm modules podspec need this.

## Changelog:

[iOS] [FIXED] - Add React-ImageManager path to work with use_frameworks!

For more details, see:
https://reactnative.dev/contributing/changelogs-in-pull-requests

## Test Plan:

Should not be breaking - it will add to the header_search_paths React-ImageManager

### CODE REVIEW

**Comment by billnbell** [comment]
I signed the CLA

**Comment by cipolleschi** [comment]
Hi there! Thanks for taking the time for doing this.
I think we have also to update the ruby tests, otherwise the CI will stay red. I think [this](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb#L123-L156) is the test that needs to be updated.

**Comment by billnbell** [comment]
> Hi there! Thanks for taking the time for doing this.
> I think we have also to update the ruby tests, otherwise the CI will stay red. I think [this](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb#L123-L156) is the test that needs to be updated.

Yeah I added that one - let's see what the tests do

**Comment by billnbell** [comment]
OK rebased.

**Comment by cipolleschi** [comment]
I don't know what's going on with the CI. Main is green, I don't understand why this branch can't build correctly... :/

**Comment by billnbell** [comment]
What do you want me to do for `/rebase` ? I am not getting it.

**Comment by billnbell** [comment]
I merged from Facebook into main and merged that and rebased into patch-2. Should be rebased.

**Comment by cipolleschi** [comment]
Cool! Now the CI is running properly!

There are some ruby tests failures, which are expected! 

You can run ruby tests locally on your machines:
1. navigate to: `react-native/packages/react-native/scripts`
2. run `./run_ruby_tests.sh`

This will highlights the failures locally and you should be able to fix the tests and update the PR! ;) 

Thanks again for taking the time to work on this!

**Comment by billnbell** [comment]
ok fixed those 2.

**Review by billnbell — COMMENTED** [review]
ok good

**Pull request closed without merging**
