### PR TITLE
Fix for "Unable to resolve module nullthrows".

### PR DESCRIPTION
**Pull request by jgibbons**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @sahrens and @gabelevi to be potential reviewers.

**Comment by javache** [comment]
@davidaurelio wouldn't the invariant in this file also need to be scoped to fbjs?

**Comment by davidaurelio** [comment]
Yes, that's necessary

**Comment by jgibbons** [comment]
Invariant works fine as is as shown in 
https://rnplay.org/apps/OKDyIQ.

However, I've made the change for consistency.

**Comment by facebook-github-bot-6** [comment]
@jgibbons updated the pull request.

**Comment by jgibbons** [comment]
Any chance this can be merged @davidaurelio?

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/999147503507841/int_phab) to review.

**Comment by satya164** [comment]
There are conflicts with master. You need to rebase @jgibbons

**Comment by satya164** [comment]
@jgibbons The PR seems to contain lots of unrelated commits now.

**Comment by jgibbons** [comment]
Sorry @satya164. I messed up the rebase.

**Pull request closed without merging**
