### PR TITLE
Reverts "Timing: Fixes timer when app get into background (#24649)"

### PR DESCRIPTION
**Pull request by radko93**
## Summary
This PR reverts commit https://github.com/facebook/react-native/commit/338298417f8077dee177057c57b38671b4ec8c75 that is causing #26696 #26995.
> app would be closed immediately after going to background on iOS 13.1/13.2 and was investigated by @minhtc https://github.com/facebook/react-native/issues/26696#issuecomment-548056694. The commit that is being reverted is apparently causing the app to be closed immediately. This has to be reverted in master separately as the file differs there.

Similar PR for 0.61. branch https://github.com/facebook/react-native/pull/27065

## Changelog

[iOS] [Fixed] - Fix apps crashing on iOS 13.x when running timer in the background

## Test Plan

Try [this](https://github.com/facebook/react-native/commit/338298417f8077dee177057c57b38671b4ec8c75#commitcomment-35745287) snippet on iOS 13.1/13.2, the app should not crash anymore

### CODE REVIEW

**Comment by cpojer** [comment]
Duplicate of https://github.com/facebook/react-native/pull/27065

**Comment by grabbou** [comment]
Not really. The #27065 is towards a 0.61-stable branch (so we can have easier time cherry-picking). Here, it's something that should be imported if we revert from master.

**Comment by cpojer** [comment]
Thanks for the explanation, I didn't realize they were meant for different branches, my mistake.

**Comment by cristianoccazinsp** [comment]
Sorry to bring this up, does this bug only affect RN 0.61? I'm seeing lots of strange "no background task exists with identifier ..." logs with RN 0.60 and iOS 13.x. These logs were not here before. I wonder if these background timers have anything to do with it.

**Comment by craftzdog** [comment]
Hi, I'm from https://github.com/facebook/react-native/issues/25083.
@zhongwuzw I upgraded my RN project and found that the patch got reverted. Now, how do you let JS keep running for a few seconds in background on iOS? Thanks!

**Pull request closed without merging**
