### PR TITLE
Add Navigator option to keep a transitioning-out view in place. 

### PR DESCRIPTION
**Pull request by seansfkelley**
See #4494.

Based on https://github.com/facebook/react-native/issues/4494#issuecomment-220029136, which is itself taking a suggestion from https://github.com/facebook/react-native/issues/4494#issuecomment-164065386.

This commit doesn't change any of the scene configs, so any visible views in the background will still undergo their scaling/transform/opacity transitions.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @hedgerwang to be potential reviewers.

**Comment by seansfkelley** [comment]
Github currently seems a little confused; it thinks the head of my source branch is 73ade1ce48a0353a2b796f24e935da36fff466f5 but I amend-force-pushed (cleaning up a clerical mistake -- left a constant out) and it _should_ now show as bbfcda543589d971a746d5e041da221f988027da (which it does on the command line, including for a fresh checkout). Gonna let this sit for a while and see if Github catches up, otherwise reopen it with a new branch.

**Comment by facebook-github-bot-9** [comment]
@seansfkelley updated the pull request.

**Comment by seansfkelley** [comment]
@janicduplessis @hedgerwang thoughts?

**Comment by facebook-github-bot-7** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @janicduplessis as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by zicjin** [comment]
I implemented the CustomComponents/Navigation/Navigator.js code, first execution navigator.push ({component:A... sceneOptions: {retainPreviousView: true} ...}), and then executed navigator.replace ({component:B... sceneOptions: {retainPreviousView: false} .. .}), the view does not correctly display no transparency.

**Comment by satya164** [comment]
@seansfkelley Hey. Can you rebase it with master please?

**Comment by facebook-github-bot-9** [comment]
@seansfkelley updated the pull request.

**Comment by satya164** [comment]
Seems tests are failing due code analysis bot. Any idea @bestander ?

**Comment by bestander** [comment]
Yeah, that bot script fails sometimes, I have a task to look into it.
For now, it is ok to ignore this issue.
Thanks for cc-in me

**Comment by facebook-github-bot-7** [comment]
@seansfkelley I tried to find reviewers for this pull request and wanted to ping them to take another look. However, based on the blame information for the files in this pull request I couldn't find any reviewers. This sometimes happens when the files in the pull request are new or don't exist on master anymore. Is this pull request still relevant? If yes could you please rebase? In case you know who has context on this code feel free to mention them in a comment (one person is fine). Thanks for reading and hope you will continue contributing to the project.

**Comment by facebook-github-bot-8** [comment]
@seansfkelley updated the pull request - [view changes](https://github.com/facebook/react-native/pull/7682/files/9db42927e95673135178ff5ab7da2f7186e9b848..12fa17294fb69dbd2852caaf442de54c4b872b74)

**Comment by ericvicenti** [comment]
This looks reasonable. I think there may be some edge cases depending on exactly what transition is happening, but I can see the value to have this and I doubt it will break anything.

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
This needs a rebase BTW

**Comment by seansfkelley** [comment]
I don't use react-native anymore and don't have the environment set up to merge this and confirm that it still works as intended. It's only one actual commit (and three merges); if any of the thumb-uppers want to take it over that's fine with me.

**Comment by ericvicenti** [comment]
Ok, if somebody needs this, feel free to rebase and re-submit!

**Pull request closed without merging**
