### PR TITLE
Update connect dependency

### PR DESCRIPTION
**Pull request by bradmsmith**
connect@2.30.2 has a dependency with a security vulnerability

```
$nsp check
(+) 1 vulnerabilities found
┌───────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                                                                            │
├───────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ negotiator                                                                                                                                      │
├───────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.5.3                                                                                                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <= 0.6.0                                                                                                                                        │
├───────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ >= 0.6.1                                                                                                                                        │
├───────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │ react-native@1000.0.0 > connect@2.30.2 > compression@1.5.2 > accepts@1.2.13 > negotiator@0.5.3                                                  │
├───────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/106                                                                                                          │
└───────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
Only change is bumping up the version. `npm test` passes

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @davidaurelio to be potential reviewers.

**Comment by javache** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing.

**Comment by bestander** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3662813) to review internal test results.

**Comment by bestander** [comment]
@bradmsmith, the e2e tests are failing.
Could it be related to connect update?

**Comment by ide** [comment]
Updating the major semver version of a dependency often doesn't work -- please test and fix up the call sites as needed. Also a DoS isn't really a problem since this server runs on localhost and usually behind a NAT.

**Comment by bestander** [comment]
I'll close this for now, feel free to reopen.

**Pull request closed without merging**
