### PR TITLE
Update Gradle wrapper to 5.6.1

### PR DESCRIPTION
**Pull request by sunnylqm**
## Summary
Encountered [an issue with gradle wrapper 5.6](https://github.com/gradle/gradle/issues/10347), which was fixed in 5.6.1

## Changelog

[Android] [Changed] - Gradle wrapper 5.6.1

## Test Plan: 
Ran build and tests locally.

### CODE REVIEW

**Comment by osdnk** [comment]
Let's try!

**Comment by dulmandakh** [comment]
@osdnk please merge 👍

**Comment by osdnk** [comment]
I cannot do it unless I receive an approve on Phabricator cc @gengjiawen

**Comment by mdvacca** [comment]
trying again...

**Comment by osdnk** [comment]
I have some problems landing this PR re-trying

**Comment by dulmandakh** [comment]
Closing this because of https://github.com/facebook/react-native/pull/26349

**Pull request closed without merging**
