### PR TITLE
Revert PR-7825 snapshot changes

### PR DESCRIPTION
**Pull request by bestander**
Tests got broken after https://github.com/facebook/react-native/pull/7825, reverting changes

Test Plan:
./scritps/objc-test.sh

### CODE REVIEW

**Comment by bestander** [comment]
Locally tests are passing, merging now

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @feichngr to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1726564130928244/int_phab) to review.

**Pull request closed without merging**
