### PR TITLE
Correctly handle the case where HEADER_SEARCH_PATHS is a single string

### LINKED ISSUE #12959: `react-native link` corrupts `project.pbxproj` file
### Description

Starting from a working project, recently upgraded to React Native 0.42.0. Following the instructions at https://developers.facebook.com/docs/react-native/getting-started

```
$ react-native install react-native-fbsdk
Scanning 646 folders for symlinks in /Users/dylan/dev/cala/ios/node_modules (6ms)
calaRN@1.2.68 /Users/dylan/dev/cala/ios
└── react-native-fbsdk@0.5.0

Scanning 647 folders for symlinks in /Users/dylan/dev/cala/ios/node_modules (5ms)
rnpm-install info Linking react-native-fbsdk ios dependency
rnpm-install info iOS module react-native-fbsdk has been successfully linked
rnpm-install info Module react-native-fbsdk has been successfully installed & linked
```

```
$ react-native link react-native-fbsdk
Scanning 647 folders for symlinks in /Users/dylan/dev/cala/ios/node_modules (6ms)
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/*" or ";" but "\"" found.
```

```
$ open ios/calaRN.xcodeproj
```

```
$ git diff ios/calaRN.xcodeproj/project.pbxproj
```
https://gist.github.com/dylanpyle/144e98578227c72287a119d386fb1bee

### Reproduction

Can provide access to the project in question to the React Native team if needed; [email me](mailto:d@ca.la).

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Operating System: macOS 10.12.3
* Dev tools: XCode 8.2.1

### PR DESCRIPTION
**Pull request by dylanpyle**
Fixes #12959

Would love some feedback on the test plan here. Modifying `project.pbxproj`
means that there's no test coverage for the (much more common) case where it's
actually an array. It might sense to add a new `pbxproj` fixture, but that's a
huge amount of overhead for such a small change.

**Test plan (required)**

```
$ $(npm bin)/jest local-cli/link/__tests__/ios/mapHeaderSearchPaths.spec.js
 PASS  local-cli/link/__tests__/ios/mapHeaderSearchPaths.spec.js
  ios::mapHeaderSearchPaths
    ✓ should be called twice (71ms)
    ✓ calls the function with an array of paths, given a project with one (37ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.356s
```

Tested, and passing, both with and without the `pbxproj` change in this PR.

### CODE REVIEW

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Comment by Kureev** [comment]
Great job, @dylanpyle! Thanks for your contribution!

**Comment by dylanpyle** [comment]
@Kureev I'm not familiar with the React Native release process — anything more I need to do here, or is this waiting on a FB team member to merge? Looking forward to using the fix in my app ☺️

**Comment by Kureev** [comment]
Can someone take a look? cc @bestander @mkonicek

**Comment by hramos** [comment]
Apologies, looks like the bot did not pick up the shipit command way back then. I'll take a look at importing this tomorrow.

**Comment by Kureev** [comment]
Thanks, @hramos! 🙌  Should I re-ship it?

**Comment by hramos** [comment]
This is already in master (had to manually land it internally).

**Pull request closed without merging**
