### PR TITLE
Adds Immerse to Showcase

### PR DESCRIPTION
**Pull request by markthom-as**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

Adds Immerse to showcase - a React Native WebRTC app for daily language practice.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
A big overhaul to the showcase page is happening with https://github.com/facebook/react-native/pull/8263/ --- so I want to land that first and then this will have to be rebased on top of that.

**Comment by JoelMarcey** [comment]
cc @lacker

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by lacker** [comment]
Verbling seems like a good showcase candidate. We need a link to some sort of useful news or something though. Maybe just https://www.crunchbase.com/organization/verbling#/entity - did you guys do any PR around the launch of Immerse?

**Comment by JoelMarcey** [comment]
@markthom-as #8263 has landed. So this pull request can be rebased and updated on top of that.

**Comment by facebook-github-bot-9** [comment]
@markthom-as do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by mkonicek** [comment]
@markthom-as I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment asks a question. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to add Immerse to the showcase.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (70/60 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:42644)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJVe-003LGn-FR
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:58:16 +0000
Received: from o6.sgmail.github.com ([192.254.113.101])
	by filter03.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES128-SHA:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJVa-0000FM-Pk
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:58:14 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=LWM+5b88Kq6joxyPA4uJPpsY3+k=; b=Z42Jdr1R6Pf/Xa+B
	drSgBvXlbUynaHufv0wRCKFOhtLDzhGK1vk4O8gwmiF0HGryZJ5M5fscBPEEzZt6
	gpGBKIdHCP03zDKk2E52B6kkN4Z3Y4v9mfQ4iusqVJB9jaYpCMy5JQHKYT83k6bd
	OaUmllMPKECiAUPu3uiLQXLWBMs=
Received: by filter0993p1mdw1.sendgrid.net with SMTP id filter0993p1mdw1.10052.57D295C1E
        2016-09-09 10:58:09.109071843 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id tK9ggrcdSkSonijO70xBkQ
	for <bunny@thumbmunkeys.com>; Fri, 09 Sep 2016 10:58:08.980 +0000 (UTC)
Date: Fri, 09 Sep 2016 03:58:08 -0700

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (71/60 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:42648)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJVk-003LIa-2v
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 10:58:25 +0000
Received: from o5.sgmail.github.com ([192.254.113.10])
	by filter03.reliabledns.org with esmtps (TLSv1.2:DHE-RSA-AES128-SHA:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-d0c9-bunny=thumbmunkeys.com@sgmail.github.com>)
	id 1biJVi-0000Fu-RN
	for bunny@thumbmunkeys.com; Fri, 09 Sep 2016 03:58:20 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=adn9+nFqAV/B0hubtOdttfoi6TY=; b=a5VTTvU9kHpLa6Ow
	zTryjtmyxy1u/Bn59en3Rp3SpvirURy1NY5t8q6rVkhuba5Q2ATSlSnVQ9yuPoq2
	T1d9BeHSh/gYpidWQ3ADNZYVmZ3oGpq11zmHFFHm6gT28cEdK2oC1fei1WiWXnkz
	YE2T/AJcXWqi3DJ/0JlX5p0bNPo=
Received: by filter0977p1mdw1.sendgrid.net with SMTP id filter0977p1mdw1.10927.57D295CA11
        2016-09-09 10:58:18.310916519 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id GLTtikFeTHOO7emAfOxOHQ
	for <bunny@thumbmunkeys.com>; Fri, 09 Sep 2016 10:58:18.328 +0000 (UTC)
Date: Fri, 09 Sep 2016 03:58:18 -0700

**Pull request closed without merging**
