### PR TITLE
[packager] add breaking test for resolving un-dedupeable dependencies

### PR DESCRIPTION
**Pull request by mvayngrib**
the same module may exist in the dependency tree with different versions

### CODE REVIEW

**Comment by satya164** [comment]
cc @martinbigio

**Comment by martinbigio** [comment]
Thanks a lot for adding this!. I'm not sure if this feature actually works though (i.e.: does the module ID used on the `__d` for the two `bPackage` dependencies might be the same and therefore the last definition will win and you'll actually end up with a single actual version which could lead to all sort of weird issues due to versioning issues.

@davidaurelio is working on using numerical indexes instead of string indexes which will solve this problem. I'm not sure if it worth merging this considering David is refactoring this at the moment.

**Comment by mvayngrib** [comment]
@martinbigio sorry, didn't actually implement anything, just added a breaking test

**Comment by martinbigio** [comment]
@mvayngrib no problem!. We'll support this very soon :)

**Comment by mkonicek** [comment]
@martinbigio Any updates. @mvayngrib We can't merge this PR as-is if it only adds a breaking test :)

I'm going through all PRs making sure they are either being actively worked on or closed, to keep the number of open PRs under control.

**Comment by davidaurelio** [comment]
Numerical IDs are in and will go in v0.23, this shouldn’t be an issue any longer (06b5bda34923b68ba5141e78c36ccbdc5f4bcff1)

**Comment by mkonicek** [comment]
Thanks for looking David! I'll close this PR based on your comment.

Thanks for the contribution @mvayngrib and sorry about the churn. Hope you'll continue contributing to React Native.

**Comment by mvayngrib** [comment]
@mkonicek no problem, and I'll definitely be contributing more :)

**Pull request closed without merging**
