### PR TITLE
[Website] Add footer

### PR DESCRIPTION
**Pull request by hramos**
Add footer to all pages in the website.

Preview:
screencapture-localhost-8079-react-native-docs-network-html-1474655915887

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @Andreyco and @JoelMarcey to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
@hramos updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10075/files/3825389b1425b47269ebedde30464cd90adf9157..f4cafadcae19227fb48e74f7b69727dcd4dd6865)

**Comment by facebook-github-bot-2** [comment]
@hramos updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10075/files/f4cafadcae19227fb48e74f7b69727dcd4dd6865..7a46e07236936318a7786ae8021d85105c1b4b25)

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3917827).

**Pull request closed without merging**
