### PR TITLE
suggest yarn

### PR DESCRIPTION
**Pull request by GantMan**
simple suggested edit to the blog.

### CODE REVIEW

**Comment by mkonicek** [comment]
I like this but maybe we could add a separate note about yarn somewhere further in the blogpost to keep the Getting started instructions as simple as possible and ready-to-copy-paste? No strong opinion though.

@ncuillery I'll leave it up to you to decide :)

**Comment by ncuillery** [comment]
I'm not sure, it doesn't look great, the line is too long and the syntax highlighting doesn't recognize the comment:
capture d ecran 2016-12-05 a 22 50 04


@mkonicek @GantMan How about
capture d ecran 2016-12-05 a 22 59 40


Source:
<pre>
Install `react-native-git-upgrade` globally:

```bash
$ npm install -g react-native-git-upgrade
```
or, using [Yarn](https://yarnpkg.com/):

```bash
$ yarn add global react-native-git-upgrade
```

Then, run it inside your project directory:

```bash
$ cd MyProject
$ react-native-git-upgrade 0.38.0
```
</pre>

**Comment by GantMan** [comment]
I like it.  It gives easy copy and paste!

**Comment by GantMan** [comment]
I'll close this PR in favor of the above method.

**Pull request closed without merging**
