### PR TITLE
Update error message on unrecognized commands

### PR DESCRIPTION
**Pull request by lacker**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Kevin: This isn't quite a typo, but it's a change to an error message.

In my experience, frequently when this error message is displayed, the command is unrecognized because I haven't run npm install, I just checked out a repo of someone else's. We could just update this error message a bit, and I think it would improve the developer experience.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @bestander and @mkonicek to be potential reviewers.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
@lacker updated the pull request.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1796292257261341/int_phab) to review.

**Pull request closed without merging**
