### PR TITLE
Add a default case to `Platform.select`

### PR DESCRIPTION
**Pull request by satya164**
You could then do this,

```js
Platform.select({
  android: require('./AndroidSpecificImpl'),
  default: require('./GenericImpl'),
})
```

It'll be useful since we've more platforms now, e.g. - windows

### CODE REVIEW

**Comment by ide** [comment]
IIRC there is also a Babel transform that statically rewrites Platform.select calls so they are inlined -- that plugin might need to be updated too. Not totally sure who knows about this plugin, maybe @davidaurelio?

**Comment by ericvicenti** [comment]
Found it: https://github.com/facebook/react-native/blob/c5f6e864f928e7145a94f85224f0e8c43701db78/packager/react-packager/src/JSTransformer/worker/inline.js#L80

And yep it certainly seems owned by @davidaurelio

**Comment by satya164** [comment]
Thanks @ericvicenti. I don't understand the code yet, but if someone could point me in the right direction I can update it.

**Comment by ericvicenti** [comment]
I think it inlines things so that the require statements of other platforms go away. I think it will convert this:

```
Platform.select({ ios: require('Foo'), android: require('Bar') });
```
To this on Android:

```
Platform.select({ ios: android, android: require('Bar') });
```

It is probably easiest to observe what it does and simply make sure it still behaves well after your change.

**Comment by davidaurelio** [comment]
The transform removes the complete `Platform.select` call and replaces it with the value of that property.

The algo goes like this:

1. Bail out if the argument to `Platform.select` is [not an object literal](https://github.com/facebook/react-native/blob/c5f6e864f928e7145a94f85224f0e8c43701db78/packager/react-packager/src/JSTransformer/worker/inline.js#L138).
2. Replace the call with the [property value for `platform`, if present](https://github.com/facebook/react-native/blob/c5f6e864f928e7145a94f85224f0e8c43701db78/packager/react-packager/src/JSTransformer/worker/inline.js#L101).
3. Replace the call with `undefined`

You could add the functionality by changing the signature of `findProperty` to `findProperty(objExpression, key, fallback)`, where fallback is a function, and [call it here](https://github.com/facebook/react-native/blob/c5f6e864f928e7145a94f85224f0e8c43701db78/packager/react-packager/src/JSTransformer/worker/inline.js#L137) as `findProperty(arg, opts.platform, () => findProperty(arg, 'default', () => t.identifier('undefined')))`

**Comment by davidaurelio** [comment]
tests live here, make sure to add some: https://github.com/facebook/react-native/blob/c5f6e864f928e7145a94f85224f0e8c43701db78/packager/react-packager/src/JSTransformer/worker/__tests__/inline-test.js

**Comment by satya164** [comment]
Thanks a lot for the explanation @davidaurelio . Will fix it as soon as I can.

**Comment by mkonicek** [comment]
I like the idea and ran into this too that I needed a `default`. Once the transform supports this too happy to merge it 👍

**Comment by satya164** [comment]
Sorry haven't gotten time to look at it. I'll take a look over the weekend.

**Pull request closed without merging**
