### PR TITLE
Navigator.SceneConfigs.PushFromRight similar to native iOS animation.

### PR DESCRIPTION
**Pull request by neciu**
The animation looks ok now.

However, the original iOS navigator adds transparent overlay and shadow. Any idea how to implement it? I'd like to add it.

### CODE REVIEW

**Comment by mkonicek** [comment]
Hey @neciu, note that the Navigator is getting deprecated in favor of NavigationExperimental.

Do you still plan to work on this? If yes, can you rebase and add a video showing what this PR does (before / after)?

**Comment by facebook-github-bot-8** [comment]
@ericvicenti would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by neciu** [comment]
@mkonicek the gifs:

before:
118fhs

after:
118fi6

**Comment by mkonicek** [comment]
I'll let @ericvicenti review.

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
(Flaky CI)

**Comment by hufeng** [comment]
really nice. waiting release....

**Pull request closed without merging**
