### PR TITLE
Set viewTag for RCTTouchEvent to avoid EventID conflict

### PR DESCRIPTION
**Pull request by littlesome**
Using target view's reactTag as viewTag for RCTTouchEvent.

Fix issue https://github.com/facebook/react-native/issues/9503

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @majak and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
@littlesome updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9952/files/31209967e3368ea685c21ee98a5bc24334b1bd59..620e2161eb5f809fa4c6f8faffe997625328e34e)

**Comment by majak** [comment]
Nice find!
Could you please split off the "add a way to disable touch handler for a RCTRootView" part as a separate PR?

It's a separate part and may warrant further discussion (it's not clear to me what purpose it should serve and whether it achieves it).

**Comment by facebook-github-bot-6** [comment]
@littlesome updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9952/files/5658c8f0fe8b84b2454713d0dfe8d434fe4ba2cc..620e2161eb5f809fa4c6f8faffe997625328e34e)

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by littlesome** [comment]
@majak  Hi, thanks for review. I'm new to use git, am I doing right?

**Comment by majak** [comment]
@littlesome I think this looks ok :) 
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3880152) to review internal test results.

**Pull request closed without merging**
