### PR TITLE
Add renderAsOriginal to selectedIcon

### PR DESCRIPTION
**Pull request by urbancvek**
Hey,
I've created a PR a few weeks ago #7264. It got merged in and then I received some emails and got mentioned in a few issues that it doesn't use renderAsOriginal prop on selectedIcon. Instead the app would use tint color. 

The problem can be seen here #7467.

I've now added a method in TabBarItem that sets selectedIcon to renderAsOriginal if the prop is set.
I added a "relay" icon to UIExplorer TabBarIOS example so you can see the item is now rendered in color as the image supplied.

Oh and also should this PR be made from master. Had to work on this issue from 0.27 because the master was broken for me.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @davidaurelio to be potential reviewers.

**Comment by janicduplessis** [comment]
Seems like your branch is in a weird state, can you remove the extra commit?

**Comment by facebook-github-bot-4** [comment]
@urbancvek updated the pull request.

**Comment by janicduplessis** [comment]
Thanks @urbancvek !

@facebook-github-bot shipit

**Pull request closed without merging**
