### PR TITLE
Doc. Update For Module Dependency Injection

### PR DESCRIPTION
**Pull request by joshyhargreaves**
Added details about how IOS Native Modules can be initialized & registered manually with custom initializers so that dependencies can be injected to said modules. 

Please let me know if there is a more appropriate place to detail this in the documentation or this is in fact detailed elsewhere; I also believe we do not have documentation on how to do the equivalent on Android, however it is a bit more obvious as the automatic MACRO registration mechanism does not exist on Android and modules need to be initialized manually anyway. As I currently understand there isn't currently any documentation detailing this apart from comments in the source. 

Please let me know if you would require any style changes (variable names etc), to be more en-keeping with the rest of the documentation.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @knowbody as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by bestander** [comment]
@majak what do you think of this?

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3843018) to review internal test results.

**Pull request closed without merging**
