### PR TITLE
Turn Flow strict mode on for Picker

### PR DESCRIPTION
**Pull request by nd-02110114**
Related to #22100

Turn Flow strict mode on for Libraries/Components/Picker/Picker.js

## Test Plan:
- [x] npm run prettier
- [ ] npm run flow-check-ios
- [ ] npm run flow-check-android
 
This error was happend #22101 #22048 

## Release Notes:
[GENERAL] [ENHANCEMENT] [Libraries/Components/Picker/Picker.js] - Flow strict mode

### CODE REVIEW

**Comment by nd-02110114** [comment]
I got this error.... How shoud i do...? 🙇 

```js
// Importing from an untyped module makes it any and is not safe! Did you mean to add @flow to the top of PickerIOS? (untyped-import)
const PickerAndroid = require('PickerAndroid');
const PickerIOS = require('PickerIOS');
```

**Comment by TheSavior** [comment]
You won't be able to turn on `flow strict-local` until those files are typed. I just wouldn't worry about switching this file over to strict-local for now and instead just leave it with `@flow`.

**Comment by TheSavior** [comment]
What happened with this PR? Did you intend to close it?

**Comment by nd-02110114** [comment]
@TheSavior 
I'm so sorry for no comment🙇 
i resubmit this PR https://github.com/facebook/react-native/pull/22128

**Comment by nd-02110114** [comment]
Deprecated #22128

**Pull request closed without merging**
