### PR TITLE
Do you mean 'transitions' not 'transactions'?

### PR DESCRIPTION
**Pull request by jessep**
Explain the **motivation** for making this change. What existing problem does the pull request solve?

Was confused by the word 'transactions' here. 'Transitions' would make more sense to me, assuming that was what was intended. If not, my bad!

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @sunnylqm and @artyomtrityak to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by artyomtrityak** [comment]
that's @sahrens call. I believe you're right

**Comment by sahrens** [comment]
Hmm, hard to say actually. The way LayoutAnimation works is by taking a batch of layout updates - a layout transaction - and animating the result. The term "transition" is more of a CSS thing, but the concept is similar...I could see "transition" being more intuitive to people, but I would worry about conflation of the concepts since they are not the same...do you guys still want to change it here?

**Comment by artyomtrityak** [comment]
@sahrens  Once you've explained it seems like it should be transaction

**Comment by rclai** [comment]
The term transaction comes from the iOS CATransaction class.

**Comment by sahrens** [comment]
That's not where the naming comes from here, but yes it is more similar to CATransaction than CSS transitions.


On Aug 31, 2016, at 12:59 PM, Richard Lai <notifications@github.com<mailto:notifications@github.com>> wrote:


The term transaction comes from the iOS CATransaction class.

**Comment by mkonicek** [comment]
Thanks for the explanation @sahrens:

>  The way LayoutAnimation works is by taking a batch of layout updates - a layout transaction - and animating the result.
> I could see "transition" being more intuitive to people, but I would worry about conflation of the concepts since they are not the same...

Let's keep transaction as it's more accurate.

Thanks for the pull request @jessep! Anytime you see anything being even slightly unclear pull requests are welcome!

**Pull request closed without merging**
