### PR TITLE
chore: remove extra require

### PR DESCRIPTION
**Pull request by maksimr**
We already have require fs [here](https://github.com/maksimr/react-native/blob/patch-cli/local-cli/cli.js#L34)

### CODE REVIEW

**Comment by martinbigio** [comment]
wouldn't this break the cli?

**Comment by maksimr** [comment]
@martinbigio how? The line 34 already has require('fs') https://github.com/maksimr/react-native/blob/patch-cli/local-cli/cli.js#L34
I think `extra require` was added by inattention

**Comment by martinbigio** [comment]
Oh sorry, I was checking on an outdated version of that file. Thanks for the PR!

**Comment by martinbigio** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
