### PR TITLE
Fixed ScrollView transition with snapToInterval

### PR DESCRIPTION
**Pull request by mmeineke**
Reproduce:
- Use a slide gesture to slide to the next slide
- During the automatic transition tap the ScrollView again without moving
- The ScrollView slides back to the previous slide

Shows the bug:
bug

Bug fixed:
bug-fixed

Used Code for this showcase:
```
import React, {
    Dimensions,
    Image,
    StyleSheet,
    ScrollView,
    Text,
    View
} from 'react-native';

let screenWidth = Dimensions.get('window').width;

let spacing = 10;
let outerSpacing = spacing * 4;
let slideWidth = screenWidth - (spacing + outerSpacing) * 2;

let styles = StyleSheet.create({
    wrapper: {
        flex: 1,
        paddingVertical: 10
    },
    carousel: {
        flex: 1,
        marginTop: 50
    },
    container: {
        alignItems: 'center',
        paddingHorizontal: outerSpacing,
        flex: 1
    },
    slide: {
        flex: 1,
        paddingBottom: 20,
        marginHorizontal: spacing,
        width: slideWidth
    },
    image: {
        height: 200
    },
    slideText: {
        textAlign: 'center',
        marginTop: 10
    }
});

let slides = [
    {image: 'http://lorempixel.com/640/480/abstract/?1', title: 'Slide 1'},
    {image: 'http://lorempixel.com/640/480/abstract/?2', title: 'Slide 2'},
    {image: 'http://lorempixel.com/640/480/abstract/?3', title: 'Slide 3'},
    {image: 'http://lorempixel.com/640/480/abstract/?4', title: 'Slide 4'},
    {image: 'http://lorempixel.com/640/480/abstract/?5', title: 'Slide 5'}
];

function CarouselDemo() {
    return (
        <ScrollView style={styles.wrapper}>
            <ScrollView
                style={styles.carousel}
                contentContainerStyle={styles.container}
                automaticallyAdjustContentInsets={false}
                showsHorizontalScrollIndicator={false}
                scrollsToTop={false}
                horizontal
                decelerationRate="fast"
                bounces={true}
                alwaysBounceHorizontal={false}
                snapToAlignment="start"
                snapToInterval={slideWidth + spacing * 2}
            >
                {slides.map((slide, i) => (
                    <View style={styles.slide} key={`slide_${i}`}>
                        <Image
                            source={{uri: slide.image}}
                            style={styles.image}
                        />
                        <Text style={styles.slideText}>{slide.title}</Text>
                    </View>
                ))}
            </ScrollView>

        </ScrollView>
    );
}

export {CarouselDemo};
```

### CODE REVIEW

**Comment by Benmidi** [comment]
I'm running up against this issue too, thanks for the PR!

**Comment by facebook-github-bot-2** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mroswald** [comment]
@nicklockwood @sahrens @tadeuzagallo can anyone please have a look?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/fixed-scrollview-transition-with-snaptointerval

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by mroswald** [comment]
@mkonicek this IS a pull request with a fix :-)

**Pull request closed without merging**
