### PR TITLE
[NavigatorIOS] Move to OSSLibraries

### LINKED ISSUE #1519: [NavigatorIOS] Move to OSSLibraries folder
In order to be able to better support community contributions and make clear that this library is not currently a priority for Facebook, the plan is to try moving this component to a separate directory that is not managed in the same way by the sync process.

1. Move `NavigatorIOS.ios.js` to new folder `OSSLibraries/NavigatorIOS/NavigatorIOS.ios.js`
2. [RCTNavigator code](https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=RCTNavigator) to that folder, and in new Xcode project

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #1519

UIExplorer runs w/o issues.

CC: @brentvatne I forgot about your later commit suggesting making `Components` folder inside `OSSLibraries`. Shall we make it then?

### CODE REVIEW

**Comment by brentvatne** [comment]
@grabbou - yeah let's make a components directory

**Comment by satya164** [comment]
Any updates on this?

**Comment by facebook-github-bot-7** [comment]
@sahrens would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by sahrens** [comment]
Does this really blame to me?  No idea if this is still relevant - @brentvatne?

**Comment by mkonicek** [comment]
Looks like we never ended up adding the `OSSLibraries` folder. Seems not high-pri, we can revisit. Closing this PR.

**Pull request closed without merging**
