### PR TITLE
Add caveat on PCH errors

### PR DESCRIPTION
**Pull request by GantMan**
Moving files that have generated PCHs causes an error that you cannot clear easily.  Here are the instructions on how.

I was prompted to place this info here via #6797

### CODE REVIEW

**Comment by grabbou** [comment]
Awesome, thanks! LGTM in general, but it will need to be reviewed by @mkonicek as he is the grammar master here 💃

**Comment by mkonicek** [comment]
What does "Moving after compile mean", and what does "Moving a React Native project" mean? Does this mean moving the whole folder, e.g. `cd /tmp; react-native init MyApp; mv MyApp ~/`?

Just from reading this documentation I can't tell. Thanks for putting the effort in adding it, please just make it a bit more specific and let's merge it.

**Comment by facebook-github-bot-6** [comment]
@GantMan updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@GantMan updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@GantMan updated the pull request.

**Comment by GantMan** [comment]
@mkonicek I made the message more expressive as you requested.  I feel it reads well, now.

I also removed the italics on `e.g.` since there was a pre-existing usage of e.g. without italics.  Please let me know if I can help any further.

**Comment by facebook-github-bot-7** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @mkonicek as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by facebook-github-bot-3** [comment]
@GantMan updated the pull request.

**Comment by GantMan** [comment]
@grabbou  - this is kinda aging a bit, was a small commit with a thumbs up from @mkonicek

**Comment by mkonicek** [comment]
This reads really nicely, thanks and apologies about the delay, I've been swamped :)

@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1067904443255747/int_phab) to review.

**Pull request closed without merging**
