### PR TITLE
DockMan app added to showcase

### PR DESCRIPTION
**Pull request by genki**

### CODE REVIEW

**Comment by satya164** [comment]
Can you please rebase your commits?

**Comment by satya164** [comment]
Also keep the list alphabatical.

**Comment by genki** [comment]
Thank you for reviewing. I have rebased commits and sorted the list alphabetically.

**Comment by satya164** [comment]
@genki Can you also squash your commits to one? Also you've the app twice in the list now. Thank you :)

**Comment by genki** [comment]
Sorry my messy pull request.
I have removed duplication and squashed commits.

**Comment by satya164** [comment]
@genki Thank you.

**Pull request merged**
