### PR TITLE
Add JS library for requesting Android M Permissions

### PR DESCRIPTION
**Pull request by cmcewen**
Explain the **motivation** for making this change. What existing problem does the pull request solve?

The Android permissions native module was open sourced recently (https://github.com/facebook/react-native/commit/b7352b46671d09471d6aa9355ea41368ea05df96) but it is currently undocumented and requires directly interfacing with the native module.

This provides a JS wrapper to make it easier to use the permissions module and documents it.

This could be cleaner if the native code used Promise blocks instead of callbacks, but I didn't want to change the native code without a thumbs up since I'm guessing this is used in one of facebook's apps. Happy to do that if it makes sense

I also tried to make the `PERMISSIONS` object a class property - it works in the actual code but not in the documentation (think it's a jsdocs problem), so decided to initialize in the constructor.

**Test plan (required)**

If the API looks good, I will change the UIExplorer example to use this.

cc @andreicoman11

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @lacker to be potential reviewers.

**Comment by charpeni** [comment]
Great job, it sounds good!

Can you add a screenshots of the documentation ?

```
$ cd website
$ npm install && npm start
go to: http://localhost:8079/react-native/index.html
```

**Comment by satya164** [comment]
Would be awesome if you could send a follow-up PR changing callbacks to promises.

**Comment by cmcewen** [comment]
screen shot 2016-08-09 at 10 39 53 am

@satya164 will do!

**Comment by facebook-github-bot-2** [comment]
@cmcewen updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@cmcewen updated the pull request.

**Comment by ekryski** [comment]
Nice work @cmcewen! Stoked to see this one land.

**Comment by facebook-github-bot-5** [comment]
@cmcewen updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@cmcewen updated the pull request.

**Comment by satya164** [comment]
LGTM.

cc @dmmiller @foghina do you think this is good to go?

**Comment by dmmiller** [comment]
Seems good to me, but I'd like @andreicoman11 to look at it since he wrote the permissions module piece.

**Comment by andreicoman11** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3716303) to review internal test results.

**Comment by cinder92** [comment]
is this available in RN 0.37?

**Pull request closed without merging**
