### PR TITLE
[Android] Add onUserLeaveHint support to ReactActivityDelegate

### PR DESCRIPTION
**Pull request by behenate**
## Summary:

**This is a resubmission of the previous PRs. We are trying to figure out why it causes crashes in some apps.**

This PR adds `onUserLeaveHint` support into the `ReactActivityDelegate`. It allows modules to receive an event every time user moves the app into the background. This is slightly different than `onPause` - it's called only when the user intentionally moves the app into the background, e.g. when receiving a call `onPause` should be called but `onUserLeaveHint` shouldn't.

This feature is especially useful for libraries implementing features like Picture in Picture (PiP), where using `onUserLeaveHint` is the [recommended way of auto-entering PiP](https://developer.android.com/develop/ui/views/picture-in-picture#:~:text=You%20might%20want%20to%20include%20logic%20that%20switches%20an%20activity%20into%20PiP%20mode%20instead%20of%20going%20into%20the%20background.%20For%20example%2C%20Google%20Maps%20switches%20to%20PiP%20mode%20if%20the%20user%20presses%20the%20home%20or%20recents%20button%20while%20the%20app%20is%20navigating.%20You%20can%20catch%20this%20case%20by%20overriding%20onUserLeaveHint()%3A) for android < 12.

## Changelog:

[ANDROID] [ADDED] - Added `onUserLeaveHint` support into `ReactActivityDelegate`

## Test Plan:

Tested in the `rn-tester` app - callbacks are correctly called on both old and new architecture.

### CODE REVIEW

**Comment by behenate** [comment]
@cortinico Any updates on the source of the crashes?

**Comment by cortinico** [comment]
> @cortinico Any updates on the source of the crashes?

I haven't had the time to test again sorry. Hopefully I should have an answer by next week

**Comment by cortinico** [comment]
@behenate do you want to get back to this? (sorry for the late reply).
If so, can I ask you to rebase?

**Comment by cortinico** [comment]
I did some investigation and there was a NPE here:

```
07-02 17:17:09.277  7756  7756 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactDelegate.onUserLeaveHint()' on a null object reference
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onUserLeaveHint(ReactActivityDelegate.java:142)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onUserLeaveHint(ReactActivity.java:119)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.Activity.performUserLeaving(Activity.java:9182)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1786)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:5458)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5438)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
07-02 17:17:09.277  7756  7756 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

I've fixed it with a null check and will attempt another land. Will keep you posted if it causes further crashes.

**Pull request closed without merging**
