### PR TITLE
Adds dropdown for choosing docs version

### PR DESCRIPTION
**Pull request by samuelkraft**
This commit simplifies choosing a version of the docs by adding a dropdown/select in the main nav.

See gif below:
dropdown

### CODE REVIEW

**Comment by bestander** [comment]
@samuelkraft that is very cool, and the design looks cohesive with the rest of the website.
I like that you you have left untouched the click behavior that leads to a static page.
That should be good for accessibility.

Before accepting this I need to clear a few things so that we don't break someone's experience.

1. How does it work on touch devices?
`a:hover` menu is a bitch to make work on different android, ios and windows tablets, at least it was for me.
Can you test on those?
If you deploy this somewhere I can help with testing because I have a few on my desk and at home.

2. We cut a branch every 2 weeks.
Let's assume we decide to do it every 1 week.
So in a year the dropdown will have 20-50 entries which is not good for such a control.
It would be better to show only top 2-3 versions.

3. Because the element has a hover behavior now, users may not guess that it is also clickable and leads to the page with all the versions.
Any ideas how to improve that?

@vjeux what do you think?

**Comment by samuelkraft** [comment]
@bestander

1. On iOS the menu will show on first tap - and then if you tap again it follows the link. I'm actually not sure about android/windows tablets, that's why I kept the regular click behaviour. Worst case you get sent to the /versions page. If the dropdown is buggy on touch we could disable it there instead.
Another solution is only showing the menu on click, but I like having the regular link as you said. 

2. Good point. If we were to only show 2 or 3 links your third point is important so that users understand older versions are available. I think adding a "show older versions" link in the bottom linking to /versions could be a good solution.

**Comment by vjeux** [comment]
One thing to keep in mind is that we don't regenerate old documentations when a new one is released, so if you are on 0.15 you wouldn't see 0.20 (current) in your list.

Also, I really want to use 0.xx versions here instead of "master", "current", "next" which are confusing labels.

**Comment by bestander** [comment]
@vjeux has a good point.
This dropdown is not transient and hardcodes the versions at the time of builds

**Comment by samuelkraft** [comment]
Yes, 0.xx is a lot easier to understand than the labels. I don't think "(current)" is needed in this list either as the current selected doc is visible in the link. I am not entirely sure how generating the docs works, the logic for fetching versions was basically taken from the /versions page.

Please let me know what you think needs to be done @vjeux

**Comment by vjeux** [comment]
One way to solve the versioning problem is to have the master build generate a js file with the list of all the versions and store it in a js file in an absolute path (not versioned). Then, all the versioned implementations would just load that absolute js file that implements the dropdown and knows all the versions.

Probably going to have to do raw dom manipulation as we don't really want to load up react as it is a static website.

Does it make sense?

**Comment by bestander** [comment]
Agree with @vjeux, we should keep this site lean, without much JS needed during runtime.
The React components are all converted to static HTML during build and deployment.

So to give you some scope.
Every release is deployed to a new folder in gh-pages: `https://github.com/facebook/react-native/tree/gh-pages/releases`
Every time a new docs release is done (when `master` or `xx-stable` branch is built) a file versions.html that lists all folders in `https://github.com/facebook/react-native/tree/gh-pages/releases` is generated and put to `https://github.com/facebook/react-native/blob/gh-pages/versions.html`.

This way /react-native/versions.html link always contains up-to-date list of versions.

**Comment by samuelkraft** [comment]
Thanks @vjeux . I'm not sure if I know how to implement this though. I'll gladly accept any help if someone sees this :)

**Comment by bestander** [comment]
@samuelkraft yeah, this task requires a lot of things to consider.
Forwards compatibility, for example, would be a must because all the gh-pages website versions will be stored "forever" (as long as they are needed for users).

Maybe every release could generate and overwrite a .json file that describes all the available docs versions. 
Then we would only need to worry about forwards compatibility for the data structure rather than the whole JS dropdown widget.

It would be great if you want to push this feature through but honestly it feels more like a cosmetic change, so I would understand if you did not want to get invested too much into this process :)

If anyone wants to charge through - let's keep the PR.
Otherwise let's close it and reopen when there is a need and a way to make it.

**Comment by samuelkraft** [comment]
Yeah, it was more things to consider than I thought :) I'll leave this PR open for now. Thanks anyway @bestander

**Comment by bestander** [comment]
@samuelkraft, keep this PR if you intend to keep going, we would appreciate this.
But close it if you are stuck, be mindful, we have 200 PRs open and PRs in a non progressing state do more harm than good.

**Pull request closed without merging**
