### PR TITLE
Disable react-in-jsx-scope rule in eslint config

### PR DESCRIPTION
**Pull request by matinzd**
## Summary:

All newly generated react native apps are still showing warnings to use react in the jsx scope. That is not needed anymore as of react 18 with built-in jsx transform plugin.

Reproduction: https://github.com/matinzd/react-in-jsx-warning-repro

Run `npm run lint` in this repo.

## Changelog:

[GENERAL] [FIXED] - Disable `react-in-jsx-scope` rule in eslint config

## Test Plan:

Initiate a new template with community CLI and you should not see this warning anymore.

### CODE REVIEW

**Comment by matinzd** [comment]
@cortinico ?

**Comment by cortinico** [comment]
Sorry for the delay.

> All newly generated react native apps are still showing warnings to use react in the jsx scope.

Which warnings are you referring to @matinzd ? I haven't seen any warning related to what you're mentioning recently 🤔

**Comment by matinzd** [comment]
Eslint will warn about importing react everywhere when you create a new react native project that is dependent on this config.

**Comment by sunnylqm** [comment]
@cortinico 


QQ20241214-171616

**Comment by matinzd** [comment]
This is ready. @cipolleschi @cortinico

**Pull request closed without merging**
