### PR TITLE
added expr function to interpolator. currently limited to only linear interpolation

### PR DESCRIPTION
**Pull request by clozr**
Currently quadratic, inverse interpolation etc. cannot be supported by Interpolator. This small change would allow custom interpolator expression.

### CODE REVIEW

**Comment by janicduplessis** [comment]
Can you just use the easing function to do that?

**Comment by clozr** [comment]
Interpolation is meant to define various relationship between your animation variables.
Easing defines the speed/timing of these changes. Once it drives the value of primary variables based on the easing curve. All other dependent variables are supposed to be derived from animation.  This simple change can in fact makes interpolation very powerful. 
For example, if we want to implement a case where you have 'full screen' cards shrunk down and shown as slider at bottom and you want to be able to pan to zoom to 'full screen', you can't achieve that with current interpolation. You could may be approximate that using the piecewise linear interpolation but again it's just a hack. Here is the animation with linear interpolation:

[https://github.com/paramaggarwal/rn-paper-interface/blob/master/static/demo.gif](url)

You can see that zoom overshoots a little bit and then pulls back.
Following spec gives you the perfect animation where it will just smoothly zoom without any pullback.

`getListViewStyle() {
    let {width, height} = Dimensions.get('window');
    let [halfWidth, halfHeight] = [width/2, height/2];
    return [
      styles.listContainer,
      {
        width: this.state.dockAnimation.interpolate({
          expr: v => v*width,
          }),
      },
      {
        transform: [
          {
            scale: this.state.dockAnimation.interpolate({
              expr: v => 1/v
            }),
          },
          {
            translateX: this.state.dockAnimation.interpolate({
              expr: v => -halfWidth*v*(v-1)
            }),
          },
          {
            translateY: this.state.dockAnimation.interpolate({
              expr: v => halfHeight*(v-1)
            }),
          }
        ],
      }
    ];
  }`

**Comment by lelandrichardson** [comment]
@clozr that's a pretty neat demo!

I once put up a PR for something kind of similar to this, though it would allow multiple animated values to be combined in an arbitrary expression: https://github.com/facebook/react-native/pull/2045

The main take-away is that an arbitrary expression like this is hard to serialize (unless we just sample across 0 -> 1 as an easing function and linearly interpolate from there.

I think there is a better way to do this where we can keep everything serializable (and thus allow for these animations to be offloaded to the native main thread), and it should already be possible!

I'm not sure if I 100% understand your pasted code, but I had a quick go....

the code you pasted worked like this:

```js
function getListViewStyle() { 
  let {width, height} = Dimensions.get('window'); 
  let [halfWidth, halfHeight] = [width/2, height/2]; 
  let width = this.state.dockAnimation.interpolate({ expr: v => v*width, });
  let scale = this.state.dockAnimation.interpolate({ expr: v => 1/v })
  let translateX = this.state.dockAnimation.interpolate({ expr: v => -halfWidth*v*(v-1) });
  let translateY = this.state.dockAnimation.interpolate({ expr: v => halfHeight*(v-1) });
  return [ 
    styles.listContainer, 
    {
      width,
      transform: [ 
        { scale }, 
        { translateX }, 
        { translateY },
      ],
    },
  ]; 
}
```

I believe the same effect could be created using the built-in arithmetic operators into animated:

```js
let { multiply, add, division } = Animated;

function getListViewStyle() { 
  let {width, height} = Dimensions.get('window'); 
  let [halfWidth, halfHeight] = [width/2, height/2];
  let v = this.state.dockAnimation;
  let width = multiply(width, v);
  let scale = division(1, v);
  let translateX = multiply(multiply(add(v, -1), v), -halfWidth);
  let translateY = multiply(multiply(add(v, -1), v), halfHeight);
  return [ 
    styles.listContainer, 
    {
      width,
      transform: [ 
        { scale }, 
        { translateX }, 
        { translateY },
      ],
    },
  ]; 
}
```

Can you give this a try?  Let me know if you run into any trouble or if I'm not understanding correctly.

**Comment by clozr** [comment]
@lelandrichardson 
First of all your rewrite works. Second #2045 is excellent pull request, and this one is exactly that although in a hacky way. Yours `Animated.Formula` is more elegant 👍 . 

Reading through #2045, main problem seems to be serialization to objective C for native animation. But I think we can use [DDMathParser](https://github.com/davedelong/DDMathParser/wiki/Usage) or something similar for that. It is extremely limiting to just have multiply, divide, modulo and work everything out using them. How would you get constrained circular motion which requires sin or cosine and many atypical animation situation?

**Comment by ide** [comment]
I also don't think it's unreasonable to say that if you want native UI thread animations you should use the native operators. Prototype with the JS expressions and later optimize by modeling your animations with the native operators if possible & desired.

**Comment by lelandrichardson** [comment]
@clozr i'd be very interested in a solution that involved DDMathParser and something similar for android + JS.  If you want to try putting something like that together, i think it'd be a very compelling addition to the animated library.

**Comment by janicduplessis** [comment]
I think the ideal solution would be to have some math formula DSL (like DDMathParser) that would work for ios, android and js. It should be implemented like css-layout so we can compile it to C or JS.

**Comment by hramos** [comment]
What's the consensus here? Should we land this?

**Comment by clozr** [comment]
I think we should allow some flexibility in the javascript based animation. If we can't serialize the expression to native world, we fallback to javascript base animation. Long term we need an expression compiler/evaluator so that native and javascript both can use the same syntax.

I searched for some unified math expression framework but couldn't find one which would work on all of the supported( Java/Javascript/Objective C++ ) languages.

In the meantime, WE SHOULD GIVE THE JAVASCRIPT BASED FLEXIBILITY to developers so that they don't feel restricted.

**Comment by janicduplessis** [comment]
@clozr @hramos I'm fine with landing this and then we can deprecate it if / when we come up with a better solution.

**Comment by ide** [comment]
some bikeshedding - how about `expression` instead of `expr`?

**Comment by janicduplessis** [comment]
Agree with `expr` -> `expression`.

**Comment by clozr** [comment]
sure! I will update the PR.

**Comment by lelandrichardson** [comment]
@janicduplessis @clozr @ide  How do we feel about landing a rebased version of https://github.com/facebook/react-native/pull/2045 instead?

I feel like it is more in line with the current API of animated and the graph concept.

With that said, I do think that using some string-based expression parser might be an even better approach.

**Comment by clozr** [comment]
Some C++ based parser:

https://github.com/beltoforion/muparser
https://www.gnu.org/software/libmatheval/manual/libmatheval.html
https://github.com/tartakynov/mathpresso

**Comment by mkonicek** [comment]
@ide, @lelandrichardson Are you happy with this now? If yes shipit 👍 

Is this going to work with native Animated?

**Comment by ide** [comment]
I looked at #2045, which gives you a similar feature (write any interpolation function) but it's implemented as a node. I prefer the node API but I'm not sure if there are useful things you can do with this API that you can't do with the node one. After we pick which API we want, the implementation of each looks good to me.

**Comment by lelandrichardson** [comment]
IMO the API in #2045 is more powerful, and goes along with the spirit of the Animated API more closely. (I say that trying to not be TOO biased because i originally wrote it... lol)

With the current PR, it is just a custom interpolator function, and doesn't allow you to express the node as a function dependent on more than one other node in the graph. If we move forward with something like this, I believe it should be closer to what is in #2045, with the intention that it eventually be replaced with some expression parsing like the libraries mentioned above.

For example, in #2045 you could do:

```
const a = new Animated.Value(0);
const b = new Animated.Value(0);

const c = new Animated.Formula([a, b], '(a, b) => a^(b^2 - 1)');
```

whereas this would strictly not be possible with the current PR (because it is limiting to depend on a single node).

**Comment by ide** [comment]
@lelandrichardson that makes sense, supporting multiple values seems important. Reading over #2045's comments made me want to run through the possibilities again.

1. We could build up library of math operators (ex: add, multiply, exponentiate, trig) and then have a pure-JS expression parser that converts `(a, b) => a^(b^2 - 1)` into a pipeline of nodes. This would work well with native animations but is limited to the set of operators we implement. I like that this is fairly simple, but not sure if it ends up being constraining too much of the time.

2. We also could embed a math expression library in native code and do something like Animated.Formula. This is probably my least favorite solution because of the native dependency, it's harder to make changes to it. At least the C++ bridge makes it easier to share code though.

3. Lastly we could provide a JS-only version of Animated.Formula that takes in any JS function (like this PR). This is super flexible and is the ultimate escape hatch.

I lean towards a combination of 1 and 3. Option 1 goes quite far and has native support and option 3 is there for when you need flexibility/power more than anything else. Option 2 isn't bad either but I would be curious to know if we could deprecate the other nodes we have, otherwise maybe it's better to build out option 1.

**Comment by clozr** [comment]
So yesterday I was experimenting with an animated color slider. I wanted to use some color interpolators exposed by d3 and some other interesting interpolators.  
Although having a uniform API which could let us leverage the native animation is really good, we must have flexibility in javascript based animation. This approach allows the interpolation to use INTERPOLATION functions exposed by third party APIs which may be complex in nature, and we just want to use it OFF THE SHELF.
Here is a simple example.
```
import * as IPL from 'd3-interpolate';
let ipl = ipl.interpolateRgbBasis(<Some Colors Array>);
let x = new Animated.Value(0)
let color = x.interpolate({
   expression: v => ipl(v/width)
})
```
So, this approach allows you to mix and use third party libraries interpolation. 
We could later allow complex math expression which could work both for 'native' as welll as 'js' world while retaining this functionality and informing users that this is restricted to javascript only.

I think semantic wise it also aligns as it says that you got an **_interpolated variable_** not exactly a **_formula_** and you could use toJSON method etc. applicable to variables.  I can extend it for multi node if we decide to go with this.

**Comment by lelandrichardson** [comment]
@clozr correct me if i'm wrong, but it seems like what you are trying to do in your example can already be done by specifying a custom interpolate function?

**Comment by clozr** [comment]
I was just emphasizing how easy it is to import third party interpolation library and use it with this approach. I am interested in knowing how would you do this?

**Comment by clozr** [comment]
The easing function is applied after the linear interpolation of input and output range.  Which is not very elegant and forces us to provide input/output range. I guess we should deprecate easing in favor of expression as the easing behavior then can be composed with the combination of these two.

**Comment by clozr** [comment]
Oh I just realized that easing may be getting used on native side too! Never mind.

**Comment by clozr** [comment]
So how should we proceed?

**Comment by lacker** [comment]
I don't think this is the right way to do interpolation. Adding something with a plan of maybe-deprecating-it-later is just adding more technical debt and making the system worse here. In particular if we are not accepting https://github.com/facebook/react-native/pull/2045 then this is kind of the same thing so it's inconsistent if we just add this in.

Basically, right now we have three different ways of animating a custom way:

Use interpolation
Use easing
Combine Animated.add and Animated.multiply

This seems like it's already too many. We shouldn't proceed from here by adding lots more flags to interpolation, that will just leave the API hard to use. In terms of what to do, I think the ideal would be if someone had a proposal for a next-gen Animated API and they could propose it in an issue or something.

Anyway I am going to close this pull request but I think improving the animated API is a good thing to do so it would be interesting to see more proposals for it overall.

**Pull request closed without merging**
