### PR TITLE
Fix ClassCastException

### PR DESCRIPTION
**Pull request by thomasleplus**

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @dmmiller and @andreicoman11 to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by janicduplessis** [comment]
Hey @thomasleplus, thanks for the pull request!

Could you please provide a test plan for this to help the reviewer? For a simple bug fix like this it would be nice to have an explanation of how to reproduce the bug, why it happens and how you tested the fix.

See https://github.com/facebook/react-native/blob/master/PULL_REQUEST_TEMPLATE.md

Let me know if anything isn't clear, thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by dmmiller** [comment]
Why is this needed?

**Comment by facebook-github-bot-0** [comment]
@thomasleplus updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@thomasleplus updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@thomasleplus updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@thomasleplus updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@thomasleplus updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@thomasleplus updated the pull request.

**Comment by thomasleplus** [comment]
Hi @janicduplessis and @dmmiller,

Sorry, my pull request lacked information to say the least. I stumbled into this bug while reading the code so I don't have an actual test case. So what I did is that I've added a unit test that allows to reproduce the exception before the fix, and shows that it is fixed afterwards. I hope this will be sufficient.

Regards and thanks for your help,

Tom

**Comment by dmmiller** [comment]
Can you show the exception?  Looking at the code, just calling toArray() on the list should return an array so I'm curious why there is an exception.

**Comment by thomasleplus** [comment]
The issue is that toArray() returns an Object[] and you can't cast that into a InputFilter[] even if you know for certain that each object inside the array is an instance of InputFilter. It's kind of a strange limitation of Java, other languages like C++ support that because it is all pointers to them anyway. But in Java arrays are typed object that you can't cast that easily.

Now my guess regarding why toArray() returns an Object[] is that they didn't want to have to check if all the objects in the collection have a common ancestor to instantiate a more specifically-typed array. With the introduction of generics in Java 5, you would think that, since we are dealing here with a LinkedList&lt;InputFilter&gt;, toArray() would know to instantiate an InputFilter[] but it doesn't because the generic type is lost during compilation due to [type erasure](https://docs.oracle.com/javase/tutorial/java/generics/erasure.html)

That's why the toArray(T[]) method exists, so that you can provide an array type. If you just pass a new InputFilter[0] for example, toArray(T[]) will just use that array's type to know what type of array to instantiate. If you provide an array large enough to contain all the elements in your list, toArray(T[]) will reuse the array provided and return it.

This is a fairly common Java mistake that I used to do myself. That's why I noticed it reading the code. You can find discussions about on the web including (here)[https://stackoverflow.com/questions/5690351/java-stringlist-toarray-gives-classcastexception].

Here the stack trace when the unit test that I have fails (before my fix of course):
```
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Landroid.text.InputFilter;
	at com.facebook.react.views.textinput.ReactTextInputManager.setMaxLength(ReactTextInputManager.java:292)
	at com.facebook.react.views.textinput.ReactTextInputPropertyTest.testMaxLength(ReactTextInputPropertyTest.java:340)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1873)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:773)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:638)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:49)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by dmmiller** [comment]
Thanks for the great explanation.

@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1037377063009773/int_phab) to review.

**Pull request closed without merging**
