### PR TITLE
[docs] Mention that LayoutAnimation has to be explicitly enabled on A…

### PR DESCRIPTION
**Pull request by mkonicek**
This is mentioned in a different document but we forgot to mention it in JS docs:
- Mentioned here: http://facebook.github.io/react-native/docs/animations.html#layoutanimation
- Missing here: http://facebook.github.io/react-native/docs/layoutanimation.html

**Test plan**

    cd website
    npm install
    npm start

screenshot 2016-11-25 21 48 36

### CODE REVIEW

**Comment by janicduplessis** [comment]
👍 

@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@mkonicek It would be nice if the bot used the first commit instead of the last one for the author so we can edit the PR without hijacking it -_-

**Comment by mkonicek** [comment]
@janicduplessis I agree. Requested that from the open source team now, no guarantee they'll implement it yet.

**Comment by sahrens** [comment]
@janicduplessis: Is this still experimental? What do you think about turning it on by default everywhere, with an opt-out if people see bugs and don't want to change all their code that works on iOS?

**Comment by janicduplessis** [comment]
@sahrens Create and update animations are really stable, I used it quite a bit without issues. Delete animations have a few issues that I never had time to fix so what we could do is disable delete animations in the preset and enable layout animations by default on Android.

**Pull request closed without merging**
