### PR TITLE
[transform] add perspective property to transform

### PR DESCRIPTION
**Pull request by chirag04**
cc @sahrens @vjeux

### CODE REVIEW

**Comment by brentvatne** [comment]
@chirag04 - can we get a UIExplorer example too? :) Awesome

**Comment by chirag04** [comment]
sure. What sort of an example would you want?

**Comment by sahrens** [comment]
An "Animated - Flip" example would be sweet :)

**Comment by sahrens** [comment]
Otherwise code looks great :)

**Comment by chirag04** [comment]
@brentvatne @sahrens Wondering where should be adding this example. 

There is one example for animated api but it is the demo app @sahrens had in this react-europe talk. No scope to adding there i guess.

**Comment by sahrens** [comment]
A new top-level example would be fine I think.

**Comment by chirag04** [comment]
named Perspective and showing the flip?

**Comment by sahrens** [comment]
Maybe name it Transforms and the flip/perspective could be one example
inside it?

**Comment by chirag04** [comment]
Sure.

**Comment by chirag04** [comment]
Modified the existing transformExamples to work with UIExplorer. Kept other examples as is and adding flip on top.

I would need backfaceVisibility, RotateXYZ, and perspective to be merged into master and published to npm for this example to work i guess. @sahrens  When do you think will these 3 be merged?

Should we wait till we get all these published and then send a new PR for example?

ios simulator screen shot jul 14 2015 3 14 25 pm

**Comment by sahrens** [comment]
I'll have everything merged this week, hopefully tomorrow.  If you just put something up here I can manually merge it all together.

**Comment by chirag04** [comment]
done. Looking forward to it.

**Comment by sahrens** [comment]
@facebook-github-bot import

**Comment by sahrens** [comment]
I updated the example internally - should sync out soon:

image

**Comment by sahrens** [comment]
I updated the example internally - should sync out soon:

matrixflip

**Comment by chirag04** [comment]
@sahrens Awesome!

**Comment by chirag04** [comment]
[Off Topic]

@sahrens If i were to show 10 flip cards in a listView, How would i animate the flip individual?

Animated is tied to state and all these 10 flip cards will be transforming on that one state. Should i create 10 state values to represent the flip state of all these 10 cards?

Can you suggest any other/better pattern for this?

Thanks for the help.

**Comment by chirag04** [comment]
I think i have the solution. I just made a small component which will represent the state of one flashcard and animate it. In the listview i will just render that component for each row. This is working nicely.

Only one thing left for a listview with flashCards. :dancer:  which is figuring out how to position the cards.

Position 'absolute' is causing all 10 cards to align on below the other.

**Comment by sahrens** [comment]
You could also potentially do 10 different interpolations?

**Comment by sahrens** [comment]
Oh yeah component encapsulation is the way to go.

Why are you using position absolute?

**Comment by chirag04** [comment]
For flip, I need the two cards to be at one below the other. position: 'absolute' for that. Is there a better way for that?

**Comment by chirag04** [comment]
@sahrens  Wondering if it possible to update the interpolation outputRange dynamically without a re-render.

I have the view to rotate with animation but what if i wanted to revert the animation to original state. outputRange here is hardcoded and if i were to do a reverse flip I need the outputRange to go from ``360->180``.

eg:
``
rotateX: this.state.theta.interpolate({
     inputRange: [0, 180],
     outputRange: ['180deg', '360deg']
})
``

Wondering if we can have a way to update the interpolation without a re-render. Could be a useful api.

cc @vjeux  @ide  @brentvatne

**Comment by sahrens** [comment]
First off, it shouldn't be a big deal to re-render for the beginnings of animations/transitions.

Second, you shouldn't need to change the interpolation. If you need to flip back, just animate back to 0. If you want to flip the other way, then just animate to -1 which should interpolate to -180.

I'm not entirely sure what your trying to accomplish, so let me know if that doesn't do what you need (and provide more detail).

**Comment by chirag04** [comment]
Oh damn! I never knew interpolate will handle it smartly. Yes, you are right, animating back to 0 is flipping it back to original position.

Thanks you so much for this. I just made a listview of flashcards. A tap on any flashcard will flip it and flip back on next tap.

Animated api is so powerful and amazing. Kudos to you and the team :)

**Pull request closed without merging**
