### PR TITLE
Add dev bundle download listener on Android

### PR DESCRIPTION
**Pull request by janicduplessis**
This exposes a way to listen to JS bundle download events when creating a ReactInstanceManager. This can be used to display a custom native UI while the JS bundle is loading. It is a pretty specific use case but Expo will need this to display loading progress on the app loading splash screen.

**Test plan**
Tested by adding a listener to the ReactInstanceManager in the Expo app and checked that it gets called when the bundle is loading.

### CODE REVIEW

**Comment by hramos** [comment]
PR looks good, we just need to update some internal projects that refer to `BundleDownloadCallback` before we can land this. I'll import this PR and update the internal diff with whatever needs to be done here.

**Comment by hramos** [comment]
Importing again so we can get all the recent changes.

**Comment by brentvatne** [comment]
@hramos - looks like import failed? :(

**Comment by janicduplessis** [comment]
@hramos Fixed conflicts, could you try shipping this again?

**Comment by hramos** [comment]
Status: we made some changes to the internal source of truth repo which required a rebase. Next I just need to update some internal references to this callback (again, as these changes get blown away whenever I re-import this PR).

**Comment by janicduplessis** [comment]
@hramos Fixed conflicts, could you try shipping this again?

**Comment by hramos** [comment]
Re-importing, let's try again.

**Pull request closed without merging**
