### PR TITLE
Fix alternative downloadBoost src

### PR DESCRIPTION
**Pull request by btoueg**
ReactAndroid:downloadBoost task sometimes fail for missed SSLHandShake and the alternative url is not up-to-date.

Issue raised when download fails looks like http://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@btoueg Could you sign the CLA please so we can merge this?

**Comment by ide** [comment]
@bestander has a PR out to replace this entirely by hosting on npm, this PR will be out of date if that gets merged then.

**Comment by btoueg** [comment]
@janicduplessis done

**Comment by btoueg** [comment]
@ide will the people who are building from source be affected by @bestander PR?

**Comment by ide** [comment]
Yes, that's the point of his PR.

**Comment by btoueg** [comment]
@ide @bestander #11511 has been closed?

**Comment by bestander** [comment]
Yes, @btoueg.
Now that we rely on github to serve boost let's close this PR

**Pull request closed without merging**
