### PR TITLE
_getText defaults to blank string when no default value set

### PR DESCRIPTION
**Pull request by m3vaz**
#6936 reports a problem with the implementation of TextInput. On iOS clearing a TextInput with no default value set would preserve the first portion of the text being cleared. 

One of the potential fixes that @grabbou suggested was to make _getText return an empty string in the worst case of null value and null defaultValue.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @erickreutz to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
@m3vaz updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9553/files/473f9f9fbab443603fd6e69233962ff52421cc5c..327cdb589cd2d1e1481f59d90e430e83592c54b4)

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-3** [comment]
@m3vaz updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9553/files/327cdb589cd2d1e1481f59d90e430e83592c54b4..dbbb26f36c5b8daeb7708fe75aa7c4ee7b5266cb)

**Comment by ide** [comment]
Can you make this do the same check as value's with the typeof string check?

**Comment by facebook-github-bot-2** [comment]
@m3vaz updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9553/files/dbbb26f36c5b8daeb7708fe75aa7c4ee7b5266cb..b318f0dc9210a9f890d9dee2a035f66ab8db372b)

**Comment by m3vaz** [comment]
@ide Like so?

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3800913) to review internal test results.

**Pull request closed without merging**
