### PR TITLE
Android: Add onScroll event to TextInput

### PR DESCRIPTION
**Pull request by rigdern**
Corresponding iOS PR: https://github.com/facebook/react-native/pull/11002

This adds an onScroll event to TextInput which is useful when a multiline TextInput has so much content that it is scrollable.

**Test plan (required)**

Verified the event works properly in a test app. Also, my team uses this event in our app.

Adam Comella
Microsoft Corp.

### CODE REVIEW

**Comment by ericvicenti** [comment]
@mkonicek, can you give this a quick look-over? I just stamped this feature on iOS and it would be great to get them in together.

**Comment by mkonicek** [comment]
Looks great, thanks!

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Looks like there are merge conflicts now in TextInput.js, sorry about that! Can you rebase please?

**Comment by rigdern** [comment]
@mkonicek I predict there will be another merge conflict here when #11007 goes in so I'll wait for that to be merged first.

The problem is this change, #11007, and #10900 all [pass a new prop to `AndroidTextInput`](https://github.com/facebook/react-native/blob/fc23784fe749cd88cb183b73212a4e247385fc2e/Libraries/Components/TextInput/TextInput.js#L709-L721). The merge algorithm sees that one revision has the line `disableFullscreenUI={this.props.disableFullscreenUI}` whereas this PR has the line `onScroll={this._onScroll}`. It doesn't have enough knowledge to realize these lines don't represent conflicts and we want both of them.

If there's no better way to coordinate these changes, I'll just wait for #11007 to be merged before updating this one.

**Comment by mkonicek** [comment]
Sounds good @rigdern! I'll look why importing #11007 failed and comment there.

**Comment by mkonicek** [comment]
@rigdern Looks like https://github.com/facebook/react-native/pull/11007 has a test failure, I'll hold off merging this one based on your comment above saying we should merge https://github.com/facebook/react-native/pull/11007 first. Let me know if you'd like this one merged first instead.

**Comment by hramos** [comment]
Now that #11007 is merged, can we go ahead with this PR?

**Comment by rigdern** [comment]
@hramos There are some merge conflicts that need to be resolved. I don't have time to do that today. Maybe next week.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
