### PR TITLE
Fix remote debugging in three examples

### PR DESCRIPTION
**Pull request by joshzana**
The 2048, Movies, and TicTacToe examples don't include RCTWebSocketDebugger
and error out if the user hits Cmd-D.
This fixes them according to the steps at http://stackoverflow.com/a/29437736

### CODE REVIEW

**Comment by nicklockwood** [comment]
libuicore is no longer required. If you wouldn't mind removing it, I'll get this merged.

**Comment by joshzana** [comment]
Can this be merged?

**Comment by brentvatne** [comment]
Sorry for the delay, `RCTWebSocketDebugger` is no longer a thing, so I'm closing this

**Comment by nicklockwood** [comment]
RCTWebSocketDebugger is still there, it's just included in the RCTWebSocket lib now instead of being a separate module.

**Comment by nicklockwood** [comment]
Ah, but the issue itsef is resolved, I believe. Nevermind :-)

**Pull request closed without merging**
