### PR TITLE
Give barTintColor and titleTextColor to the RCTNavigatorIem

### LINKED ISSUE #273: You can't set barTintColor on NavigatoriOS
I see that in the code that you can set the barTintColor property on NavigatoriOS, but the property isnt actually given to the Objc code.

Is there a another way to set the background of the navigator or is this a bug?

### PR DESCRIPTION
**Pull request by coenert**
Resolves #273, and also another bug regarding the titleTextColor.

### CODE REVIEW

**Comment by AbeEstrada** [comment]
:+1: I hope this gets merged soon.

**Comment by nim23** [comment]
Just a heads up, for some reason providing the barTintColor, void's the tintColor and is always blue. I made the same changes as this commit to my local copy of react-native and as soon as I provide a barTintColor, tintColor is always blue.

**Comment by harrywincup** [comment]
`tintColor` seems to be intentionally disabled if `barTintColor` is present, though i'm not sure why? https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/React/Views/RCTWrapperViewController.m#L80

**Comment by torifat** [comment]
The `alpha` value on `barTintColor` doesn't have any effect on the navigation bar and it looks ugly without transparency. It seems using a transparent image as background is the current solution. I'm naive to iOS development. So, any expert can correct me if I'm wrong. But, I believe they have not implemented it intentionally - https://github.com/facebook/react-native/blob/master/Libraries/Components/Navigation/NavigatorIOS.ios.js#L47

**Comment by vjeux** [comment]
There are trailing whitespaces. Also, can you make use of those in the NavigatorIOSExample?

**Comment by eduardinni** [comment]
I completed this pull request, based on all your comments here. I include one working example.

I don't know if it is possible to merge pull requests, but mine is #695

**Comment by brentvatne** [comment]
This was merged!

**Pull request closed without merging**
