### PR TITLE
Fix path to UIExplorer examples

### PR DESCRIPTION
**Pull request by javache**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @sahrens to be potential reviewers.

**Comment by JoelMarcey** [comment]
Thanks for getting this PR out so quickly.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1824379951123114/int_phab) to review.

**Pull request closed without merging**
