### PR TITLE
npm progress shown on react init

### LINKED ISSUE #3771: Show download progress bar during 'react-native init'
'react-native init' spends almost all its time in 'npm install':
https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L191

It would be cool to show a progress bar during the download.

A quick Google search returns: https://github.com/npm/npm/issues/6911

### PR DESCRIPTION
**Pull request by udnisap**
fixes #3771 for npm 3 and upwards

### CODE REVIEW

**Comment by christopherdro** [comment]
Did you mean node 5 and upwards?

**Comment by satya164** [comment]
This is awesome. Thanks a lot :)

**Comment by satya164** [comment]
LGTM

**Comment by christopherdro** [comment]
Testing and looks good!
cc @mkonicek

**Comment by satya164** [comment]
Let's merge this then.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
Seems it didn't go through. cc @mkonicek

**Comment by mkonicek** [comment]
Thanks for the ping! The react-native-cli is a bit of a special case as we don't store it in the fb codebase (same like docs) so we have to merge it directly on github.

We'll also need to release a new version of the react-native-cli for this to take effect, created a TODO.

**Comment by satya164** [comment]
Thanks @mkonicek

**Pull request merged**
