### PR TITLE
New Share API Use Cases

### PR DESCRIPTION
**Pull request by chirag-singhal**
## Summary
 * New use cases for share API in rn-tester

## Changelog
[General] [Changed] - Changed use cases for share API in rn-tester

## Test Plan 
* Tested app in both Android and iOS

Screenshot_2020-09-09-21-20-41-322_com facebook react uiapp

image

### CODE REVIEW

**Comment by dulmandakh** [comment]
Please remove gradle change, so that is only contains Share only changes. Thanks

**Comment by chirag-singhal** [comment]
@dulmandakh Removed gradle changes

**Review by rickhanlonii — COMMENTED** [review]
Code looks good, can you include a before/after demo in the test plan?

**Comment by chirag-singhal** [comment]
@rickhanlonii added the screenshots

**Pull request closed without merging**
