### PR TITLE
Revert "Add docs survey link to site header"

### PR DESCRIPTION
**Pull request by JoelMarcey**
This reverts commit 4a7f2192f9cf95f0c8fa4b0742eb472c13ee2859.

Adding the link breaks mobile

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @bestander and @skevy to be potential reviewers.

**Comment by bestander** [comment]
How about fixing it instead? :)
I think if you use '&nbsp' instead of spaces it won't break into multiple lines.
And we could temporarily remove another link to free up space.
And also use media queries to style it for small screens if necessary

**Comment by JoelMarcey** [comment]
@bestander .... @vjeux is suggesting and coming up with a more amenable solution/fix right now I think...

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1631090663882929/int_phab) to review.

**Pull request closed without merging**
