### PR TITLE
Cancel check update task

### PR DESCRIPTION
**Pull request by ywz2010**
When call `[RCTDevMenu invalidate]`, it will cancel updateTask. But in fact, after the `[updateTask cancel]`, the updateTask's completionHandler will call `checkForUpdates` again, so it will create a new updateTask.

### CODE REVIEW

**Comment by ywz2010** [comment]
`_updateTask` created by `[NSURLSession sharedSession]`. So up to 4 tasks can run at the same time. If I create a new rootView and destroy it, after  `[RCTDevMenu invalidate]` it will create a new web connect. After I repeat it 4 times in a short time, there exit 4 `_updateTask` , so `RCTJavaScriptLoader` cann't load bundle because it download task is created by  `[NSURLSession sharedSession]` too.

**Comment by satya164** [comment]
cc @nicklockwood

**Comment by facebook-github-bot-2** [comment]
@nicklockwood would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3669576) to review internal test results.

**Pull request closed without merging**
