### PR TITLE
Added complete index example

### PR DESCRIPTION
**Pull request by lovato**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an _existing_ commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

Make it more clear to the beginners.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @scarlac to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
It was a deliberate choice to use a partial example here, as the last code example includes the entire JS file.

**Comment by facebook-github-bot-8** [comment]
@lovato updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9798/files/5d28e429723af7050e33c730e01031ba229b4e7c..f65af6b804f05c9be2ea237152ecefac5282bcc6)

**Comment by lovato** [comment]
CircleCI says:

Version '6.2.0' not found - try `nvm ls-remote` to browse available versions.
nvm install 6.2.0 && nvm alias default 6.2.0 returned exit code 3
Action failed: set node.js version to 6.2.0

What am I supposed to do?

**Comment by lovato** [comment]
@hramos, ok. Only saw your comment now. You are the maintainer, but I disagree. At the beginners guide, things are supposed to work. And the last example was not working as well, and I also opened a pull request.

https://github.com/facebook/react-native/pull/9802

I got an invalid token because of the misplaced "return" statement, and there was a "export default" for the app, and no AppRegistry, which made me do a lot of research to complete the guide.

**Comment by mkonicek** [comment]
@lovato Thanks for updating the complete example in #9802. If we merge that, would be happy with keeping the part in this PR partial as @hramos who wrote this guide suggested?

**Comment by mkonicek** [comment]
We're thinking of generating a simple app template including navigation so people would not have to copy&paste from this guide when getting started with React Native. Stay tuned :)

**Comment by lovato** [comment]
Yes, totally agree @mkonicek. My point was that I was more than happy using the web emulator on previous lessons, to play around, and on Navigator, there was no web emulator (I guess its not compatible?) nor the examples were working.

**Comment by hramos** [comment]
Agree it would be great if the React Native Web Player could be used here. [react-native-web](https://github.com/necolas/react-native-web) does not currently support navigators, and it blocks us from using the web player in this case unfortunately.

**Comment by hramos** [comment]
Now that #9802 landed, see Martin's feedback.

**Comment by lacker** [comment]
I think by now this has been abandoned so I am going to close this pull request. I think the way to go is probably to wait until we improve the navigation libraries as per the roadmap, anyway. Thanks for pointing out this issue.

**Pull request closed without merging**
