### PR TITLE
Fix #5432: prevent jumping on refreshing

### LINKED ISSUE #5432: RefreshControl jumping in ListView [iOS]
In my application I am the `ListView` component like in the code below. Everything works like charm except of one tiny ugly bug. When I start pulling the list view down it goes down smoothly and increases the number of strokes of the loading spinner. But in the moment the spinner graphic completes and starts spinning I am observing an ugly jump. 

This is exactly the same behavior as described in this [stackoverflow post](http://stackoverflow.com/questions/23769967/pull-to-refresh-jump-in-ios)

```javascript
<ListView
  onEndReached={this._loadMore.bind(this)} 
  onEndReachedThreshold={0}
  refreshControl={
    <RefreshControl
      refreshing={this.state.isRefreshing}
      onRefresh={this._refresh.bind(this)}
    />
  }
  renderFooter={() => {
    return <Image style={styles.loadingIndicator} source={require('../../images/loading.gif')}/>
  }}
  dataSource={this.state.dataSource.cloneWithRows(preparedItems)}
  loadData={this._refresh.bind(this)}
  scrollRenderAheadDistance={1600}
  pageSize={6}
  removeClippedSubviews={true}
  initialListSize={20}
  renderRow={this._renderRow.bind(this)}
/>
```

### PR DESCRIPTION
**Pull request by ptmt**
Reproduce: https://rnplay.org/apps/0rDi5g
Context: https://github.com/facebook/react-native/issues/5432
Possible fix: http://stackoverflow.com/questions/19483511/uirefreshcontrol-with-uicollectionview-in-ios7/19926917#19926917

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @rigdern to be potential reviewers.

**Comment by javache** [comment]
cc @mmmulani

**Comment by mmmulani** [comment]
thanks for this fix but it looks pretty deep, like it will apply to `UIScrollView` even when it's being used for other components. Could you maybe restrict it to only the `ListView` case?

**Comment by ptmt** [comment]
I agree, the solution doesn't look nice. Not sure it's only about ListView, though. See jumping using `ScrollView` https://rnplay.org/apps/BOpXeA which looks the exactly same as with using `ListView` https://rnplay.org/apps/0rDi5g.

**Comment by mmmulani** [comment]
yeah so maybe limit it to scroll views with refresh views

**Comment by mmmulani** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/524289111109419/int_phab) to review internal test results.

**Comment by mmmulani** [comment]
I just tried this on the example you linked and it doesn't actually do anything different.

I was able to get rid of the jankiness by doing a `setState({refreshing: true})` in the onRefresh: https://rnplay.org/apps/65ABgg

is that closer to what you'd expect?

**Comment by ptmt** [comment]
Yes, since I added check for `.refreshing`, the example needs `refreshing: true` in order to apply the fix. What's you opinion, is this check required (only left a check for `rctRefreshContol` then)?

**Comment by mmmulani** [comment]
so I patched that code in and tried running the example but the code was never triggered. Furthermore if setState({refreshing:true}) in onRefresh before the setTimeout, it looks like the animation is all okay: https://rnplay.org/apps/65ABgg

**Comment by ptmt** [comment]
I still observe the bug described here: https://github.com/facebook/react-native/issues/5432
jul-20-2016 17-34-30

**Comment by janicduplessis** [comment]
iOS 10 has support for UIRefreshControl in ScrollView so hopefully this fix won't be needed in iOS 10+. Then whenever iOS9- is not used anymore we can remove this.

**Comment by ptmt** [comment]
@mmmulani Can I help somehow to clarify the issue? I still can reproduce it without the fix in this patch.

**Comment by mmmulani** [comment]
hey sorry, I'm a bit swamped with other work this week. Can hopefully take a look next week

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @nicklockwood as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ptmt** [comment]
Can reproduce this jump on 0.33.0-rc.0

**Comment by facebook-github-bot-6** [comment]
@ptmt updated the pull request - [view changes](https://github.com/facebook/react-native/pull/8896/files/724f2a846eeb899a5bc601fa7c7a0370664deb72..f0f8d21e1c28b50b27e9b41deab810d6db25ee27) - [changes since last import](https://github.com/facebook/react-native/pull/8896/files/724f2a846eeb899a5bc601fa7c7a0370664deb72..f0f8d21e1c28b50b27e9b41deab810d6db25ee27)

**Comment by ptmt** [comment]
Closing, since there is no more point in this pull request. iOS 10 is out there and has better way to fix this issue.

**Comment by jeanregisser** [comment]
@ptmt I still see this issue on iOS 10.1.1 and RN 0.38.
What's the better way to fix this?

**Comment by jeanregisser** [comment]
Ok I see in the iOS 10 docs that `UIScrollView` has now a `refreshControl` property https://developer.apple.com/reference/uikit/uiscrollview/2127691-refreshcontrol?language=objc

`RCTScrollView` doesn't yet use it though. I'll try it to see if it helps with this issue.

**Comment by jeanregisser** [comment]
Quick test shows that the problem is still present when using the `refreshControl` property on iOS 10.

**Comment by loveaurell** [comment]
I'm also experiencing this on RN 0.39, iOS 10.2

**Comment by majd-kho** [comment]
Issue still present in IOS 10.3 RN 0.47

**Pull request closed without merging**
