### PR TITLE
[Android][TextInput] Fix: mostRecentEventCount is not updated.

### PR DESCRIPTION
**Pull request by jainkuniya**
## Motivation

Update it's value as it changes on the JS thread, so that updated value is used (https://github.com/facebook/react-native/blob/f7f5dc66493ad25a85927a9503728b0491c8aab9/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L243) whenever setSelection(int start, int end) is called (https://github.com/facebook/react-native/blob/f7f5dc66493ad25a85927a9503728b0491c8aab9/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L315).

## Test Plan

**On [current master](https://github.com/facebook/react-native/tree/f7f5dc66493ad25a85927a9503728b0491c8aab9)**
Log the value of `mMostRecentEventCount` in the `setSelection` method. https://github.com/facebook/react-native/blob/f7f5dc66493ad25a85927a9503728b0491c8aab9/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L243
It is always `0`.

**On this PR** 
It's values gets updated as it new value is set here (https://github.com/facebook/react-native/blob/f7f5dc66493ad25a85927a9503728b0491c8aab9/Libraries/Components/TextInput/TextInput.js#L921)

To try this PR working, test plan of #17894 can also be used :).

## Release Notes

 [ANDROID] [BUGFIX] [TextInput] - Fix: mostRecentEventCount is not updated.

### CODE REVIEW

**Comment by shergin** [comment]
@jainkuniya Thank you for tackling this!
Why do you think that setting the variable in `public void maybeSetText(ReactTextUpdate reactTextUpdate) {` is not enough? (Looks like it is, but why?) Why should we keep both update paths?

**Comment by jainkuniya** [comment]
hi @shergin 

`public void maybeSetText(ReactTextUpdate reactTextUpdate) {` is only called once (and sometimes it is never called) and it is definitely not called as soon as event count changes so `mMostRecentEventCount` is not updated to recent value via this path. I am thinking to remove this path https://github.com/jainkuniya/react-native/blob/bc874a55da16770034afb3a343c948d8328d9227/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L362 . Should I?

**Comment by jainkuniya** [comment]
hi @shergin, @janicduplessis, @hramos 
waiting for your review :)

**Comment by hramos** [comment]
I don't usually perform reviews, that's up to the community. Ping me again once this has been reviewed.

**Comment by jainkuniya** [comment]
It's waiting for review :)

cc @shergin, @janicduplessis

**Comment by theolavaux** [comment]
When will the change be included in a release?

**Pull request closed without merging**
