### PR TITLE
Back out "Apply Babel arrow transform only when needed"

### PR DESCRIPTION
**Pull request by GijsWeterings**
Summary:
Original commit changeset: ad96540bb777

Original Phabricator Diff: D50818568

Changelog: [Internal]

Reviewed By: robhogan

Differential Revision: D50885400

### CODE REVIEW

**Comment by gaearon** [comment]
Sorry for the churn! What kind of breakage was it?

**Comment by GijsWeterings** [comment]
@gaearon We've got an (ancient) ContainerProxy utility internally that does some instance proxying for HOC. This utility depends on calling `.prototype` on a `React$ComponentType<any>` variable, but (apparently, TIL) arrow functions don't have a `.prototype`. @robhogan is going to follow up on this

**Comment by gaearon** [comment]
Oh wild. Thanks!

**Comment by gaearon** [comment]
@GijsWeterings @robhogan Has this been solved?

**Comment by GijsWeterings** [comment]
@gaearon Hey sorry for the slow response! @yungsters currently has a big stack up internally to move off of the ContainerProxy as part of our code modernisation efforts internally, so after that we can test reapplying this!

**Comment by yungsters** [comment]
Sorry for the delays. I've finally gotten around to cleaning up the last remnants of `ContainerProxy` hackiness, and I have a diff up to bring this back (which I just exported as https://github.com/facebook/react-native/pull/44534).

**Comment by yungsters** [comment]
https://github.com/facebook/react-native/pull/44534 has been merged!

**Pull request closed without merging**
