### PR TITLE
Add Troubleshooting doc for recurring issues

### PR DESCRIPTION
**Pull request by tehfailsafe**
Closes my issue at https://github.com/facebook/react-native/issues/306

### CODE REVIEW

**Comment by amasad** [comment]
We should have a troubleshooting page to include things and other hiccups like the port issue.

**Comment by tehfailsafe** [comment]
Good idea, adding it now.

**Comment by amasad** [comment]
Thanks, that would be great. This way we can have the quick start be sweet and short. With a link to a troubleshooting page.

**Comment by amasad** [comment]
This is great! I like the screenshots
screenshot 2015-03-27 22 49 04

**Comment by amasad** [comment]
But where is this linked from? I can't find in the left hand side menu.
cc @vjeux

**Comment by tehfailsafe** [comment]
Wasn't sure if I should do that or you guys need to.

**Pull request merged**
