### PR TITLE
added script to release blog independent of website versioning

### PR DESCRIPTION
**Pull request by bestander**
I suppose over time we should simplify the script.
But for now this will do.

Logic: 
1. don't copy "blog" folder to /releases/XX when doing a docs release
2. don't copy "blog" folder to / when doing stable docs release
3. copy "blog" folder to / only when doing building docs for master branch

CC @vjeux

### CODE REVIEW

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Okay, just realized that we also need to copy the following files over: website/src/img/blog/*

**Comment by bestander** [comment]
Damn, can't we have images with the blog?

**Comment by vjeux** [comment]
Yeah we can, let me do that

**Pull request closed without merging**
