### PR TITLE
[React Native] Use `react-native` instead of `React` on hmr config

### PR DESCRIPTION
**Pull request by martinbigio**
Check https://github.com/facebook/react-native/issues/6640 for details

### CODE REVIEW

**Comment by martinbigio** [comment]
cc @satya164, @skevy, @bestander

**Comment by skevy** [comment]
FYI @bestander we're getting some type of weird transient error on the Buck tests here.

**Comment by bestander** [comment]
@skevy thanks for being on top of CI errors!
@martinbigio I think you need to rebase to let CI pass

**Comment by martinbigio** [comment]
Cool, just updated the PR rebasing.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by martinbigio** [comment]
We still need to push a new version of the preset. I'll do it later today.

**Comment by martinbigio** [comment]
just release babel-preset-react-native@1.5.5

**Pull request closed without merging**
