### PR TITLE
Fixes The loadScript method in the release version app should be caught when loading a JS bundle file exception.

### PR DESCRIPTION
**Pull request by yanbober**
Fixes The loadScript method in the release version app should be caught when loading a JS bundle file exception.

### CODE REVIEW

**Comment by mkonicek** [comment]
I'm not sure I understand.

How could someone reproduce this bug? How did you verify your change fixes the bug?

**Comment by yanbober** [comment]
@mkonicek    You can think about this exception when the loadScript method is in the "DEBUG = false;" version of "devSupport = false;"; the exception is of course a hot fix.

**Comment by mkonicek** [comment]
@yanbober How would someone actually reproduce it? What commands should I run in my terminal (build an app etc.), what should I click in my emulator to see the bug?

How did you verify your change fixes the bug?

**Comment by hramos** [comment]
Ping @yanbober

**Comment by hramos** [comment]
This PR appears to be abandoned. Closing for now.

**Pull request closed without merging**
