### PR TITLE
[TextInput] Added support for textAlign to TextInput

### PR DESCRIPTION
**Pull request by darylrowland**
Added remapping of style textAlign property to textAlignment (which is the name of the same property on text input components)

### CODE REVIEW

**Comment by darylrowland** [comment]
Think I've exposed it now in RCTTextViewAttributes. Let me know if that's not correct. Thanks.

**Comment by darylrowland** [comment]
Will this one be merged into the main branch soon?

**Comment by machard** [comment]
+1

**Comment by ide** [comment]
yeah. this seems simple and reasonable.

**Comment by ranyefet** [comment]
+1

**Comment by rpastorelle** [comment]
+1

I've been using this for a while by manually making the update. Wondering when this will get merged into the main branch as well...

**Comment by alinz** [comment]
+1

just got into this problem. I hope this merge goes through. I really need it. Thanks @darylrowland

**Comment by brentvatne** [comment]
Looks good to me

**Comment by brentvatne** [comment]
Scratch the above comment - @darylrowland could you also add support for this prop to `RCTTextView`? And ideally also include an example in UIExplorer so we can pull it down and see.

**Comment by sahrens** [comment]
reassigning to nick (that's how we track who the internal owner is) but this still needs revision from @darylrowland based on @brentvatne's comments.

**Comment by stirman** [comment]
:) Been waiting on this one!

**Comment by bobspace** [comment]
@facebook-github-bot import

**Comment by bobspace** [comment]
@facebook-github-bot import

**Comment by QuantumInformation** [comment]
How to you align a text input itself?

image

I tried putting it in a flex container with center align:
image

**Comment by ixje** [comment]
@QuantumInformation  use `alignSelf: 'center'` on the TextInput

**Comment by AngelTrinidad** [comment]
Some news about this?

**Comment by DPOSPOS** [comment]
textAlign={'center'}

**Pull request closed without merging**
