### PR TITLE
Fix how KeyboardAvoidingView handles the onLayout prop.

### LINKED ISSUE #32608: KeyboardAvoidingView does not handle the onLayout prop correctly
### Description

```
import { KeyboardAvoidingView } from 'react-native'

const doOnLayout = ({ nativeEvent: { layout } }) => {
  console.log(layout)
}

<KeyboardAvoidingView onLayout={doOnLayout}>
  {/* ... */}
</KeyboardAvoidingView>
```

When the `onLayout` prop is provided the `KeyboardAvoidingView` doesn't adjust the view to avoid overlap with the keyboard. If you remove the `onLayout` prop everything works as expected.

This happens because the `KeyboardAvoidingView` component relies on the `onLayout` prop internally, so when we supply the prop ourselves it overrides the internal implementation.

This behavior is seen regardless of the value supplied to the `behavior` prop.

### Version

0.66.0

### Output of `react-native info`

N/A

### Steps to reproduce

Use the `KeyboardAvoidingView` and pass in the `onLayout` prop.

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by JeffreyHyer**
## Summary

Resolves #32608

This PR updates the `KeyboardAvoidingView` to correctly handle the `onLayout` prop.

## Changelog

[General] [Fixed] - `onLayout` prop is handled correctly in `<KeyboardAvoidingView>`

## Test Plan

| Current Behavior with the `onLayout` prop specified | After applying fix |
|---|---|
| Simulator Screen Recording - iPhone 11 - 2021-11-17 at 14 44 09 | Simulator Screen Recording - iPhone 11 - 2021-11-17 at 14 44 28 |

### CODE REVIEW

**Review by philIip — APPROVED** [review]
this looks good, thanks for working on this! can you update the test plan with a before / after video? thanks!

**Comment by JeffreyHyer** [comment]
Thanks @philIip, I've updated the Test Plan with before and after screen caps 👍

**Comment by philIip** [comment]
@JeffreyHyer can you rebase and resubmit? i will go for the land.

**Comment by JeffreyHyer** [comment]
@philIip Just rebased, should be good to merge.

**Pull request closed without merging**
