### PR TITLE
remove max children limitation on SwipeableQuickActions

### PR DESCRIPTION
**Pull request by chirag04**
**motivation**
Right now `SwipeableQuickActions` only allows two actions. Let this limit be in the userland.

cc @fred2028

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @fred2028 and @bhosmer to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @fred2028 as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by chirag04** [comment]
ping @hramos :)

**Comment by hramos** [comment]
Can you elaborate on why this is needed?

What happens if three or more actions are used? I'm mostly curious about why this was limited in the first place.

**Comment by chirag04** [comment]
Our apps had more than two buttons for swipeable row.

i don't know y it was setup like this in the first place. maybe some product requirement internally at fb?

I'm not using this component anymore because it was easy for me to roll my own that does not have this limitation of 2 buttons only. I can image this being a common case to have more than 2 buttons so we can still merge this PR i guess.

**Comment by ericvicenti** [comment]
This makes sense. I'm guessing the limit was due to a general width limit of phones, but I agree it doesn't make much sense to have this limit

**Comment by mkonicek** [comment]
Trying again.

@facebook-github-bot shipit

**Pull request closed without merging**
