### PR TITLE
Update GettingStartedOnLinux.md

### PR DESCRIPTION
**Pull request by jareks**
1. add information about automake and python-dev apt dependencies
2. Suggest current watchman version  (4.5 vs 4.1)

### CODE REVIEW

**Comment by satya164** [comment]
Could you move it to a separate block and document that it's Ubuntu-only?

**Comment by jareks** [comment]
@satya164 
This document is already Ubuntu specific, quote from Prerequisites:
"For the purposes of this guide, we assume that you're working on Ubuntu Linux 14.04 LTS."

Additionally, there are other apt-get commands listed already therefore I have just added a missing one.

**Comment by satya164** [comment]
@jareks There's only one `apt-get` command, and it includes a note that it's Ubuntu only, apart from the note at the top. Eventually we should include make it more generic, so including a note doesn't hurt.

**Comment by jareks** [comment]
@satya164 fair enough, I have added extra node. Do you think it's ok now?

**Comment by satya164** [comment]
Something weird happened with this PR, hmm...

**Comment by satya164** [comment]
Looks good

@facebook-github-bot shipit

**Pull request closed without merging**
