### PR TITLE
Fail gracefully for node<4 in react-native-cli (const->var)

### PR DESCRIPTION
**Pull request by rh389**
`const` declarations were recently introduced into https://github.com/facebook/react-native/blob/master/react-native-cli/index.js, which runs before any transpilation so needs to be old-school. Replace them with `var`. 

Fixes https://github.com/facebook/react-native/issues/11603

### CODE REVIEW

**Comment by Fahrradflucht** [comment]
I don't see why this should be necessary. [There is an engines key](https://github.com/facebook/react-native/blob/master/react-native-cli/package.json#L8) in the `package.json` of `react-native-cli` which specifies `"node": ">=4"`. As far as I know even node `4.0.0` supports `const` declarations.

**Comment by rh389** [comment]
True, but a check for that is made at the end of 'run' by 'checkNodeVersion', where we fail gracefully with a helpful message if the requirements aren't met. As it is, the script crashes out before we get that far.

**Comment by Fahrradflucht** [comment]
This is not the same thing. `checkNodeVersion` refers to the engines key of the package.json at [`REACT_NATIVE_PACKAGE_JSON_PATH`](https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L69) which is `react-native`'s package.json and not `react-native-cli`'s.

They are the same at the moment but is sure for the time to come?

That aside. If you are correct and `react-native-cli` should always run to fail gracefully if `react-native`'s node requirements aren't fulfilled. Doesn't that mean that `react-native-cli`'s engines key should be set to an earlier version or get removed?

**Comment by rh389** [comment]
Sorry, yes you're right - I was jumping to conclusions based on the fact that `var` is used throughout the rest of the file. https://github.com/facebook/react-native/commit/72b713262fbb84a0606260c4d8879621a3c7f8e7 suggests the CLI deliberately dropped support for node<4 so that we could use newer language features from then on.

The `engines` key is [advisory](https://docs.npmjs.com/files/package.json#engines) so I think it's legitimate to install but fail gracefully on older versions. https://github.com/facebook/react-native/issues/11603 demonstrates that the `engines` config alone isn't enough to make it clear to everyone what the problem is, so I guess the options are:
1. Retain enough support to fail gracefully (ideally checking against the CLI's `engines` setting).
2. Move forward and accept that users of old node versions will get a bad experience  (although note 0.12 is [only just leaving LTS](https://github.com/nodejs/LTS)). Anyone familiar with ES6 should probably figure out the problem themselves anyway.

(Aside: I guess maybe people are running into this issue because the [Getting Started](https://facebook.github.io/react-native/docs/getting-started.html) guide doesn't mention that homebrew might need updating)

**Comment by Fahrradflucht** [comment]
I think this means @ide's opinion on this could be interesting.

**Comment by ide** [comment]
The intent of the version check is to make it really clear and helpful to people running old versions of Node that they are using a too-old version and what they can do to upgrade (moving forward we'll probably require Node 6 soon). The "engines" field in package.json isn't enough since people don't always see the warning message when running npm install since it's buried in other console output.

So what we want to do is have a small JS file that is compatible with ES5 and checks the Node version. This ES5 file then will load other files that rely on modern Node.

**Comment by rh389** [comment]
> small JS file that is compatible with ES5

Assuming you're referring to [index.js](https://github.com/facebook/react-native/blob/master/react-native-cli/index.js), I take it you're in favour of this PR @ide?

If so I'm happy to add a note in the comment block indicating that it's intended to stay ES5 compatible. I hesitate because your first reason in https://github.com/facebook/react-native/commit/72b713262fbb84a0606260c4d8879621a3c7f8e7 only really applies if you intend to allow ES6 within  [index.js](https://github.com/facebook/react-native/blob/master/react-native-cli/index.js) itself, since anything passed on to the local CLI is guarded by `checkNodeVersion` anyway.

**Comment by janicduplessis** [comment]
@rh389 Can you add a comment that says this file should be es5 compatible so it can warn about old node versions.

**Comment by rh389** [comment]
@janicduplessis Done - that ok?

**Comment by rh389** [comment]
@shergin I guess this got stuck?

**Pull request closed without merging**
