### PR TITLE
Add xcodePath configuration for run-ios command

### PR DESCRIPTION
**Pull request by charlle**
Summary: 
React Native is currently hardcoding the iOS application path to `build/Build/Products`, which I believe is applicable if you have an Xcode Workspace, but a react-native init {ProjectName} will not.  The default application path for Xcode Projects is `build/Products` as of version 8.  I believe this is the cause for a lot of programmers believing the recent React Native release does not work.  Here are some reference cases:
[7308](https://github.com/facebook/react-native/issues/7308)
[1040](https://github.com/facebook/react-native/issues/10401)
[so1](http://stackoverflow.com/questions/37461703/print-entry-cfbundleidentifier-does-not-exist)
[so2](http://stackoverflow.com/questions/39339247/cfbundleidentifier-does-not-exist)

Currently the only way to resolve this issue: 
Setup Xcode to match React Native's hard coded values.
Select: `File > Workspace Settings`, Advanced, Custom, and enter `build/Build/Products`
screen shot 2017-01-13 at 8 14 31 pm

This PR changes the default application path to `build/Products` and allows programmers to set a configurable `xcodePath` from the command line.
`react-native run-ios --xcodePath 'build/Products'`

This also updates the documentation:
[Troubleshooting](https://github.com/facebook/react-native/tree/master/docs/Troubleshooting.md)
[RunningOnSimulatorIOS](https://github.com/facebook/react-native/tree/master/docs/RunningOnSimulatorIOS.md)

### CODE REVIEW

**Comment by haifaGh** [comment]
Hi, I keep getting this error "**:CFBundleIdentifier , Does Not Exist**". 
The versions I use : 
react-native-cli: 2.0.1
react-native: 0.40.0
npm 4.0.5
node v7.4.0
Mac OS 10.10.5
Xcode 7.2.1
WebStorm 2016.3.2

So  I proceeded with different solutions: 

- killing all the processes using port 8081 and resetting the port number

- verifying that this Bundle already exist in my info.plist

- changing the debug mode 

- Using this solution mentioned in this issue 

But none of this solutions worked for me .So, I changed my project in the same way as Xcode suggested me to (I know it's not the perfect solution for me and ) and attached is a picture explaining it more. 
I know that this is temporary solution and I'm afraid that it will cause me some problems in the future , as I'm still a beginner and it's my first time using react-native to create iOS apps. 
So, does anyone have any idea or possible solution .. Thanks 
screen shot 2017-01-18 at 13 11 58

**Comment by charlle** [comment]
@haifaGh You need to change the path of your app file to match Facebook's CLI path.
Setup Xcode to match React Native's hard coded values.
Select: `File > Workspace Settings, Advanced, Custom,` and enter `build/Build/Products`
See image above.

**Comment by haifaGh** [comment]
@charlle thank you for your help .. I tried that but it didn't solve the problem :( 
screen shot 2017-01-19 at 10 19 29

**Comment by charlle** [comment]
@haifaGh you changed the Products path in your photo to `build/Build/Products`?

**Comment by haifaGh** [comment]
Thank you.. I already solved my problem by updating the Mac Os version to 10.12.3 and the Xcode to 8.2.1 .. everything runs perfectly now :)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/add-xcodepath-configuration-for-run-ios-command

**Comment by shergin** [comment]
Looks reasonable to me.
@charlle Could you please resolve conflicts?

**Comment by mdaslamansari2008** [comment]
I am still getting this issue. I am surprised to see its such a old issue and yet not fixed. 
$ node -v
v9.5.0
$ npm -v
5.6.0
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.51.0

**Comment by jdonald** [comment]
Got the pathname problem resulting in ":CFBundleIdentifier, does not exist" too after addressing the initial Analyze errors with @mhorowitz's workaround in #14423. The mismatch of paths `build/Products` vs `build/Build/Products` was pretty clear based on the PListBuddy command.

I used @charlie's suggestion to change the paths except I did it in the **Project Settings...** rather than Workspace Settings.

That didn't seem to work at first, but eventually got further when I switched between `react-native run-ios --configuration Release` vs Debug. It also continued getting further once I set the build location back to "Xcode default" so maybe something gets sticky in the settings when upgrading Xcode over the years and it needs to be reset.

Now hitting this error:
```
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to chmod /Users/jdonald/Library/Developer/CoreSimulator/Devices/36A27A71-C0E8-40D7-A644-C0930E56B109/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/4AB34A7F-CE56-4029-921E-5E7686888568/AppName.app/$(EXECUTABLE_NAME) : No such file or directory
Launching org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)
```
(because that long garbage path doesn't appear to exist)

Maybe someone can tell me if there already exists a ticket for that one before I file a new one, but this is already three levels deep for a user simply trying to get run-ios to work.

node v9.10.1
npm 5.6.0
react-native-cli: 2.0.1
react-native: 0.55.1
Xcode 9.3

**Comment by Kielan** [comment]
rather than trying to resolve this issue with a pull request, a documentation guide exaplaining how react native handles it's under the hood paths which collide with native projects, seems to be particularly an issue if your react native project is not a workspace. Maybe all react native projects should be workspaces and that should be recommended in <h1/> or <h2/> on the website

**Comment by iamosmanyilmaz** [comment]
Thank you so much. It finally worked.

**Comment by Gutyn** [comment]
@osmanyz it worked how?

**Pull request closed without merging**
