### PR TITLE
[package.json] Warn when installing react-native globally

### LINKED ISSUE #730: [JS] Warn when `npm install -g react-native`
Several people didn't add -cli and then got confused that it didn't work.

### PR DESCRIPTION
**Pull request by dbanck**
Added a postinstall hook as @frantic suggested, in #730.

The message might be hard to spot. Maybe color it?
Imgur

### CODE REVIEW

**Comment by tadeuzagallo** [comment]
If you have linked your react-native repo, like I have, it will warn you forever...
Maybe we could do something like

```sh
if [[ "$(pwd | grep $(npm get prefix))" != "" ]]; then
 echo "WARNING: Looks like you installed react-native globally, did you mean react-native-cli?"
fi
```

**Comment by tadeuzagallo** [comment]
Well, I wrote the comment, thought it was stupid, and deleted it, but now I think it might be relevant again :P

If you have react-native linked I think it will warn every time you create a new project (here's why I deleted it, I'm not sure, but I think so), anyway another way that it'd happen would be:

```sh
if [[ "$(pwd | grep $(npm get prefix))" != "" ]]; then
  echo "WARNING: ..."
fi
```

**Comment by frantic** [comment]
Good stuff! cc @vjeux

**Comment by vjeux** [comment]
Hmm, i already added a warning about this, didn't I?

**Comment by dbanck** [comment]
Found your commit 0a5967dbfe8629074297f8ec5d85dd5d70a91a79 from 6 days ago.

But the reference has been removed from `package.json` 4 days ago: https://github.com/facebook/react-native/commit/0686b0147c8c8084e4a226b7ea04585362eccea8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L42

So maybe call `wrong-react-native.js` on postinstall, too?

**Comment by brentvatne** [comment]
@vjeux - I tried out a `npm i -g react-native` yesterday and didn't get a warning, so this or #889 still needs to make it in :smile:

@dbanck - sorry for the delay, can you please rebase this?

**Comment by vjeux** [comment]
Woops, I need to publish a new version of react-native-cli. I'll do that when i release 0.15.0

**Comment by paramaggarwal** [comment]
Reminder to publish new version of `react-native-cli` - npm says latest was two months ago!

**Comment by brentvatne** [comment]
@vjeux ^

**Pull request closed without merging**
