### PR TITLE
Add Kiwiship app

### PR DESCRIPTION
**Pull request by allanjsx**
Add Kiwiship app to showcase page.

Kiwiship app is powered purely by RN and currently available on iOS platform.

### CODE REVIEW

**Comment by ide** [comment]
Can you keep the alphabetical ordering? Thanks!

**Comment by grabbou** [comment]
@facebook-github-bot cla

**Comment by grabbou** [comment]
In case our new command didn't work, @allanjsx if you could sign the CLA if you haven't yet it would be great. Once that's done, we will be able to proceed with this PR further.

**Comment by allanjsx** [comment]
Done signing CLA. Thank you!

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by allanjsx** [comment]
I don't see this change is live... when is the deployment scheduled? @janicduplessis

**Comment by janicduplessis** [comment]
Now that the website is versioned it won't show up on the website until we release the next version so 0.26 in this case. You can probably see it if you choose the master version of the site http://facebook.github.io/react-native/releases/next/showcase.html.

This part of the website should probably not be versioned but I'm not sure how we could do that with the current setup.

**Pull request closed without merging**
