### PR TITLE
Add Splash to Showcase

### PR DESCRIPTION
**Pull request by alexleventer**
Add an additional react native app to the showcase page.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by brentvatne** [comment]
Hello @alexleventer! Congrats on the app :) Could you put this in alphabetical order? And while you're there I noticed there's a couple that are out of order, could you sort those out? Thanks! :pray:

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by alexleventer** [comment]
@brentvatne done 💯

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
@alexleventer updated the pull request.

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/461695857358795/int_phab) to review.

**Pull request closed without merging**
