### PR TITLE
AHKNavigationController

### PR DESCRIPTION
**Pull request by yamill**
This enables **NavigatorIOS** swipe-back when Navigation Bar is hidden.
**Issue:** https://github.com/facebook/react-native/issues/1341

See: https://github.com/fastred/AHKNavigationController for more detail

### CODE REVIEW

**Comment by insraq** [comment]
I've manually patched this with RN 0.20. Works perfectly. Can we have this merged into the core? Thanks!

**Comment by insraq** [comment]
Actually you have to add those files to the xcode project file.

**Comment by yamill** [comment]
@insraq thanks for catching that! :+1: i just added it to the xcode project. hopefully this will get merged into the core.

**Comment by satya164** [comment]
cc @nicklockwood

**Comment by mkonicek** [comment]
This is a large PR and the NavigatorIOS is not maintained by Facebook so I don't think anyone has bandwidth to review this.

Posted in this read-only group, feel free to follow along there:
https://www.facebook.com/groups/reactnativeoss/permalink/1533536423609653

**Comment by facebook-github-bot-1** [comment]
@AaaChiuuu would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
Actually I'll close this since the NavigatorIOS is not maintained. Feel free to copy the NavigatorIOS code into your project and modify it there, or fork it on your GitHub account.

**Comment by mkonicek** [comment]
Thanks for understanding!

**Pull request closed without merging**
