### PR TITLE
Make react-native work with react v15 rc

### PR DESCRIPTION
**Pull request by chentsulin**
React v15 rc is out. It's worth to provide early access for testing on v15.

### CODE REVIEW

**Comment by lelandrichardson** [comment]
if you change it to:
```
^0.14.5 || ^15.0.0-rc
```

I *think* it will work with all rc versions. For example: https://github.com/airbnb/enzyme/blob/master/package.json#L83

**Comment by chentsulin** [comment]
@lelandrichardson Will `^15.0.0-rc.1` work with `15.0.0-rc.2`? I am not sure about this
https://github.com/reactjs/react-redux/blob/master/package.json#L98

**Comment by ide** [comment]
Last I remember, npm doesn't fully honor semver when it comes to peer dependencies. Their recommendation is for the React team to release 15.0.0 without the prelease `-rc` suffix, but to keep `react@latest` pointing at 0.14.x. I don't get what we gain from npm's ignoring of semver for peer deps but that's the way things work currently.

**Comment by lelandrichardson** [comment]
@ide i think this is a good strategy as well, however react seems to be using the `-rc` suffix anyway. Nevertheless, we checked and npm does seem to match `1.2.3-rc.1` and `1.2.3-rc.2` to a `^1.2.3-rc` semver range.

**Comment by skevy** [comment]
@spicyj do you forsee any issue with upgrading the RN react dep? I'm not crazy familiar with changes in React 15 and how they may affect RN.

**Comment by spicyj** [comment]
It will definitely require some work.

**Comment by spicyj** [comment]
I would be shocked if you can run any app with this change as-is.

**Comment by skevy** [comment]
That's what I was thinking...

@chentsulin have you tested this change?

**Comment by chentsulin** [comment]
Not yet...so should we update devDependencies to v15 and see which tests is failed?

**Comment by spicyj** [comment]
@sebmarkbage is working on it and is pretty far along already. There's a lot of changes so probably not easy to do by just hunting tests.

**Pull request closed without merging**
