### PR TITLE
Fix transform order

### LINKED ISSUE #9073: Transform Order Backwards
To make a diamond shape, I would expect the following to work.

``` js
transform: [
  { rotate: '45deg' },
  { scaleY: 0.5 },
],
```

However, this does not work. It seems to be doing the transforms in the reverse order, as reversing it achieves the desired result.

### PR DESCRIPTION
**Pull request by jacobp100**
Fixes #9073.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @asmockler and @davidaurelio to be potential reviewers.

**Comment by javache** [comment]
The CircleCI failure here seems correct

```
There was 1 failure:

1) testTransformations(com.facebook.react.tests.ViewRenderingTestCase)

junit.framework.AssertionFailedError: expected:<5.0> but was:<5.47942>

	at junit.framework.Assert.fail(Assert.java:50)

	at junit.framework.Assert.failNotEquals(Assert.java:287)

	at junit.framework.Asser--------- beginning of /dev/log/main
```

**Comment by facebook-github-bot-2** [comment]
@jacobp100 updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@jacobp100 updated the pull request.

**Comment by jacobp100** [comment]
Reversing the order of transforms seems to fix the issue. I have no idea why though. 🤔

**Comment by facebook-github-bot-3** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @bestander as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by bestander** [comment]
@javache does this look right now?

**Comment by javache** [comment]
I'm not sure what the correct behaviour should be here. Given that a unit test needs to be changed to make tests pass, this means any product code using multiple transforms will be broken by this change. It would seem safer to me to just update the docs and mention the reversed order.

**Comment by hramos** [comment]
Ping @jacobp100, would you consider documenting the reversed order instead?

**Comment by ericvicenti** [comment]
We can run a codemod that reverses the transform order for you. I took a stab at it here: 

https://astexplorer.net/#/wwxpzrcHhZ

**Comment by lacker** [comment]
It seems like the current behavior is that transforms apply in the reverse order as the list. That doesn't necessarily seem wrong, and it's a breaking change to apply it, so let's just not do it. It seems like most if not all commenters agree here. I'm going to close this pull request but if there's a clean way to do this please feel free to reopen it.

**Pull request closed without merging**
