### PR TITLE
Fix caching of task bundleJsAndAssets

### PR DESCRIPTION
**Pull request by SimonSimya**
## Summary
Fixes https://github.com/facebook/react-native/issues/24330

## Changelog

[Android] [fixed] - Fixed https://github.com/facebook/react-native/issues/24330

## Test Plan

1. Build the app via `./gradlew assembleRelease`
2. Build the app again via `./gradlew assembleRelease` without changes
3. Task `bundleReleaseJsAndAssets` is UP-TO-DATE

I tested with multiple flavors. It works when cleaning the build before and with all subsequent builds.

### CODE REVIEW

**Comment by dulmandakh** [comment]
Could you please add description. Did you tested the change?

**Comment by SimonSimya** [comment]
@dulmandakh just edited the description

**Comment by dulmandakh** [comment]
how do you handle a case where asset is removed or not used anymore?

**Comment by SimonSimya** [comment]
If assets are removed or added, gradle will automatically run the task again because the input has changed. More information here: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_inputs_outputs

**Comment by cpojer** [comment]
Ah, actually @SimonSimya: do you mind signing the CLA? Just go to http://code.facebook.com/cla and follow the steps. Once that's done, I can merge your PR :)

**Comment by cpojer** [comment]
Unfortunately we cannot merge PRs without a CLA :( Let me know if you have a chance to sign it and I will reopen it.

**Comment by amank22** [comment]
Although this change is outdated (with few extra deleteDirs added), is there any chance we can reopen this?

**Comment by cortinico** [comment]
> Although this change is outdated (with few extra deleteDirs added), is there any chance we can reopen this?

You can re-submit this PR @amank22

**Comment by amank22** [comment]
I tried the changes on my company project with AGP 7.1.3
Rn version: 0.65.1
Found few issues (maybe because of setup issues or latest agp, not sure)
```
- Gradle detected a problem with the following location: '<<path>>/APP-Afore'. Reason: Task ':mobile:bundleBuildReleaseJsAndAssets' uses this output of task ':rn-fetch-blob:writeReleaseAarMetadata' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Invalidating VFS because task ':mobile:bundleBuildReleaseJsAndAssets' failed validation
Not watching anything anymore
Watching 0 directory hierarchies to track changes

Caching disabled for task ':mobile:bundleBuildReleaseJsAndAssets' because:
  Caching has been disabled to ensure correctness. Please consult deprecation warnings for more details.

Task ':mobile:bundleBuildReleaseJsAndAssets' is not up-to-date because:
  Incremental execution has been disabled to ensure correctness. Please consult deprecation warnings for more details.

```

Maybe there are other things which needs to be done. Was about to give a PR but will see if I can find something more in detail.

Thanks

**Pull request closed without merging**
