### PR TITLE
[RFC] Trigger red boxes for all promise rejections

### PR DESCRIPTION
**Pull request by davidaurelio**
This change will trigger red boxes instead of yellow boxes for all promise rejections.

At Facebook, we found that rejected promises aren't usually used for application logic and almost always represent a programming error.
Browsers, in general, also show rejected native Promises as errors.

I’ve put this up for discussion.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @skevy to be a potential reviewer.

**Comment by skevy** [comment]
Generally, I think this is fine. It would be nice to opt into (or maybe opt out of) it? I wonder if we could leave an implementation that doesn't hard error, to give people (power users I guess) the option to do `global.Promise = require('PromiseWarnOnRejection');` or something.

**Comment by davidaurelio** [comment]
cc @ide @sahrens @spicyj

**Comment by ide** [comment]
> rejected promises aren't usually used for application logic and almost always represent a programming error

Could you elaborate a bit more on this? When I think of unhandled rejections, I imagine cases where someone writes `fetch('/my-logging-endpoint', someAnalyticsData)` and doesn't add an error handler either because they forgot or they don't need one. Or when people create a promise in one tick of the event loop and add handlers in another.

> Browsers, in general, also show rejected native Promises as errors.

With RN we're covering up the whole screen and making the app temporarily unusable for that moment, which is a lot heavier than an error message in the web console. If there are more non-fatal errors (as opposed to warnings) of this nature maybe we could add a new type of box that is colored red and has the behavior of the yellow boxes.

**Comment by spicyj** [comment]
The most common reason this is important is for code like:

```
fetch(...)
  .then((resp) => {
    this.setStat({  // should be setState
      resp: resp,
    });
  });
```

where the callback throws and it goes into a black hole. Even if you are reasonably diligent about error handling and write like

```
fetch(...)
  .then((resp) => {
    this.setStat({  // should be setState
      resp: resp,
    });
  })
  .catch((e) => {
    this.setStat({  // should be setState
      error: e,
    });
  });
```

then because the catch block throws, the error is still swallowed silently. This is a huge problem for us because exceptions go unreported.

**Comment by sahrens** [comment]
I think the way we handle console.error is a separate issue from handling promise rejections.

What do you think about universally moving console.error to the YellowBox system instead of full-screen RedBoxes?

**Comment by satya164** [comment]
@spicyj 

How about if we Redbox in case of certain types of errors in promise rejection instead of all errors? For example, in your example, it's always a `ReferenceError`.

**Comment by facebook-github-bot-2** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @skevy as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by spicyj** [comment]
I think it would be better to do it for all exceptions since any exception can disrupt your code flow.

**Comment by satya164** [comment]
@spicyj personally in my code, there are many places where I don't care/need to handle promise rejections. With all rejections producing redbox, it'll force me to add error handlers everywhere which do nothing.

**Comment by spicyj** [comment]
Can you give an example? I tend to think of promise rejections as akin to thrown errors, and if you wanted to silence those then an empty `catch (e) {}` would be a best practice.

**Comment by satya164** [comment]
@spicyj for example when I'm sending a post request for analytics or some kind of logging, I don't need to handle the failure

**Comment by mehcode** [comment]
Just going to throw in my 2 cents towards treating promise rejections as a general exception. If you want to ignore an exception you would wrap it with an empty `catch {}`; the parallel should apply here with `.catch()`.

This makes even more sense with `async/await` as `await` translates a rejection into an exception.

**Comment by sahrens** [comment]
I think a failed/rejected network request is kind of a special case, but really should also be handled - you should log those failures and track them so you can monitor the health of your app/server.

The main problem is that if you do something clowny inside a promise chain, the exception shouldn't just get swallowed, it should RedBox like any other exception would.

**Comment by rops** [comment]
I'd love to see this change in. Hunting down exceptions swallowed in a promise chain is not fun at all.

**Comment by lacker** [comment]
What's wrong with the current behavior of yellow-boxing this? A lot of folks are saying they want to be able to debug this, but you can still use the yellow box to debug. Browsers log a warning to the console when you ignore a rejected promise; they don't throw up a full-screen error. So I think the current behavior is more in tune with how promises are expected to behave.

**Comment by lelandrichardson** [comment]
> > rejected promises aren't usually used for application logic and almost always represent a programming error
> Could you elaborate a bit more on this? When I think of unhandled rejections, I imagine cases where someone writes fetch('/my-logging-endpoint', someAnalyticsData) and doesn't add an error handler either because they forgot or they don't need one. Or when people create a promise in one tick of the event loop and add handlers in another.

Is this really true though? I think the spec of `fetch` is that it only rejects the promise in cases of network connectivity issues or timeouts. If the server responds with a 500 etc the promise "resolves" not "rejects". I feel like network connectivity issues may be something that you don't care about, but normally I think people should. If you really want to, you could create a small wrapper around `fetch` that catches, and just use that instead.

We could also create a sensible white-list of error types that we are okay with `console.warn`ing, and then for the rest (ie, `ReferenceError`) we would redbox.

Thoughts?

**Comment by lacker** [comment]
> I feel like network connectivity issues may be something that you don't care about, but normally I think people should.

Sure - but you can care about that just as easily with a yellow box. A red box makes sense if there's no further debugging value you can get from running the application. With a rejected promise, however, it's quite likely that continuing to run the application is useful. That's why I think yellowboxing is the right behavior. The question isn't "is it totally fine to ignore rejected promises", the question is whether an error like this should block further execution of the application.

**Comment by ericvicenti** [comment]
I really think we should land this. You can always close a redbox and keep running the application when this happens- and it will really encourage people to catch potential problems in their app!

Plus, this does not affect production, where an unhandled promise rejection would happen in the background without crashing the app.

**Comment by hramos** [comment]
@ericvicenti @lacker seems like you both disagree on whether this is the right behavior. Let me know how you want to proceed.

**Comment by ericvicenti** [comment]
I really think we should push this forward. I think we want all runtime errors to be "in-your-face" bad, even in rejected promises.

**Comment by ide** [comment]
@ericvicenti I buy that, this is how I think of it: We want to treat sync and async errors similarly. This is consistent with Chrome and Node (in a coming release). So since we redbox on sync JS errors, it would follow we'd redbox on async JS errors too (in practice this means unhandled promise rejections since they're the mechanism for async fns).

The next thing to figure out is what to do when there is an unhandled error (regardless of whether it's sync or async). Node crashes the process, Chrome keeps it alive and prints a red stacktrace to the console. If the redbox is too disruptive, especially for large teams where someone might be in the middle of fixing an error while the rest of the team is working, we could combine the behavior of the yellowbox with the color of the redbox. That would help errors stand out from warnings, be very visible, and be less disruptive to a team.

**Comment by sahrens** [comment]
Would it be hard to make it easily configurable? I think we want async errors to fully redbox at FB (crash in prod) because otherwise it leaves the app in a potentially undefined state, but other groups may not want that.

**Comment by sahrens** [comment]
And if it ends up crashing all the time, then we can switch to the softer behavior as well while we fix things :)

**Comment by satya164** [comment]
@sahrens YellowBox allows ignoring errors. Maybe we can do similar for Redbox.

**Comment by ericvicenti** [comment]
@satya164, the redbox also allows ignoring of error, doesn't it? Just hit escape or 'cancel' on the redbox and it closes.

**Comment by satya164** [comment]
@ericvicenti I mean ignore them so that they don't appear at all,

```js
console.ignoredYellowBox = ['Some warning text you want to ignore'];
```

**Comment by hramos** [comment]
Have we reached any consensus? Do you want to wait until some sort of ignore configuration setting is added before landing this?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/rfc-trigger-red-boxes-for-all-promise-rejections

**Pull request closed without merging**
