### PR TITLE
Improve e2e tests on Android

### PR DESCRIPTION
**Pull request by grabbou**
This PR adds `Live Reload` tests to our e2e-tests on Android which makes the process of releasing Android fully automatic w/o a need of any manual actions.

That's a part of the bigger process that I am working on (automating iOS tests as well) and so I've added few helpers / utils to see how the suite could be improved.

@bestander

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @bestander and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@grabbou updated the pull request - [view changes](https://github.com/facebook/react-native/pull/10073/files/c92c65824bd755600d37a41f334ae7d4b3924f56..87dd15207fec7cc363bfbbfda6383e31e71542d8)

**Comment by bestander** [comment]
FYI just selecting `Debug` in dev menu does not really test Chrome Debugging.
This is a bit more complex because for a real test we need Chrome to be available in CI and I don't know how we could write a tests that would verify that it is _really_ working.

So I am not sure that this test actually replaces the need to check it with your own eyes on a real device.

Also e2e failed :)

**Comment by grabbou** [comment]
> So I am not sure that this test actually replaces the need to check it with your own eyes on a real device.

After that test was added to the Appium suite, the guide asking to check `Chrome Debugger` on a real device was removed, so that made me thinking that way. If it's still a need to check it manually, we should reflect that in the release hints.

Anyways, I'll investigate the issues with the CI and let you know.

**Comment by grabbou** [comment]
This is still on track, I am about to rebase it and ship an update. Likely to happen tomorrow as I'll be rolling out new React.

**Comment by mkonicek** [comment]
Nice! Looks like the test failed on CircleCI, not sure if related? https://circleci.com/gh/facebook/react-native/11489?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by grabbou** [comment]
Yep, I'll close that one and re-submit new one when I am ready :)

**Pull request closed without merging**
