### PR TITLE
Update link in Native UI Components (iOS) guide

### PR DESCRIPTION
**Pull request by umhan35**
Update the event mapping link: update line number from 1146 to 1165

### CODE REVIEW

**Comment by vjeux** [comment]
We have flaky tests, this pull request should break anything :(

**Comment by vjeux** [comment]
```
.flowconfig:40 Wrong version of Flow. The config specifies version 0.10.0 but this is version 0.11.0
```

The reason is that we enforce version 0.10.0 but travis brew install the latest available version: 0.11.0. Will find a solution

**Comment by ide** [comment]
@vjeux won't this be a problem for users too? Ex: I run `brew update && brew upgrade`, which automatically gets the latest version of flow (may be used for other projects). As a practical proposal, what if the version in the config were a min version, so flow 0.10 and 0.11 would both be supported but not 0.9?

**Comment by vjeux** [comment]
cc @gabelevi

**Pull request merged**
