### PR TITLE
Add timer usage for es6

### PR DESCRIPTION
**Pull request by sunnylqm**

### CODE REVIEW

**Comment by brentvatne** [comment]
While this is technically correct I'm not a fan of manually doing this on every component that needs `setTimeout` or `requestAnimationFrame` or `setInterval`. At Exponent we use react-mixin on es6 classes for TimerMixin: https://github.com/brigand/react-mixin - cc @ide

**Comment by Kureev** [comment]
@sunnylqm can you please update your PR according to the changes @brentvatne proposed?

**Comment by sunnylqm** [comment]
@Kureev updated

**Comment by Kureev** [comment]
Thanks, @sunnylqm!

Can you also rebase this branch by the current master?

**Comment by sunnylqm** [comment]
@Kureev  I think I've rebased...?

**Comment by Kureev** [comment]
@sunnylqm 

image

**Comment by Kureev** [comment]
@sunnylqm if you'll have problems with the merge, it's also possible to close this PR and create a new one from the latest master (don't forget to make a reference to this one).

**Comment by sunnylqm** [comment]
@Kureev OK, done!

**Comment by Kureev** [comment]
@vjeux @sahrens @sahrens what would be a next action on this PR? It's currently up to date with the master and seems to be a valuable doc change. Can we merge it in?

**Comment by brentvatne** [comment]
There is a typo here: "exsiting" should be "existing"

**Comment by brentvatne** [comment]
I would change...

> However, `TimerMixin` and any other mixins *can not be used on ES6*. You need to use some helper like [react-mixin](https://github.com/brigand/react-mixin) to migarate existing mixins to ES6 classes.

to...

> Keep in mind that if you use ES6 classes for your React components [there is no built-in API for mixins](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#mixins). To use `TimerMixin` with ES6 classes, we recommend [react-mixin](https://github.com/brigand/react-mixin).

**Comment by Kureev** [comment]
@brentvatne done!

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
