### PR TITLE
Fix crashes onKeyPress Android

### PR DESCRIPTION
**Pull request by joshyhargreaves**
## Motivation
There appear to be two different types of crashes related to the recent addition of `onKeyPress` on Android introduce in `0.53`. This PR addresses the cause of both of them.

Firstly, it seems possible to get an `indexOutOfBoundsException` with some 3rd-party keyboards as observed in https://github.com/facebook/react-native/issues/17974 & https://github.com/facebook/react-native/issues/17922. I have simplified the backspace determining logic slightly, and also put in an explicit check for zero case so it is not possible to get an indexOutOfBoundsException & it should make sense in the context of the onKeyPress logic.

Secondly, it appears that `EditText#onCreateInputConnection` can return null. In this case, if we set `null` to be the target of our subclass of `ReactEditTextInputConnectionWrapper`, we will see the crashes as seen [here](https://github.com/facebook/react-native/issues/17974#issuecomment-368471737), whereby any of methods executed in the `InputConnection` interface can result in a crash. It's hard to reason about the state when `null` is returned from `onCreateInputConnection`, however I would might reason that any soft keyboard input cannot update the `EditText` with a `null` `input connection`, as there is no way of interfacing with the `EditText`. I'm am not sure, if there is a later point where we might return/set this input connection at a later point? As without the `InputConnection` onKeyPress will not work. But for now, this will fix this crash at least.

## Test Plan
I have not managed to reproduce these crashes myself yet, but users have confirmed that the `indexOutOfBounds` exception is fixed with the 'zero' case and has been confirmed on the respective issues https://github.com/facebook/react-native/issues/17974#issuecomment-368471737.

For the `null` inputConnection target case, I have verified that explicitly setting the target as null in the constructor of `onCreateInputConnection` results in the same stack trace as the one linked. Here is also a [reference](https://github.com/stripe/stripe-android/pull/392/files#diff-6cc1685c98457d07fd4e2dd83f54d5bb) to the same issue closed with the same fix for another project on github.

It is also important to verify that the behavior of `onKeyPress` still functions the same after this change, which can be verified by running the RNTesterProject and the `KeyboardEvents` section in `InputText`.
The cases to check that I think are important to check are: 
- Cursor at beginning of input & backspace
- Return key & return key at beginning of input
- Select text then press delete
- Selection then press a key
- Space key
- Different keyboard types

This should not be a breaking change. 

## Release Notes
 [ANDROID] [BUGFIX] [TextInput] - Fixes crashes with TextInput introduced in 0.53.

### CODE REVIEW

**Comment by kelset** [comment]
It looks like the only test that failed is because of bad credentials :/

But thanks for your PR @joshyhargreaves!

**Comment by hramos** [comment]
The bad credential issue is fixed on master. It's OK to ignore the failing step, as it's only trying to run Danger, our PR linter. Everything else appears to check out.

**Comment by joshyhargreaves** [comment]
@hramos do you think it's worth also landing this PR on 0.54?

**Comment by hramos** [comment]
@joshyhargreaves I opened #18128 where we can discuss further.

**Comment by grabbou** [comment]
Since it appears to me that some of the crashes were affecting users on `0.53.x`, do you think we should backport it there too?

**Comment by kelset** [comment]
TBH I think it should depend on how 'breaking' is upgrading to 0.54. If it's a big jump then it may be worth it, if it's ex. only upgrading Flow then no need.

**Comment by grabbou** [comment]
Yeah, let's actually wait for someone to request it (esp. who is blocked) than being proactive in this space.

**Comment by krewllobster** [comment]
I am experiencing this bug using react-native 0.53.0. I get the following stack trace after app crashes when deleting text in a <TextInput /> element. Running on a USB connected Moto X2 via "react-native run-android". Is there a way for me to get this patch without upgrading to react-native 0.5.4?

Stack Trace

java.lang.IndexOutOfBoundsException: charAt: -1 < 0
at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:117)
at com.facebook.react.views.textinput.ReactEditTextInputConnectionWrapper.setComposingText(ReactEditTextInputConnectionWrapper.java:104)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by adhithiravi** [comment]
We are experiencing this crash too. Any plans on merging this PR soon?

**Comment by adhithiravi** [comment]
Do you know when this will be merged over, this crash is affecting us on android.

**Comment by hramos** [comment]
This fix has been on master for close to a year.

**Pull request closed without merging**
