### PR TITLE
okhttp version 3.12.12

### PR DESCRIPTION
**Pull request by halaei**
## Summary

This updates okhttp to the newest compatible version with a couple of fixes and improvements. See https://github.com/square/okhttp/commits/okhttp_3.12.x

## Changelog

[Android] [Changed] - Update Okhttp to version 3.12.12

## Test Plan

Current tests should pass.

### CODE REVIEW

**Comment by dulmandakh** [comment]
please bump okhttp in Buck too, so that CI can use it

**Review by dulmandakh — APPROVED** [review]
@mdvacca please review and merge

**Comment by dulmandakh** [comment]
@mdvacca @fkgozali it looks like this PR would fix many crashes according to OkHTTP changelog, please merge it as soon as possible https://square.github.io/okhttp/changelog_3x/#version-3126

**Comment by jgreen210** [comment]
(I'm a RN user trying to resolve an okhttp/okhttp-urlconnection version conflict between react-native (which wants a 3.x version) and another library (which wants a 4.x version). I need to decide whether to force use of 3.x or 4.x in our app, with both choices potentially breaking something, based on semver.)

So, is someone able to elaborate on why the "newest compatible version" of okhttp etc. isn't a 4.x version?

I've checked the open github issues mentioning "okhttp", plus the recent closed ones, and while there is https://github.com/facebook/react-native/issues/27282, it doesn't explain what problems exist with 4.x.

**Comment by halaei** [comment]
@jgreen210 I am not sure, maybe okhttp 4.x doesn't work on Android < 5.0? React Native supports Android >=4.1.
https://github.com/square/okhttp#requirements

**Comment by mikehardy** [comment]
@jgreen210 - @halaei is exactly right. react-native minSdkVersion is API16 so they must stay on the 3.12.x okhttp branch

**Pull request closed without merging**
