### PR TITLE
[Android] Added Happy Eyeballs for address selection

### LINKED ISSUE #32730: Android `fetch` hangs indefinitely with IPv6 hosts
### Description

This is a very bizarre issue that has been previously reported a bunch of times, and this is basically a continuation of:

https://github.com/facebook/react-native/issues/29608

I initially started running into this on RN 0.66 with AWS Cognito. Bumping to 0.66.3 didn't help.

I'm also pretty sure this used to work before and I'm not sure when it broke. It's on an app that has been shelved for a while. 

The problem is very strange because the network request does not seem to be issued, but simply hitting CMD+S to save any file so that a hot-reload is issued will immediately dispatch the network request.

I discovered the promise hanging issue by adding some logs to the `fetch` calls the cognito library was doing:
image
Notice how the `.then` is not executed.

While troubleshooting I came across a mention here of a workaround: https://github.com/facebook/react-native/issues/29608#issuecomment-884521699 (courtesy of @danmaas) which seems to completely resolve the issue.

Here's the same `.then` correctly being executed after applying that patch:
image

### Version

0.66.3

### Output of `react-native info`

```
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 142.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /private/var/folders/9p/k1yqxx0d7rn1nlztg_wm7sbw0000gn/T/xfs-2dcae145/node
    Yarn: 2.4.0-git.20210330.hash-ebcd71d5 - /private/var/folders/9p/k1yqxx0d7rn1nlztg_wm7sbw0000gn/T/xfs-2dcae145/yarn
    npm: 7.20.1 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2021.11.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /Users/andreialecu/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I'm able to reproduce it with this:

```
  React.useEffect(() => {
    console.log('confirm start', new Date());
    fetch('https://cognito-idp.eu-west-1.amazonaws.com/', {
      method: 'POST',
      mode: 'cors',
    })
      .then(() => console.log('then', new Date()))
      .catch(() => console.log('catch', new Date()));
    setTimeout(() => {
      console.log('5 seconds passed');
    }, 5000);
  }, []);
```
Output:
Screenshot 2021-12-09 at 19 29 06

After applying https://github.com/facebook/react-native/issues/29608#issuecomment-884521699:
Screenshot 2021-12-09 at 19 30 32

### Snack, code example, screenshot, or link to a repository

_No response_

### PR DESCRIPTION
**Pull request by marcesengel**
## Summary

PR #32889 to main.

## Changelog

- Added Happy Eyeballs (https://datatracker.ietf.org/doc/html/rfc8305#section-5), missing usage of historical data - fixes #32730 

[Android] [Feature] - Added Happy Eyeballs for network request target address selection

## Test Plan

See #32889.

### CODE REVIEW

**Comment by cortinico** [comment]
Thanks for opening this PR @marcesengel 
I believe we should not introduce an Happy Eyeball implementation inside React Native at this stage. 

Square's OkHTTP are going to implement Fast fallback in OkHTTP 5.x, which is their implementation of Happy Eyeball:
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-500-alpha4

We should rather:
- Look into bumping our OkHTTP version to the latest stable.
- Potentially try to adapt our codebase to make sure that is OkHTTP 5x compatible. That means that you'll be able to just bump the OkHTTP version to 5.x without having to make any changes or fork RN to make it work.

**Comment by marcesengel** [comment]
Sounds good @cortinico, I wasn't sure how feasible it would be to wait for a major bump of OkHTTP and to introduce it here.

Closing this in favor of the aforementioned procedure :+1:.

In the meantime people can feel free to use my patched branch `marcesengel/react-native#0.66-patched-3`.

**Comment by cortinico** [comment]
> In the meantime people can feel free to use my patched branch `marcesengel/react-native#0.66-patched-3`.

Thanks for suggesting this 👍 

In the meanwhile, would you be up for opening a draft PR with the OkHTTP bump to 5.x alpha? It could help us spot early breaking changes and we could test it against the internal infra to make sure nothing breaks.
(That's also a task that someone else in the community can pickup if they wish).

**Comment by marcesengel** [comment]
@cortinico some interesting updates on the matter: https://github.com/square/okhttp/issues/506#issuecomment-1227325306, seems like reddit is using OkHTTP 5.0.4 in production and it's going smoothly.

Sadly last time I checked I couldn't build RN on my M1 machine, so unless this changed I won't be able to contribute anything anytime soon :(

**Comment by cortinico** [comment]
> Sadly last time I checked I couldn't build RN on my M1 machine, so unless this changed I won't be able to contribute anything anytime soon :(

You should now be able without any problems.

> seems like reddit is using OkHTTP 5.0.4 in production and it's going smoothly.

They're still using the alpha which is considered "good enough" for production.

**Comment by marcesengel** [comment]
> You should now be able without any problems.

😍 

> They're still using the alpha which is considered "good enough" for production.

Yup - this ready like the React team won't make this move unless it's stable? Would be a shame imo, as this really breaks stuff for a lot of consumers.

**Comment by cortinico** [comment]
> Would be a shame imo, as this really breaks stuff for a lot of consumers.

What is preventing a consumer to bump OkHTTP version to whatever they wish?

**Comment by cortinico** [comment]
> I meant to say that it'd be a shame if the React team doesn't want to make the move to 5.0.4 [because it's alpha], as NOT having 5.0.4 breaks stuff for a lot of consumers [of react-native powered apps].

Can you clarify on "breaks stuff for a lof of consumer"? Is there anything beyond Happy Eyeball? Also I invite you to raise this issue upstream on OkHTTP to promote the latest release to stable if it's so crucial.

Also, my question still holds:

> What is preventing a consumer to bump OkHTTP version to whatever they wish?

Users should be able to update OkHTTP version regardless of the one we ship inside RN. If this is not possible, that's something we can look into, as I mentioned in one of my preivous comments:

> Potentially try to adapt our codebase to make sure that is OkHTTP 5x compatible. That means that you'll be able to just bump the OkHTTP version to 5.x without having to make any changes or fork RN to make it work.

**Comment by marcesengel** [comment]
> Can you clarify on "breaks stuff for a lof of consumer"?

Yes. There are quite a few ISPs (at least in Germany) where IPv6 isn't working properly. If a customer uses this kind of network, they are waiting a very long time until all their IPv6 requests have timed out and only then they can get a server response (when the first IPv4 address is tried).

> Users should be able to update OkHTTP version regardless of the one we ship inside RN. If this is not possible, that's something we can look into, as I mentioned in one of my preivous comments:

I didn't know that was possible without building RN yourself. In my opinion it'd still be very beneficial to have the issue described above fixed by default and not requiring to fiddle with RN for this.

**Comment by cortinico** [comment]
> I didn't know that was possible without building RN yourself. In my opinion it'd still be very beneficial to have the issue described above fixed by default and not requiring to fiddle with RN for this. I understand however that company policy states not to use 3rd party libs while in alpha.

It's possible as you can just specify a dependency on your `build.gradle` and the higher version of OkHTTP will override the one provided by React Native

**Pull request closed without merging**
