### PR TITLE
Added `resizeMode` to <Image> documentation

### PR DESCRIPTION
**Pull request by cloudrave**
The `resizeMode` property of the `<Image>` component is currently undocumented.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @davidaurelio and @JoelMarcey to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by Bhullnatik** [comment]
It is actually documented, you were looking at the [general Images guide](http://facebook.github.io/react-native/releases/0.31/docs/images.html) rather than the documentation of the [`Image` component](http://facebook.github.io/react-native/releases/0.31/docs/image.html#resizemode).

**Comment by cloudrave** [comment]
Oh, that is embarrassing.  Sorry.

**Pull request closed without merging**
