### PR TITLE
Added ability to build website per pull request

### PR DESCRIPTION
**Pull request by bestander**
This change allows building docs website for every pull request and deploys it to github.com/facebook/react-native-pr-docs gh-pages branch.

After CI runs all tests, it builds the website and pushes it to `facebook.github.io/react-native-pr-docs/releases/<pr-number>`.

Required for this to work:
- create repo github.com/facebook/react-native-pr-docs and allow reactjs-bot to push to it
- enable gh-pages feature for that repo

Further improvements:
- build a sciprt similar to bots/code-analysis-bot.js that posts a comment with link to website generated for this PR
- deploy website only if there are any changes compared to master branch

### CODE REVIEW

**Comment by bestander** [comment]
cc @vjeux @knowbody

**Comment by knowbody** [comment]
You're awesome. Hats down 👒

**Comment by vjeux** [comment]
Wahhhh, already oO

Code looks good to me :)

**Comment by mkonicek** [comment]
@bestander Is this good to go?

**Comment by bestander** [comment]
not yet, I need to set up a private repo for PR websites, will get back to this next week

**Comment by mkonicek** [comment]
@bestander :+1:

**Comment by bestander** [comment]
1. We need to set up a technical GH repo to host the PRs website
2. FB works on a big docs revamp, so maybe this task will become outdated soon

**Comment by bestander** [comment]
Ok, so I've spent a couple of hours working on this PR.

I created a private github repo and if someone pushes a commit to its `gh-pages` branch, we will get website generated at e.g. https://facebook.github.io/react-native-pr-docs/releases/6572/.

The script is ready to be used but we can't execute it via Circle CI because it would compromise a write key to the private repo and malicious actors could obtain the key.
We could reduce the risk by creating a throw-away account with access to only one repo for PR builds but it seems wrong may cause a genuine key leak if someone changes the code without having full context.

@caabernathy proposed an idea that our @facebook-github-bot  could actually run this script instead of CircleCI, thus keeping the deployment key safe.
@facebook-github-bot has hooks on the PR lifecycle, so it can trigger the script execution when PR is created and trigger cleanup when PR is closed.
Also the bot has access to commenting on the Pull Request and it can post comment with a link to the PR docs website.

Does anyone think it is worth another day of github-bot hacking to pull it through or building website for PRs is not that useful to us?

**Comment by mkonicek** [comment]
@bestander This seems very cool! We sometimes ask people to test their doc changes locally and attach a screenshot. This way everyone could easily see what the docs will look like.

**Comment by bestander** [comment]
I struggle to finish this PR because of the extra infra required to make this work.
It is not hard but prone to become broken any moment keys or scripts get moved around.

Let's close this until OSS team is ready to work on website tools again.

**Pull request closed without merging**
