### PR TITLE
extracted buildModuleSchema in parsers-common.js

### PR DESCRIPTION
**Pull request by dakshbhardwaj**
## Summary
This PR is a task from #34872 

> Extract the buildModuleSchema function ([Flow](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/modules/index.js#L571), [TypeScript](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/typescript/modules/index.js#L584))in the parsers-commons.js function. The two functions are almost identical except for the filter(property =>) at the end of the function, which is different based on the language.

## Changelog
[Internal] [Changed] - Extract the function isModuleRegistryCall in parsers-common.js

## Test Plan
I tested using Jest and Flow commands.

### CODE REVIEW

**Comment by cipolleschi** [comment]
Hi @dakshbhardwaj, thank you for taking this.

Just a question: are you sure you added/committed all the changes? I can see the new function in the `parsers-common.js`, but I can't see it used, nor the same code removed from the other files.
Could you double check that please? :pray:

**Comment by dakshbhardwaj** [comment]
> Hi @dakshbhardwaj, thank you for taking this.
> 
> Just a question: are you sure you added/committed all the changes? I can see the new function in the `parsers-common.js`, but I can't see it used, nor the same code removed from the other files. Could you double check that please? 🙏

Hi @cipolleschi i haven't removed it from the other files because this pr has dependency from the other tasks as some other functions are also needed to be moved to `parsers-common.js` so i'll push the code once those pr's are merged

**Comment by Pranav-yadav** [comment]
Hey @dakshbhardwaj !

Just heads up, the dependent changes are merged :)

**Comment by cipolleschi** [comment]
@dakshbhardwaj could you please rebase on top of `main`, please?

**Comment by cipolleschi** [comment]
gentle ping to @dakshbhardwaj, are you still interested working on this?

**Comment by cipolleschi** [comment]
Closing this as the author is not responsive.

**Pull request closed without merging**
