### PR TITLE
Update Fresco to 0.13.0

### PR DESCRIPTION
**Pull request by charpeni**
Update Fresco to 0.13.0 in gradle and BUCK, also update documentation about GIF and WebP support.

### Test plan
1. `react-native init`
2. Add a GIF and a PNG into the first view. It works fine.
3. Update Fresco into RN.
4. Build from source.
5. Everything works fine and we don't need ProGuard fix anymore.

cc @oprisnik @foghina

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @andreicoman11 to be potential reviewers.

**Comment by satya164** [comment]
cc @bestander

**Comment by andreicoman11** [comment]
@oprisnik already has a diff for this internally, let's land that one instead.

**Comment by charpeni** [comment]
@oprisnik @andreicoman11 Any news?

**Comment by oprisnik** [comment]
We didn't go with my 0.13 update since we wanted to upgrade directly to 0.14.1. Unfortunately, there are some issues with that. We've updated the Android support library for Fresco but updating it for RN is not trivial due to API changes.

See also #7791.

cc @mkonicek

**Pull request closed without merging**
