### PR TITLE
Added section concerning open source applications to showcase

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Hi there,

I would like to add a section about open source applications to the showcase page. The discussion concerning this matter took place in #6887.

### CODE REVIEW

**Comment by manonthemat** [comment]
You did not add *No Fluff: Hiragana* to the open source app block. As an alternative, these apps could've been included in the regular manner and just add the source property to showcase their source repository.

**Comment by dsibiski** [comment]
I think the idea of the original issue was to showcase open source app repos to help people get started and to see good examples of apps that they can clone immediately in Github. Not exactly to showcase the ones that are actually in the App Stores...at least that's my take on it.

Here is the original tweet that started it going:

> Should there be a curated list of RN apps that are complete open source? It's super helpful to people getting started

https://twitter.com/jordwalke/status/718541198122569728

**Comment by dsibiski** [comment]
@DanielMSchmidt Nevermind my comment above, I misread your last comment in the related issue. Carry on! :+1:

**Comment by chirag04** [comment]
@DanielMSchmidt while you are at it do you want to split out the `opensource array` and the `apps array` etc into it's own file? `showcase.js` is getting way too big. we can also sort the list while rendering rather than relying on the users to keep the list sorted.

**Comment by DanielMSchmidt** [comment]
@chirag04 great idea, I will do that!
@manonthemat I will do the first one, i think your second comment would miss the point. Open source apps should stick out in order to help developers find inspiration and improve their learning. all other apps are just there to show the possibilities of react native. maybe we can continue this discussion in the issue I menitioned 😉

**Comment by DanielMSchmidt** [comment]
I updated my PR; it does the following things: 

- added open source apps (with a note to more examples at awesome-react-native)
- added sorting of applications
- moved applications to own files

**Comment by DanielMSchmidt** [comment]
Just saw that circe-ci failed because there is no toUppercase(), will fix that later today!

**Comment by facebook-github-bot-6** [comment]
@brentvatne would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by DanielMSchmidt** [comment]
I guess this is no longer needed, as I got no feedback on this issue.

**Pull request closed without merging**
