### PR TITLE
Turbo module codegen support interface like alias in module

### PR DESCRIPTION
**Pull request by ZihanChen-MSFT**
## Summary

Turbo module codegen support interface like alias in module.

In typescript, interface allows inheritance, but the codegen schema doesn't have such information. In this PR the codegen schema is not changed, interfaces are flattened.

In the next change, I will update the codegen schema so that it allows inheritance, in order to generate more precise C++ code.

## Changelog

[GENERAL] [CHANGED] - Turbo module codegen support interface like alias in module

## Test Plan

`yarn jest react-native-codegen` passed

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
Code looks good. Just to double-check: do we need something similar with Components also?

I'm thinking about a component with some props like:

```ts
interface BaseProps {
  sharedProp: number
}

interface iOSProps extends BaseProps {
  iOSProp: number
}

interface AndroidProps extends BaseProps {
  androidProp: number
}
```

If we need it, it is fine to add it in a new PR, though.

**Review by cortinico — APPROVED** [review]

**Comment by ZihanChen-MSFT** [comment]
@cipolleschi Hi, component doesn't support alias, all interfaces or aliases got inlined into the component.

**Comment by migueldaipre** [comment]
Hey Guys, it's released?

**Comment by cortinico** [comment]
> Hey Guys, it's released?

@migueldaipre Nope this will land in 0.72

**Pull request closed without merging**
