### PR TITLE
Animated: Implement toJSON method of Animated

### PR DESCRIPTION
**Pull request by wusuopu**
Fix issue https://github.com/facebook/react-native/issues/7441

### CODE REVIEW

**Comment by ide** [comment]
This might not work well with native Animated values. Perhaps we should make AnimatedValue override `toJSON()` so it can decide the best way to format itself. cc @vjeux

**Comment by wusuopu** [comment]
@ide You are right. Maybe the best way is to override `toJSON()` of AnimatedValue

**Comment by facebook-github-bot-7** [comment]
@wusuopu updated the pull request.

**Comment by ide** [comment]
Looks like a good start.
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/978189145613632/int_phab) to review.

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/978189145613632/int_phab) to review.

**Pull request closed without merging**
