### PR TITLE
Fix link typo to more resources page

### PR DESCRIPTION
**Pull request by seekshiva**

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @lacker to be potential reviewers.

**Comment by charpeni** [comment]
Can you direct your merge into `master` instead of `0.29-stable` ?

**Comment by seekshiva** [comment]
It looks like the above link does not exist in `Networking.md` in master. I can close this PR if you'd like. But it is broken in the current [Networking page in facebook.github.io](https://facebook.github.io/react-native/docs/network.html)

**Comment by hramos** [comment]
@seekshiva it sounds like the issue is fixed in master in that case. It should make the next release cut.

**Pull request closed without merging**
