### PR TITLE
Accessible colors for DynamicColorIOS

### PR DESCRIPTION
**Pull request by birkir**
## Summary

Allow you to harvest the `UIAccessibilityContrastHigh` trait from iOS to show accessible colors when high contrast mode is enabled.

```jsx
// usage

PlatformColorIOS({
  light: '#eeeeee',
  dark: '#333333',
  highContrastLight: '#ffffff',
  highContrastDark: '#000000',
});

// {
//   "dynamic": {
//     "light": "#eeeeee",
//     "dark": "#333333",
//     "highContrastLight": "#ffffff",
//     "highContrastDark": "#000000",
//   }
// }
```

This is how apple's own dynamic system colors work under the hood (https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/#dynamic-system-colors)

---

The react native docs mention that more keys may become available in the future, which this PR is adding:

> In the future, more keys might become available for different user preferences, like high contrast.

https://reactnative.dev/docs/dynamiccolorios

## Changelog

[iOS] [Added] - High contrast dynamic color options for dark and light mode.

## Test Plan

Added unit tests for `normalizeColor` to pass the high contrast colors downstream to RCTConvert

### CODE REVIEW

**Comment by birkir** [comment]
Checks: Unrelated issue with test_windows test.

**Comment by p-sun** [comment]
Looks good! Would you mind renaming it to highContrastDark and highContrastLight since it's more specific and clearer than accessible? Android and Windows also use the words High Contrast.

**Comment by birkir** [comment]
> Would you mind renaming it to highContrastDark and highContrastLight since it's more specific and clearer than accessible? Android and Windows also use the words high contrast.

Current naming comes from Apple's UIColor table in the iOS Human Guidelines.

The UIColor has an "dark" and "light" options, and "accessible" variant for each of those, but they react automatically to High Contrast and Invert Colors traits.

I think overall it's a good suggestion to scope keys by traits. Especially if the API will reach other platforms as well.

Only thing is that colour schemes won't be scoped (the dark and light keys).

If no one disagrees, I'll go ahead and scope the keys!

Thanks for the feedback @p-sun

**Comment by p-sun** [comment]
What does "Only thing is that colour schemes won't be scoped (the dark and light keys)" mean?

**Comment by birkir** [comment]
> What does "colour schemes won't be scoped (the dark and light keys)" mean?

Traits are highly dynamic and can offer a matrix of different values for different states. For example, we can have a scenario where you are in a dark mode, with high contrast enabled, inverted colors, and a P3 display gamut.

Enabling all these keys in the current setup, won't allow you to match more than two of those scenarios, a color scheme, and only one trait.

```jsx
{
  dark: 'red',
  highContrastDark: 'hotpink',
  invertedDark: 'blue',
  gamutP3Dark: '#ff0001'
}
```

Where what you would actually like to do is something like
```objc
[UIColor colorWithDynamicProvider:^UIColor *_Nonnull(UITraitCollection *_Nonnull collection) {
  if (trait.legibilityWeight == UILegibilityWeightBold) {
    return [UIColor whiteColor];
  }

  if (trait.userInterfaceStyle == UIUserInterfaceStyleDark) {
    if (trait.accessibilityContrast == UIAccessibilityContrastHigh) {
      return [UIColor blueColor];
    }
    return [UIColor redColor];
  }
}]
```

I just didn't think it was feasible to try to implement this and went with the simplified version that Apple offers, "accessible".

(this is just an example, inverted colors isn't a trait as of now)

**Comment by p-sun** [comment]
I see! Naming it high contrast makes sense then.

Android only has the ["High Contrast Text" switch](https://support.google.com/accessibility/android/answer/6151855?hl=en) in the settings -- I believe this only changes text colors. So Android developers have even fewer color trait choices than iOS.

**Comment by birkir** [comment]
@p-sun I updated the docs in a new pull request on react-native-website.

The PR is ready for merge on my end ✅

**Pull request closed without merging**
