### PR TITLE
fix lint warnings

### PR DESCRIPTION
**Pull request by trave7er**
added two semi colons, separated from other lint commits to avoid potential conflicts

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
Failed to apply patch D2818391. Conflict when rebasing onto trunk.
@trave7er could you please rebase?

**Comment by mkonicek** [comment]
Failed to merge because bots/code-analysis-bot.js doesn't exist in the fb codebase :( We really need to come up with a good generic solution for this. For now I'll have to ask you to split this into two PRs, each with one file. This is shitty and we'll fix it, thanks for the patience!

**Comment by trave7er** [comment]
np. just updated

**Comment by ide** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
