### PR TITLE
RFC, WIP: Refactor Text into platform-specific files

### PR DESCRIPTION
**Pull request by mkonicek**
Do not review yet.

React Native for Windows is going to be released as a separate npm module. Since the Windows versions of components will have platform-specific prop types and logic, we (Eric Rozell, Nick Lockwood, Konstantin Raev, David Aurelio) decided to split the cross-platform components into:
- a file with code shared by all platforms
- one file per platform with platform-specific code

The approach I'm trying out here is to move the shared code into a mixin. It defines the current `propTypes`, in `Text.windows.js` it will be possible to do the following:

    const Text = React.createClass({
      mixins: [TextBaseMixin],
      propTypes: {
        ...TextBaseMixin.propTypes,
        /**
         * Button on the Xbox controller that can be used
         * to trigger the onPress handler.
         */
        xBoxButton: React.PropTypes.string,
      },
      render(): ReactElement {
        const newProps = this.getNewProps();
        ...
      },
    });

**Test plan**

- propTypes validation works - `<Text style={'foo'} />` produces a warning both on iOS and Android:
screen shot 2016-05-12 at 2 15 31 pm

- Mixins work, tried adding `TimerMixin` to `TextBaseMixin`'s mixins, `Text.ios.js` can use `this.setTimeout` and `componentWillUnmount` fires correctly when `<Text>` is unmounted.
- `onPress` handlers work - tried `<Text onPress={() => alert('press')} />`
- **TODO: The code that renders `propTypes` on the website will need changes**. It can't see the `propTypes` inherited from the mixin.
- Ran the UIExplorer:

screen shot 2016-05-12 at 1 07 51 pm

screen shot 2016-05-12 at 1 10 51 pm

screen shot 2016-05-12 at 1 44 25 pm

screen shot 2016-05-12 at 1 45 47 pm

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @sahrens and @grabbou to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
@mkonicek updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@mkonicek updated the pull request.

**Comment by facebook-github-bot-3** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @sahrens as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by mkonicek** [comment]
This was just an RFC to demo how we can share parts of components with RN for Windows. We can close it and keep for reference.

cc @rozele

**Pull request closed without merging**
