### PR TITLE
Update SectionList.js

### PR DESCRIPTION
**Pull request by CheragV**
minor documentation change ands -> and

Thanks for submitting a PR! Please read these instructions carefully:

- [ ] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

What existing problem does the pull request solve?

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

## Next Steps

Sign the [CLA][2], if you haven't already.

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by hramos** [comment]
Can you resolve the conflicts?

**Comment by hramos** [comment]
Closing due to lack of response.

**Comment by CheragV** [comment]
Hi,

Had problems getting the CLA. Will get back after work to try again.

Thanks and Regards,
Cherag Verma

On May 31, 2017 12:59 AM, "Héctor Ramos" <notifications@github.com> wrote:

Closed #13050 <https://github.com/facebook/react-native/pull/13050>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/react-native/pull/13050#event-1102960580>, or mute
the thread

**Comment by hramos** [comment]
Feel free to email cla@fb.com and we can help!

**Pull request closed without merging**
