### PR TITLE
Enable build config feature for third-party libraries

### LINKED ISSUE #40559: Several packages seem to be incompatible with React Native 0.73 due to `buildConfig`
### New Version

0.73.0-rc.1

### Old Version

0.72.5

### Build Target(s)

Android

### Output of `react-native info`

System:
  OS: Linux 6.1 Manjaro Linux
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 5.39 GB / 13.51 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.7.0
    path: /tmp/yarn--1696745056791-0.4798124459808675/node
  Yarn:
    version: 1.22.19
    path: /tmp/yarn--1696745056791-0.4798124459808675/yarn
  npm:
    version: 10.1.0
    path: /usr/bin/npm
  Watchman:
    version: 2023.10.02.00
    path: /usr/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: javac 21
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0-rc.1
    wanted: 0.73.0-rc.1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Issue and Reproduction Steps

**Steps to reproduce:**

- Create a fresh `react-native@0.73.0-rc.1` project 
- Install `@react-native-async-storage/async-storage`
- Build application

Then, I can see the following error:

```
A problem occurred configuring project ':react-native-async-storage_async-storage'.
> defaultConfig contains custom BuildConfig fields, but the feature is disabled.
  To enable the feature, add the following to your module-level build.gradle:
  `android.buildFeatures.buildConfig true`
```

I had to patch `node_modules/@react-native-async-storage/async-storage/android/build.gradle` and add the following code to eliminate this error:

```
android {
    // ...
    buildFeatures {
        buildConfig true
    }
    // ...
}
```

The same thing is happening to `react-native-blob-util`, `@react-native-community/blur` and some more packages.

Here are some real-world examples that showcase this error:
- https://github.com/thu-info-community/thu-info-app/actions/runs/6445352956/job/17499307819
- https://github.com/thu-info-community/thu-info-app/actions/runs/6445418469/job/17499448561

What is the proper way to solve this issue?

Thanks!

### PR DESCRIPTION
**Pull request by UNIDY2002**
## Summary:

Fix #40559

Automatically enable the build config feature for third-party libraries so that no extra modification is required.

## Changelog:

[ANDROID] [FIXED] - Automatically enable the build config feature for third-party libraries

## Test Plan:

- Create a fresh `react-native@0.73.0-rc.2` project
- Install `react-native-webview`
- Build application
- (Expected) Application fail to build
- Apply this PR
- (Expected) Application build successfully

### CODE REVIEW

**Comment by cortinico** [comment]
Thanks for the fix @UNIDY2002 

> Automatically enable the build config feature for third-party libraries so that no extra modification is required.

While this is a smart move on paper, it comes with APK size costs, as `BuildConfig` classes will be created for each library, even for those that don't need `BuildConfig` at all.

So I'm unsure if we should attempt to "fix" libraries as they would effectively need to opt-in to this feature (this a breaking change introduced by AGP 8.x here https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes)

**Comment by UNIDY2002** [comment]
@cortinico Thank you for your explanation!

So the best practice should be requiring libraries to adjust their setups.

I will close this PR and the relevant issue.

**Comment by cortinico** [comment]
> I think we can try to be smarter and potentially check if the library is setting a `buildConfigField` and not enabling the `buildConfig` feature, if so -> enable it for them.

@UNIDY2002  Would you be up for attempting a PR that would achieve this?

**Comment by UNIDY2002** [comment]
> Would you be up for attempting a PR that would achieve this?

Yes, I will try to find a way to implement this.

**Comment by UNIDY2002** [comment]
Umm, I'm afraid I've encountered difficulties determining whether a library is setting a `buildConfigField`. I can't access buildConfigFields from `ext.defaultConfig`, and I am not sure whether there is another way to do this.

Before I come up with a proper way of detecting this info, I'm going to temporarily give up this attempt.

**Comment by cortinico** [comment]
> Umm, I'm afraid I've encountered difficulties determining whether a library is setting a `buildConfigField`. I can't access buildConfigFields from `ext.defaultConfig`, and I am not sure whether there is another way to do this.
> 
> Before I come up with a proper way of detecting this info, I'm going to temporarily give up this attempt.

Thanks for reporting. You're right that this is not easily possible. We'll end up enabling `buildConfig` for all the libraries as you suggested

**Pull request closed without merging**
