### PR TITLE
Bump SoLoader to 0.8.0

### PR DESCRIPTION
**Pull request by Alaa-Ben**
## Summary

This PR bumps bumps Soloader to 0.8.0. This fixes white screen/ crash issues when downloading from Google Play.

Related to:
#25927 #26400 

## Changelog
[Android] [Changed] - Bump Soloader to 0.8.0

## Test Plan
A few CI tests fail, but I don't see the link with what I changed, especially the ios tests.
It's working locally though, and for people on github who tried this solution as well.

### CODE REVIEW

**Comment by radko93** [comment]
Tested this in my apps and it did no harm but fixed linked issues.

**Comment by mdvacca** [comment]
LGTM, CC @ejanzer

**Comment by ScreamZ** [comment]
Is that available on some RN released version bad surprise in production for me…

**Comment by vidsag** [comment]
Hi.. I am currently using RN 0.61.4. I am trying to upgrade to latest SoLoader to fix some ANR is loadLibrary. Then I saw an upgrade to SoLoader was reverted for 0.61.4. Any reason as to why this was reverted?

**Pull request closed without merging**
