### PR TITLE
Implement Runtime.getHeapUsage for hermes chrome inspector

### PR DESCRIPTION
**Pull request by janicduplessis**
## Summary

I was looking at the hermes chrome devtools integration and noticed requests to `Runtime.getHeapUsage` which was not implemented. When implemented it will show a summary of memory usage of the javascript instance in devtools.

image

## Changelog

[General] [Added] - Implement Runtime.getHeapUsage for hermes chrome inspector

## Test Plan

Before

image

After

image

### CODE REVIEW

**Comment by janicduplessis** [comment]
I realized most of the code is generated using tools/run_msggen. I was able to adapt the script to make it usable outside fb, except for the `signedsource` part. So someone will have to re-run the codegen in the fb repo. (`cd ReactCommon/hermes/inspector/tools && ./run_msggen`).

I also added support for including experimental commands to msggen since `Runtime.getHeapUsage` is considered experimental.

**Comment by ShikaSD** [comment]
Hey, @janicduplessis, seems like update of the devtools version made the `"params"` field required for the `resume` command, breaking some internal tooling. Would it be possible to either implement the same command without upgrading the version or update codegen to make sure params field is optional?
I am reverting it for now, as we have a cutoff for internal tooling release in a hour :)

**Comment by janicduplessis** [comment]
Sadly the command does not exist when using the current devtools protocol version. I checked and it was added after the params object to resume, so there is also no version that exist where it would work.

Would it be hard to update the internal tool to pass params? Other option would be to make the codegen check if params exist, but would cause lots of changes to the codegen output.

**Comment by ShikaSD** [comment]
> Would it be hard to update the internal tool to pass params?

It seems like we have quite a few tools that use this codegen as a source of truth, so probably it is better to modify codegen to check for optional param :) 
Does input for the codegen specify whether the param is optional or not? I believe we can add this check to only apply when the parameter is not required, so it should be negligible here.

**Comment by janicduplessis** [comment]
Actually it might be possible to address with minimal changes by checkout if all parameters are optional, then make the whole params object optional.

**Comment by janicduplessis** [comment]
> Does input for the codegen specify whether the param is optional or not? I believe we can add this check to only apply when the parameter is not required, so it should be negligible here.

Yep https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/js_protocol.json#L641

**Pull request closed without merging**
