### PR TITLE
Added Activity interpretation from AndroidManifest.xml

### PR DESCRIPTION
**Pull request by ptomasroos**
Today .MainActivity is harded when running `react-native run-android`

In our use-case we have a SplashActivity which we need to start for the splash screen.

One would say you can put that behaviour into the MainActivity but that would mean stuff like rnpm stops working because it expects react's activity to be just MainAcitivity.

This PR parses the AndroidManifest.xml in order to find which intent that is configured to be the main action.

I'ts been tested on local repositories which has changed the MainActivity

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @jimthedev and @jsdevel to be potential reviewers.

**Comment by grabbou** [comment]
Sounds really good! We are planning to merge `rnpm` this weekend and this is likely to produce some conflicts (minors, we just changed structure and few lines). Would you mind rebasing after that and adding that in? On a positive note, `rnpm` has config that already parses stuff, so it should be a matter of just using proper variable! #power 

CC: @Kureev is this something we already expose in `rnpm` ? If not, maybe @ptomasroos can take a look into adding that to our core?

**Comment by ptomasroos** [comment]
I did see that as well @grabbou , just felt weird to depend on a manifest parser in the rnpm package.
I would make sense to move that to a lib directory in order to use it from various places in the code place probably.

**Comment by grabbou** [comment]
>  felt weird to depend on a manifest parser in the rnpm package

We already have it and parse activity on Android in order to get some real things :) https://github.com/rnpm/rnpm/blob/master/src/config/android/index.js#L93

We return it [here](https://github.com/rnpm/rnpm/blob/master/src/config/android/index.js#L110) so that you can just access it and use your function to find it (can't be applied `right now`, but it's more like a clue how to do it once we finish merging)

**Comment by ptomasroos** [comment]
Sure thing. Will hang in there.

**Comment by facebook-github-bot-2** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @burgalon as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ptomasroos** [comment]
Bump? Can we maybe merge this?

**Comment by facebook-github-bot-8** [comment]
@ptomasroos updated the pull request - [view changes](https://github.com/facebook/react-native/pull/8190/files/b7a0192fc5634b37fc1e35dcc8724356e9683eeb..004dfd04e99cadaf0fa7149e687ed27f5f880b46)

**Comment by facebook-github-bot-3** [comment]
@ptomasroos updated the pull request - [view changes](https://github.com/facebook/react-native/pull/8190/files/004dfd04e99cadaf0fa7149e687ed27f5f880b46..6439b0ce9c67b0ee6b05130d3c55ab7dadfa205e)

**Comment by hramos** [comment]
@grabbou thoughts, do you approve this?

**Comment by grabbou** [comment]
I don't like the fact of `xml` being used here given that this is rather very project specific thing. I understand the specific need for it and that's why I decided to simplify the approach and submit #11049.

**Pull request closed without merging**
