### PR TITLE
Increased timeouts and retries for instrumentation tests

### PR DESCRIPTION
**Pull request by bestander**
Tests fail quite often but retries seem to help.

Test Plan:
- see Circle CI logs

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek to be a potential reviewer.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1050591968363375/int_phab) to review.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1050591968363375/int_phab) to review.

**Pull request closed without merging**
