### PR TITLE
Add information about verifying Xcode Command Line Tools are installed

### PR DESCRIPTION
**Pull request by JoelMarcey**
screen shot 2016-05-19 at 10 12 35 am

### CODE REVIEW

**Comment by JoelMarcey** [comment]
cc @mkonicek

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @willfong and @atifmansoor to be potential reviewers.

**Comment by atifmansoor** [comment]
I would also like if you mentioned that you need to run XCode once after installing it to accept the license agreement. Otherwise, if you try to run-iOS before that, it will complain.

**Comment by JoelMarcey** [comment]
@atifmansoor Let me look to do that in another pull request

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/499619200245980/int_phab) to review.

**Pull request closed without merging**
