### PR TITLE
[Website] add missing KeyboardAvoidingView documentation

### PR DESCRIPTION
**Pull request by skv-headless**

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @nicklockwood to be potential reviewers.

**Comment by hramos** [comment]
Thanks for adding this! Did you confirm that the page was generated successfully? Sometimes react-docgen trips up with our use of some Flow features.

**Comment by skv-headless** [comment]
actually I get ```Error: TypeError: content.trim is not a function``` error. But I see same error for all components so I decided that you aware of that problem. I removed trim function in ```website/layout/AutodocsLayout.js``` and it works

**Comment by hramos** [comment]
The content.trim issue should be fixed by #9666 (sorry!). Okay, this LGTM!

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3791743) to review internal test results.

**Pull request closed without merging**
