### PR TITLE
the port should be 8081 rather than 8097

### PR DESCRIPTION
**Pull request by rocman**

### CODE REVIEW

**Comment by frantic** [comment]
@rocman could you please explain the use case and test plan? 8097 is used by standalone build of react-devtools that we are testing internally and shouldn't interfere with built in Chrome debugging.

**Comment by rocman** [comment]
Maybe it's because I'm using the project code generated by the old version of React Native, in which the react-devtools does not run and no service provided on 8097. I'll try to test on a new project later.

**Comment by satya164** [comment]
@rocman Did you try?

**Comment by grabbou** [comment]
Hey guys, I'm going through all PRs and looking at which ones should be closed. Looks like this one has been in an "undecided" state sine November.

If you are experiencing some issues @rocman, please re-open if it's still the case in latest version.

**Pull request closed without merging**
