### PR TITLE
Updating babel to latest version

### PR DESCRIPTION
**Pull request by skevy**
This should happen, given the fact that were several versions old, and many bugs have been fixed since the RN/Babel 6 upgrade.

I'm pretty positive this solves some of the issues around .babelrc's in people's projects not being respected. And by "pretty positive" I mean that in my test project I'm able to use a babelrc and it works just fine (but didn't prior to this upgrade).

### CODE REVIEW

**Comment by satya164** [comment]
How about adding something like http://greenkeeper.io/ ?

**Comment by skevy** [comment]
That would be cool if we were able to continuously keep the Travis build green. 😊

**Comment by davidaurelio** [comment]
> That would be cool if we were able to continuously keep the Travis build green. 😊

yes, definitively! @mkonicek is working on a solution to prevent FB-internal commits from breaking them.

**Comment by martinbigio** [comment]
I run into https://github.com/facebook/react-native/issues/4137 which should be fixed by this. I'll import this test it and land it

**Comment by martinbigio** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
Thanks @martinbigio!

**Comment by skevy** [comment]
@martinbigio @mkonicek just FYI, I just updated this to lock babel to the minor version (e.g. 6.3.x).

A bug that just broke React Native just landed in babel 6.4.0. Ref: https://phabricator.babeljs.io/T6926 -- and fixed here, but not yet released: https://github.com/babel/babel/pull/3242

So, @ide and I were talking, and we think it's reasonable and prudent to just lock to minor versions on Babel, because it's such a critical piece of the infra.

FYI (simply because I just learned this today...though it's probably something you all already know haha) - shrinkwrap is not respected when you have react-native as a dep...only when you run `npm install` in the react-native project (for example, with tests...which is why those are still passing).

**Comment by skevy** [comment]
We can update babel to 6.4.x when this bug is resolved and we verify there are no regressions. For now, I think we can stick with 6.3.x

**Comment by martinbigio** [comment]
@skevy thanks for looking into this! locking on minor versions sounds like a good plan

**Comment by ide** [comment]
+1 to locking minor versions and leaving bugfixes flexible. Babel actually pushed out a breaking change (according to the changelog at least) with the latest minor update so it might make sense to treat Babel's minor version the way we'd normally treat major versions for other packages.

**Comment by skevy** [comment]
What do you guys think about merging this? Currently, until babel fixes their issue, react-native is broken for anyone who installs from npm.

**Comment by skevy** [comment]
Though I suppose they'll probably push a hotfix shortly? Idk.

**Comment by skevy** [comment]
Actually, I lied. This won't actually fix anything, because babel doesn't lock to minors...so even if you install 6.3.26 version of babel-core, it will just install v6.4.0 of babel-generator (which is where the bug is). So, nevermind on any urgency with merging this.

We're stuck with brokenness until babel releases 6.4.1 with a fix for this problem.

*crosses fingers that it's soon*

**Comment by ide** [comment]
The way we could fix this is to surgically go in and modify the shrinkwrap in order to force it to install 6.3.x versions of babel modules, but it could get really complicated. Waiting for 6.4.1 sounds best.

cc @amasad @sebmck -- could you publish a new version of Babel shortly as a hotfix that includes https://github.com/babel/babel/pull/3245? Currently RN is broken for everyone doing a fresh npm install and I don't see an easy way to work around it from RN's side unfortunately.

**Comment by TheSharpieOne** [comment]
looks like 6.4.1 is out now.

**Comment by amasad** [comment]
published, sorry about that

**Comment by skevy** [comment]
It's all good @amasad - thanks for being so diligent!

**Comment by skevy** [comment]
Superseded by #5214

**Pull request closed without merging**
