### PR TITLE
Showcase: Add Trump Blocker

### PR DESCRIPTION
**Pull request by zixan**

### CODE REVIEW

**Comment by dsibiski** [comment]
Please move your app from the "featured" section down to the "apps" section. 👍  thanks!

**Comment by facebook-github-bot-3** [comment]
@zixan updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@zixan updated the pull request.

**Comment by zixan** [comment]
@dsibiski done 🔑

**Comment by dsibiski** [comment]
Perfect! Thanks!

**Comment by dsibiski** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/256295648052218/int_phab) to review.

**Pull request closed without merging**
