### PR TITLE
Fixed typo in NavigationCardStackExample.js

### PR DESCRIPTION
**Pull request by livioso**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

Just a typo.

### CODE REVIEW

**Comment by janicduplessis** [comment]
Thanks @livioso!

@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@livioso Have you signed the cla? If not could you do so at https://code.facebook.com/cla.

**Comment by livioso** [comment]
@janicduplessis I did. =)

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/587414498102538/int_phab) to review.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/587414498102538/int_phab) to review.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Something went wrong when importing this pull request. Please cc someone from the team at fb to help with importing this.

**Comment by satya164** [comment]
@livioso Can you rebase the PR against master?

**Comment by javache** [comment]
The code this PR touches is no longer present.

**Pull request closed without merging**
