### PR TITLE
Remove reference to the Xcode toolchain dir (unused)

### PR DESCRIPTION
**Pull request by nevir**
This path doesn't appear to be used by react native projects; and the only header in it is `FlexLexer.h`

### CODE REVIEW

**Comment by nevir** [comment]
image

**Comment by nevir** [comment]
The test failures _appear_ to be unrelated?

**Comment by ide** [comment]
I believe you're right that the test failures are unrelated but I am not sure if those lines were originally added to work with fb internally (probably not but yeah...).

cc @frantic can you import this if it looks good to you?

**Comment by facebook-github-bot-2** [comment]
@foghina would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by facebook-github-bot-9** [comment]
@AaaChiuuu would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by grabbou** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by mkonicek** [comment]
Tests are passing now. @frantic can you take a look please? Are you the right person to look at this one?

**Comment by facebook-github-bot-0** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @alexeylang as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by facebook-github-bot-9** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @alexeylang as a potential reviewer. Could you take a look please or cc someone with more context?

**Pull request closed without merging**
