### PR TITLE
Add "SAY a Short Video Community" app to the showcase.

### PR DESCRIPTION
**Pull request by qingfeng**
SAY is "Q & A community-based short video", All based react native development

- You can shoot video
- Video Filters can be switched
- Private chat

image

image

image

image

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1621251068128323/int_phab) to review.

**Comment by qingfeng** [comment]
@brentvatne 
SAY APP many features, video recording, playback, whisper, animation, and many other complex features, full use of react native, wanted to apply Showcase Featured Apps, I wonder if you can?

**Pull request closed without merging**
