### PR TITLE
Packager linking when using custom debug configuration on iOS device

### PR DESCRIPTION
**Pull request by ZdravkoN**
## Motivation

In many projects we have different environments that we connect to. For these environments (for example: Test, Staging, Production) we have custom configurations (Debug and Release). While this is not a problem on Android, it is a problem on iOS. With the current implementation of the react-native-xcode.sh script, when using a custom Debug configuration, the app started on iOS device, can't contact the Packager. This pull request solves this issue.  

## Test Plan

Connect a real device, start the app with a custom debug configuration in Xcode. Shake and Reload.

## Release Notes

[IOS][BUGFIX][./scripts/react-native-xcode.sh] Add support for connecting to the Packager when running the iOS app on device when using custom Debug configuration.

### CODE REVIEW

**Comment by ZdravkoN** [comment]
Hi @facebook-github-bot, yes, the pull request is still relevant. I will look at the changes made in master and update it.

**Comment by andon** [comment]
This is an important and simple fix. It can be merged straight away. If fixes a problem and it makes the script more consistent. The wildcards usage with `DEBUG` is already present on other places in the script.

Can someone help? Ping @davidaurelio, @javache

**Comment by ZdravkoN** [comment]
I have signed the CLA. Please re-open this pull request.

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :clipboard: Release Notes - <i>This PR may have incorrectly formatted Release Notes.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request closed without merging**
