### PR TITLE
Add Android version of Kakapo

### PR DESCRIPTION
**Pull request by bluedaniel**

### CODE REVIEW

**Comment by chirag04** [comment]
@brentvatne now that more and more android apps are coming, we shouldn't duplicate the same app twice. I'm not sure what it should look like but two separate link for android and ios would make it easy.

@bluedaniel you want to give it a go if @brentvatne agrees to this?

**Comment by bluedaniel** [comment]
Sure.

**Comment by brentvatne** [comment]
Nice :)

**Comment by brentvatne** [comment]
Ran this locally, looks good to me

**Pull request merged**
