### PR TITLE
Updates from Monday 22 Jun

### PR DESCRIPTION
**Pull request by nicklockwood**

### CODE REVIEW

**Comment by frantic** [comment]
ObjC tests fail because of #1715, I'm looking...

**Comment by frantic** [comment]
@nicklockwood I'm oncall this week, I can push the update if you don't mind :)

**Comment by frantic** [comment]
#1717

**Comment by nicklockwood** [comment]
@frantic go for it - I've been wrestling Travis all week trying to land it :-)

**Pull request closed without merging**
