### PR TITLE
Delete stale file `generatedComponentApiDocs.js`

### PR DESCRIPTION
**Pull request by Saadnajmi**
## Summary:

I noticed this file was 4 years old in both React Native and React Native macOS, and figured it was safe to delete  ¯\_(ツ)_/¯

## Changelog:

[INTERNAL] [REMOVED] - Remove stale generated doc file

## Test Plan:

N/A

### CODE REVIEW

**Comment by Saadnajmi** [comment]
> Thanks for the cleanup. I see some references of this file can you verify and cleanup those as well?
> 
> https://github.com/facebook/react-native/blob/28d5c15cb97ca7308878c24f97fd6fee518ba39f/scripts/generate-api-docs.js#L21
> 
> 
> https://github.com/facebook/react-native-website/blob/fe13c0bddd52a679606c99ce8f31a8ff0e76dd43/sync-api-docs/magic.js#L10

Updated the PR to remove the JS file, as well a second PR to update the website: https://github.com/facebook/react-native-website/pull/3699

**Comment by Saadnajmi** [comment]
Anything blocking this?

**Comment by jacdebug** [comment]
Let's get a confirmation from @TheSavior finally!

**Comment by Saadnajmi** [comment]
Pinging again, any blocker here?

**Pull request closed without merging**
