### PR TITLE
Fixing the git attrs for all the people and all the files and all future 🙌 

### PR DESCRIPTION
**Pull request by pvinis**
## Summary

We have had problems with `.gitattributes`, `.bat` and `.pbxproj` (Xcode) files for a while. The two main concerns were:
- Xcode project files not diffing correctly.
- Windows files having messed up line endings.
This PR fixes both issues, hopefully forever.

After seeing the diffs from v0.63 -> v0.64 and the changes in https://github.com/facebook/react-native/pull/29792, I, again, felt that this is going to cause problems, so I looked into both issues.

I started with `git check-attr -a Artsy.xcodeproj/project.pbxproj` after removing the `.gitattributes` file that contained `*.pbxproj -text` and there are no "guessed" attributes that would break things, and diffing and checking in worked well with the current git version. I agree this is not needed, so I left it out.

I looked into what it was doing before, and it was telling git (for the xcode project file) to "unset text", which means (according to https://git-scm.com/docs/gitattributes#_text) that it should not try to do any line ending changes when checking in that file. At some point git must have done this, and that's why it was needed, but no more, so it's safe and good to get rid of this, as it helps with nothing anymore.

Now for the bat files. We don't need any extra instructions for `gradle` and `*.sh` files as they are guessed correctly, so these are also safe to keep removed (https://github.com/facebook/react-native/pull/29792/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eL5).

But we do need the `*.bat` instruction. I noticed that when working on macOS there were two problems that made things funky.
- One, is that the editor (usually vscode but not the important) would convert line endings to lf when editing a bat file.
- Two, is that git thought the files are lf line endings.

To fix the first one, I added a rule in `.editorconfig` (that's whats important, when any editor just supports editorconfig, but all my editors do). I can't believe how we missed that for sooooo long 😅!

To fix the second, I added the `.gitattributes` instruction **and** `renormalize`d the files (https://git-scm.com/docs/git-add#Documentation/git-add.txt---renormalize and https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings). I think the problem all along was that even though the files had crlf, git still thought they were using lf.

After the editorconfig change and the renormalization, everything behaves correctly and as expected. Changing bat files on macOS and Windows is fine now, producing only the smallest change needed, no random line ending diffs. Also here is a screenshot of one of the files actually crlf. It's these tiny things at the end of each line 👓.
Screenshot 2021-03-10 at 12 20 28

I have tested this on macOS and Windows, doing changes in both bat and xcode files, and verified that diffing and checking in files works well.

## Changelog

[General] [Added] - Added an `.editorconfig` file to help with default line endings for Windows files.

[Internal] [Fixed] - Added a rule in `.editorconfig` and `.gitattributes` to help with default line endings for Windows files.

## Test Plan

Feel free to go on a macOS or Windows machine (or both) and, using any editor that supports editorconfig, do any change in a `.bat` file. Then look at your git diff in terminal or gui or whatever you use, and then look at the sky and smile. It's fixed. The diff is just your change. Everything is as it should 💜.

### CODE REVIEW

**Comment by pvinis** [comment]
I'm not sure since when this was fine. I guess we could keep it 🤷? But I think it's been a while, so I would opt for not having it 🤔.

**Comment by pvinis** [comment]
Yup. This is a known issue, and I hope sometime we will solve it with xcodegen or something similar. But these files are changing and it's important to know what is changed. They are too fragile to just commit without paying attention. The upgrade helper diffs them and even with ids changing, it's important to know what's there and what's changed.

**Comment by liamjones** [comment]
Oh, I agree the changes are important. 😄 

Personally, I just subscribe to a different resolution method - look at what the changes produce in the xcodeproj and then use Xcode itself to generate the changes again via the UI. That way there's no chance of misaligned IDs, 'Recovered References', etc.

**Comment by matt-oakes** [comment]
Not reliant for this PR, but there was a get mergetool tool that would parse, attempt to understand, and then merge the project files automatically:

* https://github.com/simonwagner/mergepbx
* https://medium.com/@mattoakes/a-better-way-to-automatically-merge-changes-in-your-xcode-project-files-3d83b3583fe4

It's not been updated for a long time though, so I have no idea if it would still work.

Anyway! That's not what this PR is about 🙂

**Comment by friederbluemle** [comment]
Thanks for the PR @pvinis - Before merging this, I would like to understand the problems you were facing a bit better. Let's have a quick look at the Gradle Wrapper scripts _on the current master branch_ in this repo:

```
$ git ls-files | grep gradlew | xargs file
gradlew:                                           a /usr/bin/env sh script text executable, ASCII text
gradlew.bat:                                       DOS batch file text, ASCII text, with CRLF line terminators
packages/react-native-codegen/android/gradlew:     a /usr/bin/env sh script text executable, ASCII text
packages/react-native-codegen/android/gradlew.bat: DOS batch file text, ASCII text, with CRLF line terminators
template/android/gradlew:                          a /usr/bin/env sh script text executable, ASCII text
template/android/gradlew.bat:                      DOS batch file text, ASCII text, with CRLF line terminators
```

Everything looks correct to me.

So first question: Why is there a need to "renormalize" the files, and why do they show up as changed in the PR diff?

**Comment by friederbluemle** [comment]
Also just a minor addition regarding `*.pbxproj -text` (@matt-oakes) - To my knowledge, a `.pbxproj` files does not normally contain a `NUL` character in its first 8000 bytes (i.e. Git would not treat it as binary), so that configuration would have no effect.

**Comment by friederbluemle** [comment]
> The normalization is something that apparently git needs.

Sorry I don't quite understand. Can you explain in more detail? If you check my message above, you can see that these files _already have the correct line endings_.

What I _think_ is happening here is your editor is converting entire files when you are only editing single lines as a side effect. That's clearly not what should happen.

Can you please try:

1. Start with a fresh/clean version of the repo
2. _Remove_ the line `end_of_line = lf` from `.editorconfig`
3. Edit some files, and verify that everything is working correctly

Again, as I mentioned, all files are already in their expected standard format - there is no need for any conversion and/or addition of new files that configure settings to the default value.

**Comment by pvinis** [comment]
I can try tomorrow. Are you in the RN discord or somewhere else where we could talk faster, so I can try and then we can talk and see what's up?

**Comment by hramos** [comment]
@pvinis @friederbluemle did you get a chance to discuss this PR? Let us know if we should consider it for merging, or if there's any more work that needs to be done.

**Comment by hramos** [comment]
Considering the contents of this PR have already been incorporated onto 0.64 and no issues have been reported, we are going to proceed with merging this PR.

**Review by hramos — APPROVED** [review]

**Comment by friederbluemle** [comment]
@hramos - Thanks for the reminder. Can you please check my comment above? As explained - The files _already_ had the correct line endings in the repository (there is no need to add gitattributes or editorconfig). Now that it's merged, the Windows .bat files have their CRLF endings **removed**, which is incorrect. I've reverted it here: #31398
@pvinis - Please confirm you followed the steps in my previous message and everything is working for you locally. Also make sure your editor does not change line endings as a side effect of editing single lines in a file (some editors might have an option in settings).
It looks like the one thing that might be useful are the three lines in the existing .editorconfig in the root of the repo:
```
# Windows files
[*.bat]
end_of_line = crlf
```
Again, @pvinis to confirm if that works locally. Thanks!

**Comment by pvinis** [comment]
I'll check this right now.

**Comment by pvinis** [comment]
Ok let's go.
I have commented out all custom git configs and editor configs.

- Cloned rn repo fresh, on master, with the changes in this PR merged.
- First thing I did, confirm the files are correct right now.
Screenshot 2021-04-23 at 09 59 26
Screenshot 2021-04-23 at 10 00 03
They are. `gradlew` has `LF`, `gradlew.bat` has `CRLF`.

As extras, I will try to edit these files and commit, and see if they stay with the correct line endings. I will also take a look at your new PR.

- Editing the files. I edited the bat file with clean neovim, and it kept all line endings, with a line removed and a line added.
Screenshot 2021-04-23 at 10 05 35
- Git shows the diff correctly, not changing the whole file like before.
Screenshot 2021-04-23 at 10 06 59
- I will also edit this file with vscode, to hopefully get some line ending breakage, to see if git handles it correctly. First thing, is that vscode correctly understands it's CRLF and things work as before with neovim, but I will force it to change to LF.
Screenshot 2021-04-23 at 10 11 42
So here we see the line endings are now LF.
Screenshot 2021-04-23 at 10 11 52
Git diff correctly shows only the changes, not making the diff 91 lines like the whole file. That is already a gain for diffing. To force it, I had to change the editorconfig, so I would say with the right editorconfig we are pretty safe, and even if that breaks, git still handled it well.

So my final thoughts here are:
- We keep the editorconfig rule for bat files. In the root of the repo for people working on RN, and in the template dir for people init-ing an RN project.
- We keep the gitattributes rule for bat files. That way git will handle the diffs well, no matter what the line endings end up being. editorconfig will keep them correct, and even if they are not correct because of a broken editorconfig, it will still handle the diffing correctly.

I think the new PR you made is not actually needed, but please, if you try to replicate all the above in a fresh master with my changes in there, and maybe even in a fresh repo on your branch, and something is handled in a better way on yours, then let me know! I am also happy to check stuff together on discord or wherever else.

**Comment by friederbluemle** [comment]
@pvinis - Thanks a lot for the detailed response and analysis :+1:

> First thing I did, confirm the files are correct right now.

I admit, it's not immediately obvious, but what you checked here are the files _in your working directory_, not the files _stored in the repository_. That's because now that there is a `.gitattributes` file, Git performs an additional _conversion_ when the files are placed in the working directory, hiding the fact that they are committed with the wrong line endings.

If you want to see how these files are actually stored:

1. Remove `.gitattributes` (so that no conversion happens)

```
git checkout -b temp
git rm .gitattributes
git commit -m"Remove .gitattributes"
```

2. Now, delete and restore the existing `gradlew.bat` file in the working directory

```
rm gradlew.bat
git checkout gradlew.bat
```

3. Check line endings using `file` (or use `bat -A`, as in your examples)

```
$ file gradlew.bat
gradlew.bat: DOS batch file text, ASCII text
```

The file only has `LF` line endings. Expected would be:

```
$ file gradlew.bat
gradlew.bat: DOS batch file text, ASCII text, with CRLF line terminators
```

Alternatively, if you use something like [`diff-so-fancy`](https://github.com/so-fancy/diff-so-fancy) the removed carriage return characters will also show up in `git diff`:

```
$ git -c core.pager='diff-so-fancy | less --tabs=4 -RFX' show -p 73844712b62 -- gradlew.bat

-@rem^M
-@rem Copyright 2015 the original author or authors.^M
-@rem^M
...
+@rem
+@rem Copyright 2015 the original author or authors.
+@rem
...
```

`^M` represents `CR`, which was _removed_ in 73844712b62 (not visible on GitHub's UI).

**Comment by pvinis** [comment]
I will check these again and report back.

But just as a quick response, I definitely care in order:
1. easy and small diffs (just the actual diffs, not the whole file)
2. setup that doesn't break easily for users (rn devs and/or rn project creators)
3. "correct" line endings for windows (especially when things work with editorconfig. I have seen a few "best practices" that actually suggest to store everything with LF and only locally on windows machines make sure to keep them with CRLF, which is happening with git.)

**Pull request closed without merging**
