### PR TITLE
[Kinda discussion] run `yarn format`

### PR DESCRIPTION
**Pull request by pvinis**
## Summary
While making another PR I run `yarn format` and about a billion files changed, so obviously it hasn't been run for a while.

This PR will serve two purposes.
- To apply the format in the existing codebase.
- To discuss how to maybe automate this for the future, and possible changes to the `.clang-format`.

So as a starting point, I have run `yarn format` with the current settings, and here is the result. After running it, I do disagree with the `MaxEmptyLinesToKeep: 1`, as two lines are great to separate things like an `@interface` and it's `#include`s above etc.
I'll make a comment underneath to vote there, and any change decided, I'll cancel and rerun `yarn format` and push again in this PR.

Secondly, there was the idea of adding git hooks to run `yarn format`. Another idea could be to have it running on the CI, or maybe run it every month or something else. Feel free to discuss and offer your opinion, ideally with some comment about previous experience with any solution suggestions. :)

## Changelog

[Internal] [Changed] - Code formatting with clang

## Test plan
We test it?

### CODE REVIEW

**Comment by pvinis** [comment]
### `MaxEmptyLinesToKeep`

👎: 1
👍: 2
😕: remove it

**Comment by pvinis** [comment]
I guess the conflicts are not super important right now, while we still decide and discuss, as I'll rebase and rerun with each decision.

**Comment by cpojer** [comment]
cc @hramos

**Comment by cpojer** [comment]
We need to revert the changes to Yoga and make sure that the formatting command excludes making changes to Yoga.

**Comment by pvinis** [comment]
ok, so exclude `ReactCommon/yoga`, right?

**Comment by hramos** [comment]
Please exclude Yoga like Christoph mentioned, as that formatting should be fixed upstream. Once that is done, we can import this and see what our internal linter thinks about this. I am not too concerned, as the .eslintrc used internally is a superset of the one in the root of this repo.

**Comment by pvinis** [comment]
I didn't find a way to tell `clang-format` to exclude a directory.. :(

**Comment by cpojer** [comment]
I'll close this for now but will put it in the backlog to reformat all the code internally and sync it out.

**Pull request closed without merging**
