### PR TITLE
Remove unused files and code for old JSC and gcc build

### PR DESCRIPTION
**Pull request by Kudo**
Summary:
----------

1. Unused prebuilt old JSC for 64bits.
2. Folly patch for gcc build.

Test Plan:
----------

1. CI green
2. RNTester for arm & arm64

### CODE REVIEW

**Comment by gengjiawen** [comment]
`test-android` looks failed.

**Comment by turnrye** [comment]
Hey @Kudo , thank you for the contribution! Since this change isn't user impacting, I likely will not suggest that we add an entry in the changelog. Nevertheless, the cleanup is appreciated. Cheers!

**Comment by Kudo** [comment]
@gengjiawen Thank you for the CI re-trigger.

@turnrye Revised, please take a look. Thanks for your awesome work to summerize the changelog.

**Comment by dulmandakh** [comment]
@facebook-github-bot  shipit

**Comment by dulmandakh** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
