### PR TITLE
Allow for an empty iOS device name

### PR DESCRIPTION
**Pull request by StevePotter**
I find it frustrating to enter my phone's full device name every time I want to run: react-native run-ios --device "Stephen Potter's iPhone" is not cool.  I could create an alias in bash profile but then I can't share that alias with others and can't use other devices with it.

If there's one iOS device plugged in and you set the --device option but don't specify a value, I think it should use it without requiring the name.  If you have more than one device, then a name should be required.  This simple code addition fixes that.  I've run with no devices, multiple devices, and it all works fine.

To test, plug in an iOS device, type 'react-native run-ios --device' and watch it go.

### CODE REVIEW

**Comment by StevePotter** [comment]
I don't understand how the Travis CI build failed due to this.  Can an expert help?

**Comment by kenleezle** [comment]
👍

**Comment by grabbou** [comment]
Hey @StevePotter, that looks very nice! Circle passed, so partially good. Could you please rebase on top of master and ping me? I'll merge it right after.

**Comment by hramos** [comment]
@StevePotter we can import once the conflicts are resolved.

**Comment by lacker** [comment]
I think this PR has been abandoned, so I am going to close this pull request. If I am mistaken please feel free to reopen - it's just a small improvement but it does seem like it would be an improvement.

**Comment by StevePotter** [comment]
Hey @lacker I ended up including it with another major PR I submitted for that same file.  Check it out https://github.com/facebook/react-native/blob/master/local-cli/runIOS/runIOS.js#L172.  So the issue is solved!

**Comment by lacker** [comment]
Yay!

**Pull request closed without merging**
