### PR TITLE
Move Image.resizeMode to component

### PR DESCRIPTION
**Pull request by patoroco**
Using resizeMode on Image component returns a warning, it needs to be passed by param

### CODE REVIEW

**Comment by vjeux** [comment]
@facebook-github-bot shipit

Thanks!

**Comment by patoroco** [comment]
@vjeux should I update something here?

**Comment by spicyj** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Looks like my implementation of looking at all the lines is not working :( Sorry for the confusion

**Comment by patoroco** [comment]
@vjeux I don't understand. This change is not appropriated?

**Comment by ide** [comment]
@patoroco your PR was merged into master

**Comment by patoroco** [comment]
Oh sorry, it didn't appear on github as merged, I asked due to this.

Thanks!

**Pull request closed without merging**
