### PR TITLE
Docker Testing Environment for Android & JS

### PR DESCRIPTION
**Pull request by nicktate**
Created a containerized environment to run unit and integration tests for both javascript and android as well as a Jenkinsfile using the new 2.0 Pipeline syntax for integration into a Jenkins CI cluster. 

Here is a quick summary of the changes:

* The android image is built from two separate dockerfiles. There is a base image that handles the heavy lifting of dependencies that are infrequently changed while the secondary image extends the base and allows for much quicker incremental builds on code updates.
* The javascript image is simple and is relatively quick to build, therefore there is no base image for any react specific javascript dependencies and it is all packaged in a single docker image.
* A new `scripts/docker` has been created including some javascript files and shell scripts to aid in the running of the tests
* The instrumentation test runner script can be passed various flags to control which tests run since the entire suite takes a significant amount of time to run synchronously
* Jenkinsfile is included for the eventual running of the tests on a ContainerShip backed Jenkins Cluster

> `DockerTests.md` has been created to give a more detailed overview of the updates including how to run the tests locally in a container

CC @ericvicenti

### CODE REVIEW

**Comment by ericvicenti** [comment]
Thank you for making this happen! The ability to run the Android integration tests locally will allow the community to write tests and reliably verify they pass, before submitting code.

I've been playing around with this. The docker setup was super easy, and the download of the Android image took about an hour on my fast home connection.

### Scripts in package.json

To make it easier to remember the commands, I added the following to the `package.json`. It may make sense to add these in the PR.

```
"scripts": {
    "test-android-setup": "docker pull containership/android-base:latest",
    "test-android-build": "docker build -t react/android -f ./Dockerfile.android .",
    "test-android-run-integration": "docker run --cap-add=SYS_ADMIN -it react/android bash scripts/docker/run-android-docker-integration-tests.sh",
    "test-android-run-unit": "docker run --cap-add=SYS_ADMIN -it react/android bash scripts/docker/run-android-docker-unit-tests.sh",
    "test-android-run-e2e": "docker run -it react/android bash scripts/docker/run-ci-e2e-tests.sh",
    "test-android-all": "npm run test-android-build && npm run test-android-run-unit && npm run test-android-run-integration && npm run test-android-run-e2e",
    "test-android-integration": "npm run test-android-build && npm run test-android-run-integration",
    "test-android-unit": "npm run test-android-build && npm run test-android-run-unit",
    "test-android-e2e": "npm run test-android-build && npm run test-android-run-e2e",
  ...
}
```

So now a new developer has simple steps: Install docker, then run `npm run test-android-setup` and wait for the long download. Then you can simply run the following to verify tests pass on the current code:

- `test-android-all` - Very slow test but it should verify all things on Android are working
- `test-android-unit` - Builds and runs unit tests
- `test-android-e2e` - Rebuilds and runs e3e
- `test-android-integration` - Rebuilds and runs integration tests. Modifier flags should pass through

### Unit tests working reliably

I always get a solid `TESTS PASSED` when running `npm run test-android-unit`

### Instrumentation test seems to have a failure

```
npm run test-android-instrumentation
```

The instrumentation tests have unclear results. The full output is [here in this gist](https://gist.github.com/ericvicenti/4ed5670640cd034e59b7be95886ede9a), and it closes without clearly reporting success or failure. Most tests log "OK", there seems to be one failure, and it is not clear if all tests have been ran.


### End-to-end test has failure in script

```
npm run test-android-e2e
```
And eventually ran into:
```
scripts/docker/run-ci-e2e-tests.sh: line 174: [: -ne: unary operator expected
```

I'm on macOS 10.12.2 and Docker 1.12.6, in case that matters.


### Docs

We should add this documentation to the main testing section of the website. This would also be a good topic to blog about.

Next week I'll draw some attention to this and we can get lots of feedback from the community- I'm sure people will be very excited for this!

**Comment by nicktate** [comment]
* Good call on adding run scripts to the package.json, I will make those changes to simplify triggering test runs.
* The error in the instrumentation tests looks like some sort of segfault, I will do a little digging to identify what the issue is. Also I can add in some better end of test feedback of the success/failures that occurred and port it back to the script that is used in the circleci test runner in a separate PR since these scripts are based off of those initial ones.
* The `scripts/docker/run-ci-e2e-tests.sh` needs to be run with the `--android` and `--js` flags provided. I will update the documentation to reflect those input options and provide better feedback from the script when parameters are not passed. You can run the e2e tests then with the following command `docker run --cap-add=SYS_ADMIN -it react/android bash scripts/docker/run-ci-e2e-tests.sh --android --js`

Thanks for the feedback @ericvicenti !

**Comment by mkonicek** [comment]
nit: Would it be possible to put the files added in the root of the repo to a folder like `ContainerShip` so it's obvious what these files are for and that they belong together?

**Comment by nicktate** [comment]
@mkonicek Organized everything under a `ContainerShip` directory at the root of the project except for the `Jenkinsfile` which current needs to be at root level to be picked up. 

@ericvicenti Made updates for the `package.json` to include scripts for test build and execution. Updated documentation for the e2e tests and also added in test result output for the instrumentation tests. Neither Norm or I could reproduce the segfault in the emulator that you experienced running locally. Can you try running again and see if it is a problem? It also looked like in that log output that the tests retried and continued to run to completion even though there was the memory issue.

**Comment by nicktate** [comment]
Hey @ericvicenti, is there any other feedback you have for us on this PR?

**Comment by normanjoyner** [comment]
hey @ericvicenti and @mkonicek anything else you'd like cleaned up on this PR?

**Comment by ericvicenti** [comment]
The last time I ran this test, the instrumentation test exited without reporting pass or failure. Other than that, this is looking awesome! I'd say we're ready to take this to the next step.

@bestander, sorry for not pinging you about this.. would you mind taking a look?

**Comment by nicktate** [comment]
@ericvicenti : Here is a link to an example run of this PR on our ContainerShip Jenkins setup. We have the instrumentation tests parallelizing and got the test run time down to ~18 minutes in the current setup for the entire android and js suite 😄 !

We are working on finishing up some load testing and should have the environment fully up and good to go sometime tomorrow.

https://reactnative.containership.cloud/blue/organizations/jenkins/React-Native-Test/detail/feature%2FcsJenkinsDroid/7/pipeline/

cc @normanjoyner

**Comment by ericvicenti** [comment]
@nicktate, wow that is awesome! I can't wait to get Jenkins running on PRs, so we can verify the signal is good!

**Comment by nicktate** [comment]
@ericvicenti I sent you an email about next steps so we can get this integrated and running on commits side by side for testing. Let me know once you get a chance to read it over so we can set up time for a call and work through the requisites to get this moving forward! 😄

**Comment by normanjoyner** [comment]
hey @ericvicenti is there anything else needed to get this merged and integrated to test alongside existing functionality?

**Comment by mkonicek** [comment]
Thanks for working on this! This is mostly self-contained in the `ContainerShip` folder and adding hooks in a few places like package.json so looks good to me. We could merge and iterate.

Pinged @ericvicenti on messenger asking for a thumbs up to merge it.

**Comment by hramos** [comment]
Just wanted to chime in and say that this worked really well for me this morning when I was looking for a way to run Android integration tests locally. Thanks for the great work!

**Comment by ericvicenti** [comment]
Apologies for the delay on this- we are still quite excited about the docker-ization of our CI! Lets land this as-is for now and keep iterating

Now I need to go on an internal investigation to see how tricky it will be to run these tests internally.

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit-ninja

**Comment by nicktate** [comment]
Hey @ericvicenti it looks like the circle CI tests failed on that import. None of it seems to be related to the code from this PR at all, and I looked at the most recent commits on the master branch and a lot of them are failing tests.

**Comment by mkonicek** [comment]
Hi @nicktate, thank you for adding this! Is there a page where we can see the tests running on ContainerShip, similar to circleci.com/gh/facebook/react-native?

**Comment by normanjoyner** [comment]
hey @mkonicek we just need to get the Jenkins instance hooked up to this repo (will require a webhook from GitHub to the ContainerShip Jenkins instance) and then the tests will execute alongside the existing ones! I'm happy to work with someone on your side to help get this set up so we can get them running in parallel!

**Comment by normanjoyner** [comment]
@mkonicek @ericvicenti i'm happy to take the discussion offline to get everything configured and running properly.

**Pull request closed without merging**
