### PR TITLE
Update Upgrading.md latest version

### PR DESCRIPTION
**Pull request by ChangJoo-Park**
release react-native version 0.21.

### CODE REVIEW

**Comment by foghina** [comment]
Perhaps it would be better to use something like `0.XX` so that we don't need to update this for every release?

**Comment by grabbou** [comment]
`npm install react-native@latest` ?

**Comment by facebook-github-bot-8** [comment]
@sunnylqm would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
Yes, 0.18 is just an example, I believe it's readable enough. If anyone wants to set a new PR to using e.g. 0.XX that's OK, I don't think we'll remember to update the version in this doc every release. So either keeping 0.18 as an example or using something more generic.

**Pull request closed without merging**
