### PR TITLE
issue Resolved : [TextInput] Auto correction doesn't call onChangeTex…

### PR DESCRIPTION
**Pull request by RD1991**
We can just call textFieldDidChange from textFieldEndEditing to resolve this bug.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @cava23 and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-4** [comment]
@RD1991 I tried to find reviewers for this pull request and wanted to ping them to take another look. However, based on the blame information for the files in this pull request I couldn't find any reviewers. This sometimes happens when the files in the pull request are new or don't exist on master anymore. Is this pull request still relevant? If yes could you please rebase? In case you know who has context on this code feel free to mention them in a comment (one person is fine). Thanks for reading and hope you will continue contributing to the project.

**Comment by facebook-github-bot-0** [comment]
@RD1991 updated the pull request - [view changes](https://github.com/facebook/react-native/pull/8845/files/a313cbec3b1f0de3297f26c8877537c8a817014a..12acd244c2ebaed543dfc85bc029fbd6e610b560)

**Pull request closed without merging**
