### PR TITLE
Change arguments for emitError to match other uses

### LINKED ISSUE #11587: On Android, when Location Services is disabled, geolocation.getCurrentPosition returns an error as a string, instead of an object according to spec
### Description/Reproduction

Disabling 'Location Services' in Android's system settings, and then calling navigator.geolocation.getCurrentPosition will result in an error, 'No available location provider.', instead of an object, where that's the value of message.

### Solution

In LocationModule.java, change this line:

    error.invoke("No available location provider.");

to this, to match the phrasing of the same error from startObserving

    emitError(PositionError.PERMISSION_DENIED, "No location provider available.");

### Additional Information

* React Native version: 0.39
* Platform: Android

### PR DESCRIPTION
**Pull request by mwiley**
FIxes #11587

### CODE REVIEW

**Comment by ide** [comment]
You still need to call the error callback or else this function will hang, please document and run through a most robust test plan to catch this.

**Comment by dabit1** [comment]
Please merge this pull request, thanks!

**Comment by dabit1** [comment]
Hi! I did the changes manually while I wait for the pull but the error variable contains a string yet. I restart my packager, I reinstalled the app, I rebooted my computer, I removed build folder but the changes does not appear. Please can somebody help me? Thanks!

**Comment by mkonicek** [comment]
Closing for a lack of response. You still need to call `error.invoke` too, otherwise the function call from JS will hang.

Anyone please feel to open a new PR that does this correctly.

**Pull request closed without merging**
