### PR TITLE
Replaced babel-eslint with @babel/eslint-parser

### PR DESCRIPTION
**Pull request by clintonb**
## Summary

babel-eslint is no longer updated. We now use its replacement library.

## Changelog

[Internal] [Changed] - Replaced babel-eslint with @babel/eslint-parser

## Test Plan

1. Install package:
```
yarn add -D 'https://gitpkg.now.sh/Afri-exchange/react-native/packages/eslint-config-react-native-community?clintonb/replace-babel-eslint'
```

2. Verify ESLint runs successfully.

### CODE REVIEW

**Comment by clintonb** [comment]
Related: https://github.com/facebook/react-native/pull/32431

**Comment by clintonb** [comment]
It's not clear to me how to fix the lingering issues. I suspect the flow plugin is not being properly loaded for the `test_js` failures. The `test_windows` tests may be have the same issue, and/or be a bit too brittle in their error expectations. 

My branch meets the needs of my project and I've already spent a few hours digging into these tests to no avail, so I may not invest any more time on this. Feedback, or contributions, are welcome.

**Comment by skdrew** [comment]
Hi @clintonb, I've been taking a look at this PR to see if I can help out as it's something I'd also like to see merged at some point.

I haven't fully solved the tests failing but I think I've made some progress. You're right that the flow plugin isn't being loaded, on my local branch (https://github.com/skdrew/react-native/tree/chore/update-eslint-config-dependencies) I've added some extra config that does load it - or at least it's supposed to, it's unable to resolve the plugin in the paths but it's a step closer!

I've also tried reference the flowtype plugin directly, but I get `Parsing error: Plugin/Preset files are not allowed to export objects, only functions.` when doing this. I've also stuck to v7.0.0 of the flowtype plugin as that's the last version that works with eslint v7.

Not sure if this helps at all, I'll keep poking around to see if I can get it sorted but I thought you might be interested to know.

**Comment by cortinico** [comment]
Closing as this was superseeded by https://github.com/facebook/react-native/pull/34020
Thanks for sending this over @clintonb though 🙏

**Pull request closed without merging**
