### PR TITLE
Update "Handling Text Input" tutorial's "follow to the next topic" section's target

### PR DESCRIPTION
**Pull request by toukovk**
The tutorial pages tend to have a "follow to the next topic" section at the end of the text.

In https://github.com/facebook/react-native/commit/f42f2dff3726eea0faa874e89ca9a6f32010ad05 tutorial ordering was changed so that "Handling touches" was added between "Handling Text Input" and "Handling Touches".

[Handling Text Input](https://facebook.github.io/react-native/docs/handling-text-input.html) page ([docs/HandlingTextInput.md](https://github.com/facebook/react-native/blob/master/docs/HandlingTextInput.md)) has "next" in metadata that was updated:

```
-next: using-a-scrollview
+next: handling-touches
```

However, the "follow to the next topic" section in the text was forgotten to be updated.

This PR updates the "follow to the next topic" section also to point to "Handling Touches".

### CODE REVIEW

**Comment by hramos** [comment]
Thanks for catching this! Should we also update Handling Touches to introduce the next topic?

**Comment by toukovk** [comment]
@hramos If you mean the links to the next section, [Handling Touches](https://facebook.github.io/react-native/docs/handling-touches.html) ([HandlingTouches.md](https://github.com/facebook/react-native/blob/master/docs/HandlingTouches.md)) seems to already have the same proper link to "Using a ScrollView" both in next meta & "follow to the next topic" section:

```
next: using-a-scrollview
```
```
... In order to handle these and other gestures, we'll learn [how to use a ScrollView](docs/using-a-scrollview.html) next
```

**Comment by hramos** [comment]
@toukovk sorry for the inconvenience, but can you open a new PR with the same commits? It looks like our tooling here is having trouble importing this. Nothing you can do about it. I'll give it another go just in case it actually lands this time.

**Comment by toukovk** [comment]
@hramos I created a new PR, please check out https://github.com/facebook/react-native/pull/15176

**Pull request closed without merging**
