### PR TITLE
added ArcChat.com Android app to showcase

### PR DESCRIPTION
**Pull request by liesislukas**
Added http://arcchat.com/ android app https://play.google.com/store/apps/details?id=com.arcchat  to showcase https://facebook.github.io/react-native/showcase.html

### CODE REVIEW

**Comment by grabbou** [comment]
Hey, looks good!

Would you mind moving your app at the top of the list to keep it alphabetical? Also - if you could move the other 2 (at the end) that are not sorted, that would be awesome. I think one of them is my fault as I've shipped it yesterday w/o checking this.

Thanks!

**Comment by liesislukas** [comment]
here you go :+1:

**Comment by grabbou** [comment]
Thanks!!

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
