### PR TITLE
Update NativeComponentsIOS.md

### PR DESCRIPTION
**Pull request by martco**
Shouldn't the string in `requireNativeComponent` match the code above?

### CODE REVIEW

**Comment by brentvatne** [comment]
@martco - pretty sure it should be `RCTMap`, can you try running the code?

**Comment by martco** [comment]
@brentvatne thanks, that explains it.

**Comment by brentvatne** [comment]
Great :smile: - if you're up for it, maybe you could add that to the docs to clarify so others don't have the same confusion that you had

**Comment by jtremback** [comment]
#1498

**Pull request closed without merging**
