### PR TITLE
Support geolocation in android webview

### PR DESCRIPTION
**Pull request by jvassbo**
Makes sure request for geolocation use in the webview is handled.
This solves issue #7609 

Currently use of geolocation in webview fails silently, as the permission request is never received by the native app.

**Test plan (required)**

1. Create new project with webview
2. Add javascript for geolocation:
```javascript
navigator.geolocation.getCurrentPosition(function (position) {
  console.log('success', position)
}, function (error) {
  console.log('could not determine position', error)
})
```
3. Run code and assert geolocation permission is requested, resulting in success (or error) callback being called

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by bbay** [comment]
I just tested this PR and it worked right away 👍 

I just followed the instructions to re-build React Native from source and my app which has a webview that loads an url which uses geolocation just worked!

@mkonicek @nicklockwood is there anything I can do to help with this PR?

**Comment by danielbraun** [comment]
@jvassbo a test failed, try to merge master and re-run?

**Comment by jvassbo** [comment]
@danielbraun not sure why the circleci build failed now, it looks like `code-analysis-bot.js` was unable to find the changed in this PR..

**Comment by danielbraun** [comment]
@jvassbo I suggest you try again, it sometimes fails for weird reasons.

**Comment by jvassbo** [comment]
@danielbraun Took a couple of tries, but now both CircleCI and Travis builds are green.

**Comment by danielbraun** [comment]
@jvassbo great. Mine also took a few times.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by vadimeremeev** [comment]
Experience same issue while building app for my web-site. Is this PR already included into react-native v0.35.0 ?

**Comment by bbay** [comment]
@vadimeremeev this was included in the [v0.31.0 release](https://github.com/facebook/react-native/releases/tag/v0.31.0) so _it should also work_ on that version, altho I haven't tried that specific release.

**Pull request closed without merging**
