### PR TITLE
Reverting Flow related changes from CI 15749 to get builds back in order

### PR DESCRIPTION
**Pull request by ericnakagawa**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

Reverting 3 commits that introduced new Flow errors during build process. This has resulted in CI not being able to successfully build. The engineer working on this has been tasked.

63d3ea17a717f032c59f0de315f4b197ededcfec
5042bae259cefb2128361e5d798b4c92befec0a9
6283878e17a74672371f769c45ad7b27ea74f8e3

Additionally, this exposed some errors in the website generation step and so I've reverted that commit as well.

118e88393e389ff70e30ada10a69b72dd31d869a

This should get CI back to green.

### CODE REVIEW

**Comment by mkonicek** [comment]
Which commit is it reverting?

**Comment by mkonicek** [comment]
lgtm, please message Spencer and Dan on fb@work (Workplace) messenger (not personal), so they know about this. It's not guaranteed people see GitHub notifications (people have too many).

**Comment by gaearon** [comment]
https://github.com/facebook/react-native/commit/118e88393e389ff70e30ada10a69b72dd31d869a is fixing an issue that is breaking people's builds internally. Can we please fix forward instead? If it breaks the website then it's the problem with the website scripts, not with this commit.

**Comment by gaearon** [comment]
I sent a fix for the website problem in https://github.com/facebook/react-native/pull/12479.

**Comment by ericnakagawa** [comment]
@gaearon The previous 3 reverts were to get CI back into a good state. Looks like this import failed so CI is still a mess.

**Comment by gaearon** [comment]
I understand the reasoning. I'm just asking you not to land revert of https://github.com/facebook/react-native/commit/118e88393e389ff70e30ada10a69b72dd31d869a because this will cause other problems. Instead, I will land #12479 now.

**Comment by gaearon** [comment]
https://github.com/facebook/react-native/pull/12479 has landed so you should be able to remove that revert.

**Comment by ericnakagawa** [comment]
@gaearon There were issues with original landing. I will be revoking this PR and handing over troubleshooting to next oncall.

**Comment by hramos** [comment]
Closed in favor of #12526.

**Pull request closed without merging**
