### PR TITLE
Add line number info to red screen.

### PR DESCRIPTION
**Pull request by greghe**
Include the localizedFailure reason in the red box screen so that Javascript syntax errors will report the line number in the packaged file where the error occurred.

### CODE REVIEW

**Comment by vjeux** [comment]
Can you put a screenshot of how it looked before vs after?

**Comment by greghe** [comment]
sure.  

Current:
current

Improved:

improved

We could get fancier with the formatted error string, but this seems sufficient.

**Comment by vjeux** [comment]
Thanks! We should probably figure out how to get some source mapping but that's better than what was before.

@facebook-github-bot shipit

**Comment by vjeux** [comment]
Actually @nicklockwood or @javache do you know if adding it to RCTFatal is going to have side effects outside of syntax errors? It seems like a very generic method

**Comment by greghe** [comment]
I know that for some errors the detailedFailureReason field can be null, in which case this screen will now display `(null)` as the contents of the detailed failure reason. But I figure this is OK since it is showing you that there is no additional information being reported in that field.

**Comment by mkonicek** [comment]
Removing the accepted label because it looks like this needs more info and the merge to the internal codebase was manually paused.

cc @javache Is this good to go? (See Christopher's question above.)

**Comment by javache** [comment]
This looks reasonable but I'm mainly worried it will cause too much noise on the redbox and in the console. Is there any other way we can make this information available? Maybe can we just special-case syntax errors coming from the RCTJSCExecutor?

**Comment by vjeux** [comment]
Note that this is a very rare event. This is a syntax error that got triggered by jsc and NOT caught by babel.

Usually this happens when babel has support for a feature that wasn't enabled. So it parses correctly on babel side but still isn't valid for jsc

**Comment by javache** [comment]
I'm working on integrating the stacktrace for all JSC errors, which should be a fair bit more readable than just adding this whole dictionary to the message and will work with symbolication tools.

**Comment by mkonicek** [comment]
Thanks for the update @javache. Should we close this PR since you're working on a different solution?

**Comment by javache** [comment]
I'll update here when my fix lands.

**Comment by mkonicek** [comment]
Nice, thanks for the fix @javache!

**Pull request closed without merging**
