### PR TITLE
[RCTLog] Use getters and setters

### LINKED ISSUE #2423: [Crash] EXC_BAD_INSTRUCTION (SIGILL) RCTLog.m:37
The crash report points to this line: ` __attribute__((constructor))` in `RCTLog.m:37`. Looks like a very cryptic issue deep within the system internals and not really with the code itself. Anyone else hitting this? Any way we can avoid this?

```
Hardware Model:      iPhone7,2
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2015-08-21 08:51:08.887 +0530
Launch Time:         2015-08-21 08:51:08.691 +0530
OS Version:          iOS 8.4 (12H143)
Report Version:      105

Exception Type:  EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x00000000e9d55821
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   AppName                          0x00000001002c8728 RCTLogSetup + 0 (RCTLog.m:37)
1   dyld                            0x00000001200b93ec ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 32 (ImageLoaderMachO.cpp:1811)
2   dyld                            0x00000001200b5688 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 328 (ImageLoader.cpp:1017)
3   dyld                            0x00000001200b54d8 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 136 (ImageLoader.cpp:489)
4   dyld                            0x00000001200b57a0 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 80 (ImageLoader.cpp:504)
5   dyld                            0x00000001200aa150 dyld::initializeMainExecutable() + 196 (dyld.cpp:1122)
6   dyld                            0x00000001200ad8bc dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 2664 (dyld.cpp:4864)
7   dyld                            0x00000001200a9040 _dyld_start + 64 (dyldStartup.s:301)
 ```

### PR DESCRIPTION
**Pull request by paramaggarwal**
As per discussion in #2423 - possible fix for crash. (cc: @javache)

Please share feedback regarding the PR, we are going to be using this diff in production to see if it fixes the crashes we are seeing.

(fixes #2423)

### CODE REVIEW

**Comment by javache** [comment]
I'd avoid creating a class just to hook in on load. Putting the dispatch_once in load is not very useful either, since it will only be executed when the program is getting read into memory. The timing would actually be very similar to `__attribute__((constructor))` and might not be caught by crash reporting frameworks like breakpad.

If possible, I'd try to insert this dispatch_once wherever we try to use the default log function (not everything is going to the accessor method right now, so that would need to be changed.

Looking forward to hearing whether this change helps fixing the crash in production.

**Comment by paramaggarwal** [comment]
@javache Yes, that is exactly my goal at the moment. To avoid using the `__constructor__` API and instead use some Objective-C construct. The fact that this doesn't really change anything is exactly what I am going for.

Let's see if this fixes our crashes. Will update.

**Comment by paramaggarwal** [comment]
@javache I have rethought these changes based on your comments and updated PR. Please do share feedback.

**Comment by javache** [comment]
@facebook-github-bot  import

**Comment by paramaggarwal** [comment]
Thanks @javache.

**Comment by paramaggarwal** [comment]
Our crashes are resolved. Thanks @javache for your help.

**Pull request closed without merging**
