### PR TITLE
macOS: Implement Platform.isMac

### PR DESCRIPTION
**Pull request by charpeni**
## Summary

Implementing `Platform.isMac` to know if we're running on macOS with Catalyst.

⚠️ Note that `Platform.OS` is still returning `ios`, even on macOS.

We'll be able to use `Platform.isMac` to target macOS.

```javascript
import { Platform } from 'react-native';

if (Platform.isMac) {
  // Do something specific to macOS
} else {
 // Do something else for other platforms.
}
```

## Changelog

[iOS] [Added] - Implement Platform.isMac to know if we're running on macOS with Catalyst.

## Test Plan

```javascript
// On iOS
Platform.isMac // false

// On macOS
Platform.isMac // true
```

### CODE REVIEW

**Comment by dulmandakh** [comment]
how about returning false in Platform.android.js

**Comment by charpeni** [comment]
@dulmandakh should we? I think it will be great to compare boolean values instead of falsy/truthy, but we're not doing it for other properties like `isTV`.

Is still working with like this, because `undefined` is falsy.

```javascript
if (!Platform.isMac) {
  // Reached on Android
}
```

**Comment by dulmandakh** [comment]
sure 😇

**Comment by charpeni** [comment]
Thanks for the feedback, @dulmandakh!

Added `Platform.isMac` to `Platform.android.js` in 2765151! Other properties could be handled in other pull requests.

**Comment by xiao99xiao** [comment]
Any update about this PR? I believe this is a must-have for building Catalyst apps.

**Comment by exotexot** [comment]
Would appreciate having this feature!

**Comment by safaiyeh** [comment]
Should this be isCatalyst? Given we have react-native-macos now, this might cause some confusion.

**Comment by losh11** [comment]
Would appreciate this, but as @safaiyeh said it makes much more sense to change Platform.isMac to Platform.isCatalyst.

**Comment by charpeni** [comment]
Thanks for bumping this in my notifications.

I submitted a new PR addressing the concern around [`react-native-macos`](https://github.com/microsoft/react-native-macos): https://github.com/facebook/react-native/pull/29937.

In the meantime, if you need to detect if the environment is Catalyst, I extracted it into an external library available as [`react-native-is-catalyst`](https://github.com/charpeni/react-native-is-catalyst).

**Comment by sota000** [comment]
Hi @charpeni, could you please resolve the merge conflict? After that I will send this to an internal review. Thanks!

**Comment by sota000** [comment]
Actually, it sounds like this PR should be closed, and the new PR should be reviewed. Is that right?

**Comment by xiao99xiao** [comment]
I think so.

**Comment by sota000** [comment]
Closing this PR in favor of #29937. Please reopen if you think otherwise.

**Pull request closed without merging**
