### PR TITLE
Symbolicate unhandled promise rejections

### PR DESCRIPTION
**Pull request by fortmarek**
## Summary:

Cherry pick of https://github.com/facebook/react-native/commit/18c9797ecc8dab220ec68aae011ddb73db17a99d. Doing a PR due to merge conflicts.

## Changelog:

[GENERAL] [FIXED] - Show correct stack frame on unhandled promise rejections on development mode.

## Test Plan:

See test plan in https://github.com/facebook/react-native/pull/40914

### CODE REVIEW

**Comment by fortmarek** [comment]
@ospfranco would you have time to look at the failed pipeline, so we can backport this to 0.72?

**Comment by ospfranco** [comment]
None of the errors on the CI look like they have to do anything with my code. Don't know how to fix those.

**Comment by fortmarek** [comment]
@ospfranco you are right, sorry for the ping. I redid the cherry pick and kept the flow type we have in `0.72-stable` instead of the one that's on `main`.

**Comment by swrobel** [comment]
This should be working as of 0.72.7, correct? I just upgraded from 0.72.6, and the error screen doesn't seem to have improved:
Simulator Screenshot - iPhone SE (3rd generation) - 2023-11-14 at 15 17 19

**Comment by swrobel** [comment]
> Are you sure you are on 0.72.7

Yes, positive

**Comment by joe-sam** [comment]
@swrobel I created a reproducer with the test plan by initiating a new react native project on version 0.72.7 and it worked fine, as you can see the warning is updated successfully (lowercased) and the promise rejection stack trace appears to be symbolicated successfully. Unsure why it was not working earlier for me ( I may not have updated RN to 0.72.7). I am removing my pick request.
image

**Pull request merged**
