### PR TITLE
if quick call jumpTo the transitionQueue will be quit before handle a…

### PR DESCRIPTION
**Pull request by carlos-wong**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

…ll the action in the queue

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @hedgerwang to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by carlos-wong** [comment]
I am checking the code of _transitionTo. It will be stop handle the transitionQueue if the destIndex is equal of the middle stage presentedIndex. So I think if the transitionQueue if not empty should not simlp check the destIndex and presentedIndex. It will quit the transitionQueue early. Next time navigator handle the nav, it will mess the transitionQueue. I just test in my program. After the change, the transitionQueue will work until finish.

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
@carlos-wong Can you please update the summary of this PR to explain what it does, why, and add a test plan showing that it works and doesn't break any existing functionality?

**Comment by carlos-wong** [comment]
@mkonicek 
What it does:  make the jumpTo function quit before all the event in the queue is handled.
Test: you make a two scene in the init route stack. And call jumpto between the two scene 20 times in 10 seconds. The finial scene will not be the last call jumpto scene.

**Comment by mkonicek** [comment]
Thanks! cc @hedgerwang, @ericvicenti

**Comment by mkonicek** [comment]
@carlos-wong Can you please update the PR description? You can edit it. If this gets merged it will become the commit message so pretty important it's descriptive :)

**Comment by ericvicenti** [comment]
Thanks for the fix, this makes sense!

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1063329117055529/int_phab) to review.

**Pull request closed without merging**
