### PR TITLE
Back out "Add onUserLeaveHint support to ReactActivityDelegate #43488"

### PR DESCRIPTION
**Pull request by rubennorte**
Summary: This change broke some apps at Meta. Reverting until we figure out a safe way to land this.

Differential Revision: D55324557

### CODE REVIEW

**Comment by cortinico** [comment]
This is being reverted because of this error:
434218817_2543331965867630_775261948160717462_n (1)

**Comment by behenate** [comment]
@cortinico Is it possible for you to check more in depth how this is causing the crash in your apps? From my perspective it's really hard to figure out why `onUserLeaveHint` breaks something with overriding modules 🤔

**Comment by cortinico** [comment]
> @cortinico Is it possible for you to check more in depth how this is causing the crash in your apps? From my perspective it's really hard to figure out why `onUserLeaveHint` breaks something with overriding modules 🤔

I need to investigate a bit further to understand what's happenign. Could you re-send the same PR again? Sorry for the back-n-forth

**Comment by behenate** [comment]
@cortinico Sure! Thanks for the help with this PR even though we it keeps getting reverted 😅

**Pull request closed without merging**
