### PR TITLE
Add Save a Stray to showcase

### PR DESCRIPTION
**Pull request by mixophrygian**
Save a Stray is an app built with React Native that uses Yelp's API to help a user locate nearby animal rescue shelters, call them, and get directions in three taps.  Android version soon to follow!

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
@mixophrygian updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@mixophrygian updated the pull request.

**Comment by mixophrygian** [comment]
What can I do to make this pass CircleCI?

**Comment by lacker** [comment]
Hey, I'm really sorry for the churn, but we are changing up how the showcase works, and just focusing on apps that have some media presence or technical blog posts / other content. So I appreciate the spirit behind this pull request but I think we should close it.

**Pull request closed without merging**
