### PR TITLE
[Android] Fixed template build gradle error on x86_64

### LINKED ISSUE #23893: build.gradle should be x86_64 instead of x86-64
## 🐛 Bug Report
A typo in build.gradle under android/app/ folder causing x86_64 apk not being build.

## To Reproduce
```
abi {
    ...
    include "armeabi-v7a", "x86", "arm64-v8a", "x86-64"
}
```

## Expected Behavior
```
abi {
    ...
    include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
}
```

## Code Example
N/A

## Environment
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 135.56 MB / 7.69 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.15.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 26.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

### PR DESCRIPTION
**Pull request by zhongwuzw**
## Summary

Fixes #23893 . Fixes x86_64 apk build.

## Changelog

[Android] [Fixed] - Fixed template build gradle error on x86_64

## Test Plan

CI passes.

### CODE REVIEW

**Comment by hramos** [comment]
The fact this issue has been in master for 2.5 months without it being caught is troublesome. Can you try adding a test to make sure we don't regress here in the future?

**Comment by zhongwuzw** [comment]
@hramos Seem we have no way to build on `x86_64`. Please see https://circleci.com/docs/2.0/faq/#which-cpu-architectures-does-circleci-support.

**Comment by dulmandakh** [comment]
I think we should add tests for the template, which will initialize a new project then build it for both Android and iOS. For Android, we can analyze APKs and check for dynamic libraries.

**Comment by grabbou** [comment]
Right now, we manually test inited app - I guess we would need to factor in other architectures. Is this PR landing? I'd like to release this to 0.59-stable branch.

**Comment by dulmandakh** [comment]
I think it's best to merge this PR and open an issue about template tests.

**Pull request closed without merging**
