### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by jarwino**

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks @jarwino! Can you sing the CLA please (see the comment by the bot above)?

**Comment by facebook-github-bot-2** [comment]
@mkonicek would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by dsibiski** [comment]
@jarwino If you're able, please sign the CLA so we can get this merged 👍

**Comment by facebook-github-bot-7** [comment]
@jarwino I tried to find reviewers for this pull request and wanted to ping them to take another look. However, based on the blame information for the files in this pull request I couldn't find any reviewers. This sometimes happens when the files in the pull request are new or don't exist on master anymore. Is this pull request still relevant? If yes could you please rebase? In case you know who has context on this code feel free to mention them in a comment (one person is fine). Thanks for reading and hope you will continue contributing to the project.

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
The docs have been rewritten so will close this one as it doesn't apply anymore:
http://facebook.github.io/react-native/docs/getting-started.html

Thanks for the fix and sorry it got missed.

**Pull request closed without merging**
