### PR TITLE
Update Performance.md

### PR DESCRIPTION
**Pull request by mikestek**
Removed information about babel plugin that does not work with current version of RN

### CODE REVIEW

**Comment by mkonicek** [comment]
Why doesn't it work? Do you have a link to a source showing why it's not working?

**Comment by mikestek** [comment]
https://github.com/facebook/react-native/issues/10412
shows others have been unable to get it working. I spent a while without being able to make release builds before was able to track down that the babel plugin was the issue, since I didn't think of checking something that was recommended by the official documentation first. So it shouldn't be in documentation if it doesn't work.

**Comment by javache** [comment]
Can you rebase and resolve conflicts?

**Comment by javache** [comment]
This pull request has been inactive for a while and the last comments are questions or there have been changes requested.

I'll close the pull request so it doesn't stay open indefinitely. If you plan to continue working on this please send a new pull request.

**Pull request closed without merging**
