### PR TITLE
fix: node module resolution for react-native/normalize-color

### PR DESCRIPTION
**Pull request by EvanBacon**
## Summary

I attempted to use this package in a node module but node module resolution will fail to resolve it properly.  A `package.json` without a `main` field will default to `./index.js`, but the default file here is `./base.js`. 

For future readers; even after this is merged it'll still not work with node tools because flow types are present in the file.

## Changelog

[General] [Fixed] - Added `main` field to `package.json` of `@react-native/normalize-color`

## Test Plan

- eyeball'd it

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
would be nice to remove flow as well, or move them to an optional type definition

**Comment by yungsters** [comment]
> would be nice to remove flow as well, or move them to an optional type definition

Yeah, we could move them to a separate library definition file.

**Comment by yungsters** [comment]
I just published [@react-native/normalize-color@2.0.0](https://www.npmjs.com/package/@react-native/normalize-color) which works using Node.js by splitting out Flow type definitions into an accompanying library definition file. I also included the rename from `base.js` to `index.js` to make usage more idiomatic.

The internal commit will be landing soon and sync'd to the repository for you to see the changes. But the published package is ready for consumption immediately. I'll be closing this PR because it has been superseded.

**Comment by yungsters** [comment]
See https://github.com/facebook/react-native/commit/65e58f26e1fbd06b1ae32e2ab3a2616c8eef08e0 for the changes which went into **@react-native/normalize-color@2.0.0**.

**Pull request closed without merging**
