### PR TITLE
[StatusBar] Add ability to toggle the network activity indicator in the status bar + example in UIExplorer

### LINKED ISSUE #986: [WebView] network Activity Indicator for WebView
Hello there.
Do we have possibility to use network Activity Indicator for WebViews without modifying files in Xcode?

### PR DESCRIPTION
**Pull request by negativetwelve**
Added the ability to turn on and off the network activity indicator using:

```
StatusBarIOS.setNetworkActivityIndicatorVisible(true)
```
and
```
StatusBarIOS.setNetworkActivityIndicatorVisible(false)
```

Also added an example to the UIExplorer example app.

Fix #986

### CODE REVIEW

**Comment by negativetwelve** [comment]
I don't think this test is related to my change, but can someone familiar with the UIExplorer tests shed some light here, would really appreciate it, thanks!

```
    ✗ -[RCTAllocationTests testContentViewIsInvalidated] (238 ms) (0)
```

**Comment by frantic** [comment]
:+1: thanks!

**Comment by frantic** [comment]
@facebook-github-bot import

**Comment by vjeux** [comment]
@facebook-github-bot import

**Pull request closed without merging**
