### PR TITLE
Fixes syntax typo in DirectManipulation section of docs

### PR DESCRIPTION
**Pull request by tegon**
Fixing JSX tag in DirectManipulation section of the docs

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @sunnylqm and @bestander to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
@tegon updated the pull request.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/220926964961286/int_phab) to review.

**Pull request closed without merging**
