### PR TITLE
overlayColor property for image

### PR DESCRIPTION
**Pull request by NoBaR**
In Android, Fresco's default rounding corners support mode is BITMAP_ONLY which doesn't work in all cases (such as animated GIF's, some scale types, etc.).
Specifying the new "overlayColor" property on an Image will cause Fresco to switch to the other rounding corners mode, OVERLAY_COLOR, and will draw rounded corners by overlaying the solid color specified.

Fresco's behaviour is explained here: http://frescolib.org/docs/rounded-corners-and-circles.html

### CODE REVIEW

**Comment by satya164** [comment]
This PR seems to have lots of unrelated changes.

**Comment by NoBaR** [comment]
yes, I dont know why it included 10 more commits, only 5fb7960 is needed.

**Comment by satya164** [comment]
Can you create a new PR with only that change?

**Comment by NoBaR** [comment]
ok, i will.

**Comment by NoBaR** [comment]
Apparently, branch 0.16-stable (which is what I used as base) is 10 commits ahead of the master :/
I'll sort it out with a new PR...

**Comment by NoBaR** [comment]
Created https://github.com/facebook/react-native/pull/5366

**Pull request closed without merging**
