### PR TITLE
Added ReactCommon to package.json to allow for building locally

### PR DESCRIPTION
**Pull request by jgibbons**
This pull request solves an error building from source as noted in https://github.com/facebook/react-native/issues/7911 and https://github.com/facebook/react-native/pull/7118. The error says BUILD FAILED due to cxxreact module not found. Previously the ReactCommon folder was excluded when installed from npm. There may be a better way to include this folder, but I'm unfamiliar with FB's build process.  

**Test plan (required)**

Create a new sample project by npm init, npm install --save https://github.com/opensports/react-native.git. Then run react-native run-android and the project should build successfully.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@jgibbons updated the pull request.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1748396618739795/int_phab) to review.

**Pull request closed without merging**
