### PR TITLE
Reading and Deskbookers app sorted alphabetically

### PR DESCRIPTION
**Pull request by emilioicai**
As requested:
- Reading and Deskbookers app sorted alphabetically
- link key used instead of linkToAppstore

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
@lyandrew would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Merging again.

**Comment by mkonicek** [comment]
@emilioicai There's a merge conflict, sorry about that. Can you rebase please?

**Comment by facebook-github-bot-9** [comment]
@emilioicai updated the pull request.

**Comment by mkonicek** [comment]
Thanks @emilioicai!

@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1173479562662461/int_phab) to review.

**Comment by geirman** [comment]
@mkonicek not sure if you noticed this import failed. are you able to resolve the conflicts?

**Comment by javache** [comment]
We did a big overhaul of the showcase so I think this is no longer relevant.

**Pull request closed without merging**
