### PR TITLE
Add Zerocar application for showcase.

### PR DESCRIPTION
**Pull request by alma-socar**
- Newly created mobile application for both iOS and Android

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @myusuf3 to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
@alma-socar updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@alma-socar updated the pull request.

**Comment by lacker** [comment]
Thanks for submitting this pull request! According to the showcase guidelines, `infoLink` should refer to one of:

1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical blog post by the app creators specifically discussing React Native

It looks like this doesn't match the criteria, so I'm going to close this pull request. But please feel free to reopen it if there is updated link information in the future.

**Pull request closed without merging**
