### PR TITLE
Update Debugging.md

### PR DESCRIPTION
**Pull request by tryangul**
The current directions do not explain how to get to the Developer Menu, which when using the Android Emulator specified in the docs is unclear. I spent a solid 30 minutes googling, until I found this Hint elsewhere in the react-native docs. Feel free to shorten and amend. But some explanation is necessary.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
The preceding section, [Accessing the In-App Developer Menu](https://github.com/tryangul/react-native/blob/c21ce056f5bd5f2522d08b97f810412398e70a1b/docs/Debugging.md#accessing-the-in-app-developer-menu), should cover this already.

**Comment by tryangul** [comment]
Using the same emulator on Linux, ctrl+M does not access the android dev menu. Perhaps the Hint should go above in that section?

**Comment by facebook-github-bot-3** [comment]
@tryangul do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by mkonicek** [comment]
@tryangul I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment requests changes. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to continue working on this.

**Pull request closed without merging**
