### PR TITLE
Add Foodstand to RN showcase

### PR DESCRIPTION
**Pull request by rreusser**
Foodstand is a community built around eating good food. We've rewritten our iOS app in React Native and are would love to submit it to the showcase!

Thanks!

### CODE REVIEW

**Comment by brentvatne** [comment]
Thanks!

**Comment by brentvatne** [comment]
@rreusser - FYI this app crashes when I try to progress past the "Choose some interests below" screen, signing in via Facebook. Seems to work with Instagram.

**Comment by udfalkso** [comment]
Thanks Brent.  Are you by chance on an iPhone 6+?

**Comment by brentvatne** [comment]
iPhone 6S (normal)

**Comment by udfalkso** [comment]
Thanks again Brent.  We're investigating this issue.

**Comment by udfalkso** [comment]
@brentvatne If you update the app to 3.0.1 this issue has been fixed and you should be able to sign in via FB.  Thanks!

**Comment by brentvatne** [comment]
Nice one @udfalkso :)

**Pull request merged**
