### PR TITLE
Make it easier to develop ReactNative from repo HEAD

### PR DESCRIPTION
**Pull request by hayeah**
There are a few problems that makes it hard to contribute to ReactNative.

1. No easy way to start small experiments without installing react-native over and over again.
2. No documentation that shows you how to develop ReactNative itself.
3. Making changes to the ReactNative repo necessitates another `npm install` to update the sample app. 

A "container app" similar to rnplay.org would make it much easier to do small experiments, as well as developing RN itself in IDE.

# PR Description

+ Brief Instructions for how to develop from the repo included in a [README](https://github.com/hayeah/react-native/blob/react-play-app/Examples/ReactPlay-hello/README.md).
+ Adds the `ReactPlay` app to `Examples`, to make it easy to run simple entry files without having to install react-native over and over again.
  + The entry file uses `SampleApp` as the entry module, thus is compatible with rnplay.
+ Makes it possible to link the react-native repo and use cli tools by running `react-native-global` .
+ Adds the `--play` flag to `run-android` and `run-ios` cli commands, to launch the ReactPlay app from the linked repo.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @martinbigio to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@hayeah updated the pull request.

**Comment by hayeah** [comment]
What's current recommended workflow for working on ReactNative?

**Comment by martinbigio** [comment]
@vjux and @mkonicek are probably the best reviewers for this PR

**Comment by janicduplessis** [comment]
Do we need to add a new app? I've had some success working on a feature or bug fix by creating a page in the UIExplorer app and working from there. I like the ability to be able to tests the cli tools, I always ended up working in an app's node_modules to test it.

**Comment by hayeah** [comment]
@janicduplessis if the app is standlone, then it's possible to create a cli command like `react-native play index.ios.js` to run a source file like rnplay.

**Comment by satya164** [comment]
When tweaking an existing feature, I usually work with `UIExplorer`, but I agree that it'll be super useful to have a playground app when starting with a new feature.

**Comment by mkonicek** [comment]
Why not use the `UIExplorer`?

**Comment by mkonicek** [comment]
This PR is 107 files, likely copied? How are you going to keep them in sync when the source files change?

**Comment by hayeah** [comment]
@mkonicek like UIExplorer, the ReactNative core is linked as project dependencies. Just edit the source files directly. 107 Files are the project templates, test files, and assets, copied from UIExplorer.

**Comment by hayeah** [comment]
@satya164 I put together the `react-native play` idea in an npm package, you could try it out

https://github.com/hayeah/rnplay

**Comment by facebook-github-bot-8** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @cpojer as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by satya164** [comment]
@grabbou May be we can implement something like `react-native play` as a `rnpm` plugin. What do you think?

**Comment by grabbou** [comment]
Yeah, that could work @satya164. When I am working on features / bug fixes - I also play around with UIExplorer by either checking it out live on the existing page, or by adding a new entry point and starting from there.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/make-it-easier-to-develop-reactnative-from-repo-head

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Pull request closed without merging**
