### PR TITLE
fix: image mock in jest setup

### PR DESCRIPTION
**Pull request by delphinebugner**
## Summary:

`resolveAssetSource` should not return nothing by default in jest as some librairies (ex: [react native fast image](https://github.com/DylanVann/react-native-fast-image/blob/9ab80fcd570b7f56da66ab20e52c9a35934067c9/src/index.tsx#L176C71-L176C71)) rely on it!
They use it to compute the image source ; without this mock implementation, all sources disappear from images in test environnement - and we do test them a lot in test env (may be the only part of Images we actually look at in snapshots! )

Relates to issue https://github.com/facebook/react-native/issues/41907 -> not sure it fixes though, as in test the "require" source resolves to an object with assetFileTransformer - still having no width and height in output even with the real `resolveAssetSource`

It was introduced in version 0.73, where Image mock was changed - see PR https://github.com/facebook/react-native/pull/36996

## Changelog:

[GENERAL][FIXED] - fix jest setup for Image.resolveAssetSource

## Test Plan:
Here is a simple test rendering a [FastImage](https://github.com/DylanVann/react-native-fast-image) with `source = { uri : "some-string"}` :

Without the fix : source is "undefined" in test :
image

With the fix : 
image

the console.log comes from react native fast image and indicates that source is correctly retrieved

I also tested passing a `require(../path.png)` as source : 
Without the fix : 
image

With the fix : 
image

### CODE REVIEW

**Comment by ryancat** [comment]
If this works before PR #36996, is it possible to just remove the line for `resolveAssetSource` and use the original defaults?

**Comment by idrissakhi** [comment]
@delphinebugner agree with @ryancat we should remove the line so it's require the actual ImageResolver to get the real image data such as width ... etc

**Comment by delphinebugner** [comment]
Yes you're right, I was going too quicly, we should absolutely keep what's ImageResolver normally do... Additional question is, should we also check and eventually remove other methods mocked in PR https://github.com/facebook/react-native/pull/36996? 

```typescript
  .mock('../Libraries/Image/Image', () => {
    const Image = mockComponent('../Libraries/Image/Image');
    Image.getSize = jest.fn();
    Image.getSizeWithHeaders = jest.fn();
    Image.prefetch = jest.fn();
    Image.prefetchWithMetadata = jest.fn();
    Image.queryCache = jest.fn();
    Image.resolveAssetSource = jest.fn();

    return Image;
  })
``` 
I checked for iOS and all of those methods just call native module NativeImageLoaderIOS ; `resolveAssetSource` is the only exception!

The original issue was about  `Image.getSize` getting undefined in test after jest setup : https://github.com/facebook/react-native/issues/35518
Out of curiosity I tried to reproduce the error in test, and even without the mock of custom methods, the test ran 🤷‍♀️ 

```
// the orginal broken test
const MyComponent = () => {
    useEffect(() => {
        Image.getSize('uri', (width, height) => {
            console.log({width, height})
        })
    }, [])

    return null
}

describe('Foo', () => {
    it('something', () => {
        render(<MyComponent/>)
    })
})
```

**Comment by delphinebugner** [comment]
Closed because I opened a newer + more exhaustive PR on the topic: https://github.com/facebook/react-native/pull/43497

**Pull request closed without merging**
