### PR TITLE
Added the ability to set the storage location

### LINKED ISSUE #19692: Allow control over AsyncStorage location on iOS
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 9.4.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

## Description

Currently, AsyncStorage stores data in the Documents directory on iOS. However, as discussed in [this issue](https://github.com/facebook/react-native/issues/2477), [this abandoned PR](https://github.com/facebook/react-native/pull/4561), and [this abandoned PR](https://github.com/facebook/react-native/pull/10697), there should be an option to store elsewhere, as this location is not appropriate for non-user-created content, as it is visible for apps that enable file sharing with iTunes or the Files app on iOS.

## Steps to Reproduce
This is the case on AsyncStorage on all versions of react-native to my knowledge.

## Expected Behavior
Some sort of control over the location in which AsyncStorage stores data, so that it will not be exported to iTunes, viewable via the Files app, etc. on iOS

## Actual Behavior
AsyncStorage saves to the Documents directory.

### PR DESCRIPTION
**Pull request by adamivancza**
Fixes #19692

Test Plan:
----------
I've created a sample application to verify & demonstrate that the feature is working as intended. I've also created a video:
asyncstorage

Release Notes:
--------------
[IOS] [FEATURE] [AsyncStorage] - Allow control over AsyncStorage location on iOS

### CODE REVIEW

**Comment by hramos** [comment]
Can you add tests?

**Comment by timotei-cliqz** [comment]
@adamivancza do you need help with the tests?

**Comment by adamivancza** [comment]
hey @timotei-cliqz! Sure thing - I won't have any time to work on this until the weekend anyway. If you do please add some tests meanwhile :).

**Comment by timotei-cliqz** [comment]
@adamivancza Will probably get to it next week.

**Comment by adamivancza** [comment]
hey @hramos @timotei-cliqz! Added the tests as discussed. PR failures seems to be independent of this PR:
* test_javascript & test_node10 failed for the same reason:
  * Animated tests Animated send toValue when an underdamped spring stops - Animated tests Animated send toValue when an underdamped spring stops
  * Error: Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...
* test_detox_end_to_end: There was an issue while running this container and it was rerun. The most recent run is shown.

**Comment by hramos** [comment]
Alright, importing to run this through our internal test suite and to also get it into the core team's review queue. Thanks for the PR!

**Comment by timotei-cliqz** [comment]
@adamivancza So cool! Thanks a lot!

**Comment by hramos** [comment]
This is still waiting for review internally, unfortunately. I'll ping some people.

**Comment by adamivancza** [comment]
thx @hramos - this is the pipeline for quite some time now

**Comment by hramos** [comment]
Yes. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cpojer** [comment]
Hey @adamivancza. Sorry for not getting back to this PR earlier. As part of the Lean Core effort (#23313) we moved AsyncStorage to its own repo, it would be great if you could re-send your PR to that one: https://github.com/react-native-community/react-native-async-storage I think it will be much easier to land and iterate a change like this over there :)

**Comment by adamivancza** [comment]
thx for the heads up @cpojer

**Pull request closed without merging**
