### PR TITLE
Fix android activity template. Fixes #5030

### LINKED ISSUE #5030: The MainActivity template in master generates invalid code
Currently the template used to generate `MainActivity.java` generates the following:

```java
package com.foo;

import com.facebook.react.ReactActivity;
import com.facebook.react.shell.MainReactPackage;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "foo";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected abstract List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage());
    }
}
```

This is invalid for several reasons. Firstly, it references `ReactPackage`, `Arrays`, and `List` without importing them. Secondly, it declares `getPackages()` as an abstract method when it actually implements the code. Thirdly (and this is the bit I can't work out how to fix), when you build the app to run on Android with `react-native run-android` it can't find `com.facebook.react.ReactActivity`, despite it being in the source tree.

The first two problems can be fixed by changing the generated `MainActivity.java` file to:

```java
package com.foo;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "foo";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage());
    }
}
```

You'll need to replace my project name with your own.

### PR DESCRIPTION
**Pull request by satya164**

### CODE REVIEW

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
Will try again.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
cc @mkonicek @vjeux Bot still broken?

**Comment by mkonicek** [comment]
Thanks so much for the fix @satya164! Don't know what I was doing :)

**Comment by mkonicek** [comment]
I tweaked your PR a bit - it added the `MainReactPackage` directly in the base activity which seems fine but I realized this created a circular dependency between `com.facebook.react` and `com.facebook.react.shell`, while `shell` depends on pretty much everything. I wanted to avoid that so kept apps depend on ``com.facebook.react.shell.MainReactPackage` as before.

**Comment by satya164** [comment]
@mkonicek Good to know. Thanks :)

**Pull request closed without merging**
