### PR TITLE
Set defaults in RCTBundleURLProvider so development mode is the default

### PR DESCRIPTION
**Pull request by jsierles**
This PR follows up from #8400 and  9845f49.

Sets URL parameters for ensuring dev mode is enabled by default.

Test Plan

Install React Native in a fresh app from react-native init.

update AppDelegate.m to use the new default development URL generator:

jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

Run on iOS device or simulator, and ensure that the dev menu can be pulled up.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @nathanajah and @shaneosullivan to be potential reviewers.

**Comment by javache** [comment]
@nathanajah is looking into changing this so we apply the defaults in the constructor.

We should also get rid of the dispatch_once.

**Comment by jsierles** [comment]
@javache Sounds good - would be good to get this into 0.29 to avoid confusion on the issue:

https://github.com/facebook/react-native/issues/8333#issuecomment-230071885

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @nathanajah as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by javache** [comment]
I think this has been fixed already, right?

**Pull request closed without merging**
