### PR TITLE
Fixed SyntaxError in example of scrollTo

### PR DESCRIPTION
**Pull request by BTMPL**
The example code uses semicolons where commas should be used.

## Motivation

Removing a typo in the documentation which might result in improper code usage.

## Test Plan

No test needed

### CODE REVIEW

**Comment by javache** [comment]
Please change the markdown files the .html is generated from: https://github.com/facebook/react-native/tree/master/docs

**Comment by BTMPL** [comment]
@javache I was actually trying to find it but it's not there - I believe it is auto generated from https://github.com/mkonicek/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L406 - if that is the case I will make a new PR and close this one.

**Comment by javache** [comment]
Yup, you would need to change it there. Please open a new PR.

**Comment by BTMPL** [comment]
Actually this is already resolved over a month ago - https://github.com/facebook/react-native/pull/13318 - but looks like it's not deployed yet.

**Comment by javache** [comment]
It's fixed in the next version of the docs: http://facebook.github.io/react-native/releases/next/docs/scrollview.html#scrollto

**Pull request closed without merging**
