### PR TITLE
Remove `babel-jest` from template

### PR DESCRIPTION
**Pull request by nonewcode**
## Summary

This removes babel-jest from the init template as it is now part of core and is installed when adding jest to a project.

## Changelog

[General] [Removed] - Remove babel-jest from init template

## Test Plan

N/A

### CODE REVIEW

**Comment by safaiyeh** [comment]
Hm I do not see it part of core?

**Comment by codecog** [comment]
@safaiyeh https://github.com/babel/babel-jest

"babel-jest is now automatically loaded by Jest and fully integrated."

**Comment by safaiyeh** [comment]
Awesome! Thanks for the link

**Comment by yungsters** [comment]
Sorry, we are working through some remaining issues with renaming the `master` branch to `main` and this PR was accidentally closed. We're working on fixing the affected PRs.

**Pull request closed without merging**
