### PR TITLE
Add transition to input search in website

### PR DESCRIPTION
**Pull request by rohmanhm**
I think if you add some transition to input search element in React-native website I think it should be good.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @Andreyco to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by vjeux** [comment]
Woot, this is #10000 !!!

**Comment by hramos** [comment]
Looks good, thanks!

**Comment by rohmanhm** [comment]
Hi @hramos  I've already joined to Facebook CLA.

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3899115) to review internal test results.

**Pull request closed without merging**
