### PR TITLE
Update runAndroid.js to fix startServerInNewWindow() (Windows)

### PR DESCRIPTION
**Pull request by jrodiger**
**Motivation**
Resolves issue: #12367. The issue is that the packager does not launch automatically on Windows when running `react-native run-android` like it does on OSX. The proposed change fixes this issue, and causes the packager to be launched automatically on Windows 10. Also note the updated code uses the syntax described in the [Node.js documentation](https://nodejs.org/api/all.html#child_process_spawning_bat_and_cmd_files_on_windows) on spawning .bat files on Windows.

**Test plan**
Manually tested on Windows 10.

Running just `react-native run-android` now results in the packager launching, without needing to run `react-native start` in a new command prompt window.

**Screenshot:**
packager

### CODE REVIEW

**Comment by mkonicek** [comment]
Ah so this never worked on Windows? What does the 'start' argument you removed do?

> Also note the updated code uses the syntax described in the Node.js documentation on spawning .bat files on Windows.

Which part of the docs?

**Comment by jrodiger** [comment]
@mkonicek On Windows 10 the command `start launchPackager.bat` runs the launchPackager.bat script in a new command prompt window/process, where as the command `launchPackager.bat` runs the batch script in the current command prompt/process. The 'start' argument is unnecessary in this case because in startServerInNewWindow() the line `return child_process.spawn('cmd.exe', ['/C', launchPackagerScript], procConfig);` is already creating a child process to run the script. I only have Windows 10 available to test this change. Should I open an issue asking for help testing this on different versions of windows? The part of the docs I am referring to is the section titled: "Spawning .bat and .cmd files on Windows" and in the docs the start argument is not used: https://nodejs.org/api/all.html#child_process_spawning_bat_and_cmd_files_on_windows

**Comment by janicduplessis** [comment]
I think it was me that implemented that I while back, it did work at some point so I'm not sure what change broke this but I also only tested on Windows 10 so should not be a Windows version issue. I'm fine with this change if you say it works.

**Comment by janicduplessis** [comment]
Looks like https://github.com/jrodiger/react-native/commit/d4cc5b53c7770f8206e8dbe99593131a3ad0c2d0 is the commit that broke it since it's the only one that made changes since my initial implementation. Just to make sure have you tested that this does not cause react-native start command to hang? It should be 2 completly independent processes and closing one should not close the other.

**Comment by jrodiger** [comment]
@janicduplessis @mkonicek `react-native start` works normally, and closing either the `react-native run-android` process or the packager process does not cause the other process to terminate.

**Comment by jrodiger** [comment]
@janicduplessis @mkonicek Is there anything else that needs to be tested?

**Comment by janicduplessis** [comment]
Cool looks good!

@facebook-github-bot shipit

**Pull request closed without merging**
