### PR TITLE
Use the right appName on init

### PR DESCRIPTION
**Pull request by jmhdez**
local-cli was getting the appName from process.argv instead of using appName parameter.

### CODE REVIEW

**Comment by mkonicek** [comment]
Assigning to @foghina to take a look.

**Comment by foghina** [comment]
This is not correct, `process.argv` can contain useful args for the generator (e.g. `--skip-ios`). This drops those arguments. You could do something like:

    var args = [appName].concat(process.argv.slice(4));

But please make sure command line arguments get passed down to the generator.

**Comment by foghina** [comment]
BTW, are you running into any specific issues due to this particular behavior?

**Comment by jmhdez** [comment]
You are right, @foghina. I didn't think about the other arguments.

I'll update the PR with your changes. Anyway, I'm not sure if this is the best option; since the dependency on `process.argv` is still there, maybe it's just better to remove the read `appName` from them and remove the `appName` argument from `init`.

I found the issue while trying to create a new project programmatically from the repl (probably an unsupported scenario anyway).

**Comment by foghina** [comment]
For this we could push the arguments list up. I.e. we can make `init()` take an `args` parameter and just pass `process.argv` from `cli.js`, so that others can more easily invoke `init()` without requiring a specific `process.argv`.

**Comment by jmhdez** [comment]
Since `local-cli/cli.js` is just exporting the required func "as is", I think `react-native-cli/index.js` could be a better place to handle command line args: https://github.com/facebook/react-native/blob/373c8777f6bad3a935089bd4c59bf2e15896de63/react-native-cli/index.js#L149

It already depends on `process.argv` anyway, so it doesn't require an extra dependency.

**Comment by foghina** [comment]
Sounds like a plan! Can you update your PR?

**Comment by jmhdez** [comment]
Done.

**Comment by foghina** [comment]
Thanks!

**Pull request merged**
