### PR TITLE
Add ability to change cache policy on iOS

### PR DESCRIPTION
**Pull request by bcaplan42**
React Native does not currently expose the ability to decide on the cache policy used by network requests. Android can work around this by utilising OkHttp Interceptors. For iOS, this PR extends the functionality of `RCTHTTPRequestHandler` by exposing an JS interface that can alter the cache policy as defined in [`NSURLRequestCachePolicy`](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSURLRequest_Class/#//apple_ref/c/tdef/NSURLRequestCachePolicy)

**Test plan**

- Make a request that returns a response with a relatively short cache duration
- Set the cache policy to `ReturnCacheDataDontLoad`
- Go offline, wait until the cached response should have expired, then make the request again.

The XMLHttpRequest demo in the UIExplorer example project has been updated with an example that demonstrates the functionality.

**Example Usage**

If a client wants to be able to serve previously viewed content when offline, even if it is known it could be stale, they could achieve it in such a way:

```
const { NetInfo } = require('react-native');
const { setCachePolicy } = require('NativeModules').HTTPRequestHandler;

NetInfo.isConnected.addEventListener(
  'change',
  (isConnected) => {
    if (isConnected) {
      setCachePolicy('UseProtocolCachePolicy')
    } else {
      setCachePolicy('ReturnCacheDataDontLoad')
    }
  }
);

```

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @grgmo and @nicklockwood to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@bcaplan42 updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@bcaplan42 updated the pull request.

**Comment by javache** [comment]
Cache policy is something you'd likely want to configure on a per-request basis, this is equivalent with one global singleton variable to configure it. Would it be possible to make this an option of the `fetch` API?

**Comment by facebook-github-bot-3** [comment]
@bcaplan42 do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by mkonicek** [comment]
@bcaplan42 I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment asks a question. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to continue working on this.

**Comment by domsmith94** [comment]
@javache I'm looking at taking this up as the ability to change the cache policy on iOS is something we really want to do for our application. My understanding is that Libraries/Fetch/fetch.js is a JS polyfill so I'm struggling to see how the NSURLRequest.CachePolicy could be set on a per-request basis from here. Any pointers of where to go from here to get this done? Thanks.

**Comment by javache** [comment]
`fetch` takes an options dictionary. I'm not sure how standardized it is, but you could add an option there to express any cache policy preference.

**Pull request closed without merging**
