### PR TITLE
[Android] Improve ellipsizeMode prop

### PR DESCRIPTION
**Pull request by rigdern**
There are a couple of buggy behaviors in the current implementation of the `ellipsizeMode` prop on Android:
  - Setting the `numberOfLines` prop stomps on whatever value you provided for `ellipsizeMode` earlier.
  - The value you've provided for `ellipsizeMode` is used even if you've configured your view to have an unlimited size (i.e. `numberOfLines` is 0 or unspecified).

This change fixes these issues which makes Android's `ellipsizeMode` prop more consistent with iOS's. Additionally, it renames LineBreakMode to EllipsizeMode in a couple of places.

**Test plan (required)**

Verified that the `numberOfLines` and `ellipsizeMode` props work correctly in an Android test app. 

Adam Comella
Microsoft Corp.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @skv-headless and @javache to be potential reviewers.

**Comment by javache** [comment]
cc @andreicoman11 @foghina

**Comment by foghina** [comment]
Won't this set the same number of lines on all text views, since `mNumberOfLines` is at the manager level and not the view level? We should probably move most of the changes in this diff to the `ReactTextView` class. See e.g. `ReactImageView` and its `maybeUpdateView` to see an example of how we forward `onAfterUpdateTransaction` to the view itself.

**Comment by facebook-github-bot-3** [comment]
@rigdern updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9594/files/7ec9153f3b2d7d65b24b23f7897ab44d7de21fc4..6cbc9720985ad0cf280115e3e15f8a3415c57082)

**Comment by facebook-github-bot-2** [comment]
@rigdern updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9594/files/6cbc9720985ad0cf280115e3e15f8a3415c57082..97be23a40d92f416aa8f6017ff92499a58e78ea9)

**Comment by facebook-github-bot-8** [comment]
@rigdern updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9594/files/97be23a40d92f416aa8f6017ff92499a58e78ea9..b809d5358565c2502c997b552c037207a233a408)

**Comment by rigdern** [comment]
@foghina oops, you are right. That was a silly mistake 😊 . I pushed an update which fixes that.

**Comment by foghina** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3810166) to review internal test results.

**Pull request closed without merging**
