### PR TITLE
Fix: RefreshControl in FlatList makes borderWidth not working

### LINKED ISSUE #22752: RefreshControl in FlatList makes borderWidth not working
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
  System:
    OS: Windows 8.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    Memory: 8.41 GB / 15.92 GB
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  2.3.0.0 AI-162.3871768
```

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
1. `react-native init MyTestingProject`
2. `cd MyTestingProject`
3. `react-native run-android`
4. Create a normal `<FlatList>`:

```javascript
import * as React from 'react';
import { Text, FlatList, RefreshControl } from 'react-native';

export default class App extends React.Component {
  state = {isLoading: false};

  render() {
    return (
      <FlatList
        style={{
          flex: 1,
          alignSelf: "stretch",
          borderWidth: 2,
          borderColor: "red"
        }}
        data={["a", "b", "c"]}
        renderItem={({ item }) => (
          <Text>
            {item}
          </Text>
        )}
        refreshControl={
          <RefreshControl
            colors={["red", "yellow"]}
            refreshing={this.state.isLoading}
            onRefresh={() => this.reload()}
          />
        }
      />
    );
  }
}
```

5. We have no **borders**! Now remove the `refreshControl` to see the **borders**:

```javascript
<FlatList
  style={{
    flex: 1,
    alignSelf: "stretch",
    borderWidth: 2,
    borderColor: "red"
  }}
  data={["a", "b", "c"]}
  renderItem={({ item }) => (
    <Text>
      {item}
    </Text>
  )}
/>;
```

### PR DESCRIPTION
**Pull request by Nizarius**
## Summary

Fixes #22752

On line 1021 you are passing base style to props: 
`style: [baseStyle, this.props.style],`

Explicitly passing base style to ScrollView just overrides this line and doesn't let developers to customise style of any inheritors of ScrollView (not only FlatList) with custom RefreshControl.

So this line (1113) seems to be removed. 

## Changelog

[GENERAL] [Fixed] - fix of Android's bug that doesn't let override ScrollView's Style with custom RefreshControl. 

## Test Plan
Use this code snippet to test that passing RefreshController doesn't break styling of ScrollView on Android.
```
type Props = {};
export default class App extends Component<Props> {
  state = { isLoading: false };

  reload = () => {
    this.setState({ isLoading: true });

    setTimeout(() => {
      this.setState({ isLoading: false });
    }, 2000);
  };
  render() {
    return (
      <ScrollView
        style={{
          flex: 1,
          alignSelf: "stretch",
          borderWidth: 10,
          borderColor: "red"
        }}
        refreshControl={
          <RefreshControl
            colors={["red", "yellow"]}
            refreshing={this.state.isLoading}
            onRefresh={() => this.reload()}
          />
        }
      >
        <View
          style={{
            width: "100%",
            height: 300
          }}
        >
          <Text>3335</Text>
        </View>
        <View
          style={{
            width: "100%",
            height: 300
          }}
        />
        <View
          style={{
            width: "100%",
            height: 300
          }}
        />
      </ScrollView>
    );
  }
}
```

The same for FlatList: 
```
type Props = {};
export default class App extends Component<Props> {
  state = { isLoading: false };

  reload = () => {
    this.setState({ isLoading: true });

    setTimeout(() => {
      this.setState({ isLoading: false });
    }, 2000);
  };
  render() {
    return (
       <FlatList
        style={{
          flex: 1,
          alignSelf: "stretch",
          borderWidth: 10,
          borderColor: "red"
        }}
        data={["a", "b", "c"]}
        renderItem={({ item }) => (
          <View style={{ height: 500 }}>
            <Text>{item}</Text>
          </View>
        )}
        refreshControl={
          <RefreshControl
            colors={["red", "yellow"]}
            refreshing={this.state.isLoading}
            onRefresh={() => this.reload()}
          />
        }
      />
    );
  }
}
```

### CODE REVIEW

**Comment by Nizarius** [comment]
@janicduplessis yeah, you're right. In fact, margin properties only work on AndroidSwipeRefreshLayout and padding properties - only on ScrollView. So padding or margin doesn't get applied twice. But there is such a problem with opacity. 
So the ideal solution seems something like that:
1) Extract all margin properties ('margin', 'marginRight' etc) and opacity from this.props.style and apply it to AndroidSwipeRefreshLayout (with baseStyle).
2) Pass other style properties (padding, borders etc) to ScrollView (with baseStyle).
This can prevent unexpected behaviour in the future as we won't duplicate any properties to both views.
I don't know if you have some utility functions for extracting properties' family ("extract all margin properties" or something similar) to make code cleaner and more declarative.

What do you think?

**Comment by janicduplessis** [comment]
I don't think we have anything currently to do this. I have something like this in an app though:

```js
const OUTER_PROPS = {
  margin: true,
  marginHorizontal: true,
  marginVertical: true,
  marginBottom: true,
  marginTop: true,
  marginLeft: true,
  marginRight: true,
  flex: true,
  flexGrow: true,
  flexShrink: true,
  flexBasis: true,
  alignSelf: true,
  height: true,
  minHeight: true,
  maxHeight: true,
  width: true,
  minWidth: true,
  maxWidth: true,
  position: true,
  left: true,
  right: true,
  bottom: true,
  top: true,
};

export function splitLayoutProps(props) {
  const inner = {};
  const outer = {};
  Object.keys(props).forEach(k => {
    if (OUTER_PROPS[k] === true) {
      outer[k] = props[k];
    } else {
      inner[k] = props[k];
    }
  });
  return { outer, inner };
}

```

 You could also use `StyleSheet.flatten` to make sure to have an object from the style prop.

@sahrens What do you think about this?

**Comment by Nizarius** [comment]
@janicduplessis seems nice. We need to define where to place this utility function.

**Comment by cpojer** [comment]
What's the status of this PR?

**Comment by Nizarius** [comment]
@cpojer I suggest, we are waiting comments for the best code styling. The implementation itself will be fast.

**Comment by sahrens** [comment]
Yeah let's add a `splitLayoutProps` export on `StyleSheet` and use that.

**Comment by Nizarius** [comment]
@sahrens I've added splitLayoutProps to export and use it.
I'm also explicitly passing baseStyle to both wrapper and container style to be sure that we don't break anything:
```
return React.cloneElement(
          refreshControl,
          {style: [baseStyle, outer]},
          <ScrollViewClass
            {...props}
            style={[baseStyle, inner]}
            // $FlowFixMe
            ref={this._setScrollViewRef}>
            {contentContainer}
          </ScrollViewClass>,
        );
```
But as I check it works without it. It's on your side. So it's up to you.

**Comment by Nizarius** [comment]
Any news, guys?

**Comment by Nizarius** [comment]
@cpojer yep, will do it soon

**Comment by Nizarius** [comment]
@cpojer done

**Pull request closed without merging**
