### PR TITLE
Fix skew transform on native side (iOS & Android)

### PR DESCRIPTION
**Pull request by MaxGraey**
According to #11992 fix skew transform in native code as well

@janicduplessis @vjeux

### CODE REVIEW

**Comment by janicduplessis** [comment]
Thanks for fixing this!

@facebook-github-bot shipit

**Comment by vjeux** [comment]
Thanks!

**Comment by lirui0407** [comment]
I tried, still not working on android platfom but ios, why?

<View style={{width:100,height:100,backgroundColor:'red',transform:[{skewX:'30deg'}]}} ></View>

**Comment by MaxGraey** [comment]
@lirui0407 See my last comment in [this topic](https://github.com/facebook/react-native/issues/12212)

**Comment by lirui0407** [comment]
Thank you!

**Pull request closed without merging**
