### PR TITLE
Readability fix for Android environment setup

### PR DESCRIPTION
**Pull request by skyebook**
Pretty straightforward

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @csholmq to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1151391681571672/int_phab) to review.

**Comment by janicduplessis** [comment]
@skyebook There is a conflict now, could you rebase on master then we can try merging again.

**Comment by skyebook** [comment]
@janicduplessis Easy one, that file has been deleted in the docs. Closing 👍

**Comment by janicduplessis** [comment]
@skyebook True, the setup docs were completely remade recently.

**Pull request closed without merging**
