### PR TITLE
Proper NativeAnimated node invalidation on Android

### PR DESCRIPTION
**Pull request by ryangomba**
This diff attempts to fix a number of Android native animation bugs related to incomplete node invalidation, e.g. https://github.com/facebook/react-native/pull/10657#issuecomment-258297467.

For full correctness, we should mark any node as needing update when it is:

- created
- updated (value nodes)
- attached to new parents
- detached from old parents
- attached to a view (prop nodes)

cc/ @janicduplessis

### CODE REVIEW

**Comment by janicduplessis** [comment]
Tested it and it works well, it fixed an issue on android where sometimes there was a white screen after poping a route on android with NavigationExperimental + native animations.

**Comment by asgvard** [comment]
@janicduplessis Not sure if it has something to do with this particular PR, but is there any chance that the #8968 have the same root cause? Like not proper node invalidation after the node is removed from the array of siblings with the different zIndexes?
I'm struggling with the same problem with white screen when transitioning between routes, but using react-router v4 and react-motion for animation. When the fading-out component should became null at the end of animation, I see the white screen instead. However during animation itself zIndexes behave as expected, I can see the "new" page floating above and the "old" fading-out page stays on background. So it happens exactly when the old one becomes null (probably not fully detached).

**Comment by janicduplessis** [comment]
This only affects native driven animations (when you start an animation with useNativeDriver=true) so unless you are using that it doesn't seems related.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
