### PR TITLE
fix(EventEmitter) only apply if listener #35577

### PR DESCRIPTION
**Pull request by DerBasler**
## Summary

During the rewrite of the event listeners in e5c5dcd a check was removed if the listener exists.
This change now checks that the listener is registred correctly.

## Changelog

[INTERNAL] [FIXED] - make sure the event listener is registred correctly

## Test Plan

Try to add an event listener without a proper func as parameter

### CODE REVIEW

**Comment by javache** [comment]
Listeners should always be non-null. Could we consider fixing the calling packages instead?

**Comment by yungsters** [comment]
I agree with @javache.

This can only happen if `addListener()` is invoked with a non-function argument as its second argument. This happening seems like a symptom of an issue further upstream in the calling code.

If the point at which this becomes an error is too confusing to debug dependent packages, I'd be amenable to introducing a type check in `addListener`, for example:

```
if (typeof listener !== 'function') {
  throw new TypeError('EventEmitter.addListener(…): 2nd argument must be a function.');
}
```

**Comment by DerBasler** [comment]
Yes you guys are right I can adjust it over the weekend. 
I guess I just wanted a quick fix for my problem 😅

**Comment by yungsters** [comment]
I think I already landed this change in main. This PR can be closed now, right?

**Comment by DerBasler** [comment]
@yungsters ah I didn't notice nice 👍 thx for the info

**Pull request closed without merging**
