### PR TITLE
Update node-haste and replace fast-path with node-haste's version to fix Windows compatibility

### PR DESCRIPTION
**Pull request by janicduplessis**
This is the last bits needed to fix Windows compatibility on master, most of the work was done in node-haste.

**Test plan**
Run npm test
Run the packager using Windows and Mac

cc @cpojer @davidaurelio

### CODE REVIEW

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by davidaurelio** [comment]
@janicduplessis will have to take care of the node_modules updates internally first. Will look into it in a few. Maybe we could even get Travis back to green this morning before merging this

**Comment by davidaurelio** [comment]
This has internal errors. no idea whether it’s flakiness or really broken :-(

**Comment by janicduplessis** [comment]
Hmm the test on circleci fails with this
```
Error: Cannot find module 'node-haste/lib/fastpath'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
```
Looks like the node-haste version doesn't get updated properly.

**Comment by janicduplessis** [comment]
Also the UIExplorer app is broken since a few commits, the tests on travis seems to fail because of that. If you have any internal tests that depend on that is may be why it fails.

**Comment by davidaurelio** [comment]
The UIExplorer have been reverted in the meantime afaik. @bestander is having a look at this now

**Comment by bestander** [comment]
@janicduplessis I would appreciate if you rebase.
CI should be stable-ish now

**Comment by bestander** [comment]
JS does not look good in tests

**Comment by janicduplessis** [comment]
I can confirm that it stills install node-haste@2.4 even if I changed the package.json. Is that caused by npm shrinkwrap? I'm not sure how that works as I've never used it before.

```
├─┬ node-haste@2.4.0 
│ ├── graceful-fs@4.1.3 
│ ├─┬ sane@1.3.3 
│ │ ├─┬ exec-sh@0.2.0 
│ │ │ └── merge@1.2.0 
```
From the npm install logs.

**Comment by ide** [comment]
@janicduplessis package.json is completely ignored when shrinkwrap is present.

**Comment by janicduplessis** [comment]
Aww, e2e test on iOS fails with
```
  [Info] Collecting info for testables... (4131 ms)
  run-test EndToEndTestTests.xctest (iphonesimulator9.2, iPhone 4s, application-test)
    [Info] Installed 'org.reactjs.native.example.EndToEndTest'. (18420 ms)
    [Info] Launching test host and running tests ... (0 ms)
      -[EndToEndTestTests testRendersWelcomeScreen][3:20:55 AM] <START> request:/index.ios.bundle?platform=ios&dev=true
[3:20:55 AM] <START> find dependencies
Error: Unable to find file with path: /private/tmp/react-native-uiz3Ujzd/EndToEndTest/ios/index.ios.js
    at Fastfs.readFile (/private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/lib/fastfs.js:141:15)
    at /private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/lib/Module.js:165:49
    at Cache.get (/private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/lib/Cache/index.js:64:103)
    at Module.read (/private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/lib/Module.js:164:26)
    at Module.getDependencies (/private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/lib/Module.js:120:19)
    at /private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/ResolutionRequest.js:29:17
    at /private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/node_modules/throat/index.js:11:22
    at new Promise (/private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/core-js/modules/es6.promise.js:197:7)
    at run (/private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/node_modules/throat/index.js:10:22)
    at /private/tmp/react-native-uiz3Ujzd/EndToEndTest/node_modules/react-native/node_modules/node-haste/node_modules/throat/index.js:39:16
```

**Comment by janicduplessis** [comment]
Ok the issue seems to happen because of a regression in node-haste 2.5.0 it tries to find the index of a new app in `/Users/janic/Developer/TestApp/node_modules/react-native/packager/index.ios.js` when it is in `/Users/janic/Developer/TestApp/index.ios.js`.

**Comment by janicduplessis** [comment]
Ok I was able to track down the bug to this change in node-haste, I'll check what is up with that.

https://github.com/facebook/node-haste/commit/9673f86c5f78fff56be2d38c5698af65ac816295#diff-1fdf421c05c1140f6d71444ea2b27638L198

**Comment by janicduplessis** [comment]
Also I'm not sure if I updated the npm-shrinkwrap.json file properly the diff seems a bit too huge :)

I did that using npm 2.14
```
rm -rf node_modules
npm install
npm install --save node-haste@2.5.0
npm uninstall --save fast-path
npm shrinkwrap
```

**Comment by mkonicek** [comment]
@janicduplessis I'm just merging https://github.com/facebook/react-native/pull/6346 which updates to a newer version. Should this PR be rebased or closed (not sure about the change in `packager/react-packager/index.js`)?

**Comment by janicduplessis** [comment]
I'm pretty sure the change in packager/react-packager/index.js is still needed. I'll rebase and test once #6346 is merged.

**Comment by skevy** [comment]
I think you're right @janicduplessis. Thanks for looking into this :)

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by davidaurelio** [comment]
@bestander @mkonicek you might want to cherry pick this for the release. It makes windows compat better

**Pull request closed without merging**
