### PR TITLE
Add SoundCloud Pulse to the app showcase

### PR DESCRIPTION
**Pull request by janmonschke**
Simple PR that adds SoundCloud Pulse to the app showcase

### CODE REVIEW

**Comment by chirag04** [comment]
@facebook-github-bot shipit

**Comment by chirag04** [comment]
@mkonicek seems like the import failed here.

**Comment by brentvatne** [comment]
Running the tests again @chirag04, if they fail @anmonschke can you rebase this?

**Comment by janmonschke** [comment]
@brentvatne I rebased the PR

**Comment by chirag04** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
