### PR TITLE
Feature/add decimal pad to android

### PR DESCRIPTION
**Pull request by JPanneel**
For a current use-case we need the a keyboard with characters 0-9 and a decimal point (or comma depending on language settings)

This exists on iOS as UIKeyboardType "decimalPad" and this is what react-native maps to for both "numeric" and "decimal-pad". This also exists on Android as inputType "numberDecimal", but is currently not accessible through react-native.

This PR maps the value "decimal-pad" of the keyboardType property of TextInput to the Android inputType "numberDecimal", effectively making "decimal-pad" cross platform without breaking anything.

## Relevant links to documentation
* https://facebook.github.io/react-native/docs/textinput.html#keyboardtype
* https://developer.apple.com/documentation/uikit/uikeyboardtype
* https://developer.android.com/reference/android/widget/TextView#attr_android:inputType

## Additional benefit 
There is this bug in some Samsung keyboards where both the - sign and decimal sign disappear when the keyboardType is set to "number" and both the "signed" and "decimal" flags are set. (Like is the case when using the react-native keyboardType prop "numeric".) https://androidforums.com/threads/numeric-soft-keyboard-missing-minus-sign-in-android-8-0-samsung-a5.1272628/ 

For developers that need decimal numbers but not negative ones, using "decimal-pad" will provide a workaround. I reproduced this on a Samsung A5 only, but maybe other phones have this exact issue. https://github.com/facebook/react-native/issues/12988 https://github.com/facebook/react-native/issues/12977 https://github.com/facebook/react-native/issues/17473 https://github.com/facebook/react-native/issues/17474

## Test Plan

* Added testcase consistent with existing keyboardType tests
* Also added testcase for the related, but missing number-pad

## Related PRs

This PR follows the same approach as the recently merged PR introducing "number-pad" https://github.com/facebook/react-native/pull/18350/commits/b638847a46491bd75e7ce7928c73f7cb78399195

Documentation PR: https://github.com/facebook/react-native-website/pull/405

## Release Notes

 [ANDROID] [ENHANCEMENT] [TextInput] - Added "decimal-pad" keyboard type

### CODE REVIEW

**Comment by mdvacca** [comment]
Thanks for working on this @JPanneel.
Can you also update the documentation here: https://facebook.github.io/react-native/docs/textinput.html#keyboardtype

**Comment by JPanneel** [comment]
@mdvacca Is that something other than what is included in https://github.com/facebook/react-native-website/pull/405 ? If so, I am not sure where to update the documentation you mention. 
https://deploy-preview-405--react-native.netlify.com/docs/next/textinput.html#keyboardtype

**Comment by JPanneel** [comment]
No problem. Thanks for the fast feedback!

**Comment by DickLemm** [comment]
See my comment https://github.com/facebook/react-native/issues/22005?_pjax=%23js-repo-pjax-container.

**Pull request closed without merging**
