### PR TITLE
[TextInput] Added support for textAlignment property

### PR DESCRIPTION
**Pull request by darylrowland**
Added textAlignment property to the TextInput component so that text can be aligned center, left, right or justified.

### CODE REVIEW

**Comment by vjeux** [comment]
textAlign should be in the style attribute, not as a prop of the component. Also, it doesn't merge anymore :(

**Comment by phamhieu** [comment]
Right now, does TextInput support center align with style attribute? 

I tried ```text-align: center;``` but nothing happen.

**Comment by ee0pdt** [comment]
@phamhieu I think you need to use camel case here, i.e. textAlign: center;

**Comment by phamhieu** [comment]
Just test. Still not work. My code for references.
```
return (<TextInput 
                style={styles.inputText}
                value = {content}
                autoFocus = {true}
                onChangeText = {(text) => this.setState({'inputText': text}) }
                onEndEditing = {() => this.setState({'showTextInput': false}) } >
              </TextInput>);
```
```
inputText: {
    height: 28,
    width: SCREEN_WIDTH,
    backgroundColor: TEXT_BG,
    fontSize: 20,
    textAlign: 'center',
    color: 'white',
  },
```

result:
screen shot 2015-04-06 at 1 49 51 pm

**Comment by darylrowland** [comment]
I've just fixed this in a much better way in a new pull request - https://github.com/facebook/react-native/pull/772

Turns out all that was wrong is that the textAlign css property needed remapping to textAlignment. So a one line change that fixes it... nice :)

**Comment by marcshilling** [comment]
This is fixed in 0.7.0rc

Just wanted to bring this up since I see some people doing it wrong here, `textAlign` is a prop directly on `<TextInput>`. Setting it as a style will not work.

**Pull request closed without merging**
