### PR TITLE
[WebView] Add props for overriding native component

### PR DESCRIPTION
**Pull request by cbrevik**
**Motivation**
Just like with #10105, the motivation is to make `WebView` more extensible. 

In order to extend `ReactWebViewManager` (Android) with your own custom logic in a new class, you will have to override [`getName`](https://github.com/facebook/react-native/blob/da4df3f12f930022910d3e37e3c724201dcb2d77/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java#L320), and refer to this name in the JavaScript-code. And that's fine.

But, the problem is that you will have to duplicate the entire file for `WebView.android.js` in order to refer to the new custom native component by name with [`requireNativeComponent`](https://github.com/facebook/react-native/blob/47d9cb4dacca6d11c7de74ef4f053427f29dc3c7/Libraries/Components/WebView/WebView.android.js#L338) (since it is hard-coded to `'RCTWebView'`). It's also necessary to do so in order to pass through any custom events or props you may want to set on the custom native WebView.

All of the above is also true for iOS.

What I'm trying to solve with this PR is give the ability to extend native `WebView` logic, while being able to re-use and extend existing `WebView` JavaScript-logic. This is done by adding a new `nativeComponent` prop on `WebView`. I've also added `nativeComponentProps` so custom props / events can be set on the custom native WebView.

**Test plan**

Let's say I've extended `ReactWebViewManager` with my own `CustomWebViewManager` in my Android-project (overriding `getName` so it returns `"RCTCustomWebView"`), and this new class may emit a `onSomethingHappened` event. 
Then I can implement my custom WebView as follows in JavaScript:
```javascript
import React, { Component, PropTypes } from 'react';
import {
    WebView
} from 'react-native';

import requireNativeComponent from 'requireNativeComponent';

class CustomWebView extends Component {
    constructor(props) {
        super(props);
    }

    static propTypes = {
        ...WebView.propTypes,
        onSomethingHappened: PropTypes.func,
    };

    onSomethingHappenedEvent = (event) => {
        var { onSomethingHappened } = this.props;
        onSomethingHappened && onSomethingHappened(event);
    }

    render() {
        return (
            <WebView 
              {...this.props} 
              nativeComponent={RCTCustomWebView} 
              nativeComponentProps={{ onSomethingHappened: this.onSomethingHappenedEvent }} 
            />
        );
    }
}

var RCTCustomWebView = requireNativeComponent('RCTCustomWebView', CustomWebView);

module.exports = CustomWebView;
```

### CODE REVIEW

**Comment by cbrevik** [comment]
This could in principle be done with more React Native components, to make it easier for the community to re-use and extend native components.

**Comment by mkonicek** [comment]
Interesting approach to reusing the `WebView.*.js`. Have you tried it out on iOS by extending the WebView in Obj-C?

Why do you need to extend the Android WebView, however? If there are bugs or missing features would you be up for contributing them upstream?

I'm curious why we haven't had a use case like this with any of the components (`Text`, `TextInput` etc.) so far. If there are very few people who need to extend the native code a reasonable tradeoff might be for you to fork the `WebView.*.js` so we don't add two extra props to the public API very few people would use.

**Comment by cbrevik** [comment]
@mkonicek 

I've tested on iOS as well, and this approach works there as well. 

You'll have to duplicate `RCTWebViewManager.m`, since the exported macro-defined methods/properties (with `RCT_REMAP_VIEW_PROPERTY`, `RCT_EXPORT_METHOD`, etc) are only picked up from the subclass, and not from the parent. So you cannot inherit the props from `RCTWebViewManager`, which is a shame. 
But, you will not have to duplicate `RCTWebView.m`, and can easily enough inherit and extend that class. 

One issue I've found in `WebView.ios.js` is that the `RCTWebViewManager` is [also referenced by name](https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L32), and is used when [deciding to `startLoadWithResult` or not](https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L383). This could be remedied though if we did like with the rest of the exported methods from the RCTWebViewManager and call `startLoadWithResult` [with `dispatchViewManagerCommand`](https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L444). 

I don't really see the need to reference the ViewManager directly, or maybe I am missing something?

----

Why not just contribute upstream? 

There might be features which is a bit too specific to a single use-case, like with for example #9949. 
In my specific case I have some sensitive logic for handling inactivity in the WebView, which doesn't seem to fit upstream either.

I don't think this is satisfactory resolved by just forking the logic. It is difficult to maintain in that case, and hard to keep up-to-date with each new RN version. Also the complexity of it is a bit too high for junior RN developers on my team, and I'd dread to hand off the project to someone else in that case. 

See for example [this discussion](https://github.com/facebook/react-native/issues/1908) on extending core components. Or [this issue](https://github.com/alinz/react-native-webview-bridge/issues/109) with regards to duplication of code. Coincidentally both by @alinz so maybe he has some input here?

This might not be necessary for simple components (`Text`, `TextInput`, etc). But for more complex components, or those that need a lot of customization, this would help a lot I think.

**Comment by jacobp100** [comment]
@cbrevik Would you be able to look into what would need to happen to get extending the iOS webview to be as easy as Android’s (without manually copying over the props)? I ask so we don’t implement this solution, and then have to introduce breaking changes later to accommodate iOS.

**Comment by cbrevik** [comment]
Well I suspect the issue is with [this line in RCTComponentData](https://github.com/facebook/react-native/blob/master/React/Views/RCTComponentData.m#L413), where the `class_copyMethodList` method only retrieves the child methods. 

We could potentially reflect (and maybe loop through) the inheritance tree with `superclass`, and retrieve the parents methods as well. 

I'll test it later this evening.

**Comment by cbrevik** [comment]
@jacobp100 

Just a preliminary test, but it seems like if we change that line to something like:

```objective-c
  Class managerClass = [_managerClass class];
  while ([managerClass class] != [RCTViewManager class]) {
    Method *methods = class_copyMethodList(object_getClass(managerClass), &count);
    // snipped away logic
    managerClass = [managerClass superclass];
  }
```

Then it will loop through and add the parents' props as well, and the extending the ViewManager becomes very easy:

```objective-c
#import "RCTCustomWebViewManager.h"
#import "RCTCustomWebView.h"
#import "UIView+React.h"

@interface RCTCustomWebViewManager () <RCTWebViewDelegate>
@end

@implementation RCTCustomWebViewManager
{
}

RCT_EXPORT_MODULE()

- (UIView *)view
{
  RCTCustomWebView *webView = [RCTCustomWebView new];
  webView.delegate = self;
  return webView;
}

RCT_EXPORT_VIEW_PROPERTY(onSomethingHappened, RCTDirectEventBlock)

@end
```

**Comment by jacobp100** [comment]
Neat! Really excited about this.

I think we need some examples in UIExplorer and documentation—but I'm happy to help with that if you need!

**Comment by cbrevik** [comment]
Absolutely, help would be appreciated! Not sure if the `RCTComponentData` change belongs in its own PR though? 

I suppose both changes would be connected, we wouldn't be able to provide a good example in UIExplorer without landing this PR first.

**Comment by lacker** [comment]
Hey @jacobp100 are you still down to follow through on that generous offer to help out with the docs on this PR? ;-)

**Comment by jacobp100** [comment]
I could certainly do that! @cbrevik, the snippet where you copy over the superclass methods, where does that go?

**Comment by cbrevik** [comment]
@jacobp100 I can create a new PR for that snippet, it probably needs re-testing first since `RCTComponentData` has changed.

**Comment by jacobp100** [comment]
I know it's been some time—just wondering if you wanted to continue with this? I can do docs if you give me code examples! @cbrevik

**Comment by cbrevik** [comment]
@jacobp100 I've had this PR in the back of my mind. Code examples shouldn't venture too far from the original issue [comment](https://github.com/facebook/react-native/pull/10946#issue-189366011) and the example there. I can take a look this week, and resolve conflicts etc.

**Comment by jacobp100** [comment]
@cbrevik I understood how to do it on the JS side, I wasn't able to get anything working on ObjC (and I didn't even try Java)

**Comment by cbrevik** [comment]
@jacobp100 Aha my bad, I'll try to put together an example repository for you. The Java-side is pretty trivial, Objective-C demands cloning the `RCTWebViewManager` as previously stated (until we have the ability to traverse the `superclass` inheritance tree).

**Comment by cbrevik** [comment]
@jacobp100 
Been busy with other stuff, so I've been slow as usual. But added an example project here: https://github.com/cbrevik/overrideWebview (see README for details)

**Comment by jacobp100** [comment]
@cbrevik I've looked at the iOS side, and think I can simplify the process for `RCTCustomWebViewManager`. Could you [look at my changes](https://github.com/jacobp100/react-native/pull/2/files).

With this, you can just make the custom view manager inherit directly from `RCTWebViewManager`, and remove everything except `(UIView *) view` and any properties you want to export. See [here](https://pastebin.com/9gWjRTRL).

Let me know what you think!

**Comment by cbrevik** [comment]
@jacobp100 Ah that's the same logic as from my comment (https://github.com/facebook/react-native/pull/10946#issuecomment-262708963) a few months ago right? 

Looks good to me at first glance, give me some time to test it out.

**Comment by jacobp100** [comment]
Completely missed that! 😂 Reassuring at least that we ended up with the same implementation.

**Comment by cbrevik** [comment]
Yeah, not too bad 😹 . Tested it out now, and it seems to work fine to me.

From earlier I can see we were discussing if making it part of this PR, or not. 
If it is compelling I suppose I could commit it to this PR. What do you think?

It would definitely make it easier to use the rest of the logic in this PR.

**Comment by jacobp100** [comment]
I think it should be. It won't affect any existing RN components. It'll mean less burden for maintaining modifications for web view, and opens the door to extending this to more components.

**Comment by cbrevik** [comment]
@jacobp100 Alright, cool. Updated this PR as well as the example project with the new logic :)

I also have an idea with the Android-side `WebView` which would possibly make that one a bit easier to extend as well.

**Comment by jacobp100** [comment]
@cbrevik Should we export [these properties](https://github.com/facebook/react-native/blob/da9a712a9e17942dcd05b8d955f0764c2026a4ad/Libraries/Components/WebView/WebView.ios.js#L559-L565) to help with subclassing?

**Comment by cbrevik** [comment]
Probably not a bad idea @jacobp100 

Maybe put it as a static on the exported class?
```javascript
class WebView extends React.Component {
  static extraNativeComponentConfig = {
    nativeOnly: {
      onLoadingStart: true,
      onLoadingError: true,
      onLoadingFinish: true,
      onMessage: true,
      messagingEnabled: PropTypes.bool,
    },
  };
  ...
}
```

Can require the custom component with:
```javascript
var RCTCustomWebView = requireNativeComponent('RCTCustomWebView', CustomWebView, WebView.extraNativeComponentConfig);
```

**Comment by jacobp100** [comment]
LGTM. Would we want to `Object.freeze` it in dev?

**Comment by cbrevik** [comment]
Maybe I'm being dense now, but why would that be necessary?

**Comment by jacobp100** [comment]
In case a user imports it, then writes `extraNativeProps.nativeOnly.myEvent = true`. Could cause issues!

**Comment by cbrevik** [comment]
Hmm, instead, maybe change it to:
```javascript
  static get extraNativeComponentConfig() {
    return {
      nativeOnly: {
        onLoadingStart: true,
        onLoadingError: true,
        onLoadingFinish: true,
        onMessage: true,
        messagingEnabled: PropTypes.bool,
      },
    };
  }
```

**Comment by jacobp100** [comment]
That could work too, but I think you'd end up using it like,

```js
{
  ...extraNativeComponentConfig(),
  nativeProps: {
    ...extraNativeComponentConfig().nativeProps,
    onMyEvent: true,
  },
}
```

But this isn't too important! Let me know what you pick and I'll add it to the docs!

**Comment by cbrevik** [comment]
Alright, updated with exported config and updated the example project usage.

I don't think a most developers will need to supply their own config for this though. As far as I've seen it's only use is for ignoring prop validation of native props which are either not exposed on the JS component, or differently named from the native prop.

In the case of the `CustomWebView` I've set up, we don't need to ignore validation of the `onSomethingHappened` event, since it has the same native/JS prop name.

**Comment by jacobp100** [comment]
Ah, I missed the `get`!

I've got a first cut of the iOS docs over [here](https://github.com/jacobp100/react-native/pull/3/files)—let me know if you think anything is missing or could be improved!

Did you want to make changes to the Android implementation? Let me know, and then I can get started on those docs too!

**Comment by cbrevik** [comment]
Nice @jacobp100! Read through it now, and it looks great. Very straight-forward and informative.

Regarding Android, what I've done now is set methods and fields as `protected` instead of `private` so subclasses can easier override/extend behavior. When doing it before I've had to duplicate a bit of code to for example override the `ReactWebView`.

I've also added "creation" methods for both `ReactWebView` & `ReactWebViewBridge` so they can more easily be overridden with custom subclasses.

I'll update the example project with some relevant code.

**Comment by cbrevik** [comment]
Updated example as well. Added a `CustomWebView` in the Android-implementation to pipe through the React-prop to the `CustomWebViewClient`. Similar change on the iOS & JS side.

**Comment by jacobp100** [comment]
Alright, Android docs done too! Again, feel free to say whether something is missing, needs more detail, or anything else.

But other than that, it looks like we should be about ready!

**Comment by cbrevik** [comment]
@jacobp100 has written docs (https://github.com/facebook/react-native/pull/10946/commits/ad98f8556d1d3685a613fc4ff2806e665936fe0c) for this new feature. So I think this PR is good to go for another review @lacker

**Comment by ptilli** [comment]
Great job guys!

I hope this feature would be extended to other components (especially Text ;;)) as well!!

**Comment by shergin** [comment]
@jacobp100 @cbrevik 👍 If you could present the changes in `RCTComponentData.m` (iOS) as separate PR, I will definitely review it and most likely merge. (Same probably true for Android.)
I would love to have this functionality at least in iOS but I have no time to tackle it myself.

**Comment by cbrevik** [comment]
@shergin Great! I'll open the two other PRs today 👍 This PR (and especially the docs) will be dependent on the other two PRs landing then.

**Comment by niztal** [comment]
Can someone merge it? I see all checks, tests and reviewes passed, all left is push the merge button.

It's blocking for other PRs to be merged.
#12807

**Comment by shergin** [comment]
Nope, it cannot be merged until we figure out (and implement) the right design of module inheritance. See discussion in #14260.
I plan to tackle this problem relatively soon (~this summer) anyway.
Or, @cbrevik, do you interested in implementing the approach roughtly descibed in https://github.com/facebook/react-native/pull/14260#issuecomment-305350775 ? 😄

**Comment by cbrevik** [comment]
Sure @shergin, something like this https://github.com/cbrevik/react-native/commit/e71c4ed8d8a04a5bd70d6dc41157b90e33e4491e?

Bit unsure on how to re-establish inheritance with the base "ViewManager" name since `NativeProps` seems to be exported with the "View" name instead. (E.g. `UIManager.RCTView.NativeProps`.)

Maybe you know of a better way?

**Comment by shergin** [comment]
@cbrevik We definitely want to support long inheritance chain.
I also think we have to avoid looping through `UIManager`; can we infer `key` from `viewConfig.BaseManager`?

**Comment by cbrevik** [comment]
@shergin Not sure, it's [this bit of hacky code](https://github.com/facebook/react-native/blob/bdd27f46964317e10467034892292706fd06680a/React/Views/RCTComponentData.m#L44-L60) which determines the exported module name. Don't think we want to replicate that on the JS side.

I could extract that bit of code into its own method in `RCTComponentData` though, to also export the parent module name in the `viewConfig`. Then we could do something like `UIManager[viewConfig.baseModuleName]`.

**Comment by shergin** [comment]
@cbrevik `viewConfig.baseModuleName` 👍

**Comment by cbrevik** [comment]
@shergin I've landed on [an implementation](https://github.com/cbrevik/react-native/compare/master...cbrevik:viewmanager-base-props) which supports longer inheritance chains. I'll test more, then open a PR.

**Comment by shergin** [comment]
@cbrevik Omg, omg! That's awesome!!1 Please, go ahead and open PR (even if it is not finished, we will discuss approach there)!

Current implementation will break Android (and all other platforms), right? Can we easily implement `baseModuleName` for Android or we should temporary workaround it on JS side?

**Comment by cbrevik** [comment]
@shergin I can open a PR a bit later then. 

I don't think it will break Android since that platform already supports inheritance (so you don't have to merge in anything). That might need a it of testing though to verify. 

As far as other platforms, UWP etc. we will have to find out.

**Comment by cbrevik** [comment]
Now that #14775 is landed, we're getting closer to landing this one as well. 

To make the API for this functionality a bit more general, I'm thinking of changing the signature from:
```jsx
<WebView 
  nativeComponent={RCTCustomWebView} 
  nativeComponentProps={{ onSomethingHappened: this.onSomethingHappenedEvent }} 
/>
```

To:
```jsx
<WebView 
  nativeConfig={{
    component: RCTCustomWebView,
    props: { onSomethingHappened: this.onSomethingHappenedEvent }
  }} 
/>
```

Makes the API a bit cleaner, and also easier to extend with more options. For example if you want to send in a custom ViewManager as well (which it seems like `WebView` might require):
```jsx
<WebView 
  nativeConfig={{
    component: RCTCustomWebView,
    props: { onSomethingHappened: this.onSomethingHappenedEvent },
    viewManager: CustomWebViewManager
  }} 
/>
```

Shouldn't be much work to make this change. Thoughts?

**Comment by jacobp100** [comment]
The extensibility of the new way definitely looks like an improvement!

**Comment by cbrevik** [comment]
Opened a new PR #15016 for this feature, since the implementation has changed over time. Closing this one in favor of that.

**Pull request closed without merging**
