### PR TITLE
Fixes #9168

### LINKED ISSUE #9168: Add support for RNPM plugins from packages matching "react-native-*"
RNPM has a recent commit that supports finding plugins from packages named with "react-native-*" (https://github.com/rnpm/rnpm/commit/769b69264f035fe366132df777fab7f6fd3bf03f). We use this feature to ship the `run-windows` command plugin inside the react-native-windows package (https://github.com/ReactWindows/react-native-windows/blob/master/package.json#L41).  Can we apply this commit here as well?

cc @Kureev @grabbou

### PR DESCRIPTION
**Pull request by grabbou**
Imports missing commit from the rnpm master.

### CODE REVIEW

**Comment by grabbou** [comment]
cc: @rozele

**Comment by Kureev** [comment]
Ping me when tests will be green

**Comment by grabbou** [comment]
Cool. BTW that is the only commit AFAIK we had to import :)

**Comment by Kureev** [comment]
Yeah, I think so as well. LGTM, let's ship it!

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
