### PR TITLE
Fix ScrollView getInnerViewNode and getInnerViewRef ref methods

### PR DESCRIPTION
**Pull request by vshab**
## Summary

Currently ScrollView ref's `getInnerViewNode` and `getInnerViewRef` are unbound and don't work as expected returning empty values. The origin of this problem probably is issued by https://github.com/facebook/react-native/commit/d2f314af75b63443db23e131aaf93c2d064e4f44

Working example of the problem is available here: https://github.com/vshab/RNGetInnerViewBug

This PR binds getInnerViewNode and getInnerViewRef to ScrollView and adds test checking the value of getInnerViewRef.

Before:
Simulator Screen Shot - iPhone 11 - 2020-12-15 at 02 07 03
After:
Simulator Screen Shot - iPhone 11 - 2020-12-15 at 01 49 31

## Changelog

[JavaScript] [Fixed] - ScrollView: Fix `getInnerViewNode` and `getInnerViewRef` ref methods

## Test Plan

1. The test checking the value of getInnerViewRef is added.
2. Example app demonstrating the problem is provided with before/after screenshots.

### CODE REVIEW

**Comment by TheSavior** [comment]
The other methods aren't bound either are they? Is the behavior of this method inconsistent with the behavior of the other methods? The functions on refs in React Native are pretty much all not bound to avoid creating new functions or breaking referential equality on every render

**Comment by vshab** [comment]
@TheSavior 
Hello!

>The other methods aren't bound either are they? 

Other methods are bound because they are defined as arrow function class properties. See https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L802 for example

>Is the behavior of this method inconsistent with the behavior of the other methods? 

Yes. Currently `getInnerViewNode` and `getInnerViewRef` just unusable. Check the example: https://github.com/vshab/RNGetInnerViewBug
I think it's a regression introduced by https://github.com/facebook/react-native/commit/d2f314af75b63443db23e131aaf93c2d064e4f44 It used to work before

>The functions on refs in React Native are pretty much all not bound to avoid creating new functions or breaking referential equality on every render

As I said before all other methods are arrow function preserving `this` and only `getInnerViewNode` and `getInnerViewRef` are regular class methods so they have different call behaviour I think.

**Comment by TheSavior** [comment]
Should the fix be to make these functions arrow functions as well instead of `.bind()`?

**Comment by vshab** [comment]
If you say so :) 
I just wanted to make a change that affects as little parts as possible.

**Comment by vshab** [comment]
@TheSavior I replaced `bind` with arrow functions.

**Comment by vshab** [comment]
@TheSavior Hello!

Anything else should be done to merge it?

**Pull request closed without merging**
