### PR TITLE
Upgrade gradle to 2.9

### PR DESCRIPTION
**Pull request by kmagiera**
New version of gradle released couple of days ago has a better support for zipTree copy task. Since we have a few of those including one for boost library which used to take very long, after upgrading we no longer need 6a656a1.

Also seems like many improvements made to gradle since 2.2 made it perform better on incremental builds (around 10% improvement on my laptop).

Command used to upgrade gradle version:

    gradle wrapper --gradle-version 2.9

Some of the plugins require updating as well since the previous versions were incompatible with gradle 2.9.

### CODE REVIEW

**Comment by baoti** [comment]
:+1:

**Comment by kmagiera** [comment]
Also added aad40b8b1d3c53145272fd958a0e9f1cdc4531a0 that shaves build time by 50% on gradle 2.9

**Comment by mkonicek** [comment]
:+1: Awesome!

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Should we also use it in apps? Maybe it will help with the common issue where the upload to device fails.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Something's up with the bot, created a task so I don't forget to merge this.

**Comment by kmagiera** [comment]
Looks like we don't use gradlew in template so there is no way to control gradle version there. One'd just use installed version

**Comment by mkonicek** [comment]
We provide gradlew in the templates: https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/bin/gradlew

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Looks like we can't import PRs that change binary files yet :(

    OpensourceGithubIssueWorkflow Import to Phabricator failed: Diff Parse Exception: Expected 'literal NNNN' to start git binary patch.

              307        }
              308    }
              309   diff --git aLibraries/FBReactKit/js/react-native-github/gradle/wrapper/gradle-wrapper.jar bLibraries/FBReactKit/js/react-native-github/gradle/wrapper/gradle-wrapper.jar
              310   index 8c0fb64a8698b08ecc4158d828ca593c4928e9dd..941144813d241db74e1bf25b6804c679fbe7f0a3 100644
              311   GIT binary patch
              ...

**Comment by mkonicek** [comment]
I'll merge your PR manually. Doing the 0.16 release and migrating the shipit bot to fbsource now. Will likely get back to this next week, have a task for it.

**Comment by mkonicek** [comment]
Thanks for the patience! :)

**Comment by kmagiera** [comment]
ok, will wait :)

**Comment by peduxe** [comment]
@mkonicek updating to gradle 2.9 didn't solve it: https://github.com/facebook/react-native/issues/2720

**Comment by mkonicek** [comment]
:tada:

Sorry for the delay! Too many thing in the queue :(

**Pull request closed without merging**
