### PR TITLE
[Don't merge] Test ESLint and Flow errors

### PR DESCRIPTION
**Pull request by satya164**
cc @bestander

### CODE REVIEW

**Comment by satya164** [comment]
So seems the bots work @bestander !

**Comment by bestander** [comment]
@satya164, indeed, it took a couple of hours after the commit.
Could be because of the queue in Travis builds.
I'll close the PR unless you have any more concerns

**Comment by martinbigio** [comment]
@bestander would be awesome for this to take a couple of minutes instead of hours. What could we do to achieve that? I'm curious about how much resources Travis provides for OSS projects. Looks like it's free, but does the number of workers scale as the project becomes more popular?

**Comment by bestander** [comment]
@martinbigio this is being discussed internally https://www.facebook.com/groups/osssupport/permalink/1013475482034400/

A few notes that are not a secret afaik.

- FB uses Travis at capacity, and FB pays for them. There will be some more negotiation about that.

- Travis limits their capacity per company travis-ci.org/facebook, the more projects we have on https://github.com/facebook using travis the more they will interfere with each other

- Some projects abuse the number of concurrent builds. Flow uses 6 VMs for every PR and branch build, React - 4, RN used 5 and I reduced it to 3. We could reduce the number of VMs on all projects (considering that build/test time takes less than VM startup and environment setup) and could reduce the queue size for some time but not in a long term perspective

- CircleCI is a good alternative, we could convince more projects to switch from Travis. I suppose the longer Travis queues are the more will switch. Though switching all projects to Circle will probably make Circle slow :) And also Circle does not provide IOS environment openly.

- Considering that Circle is faster starting up we could move the eslint-bot command to Circle and execute it first. I'll keep an eye on that option in the next few weeks depending how the Travis thing gets resolved

**Pull request closed without merging**
