### PR TITLE
Update setup.js

### PR DESCRIPTION
**Pull request by zeljkoX**
Jest test are failing if component is using Platform module. 
react-native 0.39.2
react: 15.4.1
Error: 
 TypeError: Cannot read property 'osVersion' of undefined
 at Object.get Version [as Version] (node_modules/react-native/Libraries/Utilities/Platform.ios.js:18:45)

With this pull request default platform is IOS. Should be dynamic based on package.json jest configuration if is defined.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by hramos** [comment]
Have you signed the CLA yet?

**Comment by ericvicenti** [comment]
I think this is incorrect because unlike the other things in this list, `Platform` is not a native module

**Comment by RealOrangeOne** [comment]
@ericvicenti i disagree, Looking at the source, `NativeModules` is used to detect things like OS version. So whilst the naming of this native module is incorrect, there definately needs to be one! 

https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.ios.js

**Comment by ericvicenti** [comment]
I'm surprised it hasn't been mocked out already. I agree, but it does seem strange that the rest of the things in this array are definitely mocked out.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/update-setupjs

**Pull request closed without merging**
