### PR TITLE
[SliderIOS] Add minimumTrackTintColor and maximumTrackTintColor to SliderIOS

### PR DESCRIPTION
**Pull request by brentvatne**
There are still many other props that can be added to further customize the SliderIOS component, but I had a specific need for these two so I just went ahead and added them.

### CODE REVIEW

**Comment by vitch** [comment]
Thanks for this - I need this functionality as well. In my app I additionally need `thumbTintColor` and am happy to add it in the same way (is it useful to somehow add it to this pull request?)...

The only question I would have is whether these values should be exposed via CSS (as they seem more style related)...

Also, is this likely to be merged into React Native? I can patch my local version but am just wondering what will happen in future updates...

**Comment by nicklockwood** [comment]
@vitch please make a separate pull request, as this one has already been merged. Once accepted, it will become part of RN.

I'll let @vjeux field the question about whether it should be a style vs a prop, but my undertanding is that it should be a prop.

**Comment by sahrens** [comment]
Style should only be used for base-level style that applies to View, Image, and Text.  We are actually going to take resizeMode out of style and make it a plain prop on image. 

So no, these new attributes should not go in style and should just be normal props.

But yes, we'll probably merge stuff like this in soon :)

**Comment by vitch** [comment]
Thanks for the quick responses :smile: 

I'm just looking into setting the `thumbTintColor` but it seems there is a bit of [a weird bug in iOS](http://stackoverflow.com/questions/19061157/ios-7-uislider-thumbtintcolor-does-not-change) regarding this property. If I can get the workaround to work then I'll submit a PR...

**Comment by vjeux** [comment]
The rule is that if there's an equivalent on the web in style, it should be a style with the same name and same behavior. Otherwise it should be a prop.

**Comment by brentvatne** [comment]
@vjeux - sounds very reasonable to me, I gathered that was what we were going for and said the same thing in another issue which I can't find at the moment :smile:

**Pull request closed without merging**
