### PR TITLE
[TextInput] Add __DEV__ around textInput prop check

### PR DESCRIPTION
**Pull request by dozoisch**
**Motivation** 

The prop validation was run on every render, even in prod which seems odd to me. This adds a dev check to make sure prod build skips the validation.

**Test plan (required)**

There are no changes to the ui.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @Bhullnatik to be potential reviewers.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/264012640629997/int_phab) to review.

**Comment by ide** [comment]
Can you change this from a warning to an error? Really don't want different failure modes between dev and prod.

**Comment by dozoisch** [comment]
@ide if there's a consensus, I don't mind making another PR!

**Comment by javache** [comment]
@ide this seems similar to how we do other propType validation, so I think it's fine. https://github.com/facebook/react/blob/master/src/isomorphic/classic/types/ReactPropTypes.js#L149

**Comment by ide** [comment]
@javache React creates Errors in order to capture the stack trace but it doesn't throw them. It prints a warning during propType validation: https://github.com/facebook/react/blob/95ac239cf3c527b70daeb433b7aeeaf9e41be9e5/src/isomorphic/classic/types/checkReactTypeSpec.js#L84

**Comment by dozoisch** [comment]
@ide so should we change it so that it only prints it instead of throwing?

**Comment by ide** [comment]
Yea I think we want to follow what React does with `warning`.

**Comment by dozoisch** [comment]
@ide https://github.com/dozoisch/react-native/commit/534d6ce0619c658bd254bc2144c53523ff5bfd74 would that be ok with you? If yes, I'll create a pr. Sorry for not responding, never saw you response 3 days ago!

**Pull request closed without merging**
