### PR TITLE
add asdf-vm support in react-native-xcode.sh

### PR DESCRIPTION
**Pull request by pastleo**
About asdf-vm: https://asdf-vm.com/

## Summary

This PR add [asdf-vm](https://asdf-vm.com/) support to `find-node.sh` for `scripts/react-native-xcode.sh` in `Bundle React Native code and images` build phrase and potentially other scripts using `find-node.sh` to get executable nodejs

## Changelog

[iOS] [Added] - add asdf-vm support in find-node.sh

## Test Plan

Xcode is able to complete `Bundle React Native code and images` build phrase without errors when node is installed by asdf-vm

### CODE REVIEW

**Comment by pvinis** [comment]
I guess this and https://github.com/facebook/react-native/pull/31317 can go together. I see some tiny differences, `-x`, `-s`, `-f` not used the same way.

**Comment by pvinis** [comment]
also, why is this script for xcode not using the `find-node` script??!

**Comment by charlesbdudley** [comment]
HI @pastleo, can we move this change to `find-node.sh` alongside the other environment manager code?

**Comment by pastleo** [comment]
> also, why is this script for xcode not using the `find-node` script??! The change there should be enough for all the things within RN to find the right node without duplicating code.

because this PR was created (2020/10) before `scripts/find-node.sh` (2021/1, if the [commit history](https://github.com/facebook/react-native/commits/main/scripts/find-node.sh) is correct)

> HI @pastleo, can we move this change to `find-node.sh` alongside the other environment manager code?

sure, please do, and maybe I should close this PR?

**Comment by charlesbdudley** [comment]
@pastleo, sorry, I meant do you mind making the change? :)

**Comment by pastleo** [comment]
> @pastleo, sorry, I meant do you mind making the change? :)

OK, but I wasn't developing RN for quite a while now, I will make the change when I have time (and setup a project to test as well)
Should I open new PR? or just modify this one?

**Comment by pastleo** [comment]
@charlesbdudley I just moved the change to `find-node.sh`, also created a new RN project to test and it is working

**Pull request closed without merging**
