### PR TITLE
[Map] Add custom tiles support via MKTileOverlay + UIExplorer examples

### PR DESCRIPTION
**Pull request by ptmt**
```js
<MapView tilesSource={'http://tile.openstreetmap.org/{z}/{x}/{y}.png'} />
```

ios simulator screen shot aug 20 2015 8 32 45 pm
ios simulator screen shot aug 20 2015 8 33 55 pm

### CODE REVIEW

**Comment by dwightwatson** [comment]
This would be a great addition. In addition, how difficult would it be to also support a callback that would return the tile source URL, for example if some calculations are required on the x, y and z parameters?

**Comment by ptmt** [comment]
I'm closing it, since it's pointless now. There are bunch of third-party plugins.

**Comment by thiphariel** [comment]
@ptmt Hi. Could you provide some links to third party plugins which handle that ?

**Comment by ptmt** [comment]
@thiphariel this looks awesome https://github.com/mapbox/react-native-mapbox-gl

**Comment by thiphariel** [comment]
@ptmt yeah, but we can only use mapbox tiles, not custom or OSM servers. If you know a plugin that allows that, I'm looking forward...

**Comment by ptmt** [comment]
@thiphariel sorry, it seems you're right. I couldn't find anything now. I'm reopening this, but with no hope to merge it into master, since react-native core contributors are really overwhelmed at the moment. I'm not able to extract this into a standalone plugin, maybe you can help?

**Comment by thiphariel** [comment]
Hum, right now, I do not have enough time to do it, I'm sorry :/ I prefer not to get into a task I could surely not complete ... Maybe someone else can help. Otherwise, no problem, perhaps it could be merged on master one day.

Anyway, thanks !

**Comment by facebook-github-bot-7** [comment]
@AaaChiuuu would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
Just read the whole discussion and based on it I think we should close this. To keep the number of open  PRs under control, all PRs should either be actively worked on or closed. If anyone has time to continue working on this in the future they can still use the code in this PR as a start.

**Comment by mkonicek** [comment]
Thanks for your contribution @ptmt! Hope you'll keep contributing to React Native.

**Pull request closed without merging**
