### PR TITLE
Fix tvOS issues in React.xcodeproj

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
**Motivation**: (1) My previous commit crossed with @mkonicek 's build fix (a8bd4621afb952c0a24cbd04a4154d2be6796aa4), so it isn't needed any more -- backing it out.  (2) RCTJSCErrorHandling needs to be added to React-tvOS target.
CC: @janicduplessis @lacker @ericvicenti

### CODE REVIEW

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by dlowder-salesforce** [comment]
@janicduplessis something weird is still going on... the "Import Started" label is not appearing as expected

**Comment by janicduplessis** [comment]
@dlowder-salesforce Looks like when using the shipit bot it doesn't add the labels, but it does when using the fb internal tool.

See your initial PR doesn't have the labels but did import properly. https://github.com/facebook/react-native/pull/12869

**Comment by dlowder-salesforce** [comment]
Ah ok, thanks for the clarification

**Comment by mkonicek** [comment]
Sorry about the bot flakiness guys. I have to learn about how the bot works now it's been rewritten to use webhooks a few months ago by a different team.

If it doesn't work just message me or the oncall on Slack. Fb employees use a Chrome extension now (also built by that team) that adds buttons to Chrome to do the import and luckily that one works.

screenshot 2017-03-14 07 42 42

**Comment by mkonicek** [comment]
Trying again, failed with a weird error.

**Comment by janicduplessis** [comment]
@dlowder-salesforce I think everything was fixed in a recent commit.

**Comment by dlowder-salesforce** [comment]
The issues addressed by this PR have already been fixed in https://github.com/facebook/react-native/commit/dcf3cbeb313453a6762a8a69d3749f9971d8a268 , so closing this.

**Pull request closed without merging**
