### PR TITLE
Update platform specific code inspiration code for Button component

### PR DESCRIPTION
**Pull request by cHaLkdusT**
Updated Button component inspiration. Refactored code takes advantage of Platform Specific Code, as we want to re-use as much code as possible.

## Test Plan

1. Import Button component
2. Button should work the same

## Related PRs

N/A

## Release Notes

[GENERAL] [ENHANCEMENT] [Button] - Uses spread operator for platform specific code in creating styles

### CODE REVIEW

**Comment by cHaLkdusT** [comment]
Rebasing this PR

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :lock: package.json - <i>Changes were made to package.json. This will require a manual import by a Facebook employee.</i>
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR - <i>This PR is extremely unlikely to get reviewed because it touches 86365 lines.</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cHaLkdusT** [comment]
Should I re-submit a new PR to resolve rebasing issue?

**Comment by hramos** [comment]
You can push changes to this PR, or open a new one. Makes no difference to us.

**Comment by cHaLkdusT** [comment]
Will create a new PR

**Pull request closed without merging**
