### PR TITLE
[Image] Update Image docs to include isStatic flag

### PR DESCRIPTION
**Pull request by mattotodd**
re issue: https://github.com/facebook/react-native/issues/751

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks! And thanks for marking it as highly to change as well :)

**Comment by brentvatne** [comment]
@vjeux - looks good to me

**Comment by vjeux** [comment]
@facebook-github-bot import

**Comment by vjeux** [comment]
So sorry about the huge wait time :( We actually removed isStatic flag

**Comment by idibidiart** [comment]
@vjeux so there is no way to quickly prototype with images in local folder? (not web accessible)

**Comment by ide** [comment]
Asset management is supposed to be coming to the packager but in the meantime you could make your images web accessible with `python -m SimpleHTTPServer`.

**Comment by idibidiart** [comment]
That's great. Thanks.

**Comment by vjeux** [comment]
Internally we can do require('./image.png') and have the packager send the image. I'm not sure what's the status is for open source yet.

**Pull request closed without merging**
