### PR TITLE
[JS Polyfills] Also call the original `console` methods if they exist

### PR DESCRIPTION
**Pull request by ccheever**
Ex. When `console.log` or similar is called, this will call
the original method, which can be quite useful.

For example, under iOS, this will log to the Safari console debugger,
which has an expandable UI for inspecting objects, etc., and is also
just useful if you are using that as a REPL.

I don't believe this incurs a meaningful performance penalty unless
the console is open, but it would be easy to stick behind a flag
if that is a problem.

### CODE REVIEW

**Comment by brentvatne** [comment]
@vjeux - this looks good to me, do you see any issues with pulling this in?

**Comment by vjeux** [comment]
Sorry for the super long review time :x Can you get rid of all the unrelated changes and rebase? Thanks!

**Comment by ide** [comment]
@vjeux here is a rebased version: https://github.com/facebook/react-native/pull/2486

**Comment by ide** [comment]
merged (w original author attribution!)

**Pull request closed without merging**
