### PR TITLE
add lost params for including Stetho

### PR DESCRIPTION
**Pull request by Sveta-K13**
Method onCreate must be called with parameter -  Bundle savedInstanceState. 'savedInstanceState' needed for call super class's implementation of this method. Also, you need to import android.os.Bundle package

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
@Sveta-K13, can you update your original comment with more context about this PR?

**Comment by Sveta-K13** [comment]
@hramos done

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
