### PR TITLE
feat: set disabled accessibilityState when TouchableHighlight is disabled

### PR DESCRIPTION
**Pull request by Naturalclar**
#30950 

## Summary

automatically set `disabled` to accessibilityState when TouchableHighlight is disabled

## Changelog

[General] [Changed] - Set disabled accessibilityState when TouchableHighlight is disabled

## Test Plan
Tested on physical android device that pressing disabled TouchableHighlight announces "dim" when talkback is on

### CODE REVIEW

**Comment by kacieb** [comment]
This is great and those test cases are awesome! 😍  Thank you so much for working on this!

@lunaleaps Do you think the component should also be disabled if accessibilityState.disabled=true, if the disabled prop is not set? Like in this PR: https://github.com/facebook/react-native/pull/31001

**Comment by lunaleaps** [comment]
Yea! I think it'd be good to have this consistent across the components. @Naturalclar can you follow the logic in #31001 where `accessibilityState.disabled` set to true will wil also disable the component?

**Comment by Naturalclar** [comment]
@lunaleaps Sure thing! made the change in 4dc00ba

**Comment by amarlette** [comment]
Thank you @Naturalclar for this contribution! I would like to give you a shout-out on Twitter and include you in our end-of-month issues update for your contribution. Do you have a Twitter we can tag? Is your twitter @ the same as your Github?

**Comment by Naturalclar** [comment]
@amarlette thank you! 
My Twitter account is [natural_clar](https://twitter.com/natural_clar) 😃

**Comment by kacieb** [comment]
Thank you so much for this pull request!!!

I made a few small changes to the test cases before landing, and wanted to let you know in case you write any future tests! Thanks so much for including the tests by the way, that will make sure this functionality doesn't break in the future.

I changed the `expectRenderMatchingSnapshot` calls to use this structure instead:
```
expect(
  ReactTestRenderer.create(<TouchableHighlight ... />)
).toMatchSnapshot();
```

This is because `expectRenderMatchingSnapshot` is primarily only needed for checking that the display name works correctly, and that mocking and unmocking the component works as expected. This wasn't necessary in this case, since we're only checking prop values.

Thanks again for helping improve React Native's accessibility! 🎉

**Pull request closed without merging**
