### PR TITLE
iOS: Remove leading space from accessibilityLabel

### PR DESCRIPTION
**Pull request by rigdern**
In some cases, the accessibilityLabel contains a leading space. This is because `RCTRecursiveAccessibilityLabel` adds a space before every iteration of the loop including the first.

After this change, the contract is that:
  - `RCTRecursiveAccessibilityLabel` always returns a string with a leading space.
  - `accessibilityLabel` never returns a string with a leading space.

**Test plan**

I created a test app with the following code:

```
<View style={{height: 100, width: 100, backgroundColor: 'steelblue'}} accessible={true}>
  <View style={{height: 20, width: 20, backgroundColor: 'red'}} accessibilityLabel='One' />
  <View style={{height: 20, width: 20, backgroundColor: 'yellow'}} accessibilityLabel='Two' />
  <View style={{height: 20, width: 20, backgroundColor: 'green'}} accessibilityLabel='Three' />
</View>
```

Before this change, the accessibilityLabel of the outermost View was " One Two Three" (notice the leading space).

After this change, it is "One Two Three" as desired.

Adam Comella
Microsoft Corp.

### CODE REVIEW

**Comment by shergin** [comment]
I believe, it would be better if we will fix it inside `RCTRecursiveAccessibilityLabel`.

**Comment by rigdern** [comment]
@shergin Thanks for the feedback. I pushed a commit which does the fix inside of `RCTRecursiveAccessibilityLabel` instead.

**Comment by jaunesarmiento** [comment]
I'm not sure if it's just my setup but I'm still getting whitespaces in my accessibility labels even after applying this patch. Probably due to higher-order components (e.g Redux's `connect`). I really need this to work for our UI tests. 

Here's a sample output that `XCUIApplication().otherElements` prints in the log:
```
    Other 0x600000361800: traits: 8589934592, {{-331.3, 44.0}, {331.3, 158.0}}, label: ' ',
    Other 0x600000362400: traits: 8589934592, {{-331.3, 202.0}, {331.3, 50.0}}, label: 'Game Feed',
    Other 0x6000003624c0: traits: 8589934592, {{-331.3, 202.0}, {331.3, 50.0}}, label: 'Game Feed',
    Other 0x600000362640: traits: 8589934592, {{-331.3, 252.0}, {331.3, 50.0}}, label: 'My Games',
    Other 0x600000362700: traits: 8589934592, {{-331.3, 252.0}, {331.3, 50.0}}, label: 'My Games',
    Other 0x600000362880: traits: 8589934592, {{-331.3, 302.0}, {331.3, 50.0}}, label: 'Preferred Sports',
    Other 0x600000362940: traits: 8589934592, {{-331.3, 302.0}, {331.3, 50.0}}, label: 'Preferred Sports',
    Other 0x600000362c40: traits: 8589934592, {{-331.3, 352.0}, {331.3, 50.0}}, label: 'Profile',
    Other 0x600000362ac0: traits: 8589934592, {{-331.3, 352.0}, {331.3, 50.0}}, label: 'Profile',
    Other 0x600000362dc0: traits: 8589934592, {{-331.3, 402.0}, {331.3, 50.0}}, label: 'Settings',
    Other 0x600000362e80: traits: 8589934592, {{-331.3, 402.0}, {331.3, 50.0}}, label: 'Settings',
    Other 0x600000361c80: traits: 8589934592, {{-331.3, 44.0}, {331.3, 408.0}}, label: '  Game Feed My Games Preferred Sports Profile Settings',
    Other 0x600000361e00: traits: 8589934592, {{-331.3, 44.0}, {331.3, 661.7}}, label: '  Game Feed My Games Preferred Sports Profile Settings  ',
    Other 0x600000361980: traits: 8589934592, {{-331.3, 0.0}, {331.3, 736.0}}, label: '  Game Feed My Games Preferred Sports Profile Settings   2.5.0.17041001_dev',
    Other 0x600000363000: traits: 8589934592, {{-331.3, 0.0}, {331.3, 736.0}},
    Other 0x600000361b00: traits: 8589934592, {{-331.3, 0.0}, {331.3, 736.0}}, label: '  Game Feed My Games Preferred Sports Profile Settings   2.5.0.17041001_dev ',
    Other 0x600000362580: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}},
    Other 0x600000363780: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '  ',
    Other 0x600000363840: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '  ',
    Other 0x600000363900: traits: 8589934592, {{-414.0, 0.0}, {1656.0, 736.0}}, label: '  ',
    Other 0x600000362280: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '  ',
    Other 0x600000363540: traits: 8589934592, {{182.0, 639.0}, {8.0, 8.0}},
    Other 0x600000363480: traits: 8589934592, {{196.0, 639.0}, {8.0, 8.0}},
    Other 0x6000003633c0: traits: 8589934592, {{210.0, 639.0}, {8.0, 8.0}},
    Other 0x600000363240: traits: 8589934592, {{224.0, 639.0}, {8.0, 8.0}},
    Other 0x600000363600: traits: 8589934592, {{0.0, 636.0}, {414.0, 75.0}}, label: '   ',
    Other 0x600000363180: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '      ',
    Other 0x6000003627c0: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '        ',
    Other 0x600000362a00: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '        ',
    Other 0x600000362b80: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '        ',
    Other 0x600000362d00: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '        ',
    Other 0x600000362100: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}},
    Other 0x600000362f40: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '         ',
    Other 0x600000361a40: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '            Game Feed My Games Preferred Sports Profile Settings   2.5.0.17041001_dev ',
    Other 0x600000361ec0: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '             Game Feed My Games Preferred Sports Profile Settings   2.5.0.17041001_dev  ',
    Other 0x600000361d40: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '             Game Feed My Games Preferred Sports Profile Settings   2.5.0.17041001_dev  ',
    Other 0x600000361bc0: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '             Game Feed My Games Preferred Sports Profile Settings   2.5.0.17041001_dev   ',
    Other 0x6000003621c0: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}}, label: '             Game Feed My Games Preferred Sports Profile Settings   2.5.0.17041001_dev   ',
    Other 0x60000017be40: traits: 8589934592, {{0.0, 0.0}, {414.0, 736.0}},
    Other 0x60000017c080: {{0.0, 0.0}, {414.0, 20.0}},
    Other 0x600000360900: traits: 8388608, {{6.0, 0.0}, {39.0, 20.0}},
    Other 0x600000360840: traits: 8388608, {{50.0, 0.0}, {13.0, 20.0}}, label: '3 of 3 Wi-Fi bars', value: SSID,
    Other 0x600000360780: traits: 8389120, {{185.0, 0.0}, {48.0, 20.0}}, label: '5:21 AM',
    Other 0x6000003606c0: traits: 8388608, {{376.0, 0.0}, {33.0, 20.0}}, label: '-100% battery power',
    Other 0x60000017b300: {{0.0, 0.0}, {414.0, 20.0}}
```

Could it be that the some components return blank as `accessiblityLabel`?

**Comment by rigdern** [comment]
@jaunesarmiento What version of React Native are you using? Are you sure it includes the fix?

**Comment by jaunesarmiento** [comment]
@rigdern 0.42. I've used the commit as a patch. Yes, the fix is included cause the prior to this fix, the following have leading whitespace in them:
```
Other 0x600000362400: traits: 8589934592, {{-331.3, 202.0}, {331.3, 50.0}}, label: 'Game Feed',
Other 0x6000003624c0: traits: 8589934592, {{-331.3, 202.0}, {331.3, 50.0}}, label: 'Game Feed',
Other 0x600000362640: traits: 8589934592, {{-331.3, 252.0}, {331.3, 50.0}}, label: 'My Games',
Other 0x600000362700: traits: 8589934592, {{-331.3, 252.0}, {331.3, 50.0}}, label: 'My Games',
Other 0x600000362880: traits: 8589934592, {{-331.3, 302.0}, {331.3, 50.0}}, label: 'Preferred Sports',
Other 0x600000362940: traits: 8589934592, {{-331.3, 302.0}, {331.3, 50.0}}, label: 'Preferred Sports',
Other 0x600000362c40: traits: 8589934592, {{-331.3, 352.0}, {331.3, 50.0}}, label: 'Profile',
Other 0x600000362ac0: traits: 8589934592, {{-331.3, 352.0}, {331.3, 50.0}}, label: 'Profile',
Other 0x600000362dc0: traits: 8589934592, {{-331.3, 402.0}, {331.3, 50.0}}, label: 'Settings',
Other 0x600000362e80: traits: 8589934592, {{-331.3, 402.0}, {331.3, 50.0}}, label: 'Settings',
```

**Comment by jaunesarmiento** [comment]
@rigdern nevermind. Found out that it's easier to use `testID` for this use case. Thanks though.

**Comment by shergin** [comment]
@jaunesarmiento Obviously, you should not use `testID` for accessibility purposes! :(

**Comment by rigdern** [comment]
@jaunesarmiento I know you may not be interested anymore but I suspect PR #14177 will fix your issue.

**Pull request closed without merging**
