### PR TITLE
Fix downloading hermes for nightlies

### PR DESCRIPTION
**Pull request by tsapeta**
## Summary:

https://github.com/facebook/react-native/pull/38963 introduced a regression that breaks downloading hermes tarball for nightlies. It fails with the following error when running `pod install`:

```
Fetching podspec for `hermes-engine` from `../../../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[!] Failed to load 'hermes-engine' podspec: 
[!] Invalid `hermes-engine.podspec` file: undefined local variable or method `react_native_path' for Pod:Module
Did you mean?  react_native_post_install.
```

The root cause is that the `download_nightly_hermes` method was just not implemented.

## Changelog:

[IOS] [FIXED] - Fixed downloading hermes tarball for nightlies

## Test Plan:

After applying these changes, `pod install` in my project no longer fails and downloads the tarball correctly.

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
Thanks for the fix, sorry for the breakage! 🙇

**Comment by dmytrorykun** [comment]
@tsapeta thank you for identifying this issue!
After https://github.com/facebook/react-native/pull/38920 we no longer need to download nightly hermes manually. Proper solution for this bug would be to just remove this line https://github.com/facebook/react-native/blob/main/packages/react-native/sdks/hermes-engine/hermes-utils.rb#L188
I does nothing, it remained there probably due to bad mere or something like that.

**Review by dmytrorykun — CHANGES_REQUESTED** [review]
My previous comment.

**Comment by tsapeta** [comment]
@dmytrorykun Thanks! I deleted that line, but it turned out that we also need to pass the version as an argument to get the proper url. Hopefully it's fine now 🙂

**Comment by dmytrorykun** [comment]
@tsapeta It's perfect, thank you!

**Pull request closed without merging**
