### PR TITLE
[Showcase] Update Exponent logo and links

### PR DESCRIPTION
**Pull request by ide**

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1295915900424892/int_phab) to review.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1295915900424892/int_phab) to review.

**Pull request closed without merging**
