### PR TITLE
Remove unused/invalid Flow suppression

### PR DESCRIPTION
**Pull request by arv**
The suppression comment was not formatted correctly and thus not
used.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @davidaurelio and @lelandrichardson to be potential reviewers.

**Comment by ide** [comment]
`npm run flow -- check` succeeded - merging

@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3917036).

**Comment by arv** [comment]
Some more info... If I changed that comment to `$FlowIssue #123` it says invalid suppression, meaning that there is no error for Flow to suppress. The reason that this is not causing any issue on master is that `$FlowIssue` is not recognized by Flow.

**Pull request closed without merging**
