### PR TITLE
Fixed incorrect rows reported in onChangeVisibleRows

### PR DESCRIPTION
**Pull request by dmueller39**
There is a bug in onChangeVisibleRows when the renderSeparator is not null. The _updateVisibleRows function does not account for the presence of separator frames in the  _childFrames array.

When renderSeparator is not null, increment the totalIndex an additional
time for each row that isn't the last in its section, or the last in the entire
list.

This continues a slightly brittle precedent of having a set of parallel conditions in render and _updateVisibleRows. (i.e. renderSectionHeader is used in both functions, in render as a condition to create a sectionHeader, and in _updateVisibleRows as a condition to increment the totalIndex.

Before change:
yeeqnmvmif

After change:
gzbrljclzm

Built using https://gist.github.com/dmueller39/f95028f6fe8bd251944bb604e51f18b2

### CODE REVIEW

**Comment by dmueller39** [comment]
@vjeux The continuous integration is marked as "canceled". Does that mean it actually failed? Or should I retest this somehow?

**Comment by dmueller39** [comment]
Fixes https://github.com/facebook/react-native/issues/7360

**Comment by damusnet** [comment]
Fixes #6702

**Comment by vjeux** [comment]
@sahrens, it looks like this is a simple fix and would fox three independent issues. Could you look into it? Thanks!

**Comment by facebook-github-bot-2** [comment]
@pglotov would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by sahrens** [comment]
@facebook-github-bot shipit

**Comment by dmueller39** [comment]
@sahrens How can I help to get this merged?

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/242535166094038/int_phab) to review.

**Comment by vjeux** [comment]
So, our shipit bot sometimes fail and doesn't currently reply with an error. If you don't see it replying within a couple of minutes, do not hesitate to ping on the pull request to figure out what's going on.

It's definitely suboptimal and someone is working on fixing it, so that a pull request doesn't stay in limbo for weeks. Sorry about that!

**Comment by dmueller39** [comment]
@vjeux The more you know! ™

**Pull request closed without merging**
