### PR TITLE
Allow to control transition in CardStack

### PR DESCRIPTION
**Pull request by ptomasroos**
This pull request allows users of CardStack to configure the transition of the underlying NavigationTransitioner.

This is very generic and a useful feature in order to customize the experience of a stack.

Tested this with UIExplorer

### CODE REVIEW

**Comment by ptomasroos** [comment]
You're welcome @hedgerwang !

**Comment by ptomasroos** [comment]
Any reason this didnt get pulled @hedgerwang ?

**Comment by hedgerwang** [comment]
Looks like ci was broken and the branch is outdated.

image

**Comment by ptomasroos** [comment]
@hedgerwang updated branch!

**Comment by hramos** [comment]
Sorry about the delay here @ptomasroos, looks like this needs one more change to resolve the conflict, then we can import.

**Comment by lacker** [comment]
I think this pull request has been abandoned. Sorry we didn't get through the review faster! Anyway, I am going to close it, but if you are still interested in working on this then please feel free to spin it back up again.

**Pull request closed without merging**
