### PR TITLE
Akring integration tests fix

### PR DESCRIPTION
**Pull request by alexkring**
## Motivation (required)

Fix a bug that allows us to run integration tests in our android project, where RN is specified as a module to our project.

sdkHandler does not exist. The android documentation suggests that we should be using android.ndkDirectory instead.

http://tools.android.com/tech-docs/new-build-system/migrating-to-1-0-0

An alternative solution would be to set the environment variable ANDROID_NDK, but we do not want to rely on setting this environemnt variable at a system wide level.

## Test Plan 

We ran two tests. 
1.) perform a gradle sync from within our Android studio project, and verify there is no error output. 
2.) build android using ./gradleW, from command land. Verify there are no build errors.

### CODE REVIEW

**Comment by alexkring** [comment]
@shergin Any update on this commit? It has been idle for a while now. 
Also, I'm not sure what the "JS" label is, but I am guessing that stands for javascript? This merge is about android not javascript. Thanks for the help :]

**Comment by shergin** [comment]
@alexkring Sorry, I applied the (wrong) tag just to improve discoverability of the PR.
Looks reasonable to me, btw, but I don't have real android expertise to accept it.
Can we make this code a bit easier to read?
So, now we have three sources of NDK path, are you sure that the order/priority is correct? Why?

**Comment by alexkring** [comment]
@shergin Yes, the order is correct. I am adding one additional directory to check, and we only check that directory, if the existing to spots that are currently checked, fail. This is the additional directory that we check:

android.ndkDirectory.absolutePath

**Comment by shergin** [comment]
@alexkring Yes, I understand. My question was more about **conceptual** correctness of the order. Can we always use `android.ndkDirectory.absolutePath`?

**Comment by alexkring** [comment]
@shergin That is a difficult question to answer, and I dont think I can say with 100% certainty that we can always use android.ndkDirectory.absolute path, given how complicated it is to understand versioning with the android gradle plugin.

But, I feel pretty confident that we can rely on this. This function was introduced in version 1.4 of the Android Plugin DSL, which was release over 2 years ago. The latest version is 2.3.

http://google.github.io/android-gradle-dsl/1.4/com.android.build.gradle.LibraryExtension.html
https://github.com/google/android-gradle-dsl/tree/gh-pages/1.4

**Pull request closed without merging**
