### PR TITLE
Adding Trakref® to Showcase

### PR DESCRIPTION
**Pull request by NateHook**
We would like to see if we can get Trakref® added to the Showcase of React applications.

Our Product is simply called Trakref® and it was created in-house by the Trakref® dev team.

trakref-stacked-logo-icon

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-6** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-1** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@NateHook updated the pull request.

**Comment by dsibiski** [comment]
@NateHook It looks like you're trying to merge the wrong branch...please delete this PR and create another one that refers to the correct branch.

**Comment by facebook-github-bot-3** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@NateHook updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@NateHook updated the pull request.

**Pull request closed without merging**
