### PR TITLE
Update Babel/React Dependencies

### PR DESCRIPTION
**Pull request by skevy**
PR does as it says -- updates Babel dependencies to latest versions.

In general, this changes nothing for 99.9% of users (everyone that isn't FB). If they were to `npm install react-native` right now, they would get all of these dependencies anyway.

However, this does revert a previous change where we were using "~" instead of "^" in front of the Babel deps in order to attempt to lock them to minor dependencies. However, due to the fact that each Babel package uses "^", and there are so many interdependencies, this actually would cause an issue where multiple versions of babel-core, et. al. to be installed.

*Edit* - In addition, we add React to `devDependencies` so that it behaves properly in testing, now that it's a peer dependency.

### CODE REVIEW

**Comment by skevy** [comment]
cc @kittens @vjeux

**Comment by steveluscher** [comment]
@facebook-github-bot import

**Comment by skevy** [comment]
@steveluscher was there a blocking issue on this?

**Comment by steveluscher** [comment]
screen-shot-2014-12-22-at-11 39 29-pm

**Comment by steveluscher** [comment]
cc/ @davidaurelio

**Pull request closed without merging**
