### PR TITLE
Add link to the survey at the bottom of the page

### PR DESCRIPTION
**Pull request by vjeux**
simulator screen shot may 11 2016 3 03 14 pm

screen shot 2016-05-11 at 3 03 25 pm

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @janicduplessis and @skevy to be potential reviewers.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by JoelMarcey** [comment]
@facebook-github-bot import

**Comment by JoelMarcey** [comment]
@facebook-github-bot import

**Pull request closed without merging**
