### PR TITLE
fix: background color fix when border is dotted and dashed

### PR DESCRIPTION
**Pull request by shubhamguptadream11**
## Summary:
This PR fixes these issues: https://github.com/facebook/react-native/issues/42289, https://github.com/facebook/react-native/issues/45368

## Changelog:

[IOS] [FIXED] - Message

In iOS for old/new architecture when we are trying to pass borderStyle other than 'solid' then in this 
**Old Arch file**
https://github.com/facebook/react-native/blob/2eb7bcb8d9c0f239a13897e3a5d4397d81d3f627/packages/react-native/React/Views/RCTView.m#L807
**New Arch file**
https://github.com/facebook/react-native/blob/2eb7bcb8d9c0f239a13897e3a5d4397d81d3f627/packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm#L652
 file useCoreAnimationBorderRendering is coming as nil since borderStyle passed is not **solid**. Due to which else case block executes and there we are applying backgroundColor as nil.

I just removed that hardcoded check for sold style and make sured that it is now working now with all three borderStyle 'dotted' | 'solid' | 'dashed' for Text and View both

## Test Plan:

Tested with possible borderStyle values.

Providing the fixed screenshot here.

simulator_screenshot_5E7DDDE7-71F2-4A35-93B3-BFD9F980EA18

### CODE REVIEW

**Review by cipolleschi — COMMENTED** [review]
Hi @shubhamguptadream11, thank you for this fix.

This code only target the old architecture.
Can you please verify if the New Architecture suffer from the same problem and provide a fix there as well?

It should be somewhere [here](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm).

**Comment by shubhamguptadream11** [comment]
@cipolleschi I already did this before. Should I merge both PR into one?
https://github.com/facebook/react-native/pull/45369

**Comment by shubhamguptadream11** [comment]
@cipolleschi Added fix for new arch as well. Please review this once.

**Review by cipolleschi — APPROVED** [review]

**Comment by cipolleschi** [comment]
Thanks for the fix. Let me import this and let's see how it goes internally! :D

**Pull request closed without merging**
