### PR TITLE
update AsyncStorage.js documentation

### PR DESCRIPTION
**Pull request by arielelkin**
Otherwise it could be perceived as safe for storing sensitive data.

See
https://medium.com/@ntoscano/react-native-persistent-user-login-6a48ff380ab8#.2pxlht5ti

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @geirman to be potential reviewers.

**Comment by geirman** [comment]
Thanks! Storage is actually unencrypted for both iOS and Android, so you need not mention iOS specifically. So, you could simply add "`unencrypted`" to the list of attributes like so...

> `AsyncStorage` is a simple, unencrypted, asynchronous, persistent, key-value storage...

Also, be sure to eliminate trailing spaces.

**Comment by arielelkin** [comment]
@geirman done: https://github.com/facebook/react-native/pull/8809/commits/fe3cdf355c403cc778b44ac4bb47d5b97fb5bb9c

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Thanks!

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/981058288683162/int_phab) to review.

**Pull request closed without merging**
