### PR TITLE
[Android] [Added] - Add DevSetting native module (making it cross-platform)

### PR DESCRIPTION
**Pull request by elucaswork**
## Summary

React Native has a `NativeModule` to manipulate programmatically the dev menu options (live reload, hot reload, remote debugging, etc), called [`DevSettings`](https://github.com/facebook/react-native/blob/master/React/Modules/RCTDevSettings.mm#L120). However this module is only available for iOS.

This PR brings the same `DevSettings` for Android, making it a cross-platform NativeModule.

Motivation: Right now if your app needs to programmatically reload RN, one option is to install [`react-native-restart`](https://www.npmjs.com/package/react-native-restart). It's a tiny dependency, but it's annoying to have to install it, while the code to do so is inside RN codebase. According to NPM, react-native-restart has ~12k weekly downloads, shows it's a recurring feature for many apps (my case).

Thus making `NativeModules.DevSettings` is a small increment in the codebase, just exposing the dev menu methods, to improve the Development Experience

## Changelog

[Android] [Added] - Add DevSetting native module (making it cross-platform)

With expection of `setIsShakeToShowDevMenuEnabled`, the following methods will be available for both platforms: 
* reload
* setHotLoadingEnabled
* setIsDebuggingRemotely
* setIsShakeToShowDevMenuEnabled
* setLiveReloadEnabled
* setProfilingEnabled
* toggleElementInspector

## Test Plan

The following buttons should work for both iOS and Android.

```js
<View>
  <Button
    onPress={() => {
      NativeModules.DevSettings.reload();
    }}
    title="Reload"
  />
  <Button
    onPress={() => {
      NativeModules.DevSettings.setHotLoadingEnabled(true);
    }}
    title="setHotLoadingEnabled"
  />
  <Button
    onPress={() => {
      NativeModules.DevSettings.setIsDebuggingRemotely(true);
    }}
    title="setIsDebuggingRemotely"
  />
  <Button
    onPress={() => {
      NativeModules.DevSettings.setLiveReloadEnabled(true);
    }}
    title="setLiveReloadEnabled"
  />
  <Button
    onPress={() => {
      NativeModules.DevSettings.setProfilingEnabled(true);
    }}
    title="setProfilingEnabled"
  />
  <Button
    onPress={() => {
      NativeModules.DevSettings.toggleElementInspector();
    }}
    title="toggleElementInspector"
  />
</View>
```

P.S DevSettings is only available via NativeModules (it doesn't have a Library, `import { DevSetting } from "react-native"`). But I think It'd useful to have it and add documentation for it to make these features more well known. In case this PR gets approved, please let me know if making a `DevSetting` library looks ok. I'd be happy to do it.

Possible features to be included into DevSettings module: 
  * Expose a method to add a custom item into the dev menu (via `RCTDevMenuItem` and `DevSupportManager.addCustomDevOption`);
  * Expose a method to register a custom keyboard shortcut, e.g: CMD+B to open Storybook (via `RCTKeyCommands` and)

### CODE REVIEW

**Comment by cpojer** [comment]
I'm getting:

```
ReactAndroid/src/main/java/com/facebook/react/devsupport/DevSupportManagerImpl.java:1053: error: local variable enableHotModuleReplacement is accessed from within inner class; needs to be declared final
          mDevSettings.setHotModuleReplacementEnabled(enableHotModuleReplacement);
```

for all the variables in the lines you changed in that file.

Do you mind patching up the PR? :)

**Comment by lucasbento** [comment]
This is pure ❤️

**Comment by cpojer** [comment]
@elucaswork can you make sure test_android passes on CI? It seems like it's not working.

**Comment by elucaswork** [comment]
@cpojer I was not getting the issues you mentioned, but I saw it happening for CI as well. I was able to make a commit fixing it. 

Now the CI is failing with other issues that I can't replicate on my environment

```
BUILDING: FINISHED IN 4.0s (100%) 234/237 JOBS, 196 UPDATED
BUILD FAILED
Command failed with exit code 1.
stderr: /root/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/debug/DevSettingsModule.java:13: error: package com.facebook.react.devsupport.interfaces does not exist
import com.facebook.react.devsupport.interfaces.DevSupportManager;
                                               ^
/root/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/debug/DevSettingsModule.java:25: error: cannot find symbol
  private final DevSupportManager mDevSupportManager;
                ^
  symbol:   class DevSupportManager
  location: class com.facebook.react.modules.debug.DevSettingsModule
/root/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/debug/DevSettingsModule.java:27: error: cannot find symbol
  public DevSettingsModule(DevSupportManager devSupportManager) {
                           ^
  symbol:   class DevSupportManager
  location: class com.facebook.react.modules.debug.DevSettingsModule
Errors: 3. Warnings: 0.

```

For me, even rebasing my branch against master, and rebuilding the project, I always get `BUILD SUCCESSFUL`. I'm using Android 3.3.2.

I'm not an Android developer, so I don't have an idea of what can be the problem yet. But it's weird for me that [`RedBoxDialog`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/devsupport/RedBoxDialog.java#L36) is also using `DevSupportManager`, the same way as `DevSettingsModule`, but the error is happening just for this new class :-/

I'm gonna continue investigating this issue. But if you have an idea of what I can be, just let me know, please.

**Comment by cpojer** [comment]
We use buck to build Android on CI and at Facebook. Can you compare the BUCK file in the folder for the Redbox code and update it accordingly? It is most likely that you just need to add the right dependency in a BUCK file and it is probably a one-liner :) Thanks for looking into this, I know it is not straightforward.

**Comment by cpojer** [comment]
Let's see what the internal CI says. It seems that there is some androidx issue on CI here.

**Comment by elucaswork** [comment]
@cpojer cool. Thanks for your support! Very helpful. 

Also, please let me know what you think of exposing `DevSetting` module through a JS library. If you guys agree with it, I could make it happen in a separate PR.  Same for the "possible features" I've mentioned in the description.

**Comment by cpojer** [comment]
Yeah I think that's a good idea, we just need to make sure it is only available in development :)

**Pull request closed without merging**
