### PR TITLE
[PushNotification] Add soundName config for UILocalNotification

### PR DESCRIPTION
**Pull request by pecheriere**
Current version wasn't triggering any sound when a local notification was fired. I added the possibility to provide a custom sound and fallback to the default iOS sound if not provided.

### CODE REVIEW

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
Thanks!

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@mkonicek pinging on this one (i know you're flying right now, so no rush).

Interestingly, this one didn't even send back the Facebook import message

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
There's something seriously wrong with the bot :(

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
I'll debug the bot.

**Comment by mkonicek** [comment]
It's working on other PRs: https://github.com/facebook/react-native/pull/5146 Will take a  look soon.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
It fails with:

    Patch is malformed: From 99865befd2608a6b8853f5733a27dea45a9cce53 Mon Sep 17 00:00:00 2001
    From: =?UTF-8?q?Pierre-Etienne=20Cheri=C3=A8re?=
    <pecheriere@users.noreply.github.com>
    Date: Thu, 17 Dec 2015 10:01:20 +0100
    Subject: [PATCH 1/2] Add soundName config for UILocalNotification
    ...

**Comment by mkonicek** [comment]
This sounds silly but can you try sending the PR with ASCII-only characters in author? http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by mkonicek** [comment]
Oh lol, here's the code that throws that :)

    list($status, $matches) = Regex::match('/From: (.*) <(.*)>/', $patch);
    if (!$status) {
      throw new SystemException('Patch is malformed: '.$patch);
    }

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
I'm not sure we support non-ASCII user names well though :(

screen shot 2016-01-06 at 3 56 46 pm

**Comment by mkonicek** [comment]
OK the merge worked but didn't manage to preserve the author, sorry about that: https://github.com/facebook/react-native/commit/ac72611bb1c41765a59c8249cc4332110341deb1

It has to do with the newline in the From field, first time I saw this happen:

    From: =?UTF-8?q?Pierre-Etienne=20Cheri=C3=A8re?=
    <pecheriere@users.noreply.github.com>
    Date: Thu, 17 Dec 2015 10:01:20 +0100

**Comment by npomfret** [comment]
I cannot get my custom sound to play in a local notification, it always plays the default sound.  Is there a 'trick' to getting this working?

**Pull request closed without merging**
