### PR TITLE
Better error handling in Android Geolocation module (PR 1)

### PR DESCRIPTION
**Pull request by mkonicek-pr-test**
Just a testing PR for the shipit bot (please don't close :))

### CODE REVIEW

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
comment

**Comment by mkonicek** [comment]
hi

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot shipit

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot import

**Comment by mkonicek-tester** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
