### PR TITLE
[KeyboardAvoidingView] Don't configure the next layout animation if the height hasn't changed

### PR DESCRIPTION
**Pull request by negativetwelve**
### Problem

Scenario: a view wrapped with a KeyboardAvoidingView that contains multiple TextInput components as children.

Right now, when you tap between the TextInputs, you queue up a bunch of LayoutAnimations that aren't executed because the state on the KeyboardAvoidingView does not update and thus does not change it's layout.

This means that any other action (such as navigating back on the Navigator) would receive this queued LayoutAnimation sometimes causing views to move in unexpected ways.
### Test plan (required)

Unfortunately, I can't send a video of the app we're building, but if necessary, I can put together a small example to show the issue.

Make sure tests pass on both Travis and Circle CI.
### Code formatting

I made a few small style changes to be consistent with the rest of the codebase:
1. remove spaces around destructuring
2. variables with the same name as the key inside objects

### CODE REVIEW

**Comment by hramos** [comment]
This seems pretty straightforward. If you can provide a basic reproduction of the issue, that would help.

**Comment by negativetwelve** [comment]
@hramos okay, i'll try to put together an example

**Comment by maluramichael** [comment]
Is this the same thing i described in https://github.com/facebook/react-native/issues/10765#issuecomment-259109962

**Comment by negativetwelve** [comment]
@maluramichael I don't think so, in your case, setState should set the bottom to 0 which should cause the onLayout to be called. In my understanding, LayoutAnimation only adds a layer on top of an existing transition (basically hooks into the state change), but doesn't actually affect the state change itself. The value for setState will still change no matter if there's a LayoutAnimation or not.

**Comment by lacker** [comment]
I think we need a better way to test this other than just ensuring that existing unit tests work. Could you add a new test that specifically catches this behavior?

**Comment by jgkim** [comment]
Also, we don't need to configure the next `LayoutAnimation` if `behavior` prop is not defined.

**Comment by lacker** [comment]
It seems like this pull request has gone stale so I am going to close it. Please feel free to reopen if you are still interested in working on it!

**Comment by AlimovSV** [comment]
I believe this PR should be reopened. @negativetwelve is right with his fix. Without the fix we often get an unexpected layout animation for views inside the KeyboardAvoidingView.

**Pull request closed without merging**
