### PR TITLE
Fixes Buck file in trunk

### PR DESCRIPTION
**Pull request by bestander**
Test Plan:
- circle ci status

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @AndrewJack to be potential reviewers.

**Comment by bestander** [comment]
`buck fetch` passes, I'll shipit to unbreak tests

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/103951226701057/int_phab) to review.

**Pull request closed without merging**
