### PR TITLE
Back out "fix(iOS): Replace uses of `CGColorRef` with UIColor to avoid manual memory management"

### PR DESCRIPTION
**Pull request by joevilches**
Summary:
Original commit changeset: 5e85e17567e3

Original Phabricator Diff: D63989547

This is causing some crashes internally

Changelog: [Internal]

Differential Revision: D64194385

### CODE REVIEW

**Comment by joevilches** [comment]
cc @Saadnajmi this was causing some problems internally. Not your code, I had to change some things that called `RCTCreateCGColorRefFromSharedColor` internally and that was the source of the issue. I will look into fixing that and bring this back afterwards

**Comment by Saadnajmi** [comment]
> cc @Saadnajmi this was causing some problems internally. Not your code, I had to change some things that called `RCTCreateCGColorRefFromSharedColor` internally and that was the source of the issue. I will look into fixing that and bring this back afterwards

I see, in the future, I guess I can separate removing `RCTCreateCGColorRefFromSharedColor()` to a different PR to try and limit issues like that?

**Comment by joevilches** [comment]
Yeah that would at least make it so that you are not blocked. We could try doing that now if you don't want to be held up. There was only one location where this happened, but it is not immediately obvious to me how to reorganize it to avoid said problem

**Comment by Saadnajmi** [comment]
> Yeah that would at least make it so that you are not blocked. We could try doing that now if you don't want to be held up. There was only one location where this happened, but it is not immediately obvious to me how to reorganize it to avoid said problem

I would appreciate just bringing back the one method and not backing out the change if possible :D

**Comment by joevilches** [comment]
That's a good idea! This issue is currently blocking some build infra and we are a few hours into landing, so I am gonna just wait for that. But I can bring it back while leaving that method in place for you. Should be easy enough

**Pull request closed without merging**
