### PR TITLE
Map follow user location

### LINKED ISSUE #3105: [MapView] showsUserLocation without automatic zooming?
I would like to show the user's current location on a map, but the automatic zooming that comes along with it leads to a rather hectic user experience for my particular use case.  

Would it be possible to allow showing of the user location without also forcing the map to zoom in on that location?  

```
    // If it needs to show user location, force map view centered
    // on user's current location on user location updates
    _followUserLocation = showsUserLocation;
```

Commenting out this last line in RCTMap.m seems to do what I want.  

Could such a thing be wrapped in an additional configuration option?  Perhaps something like showsUserLocationZoom={false}?  

If that sounds amenable I could try work on a PR (unless someone more familiar with Objective C has a few min to tackle it).  

Thanks!!

### PR DESCRIPTION
**Pull request by Crash--**
Fix #3105

It's the same PR as #3119 but as I force-pushed in my branch, I can't reopen the PR. I added an example. 
capture d ecran 2016-01-05 a 07 15 37

### CODE REVIEW

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
Actually, as I look at this, isn't there a potential bug here?

Isn't the fact that this works just luck that the method properties are iterated in an order that puts `followUserLocation` after `showsUserLocation`. See this line:

https://github.com/facebook/react-native/blob/master/React/Views/RCTMap.m#L106

If for some reason the properties on the RCTMapManager class were iterated through in a different order (putting `followUserLocation`) before `showsUserLocation`...the prop would be overridden by the `showsUserLocation` setter.

I think a better implementation is to put a setter for followUserLocation in RCTMap so that it's a bit more bulletproof. Thoughts @nicklockwood ?

**Comment by nicklockwood** [comment]
@skevy, yeah I came to the same conclusion. I made a few changes internally.

**Comment by skevy** [comment]
@nicklockwood awesome! you rock.

**Comment by Crash--** [comment]
Thanks for the change!

**Comment by nicklockwood** [comment]
@Crash no worries - I thought it made a bit more sense this way.

**Pull request closed without merging**
