### PR TITLE
Update Object.assign non-object error message

### PR DESCRIPTION
**Pull request by spicyj**
These are the sources, not the target. Copy pasta from above.

### CODE REVIEW

**Comment by spicyj** [comment]
@amasad This error message seems obviously wrong but I'm confused why we need to error out at all. Won't primitives have no own props?

**Comment by amasad** [comment]
I don't remember writing this. I think we copied it from www. Check the blame there. Might've been @sebmarkbage

**Comment by sebmarkbage** [comment]
I don't think leaving them out would be spec behavior IIRC but this particular check was added to prevent deopts of the function when someone wrecklessly uses a primitive. This was observed on www.

**Comment by sebmarkbage** [comment]
This really should be a warning though. Catching this shouldn't silence it. It is not ok to use at all.

**Comment by sebmarkbage** [comment]
lgtm

**Comment by spicyj** [comment]
I didn't update anything. >_>

**Comment by spicyj** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
