### PR TITLE
fix examaple TabBarIOSExample bug; show click num when user click second & third tabbar

### PR DESCRIPTION
**Pull request by vczero**

### CODE REVIEW

**Comment by sahrens** [comment]
This seems reasonable, but can you rebase and make sure tests are passing?

**Comment by sahrens** [comment]
@facebook-github-bot import

**Comment by sahrens** [comment]
Can you rebase and re-record the snapshot tests to get the travis build to pass?

**Comment by vczero** [comment]
@sahrens Can you rebase and re-record the snapshot tests to get the travis build to pass?－－this is for @facebook-github-bot? if not be, how can I do? Thank you ~

**Comment by sahrens** [comment]
The bot can't help here - you need to re-record for any change that will affect the snapshot tests.  Follow the instructions in the docs here, update your PR, and make sure your Travis build passes and then we'll merge it in:

https://github.com/facebook/react-native/blob/master/docs/Testing.md#running-tests-and-contributing

**Pull request closed without merging**
