### PR TITLE
Update showcase.js

### PR DESCRIPTION
**Pull request by alexHlebnikov**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @brentvatne to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hramos** [comment]
Hey @alexHlebnikov, we are changing the way the showcase works so that everything now has a link to some external content, like press coverage by a well-known publisher, or a deep technical blog post detailing the development process using React Native. Unfortunately it does not seem like this application meets these requirements at this time.

**Comment by alexHlebnikov** [comment]
Hi @hramos! 

Can you tell me more details which requirements were doesn't met? 
Because Sib.fm is a well known in Siberia internet media.
Also, the app is branded with a public company brand - [2GIS] (http://info.2gis.com/index_en.html).

Why these two conditions are not enough?

**Comment by lacker** [comment]
Well, the link should just be useful for the average reader of the website. Usually that means, there's some reason it would get clicked on, and then there's some useful content at the link. In particular it probably has to be in English to be useful to the readers of the website - the language is vast majority English, a little bit Chinese, and then a huge dropoff to #3. Even the Chinese apps we are including here have English-language links. The only stuff I can find looks Russian, so, it just doesn't seem like it would be something we can get people to click on.

**Comment by alexHlebnikov** [comment]
Thank you for answer, @lacker.

**Pull request closed without merging**
