### PR TITLE
Update Xcode projects

### PR DESCRIPTION
**Pull request by pvinis**
A few people have been complaining, including me, that when we compile a react native project, there are a lot of warnings from xcode, suggesting to update the project build settings to the new recommendations.

I took the liberty to actually update the xcode projects, so we can finally have these gone, as well as replace some deprecated methods with the new suggested ones.

## Test Plan

I made two react native projects, one with the regular react native and the other one using this branch.
Left is before, right is after:
screen shot 2018-06-05 at 15 44 34

## Release Notes

[IOS] [MINOR] [Xcode] - updated the Xcode projects with the latest suggestions from Xcode 9.3, and replaced a few deprecated methods of iOS with their new replacements.

### CODE REVIEW

**Comment by hramos** [comment]
I'd accept this PR if it was limited to upgrading the project to recommended settings. Can you split out the method removals / replacements to a separate PR?

**Comment by pvinis** [comment]
alright. i will separate it. thanks.

**Comment by hramos** [comment]
We recently merged a PR that fixed a bunch of these warnings, by the way.

**Comment by pvinis** [comment]
i saw, ill make sure to go from master, to see if i have some more stuff here.

**Comment by pvinis** [comment]
@hramos done. only xcode recommendations here. ill make the rest into different prs. thanks again.

**Comment by hramos** [comment]
I'm reverting this as end to end tests are now broken. Let's work on a fix so we can land these changes successfully again.

**Comment by pvinis** [comment]
the erros are because of some method implementations that are broken on master. i had this fixed on the original pr.

i think the best way forward it if i make a new pr with the method fixes for this. then after merging that one, we can merge this too. sounds good?

**Comment by pvinis** [comment]
pushed #19790, which has the fixes i had for e2e. the tests passed so i guess we could merge that one first. then this one, along with the 2-3 more i made, should be fine on merge.

**Comment by pvinis** [comment]
ill rebase right after #19574 lands on master.

**Comment by pvinis** [comment]
rebased this to master. lets see if tests are happy now.

**Comment by hramos** [comment]
Thanks @pvinis!

**Pull request closed without merging**
