### PR TITLE
Merge `rnpm config` with the `cli config`, step 1

### PR DESCRIPTION
**Pull request by grabbou**
This is step one on merging the `rnpm` config with the `cli config`. The plan is to remove two sources of truth (rnpm package.json config and rn-cli Javascript config)

Rationale:
As of now, we have `rnpm` config, that used to live in the `local-cli/core/config/index.js` and the `rn-cli` config, living in `default.config.js` and `utils/Config.js`. 

This PR moves all the things into one file, called `local-cli/core', simplifies things, enhances types (Config now has better types, added missing properties and fixed descriptions).

One notable addition is that users can now opt-in to override the commands that are loaded at the package level. Previously it was only possible to add a command by writing a plugin. Now, you can just tweak the `rn-cli.config.js`.

This is one of the several improvements I have on my roadmap, with better documentation for the CLI as well.

### CODE REVIEW

**Comment by grabbou** [comment]
CC: @bestander @mkonicek @brentvatne @jesseruder

**Comment by mkonicek** [comment]
> As of now, we have rnpm config, that used to live in the local-cli/core/config/index.js and the rn-cli config, living in default.config.js and utils/Config.js.

I've never touched these configs I think. Who would normally modify these configs? Do people modify them when building React Native apps? If so, how? Would they edit `MyApp/node_modules/local_cli/core/rn-cli.config.js`?

> Previously it was only possible to add a command by writing a plugin. Now, you can just tweak the rn-cli.config.js.

Tweak how? Could you add a code example showing how someone would want to tweak it and why?

**Comment by GantMan** [comment]
Excellent PR!  This is definitely a step in the right direction!  I can already see the benefit!

@mkonicek - you would simply place your own `rn-cli.config.js` in your root of your project.  As an agreed way to properly override for specifics in projects that have those needs.

**Comment by grabbou** [comment]
> I've never touched these configs I think. Who would normally modify these configs? Do people modify them when building React Native apps? If so, how?

You create `rn-cli.conifig.js` file in the root folder of your project. You can then, override some of the default options for the `cli` instead of passing them via flags to each command separately. That is the feature it's been there all the time. This PR adds the `rnpm` specific configuration to that file because we never managed to do it before. 

> Tweak how?

The docs are pending work and currently none of the options are described. One can see the flow type located in the `local-cli/core/index.js` that tells us that the function returns an array of commands (Command is also a type). Better docs are coming when we sort out how to and where to describe it.

**Comment by grabbou** [comment]
Travis failure seems unrelated. Restarted.

**Comment by grabbou** [comment]
I got approval from @brentvatne yesterday but we haven't merged it because of the tests failure that occurred.

Now, that it's been fixed, I think it's ready for shipping.

**Comment by grabbou** [comment]
Tests will be fixed by https://github.com/facebook/react-native/pull/11582

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Comment by grabbou** [comment]
Tests failing because of new commands that were added to the master. I'll fix them in the morning and hopefully we can land it.

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Comment by grabbou** [comment]
Force shipping after @brentvatne, this time rebased.

**Comment by bestander** [comment]
@grabbou, one test failed in Java but it seems like a flaky test, I restarted it to confirm.
However this PR needs to be rebased on master.

**Comment by bestander** [comment]
Yeah, just rebase and try again

**Comment by grabbou** [comment]
Rebased. Tests passing locally so I'll just ship. Hopefully it goes through this time.

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Comment by grabbou** [comment]
Keeping fingers crossed it finally lands! 🚀 There's so much thing yet to be done there :)

**Comment by grabbou** [comment]
Same tests are failing on master. This happens to this PR after rebase.

**Comment by bestander** [comment]
This test failed:

com.facebook.react.TextRenderingTestCase#testFontWeight
java.lang.NullPointerException

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
I'll retry because there was a break in trunk this weekend

**Comment by bestander** [comment]
I think here it is.
We had some internal packager wrappers refering to ConfigT.
``` 
Flow errors detected in root "Libraries/FBReactKit/js"!
=====Flow error #0====
Libraries/FBReactKit/js/cli-utils/packager-worker-for-buck/src/assemble-library.js line 28 col 14-20: Named import from module `../../../react-native-github/local-cli/util/Config.js`
This module has no named export called `ConfigT`.
```

I can't fix it now, working from home today and only on OSS

**Comment by bestander** [comment]
@grabbou, the quickest way to land this would be by reexporting ConfigT via the util/Config.js

**Comment by grabbou** [comment]
@bestander ConfigT is no longer there, it has changed location, now it's in `local-cli/config`. Is it possible you update internal paths? I can't do anything about it, and the change is just kinda required.

**Comment by grabbou** [comment]
PS. Thanks for helping me to land the other commit!

**Comment by bestander** [comment]
Sure, will do when I am in the office.
I just thought of a hack in local-cli/config
```
export ConfigT from '/path/to/new/location';
```
that you could try today to unblock.

**Comment by grabbou** [comment]
A, makes sense! I'll try to re-export then and ship once again, if it lands before, you can then fix it :) Thanks!

**Comment by grabbou** [comment]
Okay, added temporary fixed. Let's try once again.

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Pull request closed without merging**
