### PR TITLE
[PickerIOS] Add multiple component support

### PR DESCRIPTION
**Pull request by VojtechBartos**
Hey guys,
the issue is that current `PickerIOS` component doesn't support having multiple components and rendering everything to single one. Multiple components means that inside one picker you can have multiple "sub" pickers (Take a look on attached screenshots below). 

screen shot 2016-10-29 at 18 56 43

vs 

screen shot 2016-10-29 at 18 54 35

This PR adding support to `PickerIOS` component and slightly changing component API.

- added child component `PickerIOS.Component` and the already existing component `PickerIOS.Item` should be child of the new `PickerIOS.Component`
- removed property `selectedValue` from `PickerIOS` and moved it to `PickerIOS.Component`
- `PickerIOS` property `onChangeValue` receiving instead of `(newValue, newIndex)` one additional argument `component`, describing index of the component. So `(component, newValue, newIndex)`

**Test plan**

- `Picker`
  - make sure everything works correctly as before, because of changing API of the `PickerIOS` i have to slightly tweak `Picker` to support just 1 component
- `PickerIOS`
  -  Test in UI explorer the PickerIOS works correctly (including new example with multiple components)
  - `onValueChange` should be receiving new first extra argument `component`, describing component index
  - changing `PickerIOS.Component` `selectedValue` should be changing selected value in specific picker component

### CODE REVIEW

**Comment by VojtechBartos** [comment]
@spicyj @javache ping :)

**Comment by lacker** [comment]
I'm concerned about the "slightly changing the component API" part. One of our missions right now with React Native is to reduce breaking changes and so even a fundamental improvement of this component seems like it is not necessarily a net improvement in developer experience if this is going to break peoples' apps. Maybe it would be a better idea to have a separately named component like a MultiPickerIOS? You could distribute it separately with `react-native link` for example.

**Comment by VojtechBartos** [comment]
@lacker ahh got it, but it would be nice the PickerIOS would support it natively. Would it help if i would re-implement it in way that old API would be still supported so it wouldn't break people's apps or it would bring more confusion? If not, nothing happens, close the PR, i have already implemented it in our app so it's not blocker for me. If i will find a free time maybe i will publish it separately.

**Comment by lacker** [comment]
I think the best way forward here is to release this as a separate library, since it's a decent amount of code on top of the existing PickerIOS behavior. So I am going to encourage that approach, and close this pull request. Thanks!

**Pull request closed without merging**
