### PR TITLE
Add @Expensify to React Native incubating partners list

### PR DESCRIPTION
**Pull request by AndrewGable**
## Summary:

Adding @Expensify to the React Native incubating partners list

## Changelog:

[Internal] - Adding @Expensify to the React Native incubating partners list

## Test Plan:

N/A - Just documentation update

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
### Hi @AndrewGable, 👋

### Congratulations 🎉 on your **_"First Pull Request"_** to [React Native](https://github.com/facebook/react-native)! 🥳

Thank you, 🙏 for taking the time to contribute to this project and share your ideas.

Someone from the team will review your PR and get back to you _as soon as possible_ with feedback if any. 😊 Post review, and if all tests are passing, your PR will be _imported_ to internal FB phabricator and should be merged if it also passes all internal tests. 🥳

<details>
<summary>P.S.: In the <i>meantime</i>, you should go through below checklist: <sup>(click to expand)</sup>
</summary>

1. Make sure you have _signed_ the [CLA](https://code.facebook.com/cla) 📃🙂,
2. There are _no_ typos 😄,
3. All tests 🧪 are _passing_. i.e. The CI checks should be green 🟢, and
4. You have _added_ necessary tests for your code, if it's a refactor or a new functionality. 🧪
 
</details>

---

<sup>

[Contributing Guidelines](https://reactnative.dev/contributing/overview) | [React Native Website](https://reactnative.dev/) | [Framework discussions, proposals and RFCs](https://github.com/react-native-community/discussions-and-proposals/discussions)

</sup>

**Comment by Andjeliko** [comment]
@AndrewGable makes absolute sense, Expensify is such an important partner in the React Native community!

**Review by lunaleaps — CHANGES_REQUESTED** [review]
Chatted offline with @AndrewGable about next steps. Will hold off until next partner's meeting.

**Review by rickhanlonii — APPROVED** [review]
Awesome, I'm super excited to add Expensify as a partner!

**Pull request closed without merging**
