### PR TITLE
Cherry-pick #9149 into 0.31-stable branch

### PR DESCRIPTION
**Pull request by hramos**
#9149 resolved an issue where Edit on GitHub links lead to a release branch, which results in pull requests being opened against a release branch instead of master. Many issues "resolved" in this manner have already been addressed in master.

This PR is intentionally against `0.31-stable` as it is cherry-picking changes already landed to master.

See prior discussion in #9222. This new PR uses the single squashed commit, and does so against 0.31-stable, which is now the latest release.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Awesome thanks. Merging.

**Comment by bestander** [comment]
You don't have to bump them.
Just add tag "latest" to the last commit of 0.31-stable branch and make CircleCI build it.
This does not have to cause an npm release.

**Comment by JoelMarcey** [comment]
@bestander I thought I knew how to bump something, but maybe I don't. This is what I did:

```
% git fetch
% git checkout -b 0.31-stable origin/0.31-stable
% git tag -d latest
% git tag latest
% git push origin :latest
% git push --tags
```

But I don't see the tag updated here nor CircleCI running.

What did I miss?

**Comment by bestander** [comment]
@JoelMarcey, I don't see this commit in 0.31-stable branch https://github.com/facebook/react-native/commits/0.31-stable.
You should push 0.31-stable explicitly.
`git push origin 0.31-stable --tags`

**Comment by JoelMarcey** [comment]
@bestander Ok. We talked offline about this. It was because we didn't run the instructions above within 1 hour of this cherry-picked commit landing in the stable branch. So you had to trigger the CircleCI build manually in that case.

In the future, I can just push a dummy commit to the stable branch and then run the tag instructions within an hour to get the CircleCI build going.

**Comment by JoelMarcey** [comment]
@hramos Your `Edit on GitHub` update should be available in the next hour or so.

**Pull request merged**
