### PR TITLE
Android: Fix native animation crash

### LINKED ISSUE #9887: animation fails when running the same animation multiple times (useNativeDriver)
I'm animating this component at the moment of creation:

``` typescript
import * as React from 'react'
import { Animated, StyleSheet, Text } from 'react-native'

interface InnerProps {
  damage: number
  pageX: number
  pageY: number
  id: any
}

interface InnerState {
  bounceValue: any
  translateValue: any
  fadeValue: any
  id: any
}

export default class Damage extends React.Component<InnerProps, InnerState> {

  constructor(props: InnerProps) {
    super(props)
    this.state = {
      bounceValue: new Animated.Value(1),
      translateValue: new Animated.Value(0),
      fadeValue: new Animated.Value(1),
      id: props.id,
    }
  }

  public componentDidMount() {
    Animated.parallel([
      Animated.timing(this.state.translateValue, {
        toValue: -200,
        duration: 1000,
        useNativeDriver: true,
      }),
      Animated.spring(this.state.bounceValue, {
        toValue: 5,
        useNativeDriver: true,
      }),
      Animated.timing(this.state.fadeValue, {
        toValue: 0,
        duration: 900,
        useNativeDriver: true,
      }),
    ]).start()
  }

  public shouldComponentUpdate(props: InnerProps, state: InnerState) {
    return props.id !== state.id
  }

  public render() {
    return <Animated.Text
      style={{
        position: 'absolute',
        top: this.props.pageY,
        left: this.props.pageX,
        color: 'yellow',
        opacity: this.state.fadeValue,
        transform: [{translateY: this.state.translateValue},
        {scale: this.state.bounceValue}],
      }}
    >
      {this.props.damage}
    </Animated.Text>
  }
}
```

The problem is that, when i'm making a lot of animation for an amount of time (let's say 10 per second for about 8 seconds) it will throw an error:
screen shot 2016-09-13 at 12 53 40 pm
 ViewManager for tag `some tag` could not be found

this happens in this file:
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java

I think this is a bug, because when i remove 'useNativeDriver' this stops happening but of course the performance drops dramatically.

### PR DESCRIPTION
**Pull request by rigdern**
An exception is thrown when the native animation code attempts to play an animation on a view that hasn't been created yet. This can happen because views are created in batches. If this particular view didn't make it into a batch yet, the view won't exist and an exception will be thrown when attempting to start an animation on it.

This change eats the exception rather than crashing. The impact is that the app may drop one or more frames of the animation.

**Notes**

I'm not familiar enough with the Android native animation code to know whether or not this is a good fix. My team is using this change in our app because dropping animation frames is better than crashing the app. [This is the code](https://github.com/facebook/react-native/blob/c612c615449b8645976429ad1c0661a4f6e56115/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java#L874-L892) that is creating the views in batches. Hopefully my PR at least provides some insight into the cause of the bug.

This may fix #9887.

**Test plan (required)**

My team is using this change in our app.

Adam Comella
Microsoft Corp.

### CODE REVIEW

**Comment by janicduplessis** [comment]
@satya164 I think you mentioned you had this crash, could you test this diff see if it fixes it?

@rigdern Looks like we're not queuing the props update on the operation queue and instead applying it immediately which is probably the cause of the crash (https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L229). Could you try adding the operation to the queue and see if the crash still happens? Something like `mUIViewOperationQueue.enqueueUpdateProperties` should work there. The only concern here is that we want to prioritize updating the view over other operations so we're not missing frames, an alternative solution would be to try updating it immediately and fallback to queueing the update if there is an exception.

**Comment by janicduplessis** [comment]
cc @kmagiera

**Comment by satya164** [comment]
@janicduplessis Great! Will test this tomorrow and let you know.

**Comment by rigdern** [comment]
@janicduplessis The view update is currently being done through `synchronouslyUpdateViewOnUIThread`. Moving completely away from `synchronouslyUpdateViewOnUIThread` here seems suspicious because it appears that `synchronouslyUpdateViewOnUIThread` was introduced just for this use case in https://github.com/facebook/react-native/commit/65ccdffc8d948073e03fd792ec080f8a9a7cc93a#diff-ed80d5990dea7c0f1947e73bb23569dd. @kmagiera did that commit so perhaps he has an opinion on the right fix for this issue.

I suppose we could use `enqueueUpdateProperties` if `synchronouslyUpdateViewOnUIThread` will fail because the view doesn't yet exist.

**Comment by ryangomba** [comment]
Unsure of the behavior on Android, but on iOS we needed to make sure that NativeAnimatedModule was receiving calls on the same thread as UIManager, otherwise we'd see this race as well.

**Comment by rigdern** [comment]
@ryangomba Thanks for the suggestion but I think the Android bug has a different cause. As you can see [by this assert](https://github.com/facebook/react-native/blob/9fc6204efce96877c7e6e3de0ff73520e4a0f5ea/ReactAndroid/src/main/java/com/facebook/react/animated/NativeAnimatedNodesManager.java#L355), the code this PR changes is already running on the UI thread.

The cause of the bug is that `createView` calls and other view operations are generally put into a queue and processed in batches whereas animation manipulations skip the queue and are done synchronously. The crash occurs when an animation manipulation runs before the `createView` call for that view has been popped from the queue and executed.

**Comment by ryangomba** [comment]
So, if I understand correctly:

We're sending messages over the bridge, some to UIManagerModule (createView) and some to NativeAnimationsModule (connectAnimatedNodeToView). On onBatchComplete, both modules are going to try to flush their operation queue. If NativeAnimationsModule beats UIManagerModule to the punch, we might have a problem. So we need to find a way to ensure the proper ordering, i.e. UIManagerModule always commits before NativeAnimationsModule.

Does this sound correct?

**Comment by rigdern** [comment]
@ryangomba Your description missed an important detail. Even if the UIManagerModule gets to process its operations before NativeAnimationsModule, the bug would still exist. This is because the UIManagerModule [does its work in batches of 8 ms](https://github.com/facebook/react-native/blob/c612c615449b8645976429ad1c0661a4f6e56115/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java#L874-L892). So the UIManagerModule might not get to the `createView` call in that frame and then when the NativeAnimatedModule runs its operations, it'll still blow up because the view it's attempting to operate on doesn't exist.

**Comment by janicduplessis** [comment]
I think the issue is that android has some code split view creations over multiple frames which iOS probably don't and creates every view in one batch. [This code](https://github.com/facebook/react-native/blob/c612c615449b8645976429ad1c0661a4f6e56115/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java#L874-L892) should make it clearer. If I understand correctly what happens is:

View creation operations -> frame time elapsed -> pause view creation -> process `connectAnimatedNodeToView` -> view doesn't exist yet because creation was paused

**Comment by janicduplessis** [comment]
@rigdern I think using `enqueueUpdateProperties` if `synchronouslyUpdateViewOnUIThread` might be the best / safer option, I'd rather not skip updating values to avoid cases where a view won't be created with the proper initial value and not updated until the next animation is run. There might be a possible race between the update from `enqueueUpdateProperties` and the next `synchronouslyUpdateViewOnUIThread` but I doubt it will be a real issue in practice, less so than skipping an update.

**Comment by rigdern** [comment]
@janicduplessis I thought more about this issue and I'm thinking we should stick with the fix I originally submitted. Let's look at the edge cases that each solution misses.

#### Solution 1: No-op when view doesn't exist yet

This is the solution currently implemented by this PR. Animation states attempted to be applied before the view is created are dropped. In the worst case, the animation will finish before the view is created and the UI will not be updated to reflect the final animation state.

#### Solution 2: Fallback to `enqueueUpdateProperties` when view doesn't exist yet

Animation states attempted to be applied before the view is created are added to the UI operation queue. These animation states will likely not be seen because when they are applied, they will immediately be overwritten by the current animation state which is calling `synchronouslyUpdateViewOnUIThread`. This is because AnimationDriver runs its operations after the UIManager.

Here's an edge case this implementation misses. Suppose a couple of animation states come in before the view is created so they are added to the UI operation queue. Now suppose the animation completes before those animation operations are popped off of the UI queue. When they are popped off of the queue, the view's state would be reverted to an earlier state of the animation. Consequently, the final state of the view would be some early frame of the animation.

#### Conclusion

I'm in favor of Solution (1) because I think its implementation is simpler, its buggy edge case is less likely to be hit, and the impact of its buggy edge case is slightly less severe.

A proper fix would probably be along the lines of not starting the animation until the view is created. I get the sense that would be quite a bit more involved than the current PR. I don't have much experience with the native animation implementation so if somebody familiar with the native animation implementation wants to look into a proper fix, I'd be happy to hand off my PR.

**Comment by janicduplessis** [comment]
Thinking about it more I'll test always using `enqueueUpdateProperties` to see if the animations still run fine and are not a frame behind. There might be some cases where animations might drop a frame because there is a big batch of UIOperations queued up before and it doesn't get executed in the frame time budget but I think I'd rather have this than some possible inconsistencies due to race conditions.

**Comment by janicduplessis** [comment]
Posted a PR for what I suggested, after testing this solution seemed to work really well. #10980

I'm pretty confident that it will fix the crash if our understanding of why it happens is right.

**Comment by astreet** [comment]
It'd be nice if we made animations pending until the associated view were created, and then we hook up the animation at that point. Hooking up the animation would also forward the animation to whatever point its supposed to be at so that we don't have weird jumpiness. What do you think?

**Comment by janicduplessis** [comment]
Any suggestion on how to implement this? I was thinking we could add some sort of ViewCreationListener on `UIViewOperationQueue` that would get called when the view is actually created. We'd have something like Map<viewTag, List<listener>> and in CreateViewOperation#execute we could call the proper listeners. This would allow to check if the view is already created and update it or add a listener to update it when created.

**Comment by astreet** [comment]
The listener pattern sounds fine, I'd just try to make sure we remove the listener when it's not needed. Implementation-wise, I'd rather just expose `onViewCreated(int viewTag, View nativeView)` instead of registering listeners per view tag.

**Comment by rigdern** [comment]
@janicduplessis Thanks for trying out that alternative fix in #10980. Are you planning on exploring a fix based on Andy's suggestion of applying the animation only after the view has been created?

**Comment by janicduplessis** [comment]
@rigdern Yes, I'll try that solution soon.

**Comment by janicduplessis** [comment]
Not sure when I'll have time to work on the fix we discussed so I'm fine with landing this for now since it's way better to ignore the update than crash in this case.

**Comment by lacker** [comment]
@facebook-github-bot go home you're drunk

OK let me rebase & make sure it passes CI and then I will land it.

**Comment by lacker** [comment]
@rigdern the build failures look legit here - https://circleci.com/gh/facebook/react-native/14156?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link -

/home/ubuntu/react-native/ReactAndroid/src/main/java/com/facebook/react/animated/NativeAnimatedNodesManager.java:15: error: package com.facebook.common.logging does not exist
import com.facebook.common.logging.FLog;
                                  ^
/home/ubuntu/react-native/ReactAndroid/src/main/java/com/facebook/react/animated/NativeAnimatedNodesManager.java:23: error: package com.facebook.react.common does not exist
import com.facebook.react.common.ReactConstants;
                                ^
Errors: 2. Warnings: 0.

Rule //ReactAndroid/src/main/java/com/facebook/react/animated:animated has failed to build.
com.facebook.common.logging
com.facebook.common.logging.FLog
com.facebook.react.common
com.facebook.react.common.ReactConstants
Try adding the following deps:
//ReactAndroid/src/main/java/com/facebook/react/common:common

**Comment by rigdern** [comment]
@lacker Thanks, I fixed the build failure and Travis + Circle have now finished successfully.

**Pull request closed without merging**
