### PR TITLE
Update ws dependency

### LINKED ISSUE #7643: Update *ws* dependency
Looks like the current version of [**ws**](http://npm.im/ws) has a vulnerability:

```sh
$ nsp check
(+) 1 vulnerabilities found
```

|    | Remote Memory Disclosure    
|----|:----|
| Name | ws
| Installed | 0.8.1
| Vulnerable | <= 1.0.0
| Patched | >= 1.0.1
| Path | Magnet@0.0.1 > react-native@0.25.1 > ws@0.8.1
| More Info| https://nodesecurity.io/advisories/67

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #7643

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @davidaurelio to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ide** [comment]
Did you test this? Please include your test plan in your commit message.

**Comment by pdehaan** [comment]
> Did you test this?

Nope. Just bumped the version number in package.json via GitHub site and submitted.

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by davidaurelio** [comment]
@facebook-github-bot import

**Comment by davidaurelio** [comment]
Let’s have a look how this works out

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @cpojer as a potential reviewer. Could you take a look please or cc someone with more context?

**Pull request closed without merging**
