### PR TITLE
[Android] Update OkHttp to 3.14.9 to improve security

### PR DESCRIPTION
**Pull request by WookieFPV**
## Summary

Okhttp 3.12.X allows Connections using TLS 1.0 and TLS1.1.
TLS 1.0 and TLS 1.1 are no longer secure.
Google, Mozilla, Microsoft, and Apple announced that their browsers will require TLSv1.2 or better starting in early 2020.

https://square.github.io/okhttp/changelog_3x/#version-310
https://github.com/facebook/react-native/wiki/Changelog

Starting from 3.13.0 TLSv1 and TLSv1.1 are no longer enabled by default.
3.13.0 requires JAVA 8 and Android SDK 21 (which was blocking the Upgrade in the Past).

## Changelog

[Android] [Changed] - Update Okhttp to version 3.14.19

## Test Plan

Current tests should pass.
Connections using TLS 1.0 and TLS 1.1 should not be possible.

### CODE REVIEW

**Comment by dulmandakh** [comment]
@WookieFPV could you please rebase so that Android CI works as expected.

**Comment by WookieFPV** [comment]
@dulmandakh thank you, the android CI now works as expected.

**Comment by dulmandakh** [comment]
Please, remember to bump okio as well.

**Comment by WookieFPV** [comment]
The latest okio Version 1.X is already used.
Okhttp 3.13.0+ requires okio Version 1.17.3 or later and RN uses 1.17.5 (https://square.github.io/okhttp/changelog_3x/#version-3130).

This should be fine in my optionion.
I don't feel comfortable doing a major upgrade on okio, I mostly do RN and very few native android development.

**Review by dulmandakh — APPROVED** [review]

**Comment by dulmandakh** [comment]
@fkgozali I would propose merge this PR, because bumping okhttp to 4.x would add Kotlin as  a dependency, also some APIs changed thus tests are failing.

**Pull request closed without merging**
