### PR TITLE
Core Components Tutorial to ES6

### PR DESCRIPTION
**Pull request by Ehesp**
Converts the ListView tutorial to ES6. Not sure if there is any specific linting guidelines for this?

Related to documentation ListView lockdown: https://github.com/facebook/react-native/issues/8184

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @stevemao to be potential reviewers.

**Comment by janicduplessis** [comment]
Hey, thanks for the PR! Can you close this one and open a new one on master instead of 0.27-stable branch.

**Comment by satya164** [comment]
cc @mkonicek seems more people are sending PR's to release branches. In last 1-2 weeks, I've probably seen 4.

**Comment by janicduplessis** [comment]
@satya164 True, maybe we can add a note in CONTRIBUTING.md

**Comment by satya164** [comment]
@janicduplessis I was thinking the bot could reply to these.

**Comment by mkonicek** [comment]
cc @JoelMarcey, I believe we want to move the docs to ES6.

**Comment by mkonicek** [comment]
@Ehesp can you please update this PR to be for the master branch?

**Comment by JoelMarcey** [comment]
@mkonicek 

>  I believe we want to move the docs to ES6.

Yeah, we do. In fact, moving this exact example to ES6 was going to be part of our lockdown next week. So this is great. 

Once this get put on master, we can review and land it, I think.

**Comment by ZakariaRidouh** [comment]
@JoelMarcey I've also been thinking about moving all the demos to ES6 and if you guys are interested in going on with it, I can submit a PR 😄

**Comment by Ehesp** [comment]
Ah yes sorry - will sort in a few hours.

**Comment by Ehesp** [comment]
Re-submitted - see above.

Also there is a note for the master branch on this commit (https://github.com/facebook/react-native/pull/8209/commits/420be9e7393e7fa0008b035b3456723cfb121a3d) - was just being stupid sorry!

**Comment by stevemao** [comment]
> I was thinking the bot could reply to these.

I like this idea. We should be able to do something like `shipit master` and the bot can cherry-pick the change to master if there's no conflict.

**Comment by JoelMarcey** [comment]
@ZakariaRidouh 

> @JoelMarcey I've also been thinking about moving all the demos to ES6 and if you guys are interested in going on with it, I can submit a PR 😄

We would definitely be interested in a PR, I think. What do you think @mkonicek @caabernathy @lacker @bestander ??

**Comment by bestander** [comment]
Sure thing!

**Pull request closed without merging**
