### PR TITLE
[Docs] Wrong function name

### PR DESCRIPTION
**Pull request by jasonals**
RippleAndroid is actually Ripple

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks! I'm now working on a system to import Pull requests to the internal Facebook repo :)

**Comment by mkonicek** [comment]
Can you sign the CLA if you haven't already? https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by mkonicek** [comment]
Can you sign the CLA if you haven't already?
https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by vjeux** [comment]
@mkonicek there was an issue with the bot, he already signed the CLA

**Comment by jasonals** [comment]
Yup, says I signed it.

**Comment by mkonicek** [comment]
OK cool! I'm now working on a tool to import PRs into the Facebook Android codebase :)

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
