### PR TITLE
Fixing tests for npm 2/3

### PR DESCRIPTION
**Pull request by skevy**
Supersedes #6343.

Note...this is just updating some Jest/node-haste configuration and the Shrinkwrap. The shrinkwrap update is what is key here.

Do not merge until CI passes :)

cc @mkonicek @bestander

### CODE REVIEW

**Comment by skevy** [comment]
:ship: :ship: :ship:

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Failed internal tests, will continue merging this with David tomorrow.

    uncaught error Error: UnableToResolveError: Unable to resolve module ReactChildren from /data/.../react-native-github/Libraries/ReactNative/ReactNative.js: Unable to find this module in its module map or any of the node_modules directories under /data/node_modules/ReactChildren and its parent directories
    This might be related to https://github.com/facebook/react-native/issues/4968
    To resolve try the following:
      1. Clear watchman watches: `watchman watch-del-all`.
      2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
      3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
        at /data/.../react-native-github/node_modules/node-haste/lib/DependencyGraph/ResolutionRequest.js:413:17
        at run (/data/.../react-native-github/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:84:47)
        at /data/.../react-native-github/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:95:28
        at flush (/data/.../react-native-github/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:19:5)
        at nextTickCallbackWith0Args (node.js:419:9)
        at process._tickCallback (node.js:348:13)
    See logs /var/folders/4d/rqpj5cz94s557zqwa4csc4_m000xbj/T/react-packager.log
        at SocketClient._handleMessage (SocketClient.js:144:23)
        at BunserBuf.<anonymous> (SocketClient.js:53:42)
        at emitOne (events.js:77:13)
        at BunserBuf.emit (events.js:169:7)
        at BunserBuf.process (/data/.../react-native-github/node_modules/bser/index.js:289:10)
        at /data/.../react-native-github/node_modules/bser/index.js:244:12
        at nextTickCallbackWith0Args (node.js:419:9)
        at process._tickCallback (node.js:348:13)

**Comment by bestander** [comment]
Hey @skevy,

We are building the JS with BUCK and packager for internal apps and this error gets popped up:
```
uncaught error Error: UnableToResolveError: Unable to resolve module ReactDefaultPerf from /Users/bestander/fbsource/fbobjc/Libraries/FBReactKit/js/react-native-github/Libraries/Utilities/RCTRenderingPerf.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/ReactDefaultPerf and its parent directories
```

The folder ` /Users/node_modules/ReactDefaultPerf ` looks weird, something is wrong with the paths.
@davidaurelio is going to have a look at this but if you have an idea where it could originate from, throw it here.

Right now we can't merge this PR.

**Comment by bestander** [comment]
The problem is probably in packager being executed not from `react-native-github` context (the folder that gets synced to this repository root) but from 4 folders up the tree

**Comment by mkonicek** [comment]
Just talked about this a bit more with David, the root cause is the difference in the internal and open source setup:

- In open source React is a peer dependency of React Native
- Internally React is a dependency of React Native, we don't have the peer dependency. We run `npm shrinkwrap --dev` (which includes React because it's a dev dependency of RN) and the create a tarball from node_modules and use that internally. We don't run npm on CI servers etc.

**Comment by mkonicek** [comment]
Also, React is a dev dependency of React Native, we run `npm-shrinkwrap --dev` to create the shrinkwrap file and we now also publish it to npm.

This mean that anyone who runs `react-native init` gets two copies of React:
`node_modules/react-native/node_modules/react`, `node_modules/react` which is just wrong.

There's no easy way to change how the shrinkwrap generation works because we share that file both internally and in open source and the setup in each is very different.

We should stop publishing `npm-shrinkwrap.json` to npm, which means we'll only use that file internally as we have for the last year.

**Comment by davidaurelio** [comment]
I just realized that this cannot possibly work

The changes to node-haste make incorrect assumptions:

- the special haste-enabled folders live in *&lt;one-of-the-roots>/node_modules/&lt;name>* – that’s not the case for our internal setup, where stuff lives in *&lt;root>/a/b/node_modules/&lt;name>*
- react lives in the top level node_modules folder. That’s not the case for our internal setup. React lives in *&lt;react-native-folder>/node_modules/react*.

**Comment by mkonicek** [comment]
Thanks David, I'll close the PR.

@skevy you can reopen but don't see any way to merge this.

**Comment by mkonicek** [comment]
Should we revert some changes in node-haste?

**Comment by mkonicek** [comment]
Sorry it's probably not obvious at all how the internal setup works. I've only learned about it yesterday and today.

**Comment by mkonicek** [comment]
FYI I've removed shrinkwrap from what we publish to npm here: https://github.com/facebook/react-native/commit/10e990f415e3aabf49bde098956723c356948503

**Comment by janicduplessis** [comment]
It would be nice to publish a version of node-haste that has the Windows fix in it but not the haste module resolution changes to fix Windows support before the next release. Unless you think you can fix the bad assumptions so it work in your internal setup before that.

**Comment by davidaurelio** [comment]
Agreed. Let’s wait what @skevy thinks about is. I could publish node-haste 2.6.2 and remove the other 2.6.x releases

**Comment by cpojer** [comment]
Please let's just make sure we aren't breaking Jest again.

**Comment by skevy** [comment]
So, am I understanding right that we have to back out my changes to node-haste re `isNodeModulesDir`?

**Comment by skevy** [comment]
Ok yah, I guess we do. I still feel like we need to fix how that part of the packager works some how. Not sure if anyone has any ideas here.

**Comment by davidaurelio** [comment]
The best thing I can think of right now is not to use haste imports in react native at all, either by changing that directly in the source, or by rewriting it during `npm publish`

@cpojer that would be nice :-) I just checked, and jest still uses haste@^2.5.0. i.e. we should be good?

**Comment by cpojer** [comment]
@davidaurelio as long as we revert to whatever 2.5 did is fine. 2.6.0 breaks Jest pretty badly (and rn too I think).

**Comment by davidaurelio** [comment]
(y) I will be careful

**Pull request closed without merging**
