### PR TITLE
Updates from Wed 1 Jul

### PR DESCRIPTION
**Pull request by a2**

### CODE REVIEW

**Comment by ide** [comment]
Just a heads up that if the jest upgrade in https://github.com/a2/react-native/commit/555236865b6ddf47c39e2de1e7d53b0957bd0b2f lands we'll need to accelerate the migration to io.js (tracking in https://github.com/facebook/react-native/issues/1737).

**Comment by a2** [comment]
Part of #1819 and #1382 need to be landed internally so doing that now. Will then merge the rest into this PR. Thanks, @ide!

**Comment by ide** [comment]
@a2 I have some idea of what the js failure is... I can help look into it but it's easier for me to test against master. Do you want to go ahead and merge especially since tests are failing on master anyway?

**Comment by a2** [comment]
I didn't want to merge it yet but since it's a JS change, that's not really my area of expertise. I asked @amasad to look into it since it's getting late in London but if we can't figure it out tonight, I'll look into it more tomorrow.

**Comment by ide** [comment]
OK. 

I think the `packager/react-packager/src/JSTransformer/__tests__/Cache-test.js` failure might be fixed by adding `jest.runAllTicks();` at the end above the runAllImmediates call.

**Comment by amasad** [comment]
Why is `runAllTicks` changed to `runAllImmediates`? That seems to be what the breakage is

**Comment by ide** [comment]
Bluebird changes its scheduler to use setImmediate when running on Node 0.12 or newer: https://github.com/petkaantonov/bluebird/blob/634af0e27ff4faab62c6c5bfd105527abcf8b06e/src/schedule.js#L10. There's an update to .travis.yml to run iojs-v2 instead of Node 0.10, so the runAllImmediates call was added.

**Comment by amasad** [comment]
ah, but we stopped using bluebird. We're now using https://github.com/then/promise

**Comment by ide** [comment]
Then I think what's happening is that the `runAllTicks` call was always needed, and now with Promise it might be OK to drop the `runAllImmediates` call.

**Comment by a2** [comment]
The e2e tests are failing [on Travis](https://travis-ci.org/facebook/react-native/jobs/69266072) but I ran them locally and they passed. Going to merge this and we can figure out what's happening on Travis later.

**Comment by a2** [comment]
Okay so the builds are passing now but I didn't change anything. [WTF Travis.](https://travis-ci.org/facebook/react-native/builds/69271557)

**Comment by ide** [comment]
@a2, @amasad thanks for getting the tests to pass again =)

**Pull request merged**
