### PR TITLE
Fixes getDefaultProps warning

### PR DESCRIPTION
**Pull request by wadewegner**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

Resolves the "Warning: getDefaultProps was defined on MyScene, a plain JavaScript class."

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by hramos** [comment]
Can you open a PR against the master branch instead?

**Comment by wadewegner** [comment]
Sorry @hramos, not entirely sure I understand. I made an update to documentation. Why master?

**Comment by facebook-github-bot-9** [comment]
@wadewegner do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by hramos** [comment]
@wadewegner the doc site is built from master with every new release. If the fix is only made on a release branch, then the fix will not be reflected in the next release.

Once the fix is in master, if it's necessary we can cherry pick the commit into the current release branch to make sure the doc fix is visible before the next release is cut.

**Comment by lacker** [comment]
It looks like this is abandoned so I'm going to close this pull request. It would be nice to get rid of more warnings here though - if you are indeed still working on this then please feel free to reopen.

**Pull request closed without merging**
