### PR TITLE
FIX: Call all android back key handlers before invoking default

### PR DESCRIPTION
**Pull request by dltmd6262**
Fixes issue #9736

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @webzepter and @DanielMSchmidt to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by DanielMSchmidt** [comment]
Looks good to me and this seems to be the [intended behavior](http://facebook.github.io/react-native/releases/0.32/docs/backandroid.html#backandroid).

**Comment by webzepter** [comment]
@dltmd6262 Hello! `break` statement in https://github.com/facebook/react-native/commit/b8576312ca4a950d8bf4a5f4ec3a80c4f55d88b0 is a feature, not a bug 😅 .
Motivation: We use `BackAndroid` listeners to prevent closing screens with user's input.
When we have two screens in the stack (each screen with listener, which show alerts),
we want to show alert only from the last screen listener, not from all.

**Comment by dltmd6262** [comment]
I reversed the commit and added documentation based on commit b857631

**Comment by facebook-github-bot-7** [comment]
@dltmd6262 updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9757/files/9fd478f65f86f9d520ec0acddaa6ddf03b7f4a06..c300ce0b11d64153106e2bbe03afb9ee054dc98f)

**Comment by DanielMSchmidt** [comment]
@dltmd6262 @webzepter We should change the upper text, too. It states " exit the app if there are no listeners or if none of the listeners return true". The "none of the listeners" can be interpreted (like I did, e.g.) as everyone gets called.

**Comment by dltmd6262** [comment]
Well I actually think that part is true because the for loop calls all the handlers if they dont return true!

**Comment by dltmd6262** [comment]
So in the case of exiting the app everyone was called and no one returned true

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
Thanks for the review @DanielMSchmidt!
Looks good as per https://github.com/facebook/react-native/commit/b8576312ca4a950d8bf4a5f4ec3a80c4f55d88b0

@facebook-github-bot shipit

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
