### PR TITLE
Apple TV: TouchableOpacity and Button need hasTVPreferredFocus support

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
**Motivation**

Give `TouchableOpacity` and `Button` the same TV focus support as is already present in `TouchableHighlight`.

**Test plan**

Manual testing on TV simulator and devices.

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
@hramos could you please try importing this again?

**Comment by hramos** [comment]
Update, this failed internally with the following:

```
2 Flow errors detected!
=====Flow error #0====
/Libraries/Components/Button.js line 59 col 22-3: property `hasTVPreferredFocus`
Property not found in
react.js line 79 col 35-46: object type
=====Flow error #1====
/Libraries/Components/Button.js line 98 col 7-25: property `hasTVPreferredFocus`
Property not found in
/Libraries/Components/Button.js line 101 col 9-18: object type
```

**Comment by dlowder-salesforce** [comment]
Thanks @hramos , I just submitted what I think is the fix.  My environment is giving me a flow version mismatch and hundreds of flow errors, so it's hard to run those tests locally :)

**Comment by hramos** [comment]
Quick update: this is waiting on some internal snapshot tests we need to update, to account for the new prop. It's on my todo list.

**Comment by hramos** [comment]
This is hopefully landing tonight. Sorry for the delay.

**Pull request closed without merging**
