### PR TITLE
Maintain cursor position when TextInput value is changed programmatically

### PR DESCRIPTION
**Pull request by cava23**
This is useful for applying input masks in the onChange handler that you then need to propagate down to the native component. In our case, we add commas as the user enters a price. Without this change, the cursor will end up in the wrong place when the text is transformed in our onChange handler.

### CODE REVIEW

**Comment by cava23** [comment]
I signed the CLA on behalf of my company just before issuing this PR, so cava23 and seanj should be on record shortly.

**Comment by nicklockwood** [comment]
@cava23 can you rebase this against the latest version?

**Comment by cava23** [comment]
Is the Travis failure due to my change?

**Comment by nicklockwood** [comment]
@cava23 no, I don't think so.

**Comment by nicklockwood** [comment]
The Android behavior is to keep the distance of the cursor from the *end* of the text constant. I think that's basically equivalent to what you're doing here, but the logic would be much simpler - you'd simply take the text length beforehand, subtract the offset + length of the selection, and then after updating the text, set the cursor position to the new length - that offset.

What do you think?

**Comment by cava23** [comment]
Yeah, I like that idea. I'll give it a whirl.

**Comment by cava23** [comment]
@nicklockwood Would you agree that in the case of a non-empty text selection, the best action would be to not alter the selectedTextRange? It seems like the probability of incorrectly moving the cursor is pretty high.

**Comment by nicklockwood** [comment]
@cava23 I can't really imagine a situation where that would happen, except by accident due to latency.

Immediately after the user types or pastes text the range will be collapsed back to length: zero, and we should only really ever be changing the text at that point, because if the user hasn't just typed something, why are we correcting it?

**Comment by nicklockwood** [comment]
@cava23 yeah, I think this is fine.

**Comment by nicklockwood** [comment]
@facebook-github-bot shipit

**Comment by JakeRawr** [comment]
@nicklockwood @cava23  this is going to be in v0.17? 

Thank you for this!

**Comment by nicklockwood** [comment]
I'm not sure when the branch is/was cut for v0.17 - @mkonicek?

**Comment by chenxsan** [comment]
Just confronted this problem on react-native 0.22.

The cursor position is not placed right after the text instead of where the mask end was.

textinput-caret

**Pull request closed without merging**
