### PR TITLE
optimize image assets

### PR DESCRIPTION
**Pull request by GantMan**
Ran all images through optimizers to minimize file sizes with near lossless optimizations.  This will speed up the Github pages and any shallow depth git clones of this repo.

**REPORT:** - 5MB of unnecessary image cruft squeezed out of the assets.

JPG ran through `jpegoptim`
PNG ran through `pngout` and then `advpng`
GIF ran through `gifsicle`

Willing to do this for `react` repo as well if desired.

### CODE REVIEW

**Comment by ide** [comment]
Some of the images are used in tests for before/after snapshots. Can you make sure those ones are left unoptimized?

**Comment by GantMan** [comment]
Sure @ide - can you help me identify those?
Are they the `/ReferenceImages/IntegrationTests-IntegrationTestsApp` items?

Just let me know what folder(s) to revert.  
Also very interesting tests!  Any docs on those integration tests?  I'd love to learn more.

**Comment by GantMan** [comment]
@ide - Returned integration test images to their uncompressed status.

**Comment by hramos** [comment]
Diffs with large binary changes need to be manually imported. Let's see how it goes.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by GantMan** [comment]
hrmm, let me know what to fix if anything 👍 

Not a very important change, but beneficial.

**Comment by GantMan** [comment]
Not sure why CI is failing here.

**Comment by mkonicek** [comment]
@GantMan It used to be impossible to import binary files to the fb repo but that's been fixed now. You'll need to rebase though. Sorry about the churn.

**Comment by GantMan** [comment]
would it be terrible if I opened a new PR?  I could help so much faster that way.

**Comment by mkonicek** [comment]
Yes opening a new PR works just fine!

**Comment by mkonicek** [comment]
Sorry about the delay. Doing some open source oncall work and trying to going through pull requests that were accepted and got stuck.

**Pull request closed without merging**
