### PR TITLE
Add SCTV App to React Native showcase

### PR DESCRIPTION
**Pull request by InnerPeace080**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by mkonicek** [comment]
@facebook-github-bot cla

**Comment by facebook-github-bot-1** [comment]
Hey @InnerPeace080! Thanks for sending this pull request! We would love to review your changes however it looks like you haven't signed the CLA yet. You can do so at https://code.facebook.com/cla.

**Comment by InnerPeace080** [comment]
i had signed the cla. thank for report

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/184508731950759/int_phab) to review.

**Pull request closed without merging**
