### PR TITLE
Leak mutex to avoid a crashing issue

### PR DESCRIPTION
**Pull request by chuganzy**
Try to solve https://github.com/facebook/react-native/issues/13588
ref: https://github.com/facebook/componentkit/pull/906

Test Plan:
----------
Regression / smoke tests should be enough.

Changelog:
----------
[iOS] [Fixed] - Fix a crashing issue on RCTFont / mutex

### CODE REVIEW

**Comment by DimitryDushkin** [comment]
Ping. Eliminating crash is really important.

**Comment by DimitryDushkin** [comment]
We've released out app with this patch and this crash gone away.

**Comment by DimitryDushkin** [comment]
Where is my manners. Thank you @chuganzy!

**Comment by shergin** [comment]
@chuganzy 
Wait, wait, what makes you think that the linked crash happens when application is closing? Should we leak all static mutexes?

**Comment by shergin** [comment]
Here's a quote from Oliver:

> Historically, TextKit has had lots of hidden thread-safety issues despite being stated as thread safe. CK locks around all access to TextKit, but there are still issues that have cropped up in the recent past. We built the same text locking system in both CK and ASDK, and they both work this way.

As I can see, that's *not* how RN works here (and everywhere else) with fonts and co. So, maybe *this* is the problem.

**Comment by chuganzy** [comment]
Here's a quote from @ocrickard

> OK, looks like std::mutex is not trivially destructible in Clang, so we should probably just leak that mutex. Anyway, I believe this crash is happening on exit() as @gkassabli said above, so it probably has no impact on user experience.

**Comment by shergin** [comment]
Yes, exactly. My point is that the fix in CK fixes different type of the crash, not the one that promised in this diff's description.
I believe this change will not fix https://github.com/facebook/react-native/issues/13588 .

**Comment by shergin** [comment]
Just chatted with Oliver and... I was a bit wrong. :)
So, this fix seems to fix the one of the crashes mentioned in the assigned issue (but probably not that one which in the description).

As Oliver pointed out, all TextKit-related crashes wich has something like  '0x185dfc238 std::__1::mutex::try_lock() + 34' will be fixed with this fix.

**Comment by chuganzy** [comment]
@shergin Thank you, but seems like the issue in its description also indicates that it's crashing when it tries to lock from its line so I am hoping that this solves the issue🤞

**Pull request closed without merging**
