### PR TITLE
feat(text-input):  [iOS] `inputAccessoryViewButtonLabel` prop

### LINKED ISSUE #29244: iOS: returnKeyType is not localized for numeric TextInput
## Description
The return key for a numeric TextInput is not localized to the OS Language of the user. 

On a default alphabetic input, the "done" button is correctly localized. 

## React Native version:
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 43.03 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5

## Steps To Reproduce
Embed the following component:
```
<TextInput 
              keyboardType = 'numeric'
              returnKeyType='done' 
              />
```
## Expected Results
I expected the return key "done" to be correctly localized to the OS Language, like it is done for non-numeric textInputs

## Snack, code example, screenshot, or link to a repository:
IMG_1004

### PR DESCRIPTION
**Pull request by mateoguzmana**
## Summary:

Fixes #29244, also mentioned in #25009

As mentioned in the linked issues, the current return key label in the input accessory view is not localized. In the code, right now the texts are hardcoded (see: [RCTTextInputComponentView.mm](https://github.com/facebook/react-native/blob/main/packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm#L552) and [RCTBaseTextInputView.mm](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.mm#L694)). I could not find the historical reason for this, but doing some investigation there doesn't seem to be a way of getting the translated text into the code by using the existing props. (Ref: https://stackoverflow.com/a/58190342/5415299)

The solution: adding a new property `inputAccessoryViewButtonLabel` which can be used to overwrite these defaults non-translated values. The property is optional to avoid breaking changes.

The implementation works for both Fabric and Paper.

## Changelog:

[IOS] [ADDED] - TextInput `inputAccessoryViewButtonLabel` prop

## Test Plan:

A new example has been added under the `TextInput` examples in the RNTester. See below:

<details>
<summary>Video demonstrating how the new prop behaves</summary>

https://github.com/user-attachments/assets/b15cb8b8-494a-4f41-b434-e33eeef5d267

</details>

### CODE REVIEW

**Comment by BatDroid** [comment]
Hi [mateoguzmana](https://github.com/mateoguzmana), does this gonna also fix the label for cancel button?

**Comment by mateoguzmana** [comment]
> Hi [mateoguzmana](https://github.com/mateoguzmana), does this gonna also fix the label for cancel button?

@BatDroid yes, you will be able to provide your own localised label :)

**Comment by BatDroid** [comment]
> > Hi [mateoguzmana](https://github.com/mateoguzmana), does this gonna also fix the label for cancel button?
> 
> @BatDroid yes, you will be able to provide your own localised label :)

Mostly what I meant was the fact that if the `keyboardType="number-pad"` then there'll be also a `cancel` button in the left along with `Done` button.

**Comment by cortinico** [comment]
Hey @mateoguzmana 
I've just realized this prop was not documented on https://github.com/facebook/react-native-website/

Can I ask you to follow up over there? Thank you very much 🙏

**Comment by mateoguzmana** [comment]
> Hey @mateoguzmana I've just realized this prop was not documented on https://github.com/facebook/react-native-website/
> 
> Can I ask you to follow up over there? Thank you very much 🙏

Absolutely, will follow up on it!

**Pull request closed without merging**
