### PR TITLE
[Inspector]Fix warnings of StyleInspector

### PR DESCRIPTION
**Pull request by wusuopu**
Fix issue #5831

### CODE REVIEW

**Comment by wusuopu** [comment]
Now it set the key property of Text elements in StyleInspector and fix this issue.

simulator screen shot feb 9 2016 1 58 48 pm

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Thanks

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
