### PR TITLE
clean four MapView lint warnings

### PR DESCRIPTION
**Pull request by trave7er**
clean four MapView lint warnings.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks @trave7er

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by christopherdro** [comment]
We should encourage contributors to squash their commits.

**Comment by satya164** [comment]
@christopherdro I thought these PRs are automatically squashed by the bot. No?

**Comment by ide** [comment]
Code commits that need to be synced are automatically squashed. Doc commits are not.

**Comment by christopherdro** [comment]
Good to know... Haven't had a chance to to use the bot much yet.

**Pull request closed without merging**
