### PR TITLE
[Executor] Use Obj-C API in `toggleProfilingFlag`

### PR DESCRIPTION
**Pull request by ide**
Uses the Obj-C API to set a global flag for whether or not profiling is active.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
@AaaChiuuu would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by ide** [comment]
Feel free to close this if the Obj-C is going away in favor of C++.

**Comment by mkonicek** [comment]
@ide This PR got forgotten about because we didn't have the blame bot back then. Do you still plan to rebase this or should we close?

**Comment by ide** [comment]
@mkonicek is the plan to still move the core from Obj-C to C++? If so I'll close this PR and won't bother with rebasing.

**Comment by mkonicek** [comment]
@ide Yes the bridge is being rewritten in C++.

**Pull request closed without merging**
