### PR TITLE
Fix batch bridge invalidate

### PR DESCRIPTION
**Pull request by ywz2010**
If batchBridge load error, it will call  `[self stopLoadingWithError:loadError]`  function. In this function, it will  call `[_javaScriptExecutor invalidate]`.And `  [_context performSelector:@selector(invalidate)   onThread:_javaScriptThread  withObject:nil waitUntilDone:NO];` will stop the `_javaScriptThread` runloop. 

  When we want to release bridge , we will call batchBridge invalidate function, but `[_javaScriptExecutor executeBlockOnJavaScriptQueue:block]` will not run the block because the jsThread is stoped. RCTTiming's methodQueue is RCTJSThread. The `dispatch_group_leave(group);`  have no change to run. This will make that we will not release the batchBridge.

### CODE REVIEW

**Comment by ide** [comment]
This will likely introduce a regression fixed in https://github.com/ywz2010/react-native/commit/8ea9a1bc94a0d5635f6ab286331a8acba912f15f. Can you verify that an invalid bundle (e.g. has a syntax error) doesn't trigger infinite recursion (https://github.com/facebook/react-native/issues/5090), or come up with another fix?

**Comment by ywz2010** [comment]
@ide   Can `[batchedBridge invalidate]` call module's invalidate function not in  JSThread. If the moduleData's mehtodQueue is RCTJSThread , call it on mainthread.  I don't know the reason why `dispatch_group_notify(group, dispatch_get_main_queue()` call the `[_javaScriptExecutor executeBlockOnJavaScriptQueue:block` . What will it cause if I run 

       [_jsDisplayLink invalidate];
      _jsDisplayLink = nil;

      [_javaScriptExecutor invalidate];
      _javaScriptExecutor = nil;

      if (RCTProfileIsProfiling()) {
        RCTProfileUnhookModules(self);
      }

      _moduleDataByName = nil;
      _moduleDataByID = nil;
      _moduleClassesByID = nil;
      _modulesByName_DEPRECATED = nil;
      _frameUpdateObservers = nil;
      _pendingCalls = nil;
 on main thread?

**Comment by ywz2010** [comment]
I think we can call the code on the main thread. 
`[_javaScriptExecutor invalidate]` also can called on mainThread.

    [_jsDisplayLink invalidate];
    _jsDisplayLink = nil;

    [_javaScriptExecutor invalidate];
    _javaScriptExecutor = nil;

    if (RCTProfileIsProfiling()) {
      RCTProfileUnhookModules(self);
    }

    _moduleDataByName = nil;
    _moduleDataByID = nil;
    _moduleClassesByID = nil;
    _modulesByName_DEPRECATED = nil;
    _frameUpdateObservers = nil;
    _pendingCalls = nil;

**Comment by tadeuzagallo** [comment]
I don't think this is the way we should fix it. If something is fundamentally wrong about the way we're invalidating we should take a step back and fix it properly, the proposed solution will break the contract that `invalidate` is called on the module's `methodQueue`.

**Comment by ywz2010** [comment]
@tadeuzagallo Yes, you are right.  We can make a rule that all `invalidate` called on the main thread asynchronously.  And check the exist modules.

**Comment by tadeuzagallo** [comment]
That would break all the assumptions for all the already written modules, that's not an option. I'll try just moving the deallocation of the JS context to `dealloc`, that should delay stopping the runloop, allowing us to still invalidate all the modules in the right `methodQueue`.

**Pull request closed without merging**
