### PR TITLE
Add Chop to showcase

### PR DESCRIPTION
**Pull request by viviancromwell**
add Chop to showcase

### CODE REVIEW

**Comment by hramos** [comment]
Thanks for sending this pull request. According to the guidelines in that file, "infoLink" must be one of:

 1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native

I am going to close this, but if you have one of those two things, feel free to reopen with a new link.

**Comment by viviancromwell** [comment]
@hramos I made the changes requested to my PR branch (https://github.com/viviancromwell/react-native/commit/9fab5b0d9aaff0c9df48af7ddf57d3f482424283) but GitHub isn't showing me the option to reopen the PR, should I just create a new PR?

**Comment by hramos** [comment]
@viviancromwell now that I re-opened the PR, your commit is showing up. Sorry about that. The article looks great.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by ide** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
