### PR TITLE
Fix markdown link in blog post

### PR DESCRIPTION
**Pull request by orta**
See the last sentence:

screen shot 2016-07-06 at 11 42 11 am

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @lacker to be a potential reviewer.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1772984956249152/int_phab) to review.

**Pull request closed without merging**
