### PR TITLE
[Blog] Link to individual blog posts from post title

### PR DESCRIPTION
**Pull request by hramos**
Linkify the blog post title when the excerpt is displayed in the blog index.

Update Facebook OpenGraph meta tags for individual blog posts to fix sharing previews.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @vjeux and @bestander to be potential reviewers.

**Comment by bestander** [comment]
LGTM, let's wait till Circle builds it

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3771630) to review internal test results.

**Pull request closed without merging**
