### PR TITLE
[npm] Include ReactAndroid with the npm distribution

### PR DESCRIPTION
**Pull request by ide**
Enables building RN Android from source while keeping it in sync with the iOS distribution.

### CODE REVIEW

**Comment by chirag04** [comment]
@mkonicek can we get this merged?

**Comment by ide** [comment]
cc @mkonicek @vjeux seems like a couple of contributors have needed to build RN Android from source. If you really don't want this I can maintain a fork too. This mostly mirrors the current iOS situation, though, which has worked well.

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by chirag04** [comment]
:+1: 

@ide Should we document how to build from source for android? I can PR after i get this working. I think we just need to change ``setting.gradle`` to point the path of ReactAndroid and ``build.gradle`` to compile reactAndroid

**Comment by ide** [comment]
If we update settings.gradle the rest should be self-documenting. Some build.gradle files already have :ReactAndroid instructions in them, commented out.

**Comment by chirag04** [comment]
I'm not able to compile it from node_modules though. I did change settings.gradle and build.gradle.

I get:
```
startup failed:
  build file '/Users/chirag/Desktop/lrn/lrn/node_modules/react-native/ReactAndroid/build.gradle': 8: unable to resolve class de.undercouch.gradle.tasks.download.Download
   @ line 8, column 1.
     import de.undercouch.gradle.tasks.download.Download
     ^

  1 error
```

**Comment by chirag04** [comment]
@ide are you able to compile rn-android from source?

**Comment by ide** [comment]
Yes, i use the code in node_modules.

**Comment by chirag04** [comment]
Can you share what you changed in setting.gradle?

**Comment by chemuto** [comment]
I am having the same problems as @chirag04 when trying to compile rn android from source:
unable to resolve class de.undercouch.gradle.tasks.download.Download

It would be great to have some documentation on building from source for android.

Thanks

**Comment by chirag04** [comment]
@chemuto I got it working. Refer the comment here: https://github.com/facebook/react-native/issues/3337#issuecomment-147243916. follow step 1 in that comment.

**Comment by mkonicek** [comment]
@chemuto See the docs on building from source: https://github.com/facebook/react-native/tree/master/ReactAndroid

**Comment by mkonicek** [comment]
@ide @chirag04 I don't understand the reason to this. If you want to build from source you can clone the github repo and follow the instructions: https://github.com/facebook/react-native/tree/master/ReactAndroid

**Comment by mkonicek** [comment]
Publishing the Android sources makes the npm package bigger and most people won't need the sources in `npm_modules`. I'm going to revert this for now until we have a clear need for this.

**Comment by chirag04** [comment]
My only need for build from source is to not change the workspace to UIExplorer. UIExplorer may not have the setup to replicate the bug found in RN using my project setup.

**Comment by mkonicek** [comment]
OK get it, that's a valid use case, let's keep `ReactAndroid`. I'm just adding an `.npmignore` for `ReactAndroid/build` (Gradle output) which is huge (>100MB) so we never accidentally publish this.

**Comment by chirag04** [comment]
:+1:

**Comment by ide** [comment]
Good call on not publishing the build output. Thanks @mkonicek @chirag04

**Pull request closed without merging**
