### PR TITLE
Allow View containers to specify custom measure functions

### PR DESCRIPTION
**Pull request by obipawan**
This PR allows `ViewManagers` that are containers (extending `ViewGroupManager`) to specify it's custom `CSSNode.MeasureFunction`.
`ViewManagers` that don't need to specify this can extend `SimpleViewGroupManager` instead

### CODE REVIEW

**Comment by mkonicek** [comment]
Hey @obipawan, what's the motivation for this?

**Comment by obipawan** [comment]
Hey @mkonicek 
This change is basically to allow custom Views that are also containers(`ViewGroup`) to other views to be able to specify a measure function if they wanted to. With the current `ViewGroupManager`, it's not possible to specify a custom `LayoutShadowNode`. 
It also brings this in parity with iOS where one can create any native view from `RCTViewManager` and then specify a custom `RCTShadowView`.

**Comment by mkonicek** [comment]
OK thanks for the explanation! @kmagiera, @foghina are you OK with this?

**Comment by astreet** [comment]
Why can you not provide a custom LayoutShadowNode by extending ViewGroupManager?

**Comment by kmagiera** [comment]
I don't see this change being necessary to support the use case you're describing. If you want your view group manager to use custom class as a shadow node you can simply override `createShadowNodeInstance` and `getShadowNodeClass` (note that both methods are not marked as `final` in `ViewGroupManager`). TBH I'd rather avoid adding yet another base class to the namespace

**Comment by obipawan** [comment]
Hey @kmagiera It's possible to override `createShadowNodeInstance`, but as for `getShadowNodeClass` you'd have to make the return type to an unchecked `Class` type for it to work. Though this is yet another base class, it would make it safer to have the return type checked IMO.

**Comment by kmagiera** [comment]
@obipawan  Are you sure that is the case here? The return type on `getShadowNodeClass` in `ViewGroupManager` is `Class<? extends LayoutShadowNode>` (not `Class<LayoutShadowNode>`) which should allow you to return class object of any class that extends `LayoutShadowNode`.

**Comment by obipawan** [comment]
@kmagiera Apologies! you're absolutely right. I missed that this was changed for [0.18](https://github.com/facebook/react-native/releases/tag/v0.18.0-rc) and missed this even while submitting this PR. My bad!

**Pull request closed without merging**
