### PR TITLE
Add ability to specify main Activity in run-android

### PR DESCRIPTION
**Pull request by grabbou**
Follow up to #8190

Tested with custom parameter as well as w/o (using default value). All worked well.

CC: @ptomasroos

### CODE REVIEW

**Comment by mkonicek** [comment]
LGTM, thanks! 👍 

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by ptomasroos** [comment]
This is fine with me @grabbou ! Lets try to get it in again

**Comment by grabbou** [comment]
Ping @mkonicek

**Comment by grabbou** [comment]
@facebook-github-bot shipit-ninja

**Comment by grabbou** [comment]
Rebased, one more time.

**Comment by bestander** [comment]
@grabbou, this PR was merged although it was overridden in https://github.com/facebook/react-native/commit/85c8333bc87d27a7f5f31a74d62c3d0b3ad631f9.

**Comment by grabbou** [comment]
I know @bestander, but I've rebased now and this PR re- applies the changes once again. Shall I submit another PR?

**Comment by bestander** [comment]
Let's try to ship it first and if it fails try a new pr

**Comment by grabbou** [comment]
I've re-opened then

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
On the other hand github shipit bot won't be able to create a new Phabricator diff.
Can you create a new PR please?

**Comment by grabbou** [comment]
Will do. But this is really depressing to keep rebasing these things forever :( Luckily I don't mind it 🚀

**Comment by bestander** [comment]
Sorry for it, @grabbou, thank you for keeping the spirits high!

**Pull request closed without merging**
