### PR TITLE
Added Samanage to the showcase

### PR DESCRIPTION
**Pull request by eyaleizenberg**
Added the Samanage iOS React Native app to the showcase.

### CODE REVIEW

**Comment by mkonicek** [comment]
Please add the app to the `apps` array.

See the explanation here: http://facebook.github.io/react-native/showcase.html

screen shot 2016-04-21 at 2 00 05 pm

**Comment by eyaleizenberg** [comment]
@mkonicek How can I get our app on the featured list?

**Comment by mkonicek** [comment]
@eyaleizenberg I believe @brentvatne mantains that list :)

@facebook-github-bot shipit

**Comment by mkonicek** [comment]
In general we should probably add every app to the `apps` list and only later move apps to featured apps.

**Pull request closed without merging**
