### PR TITLE
feat: add `disabledButtonTintColor` prop in `ActionSheetIOS`

### PR DESCRIPTION
**Pull request by henninghall**
### Problem
Setting the `tintColor` prop in ActionSheetIOS also changes the tint of disabled entries. This could make them visually indistinguishable from enabled items. The degree to which they are indistinguishable depends on the tint color.

### Solution
This new prop `disabledButtonTintColor` allows customization of disabled items' tint color.

Related PR: https://github.com/facebook/react-native/pull/31972

## Changelog:

[IOS] [ADDED] - added `disabledButtonTintColor` prop to ActionSheetIOS

## Test Plan:

Tested in RNTester project. 

<table>
  <tr>
    <td align="center">
      <strong>Before</strong>
    </td>
    <td align="center">
      <strong>After</strong>
    </td>
  </tr>
  <tr>
    <td>
      Screenshot Before
    </td>
    <td>
      Screenshot After
    </td>
  </tr>
  <tr>
    <td align="center">
      <strong>Before</strong>
    </td>
    <td align="center">
      <strong>After</strong>
    </td>
  </tr>
</table>

### CODE REVIEW

**Comment by henninghall** [comment]
@cortinico I there anything I can do to get someone to take a look at this PR? 🙏

**Review by cipolleschi — APPROVED** [review]
This looks good, thanks for the contribution

**Comment by lunaleaps** [comment]
Commented on the imported PR but wondering about this
> Setting the tintColor prop in ActionSheetIOS also changes the tint of disabled entries

Could we change ActionSheetIOS to not set the same tintColor to disabled entries? Or is that out of our control?

**Comment by lunaleaps** [comment]
In addition, if a user didn't set `disabledButtonTintColor`, but did set `tintColor`, with this PR, would we still set the disabled action button tint color to `tintColor`?

**Comment by lunaleaps** [comment]
> > Could we change ActionSheetIOS to not set the same tintColor to disabled entries? Or is that out of our control?
> 
> @lunaleaps this will break other apps that depend on the color being set.

Would it be worth a breaking change? Or is this component something we don't want to actively support? Overall I'd say my comments aren't blocking but since we're looking at this anyway

**Comment by cipolleschi** [comment]
> Would it be worth a breaking change? 

This would be a subtle breaking change, because it's just a behavioral one. So it easier for it to go unnoticed. I'd rather to avoid breaking the component to avoid the confusion.

>  Or is this component something we don't want to actively support? 

So far, we are supporting it. However, it is an amazing candidate to go into Lean Core 2.0.

**Pull request closed without merging**
