### PR TITLE
Correct activity request code

### PR DESCRIPTION
**Pull request by anshulagarwal06**
Change activity request code to IMAGE_PICKER_REQUEST in currentActivity.startActivityForResult(chooserIntent, IMAGE_PICKER_REQUEST);

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @satya164 and @alvinthen to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@anshulagarwal06 Can you please sign the CLA so that I can accept your PR?

**Comment by anshulagarwal06** [comment]
@satya164 : CLA Signed . you can accept PR

**Comment by facebook-github-bot-2** [comment]
@anshulagarwal06 updated the pull request.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/501160330090650/int_phab) to review.

**Pull request closed without merging**
