### PR TITLE
Improve watcher timeout error message (fixes #5005)

### LINKED ISSUE #5005: Warning about "watchman" even when using NodeWatcher
Readers of packager's `FileWatcher/index.js` warning message _Watcher took too long to load / Try running watchman version from your terminal / https://facebook.github.io/watchman/docs/troubleshooting.html_ may conclude that they have a problem with watchman, also when [NodeWatcher](https://github.com/amasad/sane#sanenodewatcherdir-options) is being used.

Since `watchman` is often not installed (on Linux), this may be a source of confusion. I'd suggest to include the watcher name in the message, and perhaps something like _when you're using watchman, try ..._.

### PR DESCRIPTION
**Pull request by wvengen**

### CODE REVIEW

**Comment by milend** [comment]
@facebook-github-bot import

**Comment by skevy** [comment]
@mkonicek @vjeux it's weird...this PR didn't ask about the CLA.

**Comment by vjeux** [comment]
The bot didn't really like being turned off for the night. CLA is good here

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by wvengen** [comment]
Thanks for merging!

**Pull request closed without merging**
