### PR TITLE
ReactPicker extends AppCompatSpinner

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

Google recommends to extend AppCompat widget, and this PR changes ReactPicker to extend AppCompatSpinner.

## Changelog

[Android] [Changed] - ReactPicker extends AppCompatSpinner

## Test Plan

CI is green, and everything works as before.

### CODE REVIEW

**Comment by cpojer** [comment]
@dulmandakh let me know once this is ready for review and landing.

**Comment by dulmandakh** [comment]
@cpojer it's done.

**Comment by cpojer** [comment]
@dulmandakh can you fill out the changelog etc.?

**Comment by dulmandakh** [comment]
@cpojer oops, done 👍

**Comment by cpojer** [comment]
I think you'll need to rebase this one because the other one just landed.

**Comment by dulmandakh** [comment]
@cpojer done

**Pull request closed without merging**
