### PR TITLE
Improve website menu on mobile

### PR DESCRIPTION
**Pull request by janicduplessis**
Update the layout of the navbar on mobile.

image

**Test plan (required)**

Tested locally in mobile chrome and safari.

### CODE REVIEW

**Comment by vjeux** [comment]
The links in the top bar are the most important things in the website. We must absolutely not hide them in a hamburger menu. What we should do instead is make sure that they fit in two rows instead of the current janky way it is :)

Thanks for submitting that pull request though!

**Comment by janicduplessis** [comment]
@vjeux What about something like

image

**Comment by vjeux** [comment]
Looks awesome!

**Comment by janicduplessis** [comment]
:+1: I'll update with that :)

**Comment by janicduplessis** [comment]
Updated!

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Thx :)

**Pull request closed without merging**
