### PR TITLE
[Android] Natively loopable animations

### PR DESCRIPTION
**Pull request by edmofro**
* Provides new ‘shouldLoop’ config parameter for timing animation
* If useNativeDriver = true, will use Java code running on UI thread to
control looping
* Use case: We have a long running database query and calculation
process tying up the javascript thread, and want to display a loading
spinner while it is running. With this we can show a looping spinner
without returning to js to manage the loop.
* Note, this does the minimum to  fulfil our requirements, and no more. I.e. works only on Android, for the timing animation, and when useNativeDriver is true.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @kmagiera to be a potential reviewer.

**Comment by brentvatne** [comment]
Seems like a useful feature, I ran into similar use case before too. I think the api we want for this is `Animated.loop` though, so it's similar to `Animated.sequence`, `parallel`, and `stagger`: `Animated.loop(Animated.timing(value, config)).start()`. Can you update the PR for this?

This would be neat to integrate with those other animated controllers as well, so you could do: `Animated.loop(Animated.sequence([....]))`

**Comment by edmofro** [comment]
That sounds like a great api @brentvatne, and I'd love to update the PR - unfortunately our company can only afford to spend time on our own requirements at the moment. Was throwing this out there for some inspiration in case anyone wanted to pick it up. We'll continue to use it internally (will attempt to keep my fork up to date) until someone more giving with their time builds Animated.loop or similar. Cheers!

**Comment by facebook-github-bot-7** [comment]
@edmofro updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9513/files/7baee12f4ddebbef789c9faba33193d99c1d7ce4..a495ec40d909d32b034d52fff87c3f4bcebb3d90)

**Comment by facebook-github-bot-8** [comment]
@edmofro updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9513/files/a495ec40d909d32b034d52fff87c3f4bcebb3d90..e36d46812b2a3b2dba30be368734e049d0529120)

**Comment by brentvatne** [comment]
@janicduplessis will work on the API proposal that I mentioned above :)

**Comment by edmofro** [comment]
@janicduplessis how is it coming along?

**Comment by janicduplessis** [comment]
Haven't had time to work on this yet but its in the pipeline :)

**Comment by edmofro** [comment]
@facebook-github-bot this is now assigned to @janicduplessis (feel free to chip in if there's a specific sentence the bot listens to)

**Comment by janicduplessis** [comment]
Let's just close it for now as we won't merge it in this current state. Hopefully I'll have some time to work on this soon.

**Pull request closed without merging**
