### PR TITLE
Automatic update of `RCT-Folly`

### PR DESCRIPTION
**Pull request by fortmarek**
## Summary

When upgrading `react-native`, the version `RCT-Folly` defined [here](https://github.com/facebook/react-native/blob/main/third-party-podspecs/RCT-Folly.podspec) can change. If that happens, if you run `pod install` after `yarn install`, you will get a similar error to this:
```
[!] CocoaPods could not find compatible versions for pod "RCT-Folly":
  In snapshot (Podfile.lock):
    RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)

  In Podfile:
    RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)

    React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`) was resolved to 0.66.3, which depends on
      RCT-Folly (= 2021.06.28.00-v2)
```

This error occurs because `Cocoapods` does not update pods that point to a local podspec. Locally, you could resolve this issue by running `pod update RCT-Folly --no-repo-update`. On the CI, you have to do a clean checkout (in case you cache the `Pods` folder which we do). All of this makes upgrading `react-native` painful - for the whole community and for us @shopify

There are other users who have struggled with this, such as [here](https://github.com/facebook/react-native/issues/32423). The suggestion there is to delete `Podfile.lock` which is unnecessary - but it shows that users are confused what to do with this error and is something worth fixing.

To mitigate these issues, `react_native_pods.rb` automatically marks `RCT-Folly` as changed in the [detect_changes_with_podfile method](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/lockfile.rb#L289) from `Pod::Lockfile` if the version in `node_modules/react-native/third-party-podspecs/RCT-Folly.podspec` and `Pods/Local Podspecs/RCT-Folly.podspec.json` mismatch. 

Instead of automatically updating the local podspec (in `Pods/Local Podspecs` directory) we could also:
a) integrate `RCT-Folly` as a local pod (such as `React-Core` and others)
b) integrate `RCT-Folly` as an external dependency (going through Cocoapods' centralized repository)

I don't have enough context on why `RCT-Folly` is bundled the way it is, so I am open to suggestions here.

## Changelog

[iOS] [Fixed] - Fix `pod install` when `RCT-Folly` version has been updated.

## Test Plan

I have created a [repository](https://github.com/fortmarek/react-native-upgrade-reproduction) where you can reproduce the issue. You can simply:
1) clone the repo (`git clone https://github.com/fortmarek/react-native-upgrade-reproduction`)
2) Run `yarn install && cd ios && pod install`
3) Change `react-native` version in `package.json` to `0.66.3`
4) Run again `yarn install && pod install`
5) Observe error

To test the fix, you can then:
1) copy-paste the `react_native_pods.rb` file from this branch to `react-native-upgrade-reproduction/node_modules/scripts/react_native_pods.rb`
2) run `pod install` again

This time, the `pod install` command should succeed.

### CODE REVIEW

**Comment by fortmarek** [comment]
Hey @fkgozali @sota000, would you have some time to look at this? :pray:

**Comment by sota000** [comment]
Hi @fortmarek, sorry for the delayed response! My question would be that if RCT-Folly has the problem, wouldn't some other modules with the same setup have the same problem?

As for local vs. third party set up, I don't really have the history context either. It might be possible that it was done it because how the podspec file for RCT-Folly was set up. Maybe a better solution could be try to make it a local podspec?

**Comment by fortmarek** [comment]
Hey @sota000!

> My question would be that if RCT-Folly has the problem, wouldn't some other modules with the same setup have the same problem?

Correct, I have updated the PR to automatically update all podspecs in `third-party-podspecs` directory. Good catch!

> As for local vs. third party set up, I don't really have the history context either. It might be possible that it was done it because how the podspec file for RCT-Folly was set up. Maybe a better solution could be try to make it a local podspec?

Currently, it _is_ a local podspec. The alternatives are:
- local pod -> for this we need to have the sources locally. Unfortunately, that does not really suit us since the code for e.g. `Folly` is in a different repository. We _could_ introduce git submodules to have the files locally but it's not really ideal.
- remote pod -> we'd need to publish local podspecs such as `Folly` to the cocoapods directory. The podspecs could even keep living in the `react-native` repository. However, there is some maintenance tied to publishing cocoapods. 

I'm leaning to keeping the current solution, although migrating to remote pods might be a good solution as well. However, that's something I cannot help with since the remote pods would have to published by Facebook employees/React Native Core group.

**Comment by fortmarek** [comment]
@sota000 any updates on this one?

**Comment by cortinico** [comment]
> @sota000 any updates on this one?

I can provide a short update. We're mostly fine with the proposed approach. 
I'd like to get a final pass from @fkgozali
(sorry for this PR taking way longer than usual).

**Comment by cipolleschi** [comment]
Hi there! I was looking into this issue.
AFAIU, what's happening is that `react-native` has a strong dependency with `RCT-Folly` but there is no process that enforces that.
The proper fix should be that, every time we release a new version of `react-native`, we had a process which bumps the `RCT-Folly` version as well. This should avoid any Cocoapods black magic. Those podspecs are already complex and hard to maintain. I think we should find a better way t handle these issues, instead of adding patches to the script.

That said, for the time being, I think we can live with this patch. Improving how the pods work would be an effort that we have to carry out soon, to reduce complexity and technical debt.

**Review by cipolleschi — APPROVED** [review]

**Pull request closed without merging**
