### PR TITLE
gradle vm cleanup fix

### PR DESCRIPTION
**Pull request by enniel**
## Summary

This patch remove unused .so files for reduce android .apk and .aab

## Changelog

- [Android] [Fixed] - Exclude unused .so files for reduce android .apk and .aab

## Test Plan

I have created a repository for testing:
https://github.com/enniel/react-native-invalid-build-example

That lines includes patch for fix bug:
https://github.com/enniel/react-native-invalid-build-example/blob/f195ecdbeaca88ffb57c344615ede45ea0f6ef57/android/app/react.gradle#L331-L385

```sh
git clone https://github.com/enniel/react-native-invalid-build-example
cd react-native-invalid-build-example
npm i
```

debug, hermes disabled, without patch
```sh
git switch hermes-disabled-without-patch
npm run build:android:debug:apk
```
open android/app/build/outputs/apk/debug/app-debug.apk in android studio

debug-hermes-disabled-without-patch

debug, hermes enabled, without patch
```sh
git switch hermes-enabled-without-patch
npm run build:android:debug:apk
```
open android/app/build/outputs/apk/debug/app-debug.apk in android studio

debug-hermes-enabled-without-patch

debug, hermes disabled, with patch
```sh
git switch hermes-disabled-with-patch
npm run build:android:debug:apk
```
open android/app/build/outputs/apk/debug/app-debug.apk in android studio

debug-hermes-disabled-with-patch

debug, hermes enabled, with patch
```sh
git switch hermes-enabled-with-patch
npm run build:android:debug:apk
```
open android/app/build/outputs/apk/debug/app-debug.apk in android studio

debug-hermes-enabled-with-patch

release, hermes disabled, without patch
```sh
git switch hermes-disabled-without-patch
npm run build:android:release:apk
```
open android/app/build/outputs/apk/release/app-release.apk in android studio

release-hermes-disabled-without-patch

release, hermes enabled, without patch
```sh
git switch hermes-enabled-without-patch
npm run build:android:release:apk
```
open android/app/build/outputs/apk/release/app-release.apk in android studio

release-hermes-enabled-without-patch

release, hermes disabled, with patch
```sh
git switch hermes-disabled-with-patch
npm run build:android:release:apk
```
open android/app/build/outputs/apk/release/app-release.apk in android studio

release-hermes-disabled-with-patch

release, hermes enabled, with patch
```sh
git switch hermes-enabled-with-patch
npm run build:android:release:apk
```
open android/app/build/outputs/apk/release/app-release.apk in android studio

release-hermes-enabled-with-patch

### CODE REVIEW

**Comment by ecreeth** [comment]
### Awesome! these are my results:

<details>
<summary>release, hermes disabled, without patch</summary>

release, hermes disabled, without patch
</details>

<details>
<summary>debug, hermes disabled, without patch</summary>

debug, hermes disabled, without patch
</details>

<details>
<summary>debug, hermes enabled, without patch</summary>

debug, hermes enabled, without patch
</details>

<details>
<summary>debug, hermes disabled, with patch</summary>

debug, hermes disabled, with patch
</details>

<details>
<summary>debug, hermes enabled, with patch</summary>

debug, hermes enabled, with patch
</details>

<details>
<summary>release, hermes enabled, without patch</summary>

release, hermes enabled, without patch
</details>

<details>
<summary>release, hermes disabled, with patch</summary>

release, hermes disabled, with patch
</details>

<details>
<summary>release, hermes enabled, with patch</summary>

release, hermes enabled, with patch
</details>

**Comment by cortinico** [comment]
This is great stuff! Thanks for looking into it @enniel 
Just one note: would you be able to re-apply the same logic also here:

https://github.com/facebook/react-native/blob/382e78e0f0034ed0dbac7d976412add34f8527fa/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt#L194-L228

**Comment by enniel** [comment]
> This is great stuff! Thanks for looking into it @enniel
> Just one note: would you be able to re-apply the same logic also here:
> 
> https://github.com/facebook/react-native/blob/382e78e0f0034ed0dbac7d976412add34f8527fa/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt#L194-L228

Done!

**Comment by cortinico** [comment]
> > This is great stuff! Thanks for looking into it @enniel
> > Just one note: would you be able to re-apply the same logic also here:
> > https://github.com/facebook/react-native/blob/382e78e0f0034ed0dbac7d976412add34f8527fa/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt#L194-L228
> 
> Done!

Thanks for doing that 🙏

**Pull request closed without merging**
