### PR TITLE
Hook up Android intent to Linking.js #7079

### PR DESCRIPTION
**Pull request by satya164**
Fixed #7118 by @rreusser

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @cjhopman and @mhorowitz to be potential reviewers.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
@satya164 updated the pull request.

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1795084894058048/int_phab) to review.

**Comment by rreusser** [comment]
Thanks *sooo* much @satya164! Sorry this dragged on so long. It's tough once it's no longer your day job. Really appreciate this though!

**Comment by satya164** [comment]
@rreusser No problem. Thank you for working on this. I know the struggle :D

**Review by avonipenti — COMMENTED** [review]
Hi, we still have the issue of users complaining android deep links opening multiple instances of the app and using up all their data. Can this be merged soon?
We are using 'SingleTask' for the mainActivity but it still happens.

Thanks

**Pull request closed without merging**
