### PR TITLE
[Android] Adding Hyphenation Frequency prop for Text component

### PR DESCRIPTION
**Pull request by fabriziobertoglio1987**
## Summary

This issue fixes https://github.com/facebook/react-native/issues/28279
android_hyphenationFrequency prop for Android Text component which sets the frequency of automatic hyphenation to use when determining word breaks. 

## Changelog

[Android] [Fixed] - Adding Hyphenation Frequency prop for Text component

## Test Plan

More info are available in the [android docs](https://developer.android.com/reference/android/widget/TextView#setHyphenationFrequency(int)). I will add the documentation to the docs later once the pull request is taken in consideration for merging.

| **AFTER** | 
|:-------------------------:|
|  | 

I remain available to do improvements. Thanks a lot. Fabrizio.

### CODE REVIEW

**Comment by TheSavior** [comment]
I can't confirm that this will get approved (I don't have context on the Android side), but we've been following a pattern of the platform prefixes being `android_`, so this prop should be `android_hyphenationFrequency`. This is also seen in these props on Pressable: https://github.com/facebook/react-native/blob/master/Libraries/Components/Pressable/Pressable.js#L122-L127

**Comment by fabriziobertoglio1987** [comment]
thanks a lot @TheSavior . Changes are included in https://github.com/facebook/react-native/pull/29157/commits/4500095ef33a6a95f7daa8debd6fa9f069ba7ea3. I'm fixing the same issue also in https://github.com/facebook/react-native/pull/29059. I have no prerogative for the PR to be merged, but just hope to get a better insight in the react-native project and write more relevant pr in the future.. Thanks a lot. Fabrizio

**Comment by JoshuaGross** [comment]
This seems pretty reasonable to me :)

**Comment by JoshuaGross** [comment]
@fabriziobertoglio1987 I'm working on testing internally and having some conversations about the prefix. While I'm doing that, could you issue a PR to the docs site to add documentation for the new prop?

https://github.com/facebook/react-native-website/tree/master/docs

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot @Joshua I added the docs and also added a new commit to this Pull Request https://github.com/facebook/react-native/pull/29157/commits/14709f80a3bd035fbcce69a7dc73234c3cffaf36  as [setHyphenationFrequency](https://developer.android.com/reference/android/widget/TextView#setHyphenationFrequency(int)) android method is available only from API 23+. 

I decided to write this PR as a solution of https://github.com/facebook/react-native/issues/28279 to give users more control on the Text Component, but this could be not the optimal solution. I don't work on iOS.

I tested on RNTester example. I remain available. Thanks a lot. I wish you a good day. Fabrizio

**Comment by JoshuaGross** [comment]
@fabriziobertoglio1987 Thank you for following up on this! The amendment is being merged in.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/pull/29258

**Pull request closed without merging**
