### PR TITLE
Change Android testID prop from tag to content-description

### PR DESCRIPTION
**Pull request by tuckerconnelly**
Fixes https://github.com/facebook/react-native/issues/7135

This will make automated tests with [Appium](http://appium.io/) possible in Android.

Test plan:

The "Touchable feedback events" section in the UIExplorer has a testID. Checked it in the Appium inspector before, no content-description. Checked it after, it was there:

screen shot 2016-07-16 at 8 25 45 pm

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @kmagiera and @sebmarkbage to be potential reviewers.

**Comment by janicduplessis** [comment]
@bestander Is tag used by other e2e test systems? In this case we might want to set both tag and contentDescription.

**Comment by mkonicek** [comment]
We use the tag in our internal e2e testing system. contentDescription is used for accessibility: https://developer.android.com/training/accessibility/accessible-app.html

You could:
- Look up views by tag in Appium
- Use `accessibilityLabel` if you must use `contentDescription`: https://facebook.github.io/react-native/docs/accessibility.html

**Comment by jsdevel** [comment]
@mkonicek instead of breaking your e2e tests by using content description, would you accept a PR to leave the existing setter and add an adidtional setter to propagate resource-id?

**Pull request closed without merging**
