### PR TITLE
Fix flowconfig in starter project

### PR DESCRIPTION
**Pull request by skevy**
In the .flowconfig in the starter project, we're missing the correct suppression comments.

This should fix the flow issues in the e2e tests.

### CODE REVIEW

**Comment by skevy** [comment]
cc @ericvicenti @hramos

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit-ninja

**Comment by skevy** [comment]
Note this should be noted as a breaking change in the next release, unless it's fixed internally by then.

**Comment by ericvicenti** [comment]
Although it is possible to avoid a breaking change, I do like the idea of `FlowExpectedError`.

It is a shame we need to update the flow config in everybody's app for suppression that only happens within RN.

**Comment by skevy** [comment]
@ericvicenti this would still be a breaking change actually, as long as "site=react_native_oss" in Flow suppression comments exists in the code base.

**Comment by skevy** [comment]
Until Flow supports nested flowconfig's (which I'm not sure is even on the Flow team's roadmap) or a very complete react-native flow interface definition is added to flow-typed, which would be pretty difficult, and probably should be auto-generated in order to keep completeness and for it stay up to date, this is just something that we have to deal with. Adding to flow-typed would actually let projects using Flow and depending on RN to actually ignore all of node_modules/react-native in their flowconfig.

**Comment by sahrens** [comment]
Awesome, thanks @skevy!

`$FlowExpectedError` should be widely beneficial because it let's people write their own flow tests like https://github.com/facebook/react-native/blob/master/Libraries/Experimental/__flowtests__/FlatList-flowtest.js

**Comment by hramos** [comment]
Thanks @skevy!

**Comment by skevy** [comment]
@sahrens totally agree that this is a useful feature! Gonna start doing this myself :p

It's unfortunate that it's a breaking change. But it is what it is. Just the state of the world at the moment.

**Comment by desmond1121** [comment]
Awesome, thanks @skevy!

**Pull request closed without merging**
