### PR TITLE
[android] Fix signed apk anroid docs

### PR DESCRIPTION
**Pull request by bsansouci**
The docs weren't in sync with the code. This is really just a small fix.

### CODE REVIEW

**Comment by mkonicek** [comment]
cc @martinbigio

I believe `--bundle-output` is the new version.

**Comment by bsansouci** [comment]
I closed this PR because I'm using 0.13.0 and it seems to be completely different on master anyways ;)
Though if anyone's using 0.13.0, the docs don't align :/

**Comment by martinbigio** [comment]
yes, the pr for the doc is correct. We're planning to update the docs next week. cc @frantic

**Comment by foghina** [comment]
@martinbigio wait, so the final version is `--bundle-output` or `--out`? If it's the latter I'm going to need to update the gradle integration.

**Comment by bsansouci** [comment]
master seems to go for `--bundle-output` https://github.com/facebook/react-native/blob/c1faabcdf6f4fd15643743d23ebda556c4f49045/private-cli/src/bundle/bundleCommandLineArgs.js#L32

**Comment by martinbigio** [comment]
@foghina it's `--bundle-output`, we're good. I didn't remember I have already updated that docs :)

**Pull request closed without merging**
