### PR TITLE
[RNPM] Should be R.string, not R.strings

### PR DESCRIPTION
**Pull request by geof90**
Fix regression of https://github.com/rnpm/rnpm-plugin-link/pull/88.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @grabbou and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
@geof90 updated the pull request.

**Comment by geof90** [comment]
@Kureev @grabbou

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Comment by Kureev** [comment]
@geof90 thanks a lot! ❤️

**Pull request closed without merging**
