### PR TITLE
Update gradle-download-task from 2.0.0 to 3.1.2 to fix boost zip down…

### PR DESCRIPTION
**Pull request by younthu**
Small pull request

 **motivation** 
The doc 'Building React Native from source' is not up to date now.

While i try to build from the source my self, the gradle-download-task(2.0.0) will always fail to download boost zip with a failure of 403.

After i upgrade the gradle-download-task to 3.1.2, the download works well.

**Test plan (required)**
I tested to build the source myself, it works.

This is non-code update, it is document update, hope to help other people who get the same download failure.

**Code formatting**
Non-code update PR.

### CODE REVIEW

**Comment by mkonicek** [comment]
This is awesome, thanks!

Android tests are currently broken on master but once they're fixed could you rebase this to have green Android tests on the PR?

**Comment by younthu** [comment]
@mkonicek 

I updated the PR, all those tests are green now.

Can you help to have a review?

Thanks.

**Comment by christopherdro** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
Could you also update https://github.com/facebook/react-native/blob/master/build.gradle#L10. Not sure if it's too late since it was shipped (was 8 hours so it might have failed).

**Comment by younthu** [comment]
I can try it, but not sure it is the right process or not.

**Comment by chirag04** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
