### PR TITLE
Update Gradle Wrapper to 6.3

### PR DESCRIPTION
**Pull request by friederbluemle**
## Summary

```
Welcome to Gradle 6.3!

Here are the highlights of this release:
 - Java 14 support
 - Improved error messages for unexpected failures

For more details see https://docs.gradle.org/6.3/release-notes.html
```

## Changelog

[Android] [Changed] - Update Gradle Wrapper to 6.3

## Test Plan

Build project

### CODE REVIEW

**Comment by friederbluemle** [comment]
Gradle 6.2.2 was released on March 4.
Updated and rebased this PR.

**Comment by friederbluemle** [comment]
Rebased again and updated to Gradle 6.3

It looks like `gradlew.bat` accidentally had its CRLF endings removed in 07def553968f88f65a2a07c3aea8e757e49530dd (cc @hramos).

**Comment by friederbluemle** [comment]
Green CI 😍Thanks @hramos 💯👏

**Comment by SaeedZhiany** [comment]
Hi @friederbluemle

Why you completely removed `gradle-wrapper.jar` files? it's no longer needed to track in our projects git repositories too?

**Comment by friederbluemle** [comment]
@SaeedZhiany - I did not remove any `gradle-wrapper.jar` files. They got updated. You might be referring to `gradlew.bat` maybe? Just looking at the plain diff, it appears that **all** lines were changed.

The reason is that both `gradlew.bat` files had incorrect file endings on the `master` branch and Gradle's `wrapper` task automatically fixes that.
`*.bat` is only used on Windows and Windows uses `CRLF` (two characters) for a linebreak. It first got accidentally (?) changed in 44ae0fea07fac5e2a62804d537241c39f2b8da0d, subsequently reverted in 067b7a836de23c17fa9ee6bb9a7918e80473c2ee, then again re-applied in 07def553968f88f65a2a07c3aea8e757e49530dd.

To make it more clear, I _could_ use two commits here `1. Normalize file endings`, followed by `2. Update Gradle Wrapper`, but since all PRs in this repo get squashed by default anyway I just used one commit. Let me know if you want me to split it up real quick to make the review more clear.

**Comment by mdvacca** [comment]
lgtm

**Comment by friederbluemle** [comment]
Thanks @mdvacca

**Comment by SaeedZhiany** [comment]
Thanks @friederbluemle 

LGTM,

Usually, binary file changes shown by a removed file and a new added file in the `changes` tab, and when I checked the Tab I didn't see the new `jar` files there. I just thought you remove them completely which you don't, maybe something is wrong with GitHub.

However, Thanks for this PR 👍

**Comment by SaeedZhiany** [comment]
@friederbluemle 

Sorry if this is not the right place for the following question. (I can remove all my comments after the discussion about the question finished)

I want to create an android docker for building projects on my CI server and I want to put SDK staff in it so it can be build projects without (or minimum) needing to the internet. 

Is it safe to use android `Gradle wrapper`, `AGP`, `buildToolsVersion`, `compileSdkVersion`, `targetSdkVersion` versions upper than the current RN's templates?

I mean 

```
  buildToolsVersion = "29.0.3"
  minSdkVersion = 16
  compileSdkVersion = 29
  targetSdkVersion = 29
...
  classpath("com.android.tools.build:gradle:3.6.2")

...
gradle-6.3-all.zip
```

because I need to use the docker for the long term and I want to build the SDK with the latest versions available right now.

**Comment by SaeedZhiany** [comment]
@friederbluemle 

Sorry if this is not the right place for the following question. (I can remove all my comments after the discussion about the question finished)

I want to create an android docker for building projects on my CI server and I want to put SDK staff in it so it can be build projects without (or minimum) needing to the internet. 

Is it safe to use android `Gradle wrapper`, `AGP`, `buildToolsVersion`, `compileSdkVersion`, `targetSdkVersion` versions upper than the current RN's templates?

I mean 

```
  buildToolsVersion = "29.0.3"
  minSdkVersion = 16
  compileSdkVersion = 29
  targetSdkVersion = 29
...
  classpath("com.android.tools.build:gradle:3.6.2")

...
gradle-6.3-all.zip
```

because I need to use the docker for the long term and I want to build the SDK with the latest versions available right now.

**Comment by friederbluemle** [comment]
Hi @SaeedZhiany - Yes, these versions _should_ work. Send me an email if you run into any issues!

**Pull request closed without merging**
