### PR TITLE
Don't clear ReactNativeHost if other inst exists

### PR DESCRIPTION
**Pull request by cmc5788**
Do not call `getReactNativeHost().clear()` in `ReactActivity.onDestroy` if another created `ReactActivity` instance exists. This avoids the scenario where a dying `ReactActivity` in the background clears and destroys the shared `ReactInstanceManager` instance being used by another `ReactActivity` in the foreground. This fixes a scenario which can result in lifecycle corruption.

This is an improvement on #8634 after commentary that one `ReactInstanceManager` per Activity, as in 0.28.0, was not an appropriate technique to avoid the scenario above.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @foghina and @andreicoman11 to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
@cmc5788 updated the pull request.

**Comment by cmc5788** [comment]
@foghina is this still a priority for you guys? I know most people probably use stock react, but there are some serious and obvious problems resulting from basic Activity lifecycle that are unsolved without this PR outside of very basic usage of React.

**Comment by foghina** [comment]
Hmm, I'm doing some fixes internally that will completely remove the `.clear()` call from `onDestory()`, and other fixes related to multiple activities (e.g. not forwarding lifecycle events if they come from an activity different than the current one). I hope to land some of it this week, and I think it would address your issues as well.

**Comment by foghina** [comment]
@cmc5788 we are now not clearing the react instance at all, as of 3c4fd42.

**Pull request closed without merging**
