### PR TITLE
Update ImageResizeMode.java

### PR DESCRIPTION
**Pull request by zhuchaowe**
[Android]Image resizeMode 'contain' should be converted as 'FIT_CENTER'

### CODE REVIEW

**Comment by zhuchaowe** [comment]
for this issues #4031

**Comment by mkonicek** [comment]
Thanks! Can you provide screenshots before / after with various aspect ratios and also the iOS screenshot? The images in the linked issue don't load for me.

**Comment by mkonicek** [comment]
You should also test this with images smaller than the view, and larger than the view.

**Comment by satya164** [comment]
@zhuchaowe Any updates on this?

**Comment by satya164** [comment]
Related https://github.com/facebook/react-native/issues/4031

**Comment by thstarshine** [comment]
Any update on this?

**Comment by mkonicek** [comment]
If we don't get proper test cases we should close this.

**Comment by satya164** [comment]
Closing. Please comment if you want to re-open

**Pull request closed without merging**
