### PR TITLE
Helping with helloworld on local machine

### PR DESCRIPTION
**Pull request by inconceivable**
It is not just copy and paste into  index.ios.js or index.android.js to make the hello world app work on your local machine, as the text suggests. It requires the app's name to match the component which is registered with the registry. I did the Getting Started page before this and thus had the AwesomeProject app started and could paste into it, but naturally it did not work. To get it working, I originally just basically did find and replace HelloWorldApp -> AwesomeProject, which worked, but the better solution I found was in the stackoverflow topic I linked. If there is a better way to make it easier for beginners to test the hello world app in their local machine, I would be open to it.

Thanks for submitting a PR! Please read these instructions carefully:

- [ ] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

What existing problem does the pull request solve?

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

## Next Steps

Sign the [CLA][2], if you haven't already.

Small pull requests are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

Make sure all **tests pass** on both [Travis][3] and [Circle CI][4]. PRs that break tests are unlikely to be merged.

For more info, see the ["Pull Requests"][5] section of our "Contributing" guidelines.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9
[2]: https://code.facebook.com/cla
[3]: https://travis-ci.org/facebook/react-native
[4]: http://circleci.com/gh/facebook/react-native
[5]: https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests

### CODE REVIEW

**Comment by hramos** [comment]
The original intention here is not for people to copy/paste this into the AwesomeApp from the Getting Started. I'm sorry that was not clear.

We can improve the docs here. I'd rather not link to an external site with a solution. Why not either update the tutorial so it is clear that this requires creating a brand new app, or update the code samples in the tutorial so that it indeed allows for direct copy paste?

**Comment by inconceivable** [comment]
Good point, external links are fragile. I committed some improvements to the instructions to my patch-1 branch, however, I'm not sure how to send that to you or what I should do next (I'm a bit new to git/github).

**Comment by hramos** [comment]
Sorry for not following up earlier. So this doc has changed quite a bit since then, and I believe the issue has been addressed.

**Comment by inconceivable** [comment]
Oh good! I figured it wasn't too big of a deal, so I didn't worry about it.
Thanks for letting me know!

**Pull request closed without merging**
