### PR TITLE
Fix  this._component is null

### PR DESCRIPTION
**Pull request by jerson**
related to #10635

### CODE REVIEW

**Comment by satya164** [comment]
This is not an actual fix since we don't know it became null in the first place. We need to figure out why it's null and fix that.

**Comment by jerson** [comment]
hi @satya164 ,  this is the exception http://crashes.to/s/280c411449d

**Comment by satya164** [comment]
@jerson yes, but why does it happen

**Comment by ide** [comment]
This doesn't fix the fact that `this._component` is null. Please fix the root cause instead of covering up errors.

**Comment by fanyuRN** [comment]
I meet the mistake is this._component is undefined; what problem is this?

**Comment by hramos** [comment]
@jerson there's some comments that haven't been addressed yet, do you still plan to ship this PR?

**Comment by mkonicek** [comment]
> This doesn't fix the fact that this._component is null. Please fix the root cause instead of covering up errors.

> @jerson there's some comments that haven't been addressed yet, do you still plan to ship this PR?

Closing since the last comment is a question and this PR has been inactive in a while. If you plan to continue working on this please send a new PR that fixes the root cause.

**Pull request closed without merging**
