### PR TITLE
Added 'help' command to local CLI.

### PR DESCRIPTION
**Pull request by hedgerh**
### Summary
Added 'help' command to local CLI.

Displays options for a given command.
Usage:
  - react-native help [command]
  - react-native --help [command]
  - react-native [command] --help'

### Motivation
There is no documentation of the options for each of the CLI's commands.

Closes https://github.com/facebook/react-native/issues/6973

### Test plan
Using ["Running CLI with local modifications"](https://github.com/facebook/react-native/blob/master/react-native-cli/README.md) method to test locally.

I've tested all three syntaxes that can be used: `help <command>`, `--help <command>` and `<command> --help`, and have tested them on every documented command.  I've also tested error handling by putting in bad command names in each syntax.

Linted and had 0 errors / warnings from my changes.

**Testing `react-native help <command>` syntax:**
image

**Testing `react-native --help <command>` syntax:**
image

**Testing `react-native <command> --help` syntax:**
image

**Testing bad command names:**
image

**Output of all of the remaining commands:**
image

image

image

image

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @mroswald and @martinbigio to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@hedgerh updated the pull request.

**Comment by mroswald** [comment]
@hedgerh just had a first, quick look: can you add which commands are required and which are not?

**Comment by facebook-github-bot-2** [comment]
@hedgerh updated the pull request.

**Comment by hedgerh** [comment]
@mroswald:  Done.  Added a `[required]` string to any option that is required.

**Comment by mroswald** [comment]
@hedgerh nice work

**Comment by mroswald** [comment]
@facebook-github-bot ship-it

**Comment by mroswald** [comment]
@facebook-github-bot shipit

**Comment by christopherdro** [comment]
@mroswald This is decent sized PR and should require approval from some team members before being merged in.

**Comment by mroswald** [comment]
@christopherdro Yes, for sure! To be honest, I'm not sure how this command is supposed to be used. My understanding was it only reacts to some github users (core devs) and all others doing a review here can use it to signalize their agreement on this PR. So from my side I'm fine with the changes

**Comment by christopherdro** [comment]
@mroswald Hey! So the ship it command begin the process of merging the PR. However, you can always signalize your agreement by commenting and pinging someone from the original bots blame information.

**Comment by christopherdro** [comment]
Hmm, just saw this that might end up conflicted.
https://github.com/facebook/react-native/pull/7550

@grabbou Thoughts? Maybe this can also add a section for rnpm?

**Comment by grabbou** [comment]
Ah, for now `rnpm` is going to be completely hidden inside `local-cli`, but at some point we will probably need to document it more or less :)

**Comment by mroswald** [comment]
@christopherdro whom do you mean with `pinging someone from the original bots blame information`? @martinbigio ? :-)

**Comment by christopherdro** [comment]
Doh! I didn't notice you were also one of the ones that got blamed.
But by my comment I was referencing that.

Es tut mir leid. :)

**Comment by mroswald** [comment]
@christopherdro doesn't matter :-) Just wanted to make sure I understand the process correctly

**Comment by hedgerh** [comment]
Anything that I need to do at the moment? Or are we still waiting for clearance from core team? :)

**Comment by christopherdro** [comment]
@hedgerh You would have to rebase again since its out of date.

@martinbigio @mkonicek Thoughts on getting this merged in?

**Comment by satya164** [comment]
I don't think we need 3 different commands to do the same thing. `react-native help [command]` should be enough.

**Comment by mroswald** [comment]
@satya164 I disagree, if we have the option to easily support each resonable syntax, we should support it

**Comment by satya164** [comment]
@mroswald It's unnecessary and just confusing. It's like having 3 different syntaxes for subtraction.

**Comment by christopherdro** [comment]
I agree with @satya164 that having 3 might be a bit excessive.

`react-native [command] --help` feels most natural to me and matches your original screenshots.

**Comment by hedgerh** [comment]
I also disagree.  For me, `react-native help [command]` is the most natural.  A lot of CLIs, such as `npm`, `browser-sync`, support both `npm --help` and `npm help`, for example.

I just tested with `npm`, and it supports all three syntaxes:

```
npm help link
npm --help link
npm link --help
```

The idea is to make it as accessible as possible, so there isn't a "wrong way" to get help, no matter what comes naturally to you.

**Comment by hedgerh** [comment]
Plus all three methods are already implemented.

**Comment by satya164** [comment]
> For me, react-native help [command] is the most natural.

I kinda prefer this, because `--*` args are usually used for passing options to a command (at least how we use them). `help` seems more like a command rather than an option.

> A lot of CLIs, such as npm, browser-sync, support both npm --help and npm help, for example.

I think it doesn't matter unless we've a very strong reason to support it. I think the best way is to educate the user about the correct command when he types in the wrong command.

> Plus all three methods are already implemented. It'd only be confusing if we documented all three, which most CLIs usually do not.

There's no point in having undocumented ways. It'll get eventually get documented unofficially, say on stackoverflow and then it'll create confusion.

**Comment by hedgerh** [comment]
> I think the best way is to educate the user about the correct command when he types in the wrong command.

It's pedantic to say, "I know what you're trying to do, except I don't like the syntax that you used.  Instead of console logging help, I'm going to console log this message to make you print it the way I want you to."  If we go with one, it doesn't make any sense to parse the other two, then print out an error message instead of the help.

I think the lack of a standard for help syntax is a strong enough reason to support all 3.  Some people, like you and I, prefer `react-native help [command]`, whereas @christopherdro and a couple of other people have mentioned a preference to `react-native [command] --help`.  I think a "no wrong answers" approach is better than annoying the user or risking someone potentially not finding help documentation when they need it.  Like I mentioned, CLIs like `npm` have set a precedent for this.

Having said all of that, I yield to what you all think is best.  Once there is consensus, I'll make the appropriate changes.

**Comment by christopherdro** [comment]
@vjuex Wanna lay down the final judgement. :)

**Comment by satya164** [comment]
> It's pedantic to say, "I know what you're trying to do, except I don't like the syntax that you used. Instead of console logging help, I'm going to console log this message to make you print it the way I want you to." If we go with one, it doesn't make any sense to parse the other two, then print out an error message instead of the help.

Why not add `react-native --run-ios`, `react-native --run ios` and `react-native run ios` along with `react-native run-ios` then? With any library API/CLI args, we can know common mistakes user will make, and we can do three things, 1) show a cryptic error message, 2) handle possible misspellings and show a helpful message, 3) add APIs with all possible misspellings 

> @christopherdro and a couple of other people have mentioned a preference to `react-native [command] --help`

It really doesn't matter. I don't have a strong preference on it.

> I think a "no wrong answers" approach is better than annoying the user or risking someone potentially not finding help documentation when they need it.

IMO tip on how to access the help should always be printed when user types a wrong command. This leaves absolutely 0 chance of people not finding help docs.

**Comment by hedgerh** [comment]
@satya164 I am going to get rid of `react-native help [command]` and `react-native --help [command]`.  If a user tries to use them, it'll show the default usage message, where help usage will be shown at the bottom for `react-native [command] --help`.  That way no extra parsing will need to be done.

Thanks for all of your input.  Unless @mroswald or someone wants to push for keeping all syntaxes, I'm going to go ahead.

**Comment by hedgerh** [comment]
Quick question, is it safe to use this button, or should I rebase via command line always?

image

**Comment by facebook-github-bot-6** [comment]
@hedgerh updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@hedgerh updated the pull request.

**Comment by hedgerh** [comment]
Ready for review.

image

**Comment by satya164** [comment]
> Quick question, is it safe to use this button, or should I rebase via command line always?

Yes, it's safe

> @satya164 I am going to get rid of react-native help [command] and react-native --help [command]. If a user tries to use them, it'll show the default usage message, where help usage will be shown at the bottom for react-native [command] --help. That way no extra parsing will need to be done.

cool!

@mkonicek Can you give a quick look here?

**Comment by facebook-github-bot-6** [comment]
@hedgerh updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@hedgerh updated the pull request.

**Comment by mkonicek** [comment]
@hedgerh Awesome idea! Minor thing: can you please do this without the columnify dependency? I'd really like to avoid us adding more dependencies, even if they are "small". When printing the options you can just compute max length and add a few spaces after each option rather than adding a dependency that has two dependencies.

**Comment by facebook-github-bot-5** [comment]
@hedgerh do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by grabbou** [comment]
One thing to note here is that with `rnpm` being merged, we are going to get `help` commands automatically thanks to `rnpm` using `commander` module. Following the diff, it's pretty similar in terms of extracting params and flags to separate variables, just like we did in our PR.

**Comment by hedgerh** [comment]
Hey all, things got a bit busy for me and I hadn't gotten around to making the last requested change.

@grabbou: thanks for the heads up. I'll read up on the `rnpm` merge and, once it's merged, will update this PR accordingly to take advantage of `commander`'s built in `help` command.

**Comment by hedgerh** [comment]
Closing this as help command has been implemented!

**Pull request closed without merging**
