### PR TITLE
[Docs] Update Image docs and examples to the new asset system

### PR DESCRIPTION
**Pull request by andybb**
After the release of 0.14, static images should be placed in the source code tree and then required as explained in the [Images guide] (https://facebook.github.io/react-native/docs/images.html). This pull request updates the image documentation and examples to the new asset system. UIExplorer tested on iOS and Android.

### CODE REVIEW

**Comment by satya164** [comment]
@andybb Thanks.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@andybb import failed because of conflicts.
Could you please rebase?

**Comment by andybb** [comment]
@bestander Done.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
Sorry, our internal packager freezes when tries to build the bundle.
Created internal task t9668879, we'll fix it an then this diff will get merged

**Comment by satya164** [comment]
ping @bestander :)

**Comment by bestander** [comment]
Thanks, bumped @martinbigio on task t9668879.

**Comment by martinbigio** [comment]
The problem is this 4 images are empty files:

Examples/UIExplorer/uie_thumb_normal@2x.png 
Examples/UIExplorer/uie_thumb_selected@2x.png 
Examples/UIExplorer/uie_comment_normal@2x.png 
Examples/UIExplorer/uie_comment_highlighted@2x.png

**Comment by andybb** [comment]
@martinbigio: Should I change anything? The images are just moved/renamed.

**Comment by bestander** [comment]
Let me test it once more

**Comment by bestander** [comment]
Sorry @anderdb, we had a unicorn infestation in the data center.
Had to use a chainsaw...
Because of that images were imported incorrectly, as blank files as a matter of fact.
I'll talk to the robots on duty and get this sorted in no time.

**Pull request closed without merging**
