### PR TITLE
fix ios formdata boundary include slash

### PR DESCRIPTION
**Pull request by unordered**
some server not work when upload a file with FromData in ios. 
the reason is that there is a slash in boundary, like:
```
multipart/form-data; boundary=b/QeEbFgqK9PCZo4T/eXv7f.T74SHd5MxCZ846AsTz-yNV0xrRR_Zks4fkNMCzJck9ZE8o

// koa request.js (line 548)
  is(types) {
    if (!types) return typeis(this.req);
    if (!Array.isArray(types)) types = [].slice.call(arguments);
    return typeis(this.req, types);
  }

// type-is index.js (line 237)
function normalizeType (value) {
  // parse the type
  var type = typer.parse(value)

  // remove the parameters
  type.parameters = undefined

  // reformat it
  return typer.format(type)
}

// media-typer
var paramRegExp = /; *([!#$%&'\*\+\-\.0-9A-Z\^_`a-z\|~]+) *= *("(?:[ !\u0023-\u005b\u005d-\u007e\u0080-\u00ff]|\\[\u0020-\u007e])*"|[!#$%&'\*\+\-\.0-9A-Z\^_`a-z\|~]+) */g;
```

thanks for @dougwilson 's [answer](https://github.com/jshttp/media-typer/issues/5).
> The / is an illegal character for Content-Type, which is what this module parses. The boundary parameter value needs to be quoted if it contains a / character, for example:
```
multipart/form-data; boundary="b/QeEbFgqK9PCZo4T/eXv7f.T74SHd5MxCZ846AsTz-yNV0xrRR_Zks4fkNMCzJck9ZE8o"
```

### CODE REVIEW

**Comment by javache** [comment]
That will just break https://github.com/facebook/react-native/issues/7564 again. Can you instead change the dictionary where we generate the boundary from?

**Comment by javache** [comment]
https://github.com/facebook/react-native/blob/e1577df1fd70049ce7f288f91f6e2b18d512ff4d/Libraries/Network/RCTNetworking.mm#L52

**Comment by unordered** [comment]
remove slash from the dictionary of generate boundary

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by ivpusic** [comment]
I have the same issue. Currently https://golang.org/pkg/mime/#ParseMediaType returns error, because of "/". This is fixing the problem for me.

**Comment by jaggerwang** [comment]
Same problem, take me a few days to figure this out!!! Before update RN to 0.39, fetch works fine.

**Comment by javache** [comment]
@unordered Can you sign the CLA so I can pull this?

**Comment by unordered** [comment]
@javache ok

**Comment by ethan37** [comment]
Thanks, finally fixed this issue for me!

**Comment by bluedaniel** [comment]
Just want to highlight that this is an important fix which should be in the next release.

**Pull request closed without merging**
