### PR TITLE
Provide a flip transition animation for View component.

### PR DESCRIPTION
**Pull request by adamkrell**
This gives the `<View />` component a flip animation. It doesn't actually modify the view, but utilizes the iOS built in transition animation for UIView.

Example code: https://github.com/adamkrell/FlipCardRN

### CODE REVIEW

**Comment by browniefed** [comment]
I believe this can be accomplished with perspective, like in the UI Explorer example here https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/TransformExample.js

**Comment by adamkrell** [comment]
@browniefed That's interesting. I haven't experimented with the `Animated` library yet. The nice thing about using UIView animations is that they are smooth and performant. Do you think this is unnecessary?

**Comment by browniefed** [comment]
@adamkrell they are pretty smooth but in JS now, they'll be hopefully moving to the native world eventually. However I don't think this should be in core, it'd be great if this were a custom view you just released.

**Comment by adamkrell** [comment]
@browniefed The View component is quite complex. I'm not exactly sure how to implement that without duplicating a lot of the react native code. Is there an easier way to implement it as a separate component?

**Comment by browniefed** [comment]
@adamkrell you can just extend RCTView and add your own side prop, lots of examples of custom components on the web.

**Comment by nicklockwood** [comment]
I like the feature, but this isn't the right way to implement it. If we want to support native transitions, we should come up with a proper API for specifying them, possibly an extension of the LayoutAnimation system, or the Animated API?

**Comment by adamkrell** [comment]
@browniefed Thanks. I'll give that a try.

**Comment by adamkrell** [comment]
@nicklockwood Supporting an API for the native transitions and animations makes sense. I was trying to think of a simple way to add a basic flip animation to a view using a declarative approach (e.g., side = front or back). But there is so much that can be done with animations and transitions that it does seem too specific to make it a property.

**Pull request closed without merging**
