### PR TITLE
Initial stab at NavigationExperimental tutorial

### PR DESCRIPTION
**Pull request by hramos**
Add a NavigationExperimental section to the Navigation guide.

navexp

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @alvaromb to be potential reviewers.

**Comment by hramos** [comment]
There's a few more content edits to go to get more of the Navigator and NavigatorIOS sections in sync with their API references. We may need to break out experimental into its own guide, but I don't want to have a new permalink for NavigationExperimental as the name has not been finalized yet.

**Comment by JoelMarcey** [comment]
Yay! This is great!

Looks like this needs a rebase.

Btw, did you try to add the React Native Web Player to any of your examples? Or is any navigation not supported by it?

**Comment by hramos** [comment]
@JoelMarcey That would be ideal, but I don't see any of the navigation APIs in react-native-web.

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/191946804541116/int_phab) to review.

**Comment by JoelMarcey** [comment]
@hramos The patch is not applying internally. Might need another rebase -- we can try that. If that doesn't work, we may have to get more creative with an interactive rebase as the merge commit may have caused some possible funkiness here.

**Comment by facebook-github-bot-0** [comment]
I tried to merge this pull request into the Facebook internal repo but some checks failed. To unblock yourself please check the following: Does this pull request pass all open source tests on GitHub? If not please fix those. Does the code still apply cleanly on top of GitHub master? If not can please rebase. In all other cases this means some internal test failed, for example a part of a fb app won't work with this pull request. I've added the Import Failed label to this pull request so it is easy for someone at fb to find the pull request and check what failed. If you don't see anyone comment in a few days feel free to comment mentioning one of the core contributors to the project so they get a notification.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
Rebased, lets see how it goes.

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/191946804541116/int_phab) to review.

**Comment by JoelMarcey** [comment]
It shipped!

**Comment by JohnyDays** [comment]
Thanks so much for this, I've been using it an app and winging it from examples, this is awesome!

**Pull request closed without merging**
