### PR TITLE
Fix unit tests in open source environment

### PR DESCRIPTION
**Pull request by davidaurelio**
**Test plan**

run `npm test`, see all tests pass

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by davidaurelio** [comment]
@facebook-github-bot import

**Pull request closed without merging**
