### PR TITLE
Block url requests with regex prop and notify javascript about the ev…

### PR DESCRIPTION
**Pull request by younthu**
**motivation** 
An alternative solution for [onShouldStartLoadWithRequest callback](https://github.com/facebook/react-native/pull/6478)

It is common case to block some urls and get called back to do something else, we did it in our project with regex prop to satisfy our requirement,  may others has the same requirement, so extracted the code out for all others use.

**Usage**

~~~
<WebView ref="webview" 
                   source={{uri:"https://www.google.com"}}
		    onUrlBlocked={(event)=>{
			    alert("url blocked");
		    }}
		    blockList={[".*mail.*"]} // it will block link to any link contains 'mail' in current page, for this example, it will block link to gmail
		> 
</WebView>
~~~

### CODE REVIEW

**Comment by hramos** [comment]
I'm not sure if adding this to the core component is the best approach. I would be OK with this functionality existing as part of a third party WebView component. With that said, I'll close this PR.

**Comment by bartolkaruza** [comment]
@hramos  Have you read the whole thread at #6478 where a feature parity proposed solution was declined by @astreet in favor of an approach similar to this PR? Thousands of developers are running into the issue of RN Android not supporting url overriding for Webviews properly and they are all led through a long maze with a disappointing ending, here. 
The progress on this very real issue has been 0 since #6478 was closed by @pglotov due to pushback from @astreet and #12178 was closed without proper consideration of the PR.

Should we not consider getting either of these two PR's or some third option that _just works_ into the RN core a top priority?

I know it is a hard problem, but consider the implementer; On a native Android app, this is a trivial issue, by simply implementing the shouldOverrideUrlLoading interface method. When adding React Native to the native app, it becomes an extremely complex issue. Not only do you have to implement the `WebViewClient`, but you now have to extend a RN View manager and figure out how to replicate the built in `ReactWebViewClient` which is not accessible to implementers in a protected inner class, [here](https://github.com/facebook/react-native/blob/d71d28f09495a1e2802db169e2d0cd1ec5bd5973/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java#L111).

Considering the average implementer will not have a lot of native experience, asking them to do things that are harder than it would be for a native Android developer, does not seem right. The framework should do the hard work to make requirements like this trivial to implement. To make that work, I think we should do the hard work to help contributors get their valuable fixes and improvements landed.

**Comment by bartolkaruza** [comment]
On closer inspection, the extension is easier than it used to be, using https://github.com/facebook/react-native/pull/14261 and https://github.com/cbrevik/overrideWebview/blob/master/android/app/src/main/java/com/overridewebview/CustomWebViewManager.java , but still..

**Comment by 0x5e** [comment]
In my situation, block list can't help, white list is needed, then this feature will be complicated 😅

**Pull request closed without merging**
