### PR TITLE
[Image] Improved loading of Assets Library and Photos Framework images.

### PR DESCRIPTION
**Pull request by aroth**
Update to https://github.com/facebook/react-native/pull/1969

--
Recent improvements allow RCTImageLoader to select a more appropriate sized image based on the layout dimensions. Sizes:

	- asset.thumbnail
	- asset.aspectRatioThumbnail
	- asset.defaultRepresentation.fullScreenImage
	- asset.defaultRepresentation.fullResolutionImage

Prior, only the fullResolutionImage was used. This was memory intensive and resulted in crashes when loading several large images at once. The updated implementation works well, but can be made more efficient:

Consider loading 10 8MP (3264x2448) images in 150x150 pixel containers. The target size (150x150) is larger than asset.thumbnail (approx 100x100), therefore the fullScreenImage representation is used instead (approx 1334x1000).

This commit will scale the asset to the minimum size required while taking into account original aspect ratio and device scale. Memory usage is considerably lower and many more images can be loaded in 
sequence without having to worry about memory warnings/crashes.

Memory comparison:

... | Master | This PR
---- | ------------ | -------------
8MP image to 150x150 thumb | 5.2mb (scaled to 1334x1000) | 468kb (scaled to 400x300)
8MP image to 320x240 thumb | 5.2mb | 1.2mb
100 images from camera roll 150x150 | 176.2mb spike | 138.3mb spike

Additional reading:
http://www.mindsea.com/2012/12/downscaling-huge-alassets-without-fear-of-sigkill/

Support has been added for both ALAssets and Photos Framework.

Also added additional example: tap an image from the Camera Roll Example to see multiple versions of the image at different resolutions.

screen shot 2015-07-15 at 2 30 47 pm

### CODE REVIEW

**Comment by aroth** [comment]
@nicklockwood I've closed #1969 and created this new PR. Thanks.

**Comment by myusuf3** [comment]
:100: Currently seeing crashes when trying to use full resolution images here. This fixes the issue for us and gives a flexibility to choose how we want to do things! Nice work @aroth

**Comment by josebalius** [comment]
+1 can't wait for this to land.

**Comment by brentvatne** [comment]
@nicklockwood @tadeuzagallo @a2 - if any of you get a chance to look at this it would be appreciated! I know it's not high priority for Facebook at the moment but it looks like a recurring OSS issue. Related: #902, #1704

**Comment by myusuf3** [comment]
:100:

**Comment by kevingalvez-pro** [comment]
has this been included in recent releases?

**Pull request closed without merging**
