### PR TITLE
RN: Upgrade ESLint Packages

### PR DESCRIPTION
**Pull request by yungsters**
## Summary

Upgrades ESLint to v7.28.0. This is the latest version before v8.0.0, which would be a more involved upgrade.

Upgrades all ESLint-related dependencies to their latest version, except for [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype/). This is because eslint-plugin-flowtype@8.0.0 dropped support for ESLint v7.

## Changelog

[General][Changed] - Upgraded packages to the latest versions for ESLint v7.

## Test Plan

```
# See no new errors or warnings.
$ yarn run lint
```

### CODE REVIEW

**Comment by wcandillon** [comment]
For this to work with eslint 8 and typescript, the eslint-typescript plugin needs to be upgraded to the latest version (5.4.0).

@yungsters you would like me to do a PR for it?

**Comment by yungsters** [comment]
@wcandillon, sure! Thanks.

**Comment by Kerumen** [comment]
@wcandillon Were you able to set up a PR to upgrade the eslint-typescript plugin to support eslint v8? 🙏🏻

**Comment by wcandillon** [comment]
@Kerumen yes at #33448

**Pull request closed without merging**
