### PR TITLE
Update Gradle wrapper to 4.10.3

### PR DESCRIPTION
**Pull request by friederbluemle**
## Summary

Projects generated with the **latest stable version of Android Studio** come with Gradle wrapper `4.10.1`. The [Gradle documentation](https://docs.gradle.org/4.10.3/release-notes.html) states:

> NOTE: Gradle 4.10 has had three patch releases. You should use the latest patch release (4.10.3).

Currently, `react-native` is using `4.10.2`. This PR brings Gradle wrapper from `4.10.2` to `4.10.3`. Updates were automatically performed using the `gradle wrapper` task.

Related: #23324

## Changelog

[Android] [Added] - Update Gradle wrapper to 4.10.3

## Test Plan

Regular testing. No changes.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Rebased onto latest `master`.

**Comment by hramos** [comment]
We're updating to Gradle 5.0 in https://github.com/facebook/react-native/pull/23324.

**Comment by friederbluemle** [comment]
@hramos - Thanks for your comment. Yes, I know - That's why I linked the PR in the description :) As much as I applaud the usage of newer versions, don't you think it would be advisable to keep the Gradle wrapper version in sync with whatever the currently used Android Gradle plugin officially supports? For Android Gradle plugin `3.3.0` and `3.3.1` (the latest) that is Gradle `4.10.x`.

**Comment by hramos** [comment]
I'll let you and @dulmandakh sort this out.

**Comment by hramos** [comment]
I'm going to close this, as #23324 is landing. Happy to hear any arguments in favor of downgrading to 4.10.3 from 5.0. I'm following @dulmandakh advice given he has been actively sending PRs to upgrade our Gradle config over the past year.

**Pull request closed without merging**
