### PR TITLE
[RFC] Pass props (information) to view constructor

### PR DESCRIPTION
**Pull request by frags51**
## Summary
(This is a draft PR, looking for feedback on this change)

One of our use cases involves the creation (construction/init) of a Native Component view based on some information (variables/props) from JS. Change in that information (prop) doesn't need to cause any re-render or updates in the native component. Right now, there is no way to achieve this.

I was wondering if it's possible to modify the createView method so that it passes props (it could be a new entity as well, e.g. constructionProps, but the thing is we already have props being passed from JS so this would involve least amount of change) to the view() defined in the Native Component's view manager. It could be documented that these props are subject to change due to batched updates etc and should not be relied upon for any rendering apart from View Creation.

Suggestions to achieve this in some other way are appreciated. For e.g. one way could have been to create a subview, and modify that based on whenever props are set. However, that approach doesn't work very well for us because we are extending another native component, and then need to pass (set) all the props to that component as well and might cause layout issues as well.

I wanted to understand why that functionality hasn't been provided in RN so far. Is this whole design pattern incorrect?

## Changelog

[IOS] [ADDED] - Add props as an optional argument to view().

### CODE REVIEW

**Comment by XantreGodlike** [comment]
Hi. Why you cannot use ref prop for it. Or give another name for that prop. Thus, when the child component changes this props, the parent component will still have access to that data from the ref

**Comment by frags51** [comment]
> Hi. Why you cannot use ref prop for it. Or give another name for that prop. Thus, when the child component changes this props, the parent component will still have access to that data from the ref

Could you provide a code sample? Right now there is only a single component; no parent child relation. The goal is to construct the view based on some logic at JS side

**Comment by frags51** [comment]
Bump

**Comment by philIip** [comment]
why don't you want your component to rerender after updating a prop? what type of information does this component needs that does not impact its layout or behavior?

**Comment by sammy-SC** [comment]
Hello @frags51,

thank you for taking the time to write up this RFC.

I would like to better understand your use case. Why are you trying to avoid re-render? I'm primarily curious to know whether there is a reason beyond performance. To tackle expensive re-renders, I recommend profiling your app with React DevTools to see what is causing the re-renders. React has several ways to make re-renders faster, like [useCallback](https://react.dev/reference/react/useCallback) and [useMemo](https://react.dev/reference/react/useMemo). 

Also, what would this look like from JavaScript side. How will users distinguish between props that do cause re-render and the ones that don't?

**Pull request closed without merging**
