### PR TITLE
[Navigator] Fixed a tiny coding mistake

### PR DESCRIPTION
**Pull request by cauchywei**
When I try to read Navigator.js, I found a tiny mistake in line 1099
```JavaScript
return (this.state.transitionFromIndex != null) || (this.state.transitionFromIndex != null);
```
I think the code  may be written as follow accorrding to the context:
```JavaScript
return (this.state.transitionFromIndex != null) || (this.state.activeGesture != null);
```

### CODE REVIEW

**Comment by ide** [comment]
Can you describe how you tested this change?

**Comment by cauchywei** [comment]
@ide  it is easy to test.

image


According to `transitionFromIndex` and `activeGesture`'s value, handlers dealing with (directly) transition  and gesture ( swipe left to right to go back pre-scene)  to ensure transition work right between scenes.

```JavaScript
/**
   * This happens for each frame of either a gesture or a transition. If both are
   * happening, we only set values for the transition and the gesture will catch up later
   */
  _handleSpringUpdate: function() {
    ......
    // Prioritize handling transition in progress over a gesture:
    if (this.state.transitionFromIndex != null) {
      ......
    } else if (this.state.activeGesture != null) {
       ......
    }
  },


onAnimationStart: function() {
    ......
    if (this.state.transitionFromIndex != null) {
      ......
    } else if (this.state.activeGesture) {
      ......
    }
    ......
  }
```

It means  `transitionFromIndex` and `activeGesture`' at least one is non-null when I try to pop, push or swipe back, so the scene container should capture the touch event to prevent a button  or something to become a responder while I swiping back ( Although it is difficult to trigger ) .

**Comment by facebook-github-bot-1** [comment]
@cauchywei updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@janicduplessis would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
@cauchywei Have you reproduced a bug caused by this line being wrong?

Would it make sense to change the line to:

    return (this.state.transitionFromIndex != null);

To keep the current behavior?

**Comment by mkonicek** [comment]
Thanks for the detailed example!

**Comment by lacker** [comment]
It looks like this pull request is abandoned. I'm going to close it, but please feel free to reopen if you are in fact still working on it.

**Pull request closed without merging**
