### PR TITLE
Update to Xcode 7.3 on Travis

### PR DESCRIPTION
**Pull request by spicyj**
Hopefully this will fix https://travis-ci.org/facebook/react-native/jobs/123444671.

### CODE REVIEW

**Comment by ide** [comment]
There are some warnings and errors in the tests:

I think `ld` is trying to process an option called `-F${entirePathAsPartOfTheFlagsNameLol}`:
```
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/Developer/Library/Frameworks'
```

```
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-10174/DVTFoundation/FoundationClassCategories/DVTNSBundleAdditions.m:24
Details:  Assertion failed: [NSThread isMainThread]
Function: NSBundle *_DVTFoundationBundle()
Thread:   <NSThread: 0x7fe09866f6b0>{number = 2, name = (null)}
Hints: None
Backtrace:
  0   -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _DVTAssertionFailureHandler (in DVTFoundation)
  4   _DVTFoundationBundle (in DVTFoundation)
  5   -[DVTDeveloperPaths _developerFolderPath] (in DVTFoundation)
  6   -[DVTDeveloperPaths init] (in DVTFoundation)
  7   __33+[DVTDeveloperPaths defaultPaths]_block_invoke (in DVTFoundation)
  8   _dispatch_client_callout (in libdispatch.dylib)
  9   dispatch_once_f (in libdispatch.dylib)
 10   +[DVTDeveloperPaths defaultPaths] (in DVTFoundation)
 11   __60+[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 12   _dispatch_client_callout (in libdispatch.dylib)
 13   dispatch_once_f (in libdispatch.dylib)
 14   +[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:] (in DVTiPhoneSimulatorRemoteClient)
 15   __41+[DTiPhoneSimulatorSystemRoot initialize]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 16   _dispatch_client_callout (in libdispatch.dylib)
 18   +[DTiPhoneSimulatorSystemRoot initialize] (in DVTiPhoneSimulatorRemoteClient)
 19   _class_initialize (in libobjc.A.dylib)
 20   lookUpImpOrForward (in libobjc.A.dylib)
 21   objc_msgSend (in libobjc.A.dylib)
 22   +[SimulatorInfo _systemRootWithSDKVersion:] (in xctool)
 23   -[SimulatorInfo systemRootForSimulatedSdk] (in xctool)
 24   -[SimulatorInfo simulatedRuntime] (in xctool)
 25   -[SimulatorInfo simulatedDevice] (in xctool)
 26   CreateTaskForSimulatorExecutable (in xctool)
 27   -[OCUnitIOSLogicTestQueryRunner createTaskForQuery] (in xctool)
 28   -[OCUnitTestQueryRunner runQueryWithError:] (in xctool)
 29   +[TestableExecutionInfo queryTestCasesWithSimulatorInfo:error:] (in xctool)
 30   +[TestableExecutionInfo infoForTestable:buildSettings:simulatorInfo:] (in xctool)
 31   __56-[RunTestsAction runTestables:options:xcodeSubjectInfo:]_block_invoke (in xctool)
 32   _dispatch_call_block_and_release (in libdispatch.dylib)
 33   _dispatch_client_callout (in libdispatch.dylib)
 34   _dispatch_queue_drain (in libdispatch.dylib)
 35   _dispatch_queue_invoke (in libdispatch.dylib)
 36   _dispatch_root_queue_drain (in libdispatch.dylib)
 37   _dispatch_worker_thread3 (in libdispatch.dylib)
 38   _pthread_wqthread (in libsystem_pthread.dylib)
 39   start_wqthread (in libsystem_pthread.dylib)
```

```
./scripts/objc-test.sh: line 32:  2202 Abort trap: 6           xctool -project Examples/UIExplorer/UIExplorer.xcodeproj -scheme UIExplorer -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.2' test
```
^ should this say OS=9.3?

**Comment by spicyj** [comment]
I was hoping the DVT stuff was transient but I restarted and the same thing happened so I guess not. Not sure how to fix the `ld` args…

> ^ should this say OS=9.3?

I don't think it matters.

**Comment by ide** [comment]
The ld args might be fine, depending on its option parser, though it's probably prudent to quote the path string just in case.

The reason I thought OS=9.3 might be necessary is because the Xcode 7.3 machines might not have the 9.2 simulator.

Anyway looks like xctool is bad: https://github.com/facebook/xctool/issues/684. Can you try changing `brew reinstall nvm` to `brew reinstall nvm xctool`?

**Comment by spicyj** [comment]
Ooh good eye.

**Comment by ide** [comment]
And FWIW the XCode 7.3 machines do come with the 9.2 simulator so I think we're OK there unless FB is internally running screenshot tests with 9.3 (which might be the case?). https://docs.travis-ci.com/user/languages/objective-c/#Xcode-7.3

**Comment by spicyj** [comment]
Looks like we are doing 9.3 internally now. I'll update.

**Comment by spicyj** [comment]
Looks like the JS tests are failing with flow errors? Going to assume that's not my fault. The objc test works now.

**Comment by ide** [comment]
The Obj-C E2E test failed since it stalled so I restarted it. If it turns green let's ship this.

**Comment by spicyj** [comment]
Stalled again.

**Comment by spicyj** [comment]
:\

**Comment by bestander** [comment]
Latest restart fails because of immutable.js update to 3.8.0
This should fix: https://github.com/facebook/react-native/pull/7014

**Comment by bestander** [comment]
To unblock trunk I'll ship your code, thanks for doing the fix.
Immutable fix should land about the same time.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
And yeah, I am not sure that tests stall, they are just very slow.

**Pull request closed without merging**
