### PR TITLE
Fixes ActivityIndicatorIOS doesn't hide initially in 0.27

### PR DESCRIPTION
**Pull request by redmar**
I used the reproducible steps as described in origin bug ticket #7987 as test plan.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by janicduplessis** [comment]
Can you submit the PR on master instead of 0.27-stable, we can cherry pick it into the next release after. Also don't forget to sign the CLA, thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by javache** [comment]
Duplicate of #8134

**Pull request closed without merging**
