### PR TITLE
[WIP] [Not for Merge] Disable ReactPerf and Update Systrace React Integration

### PR DESCRIPTION
**Pull request by gaearon**
This is a work in progress, not for merge yet.

We will likely disable ReactPerf in Fiber because it's not clear how to make it work correctly, and whether the heuristics it used even make sense in Fiber.

Instead, we are now hooking into [User Timing API](https://github.com/w3c/user-timing) API if one is available in the environment, to report the React measurements. In this PR, I applied an RN sync manually (which is necessary to test this change until we land Fiber support), and implement the necessary User Timing API subset on top of Systrace in the second commit. The corresponding React PR is at https://github.com/facebook/react/pull/9071.

* First commit: React sync + enabling Fiber (irrelevant to this PR) https://github.com/facebook/react-native/commit/666a00498ec4705f785d69b35bfac8c9a944d7c1

* Second commit: Replace React debugging code with a User Timing polyfill for Fiber https://github.com/facebook/react-native/commit/4fb86f7d5f3f9be76fec7d59de9808a0404d1821

screen shot 2017-03-08 at 1 51 30 pm

The result is more or less equivalent to the Systrace React integration we had before, although it also displays some Fiber-specific features (such as a separate commit phase). It also doesn't rely on private React APIs and is consistent with what we use for the browser, so we shouldn't be breaking this integration again in the future.

One unfortunate problem here is that there is no way to re-label Systrace measurements after they happened. In the browser, we are able to rename measurements to include warning messages (since by the time the measurement ends, we know if user did some bad pattern). However, `Systrace` can only include the label when starting the measurements, so the warnings are not exposed.

### CODE REVIEW

**Comment by gaearon** [comment]
cc @bvaughn — this is for me to pick up after you do the next sync

**Comment by bvaughn** [comment]
@gaearon FYI landed the 16.0.0-alpha.4 sync yesterday

**Comment by sdeleon28** [comment]
What's the status of this? Is there currently any way to profile JS Thread events? I'm really struggling to pinpoint performance bottlenecks with current tooling 😞

**Comment by bvaughn** [comment]
@sdeleon28 For what it's worth, the new DevTools profiler plug-in will support the next React Native release.

**Comment by sdeleon28** [comment]
@bvaughn that's useful info. Thanks!

Still doesn't change the fact that I have zero tools to identify the bottleneck I'm currently facing, tho :(

I'm going to give `console.time` and `console.profile` a try. Less than ideal, but this is my last resort - _Suffocation / No breathing / Don't give a BLEEP if I cut my arm, bleeding_

**Pull request closed without merging**
