### PR TITLE
Use "typos" tool to bulk detect/correct typos in RN core code

### PR DESCRIPTION
**Pull request by rshest**
Summary:
## Changelog:
[Internal] -

While merging a Contributor PR in D43816768, I got curious whether such things as detecting/fixing typos could be automated.

There is a tool called [typos](https://github.com/crate-ci/typos), which, as it turns out, works very well on source code files.

The amount of false positives was minimal, most of the suggestions were valid ones.

And the total amount of typos found and fixed was more than 300, which is... quite a bit :)

### Metodology

* Run `typos` separately on `ReactCommon`, `Libraries`, `React`, `ReactAndroid` and `scripts` folders inside `packages/react-native`, e.g.:
```
$ typos -w --config ~/tmp/_typos.toml ~/fbsource/xplat/js/react-native-github/packages/react-native/ReactAndroid
```

Contents of the `_typos.toml` config file:
```
[default.extend-words]
collapsable = "collapsable"
NDK = "NDK"
inout = "inout"
```

(yeah, it really didn't like the "collapsable" word, for some reason ;))
* Inspect all the changes manually and revert false positives (as mentioned, their amount was minimal)

Note that most of the changes are inside things like comments and error messages, however there are a few among identifier name fixes (`typos` is actually quite smart at understanding naming conventions in code) - I kept the suggestions in cases that are local and not part of a public API. There are also misspelled file name changes in a couple of cases.

Differential Revision: D44172494

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
@rshest This is awesome! Btw, will it be possible to add `typos` as dev dep and keep its config file in the root, and a `typos` script in package.json?

That way the authors can run the script (only for their changes) by passing cli args to the dir/sub-dir to check the typos _before_ pushing the diff to the remote/upstream. (Obvio the script would require some minor changes to handle args from cli.)

Another thing we would like to keep in mind is that **_not_** making it mandatory like those pre-commit hooks 🙂 (thank god, we don't have them here). Instead, we can make it mandatory in _CI_ just like linter if we want to...

Lmk WDYT; I'll be happy to submit a PR for this :)

**Comment by rshest** [comment]
> Closing as this landed in [b9c64f3](https://github.com/facebook/react-native/commit/b9c64f3651ac87a1495acead12500d51a4938036)

@cortinico My bad, sorry, I must have forgotten to export the latest change there. Thanks for taking care of this!

**Comment by rshest** [comment]
> @rshest This is awesome! ~Btw, will it be possible to add `typos` as dev dep and keep its config file in the root, and a `typos` script in package.json?~
> 
> Edit: It seems they don't have npm pkg, so what we can do is we can keep the config file in the root as mentioned. If authors want they can download the platform-specific bin. Also, we can try the CI setup btw...
> 
> That way the authors can run the script (only for their changes) by passing cli args to the dir/sub-dir to check the typos _before_ pushing the diff to the remote/upstream.
> 
> Another thing we would like to keep in mind is that **_not_** making it mandatory like those pre-commit hooks 🙂 (thank god, we don't have them here). Instead, we can make it mandatory in _CI_ just like linter if we want to...
> 
> Lmk WDYT; I'll be happy to submit a PR for this :)

Hey Pranav! Thanks for the input, and I think that's a sound idea in general!

We should consider, however, whether the benefit from adding the extra moving part would outweigh the cost of maintenance, running and dealing with potential breakages and people consequently losing time, caused by this very moving part.

Would be happy to hear opinions here :)

**Comment by Pranav-yadav** [comment]
Yeah. It may create extra chaos.

> whether the benefit from adding the extra moving part would outweigh the cost of maintenance

From my initial observations the tool doesn't even take 1sec to scan whole codebase (provided the codebase is already scanned once, and has fixed number of typos).

> running and dealing with potential breakages and people consequently losing time, caused by this very moving part.

True. FYI, [I'll be experimenting](https://github.com/reactjs/react.dev/pull/5767#issuecomment-1477152998) with the [typos gh-actions](https://github.com/crate-ci/typos/blob/master/docs/github-action.md) on none other than [**React.dev** repo](https://github.com/reactjs/react.dev) ci :)
So, hopefully we'll be able to use those insights and finding and we can move forward this discussion _afterwards_.

**Comment by rshest** [comment]
> True. FYI, [I'll be experimenting](https://github.com/reactjs/react.dev/pull/5767#issuecomment-1477152998) with the [typos gh-actions](https://github.com/crate-ci/typos/blob/master/docs/github-action.md) on none other than [**React.dev** repo](https://github.com/reactjs/react.dev) ci :) So, hopefully we'll be able to use those insights and finding and we can move forward this discussion _afterwards_.

Oh, that's great! Let's test drive this on the React repo, then, and if that works well - by all means, please feel free to make a PR for integrating it in RN :)

**Pull request closed without merging**
