### PR TITLE
fix npm start can't work

### PR DESCRIPTION
**Pull request by haiyangjiajian**
In docs/IntegrationWithExistingApps.md, the "npm start" can't work . Replace "npm" with "react-native". The screenshots are as below
include
include

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@lacker or @hramos Can you corroborate whether this is indeed true?

**Comment by lacker** [comment]
The instructions in this doc explain how to set up your package.json so that `npm start` works. So that should be the way to go. If you omit that part, though, then `npm start` won't work. So I think we should leave the docs as is. I'm going to close this issue but if I am missing something let's continue the discussion.

**Comment by haiyangjiajian** [comment]
Sorry, I checked my package.json and  found out that I put "start": "node node_modules/react-native/local-cli/cli.js start" in the wrong place. It is just like this:
```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "start": "node node_modules/react-native/local-cli/cli.js start",
```
The doc works well, it's my carelessness.

**Comment by lacker** [comment]
Cool, I'm glad you figured it out!

**Pull request closed without merging**
