### PR TITLE
Update RCTUtils.m

### PR DESCRIPTION
**Pull request by kesjien**
Ceiling values. Regarding to #2018

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

Regarding https://github.com/facebook/react-native/issues/2018

Text rendered on all plus devices 3x scale only on real devices without splashscreen installed through images.xassets ,show superfluous lines, seems like text's border.

Also with the zoomed mode on other ios devices.

### CODE REVIEW

**Comment by kesjien** [comment]
PR just for an information

**Comment by ide** [comment]
I'm not sure this is right -- the purpose of this function is to round up to the nearest physical pixel and not the nearest logical point. Perhaps one of the callers of this function should be calling a different rounding function?

**Comment by kesjien** [comment]
True. Im sure it is not the right fix but it points out on the problem. Anyway this way of rounding is not clear for me.

**Comment by javache** [comment]
This rounds a value to the nearest pixel value (e.g. on an iPhone 6+ passing 6.4f will round it to 6.333f, while on an iPhone 6 it'll be 6.5f).

**Pull request closed without merging**
