### PR TITLE
Travis CI reliability fixes: preload package manager and increase tim…

### PR DESCRIPTION
**Pull request by dlowder-salesforce**
- Consolidate common code in iOS and tvOS test scripts
- Start the packager before starting tests, to improve reliability
- Increase timeout value in RCTTestRunner.m

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
@bestander here is my first cut at Travis reliability improvements....

**Comment by bestander** [comment]
Very nice, @dlowder-salesforce!
Thanks for finding some time for that.
Let's wait for travis to report.

**Comment by javache** [comment]
@bestander What's going on with Travis queue times? This PR was opened 15 hours ago and Travis still hasn't started a run.

**Comment by dlowder-salesforce** [comment]
@javache @bestander : 

Update - We apologize for the extended delays. We've completed needed work to help stabilize things and try to improve our overall throughput. We are beginning to resume builds. 
Oct 14, 04:45 UTC
Update - The maintenance is taking longer than expected but we hope to resume builds shortly 
Oct 14, 03:29 UTC

**Comment by bestander** [comment]
Yeah, the queue is piling

**Comment by dlowder-salesforce** [comment]
Still seeing some random failures in the PropertyUpdateTest.  Also it seems like sometimes in the Travis environment, the simulator won't start, or takes too long to start.

**Comment by bestander** [comment]
I'll restart a few times, let's see if  it is already an improvement

**Comment by christopherdro** [comment]
Looks like tvOS is the only test that fails now. Going to give it another restart to get an updated status.

**Comment by dlowder-salesforce** [comment]
OK I think I see what the tvOS problem is... will update this PR soon.

**Comment by dlowder-salesforce** [comment]
OK now in Travis CI, the objc-test is passing for both iOS and tvOS, but I see a bizarre failure in the bezier JS test... I don't see that failure in my local environment.

**Comment by bestander** [comment]
Awesome, don't worry about the bezier test, I'll deal with it

**Comment by christopherdro** [comment]
I restarted it and it passed. 👏

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
