### PR TITLE
Add support for resource-id

### LINKED ISSUE #9777: Add support for resource-id
### Issue Description

There currently isn't a way to find elements by resource-id using appium/uiautomatorviewer.

`react-native` currently supports `contentDescription` via `accessibilityLabel`.  This is great for clickable elements, but not so great for testing other things like splash screen visibility.

I'd be more than willing to add support for this, but am currently not aware of how `react-native` builds the android views.  If someone could give me some guidance on how `android:id` could be added to a view then I'd most certainly be willing to give it a shot.  My understanding of `android:id` (per the [View docs on IDs](https://developer.android.com/reference/android/view/View.html)), is that it must be set in the XML prior to view creation.

I don't believe this is a duplicate of #7135, because I'm not proposing that we break the way testID currently works, more that I feel it would be nice if `testID` could add it's value to the corresponding view component in the XML.
### Steps to Reproduce / Code Snippets
- Add `testID="something"` to any component (e.g. `View`)
- Run the app on an android device
- Run `uiautomatorviewer`

You'll notice that `resource-id` is empty

without-id
#### Expected Results

`resource-id` has a value like `com.myApp:id/something`
### Additional Information
- React Native version: `0.32`
- Platform(s) (iOS, Android, or both?): Android.
- Operating System (macOS, Linux, or Windows?): All

### PR DESCRIPTION
**Pull request by lightboys22**
Track react tag using android.view.View.tag. Allow developers to set resource id by setting component.testID

Fixes #9777

## Test Plan

First, you need to declare the resource id by creating /_your_android_studio_folder_/res/values/ids.xml

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
<item type="id" name="my_test_id"/>
</resources>
```

Second, set the testID of your component to a resource name.

```
<Button
onPress={onButtonPress}
title="Press Me"
testID='test_id'
/>
```

Third, run the app and observe the resource id using UIAutomator viewer (/Android/sdk/tools/bin/uiautomatorviewer)

## Changelog

[ANDROID] [Fixes] - BaseViewManager: Allow developers to set resource id by setting component.testID

### CODE REVIEW

**Comment by craigrbruce** [comment]
@lightboys22 This is great work! I would suggest renaming `testId` as we have other applications for this facility beyond testing, namely gaining control of navigation (using a d-pad for example).

Perhaps a better name would be `resource-id`?

**Comment by hramos** [comment]
Is this a duplicate of https://github.com/facebook/react-native/pull/18527, which you also opened?

**Comment by cpojer** [comment]
@lightboys22 could you rebase this commit on master? Let's figure out how to get this merged!

**Comment by lightboys22** [comment]
@cpojer Hi Christopher,
You honored me with your presence. My team bypassed this issue by using Espresso. 

Although Espresso only allows us to find UI elements by it content-description, Espresso is good enough for us.

**Comment by harking** [comment]
@cpojer We've recently run into this again for some of our projects. Are you still open to including this fix?

**Comment by lightboys22** [comment]
@harking I am too lazy to continue to work on this pull request. My previous team was using Espresso, which allow you to find elements based on the “test-is” view tag.

**Pull request closed without merging**
