### PR TITLE
Added option to set mixed content mode in android webview

### PR DESCRIPTION
**Pull request by prabakarviji**
PR for option to set mixed content mode in Webview(Android) for issue #8460

### CODE REVIEW

**Comment by lacker** [comment]
Is it possible to make this work the same way in both iOS and Android? Adding this feature to one and not the other seems a bit technical-debty.

**Comment by mehraan** [comment]
@lacker I don't think it can be done in the same fashion in iOS, as it is not an option on the WebView. On iOS, you'd need to configure it per domain in the `Info.plist`.
See the App Transport Security section in the [Apple Documentation](https://developer.apple.com/library/content/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html#//apple_ref/doc/uid/TP40016198-SW1).

**Comment by prabakarviji** [comment]
@mehraan +1

**Comment by lacker** [comment]
I guess that is intuitive. Does this change end up clearly reflected in the docs, specifically the Androidy nature of it? I'm not sure how the autogen docs will pick it up but you can check by running a local website copy. If it does just work then could you paste a screenshot here?

**Comment by prabakarviji** [comment]
No @lacker . It doesn't picking.

**Comment by prabakarviji** [comment]
@lacker Any update on this PR?

**Comment by lacker** [comment]
Can you figure out how to make the docs reflect this change?

**Comment by prabakarviji** [comment]
@lacker Added documentation for `mixedContentMode`.

**Comment by prabakarviji** [comment]
@lacker Updated the PR.

**Comment by prabakarviji** [comment]
@lacker Any update regarding this PR?

**Comment by lacker** [comment]
It looks pretty good to me. Can you fix the conflicts and I'll merge?

**Comment by prabakarviji** [comment]
@lacker Removed conflicts and updated.

**Comment by lacker** [comment]
Circle seems borked, set it to run again.

**Comment by prabakarviji** [comment]
@lacker It seems like all checks have passed. :)

**Comment by prabakarviji** [comment]
@lacker It's seems like all checks have passed. Can you merge it ?

**Comment by mkonicek** [comment]
Failed with what looks like an unrelated error. Retrying merge.

**Pull request closed without merging**
