### PR TITLE
Request toolbar layout after drawable loads

### LINKED ISSUE #11209: ToolbarAndroid Actions Disappear On Change With Input Focus
### Description

The actions seem to disappear when they are updated if an input is focused.  Updating the actions seem to work as long as no inputs are focused.

This did not happen on version 0.29 but breaks on 0.38.  I think that there is a related crash on 0.37, but it's more difficult to recreate.

### Reproduction

https://rnplay.org/apps/jFEJew

### Solution

Unknown.

### Additional Information

* React Native version: 0.38
* Platform: Android
* Operating System: MacOS & Linux

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
## Motivation

Fixes #11209

Updating action items in a `ToolbarAndroid`, or more specifically the native `ReactToolbar`, after the initial render presently will not always work as expected - typically manifesting itself as new action items not being displayed at all (under certain circumstances).

This seems to be happening because Fresco gets back to us asynchronously and updates the `MenuItem` in a listener. However when a keyboard is displayed the `Toolbar` is in a weird state where updating the `MenuItem` doesn't automatically trigger a layout.

The solution is to trigger one manually.

## Test Plan

This is a bit wacky, so I created a sample project:

https://github.com/Benjamin-Dobell/DynamicToolbar

`master` demonstrates the problem. Run the project, the toolbar action item is scheduled to update every 2 seconds. It works fine _until_ you give the `TextInput` focus. Once you give it focus the action item disappears and it never recovers (despite on-going renders due to state changes).

You can then checkout the `fixed` branch, run `yarn` again, and see that problem is fixed. This branch is using a prebuilt version of React Native with this patch applied. Of course you could (and probably should) also modify `master` to use a version of RN built by the Facebook CI (assuming that's a thing you guys do).

### CODE REVIEW

**Comment by smallpath** [comment]
Works like a charm in my case! thanks very much.

**Comment by Benjamin-Dobell** [comment]
I would really appreciate it if someone from Facebook could take a look at this.

This issue has been present for as long as I've been using React Native and it's a show stopper when trying to update the action bar dynamically on Android e.g. displaying/enabling a "check" (confirm) action item in response to valid text being entered in a text field.

It's just a simple single line fix. The test repository doesn't do anything complicated, I just needed to bundle up some action item images somewhere for testing. All the relevant test code is contained in one file:

https://github.com/Benjamin-Dobell/DynamicToolbar/blob/master/index.android.js

I've been having a lot of trouble making release builds with my current patched `master`-based fork (nothing to do with this patch, just seems to be due to `master` being a WIP), so I'd love to see this merged into an official release that I can rely on.

Thanks

**Comment by Benjamin-Dobell** [comment]
Awww, 0.45 was released without this being considered. Please don't let this fix slip into obscurity...

**Comment by shergin** [comment]
@Benjamin-Dobell  Could you please rebase it on master?

**Comment by Benjamin-Dobell** [comment]
@shergin Done.

**Comment by forki** [comment]
any news why this isn't merged?

**Comment by forki** [comment]
I can verify that this change also fixes #13780 - Please please please merge it.

**Comment by forki** [comment]
@Benjamin-Dobell one question:

using your repro works well when I use the apk. but with "reac-native.cmd run-android" I get:

image

we see the same thing when we try to use your fork against our app. Do you know what that issue might be?

**Comment by forki** [comment]
In https://github.com/facebook/react-native/pull/15120 I verified that this commit cherry-picked on master is green on CI. Please consider to merge and release it. It's really important for ud

**Comment by forki** [comment]
Something is flaky with the Travis build. But seems unrelated

**Comment by Benjamin-Dobell** [comment]
@forki Yeah, I just rebased in hope I'd see some green lights. 1 out of 2, that's not too bad :wink:

Regarding the packager issue you encountered; maybe just make sure you're using yarn (there's a `yarn.lock` but no `npm-shrinkwrap.json`) and clear the packager cache - otherwise I'm not too sure.

**Comment by forki** [comment]
We use yarn and we did git clean -xdf 
Anyway try to close and reopen the PR to rerun the Travis

**Comment by hramos** [comment]
@Benjamin-Dobell have you pushed your changes after rebasing? I don't see any new commits here. That should trigger Travis to run again.

**Comment by forki** [comment]
Yes he did. But Travis is flaky with unrelated issues

**Comment by forki** [comment]
@shergin what is the status here? Anything we can do to help?

**Comment by forki** [comment]
💋

**Comment by forki** [comment]
any chance this can be merge into 0.47-stable? It's still not in RN 047-rc5

**Comment by hramos** [comment]
@forki you should comment on https://github.com/facebook/react-native/issues/14840

**Pull request closed without merging**
