### PR TITLE
Removed takeSnapshot util function from ReactNative renderer

### PR DESCRIPTION
**Pull request by bvaughn**
It was added to react-native-implementation in c7387fe

Relates to [this comment](https://github.com/facebook/react-native/commit/848593c0f0b75da9ff342596908c5091a2cd1430#commitcomment-21585552) and issue #13343

cc @janicduplessis

### CODE REVIEW

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
How do you handle syncing the ReactNative renderer? I didn't remove it in my initial PR since I thought React's repo was the source for that code.

**Comment by bvaughn** [comment]
It usually would go into React GH repo -> then eventually get synced to fbsource -> then find its way to ReactNative GH. In this case I'll do a manual upstream sync because I wanted to land it in RN GH as soon as possible.

**Comment by aloveb** [comment]
why

**Comment by aloveb** [comment]
how can I use the function to take snapshot now?
why there is an error, UIManager.__takeSnapshot is undefined?

**Comment by aloveb** [comment]
image

**Comment by bvaughn** [comment]
Not sure which version of react-native you're using. The line number shown for `ReactNativeStack-dev.js` in your stack trace doesn't quite line up to `takeSnapshot` for [the latest version, 0.47.1](https://unpkg.com/react-native@0.47.1/Libraries/Renderer/ReactNativeStack-dev.js).

That being said, [this is where `__takeSnapshot` is defined on `UIManager`](https://github.com/facebook/react-native/blob/c9aeaf675dcf0292d148950d0fb020eeb13d3af1/Libraries/ReactNative/UIManager.js#L24-L36). I haven't heard any other issues about it since this change landed 4 months ago. Have you, @janicduplessis?

**Comment by aloveb** [comment]
@bvaughn Thanks a lot for your response.

I also use the version 0.47.1, and debug the code in my local, UIManager.takeSnapshot is undefined.

image

UIManager.__takeSnapshot = UIManager.takeSnapshot;

and I use the code in android environment.
Does it support android or need any other setting?

Best

**Comment by janicduplessis** [comment]
@aloveb Just looked at the code and takeSnapshot is not implemented on Android.

**Comment by aloveb** [comment]
@janicduplessis Ok, thanks for your answer

**Comment by heluotian** [comment]
@aloveb I have the same problem, have you solved it?

**Pull request closed without merging**
