### PR TITLE
Native Animated - Restore, reorganize and add new tests

### PR DESCRIPTION
**Pull request by janicduplessis**
Native Animated tests were removed a while back because they were failing, this restores the existing tests and reorganize / cleanup them. It also adds new ones so we have at least one test for each public API. These tests mostly assert that the native animated module is called with the proper args.

### CODE REVIEW

**Comment by janicduplessis** [comment]
@cpojer Could you have a look at this or ping someone that can?

**Comment by janicduplessis** [comment]
I also had trouble generating coverage reports, pinged you about it on RN slack.

**Comment by cpojer** [comment]
Hey! I don't actually work on React Native itself. Just the react native packager.

cc @ericvicenti

**Comment by ericvicenti** [comment]
Ok, lets get this in. Having a test is a good way to document the current behavior, and it looks pretty well written, even though I haven't reviewed every line of it.

**Comment by mkonicek** [comment]
Looks like it failed in fb CI with:

```
FAIL  Libraries/Animated/src/__tests__/AnimatedNative-test.js
  ● Native Animated › Animated Events › should map events

    expect(jest.fn()).toBeCalledWith(expected)
    
    Expected mock function to have been called with:
      [1, "onTouchMove"]
    But it was called with:
      [1, "onTouchMove", 15]
      
      at Object.<anonymous> (Libraries/Animated/src/__tests__/AnimatedNative-test.js:172:64)
```

**Comment by mkonicek** [comment]
Trying again in case the PR has been updated since.

**Comment by janicduplessis** [comment]
@mkonicek Looks like some recent PRs to native animated broken this, fixing it.

**Comment by janicduplessis** [comment]
Fixed and added an extra test for Animated.loop which landed recently.

**Comment by janicduplessis** [comment]
@mkonicek You'll have to import this again.

**Comment by janicduplessis** [comment]
@ericvicenti Could you try landing this again?

**Pull request closed without merging**
