### PR TITLE
Update Image.ios.js

### PR DESCRIPTION
**Pull request by rbaron**
Fixed a tiny typo.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @charpeni to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by Kureev** [comment]
Sign CLA and I'll ship it

**Comment by JoelMarcey** [comment]
I am mobile. But wasn't this already fixed in master? Or maybe there is another PR out to fix it?

**Comment by Kureev** [comment]
Oh, I missed: we accept PRs only to master

**Pull request closed without merging**
