### PR TITLE
eslint config & plugin packages - prep for monorepo RFC

### PR DESCRIPTION
**Pull request by afoxman**
## Summary

The [monorepo RFC](https://github.com/react-native-community/discussions-and-proposals/pull/480) calls for renaming:

* `@react-native-community/eslint-config` -> `@react-native/eslint-config`
* `@react-native-community/eslint-plugin` -> `@react-native/eslint-plugin`

It also calls for the versions to be aligned with the rest of main -- currently `0.72.0`.

## Changelog

[General][Changed] - Renamed `@react-native-community/eslint-config` to `@react-native/eslint-config` v0.72.0 to align with other packages
[General][Changed] - Renamed `@react-native-community/eslint-plugin` to `@react-native/eslint-plugin` v0.72.0 to align with other packages

## Test Plan

First test is to run `yarn lint`, and verify that output matches before and after this change.

Second test is to change the ESLint config to use the "old" packages (under `@react-native-commnuity`) and run `yarn lint` to make sure that they work as expected. This is what customers will experience, until they manually move to the new ESLint packages.

### CODE REVIEW

**Comment by afoxman** [comment]
cc @cortinico Monorepo PR

**Comment by afoxman** [comment]
There are some errors from CircleCI about the new packages not being in NPM yet they are referenced as dependencies in the old packages. If you'd like, I can split this up so the new packages are published first, then land that, and make a 2nd PR to update the old packages, making them point to the new ones. I didn't do that initially because I know this is going to cause a lot of internal work, and I thought 2 PRs might increase that workload.

**Comment by afoxman** [comment]
cc @cipolleschi for tracking

**Comment by hoxyq** [comment]
Hey @afoxman,

Thanks for working on this, I am now planning to continue your work this and #34581 PRs. There are some changes that we need to introduce before merging this.

Could you please share if this is okay for you?

**Comment by afoxman** [comment]
> Hey @afoxman,
> 
> Thanks for working on this, I am now planning to continue your work this and #34581 PRs. There are some changes that we need to introduce before merging this.
> 
> Could you please share if this is okay for you?

Hi @hoxyq, definitely! Thank you for picking this up for me and pushing the monorepo forward.

**Comment by mm-webx** [comment]
Its not working: 
```yarn add --dev eslint prettier @react-native/eslint-config```

```error An unexpected error occurred: "https://registry.npmjs.org/@react-native%2feslint-config: Not found".```

**Comment by kelset** [comment]
@mm-webx I don't think it's expected to work yet, these new versions still need to be published. It will take time, for now you are not supposed to migrate to it.

**Comment by hoxyq** [comment]
> Its not working: `yarn add --dev eslint prettier @react-native/eslint-config`
> 
> `error An unexpected error occurred: "https://registry.npmjs.org/@react-native%2feslint-config: Not found".`

Hey @mm-webx, @kelset is correct, before we publish this package you can use `@react-native-community/eslint-config`, the instruction for it is [here](https://github.com/facebook/react-native/blob/0.71-stable/packages/eslint-config-react-native-community/README.md)

**Pull request closed without merging**
