### PR TITLE
Request permissions fix

### LINKED ISSUE #2290: [PushNotificationIOS] Unable to request permission
I get the error `registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.`

I am able to request permissions if i change 

#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_8_0 
to
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_8_0

Line no: 141 in 8.0
Line no 155 in current master

### PR DESCRIPTION
**Pull request by NishanthShankar**
#2290 Fix for request permission in [PushNotificationIOS]

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
@tadeuzagallo would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by ide** [comment]
Uhh... the concept of user notifications was added in iOS 8. Just reading the code, I don't think this PR is correct.

**Comment by tadeuzagallo** [comment]
That doesn't seem right... I don't think that should really be gated by the preprocessor in the first place.

@javache would you look at this? :D

**Comment by javache** [comment]
The gating here is correct, but this really should be a runtime check, assuming everyone is building with the iOS9 SDK.

**Comment by mkonicek** [comment]
@NishanthShankar I'll close this based on the comments above and the fact this PR is from August and needs rebasing. If you'd like to send a new PR that does the runtime check please feel free. Thanks for you contribution and I hope you'll continue to contributing to React Native in the future.

**Pull request closed without merging**
