### PR TITLE
Remove usages of RecyclerViewBackedScrollView in UIExplorer and NetworkOverlay

### PR DESCRIPTION
**Pull request by janicduplessis**
RecyclerViewBackedScrollView was deprecated, this removes usages in Examples as well as in NetworkOverlay.

**Test plan**
Tested that RecyclerViewBackedScrollView deprecation warning doesn't show up anymore.

### CODE REVIEW

**Comment by janicduplessis** [comment]
Let's try it again

@facebook-github-bot shipit-ninja

**Comment by janicduplessis** [comment]
@hramos Could you try shipping again?

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Yay landed!

**Pull request closed without merging**
