### PR TITLE
Remove old examples from RN repo

### PR DESCRIPTION
**Pull request by ericvicenti**
React Native originally shipped with these examples, which have gotten super old and unmaintained. 

Cruft like this in the core repo only slows us down with extra issues and pull requests. Eventually we may create a different repo for samples that will be maintained into the future.

We are doing some spring cleaning in the repo, so now is a good time to remove these and let the community share their own examples.

### CODE REVIEW

**Comment by ericvicenti** [comment]
After we remove the examples, we can close the following issues/pulls:

https://github.com/facebook/react-native/issues/7274
https://github.com/facebook/react-native/issues/12024
https://github.com/facebook/react-native/issues/12124
https://github.com/facebook/react-native/pull/11980
https://github.com/facebook/react-native/issues/7652
https://github.com/facebook/react-native/issues/11028
https://github.com/facebook/react-native/issues/12169
https://github.com/facebook/react-native/issues/12669

**Comment by ericvicenti** [comment]
I'll fix IntegratingWithExistingApps.md, but I think we should leave the blog post alone for now. If a cleaned up example gets published somewhere, then we can link to it.

**Comment by ericvicenti** [comment]
Actually, after looking through `IntegratingWithExistingApps.md`, it looks like it refers to a 2048 native app, rather than this JS implementation. So I think this is ready to land as-is.

**Comment by dlowder-salesforce** [comment]
It turned out that the 2048 game is a good example app to use to demonstrate use of the TVEventHandler for custom input handling on Apple TV, so I created a standalone repo for it at https://github.com/dlowder-salesforce/rn-tvos-example-2048 .

**Pull request closed without merging**
