### PR TITLE
Support/use Promises 

### PR DESCRIPTION
**Pull request by raphamorim**
I think that would be a good promises apply. Even for more complex tasks. What do you think?

I started developing locally using [bluebird](https://github.com/petkaantonov/bluebird) to "promisify" all functions. For now, I just sent half PR, without promises part. If agree, I'll add promises feature.

### CODE REVIEW

**Comment by vjeux** [comment]
What problem are you trying to solve with promisifying this file?

**Comment by raphamorim** [comment]
Not only this file. I would like to promisify tasks as extractDocs and generate, as would work better without getting depending on callbacks. What do you think?

**Comment by vjeux** [comment]
It's unclear to me what the benefits would be, all the extractDocs methods are synchronous so adding asynchronocity in the mix would only make the code harder to work with.

As for the server itself, it's working fine as is.

It's tempting to go around a codebase and use the latest shiny abstraction but you should only do that to solve problems. If there aren't problems, adding abstraction is a net negative operation

**Comment by raphamorim** [comment]
Gotcha, you're right. Valid only commits to log repair :)

**Pull request merged**
