### PR TITLE
website: Update prism regexes for better JavaScript code highlight

### PR DESCRIPTION
**Pull request by unexge**
Before:
screen shot 2017-05-19 at 20 01 28

After:
screen shot 2017-05-19 at 20 01 11

### CODE REVIEW

**Comment by janicduplessis** [comment]
cc @hramos

**Comment by hramos** [comment]
The updated syntax highlighting looks better, thanks! Since we're using Prism here, I wonder if we can simply update to a more recent version of Prism and get the same benefit, rather than diverge from the library here. What do you think?

**Comment by unexge** [comment]
Prism is not installed actually, it just a copy of Prism(with some modifications).

see: https://github.com/facebook/react-native/blob/master/website/core/Prism.js#L15

**Comment by hramos** [comment]
Right - do you think we can copy a newer version of Prism instead here? e.g. do newer versions support the updated syntax highlighting you're adding here?

**Comment by unexge** [comment]
i changed js regexes with last version of Prism regexes. do you mean update all Prism with the last version instead of just js regexes?

**Comment by hramos** [comment]
I think this approach works just fine. Thanks for the PR!

**Pull request closed without merging**
