### PR TITLE
Adding supported formats to Image component docs

### PR DESCRIPTION
**Pull request by franciscofsales**
## Motivation

The lack of very clear docs on supported image formats is causing unnecessary issues (#13806).
This should mitigate and keep the issue list cleaner.

## Test Plan

Its only a documentation change. No code changes made.

### CODE REVIEW

**Comment by L42y** [comment]
AFAIK, webp is not supported on iOS yet.

**Comment by franciscofsales** [comment]
@L42y I'm in the process of testing all the previous formats on both platforms, will confirm it soon

**Comment by franciscofsales** [comment]
Tested on real devices and documented it on [this repo](https://github.com/franciscofsales/react-native-image-format-test)

**Comment by brentvatne** [comment]
ha! I didn't know that iOS supported psd, neato.

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
