### PR TITLE
Bugfix: fix infinite loop on windows.

### PR DESCRIPTION
**Pull request by tdzl2003**
I try to run react-native on windows. both packager server and cli bundle meet a infinite loop.

Finally I found the reason:  root path on windows is not '/'

The better way is compare dirname with currDir self.

### CODE REVIEW

**Comment by ide** [comment]
LGTM

**Comment by tdzl2003** [comment]
Anyone tells me how can I stop adding extra commits into this pull-request?

**Comment by ide** [comment]
Your PR is from your master branch so all commits to to show up here. Commit to another branch for now and in the future do your PR work on separate branches and have master only track upstream.

**Comment by tdzl2003** [comment]
should I close this pr and resend it from another branch?

**Comment by ide** [comment]
Whatever is convenient for you.

**Comment by tdzl2003** [comment]
#2051 Resubmit at here.

**Pull request closed without merging**
