### PR TITLE
Fix RCTPicker crash

### PR DESCRIPTION
**Pull request by EngsShi**
If user slide picker when picker item is zero, `UIPickerViewDelegate` will call `pickerView:didSelectRow:inComponent` row=0, `_items[row][@"value"]` will crash.

### CODE REVIEW

**Comment by mkonicek** [comment]
Thanks for the fix! Are you saying that `row` was 0 and `_items.count` was 0 (there were no items in the picker)? How can that happen? Can you provide a screenshot please of what that picker looks like?

**Comment by EngsShi** [comment]
Yes. `row` was 0 and `_items.count` was 0.


image
Right picker were no items.

**Comment by mkonicek** [comment]
Ah so it happens when there are no items in the picker?

**Comment by danielfeelfine** [comment]
@EngsShi it's fix this https://github.com/facebook/react-native/issues/12829?

**Pull request closed without merging**
