### PR TITLE
Remove extra comma at the end of stringifySafe call

### PR DESCRIPTION
**Pull request by sdd330**

### CODE REVIEW

**Comment by ide** [comment]
I think these are intentional. https://github.com/facebook/react-native/commit/d9b7e63e47434ca0ace9b5fe4f11152cf31d002c

**Comment by sdd330** [comment]
Ok, got it

**Comment by cheunghy** [comment]
What does this for? Why adding trailing comma?

**Comment by sdd330** [comment]
For testing purpose maybe

**Comment by ide** [comment]
It's so that multiline function calls affect just one line of code if you add or remove an argument. Same thing as array and object literals.

**Pull request closed without merging**
