### PR TITLE
Mention in the docs how to install JS dependencies

### PR DESCRIPTION
**Pull request by xixixao**
I don't think this is the right place, but either I have completely missed it, or there is no mention of installing JS libraries anywhere in the docs. It works perfectly out of the box, but I think it deserves a concrete mention (along the lines of what I added). Perhaps it should be a separate page under "Guides"? I don't have a good solution, just wanted to raise this omission (the closest is mention of `import` in "Using Navigators").

### CODE REVIEW

**Comment by lacker** [comment]
Well, I agree this is not the right place. I think we could use a guide on modules in general - that you can use most plain-js libraries just with `npm`, there are some that you have to link, there's some that might not work, and instructions with how to a create and publish your own module. Would you be interested in writing up a doc like that?

**Comment by xixixao** [comment]
Unfortunately I am a complete n00b in regards to React Native, so have no clue about what's required besides the general `npm install`. But that content sounds really good!

**Comment by mkonicek** [comment]
I think having a section on Installing dependencies is a great idea!

However, the text added in this PR will confuse people - it only works for purely JS libraries, not for libraries that contain native code.

In general, people look for libraries here: https://js.coach/react-native

And then run:
- `npm install somelib` (or `yard add somelib` - it's the equivalent)
- `react-native link` (to link the native code into their Android or iOS build files)

This might work too although I'm not sure, can you try?
- `react-native install somelib` (it should do both steps above but not sure if it works)

**Comment by hramos** [comment]
Adding the text here is not ideal but I agree with the sentiment, this needs to be documented somewhere sane.

**Comment by hramos** [comment]
Closing as it doesn't seem like this will be merged.

**Pull request closed without merging**
