### PR TITLE
BREAKING: Remove @provides support from packager

### PR DESCRIPTION
**Pull request by jetzhliu**
see https://github.com/facebook/react-native/commit/d82f2553fb0da40b02ca5515767211105e2eec07

### CODE REVIEW

**Comment by janicduplessis** [comment]
cc @voideanvalue @davidaurelio

**Comment by janicduplessis** [comment]
Updated the title to better reflect what this is actually doing.

**Comment by mkonicek** [comment]
Pinged people on Messenger.

**Comment by davidaurelio** [comment]
fine with me. Let’s do this

**Comment by mkonicek** [comment]
Thank you for looking David!

**Pull request closed without merging**
