### PR TITLE
[iOS][cocoapods] Fixes import error in "RCTNativeAnimatedNodesManager.h" 

### PR DESCRIPTION
**Pull request by ceyhuno**
Fixes import error in "RCTNativeAnimatedNodesManager.h" mentioned at #13198. 
This same fix was included in #13217 but it was not merged.
Unfortunately #13785 didn't fix this problem.

### CODE REVIEW

**Comment by javache** [comment]
The import in the header needs to be namespaced, this is not a correct solution.

**Comment by guysegal** [comment]
@javache when using nameapace it's impossible to compile the code without a script that changes the import.
I know the non namespaced imports are deprecated but this is a long time blocker for anyone who uses cocoapods and wants to upgrade

**Comment by vjeranc** [comment]
This definitely worked on 0.44.0 after #13785

There was no need for namespace change.

**Comment by Igor1201** [comment]
@vjeranc Could you please tell us in what device configuration (OSX/Xcode version) are you able to build it?
Also, we're using cocoapods 1.2.1.

**Comment by guysegal** [comment]
I just doubled check, it's not working:

react native - 0.44.1
xcode - 8.3.2
cocoapods -  1.2.1 

We are using swift pods in the project so the podfile contains `use_frameworks!` declaration

**Comment by shergin** [comment]
Looks like we have to add this header to "Copy header files" build step inside for RCTAnimation project.

**Comment by guysegal** [comment]
if this will fix it that would be awesome.. :)

**Comment by ceyhuno** [comment]
`RCTValueAnimatedNode.h` is already under `Copy Files` build phase in `RCTAnimation` project

**Comment by shergin** [comment]
¯\_(ツ)_/¯

**Comment by esam091** [comment]
Any conclusion to this PR? can't get my project to build without hacks 😕

**Comment by timwangdev** [comment]
Please merge. Thanks!

**Comment by rodriguesbreno** [comment]
@javache 

What about
instead of 
```import "RCTValueAnimatedNode.h"```
use 
```import  <React/RCTValueAnimatedNode.h>```

it works (but tested only with the lib at cocoa pods)

**Comment by shergin** [comment]
Okay, does anyone have idea which exact problem we are trying to solve?
Why exactly is the issue #13198 happening?

**Comment by vjeranc** [comment]
I must admit to having no idea why the [previous fix](https://github.com/facebook/react-native/pull/13785/files) does not work. We've been building 0.45.1 and newer updates without any issues.

There might be some conflicts in `project.pbxproj` and the modified version after applying `*.podspec` definitions. Our `project.pbxproj` was heavily cleaned (removed references to all unneeded projects like tests and similar). Although I do remember trying out the fix on a clean 0.44 project and it worked.

**Comment by ceyhuno** [comment]
@rodriguesbreno Changed `import "RCTValueAnimatedNode.h"` to `import <React/RCTValueAnimatedNode.h>` and it works now 👍   Updated the PR, thank you!

**Comment by msand** [comment]
This should probably be solved using this approach: https://github.com/facebook/react-native/issues/13198#issuecomment-371749528

**Comment by msand** [comment]
@shergin The root issue is that when using cocoapods the React Native modules/frameworks are all built as one and thus can't reference/import from each other using the namespaced global/system imports (Header Search Paths), as they're not separate pods but just sub-specs of one pod. Instead, in this case, the files need to be imported locally from the User Header Search Paths. https://stackoverflow.com/a/1044399/1925631 Importing locally breaks the non-cocoapods builds, thus requiring the if statement to handle both cases. https://clang.llvm.org/docs/LanguageExtensions.html#include-file-checking-macros
```
#if __has_include(<React/RCTValueAnimatedNode.h>)
#import <React/RCTValueAnimatedNode.h>
#else
#import "RCTValueAnimatedNode.h"
#endif
```

**Pull request closed without merging**
