### PR TITLE
(WIP) implemented iOS builds using CircleCI

### PR DESCRIPTION
**Pull request by bestander**
WIP: trying to trigger a build from a Pull Request

### CODE REVIEW

**Comment by mkonicek** [comment]
So excited about this! 👍

**Comment by facebook-github-bot-7** [comment]
@mkonicek would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by bestander** [comment]
Ha ha

**Comment by mkonicek** [comment]
Good to close? :)

**Pull request closed without merging**
