### PR TITLE
⬆️ Upgrade ESLint TS parser and plugin

### PR DESCRIPTION
**Pull request by wcandillon**
I had an issue with the old version of the parser and upgrading it via `yarn resolve` solved it.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This was required for us as well, adding this (which is the same as these version bumps, essentially) fixed it for us. Would love to see this merged and released

Added to `package.json`:
```json
  "resolutions": {
    "@typescript-eslint/eslint-plugin": "^4.26.1",
    "@typescript-eslint/parser": "^4.26.1"
  },
```

With apologies for the direct ping but @PeteTheHeat I see you triggered the facebook github bot for a merge most recently, and this seems like an easy win? Not sure who else to contact to push buttons in these parts :-). Cheers

**Comment by mikehardy** [comment]
With apologies again for a direct ping, but @matt-oakes it appears based on a recent PR that you have npm publish powers and published this last time? I'll quickly admit I'm just reading old stuff and pinging people, which means this might not be correct and thus might be annoying, apologies in advance if that's the case

**Comment by PeteTheHeat** [comment]
Are the failures to test_ios_unit_hermes relevant to the changes in this diff?

**Comment by mikehardy** [comment]
@PeteTheHeat unfortunately I cannot see in CircleCI as it requires a login and to do so via github would allow it read/write access to all sorts of repos I share with others, I can't do that.

However, the change here is a bump to the transitive dependencies used by linters, specifically the combo of eslint and typescript. That should fail a lint type check, not a unit test check. Specifically I would presume "Facebook Internal - Linter" or "ci/circleci:analyze_code" to be the ones affected?

Further, given there is another run named "ci/circleci: test_ios_unit_jsc" that passes, and only the hermes "ci/circleci: test_ios_unit_hermes" variant is failing, I would *assume* (danger, danger) that this could not have anything to do with the failure.

Software always surprises, bit I think it's unrelated.

**Comment by matt-oakes** [comment]
@mikehardy I did have publish access before and, as far as I'm aware, I still do. However, I don't have permission to merge anything so it would need to be reviewed and merged before I could publish it.

**Comment by mikehardy** [comment]
Ah, I see @matt-oakes - I thought that was what the import from the facebook bot meant, but I suppose we need to wait for @PeteTheHeat to do something else perhaps pending resolution of unit tests on circleci which now appear to have failed on both jsc and hermes variant (which is odd, since jsc was green before?). But I have no insight there so :shrug: not sure what else I can do to get the dependencies bump other than continue with the resolutions block I've got in package.json locally and hope.

**Comment by matt-oakes** [comment]
@mikehardy @PeteTheHeat Sorry, I should have said before, but ideally a change should be merged in that bumps the version number of the package so the version that's in the repo stays in sync with what's published.

Can someone open up a PR to do that? I presume it's a major version bump because of the bump in dependencies?

**Comment by mikehardy** [comment]
@matt-oakes oh of course :facepalm: - just posted #31372

**Comment by matt-oakes** [comment]
@mikehardy @wcandillon Published as [v3.0.0](https://www.npmjs.com/package/@react-native-community/eslint-config/v/3.0.0).

**Comment by mikehardy** [comment]
Fantastic! I really appreciate the collaboration getting this in the tree and out on npmjs, thanks @PeteTheHeat and @matt-oakes and @wcandillon for posting it originally

**Comment by Bibazavr** [comment]
I'm upset that my similar [merge](https://github.com/facebook/react-native/pull/30808) was just ignored

**Comment by mikehardy** [comment]
@Bibazavr oh I didn't even see that when I searched! Don't be too upset though. In general I think react-native maintenance at the core level is a little bit reactive and definitely we're all busier than we should be. I think I was just the "squeaky wheel" on this one and it worked :shrug: . Keep trying!

**Pull request closed without merging**
