### PR TITLE
Remove translations for non-existent languages "fb" and "cb"

### LINKED ISSUE #42024: [v0.73.1][Android] Google.Play rejects app bundles because it "targets the following unrecognized languages: cb, fb"
### Description

I'm getting the following error when uploading an app bundle, built with RN v0.73, to Google.Play (it is an existing project, that had no such issue before):
image

Googling for the error message, I came across [this StackOverflow thread](https://stackoverflow.com/questions/58924089/error-when-trying-upload-aab-to-google-play-console-res-values-fb), which is old, and is not related to RN, but it mentions
> _I think it's because a folder named 'values-fb', that's a folder which have some files, usually used to translations_

So, I've checked whether my project has some folders with names ending with `-cb` and `-fb` suffixes, and I found them in RN package, and then in intermediate built artifacts:
image
image

I guess, it requires a fix on RN side, renaming those folders (although the very error message suggests a workaround via `resConfigs` Gradle prop)? 

### Steps to reproduce

N/A

### React Native Version

0.73.1

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

### Screenshots and Videos

_No response_

### PR DESCRIPTION
**Pull request by pandaninjas**
## Summary:
This PR resolves #42024
Values directories for language codes "fb" and "cb" are added incorrectly, causing Google Play Console to reject the app due to unrecognized languages. 
## Changelog:

[Android] [Fixed] - Removed translations for non-existent languages "fb" and "cb", fixing bug where Google Play Console refuses to accept the AAB.

## Test Plan:
Under current React Native:
```sh
npx react-native@latest init AwesomeProject
cd AwesomeProject
npx react-native build-android --mode=release
```
Uploading AAB to Google Play Console (recommended to create a new app for this, it can be deleted later)
image
Under this contribution:
Apply this patch to the react-native in AwesomeProject
`npx react-native build-android --mode=release`

### CODE REVIEW

**Comment by pandaninjas** [comment]
This PR still doesn't work because `generateReleaseResValues` still adds values-fb and values-cb even when the directories are deleted.

**Comment by NickGerleman** [comment]
I think a bot will go add these back if they are removed. I can change some settings so that they aren't projected into OSS though.

In the meantime, could you follow the recommendation of excluding in Gradle config?

**Comment by pandaninjas** [comment]
> I think a bot will go add these back if they are removed. I can change some settings so that they aren't projected into OSS though.
> 
> In the meantime, could you follow the recommendation of excluding in Gradle config?

We can't use Android Gradle Plugin's resConfigs to specifically exclude languages because resConfigs is a list of languages to be included in the result AAB. 

It could be possible if we specified every single language allowed by Google Play Console.

**Comment by NickGerleman** [comment]
We removed these from 0.73 branch.

In main branch, we now filter to the list of languages published by Google as supported for Play Store distribution.

**Comment by pandaninjas** [comment]
> Hi when this problem will be solve it's still present on 0.73.4

Have you tried `.\gradlew clean` before rebuilding it with `npx react-native build-android --mode=release`? It should be fixed (and it was for me)

**Comment by EricB84300** [comment]
> > Hi when this problem will be solve it's still present on 0.73.4
> 
> Have you tried `.\gradlew clean` before rebuilding it with `npx react-native build-android --mode=release`? It should be fixed (and it was for me)

Hi
Great! Thx It for me too.
Thx for your answer @pandaninjas

**Pull request closed without merging**
