### PR TITLE
Fix 16 linter warnings in Examples/

### LINKED ISSUE #3316: [Lint] Clean up the JS lint warnings and consider adding `npm run lint` to Travis
We have over 200 lint warnings 😓Trying to fix them all in one commit is going to be rough and harder to test, bisect, and deal with merge conflicts, but if we attacked them a few files at a time I bet we could knock that number down to zero pretty quickly.

(Thank you to everyone who's submitted a PR. If you are interested in helping out please look at the submitted PRs so we don't overlap!)

### PR DESCRIPTION
**Pull request by billglover**
Partially fixes #3316 by addressing 16 linter warnings:
 - Strings should be singlequote
 - Missing semicolon

Travis build jobs 1.1 through 1.4 complete successfully. 1.5 fails through what appears to be an unrelated issue on master.

### CODE REVIEW

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by chirag04** [comment]
haha. awesome bot flow @vjeux .

**Comment by vjeux** [comment]
I know, I'm so happy it worked!

**Pull request closed without merging**
