### PR TITLE
Add My IP to showcase

### PR DESCRIPTION
**Pull request by joshbuchea**

### CODE REVIEW

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by joshbuchea** [comment]
Hmm what did I do wrong?

**Comment by joshbuchea** [comment]
@skevy sorry to trouble you, but the import failed, and I'm not sure why. Any chance you could enlighten me?

**Comment by skevy** [comment]
@joshbuchea can you rebase this PR? After you do that I'll try shipping it again

**Comment by joshbuchea** [comment]
@skevy First time rebasing a PR. Hopefully I did it correctly.

**Comment by skevy** [comment]
Nope. :(

You have two options now: 

1. You can close this PR and open a new one with your change (if you do this, feel free to tag me in it and I'll get it merged).
2. You can scrap this branch, re-create it with your changes, and force-push it back to your repo.

I'd recommend number 1 for simplicity's sake.

For future reference...

Adam's guide to GitHub (you may have done some of these steps already...but just for reference):

1. Fork RN to your Github.

2. Pull down your fork and create a branch.

  ```bash
  git clone git@github.com:[your username]/react-native.git
  git remote add fb-upstream git@github.com:facebook/react-native.git
  git checkout -b my-pr-branch-name # this creates a new branch, based off of master
  ```

3. Make your changes and commit them.

4. Rebase your changes on to `fb-upstream/master`:

  ```bash
  git checkout my-pr-branch-name # make sure you're on your branch
  git fetch fb-upstream # pull down the latest changes from upstream, but don't merge them
  git rebase fb-upstream/master # rebase your changes onto FB master
  ```

  If there are any conflicts...fix them and follow the instructions.

5. Push to your remote branch:

  ```bash
  git push origin my-pr-branch-name
  ```

You can repeat these steps for every PR you ever make, and you can repeat steps 3, 4, and 5 to continue making changes and keep your PR up-to-date with upstream.

Note that on step 5 -- you'll most likely need to force push (use the `-f` flag), as the commit history will have changed when you rebase. Do this with caution.

**Comment by joshbuchea** [comment]
Ha figures. :)

I'll take your advice and go with option #1. Thank you very much for the detailed feedback @skevy. It's very helpful to a rebasing noob like myself.

**Pull request closed without merging**
