### PR TITLE
Fix warning message to show the actual error

### PR DESCRIPTION
**Pull request by newmetl**
...

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @corbt to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by janicduplessis** [comment]
Hey @newmetl, please submit your PR on the master branch. Also could you provide an explanation of the issue and screenshots of the alert before / after your change (see https://github.com/facebook/react-native/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by hramos** [comment]
Closing, feel free to open a new PR against master.

**Pull request closed without merging**
