### PR TITLE
Fixes #5688 onChangeVisibleRows for Android

### LINKED ISSUE #5688: [0.19][Android][ListView] onChangeVisibleRows isn't called on Android
Hi, i found the function for **onChangeVisibleRows** of ListView would be called on iOS when init or scroll a ListView but not on Android. 

I did a quick dig in source code of ListView component and found **e.nativeEvent.updatedChildFrames** was undefined when passed to _updateVisibleRows function which caused **onChangeVisibleRows** can't be called on Android. 

I checked UIExplorer example also and saw this prop was demonstrated in ListViewPagingExample, but only included in example of iOS version. Does it mean it's not supported on Android currently?

### PR DESCRIPTION
**Pull request by ptomasroos**
This PR includes a fix for the old missing feature of onChangeVisibleRows on Android.
Fixes https://github.com/facebook/react-native/issues/5688
Also reported on product pains https://productpains.com/post/react-native/listview-onchangevisiblerows-android-support

**Test plan (required)**

Test through UIExplorer which has a callback on the ListView Paging example and walking through rows + sections and making sure visible rows matches to whats visible.

### CODE REVIEW

**Comment by ptomasroos** [comment]
cc @janicduplessis @ide @javache

**Comment by ptomasroos** [comment]
@hramos Can we get someone to look at this ?

**Comment by johnnycopperstone** [comment]
Does anyone know when this might be released please?

**Comment by vitorebatista** [comment]
Why this PR is close?

**Comment by ptomasroos** [comment]
No need for it now when flatlist is available.

**Comment by johnnycopperstone** [comment]
flatlist?

**Comment by philipheinser** [comment]
@ptomasroos Can we use flat list in rn-0.42.0 or do we have to checkout master?

**Comment by biohazardffm** [comment]
Would still be nice when that error would be fixed anyway. 
When will flatlist be production ready?

**Comment by rborn** [comment]
@ptomasroos why can't this be merged? FlatList is still experimental and people still use the normal listview...
Thanks.

**Comment by ptomasroos** [comment]
No one took a look on it for quite some time. Feel free to copy the branch and open a PR if you need it! We've migrated to FlatList

**Comment by philipheinser** [comment]
@ptomasroos How can I use FlatList right now? Do you use the master branch?

**Pull request closed without merging**
