### PR TITLE
Fix typo "it's" -> "its".

### PR DESCRIPTION
**Pull request by follower**
See: http://grammarist.com/spelling/its-its/

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @spicyj and @foghina to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by foghina** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
I cannot do that @foghina, because @follower does not have an active CLA on file.

**Comment by follower** [comment]
FYI I'm not going to sign the CLA for this change.

**Comment by spicyj** [comment]
Sorry about this. We don't really need a CLA for trivial changes but I guess the bot is more aggressive.

**Pull request closed without merging**
