### PR TITLE
Android - pass initial props to ViewManager createView in non-Fabric

### PR DESCRIPTION
**Pull request by gkode**
## Summary

https://github.com/facebook/react-native/issues/31051
When trying to create custom viewmanagers,  we don't have props, I have a use case where I want to create views on the basis of provided react prop from react native. 
## Changelog

[CATEGORY] [TYPE] - ReactNative WebView

## Test Plan

Tested Manually.

### CODE REVIEW

**Comment by JoshuaGross** [comment]
@gkode Can you specify defaults in your custom view manager that will be used if null props are passed in? That seems like an easier change and wouldn't require upstreaming anything. 

For this sort of change we would need a more comprehensive test plan than "tested manually" - how does this impact components in the ecosystem in general? Could it break anything? 

A few lines below your change, `updateProperties` will be called. Why isn't that good enough?

**Comment by JoshuaGross** [comment]
In the future I would also recommend giving PRs a more descriptive title to help maintainers. I updated this one for you :) 

Other thoughts:

1) We tend to be hesitant about making changes like this without a lot of testing and a comprehensive test plan. This behavior hasn't changed in ~6 years, and it's a fairly invasive change. What side-effects could it cause?
2) Is there another way to achieve this in general?
3) On the other hand, Fabric _does_ pass in initialProps on createView, and we did this intentionally so that certain decisions can be made when views are created for some custom ViewManagers, so maybe consistency is good between non-Fabric and Fabric: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/fabric/mounting/SurfaceMountingManager.java#L500

I think I'd be okay making this change in the spirit of consistency between Fabric and non-Fabric, but I would want to see a more reproducible and fleshed-out test plan first.

**Comment by gkode** [comment]
> @gkode Can you specify defaults in your custom view manager that will be used if null props are passed in? That seems like an easier change and wouldn't require upstreaming anything.
> 
> For this sort of change we would need a more comprehensive test plan than "tested manually" - how does this impact components in the ecosystem in general? Could it break anything?
> 
> A few lines below your change, `updateProperties` will be called. Why isn't that good enough?

While createViewInstance, I want to provide already existing view in memory on the basis of provided props to Native hierarchy. But in Update properties, view is already created and added in native view hierarchy. So, I will have to replace my existing view (in memory) in update properties method with the one created in CreateViewInstance which makes my code a bit messy. 

Can you please help with making test plan for it ? What all test we want to pass on it to make sure it doesn't break anything. I tested this change on android only.

**Comment by JoshuaGross** [comment]
I realized that some of our FB-internal view managers use the presence of props in the constructor to differentiate between Fabric and non-Fabric rendering modes. I will need to think about this a bit more.

**Comment by gkode** [comment]
> I realized that some of our FB-internal view managers use the presence of props in the constructor to differentiate between Fabric and non-Fabric rendering modes. I will need to think about this a bit more.

is it really right parameter to differentiate between fabric and non-fabric?

**Comment by gkode** [comment]
> > I realized that some of our FB-internal view managers use the presence of props in the constructor to differentiate between Fabric and non-Fabric rendering modes. I will need to think about this a bit more.
> 
> is it really right parameter to differentiate between fabric and non-fabric?

@JoshuaGross What's the plan to take this change forward

**Comment by gkode** [comment]
@JoshuaGross  Any update on it.

**Comment by JoshuaGross** [comment]
Merged @gkode, just took a while to audit everything relying on this internally

**Pull request closed without merging**
