### PR TITLE
Ios: complete iOS vibration pattern supports (js) 

### PR DESCRIPTION
**Pull request by zxcpoiu**
This is a revised follow up version from #8574 ( originally implemented in `objc` )
This PR change the implementation in JS suggested by @javache 

**motivation**

To supports vibration pattern like android.

The [iOS vibration implementation link](http://stackoverflow.com/questions/12966467/are-there-apis-for-custom-vibrations-in-ios/13047464#13047464) mentioned by @skv-headless at https://github.com/facebook/react-native/pull/6061#discussion_r54062592, which will not be accepted by apple since that implementation uses a private API. Thus, I use pure public API `NSTimer` to implement it.

**Note**

Since vibration time on iOS is not configurable, there are slightly differences with android.
for example:

**Android Usage:**
`Vibration.vibrate([0, 500, 200, 500])`
==> V(0.5s) --wait(0.2s)--> V(0.5s)

`Vibration.vibrate([300, 500, 200, 500])`
==> --wait(0.3s)--> V(0.5s) --wait(0.2s)--> V(0.5s)

**iOS Usage:**
if first argument is 0, it will not be included in pattern array.
( vibration length on iOS is about 500ms )
 
`Vibration.vibrate([0, 1000, 2000, 3000])`
==> V(fixed) --wait(1s)--> V(fixed) --wait(2s)--> V(fixed) --wait(3s)--> V(fixed)

`Vibration.vibrate([0, 1000, 2000, 3000], true)`
==> V(fixed) --wait(1s)--> V(fixed) --wait(2s)--> V(fixed) --wait(3s)--> V(fixed) --wait(1s)--> V(fixed) --wait(2s)--> V(fixed) --wait(3s)--> V(fixed)

`Vibration.vibrate([1000, 2000], true)`
==> --wait(1s)--> V(fixed) --wait(2s)--> V(fixed) --wait(1s)--> V(fixed) --wait(2s)--> V(fixed)

`Vibration.vibrate([0, 1000], true)`
==> V(fixed) --wait(1s)--> V(fixed) --wait(1s)--> V(fixed) 

**Test plan (required)**

I also added examples in `UIExplorer`.
Open `UIExplorer` on iOS, and plays it around.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @skv-headless and @javache to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@zxcpoiu updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@zxcpoiu updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@zxcpoiu updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@zxcpoiu updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@zxcpoiu updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@zxcpoiu updated the pull request.

**Comment by zxcpoiu** [comment]
Fixed ci

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3775085) to review internal test results.

**Pull request closed without merging**
