### PR TITLE
Add doc warning stating that TouchableOpacity can only support a single child

### PR DESCRIPTION
**Pull request by pwmckenna**
screen shot 2015-05-24 at 5 15 31 pm

### CODE REVIEW

**Comment by pwmckenna** [comment]
addresses https://github.com/facebook/react-native/issues/1354

**Comment by ide** [comment]
This looks good in spirit. I might trim the content for brevity, something like

NOTE: TouchableOpacity supports only one child
If you wish to have to have several child components, wrap them in a View.

**Comment by pwmckenna** [comment]
Update: 
screen shot 2015-05-25 at 10 04 11 pm

**Comment by ide** [comment]
lgtm

**Pull request merged**
