### PR TITLE
Code syntax error while invoke function compareKey

### PR DESCRIPTION
**Pull request by xing-zheng**
remove the unnecessary comma

### CODE REVIEW

**Comment by ide** [comment]
This is intentional and part of the style guide.

**Comment by xing-zheng** [comment]
Hi @ide, I've never heard that we should add trailing comma to the argument list of function calls.
Trailing comma is recommended for Arrays and Objects.
Could you show me the style guide witch recommend trailing comma for argument list? Thank you.

**Comment by ide** [comment]
It's an internal FB style -- look at the rest of the JS for examples.

**Comment by xing-zheng** [comment]
Thank you! @ide

**Pull request closed without merging**
