### PR TITLE
Make the unix environment setup script more resilient

### PR DESCRIPTION
**Pull request by jacob-meacham**
# Motivation
This PR helps with confusion demonstrated in #5668. It also makes the react-native packager a slightly better citizen, by only setting the soft file limit, allowing future `ulimit` calls to update that limit upwards.

# Test Plan
*NOTE: This test plan has __not__ yet been run*

The script is POSIX compliant from running shellcheck:
```
TODO: Shellcheck output here
```

I've tested starting the packager on the following OSes and shells
TODO
* OS X 10.11.6 
    - [ ] bash
    - [ ] sh
    - [ ] zsh
* Ubuntu 
    - [ ] bash
    - [ ] sh
    - [ ] ksh
    - [ ] posh
* CentOS 
    - [ ] tcsh
    - [ ] sh
    - [ ] bash
* Alpine
    - [ ] sh

And have tested the following initial settings
* unlimited hard file limit
* hard file limit of 4096
* hard file limit of 2048
* hard file limit of 2047

by starting the packager

### CODE REVIEW

**Comment by lacker** [comment]
So what's up with this pull request - do you think it's good to go? It was just unclear to me because you say you haven't finished testing it, but it's been a couple weeks and so I was wondering what now.

**Comment by jacob-meacham** [comment]
Hi Kevin, sorry for the delay - I got very busy and haven't had a chance to test yet. I hope to do so in the next few days, but if you'd prefer to keep the number of PRs low, I can close this out and reopen once I've finished testing.

**Comment by lacker** [comment]
Let's keep it open but if you don't find time in the next couple weeks then let's close it for cleanliness.

**Comment by jacob-meacham** [comment]
I'm going to close this for now - once I get a chance, I'll reopen and finish off the testing

**Comment by torukMnk** [comment]
FYI, I had the same issue related to `ulimit` and root privileges https://github.com/facebook/react-native/issues/5668 , I fixed it manually.

`react-native: 0.58.3`
`macOS Mojave 10.14.2`

**Pull request closed without merging**
