### PR TITLE
Fix VirtualizedList with initialScrollIndex not rendering all elements when data is updated

### PR DESCRIPTION
**Pull request by AntoineDoubovetzky**
## Summary

Fixes https://github.com/facebook/react-native/issues/33529 (note that I reproduced the bug on iOS too).

The bug comes from the fact that we were using `this._scrollMetrics.offset` to determine if the initial scroll was done. But sometimes it equals 0 even after the initial scroll is done, for example when the content does not fill the list. So I replaced it with `this._hasDoneInitialScroll`.
I believe that `this._hasDoneInitialScroll` was not used in the first place because it was introduced later (3 years ago vs 5 years ago for the original code).

The replacement correctly fixes the broken test case and the example given in the issue.

Then I had to update two test cases (rename the first and remove the second), that shows explicitly the broken behavior:
we have to simulate the initial scroll for the content to be adjusted, so when the content does not fill the view and the scroll cannot be executed, the content is not adjusted.

## Changelog

[General] [Fix] - Fix VirtualizedList with initialScrollIndex not rendering all elements when data is updated

## Test Plan

- I added a broken test case based on the issue
- I tested with the RNTesterApp using the code example given in the issue

### CODE REVIEW

**Comment by ryancat** [comment]
Thanks for making this change. I think it makes sense to me.

One thing to mention here -- I tried to reproduce this with your example, but got error at [VirtualizedList.js](https://github.com/facebook/react-native/blob/main/Libraries/Lists/VirtualizedList.js#L450) where the `this._highestMeasuredFrameIndex` value is still zero. I believe that only got updated when [onCellLayout](https://github.com/facebook/react-native/blob/main/Libraries/Lists/VirtualizedList.js#L1300) is triggered, which is not happening when I load the playground code.

**Comment by AntoineDoubovetzky** [comment]
@ryancat Sure, I'll check if that's also the case for me and I'll try to give you an update soon.

**Comment by AntoineDoubovetzky** [comment]
@ryancat You were right, I get the same error using the example in the issue. There is no error when adding the `getItemLayout` or the `onScrollToIndexFailed` prop as mentionned in the warning.

<details>
<summary>The correct code example is the following:</summary>

```
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 * @flow
 */

import {Text, FlatList, SafeAreaView, View} from 'react-native';
import * as React from 'react';

const getData = length => {
  return new Array(length).fill(0).map((_, index) => ({
    title: `item ${index}`,
  }));
};

const ITEM_HEIGHT = 70;

const RNTesterApp = (): React.Node => {
  const renderItem = React.useCallback(
    (item: {
      item: {
        title: string,
      },
    }) => {
      return (
        <View style={{height: ITEM_HEIGHT, backgroundColor: '#00ff00'}}>
          <Text>{item.item.title}</Text>
        </View>
      );
    },
    [],
  );

  const [data, setData] = React.useState(getData(2));

  React.useEffect(() => {
    setTimeout(() => {
      setData(getData(4));
    }, 2000);
  }, []);

  return (
    <SafeAreaView>
      <FlatList
        data={data}
        renderItem={renderItem}
        initialScrollIndex={1}
        getItemLayout={(items, index) => ({
          length: ITEM_HEIGHT,
          offset: ITEM_HEIGHT * index,
          index,
        })}
      />
    </SafeAreaView>
  );
};

export default RNTesterApp;
```
</details>

I think there is no issue with this warning:
When `index > this._highestMeasuredFrameIndex`, we won't be able to get the frame from `this._frames` so we'll need to get it from `getItemLayout`:
https://github.com/facebook/react-native/blob/a223874cb5c69be1947d43db4d74371c43c90e5d/Libraries/Lists/VirtualizedList.js#L1864-L1869

**Comment by AntoineDoubovetzky** [comment]
I rebased onto master to resolve conflicts.

**Comment by AntoineDoubovetzky** [comment]
(Rebased again after commit was reverted)

**Comment by yepMad** [comment]
Is this still a problem or something? I have a horizontal FlatList, each item has the width of the screen (carousel style) and with active pagination. When I declare a value for initialScrollIndex all next items are only rendered when scrolling/paging is done

**Pull request closed without merging**
