### PR TITLE
Update showcase.js

### PR DESCRIPTION
**Pull request by genki**
Added a link to android app of DockMan.

### CODE REVIEW

**Comment by satya164** [comment]
Hey @genki . Can you sign the CLA?

**Comment by genki** [comment]
@satya164 I've tried to sign, but the form said "The 'Email' value has been registered on this form before."
Ain't I already signed?

**Comment by satya164** [comment]
That's weird. cc @mkonicek

**Comment by satya164** [comment]
@vjeux Something wrong with the bot?

**Pull request merged**
