### PR TITLE
Cherry-pick: Navigator Tutorial

### PR DESCRIPTION
**Pull request by JoelMarcey**
I saw no reason why we shouldn't add @hramos Navigators tutorial in the current `0.29` documentation.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @hramos and @vjeux to be potential reviewers.

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/499730303557265/int_phab) to review.

**Comment by JoelMarcey** [comment]
@hramos With cherry-picks, you just directly merge it. e.g., By pressing the `Merge pull request` button. :)

**Comment by hramos** [comment]
TIL! :)

**Pull request merged**
