### PR TITLE
ActionSheetIOS - Pass URL, not file contents to UIActivityViewController for file URLs.

### PR DESCRIPTION
**Pull request by sheparddw**
Currently, when sharing local files, the file contents are being sent as NSData causing the file to never be attached when sharing via Email or via Airdrop, being renamed to something obscure such as (null)-257D026032E9-1.data
Simply passing the Local File URL to UIActivityViewController instead of the file contents resolves this issue.
More info on this issue: https://github.com/facebook/react-native/issues/8442

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @javache to be potential reviewers.

**Comment by facebook-github-bot-5** [comment]
@sheparddw updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9693/files/b679b68a254c177521e80bfb11181ff29f4eab23..a12ea075e05a8c11ba79978c8b450cdf0a0f1537)

**Comment by mkonicek** [comment]
> Simply passing the Local File URL to UIActivityViewController 

Does this pull request do that?

**Comment by sheparddw** [comment]
@mkonicek, yes, this PR makes it so URLs that are not base64 pass URLs instead of content to the UIActivityViewController. Go ahead and test it out if you wish to share files.
I was able to share .vcf (contact card) files when using this branch without the strange behavior currently in the master branch and all previous other versions tested.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3821142) to review internal test results.

**Pull request closed without merging**
