### PR TITLE
remove accessibilityStates validAttributes config from ReactNativeViewViewConfig.js

### PR DESCRIPTION
**Pull request by luism3861**
## Summary
this little PR remove `accesibilityStates` config in validAttributes, like comment says it can be removed after next release.

## Changelog
Javascript

### CODE REVIEW

**Review by alshamiri5 — APPROVED** [review]

**Comment by Naturalclar** [comment]
reference for more information on why it can be removed: https://github.com/facebook/react-native/pull/26168

**Comment by luism3861** [comment]
> reference for more information on why it can be removed: #26168

thank you @Naturalclar!

**Comment by luism3861** [comment]
@

**Comment by luism3861** [comment]
@cpojer could you review this PR?

**Comment by luism3861** [comment]
@Young could you review this PR?

**Comment by luism3861** [comment]
@yungsters could you review this PR?

**Pull request closed without merging**
