### PR TITLE
RFC: <Navigator.Next />. For Navigation Simplification 

### PR DESCRIPTION
**Pull request by hedgerwang**
This is the proposal to break the features <Navigator /> into separate modules so that <Navigator /> can become the pure view that only focuses on rendering.

The navigation state will be managed independently.

### CODE REVIEW

**Comment by vjeux** [comment]
cc @ide

**Comment by ide** [comment]
Hey @hedgerwang, sorry it took me awhile to write up some feedback. Overall I like the idea of separating the navigation state from the UI, particularly for deep linking where we want to know the current navigation state (so we can make a permalink) and how to render any navigation state (so we can visit a permalink).

---

**Tree structure and focused node:** you mentioned that exactly one node must be focused. I was thinking in a more complex app especially on a tablet, you might have two sibling navigators displayed on screen at the same time so there could be two scenes focused like this:

```
  +-----------------------------------------+  
  |                  app                    |  
  |                                         |  
  | +------------------+ +----------------+ |  
  | |                  | |                | |  
  | |                  | |                | |  
  | |                  | |                | |  
  | |     contentL1    | |     contentR1  | |  
  | |                  | |                | |  
  | |                  | |                | |  
  | |                  | |                | |  
  | +------------------+ +----------------+ |  
  |                                         |  
  +-----------------------------------------+  
```

The navigator on the left-hand side can display scenes `contentL1`, `contentL2`, etc... and similarly the navigator on the right-hand side can display scenes `contentR1`, `contentR2`, etc... To express the navigation state I would write:

```
|-- app
   |-- [left=contentL1, right=contentR1] * // currently focused
   |-- [left=contentL1, right=contentR2]   // can navigate to this state
   |-- [left=contentL2, right=contentR2]   // and then this one
```

There is probably a simpler way to express this state so if having multiple sibling navigators is a valid use case then we might want to pick a different data structure for it.

---

**Layout:** sometimes there may be a child scene that covers the entire parent scene so that it intercepts all gestures, but parts of the child are transparent. For example, there could be a dialog that can be dismissed by swiping anywhere (even outside of the dialog), but you can still see the parent scene behind the dialog:

```
+-----------------------------+         
|             app             |         
|                             |         
|                             |         
|      +---------------+      |         
|      |               |      |         
|      |    dialog     |      |         
|      |               |      |         
|      +---------------+      |         
|                          ^  |         
|                          |  |         
+-----------------------------+         
                           |            
                           +            
can swipe anywhere to dismiss dialog    
```

To implement this, I would make the dialog scene's layout cover the entire screen (a big transparent View) so that it receives all touches before the app scene.

**Gestures:** I believe you had some ideas about progress events. I'm not sure about a lot of the API but they are these are some types of transitions I've seen in other apps:

- Navigation bar of course
- Carousel navigation like Snapchat (built on top of ScrollView... reimplementing the scroll pagination physics still doesn't feel right)
  - Also, carousel that updates the nav bar, like the Skype app
- Lightbox navigation when opening a single photo in the Facebook app
- Opening/closing a photo that's part of an album in the Facebook app
- The story strip in FB Paper (might be hard)
- Minimizing a video in the YouTube app while it keeps playing in the corner
- Opening/closing an email in Google Inbox

It could be a little helpful to look at UIViewController's API to see how the transitions are structured. The full API is pretty complex but it might provide an idea or two.

**Comment by chirag04** [comment]
@hedgerwang  Is this still applicable. Seems like we are already moving forward with `NavigationExperimental`.

**Comment by mkonicek** [comment]
@hedgerwang Looks like you plan to work on this and land it? I'm going through old PRs and closing the ones with no activity for a long time. Leaving this one open for now.

**Comment by ericvicenti** [comment]
I'm closing this because we're moving forward with NavigationExperimental

**Pull request closed without merging**
