### PR TITLE
Adds full support for UserNotifications framework

### PR DESCRIPTION
**Pull request by simonmitchell**
Thanks for submitting a PR! Please read these instructions carefully:

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

This code change moves to a newer and better supported API for registering and managing both local and remote notifications on iOS in-line with the changes Apple released in iOS 10. The motivation here is to make sure we are not using APIs which will eventually be deprecated, but also to add the following:
- Ability to present iOS notification UI when notifications are received in the foreground.
- Ability to set custom categories when registering for push notifications, including actions and custom text fields.
- Ability to listen for when a user interacts with a notification or one of it's actions.

## Test Plan (required)

This was tested on a production codebase which we have written for a client, tested:
- Showing a notification when the app is in the foreground:
img_7692
- Ability to set custom categories for push notifications:
img_7693
- Ability to listen for custom action responses:
screen shot 2017-06-14 at 11 33 08

### CODE REVIEW

**Comment by simonmitchell** [comment]
@facebook-github-bot This is still 100% relevant code, I have no idea who to pick to review it however I'm afraid. The files all exist still, and none are new. I've merged your master back into this pull request, and there is still a lot of the functionality that I added that isn't available on master.

**Comment by duhseekoh** [comment]
Surprised there isn't more demand for this feature.

**Comment by simonmitchell** [comment]
Me too! I’ve given up on it somewhat, the project we needed it for uses a 3rd party library for push notifications anyways which we’ve forked to add support for this. Just thought I’d be nice and PR it for the benefit of everyone!

**Comment by simonmitchell** [comment]
@shergin as the person with the most commits to React Native could you try and find a real person who could look at this? It's a fairly major bit of functionality on iOS now, and something I feel like Facebook are missing out on with their apps, as well as the wider React Native community! I'm really not sure who else to tag as It's the first PR I've submitted to the project! Thanks 👍

**Comment by simonmitchell** [comment]
@shergin @javache @davidaurelio @sahrens can we please have a real human look over this!?

**Comment by pie6k** [comment]
Would be great to have this feature

**Comment by simonmitchell** [comment]
@shergin @javache @sahrens @davidaurelio 

Please please please can we get a real person to look at this!? 😩

**Pull request closed without merging**
