### PR TITLE
chore(showcase): Add Cinemy app to showcase

### PR DESCRIPTION
**Pull request by ClaudioCarmeli**

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @RetroPoktan to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by lacker** [comment]
Thanks for sending this pull request. According to the guidelines in that file, infoLink must be one of:

  1/ An English-language news article discussing the app, built either by a funded startup or for a public company
  2/ An English-language technical blog post by the app creators specifically discussing React Native

I am going to close this, but if you have one of those two things, feel free to reopen with a new link.

**Pull request closed without merging**
