### PR TITLE
<Text> module add textDecoration style attributes

### PR DESCRIPTION
**Pull request by pcottle**
This is simply a rebased and squashed version of @KJlmfe's PR over at https://github.com/facebook/react-native/pull/845

It was actually already squashed into one commit, but for some reason that was hard to see from the original PR.

### CODE REVIEW

**Comment by pcottle** [comment]
```
    ☂ -[UIExplorerTests testTextExampleSnapshot] (1208 ms) (0)
```

looks like the examples need to be re-recorded, justasec...

**Comment by pcottle** [comment]
Re-recorded tests, new image and results:

screen shot 2015-07-04 at 11 10 56 am

testtextexamplesnapshot_1 2x

**Comment by brentvatne** [comment]
Thanks @pcottle! This looks good to me

**Comment by brentvatne** [comment]
It would be great to get this in for 0.8.0-rc if it's ready, we are planning on shipping that sometime in the new couple of days if possible @nicklockwood

**Comment by nicklockwood** [comment]
Should be OK - I'll just need to check there are no issues with Android compatibility since it's a shared component.

**Pull request closed without merging**
