### PR TITLE
limit try times of setupDevtools

### PR DESCRIPTION
**Pull request by rocman**
No matter why, the tries should be limited at a certain times.
And this seams to be relative with https://github.com/facebook/react-native/issues/3953

### CODE REVIEW

**Comment by frantic** [comment]
It should be possible to attach the view inspector at any point in time, and since we don't yet have any infra in place to notify the app, polling is our best option.

I do see that this code is no clearing `_interval` in case the socked is disconnected. If that's the issue that's causing the memory leak you are experiencing, the fix should be relatively simple – move `_interval` one level up and add `clearInterval(_interval)` to `onclose` and `onerror`.

**Comment by rocman** [comment]
https://github.com/facebook/react-native/issues/4282
in setupDevtools(https://github.com/facebook/react-native/blob/master/Libraries/Devtools/setupDevtools.js), the method 'tryToConnect' starts a interval which waiting for a message with a evt.data which starts with 'eval:'.
After searching in the code, I found that there seams to be nowhere to send the message on demand. And so, the interval is invoked again and again.

**Comment by frantic** [comment]
This command is sent from [devtools](https://github.com/facebook/react-devtools). In my prev comment I made a suggestion on how this can be fixed, limiting retries will break other workflows.

**Comment by rocman** [comment]
I just checked that my devtools has been installed. I don't understand why I get ws.onerror in setUpDevtools.js

**Comment by frantic** [comment]
Likely because this code connects to external devtools. See https://github.com/facebook/react-devtools/pull/263

**Comment by mkonicek** [comment]
> I just checked that my devtools has been installed. I don't understand why I get ws.onerror in setUpDevtools.js

> Likely because this code connects to external devtools. See facebook/react-devtools#263

**Comment by mkonicek** [comment]
Hey @rocman! Thanks for making the pull request, but we are closing it due to inactivity (based on comments above there was no agreement how to proceed) to make sure all pull requests are either being worked on or closed. If you want to get your proposed changes merged, please rebase your branch with master and send a new pull request :)

**Pull request closed without merging**
