### PR TITLE
Add Blink App in Showcase

### PR DESCRIPTION
**Pull request by sriraman**
We have made a Companion app for our Blink smart watch in React Native. Currently, It's available only in the Play store. It will be launched in App Store soon. It is under review by apple team with our hardware.

If you want to know more about the company, You can checkout Mashable ( http://mashable.com/2016/09/30/blink-smartwatch-india/#aAdTEyTkfOqW ) , The Next Web ( http://thenextweb.com/gadgets/2016/09/30/the-blink-smartwatch-takes-the-fight-to-google-and-pebble-with-a-custom-os/ ) , Tech in Asia ( https://www.techinasia.com/witworks-blink-%3E%20smartwatch-apple-competitor ) etc., 

Thanks.,

### CODE REVIEW

**Comment by sriraman** [comment]
Ya. I signed the CLA.

**Comment by lacker** [comment]
Hi, thanks for submitting a pull request! According to the instructions in this file:

Thousands of applications use React Native, so we can't list all of them
in our showcase. To be useful to someone looking through the showcase,
either the app must be something that most readers would recognize, or the
makers of the application must have posted useful technical content about the
making of the app. It also must be useful considering that the majority of
readers only speak English. So, each app in the showcase should link to either:
1/ An English-language news article discussing the app, built either by a funded startup or for a public company
2/ An English-language technical post on a funded startup or public company blog discussing React Native
For each app in the showcase, use infoLink and infoTitle to reference this
content.

I'm closing this pull request since it does not adhere to these guidelines.

**Comment by sriraman** [comment]
We are a funded startup. Can I give pull request with the funding links?

https://www.techinasia.com/iot-startup-blink-raises-funding-india-homegrown-smartwatch

**Comment by lacker** [comment]
Since that link doesn't discuss the app, my concern is that it will not be useful to a React Native developer who is browsing through the showcase. We would like to keep it focused on articles that talk about the app either from a public point of view or from a developer point of view.

**Comment by sriraman** [comment]
The article which was featured in Hashnode is focussed on React Native and the Blink App only right?

https://hashnode.com/post/what-we-learned-after-using-react-native-for-a-year-civdr8zv6058l3853wqud7hqp

This post talks about why did we choose React Native for our Companion app, What are the problems faced? and How did we tackle the issues?

**Comment by hramos** [comment]
@sriraman thanks for posting a link to the article announcing Witwork's funding. The current "infoLink" value should be fine as it is a technical blog post on using React Native from a developer's perspective. The one thing that needs to be addressed here is moving this app to the right place. It should be at the end of the "featured" array, and not the "pinned" array.

**Comment by sriraman** [comment]
@hramos  Sorry, accidentally added it in the pinned array. Now, I have moved it to the featured array.

Thanks,

**Pull request closed without merging**
