### PR TITLE
 THUMB_URLS of Examples are fixed. Issue #4159

### PR DESCRIPTION
**Pull request by bozzmob**
Fixed THUMB_URLS in examples. Have kept a local copy of images as decided. Refer #4159 for more details.

### CODE REVIEW

**Comment by nicklockwood** [comment]
Awesome! Thank you.

@facebook-github-bot shipit

**Comment by bozzmob** [comment]
@nicklockwood My pleasure...

**Comment by bozzmob** [comment]
I see that the images are perfect in my fork - https://github.com/bozzmob/react-native/tree/master/Examples/UIExplorer/Thumbnails

But, the **same commit** (which I used for pull request) shows a 0 Bytes file on FB's repo. https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/Thumbnails

Any idea what's the problem is?

**Comment by bozzmob** [comment]
Thanks @nicklockwood :+1:

**Pull request closed without merging**
