### PR TITLE
Update the getCacheFilePaths function to limit filename length

### PR DESCRIPTION
**Pull request by nicktate**
@ericvicenti 

* The hash generated for the file path can contain filenames exceeding
the 255 limit that occurs on most filesystems
* This function now splits filenames over length 143 (the max filename
length for an encrypted file) into prefix directories

Here is an example of the error produced from the file during android e2e tests
```
Error: ENAMETOOLONG: name too long, open '/tmp/react-native-cpnt4fWv/EndToEndTest/react-native-packager-cache-ifttK9q0xA09ITRCk5cLyvJbMiI=/97/304afe94dd3270dcb13bc6fe91d39ef863b89
3ece7eb3b87140deab16dafc0218006a8f0b5cda08d6379b3c8695cc795211242817e015f0b7fb7dc6d486b136e4173838c0e5f9b9eab8aa5e5c2cfe0db63c124d7741e296b6e92e681a908b093c35f8e8497d6f075fa974a89
1fd2726d9549index.android.js.meta'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at readMetadataFileSync (/tmp/react-native-cpnt4fWv/EndToEndTest/node_modules/react-native/packager/src/lib/TransformCache.js:249:26)
    at readSync (/tmp/react-native-cpnt4fWv/EndToEndTest/node_modules/react-native/packager/src/lib/TransformCache.js:320:16)
    at Object.readSync (/tmp/react-native-cpnt4fWv/EndToEndTest/node_modules/react-native/packager/src/lib/TransformCache.js:350:20)
    at Module._readFromTransformCache (/tmp/react-native-cpnt4fWv/EndToEndTest/node_modules/react-native/packager/src/node-haste/Module.js:378:41)
    at Module.readCached (/tmp/react-native-cpnt4fWv/EndToEndTest/node_modules/react-native/packager/src/node-haste/Module.js:364:25)
    at Promise.resolve.then (/tmp/react-native-cpnt4fWv/EndToEndTest/node_modules/react-native/packager/src/node-haste/Module.js:346:27)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### CODE REVIEW

**Comment by ericvicenti** [comment]
This looks like a logical fix to a well-documented issue.

cc @jeanlauliac and @davidaurelio who have a bit more context on the packager code

I'll let this sit in a review state for a day to give folks in London time to review. If nobody has any concerns by this time tomorrow, I'll land it.

**Comment by jeanlauliac** [comment]
I'm surprised by the example, does that mean the Javascript file name is already very long, including a hash in its name?

Anyway, since the `filePath` is already included in the hash, we can actually do a simpler solution: not append the basename at all. Originally I think we added it for debugging, but that's not really useful anymore. SHA-1 hashes have fixed size, so it should never be too long. Also, collisions could happen, but they would be handled reasonably by the code that verifies the sourceCode hash in the metadata.

**Comment by jeanlauliac** [comment]
I'll send a changeset.

**Comment by jeanlauliac** [comment]
@nicktate can you please rebase past cb88df00ae102a31e98a7a4240f3d410e9ee7062 and see if the `ENAMETOOLONG` error still reproduces? I believe this should solve the issue 😌

**Comment by nicktate** [comment]
@jeanlauliac Makes sense, didn't know you added that originally for debugging. 👍

**Pull request closed without merging**
