### PR TITLE
[Touchable] Change default `activeOpacity` to 0.2 to match iOS

### PR DESCRIPTION
**Pull request by ide**

### CODE REVIEW

**Comment by nicklockwood** [comment]
Makes sense. Might break some of our internal apps if they're using the default though - we'd better verify that before merging.

**Comment by vjeux** [comment]
Can you post screenshots of iOS and Touchable with this change?

**Comment by ide** [comment]
Couldn't get a screenshot while pressing down so here is a video: https://gfycat.com/WelllitGaseousDolphin

**Comment by vjeux** [comment]
Thanks! Looks good

**Comment by sahrens** [comment]
This is now landing internally.

**Pull request merged**
