### PR TITLE
add husky and lint-staged to current workflow

### PR DESCRIPTION
**Pull request by gengjiawen**
## Summary

make format more easier with hooks, just like `create-react-app`.

## Changelog

[General][Workflow] - improve develop efficiency with husky and lint-staged.

## Test Plan

pass current ci

### CODE REVIEW

**Comment by cpojer** [comment]
@hramos do you think this is ok to do and will work with the facebook-github-bot? Basically I'm worried that we make a change internally that won't pass lint rules, which would mess up applying the changes from Mercurial to git and will hold up commits to GitHub until we fix it internally. That would be bad.

(also cc @zpao)

**Comment by hramos** [comment]
I've had mixed experiences using a similar approach in the facebook/react-native-website repo. I probably won't have time to look at this today, let me think about it.

**Comment by gengjiawen** [comment]
@hramos Which part do you dislike. I has been using `husky` + `lint-staged` for a long time. Pretty work well for me. Maybe some cases I am missing ?

**Comment by zpao** [comment]
We shouldn't end up with any actual hooks in fresh clones (eg shipit syncs) since that'll require the post install hook of husky to set up (IIRC) and we don't run that. I think the problem is that since we won't be running this internally, we'll sync code and then the next PR will be making formatting changes to unrelated files.

**Comment by gengjiawen** [comment]
I see https://github.com/facebook/create-react-app/blob/master/package.json using it.

**Comment by cpojer** [comment]
@gengjiawen create-react-app doesn't sync with Facebook, so that's why it can be used there. I'm sorry to have to close this but it seems like FB's tooling isn't going to play nicely with this, so we'll have to keep relying on CI to give us this signal for now.

**Pull request closed without merging**
