### PR TITLE
ActionSheetIOS add destructiveButtonIndexes array

### PR DESCRIPTION
**Pull request by sdg9**
## Motivation (required)

iOS [Action Sheets docs](https://developer.apple.com/ios/human-interface-guidelines/ui-views/action-sheets/) say 

> Make destructive choices prominent. Use red for buttons that perform destructive or dangerous actions, and display these buttons at the top of an action sheet.

Currently ActionSheetIOS's showActionSheetWithOptions only supports a single destructive button via the prop `destructiveButtonIndex`.  

This PR maintains backwards compatibility with `destructiveButtonIndex` while simultaneously supporting `destructiveButtonIndexes` allowing developers to pass an array of destructive indexes

## Test Plan (required)

```js
ActionSheetIOS.showActionSheetWithOptions({
  options: ['one', 'two', 'three'],
  destructiveButtonIndexes: [0, 1],
}, () => {});
```
actionsheet

Some additional tests, all working as expected (item only red if it is a matching index).

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
      destructiveButtonIndexes: [0, 19],
    }, () => {});
```

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
      destructiveButtonIndexes: [],
    }, () => {});
```

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
      destructiveButtonIndexes: undefined,
    }, () => {});
```

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
    }, () => {});
```

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
      destructiveButtonIndexes: [0, 5, 0, 0],
    }, () => {});
```

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
      destructiveButtonIndexes: [0, 5, 0, 0, 'non numeric', 12.34],
    }, () => {});
```

The following will crash the app but I believe this is expected

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
      destructiveButtonIndexes: 'not an array',
    }, () => {});
```

```js
    ActionSheetIOS.showActionSheetWithOptions({
      options: ['one', 'two', 'three'],
      destructiveButtonIndexes: null,
    }, () => {});
```

- [x] Explain the **motivation** for making this change.
- [x] Provide a **test plan** demonstrating that the code is solid.
- [x] Match the **code formatting** of the rest of the codebase.
- [x] Target the `master` branch, NOT a "stable" branch.

### CODE REVIEW

**Comment by janicduplessis** [comment]
Thanks for the PR!

I think we should avoid having 2 options to do the same thing. I can think of 2 possibilities; allow passing both `int` and `Array<int>` to `destructiveButtonIndex` or add `destructiveButtonIndices` (We seem to use indices over indexes in the codebase) and deprecate `destructiveButtonIndex`.

I'm leaning a bit for the first solution since we won't have to deprecate anything and even if it isn't the best naming probably that 99% of the time people will want only 1 destructive button.

**Comment by sdg9** [comment]
To avoid two properties doing similar things I agree your first suggestion is the more pragmatic approach.  

Can I get confirmation that overloading destructiveButtonIndex to accept an int or array of ints is the desired approach before I update the code?

**Comment by janicduplessis** [comment]
Yes this is fine! Thanks

**Comment by sdg9** [comment]
@janicduplessis sorry for the delay, thanks for the help @noahmalmed

**Comment by ken0x0a** [comment]
plz merge this I want to use.
even Instagram using multiple destructive button.
Why not?

**Comment by janicduplessis** [comment]
@ken0x0a This was merged in https://github.com/facebook/react-native/pull/18254

**Comment by ken0x0a** [comment]
@janicduplessis Thank you for your reply!

I forget that I wrote here.
Actually I found this was merged, but even though I can not use because expo/react-native still not merge #18254.

I'm now waiting for expo merge this.

**Pull request closed without merging**
