### PR TITLE
Implement EventTarget interface for WebSocket.

### LINKED ISSUE #2583: [WebSocket] WebSocket polyfill does not implement EventTarget interface
```
Error: ws.addEventListener is not a function
```
specs: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

### PR DESCRIPTION
**Pull request by leeyeh**
close #2583

### CODE REVIEW

**Comment by leeyeh** [comment]
The test passed locally. It seems that the new node package `event-target-shim` is not installed properly in travis. Maybe [the cache node_modules config](https://github.com/facebook/react-native/blob/master/.travis.yml#L7) is relevant.

**Comment by ide** [comment]
cc @frantic @vjeux this PR looks good and web sockets are mostly Community Responsibility. What's the process for adding new npm dependencies? Should PRs update npm-shrinkwrap.json?

**Comment by vjeux** [comment]
@ide ping someone from the team to pull the npm module internally. Sucks but well :(

**Comment by ide** [comment]
OK. I am accepting this. When this is imported, it will be necessary for someone at FB to download the "event-target-shim" module and rebuild npm-shrinkwrap.json.

**Comment by ide** [comment]
@vjeux could you or someone else familiar with adding a new npm module help import this? There are some Android websocket diffs that are blocked on this one.

**Comment by vjeux** [comment]
@facebook-github-bot import

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
