### PR TITLE
Fix android platform border color

### PR DESCRIPTION
**Pull request by axinvd**
## Summary:
If you try to apply PlatformColor to borders on Android app will crash with the next error:

"Error while updating property 'borderColor' of a view managed by: RCTView"

## Changelog:

[ANDROID] [FIXED] - Fix android crash when apply PlatformColor to borders

## Test Plan:

In RNTester example, go to APIs -> PlatformColor
|    Before  | After |
| ----------- | ----------- |
|  drawing    | drawing      |

### CODE REVIEW

**Comment by axinvd** [comment]
Fixes:
https://github.com/facebook/react-native/issues/38950
https://github.com/facebook/react-native/issues/38614
https://github.com/facebook/react-native/issues/32942

**Comment by javache** [comment]
Thanks! Could you test this on the new architecture too?

**Comment by axinvd** [comment]
I tested on rn-tester, where new arch enabled by default

**Comment by javache** [comment]
The code you're changing only applies on the old architecture. The new architecture uses `BaseViewManagerDelegate`, which seems like it still has the same issue.

**Comment by axinvd** [comment]
In BaseViewManagerDelegate setting native view properties like setBackgroundColor
BorderColor setting in ReactViewBackgroundDrawable

**Pull request closed without merging**
