### PR TITLE
Adding Bdsdiet to Showcase

### PR DESCRIPTION
**Pull request by osungjin**

### CODE REVIEW

**Comment by osungjin** [comment]
This app is only local service in South Korea and therefore I attached local media news.
Is it okay?

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by lacker** [comment]
Hmm, the problem is that basically all of this website audience is English-speakers, so if they follow this link they will find it unuseful. Is there anything about this app or about this company in English? Like if this is a funded startup is there some funding announcement?

**Comment by osungjin** [comment]
@lacker Check it plz.

**Comment by lacker** [comment]
Can you make the name "BDS Diet" for consistency with that link?
Also that title seems a bit awkwardly phrased. How about "BDS Diet provides real estate brokerage services in Korea."

**Comment by osungjin** [comment]
Thanks. The sentence was modified naturally. Also name was modified to Bdsdiet.
Anything else?

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1624512257865247/int_phab) to review.

**Pull request closed without merging**
