### PR TITLE
Fix typo in NavigationTransitioner

### PR DESCRIPTION
**Pull request by jmurzy**
Typo.

🍺

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @bhosmer to be potential reviewers.

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1007557735959004/int_phab) to review.

**Pull request closed without merging**
