### PR TITLE
Fix textTransform when used with other text styles on Android

### PR DESCRIPTION
**Pull request by janicduplessis**
On Android `textTransform` breaks other styles applied to the text. It seems related to the usage of `ReplacementSpan` which allows drawing the text manually but seems to throw away some changes made by other span applied to the text.

To fix it I removed the usage of `ReplacementSpan` and simply transform the text before appending it to the `Spannable` string. To make sure textTransform is inherited correctly I added it to TextAttributes which handles this.

Test Plan:
----------
I added a test case to RNTester. It should render turquoise text on a blue background. It also adds line height and letter spacing to make sure the text is properly measured and all styles are applied.

Before the fix:
screen shot 2018-12-15 at 8 16 30 pm

After the fix:
screen shot 2018-12-15 at 8 15 05 pm

Also made sure all existing text transform examples produce the expected result.

Changelog:
----------
[Android] [Fixed] - Fix textTransform when used with other text styles on Android

### CODE REVIEW

**Comment by kristerkari** [comment]
This will most likely fix https://github.com/facebook/react-native/issues/21966, right?

**Comment by janicduplessis** [comment]
@kristerkari I think so, I can test with an example from the issue

**Comment by janicduplessis** [comment]
@rigdern Quite possible, I just tested on snack but `textTransform` on android doesn't work on latest expo yet.

This should print `aB`
```js
<Text style={{textTransform: 'uppercase'}}>
  <Text style={{textTransform: 'none'}}>a</Text>
  <Text style={{textTransform: null}}>b</Text>
</Text>
```

I can test it when I get on a computer.

**Comment by janicduplessis** [comment]
@rigdern you were right https://github.com/facebook/react-native/pull/22694

**Comment by hramos** [comment]
@rigdern's changes landed in f6f8b092f9dac03e81cb01a73e748f3df85ea519. @janicduplessis do you still want your changes to be incorporated? If so, let me know if you can resolve the conflicts.

Thanks to both of you for working on getting these issues addressed!

**Comment by janicduplessis** [comment]
@hramos Looks like https://github.com/facebook/react-native/pull/22917 will also conflict with this. I think we should try to land #22917 first and then I can rebase this on top of the improvements to text inheritance that @rigdern implemented.

**Comment by rigdern** [comment]
@janicduplessis #22917 has been merged.

**Comment by janicduplessis** [comment]
@hramos @rigdern Rebased on top of #22917 and re-tested to make sure everything still works. I also included the little fix in #22694 since I ended up changing these lines.

**Comment by rigdern** [comment]
@janicduplessis The PR description says:

> To do that I can pass the parent's textTransform when recursing through text shadow nodes.

This sentence seems to need to be updated now that this information is passed around via `TextAttributes.java`

**Pull request closed without merging**
