### PR TITLE
Android: Setting numberOfLines to 0 behaves differently than on iOS.

### PR DESCRIPTION
**Pull request by manicakes**
**Motivation**

For the `Text` component, if `numberOfLines` is set to `0`, the behavior on iOS is such that there is no limit.

On Android, the behavior is such that `numberOfLines={0}` will not render the `Text` component.

Since we want behavior to be the same across platforms, this change will make sure Android behaves the same as iOS.

**Test Plan**

Create a `Text` component specifying `numberOfLines={0}` on an Android project.

Expected:
- `Text` component displays, with no limit to number of lines.

Result:
- `Text` component does not appear at all.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @skv-headless and @axelander to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by dmueller39** [comment]
This would be helpful in keeping consistency between Android and ios behaviors.

**Comment by facebook-github-bot-2** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@manicakes updated the pull request.

**Comment by manicakes** [comment]
@kmagiera @mkonicek any thoughts on this? This is a very simple/safe code change that fixes an inconsistency between iOS/Android. Thanks in advance. :)

**Comment by ide** [comment]
I think this looks good, would like someone familiar with the code to sign off though.

**Comment by manicakes** [comment]
Thanks @ide !

**Comment by facebook-github-bot-3** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@manicakes updated the pull request.

**Comment by manicakes** [comment]
@skv-headless @vjeux wondering if someone familiar with the code could take a look and give feedback or merge? It's a super simple fix, so shouldn't take long. :) Thanks in advance!

**Comment by skv-headless** [comment]
I think bot isn't working correct I didn't touch this lines. @kmagiera and @mkonicek did. For me everything looks great 👍

**Comment by facebook-github-bot-5** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@manicakes updated the pull request.

**Comment by ekryski** [comment]
This looks good to me. 😄

**Comment by facebook-github-bot-5** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@manicakes updated the pull request.

**Comment by ide** [comment]
Merging this since it looks right to me and is simple, and is easy to revert if needed.

@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3697115) to review internal test results.

**Comment by manicakes** [comment]
@ide you da man! Thanks!

**Comment by facebook-github-bot-5** [comment]
@manicakes updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@manicakes updated the pull request.

**Pull request closed without merging**
