### PR TITLE
[npm] Remove unused npm packages and move CI dependency to devDependencies

### PR DESCRIPTION
**Pull request by ide**
There are several npm packages that are no longer used and do not show up when grepping the code base. Also the "async" dependency is used only in CI and should be moved to devDependencies.

Test Plan: Load the UIExplorer. Run Travis CI, Circle CI, and FB internal tests.

### CODE REVIEW

**Comment by skevy** [comment]
@ide this should be either cleaned up or closed, given the recent changes to dependencies with the packager moving.

**Comment by ide** [comment]
Updated this PR. @hramos could you please re-import this when you have a chance to?

**Comment by cpojer** [comment]
This is awesome!

**Comment by hramos** [comment]
I'll take a look at this after #14880 lands.

**Pull request closed without merging**
