### PR TITLE
replace var to const on uiexplorer

### PR DESCRIPTION
**Pull request by skv-headless**
to unification

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @sebmarkbage and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@skv-headless updated the pull request.

**Comment by dsibiski** [comment]
Thanks for the contribution!

However, perhaps some of the things mentioned in the following PR from the React repo might ring true for this kind of "sweeping" change as well: https://github.com/facebook/react/pull/6463

Maybe @vjeux or @mkonicek have something to say about it...

**Comment by skv-headless** [comment]
As you wish. I can close PR. It is just strange to me that one project written in different styles.

**Comment by janicduplessis** [comment]
I think this is fine since it's example code.

**Comment by dsibiski** [comment]
@skv-headless I wasn't asking you to close this, simply saying that "perhaps" it was something to be careful of based on how some of the core members felt about it. @janicduplessis brings up a good point that it's only example code.

That being said, it looks like there are a couple more linter issues, if you could fix these this PR might be something others find no problem with as well. 👍

**Comment by skv-headless** [comment]
Ok. I just don't want to increase number of PRs.

**Comment by mkonicek** [comment]
However, perhaps some of the things mentioned in the following PR from the React repo might ring true for this kind of "sweeping" change as well: facebook/react#6463

I'm not a "blame purist" if a change is useful but it's true this will make the blame bot cc you on this code all the time now :)

**Comment by mkonicek** [comment]
Looks like there are some related test failures:
https://circleci.com/gh/facebook/react-native/5887

**Comment by skv-headless** [comment]
I've seen. I decided don't fix until any approve.

**Comment by satya164** [comment]
@skv-headless until who approves? ;)

**Comment by skv-headless** [comment]
until any feedback

**Comment by satya164** [comment]
@skv-headless AFAIK nobody really has strong opinions against this, and we've merged such PRs in past. So I think it should be fine to merge this PR.

**Comment by skv-headless** [comment]
Have a problems with rebase. I think it doesn't worth it.

**Pull request closed without merging**
