### PR TITLE
Android WebSocket: include cookies in request

### PR DESCRIPTION
**Pull request by antoinerousseau**
This PR updates #6851 from @srikanthkh, fixing coding conventions and javadoc, and adding a test plan.
## Test plan

Added testing functions into the WebSocketExample page of the UIExplorer, including a tiny http server to set a cookie on demand. Instructions included in the UIExplorer app.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @philikon and @AndrewJack to be potential reviewers.

**Comment by zxcpoiu** [comment]
@facebook-github-bot label Android

**Comment by shirou** [comment]
Hi, is there any update? I met same issue and resolved with this great PR.

**Comment by facebook-github-bot-9** [comment]
@antoinerousseau updated the pull request.

**Comment by antoinerousseau** [comment]
@shirou I wish someone from FB would realize that this PR is ready to be merged!

**Comment by facebook-github-bot-0** [comment]
@antoinerousseau updated the pull request.

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @philikon as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by shirou** [comment]
@antoinerousseau Could you update this branch?

@philikon Could you review and if there are no problem, merge this PR? or if you have some concern, I will help. We really need this PR.

Thank you.

**Comment by facebook-github-bot-1** [comment]
@antoinerousseau updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9114/files/2fd49f79410e2978dd454df50c509e9883465118..83deb24debf23aed9c91214313b9a50bf2e3856a)

**Comment by lacker** [comment]
Why is this the right behavior? It's not clear to me that websockets should automatically use cookies.

FWIW https://github.com/facebook/react-native/pull/10575 is a similar pull request.

**Comment by lacker** [comment]
Chatted with some folks internally to make sure this is 1/ philosophically what we want to do and 2/ wont break FB apps and this seems good.

@facebook-github-bot shipit

**Pull request closed without merging**
