### PR TITLE
feat(iOS): line break mode implement JS APIs for the new mode

### PR DESCRIPTION
**Pull request by shubhamguptadream11**
## Summary:

Solves this issue: https://github.com/facebook/react-native/issues/44107

## Changelog:

[IOS] [ADDED] - Line break mode for TextInput components. **This includes JS APIs for the new mode.**

This PR is a breakdown of [this](https://github.com/facebook/react-native/pull/45968) PR.

## Test Plan:

- Added unit tests to cover the new JS APIs.
- Verified that the new mode functions as expected through manual testing.

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
great job, thanks for doing this work!

**Comment by shubhamguptadream11** [comment]
Hi @cipolleschi,

I hope you're doing well. I noticed that the C++ implementation and linking parts of this prop were merged—thanks for that! The JavaScript part is still pending.

Could you please take a look and merge it when you have a moment? If there's anything you'd like me to adjust, just let me know.

Thank you for your time and support!

**Comment by cipolleschi** [comment]
Hi @shubhamguptadream11! Sorry for not explain it beforehand.
For how the internal infrastructure work, I need soak the native part for some days before I can ship the JS part. I can see what's the state of the infra on Thursday, but it's more likely that I can actually land the JS part next week.

**Comment by shubhamguptadream11** [comment]
@cipolleschi Thanks for the clarification! That makes sense. I appreciate you taking the time to ensure everything is stable.
Thanks

**Comment by shubhamguptadream11** [comment]
Hi @cipolleschi 
I hope you're doing well. I wanted to follow up on the status of the JS part of the PR.

**Comment by shubhamguptadream11** [comment]
Hi @cipolleschi ,

I hope you're doing well. Just wanted to kindly follow up on the status of the JS part of the PR. I understand you may be busy, but I’d appreciate any updates or feedback when you have a moment.

Thank you for your time and consideration!

**Pull request closed without merging**
