### PR TITLE
 Renamed react-native-gradle-plugin to @react-native/gradle-plugin

### PR DESCRIPTION
**Pull request by rahul3002**
## Changelog

[CATEGORY] [TYPE] - Message

### CODE REVIEW

**Review by cortinico — CHANGES_REQUESTED** [review]
Hey @rahul3002 
Thanks for your PR.

You should fine by just updating this field:
https://github.com/facebook/react-native/blob/a0d1585cdb5ae86e5d4e5bc51fdfa9ae7e049b4b/packages/react-native-gradle-plugin/package.json#L2
to `@react-native/gradle-plugin`.

Then you should update all the references. Please don't move files or folder as we can't import this otherwise.

Let's also make sure the CI is green first.

**Comment by rahul3002** [comment]
should i change reference of every file

**Comment by cortinico** [comment]
> should i change reference of every file

You should check where `react-native-gradle-plugin` is used replace it with `@react-native/gradle-plugin`

**Comment by rahul3002** [comment]
I have renamed all reference files  react-native-gradle-plugin is used and replaced it with this  @react-native/gradle-plugin
one file I'm unable to edit that file don't what happened I have forked this repository then also

.circleci /verridco.yml I'm unable to see In my fork how could i solve this issue

**Comment by rahul3002** [comment]
I'm trying to solve this conflicts but its not giving access to me

**Comment by cortinico** [comment]
> .circleci /verridco.yml I'm unable to see In my fork how could i solve this issue

I think you should rather close this PR and send a new one. To bring your Fork up to date, just re-fork the repo ro use the button that Github offers on the UI to do so

**Comment by rahul3002** [comment]
ok will do it

**Pull request closed without merging**
