### PR TITLE
Add support for overriding entry file in react-native-xcode.sh

### PR DESCRIPTION
**Pull request by kennethlynne**
We need this as we have our codebase in typescript, and a different folder structure than the default

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @frantic and @clickthisnick to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by frantic** [comment]
Hey @kennethlynne, thank you for your pull request. The `react-native-xcode.sh` script was designed to make the initial experience with React Native seamless. Indeed, the script is very simple and makes a lot of assumptions about the structure of your project.

However, if it doesn't fit your needs anymore, I recommend copying it into your source tree and changing Xcode to use your forked script. You will have more freedom over what happens and when. There is a trade-off in accepting this PR – it adds another configuration change that serves only small percent of the users. It will require maintenance and also encourage other people to tune it to fit their needs.

**Pull request closed without merging**
