### PR TITLE
[Flow] Deal with 0.38 'FlowFixMe's

### PR DESCRIPTION
**Pull request by rh389**
Largely typing fixes to deal with the glut of new `FlowFixMe` suppressions introduced with flow 0.38 in https://github.com/facebook/react-native/commit/a4bfac907ece6c1b28c2632aa2681387a1d6682d

Tested with flow itself. CC @gabelevi

### CODE REVIEW

**Comment by ericvicenti** [comment]
Can you resolve conflicts and ping me? I'll start landing as soon as you've rebased

**Comment by rh389** [comment]
@ericvicenti - Thanks, that's done.

**Comment by rh389** [comment]
@ericvicenti Any idea what happened here? The tests passed and the branch was up to date but import failed. Happy to resubmit as a new PR if that'll help.

**Comment by mkonicek** [comment]
Thanks for doing this! Tests passed. Not sure why if failed internally. Merging again.

**Pull request closed without merging**
