### PR TITLE
Fix that BackHandler was not called on Android

### PR DESCRIPTION
**Pull request by jerolimov**
This fixes issues #18954 and #15497

The transformation from Set to (an reversed) Array does not work on Android devices when the remote debugging was started with `react-native run-android`.

## Test Plan

Add the following code to your App.js and run the app with `react-native run-android` in an Android device:

```
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', () => {
      console.warn('Callback called. Do not close app. Do nothing at all.');
      return true; // Do not close the app.
    });
  }
```

After adding this, the app should NOT close when you press the back button. Without this fix, the app closes (which is the default behaviour).

See also the comments from @Victoriayangx in #18954 and #15497.

## Related PRs

#17820 by @AuroreM tries to fix this also by improving the iterator polyfill. (See this after creating this PR...)

## Release Notes

[ANDROID] [BUGFIX] [BackHandler] - Fix that BackHandler was not called on Android

### CODE REVIEW

**Comment by jerolimov** [comment]
@facebook-github-bot ping

**Comment by jerolimov** [comment]
Over 50 days and zero feedback 😞

**Comment by jerolimov** [comment]
Ping @TheSavior @sophiebits @rubennorte because you already worked on the changed file.

**Comment by jerolimov** [comment]
@eslint-bot ping

**Comment by TheSavior** [comment]
Fwiw, it is hard to feel confident merging this because I’m not sure anyone on our team is familiar with this code and the potential edge cases that could occur which might not be in the happy path you mention in your test plan.

For this to get some more traction we probably need to hear from more people that it works for them and didn’t cause any problems. If there are other edge cases you can think of which you can test and include in your test plan that would be great.

Essentially, can you help us feel more confident in this change? :-/

**Comment by jerolimov** [comment]
@TheSavior In some environments the Set operators .add .delete .reverse does not work as expected. I did not understand why exactly this happen, because I have also projects which has no problem here. But you can see some other people running into this issue: #18954 and #15497

I'm also unhappy that nobody verifies this.. But in the one project we had, changing this implementation from Set to an Array works fine.

The API works still the same way.

https://github.com/facebook/react-native/blob/e09622c68aec0da301cd0c622b7baf50eaaf5683/Libraries/Utilities/BackHandler.android.js

1. The app could add and remove event listeners to BackHandler (line 74 and 89). Sure, a Set provides some easier api, but based on the problem that it doesn't work.. I switched this to Array.push and Array.splice.
2. The listeners was called in reverse order, which means last listener first (line 24)
3. If one if these added listeners return true (or truthy), it means "I handled the back button", stop calling the other listeners and do not close the app. (line 26)
4. If no listener return a true (or truthy) value, "nobody" handles the back button and we want to close the app (line 30)

**Comment by TheSavior** [comment]
Alright, this seems fine. Let’s give it a shot. I can’t import from my phone so pinging @hramos to land, otherwise I’ll land later.

**Pull request closed without merging**
