### PR TITLE
Adding http as failover for react-tools git repo.

### LINKED ISSUE #2797: Init project hangs forever
I cannot create a new react-native project any more (worked yesterday). The init command hangs forever in this state:

```
$ react-native init MyProject
This will walk you through creating a new React Native project in /Users/.../Projects/MyProject
\
```

The directory `MyProject` gets created with a single file `package.json` with the following content:

```
{"name":"MyProject","version":"0.0.1","private":true,"scripts":{"start":"node_modules/react-native/packager/packager.sh"}}
```

The slash/backslash is still flipping but no matter how long I wait, nothing happens. Connection to NPM is working generally, e.g. I'm able to install new packages, so my internet connection should be fine.

I tried with Node 4.0.0 as well as latest Node 4.1.0 and NPM 2.14.3.

I'm curious because yesterday everything worked like a charm, so I guess my general config is fine.

Any help?

### PR DESCRIPTION
**Pull request by knightsamar**
Fixes #2797 for me.

Most times git://github.com/facebook/react-tools times out. So adding
http as a fail-over so that if git protocol doesn't work while cloning
the react-tools repo as a dependency, http would atleast work and ensure
that a simple "react-native init myProject" doesn't fail.

Submitting a PR so that http is used as a failover when cloning. (I guess that is what git+http does in package.json)

### CODE REVIEW

**Comment by ide** [comment]
Can you change it to https?

**Comment by spicyj** [comment]
We could also look at using a .tgz URL?

**Comment by knightsamar** [comment]
@spicyj @ide Wish I could both as another level of fail-over :)

**Comment by spicyj** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
