### PR TITLE
removed mocks to React in a few tests because they fail tests on CI

### PR DESCRIPTION
**Pull request by bestander**
jest tests got broken on CircleCI with this change https://circleci.com/gh/facebook/react-native/5586

This is very mysterious because I can't reproduce the problem with the same node/npm version locally.
The tests fail because jest.mock('React') throws a "no haste module found" error.

### CODE REVIEW

**Comment by bestander** [comment]
Tried clearing caches on CI but it does not help.
Wild guess - tests don't fail on Mac because filesystem is not case sensitive?

**Comment by sebmarkbage** [comment]
lgtm

**Comment by bestander** [comment]
That is a quick fix but it just fixes a particular test for linux, still linux development is most likely broken.
Preparing an internal true diff

**Comment by bestander** [comment]
Fix will be coming from inside D3212561, discussion is happening

**Pull request closed without merging**
