### PR TITLE
Add skewX and skewY to the transform style options

### PR DESCRIPTION
**Pull request by browniefed**

### CODE REVIEW

**Comment by browniefed** [comment]
Seems to fail because of https://github.com/facebook/react-native/pull/2649

**Comment by ide** [comment]
cc @sahrens @vjeux

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Hey, do you mind rebasing on-top of the latest version, it doesn't apply cleanly anymore :( Sorry about that

**Comment by vjeux** [comment]
I just rebased myself, should land soon

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by browniefed** [comment]
@vjeux sorry about that, on vacation, and away from computer. Thanks for rebasing.

**Pull request closed without merging**
