### PR TITLE
RNTester Android: Add stub C++ for TurboModule provider

### PR DESCRIPTION
**Pull request by fkgozali**
Summary:
This is the base setup to compile C++ as part of RNTester app. There is no dependencies on ReactAndroidNdk lib yet, just a bunch of ndkBuild setup in Gradle. Note: this is using Gradle's `nkdBuild` support instead of calling `ndk-build` manually like in ReactAndroid/build.gradle.

Reference: https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.ExternalNativeNdkBuildOptions.html

Note that `ANDROID_NDK` env var is honored to pick the right NDK version.

For now, this is gated behind `USE_CODEGEN` env variable.

Changelog: [Internal]

Differential Revision: D23887058

### CODE REVIEW

**Comment by fkgozali** [comment]
cc @dulmandakh @Kudo @safaiyeh @gedeagas - just FYI to showcase the need of NDK build for RNTester going forward. Tagging you all because of recent discussion in https://github.com/facebook/react-native/pull/29987

Using Android Gradle plugin's `ndkBuild` seems to honor `ANDROID_NDK` env var. Note that I didn't have https://github.com/facebook/react-native/pull/29987 on my branch, so nothing specifies the NDK version in gradle for me.

**Comment by safaiyeh** [comment]
Great this is awesome! Creates a nice DX when first setting up RN without knowing the NDK versions

**Comment by fkgozali** [comment]
Side note: we should eventually convert the manual ndkBuild script in https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle#L313-L327 to use the same Android Gradle `ndkBuild`.

**Comment by gengjiawen** [comment]
@fkgozali Build failed with

```console
Build command failed.
Error while executing process /Users/daniel/Library/Android/sdk/r17c/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/daniel/code/react-native/packages/rn-tester/android/app/src/main/jni/Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=/Users/daniel/code/react-native/packages/rn-tester/android/app/build/intermediates/ndkBuild/hermesDebug/obj NDK_LIBS_OUT=/Users/daniel/code/react-native/packages/rn-tester/android/app/build/intermediates/ndkBuild/hermesDebug/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++1y APP_PLATFORM=android-16 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/daniel/code/react-native/packages/rn-tester/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/daniel/code/react-native/packages/rn-tester/android/app/build REACT_ANDROID_DIR=/Users/daniel/code/react-native/ReactAndroid APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:/Users/daniel/code/react-native/packages/rn-tester/android/app/src/main/jni/Android.mk:react_codegen_reactandroidspec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/daniel/code/react-native/packages/rn-tester/android/app/build/react-ndk/exported/arm64-v8a/libreact_codegen_reactandroidspec.so exists  or that its path is correct   

/Users/daniel/Library/Android/sdk/r17c/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

Any idea ?

**Comment by fkgozali** [comment]
Looks like the :ReactAndroid NDK didn't get built before building :rn-tester target. I fixed something with this commit: https://github.com/facebook/react-native/commit/b931bd33fee1a2a1fb4e26fcd5a469c16bfe425d - if you are on the latest master, it should work?

> Check that /Users/daniel/code/react-native/packages/rn-tester/android/app/build/react-ndk/exported/arm64-v8a/libreact_codegen_reactandroidspec.so exists  or that its path is correct

That .so should've been copied over by this Android-prebuilt.mk configuration:
https://github.com/facebook/react-native/blob/2a3c26e97539569f7c6e783c7262c50fdafad8e2/ReactAndroid/Android-prebuilt.mk#L92

**Comment by gengjiawen** [comment]
I am using latest master with this patch, the build still failed.

```diff
diff --git a/packages/rn-tester/android/app/build.gradle b/packages/rn-tester/android/app/build.gradle
index e92dc1c6c3..7f9ac2339a 100644
--- a/packages/rn-tester/android/app/build.gradle
+++ b/packages/rn-tester/android/app/build.gradle
@@ -85,8 +85,8 @@ project.ext.react = [
     hermesCommand: "$rootDir/node_modules/hermes-engine/%OS-BIN%/hermesc",
     enableHermesForVariant: { def v -> v.name.contains("hermes") },
     jsRootDir: "$rootDir/RNTester",
-    enableCodegen: (System.getenv('USE_CODEGEN') ?: '0').toBoolean(),
-    enableFabric: (System.getenv('USE_FABRIC') ?: '0').toBoolean(),
+    enableCodegen: true,
+    enableFabric: true,
 ]
```

**Comment by fkgozali** [comment]
Oh, there are a bunch of places where the USE_CODEGEN is used, so I recommend doing this instead of hardcoding to true:

```
USE_CODEGEN=1 ./gradlew ...
```

**Comment by gengjiawen** [comment]
Thanks, it worked.

**Comment by nomi9995** [comment]
@fkgozali 
I am using react-native@0.0.0-20220120-2008-2f67f5d68 nightly release

https://github.com/nomi9995/react-native-turbomodule-fabric-renderer-boilerpate

I am always getting this error from `android.mk`, is there anything, I am doing wrong?
```
C/C++: fcntl(): Bad file descriptor
C/C++: /Users/apple/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
[CXX1405] error when building with ndkBuild using /Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/src/main/jni/Android.mk: Build command failed.
Error while executing process /Users/apple/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/src/main/jni/Android.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 NDK_OUT=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/build/intermediates/cxx/Debug/1e4i2923/obj NDK_LIBS_OUT=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/build/intermediates/cxx/Debug/1e4i2923/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/build REACT_ANDROID_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/../node_modules/react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/android/app/build/react-ndk/exported/x86/libfb.so exists  or that its path is correct   

fcntl(): Bad file descriptor
/Users/apple/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

C/C++: /Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/../ReactCommon/butter/Android.mk:28: *** Android NDK: Aborting.    .  Stop.
[CXX1405] error when building with ndkBuild using /Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk: Build command failed.
Error while executing process /Users/apple/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/681pv6ab/obj NDK_LIBS_OUT=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/681pv6ab/lib NDK_APPLICATION_MK=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/src/main/jni/Application.mk THIRD_PARTY_NDK_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/build/third-party-ndk REACT_COMMON_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/../ReactCommon REACT_GENERATED_SRC_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/build/generated/source REACT_SRC_DIR=/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react -j12 --output-sync=none APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: WARNING: Ignoring unknown import directory: /Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/build/generated/source    
Android NDK: /Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/../ReactCommon/butter/Android.mk: Cannot find module with tag 'glog' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         

/Users/apple/Data/Work/reactnative/ReactNativeTurbomoduleFabricRendererBoilerpate/node_modules/react-native/ReactAndroid/../ReactCommon/butter/Android.mk:28: *** Android NDK: Aborting.    .  Stop.
```
https://github.com/facebook/react-native-website/pull/2879#discussion_r789385019

**Comment by cortinico** [comment]
> facebook/react-native-website#2879 (comment)

Addressed here https://github.com/facebook/react-native-website/pull/2879#discussion_r789627402

**Pull request closed without merging**
