### PR TITLE
Add option to hide context menu for TextInput

### PR DESCRIPTION
**Pull request by amhinson**
## Motivation

There is currently no way to disable to context menu that automatically appears over a TextInput. This is especially troublesome if you would like to disable the user from pasting text into certain fields. This PR adds a `contextMenuHidden` property to TextInput that will hide it.

## Test Plan

I'm not sure if testing is necessary here. I would be happy to investigate further on how this would be tested, if deemed necessary!

## Related PRs

https://github.com/facebook/react-native-website/pull/95

## Release Notes

[FEATURE][TextInput] - Added `contextMenuHidden` property

### CODE REVIEW

**Comment by amhinson** [comment]
PR updated with latest adjustments to TextInput.

**Comment by polarbear2010** [comment]
Coming from https://facebook.github.io/react-native/docs/0.53/textinput.html#contextMenuHidden
and suddenly realise that this beautiful PR is not yet merged..... Anything to do to speed up the merge?

**Comment by amhinson** [comment]
@facebook-github-bot PR updated

**Comment by hramos** [comment]
Hold on - looks like you've added some changes after the PR was approved. Might want to open a new PR because the changes made after the PR was approved won't be included.

**Comment by amhinson** [comment]
@hramos Oh ok sorry about that. There was a merge conflict that was just introduced after the approval. I'll create a new PR real quick.

**Comment by amhinson** [comment]
https://github.com/facebook/react-native/pull/18125

**Comment by hramos** [comment]
No need to close the PR -_- it was in the process of being merged...

**Comment by amhinson** [comment]
Ah I misunderstood. Sorry!

**Pull request closed without merging**
