### PR TITLE
fix bugs: navigator scene rerender

### PR DESCRIPTION
**Pull request by soliury**
Fix bugs: https://github.com/facebook/react-native/issues/5726

### CODE REVIEW

**Comment by chirag04** [comment]
dupe https://github.com/facebook/react-native/pull/3016. This will break navigator replace.

You can use `shouldComponentUpdate`

**Comment by soliury** [comment]
You mean add the `shouldComponentUpdate ` to the scene Component?

**Comment by chirag04** [comment]
yes

**Comment by soliury** [comment]
But it don't work

**Comment by soliury** [comment]
I have find why it don't work. I have fixed it. It because I use redux, and I wrapper the component in renderScene function, I should wrapper the component before I push the route.

**Pull request closed without merging**
