### PR TITLE
getCurrentConnectivity should resolve with object

### PR DESCRIPTION
**Pull request by l-urence**
`getCurrentConnectivity()` should resolve with object instead of array otherwise in `NetInfo.fetch().done(reach => console.log('Initial: ' + reach))` `reach` will be undefined (see https://github.com/l-urence/react-native/blob/master/Libraries/Network/NetInfo.js#L200).

cc @satya164

### CODE REVIEW

**Comment by l-urence** [comment]
As far as I can see Android looks good. But never tested.

**Comment by corbt** [comment]
I've also noticed that `NetInfo.fetch` appears broken currently, and it looks like this should fix it. Do you have a test plan? Perhaps a code sample that shows how it was broken before and now works?

**Comment by satya164** [comment]
cc @bestander @nicklockwood

**Comment by corbt** [comment]
I think `NetInfo.fetch` was just forgotten in https://github.com/facebook/react-native/commit/c9a1956c4fd9cfb6bf883c835b501d097181e1a4. Probably would be worth looking for calls to `RCTPromiseResolveBlock` and making sure nothing else was missed.

**Comment by satya164** [comment]
ccing @dmmiller too

**Comment by l-urence** [comment]
Apparently all other `RCTPromiseResolveBlock` calls are okay or at least they do not return an array (`find . -name *.m | xargs egrep 'resolve\('`). 

@corbt The code should now work as described in the [documentation](https://facebook.github.io/react-native/docs/netinfo.html#content).

**Comment by corbt** [comment]
sweet, thanks again for working on this @l-urence.

@facebook-github-bot shipit

**Comment by dmmiller** [comment]
Thanks for catching this one.

**Comment by shraddha1704** [comment]
I upgraded to 0.22 today. I am getting the following error:
   undefined is not an object (evaluating 'RCTNetInfo.getCurrentConnectivity().then')

**Comment by bestander** [comment]
@shraddha1704 this PR was picked into 0.22 release.
Try creating a new issue with more details please

**Comment by shraddha1704** [comment]
Found a solution. Replacing the fetch function in NetInfo.js with:
fetch(): Promise {
    return new Promise((resolve, reject) => {
      RCTNetInfo.getCurrentConnectivity(
        function(resp) {
          resolve(resp.network_info);
        },
        reject
      );
    });
  },

**Comment by satya164** [comment]
@shraddha1704 Your native code seems to be out of date. Run `react-native upgrade` to update your native files.

**Pull request closed without merging**
