### PR TITLE
Generate bundle and assets when building via Xcode

### PR DESCRIPTION
**Pull request by frantic**
This integrates React Native into Xcode's build process, which lets us automatically handle bundling and packaging image assets.

Tested the script via https://github.com/frantic/ReactNativeAssetsExample

Loaded from packager:
screen shot 2015-10-19 at 3 11 12 pm

Loaded from offline bundle:
screen shot 2015-10-19 at 3 10 58 pm

Android:
screen shot 2015-10-19 at 3 11 20 pm

### CODE REVIEW

**Comment by brentvatne** [comment]
@frantic - so all we need to do is put images in `/assets`, no more thinking about Images.xcassets?

**Comment by frantic** [comment]
@brentvatne almost. Documentation coming soon. That's something we've been working on for a while, it just has pretty big surface area. The idea is yes, we provide a cross-platform alternative for `Images.xcassets` - you put your images next to your JS files and require them as you'd require JS file (see [this](https://github.com/frantic/ReactNativeAssetsExample/blob/master/ReactIconView.js#L29)). And behind the scenes packager will figure out what files are needed and we'll bundle them using Xcode (this PR) and Gradle (#3462) hooks.

**Comment by frantic** [comment]
You will still be able to use `Images.xcassets` or Android drawables if you want to, but this means you'd have to maintain them yourself. `require('image!stuff')` will be deprecated in favor of good old `{uri: 'stuff'}` and if you use it – it's going to be your responsibility to make sure those images exist and packaged properly. The only benefit I see for this system is when RN is inside a hybrid app and shares images with it.

We are trying to make the new system ("packager managed assets") available for the next release cut.

**Comment by frantic** [comment]
@facebook-github-bot import

**Pull request closed without merging**
