### PR TITLE
react-packager: Switch from Q to Bluebird as promises library

### PR DESCRIPTION
**Pull request by pilwon**
This PR improves performance of `react-packager` by switching the promises library from the [Q](https://github.com/kriskowal/q) to [Bluebird](https://github.com/petkaantonov/bluebird).

[Here is the test result](https://github.com/facebook/react-native/issues/361#issuecomment-87829808) showing a noticeable difference. (2x speed improvement)

Please refer to [this issue](https://github.com/facebook/react-native/issues/361) for more details.

### CODE REVIEW

**Comment by pilwon** [comment]
`Jest` is not running on my machine for some reason. Let me fix it and see where the test fails.

**Comment by pilwon** [comment]
It turns out code works fine but `Jest` gets confused with `bluebird`. (blocker: https://github.com/facebook/jest/issues/90)

@petkaantonov `Jest` works with `Q` but not with `bluebird`. Do we have a solution for this?

**Comment by amasad** [comment]
ok, I think I can fix the jest error (or at least hack around it). I'll work on pulling this

**Comment by amasad** [comment]
Tested on internal source (which is considerably larger) and this yields a consistent 30% speedup. Good job! I'll sync the changes here soon.

**Comment by pilwon** [comment]
@amasad Very nice. I think a lot of folks will enjoy the speed improvement with this update :sparkles: :grinning: :+1:

Btw, I noticed `promisify()` is the only non-standard ES6 Promises feature used in `DependencyGraph`. Not sure about the other modules but if the use of promises library can be kept to minimum like that we may want to search for an even better one. (`Bluebird` is still my #1 choice but you never know...)

**Comment by pilwon** [comment]
@amasad Updated all code to use `bluebird`. `q` is completely dropped. (even removed from `package.json`) Passed all tests.

**Comment by amasad** [comment]
I already updated that internally :) I should've mentioned that

**Comment by amasad** [comment]
I just need to sync from our internal repo. Our tools are not in a great place now, but we can't merge pull requests directly from github we have to go through internal review process

**Comment by pilwon** [comment]
@amasad Understood. FB's merge policy between the internal code and `react-native` was not clear to me even after reading [this section](https://github.com/facebook/react-native/blob/2bb10cdaf956a2d88e4eb9b62572165633094143/CONTRIBUTING.md#pull-requests).

Will FB always update its internal code first then bring the changes to `react-native` next? This means PRs cannot be directly merged to `react-native` that is the only repo external contributors have access to. I can see this merge strategy has its own benefits such as getting all contributed code quality ensured by internal review process and maintain code consistency. If this is the case, please add to `CONTRIBUTING.md` so all contributors who sends PR clearly understand the merge process. Thanks-

**Comment by vjeux** [comment]
@pilwon we want to eventually be github first but are not ready yet. For the time being, we need to ensure that every pull request passes our internal test suites and don't break our internal apps. Good idea about updating the contributing.md file

**Comment by sahrens** [comment]
Merged internally and synced.

**Pull request closed without merging**
