### PR TITLE
Resolve deprecations in android template

### PR DESCRIPTION
**Pull request by AlexanderEggers**
## Summary:

This PR resolves different deprecation warnings that are part of the current android template.

## Changelog:

[ANDROID] [FIXED] - Resolve deprecation warnings in the android template

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
@AlexanderEggers could you do the same on the 0.73 release branch?

**Comment by AlexanderEggers** [comment]
@cortinico Yep sure, no problem. Until when do you need the changes?

**Comment by cortinico** [comment]
@AlexanderEggers can I ask you to rebase and fix the conflicts?

**Comment by AlexanderEggers** [comment]
@cortinico I merged the latest main into this branch.

**Pull request closed without merging**
