### PR TITLE
Remove var in Libraries/Utilities/buildStyleInterpolator.js

### PR DESCRIPTION
**Pull request by mottox2**
Replaces the keywords var with const in Libraries/Utilities/buildStyleInterpolator.js

Test Plan:
----------
- [x] Check npm run flow
- [x] Check npm run flow-check-ios
- [x] Check npm run flow-check-android

Release Notes:
--------------
[GENERAL] [ENHANCEMENT] [Libraries/Utilities/buildStyleInterpolator.js] - remove var

### CODE REVIEW

**Comment by TheSavior** [comment]
Thanks for contributing!

**Comment by TheSavior** [comment]
@mottox2 @ggtmtmgg @yushimatenjin I'm excited to see all of you first time contributors helping to fix our linter errors! Out of curiosity, what led all of you to submit these PRs? Is there some post somewhere pointing people here? How can we help encourage more first time contributors?

**Comment by ggtmtmgg** [comment]
@TheSavior 

We're making a Japanese community named React Native OSS.
Our aim is to contribute to facebook/react-native by pair programming.
@Tnarita0000 found this issues and taught us how to first contribute.

However, "Good first issue" tag is not maintained well, so we're struggling with finding good issues for first contributers.
Could you join our official Slack team and help find good issues? Any IM is fine, but it would be nice to know how we can contact you.

**Comment by turnrye** [comment]
@ggtmtmgg that's great news! As you run across issues with an unfitting "Good first issue" label, will you please comment and let us know? I'm sure future devs will be thankful :)

I'd suggest staying with that label for now; one issue that's open and well defined right now is #22100.

**Comment by ggtmtmgg** [comment]
> As you run across issues with an unfitting "Good first issue" label, will you please comment and let us know? 

Sure, We'll leave this kind of comments from now.

#22100 looks good first issue, We'll take some files. Thank you.

**Pull request closed without merging**
