### PR TITLE
Fix RCTScrollView don't response user touch event when select the b…

### PR DESCRIPTION
**Pull request by wenpkpk**
the scrollview don't response user press(touch) event, when user draging the scrollview and press the bottom tab button rapidly.

`
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  UITabBarController *tabVC = [[UITabBarController alloc] init];
  UIViewController *a = [[UIViewController alloc] init];
  a.title = @"----------";
  a.view.backgroundColor = [UIColor whiteColor];
  UIViewController *b = [[UIViewController alloc] init];
  b.title = @"++++++++++";
  tabVC.viewControllers = @[a, b];
  
  NSURL *jsCodeLocation;
  
  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */
  
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/Examples/2048/Game2048.bundle?platform=ios&dev=true"];
  
  /**
   * OPTION 2
   * Load from pre-bundled file on disk. To re-generate the static bundle, `cd`
   * to your Xcode project folder in the terminal, and run
   *
   * $ curl 'http://localhost:8081/Examples/2048/Game2048.bundle?platform=ios' -o main.jsbundle
   *
   * then add the `main.jsbundle` file to your project and uncomment this line:
   */
  
  //  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
//  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Game2048"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.frame = a.view.bounds;
  [a.view addSubview:rootView];
  
  UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:tabVC];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.rootViewController = nav;
  [self.window makeKeyAndVisible];
  return YES;
}
`

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @rigdern to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by wenpkpk** [comment]
video bellow.
[Uploading rn-scrollview-bug2.mov.zip…]()

**Comment by wenpkpk** [comment]
demo video file upload failed, if necessary please provide your mail address. thx~

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by wenpkpk** [comment]
@facebook-github-bot

**Comment by wenpkpk** [comment]
@sahrens @nicklockwood

**Comment by ide** [comment]
Can you please clean up this pull request? it's hard to tell what is going on here.

**Comment by wenpkpk** [comment]
close this pr.

See：[new PR](https://github.com/facebook/react-native/pull/8838)

**Pull request closed without merging**
