### PR TITLE
[iOS] "subject" field for Share

### PR DESCRIPTION
**Pull request by gusgard**
Add field `subject` to `Options` when Share.
Check https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/ActionSheetIOS/ActionSheetIOS.js#L52

iOS:
The field `subject` is obtained from `Options`
https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L159

# Test Plan

**iOS:**
Tested the following components `ActionSheetIOS` and `Share` using RNTester

**Android**
Don't use the key `subject`
Check https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/share/ShareModule.java#L52

### CODE REVIEW

**Comment by gusgard** [comment]
@facebook-github-bot

**Comment by gusgard** [comment]
@facebook-github-bot

**Comment by hramos** [comment]
This looks like more than a docs change, so the test plan needs updating.

**Comment by gusgard** [comment]
@hramos updated

**Comment by janicduplessis** [comment]
Thanks for the PR!

@hramos It looks like subject was already implemented natively but not documented / flow typed so it's _kind of_ a doc change haha.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by gusgard** [comment]
@janicduplessis could you ship it again? I'm guessing the branch wasn't merged to master for a while.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
