### PR TITLE
Docs update - Direct user to changelog for manual steps of version

### PR DESCRIPTION
**Pull request by GantMan**
For some reason the last PR targeted 0.30-stable as pointed out by @charpeni - here:  https://github.com/facebook/react-native/pull/9010

Fixed here in a second PR, due to the fact that initial PR would not allow a change.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @odino and @JoelMarcey to be potential reviewers.

**Comment by JoelMarcey** [comment]
cc @foghina @frantic

**Comment by facebook-github-bot-1** [comment]
@GantMan updated the pull request.

**Comment by satya164** [comment]
We already have the steps in the changelog. Can we just point to the chagelong instead of copying the instructions here?

**Comment by satya164** [comment]
Also totally forgot this file existed. We've not updated this in a while and we list breaking changes in the changelog. Not sure if it's worth adding migration instructions for individual releases in this file, since we usually write the instructions in the changelog.

We could just have a link pointing to the releases page telling check the release to for any manual upgrading steps.

**Comment by GantMan** [comment]
I forgot how I came across it.  

Would you like me to rewrite it to say something like, "Some upgrades require manual steps, e.g. 0.13 to 0.14, or 0.28 to 0.29.  Be sure to check the changelog when upgrading so that you can identify any manual changes your particular project may require." Then link to changelog?

**Comment by satya164** [comment]
@GantMan Sounds good.

**Comment by facebook-github-bot-4** [comment]
@GantMan updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@GantMan updated the pull request.

**Comment by GantMan** [comment]
@satya164  -  Updated the section, also updated PR title, and merged master into PR.

Let me know if you need anything from me.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1587824414851558/int_phab) to review internal test results.

**Pull request closed without merging**
