### PR TITLE
Use jsx files in the dependencies and the watchers

### PR DESCRIPTION
**Pull request by pickhardt**
See also https://github.com/facebook/react-native/issues/2303

### CODE REVIEW

**Comment by jaygarcia** [comment]
Excellent!

**Comment by amasad** [comment]
Looks good! We're currently working in the process of moving the packager to it's own github repo and we'll be able to accept contributions like this much faster (we can just use the Github merge button). I'm hoping we can release it some time this week, and I'll ping so we can move the PR there.

**Comment by MadRabbit** [comment]
please merge this!

**Comment by ide** [comment]
@pickhardt This looks good to me. Can you please rebase?

**Comment by pickhardt** [comment]
Isn't the packer going to move to a new repo, so this pull request doesn't matter here any longer?

**Comment by MadRabbit** [comment]
i guess when they move package into another repo they can move it along with the patch

**Comment by MadRabbit** [comment]
@pickhardt  i think this patch doesn't work anymore. i tried to reproduce it locally by patching files in `node_modules` manually, and it keeps throwing errors like that

```
Unable to resolve module ./components/search_bar from /[filtered]/src/app.ios.js
```

works perfectly with plain `.js` files. is there any way i can debug it?

**Comment by pickhardt** [comment]
Yeah it says the branch has conflicts that must be resolved. I'm not sure what they are - the file changed looks pretty straightforward to me. Honestly it's not that important to me any longer, I switched to using .js files. The main reason I wanted .jsx had to do with my text editor's code styling, but that isn't a problem anymore.

**Comment by hojberg** [comment]
Would love to see this rebased and merged!

**Comment by natorojr** [comment]
This would be awesome! Please merge.

**Comment by jonaswindey** [comment]
Still waiting for this merge.

**Comment by brentvatne** [comment]
@pickhardt - looks like the new home for this is here: https://github.com/exponentjs/react-native/blob/8d8da11010e478bb08c2298f9512965f1ee21037/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js#L57

@jonaswindey @natorojr @hojberg @pickhardt - if any of you are interested in this please submit a new PR and I can merge this quickly now that I have ability to land any type of PR :)

**Pull request closed without merging**
