### PR TITLE
[Android] Fix non selectable Text in FlatList

### PR DESCRIPTION
**Pull request by fabriziobertoglio1987**
## Summary

This issue fixes https://github.com/facebook/react-native/issues/26264 fixes https://github.com/facebook/react-native/issues/27107
Text is not selectable inside a FlatList on Android. The solution is to invalidate the ReactTextView after a change of the selectable prop. If the view is visible, onDraw(android.graphics.Canvas) will be called at some point in the future and make the Text selectable.

## Changelog

[Android] [Fixed] - Fix non selectable Text in FlatList

## Test Plan

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

The issue was demonstrated in the following [snack](https://snack.expo.io/@fabrizio.bertoglio/selectable-bug-in-flatlist) (more info in issue https://github.com/facebook/react-native/issues/26264). 

The solution is:

1) Calling `invalidate()` from [setSelectableText][1] after changing the `selectable` prop and `mSelectableText` value. [`invalidate()`](https://developer.android.com/reference/android/view/View#invalidate()) triggers the `onDraw` callback.

[1]: https://github.com/fabriziobertoglio1987/react-native/blob/8027524947cafd5cbdc492e4ef9c92b346fe23fc/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextView.java#L427-L430

2) calling `setTextIsSelectable(mSelectableText);` from the [`onDraw`][2] callback

[2]: https://github.com/fabriziobertoglio1987/react-native/blob/8027524947cafd5cbdc492e4ef9c92b346fe23fc/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextView.java#L456-L460

The example below is availabe in RNTester FlatList example. Two options (`onPressDisabled` and `textSelectable`) have been added to test the functionality inside a FlatList. 

<p align="center">

</p>

</p>
</details>

### CODE REVIEW

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/commit/372d001a5d5e24b68d194e01c356d973642fac86

**Comment by ShikaSD** [comment]
Hey, just noticed this PR in the internal review queue :)

Not sure doing this in each onDraw here is a correct solution (for performance and otherwise).
If the underlying reason for this change was to delay the update, doing it in `postOnAnimation()/post()` (whatever works) is more correct approach. If it was caused by some other issues (e.g. cleared on view removal), maybe we can use `onAttachedToWindow` or some other callbacks to re-apply the value?
E.g.:

```
public void setSelectableText(boolean value) {
  postOnAnimation(new Runnable() {
    @Override
    public void run() {
      setTextSelectable(value)    
    }
  });
}
```

**Comment by fabriziobertoglio1987** [comment]
after some investigation I notice that

The change was already applied with commit https://github.com/facebook/react-native/commit/89340f1620295c7ca6baecccc6b6d3befdf45cdb and then reverted later with commit https://github.com/facebook/react-native/commit/862136a398decff8ad5d4509ca51bd6b893ff851

https://github.com/facebook/react-native/commits/main?after=363a8fb08cef8326bba53cd3ea250bde02444126+34&branch=main&path%5B%5D=ReactAndroid&path%5B%5D=src&path%5B%5D=main&path%5B%5D=java&path%5B%5D=com&path%5B%5D=facebook&path%5B%5D=react&path%5B%5D=views&path%5B%5D=text&path%5B%5D=ReactTextView.java

**Comment by cjhines** [comment]
Is this broken again on 0.68?

**Comment by Zmwang622** [comment]
I'm on version 0.64.3, and Text still isn't selectable in a FlatList. Any ideas? @fabriziobertoglio1987 

This is my code:

```tsx
const MyClass = ({data}) => {
  const renderItem = useCallback(
      (item: key) => {
        return (
          <View>
              <Text selectable> {key} </Text>
              <Text selectable> {data[key]} </Text>
          </View>
        )
      }
   ,  [data])
  return <FlatList data={Object.keys(data)} renderItem={renderItem}
} 
```

**Comment by fabriziobertoglio1987** [comment]
@Zmwang622 I think it is part of 0.67 https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0670

**Comment by Zmwang622** [comment]
@fabriziobertoglio1987 Ah okay got it, thanks for the quick response!

**Comment by markedwards** [comment]
I'm using react-native 0.72.4 and still need `removeClippedSubviews={false}` to enable text selection on Android.

**Comment by Code-Victor** [comment]
Please, this issue isn't fixed yet. 
I just spent over an hour trying to fix this issue, thank God I found this.
https://github.com/facebook/react-native/issues/26264

**Comment by LA-Johan** [comment]
Reopened the issue here: https://github.com/facebook/react-native/issues/46999

**Pull request closed without merging**
