### PR TITLE
[bot_testing] Testing a new bot - code that does not compile

### PR DESCRIPTION
**Pull request by mkonicek**
Please ignore this pull request. Just testing a new bot.

### CODE REVIEW

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
c

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
