### PR TITLE
Updated Embed Into Existing Android App Readme

### PR DESCRIPTION
**Pull request by thorbenprimke**
Motivation: Fix the documentation so that others don't stumble. 

**Test plan**: Integrating RN into an existing Android app doesn't cause the `ConnectivityManagerCompat` exception anymore.

--- 

The instructions where still pointing at maven central. This updates the dependency and provides instructions on how to reference the local maven folder in `node_modules`.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @foghina and @sebmarkbage to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
@thorbenprimke updated the pull request.

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by thorbenprimke** [comment]
Related to issue #6152

**Comment by facebook-github-bot-0** [comment]
@thorbenprimke updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@thorbenprimke updated the pull request.

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1047628312019318/int_phab) to review.

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1047628312019318/int_phab) to review.

**Pull request closed without merging**
