### PR TITLE
[Hotfix] Footer background issues in the blog index.

### LINKED ISSUE #10091: [Website] Blog CSS displaying black background on Read More buttons
Visit http://facebook.github.io/react-native/blog/ to see the issue in action.

This was likely introduced in #10075 by yours truly.

### PR DESCRIPTION
**Pull request by hramos**
Fixes #10091.

Some now unused CSS is removed here as well.

### CODE REVIEW

**Comment by hramos** [comment]
@facebook-github-bot shipit-ninja

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @Andreyco and @JoelMarcey to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Normally, hramos, someone else should review and ship your pull request. However, we will trust that you know what you are doing. Shipping!

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3919399).

**Pull request closed without merging**
