### PR TITLE
[Packager] Adds support for ES6 export syntax to the packager's DependencyResolver.

### PR DESCRIPTION
**Pull request by skevy**
This PR includes:
- A regex that allows for the `export` syntax.
- Updated tests.

### CODE REVIEW

**Comment by skevy** [comment]
Woah @facebook-github-bot you're awesome.

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@vjeux do you want me to fix the failing test?

**Comment by vjeux** [comment]
@skevy yes!

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
Ugh. I'm sorry for the trouble here. Looking at the travis logs, I didn't introduce this test failure.

I can try to fix either in this PR or in another. Up to you.

**Comment by javache** [comment]
The test fix is landing internally, it will be pushed soon.

**Comment by skevy** [comment]
Great. Thanks @javache

**Pull request closed without merging**
