### PR TITLE
Fix check-for-reproducer action not adding Missing Repro comment

### PR DESCRIPTION
**Pull request by kacperkapusciak**
## Summary:

This PR fixes a bug where GitHub Actions bot didn't add a comment when "Needs: Repro" label was present in an issue. 

When a maintainer adds the label manually the bot comments with "Missing Reproductible Example" as normally.

It seems like the problem occurred because of a difference in a sandbox repository and the proper facebook/react-native repo environment.

My sandbox that I used to test https://github.com/facebook/react-native/pull/38338 had an "bot" account with Personal Access Token setup to reply to issues. Turns out that bots using PAT have more permissions and can trigger one action from the other.

**The solution is to send the comment directly from the `checkForReproducer` action.** This won't collide with other actions but sadly will duplicate the sending logic into two actions.

This PR also makes the bot respect when a maintainer removes and adds a label by hand and won't alter the maintainer decision.

Related to ☂️ https://github.com/facebook/react-native/issues/35591

## Changelog:

[INTERNAL] [FIXED] - Fix check-for-reproducer action not adding Missing Repro comment

### When issue is added

1. Bot adds comment and "Needs: Repro" label when no reproducer is present in the issue body
image

2. Bot adds comment and "Needs: Repro" label when a repository not connected to the user's name was submitted

image

3. Bot doesn't trigger when Snack is present in issue body

image

4. Bot doesn't trigger when Github Repo under the user's name is present in the issue body

image

### When issue body is edited

1. Bot removes the comment and "Needs: Repro" label when user edits the issue and adds a link to snack

image

2. Bot removes the comment and "Needs: Repro" label when user edits the issue and adds a GitHub repo under user's name

image

2. Bot triggers when user removes the reproduction from issue body

image

### When comment is added

1. Bot removes the comment and the Needs Repro label when user submits a repo under their name
image

2. Bot removes the comment and the Needs Repro label when any user submits a snack 
image

3. Bot removes the comment and the Needs repro label when other user submits a repo under their name

image

### When maintainer changes the label

1. When maintainer changes the label it turns off the action, needs repro bot won't interfere with the issue anymore

image

### CODE REVIEW

**Comment by kacperkapusciak** [comment]
> If having a bot with a PAT can solve this, I'll gladly set up one for @react-native-bot and add the token to the setup

I'm afraid of a case where there would an infinite loop somewhere I haven't tested yet (or 20 max invocations as GitHub docs says) so maybe it's better to have it that way

**Comment by cortinico** [comment]
> so maybe it's better to have it that way

What do you mean with "that way" here?

**Comment by kacperkapusciak** [comment]
@cortinico sorry, I meant without the PAT so loops in GH action invocation wouldn't be possible. I think it's safer

**Comment by kacperkapusciak** [comment]
@cortinico I coded it so it when a non-author (a maintainer) alters the "Needs: Repro" label it turns off the action completely

Q: Do you think it should attempt to remove the "Missing Repro" comment when a maintainer removes the label before it turns off?

image

**Comment by cortinico** [comment]
> Q: Do you think it should attempt to remove the "Missing Repro" comment when a maintainer removes the label before it turns off?

Not necessarily. Let's keep it as it is for now, and we can refine it afterwards

**Pull request closed without merging**
