### PR TITLE
Flex gap

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
Implements rowGap and columnGap. Creating a draft PR for testing. Will update this section soon! Feedbacks are welcome.

## Approach
- This PR adds React native binding for this [Yoga PR](https://github.com/facebook/yoga/pull/1116)

## To test the example
- Run rn-tester as per the instructions in readme.md. I've modified RNTesterAppShared.js with flex gap example. 

https://user-images.githubusercontent.com/23293248/146173072-bce93401-cd37-413a-bd3e-40efda38a59a.mov

### CODE REVIEW

**Comment by satya164** [comment]
Would also be cool to support [`gap` property](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) which is a shorthand for both `row-gap` and `column-gap`

**Comment by intergalacticspacehighway** [comment]
Added gap property 🎉

**Comment by necolas** [comment]
@TheSavior this is a patch that implements one of the layout tasks on the convergence roadmap 🥳

**Comment by axeldelafosse** [comment]
Hey Eli and Nicolas! Can you tell us more about the convergence roadmap please? Thanks 🙏

**Comment by necolas** [comment]
yoga and browser flexbox layout are slightly different and we'd like yoga to better match the flexbox spec

**Comment by axeldelafosse** [comment]
OK cool! Feel free to share your plans with the community, I'm sure we can help

**Comment by intergalacticspacehighway** [comment]
Updated gap approach with @jacobp100's [implementation](https://github.com/facebook/yoga/pull/1116). Margin based implementation felt hacky and it also used `owner_` property directly as [discussed here](https://github.com/facebook/yoga/issues/812#issuecomment-997906954). Thanks to @jacobp100 for pointing it out. Once the Yoga PR gets merged, we can move this to ready for review. 🥳

**Comment by SpeedyCraftah** [comment]
Any updates? This is a highly demanded and killer feature in my opinion which should be expedited

**Comment by nandorojo** [comment]
Does anyone have a patch for `react-native` + `yoga` for using flex gap?

**Comment by intergalacticspacehighway** [comment]
@nandorojo this is the [new PR.](https://github.com/facebook/react-native/pull/34360) will close this one.

**Pull request closed without merging**
