### PR TITLE
[Codegen] Extract the switch(configType) block from the buildSchema function into a new function in the parsers/utils.js file

### PR DESCRIPTION
**Pull request by MaeIg**
## Summary

This PR aims to extract  the switch(configType) block from the buildSchema function into a separate function in a shared file between typescript and flow. It is a task of #34872:
> This task is more advanced than the others. Extract the switch(configType) block ([Flow](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/index.js#L82-L119), [TypeScript](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/typescript/index.js#L92-L129)) from the buildSchema function into a new function in the parsers/utils.js file and use it in the two functions. Note that the new function must accept some callbacks to wrapModule/ComponentSchema and to buildModule/ComponentSchema.

## Changelog

[Internal] [Changed] - Extract the switch(configType) block from the buildSchema function into a new function in the parsers/utils.js file

## Test Plan

yarn flow:
image

yarn lint:
image

yarn jest react-native-codegen:
image

I added new tests:
image

### CODE REVIEW

**Comment by MaeIg** [comment]
Hi @cipolleschi,

As requested in the task, I put `buildComponentSchema`, `wrapComponentSchema` and `buildModuleSchema` as parameters of the new function. But, these 3 functions are duplicated in flow and typescript folder. For me, they are really easy to extract!

I think we should consider extracting them into `parsers/parsers-commons.js` as done previously (2 years ago) for wrapModuleSchema.

What do you think about it? Should I propose these task in the umbrella issue?

**Review by cipolleschi — APPROVED** [review]
Seems very good to me and very thanks for the tests also!

Your proposal on those extra refactoring is pretty good and, eventually, we will do that and we will add them to the umbrella issue.
The `wrapModuleSchema` has already been refactored. The `buildModuleSchema` is pretty big and, IIRC, there are other PR that are working on parts of the function. I'd rather to focus on merging all the open PRs, now, to help us in figuring out what's left to do!

I hope to add some more tasks later this week. :+1:

**Comment by cipolleschi** [comment]
@MaeIg could you rebase this please? :pray:

**Comment by MaeIg** [comment]
> @MaeIg could you rebase this please? 🙏

Done! 😃

**Review by cortinico — APPROVED** [review]

**Pull request closed without merging**
