### PR TITLE
[WIP] BUCK for AndroidX

### PR DESCRIPTION
**Pull request by dulmandakh**
This is *hypothetical* BUCK for AndroidX's **appcompat** package that mimics Gradle dependency tree, and to use as sample for https://github.com/facebook/react-native/issues/23112.

Buck command to fetch defined targets
``` bash
buck fetch ReactAndroid/src/main/third-party/android/androidx:appcompat
```

### CODE REVIEW

**Comment by dulmandakh** [comment]
we can use either exported_deps or provided_deps, and I don't have opinion about the choice.

**Comment by cpojer** [comment]
@dulmandakh what's the status of this PR?

**Comment by dulmandakh** [comment]
Waiting for David to land AndroidX at FB.

**Comment by dulmandakh** [comment]
@mdvacca I looked into https://github.com/facebook/react-native/pull/23604, and CI failed because *is_androidx* is not supported in BUCK. So I assume that there is custom implementation that would look like my changes in *tools/build_defs/oss/rn_defs.bzl*. And you can see Android CI is still green, even I have *is_androidx* in switchview.

I found that AndroidX is a lot different than Android Support Library, and requires a lot of work than Android Support Library version bump. Therefore, I would need implementation details of is_androidx in rn_android_library and BUCK for AndroidX used at FB, so I can mimic it in OSS and have smoother AndroidX migration.

**Comment by dulmandakh** [comment]
@mdvacca once we land AndroidX Buck and custom *is_androidx* implementation, you can land AndroidX changed without breaking OSS CI.

**Comment by mdvacca** [comment]
Landed as part of another PR

**Pull request closed without merging**
