### PR TITLE
[NavigationExperimental] Support custom card style interpolators

### PR DESCRIPTION
**Pull request by dingbat**
Transition animations are not very customizable right now with NavigationExperimental, unless I am missing something big. This PR allows NavigationCardStack to receive the `horizontalCardStyleInterpolator` and `verticalCardStyleInterpolator` props to override the default interpolators.

See the gif, transition animation changes from the default one (with scale) to a custom one (without scale) when passing in a custom interpolator. (The custom interpolator is an exact copy of the one in `NavigationCardStackStyleInterpolator.forHorizontal`, minus the scale transform.)

cmz0gagoec

Let me know if there's a robust way to test, but I couldn't find anything.

**To address**
The new `canUseNativeDriver` function on NavigationCardStackStyleInterpolator, which returns `true`, is dependent on the interpolator, so custom interpolators may need to falsify this. Didn't include it on the first pass since I wasn't sure, but how does moving it out of NavigationCardStackStyleInterpolator and changing it to a boolean property on NavigationCardStack which defaults to `true` sound? (The `isVertical` param passed to it won't be relevant anymore because the user of NavigationCardStack knows the direction set.)

### CODE REVIEW

**Comment by dingbat** [comment]
Actually now I'm realizing, instead of having separate properties for horizontal and vertical, we could just have a single `cardStyleInterpolator` property (again, the user of the class knows the direction being set and can provide a different interpolator accordingly). By default, when it's not provided, we use NavigationCardStackStyleInterpolator's `forHorizontal` or `forVertical` depending on direction. Less redundancies that way and seems DRYer.

**Comment by Exilz** [comment]
I ended up making the same changes to try out something. I dropped these changes but I'd love to see them merged. +1 !

**Comment by fabriziomoscon** [comment]
I would love to see this merged.
I am using a gradient View background and the transition scale looks very awkward, because it leaves 5% of empty gap at the top and at the bottom.
Please consider it for merging

**Comment by ericvicenti** [comment]
This seems like a good way to accomplish this. Thanks for the contribution!

**Pull request closed without merging**
