### PR TITLE
Incorrect variable name

### PR DESCRIPTION
**Pull request by wilsonpage**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

(You can skip this if you're fixing a typo or adding an app to the Showcase.)

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @bestander and @dmmiller to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by dmmiller** [comment]
I think is actually 'timeStamp' on Android and 'timestamp' on iOS. :(

**Comment by christopherdro** [comment]
@dmmiller Is right.
There was a PR submitted some time ago that never landed because it needed revisions.
https://github.com/facebook/react-native/issues/4627

Maybe this is something worth revisiting?

**Comment by facebook-github-bot-5** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @bestander as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by mkonicek** [comment]
Looks like the web spec uses timeStamp:
https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp
http://www.w3.org/TR/DOM-Level-3-Events/

We should change the iOS key to timeStamp instead, I'll try to find some time to do that. In the meantime using `timeStamp` in the docs seems OK.

@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
I cannot do that @mkonicek, because @wilsonpage does not have an active CLA on file.

**Comment by lacker** [comment]
I'll move this to https://github.com/facebook/react-native/pull/7553 to deal with the typo-but-no-cla thing :P

**Pull request closed without merging**
