### PR TITLE
Implement RefreshControl for WebView

### PR DESCRIPTION
**Pull request by enyce12**
This pull requests makes it possible to use RefreshControl together with a WebView.

https://github.com/facebook/react-native/issues/7870

### CODE REVIEW

**Comment by jacobp100** [comment]
Is it not possible to access the scrollview for the `UIWebView`, and just implement something similar to `RCTScrollView`?

**Comment by enyce12** [comment]
Directly accessing the ScrollView leads to the following error when performing the refresh action:
`Exception thrown while executing UI block: [RCTView contentOffset]: unrecognized selector sent to instance 0x7f8ebbc06b40`

**Comment by jacobp100** [comment]
Were you trying that in Objective C, or in the JS?

**Comment by enyce12** [comment]
In the JS part. If you meant to make changes in Objective C I'm not sure were to look at, though.

**Comment by jacobp100** [comment]
I’m slightly hesitant for the iOS implementation, since it’s putting the web view, which is a scroll view, inside another scroll view. I don’t know much about Android, but that may or may not be the same.

However, it might be worth seeing if we can ping someone from the Facebook team for this one. AFAICT, this isn’t native or common behaviour for either platform, so it would be to know if this is a change that will get approval before looking at the implementation.

Failing that, it could be done as a module, that just uses the output of `WebView`, and puts its children in a scrollview along with the refresh control.

**Comment by lacker** [comment]
To me, this seems like an unusual feature to put directly into WebView. For one, adding a pull to refresh on a webview seems unusual. For two, why can't this be implemented without modifying WebView & without modifying the React Native core, in a custom component for example?

**Comment by ide** [comment]
> For one, adding a pull to refresh on a webview seems unusual. 

I could see people wanting to do this in contexts where the WebView is a way to write a screen with HTML and you want it to behave natively otherwise. Instagram used to (and might still) use a WebView for the notifications screen, for example.

> why can't this be implemented without modifying WebView & without modifying the React Native core, in a custom component for example?

With regard to the current implementation in this PR I'm inclined to agree that this could be done in user space. However I think this PR might be written better by using a different approach, at least on iOS, specifically by adding the UIRefreshControl directly to webView.scrollView instead of nesting scroll views in scroll views. That would require a core change to RCTWebView.m.

Not sure about the Android side of the story but I think we should avoid nesting scroll views when possible.

**Comment by lacker** [comment]
Gotcha. Yeah I think there are two things going on - one is that if you're doing the approach in this PR, you might as well do it in user space. The other thing is that doing it in user space may not be ideal. I don't have a strong opinion on that, but either way the direction we want to go is not the one in this pull request, so I'm going to close it.

**Pull request closed without merging**
