### PR TITLE
[React] Use tilde for React peer dep

### PR DESCRIPTION
**Pull request by ide**
Paul suggested that we use the tilde to pull in only bug fixes to React and that React might not follow semver for internalish APIs that RN uses, so it's safer to use the tilde. When RNRenderer is split out from React we can go back to the caret.

### CODE REVIEW

**Comment by ide** [comment]
cc @zpao @bestander

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @cpojer and @davidaurelio to be potential reviewers.

**Comment by bestander** [comment]
6aeff966f6e50a9d56567ecd1ad195b8

**Comment by bestander** [comment]
Node modules... too bad we can't put comments in package.json because we tend to accumulate some knowledge around this fragile structure.
So, ~ seems reasonable to reduce the risks of breaking changes.

Could you bump devDependency too?

**Comment by facebook-github-bot-8** [comment]
@ide updated the pull request.

**Comment by davidaurelio** [comment]
It’s worth noting that this does not solve the problem with `react-native init`: it calls `npm install --save react-native`. I’m just running a couple of experiments.

**Comment by bestander** [comment]
`init` now does `--exact-save`, https://github.com/facebook/react-native/pull/7879.
Anyone objects?

**Comment by davidaurelio** [comment]
@bestander we don’t use `--save-exact` [here](https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L216) and [here](https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L232).

When running `react-native init <project-name>`:

- using npm 3 (shipping with node 5), react won’t be installed *at all,* leaving that responsibility to the developer.
- using npm 2, we *still* end up with a dependency of `"react": "^15.0.2"`

**Comment by bestander** [comment]
moving discussion to the relevant PR

**Comment by davidaurelio** [comment]
For the record: #7879

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @cpojer as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by bestander** [comment]
Ok, this is now fixed

**Pull request closed without merging**
