### PR TITLE
Update type check for NavigationCardStack

### PR DESCRIPTION
**Pull request by lgan1989**
The typecheck inside of NavigationCard is PropTypes.any while in NavigationCardStack it is  View.propTypes.style. 

let's make them consistent to avoid unnecessary warnings. (e.g. trying to pass a animationStyle as cardStyle)

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @hedgerwang and @jmurzy to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
> The typecheck inside of NavigationCard is PropTypes.any while in NavigationCardStack it is View.propTypes.style.

It seems like `View.propTypes.style` is more accurate? Why not use it in both places? `PropTypes.any` is an equivalent of no typing.

> let's make them consistent to avoid unnecessary warnings. (e.g. trying to pass a animationStyle as cardStyle)

What is animationStyle and why is not a `View.propTypes.style`?

**Comment by lgan1989** [comment]
@mkonicek the thing is NavigationCard's render() it's using a Animated.View the style property could be as following:

`  
<Animated.View
   style={{opacity: this.state.fadeAnim}}>
  {this.props.children}
</Animated.View>`

while  
`
this.state = {
  fadeAnim: new Animated.Value(0),
};
`

**Comment by ericvicenti** [comment]
Ah, I see the problem. Can't we use `Animated.View.propTypes.style`?

**Comment by lgan1989** [comment]
@ericvicenti  this could work, although after I changed it to Animated.View.propTypes.style it exposed another issue(warning):

since there is a property in NavigationPropTypes named "position", and it's conflicted with the ViewStylePropTypes check inside of AnimatedImplementation.js@1485.

Although I think this false warning is not critical and it's because the checking itself in AnimatedImplementation is not so precise.

**Comment by satya164** [comment]
> since there is a property in NavigationPropTypes named "position", and it's conflicted with the ViewStylePropTypes check inside of AnimatedImplementation.js@1485.

I have had this issue with one of my modules and I think `PropTypes.any` is our best best for now.

**Comment by facebook-github-bot-4** [comment]
@lgan1989 updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9808/files/ac782a8e5b79e7fae34b4ed74afedf0aa94a73b2..cc3e162f433b1bbc5b6380983297c2343f60c0f4)

**Comment by facebook-github-bot-1** [comment]
@lgan1989 updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9808/files/cc3e162f433b1bbc5b6380983297c2343f60c0f4..2ef8610ddb7327f795316f10d28d72c042d62b75)

**Pull request closed without merging**
