### PR TITLE
[Headers] Add an umbrella header for the library

### PR DESCRIPTION
**Pull request by ide**
The umbrella header allows projects that link React Native using CocoaPods to import it in standard fashion: `#import <React/React.h>`. Currently all of the headers are exported so that external projects can experiment.

### CODE REVIEW

**Comment by sahrens** [comment]
cc @nicklockwood

**Comment by sahrens** [comment]
cc @tadeuzagallo too.

**Comment by ide** [comment]
This has been kind of hacked together as React Native has been refactored, so I think the concept stands but each library should have its own umbrella header, and then maybe have a master umbrella header that imports the core + ubiquitous libraries (text, image support but not geolocation, vibration, etc).

**Comment by tadeuzagallo** [comment]
Sounds good. Everything that is non-optional is exposed in this header, and one more header per subspec.

**Pull request closed without merging**
