### PR TITLE
Fix symlink resolving for examples in the repo

### PR DESCRIPTION
**Pull request by Kureev**
Motivation:
Few days ago @gaearon [filed an issue](https://github.com/facebook/react-native/issues/12406) that examples in the react-native repo doesn't work after the [recent changes in local-cli](https://github.com/facebook/react-native/commit/bce6ece5f6927bcc06252dc2368840aa0c6fa30e). This PR fixes reported bug.

**Test plan (required)**
- No UI changes
- [x] Run UIExplorer from XCode (no package.json in the folder) and check if packager/application runs correctly

cc @davidaurelio @satya164 @grabbou

### CODE REVIEW

**Comment by Swaagie** [comment]
A similar fix, among others, were posted 2 days ago, https://github.com/facebook/react-native/pull/12400. I like this cleaner approach to config btw, the hardcoded `NODE_MODULES` was also resolving to a wrong directory (yet working) directory when RN itself is symlinked

**Comment by Kureev** [comment]
Hi @Swaagie! Thanks for your PR, it looks really great. I think we can find a way how we can combine our PRs and ship both. I love the work you did with scoped modules, that's just great! Also, you caught a bug with `projectRoots`. I think it's a very valuable contribution to the project.

Maybe we can wait someone to review our PRs and find how we can merge them. I think in either case the merge is not going to be that big.

**Comment by Swaagie** [comment]
Sounds like a plan.

**Comment by gaearon** [comment]
Thanks for the quick fix!

**Comment by Kureev** [comment]
Rebased in a hope it'll fix CI builds

**Comment by ericvicenti** [comment]
I can not repro the issue on master. Do we still need this?

**Comment by gaearon** [comment]
By can't repro, do you mean it doesn't crawl to folders above? My issue description is specific to my computer—if you don't have a broken symlink, you won't see the same error. But the problem is it crawls parent directories in the first place.

**Comment by gaearon** [comment]
This is the key part of my report:

screen shot 2017-03-03 at 11 45 30 pm

You won't see the same error if you don't have broken symlinks in a folder above.

**Comment by Kureev** [comment]
I just double-checked the code in `master` and it still looks broken. That's how you can reproduce this issue on Mac:

- In the folder where you have react-native repo run:
  ```
  $ ln -s foo ./bar
  ```
  (here I assume that "bar" doesn't exist and symlink is broken)
- Go to `react-native/examples/UIExplorer` and open `UIExplorer.xcodeproj`
- Run

You should see something like this:
image

**Comment by Kureev** [comment]
I'd also like to explain the reason why this issue occurs: there is [the line](https://github.com/facebook/react-native/pull/12435/files#diff-60f233a846cf01cd8182804290157fdeL26) that defines a path to `node_modules` as `../../../` (because usually local-cli is located in `node_modules/react-native/local-cli` which is apparently not the case if you run a project from `examples` in RN repo: `react-native/examples/UIExplorer`). 

Let me know if you need any additional information to review this PR. Also, feel free to ping me on Slack.

**Comment by ericvicenti** [comment]
Thanks @Kureev, this is a well documented fix. My apologies for glossing over the important detail. I'll land it now.

**Pull request closed without merging**
