### PR TITLE
Bump NDK to 25

### PR DESCRIPTION
**Pull request by szymonrybczak**
## Summary:

Bumps NDK to current LTS Release.

## Changelog:

[Android] [Changed] - Bump NDK to 25
## Test Plan:
CI Green ✅

### CODE REVIEW

**Comment by szymonrybczak** [comment]
Looks like CircleCI's machine broke on installing dependencies on iOS 🥲

**Review by cortinico — CHANGES_REQUESTED** [review]
That's sadly not sufficient :(
First I'd like to wait for this to land:
- https://github.com/facebook/react-native/pull/37019

Then we'll have to make sure all the dependencies we link against are built with NDK 25. Namely:
- FBJNI
- Hermes
- Flipper

Your change is only bumping the NDK version of the template. We'll have to take care of the NDK version of ReactAndroid as well. Would you be able to take a look at it?

**Comment by szymonrybczak** [comment]
@cortinico Yeah, so:
FBJNI -  [23.1.7779620](https://github.com/facebookincubator/fbjni/blob/a4be46cea1e2946b441bc0ba2524abafe6e4ec19/build.gradle#L42)
Hermes - Not sure, where to find it.
Flipper - [25.1.8937393](https://github.com/facebook/flipper/blob/main/build.gradle#L52)
I can create PRs bumping versions in those repositories. 
Yes, I can look at ReactAndroid, is just doing that - will be okay in `build.gradle.kts`?
```
val ndkVersion by extra(System.getenv("ANDROID_NDK_VERSION") ?: "25.2.9519653")
```

Also I think we can bump NDK version in the `docker-android`, WDYT?

**Comment by cortinico** [comment]
> FBJNI - [23.1.7779620](https://github.com/facebookincubator/fbjni/blob/a4be46cea1e2946b441bc0ba2524abafe6e4ec19/build.gradle#L42)

I'm currently working on it. Will be out with FBJNI version 0.5.0 sometime soon

> Hermes - Not sure, where to find it.

This is controlled by `ReactAndroid/hermes-engine/build.gradle` so it will be bumped with everything.

> Flipper - [25.1.8937393](https://github.com/facebook/flipper/blob/main/build.gradle?rgh-link-date=2023-06-20T14%3A20%3A31Z#L52)

That's correct as that's the version we want to use actually (see https://developer.android.com/build/releases/gradle-plugin#compatibility-8-0-0 as the default for 8.0.0).

We'll have to find which version of Flipper is the first one that bumped NDK to 25 and make sure we use it.

**Comment by cortinico** [comment]
> Also I think we can bump NDK version in the `docker-android`, WDYT?

Yup that's also needed 🙏

**Comment by szymonrybczak** [comment]
> We'll have to find which version of Flipper is the first one that bumped NDK to 25 and make sure we use it.

It was bumped in this PR https://github.com/facebook/flipper/pull/4443, and it was first released in `0.187.1`, btw. just out of curiosity why the first one?


> Yup that's also needed 🙏

PR: https://github.com/react-native-community/docker-android/pull/204

**Comment by cortinico** [comment]
> and it was first released in `0.187.1`, btw. just out of curiosity why the first one?

Because we might already have it shipped/bumped, but that's not the case as we're on `0.182.0`

**Comment by cortinico** [comment]
@szymonrybczak can we move this forward?

**Comment by cortinico** [comment]
> FBJNI - Bumped, but not released yet.
> docker-android - Bumped, but not released yet.

I will take of those two next week.

> Flipper - Not bumped in RN repository.

@szymonrybczak do you want to attempt to do this bump? It should be fairly easy (just search for a previous Flipper bump) 👍 I can support if needed

**Comment by cortinico** [comment]
Hey @szymonrybczak 
Sorry this took longer for me, but now we should be fully unblocked:

https://github.com/facebookincubator/fbjni/releases/tag/v0.5.0
https://github.com/react-native-community/docker-android/releases/tag/v10.0

Can I ask you to bump those 2 and rebase? And we should be able to import this 👍

**Pull request closed without merging**
