### PR TITLE
(eslint-config) update community eslint plugin in eslint config

### PR DESCRIPTION
**Pull request by Naturalclar**
## Summary

Updating the community eslint-plugin used in the eslint-config to the latest version.

expecting new eslint-config version to be released with this change so that it can be included in new project template for 0.63 https://github.com/react-native-community/releases/issues/186

## Changelog

[General] [Changed] - Update community eslint plugin in the eslint config

## Test Plan

yarn lint passes

### CODE REVIEW

**Comment by Naturalclar** [comment]
@matt-oakes made the change as requested :+1:

**Comment by matt-oakes** [comment]
Looks good to me! @cpojer can you put this change through?

**Comment by Naturalclar** [comment]
awesome!
@matt-oakes Could you release the new version when you get the chance? :+1:

**Comment by matt-oakes** [comment]
@Naturalclar Done!

**Pull request closed without merging**
