### PR TITLE
Adding key property to ListView rows

### PR DESCRIPTION
**Pull request by schwolf**
Doc adjustment:
It is a best practise to give dynamic children key properties, this should not be omitted here.
Also suppresses warnings like 'Each child in an array or iterator should have a unique key prop' in development environments.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
@arasmussen would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by arasmussen** [comment]
LGTM

**Comment by mkonicek** [comment]
Thanks for adding this and sorry this pull request got missed!

Unfortunately the docs have been revamped since so this doesn't apply anymore :(
http://facebook.github.io/react-native/docs/tutorial.html

**Comment by sunnylqm** [comment]
@mkonicek Can we keep both tutorials as "basic tutorial" and "advanced tutorial"? And I think we need more to fill the gaps. Now the tutorial and following docs look just like this for newbie.

**Pull request closed without merging**
