### PR TITLE
Remove find-node.sh that cause PhaseScriptExecution.

### PR DESCRIPTION
**Pull request by nitaking**
## Summary

`find-node.sh` is th couse of many build errors. (Causes PhaseScriptExecution)

- https://github.com/facebook/react-native/issues/31228
- https://github.com/facebook/react-native/issues/31354
- https://github.com/facebook/react-native/issues/31275
- https://github.com/facebook/react-native/issues/31259
- https://github.com/facebook/react-native/issues/31181
- https://github.com/facebook/react-native/issues/31249
- https://github.com/facebook/react-native/issues/31238

I think that the node path setting is not done by the library, but by the user.
If the react-native even complements the node's path setting, shouldn't it be complemented by the document?

What is the community's policy on this?
We are losing a lot of time to this meritless hacky code. This fix should be incorporated as a band-aid, even if it's not ideal.

## Changelog

[iOS] [Fixed] - Remove find-node script.

### CODE REVIEW

**Comment by gnattu** [comment]
Let me add #31260 to this.

**Comment by nitaking** [comment]
Have identified a problem with the release build in this fix.

**Comment by nitaking** [comment]
@gnattu 
Thanks.
The fix for #30781 succeeds in release build / debug build.
Can I replace this PR with this fix?

**Comment by AyoubAtba** [comment]
I'm having this problem any solutions????

**Comment by leotm** [comment]
On new M1 Mac Mini after `brew install node`, `sudo mkdir /usr/local/bin` then `sudo ln -s /opt/homebrew/bin/node /usr/local/bin/node` got Xcode building for me, I gave current PR changes a shot first with no luck.

**Comment by nitaking** [comment]
This fix seems to have fixed the problem, so I'll close this PR.

https://github.com/facebook/react-native/commit/d75683ac943205d64dd4142cca713ab2356094b8

**Comment by rogeriomq** [comment]
> On new M1 Mac Mini after `brew install node`, `sudo mkdir /usr/local/bin` then `sudo ln -s /opt/homebrew/bin/node /usr/local/bin/node` got Xcode building for me, I gave current PR changes a shot first with no luck.

I use ASDF and create link with `sudo ln -s /Users/YOUR_USER/.asdf/shims/node /usr/local/bin/node`.  Solved!

**Pull request closed without merging**
