### PR TITLE
[Cosmetic] Fix some lint warnings

### PR DESCRIPTION
**Pull request by dalinaum**
1. Use singlequote instead of doublequoe on Sample.android.js
1. Remove invariant of Sample.ios.js that is not used

### CODE REVIEW

**Comment by brentvatne** [comment]
Looks reasonable to me

**Comment by vjeux** [comment]
@facebook-github-bot import

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Woops, something went wrong with the bot

**Pull request merged**
