### PR TITLE
Migrate ReactHorizontalScrollContainerViewManager to use ViewManagerInterface

### PR DESCRIPTION
**Pull request by mdvacca**
Summary:
Migrate ReactHorizontalScrollContainerViewManager to use ViewManagerInterface

changelog: [internal] internal

Differential Revision: D65428646

### CODE REVIEW

**Comment by NickGerleman** [comment]
@mdvacca @javache this diff may cause small regression since view manager delegates miss out on view props which are part of ReactViewManager but not BaseViewManager.

**Comment by NickGerleman** [comment]
> @mdvacca @javache this diff may cause small regression since view managers with delegate defer to delegate instead of prop setter, and generated delegates miss out on view props which are part of ReactViewManager but not BaseViewManager.

FYI @cortinico

**Comment by cortinico** [comment]
> > @mdvacca @javache this diff may cause small regression since view managers with delegate defer to delegate instead of prop setter, and generated delegates miss out on view props which are part of ReactViewManager but not BaseViewManager.
> 
> FYI @cortinico

Thanks for the heads up

**Comment by mdvacca** [comment]
Let's create a task/issue as this problem can affect any ViewManager that doesn't extend BaseViewManager directly, it does not only affect ReactHorizontalScrollContainerViewManager

**Pull request closed without merging**
