### PR TITLE
Android: Add support for having borders on <Text> & <TextInput> components

### PR DESCRIPTION
**Pull request by rigdern**
Currently, `<Text>` and `<TextInput>` components on Android do not support borders.
This change adds support for the borderRadius, borderColor, and
borderWidth props on the `<Text>` and `<TextInput>` components on Android.

ReactViewGroup already implements this functionality so
we copied its implementation over into the ReactTextView
and ReactEditText classes.

**Test plan (required)**

Verified that the various border props work on Text and TextInput components in a test app.

Adam Comella
Microsoft Corp.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @manicakes and @lexs to be potential reviewers.

**Comment by mkonicek** [comment]
Sorry for the delay @rigdern. Thanks for adding this!

Would it make sense to extract some of the code to helpers shared between `ReactTextView` and `ReactViewGroup` or not worth it?

**Comment by lexs** [comment]
Methods are so short so helpers will probably just be awkward.

**Comment by lexs** [comment]
Looks like it needs a rebase @rigdern

**Comment by mkonicek** [comment]
Yeah, sorry about the churn @rigdern :(

**Comment by andreicoman11** [comment]
Awesome work! Sounds like we add this behavior into TextInput as well.

**Comment by facebook-github-bot-9** [comment]
@rigdern updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9658/files/3fcb6275e0f5bb280d958f3670ccf15e3beca071..6a03b8fdfc4597fdfc5c0acc8117b8f76949850e) - [changes since last import](https://github.com/facebook/react-native/pull/9658/files/3fcb6275e0f5bb280d958f3670ccf15e3beca071..6a03b8fdfc4597fdfc5c0acc8117b8f76949850e)

**Comment by rigdern** [comment]
@mkonicek I rebased the branch and added similar border support for the `<TextInput>` component. I agree with @lexs statement that it'd be awkward to share the code because the methods are so short.

**Comment by andreicoman11** [comment]
This look great! Mind looking into the test failure? Then we can ship this.

**Comment by facebook-github-bot-6** [comment]
@rigdern updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9658/files/6a03b8fdfc4597fdfc5c0acc8117b8f76949850e..42620ca3b4061ad060b1141e59ea695f1ac8658b) - [changes since last import](https://github.com/facebook/react-native/pull/9658/files/3fcb6275e0f5bb280d958f3670ccf15e3beca071..42620ca3b4061ad060b1141e59ea695f1ac8658b)

**Comment by facebook-github-bot-7** [comment]
@rigdern updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9658/files/42620ca3b4061ad060b1141e59ea695f1ac8658b..b6916ebf2c93389d2575e4337fbf86cdd882e2ca) - [changes since last import](https://github.com/facebook/react-native/pull/9658/files/3fcb6275e0f5bb280d958f3670ccf15e3beca071..b6916ebf2c93389d2575e4337fbf86cdd882e2ca)

**Comment by andreicoman11** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3819993) to review internal test results.

**Pull request closed without merging**
