### PR TITLE
[Android] Add missing onError event to Image

### LINKED ISSUE #7440: [Android] Support for Image onError
Hey Guys,

Will there be support for an onError callback on Image for Android? I want to set an error image if the image fails to load, without resorting to hacking around onLoad and onLoadEnd. If I'm overlooking an obvious easy way to do this please let me know :)

### PR DESCRIPTION
**Pull request by webzepter**
This PR adds `onError` prop to `Image` on Android. Closes #7440 

**Motivation**:
We have image feed and show refresh button when image loading had failed. 

Usage of  `onError` event is necessary to track loading failures

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @andreicoman11 and @Bhullnatik to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
@webzepter updated the pull request.

**Comment by brentvatne** [comment]
Hi there! Thanks for the PR. This was actually intentionally left out because Fresco doesn't fully support it yet, see: https://github.com/facebook/react-native/pull/3791#discussion_r62737711

**Comment by mkonicek** [comment]
@brentvatne Looks like we emit an `ON_ERROR` event in native? This PR would make it possible to handle it in JS, correct?

https://github.com/facebook/react-native/blob/bcf48e74aee77d8e5604047b1412154247370f12/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java#L214

**Comment by webzepter** [comment]
@mkonicek yes

**Comment by facebook-github-bot-5** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @rigdern as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by brentvatne** [comment]
@mkonicek - the problem is that the behaviour is inconsistent with iOS-- once Fresco has similar error semantics this is easy. I don't follow that project closely and I'm not sure what the current state is. if we merge this we have to keep in mind, and document, that the callbacks fire in different situations on each platform.

**Comment by lacker** [comment]
Hey, so chatting with @brentvatne and based on the discussion in https://github.com/facebook/react-native/pull/3791#discussion_r62737711 and this thread it seems like this current behavior is working as intended, at least as long as Fresco's behavior makes it impossible for iOS and Android to behave consistently. I'm going to close this pull request, but if it is indeed possible to have this with consistent behavior across iOS and Android, feel free to reopen.

**Pull request closed without merging**
