### PR TITLE
[PushNotificationIOS] Rename _remoteNotificationCompleteCalllbackCalled to _remoteNotificationCompleteCallbackCalled

### PR DESCRIPTION
**Pull request by koenpunt**
Just noticed this typo

### CODE REVIEW

**Comment by hramos** [comment]
That's unfortunate. To avoid introducing a breaking change, would you consider leaving the misspelled method in place, but with a deprecation warning?

**Comment by koenpunt** [comment]
Is that necessary? since it's an internal method

**Comment by koenpunt** [comment]
Ehm, wait, it isn't even a method, just a property

**Comment by hramos** [comment]
Ah, you're right. Landing.

**Pull request closed without merging**
