### PR TITLE
Add logging level for RNPM previous linking

### PR DESCRIPTION
**Pull request by GantMan**
Sometimes when working with a team of developers, someone adds a library but does not link it.  To identify if this required linking, you have to type `react-native link` and then read a wall of text to see if rnpm handled the issue.   This can be sped up with a friendly logging level for previously linked messages.

**This PR turns this:**
screen shot 2016-08-21 at 11 49 07 am

**Into this:**
screen shot 2016-08-21 at 11 52 31 am

Which is a pretty nice experience!   This also helps you quickly identify when 1 thing wasn't linked, at a glance, like so!
image

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @grabbou to be a potential reviewer.

**Comment by GantMan** [comment]
Looks like a test failed, but unrelated to the change as far as I can tell.  Seems to be a timeout.

**Comment by satya164** [comment]
I think `info`, `debug`, `warn` and `error` are the only log levels used everywhere. So we shouldn't change that. I'd prefer something like,

```
install info [skip] ...
install info [done] ...
```

But @Kureev is the boss!

**Comment by GantMan** [comment]
The color adjustments as you see are quite stark, and helpful.  Moving to a prefix won't have those benefits (unless the prefix is colored).  Happy to adjust this either way, though :)

**Comment by satya164** [comment]
I think we can color the prefix. But let's wait for @Kureev

**Comment by grabbou** [comment]
Great PR, I think `skip` prefix of gray color would be good enough (and also potentially useful for other commands).

**Comment by GantMan** [comment]
@grabbou - Here's what `chalk.grey` looks like on my machine.   Seems pretty good.
image

Let me know if I should update the PR with this.

**Comment by grabbou** [comment]
Looks good to me that way. Don't want to spend much time working on the `log` module as eventually we are going to replace it with something unified across all commands :)

**Comment by GantMan** [comment]
ok @grabbou - updated the PR to be the grey.

**Comment by facebook-github-bot-9** [comment]
@GantMan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9507/files/9fd1626d3c062550222ac04c31132f9e2bca923a..65674cc9588af83329daaa9b4d916d52c43bc6c1)

**Comment by facebook-github-bot-5** [comment]
@GantMan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9507/files/65674cc9588af83329daaa9b4d916d52c43bc6c1..b9b2e1d9a7ac6f6368640e5988d1060670217057)

**Comment by facebook-github-bot-7** [comment]
@GantMan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9507/files/b9b2e1d9a7ac6f6368640e5988d1060670217057..65674cc9588af83329daaa9b4d916d52c43bc6c1)

**Comment by grabbou** [comment]
@GantMan mind updating just to be sure it passes? I'll ship it right after! Thanks, looks very good now :)

**Comment by facebook-github-bot-6** [comment]
@GantMan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9507/files/65674cc9588af83329daaa9b4d916d52c43bc6c1..b6bc06b6cf9323301d483e64193fb9e216487742)

**Comment by GantMan** [comment]
@grabbou  - tests failed again?   Any way you can just kick it off from circle-ci?

**Comment by grabbou** [comment]
You can ignore the tests, I think they are failing because of other reason. Have you tried rebasing?Github says there's a conflict (I just moved files around in my recent commit).

**Comment by facebook-github-bot-7** [comment]
@GantMan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9507/files/b6bc06b6cf9323301d483e64193fb9e216487742..ed071c9da2208fc883e61c0b4bf4997ecb794f9a)

**Comment by facebook-github-bot-9** [comment]
@GantMan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9507/files/ed071c9da2208fc883e61c0b4bf4997ecb794f9a..9b37927dfd5319f6e77c76cd2df796b596fd1e2b)

**Comment by GantMan** [comment]
@grabbou - updated the PR to be OK with master.

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@GantMan this PR has jest test failures.
@grabbou, please keep an eye on failed CI reports when shipping.

I'll do a quick revert, please send give it another try.
Unless you have a quick fix in mind

**Comment by bestander** [comment]
Filed PR builds https://circleci.com/gh/facebook/react-native/tree/pull%2F9507

**Comment by GantMan** [comment]
@bestander  - as you can see from the above, we're concluding that the failures are not directly related to this PR.  If you have a suggestion for how to fix this, happy to do so.

**Comment by bestander** [comment]
Yeah, we do have random errors or integration between build systems broken, this week was particularly red build-wise because of Buck changes.
But when both circle and travis are red then it is a good chance that something is wrong with the code.

In this case, build before revert
https://circleci.com/gh/facebook/react-native/10441 (failing on npm test)
after revert
https://circleci.com/gh/facebook/react-native/10442 (green so far).

Could you help us out and give find a fix?
I suppose that ` local-cli/link/link.js` is used in jest tests and loading `chalk` just chokes jest.
Most logical is to mock chalk in __mocks__ folder

**Comment by grabbou** [comment]
> Yeah, we do have random errors or integration between build systems broken, this week was particularly red build-wise because of Buck changes.

I think that's partially the reason we tend to ignore errored builds when changes are small. Sorry for the troubles, I'll double check the trace next time!

FYI I'll be online in 2/3 hours to take a closer look at that one.

**Comment by GantMan** [comment]
Ah, that makes sense @bestander 

What's the procedure from here?  Do I open a new PR with the mocks?

**Comment by bestander** [comment]
Yeah, just open a new PR please

**Pull request closed without merging**
