### PR TITLE
fix create multiple ReactInstanceManager

### PR DESCRIPTION
**Pull request by chenqizheng**
## Summary

 create multiple ReactInstanceManager will be crash.

 Crash log:
 >---java.lang.IllegalMonitorStateException: object not locked by thread before wait()
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:442)
java.lang.Object.wait(Object.java:568)
com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:953)
java.lang.Thread.run(Thread.java:929)

**Never synchronize on Boolean** 
**Lock object must be final**

## Changelog

[Android] [Fixed] - fixbug Create multiple ReactInstanceManager

### CODE REVIEW

**Comment by JoshuaGross** [comment]
Hi @chenqizheng, can you help me understand how you're running into this crash? Why are you creating multiple ReactInstanceManager instances?

**Comment by chenqizheng** [comment]
> Hi @chenqizheng, can you help me understand how you're running into this crash? Why are you creating multiple ReactInstanceManager instances?

1.  can you help me understand how you're running into this crash? 

This is a crash when multi-threaded（crash probability 0.1%）. But I cannot reproduce it.
when UIThread run in “ReactInstanceManager.destroy” method. "create_react_context" Thread run in ReactInstanceManager line:1009,  just now,  “ReactInstanceManager.destroy” method run to "mHasStartedDestroying = false;". "create_react_context" thread synchronize Object is Boolean.TRUE, but call "wait" method is Boolean.FALSE.

this is a Java Code Sample to use Boolean Lock .
[Boolean Lock test](https://github.com/chenqizheng/leetcode/blob/master/src/main/java/com/chen/concurrent/BooleanLockTest.java) 

2. Why are you creating multiple ReactInstanceManager instances？

In My App, I has multiple Fragment,  has multiple React-Navite Module bundle.so I need to create multiple ReactRootView and ReactInstanceManager

**Comment by sunnylqm** [comment]
Is this related? https://github.com/facebook/react-native/issues/21755#issuecomment-447507580

**Comment by chenqizheng** [comment]
> Is this related? [#21755 (comment)](https://github.com/facebook/react-native/issues/21755#issuecomment-447507580)

No. My problem is not reproducible. Analyze crash logs, The problem is not just creating multiple ReactInstanceManager.

**Pull request closed without merging**
