### PR TITLE
Fixed typo in packager middleware

### PR DESCRIPTION
**Pull request by bestander**
**Test plan (required)**

Run packager

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @grabbou and @Kureev to be potential reviewers.

**Comment by bestander** [comment]
Fixes https://github.com/facebook/react-native/pull/9009

**Comment by kentaromiura** [comment]
LGTM
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1039302399457765/int_phab) to review internal test results.

**Pull request closed without merging**
