### PR TITLE
Eslint fixes 

### PR DESCRIPTION
**Pull request by udnisap**
Now it is 259 problems (119 errors, 140 warnings). 
This will reduce to 199 problems (119 errors, 80 warnings)

partial fix for #3316

### CODE REVIEW

**Comment by satya164** [comment]
Hey. Thanks for the PRs. Can you sign the CLA and fix these few additonal warnings?

**Comment by bestander** [comment]
@udnisap sorry, your PR got lost in the sea of others.
Would you mind rebasing and pinging me? 
I'll push it through.
We updated to eslint 2, so changes may break.

**Comment by facebook-github-bot-1** [comment]
@udnisap do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by ide** [comment]
We should change the lint rules to accept `!= null` and `== null`. Some of those existing checks without === are valid.

**Comment by udnisap** [comment]
I think we can close this. I wont be able to work on this for awhile.

**Comment by bestander** [comment]
ok, some other time, sorry for taking that long.
If anyone wants to inherit, just checkout PR and create a new one

**Pull request closed without merging**
