### PR TITLE
Update IntegrationWithExistingApps.md

### PR DESCRIPTION
**Pull request by Brian-Kaplan**
Just a little nit pick to add extra information to this doc. I spent a few hours trying to fix this problem because I had not placed the code in build.gradle correctly. I think this small addition would be useful to others.

### CODE REVIEW

**Comment by Brian-Kaplan** [comment]
@lacker your wish is my command

**Comment by hramos** [comment]
Thanks for sending this pull request! We would love to review your changes however it looks like you haven't signed the CLA yet. You can do so at https://code.facebook.com/cla.

**Comment by Brian-Kaplan** [comment]
@hramos @lacker why are your CI tests failing because of this?

**Comment by lacker** [comment]
Seems unrelated. Let me try rerunning them.

**Comment by hramos** [comment]
CI failures are likely to be unrelated. We're currently working on getting the tests back to green.

**Comment by Brian-Kaplan** [comment]
@hramos @lacker any updates on these tests?

**Comment by hramos** [comment]
@Brian-Kaplan we're still working on it.

**Pull request closed without merging**
