### PR TITLE
typo

### PR DESCRIPTION
**Pull request by coolguy001tv**
`constuctor` to `constructor`

### CODE REVIEW

**Comment by dsibiski** [comment]
@facebook-github-bot shipit

**Comment by dsibiski** [comment]
Thanks!

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
We have a test error here:
```
/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/promise/lib/done.js:10
      throw err;
      ^
SyntaxError: /data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/Examples/UIExplorer/UIExplorerExampleList.js: missing super() call in constructor
  43 | 
  44 | class UIExplorerExampleList extends React.Component {
> 45 |   constructor(props: {
     |   ^
  46 |     disableTitleRow: ?boolean,
  47 |     onNavigate: Function,
  48 |     filter: ?string,
    at File.buildCodeFrameError (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-core/lib/transformation/file/index.js:431:15)
    at NodePath.buildCodeFrameError (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:147:26)
    at pushBody (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-preset-react-native/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:291:24)
    at buildBody (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-preset-react-native/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:244:10)
    at run (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-preset-react-native/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:151:10)
    at PluginPass.ClassExpression (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-preset-react-native/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:63:60)
    at newFn (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:75:18)
    at NodePath.call (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/data/sandcastle/boxes/instance-fbobjc-fbsource-catalyst-buck-iphonesimulator-local/fbobjc/Libraries/FBReactKit/js/react-native-github/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:156:16)
```

**Comment by grabbou** [comment]
Can we use propTypes? Don't think there's constructor needed if it's empty.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/607342719428494/int_phab) to review.

**Comment by mkonicek** [comment]
There's a legit error:

    missing super() call in constructor, caught by e2e tests

**Comment by grabbou** [comment]
We should just rewrite that to flow `props {}` instead afaik.

**Comment by facebook-github-bot-1** [comment]
@coolguy001tv do you have any updates for this pull request? It's been a while since the last update so wanted to check in and see if you've looked at the requested changes.

**Comment by javache** [comment]
Already fixed it seems.

**Pull request closed without merging**
