### PR TITLE
Add support for flashScrollIndicators on iOS

### PR DESCRIPTION
**Pull request by jeanregisser**
## Motivation

Flashing scroll indicators is a standard behavior on iOS to show the user there's more content.

## Test Plan

Launch RNTester on iOS, go to the ScrollView section, tap the "Flash scroll indicators" button.
You'll see this:

Flash scroll indicators

# Misc

I've exposed the method `flashScrollIndicators` on all scrolling components that were already exposing a `scrollToXXX` method so it's usable from those components using a ref.

Let me know what you think.

### CODE REVIEW

**Comment by jeanregisser** [comment]
@javache let me know if there's anything I can do to make the import succeed.

**Comment by javache** [comment]
Can you update the ScrollViewExample snapshot test? This is currently breaking tests.

**Comment by jeanregisser** [comment]
@javache done!

Note: while generating the updated snapshots, I noticed 2 issues:
- I had to fix the RNTester tvOS unit test to link against RCTTest otherwise it didn't compile. (Is it just me?)
- `testSliderExample_1@2x.png` has not been updated in 295a0150d4a9a0c1ce62675c38afb84877aee5d5
See the difference for "Custom min/max track tinit color" in [testSliderExample_1-iOS10@2x.png](https://github.com/facebook/react-native/blob/3c64d9541373eecdae3d012cd50e3ef5fbe25f81/RNTester/RNTesterIntegrationTests/ReferenceImages/RNTester-js-RNTesterApp.ios/testSliderExample_1-iOS10%402x.png) and [testSliderExample_1@2x.png](https://github.com/facebook/react-native/blob/3c64d9541373eecdae3d012cd50e3ef5fbe25f81/RNTester/RNTesterIntegrationTests/ReferenceImages/RNTester-js-RNTesterApp.ios/testSliderExample_1%402x.png)

Is it still worth it to update non `-iOS10` snapshots? Are automated tests only running for iOS10?
Should I open new PR to fix these?

Thanks

**Comment by shergin** [comment]
I am afraid, we have to redo snapshots one more time... because I changed them.

**Comment by jeanregisser** [comment]
@shergin what iOS versions did you use to generate the snapshots?

I rebased my changes against the latest master and tried to regenerate the snapshots, but I got more changed snapshots than `testScrollViewExample_1*`. I used iOS 10.1 and 10.2. and got the same change for both on `testSliderExample_1-iOS10@2x.png`.

Here is a visual diff: left is original version in master you generated, middle is diff, right is my version:

diff

As you can see, the difference is only in the last 2 examples that use a custom track image.
Looking at `slider.png` and `slider-left.png` or `slider-right.png` I see that they have an embedded color profile: `Generic RGB Profile`.

I'm wondering if the new snapshot infra is dependant on a specific screen color profile.
What's your take on this?

**Comment by jeanregisser** [comment]
I just tried changing my screen color profile and got the same results as on my initial test.

Also I can see that the example with the thumbs up image `uie_thumb_big.png` is not affected by the difference. And this one has no color profile embedded.

**Comment by shergin** [comment]
Oooops, as I mentioned in 3df537a25c9490da85ba5620c95ddaef98d53d18, I changed the way how we make screenshots, and it probably causes your problem. The tests works fine in cloud thought. 
I used iPhone 5S and iOS 10.3.

So, should we remove color profile from images?

**Comment by jeanregisser** [comment]
Ok I'll try tomorrow with 10.3
What about the non iOS10 snapshots? Did you use iOS 9.3? Or else?

**Comment by jeanregisser** [comment]
Alright @shergin @javache, I got the right output!

For iOS10 snapshots, I used iOS 10.3 on iPhone 5S and Apple TV 10.2 simulators. 
For non iOS10 snapshots, I used iOS 9 on iPhone 5S and Apple TV 9.2 simulators.
With these, only the `testScrollViewExample_1*` were changed, which is expected.

We should probably document what devices and iOS versions are used to generate those snapshots. I had different results using 10.2 or iOS 9.3

**Pull request closed without merging**
