### PR TITLE
Include ViewStylePropType files so that AnimatedWeb can be built

### PR DESCRIPTION
**Pull request by browniefed**
Reference https://github.com/facebook/react-native/issues/4244

### CODE REVIEW

**Comment by mkonicek** [comment]
Looks like  #4244 is resolved.

**Comment by mkonicek** [comment]
Hey @browniefed! Thanks for making the pull request, but we are closing it due to inactivity to make sure all pull requests are either being worked on or closed. If you want to get your proposed changes merged, please rebase your branch with master and send a new pull request :)

**Comment by mkonicek** [comment]
I hope I'm not closing this one by mistake. Saw the linked issue was closed.

**Comment by browniefed** [comment]
@mkonicek you're good, we split out animated to an entire different org https://github.com/animatedjs

**Pull request closed without merging**
