### PR TITLE
Edits to flipper pods comments

### PR DESCRIPTION
**Pull request by brotsky**
grammar edits

## Changelog

[Internal] [Fixed] - Edits to flipper pods comments

### CODE REVIEW

**Comment by charpeni** [comment]
@facebook-github-bot shipit

**Comment by charpeni** [comment]
Ugh, the base branch wasn't happy. Will take a look at it.

**Comment by charpeni** [comment]
@facebook-github-bot shipit

**Comment by brotsky** [comment]
> Thanks!

no problem!

**Pull request closed without merging**
