### PR TITLE
[Systrace] Update message with instructions

### PR DESCRIPTION
**Pull request by tadeuzagallo**
The middleware for automatically converting Systrace traces to HTML and popping the browser hasn't worked properly for a while, since the version on Homebrew generates some code that uses `Object.observe`, which was deleted from Chrome ages ago. People have complained about it, but fixing it properly has proven to be harder than expected, so I suggest we simply update the message with instructions for people to load it on Chrome, which is what all of us have been doing anyway (AFAIK).

### CODE REVIEW

**Comment by ide** [comment]
LGTM but would like someone at FB to sign off on it to make sure it doesn't break internal workflows either (@astreet?).

**Comment by astreet** [comment]
Sorry, I really don't know anything about the systrace integration with the packager. Looks like @Martin B wrote it so I'll try to tag him as a reviewer.

**Comment by tadeuzagallo** [comment]
Actually, I wrote it, I believe @martinbigio moved it later as it was messy. Maybe @javache would know?

**Comment by javache** [comment]
Hey @tadeuzagallo! We actually tried upgrading trace2html upstream (https://github.com/Homebrew/homebrew-core/pull/4638 https://github.com/Homebrew/homebrew-core/pull/7485) but I don't think that has shipped.

**Comment by tadeuzagallo** [comment]
Yeah, I'm aware of that, but I tried running the regular workflow and it didn't work, so I thought it could make sense to just update the message, and later on if/when it ships on systrace we can just change it back. Not sure how many people use it though, but seems unfriendly since it's just there seating in the dev menu and when people run it it fails and they get an unhelpful alert.

**Comment by javache** [comment]
Internally we tell people to run this

    curl https://gist.githubusercontent.com/javache/344da5bb6b7801087e2fb4fdf33342aa/raw/b9da7a846de1f45281cfb2ad3cab2546c6858d83/gistfile1.txt > "$(EDITOR=echo brew edit trace2html)"
    brew reinstall trace2html

Perhaps we could add something like that to the debug message? I'm fine with merging this too though.

**Comment by gaearon** [comment]
@tadeuzagallo I was going to import this, but looks like there’s no CLA on you 😢 . Could you please email **cla@fb.com** with your details?

**Comment by tadeuzagallo** [comment]
Oops... I already emailed, just forgot to fill the form, will do it today!

**Comment by gaearon** [comment]
Thanks! I just bumped into this issue myself and been copy-pasting `Object.observe` polyfill into the generated HTML 😭

**Pull request closed without merging**
