### PR TITLE
Fix StyleSheet 'textAlign' for AndroidTextInput,rename Android native props

### PR DESCRIPTION
**Pull request by trave7er**
- rename Android native prop 'textAlign' to 'textAlignAndroid'
- rename Android native prop 'textAlignVertical' to 'textAlignVerticalAndroid'
- add another 'setTextAlign' in ReactTextInputManager for StyleSheet prop
- add demo

### CODE REVIEW

**Comment by trave7er** [comment]
The reason behind renaming 'textAlign' to 'textAlignAndroid': StyleSheet is looking for a prop 'textAlign' of type 'String', while AndroidTextInput is looking for an Android native prop with the same name of type 'int'

**Comment by foghina** [comment]
@andreicoman11

**Comment by kmagiera** [comment]
I don't understand why we need separate `textAlign` attribute at all. Can't we just update all android TextInput examples to set `textAlign` through `style` [property](http://facebook.github.io/react-native/docs/text.html#props) and also add `textVerticalAlign` to the `StyleSheet` definition instead of exposing it as a direct property of the view (it may be implemented for regular textview as well).

cc @foghina who may have more context on why the decision on not using `textAlign` from `StyleSheet` was made here 22ea66923f437fe91657f90b146404eb0d0e51ba

**Comment by trave7er** [comment]
Hi @kmagiera, thanks for your input. It seems that `ReactEditText` and `ReactTextView` are inherited from different native views: `ReactEditText extends EditText`, `ReactTextView extends TextView`. And the `setTextAlign` method I added are almost identical to the one in `TextView`, but since they are from different super classes, I'm not sure how to create a simpler and more elegant solution.

And with the changes in this PR, `StyleSheet` will be picking up `textAlign` of type `String`.

**Comment by kmagiera** [comment]
I think it's fine to use `Strings` for `textAlign` property especially that `TextView` is a component that is used much more frequently and considering that it's using `Strings` for this property means that using `int` in `EditText` shouldn't make that much of a difference.

To actually have any benefits from optimizing this sort of bridge traffic it would be better to think about some more generic solution that would allow us to perform this type of String<->int conversions that would be more transparent from the code perspective, so that we can optimize all those properties automatically.

**Comment by trave7er** [comment]
BTW, is it possible to overload `@ReactMethod` methods?

**Comment by kmagiera** [comment]
Yes, although need to add `@ReactNative` annotation to the overloaded method as well

**Comment by trave7er** [comment]
@kmagiera I just put up a new PR https://github.com/facebook/react-native/pull/4481 that addresses some of the issues we talked about here. Basically, the new PR is no longer a breaking change, and it also unifies the Android native prop and the StyleSheet prop.

**Comment by kmagiera** [comment]
Thanks so much, I understand this can now be closed in favor of #4481

**Pull request closed without merging**
