### PR TITLE
[Android][Tests][E2E] Brings accessibilityLabel into PickerAndroid

### PR DESCRIPTION
**Pull request by isnifer**
Hi!

I found problem with accessibilityLabel on PickerAndroid.
There's no value in content-desc attribute while accessibilityLabel is correct.
I found that accessibilityLabel is not propagated into native components via
native props.

This PR brings accessibilityLabel for PickerAndroid.

Without this solution my appium tests fails, for example:

My code:
```jsx
<Picker
    style={this.props.style}
    selectedValue={this.props.value}
    onValueChange={this.onChange}
    disabled={this.props.disabled}
    accessibilityLabel="select_wineType">
    // Chilren
</Picker>
```

```sh
✖  Error: element (~select_wineType) still not visible after 5000ms
```
Because xml of this view is (look into content-desc of Spinner):
```xml
<android.widget.Spinner index="0" text="" class="android.widget.Spinner" package="com.hello_github" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="true" long-clickable="false" password="false" selected="false" bounds="[0,148][720,248]" resource-id="" instance="0">
    <android.widget.TextView index="0" text="All wines" class="android.widget.TextView" package="com.hello_github" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,176][672,219]" resource-id="android:id/text1" instance="0"/>
</android.widget.Spinner>
```
`content-desc=""` is empty.

After this patch:

```sh
✔  Select "wineType" exists on page
```

```xml
<android.widget.Spinner index="0" text="" class="android.widget.Spinner" package="com.hello_github" content-desc="select_wineType" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="true" long-clickable="false" password="false" selected="false" bounds="[0,148][720,248]" resource-id="" instance="0">
    <android.widget.TextView index="0" text="All wines" class="android.widget.TextView" package="com.hello_github" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,176][672,219]" resource-id="android:id/text1" instance="0"/>
</android.widget.Spinner>
```

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @spicyj to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
@isnifer updated the pull request.

**Comment by facebook-github-bot-1** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @spicyj as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by facebook-github-bot-4** [comment]
@isnifer updated the pull request - [view changes](https://github.com/facebook/react-native/pull/8873/files/2781ff9c1a8586de5bfc08833ff47ba905bcfb9e..f385cc66d7cf1ddc4f92a5c23c58abb64123a62f)

**Comment by spicyj** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
