### PR TITLE
use Nullable, NonNull and GuardedBy annotations from AndroidX

### PR DESCRIPTION
**Pull request by dulmandakh**
## Summary

This PR replaces JSR-305 Nullable, NonNull and GuardedBy annotations with same annotations from AndroidX, and remove JSR-305 from deps when possible. AndroidX annotation is used in every aspect of AndroidX, thus most packages require it to build.

## Changelog

[Android] [Changed] - use Nullable and NonNull annotations from AndroidX

### CODE REVIEW

**Comment by cpojer** [comment]
I had to revert the changes to Yoga because it can run outside of Android.

**Comment by dulmandakh** [comment]
@cpojer excluded yoga from the change

**Comment by cpojer** [comment]
I think I'll need @mdvacca's help to land this :)

**Comment by cpojer** [comment]
Hey @dulmandakh, could you rebase and resolve conflicts on this PR this week so we can merge it? :)

**Comment by mdvacca** [comment]
@dulmandakh  
Nullable and NonNull annotations were migrated to Android X as part of:
https://github.com/facebook/react-native/commit/aa5edca0e229940c79f2efcb917f5c8b05022e4d

Feel free to close this PR and I will migrate GuardedBy annotations as part of another PR.

CC @cpojer, @makovkastar

**Pull request closed without merging**
