### PR TITLE
match plist indentation with xcode format

### LINKED ISSUE #11668: react-native link creates large diff on project's Info.plist
### Description

When running `react-native link`, the indentation of `Info.plist` of the xcode project changes from tabs to spaces, which results in a big changeset. And this wouldn't be an issue if this happens only once, but the problem is that everytime something gets changed in the plist from xcode, it reverts back to tabs.

I did a bit of research, and found that the plist builder allows options, specifically `indent`, but when set to a tab (`\t`), the indendation still doesn't match with the format xcode maintains, because xcode starts its indentation from the first `dict` element, and not the `dict` element itself:

image

This might be an issue that has to be solved with the plist builder library, but the plist format itself doesn't dictate this specific indentation, only xcode does.

### Solution

A possible solution could be that the plist is generated in so to say "fragments", where the `dict` element is generated, and then is manually wrapped in the `plist` element.

### PR DESCRIPTION
**Pull request by koenpunt**
xcode has its own way of indentation of the plist.

fixes #11668

### CODE REVIEW

**Comment by ncuillery** [comment]
That makes the output of the `link`command consistent with the upgrade too. No more unreadable `Infos.plist` diff after running either of the commands  👍 👏

**Comment by grabbou** [comment]
Are we sure this is the only occurrence of the plist write? Maybe it makes sense to extract the entire fs.writeSync to a separate function (file), called `writePlist` and document `why` we set the encoding explicitly?

Apart from that all good!

**Comment by koenpunt** [comment]
Ah you're right, `unlinkAssets` also writes the plist. What would be the preferred name for this? as opposite of `getPlist` `putPlist` would maybe be most appropriate.

**Comment by grabbou** [comment]
Yeah, `putPlist` makes sense, don't have opinion here. Separate file, unit tests and we are ready to go :)

**Comment by koenpunt** [comment]
@grabbou done! Went for `writePlist` in the end.

**Comment by grabbou** [comment]
Looks good @koenpunt, can we verify whether test failures seem PR related or not? Rebase off master could help.

I'll get to review it tomorrow and ship :)

**Comment by koenpunt** [comment]
Rebase done!

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by grabbou** [comment]
Thanks @koenpunt, I like the entire PR, the way you `got` the styleguide and contributed the code that looks 100% nice!

**Comment by koenpunt** [comment]
@grabbou thanks! but did something went wrong with shipping? Because this PR is still open..

**Comment by dsernst** [comment]
Any updates on this in the last month? Unclear what's blocking.

**Comment by koenpunt** [comment]
@grabbou ping ✨

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by grabbou** [comment]
CC: @bestander

**Comment by bestander** [comment]
Looks like it landed already

**Comment by koenpunt** [comment]
Woop 🎉

**Pull request closed without merging**
