### PR TITLE
refine android config

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation
By this change we can unify version early, like we can make kotlin version share in buildscript and app dependency the same time ([butterknife](https://github.com/JakeWharton/butterknife/blob/master/build.gradle) use the same).
## Test Plan
pass all current ci and one of my project https://github.com/gengjiawen/ReactNative64bitDemo.
## Related PRs
none
## Release Notes
 [GENERAL] [ANDROID] [TEMPLATE] - refine android config

### CODE REVIEW

**Comment by dulmandakh** [comment]
You can still access these properties from an app and any library using rootProject variable.

**Comment by gengjiawen** [comment]
not in buildscript.

**Comment by dulmandakh** [comment]
how about gradle.properties file?

**Comment by gengjiawen** [comment]
Nope, I think this is better.

**Pull request closed without merging**
