### PR TITLE
Fix typo in ResolutionRequest.js

### PR DESCRIPTION
**Pull request by radko93**
Small fix:
Fix typo in error message - should be `npm start --reset-cache`

### CODE REVIEW

**Comment by cooperka** [comment]
@radko93 this doesn't work for me. I thought the `--` was necessary to pass the `--reset-cache` flag through to `node node_modules/react-native/local-cli/cli.js start` instead of applying it to `npm start`. Is it possibly project dependent?

**Comment by radko93** [comment]
It could be related to npm or node version.

**Comment by cooperka** [comment]
Hmm, based on the comments [here](https://github.com/facebook/react-native/issues/1924#issuecomment-249861004) it looks like using the double dash is much more common. I honestly don't know how it would work without it, since npm doesn't understand that flag and it needs to be passed through.

Do you think we should open an issue, or how should this be resolved? If it truly works for you without the double dash, something very weird is going on 😕 

@radko93 I'm on node v7.7.1, npm v4.1.2, and RN v0.42.0, what about you?

**Comment by hramos** [comment]
@cooperka I merged this in and I'm willing to look at a PR to revert this if it turns out to be inaccurate.

**Pull request closed without merging**
