### PR TITLE
Convert warning about keystore into warning block in SignedAPKAndroid.md

### PR DESCRIPTION
**Pull request by tomwalters**
The current docs page [Generating a Signed APK](https://facebook.github.io/react-native/docs/signed-apk-android.html) contains a note about keeping your generated keystore safe, but this isn't well highlighted.

This commit highlights the notice in a warning blockquote to ensure people following the guide don't miss the importance of keeping the keystore safe as shown below:

screen shot 2016-06-06 at 10 01 25

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @vikeri and @mkonicek to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
@tomwalters updated the pull request.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1128211490584708/int_phab) to review.

**Pull request closed without merging**
