### PR TITLE
chore: Extract codegen ParserError from flow and typescript into a common file

### PR DESCRIPTION
**Pull request by gabrieldonadel**
## Summary

This PR extracts the `ParserError` class from the `error.js` files from the flow and typescript folders into a single file in their parent folder in order to reduce the amount of duplicated code as requested on https://github.com/facebook/react-native/issues/34872

## Changelog

[Internal] [Changed] - Extract codegen `ParserError` from flow and typescript folders into a common file

## Test Plan

Run `yarn jest react-native-codegen` and ensure CI is green

image

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]

**Review by cortinico — APPROVED** [review]

**Comment by cipolleschi** [comment]
I'm sorry, we are landing some changes and these introduced some conflicts. Could you rebase and fix them, please? :pray:

**Comment by gabrieldonadel** [comment]
> I'm sorry, we are landing some changes and these introduced some conflicts. Could you rebase and fix them, please? 🙏

Sure @cipolleschi, no problem

**Comment by cipolleschi** [comment]
@hramos could you reimport this? 🙏

**Pull request closed without merging**
