### PR TITLE
Typo in documentation/image

### PR DESCRIPTION
**Pull request by benjick**

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by janicduplessis** [comment]
Thanks!

@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3731772) to review internal test results.

**Comment by satya164** [comment]
Please always send PRs to master branch. I've changed the base to master and there seem to be many conflicts here.

**Comment by charpeni** [comment]
This fix is already on master with 0c14090.

I think 0c14090 should be cherry-pick into stable branch instead of create a new commit and a PR for each branch.

**Comment by benjick** [comment]
The edit documentation link should go to master then. This is way too
complex just to try to correct a typo.

**Comment by JoelMarcey** [comment]
I will get that Edit on GitHub link fixed into the current documentation set tonight.

**Comment by benjick** [comment]
Sounds good!

**Comment by JoelMarcey** [comment]
Ok the CircleCI build is running for these to land in `0.31-stable` . The updated `Edit on GitHub` should be available in the next hour or so.

**Comment by mkonicek** [comment]
@benjick Can you please send a new PR to the master branch? I'll close this one as it has many commits not related to the change.

**Comment by benjick** [comment]
I thought it was already fixed in master

**Pull request closed without merging**
