### PR TITLE
Fix RCTActionSheetManager crash when callback is invoked multiple times

### PR DESCRIPTION
**Pull request by SRandazzo**
## Summary
When using `ActionSheetIOS` (`RCTActionSheet`) on iPad, if a user taps repeatedly outside the actionsheet to dismiss it, iOS will invoke the `UIAlertAction` callback multiple times.

This causes us to invoke the `RCTResponseSenderBlock` more than once, which crashes the app.

This change creates a reference to the callback, which is nil'd out after initial invocation. 

This issue exists as far back iOS 9, and is present on iOS 14 as well.
Here is a previous issue I was able to find (Closed for inactivity)
https://github.com/facebook/react-native/issues/13936

I also removed a `_callbacks` NSMapTable declaration/initialization which appears to be unused and was made obsolete as of this commit: https://github.com/facebook/react-native/commit/07553d0f1c61173edad804c4e7a93c902719e05b

## Changelog

[iOS] [Fixed] - Resolves a crash when using ActionSheetIOS on iPad

## Test Plan

On iPad, create a TouchableOpacity and on it's `onPress`, call `ActionSheetIOS.showActionSheetWithOptions`. 
*Make sure the ActionSheet has a cancel button index.*
```Java Script
const BUTTONS = [ 'Option 0', 'Option 1', 'Option 2', 'Cancel'];
const CANCEL_INDEX = 3;

const options = {
            options: BUTTONS, cancelButtonIndex: CANCEL_INDEX
        };

ActionSheetIOS.showActionSheetWithOptions(options, (buttonIndex) => console.log(buttonIndex));
```

Rapidly tap outside of the ActionSheet so that it will be cancelled. 

Pre-fix, observe a redscreen: `Illegal callback invocation from native module. This callback type only permits a single invocation from native code.`

Post-fix, the ActionSheet dismissed without issue

### CODE REVIEW

**Review by Prash88 — APPROVED** [review]
LGTM!!

**Comment by SRandazzo** [comment]
Android tests appear to be failing for unrelated reasons
`Waiting for Android Virtual Device to finish booting...`

Otherwise all other tests are currently passing!

If there is anything else I can do to help maintainers with this PR lmk and I will happily adjust/update

**Comment by SRandazzo** [comment]
👋.   Any idea how I can go about getting this prioritized and merged? Anything I can do to help?

We have been using this in production via patch-package for  a while now and haven't had any issues,
Thanks

**Comment by SRandazzo** [comment]
Been using this in production via patch-package for about 9 months and would love to get some eyes on this from maintainers
A former contributor recommended I tag @hramos @JoshuaGross 
Thanks

**Comment by SRandazzo** [comment]
Wow 2 year anniversary of this being open! We are still using this code in production, but I just looked through and I believe this may have been fixed/reviewed/merged in 2 days by: https://github.com/facebook/react-native/pull/33099 
Will loop back around in the future to verify once we update RN

**Pull request closed without merging**
