### PR TITLE
Adding Gyroscope to Showcase.

### PR DESCRIPTION
**Pull request by myusuf3**

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @lacker and @brentvatne to be potential reviewers.

**Comment by brentvatne** [comment]
This is a really nice app that deserves to be on the showcase cc @lacker

**Comment by lacker** [comment]
Yeah this seems like the sort of content we want - that blog post seems helpful to RN developers. What do you mean by "our visualization experience"? How about just phrasing the link as

infoTitle: "Building a visualization experience with React Native"

**Comment by myusuf3** [comment]
Done! @lacker

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1020906874692908/int_phab) to review.

**Pull request closed without merging**
