### PR TITLE
Add subviewStyle prop to NavigationHeader

### PR DESCRIPTION
**Pull request by tlvenn**
Implements: #7204

Pinging @ericvicenti for review.

### CODE REVIEW

**Comment by ericvicenti** [comment]
Seeing as we already use the word "component", maybe we should rename this prop to `subComponentStyle`?

**Comment by tlvenn** [comment]
But wouldn't it imply that the style would be applied on the component itself rather than its container ?

**Comment by ericvicenti** [comment]
Ok, makes sense

**Comment by ericvicenti** [comment]
@facebook-github-bot shipit

**Comment by bestander** [comment]
@ericvicenti, please check the status of CI build before accepting.
This broke trunk :(
https://travis-ci.org/facebook/react-native/builds/125600477

@tlvenn do you have a quick fix?
Otherwise let's revert it and do a new iteration.

**Comment by bestander** [comment]
Revert has been pushed, give it another try please with the tests passing :)

**Comment by tlvenn** [comment]
Hmm my bad, i was actually wondering myself if I shouldn't had guard against this.. Guess I should had listen to myself :)

Let me fix and resubmit.

**Comment by bestander** [comment]
Please test related UI in UIExplorer.
We are asking for everyone to add a thorough Test Plan to every contribution because some things that may look minor can still affect a lot of people.
It usually takes less time to test than recover.

**Comment by tlvenn** [comment]
Fixed in #7235 and will make sure to proper test things next time.

**Comment by tlvenn** [comment]
Given that you already shipped the revert, I guess I need to wait until it lands before I can actually resubmit the whole thing ?

**Comment by bestander** [comment]
Yeah, it landed just a few minutes ago.
So go ahead, create a new one

On Tue, Apr 26, 2016 at 2:15 PM, Christian Meunier <notifications@github.com

**Comment by ericvicenti** [comment]
Sorry about the breakage. Thanks for being on top of this, @bestander!

**Comment by tlvenn** [comment]
New PR #7236 submitted @bestander

**Pull request closed without merging**
