### PR TITLE
Add Alert.alertAsync() , always returning a promise

### PR DESCRIPTION
**Pull request by slorber**
The point of this PR is to allow to await the completion of an Alert message

For example

```js
const myAction = async () => {
  const choice = await Alert.alertAsync(
    'Title',
    'Message',
    [
      {text: 'Yes', onPress: () => 'yes'},
      {text: 'No', onPress: () => Promise.resolve('no')},
    ],
    {
      cancelable: true,
      onDismiss: () => 'no',
    },
  );

  if (choice === 'yes') {
    doSomething();
  }
  else {
    doSomethingElse();
  }
}
```

I know it's currently possible to call `doSomething` / `doSomethingElse` inside the callbacks directly, but I clearly find this more convenient to decouple the alert question asking from the side effect of this choice, and this also makes it more easy to wire an alert message in the middle of an existing async flow, and make sure this async flow still returns a promise like it used to...

Test Plan:
----------
The current Alert JS code is not tested. 

I've been using this async wrapper in my app with great success so far.

I'm willing to write tests but not really sure I'm supposed to mock the `Alert.alert` static call with Jest, any help on this would be welcome. Should I do `Alert.alert = jest.fn();` and see how it gets called? Or is there a better way with Jest to mock this class internal static call without modifying current implementation?

Release Notes:
--------------

[GENERAL] [ENHANCEMENT] [Alert] - Add Alert.alertAsync, returning a promise

### CODE REVIEW

**Comment by vonovak** [comment]
This looks nice, but I have some doubt if it belongs to the core... Personally I find it more fitting to publish this as an independent module.

**Comment by slorber** [comment]
Don't know who to ping about that or weither it should be core or not. I prefer promises to callbacks but it's true RN doesn't have much promise based interfaces currently. @kelset any opinion?

**Comment by slorber** [comment]
Just to mention there is traction for this feature according to StackOverflow question views: https://stackoverflow.com/questions/48809762/how-to-await-for-the-response-of-alert-dialog-in-react-native

Can this be merged/reviewed? Should I publish this as a separate module?

**Comment by cpojer** [comment]
Thanks for publishing a standalone package for this. I think that's the best way forward, so I'm gonna close this PR.

**Pull request closed without merging**
