### PR TITLE
lock docker image version in ci

### PR DESCRIPTION
**Pull request by gengjiawen**
## Summary

Lock the version will help us to test new dependency version like ndk or buck.

## Test Plan

pass current ci

### CODE REVIEW

**Comment by cpojer** [comment]
How often do you expect this image to change? Can we lock it to something that doesn't have a date in it? I'm not really sure if this is better than what we have now.

**Comment by dulmandakh** [comment]
IIRC, CI will try to pull latest image from Docker registry and use it. And using this versioning scheme we can make sure that only working versions are used for CI, or prevent to use latest version automatically.

**Comment by gengjiawen** [comment]
React native is very sophisticated project in my opinion,  we may update it if `jdk`, `node`, `buck` or any other tools release new version.

You can check the image repo here: https://github.com/react-native-community/docker-android.

**Comment by dulmandakh** [comment]
@cpojer I expect that versions will be changed when we change tools versions, like SDK, NDK or BUCK.

**Comment by gengjiawen** [comment]
@cpojer If you want to involve the docker project, just let me know. I have talked to @hramos , but he has not reply my message.

**Comment by gengjiawen** [comment]
@cpojer should we import this again ?

**Comment by cpojer** [comment]
Yap! Seems like the import failed on the first try for some unknown reason.

**Pull request closed without merging**
