### PR TITLE
adds textAlignment to placeholder to match textViews alignment (for m…

### PR DESCRIPTION
**Pull request by DaveAdams88**
Submitting PR for adding textAlignment to the placeholder of textView so that it matches the alignment of the actual value text

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @bnham to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
@DaveAdams88 updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@DaveAdams88 updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@DaveAdams88 updated the pull request.

**Comment by facebook-github-bot-6** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @nicklockwood as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1760518410847420/int_phab) to review.

**Pull request closed without merging**
