### PR TITLE
[Docs] Remove default argument syntax on getVersionedGithubPath()

### PR DESCRIPTION
**Pull request by easyCZ**
Removes ES6 syntax of default arguments to fix website building as per #7434. [More info](https://github.com/facebook/react-native/pull/7434).

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @vjeux to be a potential reviewer.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/461962037341293/int_phab) to review.

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/461962037341293/int_phab) to review.

**Comment by janicduplessis** [comment]
Thanks for the quick fix :)

**Comment by bestander** [comment]
👍

**Pull request closed without merging**
