### PR TITLE
Fix 'React not found' issue

### PR DESCRIPTION
**Pull request by nicholaspsmith**
Fix React not found by importing React.

### CODE REVIEW

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
Thanks @nicholaspsmith!

**Comment by sebmarkbage** [comment]
We should fix the broken lint which caused this issue.

**Comment by janicduplessis** [comment]
@sebmarkbage Any idea what causes the lint error? I figured this was fine since we use jsx in the file.

**Pull request closed without merging**
