### PR TITLE
Simplify react-native overrides when building from source

### PR DESCRIPTION
**Pull request by mikelambert**
You may want to double-check that this works perfectly (I am trying to move away from RN-from-source, since my changes were upstreamed), but it seems to build without errors for me. And this has the advantage of working seamlessly with "rnpm", which isn't smart enough to add these excludes when linking modules.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @christopherdro and @mkonicek to be potential reviewers.

**Comment by christopherdro** [comment]
I'm not too familiar with gradle settings but this sure does look like a better option than excluding RN from each individual project.

/cc @satya164 @grabbou

**Comment by grabbou** [comment]
Leaving this one up for @satya164, he's the gradle master :)

**Comment by satya164** [comment]
LGTM

**Comment by satya164** [comment]
I need to test it though. Will it try to exclude react native from the actual plugin too when not compiling from source?

**Comment by mikelambert** [comment]
The documentation I am editing says to add these lines if/when you are building from source. You shouldn't be using these lines if you are not building from source, or it will exclude the react-native plugin and leave you with a react-native-less project.

**Comment by grabbou** [comment]
Up @satya164, this would be great to land! 🗡

**Comment by satya164** [comment]
Sorry I'll test it today.

**Comment by satya164** [comment]
BTW I actually do the exclude for normal modules also. Otherwise sometimes it results in duplicate libs due to bad configuration in modules. So we need to fix react-native link too.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by chirag04** [comment]
note for anyone calling react-native dep as react-native instead of `reactandroid`

if you name the project as react-native, gradle will skip react-native also.

`compile project(':react-native') ` does not work.

**Pull request closed without merging**
