### PR TITLE
updating package.json with required modules

### PR DESCRIPTION
**Pull request by akshatpaul**

### CODE REVIEW

**Comment by ide** [comment]
These modules aren't directly required. What are you trying to do here?

**Comment by akshatpaul** [comment]
without these modules npm start fails and npm install does not include all these modules

**Comment by ide** [comment]
Something is wrong with your npm then. Make sure you're using a recent version and maybe clean out your caches. I'm on v2.13.2.

**Comment by javache** [comment]
Seems like this was a configuration issue

**Pull request closed without merging**
