### PR TITLE
Improve documentation of Dimensions module

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
This includes giving a code sample and noting that window size may be different to screen size on android.

## Motivation (required)

Couldn't find any documentation about the difference.

## Test Plan (required)

Documentation change; But need to verify it looks right locally.

## Next Steps

* CLA is signed.
* Need to check code style: I followed what was in Keyboard.js's documentation comments, but maybe this isn't correct?

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Haven't time to verify the changes work locally, but they should — cloning the repo is taking way too long on my internet connection.

**Comment by wcandillon** [comment]
I would really like to see this merged 👍

**Comment by ThisIsMissEm** [comment]
No idea, it's been 6 months.

**Comment by AlanSl** [comment]
@charpeni Did this ever get imported into the documentation? The [Dimensions documentation page](https://reactnative.dev/docs/dimensions) is still rather sparse on this subject:

```
NAME | TYPE | DESCRIPTION
-- | -- | --
window | DisplayMetrics | Size of the visible Application window.
screen | DisplayMetrics | Size of the device's screen.
```

**Pull request closed without merging**
