### PR TITLE
New global property are no longer writable

### PR DESCRIPTION
**Pull request by marclaval**
Likely introduced by 9a3a082225277ff65857ac046fa09edb51702367
/cc @lexs

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @lexs and @javache to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by janicduplessis** [comment]
Thanks @marclaval, I see that there is another PR that tries to fix this problem and is getting merged atm. Let's close this one in favor of #7704.

**Pull request closed without merging**
