### PR TITLE
Webview: Fixed broken fullscreen modals due to zero body height.

### LINKED ISSUE #5211: [Android WebView] can't load url
I'm trying to load this URL `https://gitter.im/login` in my web view component, but it doesn't loads.

It just displays this:

I've tried to load it in a default android browser and it had loaded successfully.

Some code: 
```jsx
        <View style={{flex: 1}}>
          <WebView
            ref='webview'
            style={{height: 400}}
            url={'https://gitter.im/login/'}
            javaScriptEnabled={true}
            domStorageEnabled={true}
            onNavigationStateChange={this.onNavigationStateChange}
          />
        </View>
```

I'm on 0.18.0-rc.

Also tried other URLs, and it ~~works perfectly~~ works well only if there is no js. It seems like a bug with enabling javascript. 

Also tried to use `javaScriptEnabledAndroid`, but nothing was change.

### PR DESCRIPTION
**Pull request by danielbraun**
Fixes #5211

JavaScript plugins such as Fotorama are broken when attempting use its fullscreen feature.

If there's an absolute HTML element with 100% height under `<body>`, its height is 0 when rendered in the Android WebView.

This commit fixes it.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @mkonicek and @nicklockwood to be potential reviewers.

**Comment by satya164** [comment]
Does this commit also fix this issue? - https://github.com/facebook/react-native/issues/5211

**Comment by danielbraun** [comment]
@satya164 I've just tested it on my own device - Indeed, I can see the gitter login page.
Fixes #5211 as well.
Spread the word :)

**Comment by satya164** [comment]
@danielbraun awesome. will shipit as soon as the tests pass.

**Comment by satya164** [comment]
@danielbraun Hey. Sorry forgot to merge this. Now it seems that this has different changes. Can you fix it please and ping me?

**Comment by danielbraun** [comment]
@satya164 I've merged a pending pull request into my my fork, it added it to my pull request. I'll sort it out.

**Comment by danielbraun** [comment]
@satya164 I've replaced this PR with #8830

**Pull request closed without merging**
