### PR TITLE
Turned on old bridge for OSS

### PR DESCRIPTION
**Pull request by bestander**
This should revert back to using old bridge by default until we fix gradle script to build new bridge for OSS correctly

Test Plan:
- circle CI
- travis
- sandcastle

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @foghina and @ahmedre to be potential reviewers.

**Comment by bestander** [comment]
To make trunk green again I take the responsibility of approving the request.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1209301445793171/int_phab) to review.

**Pull request closed without merging**
