### PR TITLE
Fix `react-native link` issue when using multiple manifests

### PR DESCRIPTION
**Pull request by dantman**
`react-native link` often fails due to the wrong manifest being used when you use a debug manifest. `findManifest` returns `debug/AndroidManifest.xml` instead of `main/AndroidManifest.xml`. And the debug manifest usually does not have the package name defined so `projectConfigAndroid` throws a cryptic "Cannot read property 'replace' of undefined" error.

This fixes the issue by throwing a more user friendly error and providing a `manifestPath` userConfig.

This is mostly based on comments to #10050.

### CODE REVIEW

**Comment by dantman** [comment]
CC: @grabbou @lacker

**Comment by grabbou** [comment]
I believe @Kureev is the right person to look into Android diffs.

**Comment by Kureev** [comment]
@facebook-github-bot shipit

**Comment by dantman** [comment]
> Looks good to me. Just to let you know: this tool was build to facilitate fast/easy linkage for react-native inited projects in the first place. Therefore, this case was out of scope for the initial implementation. I'm pretty happy that community enhances current implementation by adding extra options to support custom Android projects.

Perhaps it's a bit off topic of a discussion, but I find it fairly strange to consider this use case custom. The whole reason I have multiple manifest files is to get rid of the `SYSTEM_ALERT_WINDOW` permission so release builds of my app aren't demanding an extremely intrusive permission.

**Comment by Kureev** [comment]
Thanks for your feedback. Probably, next time we can design it better. By the moment I wrote Android part of RNPM, I had no experience building / linking libraries for it. I'm happy that community steps in and help solving problems, relevant to other people.

Thank you for you contribution once again!

**Pull request closed without merging**
