### PR TITLE
Fix invalid package name and Remove unsupported prop in Image.android.js

### PR DESCRIPTION
**Pull request by leeight**
1. `textfrescosupport` -> `text.frescosupport`
2. `defaultImageSrc`, `imageTag` and `progressHandlerRegistered` looks like never exists in `ReactImageManager.java`

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @foghina and @rigdern to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@leeight updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9885/files/10412620262dcf4cb8a8706ffc3e87b9b561463a..0c1b97f6a3c0a7223d989fc52e184c45f9d050c0)

**Comment by facebook-github-bot-7** [comment]
@leeight updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9885/files/0c1b97f6a3c0a7223d989fc52e184c45f9d050c0..e44f9850d84ebea77d00c2b1f866310580347ff9)

**Comment by foghina** [comment]
@facebook-github-bot shipit

seems legit

**Comment by ide** [comment]
The bot doesn't like text after the shipit command for some reason.

@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3864980) to review internal test results.

**Comment by foghina** [comment]
Argh, sometimes it works. Thanks @ide.

**Pull request closed without merging**
