### PR TITLE
checkAndroid has been lost from my last PR. Here it is again

### PR DESCRIPTION
**Pull request by jreziga**
checkAndroid function has been lost from my last PR and I don't know why. That pull request add this function.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @grabbou and @burgalon to be potential reviewers.

**Comment by satya164** [comment]
Can you rebase against master please?

**Comment by facebook-github-bot-0** [comment]
@jreziga updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9448/files/c869e9220a9339ceff6cdccd390c34b12b815848..7e514c9a7f9b3f670d25056fedb4d92720c72476)

**Comment by satya164** [comment]
Seems it still has conflicts

**Comment by jreziga** [comment]
git rebase master is not enough ?

**Comment by satya164** [comment]
try git merge master

**Comment by jreziga** [comment]
already up to date :/

**Comment by satya164** [comment]
try sending a new PR with just the method maybe then?

**Comment by satya164** [comment]
btw you pulled master from the facebook's repo right? it might be uptodate with your fork's master branch.

**Comment by jreziga** [comment]
Can't create a PR anymore.

Yes I cloned from facebook's repository. Maybe if I delete my fork and then fork again facebook's master branch.

**Comment by satya164** [comment]
Yeah, try that

**Pull request closed without merging**
