### PR TITLE
Add contextMenuHidden to TextInput

### PR DESCRIPTION
**Pull request by amhinson**
## Motivation

There is currently no way to disable to tooltip that automatically appears over a TextInput. This is especially troublesome if you would like to disable the user from pasting text into certain fields. This PR adds a `tooltipHidden` property to TextInput that will hide it.

## Test Plan

I'm not sure if testing is necessary here. I would be happy to investigate further on how this would be tested, if deemed necessary!

## Release Notes

[FEATURE][TextInput] - Added `tooltipHidden` property

### CODE REVIEW

**Comment by shergin** [comment]
Well, this is not totatly correct.

**Comment by shergin** [comment]
My conserns:

 * This thing is called `context menu`, not `tooltip`;
 * I don't think that turning off all context menu actions is a good idea, we have to have more granular control of those features;
 * We have to avoid "Negative logic" in naming things;
 * We also have to implement it for multiline <TextInput>;
 * And for Android as well.

**Comment by amhinson** [comment]
@shergin Thanks for looking it over. Do you have any thoughts on how we can add more granular control? My idea would be to add an array of strings with multiple options, such as `'copy'`, `'paste'`, etc and also an `'all'` option that will remove it completely.

**Comment by amhinson** [comment]
I've updated to with the following adjustments:

- Changed name to `contextMenu` instead of `tooltip`
- Multiline & Android support

I'm not quite sure what would be the best way to add granular control of this feature (i.e. only disable "Paste", disable both "Select All" & "Paste" but still allow "Copy"). It seems the implementation for this cross-platform would be tricky.

**Comment by Noitidart** [comment]
Does iOS also offer a hidden tooltip feature?

**Comment by amhinson** [comment]
@Noitidart Yes, this PR is for both iOS and Android.

**Comment by chirag04** [comment]
throwing an idea out here: what if we allow passing custom contextual menus here. those who want to hide them could then simply pass `null`. Might be broader in scope but could help with multiple use-cases. cc @shergin

**Comment by amhinson** [comment]
@chirag04 I like the idea. One of the issues I saw though was that iOS and Android have slightly different ways they behave for this menu, so mapping them 1 for 1 might be tough. Also, the Android implementation wouldn't be quite as straight-forward as iOS, unless I'm missing something. I'm definitely not an Android expert by any means.

**Comment by amhinson** [comment]
Is there any chance we could get this reviewed?

**Comment by amhinson** [comment]
@facebook-github-bot Yes, this PR is still relevant. Just rebased.

**Comment by amhinson** [comment]
Closing this to create a new clean PR.

**Comment by AKKIDETROJA** [comment]
```
<TextInput
   **contextMenuHidden={true}**
  value={this.state.text}
onChangeText={(text) => this.setState({ text})}
/>
```

**Pull request closed without merging**
