### PR TITLE
Added activity recognition and privileged phone state permissions for Android Q

### PR DESCRIPTION
**Pull request by jeswinsimon**
## Summary

This PR is to add [ACTIVITY_RECOGNITION](https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition) and [READ_PRIVILEGED_PHONE_STATE](https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids),  the new permissions added as part of Android Q

This fixes https://github.com/facebook/react-native/issues/28231

## Changelog

[Android] [Changed] - add ACTIVITY_RECOGNITION, READ_PRIVILEGED_PHONE_STATE to PermissionsAndroid and NativePermissionsAndroid

## Test Plan

Test Plan:
```javascript
PermissionsAndroid.ACTIVITY_RECOGNITION === 'android.permission.ACTIVITY_RECOGNITION'
PermissionsAndroid.READ_PRIVILEGED_PHONE_STATE === 'android.permission.READ_PRIVILEGED_PHONE_STATE'
```

### CODE REVIEW

**Comment by vsk-pvr** [comment]
READ_PRIVILEGED_PHONE_STATE is not a run time permission that a 3rd party app can request for. Can you please remove the same?

**Comment by jeswinsimon** [comment]
> READ_PRIVILEGED_PHONE_STATE is not a run time permission that a 3rd party app can request for. Can you please remove the same?

My bad. Didn't realise that `READ_PRIVILEGED_PHONE_STATE` is only for whitelisted apps. I have changed it now.

**Comment by saudahmed** [comment]
Any take on this, this permission must be added to PermissionAndroid. It is still not there ACTIVITY_RECOGNITION

**Comment by saudahmed** [comment]
@jeswinsimon Do you know how it will become part of the react native package later. Will there be a new candidate release

**Comment by cortinico** [comment]
Closing as not needed anymore:
https://github.com/alanjhughes/react-native/blob/a2d2696e433154b030b4f5206e86d899d12a19cd/packages/react-native/Libraries/PermissionsAndroid/NativePermissionsAndroid.js#L57

**Pull request closed without merging**
