### PR TITLE
fixed a typo in the documantion

### PR DESCRIPTION
**Pull request by Giszmo**
I'm assuming in the example, each `setItem`, `mergeItem` and `getItem` are supposed to work on the same item. Made the first key clearly "same".

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @geirman and @milend to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by geirman** [comment]
@facebook-github-bot ship it

**Comment by javache** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/286942808319737/int_phab) to review.

**Comment by javache** [comment]
This was already fixed in #7770

**Comment by geirman** [comment]
Ah, so it was...  my bad for not noticing the previous PR I was clearly tagged in :)

**Pull request closed without merging**
