### PR TITLE
Put setChildren debug log in DEBUG clause

### PR DESCRIPTION
**Pull request by astreet**
Missed wrapping this previously :x

### CODE REVIEW

**Comment by astreet** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @gre and @dmmiller to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
I will not rubber stamp and land your change for you @astreet!  I can import it for you and you can get your change reviewed by someone though :)

**Comment by astreet** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/975564735874829/int_phab) to review internal test results.

**Pull request closed without merging**
