### PR TITLE
fixed website deployment condition logic

### PR DESCRIPTION
**Pull request by bestander**
Rookie mistake I made.

**Test plan (required)**

See that https://circleci.com/gh/facebook/react-native/5462 succeeds deploying the website correctly.

### CODE REVIEW

**Comment by mkonicek** [comment]
Website deployment worked but `publish-npm` failed, not sure if it's expected?
https://circleci.com/gh/facebook/react-native/5456

**Comment by bestander** [comment]
For got to push tags :)
Rebuilding

**Comment by bestander** [comment]
Passed now

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
