### PR TITLE
relativeKeyboardHeight works wrong in some cases

### PR DESCRIPTION
**Pull request by slavikmanukyan**
relativeKeyboardHeight calculation is wrong when frame.y < keyboardFrame.y

Let's look at an example: 

``` jsx
import React, { Component } from 'react';
import {
  KeyboardAvoidingView,
  TextInput,
  AppRegistry,
  Text,
  View
} from 'react-native';

export default class Test extends Component {
  constructor(props, context) {
    super(props, context);
  }

  render() {
    return (
      <View style={{flex: 1, marginTop: 20}}>
          <Text style={{ flex: 1, alignItems: 'center'}}>
            Hi! This is test.
          </Text>

          <KeyboardAvoidingView behavior={'position'} keyboardVerticalOffset={-20} >
            <TextInput
              style={{height: 40, borderColor: 'gray', borderWidth: 1}}
            />
          </KeyboardAvoidingView>
      </View>
    );
  }
}

AppRegistry.registerComponent('Test', () => Test);
```

rn-relativekb

How _relativeKeyboardHeight_ calculates position:

``` jsx
    const y1 = Math.max(frame.y, keyboardFrame.screenY - this.props.keyboardVerticalOffset);
    const y2 = Math.min(frame.y + frame.height, keyboardFrame.screenY + keyboardFrame.height - this.props.keyboardVerticalOffset);

    return Math.max(y2 - y1, 0);
```

How changed _relativeKeyboardHeight_ calculates:

``` jsx
if (frame.y > keyboardFrame.screenY) {
      return frame.y + frame.height - keyboardFrame.screenY - this.props.keyboardVerticalOffset;
    }
```

rn-rkh

Result: 
rn-relativekb1

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @nicklockwood and @davidaurelio to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
@slavikmanukyan updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@slavikmanukyan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9139/files/9113f963400f242f2005cda0e821c8d0ab7bd959..f3999d418cc00a9e25e9f30e609e05807d795879)

**Comment by facebook-github-bot-0** [comment]
@slavikmanukyan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9139/files/9113f963400f242f2005cda0e821c8d0ab7bd959..f3999d418cc00a9e25e9f30e609e05807d795879)

**Comment by facebook-github-bot-8** [comment]
@slavikmanukyan updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9139/files/f3999d418cc00a9e25e9f30e609e05807d795879..30d627d72aca79633ef389ebe349faf782dd9152)

**Comment by davidaurelio** [comment]
cc @andreicoman11

**Comment by andreicoman11** [comment]
cc @javache

**Pull request closed without merging**
