### PR TITLE
[Codegen 96-97] Extract throwIfConfigNotfound and throwIfMoreThanOneConfig from findComponentConfig function

### PR DESCRIPTION
**Pull request by AntoineDoubovetzky**
## Summary:

This PR contains tasks 96 and 97 from https://github.com/facebook/react-native/issues/34872:

>[Codegen 96 - assigned to @AntoineDoubovetzky] Create a throwIfConfigNotfound in the error-utils.js file and extract the error code from [Flow](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/components/index.js#L61-L63) and [TS](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/typescript/components/index.js#L62-L64)
 [Codegen 97 - assigned to @AntoineDoubovetzky] Create a throwIfMoreThanOneConfig in the error-utils.js file and extract the error code from [Flow](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/flow/components/index.js#L64-L66) and [TS](https://github.com/facebook/react-native/blob/main/packages/react-native-codegen/src/parsers/typescript/components/index.js#L65-L67)

## Changelog:

[Internal] [Changed] - Extract throwIfConfigNotfound and throwIfMoreThanOneConfig from findComponentConfig function

## Test Plan:

I tested using Jest and Flow commands.

### CODE REVIEW

**Review by cipolleschi — APPROVED** [review]
Great job! Thanks for these changes!

**Review by cipolleschi — CHANGES_REQUESTED** [review]
Sorry, just see right now that the CI is red. In tests, we have to use `require`, we can't use `import`

**Comment by AntoineDoubovetzky** [comment]
@cipolleschi It should be good now

**Review by cipolleschi — APPROVED** [review]

**Comment by cipolleschi** [comment]
I don't know why automatic rebase stopped working. While we work on this, could you pleas rebase manually? 🙏

**Pull request closed without merging**
