### PR TITLE
update Navigator.js to fix bug #6506

### PR DESCRIPTION
**Pull request by dragonwong**
Make sure `immediatelyRefresh` existed before call it.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
@janicduplessis would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by dragonwong** [comment]
Travis CI failed with error:

```
Examples/2048/Game2048.js:19
 19: var React = require('react-native');
                 ^^^^^^^^^^^^^^^^^^^^^^^ react-native. Required module not found
```

See [details](https://travis-ci.org/facebook/react-native/jobs/116832828), I think I have nothing to do with these errors. :dizzy_face:

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mkonicek** [comment]
Hey @dragonwong, sorry this got missed! I just merged another recent pull request that does the same.

**Comment by dragonwong** [comment]
@mkonicek, it's okay! Thanks for your work!

**Pull request closed without merging**
