### PR TITLE
Custom entry file on Xcode Release script

### PR DESCRIPTION
**Pull request by alessiodionisi**
Q: Explain the **motivation** for making this change. What existing problem does the pull request solve?
A: in my project I used the same js file on Android and iOS, so I added REACT_ENTRY to customize the js entry file name in the Release cmd.

**Test plan**

- On Build Phases > Bundle React Native code and images add REACT_ENTRY export.
screen shot 2016-07-14 at 19 26 57
```
export NODE_BINARY=node
export REACT_ENTRY=index.js
../node_modules/react-native/packager/react-native-xcode.sh
```
Tested on Simulator and iPhone

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @nathanajah and @frantic to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by alessiodionisi** [comment]
CLA Signed

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by nathanajah** [comment]
I'm not convinced that introducing a new variable is a better way to achieve code reuse, since you can just declare the app inside index.js and import it from both index.ios.js and index.android.js. 

index.js:
```
export default class App extends Component {
 ...
}
```

index.ios.js, index.android.js:
```
import App from './index';
import React from 'react';
import { AppRegistry } from 'react-native';
AppRegistry.registerComponent('App', () => app);
```

**Comment by alessiodionisi** [comment]
It could go so well, but personally I would prefer to have a single index.js. If the variable `REACT_ENTRY` is not set still uses index.ios.js.

**Comment by frantic** [comment]
Please see https://github.com/facebook/react-native/pull/7555

We started with `index.ios.js` and `index.android.js` because at that time it made a lot of sense and was emphasizing the importance of building for specific platform conventions. However, from personal experience I see that `Platform.OS` checks are used more frequently and the index files simply require one common entry file. Is it time to reconsider?

If you care about the subject, please feel free to open a new issue and or start the discussion in [React Native Community](https://www.facebook.com/groups/react.native.community/) group on FB.

**Pull request closed without merging**
