### PR TITLE
Disabled jest tests in e2e

### PR DESCRIPTION
**Pull request by bestander**
Currently too much noise is coming because of broken tests

### CODE REVIEW

**Comment by bestander** [comment]
cc @javache

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @kentaromiura to be a potential reviewer.

**Comment by davidaurelio** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3919029).

**Comment by kentaromiura** [comment]
@bestander can you provide me some more info about those "broken tests" ?
a link to some failure would be helpful.

**Comment by bestander** [comment]
Hey @kentaromiura, commits between https://github.com/facebook/react-native/commit/76c54847bba84990307906744c8b7dfe568b745e and https://github.com/facebook/react-native/commit/acdd08aef725e283cf290b4785205a7dfb181ad2 made some changes that resulted in CI tests failing https://circleci.com/gh/facebook/react-native/11446.

E2e tests pass but jest tests for e2e apps fail, @javache says there is an issue in Jest and he sent a patch to Jest.

This change just temporarily disabled jest tests in e2e to reduce noise.
We should fix all of it on Monday.

**Pull request closed without merging**
