### PR TITLE
Bump CLI to 13.5.1

### PR DESCRIPTION
**Pull request by szymonrybczak**
## Summary:

Updates CLI to v13.5.1.

## Changelog:

[GENERAL] [CHANGED] - Bump CLI to 13.5.1

## Test Plan:

CI

### CODE REVIEW

**Comment by szymonrybczak** [comment]
cc @huntie I've updated the PR with the newest version, mind looking again? 🙏

**Review by huntie — CHANGES_REQUESTED** [review]
@szymonrybczak Looks like the Yarn v3 breaking change is impacting our `test_<platform>_template` scripts in CircleCI.

- https://github.com/react-native-community/cli/pull/2134

Can you look at the changes to our CI scripts needed to support this?

cc @lunaleaps @fortmarek This may impact the `yarn test-e2e-local` script.

**Comment by szymonrybczak** [comment]
One of the [breaking change](https://github.com/yarnpkg/berry/blob/01586a88806a2bebd7edb28d1bee3581b1fd3762/CHANGELOG.md#300) of Yarn v3 was that immutable installs on CI were enabled by default, meaning when there's a new `yarn.lock` file generated it throws an error. When generating new project in `test_<platform>_template` it needs to create a `yarn.lock` so to workaround this error we need to set a `YARN_ENABLE_IMMUTABLE_INSTALLS=false` environment variable. 

CleanShot 2024-01-22 at 20 27 41
--
> cc @lunaleaps @fortmarek @cortinico @cipolleschi This may impact the yarn test-e2e-local script.

This error only applies in CI environments.

**Comment by szymonrybczak** [comment]
I see that after adding `YARN_ENABLE_IMMUTABLE_INSTALLS=false` to relevant jobs, project is properly created. But Android and iOS is not successfully building. I'm not sure is this change related to this fail 🤔

**Comment by cortinico** [comment]
@szymonrybczak the Android CI is failing because Verdaccio is not working properly (not sure why, but needs investigation). Practically what is happening is that we're pulling `@react-native/gradle-plugin@0.74.0` from NPM (this one https://www.npmjs.com/package/@react-native/gradle-plugin/v/0.74.0) rather than the one from Verdaccio.

If you SSH inside the worker you'll see this:

```
$ yarn why @react-native/gradle-plugin
├─ react-native@file:/root/react-native/build/react-native-1000.0.0-fbaad3dff.tgz::locator=AndroidTemplateProject%40workspace%3A.
│  └─ @react-native/gradle-plugin@npm:0.74.0 (via npm:0.74.0)
│
└─ react-native@file:/root/react-native/build/react-native-1000.0.0-fbaad3dff.tgz::locator=AndroidTemplateProject%40workspace%3A. [9bad8]
   └─ @react-native/gradle-plugin@npm:0.74.0 (via npm:0.74.0)
```

So it seems like with this change we're not accounting for Verdaccio anymore causing the CI to fail

**Comment by szymonrybczak** [comment]
@cortinico ah I see, thanks for checking this! So actually to make Yarn v3 working with local server, and to make it properly download packages from that server we need to pass the server destination in `.yarnrc.yml` file. I've created an option to pass custom config when initialising project with React Native Community CLI: https://github.com/react-native-community/cli/pull/2273.

**Comment by szymonrybczak** [comment]
After setting `npmRegistryServer` and `unsafeHttpWhitelist` before installing packages in project initialisation phase, all tests are passing!

**Review by huntie — APPROVED** [review]

**Pull request closed without merging**
