### PR TITLE
Update QuickStart-GettingStarted.md

### PR DESCRIPTION
**Pull request by drcallaway**
Add explicit instructions to start the Android emulator. After following the current instructions, I expected that running "react-native run-android" would automatically launch the emulator since there were no instructions indicating that this should be done manually. However, with no emulator running, I'd get "No connected devices!" errors. Simply starting the stock emulator before launching my app fixes this problem.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @willfong to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by JoelMarcey** [comment]
@drcallaway this will need to be rebased on top of the work that @hramos did to simplify the getting started. And given his work, I think this may now be better in the troubleshooting sections of the docs.

What do you think @hramos?

**Comment by hramos** [comment]
I agree, this would be a better fit in Troubleshooting.

**Comment by facebook-github-bot-7** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @JoelMarcey as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by JoelMarcey** [comment]
This needs a rebase and a move to `Troubleshooting`. Might be better to start a new PR, possibly and close this one out. Up to you @drcallaway. Thanks.

**Comment by mkonicek** [comment]
@drcallaway I'm going through all pull requests and noticed this one hasn't been updated in a while and the last comment requests changes. I'll close this pull request so it doesn't stay open indefinitely but please send a new one if you want to continue working on this.

**Pull request closed without merging**
