### PR TITLE
[Website] Split Showcase and add mini-Showcase to homepage

### PR DESCRIPTION
**Pull request by hramos**
We're revamping the Showcase, and in this first PR we're focusing on two things:

1. We're splitting the list of featured apps. Those in the "pinned" list will be fairly static and PRs that add/remove apps from this list will be discouraged. Apps in the "featured" list will be held to the same standards established this past summer (funded startup or public company + engineering blog post on RN / news article from established company).

2. We're displaying the pinned apps in a small showcase at the bottom of the homepage.

Note that pinned and featured apps are displayed together in the main showcase without any separation. Pinned apps will appear first in an arbitrary order, followed by featured apps in alphabetical order. Future PRs may address how apps are displayed in the main Showcase itself.

We want to also make sure people understand some of these apps are not built entirely using React Native. Some apps are native apps with individual RN views added in.

Full Showcase with pinned apps + featured apps:
screencapture-localhost-8079-react-native-showcase-html-1475605248826

Mini-showcase on the homepage:
screencapture-localhost-8079-react-native-index-html-1475605239150

### CODE REVIEW

**Comment by hramos** [comment]
cc @lacker, @skevy, @brentvatne, @lelandrichardson

**Comment by lelandrichardson** [comment]
@hramos if you'd like to use Airbnb on the "who's using React Native" page, i've gotten approval. You can use this Icon image: https://a2.muscache.com/airbnb/static/icons/apple-touch-icon-180x180-bcbe0e3960cd084eb8eaf1353cf3c730.png

**Comment by hramos** [comment]
@lelandrichardson great, I'll go ahead and add it. Do you have any preference on what the icon should link to? It looks like https://www.airbnb.com/mobile might work.

**Comment by lelandrichardson** [comment]
@hramos that works for me!

**Comment by hramos** [comment]
Added Airbnb. We're still missing infoLinks for Instagram and Airbnb, but we can make an exception since these apps will be pinned to the homepage.

**Comment by lelandrichardson** [comment]
@hramos it's not the greatest infolink, but you could use this potentially: https://www.youtube.com/watch?v=tUfgQtmG3R0

**Comment by hramos** [comment]
Works for me

**Comment by lacker** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
Waiting on the internal diff to land...

**Pull request closed without merging**
