### PR TITLE
Add AADPS to the showcase

### PR DESCRIPTION
**Pull request by zipspeed**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by zipspeed** [comment]
Already signed the CLA, but the label does not show up.

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-9** [comment]
@zipspeed updated the pull request.

**Comment by lacker** [comment]
Hey, I'm really sorry for the churn, but we are changing up how the showcase works, and just focusing on apps that have some media presence or technical blog posts / other content. So I appreciate the spirit behind this pull request but I think we should close it.

**Comment by zipspeed** [comment]
@lacker It is Okay. I was hesitating to publish my post for I would advise against using the framework. Now I don't have anything to worry about. https://zhuanlan.zhihu.com/p/21411171

**Comment by lacker** [comment]
Well I'm sorry to hear that. We are working on making navigation easier to use, though, so hopefully you'll be open to taking another look in the future sometime....

**Pull request closed without merging**
