### PR TITLE
convert: add renderingMode for Image

### PR DESCRIPTION
**Pull request by yorkie**
Added this because sometimes wanna disable tint color at `TabBarItem`, thanks :-)

/cc @ide

### CODE REVIEW

**Comment by yorkie** [comment]
I will sign in cla at next Monday just because I'm in traveling where the network is not able to connect to Facebook, sorry :-(

**Comment by brentvatne** [comment]
> Added this because sometimes wanna disable tint color at `TabBarItem`

Interesting -- could you not just nullify the tintColor prop? Very curious about this use case, could you explain in more detail? :) Thanks!

**Comment by yorkie** [comment]
@brentvatne like colorful icon, tintColor will disable this, right?

**Comment by ide** [comment]
Does this compile? Where is renderingModeStr defined?

**Comment by yorkie** [comment]
Sorry, this is copy from the code compiled in my project, I guess I missed that and now updated :-)

**Comment by yorkie** [comment]
Signed CLA :-)

**Comment by yorkie** [comment]
> could you not just nullify the tintColor prop?

@brentvatne do you mean nullify `tintColor` of `TabBarIOS`?

**Comment by yorkie** [comment]
Any update?

**Comment by mkonicek** [comment]
> do you mean nullify tintColor of TabBarIOS?

Yes.

**Comment by mkonicek** [comment]
Hey @yorkie! Thanks for making the pull request, but we are closing it due to inactivity to make sure all pull requests are either being worked on or closed. If you want to get your proposed changes merged, please rebase your branch with master and send a new pull request :)

Closing based on no reply to the comment from November:

> Very curious about this use case, could you explain in more detail?

**Pull request closed without merging**
