### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by lucasfeliciano**
Broken link on docs

### CODE REVIEW

**Comment by corbt** [comment]
@lucasfeliciano I see that that link is in fact broken. You've tested that this change causes the link in the generated pages to go to the right place?

**Comment by lucasfeliciano** [comment]
@corbt not really.
What are your instructions to test it?

**Comment by grabbou** [comment]
That should be `docs/` instead of `./` because of base url. You can check that by visiting docs and playing around with `href` property with dev tools. Once updated, ping me and I'll ship it.

**Comment by lucasfeliciano** [comment]
@grabbou it is done :+1:

**Comment by grabbou** [comment]
@facebook-github-bot shipit

**Comment by lucasfeliciano** [comment]
@grabbou do you know why this was closed?

**Comment by terrysahaidak** [comment]
@lucasfeliciano because of this
https://github.com/facebook/react-native/commit/170f4526f567b40245e75386df5f303085b32ac5

**Comment by lucasfeliciano** [comment]
I see.

Thanks for enlighten me :)

**Comment by grabbou** [comment]
Yeah, it's how merging works in FB projects :)

**Pull request closed without merging**
