### PR TITLE
Fix THUMBNAILS to follow the require Syntax

### PR DESCRIPTION
**Pull request by bozzmob**
The THUMB_URLS is following the older syntax.
Fixed THUMBNAILS to follows require Syntax. And now you see the thumbnails appearing in the Sample app.

### CODE REVIEW

**Comment by bozzmob** [comment]
I am the reviewer to my own commit? ;) That would be great! ;) @vjeux @satya164

**Comment by satya164** [comment]
Hey. Thanks for the PR. There seems to be an extra file added - Examples/UIExplorer/Thumbnails/liking.png~HEAD

Can you remove it?

**Comment by satya164** [comment]
@bozzmob **"Potential"** reviewer :D

**Comment by bozzmob** [comment]
@satya164 Done! :) He he :D Yeah! Potential reviewer ;)

**Comment by nicklockwood** [comment]
I'm curious why all the image files are marked as updated, even though they don't appear to have changed?

**Comment by satya164** [comment]
@nicklockwood Their colors seem to have changed a bit. It's visible in the one with flowers.

**Comment by bozzmob** [comment]
@satya164 @nicklockwood Yeah, not sure why the images happening, but, I think that's ok. I am the one who committed those image to this repo :) Initial fix was done by me in an older issue #2425 .

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by nicklockwood** [comment]
@bozzmob I think it's because I ran pngcrush on them after importing (it's required by our internal linter).

**Comment by satya164** [comment]
@nicklockwood Yeah, but that still doesn't explain how the images changed on @bozzmob 's machine!

**Comment by ide** [comment]
@bozzmob can you remove the PNGs from your commit?

**Comment by nicklockwood** [comment]
@ide don't worry. It failed to land anyway due to a (possibly spurious) flow error. I'll strip the images and try to re-land it.

**Comment by nicklockwood** [comment]
@satya164 I'm assuming he still had the original un-crushed versions.

**Pull request closed without merging**
