### PR TITLE
Fix: set underlineColorAndroid properly

### LINKED ISSUE #6332: [Android] underlineColorAndroid somehow applies globally to all TextInput components
I have a component in search.js. Something like this-

```
<TextInput 
    placeholder={'Search keyword'}
    placeholderTextColor={'#cccccc'}
    style={styles.input}
    autoCapitalize={'none'}
    autoFocus={true}
    underlineColorAndroid={'#cccccc'}
>
</TextInput>

```

The style for given TextInput is this-

```
input: {
    padding: 5,
    height: 45,
    fontSize: 16,
    color: '#111111',
    marginBottom: 20,
    borderWidth: 1,
  },
```

screenshot from 2016-03-07 10 57 13

I have another TextInput placed in my sign-in page. 

```
<TextInput 
    style={styles.input} 
    value={this.state.username} 
    onChangeText={(text) => this.setState({username: text, error: ''})}
    autoCapitalize={'none'} 
    autoCorrect={false} 
    returnKeyType='next' 
    keyboardType={'email-address'}
>
</TextInput>
```

Style-

```

input: {
        padding: 4,
        height: 45,
        fontSize: 22,
        color: '#ffffff',
        marginBottom: 20,
        borderWidth: 1,
        textAlign: 'center'
    },
```

screenshot from 2016-03-07 11 01 59

Why is underlineColorAndroid={'#cccccc'} from first TextInput is being applied to the second TextInput? Am I doing something wrong? Or is this a legitimate issue?

### PR DESCRIPTION
**Pull request by Swordsman-Inaction**
This PR fixes #6332 

The issue is that Android Framework will return the same drawable instance for all requests if they request for the same resource. So the changes on the drawable instance will affect all users(`TextInput` in this case). The solution is very easy, call `mutate()` before change it will get a new drawable instance which make sure the change doesn't affect other users.

### CODE REVIEW

**Comment by Swordsman-Inaction** [comment]
Is this good to merge?

**Comment by janicduplessis** [comment]
Seems like a good fix, text inputs will consume a bit more memory since they will all have a different background drawable but it should be negligible.

@astreet are you fine with this change?

**Comment by astreet** [comment]
Seems fine to me, we only would be creating a new drawable when a color is actually set.

**Comment by astreet** [comment]
Unfortunately, I've had to unland this diff as we're hitting the AOSP bug described here: https://code.google.com/p/android/issues/detail?id=191754

**Comment by astreet** [comment]
(AFAICT, it looks like just checking if `getConstantState` returns null, which inherently means `canConstantState` returned false, and not calling mutate in that case would fix this)

**Comment by Swordsman-Inaction** [comment]
Cool, good to know that. Will you fix this? @astreet

**Comment by astreet** [comment]
Yeah, I'm putting up a fix for it

**Pull request closed without merging**
