### PR TITLE
export type ButtonsArray for external use

### PR DESCRIPTION
**Pull request by lprhodes**
Enable the use the ButtonsArray by flowtype in projects that make use of react-native

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @corbt to be potential reviewers.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
@lprhodes updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9475/files/a5d89fd6eed5892e4eaf989c46a29be65c25cc5b..3ec2420db874f67e5a602f0926419db4ed017dc8)

**Comment by mkonicek** [comment]
> Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

Can you please explain why you'd use them and how? A good way is a good sample.

**Comment by lprhodes** [comment]
Sure, we have a convenience method for showing alerts in our iOS RN app where we can optionally provide buttons (of type ButtonsArray)

```
type ShowAlertProps = {
  title?: string,
  message: string,
  buttons?: ButtonsArray
}

export const showAlert = function (props: ShowAlertProps) {
  let { title, message, buttons } = props

  if (!title) title = 'Some Default Title'

  if (!buttons) buttons = [ { text: 'OK' } ]

  AlertIOS.alert(
    title,
    message,
    buttons
  )
}
```

**Comment by lacker** [comment]
This change looks good to me, can you resolve the merge conflict though?

**Comment by hramos** [comment]
Ping @lprhodes, we can ship once the conflict is resolved.

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
I will be able to merge this once the conflicts are resolved. I am not sure why this can't be done automatically.

**Comment by shergin** [comment]
Okay... I will merge it manually.

**Comment by shergin** [comment]
Was fixed in 4e437c1232771f1bce90340cc2ecd1deb0c90278.

**Pull request closed without merging**
