### PR TITLE
[Docs] Updates to Text & IntentAndroid

### PR DESCRIPTION
**Pull request by christopherdro**

### CODE REVIEW

**Comment by christopherdro** [comment]
@satya164 @mkonicek You guys ok with the addition to the IntentAndroid doc?

**Comment by satya164** [comment]
LGTM

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by christopherdro** [comment]
@mkonicek Not sure whats going on here. I didn't do anything.

**Comment by satya164** [comment]
Don't lie @christopherdro , the bot watches everything ;p

**Pull request closed without merging**
