### PR TITLE
[packager] try catch requires to check for deps

### LINKED ISSUE #1758: [Packager] Packager does not start after upgrading to NPM 3.0 beta
After upgrading to NPM 3.0 beta (https://github.com/npm/npm/releases/tag/v3.0.0), I re-installed the `node_modules` through `npm install` in my React Native project. Everything showed up in the file system, but after calling `npm start` I get the error:
```
Could not find dependencies.
Ensure dependencies are installed - run 'npm install' from project root.
```
No matter how often I call `npm install` and `npm start`, the error persists.
This happens for me with both `0.6.0` and `0.7.0-rc`.

### PR DESCRIPTION
**Pull request by eddiemonge**
Instead of checking for `node_modules`, which can be in a different place, try `require`ing the deps and catch if they aren't available then throw the install message

Fixes #1758 hopefully

### CODE REVIEW

**Comment by eddiemonge** [comment]
implemented differently in https://github.com/facebook/react-native/commit/daba14264c9f0d29c0327440df25d81c2f58316c

**Comment by grabbou** [comment]
@martinbigio what's the status on this one? Looks like referenced issue has been closed already.

**Comment by facebook-github-bot-0** [comment]
@AaaChiuuu would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by grabbou** [comment]
cc: @mkonicek have you thought about letting bot mention people that are assigned to PRs?

**Comment by martinbigio** [comment]
I don't recall why we decided to remove the node_modules dir check :/...

**Comment by mkonicek** [comment]
> implemented differently in daba142

Based on that comment let's close this PR. @eddiemonge do you agree?

**Comment by mkonicek** [comment]
@grabbou The bot mentions people based on blame info but indeed it should mention the person this is assigned to, or the person who commented the most. I disabled that bot until we find time to fix it.

**Comment by eddiemonge** [comment]
Yeah the code has completely changed. I still see a couple of places that are looking for node_modules specifically instead of just trying to require them or at least using npm get prefix option

**Pull request closed without merging**
