### PR TITLE
add "烘焙帮" case

### PR DESCRIPTION
**Pull request by everfire130**
add "烘焙帮" case

### CODE REVIEW

**Comment by bestander** [comment]
yum :)

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by everfire130** [comment]
@bestander Closed with unmerged commits/(ㄒoㄒ)/~~

**Comment by bestander** [comment]
Our merge strategy is a bit complex, we don't merge PR directly, we use scripts to patch internal source of Facebook and then another scripts patches master branch at github.
This commit seems to be merged in master branch and your attribution remains.
Anything  wrong?

**Comment by everfire130** [comment]
@bestander Soga!Should I pull a request again?

**Comment by bestander** [comment]
@everfire130 it got merged fine https://github.com/facebook/react-native/blob/master/website/src/react-native/showcase.js#L620

Keep in mind that website updates not immediately.
It will be there when 0.21 branch becomes stable.

**Pull request closed without merging**
