### PR TITLE
Initial implementation of WebSockets on Android

### PR DESCRIPTION
**Pull request by puf**
This implementation uses the okhttp web socket library that is already
used by the debug bridge.

It was tested with the Firebase library that also works with React
Native for iOS.

Fixes https://github.com/facebook/react-native/issues/2837, but without introducing a new dependency.

### CODE REVIEW

**Comment by satya164** [comment]
Hi. Awesome. Just to let you know, I also updated my pull request. There are some notable changes from your pull request,

* `onMessage` will print the IOException instead of throwing it to avoid crash
* Pass "reason" on close event, to be closer to the spec, there is a `wasClean` property in the spec also, but didn't seem to exist in okhttp-ws
* On failure event, data is not passed in the event object
* While closing, the code is specified as "1000" (CLOSE_NORMAL) and reason as "" instead of "unknown"

**Comment by puf** [comment]
Great stuff Satya! I don't mind which one gets merged in, as long as people can start building Firebase apps for Android with React Native soon. :-)

**Comment by satya164** [comment]
@puf Yup, I also need it in an app I'm working on. Right now using a custom react module. :)

**Comment by owais** [comment]
> Right now using a custom react module. :)

@satya164 which one?

**Comment by puf** [comment]
@owais Custom = self-made. Take the code for `WebSocket.android.js` and `WebSocketModule.java` from this (or @satya164 's) PR and create a custom package, like this:

```
public class AwesomeReactPackage implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();

        modules.add(new WebSocketModule(reactContext));

        return modules;
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}
```

Register that package in the MainActivity, like this:

```
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new AwesomeReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
```
Run the Android app and it'll use your new, custom WebSocket module.

**Comment by ide** [comment]
Closing this since WebSockets have landed in master.

**Pull request closed without merging**
