### PR TITLE
Fixes capitalized I's when emojiis are present after the text being edited.

### LINKED ISSUE #20908: TextInput capitalized all letter i's when there's an emoji before the text
- [x ] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 705.27 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v9.11.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.0, 27.0.3, 28.0.0
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
TextInput capitalizes all letter I's within words when there's an emoji to the left of the characters and you are editing in the middle of a sentence. 

See #19389 for more context

## Reproducible Demo
When you have an emoji as the last character of your text input and then move the text cursor back (still with emoji as last character) and enter new letters somewhere in the middle of the string. It only capitalizes the letter i.  This also happens if you start your text with an emoji, then type some words, then go back in and start editing text; all i's will be capitalized, even in the middle of words.

### LINKED ISSUE #21243: [IOS] TextInput with emojis capitalizes text and causes other issues
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.1
  Yarn: 1.9.4
  npm: 5.8.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.5.0 => 16.5.0
  react-native: 0.57.0 => 0.57.0

## Description
On IOS, adding emojis to TextInput causes the following:

- Text goes capital. Caps must be turned off every time you press a letter.
- Auto correct suggestions don't work.
- When adding newlines and emoji moves out of view, cursor gets scrolled to top of TextInput
- Removing emojis fixes it.

Works in RN0.53.

Started breaking in RN0.54 and still breaks in RN0.57.

RN0.57 has a bug that breaks the RN build. To test on RN0.57, apply this manual fix when the build fails the first time: https://github.com/facebook/react-native/issues/21071#issuecomment-420648890

## Reproducible Demo
See snack here:
https://snack.expo.io/@superandrew213/textinput-emoji-bug

Test on device and not on appetize/browser.

screenrecording_09-21-2018 19-44-21

## Related Issues
https://github.com/facebook/react-native/issues/19389, https://github.com/facebook/react-native/issues/20908, https://github.com/wix/react-native-autogrow-textinput/issues/47

### PR DESCRIPTION
**Pull request by dchersey**
Fixes #21243. 
Fixes #20908.

Credit goes to @superandrew213 who provided the patch based on 0.56; this commit merges and resolved the conflict introduced in 0.57.

Test Plan:
----------
When you have an emoji as the last character of your text input and then move the text cursor back (still with emoji as last character) and enter new letters somewhere in the middle of the string, the TextInput begins to capitalize all letter I's without this PR. 

Without this PR in place: 
1. Create a TextInput on a View
2. Run it on IOS in development or release build in a simulator or on a device
3. Type "Test with emoji 😃"
4. Move the curser back before the emojii
5. Type "edited".  The text will appear as "edIted".
6. Apply this PR
7. Run it again
8. Type "Test with emoji 😃" 
9. Move the curser back before the emojii
10. Type "edited".  The text will now appear as "edited".

Release Notes:
--------------
Help reviewers and the release process by writing your own release notes. See below for an example.

[IOS] [BUGFIX] [TextInput] - Fixes bug where letter I's are permanently capitalized when editing text that appears before emojiis

### CODE REVIEW

**Comment by dchersey** [comment]
I'm game @matthargett -- haven't contributed to RN before.  I looked through the docs and it looks like I need to update RNTester to test for my case (edited text with emojis)... before doing this I thought I would run the existing tests.  I managed to run RNTester in the simulator but I can't find any doc on running the actual tests that verify the examples.   Tried running `scripts/test-manual-e2e.sh ` but it failed on the android setup (my changes don't affect android so I don't need to solve this) and `scripts/objc-test-ios.sh` which built something successfully but did not run any tests AFAIK. 

Can you point me in the direction?

**Comment by dchersey** [comment]
@matthargett I'm game to do so; I've been able to build and run RNTester and I see the TextInputExample ... I guess I just need to add an example showing my emojii bug & testing the fix.

This is my first contribution to RN and I haven't been able to figure out how to actually add the test ... the doc is not super-helpful unfortunately.   Can you point me in a direction?

**Comment by mikefogg** [comment]
Hey guys, any update on getting this fix in there?

**Comment by matthargett** [comment]
I tried extending the current RNTester e2e tests to exercise things in this way, but had some trouble once the keyboard changes locales. GOing to mark this as approve and follow up with other folks. Thanks!

**Comment by kelset** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
