### PR TITLE
Remove legacy integration of createPerformanceLogger with Systrace

### PR DESCRIPTION
**Pull request by rubennorte**
Summary: Changelog: [internal]

Differential Revision: D61885705

### CODE REVIEW

**Comment by abhaywit** [comment]
hi @rubennorte what was the rationale for this change? thanks!

**Comment by rubennorte** [comment]
> hi @rubennorte what was the rationale for this change? thanks!

This is an internal API in React Native and it was logging too much data to Systrace in the current use cases that we had. We'll probably remove this API altogether as it's not used within React Native itself and it's not public.

**Comment by abhaywit** [comment]
> > hi @rubennorte what was the rationale for this change? thanks!
> 
> This is an internal API in React Native and it was logging too much data to Systrace in the current use cases that we had. We'll probably remove this API altogether as it's not used within React Native itself and it's not public.

@rubennorte Thanks for the response. Are the use cases that relied on these traces still relevant at Meta? If so, out of curiosity, how are those needs being addressed after this change?

For context, we used these traces to determine the number and duration of network calls during app startup, and used that data to help app developers reduce startup latency caused by excessive network requests on launch. 

Thanks.

**Comment by rubennorte** [comment]
> For context, we used these traces to determine the number and duration of network calls during app startup, and used that data to help app developers reduce startup latency caused by excessive network requests on launch.
> 
> Thanks.

@abhaywit I would recommend using the new Web performance APIs released as stable in 0.83 (https://reactnative.dev/blog/2025/12/10/react-native-0.83#web-performance-apis-as-stable).

**Pull request closed without merging**
