### PR TITLE
[TicTacToe] Fix missing image styles for TicTacToe example

### PR DESCRIPTION
**Pull request by rustyconover**
Without a width or height set for the X or O image they don't appear, fix this problem by adding styles with width and height specified.

### CODE REVIEW

**Comment by nicklockwood** [comment]
@frantic should this be using the require(image!xxx) syntax for images instead? That way, we get the size set automatically, right?

**Comment by rustyconover** [comment]
Isn't that only for Xcode bundled images?

**Comment by nicklockwood** [comment]
Oh right, these are remote images. Sorry, then yes, this is fine.

**Comment by a2** [comment]
We should probably stop using these remote images. :laughing:

**Comment by brentvatne** [comment]
@rustyconover - could you update this PR to load the images from `Images.xcassets` instead?

**Comment by sahrens** [comment]
FYI: we're deprecated the automatic style from require(image!... magic so please don't use it going forward ;)

**Comment by sahrens** [comment]
@facebook-github-bot import

**Pull request closed without merging**
