### PR TITLE
fix some lint warnings

### PR DESCRIPTION
**Pull request by chirag04**
partially fixes https://github.com/facebook/react-native/issues/3316

cc @ide

### CODE REVIEW

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Thanks!

**Comment by javache** [comment]
There's some conflicts when applying this to master. Could you rebase your PR?

**Comment by brentvatne** [comment]
@chirag04 - rebase please! :smile:

**Comment by chirag04** [comment]
Sorry for the delay. I should have it rebased today.

**Comment by brentvatne** [comment]
@chirag04 - ping in case you forgot

**Comment by chirag04** [comment]
I will close this and hopefully put a new one after lrnapp's v1.3 release is done or somebody else beats me at it :)

**Pull request closed without merging**
