### PR TITLE
Add react check

### PR DESCRIPTION
**Pull request by sunnylqm**
Add check for react, to prompt people to install/reinstall the right react version.
qq20161212-0

### CODE REVIEW

**Comment by sunnylqm** [comment]
ping @mkonicek

**Comment by lacker** [comment]
I'm concerned that the value of this feature may not be worth the complexity cost of the extra code. How do you get yourself in this situation? Just if you manually remove your copy of react? Having the wrong version of a dependency seems like something we can't necessarily fix in the CLI for all dependencies. And this problem seems like it is the same for any peer dependency, and npm has a particular way of handling peer dependencies, so perhaps it's reasonable to just operate the same way as npm and not have this sort of feature.

**Comment by sunnylqm** [comment]
@lacker When integrating with native app, for example. Or upgrading from legacy projects, etc. I am doing some consulting work, and lots of people asked about the react version problem.

**Comment by lacker** [comment]
Is this different from the general problem of, what happens when you have an npm peer dependency defined, but for some reason you have installed the wrong version of the peer dependency? It seems like some npm command should debug this rather than react-native -v.

**Comment by sunnylqm** [comment]
@lacker  People unfamiliar with npm things would ignore all the warnings, and most of the time things went well. But rn with mismatched react or without react would cause error, and there is no clue for them at all. 
AND doesn't it look neat to have all the react-things listed together?:lol

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/add-react-check

**Pull request closed without merging**
