### PR TITLE
[IOS] Text replacement by dot after 2 spaces

### PR DESCRIPTION
**Pull request by gedu**
## Summary:

Pre-requisite: 
- Ensure that the option "." Shortcut" is enabled in Settings->Keyboard.

This PR addresses several issues:

When using TextInput in an uncontrolled manner, without using the value prop, after entering a letter or word and double-tapping the spacebar, it should now correctly add a "." at the end of the letter or word.
When using TextInput in an uncontrolled manner, without using the value prop, after entering certain letters for text replacement, such as "omw" or "@@" (previously created), it now produces the expected replacements.

Motivation:

From Expensify app: https://github.com/Expensify/App/issues/17153
From discussion on: https://github.com/facebook/react-native/issues/27693

## Changelog:

[IOS][FIXED] - For uncontrolled TextInput: Double tapping space should add "." and Text Replacement for special characters

## Test Plan:

TextInput:

### "." shortcut

Pre-requisite: 
- Ensure that the option "." Shortcut" is enabled in Settings->Keyboard.

- Using the `onChangeText` and the `value` props to set new values: 
     -  Writing a letter: like `E` then tapping the space 2 times, you should see `E. `
     - Writing a word: like `Test` then tapping the space 2 times, you should see `Test. `
     
### Text Replacement
Pre-requisite: 
- Create a new Text Replacement inside of Settings -> Keyboard, using symbols: like `@@` -> `test@test.com`

- Using the `onChangeText` and the `value` props to set new values: 
     -  Writing the symbol created:  `@@` should be selected and clicking space, the `@@` should be replaced by `test@test.com`

https://github.com/facebook/react-native/assets/1676818/22941057-9ac5-49f3-b469-66880b71e596

### CODE REVIEW

**Comment by javache** [comment]
Could you provide an integration test that demonstrates how this interacts with UIKit? This piece of code is quite complex, and already has to do quite a bit of complex state management (eg see `_comingFromJS`)

Not updating the attributed string may cause issues if the text completion causes the text input to have to grow over multiple lines.

**Comment by gedu** [comment]
@javache Hey, yes I can, is there something already in place for TextInput?

**Comment by javache** [comment]
Unfortunately, I don't think we have any in place right now. You could look at adding them here: https://github.com/facebook/react-native/tree/main/packages/rn-tester/RNTesterIntegrationTests (but this may need some work to support the new architecture). You could also try an [rn-tester-e2e test](https://github.com/facebook/react-native/blob/main/packages/rn-tester-e2e/README.md).

**Comment by gedu** [comment]
I will try to work on this beginning next week

**Comment by gedu** [comment]
I ran into some issues when updating `main`, next week I will start adding the test under rn-tester-e2e

**Comment by gedu** [comment]
Ok could set the first test, and is working, will keep adding more, and will try to add as much as I can.

Testing `RewriteExample` 
```
input: test space replace
output: test_space_replace
```
Screenshot 2023-09-29 at 17 13 25

**Comment by gedu** [comment]
During my testing. I observed that whenever I attempted to set a text, the second and third characters were getting cropped.

https://github.com/facebook/react-native/assets/1676818/ff1da81f-6b43-467c-bbf0-cf51a3d56520

So then I applied my fix on the Native realm (I wanted to make sure that all was working before my fix, but I couldn't make it work)


https://github.com/facebook/react-native/assets/1676818/babecaf3-5fde-4229-b14a-879e64ef3790


And it seems that it is working after running many times the tests


Screenshot 2023-10-04 at 20 13 30

**Comment by gedu** [comment]
I updated my local and seems there were many changes and I need to find a new way to fix this issue, given that seems that isn't working now

**Comment by gedu** [comment]
Ok I could find the fix, seems that wasn't a big change after all, but only will work for fabric, but I'm double checking. Now I'm working on the testings

**Comment by gedu** [comment]
The integration tests are working on Android, but on iOS getting the text from the Input isn't working. I can add text but later I can't get it back from the Input. Looking into that

**Comment by gedu** [comment]
@javache I added some tests. What do you think?

rn_test_ios
rn_tests_android
Screenshot 2024-01-03 at 21 14 19

**Comment by gedu** [comment]
@javache friendly ping

**Comment by gedu** [comment]
@javache did you have a chance to look at this?

**Comment by zwilderrr** [comment]
hey team - can you merge? would love to get this in my app

**Comment by gedu** [comment]
@javache can you take a look at this or ping someone that can help us to review this PR?

**Comment by gedu** [comment]
I will fix the conflict soon

**Comment by zwilderrr** [comment]
Thanks!!!

**Comment by javache** [comment]
Apologies for the delay here, and thank you for adding the test!!

Synchronizing state between JS and native is a really complex part of React Native and introducing new variables like `_stateUpdated` add additional complexity there. I'd love to see a more scoped fix with detailed explanation of how `updateState` ends-up becoming re-entrant.

The right fix is probably not in bailing out early inside `updateState`, but in whatever callback gets fired that triggers the re-entrant state update. This is already what `_comingFromJS` means ("delegate methods `textInputDidChange` and `textInputDidChangeSelection` will exit early"). Can we leverage that instead?

**Comment by gedu** [comment]
@javache I found the e2e tests were removed, I will remove them from here too: https://github.com/facebook/react-native/pull/45032

> I'd love to see a more scoped fix with detailed explanation of how updateState ends-up becoming re-entrant.

Yeah, I would have to dig again to remember the exact flow.
The main issue is multiple calls and flow are happen almost at the same time and sometimes in different orders (depending if the change/update is for a controlled or uncontrolled TextInput)
I will look into so I can refresh my memory

**Comment by gedu** [comment]
@javache Looking a bit deeper I found something in the `_setAttributedString` when using `_textOf` when using the `value` and `onChangeText` (controlled component) the if condition was false, so it was processing the text in another way. I saw that
newText was
```
A{
    NSBackgroundColor = "UIExtendedSRGBColorSpace 0 0 0 0";
    NSColor = "UIExtendedSRGBColorSpace 0 0 0 1";
    NSFont = "<UICTFont: 0x165124130> font-family: \".SFUI-Regular\"; font-weight: normal; font-style: normal; font-size: 13.00pt";
}
```
oldText
```
A{
    NSBackgroundColor = "UIExtendedSRGBColorSpace 0 0 0 0";
    NSColor = "UIExtendedSRGBColorSpace 0 0 0 1";
    NSFont = "<UICTFont: 0x165124130> font-family: \".SFUI-Regular\"; font-weight: normal; font-style: normal; font-size: 13.00pt";
    NSParagraphStyle = "Alignment 4, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 4, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection 0, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0 LineBreakStrategy 65535 PresentationIntents (\n) ListIntentOrdinal 0 CodeBlockIntentLanguageHint '(null)'";
    NSShadow = "NSShadow {0, -1} color = {(null)}";
}
```
when not using the `value` and `onChangeText` (uncontrolled component) those newText and oldText were the same.
so I saw that `RCTNSAttributedStringFromAttributedStringBox` was doing a copy of the attributes, the one that does the copy is `RCTNSTextAttributesFromTextAttributes` and it check if the attributes exists if it exist it copy it, in the case of controlled component those attributes are missing, so nothing is copied and when the `_textOf` checks it fails. 
What I did is after checking all the attributes are default values before returning the copy:
```
 NSMutableAttributedString *mutableAttributedString = [[NSMutableAttributedString alloc]
        initWithString:string
            attributes:RCTNSTextAttributesFromTextAttributes(fragment.textAttributes)];
      // Apply default attributes if they're missing
    NSDictionary<NSAttributedStringKey, id> *defaultAttributes = RCTDefaultTextAttributes();
    for (NSAttributedStringKey key in defaultAttributes) {
      if (![mutableAttributedString attribute:key atIndex:0 effectiveRange:NULL]) {
        [mutableAttributedString addAttribute:key value:defaultAttributes[key] range:NSMakeRange(0, mutableAttributedString.length)];
      }
    }   
    return mutableAttributedString; 
```
That way it works. This way I don't have to add the new flag

What do you think?

https://github.com/facebook/react-native/assets/1676818/175047d2-306c-47d3-a310-da02f642c3ab

**Comment by gedu** [comment]
@javache did you have time to look into the new proposal?

**Comment by gedu** [comment]
@javache friendly ping

**Comment by gedu** [comment]
Does the new proposal makes sense? Looks good?

**Comment by gedu** [comment]
@javache can you take a look at my new proposal, I'm not using a new flag

**Comment by gedu** [comment]
Once my proposal is approved, I'll dedicate time to fixing the conflicts and getting everything sorted

**Comment by javache** [comment]
Thanks for the ping. I'll try to find an owner to help review this internally, as it may be related to other auto-correct issues we've been seeing.

**Comment by gedu** [comment]
@javache Awesome, thanks, I pushed the code without the flag and just adding the missing fields, I think I need to clean up a bit more the code

**Review by NickGerleman — CHANGES_REQUESTED** [review]
I suspect https://github.com/facebook/react-native/pull/46970 will fix this

In that change, I tried to avoid filling in specific attributes like this, since their presence is an implementation detail of `UITextField` that may change in the future (and I'm not sure that `UITextView` and others would even have the same). `Text` (non-input) we probably don't want these either. Comparison insensitive to default typing attributes helps make this more robust for the future (or... other inputs), but was something we are still planning to add UI tests for internally to catch in future iOS updates if they break things.

`NSParagraphStyle` after auto-correction in backing input will also change to non-default version, and alignment and writing direction will resolve from natural to either left or right depending on locale, so this fix would not work as user continues to type.

When I was looking at this, we also had different `EventEmitter` attributes often, which we handle now in `RCTTextInputComponentView`, but is part of the same class of issue.

**Comment by gedu** [comment]
Closing this PR in favor of https://github.com/facebook/react-native/pull/46970

**Pull request closed without merging**
