### PR TITLE
Add 'Collegiate - Learn Anywhere' to the showcase

### PR DESCRIPTION
**Pull request by gauravsapiens**
Added Collegiate, an app that lets you learn from world's best colleges for free. Collegiate includes 650+ courses from MIT, Stanford, Yale, Berkeley, IIT Madras. The app is completely built using react native.

### CODE REVIEW

**Comment by chirag04** [comment]
@facebook-github-bot shipit

@gauravsapiens very cool!

**Comment by gauravsapiens** [comment]
@chirag04 It didn't merge. Can you please help

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
Failed to merge because of a transient infra error.

@facebook-github-bot shipit

**Pull request closed without merging**
