### PR TITLE
Refactor runVerbose to avoid spawn error on windows

### PR DESCRIPTION
**Pull request by sunnylqm**
Use spawn in runVerbose would cause error on Windows
qq 20160405123602

### CODE REVIEW

**Comment by bestander** [comment]
I don't think removing `spawn` completely is a good idea, we'd better find the reason why it throws an error on Windows.
`spawn` is good because it is asynchronous and we can see the logs of the spawn-ed command while it is running.
It is essential for something long running like verbose mode.

Even more, @satya164 and I had a plan to use spawn for non verbose install, too, because install time is now minutes and we need to log progress.

**Comment by bestander** [comment]
I can't wait for Ubuntu on Windows https://msdn.microsoft.com/en-us/commandline/wsl/about :)

**Comment by ide** [comment]
There are cross-platform implementations of spawn -- just use that instead of rewriting all this code.

**Comment by ide** [comment]
@bestander agree about Ubuntu. When that launches we should consider requiring it even if it's on Windows 10 Pro only or something like that.

**Comment by facebook-github-bot-0** [comment]
@sunnylqm do you have any updates for this pull request? It's been a while so we wanted to check in and see if you've looked at the requested changes.

**Comment by janicduplessis** [comment]
spawn does work on Windows but you have to start a shell. We already use this pattern in a few place in the codebase.

```
spawn('cmd.exe', ['/C', '<command to execute>'], options);
```

There is also the shell option for the spawn command but this is only available in recent versions of node 5. I haven't tried this one though.

```
spawn('<command>', args, {shell: true});
```

**Comment by mkonicek** [comment]
@sunnylqm I'm going through all pull requests and noticed that this one hasn't been updated in a while and has some comments suggesting changes. I'll close it to keep the number of open pull requests down; if you plan to continue working on it please send a new pull request linking to this one.

**Pull request closed without merging**
