### PR TITLE
Add Emberall to showcase

### PR DESCRIPTION
**Pull request by corbt**
I'm really excited to finally have been able to share with the world the app that I've been building with React Native for the last six months! Emberall is the best way to save and share family videos, and record special moments with your kids as they're growing up. (@vjeux ping me if you want a premium account for free :P ) More details are on our company [blog](http://emberall.com/blog).

I've been heads down for a while just getting this out the door, but I'll try to have a blog post out soon with lessons learned in getting the app finished and published in the App Store.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @brentvatne and @manonthemat to be potential reviewers.

**Comment by vjeux** [comment]
<3 <3 <3

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/993459874056269/int_phab) to review.

**Pull request closed without merging**
