### PR TITLE
make AsyncStorage serially execute requests

### LINKED ISSUE #14101: AsyncStorage not fulfilling promise on Android 7+
### Issue

I am using `redux-persist` in a react native project, that runs just fine in a broad number of devices execept Android 7. I am trying to debug the problem on why my AsyncStorage is nor persisting and found this:

The following code executes inside React Native component lifecycle's
```
  componentDidMount() {
    attachObservables(store)
    setInterval(async () => {
      console.log('Inside setInterval')
      const data = await AsyncStorage.getAllKeys()
      console.log('inside the getAllKeys')
      data.forEach(async k => {
        const value = await AsyncStorage.getItem(k)
        console.group(k)
        console.log(value)
        console.groupEnd()
      })
    }, 3000)
  }
```

Code after 'Inside setInterval' is never called. It only runs once if outside the setInterval. If I call once the code outside the setInterval it appears to run just fine. I also tried callback format vs async / await version but it does not seem to matter.

Same problem I had using firebase js library (callbacks never return after the first one). I am now looking for alternatives to workaround the problem.

Works with `setImmediate` and `InteractionManager.runAfterInteractions`. Seems that `redux-persist` uses `setImmediate` or fallsback to `setTimeout`.

Any ideas?

### Additional Information

* React Native version: React Native 0.40+ (last tested on RN@0.44)
* Platform: Only Android 7 and above
* Development Operating System: Mac os, Node 7.4
* Dev tools: 

```
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        multiDexEnabled true
        applicationId "com.netbeast.yeti"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 69
        versionName "1.3.91"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

In case this is a user level question I opened a question on stackoverflow, no luck yet, https://stackoverflow.com/questions/44114061/asyncstorage-is-not-returning-the-callback?noredirect=1#comment75248695_44114061

### PR DESCRIPTION
**Pull request by dannycochran**
## Motivation

This patch is a bit of a hack job, but I'd argue it's necessary to dramatically improve the dev UX on Android devices. Somewhere in react-native, there's a shared SerialExecutor which AsyncStorage uses that is getting blocked, causing remote debugging to occasionally hang indefinitely for folks making AsyncStorage requests. This is frustrating from a dev UX perspective, and has persisted across several versions as far back as RN 0.44, and still remains on RN 0.54.

The issue seems to only happen on Android > 7+, which is likely because the ThreadPoolExecutor behavior changed in this version:
https://stackoverflow.com/questions/9654148/android-asynctask-threads-limits

Fixes #14101

## Test Plan

We've been using this patch in production for the past 4 months on our team by overriding the AsyncStorage native module. We use AsyncStorage extensively for offline data and caching.

You can test by compiling this commit version into a test react native repository that is set to build from source:

```sh
git clone https://github.com/dannycochran/react-native rnAsyncStorage
cd rnAsyncStorage
git checkout asyncStorage
cd ..
git clone https://github.com/dannycochran/asyncStorageTest
yarn install
cp -r ../rnAsyncStorage node_modules/react-native
react-native run-android
```

## Related PRs

No documentation change is required.

https://github.com/facebook/react-native/pull/16905

## Release Notes

[Android] [BUGFIX] [AsyncStorage] - Fix AsyncStorage causing remote debugger to hang indefinitely.

### CODE REVIEW

**Comment by dannycochran** [comment]
@esprehn @jsdario @shergin

**Comment by chirag04** [comment]
is this different from `SERIAL_EXECUTOR`?

**Comment by dannycochran** [comment]
@chirag04 nope, it's literally copied and pasted from there:

https://android.googlesource.com/platform/frameworks/base.git/+/1488a3a19d4681a41fb45570c15e14d99db1cb66/core/java/android/os/AsyncTask.java#237

There's just no way to import it, so I copied and pasted it and left a note in the file.

**Comment by chirag04** [comment]
@dannycochran https://android.googlesource.com/platform/frameworks/base.git/+/1488a3a19d4681a41fb45570c15e14d99db1cb66/core/java/android/os/AsyncTask.java#219

I might be missing something.

**Comment by dannycochran** [comment]
@chirag04 can you clarify what your question is? The SerialExecutor class I copied in is the same as the one provided by Android's AsyncTask class.

However, my PR instantiates an instance of SerialExecutor for use with AsyncStorage tasks, because somewhere else in react-native, the shared SerialExecutor class instance is getting blocked when remote debugging. Because the SerialExecutor class is private in AsyncTask, there's no way to import it, hence the copy and paste.

**Comment by chirag04** [comment]
> Because the SerialExecutor class is private in AsyncTask, there's no way to import it, hence the copy and paste.

Yes but an instance of the SerialExecutor class is public(SERIAL_EXECUTOR). So my question was why not use `SERIAL_EXECUTOR`. I don't understand java well enough but looks like `SERIAL_EXECUTOR` is the default executor. Also, feel like we are not fixing the root cause here.

**Comment by dannycochran** [comment]
@chirag04 Correct, that's the default, and it's the SerialExecutor instance that's blocked elsewhere in RN. Using that would be identical to the existing behavior. This PR uses its own SerialExecutor instance so it does not get blocked by something else in the codebase.

And yes, this does not get at the root cause, which is that somewhere is posting a task which hangs indefinitely. Still, I would argue landing this is pretty critical to dev UX, if you take a look at the comments / reactions to #14101, you can see how much it's impacting people.

**Comment by esprehn** [comment]
The android CI failure is unrelated:

ReactAndroid/src/main/jni/first-party/yogajni/jni/YGJNI.cpp:9:25: fatal error: yoga/YGNode.h: No such file or directory
 #include <yoga/YGNode.h>
                         ^
compilation terminated.
BUILT 294/332 JOBS 0.0s //ReactAndroid/src/test/java/org/mockito/configuration:configuration#class-abi
Build failed: Command failed with exit code 1.
stderr: ReactAndroid/src/main/jni/first-party/yogajni/jni/YGJNI.cpp:9:25: fatal error: yoga/YGNode.h: No such file or directory
 #include <yoga/YGNode.h>
                         ^
compilation terminated.
    When running <c++ preprocess_and_compile>.
    When building rule //ReactAndroid/src/main/jni/first-party/yogajni:jni#compile-pic-YGJNI.cpp.o8c77d5e7,default.

**Comment by esprehn** [comment]
fwiw this change makes Android match iOS behavior too:

```objc
static dispatch_queue_t RCTGetMethodQueue() 
{
 // ...
 queue = dispatch_queue_create("com.facebook.react.AsyncLocalStorageQueue", DISPATCH_QUEUE_SERIAL);
 // ...
}
```

iOS uses a separate serial queue to execute AsyncStorage tasks. Android using the default serial AsyncTask queue means all other serial tasks can block AsyncStorage tasks on Android unlike iOS.

**Comment by danilobuerger** [comment]
Just tested this, works for me.

**Comment by dannycochran** [comment]
@grabbou could you help me find a reviewer? This fixes #14101, which is the 8th most commented open issue right now.

**Comment by grabbou** [comment]
@javache @janicduplessis to start with.

@hramos do you know anyone at FB right now involved in Android part of things?

**Comment by sunnylqm** [comment]
Any update on this?

**Comment by esprehn** [comment]
Not sure what the bot is talking about. The file dates to the original release of RN in 2015, and the file still exists:
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/storage/AsyncStorageModule.java

**Comment by janicduplessis** [comment]
Sorry about the delay reviewing this.

Would it be possible to use newSingleThreadExecutor https://developer.android.com/reference/java/util/concurrent/Executors.html#newSingleThreadExecutor() instead of copying that code from AsyncTask.

cc @mdvacca

**Comment by esprehn** [comment]
@janicduplessis That would create a new thread instead of reusing one from the pool that backs AsyncTask, but yeah you could do that.

**Comment by silasrm** [comment]
My app has this error when try to setItem in wrong format, like JSON without stringify.

**Comment by crobinson42** [comment]
@dannycochran would love to see this moved along as the issue is now locked and it's a growing problem for folks.

**Comment by farzadshafiee** [comment]
The bugs which this PR resolves, makes it really diffcult to debug apps on Android. The changes seem really small and incremental. Wondering what's the hold up for the reviewers...

**Comment by rikur** [comment]
+                                                     1

**Comment by esprehn** [comment]
@gaearon This is another critical issue that impacts us. We had to fork the entire AsyncStorage module into our own codebase so we could apply this patch and set canOverrideExistingModule() to true. This PR has been open now for for 3 months. It'd be really awesome if you could help move this along, you had mentioned folks should ping you if PRs and issues were not being addressed.

**Comment by sahrens** [comment]
Seems fine to me - I'll try to import it.

**Comment by hramos** [comment]
The import timed out. Let's try again.

**Comment by hramos** [comment]
This failed some internal tests the other day. I'm running tests again and will post here with results if they fail.

**Comment by hramos** [comment]
I was able to reproduce on Circle CI the same failures we observed internally. See https://circleci.com/gh/hramos/react-native/3233?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, an example:

```
FAILURE com.facebook.react.modules.storage.AsyncStorageModuleTest testMultiRemove: 
Wanted but not invoked:
callback.invoke();
-> at com.facebook.react.modules.storage.AsyncStorageModuleTest.testMultiRemove(AsyncStorageModuleTest.java:146)
Actually, there were zero interactions with this mock.

Wanted but not invoked:
callback.invoke();
-> at com.facebook.react.modules.storage.AsyncStorageModuleTest.testMultiRemove(AsyncStorageModuleTest.java:146)
Actually, there were zero interactions with this mock.

	at com.facebook.react.modules.storage.AsyncStorageModuleTest.testMultiRemove(AsyncStorageModuleTest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1873)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:773)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:638)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:49)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.facebook.buck.testrunner.JUnitRunner.run(JUnitRunner.java:97)
	at com.facebook.buck.testrunner.BaseRunner.runAndExit(BaseRunner.java:272)
	at com.facebook.buck.testrunner.JUnitMain.main(JUnitMain.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.jvm.java.runner.FileClassPathRunner.main(FileClassPathRunner.java:80)
```

**Comment by mcavaliere** [comment]
The Java patch unfortunately didn't help me. 

For those that are stuck, I wrote this as a workaround. Mapping getItem() / setItem() / removeItem() to an array of Promises got the job done for me. 

Gist: https://gist.githubusercontent.com/mcavaliere/5ff291c7d30198c7e174ac7fd233794c/raw/c4b05821e967ba005b992f3b764ca6c6b23e1c19/AsyncStorageSupplement.js

Code: 

```javascript
export default class AsyncStorageSupplement {
  static multiGet(keys) {
    return Promise.all(
      keys.map(key => AsyncStorage.getItem(key))
    )
  }

  static multiRemove(keys) {
    return Promise.all(
      keys.map(key => AsyncStorage.removeItem(key))
    )
  }

  static multiSet(pairs) {
    return Promise.all(
      pairs.map((pair) => {
        return AsyncStorage.setItem(pair[0], pair[1])
      })
    )
  }
}
```

**Comment by adaltavo** [comment]
@mcavaliere your workaround worked for me. Is the problem releted only to "multi" prefixed methods???

**Comment by haggholm** [comment]
@hramos Looking at the CI failure (https://circleci.com/gh/facebook/react-native/38275?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), the error looks completely unrelated to this PR:

```
ReactAndroid/src/main/jni/first-party/yogajni/jni/YGJNI.cpp:9:25: fatal error: yoga/YGNode.h: No such file or directory
 #include <yoga/YGNode.h>
                         ^
compilation terminated.
```

But the PR does not touch any of the files involved—it just changes one Java file. I would have to guess that the failure was due to something else breaking the build, and if master passes, the PR should too. Could you maybe re-run CI and see if it passes `test_android`? It would be *extremely* nice to have this in the next version of RN and not have to patch it anymore…

**Comment by hramos** [comment]
@haggholm `test_android` is passing on master, so as long as it's red on this PR, it won't be merged. Perhaps all that's missing is a rebase, and that can be done prior to merging this.

**Comment by haggholm** [comment]
@hramos I have to admit I’m kind of crap with git and not familiar with rebase and such, but (a) it looks like the OP has not been active in a while, and (b) I do really want to see this make it in. In case it helps, I created a mirror PR for CI: https://github.com/facebook/react-native/pull/20258

Anything I can do to help get this change in, please let me know.

**Comment by haggholm** [comment]
@hramos I had to make some changes to make tests pass; once the earlier (irrelevant) errors were out of the way, the `AsyncStorageModule` tests did actually fail due to async issues; after some minor changes, my mirror PR (https://github.com/facebook/react-native/pull/20258) successfully passes `test_android`. Some other tests are failing, but right now those are also failing in `master`, and I hardly think that my change to two Java files can be blamed for iOS failures…

**Comment by hramos** [comment]
Thanks @haggholm, I'll give @dannycochran a chance to take in your changes from #20258 and see if we can get this merged.

**Comment by dannycochran** [comment]
@haggholm @hramos I synced with master and with the changes from #20258

**Comment by haggholm** [comment]
@hramos Can this be merged now? It looks like the only failing test is iOS E2E, which can hardly depend on changes to `.java` files…

**Comment by dulmandakh** [comment]
@dannycochran thank you for investigating and coming up with solution to the common issue. Could you please look at my solution (https://github.com/facebook/react-native/pull/20386).

IMHO, using dedicated thread executor to access SQLite will improve performance because  AsyncTask.THREAD_POOL_EXECUTOR is shared and might be busy with other AsyncTask tasks. Also it allows you to provide custom executor if you want concurrency etc.

**Pull request closed without merging**
