### PR TITLE
[Packager] Support ES6 re-export in the dependency resolver

### PR DESCRIPTION
**Pull request by jeanregisser**
I found out that the packager failed at resolving dependencies using the re-export syntax:

```javascript
export { default as MyLib } from 'src/mylib';
```

I've updated the resolver to understand the [fromClause from the spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports) and updated the resolver tests.

### CODE REVIEW

**Comment by amasad** [comment]
Thanks for your contribution. We're in the process of moving the packager to it's own github repo and we'll be able to accept contributions like this much faster (we can just use the Github merge button). I'm hoping we can release it some time this week, and I'll ping you so we can move this PR there.

**Comment by skevy** [comment]
@vjeux I saw you imported the other es6 issue #1940. Any chance we could get this resolved as well?

**Comment by vjeux** [comment]
@amasad now that we can easily import diffs, do you mind doing a real review?

**Comment by ide** [comment]
I tagged this as needs-revision since this needs to be rebased.

**Comment by skevy** [comment]
@vjeux @ide if I rebase this and submit a new PR, can we get this merged? This is a super glaring issue in support es6 modules in the packager. With https://github.com/facebook/react-native/commit/535ee40818bf0826e24994bdc4696834b9ebdc15, we have only partial support.

**Comment by vjeux** [comment]
@skevy yes please!

**Comment by skevy** [comment]
@vjeux #3465

**Comment by ide** [comment]
Thanks @skevy!

**Comment by skevy** [comment]
@ide this can be closed, btw, given #3465. One less PR to have open when there are hundreds :)

**Comment by ide** [comment]
Thanks for the heads up.

**Pull request closed without merging**
