### PR TITLE
Make google repo priority higher than jcenter

### PR DESCRIPTION
**Pull request by sunnylqm**
Fixes https://github.com/facebook/react-native/issues/21907#issuecomment-432319128 and prevent similar issues happening again

### CODE REVIEW

**Comment by sunnylqm** [comment]
ping @kelset @grabbou 
This is a hotfix. Now all new 0.57.x project can not build on android.

**Comment by kelset** [comment]
Thanks for the PR, we'll try to have this merged ASAP as it should fix the issue we are having on the CI for android test ✅

**Comment by kelset** [comment]
btw @sunnylqm shouldn't this change be done in the root level `build.gradle`? 🤔

**Comment by sunnylqm** [comment]
@kelset For end user only `build.gradle` in template works right? I dont know what is the root `build.gradle` for? If that is for CI, I can add that change too

**Comment by kelset** [comment]
I think that yeah, the root one defines the "overall" react native android config. Anyway, in the meantime, I've tried to replicate your change on the `0.57-stable` branch to see if it fixes the CI there (and now the test_android is green) -> https://github.com/facebook/react-native/commit/7a766bf2935208d0e01376f8e60ca009d31fbe27

**Comment by mmccartney** [comment]
I think it is safer to move `jcenter()` below `google()` rather than moving `google()` to the top (above `mavenLocal()`).  I agree we desperately need the templates fixed because the following doesn't work:

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-android # <-- build fails because jcenter is borken
```

**Comment by hramos** [comment]
Will land this one as is, but @mmccartney feel free to send another PR with your suggested changes.

**Pull request closed without merging**
