### PR TITLE
Removed core RCTConvert CoreLocation Libraries as well as reference i…

### PR DESCRIPTION
**Pull request by maschad**
## Summary

This PR is to address #28200

Even though GeoLocation was extracted from the Core, there are still libraries i.e. the CoreLocation.h library included which cause Apple to reject Apps, as mentioned here.

This removed all references to the CoreLocation library that where remaining.

## Changelog

[iOS] [Removed] - Message

## Test Plan

- Flow check passes.
- RNTest built successfully.

### CODE REVIEW

**Comment by shergin** [comment]
This file is still being used by some deps. One of them (which is blocking landing internally) is this one: https://github.com/react-native-community/react-native-maps/blob/72b0f77e31d18959e91acb036d5f91ab46e11ef2/lib/ios/AirMaps/AIRMapCircleManager.m#L14

I think we should copy the functionally/code there. And then try to remove it from here one more time.


@maschad Can you do it?

**Comment by maschad** [comment]
Thanks for the recommendation @shergin I re-added them, but my only concern is that Apple's static analyzer may still pick up the `CoreLocation` files and then trigger a warning.

**Comment by shergin** [comment]
@maschad Nonono, I meant we need to move/copy those files to that library to break the dependency the core in this regard. After we do that, we can safely remove them from the core.

I will land this one as is. But I would appreciate if you can fix that library and then open another PR that will finally delete the files from the core. 🙏

**Comment by maschad** [comment]
@shergin silly me, I should have realized that 😅. Thanks for clarifying anyways, I can definitely do that 👍🏿

**Pull request closed without merging**
