### PR TITLE
switch to size_t's in callAsFunction in facebook::react::Object

### PR DESCRIPTION
**Pull request by samuela**
## Motivation
Address those pesky clang warning 
```
Implicit conversion loses integer precision
```

## Test Plan

Compiled with and without the changes in a live react-native project and verified that these changes successfully dismissed the warnings.

## Related PRs
N/A

## Release Notes

[GENERAL] [MINOR] [jschelpers] - Fix compile warnings for a more pleasing compile experience.

### CODE REVIEW

**Comment by samuela** [comment]
test_android failure appears to be unrelated.

**Comment by samuela** [comment]
@facebook-github-bot merged in the latest master.

**Comment by samuela** [comment]
@facebook-github-bot merged in the latest master.

**Comment by samuela** [comment]
@facebook-github-bot merged in the latest master.

**Comment by cpojer** [comment]
This code has been changed a ton so I'm gonna close this PR. If this issue is not resolved in the new code, please send a new PR and we'll merge it faster than our previous response time. I promise!

**Pull request closed without merging**
