### PR TITLE
Add NavigationExperimental to UIExplorer on Android too

### PR DESCRIPTION
**Pull request by brentvatne**

### CODE REVIEW

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
On master there seem to be 2 `NavigationExperimental` examples in UIExplorer.

Also @ericvicenti The appbar doesn't have a different styling on Android. Is it intentional?

**Comment by ericvicenti** [comment]
I haven't had time to fix the NavigationHeader styles for Android, plus people may decide to use ToolbarAndroid instead

**Comment by bestander** [comment]
merged

**Pull request closed without merging**
