### PR TITLE
CHORE - Remove Trailing Spaces

### PR DESCRIPTION
**Pull request by clickthisnick**
Remove Trailing Spaces.

Why:
Sometimes there are conflicts with trailing spaces 
Saves space
Those whose tools automatically delete them will have their pr watered down with trailing space removal

### CODE REVIEW

**Comment by satya164** [comment]
Thanks, and congrats for your first PR.

@facebook-github-bot shipit

**Comment by clickthisnick** [comment]
I signed with an email address that is not the email address author of this pull request, is there anyway to change the email associated with this pull request?

**Comment by satya164** [comment]
@clickthisnick You can do a soft reset to remove the last commit and commit again with the proper id.

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
