### PR TITLE
Fix the WebSocket sendBinary error

### PR DESCRIPTION
**Pull request by sreesharp**
Fixing the WebSocket SendBinary method error. This is a regression caused during recent change.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @AndrewJack and @philikon to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
@sreesharp updated the pull request.

**Comment by sreesharp** [comment]
cc @mkonicek @satya164

**Comment by facebook-github-bot-1** [comment]
@sreesharp updated the pull request.

**Comment by satya164** [comment]
LGTM

@AndrewJack confirming, was the change intentinal?

**Comment by AndrewJack** [comment]
LGTM 👍 - Sorry this wasn't intentional

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/982453488520618/int_phab) to review.

**Pull request closed without merging**
