### PR TITLE
TouchableHighlight and TouchableOpacity look at props.accessible

### PR DESCRIPTION
**Pull request by yanni858**
To enable automation testing, we need tools such as Appium to be able to
select items within the Touchables, which they can't do if the accessible flag is true.

This change leaves the default as true, but lets us override it for automation testing.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @jesseruder and @janicduplessis to be potential reviewers.

**Comment by Prepd** [comment]
Just ran into this too. Could you add a small test plan or ideally, tests? Also rebase to master :)

**Comment by jsierles** [comment]
@yanni858 Just ran into this too. Could you add a small test plan or ideally, tests? Also rebase to master :)

**Comment by yanni858** [comment]
Closing this in favor of PR #6561, which came first.

**Pull request closed without merging**
