### PR TITLE
[Docs] ListView documentation is broken -- should include properties from ScrollView

### PR DESCRIPTION
**Pull request by arianitu**

### CODE REVIEW

**Comment by chirag04** [comment]
ListView inherits all the properties of a scrollView. horizontal being one such property of scrollView.

IMO, It's more scalable to document listview as a child of scrollview rather than documenting individual properties of scrollview in listview.

**Comment by arianitu** [comment]
Oh neat, I didn't know that ListView had all the properties of ScrollView. It does seem like some properties are already duplicated tho, for example, removeClippedSubviews.

It seems like horizontal is a property of ListView tho, it's internally used. It's also a really important property, so I don't know what the best approach is here.

If the documentation states that ListView has all the properties of ScrollView, you have to jump to ScrollView to see how to list things horizontally (which seems kind of weird?)

**Comment by brentvatne** [comment]
@arianitu - any suggestions on how we can improve the documentation for this without having to duplicate the properties?

**Comment by ide** [comment]
We could have the docs generator link to inherited props. It would find `...ScrollView.propTypes` and know to link to the props section of the ScrollView docs. That'd be a great PR.

**Comment by vjeux** [comment]
> ...ScrollView.propTypes and know to link to the props section of the ScrollView docs.

Hmm, it should already do that. If it doesn't anymore then it's a bug

**Comment by ide** [comment]
Yeah it looks broken (no ScrollView reference on https://facebook.github.io/react-native/docs/listview.html)

**Comment by brentvatne** [comment]
@arianitu - could you investigate why those props aren't being pulled out for docs?

**Comment by arianitu** [comment]
@brentvatne this seems to have been fixed before I had a chance to look at it. I think this can be closed for now.

**Pull request closed without merging**
