### PR TITLE
[iOS] [Fixed] [CocoaPods | Project] - Support building the project on arm64 macOS

### PR DESCRIPTION
**Pull request by chuganzy**
## Summary

In `scripts/react_native_pods.rb` it excludes `i386` architecture when Hermes is enabled.
However, when you look at the OS versions RN supports, `i366` arch is not needed from the beginning because there is no 32bit iOS devices RN supports.

Also RN does not yet support arm64 simulator at this moment. When we make a new project and try to run it on a simulator on arm macOS, it fails for now. Instead of conditionally excluding arm64, it should always exclude arm64 architecture to solve it. Conditionally changing the build config also causes another issue as described below: 
1. Run `pod install` on Intel macOS
2. git-push this change
3. Run `pod install` on arm64 macOS

In step 3, it shows diff in the iOS project file.

This PR aims to solve both issues.

## Changelog

[iOS] [Fixed] - Support building the project on arm64 macOS

## Test Plan

Build the project on arm64 macOS.

### CODE REVIEW

**Comment by Arkkeeper** [comment]
Why do you think that RN doesn’t support arm64 simulators? As for me, it runs without errors. What errors do you get? Do you have Hermes and Flipper enabled?

Excluding arm64 is rather doubtful solution. It was the only fix before RN 0.64 release to run RN apps on M1 Macs in iOS Simulator, but now it’s not needed anymore.

**Comment by chuganzy** [comment]
Hi @Arkkeeper, thank your for your comment. Interesting to hear that you do not have any issue on M1 macOS.
I see build error when I create new RN project using `npx react-native init`.. and yes Flipper is installed too.
Also related discussion here: https://github.com/react-native-community/discussions-and-proposals/issues/295 but I see others are having trouble with building on M1.

**Comment by chuganzy** [comment]
Ok, now I figured out `npx react-native run-ios` works if the node installed to macOS is x86_64 version. 
If you try to build it by yourself (from Xcode) it fail still.
The reason is because `npx react-native run-ios` uses `/usr/bin/env node`. So it builds the iOS app using Rosetta if node is `x86_64`.

**Comment by Arkkeeper** [comment]
I have arm64 node and I usually build iOS and Mac Catalyst versions of our apps directly from Xcode.
Let's clarify the error that you get trying to build from Xcode, could you please provide any details? Maybe it's something with swift libraries?

**Comment by chuganzy** [comment]
@Arkkeeper Interesting. Yes I am seeing exactly the same one posted here.
https://github.com/react-native-community/discussions-and-proposals/issues/295#issuecomment-786956611

**Comment by chuganzy** [comment]
Ok, I could now build the app on arm64 native.
Things I needed to change were:
1. Get rid of `LIBRARY_SEARCH_PATHS` option
2. Add a empty Swift file into the app target

**Comment by Arkkeeper** [comment]
A better solution is https://github.com/facebook/react-native/issues/31208#issuecomment-803825310

**Comment by chuganzy** [comment]
@Arkkeeper Thanks for your comment. Unfortunately it did not solve the issue on mine..

**Comment by lubomyr** [comment]
@chuganzy 
try solution described https://github.com/react-native-community/discussions-and-proposals/issues/295#issuecomment-809636024

**Comment by chuganzy** [comment]
Thank you @lubomyr, and yes I have tried it here and worked https://github.com/facebook/react-native/pull/31229#issuecomment-808499111

Still there are couple of issues in the current project setup:
1. It anyway excludes arm64 simulator on Intel macOS when you run `pod install`: https://github.com/facebook/react-native/pull/31229/files#diff-adcf572f001c2b710d14f409c14763f1a50b08369b3034548f1602685d21f67fL132
2. Due to 1, it always make diff in the Xcode project file when you run `pod install` on different arch macOS machines (Intel vs Apple)
3. If the solution [here](https://github.com/facebook/react-native/pull/31229#issuecomment-808499111) is the way RN wants to go, then we can make changes in LIBRARY_SEARCH_PATHS and add empty Swift file, but we have to 1 and 2 needs to be solved too.

To move this forward I want to clarify:
1. If 3. is the way RN wants to go
2. Why we need `LIBRARY_SEARCH_PATHS` configured in the first place (I will git blame later and put any findings here if I could!)
3. Why we need to exclude arm64 on Intel macOS (same as 2. I will git blame.)

**Comment by chuganzy** [comment]
Closing as Hermes now supports arm64!

**Pull request closed without merging**
