### PR TITLE
Cicle CI fix: limit predex threads

### PR DESCRIPTION
**Pull request by bestander**
Limited nubmer of threads Gradle may spawn when generating dex files

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @ide and @mkonicek to be potential reviewers.

**Comment by bestander** [comment]
cc @avaly

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/250013262044863/int_phab) to review.

**Pull request closed without merging**
