### PR TITLE
Typo fix in Touchable example

### PR DESCRIPTION
**Pull request by paulshen**
**Test plan**

Run UIExplorer example and see that enabled TouchableHighlight example has correct text.

image

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @Kureev and @nicklockwood to be potential reviewers.

**Comment by Kureev** [comment]
LGTM 👍

**Comment by ide** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/280974432247633/int_phab) to review.

**Pull request closed without merging**
