### PR TITLE
Add extensibility point for passing additional args to packager

### PR DESCRIPTION
**Pull request by ligaz**
Extend `react-native-xcode.sh` to allow passing of additional args to
bundle command. This is useful if you want to generate source maps for
example.

Here is an example that modifies the “Bundle React Native code and
images” script phase:

```sh
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output ${SRCROOT}/build/main.jsbundle.map"

./react-native-xcode.sh

```

Android’s `build.gradle` already have this extensibility point in the name
of:
```gradle
project.ext.react = [
    extraPackagerArgs: [
    ]
]
```

### CODE REVIEW

**Comment by ligaz** [comment]
Ping @dlowder-salesforce. Can you please take a look? Thanks.

**Comment by dlowder-salesforce** [comment]
Looks ok to me.... ping @hramos @javache

**Comment by chirag04** [comment]
@ligaz are there more extension points other than `sourcemap-output`? if not what do you think about simply adding `sourcemap-output`?

```
SOURCEMAP_FILE="$BUNDLE_FILE.map"
--sourcemap-output "$SOURCEMAP_FILE"
```

**Comment by ligaz** [comment]
@chirag04 [Here](https://github.com/facebook/react-native/blob/master/local-cli/bundle/bundleCommandLineArgs.js) is the full list of all bundle commands. Having it generic (like it is implemented for Android) is more future proof in case new command line args are added.

**Comment by hramos** [comment]
This should be landing shortly. We had some minor issues landing this internally but I've resolved them manually.

**Comment by ligaz** [comment]
Hey @hramos what's the state of this PR?

**Comment by hramos** [comment]
The original import failed due to some changes we made to our internal repository. This last one should import successfully.

**Comment by Froelund** [comment]
Any news about this @hramos ? I'm uncertain about the process, is there anything I can do to help?

**Comment by Froelund** [comment]
image

**Comment by skevy** [comment]
Hi there!

The packager no longer lives in this repo. It now lives in https://github.com/facebook/metro-bundler. The reasoning for the split is explained here: https://github.com/facebook/react-native/issues/13976.

If you're still interested in pursuing this PR, please open the PR on that repo! :)

Thanks!
-Adam

**Comment by skevy** [comment]
@Froelund sorry this didn't get merged! It should be much easier to contribute to the packager now that it's separate.

**Comment by brunolemos** [comment]
Did anyone create this issue on the new repo? Couldn't find it.

cc @ligaz

**Comment by ligaz** [comment]
I believe this script still lives in this repo and not the packager one. @hramos how we are supposed to progress with this one?

**Pull request closed without merging**
