### PR TITLE
temporarily disable broken OSS CI tests to save CI capacity

### PR DESCRIPTION
**Pull request by bestander**
Fix progress tracking via t10955118

### CODE REVIEW

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by ide** [comment]
Think I fixed iOS tests here: https://github.com/facebook/react-native/pull/7168

**Comment by bestander** [comment]
Good job, @ide.
At least we have Travis green now, I removed the comment.
For Circle I'll just remove retrues for now to make it fail faster.

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
