### PR TITLE
[io.js] Print a warning message if the user is not on io.js 2.x

### PR DESCRIPTION
**Pull request by ide**
Detects if the user is on Node or io.js 1.x and prints a banner explaining how to upgrade. We probably should link to more detailed upgrade docs so this is just a start.

I also added a function to format banners that is kind of useful.

Addresses part of #1737 

packager-banner

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@ide I just tried 

```
brew link iojs --force
```

But it gives following error for me

```
$ brew link iojs --force
Linking /usr/local/Cellar/iojs/2.3.1... 
Error: Could not symlink bin/node
Target /usr/local/bin/node
is a symlink belonging to node. You can unlink it:
  brew unlink node

To force the link and overwrite all conflicting files:
  brew link --overwrite iojs

To list all files that would be deleted:
  brew link --overwrite --dry-run iojs
```

I think we should mention 
```
brew unlink node
```
also.

**Comment by ide** [comment]
@prathamesh-sonpatki good catch. the instructions now include `brew unlink node; brew install iojs && brew ln iojs --force`.

**Comment by amasad** [comment]
awesome.

**Comment by ide** [comment]
Removed the bit about "next release" from the message since the jest upgrade and io.js support already landed. Moving fast!

**Comment by ide** [comment]
@amasad could I get an update on when this will be merged? I'd like to include it with 0.8.0-rc (checklist here #1864) to pre-emptively answer issues people might encounter if they're using Node.

**Comment by ide** [comment]
@nicklockwood could you help merge this in before we cut 0.8.0-rc? This is the last commit I'd like to include in the RC and the rest of the items on #1864's checklist can wait for 0.8.0-rc.2.

**Comment by nicklockwood** [comment]
@ide, I don't understand the JS side of the platform well enough to judge the implications of this. Maybe @vjeux or @tadeuzagallo can weigh in?

**Comment by tadeuzagallo** [comment]
LGTM

@facebook-github-bot import

**Comment by ide** [comment]
Thanks guys! Ready to release 0.8.0-rc very soon!

**Pull request closed without merging**
