### PR TITLE
move templates to .github folder

### PR DESCRIPTION
**Pull request by ZakariaRidouh**
This moves the Template files to the .github folder. This helps clear up the extra files in the root of the directory.

This is my first PR 😄  and I plan to contribute more to this awesome project.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
@ZakariaRidouh updated the pull request.

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-5** [comment]
@ZakariaRidouh updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@ZakariaRidouh updated the pull request.

**Comment by janicduplessis** [comment]
I think we should keep CONTRIBUTING.md in the root for more visibility, I agree with moving the other files.

**Comment by janicduplessis** [comment]
Also these files are referenced in a coule places like https://github.com/facebook/react-native/blob/master/bots/IssueCommands.txt#L39 for example. Could you do a quick search for the files you moved and fix the paths.

**Comment by facebook-github-bot-5** [comment]
@ZakariaRidouh updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@ZakariaRidouh updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@ZakariaRidouh updated the pull request.

**Comment by ZakariaRidouh** [comment]
@janicduplessis fixed them 😄

**Comment by facebook-github-bot-2** [comment]
@ZakariaRidouh updated the pull request.

**Comment by janicduplessis** [comment]
@ZakariaRidouh Can you update the paths to the files you moved as I mentioned above (ie: https://github.com/facebook/react-native/blob/master/bots/IssueCommands.txt#L39).

**Comment by ZakariaRidouh** [comment]
@janicduplessis yep I've fixed that.

**Comment by janicduplessis** [comment]
Found two more references to PULL_REQUEST_TEMPLATE.md https://github.com/facebook/react-native/blob/master/docs/PullRequestGuidelines.md. Can you fix this then this is good to go!

**Comment by ZakariaRidouh** [comment]
@janicduplessis haha i've fixed the last link.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by janicduplessis** [comment]
@mkonicek @bestander I guess these files are not in the fb repo, could one of you sync this?

**Comment by bestander** [comment]
All 4 files are synced to fb repo.
Probably the conflict is in the new folder creation.

**Comment by bestander** [comment]
another go

**Comment by bestander** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/240350926343762/int_phab) to review.

**Pull request closed without merging**
