### PR TITLE
add more infos on how to profile the javascript #10944

### PR DESCRIPTION
**Pull request by mdamien**
As said in #10944, there's not yet some good infos on how to profile the javascript.

I'm adding a mention to two ways of doing it (`react-addons-perf` and chrome profiler), feel free to correct me on this.

I almost added an example for `react-addons-perf` but I'm not sure what's the correct way to use. Here's the way I use it:

```javascript
import Perf from 'react-addons-perf';

....
    componentDidMount() {
        console.log('start perf tracking');
        Perf.start();
        setTimeout(() => {
            console.log('stop perf tracking');
            Perf.stop();
            Perf.printExclusive();
        }, 10000);
   }
...
```

### CODE REVIEW

**Comment by ericvicenti** [comment]
That is the correct way to use it for measuring startup time of your app. Feel free to add in the example! Also I think this applies for iOS as well. Maybe we can have one section of the document that is duplicated between both pages?

**Comment by ericvicenti** [comment]
cc @hramos

**Comment by mdamien** [comment]
@ericvicenti I've duplicated the content, maybe a good thing could be to add a section `Profiling JS` in `Performance.md` and link to it from the android profiling doc.

**Comment by hramos** [comment]
It looks like we only need to document this on Performance.md, which is the platform agnostic Performance doc.

**Comment by mdamien** [comment]
@hramos thanks, I've updated the PR accordingly

**Comment by mkonicek** [comment]
@mdamien I edited the PR a bit - a link here is sufficient, no need to replicate that info in the React Native docs: https://facebook.github.io/react/docs/perf.html

@facebook-github-bot shipit

**Pull request closed without merging**
