### PR TITLE
Add example of getting window dimensions to Dimensions docs.

### PR DESCRIPTION
**Pull request by calvinf**
This pull request adds an example to the Dimensions documentations.  Specifically, it gives an example of how to get the height and width from the window.

I'm submitting this documentation because discovering this information cost me some time and my hope is to save other folks time by having this info right in the docs generated from the comments in this file.

Let me know if you need anything else.

### CODE REVIEW

**Comment by brentvatne** [comment]
@facebook-github-bot shipit

**Comment by brentvatne** [comment]
Trying again..

@facebook-github-bot shipit

**Comment by calvinf** [comment]
@brentvatne do I need to do anything else here?

**Comment by skevy** [comment]
I think the github bot was broken...let's try again.

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
The code was merged into the fb codebase but didn't get exported back to github. Sorry about that! Will debug why that happened if it happens next time.

**Comment by vjeux** [comment]
@mkonicek the export has been stuck since yesterday afternoon

**Comment by calvinf** [comment]
Thanks for taking care of it, @mkonicek.

**Pull request closed without merging**
