### PR TITLE
Parser create getTypeAnnotationName(typeAnnotation)

### PR DESCRIPTION
**Pull request by cloudpresser**
## Summary:

> [Codegen 134 - Assigned to @cloudpresser] Create a function getTypeAnnotationName(typeAnnotation) in the Parser base class. Implement it using [this code for Flow](https://github.com/facebook/react-native/blob/d8ced6f8953cd896471983714e722caf50783960/packages/react-native-codegen/src/parsers/flow/components/events.js#L211) and [this code for Typescript](https://github.com/facebook/react-native/blob/d8ced6f8953cd896471983714e722caf50783960/packages/react-native-codegen/src/parsers/typescript/components/events.js#L223). Replace the callsites with the new function.

This is part of #34872

## Changelog:

[INTERNAL] [ADDED] - getTypeAnnotationName(typeAnnotation) in parser

## Test Plan:

`yarn jest packages/react-native-codegen` > new tests written, as well as coverage from existing tests

### CODE REVIEW

**Comment by cloudpresser** [comment]
@cipolleschi I updated this PR with changes suggested [here](https://github.com/facebook/react-native/issues/34872#issuecomment-1563485026). 
Also, now that upstream is fixed we're now passing CI tests here, :)

**Comment by cipolleschi** [comment]
@cloudpresser I'm sorry to ask for this, I have been tried to land this change for a while, but meanwhile the state of the repo has changed.
Could you please try to rebase and make sure that the CI is green again? 🙏

**Review by cipolleschi — CHANGES_REQUESTED** [review]
CI is red, unfortunately. :(

**Pull request closed without merging**
