### PR TITLE
Fix bug that index.android.bundle is missing when building a release AAB

### PR DESCRIPTION
**Pull request by thanakij**
## Summary

The official solution in [this pull](https://github.com/facebook/react-native/pull/30177) only solves some part of the [issue #29398](https://github.com/facebook/react-native/issues/29398).

Next, I would like to see my additional step I suggested [here](https://github.com/facebook/react-native/issues/29398#issuecomment-732511138) get merged so I create this pull request :).

## Changelog

[Android] [Fixed] - Fix missing index.android.bundle when building release AAB with gradle plugin 4.1

## Test Plan

Already confirmed by many people in the thread.

### CODE REVIEW

**Comment by lorenzoangelini** [comment]
@thanakij is it works also with proguard enabled? Because i have the same issue only with the proguard enabled.

**Comment by thanakij** [comment]
> @thanakij is it works also with proguard enabled? Because i have the same issue only with the proguard enabled.

Yes, I have proguard enabled in my setting for my release build.

**Comment by lorenzoangelini** [comment]
@thanakij  Perfect!

**Comment by kofsiwon** [comment]
I'am not using Proguard, but APK was crashed.
So, I had to generate APK many times when every release.
Sometimes APK file size is weird and App was crashed with Error 'Metro Server is not running, can not find index.android.bundle'

**Comment by thanakij** [comment]
Hi @lorenzoangelini, any news on this? :)

**Comment by thanakij** [comment]
> I'am not using Proguard, but APK was crashed.
> So, I had to generate APK many times when every release.
> Sometimes APK file size is weird and App was crashed with Error 'Metro Server is not running, can not find index.android.bundle'

Hi, can you try my patch to see if it works for you by either manually editing `node_modules/react-native/react.gradle` or using [patch-package](https://www.npmjs.com/package/patch-package)?

**Comment by kofsiwon** [comment]
> > I'am not using Proguard, but APK was crashed.
> > So, I had to generate APK many times when every release.
> > Sometimes APK file size is weird and App was crashed with Error 'Metro Server is not running, can not find index.android.bundle'
> 
> Hi, can you try my patch to see if it works for you by either manually editing `node_modules/react-native/react.gradle` or using [patch-package](https://www.npmjs.com/package/patch-package)?

ok, I'm trying to generate apk few times. with dependsOn(currentBundleTask).
I will let you know the test result.

how can I use patch-package? I don't know about it.

**Comment by kofsiwon** [comment]
Test with with dependsOn(currentBundleTask).

[Generate APK 5 Times]
app-release1.apk - 142.2MB
app-release2.apk - 142.2MB
app-release3.apk - 142.2MB
app-release4.apk - 142.2MB
app-release5.apk - 142.2MB
[Clean and Generate APK 5 Times]
app-release6.apk - 140.8MB
app-release7.apk - 140.8MB
app-release8.apk - 140.8MB
app-release9.apk - 140.8MB
app-release10.apk - 140.8MB
[Generate APK 5 Times]
app-release11.apk - 142.2MB
app-release12.apk - 142.2MB
app-release13.apk - 142.2MB
app-release14.apk - 142.2MB
app-release15.apk - 142.2MB

First APK after clean is weird.
"react-native": "0.63.3",

**Comment by thanakij** [comment]
Because my patch builds on top of [this pull](https://github.com/facebook/react-native/pull/30177), I just need your help to check if you have those changes as well.

**Comment by julianD77** [comment]
Looks like this PR has now been included in v66.0 onwards with this PR: https://github.com/facebook/react-native/pull/32026

**Pull request closed without merging**
