### PR TITLE
[Docs] fix props anchor links

### LINKED ISSUE #5450: [Docs] ShadowPropTypesIOS style link broken
https://facebook.github.io/react-native/docs/view.html#style

### PR DESCRIPTION
**Pull request by skv-headless**
All anchor links are broken because of https://github.com/facebook/react-native/blob/master/website/core/Site.js#L37 base tag it means that relative urls won't work.
closes #5450 
proof
screen shot 2016-02-29 at 13 34 35

### CODE REVIEW

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by skv-headless** [comment]
@vjeux I'm so sorry. I wanted to update PR to fix others anchor links. Can I update this one or create separate PR?

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by skv-headless** [comment]
@vjeux again I'm sorry. At last update I fixed anchors on support page and clean code a little bit. Could you please ship again?

**Comment by vjeux** [comment]
Erg sorry, I was too fast :p I can't shipit again but can you open up a pull request with the changes and i'll make sure to merge them in

**Pull request closed without merging**
