### PR TITLE
[NativeModules] Support for loading React and/or native modules as a dynamic framework

### LINKED ISSUE #579: [Bridge] Native module inside framework
Is there a way to implement native module inside framework instead of static library?

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds support for dynamically loading React as a framework.  If accepted, closes #579.  IntegrationTests all run successfully.

 This introduces several changes to RCTBridge.m

- extraction of strings from a mach_header section has been encapsulated in a helper class `RCTHeaderStringExtractor`.
- instances of this class are stored in an `NSSet` and uniqued by the address of their associated mach_header.
- a registration function `RCTRegisterModuleProviderContainingAddress(const void *address)` registers the binary containing a given address as a "module provider" and creates a `RCTHeaderStringExtractor` for the binary's mach_header.  A convienience helper function `RCTRegisterModuleProvider(void)` does the same, but registers the caller instead of requiring an explicit address.
- during the static `RCTBridge` initialization, all registered module providers are scanned, rather than just the binary in which `RCTBridge` is contained.

In RCTBridgeModule.h:
- the RCT_EXPORT_MODULE macro now includes a definition for `+ (void) load` that calls `RCTRegisterModuleProvider` - this allows registration of all module providers without changes to the existing api, but does potentially break native modules that already provide an implementation of `load`

A simple example project is a available at https://github.com/yusefnapora/react-dynamic-linking-example - it uses Cocoapods to install this branch with the `use_frameworks!` directive, which forces React to be compiled as a dynamic framework instead of a static library.  React components are loaded from both the framework and the app binary.

Concerns:
My biggest problem with this approach is the `load` hook for native modules; any existing native modules that currently provide an implementation of `+ (void)load` will refuse to compile.  I chose this approach because it doesn't require any explicit registration of the binary containing the modules; when the class loader invokes `load`, that will happen automatically for all "module providers".  As a result, this approach doesn't require "module providers" to know or care about whether they'll be linked dynamically or statically.

I also haven't measured the performance impact of the additional calls to `load` and `RCTRegisterModuleProvider` for each native module.  I suspect it's minimal, as the only work involved is calling `dladdr` to obtain the mach header, and creation of a `RCTHeaderStringExtractor`, which is fairly lightweight.  While a `RCTHeaderStringExtractor` is created for each invocation of `RCTRegisterModuleProvider`, only one is stored per mach header, as they are stored in an `NSSet` and `hash`ed by the mach header address.

Perhaps a compromise to allow native modules to define a `load` hook would be to check whether the class responds to a (hypothetical) `rct_load` class method and, if so, call it from the macro-provided `load` method. 

Please let me know if anything is unclear or I can do anything to help make this work.

### CODE REVIEW

**Comment by nicklockwood** [comment]
This is essentially the same as the solution I was planning, but thanks for doing the leg work!

The +load limitation is annoying, although in practice it can be worked around fairly easily (e.g. by adding custom load method inside a category).

**Comment by yusefnapora** [comment]
Awesome, glad to help :smile:

**Comment by yusefnapora** [comment]
The last commit adds automatic registration of the binary containing the `main()` function, since I encountered an issue when trying to link against a static library containing a native module. Since my app binary didn't define any native modules, it was never being registered as a "module provider".  The library was being registered, but the linker was relocating the `__DATA` sections for `RCTExport`, etc. to the app's binary, and they weren't being discovered.

**Comment by tptee** [comment]
:+1: super excited for this

**Comment by brentvatne** [comment]
@nicklockwood - any progress here? this looks like a nice feature :smile:

**Comment by mebinum** [comment]
following this, will this mean I could create a Framework in swift and include in my project? At the moment I'm trying to do that and getting `Class ... was not exported. Did you forget to use RCT_EXPORT_MODULE()?`

**Comment by yusefnapora** [comment]
@mebinum yes, this supports swift frameworks.  My main motivation for this was to explore integrating react native into an existing swift app, where most of the code is contained in a framework that's shared between app and extension targets.  Using this branch I was able to define React native modules in the framework and use them from an `RCTRootView` in either target (although react uses some cocoa apis that are off-limits to iOS app extensions).

**Comment by mebinum** [comment]
Awesome @yusefnapora look forward to this getting merged. Anyone know what the ETA on that is?

**Comment by yusefnapora** [comment]
@nicklockwood I've been busy at work and haven't kept up with this, but it looks like the new module loading system supports dynamic linkage without the crazy hacks in this PR.  :smile_cat: 

Not sure exactly when the change was made, but I did a quick test on 0.7.0-rc.2.  Modules defined in a shared framework load without a hitch, and React can be included as a pod using the `use_frameworks!` directive.

I'm going to close this and celebrate by poking at all the new features that have cropped up while I've been chained to Xcode.  Excellent work, react team; the new module loading system is very nice and clean!

**Comment by colinhang** [comment]
I still ran into the same issues as @mebinum. @yusefnapora Is there an example that i can follow to see how to get it work? Thanks!

**Pull request closed without merging**
