### PR TITLE
Fix InputType for url keyboard in Android

### PR DESCRIPTION
**Pull request by jeswinsimon**
## Summary

Fix for #35651 

## Changelog

[ANDROID][FIXED] - Updated `InputType` for `TextView`

## Test Plan

Autofill suggestions should be visible if keyboardType='url' for `TextInput`

### CODE REVIEW

**Comment by XantreGodlike** [comment]
Is it works fine?

**Comment by ryancat** [comment]
Thanks for fixing this. Could you add a screen record as test plan for this fix?

**Comment by XantreGodlike** [comment]
How to test it?

**Comment by XantreGodlike** [comment]
Will it be merged?

**Comment by XantreDev** [comment]
@ryancat pretty much sure that this is a correct combination of flags. How we can prove that it's working? https://gist.github.com/lopspower/ff2fec6c16991c072495#:~:text=textUri,TYPE_CLASS_TEXT%20/%20TYPE_TEXT_VARIATION_URI

**Comment by XantreDev** [comment]
Bump

**Pull request closed without merging**
