### PR TITLE
Update document on Getting Started with Android

### PR DESCRIPTION
**Pull request by anhldbk**
I've updated the tutorial to make it work on Linux

### CODE REVIEW

**Comment by mkonicek** [comment]
Hey @anhldbk, why might running the command need sudo?

**Comment by satya164** [comment]
If it needs sudo, you might have done some mistakes during setup.

**Comment by anhldbk** [comment]
@mkonicek, @satya164 I agree with you guys. But I already wrote that `(may need sudo)`. 
Many people have the same bug with me when installing npm: http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo

**Comment by satya164** [comment]
@anhldbk Usually that's the sign of some error on user's part. For example, if the user did `sudo npm install somepackage` while locally installing a package at some point, this issue will happen. The correct solution is to change permissions of the `~/.npm` folder. We shouldn't not encourage (or even suggest) usage of sudo in this case.

**Pull request closed without merging**
