### PR TITLE
Could not run adb reverse: Command failed:  reverse tcp:8081 tcp:8081

### PR DESCRIPTION
**Pull request by tatafu**
Could not run adb reverse: Command failed: G:\androidstudioSDK/platform-tools b reverse tcp:8081 tcp:8081 
in CMD terminal adb reverse tcp:8081 tcp:8081 error Closed

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @alloy and @skevy to be potential reviewers.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by alloy** [comment]
This PR doesn’t appear to be in any way related to the described topic. In addition the description of the issue is very sparse and doesn’t offer any insights into what’s going on.

This PR seems either bogus or @tatafu should file a new more helpful issue.

**Comment by marclundgren** [comment]
@alloy I think you're right. I can reproduce a similarly described problem (`Could not run adb reverse: Command failed: /usr/local/Cellar/android-sdk/24.3.4/platform-tools/adb reverse tcp:8081 tcp:8081`), but I don't see how this commit addresses the problem.

Anyways, let me know if you need more info on how to reproduce this bug :)

**Comment by alloy** [comment]
@marclundgren Please file a new ticket that describes the problem and link to it from here so that someone with access can close this PR 👍

**Pull request closed without merging**
