### PR TITLE
[Security] Update ws dependency

### PR DESCRIPTION
**Pull request by ericlewis**
## Summary

Our `ws` dependency is super outdated, and is [insecure](https://www.npmjs.com/advisories/550). It is used for the websocket example code in RNTester. This PR updates the dependency, and removes undefined console.logs.

## Changelog

[General] [Security] - Updates ws dependency to 6.4.1

## Test Plan

run RNTester & ensure works, check integration test too.

### CODE REVIEW

**Comment by ericlewis** [comment]
And more specifically addresses this comment: https://github.com/react-native-community/discussions-and-proposals/issues/64#issuecomment-444822438

**Comment by radeno** [comment]
CLI, Metro and Detox depends on ^1.1.x.

They should be also updated. Doesn't they?
Multiple different versions makes bundle bloated, because every package have own dependencies versions bundled within.

When will be WS updated for RN it should be updated for CLI and Metro also. But Detox is little bit complicated because there was initiation for update, but it breaks theirs Jenkins CI.

**Comment by ericlewis** [comment]
I honestly think that we should not even have `ws` as a dependency in this repo for the only purpose of serving up a demo in RNTester, seems a little silly. Could we perhaps just remove instead?

**Comment by ericlewis** [comment]
I would also be happy to find another way to deal with the websockets, it’s a very small surface area.

**Comment by radeno** [comment]
@ericlewis i agree with you. I also think if it is not possible it should be moved into `devDependencies` because it is not necessary in production. Or is it required for CI with `--production` flag?

**Pull request closed without merging**
