### PR TITLE
CLI Project Generator: Explicitly include a default .babelrc

### PR DESCRIPTION
**Pull request by namuol**
## Motivation

React Native projects nested inside babel-enabled projects can break unexpectedly due to misconfigured `.babelrc` in the parent project.

See #7821 for details.

## Test plan

Added a simple check to ensure the generator provides a `.babelrc` file by default.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @ide and @skevy to be potential reviewers.

**Comment by janicduplessis** [comment]
Tests are failing on node 4 (npm 2). I think you have to add "babel-preset-react-native" to package.json for the generated project. It works on npm 3 because of flattened dependencies.

**Comment by facebook-github-bot-1** [comment]
@namuol updated the pull request.

**Comment by facebook-github-bot-7** [comment]
@namuol updated the pull request.

**Comment by facebook-github-bot-4** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @bestander as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by bestander** [comment]
`babel-preset-react-native` may become incompatible with the one `react-native` is using when the project gets updated so I am not 100% happy about adding a new peer dependency in `react-native-cli`.

Can we do to `babel-preset-react-native` the same thing we do to `react` on local-cli?

**Comment by bestander** [comment]
Sorry for delay :)

**Comment by mkonicek** [comment]
Based on @bestander's last comment I think we should close this and revisit later if needed.

Thanks for the contribution and caring about improving tests!

**Comment by tgoldenberg** [comment]
So after looking at the related issue #7821, I think there must be an easy solution here. It sounds like @mkonicek doesn't want to modify the peer dependencies on initialization, so here's what I propose:

What if we keep the default `.babelrc` file with `{"presets": ["react-native"] }`, but not include a peer dependency of `babel-preset-react-native`? The caveat to this is that it would throw an error on npm 2, but couldn't we also make a minimum version of npm to use, and include that in the `Getting Started` docs? 

I don't think the issue should be ignored, though. There is precedent in `create-react-app`, for example, of addressing the issue of confusing behavior due to babel searching parent directories ([link](https://github.com/facebookincubator/create-react-app/pull/236)).

Sorry if I'm being naive here, this is the first RN issue I've actively worked on. I also have a forked version without the peer dependency changes at https://github.com/tgoldenberg/react-native. @janicduplessis @namuol what do you think?

**Pull request closed without merging**
