### PR TITLE
FIx docs for list view: "sticky" header not sticky on android

### PR DESCRIPTION
**Pull request by jaredly**
:( this confused me, I thought I was missing some configuration or something. But the UIExplorer app has sticky headers on iOS, and non-sticky headers on Android, so I guess that's that.

### CODE REVIEW

**Comment by christopherdro** [comment]
@satya164 Is this accurate? I remember sticky header support being added for android.

**Comment by ide** [comment]
@christopherdro It was reverted and the PR is currently on hold, no ETA.

**Comment by janicduplessis** [comment]
Yea I haven't had time to update the PR and still need quite a bit of work. Have to make some big changes so it works properly with view collapsing on Android.

Lets merge this for now and I'll try not to forget to update it when sticky headers actually land.

**Comment by janicduplessis** [comment]
@facebook-github-bot shipit

**Comment by skevy** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Comment by hramos** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
