### PR TITLE
Updating Websocket readyState in case of websocketFailed event

### PR DESCRIPTION
**Pull request by tepamid**
Fix for https://github.com/facebook/react-native/issues/9465

We are building a react-native based application which extensively uses WebSockets. The Android app crashes right after waking up being in suspended mode for a coupe of days and throws an exception:

"Cannot send a message. Unknown WebSocket id 1"

Before calling WebSocket.send(...) method from WebSocket.js we always check its readyState. I believe the problem is caused by not updating readyState if case of 'websocketFailed' event. this.close() cause the current used websocket ID to be removed from mWebSocketConnections HashMap (WebSocketModule.java), but readyState stays the same.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-0** [comment]
@tepamid updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9487/files/5c19ab5fef9e32f5831d65524669f06778b52c65..c21e25b1150525dc34c63f54987361b8c1550b66)

**Comment by facebook-github-bot-5** [comment]
@tepamid updated the pull request - [view changes](https://github.com/facebook/react-native/pull/9487/files/c21e25b1150525dc34c63f54987361b8c1550b66..18fac5ecf481bd3e6146aa39a115896fc7db0794)

**Comment by mkonicek** [comment]
This fix seems reasonable, as we already set the readyState in case of the close event.

@satya164 What do you think?

@facebook-github-bot shipit

**Pull request closed without merging**
