### PR TITLE
Remove navigator comparison and redirect to Navigation guide

### PR DESCRIPTION
**Pull request by hramos**
The new Navigation guide replaces the Navigator comparison doc. The server will redirect from navigator-comparison.html to navigation.html when this lands.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @caabernathy and @alvaromb to be potential reviewers.

**Comment by hramos** [comment]
Think of it, the earlier redirect was not going to work properly in the generated static site. I'm fine with keeping the navigator-comparison.html permalink and avoid dealing with redirects.

**Comment by caabernathy** [comment]
So is this PR still applicable since you mentioned you wanted to revert?

**Comment by hramos** [comment]
@caabernathy there is some content updates in this PR, but given the revert I think it makes more sense to split this into two new PRs.

**Comment by hramos** [comment]
See #8417

**Pull request closed without merging**
