### PR TITLE
Fix broken link to PanResponderExample.js

### PR DESCRIPTION
**Pull request by anttimo**
In recent change in 2f73ca8 all javascript files under UIExplorer were moved to js subfolders but PanResponderExample link wasn't updated accordingly.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @sebmarkbage and @sahrens to be potential reviewers.

**Comment by anttimo** [comment]
Hi @javache since you were committer on 2f73ca8f7675977f839ad5bfcb5045ff33621803 maybe you can review this?

**Comment by satya164** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1724998701098125/int_phab) to review.

**Pull request closed without merging**
