### PR TITLE
Turned old bridge for OSS back by default

### PR DESCRIPTION
**Pull request by bestander**
This should revert back to using old bridge by default until we fix gradle script to build new bridge for OSS correctly

Test Plan:
- start uiexplorer
- circle CI
- travis
- sandcastle

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @foghina and @ahmedre to be potential reviewers.

**Comment by foghina** [comment]
Did we get rid of XReactInstanceManager.Builder?

**Comment by bestander** [comment]
It certainly looks so, D3507482.
And this diff followed D3510867

**Comment by bestander** [comment]
replaced with #8539 8539

**Pull request closed without merging**
