### PR TITLE
[Fix] `Android/ColorProps`: ColorProps with value null should be defaultColor instead of transparent

### PR DESCRIPTION
**Pull request by hank121314**
## Summary

This pr:
- Fixes: #30183
- Fixes: #30056 
- Fixes: #29950
- Fixes: #29717 
- Fixes: #29495
- Fixes: #29412
- Fixes: #29378

Because most of @ReactProps(name = ViewProps.COLOR) accept @ Nullable Integer.
For example:
https://github.com/facebook/react-native/blob/abb6433f506851430dffb66f0dd34c1e70a223fe/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java#L472-L479

After update to react-native 0.63.2 to make PlatformColor work, there is a new ColorPropSetter.
https://github.com/facebook/react-native/blob/abb6433f506851430dffb66f0dd34c1e70a223fe/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagersPropertyCache.java#L194-L215

But ColorPropSetter won't return an nullable value with getValueOrDefault, it will always return it's defaultValue which is 0.
And 0 is equal to TRANSPARENT, will cause <Text /> disappear.
## Changelog

[Android] [Fixed] - ColorProps with value null should be defaultColor instead of transparent

## Test Plan
Please initiated a new project and replaced the app with the following code:
```
import * as React from 'react';
import {Text, View, TouchableOpacity, PlatformColor} from 'react-native';

export default function App() {
  const [active, setActive] = React.useState(false);

  return (
    <View>
      <Text style={active ? {color: 'green'} : null}>Example</Text>
      <Text
        style={
          active ? {color: PlatformColor('@android:color/holo_purple')} : null
        }>
        Example2
      </Text>
      <TouchableOpacity onPress={() => setActive(!active)}>
        <Text>Toggle Active</Text>
      </TouchableOpacity>
    </View>
  );
}
```

Thanks you so much for your code review!

### CODE REVIEW

**Comment by safaiyeh** [comment]
Nice work! @hank121314 I built RNTester to test this out:
Screen Recording 2020-09-03 at 11 32 06 PM

Working as expected, tagging PR submitted on the issue.

**Review by safaiyeh — APPROVED** [review]

**Comment by safaiyeh** [comment]
cc @JoshuaGross

**Comment by hank121314** [comment]
> Nice work! @hank121314 I built RNTester to test this out:
> Screen Recording 2020-09-03 at 11 32 06 PM
> 
> Working as expected, tagging PR submitted on the issue.

Thank you so much for help and testing! 😄

**Comment by Danite** [comment]
I think when the color is undefined it should also fallback to the defaultColor.

Take this case:
`<Text style={[someTextStyleWithoutColor, isActive && activeTextStyle]}> Hello there! </Text>`
it will make the text transparent once is not active.

**Comment by hank121314** [comment]
> I think when the color is undefined it should also fallback to the defaultColor.
> 
> Take this case:
> `<Text style={[someTextStyleWithoutColor, isActive && activeTextStyle]}> Hello there! </Text>`
> it will make the text transparent once is not active.

Yes, this pr is also included undefined in javascript.

**Review by hank121314 — COMMENTED** [review]
apply google-java-format suggested changes.

**Comment by Babar-Memon** [comment]
i have a same problem on image component anyone can help me out to resolve this issue

**Comment by hank121314** [comment]
> i have a same problem on image component anyone can help me out to resolve this issue

Hi @Babar-Memon , you can try to patch this pr with [Building from source](https://github.com/facebook/react-native/wiki/Building-from-source#android).
Or set color props to any colors except `null`.

**Review by fabriziobertoglio1987 — APPROVED** [review]
thanks a lot @hank121314. Your pr also fixes https://github.com/facebook/react-native/issues/29378 (not linked in your pr summary), I was searching for the solution as explained in https://github.com/facebook/react-native/issues/29412#issuecomment-773412466 and then found your PR from another related issue.

I checkout out your branch and as in the below test case, verified that it fixes also https://github.com/facebook/react-native/issues/29378 

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
|  |  |

</p>
</details>

Thanks a lot. :pray: :peace_symbol:

**Comment by hank121314** [comment]
Hi @fabriziobertoglio1987 .
Thanks for your investigation and review!
Hope this pr can be merged soon. 😄

**Comment by StanislavMayorov** [comment]
@fabriziobertoglio1987 @hank121314 Hi. Could you merge it please?

**Review by JeffGuKang — APPROVED** [review]

**Comment by taylorkline** [comment]
This did not fix `ActivityIndicator` from being transparent for me. #30057 worked for me.

**Comment by taylorkline** [comment]
Actually, in general, this fix is not working for me on 0.64.2.

**Comment by hank121314** [comment]
Hi @taylorkline, did you try to patch this pr with [Building from source](https://github.com/facebook/react-native/wiki/Building-from-source#android)?
If it still does not work, could you give me some reproducible code?
Thanks!

**Review by janicduplessis — APPROVED** [review]
LGTM, sorry this is taking forever to merge, will ping some people at fb.

**Comment by taylorkline** [comment]
@hank121314 No, I did not - my apologies, likely user error on my part then.

**Pull request closed without merging**
