### PR TITLE
Re-sourcing profile Xcode to update node version

### PR DESCRIPTION
**Pull request by rush1506**
Re-sourcing profile to update Xcode node version since Xcode use old node version and for some people (our team). This can cause the bundle to fail building main.jsbundle

Thank you for sending the PR! We appreciate you spending the time to work on these changes.
Help us understand your motivation by explaining why you decided to make this change.

If this PR fixes an issue, type "Fixes #issueNumber" to automatically close the issue when the PR is merged.

_Pull requests that expand test coverage are more likely to get reviewed. Add a test case whenever possible!_

Test Plan:
----------

**Problem**
XCode 10 using wrong node version (older) so it cannot build the main.jsbundle when release the app on IOS

**Test failed case before editing the code:**

Run command react native for release:
```
react-native run-ios --configuration Release
```
-> The bundle will not be generated, XCode throw in error

**Test success case after editing the code:**

Run command react native for release:
```
react-native run-ios --configuration Release
```
-> IOS app is upload to test flight or ipa file is generated

Release Notes:
--------------
[IOS][BUGFIX] [./scripts]  - Sourcing XCode node version again when release to help re-bundling mainjs file when X code generate react native app version `^0.57.x`

### CODE REVIEW

**Comment by rush1506** [comment]
> Hey, thanks for the PR! Can you fill in your test plan?

Sorry for the late reply. I am away for couple of weeks after the projects so I leave everything at home, here is the test plan text:

##Environment 
XCode: 10.0.0
React native: 0.57.0
React: 16.5
Node version: 8.9.4

##Problem
XCode 10 using wrong node version (older) so it cannot build the main.jsbundle when release the app on IOS

##Test Case

####Test failed case before editing the code:
Run command react native for release:
```
react-native run-ios --configuration Release
```
-> The bundle will not be generated, XCode throw in error

####Test success case after editing the code:
Run command react native for release:
```
react-native run-ios --configuration Release
```
-> IOS app is upload to test flight or ipa file is generated

**Comment by hramos** [comment]
Thanks for adding it in!

I could use some help understanding why this fix is needed. Why is Xcode using a different version of Node? The fix appears to assume the user has set up their `.bash_profile` with a path to Node. Is this a reasonable assumption to make?

**Comment by vovkasm** [comment]
Oh, no! Please don't source .bash_profile by default... I use zsh, and other shells exists in the world!

**Comment by vovkasm** [comment]
Moreover, `/.bash_profile` simple does not exists in my system. Why in root of fs? May be it should be in `/etc/profile`, but I sure problem has other solutions...

**Comment by rush1506** [comment]
> Moreover, `/.bash_profile` simple does not exists in my system. Why in root of fs? May be it should be in `/etc/profile`, but I sure problem has other solutions...

Sorry, it seems like I was not being considerate about this. Please reject my pull request

**Comment by vovkasm** [comment]
@rush1506 Actually I'd recommend as a workaround for your issue, use [nvm](https://github.com/creationix/nvm) or [nodenv](https://github.com/nodenv/nodenv). Both are supported by `react-native-xcode.sh` script. (moreover, actually it can be source of you initial issue, because `react-native-xcode.sh` script calls these managers not only if they are installed locally, but even if they simple exists in homebrew paths, see: https://github.com/facebook/react-native/blob/0.57-stable/scripts/react-native-xcode.sh#L59)

**Pull request closed without merging**
