### PR TITLE
Added the ability to set an Image as the title in NavigatorIOS.

### PR DESCRIPTION
**Pull request by farhanpatel**
This allows NavigatorIOS to have custom Images in the title instead of just text.
This adds the functionality requested in #514 

I've updated the Movies example with a custom title to show how the functionality works.

### CODE REVIEW

**Comment by avishayil** [comment]
I suggest getting this as an object, with the ability to set image height and width. Otherwise, you can render an image that will spread all over your app if it's too big.
I don't know how to do it in iOS though.

**Comment by facebook-github-bot-8** [comment]
@sahrens would you mind taking a look at this pull request? It's been a while since the last commit was reviewed.

**Comment by mkonicek** [comment]
@farhanpatel Sorry this pull request got missed. Could you please add a screenshot from the Movies app? How does it look when using a very large or small image - do people need to specify width and height too?

**Comment by lacker** [comment]
Since there's been no response from the author in over a month I'm going to close this pull request. It seems like good functionality, though, so feel free to reopen it if you are still actually working on it!

**Pull request closed without merging**
