### PR TITLE
Auto load cookies from sharedHTTPCookieStorage

### PR DESCRIPTION
**Pull request by iAladdin**
check and fill with exist cookies while request created.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure tests pass on both Travis and Circle CI.

**Code formatting**

Look around. Match the style of the rest of the codebase. See also the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

For more info, see the ["Pull Requests" section of our "Contributing" guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#pull-requests).

### CODE REVIEW

**Comment by ericvicenti** [comment]
Hi, this code change looks fine but you haven't explained what you're fixing and why. Can you update the description and clarify why this needs to be changed?

Is it possible that this will break some things when the people expect the old behavior? Is it possible that people would prefer that or need a way to keep the existing behavior?

**Comment by hramos** [comment]
Have you signed the CLA yet?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/auto-load-cookies-from-sharedhttpcookiestorage

**Comment by hramos** [comment]
Looks like an actual candidate for closing. No CLA signed in six months.

**Pull request closed without merging**
