### PR TITLE
[Android] CameraRoll support for Videos and Photos showed in same time

### PR DESCRIPTION
**Pull request by kesha-antonov**
## Motivation

Right now you can choose to show Videos OR Photos.
This PR allows to show both in the same time.

## Release Notes

[ANDROID][ENHANCEMENT] - Can show videos and photos from CameraRoll in the same time

### CODE REVIEW

**Comment by FacuAcosta** [comment]
What's the status of this PR?

**Comment by kesha-antonov** [comment]
I see that RN team only look for features that FB needs. Not what people need. So while they not need it there's no any status

**Comment by FacuAcosta** [comment]
We are already on 2018 and this problem has been there for more than a year, what are you waiting for Facebook?

**Comment by mikeng13** [comment]
Facebook, what is going with this PR? Would love to be able to use this feature!

**Comment by akyker20** [comment]
Would like to see this feature asap

**Comment by mikeng13** [comment]
@kesha-antonov looks like there are two action items that need your attention, test plan and release notes. 

@shergin I was referred to you as someone who might be able to help get this PR moving on the Facebook side. Would you please be able to help shepherd this or maybe point to someone who can help?

**Comment by Tsiniloiv** [comment]
Does this work? I need this feature, and I'll crowbar it into my build manually if I have to.

**Comment by Tsiniloiv** [comment]
@kesha-antonov I tried making the same changes to CameraRollManager as you've done, but it seems to have had no effect. Is there some additional step to making this work?

**Comment by bulats** [comment]
Any news regarding this PR? It's been ages.

**Comment by FacuAcosta** [comment]
@bulats I'm using this package and works like a charm
https://github.com/pentarex/react-native-gallery-manager

**Comment by bulats** [comment]
@FacuAcosta Thank you! Can confirm that it works.

**Comment by hramos** [comment]
Hey there, I'm going through old PRs and noticed this PR has been flagged as lacking a test plan. @kesha-antonov do you plan on adding a test plan?

**Pull request closed without merging**
