### PR TITLE
Value of opacity in TouchableOpacity properly react to state change

### PR DESCRIPTION
**Pull request by hetanthakkar1**
## Summary

This PR fixes the opacity bug where it fails to properly react to state change. This PR resolves the issue detailed in #32476

## Changelog

[General] [Fixed] - Fixed opacity value in TouchableOpacity

## Test Plan

The code I added in componentDidUpdate does solve the issue and passes all the test cases

### CODE REVIEW

**Comment by ryancat** [comment]
> I don't know why the test failed can someone please help me!

I don't think the failures are related to your changes. Could you rebase and try again?

**Comment by hetanthakkar1** [comment]
@ryancat Sure! Thanks

**Comment by hetanthakkar1** [comment]
@ryancat I'm trying to figure out why opacity didn't set on line 176

**Comment by hetanthakkar1** [comment]
@ryancat  Actually on [line 176](https://github.com/facebook/react-native/blob/6790cf137f73f2d7863911f9115317048c66a6ee/Libraries/Components/Touchable/TouchableOpacity.js#L176) we tried to set the opacity on press out but I don't think that we should set the opacity on press out because according to the docs: [onPressOut](https://github.com/facebook/react-native/blob/6790cf137f73f2d7863911f9115317048c66a6ee/Libraries/Pressability/Pressability.js#L127) will undo visual feeback which is not what we need! We need to provide visual feedback which can be done through [onPressIn](https://github.com/facebook/react-native/blob/6790cf137f73f2d7863911f9115317048c66a6ee/Libraries/Pressability/Pressability.js#L117)

I am a bit skeptical about my approach but this solution does seem to work so I am waiting for your take on this approach and once you feel that this is correct I can convert this to functional component

**Comment by hetanthakkar1** [comment]
Can someone please review my pull request

**Comment by ryancat** [comment]
> @ryancat Actually on [line 176](https://github.com/facebook/react-native/blob/6790cf137f73f2d7863911f9115317048c66a6ee/Libraries/Components/Touchable/TouchableOpacity.js#L176) we tried to set the opacity in `onPressOut` but I don't think that we should set the opacity on press out because according to the docs: [onPressOut](https://github.com/facebook/react-native/blob/6790cf137f73f2d7863911f9115317048c66a6ee/Libraries/Pressability/Pressability.js#L127) will undo visual feedback which is not what we need! We need to provide visual feedback which can be done through [onPressIn](https://github.com/facebook/react-native/blob/6790cf137f73f2d7863911f9115317048c66a6ee/Libraries/Pressability/Pressability.js#L117).
> 
> I am a bit skeptical about my approach but this solution does seem to work so I am waiting for your take on this approach and once you feel that this is correct I can convert this to a functional component.

Thanks for the investigation! I am a bit confused though -- if we documented that `onPressOut` will undo visual feedback, isn't that shows we should do what we are doing now by trying to set the opacity to inactive state.

The reason why that line wasn't working is because of a timing issue. When we are calling onPressOut, we are getting the opacity from the prop in [line 202](https://github.com/facebook/react-native/blob/6790cf137f73f2d7863911f9115317048c66a6ee/Libraries/Components/Touchable/TouchableOpacity.js#L202). However, when that method got executed, the opacity is still 1, instead of 0.1. If you try to wrap line 176 with a `setTimeout` and zero timeout, you will see this component working properly.

I think your approach works and is reasonable. The downside is to trigger additional render by doing that in the `componentDidUpdate` method. If you could avoid that additional render it would be great! I tried with `getDerivedStateFromProps` but not get very far. Using a functional approach would be better with more control on what dependencies we add to the opacity state.

**Comment by hetanthakkar1** [comment]
@ryancat Can you pleaser review

**Comment by hetanthakkar1** [comment]
@mikehardy Can you please review??

**Comment by mikehardy** [comment]
Sorry @hetanthakkar1 - this is way out of the areas of anything I have knowledge of

**Comment by dulmandakh** [comment]
Pressable is the future, so I don't use Touchable, and have no experience with its implementation.

**Comment by hetanthakkar1** [comment]
@ryancat can you please review

**Comment by hetanthakkar1** [comment]
@ryancat can you please review

**Comment by hetanthakkar1** [comment]
@ryancat Can you please review

**Comment by cortinico** [comment]
Closing in favor of #32956

**Pull request closed without merging**
